### ISSUE TITLE
E13 "file exists, add ! to override"

### ISSUE THREAD

**Issue by unknownspacewalker** [nvim-treesitter/nvim-treesitter#1004]
With `nvim-treesitter` installed I always get `E13 "file exists, add ! to override"`.
If I save a file with `w!`, then I can save the file without `!` in the current session.

**Comment by wraithy** [comment]
Apparently, vim does this if there were any issues with opening the file. See[this question](https://stackoverflow.com/questions/26070153/vim-wont-write-file-without-a-sometimes-e13) on SO.

I've been having the same problem, and in my case the cause is a failed autocommand (due to [this issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/994)) when opening files.

**Comment by steelsojka** [comment]
Can you give use a minimal reproduction? Are you sure it is nvim-treesitter?

**Comment by stsewd** [comment]
I haven't seen these errors for a while now. Maybe it was fixed upstream.

**Comment by vigoux** [comment]
Most of the time this error occurs because loading a query failed or something. With the pinning mechanism and CI this happens less often.

**Comment by atremblay** [comment]
For what it's worth, I just updated my plugins and started having this issue. Searched around and found this issue. Commented out tree sitter in my config and I do not get this error anymore.

**Comment by vigoux** [comment]
If you are using nvim-treesitter, you can do a `:checkhealth` most of the time this is a version issue which causes this.

**Comment by dlip** [comment]
This just happened for me and i fixed it by disabling part of the text objects plugin https://github.com/dlip/nixconfig/commit/a66031f76109b1b288c062cc94a502a1d91fed51

**Comment by theHamsta** [comment]
@dlip we removed that type of configuration.

**Comment by theHamsta** [comment]
I don't think we have the original issue that was reported here anymore.

**Comment by coldis** [comment]
Just in case anyone else comes across this, I ran into this issue today. Fixed it by commenting out the configuration for `rainbow` in my treesitter config

**Comment by beauwilliams** [comment]
I had the same issue too. For me the offending lines in my treesitter configuration in my nvim config was related to the `keymaps` I had set. I commented out for now.

```lua
	textobjects = {
		select = {
			enable = true,
			--NOTE: offending chunk of code
			keymaps = {
				['iF'] = {
					python = '(function_definition) @function',
					cpp = '(function_definition) @function',
					c = '(function_definition) @function',
					java = '(method_declaration) @function',
				},
```

**Comment by RaafatTurki** [comment]
Happened again, it seems like the fix differs depending on the setup but generally speaking go to your TS config and disable all modules, If that solves it re-enable them back one by one until you find the culprit.

It was `incremental_selection` in my case.

**Comment by YodaEmbedding** [comment]
Happens for me on Neovim 0.8 on MacOS.

Disabling this fixes it:

```lua
highlight = {
  enable = true,
},
```

**Comment by lysandroc** [comment]
> Happens for me on Neovim 0.8 on MacOS.
> 
> Disabling this fixes it:
> 
> ```lua
> highlight = {
>   enable = true,
> },
> ```
> 
> Removing and reinstalling `nvim-treesitter*` plugins did not help.

same thing here...

**Comment by Cijin** [comment]
> Happens for me on Neovim 0.8 on MacOS.
> 
> Disabling this fixes it:
> 
> ```lua
> highlight = {
>   enable = true,
> },
> ```
> 
> Removing and reinstalling `nvim-treesitter*` plugins did not help.

Same here

**Comment by NathanFirmo** [comment]
> Happens for me on Neovim 0.8 on MacOS.
> 
> Disabling this fixes it:
> 
> ```lua
> highlight = {
>   enable = true,
> },
> ```
> 
> Removing and reinstalling `nvim-treesitter*` plugins did not help.

Same here

**Comment by NathanFirmo** [comment]
> Seems like there is something wrong with treesitter, seeing how many people are having this issue.
> 
> For me it is also not related to any specific file-type.
> 
> `:f` is giving me this on any file:
> 
> ```
> "config/nvim/lua/x/packs/treesitter.lua" [Read errors] 19 lines --26%--
> ```
> 
> **Edit:**
> 
> Just to add this here how I fixed it:
> 
> 1. Update neovim (using brew it's like `brew install neovim`).
> 2. Restart nvim.
> 3. Install necessary tree-sitter parsers again (`:TSInstall tsx`, for example)
> 
> That was everything, and now **it's working again**.

Not works for me 😢, but I fix using treesitter on an old commit (3 weeks ago).

~~~lua
return require('packer').startup(function(use)
  use { 'nvim-treesitter/nvim-treesitter', run = ':TSUpdate', commit = '48a3da710369688df80beb2847dabbbd02e2180e', lock = true}
end)
~~~

**Comment by omezro** [comment]
> 
another solution is just set disable = { "c", "cpp" }, in highlight like this
highlight = {
  enable = true,
 disable = { "c", "cpp" },
},
then problem solved

**Comment by iduuck** [comment]
@omezro That was not really a solution for me, because I knew, that `tsx` files, with which I work extensively all the time, were broken. Just disabling this would be some sort of "monkey-patch", which is not really helping me with the plugin.

**Comment by Frydac** [comment]
> Not works for me cry, but I fix using treesitter on an old commit (3 weeks ago).
> 
> ```lua
> return require('packer').startup(function(use)
>   use { 'nvim-treesitter/nvim-treesitter', run = ':TSUpdate', commit = '48a3da710369688df80beb2847dabbbd02e2180e', lock = true}
> end)
> ```

using this older commit did not work for me.
I have the issue with multiple filetypes, but not all the time and not with all files, usually it starts after a while on a specific file I'm editing and saving regularly while other files save fine, restarting neovim helps for some time.

**Comment by vikks** [comment]
For anyone still experiencing `file exists, add ! to override` error, try commenting out autocmds one at a time, for me it fixed when i commented out this autocmd.
 
```lua
-- GoTo last location of cursor when on buffer open.
autocmd("BufReadPost", {
  command = [[ if line("'\"") > 1 && line("'\") <= line("$") | execute "normal! g`\"" | endif]]
})
```

**Comment by Sumer312** [comment]
> Just in case anyone else comes across this, I ran into this issue today. Fixed it by commenting out the configuration for `rainbow` in my treesitter config

This worked for me, but I recently moved to debian 12 from Linux Mint and on mint it was working fine, so idk what is up with that.
