### ISSUE TITLE
errors found in the query.

### ISSUE THREAD

**Issue by singlexyz** [nvim-treesitter/nvim-treesitter#1011]
<img width="912" alt="截屏2021-03-09 下午8 39 50" src="https://user-images.githubusercontent.com/4456413/110471874-a3f67100-8117-11eb-9cda-91d1f324f015.png">

And the plugin doesn't work. 
after run `TSUpdate javascript` still don't.

**Comment by steelsojka** [comment]
Can you provide some more information.  Can you define "plugin doesn't work" so we can better understand the issue. Also, can you please give a minimal .vimrc if possible?

**Comment by theHamsta** [comment]
It's also possible that you can not load your parser. E.g. by having the tree-sitter runtime 0.19.2 while our parsers are currently 0.18.X.

You could try `:TSInstallFromGrammar` if your runtime is 0.19.X (e.g. from brew) or try #1000

**Comment by stsewd** [comment]
Please provide us with the information required so we can help you and re-open this issue, or let us know if you solved this already!
