### ISSUE TITLE
Don't highlight TSError in insert mode

### ISSUE THREAD

**Issue by khaveesh** [nvim-treesitter/nvim-treesitter#1016]
**Is your feature request related to a problem? Please describe.**
Since treesitter highlights all errors even while typing an incomplete expression, it is very irritating. Previously, it was suggested to link TSError to the Normal hlgroup, so that the errors are never highlighted.

**Describe the solution you'd like**
But a better solution for those who want to be informed about syntax/parsing errors in their code, would be to highlight these errors but just not in insert mode. In a nutshell, I want TSError linked to Normal when in insert mode and `Error` otherwise.

**Describe alternatives you've considered**
Alternatives is to put up with the constant annoyance when typing or to completely silence the error highlighting. Both are IMO inferior options.

**Additional context**
Previous discussions on this topic that I found were: #78 & #119.

**Comment by stsewd** [comment]
I think you can achieve this with an auto command, maybe? `:h InsertEnter` and `:h InsertLeave`

**Comment by khaveesh** [comment]
@stsewd That works, but still would prefer an option to toggle that behaviour built into the plugin. Closing for now.

**Comment by theHamsta** [comment]
@khaveesh nvim-treesitter does not define TSError. Maybe you color theme defines it?

**Comment by tompreston** [comment]
> That works, but still would prefer an option to toggle that behaviour built into the plugin. Closing for now.

@khaveesh what did you do? I have the same problem

![Screenshot 2022-11-24 at 18 37 08](https://user-images.githubusercontent.com/669843/203848871-bec85546-1913-4022-90f8-01af432abfc4.png)

**Comment by theHamsta** [comment]
@tompreston the mapping of captures is now handled by upstream nvim. Unmap the  `@error` highlighting group. Errors are highlighted with `@error` . Your colorscheme probably links `@error` to something.

**Comment by clason** [comment]
...which upstream Neovim deliberately _doesn't_ do, so this is a colorscheme issue.
