### ISSUE TITLE
Folds in injected languages

### ISSUE THREAD

**Issue by gjeusel** [nvim-treesitter/nvim-treesitter#1023]
In a vuejs file, I can't seem to be able to query the injected javascript language nodes.

The main goal in my case would be to add the javascript nodes called "method_definition" to be folded in a vue file.

**To Reproduce**

<details><summary>GIF</summary>

![nvim-treesitter-vuejs](https://user-images.githubusercontent.com/16243660/111028604-f1b0f900-83f7-11eb-81ff-0e18eb8173bc.gif)

</details>

<details><summary>Example.vue</summary>
<code>

```vue
<template>
  <div></div>
</template>

<script lang="ts">
import { defineComponent } from "vue"

export default defineComponent({
  name: "Example",
  props: {},
  components: {},
  setup() {
    return {}
  },
})
</script>
```

</code>
</details>

<details><summary>TreeSitter queries</summary>

```treesitter
; Working queries
(script_element) @scripttag
(script_element (raw_text)) @lastvuenode

; Query not working (once uncommented, none is working in TSPlayground):
; (import_statement) @firstjsnode
```

</details>

**Expected behavior**

Being able to query import_statement node

---

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - ERROR: `tree-sitter` executable not found
  - OK: `git` executable found.
  - OK: `cc` executable found.

## Parser/Features H L F I
  - python         ✓ ✓ ✓ ✓ 
  - vue            ✓ . ✓ . 
  - query          ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ 
 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         *) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev+1129-gc12ea02e0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Library/Developer/CommandLineTools/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/gjeusel/src/neovim/build/config -I/Users/gjeusel/src/neovim/src -I/Users/gjeusel/src/neovim/.deps/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/include -I/usr/local/opt/gettext/include -I/Users/gjeusel/src/neovim/build/src/nvim/auto -I/Users/gjeusel/src/neovim/build/include
Compiled by gjeusel@Guillaumes-MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Comment by elianiva** [comment]
if you want cross-language folding, try this branch
https://github.com/nvim-treesitter/nvim-treesitter/tree/refactor-for-language-tree

**Comment by steelsojka** [comment]
@gjeusel This is expected and controlled by treesitter. A query can only query a single language and can't cross language boundaries. Once the JS is injected, it's completely controlled by the JS queries and parser. If you want to add custom queries for the injected javascript, you will have to add it to the JS queries, not the VUE queries. Treesitter will error if a query contains a node that is defined in the parser. I'll look into that branch, I completely forgot about it and thought it was done already!

**Comment by mhanberg** [comment]
I have noticed this in injected markdown code documentation snippets.

I want to be able to fold the whole doc string, but it seems to put the markdown folds at the same level as the initial fold, so you can't fold the whole thing.

Below you can see the fold column shows where the folds are at, and the second image shows what happens when you attempt to fold the whole doc snippet `@moduledoc """`

<img width="603" alt="image" src="https://user-images.githubusercontent.com/5523984/220739155-9c37fbd2-7c57-471c-b618-80a2b64f5f50.png">
<img width="588" alt="image" src="https://user-images.githubusercontent.com/5523984/220739233-63e9727c-05b9-4d9f-8364-d4bb9a71b8e6.png">
