### ISSUE TITLE
Wrong highlighting of jsx components

### ISSUE THREAD

**Issue by luisiacc** [nvim-treesitter/nvim-treesitter#1028]
Hy, so there was an issue a little while ago where on react files, normal tags (such as `<br />`, `<div />`, etc...) where not highlighted as TSTag but as TSVariable, well that is now done correctly, but now custom components(Ex: <Home />) are not highlighted as TSTag but as TSType, so that should be fixed since they should be highlighted as TSTag.

Latest nvim-treesiter commit: `e4083fc`

<details>
<summary>nvim-version:</summary>

```
NVIM v0.5.0-dev+1123-g3fbff98cf
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wst
rict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-
color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVE
L=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.dep
s/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/incl
ude
Compiled by runner@fv-az205-642
```

</details>

**Comment by kyazdani42** [comment]
not sure what you mean by custom component ?

**Comment by luisiacc** [comment]
> not sure what you mean by custom component ?

For example:
![image](https://user-images.githubusercontent.com/31720261/111205623-cf58e000-859d-11eb-80ef-a74a422569a3.png)

I notice that CustomComponent is getting the highlight of TSType and not TSTag as it should, in this example the colorscheme has TSType highlighted as a dark yellow and TSTag as green, I can confirm that is highlighted as TSType because changing the highlight of TSType changes the color of the component, notice that `<section>` is green and `<CustomComponent />` is dark yellow.

**Comment by kyazdani42** [comment]
I believe we discussed this already and Uppercased components should be TSConstructor @steelsojka. But these are actually highlighted as TSType which is not expected.

**Comment by steelsojka** [comment]
@kyazdani42 I believe this was caused by the inheritance issue if I'm not mistaken (which I might)? I agree though, it should be TSConstructor

**Comment by luisiacc** [comment]
Just to clarify, I'm talking about the highlighting of `<CustomComponent>` that should be TSTag, and NOT `function CustomComponent(props)...`, which I agree it makes sense to make it TSConstructor.

**Comment by kyazdani42** [comment]
<CustomComponent /> is just like new CustomComponent() this is why we should highlight this as TSConstructor.

**Comment by luisiacc** [comment]
> `<CustomComponent />` is just like `CustomComponent()` this is why we should highlight this as TSConstructor.

My personal opinion is that it makes more sense to highlight `<CustomComponent />` as a tag, since it's actually a tag, however highlighting it as TSConstructor also makes sense; I'm cool with whichever decision ✌

**Comment by kyazdani42** [comment]
I understand but we prefer TSConstructor to have a distinction between React components and custom components. I'm not sure why but in the jsx query everything is highlighted as `@type`

**Comment by napmn** [comment]
Any update on this? I found [this issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/498) which i believe introduced the TSType highlight group for Uppercased components. I think TSConstructor makes more sense. I just started using treesitter and tried out the playground with the output below...so the TSType has priority i guess? If this will not be changed and it stays how it is - with TSType having priority - is there a way I can change the priority myself locally?

![image](https://user-images.githubusercontent.com/22654504/120479143-e1346d00-c3ad-11eb-90fb-2bed35309fb8.png)

**Comment by kyazdani42** [comment]
i guess you could make a PR to change all `@type` to `@constructor` it would make more sense (in the `jsx/highlights.scm` query)

**Comment by stsewd** [comment]
Was this fixed with https://github.com/nvim-treesitter/nvim-treesitter/pull/1357?

**Comment by luisiacc** [comment]
Yes
