### ISSUE TITLE
Use a different character instead of "*" in `:checkhealth`

### ISSUE THREAD

**Issue by nbCloud91** [nvim-treesitter/nvim-treesitter#1031]
The use of asterisk causes the syntax  highlighting of `:checkhealth` buffer to break. Preferably use another symbol.
https://github.com/nvim-treesitter/nvim-treesitter/blob/ec41db9511309966f6ab816d0139fad30ef50be6/lua/nvim-treesitter/health.lua#L73

**Comment by NullVoxPopuli** [comment]
how do we know if your checkhealth is ok if we can't see it?

**Comment by nbCloud91** [comment]
Asterisk is used for emphasis in Markdown, if it is not escaped (with `\*`rendered as \*), a single one meddles with the formatting of all the text succeeding it.
- This is what it looks like with asterisk, note the gray color of that symbol, while all the plain-text succeeding it is rendered in *italics*
![image](https://user-images.githubusercontent.com/73609114/111305649-37cabe80-867d-11eb-97ce-42845d3e74aa.png)
- This is what it could look like, if a plus symbol is used instead of asterisk
![image](https://user-images.githubusercontent.com/73609114/111306350-20400580-867e-11eb-803b-cb32e12544df.png)

**Comment by vigoux** [comment]
Great, then we'll try to look into that soon.
We will gladly accept a pr on this btw!

**Comment by theHamsta** [comment]
Fixed via #1043

**Comment by nbCloud91** [comment]
> Fixed via #1043
This issue is not fixed by the above changes. The reason for the formatting being messed up is the (unescaped) asterisk, adding a newline before the legend does not rectify that. Let me see if I can make a PR to solve it.

**Comment by nbCloud91** [comment]
I have raised a PR here #1050. That should close this issue.
