### ISSUE TITLE
Help debugging highlight groups

### ISSUE THREAD

**Issue by dimascyriaco** [nvim-treesitter/nvim-treesitter#1032]
I used to use this snippet to find out the highlight group under the cursor: `echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')`.

But with treesitter installed this returns an empty list. This is expected? There's other way to do this?

**Comment by kyazdani42** [comment]
install the (playground)[https://github.com/nvim-treesitter/playground] and use `:TSHighlightCapturesUnderCursor` !

**Comment by dimascyriaco** [comment]
@kyazdani42 Thank you!
