### ISSUE TITLE
Neovim update breaks treesitter: ABI version mismatch

### ISSUE THREAD

**Issue by bluz71** [nvim-treesitter/nvim-treesitter#1033]
Hello,

Looks like the Neovim team upgraded to Treesitter 0.19.x, and it appears this plugin is now broken.

```sh
language.lua:33: ABI version mismatch : supported between 13 and 13, found 11
```

I assume this is a transitional breakage? Soon fixed?

I already miss Treesitter highlighting due to this breakage.

Cheers.

**Comment by bfredl** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/pull/1000

**Comment by bluz71** [comment]
Thanks @bfredl.

Not worth keeping open, wheels are in motion.
