### ISSUE TITLE
Error during tree-sitter generate

### ISSUE THREAD

**Issue by romgrk** [nvim-treesitter/nvim-treesitter#1035]
Hi,

I'm upgrading my neovim & parsers for the TS 0.19 ABI change, and all parser seem to be working fine except for the cpp one. I get an opaque "Error during tree-sitter generate" when it fails, I'd like to understand why it fails. I've checked the tree-sitter-cpp repo, it seems to have been updated for the new API, when I git clone it & manually `tree-sitter generate` it it works fine, so I was wondering how is nvim-treesitter doing it's installation of the parser? How can I debug it?

Thanks

**Comment by theHamsta** [comment]
This is because this parser requires NPM to install the C parser. Try normal :TSInstall with #1000

**Comment by romgrk** [comment]
Problem solved, thanks. It would be nice nevertheless to print more details when errors occurs, gives more actionable context.
