### ISSUE TITLE
Please run ":TSUninstall all" when upgrading to tree-sitter 0.19.3

### ISSUE THREAD

**Issue by theHamsta** [nvim-treesitter/nvim-treesitter#1036]
Clever TSUpdate is not clever enough to detect this ABI break (it only checks the parser git revision not the tree-sitter version Nvim is using).

If you're facing any tree-sitter errors about ABI, try reinstall the newest master version of Neovim and reinstall all parsers. If you're building from source try to do a clean rebuild (make clean) as some build artifacts might still be built with 0.18.x API

tree-sitter is a part of your Neovim installation. There is in theory no need to install the tree-sitter-cli. However, some parsers have not been updated to tree-sitter version. Nvim-treesitter will try to use tree-sitter-cli to install those parsers nonetheless. Those parsers should get less in the coming weeks and you can help by making the parser maintainers of your favorite language aware of that problem. There should be no problems with mainstream languages like C/C++, Go, Python,...

**Comment by Shatur95** [comment]
But there is no such command. Only `:TSUninstall`.

**Comment by ingram1107** [comment]
Only `c` parser is in good health, others (in this case `cpp`, `rust`, `python` and `javascript` are not.

`:checkhealth`:
```
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.3(parser generator, used for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found.

## Parser/Features H L F I
  - rust           x x x x 
  - javascript     x x x x 
  - python         x x x x 
  - cpp            x x x x 
  - c              ✓ ✓ ✓ ✓ 
 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         *) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

**Comment by theHamsta** [comment]
You probably have the C parser from Nvim. I had to force install it. With the newest revision of nvim-treesitter you need a Neovim version that's built with the newest version of tree-sitter

**Comment by ingram1107** [comment]
Ah I see, it seems all right now after the installation from the latest build of neovim nightly

**Comment by lalitmee** [comment]
I installed the latest neovim but still can't fix the problem following the same thing. `TSUninstall all`

**Comment by theHamsta** [comment]
@lalitmee can you provide more info? It's most probably due to your nvim distro links to the old tree-sitter version. You could also try to revert nvim-treesitter to the  one before #1000

**Comment by lalitmee** [comment]
Today I ran `PlugUpdate` and then my `nvim-treesitter` got upgraded. And from then I am getting this error
```
Error detected while processing FileType Autocommands for "*":
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/lalitmee/.config/nvim/autoload/plugged/nvim-treesitter/parser/lua.so: supported between 9 and 12, found 13
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/lalitmee/.config/nvim/autoload/plugged/nvim-treesitter/parser/lua.so: supported between 9 and 12, found 13
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/lalitmee/.config/nvim/autoload/plugged/nvim-treesitter/parser/lua.so: supported between 9 and 12, found 13
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/lalitmee/.config/nvim/autoload/plugged/nvim-treesitter/parser/lua.so: supported between 9 and 12, found 13
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/lalitmee/.config/nvim/autoload/plugged/nvim-treesitter/parser/lua.so: supported between 9 and 12, found 13

Error detected while processing CursorHold Autocommands for "<buffer=2>":
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/lalitmee/.config/nvim/autoload/plugged/nvim-treesitter/parser/lua.so: supported between 9 and 12, found 13
````
This error is the changed error after I installed the latest neovim nightly version.

I have tried the following steps:
```
TSUninstall all
TSInstall all
```

Now I have tried uninstalling neovim and reinstall again. But that also didn't work.

I am using `Pop os 20.04` and I am installing `neovim` using the `unstable/ppa` from neovim wiki.

I also have `linuxbrew` installed so I have tried this https://github.com/neovim/neovim/issues/14044#issuecomment-790242256
but it also didn't work.

Can you please help me? Thanks in advance.

**Comment by antaxiom** [comment]
I'm having this same issue with lua. What's going on with the latest update?

**Comment by theHamsta** [comment]
@lalitmee our CI required a `brew upgrade` for you as a desktop users probably a clean uninstall and reinstall of Neovim and perhaps tree-sitter. The tip from neovim/neovim#14044 can't work since it was for *before* we merged the commit. I solved the mismatch problem by downgrading the runtime to the old parsers instead of upgrading the parsers. What you need to do now is upgrade your runtime to be compatible with the now updated parsers. If you have  `ABI 9 and 12`, you can also install tree-sitter cli 0.18.X and use `:TSInstallFromGrammar` or revert the merge of #1000

@antaxiom tree-sitter made an ABI incompatible change. This means that new parsers are only compatible with the new tree-sitter runtime. If your Neovim has the old one, it will no longer work.

**Comment by lalitmee** [comment]
Actually I solved it uninstalling neovim from papa and installing it from brew. And that worked. May be because it doesn't have the old reference to he parsers of neovim treesitter which was there in the ppa neovim.

Thanks for your help. Great tool.

**Comment by fdschmidt93** [comment]
I am building neovim from on ssh like so

```bash
rm $HOME/local/bin/nvim
rm -r $HOME/local/share/nvim/
rm -rf neovim
git clone https://github.com/neovim/neovim.git
cd neovim
make clean 
make CMAKE_INSTALL_PREFIX=$HOME/local install
```
However neovim always yields ABI mismatch errors (`supported 13 - found 12`). I've also tried `make distclean` as well since it also seems to clean up dependencies though to no avail. 

Not entirely sure whether `supported 13 - found 12` essentially means I have an old compiled parser, though I both reinstalled `nvim-treesitter` anew and tried copying the locally compiled parsers to ssh (which worked in the very early versions of `nvim-treesitter` when for reasons I cannot recall I couldn't compile parsers on ssh).

Has anyone faced similar issues or can help in any way? thanks in advance :)

**Comment by pechorin** [comment]
<img width="1254" alt="Снимок экрана 2021-03-17 в 19 19 06" src="https://user-images.githubusercontent.com/226270/111501018-a7ac7800-8755-11eb-8d81-33c2f515e6a8.png">

issue on latest vimr after updating to latests version

**Comment by theHamsta** [comment]
> Not entirely sure whether supported 13 - found 12 essentially means I have an old compiled parser

means you have an old parser. It's possible that `:TSInstallFromGrammer` (it is run automatically on `:TSInstall` for some parsers has generated the wrong version. This can happen

- when you have an old version of tree-sitter-cli
- when you have ./node_modules/bin in PATH and it will use the tree-sitter-cli pinned by the parser repo

**Comment by fdschmidt93** [comment]
Many thanks!  Certainty that I'm on the right tree-sitter version helped overcoming my issues swiftly. 

It appears for whatever reason I had conflicting old parsers on in `.local/share/nvim/site/parsers` in addition to `.local/share/nvim/site/pack/packer/start/nvim-treesitter/parsers` - cleaning that out fixed my issues (as I can imagine they don't get cleared by `:TSUninstall` or the like - though in fairness reading the __full__ middle part of the path would have saved my headaches).

**Comment by bscuron19** [comment]
https://github.com/neovim/neovim/issues/14044#issuecomment-790876166

This worked for me

**Comment by ellisonleao** [comment]
I am getting a different error here: 

Tried multiple approaches and even reinstalling nvim-treesitter again, but when i call `:TSUpdate all` or `:TSUpdateFromGramma all` i am getting a:

`Error during dowload, please verify your internet connection`

My current config is just this:

```lua
  require("nvim-treesitter.configs").setup({
    highlight = {enable = true},
    ensure_installed = {"go", "python", "lua", "yaml", "json", "javascript", "bash"},
  })
```

**Comment by theHamsta** [comment]
@ellisonleao :TSInstallSync gives you more output.

**Comment by ellisonleao** [comment]
```
Downloading...
curl: symbol lookup error: curl: undefined symbol: curl_url_set, version CURL_OPENSSL_4
Error during download, please verify your internet connection
Failed to execute the following command:
{
  cmd = "curl",
  err = "Error during download, please verify your internet connection",
  info = "Downloading...",
  opts = {
    args = { "-L", "https://github.com/nvim-treesitter/tree-sitter-lua/archive/b6d4e9e10ccb7b3afb45018fbc391b4439306b23.tar.gz", "--output", "tree-sitter-lua.tar.gz" },
    cwd = "/home/ellison/.local/share/nvim"
  }
}
```

**Comment by theHamsta** [comment]
Let me google that for you

https://askubuntu.com/questions/1211782/curl-openssl-4-not-found-required-by-curl
https://github.com/curl/curl/issues/4448#issuecomment-588200364

Any of these? Have you anaconda installed or anything that manipulates your LDPATHs

**Comment by EdwinOntiveros** [comment]
When running`:TSInstallFromGrammar all` a few error messages appear.
![imagen](https://user-images.githubusercontent.com/46140107/111517317-8f6b3780-871a-11eb-8221-55a2fd087363.png)

I have the latest version of tree-sitter:
![imagen](https://user-images.githubusercontent.com/46140107/111518466-b6763900-871b-11eb-9996-6bb4fcde559f.png)

And the current version of Neovim built from master:
![imagen](https://user-images.githubusercontent.com/46140107/111518778-06ed9680-871c-11eb-9352-40b4fe2b6ca0.png)

I was able to fix the "ABI version mismatch" by following these steps:

1. Removing the `{'do': ':TSUpdate'}` portion from my plugin-init.vim (could be on a different file for you though) from the tree-parser clause.
2. Execute `:TSUninstall all`
3. Restart Neovim
It then started creating the parsers anew:
![imagen](https://user-images.githubusercontent.com/46140107/111519892-2afda780-871d-11eb-85a4-d1e608ae6917.png)

No errors this time:
![imagen](https://user-images.githubusercontent.com/46140107/111520017-4c5e9380-871d-11eb-84d0-bfbd64daead6.png)

All parsers installed correctly:
![imagen](https://user-images.githubusercontent.com/46140107/111520949-330a1700-871e-11eb-8aea-cab982bd5b81.png)

It works now as intended:
![imagen](https://user-images.githubusercontent.com/46140107/111523200-9d23bb80-8720-11eb-8ec8-9a735e6a7009.png)

I hope this helps!

**Comment by ellisonleao** [comment]
@theHamsta 

```
 /usr/lib/x86_64-linux-gnu/libcurl.so.4 -> libcurl.so.4.6.0
```
this seems to be as expected, i am not using anaconda or anything like it, curl is installed directly in the system. Do you have the full curl command i can test on my side?

**Comment by theHamsta** [comment]
You can try to change this line so that it will try to use Git instead
https://github.com/theHamsta/nvim-treesitter/blob/2083f37fc0495e053f1fa952888f3b3d6acd14bc/lua/nvim-treesitter/shell_command_selectors.lua#L53

**Comment by ellisonleao** [comment]
@theHamsta yeah, the issue was with curl on my side, i got that fixed and the updates are now running fine. Thanks for the help!

**Comment by seblj** [comment]
Don't know if it's related to this, but I also got this problem and fixed it by installing the latest of everything. However, when using the parser for typescript and tsx it is very slow compared to the others (C and Python at least). By doing --startuptime when opening a file it uses around 15-20ms for the `first screen update`. When opening a `.ts` or `.tsx` file it uses around 600-700ms for the `first screen update`.

**Comment by kyazdani42** [comment]
@theHamsta is this related to the query loading time ?

**Comment by theHamsta** [comment]
At least with 0.19.X some queries take much longer to load: https://github.com/tree-sitter/tree-sitter/issues/973

When you do a `nvim --headless -c "luafile ./scripts/check-queries.lua"` it hangs with some languages. You could help @maxbrunsfeld when you detect a specific combination of queries and parser that causes those performance regressions. Maybe also check the load times without the queries for tsx.

**Comment by seblj** [comment]
I just disabled highlighting with tree-sitter and compared the `first screen update` with and without for a tsx file. With tree-sitter highlighting enabled it used 696.356ms, and without it used 007.448. I also did this on the same file. I have tried to uninstall everything with `TSUninstall all` and then installing again multiple times. Recently when I did a `TSUninstall all` and when it then installed everything when I re-opened neovim, the checkhealth looked like this:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/5160701/111544075-3a5c0f80-8774-11eb-866f-7c7c43abea7a.png">

Even though it says there is error in highlighting for the different languages like C, tsx and typescript, they all seem to work, other than at least typescript and tsx is really slow. 
When running `nvim --headless -c "luafile ./scripts/check-queries.lua"` I got this 
`...-nightly/share/nvim/runtime/lua/vim/treesitter/query.lua:28: attempt to index a nil value` on several tests.

**Comment by tamis-laan** [comment]
After a `PlugUpdate` in order to install a new plugin TS went to hell. Following  this issue I did the following:
``` bash
rm -fr ~/.vim/
rm -fr ~/.local/nvim/
yay -S neovim-git # build from source latest version
```
Inside vim I did `TSInstall javascript html css`, doing a `checkhealth` gives me:
```
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.17.3(parser generator, used for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found.

## Parser/Features H L F I
  - html           x x x x 
  - javascript     x x x x 
  - css            x . x x 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```
Still not working X_X

**Comment by efdi** [comment]
I had all parsers broken (except C). And also "`tree-sitter` executable not found" in healthcheck with errors on startup.
Highlighting did not work.
I've recompiled neovim from latest sources, installed to /usr/local/bin/nvim, reinstalled all parsers etc, didn't help.
BUT When I symlinked /usr/bin/vim to fresh /usr/loca/bin/nvim, suddenly, it is working.
I still got "`tree-sitter` executable not found" but all parsers are OK and hightlighting now works.
Maybe it will help someone too.

**Comment by theHamsta** [comment]
@efdi tree-sitter CLI is not needed. See #1025

**Comment by cjnucette** [comment]
I was using the `ppa:neovim-ppa/unstable` on Ubuntu 20.04, and I was getting this error. Not only I was getting this error, but also my `healthcheck` was a mess. So I remove this version of `nvim` and compiled it from `github`, and problem solved. I hope this helps.

**Comment by tamis-laan** [comment]
Why close this? For me it's still not working >_<

**Comment by theHamsta** [comment]
@tamis-laan I didn't see this issue connected to a specific problem but rather an advise for the time when Neovim switched to the new runtime. People having problems very likely have different kind of problems. In your case, most likely related to your distribution. Could you try `nvim --headless -c "luafile ./scripts/check-queries.lua"` in the nvim-treesitter directory? What error message? Does it work when you use Neovim from AppImage/brew?

I'll extend the healthcheck to be again more helpful in reporting error messages.

**Comment by tamis-laan** [comment]
> @tamis-laan I didn't see this issue connected to a specific problem but rather an advise for the time when Neovim switched to the new runtime. People having problems very likely have different kind of problems. In your case, most likely related to your distribution. Could you try `nvim --headless -c "luafile ./scripts/check-queries.lua"` in the nvim-treesitter directory? What error message? Does it work when you use Neovim from AppImage/brew?
> 
> I'll extend the healthcheck to be again more helpful in reporting error messages.

I'm using the arch neovim-git package [https://aur.archlinux.org/packages/neovim-git](https://aur.archlinux.org/packages/neovim-git) which basically builds/compiles neovim from source. As I stated above clearing `~/.vim/` and `./local/nvim/` did not help either. 

Running the script you mention produces:
``` bash
> nvim --headless -c "luafile ./scripts/check-queries.lua"
Checking html highlights
Error detected while processing command line:
/usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/tux/.vim/plugged/nvim-treesitter/parser/html.so: supported between 9 and 12, found 13
Checking html locals
/usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/tux/.vim/plugged/nvim-treesitter/parser/html.so: supported between 9 and 12, found 13
Checking html folds
/usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/tux/.vim/plugged/nvim-treesitter/parser/html.so: supported between 9 and 12, found 13
Checking html indents
/usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/tux/.vim/plugged/nvim-treesitter/parser/html.so: supported between 9 and 12, found 13
Checking javascript highlights
/usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/tux/.vim/plugged/nvim-treesitter/parser/javascript.so: supported between 9 and 12, found 13
Checking javascript locals
/usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/tux/.vim/plugged/nvim-treesitter/parser/javascript.so: supported between 9 and 12, found 13
Checking javascript folds
/usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/tux/.vim/plugged/nvim-treesitter/parser/javascript.so: supported between 9 and 12, found 13
Checking javascript indents
/usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/tux/.vim/plugged/nvim-treesitter/parser/javascript.so: supported between 9 and 12, found 13
Checking css highlights
/usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/tux/.vim/plugged/nvim-treesitter/parser/css.so: supported between 9 and 12, found 13
Checking css locals
Checking css folds
/usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/tux/.vim/plugged/nvim-treesitter/parser/css.so: supported between 9 and 12, found 13
Checking css indents
/usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/tux/.vim/plugged/nvim-treesitter/parser/css.so: supported between 9 and 12, found 13
Last error: 
Check failed:
./scripts/check-queries.lua:55: /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/tux/.vim/plugged/nvim-treesitter/parser/css.so: supported between 9 and 12, found 13
```

**Comment by theHamsta** [comment]
@tamis-laan other AUR users that they removed neovim-git and reinstalled it to avoid incremental builds.

The decisive package is this one: https://archlinux.org/packages/?q=tree-sitter

**Comment by weilbith** [comment]
@tamis-laan I can recommend to use the [neovim-nightly-bin](https://aur.archlinux.org/packages/neovim-nightly-bin/) AUR package. It is way faster as you must not build each time (so pulling recent nightly builds is a bliss) and you avoid all problems which could occur during a build. At least I have good experience with it. 🤷🏾

**Comment by GGCristo** [comment]
Just in case someone is as stupid as I am, I forgot to do ``sudo make install`` after the clean re-installation of neovim, so my binary was never updated... after that is working.
