### ISSUE TITLE
Tree sitter not working and giving error

### ISSUE THREAD

**Issue by FardeenCodes** [nvim-treesitter/nvim-treesitter#1041]
**Using The latest neovim nigthly release**

**Describe the bug**

The syntax highlighting is not working and also the tree-sitter/playground is giving error
`Error executing vim.schedule lua callback: ...m/neovim-nightly/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch : supported between 9 and 12, found 13`

**To Reproduce**

1. Run  `:TSPlaygroundToggle`
2. See error

` Error executing vim.schedule lua callback: ...m/neovim-nightly/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch : supported between 9 and 12, found 13`

**Expected behavior**

Should have run without error
**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

- ERROR: `tree-sitter` executable not found                - OK: `git` executable found.
  - OK: `cc` executable found.

## Parser/Features H L F I
  - python         x x x x-                                  - query          x x x x-                                  - c              x x x x-                                 Legend: H[ighlight], L[ocals], F[olds], I[ndents]                  *) multiple parsers found, only one will be used           x) errors found in the query, try to run :                 TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/fardeen/neovim/neovim-nightly/build/config -I/home/fardeen/neovim/neovim-nightly/src -I/home/fardeen/neovim/neovim-nightly/.deps/usr/include -I/usr/include -I/home/fardeen/neovim/neovim-nightly/build/src/nvim/auto -I/home/fardeen/neovim/neovim-nightly/build/include
Compiled by fardeen@localhost

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**

**Comment by kyazdani42** [comment]
see #1036
