### ISSUE TITLE
selection command didn't contain the last character

### ISSUE THREAD

**Issue by singlexyz** [nvim-treesitter/nvim-treesitter#1045]
tree-sitter 0.19.3
NVIM  v0.5.0-dev+7c204af87
filetype: javascript & typescript

when execute `init_selection` on `domUpdated` word ⬇️ 
it didn't contain `d`

<img width="448" alt="截屏2021-03-18 上午4 21 38" src="https://user-images.githubusercontent.com/4456413/111533184-778ac680-87a1-11eb-98c9-90697884f2b1.png">

then execute `node_incremental` ⬇️ 
it didn't contain `}`

<img width="447" alt="截屏2021-03-18 上午4 23 30" src="https://user-images.githubusercontent.com/4456413/111533461-c173ac80-87a1-11eb-9f41-08ef1a456851.png">

**Comment by singlexyz** [comment]
🥺

**Comment by vigoux** [comment]
Could you retry on latest master just to be sure? I can't reproduce locally so there may be an issue with the configs

**Comment by singlexyz** [comment]
> Could you retry on latest master just to be sure? I can't reproduce locally so there may be an issue with the configs

I found the problem, because in my init.vim:
 `set selection=exclusive`
this will make the vim don't include the last char in select mode.
sorry for that, this issue will be close. 😢
