### ISSUE TITLE
TOhtml can't show highlight color

### ISSUE THREAD

**Issue by echofff** [nvim-treesitter/nvim-treesitter#1049]
**Describe the bug**

The output of :TOhtml doesn't show highlight color. just white text 

**To Reproduce**

1.Open a simple rust code. With
 ``` viml
:TSEnableAll highlight
```
It looks like
![code-with-highlight](https://user-images.githubusercontent.com/19630556/111568063-0536d800-87db-11eb-9989-b8f64e7f1219.png)

2.Exec TOhtml and save to file main1.html
``` viml
:TOhtml
:w main1.html
```

3. Disable highlight 
``` viml
:TSDisableAll highlight
:TOhtml
:w main2.html
```
![code-without-hight](https://user-images.githubusercontent.com/19630556/111568387-9dcd5800-87db-11eb-8e1e-65979e54fb3d.png)

4. Open browser

main1.html:
![html-with-hight](https://user-images.githubusercontent.com/19630556/111568434-b3db1880-87db-11eb-8bde-85903f1cccdc.png)

main2.html:
![html-without-highlight](https://user-images.githubusercontent.com/19630556/111568441-b6d60900-87db-11eb-877e-f28ebb09533f.png)

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.3(parser generator, used for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found.

## Parser/Features H L F I
  - c_sharp        ✓ . . . 
  - svelte         ✓ . ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ 
  - teal           ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ 
  - python         ✓ ✓ ✓ ✓ 
  - sparql         ✓ ✓ ✓ ✓ 
  - comment        ✓ . . . 
  - dart           ✓ ✓ . ✓ 
  - lua            ✓ ✓ ✓ ✓ 
  - ocaml          ✓ ✓ ✓ . 
  - go             ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ 
  - jsdoc          ✓ . . . 
  - ledger         ✓ . ✓ ✓ 
  - php            ✓ ✓ ✓ . 
  - julia          ✓ ✓ . . 
  - supercollider  ✓ ✓ ✓ ✓ 
  - turtle         ✓ ✓ ✓ ✓ 
  - r              ✓ ✓ . . 
  - html           ✓ ✓ ✓ ✓ 
  - devicetree     ✓ ✓ ✓ ✓ 
  - gdscript       ✓ ✓ . . 
  - rst            ✓ ✓ . . 
  - regex          ✓ . . . 
  - ql             ✓ ✓ . . 
  - fennel         ✓ ✓ . . 
  - query          ✓ ✓ ✓ ✓ 
  - nix            ✓ ✓ ✓ . 
  - cpp            ✓ ✓ ✓ ✓ 
  - kotlin         ✓ . . . 
  - ruby           ✓ ✓ ✓ ✓ 
  - vue            ✓ . ✓ . 
  - ocamllex       ✓ . . . 
  - toml           ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . 
  - graphql        ✓ . . ✓ 
  - javascript     ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ 
  - glimmer        ✓ . . . 
  - erlang         . . . . 
  - clojure        ✓ ✓ . . 
  - ocaml_interface✓ ✓ ✓ . 
 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         *) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Comment by vigoux** [comment]
Hi and thanks for reporting.
From what I can tell, the actual issue is not possible to fix here, but should be fixed upstream, in the `:TOHtml` command.

I think the "only" thing to change is make `:TOHtml` aware of decorations.

cc @bfredl am I right?

**Comment by alemuller** [comment]
Ping. Still broken.

**Comment by alemuller** [comment]
There is a function called `nvim__screenshot` that takes the a shell screenshot, it seems to work pretty well.

**Comment by David-Else** [comment]
It would be GREAT to get this working with treesitter! Treesitter highlighting is much better, at the moment having to turn it off to generate HTML is a real downer.

@alemuller How is `nvim__screenshot` different from pressing `PrtScn`?

**Comment by alemuller** [comment]
@David-Else 
The CSS from HTML should cascade to SVG according to [#StyleSheetsInHTMLDocuments](https://www.w3.org/TR/SVG/styling.html#StyleSheetsInHTMLDocuments). I haven't tried thought.

After writing a template, I realized that working with multi line text in svg isn't trivial. Maybe HTML is a better fit.

I'll have a look on the implementation of `:TOhtml`.

**Comment by lewis6991** [comment]
Closing as this is an upstream issue. No one is planning to work on this, but as always PR's are welcome.
