### ISSUE TITLE
Can't install Typescript parser

### ISSUE THREAD

**Issue by ndavidq0** [nvim-treesitter/nvim-treesitter#1052]
`TSInstall typescript` returns `Error during tarball extraction` on Windows (at least)

**Comment by theHamsta** [comment]
Probably, due to the symlinks. Can you try to rebase https://github.com/nvim-treesitter/nvim-treesitter/pull/813 on current master or just replace this line by false so it would try to use git for downloading: https://github.com/theHamsta/nvim-treesitter/blob/ce4b591dfda157049642b59981513cfd65a4e847/lua/nvim-treesitter/shell_command_selectors.lua#L127

**Comment by ndavidq0** [comment]
I currently don't have wifi. Will do so as soon as possible

**Comment by ndavidq0** [comment]
Is the PR going to be merged soon ?

**Comment by spywhere** [comment]
Work for me when set to false according to @theHamsta suggestion.

> Probably, due to the symlinks. Can you try to rebase https://github.com/nvim-treesitter/nvim-treesitter/pull/813 on current master or just replace this line by false so it would try to use git for downloading: https://github.com/theHamsta/nvim-treesitter/blob/ce4b591dfda157049642b59981513cfd65a4e847/lua/nvim-treesitter/shell_command_selectors.lua#L127

**Comment by neelkarma** [comment]
For some reason `:TSInstallSync typescript` seemed to install when `:TSInstall typescript` gave the `Error during tarball extraction` message. However, running `:TSBufEnable highlight` did nothing.

**Comment by Thanood** [comment]
Replacing the line mentioned above to `false` worked for me, too. Thanks. 😃

I have the same issue as @neelkarma btw. Calling `:TSInstallSync typescript` yields successful results, but not installing anything while `:TSInstall` and `:TSUpdate` both yield error messages.

**Comment by theHamsta** [comment]
Would #813 work? Anybody willing to rebase this PR on current master and test whether it works with our new Windows CI?

**Comment by Thanood** [comment]
Well, on Windows `and not fn.hs('win32')` would become `false` which in turn will lead to git being used instead of tar. So yes, that should work. 😃 

Regarding the rebase, should we not wait for the creator of the PR (@AdnoC) to rebase?

**Comment by vigoux** [comment]
I think we could rebase it ourselves and merge it, that's the quickest way to have that fixed.

**Comment by Thanood** [comment]
Please have a look at my rebase attempt at #1186

**Comment by neelkarma** [comment]
Everything seems to be working fine after the merge - The typescript parser installed successfully 🚀I'm only having some problems with installing the haskell parser (Error during compilation) but that's not in the scope of this issue.
Anyways, if it's fixed for everyone else, I think this issue as well as #813 can be closed.
