### ISSUE TITLE
Jxs props should be a different group

### ISSUE THREAD

**Issue by luisiacc** [nvim-treesitter/nvim-treesitter#1055]
Right now on jsx files, components props are been highlighted as TSProperty, I think they should be a separate group for more customizable themes.
![image](https://user-images.githubusercontent.com/31720261/111671326-38836200-87ef-11eb-8607-f9fc54efd1d8.png)

**Comment by kyazdani42** [comment]
hum that's debatable, but basically jsx props are object properties by definition. @steelsojka what do you think about that ? I'm not too sure because i don't want to make js an exception over other languages.
@luisiacc maybe you could try extending the queries for now and we'll discuss that and decide what we should do.

**Comment by theHamsta** [comment]
TSAttribute is used by upstream tree-sitter for html attributes. But we didn't know what was the actual purpose of TSAttribute so we removed it.

**Comment by luisiacc** [comment]
TSAttribute I think it's more appropiate for jsx props than TSProperty.

**Comment by steelsojka** [comment]
If we want to change it from TSProperty to TSAttribute we need to change it in HTML as well. I would expect JSX attributes and HTML attributes to be consistent. Currently, they both are properties. If the goal is to keep attributes differentiated from regular object properties then I'm cool with that change. I DON'T think we should do a specific highlight for JSX props though, just like @kyazdani42 said.

**Comment by luisiacc** [comment]
Any update here ?

**Comment by luisiacc** [comment]
> @luisiacc maybe you could try extending the queries for now and we'll discuss that and decide what we should do.

I have no idea how the query should look like for that, could you point me to any docs to learn ?

**Comment by theHamsta** [comment]
@luisiacc feel free to create a PR that replaces all HTML attributes by `@attribute` and all previous usages of `@attribute` by `@annotation`. We would then be much closer to the Atom queries. You could also replace `@property` by something like `@property.html-attribute.jsx` but then we need to wait for an upstream PR that allows this query specialization.

**Comment by luisiacc** [comment]
This was taken care of on [PR 1572](github.com/nvim-treesitter/nvim-treesitter/pull/1572)
