### ISSUE TITLE
Can I update tree-sitter or have to stay in sync to a certain version

### ISSUE THREAD

**Issue by dahmc** [nvim-treesitter/nvim-treesitter#1056]
Tree-sitter updated to 0.19.4 today, and while it seems there are no changes that affect the project at all, this is more of a general question:

Can I just happily keep upgrading tree-sitter or do I have to stay within a certain version/range to be compatible with this plugin?

**Comment by theHamsta** [comment]
You can use any version of tree-sitter. The ABI break in 0.19.0 was really exceptional.

**Comment by dahmc** [comment]
Thanks a lot @theHamsta for the clarification!
