### ISSUE TITLE
Unknown causes a lot of mistakes

### ISSUE THREAD

**Issue by denstiny** [nvim-treesitter/nvim-treesitter#1061]
![image](https://user-images.githubusercontent.com/57088952/111790479-34456a80-88fd-11eb-9420-0298c023f337.png)
![image](https://user-images.githubusercontent.com/57088952/111790520-3d363c00-88fd-11eb-8bb4-7770094118b9.png)
![image](https://user-images.githubusercontent.com/57088952/111790682-6ce54400-88fd-11eb-8506-41c6b34fcf7c.png)

My configuration https://github.com/denstiny/nvim-nanny/blob/main1/lua/treesitter.lua
I can't download server language

**Comment by denstiny** [comment]
I tried neovim - the nightly - git and manually compile, all useless

**Comment by theHamsta** [comment]
It's important to which tree-sitter runtime links. If you do a manual compilation you typically need to do a clean build. The message indicates that your Nvim linked against tree-sitter 0.18.X. But you'll need 0.19.X to make it work (ABI 13). Our CI passes when you use brew or the current nvim AppImage.

**Comment by denstiny** [comment]
> 哪些树传送器运行时链接很重要。如果您进行手动编译，则通常需要进行干净的构建。该消息表明您的Nvim已链接到tree-sitter0.18.X。但是您需要0.19.X才能使其正常工作（ABI 13）。当您使用brew或当前的nvim AppImage时，我们的CI通过。

It's strange that I manually delete neovim completely, and then reinstall

**Comment by denstiny** [comment]
> 哪些树传送器运行时链接很重要。如果您进行手动编译，则通常需要进行干净的构建。该消息表明您的Nvim已链接到tree-sitter0.18.X。但是您需要0.19.X才能使其正常工作（ABI 13）。当您使用brew或当前的nvim AppImage时，我们的CI通过。

You can turn off the
