### ISSUE TITLE
Highlights for jsdoc stopped working after update to 0.19

### ISSUE THREAD

**Issue by kristijanhusak** [nvim-treesitter/nvim-treesitter#1069]
**Describe the bug**

Couple of days ago while I was still on old treesitter version, jsdoc was highlighted properly. After the update, it stopped highlighting at all. It's just shown as comment.
I don't know how to go back to old version at this moment to re-test, but I'm 100% sure it worked fine.

**To Reproduce**

1. Create new `test.js` file
2. Enter this content:
```javascript
/**
 * @param {Object} test
 */
```
3. Check the highlights. It's only highlighted as comment

**Expected behavior**

Expected to have different highlights for `@param` and `Object`

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.3(parser generator, used for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found.

## Parser/Features H L F I
  - python         ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ 
  - jsdoc          ✓ . . . 
  - go             ✓ ✓ ✓ ✓ 
  - php            ✓ ✓ ✓ . 
  - c              ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev+1162-gb0c0c50d3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/kristijan/github/neovim/build/config -I/home/kristijan/github/neovim/src -I/home/kristijan/github/neovim/.deps/usr/include -I/usr/include -I/home/kristijan/github/neovim/build/src/nvim/auto -I/home/kristijan/github/neovim/build/include
Compiled by kristijan@kristijan-pc

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

</code>
</details>

**Additional context**

Screenshots:

![default](https://i.imgur.com/FzdxuOf.png)

![param-highlights](https://i.imgur.com/bLjV0oW.png)

![object-highlights](https://i.imgur.com/uDXT3wq.png)

**Comment by theHamsta** [comment]
@stsewd could this be related to injecting the comment parser at the same time?

**Comment by elianiva** [comment]
weird, mine still works and I use the comment parse as you can see 

![image](https://user-images.githubusercontent.com/51877647/112000145-4834da80-8b50-11eb-95d5-b8654397dbad.png)

**Comment by theHamsta** [comment]
@elianiva did you check whether this is truely the jsdoc parser and not the comment parser?

**Comment by elianiva** [comment]
aha! That seems to be the case :)
it gets overridden by the comment parser

**Comment by theHamsta** [comment]
@stsewd can you check whether JS can inject both parsers into the comment region?

**Comment by steelsojka** [comment]
I'm noticing the same problem. It should be using both parsers. They both just have the same root node. I'll take a look at see what's going on. Could the issue be in the queries?

**Comment by stsewd** [comment]
This looks like a problem with the precedence of the injection.
Not sure how precedence is taking into account here.
If I change the query from `((comment) @comment @jsdoc)` to `((comment) @jsdoc @comment)` the jsdoc parser is used, but the comment parser isn't. So I guess neovim is only injecting one language.

From the first screenshot looks like the comment parser isn't installed.
@kristijanhusak do you have the comment parser installed? `:TSInstall comment`?

**Comment by steelsojka** [comment]
I've dabbled in this and there isn't a good way to determine precedence for the injected languages. Right now it is more or less base on the iteration order of the injection map. There is corner cases that are very hard to get around. I was waiting for another PR to language injection before I went ahead and tackled this one.  https://github.com/neovim/neovim/pull/14046

**Comment by stsewd** [comment]
Till this is fixed I think it is fine to disable the comment parser for js, people can override the injection in `after/queries/ecma/injections.scm` adding `(comment) @comment` (or at least I think that should work)

**Comment by kristijanhusak** [comment]
@stsewd I didn't had it installed. I tried installing it, and now it looks like this:

![screenshot](https://i.imgur.com/UDBCqyR.png)

It's a bit better, but it's not as before. Before `Object` was also highlighted. Now it looks like it's not matched at all:

![screenshot-no-match](https://i.imgur.com/CR81ddT.png)

**Comment by stsewd** [comment]
@kristijanhusak you can try creating this file `~/.config/nvim/after/queries/ecma/injections.scm` with `(comment) @jsdoc` inside it as a workaround.

**Comment by stsewd** [comment]
Hmm, looks like if they are captured in separate queries they can work together, I'll see if I can send a PR.
