### ISSUE TITLE
Upgraded to .19.4 and its all broken

### ISSUE THREAD

**Issue by GustavoPrietoP** [nvim-treesitter/nvim-treesitter#1077]
Im getting this error E5108: Error executing lua ...nux64/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch : supported between 9 and 12, found 13

I've seen another thread but couldnt find a solution. 

Anyone knows how to fix this?

**Comment by theHamsta** [comment]
Install a newer nightly version of nvim (app image, brew, build from source). Do a clean build when building from source (cmake must use a newer version of the bundled tree-sitter runtime). You need ABI 13 for the new parser versions.

**Comment by theHamsta** [comment]
Same issue as https://github.com/nvim-treesitter/nvim-treesitter/issues/1076#event-4488825181 ?

**Comment by GustavoPrietoP** [comment]
> Install a newer nightly version of nvim (app image, brew, build from source). Do a clean build when building from source (cmake must use a newer version of the bundled tree-sitter runtime). You need ABI 13 for the new parser versions.
> 
> > Upgraded to .19.4
> 
> if you refer to the tree-sitter CLI binary, the CLI is not required for actually using the parsers. Just when you need to generate a parser from grammar.js (which is not necessary for most parsers).

This worked, thank you so much!
