### ISSUE TITLE
How to headless install all the necessary when build docker image?

### ISSUE THREAD

**Issue by sheeaza** [nvim-treesitter/nvim-treesitter#108]
When embedded nvim to docker image, I need to headless install all the parsers. Is there any options like:
`nvim --headless +TSInstall all`?

**Comment by vigoux** [comment]
You should now be able to run `TSInstall all` ! If you only want a certain list of parsers, you can also do `TSInstall my list of parsers` too !

**Comment by kyazdani42** [comment]
i'll also update the docs.

**Comment by sheeaza** [comment]
That's great, and for nvim headless install, it is also need a sync way to exit when installing finished, like this:
`nvim --headless ' +TSInstall -sync all' +qa`

**Comment by kyazdani42** [comment]
@sheeaza not sure i understand the sentence `it is also need a sync way to exit`, could you elaborate please ?

**Comment by sheeaza** [comment]
`TSInstall `is running asynchronous backend right? But in headless install mode, it needs a way to exist when all installations are done.
`nvim --headless ' +TSInstall -sync all' +qa`
with `-sync` option or any other symbal to represent "synchronous" meaning, the `+qa` command will excute after `+TSInstall all`  done

**Comment by kyazdani42** [comment]
could you open another issue please ?

**Comment by sheeaza** [comment]
ok, see here https://github.com/nvim-treesitter/nvim-treesitter/issues/111
