### ISSUE TITLE
Slow startuptime with tsx and typescript

### ISSUE THREAD

**Issue by seblj** [nvim-treesitter/nvim-treesitter#1082]
**Describe the bug**

Some languages are really slow to load with tree-sitter highlighting enabled. In my case, I have found typescript and tsx really slow to load, where tsx is even slower than typescript.
When opening a typescript file without tree-sitter highlighting enabled, `first screen update` in --startuptime uses 001.755ms. However, when tree-sitter highlighting is enabled, it uses 311.028ms.

There is an even bigger performance issue with tsx. Without tree-sitter highlighting: 003.876 for `first screen update`. With tree-sitter highlighting: 713.095ms for `first screen update`.

I think I know one reason it might be really slow. When using `TSHighlightCapturesUnderCursor` this is the result in a tsx-file: 
<img width="286" alt="image" src="https://user-images.githubusercontent.com/5160701/111999993-d2b01680-8b1d-11eb-8eb6-fe4304441b1a.png">

For a typescript file the same thing is happening, only four duplicates:
<img width="171" alt="image" src="https://user-images.githubusercontent.com/5160701/112001215-0b042480-8b1f-11eb-9d7f-4e267c552db8.png">

This is why I believe the typescript file is faster to load.

For my other files like C and Python, the loading time is not an issue. Here I only get two of the same if I use `TSHighlightCapturesUnderCursor`. 

**To Reproduce**

1. Have the latest neovim, tree-sitter and nvim-treesitter.
2. Install typescript and tsx
3. Open file and see the poor loading time.
4. Try `TSHighlightCapturesUnderCursor` to see duplicates.

**Expected behavior**

Not have duplicates, and faster loading time than now.

**Output of `:checkhealth nvim_treesitter`**

BTW: I believe the checkhealth is broken, especially on macOS, as it changes all the time. Maybe related to #1053?
<img width="661" alt="image" src="https://user-images.githubusercontent.com/5160701/112000542-61249800-8b1e-11eb-80bf-9cd8190e1a72.png">

**Output of `nvim --version`**

<img width="876" alt="image" src="https://user-images.githubusercontent.com/5160701/112001017-d2644b00-8b1e-11eb-9520-074d66c736d0.png">

**Additional context**

**Comment by theHamsta** [comment]
The abnormal checkhealth is probably due to #1076 #1077. Did you reinstall all parsers after updating you Nvim to 0.19.X runtime.

Could you check whether this could be part of the problem: https://github.com/neovim/neovim/pull/13778 (because it shows you 8 times TSInclude where it should only do it once or twice)

This might also be the issue https://github.com/tree-sitter/tree-sitter/issues/973 I observed that long loading times with tree-sitter-kotlin

**Comment by theHamsta** [comment]
Could you provide some timings with tree-sitter 0.18 and tree-sitter 0.19 of `tree-sitter query some-query.scm some-file.ts` for tree-sitter/tree-sitter#973

**Comment by seblj** [comment]
So I just tried out neovim/neovim#13778 together with tree-sitter 18.3 and this commit from nvim-treesitter 22f3203. This drastically improves performance. Now I only get one TSInclude in the same place for both tsx and typescript. Now when using 
--startuptime: `first screen update` uses 006.346ms for a typescript file, and 009.595ms for a tsx file. I have no problem at all with this performance, so if neovim/neovim#13778 with support for tree-sitter 19 is merged, I believe this would fix my issue.

**Comment by seblj** [comment]
> Could you provide some timings with tree-sitter 0.18 and tree-sitter 0.19 of `tree-sitter query some-query.scm some-file.ts` for [tree-sitter/tree-sitter#973](https://github.com/tree-sitter/tree-sitter/issues/973)

I just noticed that the change in the neovim PR was really small, so I tried to do the same thing on the latest build of neovim. It seems to make it a lot quicker than it is at the moment. However, it does seem to be a bit slower than 0.18.3. Now I got 115.366ms for a tsx file. This is noticeably slower than the 009.595 I got on the same file with 0.18.3, but a LOT quicker than with the duplicate problem. I'll see if I get some time tomorrow to do some more timings with 0.18 and 0.19 and post it in the issue you linked.

**Comment by theHamsta** [comment]
@seblj this seems to be tree-sitter issue. I already filed an issue. It would be easier for TS maintainers if you can provide a concrete query file (just concatenate `ecma` `typescript` highlights.scm) and post it directly on the tree-sitter issue.

**Comment by seblj** [comment]
@theHamsta Ok, I'll do this tomorrow!

**Comment by yanzhang0219** [comment]
> The abnormal checkhealth is probably due to #1076 #1077. Did you reinstall all parsers after updating you Nvim to 0.19.X runtime.

The abnormal checkhealth (https://github.com/nvim-treesitter/nvim-treesitter/issues/1053) on macOS has been existing for a while at lease since 0.19.3. After updating to 0.19.4 and reinstall all the parsers (via `TSInstall maintained`), the checkhealth nvim_treesitter is still broken. Thanks.

**Comment by steelsojka** [comment]
> Could you check whether this could be part of the problem: neovim/neovim#13778 (because it shows you 8 times TSInclude where it should only do it once or twice)

@theHamsta We really need a fix for this... I don't think anyone is looking at the root of the issue. I'm not even sure where to begin.

**Comment by theHamsta** [comment]
@yanzhang0219 but loading bug files has always been slow. This is another problem that even the loading of the query files is slow due to a version bump.

**Comment by yanzhang0219** [comment]
@theHamsta Okay. I see. Thanks.

**Comment by steelsojka** [comment]
I am noticing general slowness as well when opening files, especially when using the buffer preview in telescope.nvim. This is ever since the Treesitter update.... I think the duplicate queries may have a hand in it, but for sure something with the update.

**Comment by seblj** [comment]
> I am noticing general slowness as well when opening files, especially when using the buffer preview in telescope.nvim. This is ever since the Treesitter update.... I think the duplicate queries may have a hand in it, but for sure something with the update.

I did too notice the slowness with buffer preview for telescope. When I built neovim with the workaround from neovim/neovim#13778 it got noticeably better for me at least. But I also believe there is a problem with the update since it's still slower than before the update

**Comment by kirill-martynov** [comment]
Same thing happening with me too :(

Waiting for fix

**Comment by seblj** [comment]
Since this is no longer an issue for me after the PR from upstream fixing duplicates, I am going to close this
