### ISSUE TITLE
Need help to define a custom query

### ISSUE THREAD

**Issue by doums** [nvim-treesitter/nvim-treesitter#1084]
Hi,

For C language I'm trying to define a custom query that matches the name of a macro (eg defined with `#define`) after `#undef` directive and capture it:

```
#undef MACRO_NAME
//     ^^^^^^^^^^
```

I tried this but without success
```
(preproc_call
  argument: (preproc_arg
    type: (type_identifier) @macro_name))

; or

(((type_identifier) @property)
 (#has-ancestor? @macro_name preproc_call)
 (#has-ancestor? @property field_declaration)
 (#not-has-ancestor? @property function_declarator))
```
I use nvim-treesitter with the playground module, thank to it I can see the tree:
```
  preproc_call [25, 0] - [27, 0]
    directive: preproc_directive [25, 0] - [25, 6]
    argument: preproc_arg [25, 6] - [25, 11]
      type: type_identifier [25, 7] - [25, 11]
```
The corresponding node of the macro name is `type_identifier`.

But I fail to find the right syntax to capture it.

**Comment by theHamsta** [comment]
![image](https://user-images.githubusercontent.com/7189118/112029357-72c76900-8b39-11eb-9dfd-dbb3a110cf1f.png)

Yes, that was a nasty one. The preproc arg has a leading space. You have to press `t` in playground to turn off self injection (A c parser just for the macro region)

**Comment by theHamsta** [comment]
The equivalent for define would use `preproc_def` instead of `preproc_arg`

**Comment by doums** [comment]
Sorry but it's not clear, I assume this is a bug because you tagged the PR with the "bug" flag.
So If I understand correctly, for now it is not possible to query this, until a fix is done, right ?

**Comment by theHamsta** [comment]
The bug was tagged automatically because you chose it when creating the PR. You can just use the query in the screenshot. Use `t` to see the true syntax tree in playground. You will see that the nodes that you used are from a different C parser not the main AST.

**Comment by doums** [comment]
Oh ok, thanks for the details.
But the query does not work too..

`after/queries/c/highlights.scm`
```
((preproc_arg) @macro_name
(#eq? @macro_name " TEST" ))
```
`test.c`
```
#undef TEST
```

**Comment by theHamsta** [comment]
![image](https://user-images.githubusercontent.com/7189118/112059106-b9c65600-8b5b-11eb-879c-382452204128.png)

works on my machine. When this is the only query for C, it get's highlighted

![image](https://user-images.githubusercontent.com/7189118/112059209-d95d7e80-8b5b-11eb-8512-4e766eb48546.png)

it will no longer work when you have a post-space. Maybe you want to work with regexes?

![image](https://user-images.githubusercontent.com/7189118/112059396-14f84880-8b5c-11eb-966b-2f96553ea1a5.png)

**Comment by doums** [comment]
In fact I don't need a regex match because I want to query whatever is the macro name after the `#unset` directive.
So based on what you say, only `((preproc_arg) @macro_name)` should suffice and should work but this is not the case, even if (for testing purpose) with the regex part.
It's strange that it's work on your machine though. I have updated my plugins + parsers and my neovim build is almost on the last push.

**Comment by theHamsta** [comment]
@doums how do you check whether this query works or not? Do you set highlights? `:e!` might be necessary to update the highlights and sometimes even a restart.

You could try to display the results of https://github.com/theHamsta/nvim-treesitter/blob/b8c2128e7954fd7916c2004d92aa831b8f2d9c32/lua/nvim-treesitter/query.lua#L240-L248 directly
```
:lua print(vim.inspect(require'nvim-treesitter.query'.collect_group_results(0, 'highlights')))
```

**Comment by doums** [comment]
> @doums how do you check whether this query works or not?

The highlight is just wrong.

If I test this simple code
```
#undef TEST
```

I capture the node with `@constant.macro`
```
(preproc_call argument: (preproc_arg) @constant.macro)
```
which is mapped to `TSConstMacro`
```
hlmap["constant.macro"] = "TSConstMacro"
```
But for `TEST` macro name, the color is purple and the text style is italic instead of normal text style and orange (I override it). It's like another hi group is applied to the region. I don't know why.

But in the playground the query seems correct and working

no injected language
![no injected language](https://user-images.githubusercontent.com/6359431/112229554-79d2a200-8c33-11eb-85e8-48dbc14b1a69.png)
but it seems to be an error with injected language activated
![with injected language](https://user-images.githubusercontent.com/6359431/112230124-a3d89400-8c34-11eb-8098-a1a94ce00698.png)

**Comment by theHamsta** [comment]
Did you check `:TSHighlightsUnderCursor` and the lua function that I showed you? It's interesting to know whether the query did not match or whether it was just not mapped correctly

**Comment by theHamsta** [comment]
TSHighlightUnderCursor will not work in the injection region only in the space before it when you de

![image](https://user-images.githubusercontent.com/7189118/112234414-c7074180-8c3c-11eb-9e90-a45aa925abb9.png)

It seems that your query get's eaten up by this one which is identical. Just try you query while out-commenting all the rest of the file
```
;; Preproc def / undef
(preproc_def
  name: (_) @constant)
(preproc_call
  directive: (preproc_directive) @_u
  argument: (_) @constant
  (#eq? @_u "#undef"))
```

**Comment by doums** [comment]
Yes, `:TSHighlightCapturesUnderCursor` shows

![image](https://user-images.githubusercontent.com/6359431/112281257-263d7400-8c86-11eb-84ac-9d3c302bccce.png)

`:lua print(vim.inspect(require'nvim-treesitter.query'.collect_group_results(0, 'highlights')))`
```
{ {
    keyword = {
      node = <userdata 1>
    }
  }, {
    annotation = {
      node = <userdata 2>
    }
  }, {
    _u = {
      node = <userdata 3>
    },
    constant = {
      node = <userdata 4>
    }
  }, {
    constant = {
      macro = {
        node = <userdata 5>
      }
    }
  }, {
    function = {
      macro = {
        node = <userdata 6>
      }
    }
  } }
```

**Comment by steelsojka** [comment]
What is the injected language for the preproc_def node?

**Comment by steelsojka** [comment]
The injected language is going to overwrite any language queries you provide for the parent language. Take for example a javascript string with an injected language. Javascript will highlight it as a string and then the child language will apply it's highlights to the string using the highlight queries of the injected language. So if the injected language there is "c" then that C parser is only seeing "TEST" and is using whatever node that generates from the parser.
