### ISSUE TITLE
tree-sitter-zig

### ISSUE THREAD

**Issue by Himujjal** [nvim-treesitter/nvim-treesitter#1088]
I built the queries for ziglang in https://github.com/Himujjal/tree-sitter-zig. (`queries` folder)

But I am unable to activate the queries despite https://github.com/nvim-treesitter/nvim-treesitter#adding-queries steps. Can someone help me out. Its almost done.

EDIT: I put my queries in `~/.config/nvim/after/queries/zig/*.scm` and in `$VIMRUNTIME/after/queries/zig/*.scm` both. `tree-sitter highlight <file>.zig` command is working though.

**Comment by theHamsta** [comment]
You would have to put your queries in a folder names `queries/zig/highlights.scm` the zig part is missing. Maybe you can just add a symlink?

**Comment by theHamsta** [comment]
The `after` part is no longer working. There was a PR in upstream Neovim that removed `after` and now only plain rtp is accepted. Docs should be updated.

**Comment by Himujjal** [comment]
In checkhealth `  - zig            ✓ ✓ x x` is the message. (H, L, F, I)

But still not highlighting

**Comment by Himujjal** [comment]
I did copy the folders from `queries/*.scm` to `queries/zig/*.scm` for this folder and to `$VIMRUNTIME/queries/zig/*.scm`.

**Comment by theHamsta** [comment]
Works for me though

![image](https://user-images.githubusercontent.com/7189118/112065984-e0898a00-8b65-11eb-8b7e-69c7a83abe73.png)

- clone your repo
- added
```lua
  require "nvim-treesitter.parsers".get_parser_configs().zig = {
  install_info = {
  url = "~/projects/tree-sitter-zig",
  files = {"src/parser.c"}
  }
  }
```
- ln -s ~/projects/tree-sitter-zig/queries /home/stephan/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/zig
- highlight is working

**Comment by Himujjal** [comment]
strange thing. its still not working for me.

**Comment by Himujjal** [comment]
No
On `$ rg zig` inside the `packer/start` folder

```
neoformat/doc/neoformat.txt
449:- zig
450:  - [`zig fmt`](https://github.com/ziglang/zig)

neoformat/README.md
460:- zig
461:  - [`zig fmt`](https://github.com/ziglang/zig)

neoformat/autoload/neoformat/formatters/zig.vim
1:function! neoformat#formatters#zig#enabled() abort
2:      return ['zigfmt']
5:function! neoformat#formatters#zig#zigfmt() abort
7:      \ 'exe': 'zig',

nvim-lspconfig/CONFIG.md
5608:           https://github.com/zigtools/zls
5620:    filetypes = { "zig", "zir" }
```

**Comment by theHamsta** [comment]
And what happens when you do `set filetype=zig` manually?

**Comment by Himujjal** [comment]
Its working this way. I should probably make a PR to this repo for tree-sitter-zig

**Comment by Himujjal** [comment]
Hey I am not able to get the syntax highlighting done automatically done. I have to enter `set filetype=zig` to make it happen. Is that something to do with the official neovim core?
