### ISSUE TITLE
tree-sitter executable not found

### ISSUE THREAD

**Issue by boydkelly** [nvim-treesitter/nvim-treesitter#1097]
Im using 

```
NVIM v0.5.0-dev+1170-g691a72bb6
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

in a Fedora 34 container (neovim nightly and tree-sitter installed from copr repo)

running checkhealth I get the message:

` WARNING: `tree-sitter` executable not found (parser generator, only           needed for :TSInstallFromGrammar, not required for :TSInstall)`

I also have npm tree-sitter and nmp tree-sitter-cli installed.   

I'm not even sure if this is redundant or not.   Just that it was working recently in F33 container.

I also have a lot of these messages in checkhealth:

```
The following errors have been detected:
 - ERROR: yaml(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/          language.lua:33: ABI version mismatch for /var/home/bkelly/.local/share/        nvim/site/pack/packer/start/nvim-treesitter/parser/yaml.so: supported           between 13 and 13, found 11
 - ERROR: yaml(locals): /usr/share/nvim/runtime/lua/vim/treesitter/              language.lua:33: ABI version mismatch for /var/home/bkelly/.local/share/        nvim/site/pack/packer/start/nvim-treesitter/parser/yaml.so: supported           between 13 and 13, found 11
```

Any suggestions here?  Thank you very much!

**Comment by boydkelly** [comment]
Ok all solved here.   It seems that yarn was causing the problem.  I removed yarn and reinstalled treesitter with npm and checkhealth is fine.   I'm still left with the question as to what the fedora tree-sitter package provides here.   Its a dependency of neovim, but is it being replace by npm?

**Comment by theHamsta** [comment]
Yarn and npm support global install. The binaries are not added to path automatically. You need to reinstall the yaml parser to get the new ABI

**Comment by boydkelly** [comment]
I did reinstall all the parsers.  But yarn v2 does not support global install.   ;)  See:  [yarn global install issue](https://github.com/yarnpkg/berry/issues/821)
This is what really led to my problems.  I ended up recreating my container etc. and doing headstands, before I finally figured out.

Anyway all is working fine now.

But I'm still trying to figure out the relationship and/or difference between the tree-sitter rpm and npm packages.   Without the npm package I will get the executable not found error although the Fedora treesitter package is installed.

**Comment by horseinthesky** [comment]
Manual install fails:
```
sudo npm install -g tree-sitter

> tree-sitter@0.19.0 install /usr/lib/node_modules/tree-sitter
> prebuild-install || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/13.14.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/tree-sitter/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/tree-sitter/.node-gyp'
gyp ERR! System Linux 4.19.104-microsoft-standard
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/tree-sitter
gyp ERR! node -v v13.14.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter@0.19.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tree-sitter@0.19.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-27T20_36_43_013Z-debug.log
```

**Comment by theHamsta** [comment]
@horseinthesky the system npm does usually not work with global installations. You probably also don't want to install npm packages as root. You can download download tree-sitter from here: https://github.com/tree-sitter/tree-sitter/releases or via `cargo install tree-sitter` or using brew, or `brew install npm`.

**Comment by boydkelly** [comment]
Another possibility is to install nvm.  It will install in your home and
you will not have this issue.

**Comment by horseinthesky** [comment]
@theHamsta @boydkelly 
I wonder why it even yells that there is no executable if it doesn't need it?! It was working perfectly fine severa days ago.

**Comment by theHamsta** [comment]
I will always report this in healthcheck when it's not there. However, you will only need it for some parsers that require `:TSInstallFromGrammar`

**Comment by aonoriaga** [comment]
u need install [tree-sitter-cli](https://github.com/tree-sitter/tree-sitter/blob/master/cli/README.md)

```bash
yarn global add tree-sitter-cli
```

**Comment by LeoniePhiline** [comment]
This is also true for `cargo` users:

`cargo install tree-sitter-cli` (instead of `cargo install tree-sitter`): https://github.com/tree-sitter/tree-sitter/tree/master/cli

**Comment by hopezh** [comment]
> This is also true for `cargo` users:
> 
> `cargo install tree-sitter-cli` (instead of `cargo install tree-sitter`): https://github.com/tree-sitter/tree-sitter/tree/master/cli

Thanks for the suggestion, which helped me got rid of that warning after I installed `rust+cargo` and then `tree-sitter-cli`.
