### ISSUE TITLE
Error when highlighting math directive in rst

### ISSUE THREAD

**Issue by elxy** [nvim-treesitter/nvim-treesitter#1104]
**Describe the bug**

When highlighting math directive in reStructuredText, neovim report an error:

```
treesitter/highlighter: Error executing lua: share/nvim/runtime/lua/vim/treesitter/highlighter.lua:212: attempt to index a nil value
```

**To Reproduce**

1. Install rst and latex parsers with :TSInstall
2. Open rst file with math directives
3. See error

**Expected behavior**

Math directives should be highlighted correctly with latex parser.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.4 (6dd41e2e45f8b4a00fda21f28bc0ebc6b172ffed) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found.

## Parser/Features H L F I
  - c              ✓ ✓ ✓ ✓ 
  - comment        ✓ . . . 
  - rst            ✓ ✓ . . 
  - query          ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ 
  - lua            ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . 
  - cpp            ✓ ✓ ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ 
  - latex          . . . . 
  - python         ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev+1177-g095f5da79
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az84-550

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**

rst file to reproduce this bug

```rst
test
====

.. math::

   \mathbf{x}( = \mathbf{x}(\alpha)) = \mathbf{x}'\alpha\mathbf{s}
```

**Comment by theHamsta** [comment]
There are currently no LaTeX highlights. This PR could fix this #1106

![image](https://user-images.githubusercontent.com/7189118/112644090-541ce700-8e45-11eb-9a8d-bf22568993ce.png)

**Comment by theHamsta** [comment]
@steelsojka but the other part of the issue (missing injection causes error) is upstream

**Comment by steelsojka** [comment]
@theHamsta well the language tree doesn't concern itself with the highlighting. That's handled a layer above in the highlighter. The highlighter is the one that needs to check that there are highlight queries for that language.

**Comment by theHamsta** [comment]
But there shouldn't be an error when executing the injection queries

**Comment by steelsojka** [comment]
@theHamsta Not as part of the injections. The language tree and injections is only concerned with the structure of the languages, not highlighting at that level. The highlighter is the one that gets the queries for the language. That is what is throwing the error. The language tree is intentionally decoupled from the highlighter.

**Comment by steelsojka** [comment]
This PR should fix it https://github.com/neovim/neovim/pull/14218. I don't code in Rust, but if you want to build that branch and test it feel free ;) I'll try and get a reproducable scenario
