### ISSUE TITLE
Add sync option to TSInstall 

### ISSUE THREAD

**Issue by sheeaza** [nvim-treesitter/nvim-treesitter#111]
TSInstall runs asynchronous backend, but in headless install mode, it needs a way to exit when all installations are done.
`nvim --headless ' +TSInstall -sync all' +qa`
with `-sync` option or any other symbal to represent "synchronous" meaning, the `+qa` command will excute after `+TSInstall all` done

**Comment by vigoux** [comment]
@kyazdani42 , what do you think about that ?

**Comment by kyazdani42** [comment]
i'll fix that today.

**Comment by hyt589** [comment]
Hi, this is not mentioned in the doc. What's the correct way to install parsers synchronously? I tried `+"TSInstall -sync all" +qall` and it still exited before the installation is complete.

**Comment by stsewd** [comment]
> Hi, this is not mentioned in the doc. What's the correct way to install parsers synchronously? I tried `+"TSInstall -sync all" +qall` and it still exited before the installation is complete.

Hi, the command is called `TSInstallSync`, docs would be great it there aren't for this command
