### ISSUE TITLE
I'm having a problem when installing treesitter

### ISSUE THREAD

**Issue by briones-gabriel** [nvim-treesitter/nvim-treesitter#1110]
**Describe the bug**

When trying to install treesitter, there is an ABI version mismatch.

**To Reproduce**

1. Install neovim
2. Add treesitter with vim-plug
3. Install a language
4. Enable the highlight module

**Expected behavior**

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

1 health#nvim_treesitter#check                                                                                            
  2 ========================================================================                                                
  3 ## Installation                                                                                                         
  4   - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  5   - OK: `git` executable found.                                                                                         
  6   - OK: `cc` executable found.                                                                                          
  7                                                                                                                         
  8 ## Parser/Features H L F I                                                                                              
  9   - c              ✓ ✓ ✓ ✓                                                                                              
 10   - java           x x . x                                                                                              
 11                                                                                                                         
 12  Legend: H[ighlight], L[ocals], F[olds], I[ndents]                                                                      
 13          +) multiple parsers found, only one will be used                                                               
 14          x) errors found in the query, try to run :TSUpdate {lang}                                                      
 15                                                                                                                         
 16 The following errors have been detected:                                                                                
 17   - ERROR: java(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/gabriel/.vim/plugged/nvim-treesitter/parser/java.so: supported          between 9 and 12, found 13
 18   - ERROR: java(locals): /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/gabriel/.vim/plugged/nvim-treesitter/parser/java.so: supported              between 9 and 12, found 13
 19   - ERROR: java(indents): /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/gabriel/.vim/plugged/nvim-treesitter/parser/java.so: supported             between 9 and 12, found 13

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-XQMmDy/neovim-0.5.0+ubuntu2+git202103262338-f0ace6d41-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-XQMmDy/neovim-0.5.0+ubuntu2+git202103262338-f0ace6d41-d569569c9/build/config -I/build/neovim-XQMmDy/neovim-0.5.0+ubuntu2+git202103262338-f0ace6d41-d569569c9/src -I/build/neovim-XQMmDy/neovim-0.5.0+ubuntu2+git202103262338-f0ace6d41-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-XQMmDy/neovim-0.5.0+ubuntu2+git202103262338-f0ace6d41-d569569c9/build/src/nvim/auto -I/build/neovim-XQMmDy/neovim-0.5.0+ubuntu2+git202103262338-f0ace6d41-d569569c9/build/include
Compiled by buildd@lgw01-amd64-029

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Comment by theHamsta** [comment]
You need a  version of Neovim built with a newer version of the tree-sitter runtime. Since the build date seems to be fairly recent, did you check whether you did a clean built and that cmake fetch the newer version of tree-sitter. You can check in you code base whether you already have ABI 13 in tree-sitter.h or still 12 as your error messages indicate.

**Comment by przepompownia** [comment]
I do not understand the message shown by `checkhealth`. Assuming
```
Neovim was compiled with tree-sitter runtime ABI version 12.
```
and
```
  - ERROR: php(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/user/.vim/pack/bundle/opt/nvim-treesitter/parser/php.so: supported between 9 and 12, found 13
```
I don't know where `13` was found. Please precise this message to give the user knowledge what part require to change ABI version to be compatible with the rest.

**Comment by theHamsta** [comment]
> Neovim was compiled with tree-sitter runtime ABI version 12.

You need ABI 13.

The problem is that the parser was compiled for 13 but your ABI supports only from 9 to 12.

**Comment by briones-gabriel** [comment]
Do you think that can be a problem related to the stated above with my Ubuntu version?

**Comment by przepompownia** [comment]
Thanks for trying to explain (and the new commit in #1123). I am still confused how much part we have to match against ABI version. 

W have built-in tree-sitter runtime in Neovim (I suspect it is reported as Neovim ABI version and https://github.com/neovim/neovim/issues/14261 is related to upgrade this version).

Each compiled parser (like `php.so`) is built against its own ABI version. I am not sure if it is 13 in my example.

Is there another part to check? Does the range `9-12` come from the built-in runtime?

**Comment by theHamsta** [comment]
> Does the range 9-12 come from the built-in runtime?

yes.

> Each compiled parser (like php.so) is built against its own ABI version. I am not sure if it is 13 in my example.

When downloading the parser the parser has been already generated for a specific ABI version. We choose parsers that are compatible with the tree-sitter runtime that the official Neovim is currently using.

I would not use PPAs. They install with root privileges and can affect your system's package system by introducing new or conflicting deb-package versions. You can install Neovim in userspace with AppImage or homebrew or in a containerized environment like snap.
```
sudo snap install nvim --edge --classic
```

**Comment by przepompownia** [comment]
As long as (about 6 years?) I use daily builds from PPA, I do not have problems with package chaos between Debian repositories. Building Neovim from source can be some (although problematic) solution before getting working version from PPA. I would like to take a look at Snap before using it (at the moment, for example it is not clear for me what Snap packages can contain any non-free part).

**Comment by theHamsta** [comment]
Yes, there can be very good PPA maintainers. Then, you'll never have problems. You could for now download the AppImage from Neovim's github page or use snap until the PPA fixes the issue.

**Comment by silmeth** [comment]
I managed to work around this problem (at least with `rust` parser, I still have problems with the `kotlin` one) by downloading and building manually older version of parser, generated with older version of tree-sitter.

I downloaded the [`rust-tree-sitter` 0.17.0](https://github.com/tree-sitter/tree-sitter-rust/releases/tag/v0.17.0) release, unpacked it, and compiled using

```
gcc src/parser.c src/scanner.c -o ~/.local/share/nvim/site/plugged/nvim-treesitter/parser/rust.so -I src/ -shared -O3
```

and it seems to be working. I guess I won’t update the parser unless the PPA nvim build is fixed. But that’s a problematic approach as you need to manually download a working older version of the tree-sitter parser and build it – a process that might also be different for other parsers (though you can look at `lua/nvim-treesitter/parsers.lua` in this package for some hints regarding where the parsers are downloaded from and which files are used when building).

**Comment by theHamsta** [comment]
It will also work when you have an old tree-sitter CLI and use :InstallFromGrammar

**Comment by silmeth** [comment]
Yup! That works too, installed older tree-sitter with:

```
cargo install tree-sitter-cli --git ssh://git@github.com/tree-sitter/tree-sitter.git --tag v0.18.3
```

(unfortunately had to install from git – there have been no new versions of `tree-sitter-cli` published on crates.io for the last 2 years)

and then installed parsers with `:TSInstallFromGrammar kotlin` and the same for `rust` and `json` and they all seem to be working fine.

**Comment by briones-gabriel** [comment]
After installing "cargo" and trying to install the tree-sitter-cli I'm promted with this authentication error message:

```
tree-sitter.git --tag v0.18.3
    Updating git repository `ssh://git@github.com/tree-sitter/tree-sitter.git`
error: failed to fetch into: /home/gabriel/.cargo/git/db/tree-sitter-fcb9d42cef252e49

Caused by:
  failed to authenticate when downloading repository

  * attempted ssh-agent authentication, but no usernames succeeded: `git`

  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  no authentication available
```

Do you know how to solve it?

**Comment by silmeth** [comment]
Oh, I used an ssh repo URL – that requires you to have SSH key configured in GitHub. But no need for that in a public repo, you can just do this with https URL:

```
cargo install tree-sitter-cli --git https://github.com/tree-sitter/tree-sitter.git --tag v0.18.3
```

instead

**Comment by briones-gabriel** [comment]
Thank you, that solved my problem! I really appreciate all the help from you guys!

**Comment by przepompownia** [comment]
On Neovim from the fresh AppImage there is no ABI mismatch. Thanks @theHamsta :tada: 

Some hints (both those concerning adjusting from the nvim and parsers side) from there would be included in README as long as this problem is expected to return frequently.

**Comment by theHamsta** [comment]
@przepompownia We don't expect this problem to happen again, since we can simply start a new subsection of our lockfile when a new ABI version comes out and just choose the right one for that user. I was thinking whether we should this on the last update. But then I was like "everyone's on nightly and expected to follow the master and they will have the new version within one week. No reason to maintain compatibility with an unreleased version. Let's break stuff!". Would decide differently now...

**Comment by silmeth** [comment]
> No reason to maintain compatibility with an unreleased version. Let's break stuff!". Would decide differently now..

I think that’s generally fine (I was ready to have and solve problems when installed unstable version from an external source ;-)) but having some sort of FAQ explaining those problems to be able to diagnose them and work-around them easier. :)

But with all the pieces stabilizing soon, perhaps it’s not worth writing it now.

**Comment by mattsacks** [comment]
Sorry, I'm still a bit lost on how to solve this since I now continually get this error after running `:PlugUpdate`.

Reinstalling latest Neovim from `master` (`brew reinstall neovim`) did not include any latest ABI for treesitter. Will Neovim be coming out with an updated release or are we to start using the CLI with `:TSInstallFromGrammer` for now?

**Comment by theHamsta** [comment]
@mattsacks  you could just remove the `:TSUpdate` from your update command. 

brew ships with newest tree-sitter. Proof: our CI. You probably need to install with --HEAD and also update the tree-sitter package.

**Comment by mattsacks** [comment]
@theHamsta thanks for getting back to me!

I might be missing something here but when you say:

> _brew ships with the newest tree-sitter_

Are you talking about Neovim or the `tree-sitter` package? Regardless, I've install both from `--HEAD` and am still running into ABI mismatch issues with the `typescript` lsp.

```sh
❯ nvim --version
NVIM v0.5.0-dev+cee19696b

❯ tree-sitter --version
tree-sitter 0.19.4 (234bd795918660ca36924c1f10282dcf351eb819)
```

Just let me know if I'm missing something or there's anything else I can help debug!
