### ISSUE TITLE
handlebarsjs support 🚀

### ISSUE THREAD

**Issue by ziulev** [nvim-treesitter/nvim-treesitter#1113]
Would love to see https://handlebarsjs.com/ support 🚀

**Comment by theHamsta** [comment]
Isn't that the same as this: https://github.com/alexlafroscia/tree-sitter-glimmer We have this already integrated. Can't really tell because I don't know all of this small languages. But I read handlebars somewhere...

**Comment by elianiva** [comment]
the name is *a bit* misleading if someone don't go to the repo and read the readme

**Comment by theHamsta** [comment]
The readme does not too much either. There is toouch languages that I've never heard of. @ziulev is this the language you're looking for?

**Comment by elianiva** [comment]
`.hbs` extension is also used for handlebars. I believe Glimmer is specific to Ember.js and it supports a subset of handlebars syntax. I haven't tried the parser myself though, might be completely wrong.

**Comment by ziulev** [comment]
Actually, I would like to use [this plugin](https://github.com/windwp/nvim-ts-autotag/issues/13).

> The readme does not too much either. There is toouch languages that I've never heard of. @ziulev is this the language you're looking for?

Yes, it looks like it is.
