### ISSUE TITLE
Custom query for folding in python

### ISSUE THREAD

**Issue by argapost** [nvim-treesitter/nvim-treesitter#1114]
Hello everyone,

I want to make a custom folding query in python with the marker "# %%" like in the example below:
![fold1](https://user-images.githubusercontent.com/58076098/112992110-2c40c280-9168-11eb-9074-0545564b8b76.png)
should become:
![fold2](https://user-images.githubusercontent.com/58076098/112992118-2e0a8600-9168-11eb-88d6-73b34a52261d.png)

I tried defining this query in order to take the whole script through the module and remove the lines that start with "# %%" but it didn't work.

```
(
(module) @test
(#not-match? @test "(^# %%)")
) @fold
```

I know it can be done with regular vimscript like this:
```
" Custom Folding for python
function! BlockFolds()
 let thisline = getline(v:lnum)
 if match(thisline, '# %%') >= 0
    return ">1"
 else
    return "="
 endif
endfunction

autocmd BufEnter *.py set foldmethod=expr
autocmd BufEnter *.py set foldexpr=BlockFolds()
```

But if the python script is too long >1000lines, then neovim becomes laggy even for scrolling, insert text etc. I guess because this function has to be constantly evaluated for every line in the code.

I am no expert so if you could help me with how my query should look like in order to achieve this behaviour I would be grateful.

Thank you in advance.

**Comment by theHamsta** [comment]
Python is the only language that uses this "fold the second line"-approach. @stsewd wanted to make this configurable

**Comment by theHamsta** [comment]
Oops, I miss-interpreted the image. I fear what you want is not possible with the current folding implementation because you don't specify the start nodes of folding but the node that should define start and end. Everything that you want to fold must be a single node.

```
I tried defining this query in order to take the whole script through the module and remove the lines that start with "# %%" but it didn't work.

(
(module) @test
(#not-match? @test "(^# %%)")
) @fold
```

**Comment by argapost** [comment]
Ok I see, and I guess there isn't a way to define a node as everything between the two lines starting with # %% right?

**Comment by theHamsta** [comment]
No, a node is already defined by the parser. Though you could force something like this in the first place, there is nothing that tree-sitter helps you with that (except maybe detecting the comment).

**Comment by argapost** [comment]
Ok, thank you for your comments!

**Comment by theHamsta** [comment]
I fear tree-sitter is not the right technology for your problem (except maybe for finding the comment, but you can do this also with regexes). Have you thought about writing your function is Lua?

You could use tree-sitter to reduce the regexes though:
```
(
(comment) @test
(#match? @test "(^# %%)")
)
```


. Anyways this is not really an issue without our plugin right?

**Comment by argapost** [comment]
Yeah  thanks I ll give it a try. I ll close this issue.

**Comment by ja-mf** [comment]
@argapost I am trying to achieve the same, did you figure out if it is possible to do it with nvim-treesitter? I've seen some solutions adding a provider to nvim-ufo (see https://github.com/kiyoon/jupynium.nvim/pull/88) though it needs more code.
Happy to help you in achieving this if you havent already (with or without treesitter), my email is in my profile if you wanna chat.

Thanks!! 
Juan.
