### ISSUE TITLE
Highlighting requires I leave file and open again.

### ISSUE THREAD

**Issue by doggo-rules** [nvim-treesitter/nvim-treesitter#1124]
**Describe the bug**

I open a file and there is no highlighting (so far tested with Javascript and C). I run `:TSEnableAll highlight` and I wait (so far only waited 5 minutes at most) but nothing happens. I use NERDTree to get to another file and go back to the file that had no highlighting at first and it has the highlighting.

**To Reproduce**

1. Open a file
2. Run `:TSEnableAll highlight`
3. Wait a while and watch the highlighting not work
4. Switch to another file
5. See the highlighting appear when you go to the original file

**Expected behavior**

I expected for the highlighting to appear without the need of switching files.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check                                                                      3 ========================================================================                          4 ## Installation                                                                                   - WARNING: `tree-sitter` executable not found (parser generator, only needed for :                  TSInstallFromGrammar, not required for :TSInstall)
- OK: `git` executable found.
- OK: `cc` executable found.
 
Neovim was compiled with tree-sitter runtime ABI version 13.

## Parser/Features H L F I
 - c              ✓ ✓ ✓ ✓ 
 - javascript     ✓ ✓ ✓ ✓ 

Legend: H[ighlight], L[ocals], F[olds], I[ndents]
          +) multiple parsers found, only one will be used
          x) errors found in the query, try to run :TSUpdate {lang}
</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev+1197-ga17782042
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az204-460

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**

Might be something wrong with my extensions, gonna share them just in case:
```vim
call plug#begin()
  Plug 'preservim/nerdtree' " File Explorer
    Plug 'Xuyuanp/nerdtree-git-plugin' " NERDTree Git Status
    Plug 'ryanoasis/vim-devicons' " Fancy Icons for NERDTree
  
  Plug 'mattn/emmet-vim' " HTML Emmets
  
  Plug 'metakirby5/codi.vim' " Scratchpad

  Plug 'liuchengxu/vim-which-key' " Shows Which Key to Press

  Plug 'vim-airline/vim-airline' " Airline Status Bar

  Plug 'neoclide/coc.nvim', {'branch': 'release'} " COC for Autocompletion

  Plug 'arcticicestudio/nord-vim' " Theme

  Plug 'mg979/vim-visual-multi', {'branch': 'master'} " Multiple Cursors

  Plug 'nvim-treesitter/nvim-treesitter' " Treesitter
call plug#end()
```

**Comment by theHamsta** [comment]
Strange... `:e!` works though...

**Comment by steelsojka** [comment]
Did you call the `setup` function for nvim-treesitter?

**Comment by theHamsta** [comment]
@steelsojka you can reproduce it with  `:TSDisableAll highlight` `:TSEnableAll highlight` `:e!`

**Comment by luanguimaraesla** [comment]
The same problem here, though `:e!` works.

**Comment by rmagatti** [comment]
Seems like I'm running into this too, haven't quite been able to pinpoint when this started happening

**Comment by ruanyouxing** [comment]
same problem here, although I didn't lazy-load treesitter but there's no highlight when I open the file
