### ISSUE TITLE
markdown_fenced_languages no longer correctly highlights typescript

### ISSUE THREAD

**Issue by David-Else** [nvim-treesitter/nvim-treesitter#1126]
In my `init.vim` I have:
```
let g:markdown_fenced_languages = ['bash=sh', 'javascript', 'js=javascript', 'json=javascript', 'typescript', 'ts=typescript', 'php', 'html', 'css', 'rust']
```
Since installing treesitter typescript is no longer highlighted accurately in a markdown file:

`example.md` NOTE the same error happens using `ts` or `typescript`
```ts
#### Using the Test Runner

The most basic syntax is `deno test`. This will run all files in the working directory that end in `_test` or `.test` with the extension `.js`, `.ts`, `.jsx`, or `.tsx`.

`example_test.ts`
```ts
import { assertEquals } from "https://deno.land/std/testing/asserts.ts";

Deno.test({
  name: "testing example",
  fn(): void {
    assertEquals("world", "world");
    assertEquals({ hello: "world" }, { hello: "world" });
  },
});
```

```
```
It looks like this:
![Screenshot from 2021-04-01 20-28-56](https://user-images.githubusercontent.com/12832280/113344600-3100a480-9329-11eb-84e7-ac45689bae83.png)

but the TypeScript is meant to look like this:
![Screenshot from 2021-04-01 20-29-59](https://user-images.githubusercontent.com/12832280/113344629-3bbb3980-9329-11eb-823a-8e74f0ac785d.png)

**To Reproduce**

(maybe use this color scheme if needed https://github.com/ChristianChiarulli/nvcode-color-schemes.vim/blob/master/colors/nvcode.vim)
1. Set `markdown_fenced_languages` to typescript as per my example above
2. Look at my test file as a markdown document

**Expected behavior**

Correct highlighting as per the screenshot

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `git` executable found.
  - OK: `cc` executable found.

## Parser/Features H L F I
  - css            ✓ . ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ 
  - jsonc          ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . 
  - html           ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
</code>
</details>

**Output of `nvim --version`**

<details>
<code>
NVIM v0.5.0-dev+1191-gf89bfa686
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az36-625

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**

I have not tested other languages

**Comment by theHamsta** [comment]
But it will use vim regex highlighting for fenced languages. This will look different from tree-sitter highlighting.

If you're brave enough you might re-enable tree-sitter markdown https://github.com/nvim-treesitter/nvim-treesitter/blob/9b5e82ff9d8c14deaefb2e703eb518da5d3995fb/lua/nvim-treesitter/parsers.lua#L291 But be aware that it causes SEGFAULTs

**Comment by David-Else** [comment]
@theHamsta Thanks for the info! Do you know if this will be fixed for the big `0.5` release?

**Comment by theHamsta** [comment]
But none of those commits seems to be related to the SEGFAULTs. As long as the parser does not pass some fuzzing tests it will not be included.

**Comment by steelsojka** [comment]
Also, with the current queries `ts` won't match typescript. We need to be able to configure the language through a directive (waiting for merge) in order to allow more robust language matching.

**Comment by stsewd** [comment]
Closing this in favor of https://github.com/nvim-treesitter/nvim-treesitter/issues/872
