### ISSUE TITLE
tree-sitter-zig not being able to find query bugs

### ISSUE THREAD

**Issue by Himujjal** [nvim-treesitter/nvim-treesitter#1128]
**Describe the bug**

Not able to find out query errors. There are query errors showing up. But unfortunately I am not able to find them. Can you help me out. Here's the repo: https://github.com/Himujjal/tree-sitter-zig

**To Reproduce**

1.
```sh
cd ~
git clone https://github.com/Himujjal/tree-sitter-zig
```
1. Add the following to your config:
```lua
require("nvim-treesitter.parsers").zig = {
  install_info = {
    url = "/home/<username>/tree-sitter-zig",
    files = {"src/parser.c"}
  },
  filetype = "zig"
}
```
2. Run `:TSInstallFromGrammar zig`
3. `ln -s ~/tree-sitter-zig/queries/highlights.scm ~/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/zig/highlights.scm`

**Expected behavior**
```sh
treesitter/highligher: Error executing lua: ..u/.local/share/nvim/runtime/lua/vim/treesitter/query.lua:104: query: invalid node type at position 4163
```

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

</code>
</details>

  - zig            x ✓ ✓ ✓

<details>
<code>

Paste the output here

</code>
</details>

**Additional context**

I did try the `:TSInstall query` and did try to debug the queries using https://github.com/nvim-treesitter/playground#query-linter. Could not find the error

Anyways. you guys who are familiar with the grammars and queries stuff might do it in a few minutes which I probably am missing. Spent over 2-3 hours on this. I give up. Please make a pull request to the attached repo for update.

**Comment by theHamsta** [comment]
Your query file must be in a magical `queries/zig/` folder so that the query linter knows it's for the zig parser

![image](https://user-images.githubusercontent.com/7189118/113353676-551ab080-933e-11eb-8946-e3d1222327a7.png)

**Comment by theHamsta** [comment]
Maybe one could add the heuristic that in `tree-sitter-XXX/queries/*.scm` it will guesstimate language XXX?

**Comment by Himujjal** [comment]
I am not getting the `Types` error!

**Comment by theHamsta** [comment]
Maybe a copy and paste error. `highlights.scm` passes on my machine also.

> In fact, the whole linter is working as I can fell the slowness!

The linter was fast before 0.19.X made loading queries unbearably slow (I changed the linter events to `BufWrite` only)

**Comment by theHamsta** [comment]
Are you sure you're installing a local version of the zig parser and not the old version from lockfile?

**Comment by Himujjal** [comment]
> Are you sure you're installing a local version of the zig parser and not the old version from lockfile?

How do I check this? I am sure that `downloading [0/1]` doesn't come up when I do `TSInstallFromGrammar zig`

Here's my config:

```lua
local parser_config = require("nvim-treesitter.parsers").get_parser_configs()

parser_config.zig = {
  install_info = {
    url = "/home/himu/my_code/zig/projects/tree-sitter-zig",
    files = {"src/parser.c"}
  },
  filetype = "zig"
}
```

**Comment by theHamsta** [comment]
When there is no downloading it's using the older version (can use a `:Uninstall` to be super safe)

**Comment by Himujjal** [comment]
> Maybe a copy and paste error. `highlights.scm` passes on my machine also.
> 
> > In fact, the whole linter is working as I can fell the slowness!
> 
> The linter was fast before 0.19.X made loading queries unbearably slow (I changed the linter events to `BufWrite` only)

I am not complaining about the slow thing. lol. I was indicating it was working.

Copy paste error should not occur. I did create `queries/zig` folder and added `highlights.scm` folder. There are still no errors showing up in the `highlights.scm` but when opening `*.zig` file i see the errors

**Comment by theHamsta** [comment]
Those errors might also come from indents/locals/ etc.

**Comment by theHamsta** [comment]
```
          operator: binary_operator [69, 11] - [69, 16]
          right: payload_expression [69, 17] - [71, 9]
            payload [69, 17] - [69, 22]
              values: payload_identifier [69, 18] - [69, 21]
            block [69, 23] - [71, 9]
```
`payload_identifier` could be a `@definition.var`
```
        }) catch |err| {
            std.debug.print("Failed to send show message notification (error: {}).", .{err});
        };
```

**Comment by Himujjal** [comment]
Are you on discord? Really I don't understand what's happening.

**Comment by Himujjal** [comment]
Any ideas what should be done?

**Comment by Himujjal** [comment]
![image](https://user-images.githubusercontent.com/18563948/113360025-9de65f80-9366-11eb-8ae1-8ede75ca91f5.png)

**Comment by Himujjal** [comment]
Solved this issue. Sorry for wasting your time! There was some issue with my config. runtime path was different!
