### ISSUE TITLE
Highlight breaks after retab and shows error.

### ISSUE THREAD

**Issue by dcordb** [nvim-treesitter/nvim-treesitter#1130]
**Describe the bug**

Applying `retab` on a python code that is tab indented breaks highlight of treesitter.

Also if after this the code is edited you get the following error:
`treesitter/highlighter: Error executing lua: ...im/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:224: col value outside range`

**To Reproduce**

1. Use the following code:

```
class Test:
	def __init__(self):
		pass

	def fun(self, x):
		print(x)
```
2. Use the following minimal `init.vim`:

```
" Note change here the path to your plugins directory
call plug#begin('~/.config/nvim/plugged')
    Plug 'nvim-treesitter/nvim-treesitter'
call plug#end()

lua <<EOF
require'nvim-treesitter.configs'.setup {
    ensure_installed = { "python" },

    highlight = {
      enable = true,
    },
}
EOF
```

3. Do `:retab`.
4. The highlight breaks.

**Expected behavior**

The highlight shouldn't break and there should not be an error after editing the code.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>
health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v15.11.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found.

## Parser/Features H L F I
  - latex          ✓ . ✓ . 
  - python         ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
</code>
</details>

**Output of `nvim --version`**

<details>
<code>
NVIM v0.5.0-dev+b79596e
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/dcordb/projects/neovim/build/config -I/home/dcordb/projects/neovim/src -I/home/dcordb/projects/neovim/.deps/usr/include -I/usr/include -I/home/dcordb/projects/neovim/build/src/nvim/auto -I/home/dcordb/projects/neovim/build/include
Compiled by dcordb@daniel-pc

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/dcordb/.neovim/share/nvim"

Run :checkhealth for more info
</details>
</code>

**Comment by vigoux** [comment]
This looks like a buffer update to me, glad we got that one, thanks for reporting.

**Comment by chentau** [comment]
@dcordb  Can you please try this PR from neovim to see if this fixes it? https://github.com/neovim/neovim/pull/14278

Sorry to undercut you @vigoux

**Comment by dcordb** [comment]
@chentau yes I built neovim from that PR and it works!
