### ISSUE TITLE
delete keyword is not highlighted

### ISSUE THREAD

**Issue by Mechap** [nvim-treesitter/nvim-treesitter#1145]
**Describe the bug**

The delete keyword is not highlighted.

**To Reproduce**

TSInstall cpp

create a new file
copy this code
![image](https://user-images.githubusercontent.com/54742369/113691148-6e1fba80-96cc-11eb-8295-0da3ade76bf1.png)

**Expected behavior**

delete should be highlighted since it's a keyword.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

## Parser/Features H L F I
  - cpp            ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**
<details>
NVIM v0.5.0-dev+1160-g0f7b6b2ef
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -IC:/projects/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compilé par runneradmin@fv-az152-366

Features: -acl +iconv +tui
See ":help feature-compile"

         fichier vimrc système : "$VIM\sysinit.vim"
               $VIM par défaut : "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info

</details>

**Comment by theHamsta** [comment]
Did you check with nvim-treesitter/playground and :TSHighlightgroupUnderCursor. Delete is highlighted as `@keyword.operator` https://github.com/nvim-treesitter/nvim-treesitter/blob/11e1db3ec29abb5711556085766cb6912814c6dc/queries/cpp/highlights.scm#L154

So it will appear in the same color as `=`. You can remap TSOperatorKeyword to TSKeyword to get the same highlight as non-operator keywords.

**Comment by Mechap** [comment]
Thank you very much.
