### ISSUE TITLE
`clang` not recognised even though it's on PATH

### ISSUE THREAD

**Issue by neelkarma** [nvim-treesitter/nvim-treesitter#1146]
**Describe the bug**

Even though the LLVM tools are on `PATH` and the `clang` executable is accessible from the command line, nvim-treesitter isn't recognising `clang`.

**To Reproduce**

1. Have Windows 10
2. Install Chocolatey
3. Run `choco install llvm` in an elevated command prompt
4. Restart
5. Go into `nvim` and run `:checkhealth`
6. See the problem:
```
  - ERROR: `cc` executable not found.
    - ADVICE:
      - Check that either gcc or clang is in your $PATH
```
**Expected behavior**

nvim-treesitter recognises the `clang` executable.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.4 (56c7c6b39d908c2df059e2c7f75860f819010671) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.16.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - ERROR: `cc` executable not found.
    - ADVICE:
      - Check that either gcc or clang is in your $PATH
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - python         ✓ ✓ ✓ ✓ 
  - jsonc          ✓ ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ 
  - dart           ✓ ✓ . ✓ 
  - json           ✓ ✓ ✓ ✓ 
  - jsdoc          ✓ . . . 
  - css            ✓ . ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ 
  - c_sharp        ✓ . . . 
  - html           ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
</code>
</details>

**Output of `nvim --version`**

<details>
<code>
NVIM v0.5.0-dev+1221-g9b2d4ff62
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -IC:/projects/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-77

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
</code>
</details>

**Additional context**

**Comment by theHamsta** [comment]
You you give us die error message when you do an TSInstallSync of a language. It will show which compiler executables it checked. Also try a :echo exepath("clang")

You can set the full path to the executable by setting a Lua config (see windows Wiki) or setting the CC env variable

**Comment by neelkarma** [comment]
That's the thing; there is no error message when I try `:TSInstallSync c`. `:echo exepath("clang")` gives me `C:\Program Files\LLVM\bin\clang.EXE`, which is expected. I also set the CC env variable to `clang` and I used
```lua
require('nvim-treesitter.install').compilers = {'clang'}
```
in my lua config. But still, `:checkhealth` thinks that `clang` doesn't exist.

**Comment by theHamsta** [comment]
Yes, @neelkarma checkhealth is indeed just too naive.

**Comment by neelkarma** [comment]
@theHamsta I can confirm that on your branch the issue has been fixed 👍 
```
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.4 (56c7c6b39d908c2df059e2c7f75860f819010671) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.16.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `clang` executable found. Selected from { "clang" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.
```
