### ISSUE TITLE
indent on new line is not working in typescript 

### ISSUE THREAD

**Issue by lourenci** [nvim-treesitter/nvim-treesitter#1147]
https://user-images.githubusercontent.com/2339362/113709593-10ce3e00-96b9-11eb-90fd-8a3d07600259.mov

**Comment by kyazdani42** [comment]
looks like you are using a plugin that moves the cursor for you, i cannot reproduce with default vim cursor movement.

**Comment by lourenci** [comment]
Is there some way I can help you to reproduce the issue? I'm using polyglot right now because of this.

**Comment by kyazdani42** [comment]
you could provide a minimal config which i can reproduce this issue with.

**Comment by lourenci** [comment]
It turns out [lexima](https://github.com/cohama/lexima.vim/issues/115) is breaking the indentation. Thanks.
