### ISSUE TITLE
An error is showing after undoing a substitute command.

### ISSUE THREAD

**Issue by dcordb** [nvim-treesitter/nvim-treesitter#1163]
**Describe the bug**

An error shows when executing a specific substitute command in neovim and undoing it. The error shown is the following:

```
treesitter/highlighter: Error executing lua: ...im/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:240: end_col value outside range
```

**To Reproduce**

I'm going to show how to reproduce it with a bash file, but it's happening with other languages too.

1. Use the following minimal init.vim configuration:

```
call plug#begin('~/.config/nvim/plugged')
    Plug 'nvim-treesitter/nvim-treesitter'
call plug#end()

lua <<EOF
require'nvim-treesitter.configs'.setup {
    ensure_installed = { "bash" },

    highlight = {
      enable = true,
    },
}
EOF
```

2. Create a .sh file, for example `test.sh` with the following content:

```
params="  "hello" "
```

3. Place the cursor on first line and execute the following substitute command:

```
s/"/\\"/cg
```
Note that this triggers confirmation, just enter `n, y, y, n` (ie. we want to replace inner `"` with `\"`).

4. Press `u` to undo the changes.
5. The mentioned error is shown.

**Expected behavior**

The error shouldn't show.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v15.11.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - typescript     ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . 
  - javascript     ✓ ✓ ✓ ✓ 
  - latex          ✓ . ✓ . 
  - c              ✓ ✓ ✓ ✓ 
  - jsonc          ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev+76f5c72
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/dcordb/projects/neovim/build/config -I/home/dcordb/projects/neovim/src -I/home/dcordb/projects/neovim/.deps/usr/include -I/usr/include -I/home/dcordb/projects/neovim/build/src/nvim/auto -I/home/dcordb/projects/neovim/build/include
Compiled by dcordb@daniel-pc

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/dcordb/.neovim/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Comment by chentau** [comment]
Should be foxed in neovim master. In the future, please post these issues to neovim instead of here :)
