### ISSUE TITLE
Add support for solidity

### ISSUE THREAD

**Issue by smarquez1** [nvim-treesitter/nvim-treesitter#1168]
**Language informations**

Would love to have Solidity support, it's the language created to write Ethereum contracts.
The language is takes many syntactical ideas from JavaScript.

I found an attempt to support it's grammar here: https://github.com/JoranHonig/tree-sitter-solidity but don't know how to test it.

Here's more info on how the author wrote it: https://joranhonig.nl/incremental-parsing-of-solidity/

Thanks for your effort @JoranHonig !

**Comment by theHamsta** [comment]
You can test it with nvim-treesitter/playground

Put this in your config
```lua
  -- *Must* be *S*olidity not solidity
  require "nvim-treesitter.parsers".get_parser_configs().Solidity = {
    install_info = {
      url = "https://github.com/JoranHonig/tree-sitter-solidity",
      files = {"src/parser.c"},
      requires_generate_from_grammar  = true,
    },
    filetype='solidity'
  }
```

Restart and run `:TSInstall Solidity`. You need to have the tree-sitter-cli installed. `tree-sitter` must executable.

Seems to work fine.

**Comment by smarquez1** [comment]
wow, thanks for the quick support @theHamsta ! Didn't know that, will test ASAP.

**Comment by weilbith** [comment]
How does it look? Good to merge? 🙃

**Comment by vigoux** [comment]
Not really sure, I think this was more intended as a quick hack to enable the support of solidity.
No PR open regarding this if I remember well.

**Comment by smarquez1** [comment]
Sorry guys, didn't have the time to check if this works correctly and/or create a PR and I'm not working on Solidity anymore. I think the issue could still be useful for people who want to add Solidity treesitter support for Neovim. Did you try it @weilbith ?

**Comment by smarquez1** [comment]
OK, I just tried it and it seems to be working properly after setting `set ft=solidity`.
The current status seems to be that the parser is working correctly (as you can see in the screenshot below) but the highlights are still not implemented, but that work is being done here: https://github.com/JoranHonig/tree-sitter-solidity/pull/12

![Captura de Pantalla 2021-06-07 a la(s) 19 00 08](https://user-images.githubusercontent.com/4602587/121060175-d31d8c80-c7b1-11eb-8e1e-a5e6ac16f617.png)

**Comment by JoranHonig** [comment]
Hey everyone!

With the help of @p13nty there are now highlights on the tree-sitter-solidity impl 🚀.

Let me know if it works 🙌

**Comment by ibhagwan** [comment]
> Hey everyone!
> 
> With the help of @p13nty there are now highlights on the tree-sitter-solidity impl rocket.
> 
> Let me know if it works raised_hands

Tysm @JoranHonig!

I'm still not getting highlights though, it's very possible I'm doing something wrong as I just started using nvim 0.5 with TS, I followed the instructions in this thread, compiled the Solidity parser, I can see it's loaded in the TS modules but for some reason the highlight feature still appears as missing.

Output from `:TSModuleInfo`:

![image](https://user-images.githubusercontent.com/59988195/123996324-110e6a80-d984-11eb-8298-239c5b12e59e.png)

Additional output from `:checkhealth`:

![image](https://user-images.githubusercontent.com/59988195/123996477-37340a80-d984-11eb-954f-6c502b81cd05.png)

**Comment by ibhagwan** [comment]
So I was able to make highlights work, the steps were as follows:

- Download [queries\highlights.scm](https://github.com/JoranHonig/tree-sitter-solidity/blob/master/queries/highlights.scm) into `~/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/solidity` (assuming `packer` as plugin manager):
```sh
curl -L https://raw.githubusercontent.com/JoranHonig/tree-sitter-solidity/master/queries/highlights.scm \
    -o ~/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/solidity/highlights.scm
```
- Edit the file and comment out lines 68-69, otherwise you'll get the error `treesitter/highlighter: Error executing lua: ...TDZW/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: error at position 1760` when opening a `.sol` file

Aside from lines 68-69 raising an exception there's also an issue with block comment highlighting, here's how it looks:

![image](https://user-images.githubusercontent.com/59988195/124047876-e8a95f00-d9c9-11eb-86eb-70e4df449e93.png)

Vs. how it should look (using [`tomlion/vim-solidity`](https://github.com/tomlion/vim-solidity) solidity syntax files:

![image](https://user-images.githubusercontent.com/59988195/124048004-3aea8000-d9ca-11eb-82c4-82370743343c.png)

**Comment by ibhagwan** [comment]
@JoranHonig, I was able to fix the block comment issue, copied the regex from [tree-sitter-c](https://github.com/tree-sitter/tree-sitter-c/blob/master/grammar.js#L965) and, created  [PR #14](https://github.com/JoranHonig/tree-sitter-solidity/pull/14).

**Comment by shalzz** [comment]
Hi,

Any update on this? I'm still not able to get highlighting working with this.
If highlighting works for someone, would appreciate if you could share the config here.

**Comment by vigoux** [comment]
Hi, for now solidity is not supported at all, we are waiting for someone to make a pull request adding solidity support (that is, adding it the the `parsers.lua` and adding the queries to `queries`) to make a move.

We are not solidity experts, so we need your help :wink:

**Comment by rxditay** [comment]
@shalzz , check this https://github.com/tomlion/vim-solidity
syntax highlighting works for me.

**Comment by clason** [comment]
Added to the tracking issue, so I'm closing this -- but feel free to use this issue for further discussion!
