### ISSUE TITLE
Syntax highlighting definitions for more capture groups: packages (for Go) and a way to debug syntax groups

### ISSUE THREAD

**Issue by aktau** [nvim-treesitter/nvim-treesitter#1170]
**Is your feature request related to a problem? Please describe.**

Currently, it appears that capture groups like:

 - `package_cloud`
 - `package_identifier`

Are not mapped in neither:

 - this repo: https://github.com/nvim-treesitter/nvim-treesitter/blob/de4fbe8e083518161b687c5d9f4d500367c8968a/lua/nvim-treesitter/highlight.lua
 - nor upstream: https://github.com/neovim/neovim/blob/82ac44d01f0e92546f43c804595c14a139af77bd/runtime/lua/vim/treesitter/highlighter.lua#L27

With my preferred theme (https://github.com/mhartington/oceanic-next/blob/5ef31a34204f84714885ae9036f66a626036c3dc/colors/OceanicNext.vim#L168, cc @mhartington), this causes 
strange results (see comparison below). I actually don't know where the blue color comes from, the default color should be "white".

**Describe the solution you'd like**

Either of:

 1. A way to debug highlight groups for tree-sitter based syntax higlighting. Tricks like https://stackoverflow.com/questions/9464844/how-to-get-group-name-of-highlighting-under-cursor-in-vim don't appear to work. For example, without tree-sitter, executing `SynStack()` on the `package` word outputs: `goDirective -> Statement`. It doesn't output anything when tree-sitter highlighting is enabled.
 2. Assigning these capture groups to some syntax highlight group.

**Additional context**

Without/With TS higlighting:

![image](https://user-images.githubusercontent.com/189413/114178946-ac241500-993e-11eb-850d-24823fe22156.png)![image](https://user-images.githubusercontent.com/189413/114179121-e2fa2b00-993e-11eb-98e8-faf5e4d11d75.png)

**Comment by theHamsta** [comment]
You can get the current highlights with : TSHighlightgroupUnderCursor of nvim-treesitter/playground

You can set custom_captures in the setup call of the highlights module.

The blue color comes from the Include highlight group. We use `@include` for the import keywords of all languages. You also do a language-specific overwrite by linking goTSInclude to something you like.

**Comment by theHamsta** [comment]
You can also create a file `after/queries/go/highlights.scm` with the following content

```scheme
"package" @MyHighlightGroupForPackage
(package_identifier) @MyHighlightGroupForPackageIdentifier
```
I don't thing we need another highlight group for this (or maybe we will have highlighting of imported names again). It is really easy to highlight it in your config and as short as adding a link for a highlight group.
