### ISSUE TITLE
C++ operator defintions do not allow spaces after `operator` keyword

### ISSUE THREAD

**Issue by Tinku10** [nvim-treesitter/nvim-treesitter#1177]
**Describe the bug**

I am writing C++ code and treesitter is highlighting similar groups differently. Here is a snapshot from my editor.

![ts](https://user-images.githubusercontent.com/29244595/114400465-9ec98d80-9bbf-11eb-8b39-6487ef1df2c9.png)

As you can see from the image

1. friend is highlighted with different colors in similar sections.
2. operator keyword in second line is green whereas it is violet in others.
3. bool keyword in two lines are green whereas in others it is yellow.

I don't know if this is a problem related to treesitter particularly. For your reference I am only using treesitter engine for highlighting. Previously I was using Vim Polyglot, but I deleted it. So this is not coming from polyglot I guess.

**Comment by theHamsta** [comment]
Could it be that you're affected by https://github.com/tree-sitter/tree-sitter-cpp/pull/72 ? The fix is available since a long time but has never been merged. It would be interesting what the parser actually gives us as a result (try https://nvim-treesitter/playground). When there are errors in the syntax tree the error can propagate to wrong highlighting. You can also use `:TSHighlightsUnderCursor` so see what highlight groups are applied in the different spots.

Do you have a highlight for `@variable` set?

**Comment by Tinku10** [comment]
@theHamsta Okay, let me see the issue and try what you told.

**Comment by theHamsta** [comment]
I personally find it very annoying that the `error` regions are highlighted bold. nvim-treesitter does not set a highlight for error. But due to a caching issue in upstream nvim we cannot overwrite it at the moment.

**Comment by Tinku10** [comment]
@theHamsta  I took a look at the highlight groups, here's what I got

1. The operator keyword which was wrongly highlighted in second line is detected as @variable as well as a @function.
2. The friend keyword in the second line is detected as @variable whereas it should have been @keyword.
3. The friend keyword in the third line is detected as @type.
4. The bool type in fourth and fifth line is detected as @variable as well as @function.
5. The bool type in third and last line is detected as @variable.

**Comment by theHamsta** [comment]
Can you paste the code here?

**Comment by Tinku10** [comment]
```cpp
#include<bits/stdc++.h>
using namespace std;

template <int MOD> struct Mint{
  static constexpr int mod = MOD;
  int value;

  Mint() : value(0) {}
  Mint(int64_t v_) : value((int64_t)(v_ % mod)) { if (value < 0) value += mod; }

  static int inv(int a, int m) {
    a%=m; assert(a);
    return a == 1?1:(int)(m-(int)(inv(m, a))*(int)(m)/a);
  }
  
  Mint inverse() const {
    Mint res; res.value = inv(value, mod);
    return res;
  }

  Mint power(Mint a, int b) const{
    Mint res = 1; while(b>0){ if(b&1) res *= a; a=(a*a); b>>=1;} return res;
  }

  friend std::istream &operator>>(std::istream &input, Mint &other){
    input >> other.value; return input; 
  }

  friend std::ostream &operator<<(std::ostream &out, const Mint &other){
    out << other.value; return out;
  }

  Mint operator- () const { return Mint(-value);}
  Mint operator+ () const { return Mint(*this); }

  Mint& operator ++ (){ value++;if (value==mod) value=0; return *this; }
  Mint& operator -- (){ if(value==0) value = mod; value--; return *this; }
  Mint& operator += (const Mint& o) { value = value+o.value; if(value>=mod) value-=mod; return *this; }
  Mint& operator -= (const Mint& o) { value = value-o.value; if(value<0) value+=mod; return *this; }
  Mint& operator *= (const Mint& o) { value = (int64_t)((int64_t)(value) * (int64_t)(o.value) % mod); return *this; }
  Mint& operator /= (const Mint& o) { return *this *= o.inverse(); }

  friend Mint operator ++ (Mint& a, int32_t) { Mint r = a; ++a; return r; }
  friend Mint operator -- (Mint& a, int32_t) { Mint r = a; --a; return r; }
  friend Mint operator + (const Mint& a, const Mint& b) { return Mint(a) += b; }
  friend Mint operator - (const Mint& a, const Mint& b) { return Mint(a) -= b; }
  friend Mint operator * (const Mint& a, const Mint& b) { return Mint(a) *= b; }
  friend Mint operator / (const Mint& a, const Mint& b) { return Mint(a) /= b; }

  friend bool operator == (const Mint& a, const Mint& b) { return a.value == b.value; }
  friend bool operator != (const Mint& a, const Mint& b) { return a.value != b.value; }
  friend bool operator < (const Mint& a, const Mint& b) { return a.value < b.value; }
  friend bool operator > (const Mint& a, const Mint& b) { return a.value > b.value; }
  friend bool operator <= (const Mint& a, const Mint& b) { return a.value <= b.value; }
  friend bool operator >= (const Mint& a, const Mint& b) { return a.value >= b.value; }
};

using mint = Mint<(int)1e9+7>;
int dp[501][3000][501];

void solve(){
}

int32_t main() {
  ios_base::sync_with_stdio(false);
  cin.tie(0);
```
Yes, removing the spaces did worked.

**Comment by theHamsta** [comment]
Maybe you can push a bit on that fix. But in the past it was ignored. Maybe we should fork the C++-parser...

**Comment by Tinku10** [comment]
Okay, thanks @theHamsta

**Comment by theHamsta** [comment]
@Tinku10 to bring this issue forward: Is your problem only related to the parser bug (upstream issue) or are there further issues in our plugin?

**Comment by Tinku10** [comment]
@theHamsta Right now I only got this issue, so I thought I should notify it. 
Is Neovim 0.5 going to use this treesitter implementation? 
And if I get further issues I'll notify it here. Most of the time right now, I'm working in C++, if this issue is there in other languages too, I'm not aware of it.
Thanks for your help!

**Comment by theHamsta** [comment]
@Tinku10 official tree-sitter support is moved to neovim 0.6. Tree-sitter will only be experimental in nvim 0.5. The issue you encountered is only tied to the specific case of spaces in the `operator` definition in C++ and could be easily fixed by merging the upstream PR. Other languages are not affected.

**Comment by Tinku10** [comment]
@theHamsta should I close the issue?

**Comment by vigoux** [comment]
Not sure, this is not the first time we encounter bugs with the C++ parser, so keeping this open would allow us to push changes in the C++ parser.

Forking the parser is also completely imaginable, but we would need to rebase it pretty often...

**Comment by Tinku10** [comment]
Okay then @vigoux, I'll keep this open.

**Comment by jdrouhard** [comment]
I went ahead and merged the PR that fixed this issue. Thanks to @calixteman for the actual fix. 

I have merge access to the cpp treesitter repo, now. If there are any other cpp parser bugs, make sure to mention me.

Not all bugs are actually fixable due to the nature of the c++ grammar (some things are simply impossible without actual compilation). Others are, like this one.
