### ISSUE TITLE
Highlighting of Lua Fields Applies to Any Identifier Inside {}

### ISSUE THREAD

**Issue by theHamsta** [nvim-treesitter/nvim-treesitter#1180]
**Language informations**

Any identifier that is a direct child of field gets highlighted as `Field`. I don't know whether this is intended or whether it should only apply to fields of type `{ field = value }` (so only to the lhs `field`).

It looks a bit strange when some of the identifiers get highlighted but not when you add a ` + 1` to it.
![image](https://user-images.githubusercontent.com/7189118/114548459-13ec9f80-9c60-11eb-94b1-81e5ebe95b60.png)

**Comment by vigoux** [comment]
Hmmm I think that's an issue with a badly written query...
