### ISSUE TITLE
Add vimscript/vimL support

### ISSUE THREAD

**Issue by reportaman** [nvim-treesitter/nvim-treesitter#1187]
**Language informations**

Add support for vimscript/vimL syntax coloring using nvim-treesitter.

**Comment by kyazdani42** [comment]
@vigoux started a viml parser but apparently was very hard to do because vimL is quite badly designed, not sure if he's gonna finish it :)

**Comment by vigoux** [comment]
There is indeed a VimL parser but it is lacking a lot of language features still, I'll try to resume work on it as soon as I can, and add support for VimL.
