### ISSUE TITLE
Fortran support

### ISSUE THREAD

**Issue by argapost** [nvim-treesitter/nvim-treesitter#1194]
Hello,

Is there any plan to add support for Fortran language?

I found this parser: https://github.com/OpenFortranProject/open-fortran-parser. But I haven't yet managed to make it work.

Thank you anyways!

**Comment by theHamsta** [comment]
The link is not a tree-sitter parser. One would have to use https://github.com/stadelmanma/tree-sitter-fortran. Just have a look how the other parsers are set up in `parsers.lua`. It should be straight forward to add `tree-sitter-fortran. You can test with https://github.com/nvim-treesitter/playground

**Comment by theHamsta** [comment]
@openkork did already some work to add queries. I'll create a PR for you to experiment with his queries.

**Comment by theHamsta** [comment]
Could you try https://github.com/nvim-treesitter/nvim-treesitter/pull/1196 You need tree-sitter CLI installed and in PATH (https://github.com/tree-sitter/tree-sitter/releases)

**Comment by argapost** [comment]
First of all thanks for the quick support.

I have the tree-sitter CLI, in nvim.packer can I checkout the pull request or I should wait for it to be merged?

**Comment by theHamsta** [comment]
> I have the tree-sitter CLI, in nvim.packer can I checkout the pull request or should I wait for it to be merged?

Depends on your patience ;-)

**Comment by argapost** [comment]
Ok, so I put this:
```
local parser_config = require"nvim-treesitter.parsers".get_parser_configs()
parser_config.fortran = {
    install_info = {
        url = "https://github.com/stadelmanma/tree-sitter-fortran",
        files = {"src/parser.c", "src/scanner.cc"},
        requires_generate_from_grammar = true
    }
}
```
in my init.lua and then did TSInstall fortran. I also put the queries in .local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/fortran.

The highlights are working, but the folds aren't. (not that I need them)

Here is a screenshot with tsplayground opened.

![image](https://user-images.githubusercontent.com/58076098/115124653-914b4380-9fc3-11eb-980c-611ee1e8d064.png)

**Comment by theHamsta** [comment]
Did you set foldexpr?

**Comment by argapost** [comment]
Nope, just did! sorry! Thank you very much everything is ok now.
