### ISSUE TITLE
Folding stopped working as of april 22

### ISSUE THREAD

**Issue by JoseConseco** [nvim-treesitter/nvim-treesitter#1226]
**Describe the bug**
Folding stopped working (only tested in python) since today update ( 22 april)
![image](https://user-images.githubusercontent.com/13521338/115781309-82490480-a3ba-11eb-98c4-92617b5c4c64.png)
In past if that happened I could use :e %   but now nothing works (in past folding sometimes failed if file was opened using telescope but :e % always helped).

**To Reproduce**
Just try to fold anything in python code (maybe other can confirm bug in other languages).

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.4 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v15.14.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - php            ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ 
  - zig            ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ 
  - regex          ✓ . . . 
  - tsx            ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ 
  - teal           ✓ ✓ ✓ ✓ 
  - r              ✓ ✓ . . 
  - vue            ✓ . ✓ . 
  - rst            ✓ ✓ . . 
  - json           ✓ ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ 
  - lua            ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ 
  - ql             ✓ ✓ . . 
  - bash           ✓ ✓ ✓ . 
  - go             ✓ ✓ ✓ ✓ 
  - nix            ✓ ✓ ✓ . 
  - jsonc          ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ 
  - c_sharp        ✓ . . . 
  - dart           ✓ ✓ . ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}  

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev+1267-g7bf62ab02
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

</code>
</details>

**Additional context**

**Comment by shadmansaleh** [comment]
I'll add folding by default works but doesn't work when fold query is overwritten by user . The tittle is a bit missleading :)

**Comment by theHamsta** [comment]
@shadmansaleh no, it does not work at all for me. When it works it also works to when overriding the query.

**Comment by shadmansaleh** [comment]
> @shadmansaleh no, it does not work at all for me. When it works it also works to when overriding the query.

Strange it works for me in default setup . Just tested on python .

**Comment by JoseConseco** [comment]
This is the last comit that works for me:
![image](https://user-images.githubusercontent.com/13521338/115795975-3a81a780-a3d1-11eb-80b0-c178317c7fd0.png)
Next update (**always fold more than one**)  41ed83ffc762b611644a311e344b33d5efc01944 broke folding alt least at my end on python and lua (probably other too) ... I removed any custom autolaod python.el  (overriding default folds did not work for me anyway, so I had to edit main queries/python/folds.scm - from the plugin)

**Comment by shadmansaleh** [comment]
> Strange it works for me in default setup . Just tested on python .Same result in lua.

Ok it seems I was in a slightly older commit 🤦‍♂️

**Comment by vigoux** [comment]
Wops, then I broke something!
I'll dig into that later today then!

**Comment by stsewd** [comment]
oops, I reviewed that PR, I didn't test it locally the change made sense to me p:

**Comment by Gelio** [comment]
@JoseConseco Thanks for a detailed bisect of which commit could be responsible for breaking the folding 👍 It helped me (most likely) fix it in #1234

**Comment by JoseConseco** [comment]
nie ma problemu
