### ISSUE TITLE
Can it add support to a synchronized cooperative work with luochen1990/rainbow ?

### ISSUE THREAD

**Issue by cogig** [nvim-treesitter/nvim-treesitter#123]
**Is your feature request related to a problem? Please describe.**
When i installed [rainbow](https://github.com/luochen1990/rainbow) and nvim-treesitter, i found that the parentheses don't show different levels of parentheses in different colors.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vigoux** [comment]
Hehe, not sure how we are supposed to do that. I have some question (that should have been aswered in the template but nvm...):
How is it working now ?
How should it be working ?

**Comment by cogig** [comment]
![rainbow](https://user-images.githubusercontent.com/45864384/86006557-b973b100-ba48-11ea-8988-572424e0a296.png)

**Comment by cogig** [comment]
![rainbow2](https://user-images.githubusercontent.com/45864384/86007445-fbe9bd80-ba49-11ea-8fdc-40de4712c6dc.png)
If only installing rainbow, the work state looks like this.

**Comment by kyazdani42** [comment]
because the treesitter highlighter disables the `syntax` option in vim, which is important to avoid conflicts like this. Basically, this would require changes inside neovim or somehow implement this feature using a manual highlighter like in the treesitter highlighter.

**Comment by theHamsta** [comment]
Yes, just deactivate highlight of `TSPunctBracket`

```
highlight link TSPunctBracket Normal 
```
I am using a similar plugin.

**Comment by vigoux** [comment]
@cogig, did the comment above solved you issue ?

**Comment by cogig** [comment]
The scheme works well for me. Thank you.

**Comment by dchromejko** [comment]
The following worked for me to restore the highlighting with 'junegunn/rainbow_parentheses.vim':

```lua
require "nvim-treesitter.highlight"                                              
local hlmap = vim.treesitter.highlighter.hl_map                                  
hlmap["punctuation.bracket"] = nil
```

`TSHighlighter` is nil and setting up `hlmap.error` resulted in some strange highlights throughout the code. Setting up `highlight link TSPunctBracket Normal` did not work.

**Comment by jackcogdill** [comment]
It seems that after 1baf751fb0b03015c4c9883a87923cc4a7a4812e the above fix no longer works.

Now I'm using the following:

```vim
autocmd vimrc BufEnter * hi clear TSPunctBracket
```
