### ISSUE TITLE
Line completion

### ISSUE THREAD

**Issue by kuator** [nvim-treesitter/nvim-treesitter#1260]
Vim has line completion which can be triggered by `<c-x><c-l>`. The problem is the line can be split into several lines, and vim inserts the first half of the line.
Example is here:
![image](https://user-images.githubusercontent.com/25168308/116372173-fa398380-a82d-11eb-9dc7-bb4e7bfcf26e.png)
I think it would be nice if it completed "sentences" rather than lines.

**Comment by theHamsta** [comment]
I think there are already enough completion frameworks also with tree-sitter integration. I guess you should ask one of them to implement the feature as a completion source. Maybe nvim-treesitter-textobjects can add a helper function to list the current statements in a buffer.

**Comment by kuator** [comment]
Thanks! I use nvim-compe, I will ask it's creator if it's possible to implement this in compe

**Comment by theHamsta** [comment]
Compe is mostly handling automatic completion. If you want a special case of manually triggered completion it could be a good fit for the textobject module. I'll have a look into it
