### ISSUE TITLE
Add support for fish

### ISSUE THREAD

**Issue by ram02z** [nvim-treesitter/nvim-treesitter#1268]
**Language informations**

The only remaining language for me that doesn't have a treesitter parser is fish. I found a treesitter project for fish here:
https://github.com/krnik/tree-sitter-fish

However, it just gives me errors and I am not knowledgeable enough about treesitter to be able to understand why. I have created a seperate issue on the respective repository.

**Comment by theHamsta** [comment]
Can you try #1269 ? You can see the parsed tree with nvim-treesitter/playground

**Comment by ram02z** [comment]
@theHamsta Seems to work fine.  However, the parser seems to be missing many of the features like highlighting.
I am new to treesitter, so I am not sure what is required for highlighting to work. Could you please guide me so I can create an issue on the fish parser's repo?

> TSModuleInfo

![image](https://user-images.githubusercontent.com/59267627/116787008-9dda9c00-aa99-11eb-97f6-4cfb628d4145.png)

> TSPlayground

![image](https://user-images.githubusercontent.com/59267627/116787084-0590e700-aa9a-11eb-8df1-8e54a1de8d6e.png)

**Comment by krnik** [comment]
The queries like `highlight`, `indent` etc will need to be added to the `nvim-treesitter` repo ideally to make it work better.
In the parser repo there is only `highlights` queries but they are really minimalistic compared to `bash` for example.

**Comment by theHamsta** [comment]
You can use the playground to get the name of the nodes. See our CONTRIBUTING.md which captures to use. In the simplest case you would do something like `(comment) @comment` to give the comment node the comment highlight. The official tree-sitter docu has more info.

**Comment by ram02z** [comment]
Ok, so I think I got the hang of it. I added the highlights.scm from https://github.com/krnik/tree-sitter-fish/ to my local treesitter queries folder along with a folds.scm and injections.scm. I used the bash queries and TSPlayground as reference to create more highlight groups. Should I create a new PR in this repo?

**Comment by theHamsta** [comment]
A PR with the queries would be great 👍
