### ISSUE TITLE
Can't download precompiled parsers

### ISSUE THREAD

**Issue by K1DV5** [nvim-treesitter/nvim-treesitter#1277]
**Describe the bug**

I cannot download the artifacts from the workflow runs. When I try with Google chrome, it goes up to around 5MB and says it finished. But the files are over 60MB. I also tried it with curl, but it says `Not found`.

**To Reproduce**

1. Go to https://github.com/nvim-treesitter/nvim-treesitter/actions/runs/805062102
2. Scroll down to Artifacts
3. Click on one of the artifacts
4. See if the download completes correctly.

**Expected behavior**

The files download correctly.

**Output of `:checkhealth nvim_treesitter`**

I don't think this is necssary, as it's not related to nvim.

**Comment by theHamsta** [comment]
You're sure that something is missing in the archive. It has around 7MB for me in compressed state and ~60MB when decompressed.

**Comment by K1DV5** [comment]
Thanks @theHamsta, it seems I had a connection problem, because my downloads weren't even consistent for the same file. And got errors when I tried to open them, which led me to believe that the actual size was over 60MB (as reported on the actions page.) Now I downloaded it with my phone, got around 7MB like you said, and it's OK now. Closing.
