### ISSUE TITLE
Incorrect/missing syntax highlight for LaTeX commands

### ISSUE THREAD

**Issue by cionx** [nvim-treesitter/nvim-treesitter#1293]
**Describe the bug**

The syntax highlight for LaTeX doesn’t recognize the content of the following `amsmath` environments as math mode:

- `alignat`
- `gather`
- `flalign`
- the star-versions of the above

Here is an example with `alignat*`:

![current](https://user-images.githubusercontent.com/7231796/118166838-44258a80-b426-11eb-9fb5-e2b159012b96.png)

**To Reproduce**

Open the following code:

```latex
\begin{alignat*}{2}
	a &= 1  &\quad  b &= 2 \\
	c &= 3  &\quad  d &= 4
\end{alignat*}
```

**Expected behavior**

The  syntax highlight should be the same as for the other math environments, e.g. `align*`:

![wanted](https://user-images.githubusercontent.com/7231796/118167261-c910a400-b426-11eb-8a11-f2a80bb6b619.png)

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.4 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.1.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - latex          ✓ . ✓ . 
  - c              ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev+1318-g61aefaf29
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az168-531

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**
It seems that this can be fixed by replacing `align` with `align(at)?` in `queries/latex/highlights.scm`, as well as adding `gather` and `flalign` to this file. I didn’t open a pull request with these changes because this could/should maybe be part of #1290.

**Comment by theHamsta** [comment]
Ok, thanks for the note. I don't work a lot with LaTeX at the moment. So I really appreciate all hints! :heart:
