### ISSUE TITLE
Input lag on large javascript files

### ISSUE THREAD

**Issue by pesader** [nvim-treesitter/nvim-treesitter#1313]
**Describe the bug**

A noticeable input lag is experienced when editing large javacript files (for my test I used [pyllyukko's user.js](https://github.com/pyllyukko/user.js/)). Here's a screencast comparing neovim with treesitter and vim without it.
[![asciicast](https://asciinema.org/a/ftyuS56Le0EJs52CC0YStVKyK.svg)](https://asciinema.org/a/ftyuS56Le0EJs52CC0YStVKyK)
It is a bit hard to "see" the lag, but if you pay attention to the bottom right corner of the screen you will notice how the commands (like ```_c``` and ```_d```) appear before the actual editing is done.

**To Reproduce**

1. Find a long javascript file (~ 1000 lines)
2. Open it with neovim
3. Do any editing (delete, change, undo, etc)
4. Wait for the lag

**Expected behavior**

Ideally it should not have any noticeable input lag

**Output of `:checkhealth nvim_treesitter`**

https://pastebin.com/yEXQxpTK

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-c4VpzG/neovim-0.5.0+ubuntu2+git202105171736-dc18c1e3e-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-c4VpzG/neovim-0.5.0+ubuntu2+git202105171736-dc18c1e3e-d569569c9/build/config -I/build/neovim-c4VpzG/neovim-0.5.0+ubuntu2+git202105171736-dc18c1e3e-d569569c9/src -I/build/neovim-c4VpzG/neovim-0.5.0+ubuntu2+git202105171736-dc18c1e3e-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-c4VpzG/neovim-0.5.0+ubuntu2+git202105171736-dc18c1e3e-d569569c9/build/src/nvim/auto -I/build/neovim-c4VpzG/neovim-0.5.0+ubuntu2+git202105171736-dc18c1e3e-d569569c9/build/include
Compiled by buildd@lgw01-amd64-041

Features: +acl +iconv +tui
See ":help feature-compile"

  system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**

I think it may be relatated to these similar issues:

[Input lag on large TypeScript file #1275](https://github.com/nvim-treesitter/nvim-treesitter/issues/1275)
[input lag on cursor movement in a buffer with alot of comments](https://github.com/nvim-treesitter/nvim-treesitter/issues/1267)

And thank you so much for developing treesitter! It is the best syntax highlighting engine I've used and it really made neovim feel like a truly modern text editor.

**Comment by theHamsta** [comment]
I assume you already uninstalled comment and jsdoc parser since you aleady mentioned the other issues, right? Even without those parsers there are still some performance problems.

**Comment by PeSader** [comment]
I can confirm that uninstalling both parsers has improved performance **a lot**! Now there is no noticeable lag whatsoever.

Thanks for your help! I'm closing the issue.

**Comment by theHamsta** [comment]
@PeSader as long as those parsers have not been properly integrated we still have this issue...

**Comment by PeSader** [comment]
Oh sorry, I'll keep it open then!

Also, open issues are visible by default, so it might make it easier for other people to find the "solution" of disabling these parsers for now.

**Comment by steelsojka** [comment]
It's mostly due to just the large amount of trees they generate and we can't combine it into a single tree because then basically the whole document will be seen as the language of jsdoc when we try and get the language at cursor. I think we need a change in core in core to check the defined regions instead of using the tree itself.

**Comment by i3d** [comment]
I've noticed this in go files (6000+) and rust files (3000+). Disable highlight made dramatic difference.

**Comment by theHamsta** [comment]
@i3d did you uninstall the comment parser? It should give you some speed up.

**Comment by smolck** [comment]
FWIW, I get noticeable lag with just the `javascript` parser on [a pretty small (51 line) file](https://github.com/smolck/uivonim/blob/master/tools/build.js). Running `:TSBufDisable highlight` gets rid of (seemingly) all latency though.

**Comment by stsewd** [comment]
thanks for the example, I was able to to reproduce the issue, my guess is that maybe there is an expensive query around.

**Comment by kyazdani42** [comment]
The parser seems to struggle on a js file containing only `$`` `. I'm not sure where this comes from but a query would seem weird no ?

**Comment by elianiva** [comment]
> The parser seems to struggle on a js file containing only `` $`` ``. I'm not sure where this comes from but a query would seem weird no ?

that seems to be the case, typing <code>$\`</code> on an empty file works fine, but the moment you press <code>\`</code> after <code>$`</code>, it starts lagging. Doesn't happen if you replace $ with other character

**Comment by ahelwer** [comment]
I can confirm this is quite a bad issue. I am having to wait upwards of several seconds to input a single character on a 1600 line javascript file that makes copious use of `$`. Another tree-sitter grammar file, as you might expect: https://github.com/tlaplus-community/tree-sitter-tlaplus/blob/main/grammar.js

**Comment by amaanq** [comment]
@ahelwer I don't believe this is an issue anymore - what's your neovim version and do you experience lag with a minimal config where all plugins except nvim-treesitter are disabled? It could be a plugin that leverages nvim-treesitter that has performance issues.

Also try using nightly if you're not already on that, I don't experience lag on that file at all myself

**Comment by ahelwer** [comment]
I think you're right about that, because opening it in neovim itself (0.9.4) is pretty lag-free. I was using lunarvim which probably contributed to the lagginess. Sorry!
