### ISSUE TITLE
HTML auto indenting more than expected

### ISSUE THREAD

**Issue by yujinyuz** [nvim-treesitter/nvim-treesitter#1341]
**Describe the bug**

**To Reproduce**

1. Open index.html
2. Place cursor beside `<body>` and press  <kbd>o</kbd>
3. Notice that it is properly indented
4. Type `<p>` or `<div>`, notice it indents 2 more spaces to the right

**Expected behavior**

Should not auto indent more

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.5 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.17.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - html           ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev+1354-ga282a177d
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210525-15777-1qmfhgl/build/config -I/tmp/neovim-20210525-15777-1qmfhgl/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210525-15777-1qmfhgl/build/src/nvim/auto -I/tmp/neovim-20210525-15777-1qmfhgl/build/include
Compiled by trafalgar@waterlaw.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-a282a17_2/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**

Minimal Config:

```vim
set packpath="/tmp/empty"
set rtp-=~/.config/nvim
set rtp-=~/.config/nvim/after
set nocompatible hidden laststatus=2
set ts=2 sw=2
set nu rnu
set expandtab

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-treesitter/nvim-treesitter'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close

lua << EOF
require('nvim-treesitter.configs').setup {
  ensure_installed = {'html'},
  indent = {
    enable = true
  },
  highlight = {
    enable = true,
    use_languagetree = false
  },
}
EOF
```

Minimal HTML:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <title>Sample</title>
</head>
<body>
</body>
</html>
```

[![asciicast](https://asciinema.org/a/QcLnRypzCKDyMgUB1ni6iVKZw.svg)](https://asciinema.org/a/QcLnRypzCKDyMgUB1ni6iVKZw)

**Comment by yujinyuz** [comment]
Well, I'm not sure anymore if this is a bug as it is expecting `<body>` tag to be indented since it is inside the `<html>` tag.

I'll just close this as it works properly after doing a <kbd>gg=G</kbd>

**Comment by kyazdani42** [comment]
i've seen the bug too, so we'll keep this open until we write some tests for html indenting :)

**Comment by yujinyuz** [comment]
> i've seen the bug too, so we'll keep this open until we write some tests for html indenting :)

Sure. But it works just fine if you use the `index.html` from `create-react-app`
https://github.com/facebook/create-react-app/blob/master/packages/cra-template/template/public/index.html

**Comment by LeviOP** [comment]
I'm not able to replicate this issue anymore. HTML indents seem to have been substantially improved since this issue was opened.
