### ISSUE TITLE
Error when integrating a new parser

### ISSUE THREAD

**Issue by uyha** [nvim-treesitter/nvim-treesitter#1345]
I'm trying to create a `cmake` parser and integrate it to `nvim-treesitter`. The parser (https://github.com/uyha/tree-sitter-cmake) is more or less usable but I'm having problem integrating it with `nvim-treesitter`.
I have the following snippet for setting up my `cmake` parser:
```lua
local parser_configs = require'nvim-treesitter.parsers'.get_parser_configs()
parser_configs.cmake = {
  install_info = {
    url = 'https://github.com/uyha/tree-sitter-cmake',
    files = {"src/parser.c"}
  }
}
```
and I added the `queries` directory in my repo as the `queries/cmake` directory inside my local `nvim-treesitter` directory. However, when I open a `CMakeLists.cmake` file, I receive the error
```
Error detected while processing FileType Autocommands for "*":
E5108: Error executing lua Failed to load parser: uv_dlsym: The specified procedure could not be found.
```
I looked around for similar problems but couldn't find a straighforward solution. Could someone give me a pointer on how to process?

**Comment by vigoux** [comment]
Wo that looks like a very strange error...
Did you tried running tests using treesitter only, and does that work?

**Comment by vigoux** [comment]
Okay, I think I have the issue : in you `grammar.js` you set your language name to `CMake`.
But on neovim end, the actual filetype is all lower case.
Following that you need to either :

- Use CMake in the parser declaration in nvim-treesitter, and set the `used_by` appropriately
- Change `CMake` to `cmake` in your `grammar.js`

**Comment by uyha** [comment]
Thank you, changing `CMake` to `cmake` works.

**Comment by ajitid** [comment]
hey @uyha I'm getting the same error but the reason could be different. You mentioned:

> I looked around for similar problems but couldn't find a straighforward solution. Could someone give me a pointer on how to process?

Could you give me links for the other problems?

**Comment by uyha** [comment]
@ajitid I didn't keep track of the problems so I couldn't give you the links, maybe you can create an issue and people here can help you
