### ISSUE TITLE
E5108 SuperCollider `tree_sitter_supercollider_external_scanner_create`

### ISSUE THREAD

**Issue by madskjeldgaard** [nvim-treesitter/nvim-treesitter#1347]
The SuperCollider grammar has been overhauled substantially and nvim-treesitter has not been updated yet with these changes because some work needs to be done to align the two.

I think this is what you meant, right @vigoux ?

Here is the error message:

```
Error detected while processing FileType Autocommands for "*":         
E5108: Error executing lua Failed to load parser: uv_dlopen: /home/mads
/code/nvim-treesitter/parser/supercollider.so: undefined symbol: tree_s
itter_supercollider_external_scanner_create                            
E5108: Error executing lua Failed to load parser: uv_dlopen: /home/mads
/code/nvim-treesitter/parser/supercollider.so: undefined symbol: tree_s
itter_supercollider_external_scanner_create                            
E5108: Error executing lua Failed to load parser: uv_dlopen: /home/mads
/code/nvim-treesitter/parser/supercollider.so: undefined symbol: tree_s
itter_supercollider_external_scanner_create                            
Error detected while processing BufEnter Autocommands for "*":         
E5108: Error executing lua Failed to load parser: uv_dlopen: /home/mads
/code/nvim-treesitter/parser/supercollider.so: undefined symbol: tree_s
itter_supercollider_external_scanner_create                            
Error detected while processing FileType Autocommands for "*":         
E5108: Error executing lua Failed to load parser: uv_dlopen: /home/mads
/code/nvim-treesitter/parser/supercollider.so: undefined symbol: tree_s
itter_supercollider_external_scanner_create 
```

**Comment by madskjeldgaard** [comment]
You can ssign this to me unless someone else is already working on this

**Comment by madskjeldgaard** [comment]
This is very strange though. It seems to be some kind of linker error (that I don't experience when running the parser in the command line tool) that this function https://github.com/madskjeldgaard/tree-sitter-supercollider/blob/67ecede8fc5f2e342a7f0516b87d0476b36035ac/src/scanner.c#L7 does not exist. Why would this be a problem in nvim-treesitter and not treesitter-cli I wonder?

**Comment by madskjeldgaard** [comment]
The parser config in nvim-treesitter looks fine to me
https://github.com/nvim-treesitter/nvim-treesitter/blob/972f70956ac8635ab2f6d7ed0b24e5cd159d7a04/lua/nvim-treesitter/parsers.lua#L326

**Comment by madskjeldgaard** [comment]
@theHamsta do you have any idea about what's going on here? I'm struggling to find the cause of this to be honest

**Comment by vigoux** [comment]
When does this error happen? Did you do a `TSUninstall` then `TSInstall` in order to clean everything?

The bug report is not really clear, but it looks like you are missing a `scanner.c` in your parser config.

**Comment by madskjeldgaard** [comment]
> When does this error happen? Did you do a `TSUninstall` then `TSInstall` in order to clean everything?
> 
> The bug report is not really clear, but it looks like you are missing a `scanner.c` in your parser config.

Thank you, uninstalling it first seems to have helped. Then the problem is something else. You mentioned in a PR that there were issues with the supercollider grammar - could you elaborate?

I seem to be getting an inline error now from treesitter saying invalid node type. Is that it ?

**Comment by vigoux** [comment]
Without any error message pasted I can't be of much help.

Invalid node type often means a node name is misspelled in a query, of that a parent/child combination, will never match in a query (impossible patterns that is).

**Comment by madskjeldgaard** [comment]
> Without any error message pasted I can't be of much help.
> 
> Invalid node type often means a node name is misspelled in a query, of that a parent/child combination, will never match in a query (impossible patterns that is).

Yes, I think that was it - something has been renamed. I'll do a PR

**Comment by vigoux** [comment]
Is this issue still there or is it gone ?

**Comment by madskjeldgaard** [comment]
> Is this issue still there or is it gone ?

It seems to be gone. Thanks and sorry for the confusion
