### ISSUE TITLE
Highlighting does not work with V parser.

### ISSUE THREAD

**Issue by crthpl** [nvim-treesitter/nvim-treesitter#1363]
**Describe the bug**

Using the [V](https://github.com/vlang/v) [Treesitter Parser](https://github.com/nedpals/tree-sitter-v) does not work (no highlighting) and `:checkhealth` reports no errors other than parser features being `. . . . .` (No features present)

**To Reproduce**

1. Add this to `init.vim`:
```nvim
autocmd BufRead,BufNewFile *.v set filetype=v

lua <<EOF
local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
parser_config.v = {
  install_info = {
    url = "http://github.com/nedpals/tree-sitter-v", -- local path or git repo
    files = {"src/parser.c"}
  },
  used_by = {} -- additional filetypes that use this parser
}
EOF
```

2. `:TSInstall v` (For some reason, `:TSUpdate` will always recompile the V parser)
3. Open a file ending with `.v`
4. Highlighting will not work. `:TSPlaygroundToggle` shows that it was parsed correctly (I can see all the different syntax elements, even though the features are `. . . . .`), but `:TSHighlightCapturesUnderCursor` shows `No highlight groups found`.

**Expected behavior**

Highlighting

**Output of `:checkhealth nvim_treesitter`**
<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.5 (8d8690538ef0029885c7ef1f163b0e32f256a5aa) (parser generator, only needed        for :TSInstallFromGrammar)
  - OK: `node` found v14.15.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be                 compatible with runtime ABI.

## Parser/Features H L F I
  - c              ✓ ✓ ✓ ✓ ✓
  - v              . . . . .

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will  used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev+1372-g056c464e8
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1622611659764.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

</code>
</details>

Am I doing something wrong?

**Comment by theHamsta** [comment]
Most features need queries. You need to add them here  https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries for v.

The parser itself seems to work for me.

**Comment by crthpl** [comment]
I have made a small `highlights.scm` in `~/.vim/plugged/nvim-treesitter/queries/v`:
```scm
(comment) @comment

"fn" @keyword
```
`:TSPlaygroundToggle` still shows the correct tree. 

However, it still does not highlight and `:TSHighlightCapturesUnderCursor` still shows `No highlight groups found`.
`:checkhealth` now shows `✓ . . . .` for V now, though.

**Comment by theHamsta** [comment]
![image](https://user-images.githubusercontent.com/7189118/120901761-08549e00-c63d-11eb-9d61-24105aac0ccf.png)

You query works for me. I have put
```viml
    au! BufRead,BufNewFile *.v set filetype=v
```
into my init.vim

**Comment by crthpl** [comment]
@theHamsta  Do I have to do anything to load my query? I have just put it in the `~/.vim/plugged/nvim-treesitter/queries/v` folder. Although `:checkhealth` does say that I have highlighting.

**Comment by crthpl** [comment]
I figured it out: I hadn't installed the highlighting module.
