### ISSUE TITLE
ERROR: tsx(highlights): query: invalid syntax at position 5925

### ISSUE THREAD

**Issue by sinetoami** [nvim-treesitter/nvim-treesitter#1364]
**Describe the bug**

When I open any `tsx` file the highlight breaks and I get the above error in every line:
```
treesitter/highlighter: Error executing lua: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid syntax at position 5925
```

**To Reproduce**

Any `tsx` file

![2021-06-05-200545_1829x457_scrot](https://user-images.githubusercontent.com/16659014/120907758-95e2be80-c63a-11eb-8d69-dbe500a4745a.png)

**Expected behavior**

I hope it doesn't break the highlight.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.4 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v15.12.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - tsx            x ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

The following errors have been detected:
  - ERROR: tsx(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid syntax at position 5925

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev+1379-gf214c19e2
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/snio/.cache/yay/neovim-git/src/build/config -I/home/snio/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/snio/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/snio/.cache/yay/neovim-git/src/build/include
Compiled by snio@bitscave

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

</code>
</details>

**Additional context**

**Comment by kyazdani42** [comment]
maybe just update your tsx parser `:TSUpdate tsx`

**Comment by sinetoami** [comment]
I do @kyazdani42. Do not fix it. That's why I opened the issue. :(

**Comment by kyazdani42** [comment]
did you update properly:
-1) nvim-treesitter version ?
-2) neovim ?
make sure you use the latest master for both

**Comment by sinetoami** [comment]
@kyazdani42, before open this issue I do that.
> **Output of `:checkhealth nvim_treesitter`**
> 
> `` # health#nvim_treesitter#check ## Installation * OK: `tree-sitter` found 0.19.4 (parser generator, only needed for :TSInstallFromGrammar) * OK: `node` found v15.12.0 (only needed for :TSInstallFromGrammar) * OK: `git` executable found. * OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" } * OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI. ## Parser/Features H L F I * typescript ✓ ✓ ✓ ✓ ✓ * javascript ✓ ✓ ✓ ✓ ✓ * tsx x ✓ ✓ ✓ ✓ Legend: H[ighlight], L[ocals], F[olds], I[ndents] +) multiple parsers found, only one will be used x) errors found in the query, try to run :TSUpdate {lang} The following errors have been detected: * ERROR: tsx(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid syntax at position 5925 ``

> **Output of `nvim --version`**
> 
> ` NVIM v0.5.0-dev+1379-gf214c19e2 Build type: RelWithDebInfo LuaJIT 2.0.5 Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/snio/.cache/yay/neovim-git/src/build/config -I/home/snio/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/snio/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/snio/.cache/yay/neovim-git/src/build/include Compiled by snio@bitscave Features: +acl +iconv +tui See ":help feature-compile" system vimrc file: "$VIM/sysinit.vim" fall-back for $VIM: "/usr/share/nvim" `

I update right now to:
> NVIM v0.5.0-dev+1385-g93f15db5d
> LuaJIT 2.0.5

The issue persists. Even with the minimal configuration.

**Comment by kyazdani42** [comment]
Hum, i'm not too sure how to help here, i have the almost same versions but no issues at all. Did you by any chance, overwrote the tsx highlight query ?

**Comment by sinetoami** [comment]
hey @kyazdani42, it's weird but fix it.
I notice one thing. Yes, I overwrote the highlight query. But before does a fresh install of all my Neovim environment I've tried to remove the highlight query from my nvim directory and didn't fix it. After doing the new fresh install and recompile the plugin it works without the highlight query.

Thanks for guides me to solve this problem! 
Cheers
