### ISSUE TITLE
svelte indent issues

### ISSUE THREAD

**Issue by non25** [nvim-treesitter/nvim-treesitter#1368]
**Describe the bug**

Indent issues, there's probably more, I'll add them later if I find any.

- Text under the node with any attribute shifts one indent level left by using `=`.
- Indent messes up when doing multiline attrs manually.
- Sometimes second enter in insert mode (after a blank line) shifts one indent level left.
- Nested ifs and eachs don't autoindent properly as I type, have to use `=`.
- Else if indents one indentation level more.
- Text inserted using `o` after a node with multiline attributes shifts one indent level left.
- Non-closed tags always jump to the line start and to correct indent level after they've been closed.

**To Reproduce**

Do something similar to this: https://asciinema.org/a/ezQSsIlwo95zxl7Wq8XjykKYI

**Expected behavior**

'as I type' indent yielding same results as `=`. `=` doing sane things.

**Output of `:checkhealth nvim_treesitter`**

<details>

## Installation

  - OK: `tree-sitter` found  0.19.4 (parser generator, only needed for :TSInstallFromGrammar)

  - OK: `node` found v16.1.0 (only needed for :TSInstallFromGrammar)

  - OK: `git` executable found.

  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }

  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - svelte         ✓ . ✓ ✓ ✓ 
  - scss           ✓ . . ✓ . 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
</details>

**Output of `nvim --version`**

<details>
NVIM v0.5.0-dev+1384-gf2906a466
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/non/projects/oss/arch/neovim-git/src/build/config -I/home/non/projects/oss/arch/neovim-git/src/neovim-git/src -I/usr/include -I/home/non/projects/oss/arch/neovim-git/src/build/src/nvim/auto -I/home/non/projects/oss/arch/neovim-git/src/build/include
Compiled by non@non-lt

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
</details>

**Additional context**

https://github.com/Himujjal/tree-sitter-svelte/issues/14

**Comment by LeviOP** [comment]
fixed in #6035 as all valid html is valid svelte, so svelte indents now inherit from html tags.
