### ISSUE TITLE
javascript try..catch block not indenting properly

### ISSUE THREAD

**Issue by yujinyuz** [nvim-treesitter/nvim-treesitter#1370]
**Describe the bug**

Javascript catch block is not indenting properly

**To Reproduce**

1. Create a `sample.js` file
2. Create a `try..catch` block.
3. Put cursor under the last `}` and press <kbd>O</kbd>

**Expected behavior**
It should place the cursor properly when pressing <kbd>O</kbd>

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.5 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.17.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - html           ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev+1385-g93f15db5d
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210608-27568-1kvj6wa/build/config -I/tmp/neovim-20210608-27568-1kvj6wa/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210608-27568-1kvj6wa/build/src/nvim/auto -I/tmp/neovim-20210608-27568-1kvj6wa/build/include
Compiled by trafalgar@waterlaw.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-93f15db_2/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**

Minimal config:

```vim
set packpath="/tmp/empty"
set rtp-=~/.config/nvim
set rtp-=~/.config/nvim/after
set nocompatible hidden laststatus=2
set ts=2 sw=2
set nu rnu
set expandtab
set autoindent

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-treesitter/nvim-treesitter'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close

lua << EOF
require('nvim-treesitter.configs').setup {
  ensure_installed = {'javascript'},
  indent = {
    enable = true
  },
  highlight = {
    enable = true,
    use_languagetree = false
  },
}
EOF
```

[![asciicast](https://asciinema.org/a/qE3fMvp5dKqzqVYWvz2OT93MC.svg)](https://asciinema.org/a/qE3fMvp5dKqzqVYWvz2OT93MC)

**Comment by vigoux** [comment]
I don't see `try` nor `catch` in `ecma`'s, `indent.scm` and think this might be the issue, I am marking this as an enhancement then, as it is only a missing match in a query.

**Comment by kyazdani42** [comment]
this is the same kind of issue that arise with rust/go else branches, trying to indent try or catch clause will not change anything, i think it's a bug we need to fix inside the indent algorithm.

**Comment by yujinyuz** [comment]
I'm not sure if this helps but if I'm on a `javascript` file and I do `set filetype=typescript`

the try..catch block indentation works as expected

Do you have any ideas why? I checked the indents.scm and I've seen that `javascript/indents.scm` inherits from ecma and jsx while typescript just inherits from ecma
