### ISSUE TITLE
Can't load nvim-treesitter

### ISSUE THREAD

**Issue by kdurant** [nvim-treesitter/nvim-treesitter#1372]
os : win10 wsl1
nvim : nightly
minimal vimrc
```viml
call plug#begin('~/.config/nvim/bundle')
Plug 'git@github.com:nvim-treesitter/nvim-treesitter.git'
call plug#end()
```
![QQ截图20210609094736](https://user-images.githubusercontent.com/2704364/121279810-c27f2a80-c907-11eb-8bde-7a1a3e0d650d.png)

**Comment by vigoux** [comment]
Hi, this it looks like your version of nvim is too old.
Could you show your version number here?

**Comment by stsewd** [comment]
Please let us know your exact nvim version as the template says, you can also try downloading the latest version and see if the error goes away.
