### ISSUE TITLE
No syntax highlighting for svelte

### ISSUE THREAD

**Issue by cschmatzler** [nvim-treesitter/nvim-treesitter#1382]
**Describe the bug**

Syntax highlighting for `.svelte` files simply does not work.

**To Reproduce**

1. Install the svelte grammar
2. Open a svelte file.
3. See no syntax highlighting.

**Expected behavior**

Syntax highlighting is marked as feature for svelte, so it should give editor highlighting.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check                                                                         
  1 ========================================================================                             
  2 ## Installation                                                                                      
  3   - OK: `tree-sitter` found  0.19.5 (8d8690538ef0029885c7ef1f163b0e32f256a5aa) (parser generator,          only needed for :TSInstallFromGrammar)                                                             
  4   - OK: `node` found v16.3.0 (only needed for :TSInstallFromGrammar)                                 
  5   - OK: `git` executable found.                                                                      
  6   - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }                 
  7   - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be       compatible with runtime ABI.                                                                       
  8                                                                                                      
  9 ## Parser/Features H L F I                                                                           
 10   - typescript     ✓ ✓ ✓ ✓ ✓                                                                         
 11   - svelte         ✓ . ✓ ✓ ✓                                                                         
 12   - rust           ✓ ✓ ✓ ✓ ✓                                                                         
 13                                                                                                      
 14  Legend: H[ighlight], L[ocals], F[olds], I[ndents]                                                   
 15         \+) multiple parsers found, only one will be used                                            
 16         \x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

v0.5.0-dev+1387-g53791c054

</code>
</details>

**Comment by stsewd** [comment]
Hi, what does `:set filetype?` show? I don't think neovim has detection for that filetype, think we can copy this in the repo https://github.com/leafOfTree/vim-svelte-plugin/blob/master/ftdetect/svelte.vim or submit that patch to vim.

**Comment by cschmatzler** [comment]
`set :filetype` correctly shows `filetype=svelte`, since I've already checked that and added it, unfortunately.

Here's my config, if that helps: https://github.com/cschmatzler/dotfiles/tree/master/nvim/.config/nvim

**Comment by cschmatzler** [comment]
Okay, am an idiot, pulled an old version of my config that didn't have the `highlight` module enabled, apparently forgot to push that on my other machine. Sorry for wasting your time!

**Comment by vigoux** [comment]
Glad you figured that out pal, and no worry, we're here to help  :smile:

**Comment by manzt** [comment]
I think I might be running into a similar issue where the contents of `<script>` and `<style>` tags don't have any syntax highlighting. 

![image](https://user-images.githubusercontent.com/24403730/165834080-1fcb37ee-d4d0-4f78-b33e-2f9ca228cd06.png)

`: set filetype?` yields `filetype=svelte` and I have treesitter syntax highlighting enabled. Is this expected behavior?

### output of `nvim --version`

```
NVIM v0.8.0-dev+1527-g521e91e1c
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by manzt@Trevors-MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-521e91e/share/nvim"

Run :checkhealth for more info
```


### output of `:checkhealth nvim_treesitter`

```
nvim_treesitter: health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.6.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.1.6 (clang-1316.0.21.2.3)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - svelte         ✓ . ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

**Comment by MatthiasGrandl** [comment]
@manzt did you figure this out? i have the same problem

**Comment by manzt** [comment]
Ahh thank you for the solution! I assumed I had the other grammars enabled..

**Comment by kamalkech** [comment]
i am not understand why the people when found or fixe the issue then not share with us, we are here to lean and help others. bullshit.

**Comment by HDMiranda** [comment]
I've had the same problem the other day, it turned out that when I updated my setup from another machine it broke the highlight feature for javascript and vim.
`javascript     x ✓ ✓ ✓ ✓`

It says to try and update (`x) errors found in the query, try to run :TSUpdate {lang}`), but only worked in my case with `:TSInstall javascript`
`javascript     ✓ ✓ ✓ ✓ ✓`

**Comment by anterpin** [comment]
I have quite the opposite:
The JavaScript and the CSS context are highlighted, but the HTML is not.
(I have the svelte, javascript, css grammars installed)  

![image](https://user-images.githubusercontent.com/44070188/198896654-f58e8789-b7c6-4076-9091-46b724bc8cee.png)

## output `nvim -v`
```
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

## output `:checkhealth nvim-treesitter`
```
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.16.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - html           ✓ ✓ ✓ ✓ ✓
  - svelte         ✓ . ✓ ✓ ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - css            ✓ . ✓ ✓ ✓
  - cpp            ✓ ✓ ✓ ✓ ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - typescript     ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

```

**Comment by computergnome99** [comment]
Hey @anterpin did you ever figure this out? I have the same issue (highlighted js/css, but no markup highlighting).

**Comment by huttongrabiel** [comment]
@anterpin / @computergnome99 
I have this same issue. Did either of you manage to figure it out?

**Comment by anterpin** [comment]
@huttongrabiel / @computergnome99
Yes, I solved it, but I didn't quite remember how I did it.
I think I have updated the tree sitter version on my pc. (sudo apt-get install tree-sitter or similar)
I think it was something like that, I don't recall.

**Comment by guxuerui** [comment]
> 
Run `TSInstall svelte`

**Comment by samridht23** [comment]
i have the same problem treesitter is not working with svelte file and i have enabled highlight. treesitter is working with go and typescript but completely no highlighting in svelte file.

And i have done `:TSInstall svelte` but not is getting highlighted.

`set filetype?`
`filetype=svelte`

`nvim -v`
```
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

`:checkhealth nvim-treesitter`
```
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v19.8.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.2.1 20230201
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "6.2.8-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Wed, 22 Mar 2023 22:52:35 +0000"
}

## Parser/Features         H L F I J
  - go                  ✓ ✓ ✓ ✓ ✓
  - svelte              ✓ . ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```
