### ISSUE TITLE
Wrong indentation for switch/case statement on javascript

### ISSUE THREAD

**Issue by luisiacc** [nvim-treesitter/nvim-treesitter#1384]
**Describe the bug**

Indentation on switch/case clause on javascript doesn't work, see video below.

**To Reproduce**

https://user-images.githubusercontent.com/31720261/121768156-a0192700-cb2a-11eb-88d2-b588f3945606.mp4

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.2.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - python         ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - css            ✓ . ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

```
NVIM v0.5.0-dev+1385-g93f15db5d
Build type: Release
LuaJIT 2.1.0-beta3
```
</code>
</details>

Treesitter config: 
```vim
require'nvim-treesitter.configs'.setup {
    highlight = {
        enable = true,              -- false will disable the whole extension
        additional_vim_regex_highlighting = true
    },
    indent = {enable = true},
    incremental_selection = {enable = true},
    textobjects = {enable = true},
    playground = {
        enable = true,
        disable = {},
        updatetime = 25, -- Debounced time for highlighting nodes in the playground from source code
        persist_queries = false -- Whether the query persists across vim sessions
    }
    }

```

**Comment by Samyak2** [comment]
Adding `switch_statement` and `switch_case` to the indents file for ECMA (which is same as the indents file for JS) seems to fix it.

<details>
<summary>click to show diff</summary>

```patch
diff --git a/queries/ecma/indents.scm b/queries/ecma/indents.scm
index aad719c..9fdcc4f 100644
--- a/queries/ecma/indents.scm
+++ b/queries/ecma/indents.scm
@@ -12,6 +12,8 @@
   (template_substitution)
   (expression_statement (call_expression))
   (export_clause)
+  (switch_statement)
+  (switch_case)
 ] @indent
 
 [
```

</details>

I will open a PR soon for this.
