### ISSUE TITLE
Need to press <C-q> twice for it to work

### ISSUE THREAD

**Issue by svanharmelen** [nvim-treesitter/nvim-treesitter#1398]
**Describe the bug**

I remapped these:

```
local actions = require('telescope.actions')
require('telescope').setup{
  defaults = {
    mappings = {
      i = {
        ["<C-j>"]   = actions.move_selection_next,
        ["<C-k>"]   = actions.move_selection_previous,
        ["<C-q>"]   = actions.smart_send_to_qflist + actions.open_qflist,
        ["<ESC>"]   = actions.close,
      },
    },
  }
}
```

But when I press `C-q` nothing happens. If I press it again, it works as expected. If I instead map it to `C-a` it work the first time as well. I did try to search for anything else being mapped to `C-q` (using :verbose map <C-q>) but could not find anything...

**To Reproduce**

Remap de following the snipped above. Open the find_files (maybe select one) and press `C-q`

**Expected behavior**

Trigger on the first invocation of `C-q`

**Output of `:checkhealth nvim_treesitter`**

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/4171547/122280769-d3bcce00-cee9-11eb-90d4-8e5917621b17.png">

**Comment by vigoux** [comment]
Huh, it seems that you are posting this issue on the wrong repo?
Your issue seems only related to `telescope.nvim` but not `nvim-treesitter`, right?

**Comment by svanharmelen** [comment]
Whoeps! Sorry for the noise 😊

**Comment by vigoux** [comment]
No worry pal 😉
