### ISSUE TITLE
Elixir: "W18: Invalid character in group name"

### ISSUE THREAD

**Issue by millnitzluan** [nvim-treesitter/nvim-treesitter#1405]
**Describe the bug**

When opening elixir files like `.ex/.exs` I'm getting this error.

**To Reproduce**

1. Go to elixir files
2. See the error. `W18: Invalid character in group name`

**Expected behavior**

This error shows every time when using nvim + telescope with file preview. You can easily check it while previewing the files. Disabling elixir syntax stops the error.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.5 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v12.20.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - bash           ‚úì ‚úì ‚úì . ‚úì 
  - ruby           ‚úì ‚úì ‚úì ‚úì ‚úì 
  - python         ‚úì ‚úì ‚úì ‚úì ‚úì 
  - lua            ‚úì ‚úì ‚úì ‚úì ‚úì 
  - elixir         ‚úì ‚úì . ‚úì ‚úì 
  - html           ‚úì ‚úì ‚úì ‚úì ‚úì 
  - json           ‚úì ‚úì ‚úì ‚úì . 
  - javascript     ‚úì ‚úì ‚úì ‚úì ‚úì 
  - css            ‚úì . ‚úì ‚úì ‚úì 
  - typescript     ‚úì ‚úì ‚úì ‚úì ‚úì 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
</code>
</details>

**Output of `nvim --version`**

<details>
<code>
 nvim --version
NVIM v0.5.0-dev+1385-g93f15db5d
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210607-11245-s88s7u/build/config -I/tmp/neovim-20210607-11245-s88s7u/src -I/opt/homebrew/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/gettext/include -I/tmp/neovim-20210607-11245-s88s7u/build/src/nvim/auto -I/tmp/neovim-20210607-11245-s88s7u/build/include
Compiled by luanmillnitz@marvin.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-93f15db_2/share/nvim"

Run :checkhealth for more info
</code>
</details>

**Additional context**

I'm using iterm2.

**Comment by theHamsta** [comment]
Could this be related to https://github.com/neovim/neovim/pull/14767 ?

**Comment by millnitzluan** [comment]
IDK if it's related, built neovim with your modifications and the error is still happening.

**Comment by matiaslb** [comment]
Same thing happens to me, I believe that the issue happens when the following plugin is loaded: vim-editors/vim-elixir

**Comment by cigrainger** [comment]
Same thing happens to me, including after I removed `vim-editors/vim-elixir`.

**Comment by stsewd** [comment]
> This error shows every time when using nvim + telescope with file preview. You can easily check it while previewing the files. Disabling elixir syntax stops the error.

Does this happen when not using telescope? I think you should report this issue there, then.

**Comment by millnitzluan** [comment]
> > This error shows every time when using nvim + telescope with file preview. You can easily check it while previewing the files. Disabling elixir syntax stops the error.
> 
> Does this happen when not using telescope? I think you should report this issue there, then.

I don't that the errors happen in telescope, due that it's easy to get the error using telescope + preview. I think that the same happens without telescope.

**Comment by stsewd** [comment]
@millnitzluan can you provide a file to replicate this? Also, are you able to replicate this without telescope?

**Comment by thedelchop** [comment]
FWIW, the issue is triggered when an .exs file contain a HEREDOC string.  This example, without `telescope` installed and `syntax` set to off, always produces the error:

```elixir
defmodule Test do
  def foo do
    """
      This is a string I am going to return that
      includes some new lines and what not.
    """
  end
end
```

while this never does:

```elixir
defmodule Test do
  def foo do
    "This is a string I am going to return that includes some new lines and what not."
  end
end
```
I can also confirm that this error only appeared after I had installed `elixir-vim` and persists even after removing `elixir-vim` and re-installing `nvim-treesitter`.  I can't seem to grasp how that plugin could have an effect on tree-sitter but 🤷‍♂️ 

This is using NeoVim 0.5.0

**Comment by stsewd** [comment]
@thedelchop thanks for providing the file to test this, but I wasn't able to replicate this even installing vim-elixir. Can you try replicating this with a minimal init.vim?

**Comment by thedelchop** [comment]
@stsewd I still see the error, using that file, with this minimal init.lua file:

```
require('packer').startup(function()
  use 'wbthomason/packer.nvim'

  use { 'nvim-treesitter/nvim-treesitter',                -- The goal of nvim-treesitter is both to provide a simple and easy way to use the interface for tree-sitter in Neovim
    run = ':TSUpdate',
    config = function()
      require("nvim-treesitter.configs").setup {
        ensure_installed = {
          'elixir'
        },
        highlight = {
          enable = true
        },
        indent = {
          enable = true
        }
      }
    end
  }
end)

vim.g.mapleader = ";"
vim.api.nvim_set_keymap('i', 'jk', '<Esc>', {noremap = true})
```
And I also wiped out my `~/.local/share/nvim` and `~/.local/.cache/nvim` directories and reinstalled `neovim`.

**Comment by thedelchop** [comment]
@stsewd just to be sure, did you update your elixir parser for TS?

**Comment by stsewd** [comment]
I was able to replicate this with that minimal init.vim. Actually, I'm able to replicate with my init.vim, but the message was being hidden. I thought this was being shown as a lua error, but it's shown as a message `:messages`

**Comment by stsewd** [comment]
there is an invalid capture group in elixir highlights' queries, not sure how the CI passed...

**Comment by stsewd** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/pull/1551 should fix this, also, I think that what you actually want for these queries is a new group like `string.delimiter`

**Comment by stsewd** [comment]
BTW, the highlight queries make use of `_` instead of  `(_)` and they give a syntax error in the playground, I asked more information about the difference in https://github.com/tree-sitter/tree-sitter/issues/1253

**Comment by thedelchop** [comment]
@stsewd Awesome, thank you so much.  I am trying to learn more about tree sitter as it seems pretty cool, but I'm still kind of a newbie.  I'll try to setup the playground and see what I can find.

**Comment by theHamsta** [comment]
@stsewd the CI does not test parsers that require npm

**Comment by jameschensmith** [comment]
Just ran into this same error message in Nix files. The `string.special` fix will most likely address it, as the comments in #1551 note. When I get a chance to validate the fix, I'll post an update here :+1:
