### ISSUE TITLE
Very slow navigation on this python file

### ISSUE THREAD

**Issue by luisiacc** [nvim-treesitter/nvim-treesitter#1415]
**Describe the bug**

Navigating up and down within the lines mentioned is terribly laggy.

**To Reproduce**

1. Go to line 1044 of the file
2. Navigate up & down
3. So laggy

**Expected behavior**

Navigation should be smooth

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.2.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - c              ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - css            ✓ . ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev+1429-gb585f723b
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protec
tor-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/acc/neovim-repo/neovim/build/config -I/home/acc/neovim-repo/neo
vim/src -I/home/acc/neovim-repo/neovim/.deps/usr/include -I/usr/include -I/home/acc/neovim-repo/neovim/build/src/nvim/auto -I/home/acc/neovim-repo/neovim/build/include
Compiled by acc@acc

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/acc/neovim/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**

This is the file [pdf.zip](https://github.com/nvim-treesitter/nvim-treesitter/files/6690128/pdf.zip) 

Doing `:TSDisableAll highlight` makes the lag go away, but also the highlights and my colorscheme of course.

Extra note:
I've noted an overall slower highlighting on python files. The difference on speed when file switching is very noticable when toggling the highlights.

**Comment by elianiva** [comment]
It seems like it got slower if the cursor is above a node with *lots* of lines.
These are the big nodes in that file:
- :79 -> 962 lines
- :1044 -> 1007 lines
- :2090 -> 567 lines (not as laggy as the previous ones)

**Comment by stsewd** [comment]
You can disable the comment and rst parser, there are a lot of injections in that file, we have some performance problems with multiple injections. But looks like you don't have those parsers, so it's just slow in general :/

```

    c ✓ ✓ ✓ ✓ ✓
    json ✓ ✓ ✓ ✓ .
    css ✓ . ✓ ✓ ✓
    javascript ✓ ✓ ✓ ✓ ✓
    python ✓ ✓ ✓ ✓ ✓
    typescript ✓ ✓ ✓ ✓ ✓
    tsx ✓ ✓ ✓ ✓ ✓

```

**Comment by polarmutex** [comment]
seeing the same problem.

 is there a way to install specific commits of grammars to see which one caused the problem?

**Comment by JoseConseco** [comment]
I have similar issue.  Some longer lines in python are verry laggy.  Slowdown appeared 2-3 days ago - I reverted my loca copy of TS  to version from 10 days ago, but it did not help. 
 I think things went worse after updating latest neovim-nightly-bin those 2-3 days ago . I'm not sure how do I check out older version on nvim... Right now I'm using this command: 
`yay -u neovim-nightly-bin`

**Comment by stsewd** [comment]
You can change the commit from the lock file https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lockfile.json, but this issue is more related to neovim triggering lots of refreshes and/or ts parsing the file again.

**Comment by polarmutex** [comment]
based on my limited testing, the problem seems to start when treesitter in the neovim was upgraded to 0.19.5 on 6/11/21

**Comment by JoseConseco** [comment]
@polarmutex  do you have build on nvim for linux from before the regression?  The way it is now its unworkable.

**Comment by mizlan** [comment]
As a workaround, try checking out and building a commit of Neovim before 3085788a3ef84cebaf532bbe77fde6df16a694a2.

**Comment by luisiacc** [comment]
> As a workaround, try checking out and building a commit of Neovim before 3085788a3ef84cebaf532bbe77fde6df16a694a2.

I can confirm that this issue doesn't exists before this commit, also highlighting seems to be much faster(tested on python,javascript and html files).

**Comment by stsewd** [comment]
Thanks all for testing, think this should be reported to neovim.

**Comment by levouh** [comment]
Did anyone make an issue upstream @stsewd @luisiacc @polarmutex, etc.? If so, can you link it here? Otherwise I'm happy to create one. Seeing this problem myself as well.

**Comment by levouh** [comment]
I created one [here](https://github.com/neovim/neovim/issues/14897), let me know if someone else did this already and I'll close mine and/or link it.

**Comment by stsewd** [comment]
> I created one [here](https://github.com/neovim/neovim/issues/14897), let me know if someone else did this already and I'll close mine and/or link it.

I think you are the first, thank you :)

**Comment by brymer-meneses** [comment]
This also happens for tex files using treesitter.
