### ISSUE TITLE
/usr/bin/ld: cannot find -lstdc++

### ISSUE THREAD

**Issue by dosisod** [nvim-treesitter/nvim-treesitter#1417]
**Describe the bug**

When installing treesitter via `:TSUpdate`, `libstdc++` is not found, and compilation fails.

**To Reproduce**

1. Download my [nvim config](https://github.com/dosisod/dotfiles/blob/master/.config/nvim/init.vim) ([lines 54-61](https://github.com/dosisod/dotfiles/blob/master/.config/nvim/init.vim#L54-L61) are probably the most relevant)
2. Open `nvim`
3. Run `:TSUpdate`
4. The following error is displayed:

```
nvim-treesitter[c]: Error during compilation
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
Press ENTER or type command to continue
```

**Expected behavior**

No error during installation.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v14.17.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - c              ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-1eBo0N/neovim-0.5.0+ubuntu2+git202106210023-b585f723b-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-1eBo0N/neovim-0.5.0+ubuntu2+git202106210023-b585f723b-d569569c9/build/config -I/build/neovim-1eBo0N/neovim-0.5.0+ubuntu2+git202106210023-b585f723b-d569569c9/src -I/build/neovim-1eBo0N/neovim-0.5.0+ubuntu2+git202106210023-b585f723b-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-1eBo0N/neovim-0.5.0+ubuntu2+git202106210023-b585f723b-d569569c9/build/src/nvim/auto -I/build/neovim-1eBo0N/neovim-0.5.0+ubuntu2+git202106210023-b585f723b-d569569c9/build/include
Compiled by buildd@lcy01-amd64-006

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**

```
$ uname -s
Linux hostname 5.4.0-74-generic #83~18.04.1-Ubuntu SMP Tue May 11 16:01:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.4.0-1ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++
--prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64
--with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.4.0 (Ubuntu 8.4.0-1ubuntu1~18.04)

$ ld -v
GNU ld (GNU Binutils for Ubuntu) 2.30

$ apt list --installed libstdc++\*
Listing... Done
libstdc++-10-dev/bionic,now 10.3.0-1ubuntu1~18.04~1 amd64 [installed,automatic]
libstdc++-7-dev/bionic-updates,bionic-security,now 7.5.0-3ubuntu1~18.04 amd64 [installed,automatic]
libstdc++6/bionic,now 11.1.0-1ubuntu1~18.04.1 amd64 [installed]
```

Removing this line fixes causes everything to install without compilation (on my machine):

https://github.com/nvim-treesitter/nvim-treesitter/blob/55c5620aa318a11823b5dd3d3cd69265f3763339/lua/nvim-treesitter/shell_command_selectors.lua#L74

**Comment by theHamsta** [comment]
Most parsers don't require C++. But some do for their scanner. Please just install `lstdc++` which can be done by install `g++`

**Comment by dosisod** [comment]
I do have `libstdc++` installed (see Additional Context), as well as g++:

```
$ apt list --installed g++\*
Listing... Done
g++/bionic-updates,bionic-security,now 4:7.4.0-1ubuntu2.3 amd64 [installed]
g++-10/bionic,now 10.3.0-1ubuntu1~18.04~1 amd64 [installed]
g++-7/bionic-updates,bionic-security,now 7.5.0-3ubuntu1~18.04 amd64 [installed,automatic]

$ g++ --version
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by theHamsta** [comment]
But you don't have libstdc++ for version 8 which seems to be your c compiler. Maybe this could be the issue?

**Comment by dosisod** [comment]
This fixed my issue! Weird that I've just now ran into this.

**Comment by Chaz6** [comment]
If it helps anyone else, I ran into this on Fedora 35 and installing `libstdc++-static` resolved the problem (`libstdc++` and `libstdc++-devel` were already installed).
