### ISSUE TITLE
treesitter is causing neovim to crash

### ISSUE THREAD

**Issue by 77anshuman** [nvim-treesitter/nvim-treesitter#1418]
**Describe the bug**

Using vim-plug once nvim-treesitter is installed, if I install lua module using :TSInstall lua and then source my init.lua file which contains the nvim-treesitter.config.setup function as shown in the documentation, neovim crashes. 

![image](https://user-images.githubusercontent.com/74228646/123078026-335e3080-d438-11eb-89cb-b1cb288cd883.png)

**To Reproduce**

1. Install nvim-treesitter using vim-plug or packer.nvim (I have tried with both and got the same result)
2. :TSInstall lua (I was just testing the features)
3.  save and source init.lua
4. "Neovim has crashed" message is shown and this is seen whenever a lua file is opened.

**Expected behavior**

In the nvim-treesitter.config.setup function only highlight was enabled and thus I expected highlighting for lua syntax

**Output of `:checkhealth nvim_treesitter`**

ERROR: No health found for "nvim-treesitter" plugin

![image](https://user-images.githubusercontent.com/74228646/123079579-b3d16100-d439-11eb-88b7-c4af24be8ea2.png)

**Output of `nvim --version`**
Paste the output here

NVIM v0.5.0-dev+1424-g96d83e2a6
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-381

**Additional context**

I am using neovim nightly on Windows 10 64-bit, I mostly use nvim-qt. These are my dotfiles [github.com/omknan60/nvim-lua](url)

I have tried this on two windows 64-bit laptops, this issue is seen on both of them. But treesitter works fine on my 32-bit Windows 10 pc.

**Comment by 77anshuman** [comment]
Update : The treesitter is not the cause of the problems, the issue is caused by the language package that can be installed using :TSInstall, in my system (Windows 10 x64) lua and python have resulted in neovim crash whereas HTML, cpp, c, JSON, JS, CSS have been working great.

**Comment by stsewd** [comment]
Thanks for the report, I don't user windows, but I think we have a wiki entry for it https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support

**Comment by 77anshuman** [comment]
Thnaks, I repalced TDM GCC with Clang 3.7.0 and MinGW 5.1.0. This works very well.

**Comment by stsewd** [comment]
Great!

**Comment by obnoxiousnerd** [comment]
@77anshuman I am also having the same issue. Can you clarify what changes you made to make it work? Which `gcc` are you using? The one from TDM-GCC, or from MSYS2, or are you using `clang`?
