### ISSUE TITLE
Incorrect definition highlighting in for different scopes

### ISSUE THREAD

**Issue by steelsojka** [nvim-treesitter/nvim-treesitter#142]
**Describe the bug**
Definition is incorrect when the focused symbol is the definition.

**To Reproduce**
Given this javascript file

![nvim-ts-error-1](https://user-images.githubusercontent.com/2062154/86373096-a3344380-bc48-11ea-97e5-3d745a79a4e0.png)

When the cursor is on the variable `a` (not the function parameter), the function parameter `a` is highlighted as the definition.
If the parenthesis are removed from the arguments the variable definition is flagged as the definition of the argument.'

![nvim-ts-error-2](https://user-images.githubusercontent.com/2062154/86373289-e2fb2b00-bc48-11ea-9754-cd127805675e.png)

**Expected behavior**
Neither one should be highlighted since they are in different scopes and are definitions them self. This may just be an issue with the queries for javascript or the algorithm used for finding definitions.

**Output of `:checkhealth nvim_treesitter` ***
```
Paste the output here
```

**Output of `nvim --version`**
```
Paste your output here
```

**Additional context**

**Comment by vigoux** [comment]
Can this be a `locals.scm` issue ?

**Comment by steelsojka** [comment]
@vigoux It may be. I need to look into a little bit further.

**Comment by vigoux** [comment]
Sorry deleted the coment, but it might be related to locals.

**Comment by theHamsta** [comment]
I think the find_definition should always find declarations before the current cursor position.

Consider the following example:
```cpp
void normalReactionTest(cr::HCSITS& cr, SphereID sp)
{
   contactThreshold = Thresholds<real_t>::contactThreshold();
   // plane at 5,5,5
   // radius 1.1
   sp->setPosition(  Vec3(5,5,6) );
   sp->setLinearVel( Vec3(0,0,0) );
   cr.setErrorReductionParameter( real_t(1.0) ); // <----------------- cursor at beginning of line
   cr.timestep( real_c( real_t(1.0) ) );
}

int main( int argc, char** argv )
{
   cr::HCSITS cr(globalBodyStorage, forest->getBlockStoragePointer(), storageID, hccdID, fcdID); // <-- will find this definition
   return EXIT_SUCCESS;
}
} // namespace walberla

```

Without #145 it can't recognize the definition of `cr` as an arguments and finds cr in a completely different scope (because also the scope definition for function bodies is missing

**Comment by vigoux** [comment]
@theHamsta , I don't really agree with that, in the case of functions for example, you can find the definition of that function below the cursor (for example in Rust).
Regarding the fact it finds things somewhere else is quite weird, as it should only go upwards in scope hierarchy, that needs a bit of investigation.

**Comment by theHamsta** [comment]
Maybe related to #170
