### ISSUE TITLE
 nvim-treesitter ABI incompatible nixos

### ISSUE THREAD

**Issue by AusCyberman** [nvim-treesitter/nvim-treesitter#1432]
**Describe the bug**

![image](https://user-images.githubusercontent.com/12080502/123504507-1ecea200-d69d-11eb-8894-7702a4627b05.png)
on NixOS, for all languages, despite it running with the same binaries on Debian

**To Reproduce**

Compile Treesitter parsers on nixos

**Expected behavior**

Compatbile abi with neovim

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.19.5 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.17.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - ERROR: Neovim was compiled with tree-sitter runtime ABI version 12.
    nvim-treesitter expects at least ABI version 13
    Please make sure that Neovim is linked against are recent tree-sitter runtime when building or raise an issue at your Neovim packager. Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - haskell        . . . . . 
  - javascript     x x x x x 
  - rust           x x x x x 
  - go             x x x x x 
  - zig            x x x x x 
  - c              x x x x x 
  - agda           . . . . . 
  - query          x x x x x 
  - fennel         x x . . x 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

The following errors have been detected:
  - ERROR: javascript(highlights): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/javascript.so: supported between 9 and 12, found 13
  - ERROR: javascript(locals): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/javascript.so: supported between 9 and 12, found 13
  - ERROR: javascript(folds): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/javascript.so: supported between 9 and 12, found 13
  - ERROR: javascript(indents): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/javascript.so: supported between 9 and 12, found 13
  - ERROR: javascript(injections): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/javascript.so: supported between 9 and 12, found 13
  - ERROR: rust(highlights): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/rust.so: supported between 9 and 12, found 13
  - ERROR: rust(locals): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/rust.so: supported between 9 and 12, found 13
  - ERROR: rust(folds): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/rust.so: supported between 9 and 12, found 13
  - ERROR: rust(indents): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/rust.so: supported between 9 and 12, found 13
  - ERROR: rust(injections): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/rust.so: supported between 9 and 12, found 13
  - ERROR: go(highlights): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/go.so: supported between 9 and 12, found 13
  - ERROR: go(locals): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/go.so: supported between 9 and 12, found 13
  - ERROR: go(folds): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/go.so: supported between 9 and 12, found 13
  - ERROR: go(indents): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/go.so: supported between 9 and 12, found 13
  - ERROR: go(injections): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/go.so: supported between 9 and 12, found 13
  - ERROR: zig(highlights): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/zig.so: supported between 9 and 12, found 13
  - ERROR: zig(locals): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/zig.so: supported between 9 and 12, found 13
  - ERROR: zig(folds): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/zig.so: supported between 9 and 12, found 13
  - ERROR: zig(indents): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/zig.so: supported between 9 and 12, found 13
  - ERROR: zig(injections): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/zig.so: supported between 9 and 12, found 13
  - ERROR: c(highlights): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/c.so: supported between 9 and 12, found 13
  - ERROR: c(locals): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/c.so: supported between 9 and 12, found 13
  - ERROR: c(folds): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/c.so: supported between 9 and 12, found 13
  - ERROR: c(indents): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/c.so: supported between 9 and 12, found 13
  - ERROR: c(injections): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/c.so: supported between 9 and 12, found 13
  - ERROR: query(highlights): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/query.so: supported between 9 and 12, found 13
  - ERROR: query(locals): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/query.so: supported between 9 and 12, found 13
  - ERROR: query(folds): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/query.so: supported between 9 and 12, found 13
  - ERROR: query(indents): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/query.so: supported between 9 and 12, found 13
  - ERROR: query(injections): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/query.so: supported between 9 and 12, found 13
  - ERROR: fennel(highlights): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/fennel.so: supported between 9 and 12, found 13
  - ERROR: fennel(locals): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/fennel.so: supported between 9 and 12, found 13
  - ERROR: fennel(injections): ...aster/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/auscyber/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/fennel.so: supported between 9 and 12, found 13

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: 
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/3kgvn6vpmlcxgfk21liw4r6r9n2vqjbk-neovim-unwrapped-master/share/nvim
"

Run :checkhealth for more info

</code>
</details>

**Additional context**

Running nixpkgs master and neovim master.

**Comment by stsewd** [comment]
From where did you get your nvim? Looks like an old treesitter version was used to compile it.

**Comment by AusCyberman** [comment]
> From where did you get your nvim? Looks like an old treesitter version was used to compile it.

nixpkgs master

**Comment by stsewd** [comment]
@AusCyberman that's the version of the tree-sitter cli command, as you can see in your checkhealth ouput neovim was compiled using an old version of the tree-sitter runtime

> Neovim was compiled with tree-sitter runtime ABI version 12. nvim-treesitter expects at least ABI version 13 Please make sure that Neovim is linked against are recent tree-sitter runtime when building or raise an issue at your Neovim packager. Parsers must be compatible with runtime ABI.

Please report this to the nixos package manager, or try installing the latest tree-sitter runtime (I don't use nix so not sure how to do this)
