### ISSUE TITLE
Do not fold one line

### ISSUE THREAD

**Issue by anuvyklack** [nvim-treesitter/nvim-treesitter#1435]
Is it possible to add an option to set the threshold to not create a fold if a number of lines less than this threshold?

For example to not create folds that will consist of 3 lines but with only 1 not visible line that makes sense, like this:

```lua
for _, item in ipairs(list) do
    print(item)
end
```

**Comment by stsewd** [comment]
This can be an option, yeah https://github.com/nvim-treesitter/nvim-treesitter/blob/c04aa172a3feab61f8f4fbfa0e3d47fa12513485/lua/nvim-treesitter/fold.lua#L33-L33

**Comment by MunifTanjim** [comment]
How about using the value from `foldminlines` variable (`:help foldminlines`)?

**Comment by stsewd** [comment]
> How about using the value from `foldminlines` variable (`:help foldminlines`)?

that's better!
