### ISSUE TITLE
Provide installation instructions for `packer.nvim`

### ISSUE THREAD

**Issue by Samyak2** [nvim-treesitter/nvim-treesitter#1439]
**Is your feature request related to a problem? Please describe.**

When I was considering installation of `nvim-treesitter` in my (lua) config that uses [`packer.nvim`](https://github.com/wbthomason/packer.nvim) for package management, it wasn't obvious what I had to add to my config to do so. To be specific, the `do` part of the current `vim-plug` installation command wasn't obvious at first. It would help beginners with an (almost) fully lua-based config (like me) to have a simple ~one-liner~ few lines that they can copy to their config. The `packer.nvim` README has an example just for `nvim-treesitter` so that helped me install it.

**Describe the solution you'd like**

This being added to the README under `Installation`:
```lua
    use {
        'nvim-treesitter/nvim-treesitter',
        run = ':TSUpdate'
    }
```

**Describe alternatives you've considered**

N/A

**Additional context**

I can send a PR for this if it is appropriate.

**Comment by vigoux** [comment]
What we may do instead (more community driven), is to do a wiki page.

Would that be a solution that works for you?

**Comment by Samyak2** [comment]
From my experience, GitHub wiki pages can be a little awkward to contribute to as they exist as a separate git repo from the main repo. Is there a specific reason for suggesting Wiki pages as opposed to having the community contribute to the README (or other doc files in the repo) directly?

**Comment by vigoux** [comment]
Yes, this keeps the repo small, and avoid updates like "ad thing thing to the README", and also, the allows the community (that I hope exists hehe) to contribute more freely, and be involved!

**Comment by stsewd** [comment]
+1 on showing the more common things in the readme, and have a wiki to cover all other tools.

**Comment by stsewd** [comment]
I have created this page https://github.com/nvim-treesitter/nvim-treesitter/wiki/Installation

**Comment by Samyak2** [comment]
Okay, that makes sense. I've added packer.nvim to that wiki page.

Still, the wiki isn't mentioned in the README. A link to that wiki page in the installation section would be useful

**Comment by stsewd** [comment]
Linking to the wiki makes sense :+1:

**Comment by theHamsta** [comment]
And that one line with packer installation in README doesn't harm. You must have in mind that most people only copy the install instruction from the README and don't read much of the remaining documentation. So add `see wiki for other plugin managers` or `   use { 'nvim-treesitter/nvim-treesitter', run = ':TSUpdate'  }` to README

**Comment by Samyak2** [comment]
> You must have in mind that most people only copy the install instruction from the README and don't read much of the remaining documentation.

Yes, that is what I had in mind. Linking to the wiki page should be enough. Do I send a PR for this (it's a small change, so I'm not sure)?

**Comment by theHamsta** [comment]
@Samyak2 yes, would be nice if you could create a PR
