### ISSUE TITLE
[Question] Parsers for doc comments?

### ISSUE THREAD

**Issue by farbodsz** [nvim-treesitter/nvim-treesitter#1447]
So I noticed that there's a parser for JSDoc which highlights JS doc comments by use of injections,. I've also noticed for others like Python, a different injection like reStructuredText is used.

I'm thinking it would be good to add highlighting for doc comments in other languages. Should I go ahead and start working on a tree-sitter parser for a doc-comment "language" or is there a better/easier way of approaching this that I'm missing?

**Comment by stsewd** [comment]
We already have the comment parser :) https://github.com/stsewd/tree-sitter-comment which is injected in several languages https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/css/injections.scm if there are languages missing that injection, a PR in welcome!

Also, every language has their own format for docstrings like javadoc, markdown, etc.

**Comment by farbodsz** [comment]
> We already have the comment parser :) which is injected in several languages 

That's a great point I forgot about the comment parser :)

> if there are languages missing that injection, a PR in welcome!

Nice, thanks for clarifying!
