### ISSUE TITLE
TSInstall errors with clang set as compiler

### ISSUE THREAD

**Issue by bhavitsharma** [nvim-treesitter/nvim-treesitter#1449]
**Describe the bug**

`TSInstall cpp` fails to compile when using clang as a compiler on nixos. 

**To Reproduce**
`env CC=$(which clang) nvim '+TSInstallSync cpp'`

**Expected behavior**
Should compile

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

</code>
</details>

**Output of `nvim --version`**

<details>
<code>
NVIM v0.5.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: 
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/bqfq1sz0ifjf6gnz6j6iqx5015p4yz1d-neovim-unwrapped-master/share/nvim

Run :checkhealth for more info
</code>
</details>

**Additional context**
```
src/scanner.cc:2:10: fatal error: 'string' file not found                                       
#include <string>                                                                               
         ^~~~~~~~                                                                               
1 error generated.                                                                              
Error detected while processing command line:                                                   
Error during compilation                                                                        
Failed to execute the following command:                                                        
{                                                                                               
  cmd = "clang",                                                                                
  err = "Error during compilation",                                                             
  info = "Compiling...",                                                                        
  opts = {                                                                                      
    args = { "-o", "parser.so", "-I./src", "src/parser.c", "src/scanner.cc", "-shared", "-Os", "
-lstdc++", "-fPIC" },                                                                           
    cwd = "/home/bhavit/.local/share/nvim/tree-sitter-cpp"                                      
  }                                                                                             
}    
```
I am using homemanager for managing my dotfiles and here's my config for `nvim.nix`.
```
home.packages = with pkgs; [
    neovim-nightly
    clang-tools
    rls
    sumneko-lua-language-server
    fzf
    ripgrep
    tree-sitter
    llvmPackages_12.llvm
    clang_12
    haskell-language-server
    clangStdenv
    clangMultiStdenv
];
xdg.configFile."nvim" = {
    source = ../nvim;
    recursive = true;
};
```

**Comment by bhavitsharma** [comment]
I think this is a problem with clang. When I tried to clone the repo and compile using `clang -o parser.so -I./src src/parser.c src/scanner.cc -lstdc++ -fPIC`, it gave the same error

**Comment by theHamsta** [comment]
Apple Clang? It's somehow not entering C++ mode.

**Comment by bhavitsharma** [comment]
Stupid me: using `clang++` worked. `require 'nvim-treesitter.install'.compilers = { 'clang++'}` worked.

**Comment by theHamsta** [comment]
@bhavitsharma But it should also work with clang. clang++ will not always handle C files so you've got the inverse problem.

**Comment by bhavitsharma** [comment]
I guess then it's a problem with my nix configuration rather than treesitter because I can't compile even this with `clang`.

```cpp
#include <string>
int main() { 
return 0;
}
```
`clang temp.cpp`

**Comment by theHamsta** [comment]
But it can happen that clang++ fails with `CStruct = { .foo=1, .bar=2 }`

**Comment by bhavitsharma** [comment]
I think C++ 17 has supports for designated initializers for struct :) but I get your point. I am not sure if the issue with clang is reproducible in other platforms? Quick internet search reveals to use `clang -x c++` but I am not sure. The general recommendation to compile c++ files is to use `clang++` instead of clang.

**Comment by YodaEmbedding** [comment]
I found a way to reproduce the error. If you have `glibc` (or `musl`) installed, everything goes haywire.

```nix
{ pkgs ? import <nixpkgs> {} }:

with pkgs;
pkgs.mkShell {
  buildInputs = [
    gcc
    nodejs
    neovim
    tree-sitter
    (python39.withPackages (pp: with pp; [
      pynvim
    ]))

    # Including this suddenly breaks TSInstall:
    glibc
  ];
}
```

**Comment by theHamsta** [comment]
@bhavitsharma only in C++20. There is an open PR to use makefiles to compile c++ with clang++ and the C files with clang. But with only one command you can only use `clamg`

**Comment by Pablo1107** [comment]
Maybe this issue should still be open? I know there are workarounds, but should treesitter compile C++ files with `clang++` instead of `clang` to avoid this issue?

**Comment by dongdongbh** [comment]
It worked after I changed my GCC version from gcc-9 to gcc-10.3. This may be helpful for anyone else who is experiencing the same problem.

**Comment by hallettj** [comment]
I'm another NixOS user, and I'm installing plugins with lazy.nvim instead of through Nix. If you got here because you are in a similar situation, and you are getting oodles of errors when you start neovim, my workaround is to avoid the whole clang issue by setting the grammar compiler to `gcc`.

I have this in my plugin config - since I'm using lazy.nvim I put this in the `config` callback for my nvim-treesitter plugin config ([see in context](https://github.com/hallettj/home.nix/blob/6465db8aff49a1f3f9a75f19cdd2568a8b88698e/neovim/nvim-config/lua/plugins/treesitter.lua#L8)):

```lua
require('nvim-treesitter.install').compilers = { 'gcc' }
```

And to make sure that gcc is available while running neovim I have neovim installed through Home Manager like this ([see in context](https://github.com/hallettj/home.nix/blob/6465db8aff49a1f3f9a75f19cdd2568a8b88698e/neovim/default.nix#L24)):

```nix
  programs.neovim = {
    enable = true;
    defaultEditor = true;
    withPython3 = true;
    extraPackages = with pkgs; [
      gcc
      # ...
    ];
  };
```
