### ISSUE TITLE
Underline entire lines when closing parenthesis missing in python with gruvbox-material

### ISSUE THREAD

**Issue by pmdaly** [nvim-treesitter/nvim-treesitter#1452]
**Describe the bug**

When there are missing closing parenthesis in python, multiple lines will be entirely underlined until the syntax is corrected.  The bug started occurring recently and only occurs with gruvbox-material found here 
https://github.com/sainnhe/gruvbox-material
but not gruvbox.  Previous versions of the python treesitter parser did not cause this issue.

**To Reproduce**

1. Use https://github.com/sainnhe/gruvbox-material gruvbox colorscheme
2. type `np.random.randn(` in a python file
3.  continue onto the next line with an argument (doesn't matter what they are)
4. See underlining bug as shown below 
![Screen Shot 2021-06-29 at 12 06 08 PM](https://user-images.githubusercontent.com/8229664/123853516-65591200-d8d2-11eb-80b0-08b2fcf05a6f.png)

**Expected behavior**
expect no underlines (treesitter is off in this image)
![Screen Shot 2021-06-29 at 12 07 01 PM](https://user-images.githubusercontent.com/8229664/123853635-891c5800-d8d2-11eb-9bd3-7ba162be7ce5.png)

**Output of `:checkhealth nvim_treesitter`**

<details>
health#nvim_treesitter#check    
========================================================================    
## Installation    
   - OK: `tree-sitter` found  0.19.5 (parser generator, only needed for :TSInstallFromGrammar)    
   - OK: `node` found v14.16.1 (only needed for :TSInstallFromGrammar)    
   - OK: `git` executable found.    
   - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }    
   - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.    
    
## Parser/Features H L F I    
  - python         ✓ ✓ ✓ ✓ ✓     
  - typescript     ✓ ✓ ✓ ✓ ✓     
  - toml           ✓ ✓ ✓ ✓ ✓     
  - yaml           ✓ ✓ ✓ ✓ ✓     
  - lua            ✓ ✓ ✓ ✓ ✓     
  - bash           ✓ ✓ ✓ . ✓     
  - fish           ✓ ✓ ✓ ✓ ✓     
  - html           ✓ ✓ ✓ ✓ ✓     
  - java           ✓ ✓ . ✓ ✓     
  - javascript     ✓ ✓ ✓ ✓ ✓     
  - tsx            ✓ ✓ ✓ ✓ ✓     
  - json           ✓ ✓ ✓ ✓ .     
    
 Legend: H[ighlight], L[ocals], F[olds], I[ndents]    
         +) multiple parsers found, only one will be used    
         x) errors found in the query, try to run :TSUpdate {lang} 
</details>

**Output of `:checkhealth`**

<details>
health#mkdp#check
========================================================================
  - INFO: Platform: macos
  - INFO: Nvim Version: NVIM v0.5.0-dev+nightly-156-g22c27c0fb
  - INFO: Node version: v14.16.1

  - INFO: Script: /Users/pdaly1/.vim/plugged/markdown-preview.nvim/app/server.js
  - INFO: Script exists: 1
  - OK: Using node

health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle build/index.js found
  - OK: Service started

health#nvim_treesitter#check
========================================================================
  - ERROR: Failed to run healthcheck for "nvim_treesitter" plugin. Exception:
    function health#check[21]..health#nvim_treesitter#check, line 1
    Vim(lua):E5108: Error executing lua ...im/plugged/nvim-treesitter/lua/nvim-treesitter/query.lua:104: attempt to index a nil value

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help provider-python
          /usr/bin/python2.7 does not have the "neovim" module. :help provider-python
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help provider-python
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Python version: 3.9.5
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV
  
## Ruby provider (optional)
  - INFO: Ruby: ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin19]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help g:ruby_host_prog for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v14.16.1
  - INFO: Nvim node.js host: /usr/local/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.0

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

health#treesitter#check
========================================================================
## Checking treesitter configuration
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for bash: ABI version 13
  - OK: Loaded parser for fish: ABI version 13
  - OK: Loaded parser for html: ABI version 13
  - OK: Loaded parser for java: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for toml: ABI version 13
  - OK: Loaded parser for tsx: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for yaml: ABI version 13
</details>

**Output of `nvim --version`**

<details>
NVIM v0.5.0-dev+nightly-156-g22c27c0fb
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210625-9883-dw5bcs/build/config -I/tmp/neovim-20210625-9883-dw5bcs/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210625-9883-dw5bcs/build/src/nvim/auto -I/tmp/neovim-20210625-9883-dw5bcs/build/include
Compiled by pdaly1@INTUL18ace4d62

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-22c27c0_2/share/nvim"

Run :checkhealth for more info
</details>

**Additional context**

**Comment by stsewd** [comment]
Hi, this looks like it's part of the theme https://github.com/sainnhe/gruvbox-material/blob/6a5e1392c3c619e74b5c450da17b1915a7bddcb2/colors/gruvbox-material.vim#L425

By default, we don't link `TSError` to anything https://github.com/nvim-treesitter/nvim-treesitter/blob/master/plugin/nvim-treesitter.vim
