### ISSUE TITLE
  - ERROR: Impossible to load parser for python: Failed to load parser: uv_dlopen: /snap/core18/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libstdc++.so.6)

### ISSUE THREAD

**Issue by codehia** [nvim-treesitter/nvim-treesitter#1468]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

Paste the output here

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

Paste the output here

</code>
</details>

**Additional context**

**Comment by folke** [comment]
Hi! I'm having a similar issue on Fedora with the Nix neovim-nighlty. Since you closed it, what did you do to fix this? :)

**Comment by codehia** [comment]
> Hi! I'm having a similar issue on Fedora with the Nix neovim-nighlty. Since you closed it, what did you do to fix this? :)

I replaced the snap installation with appimage installation and it fixed itself. I hope that helps.

**Comment by Flimm** [comment]
I had the same problem with Neovim on Ubuntu 21.10 installed with Snap. Switching to the appimage installation seemed to fix it.
