### ISSUE TITLE
combining ensure_installed: "maintained" with other, specified languages

### ISSUE THREAD

**Issue by aegatlin** [nvim-treesitter/nvim-treesitter#1471]
**Is your feature request related to a problem? Please describe.**
I want all the 'maintained' parsers and then some more parsers. All specified in "ensure_installed".

**Describe the solution you'd like**
I don't claim this is a _good_ solution, but it is along the lines of what I have in mind. I want "all the maintained parsers and then some specific additional ones".

```lua
require'nvim-treesitter.configs'.setup {
  ensure_installed = ["maintained", "elixir"]
  ...
}
```

Another (probably bad) idea that I'm not sure how to implement in lua is (in psuedo-code): `maintained_array += 'elixir'`

**Describe alternatives you've considered**
I wrote my own lua setup function in my own config so I can leave ensure_installed on "maintained". I'm definitely keeping "maintained", I like that option a lot. I like the idea of having all the "maintained" parsers on my machine. This is my current work-around.

Thank you for this plugin in general. It's great! :D <3

**Comment by theHamsta** [comment]
with a recent merge request this should now be possible via
```lua
vim.cmd[[TSUpdate maintained]]
vim.cmd[[TSUpdate elixir]]
```
