### ISSUE TITLE
Highlighting for elixir is slow

### ISSUE THREAD

**Issue by fuelen** [nvim-treesitter/nvim-treesitter#1486]
**Describe the bug**
Opening any elixir file takes ~1 second. Even for very small files. Such timing makes it unusable. 
Opening other files like *.js or *.json is very fast.

**To Reproduce**

My config:
```lua
    local ts_config = require("nvim-treesitter.configs")

    ts_config.setup {
        ensure_installed = {
            "bash",
            "css",
            "erlang",
            "elixir",
            "graphql",
            "javascript",
            "json",
            "lua",
            "html",
            "yaml"
        },
        highlight = {
            enable = true,
            use_languagetree = true
        },
        indent = {
            enable = true
        }
    }
```
Open any file, like https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/application.ex

**Expected behavior**
A performance as in other plugins

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v13.7.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - css            ✓ . ✓ ✓ ✓ 
  - erlang         . . . . . 
  - bash           ✓ ✓ ✓ . ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - elixir         ✓ ✓ . ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - graphql        ✓ . . ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.0/build/config -I/build/neovim/src/neovim-0.5.0/src -I/usr/include -I/build/neovim/src/neovim-0.5.0/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.0/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Comment by andyl** [comment]
I've noticed the same thing.

**Comment by theHamsta** [comment]
Can you try to benchmark `tree-sitter query` with our highlights.scm in the tree-sitter-elixir repo? Kotlin for example is affected by https://github.com/tree-sitter/tree-sitter/issues/973

**Comment by fuelen** [comment]
@theHamsta 
```
hyperfine "tree-sitter query  /home/fuelen/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/elixir/highlights.scm /home/fuelen/projects/ecto/lib/ecto/application.ex"
Benchmark #1: tree-sitter query  /home/fuelen/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/elixir/highlights.scm /home/fuelen/projects/ecto/lib/ecto/application.ex
  Time (mean ± σ):     643.4 ms ±  12.0 ms    [User: 640.3 ms, System: 2.7 ms]
  Range (min … max):   632.6 ms … 675.1 ms    10 runs
```
```
cat /home/fuelen/projects/ecto/lib/ecto/application.ex                                                                                                                                                                          fuelen@arch
defmodule Ecto.Application do
  @moduledoc false
  use Application

  def start(_type, _args) do
    children = [
      Ecto.Repo.Registry,
    ]

    opts = [strategy: :one_for_one, name: Ecto.Supervisor]
    Supervisor.start_link(children, opts)
  end
end
```

and this is a file from private project 2190 LOC:
```
hyperfine "tree-sitter query  /home/fuelen/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/elixir/highlights.scm /home/fuelen/projects/private.ex"
Benchmark #1: tree-sitter query  /home/fuelen/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/elixir/highlights.scm /home/fuelen/projects/private.ex
  Time (mean ± σ):     698.1 ms ±   3.3 ms    [User: 685.0 ms, System: 11.7 ms]
  Range (min … max):   694.0 ms … 703.4 ms    10 runs
```

**Comment by theHamsta** [comment]
That's pretty slow and the time seems to come only from loading the query file. Can you report it at the tree-sitter repo? Also try whether a parser generated with 0.18.3 tree-sitter is faster.

**Comment by fuelen** [comment]
Should I create a new issue? Or just drop a comment using a link you've sent?
Unfortunately, I'm unable to compile tree-sitter v0.18.3

**Comment by theHamsta** [comment]
@fuelen you can just set the dev dependency to the tree-sitter version and build via `npm install`. Whatever you think will help the tree-sitter authors to figure out what's going on. Did you do try to use a minimal query to see whether the problems are actually specific queries or the parser itself?

**Comment by fuelen** [comment]
@theHamsta thanks for the tip about package.json.
I've created an issue in tree-sitter repo. See mention above^

> Did you do try to use a minimal query to see whether the problems are actually specific queries or the parser itself?

Just tried a simple expression `1 + 1`:
```
  Time (mean ± σ):     638.0 ms ±   5.1 ms    [User: 634.4 ms, System: 2.9 ms]
  Range (min … max):   630.2 ms … 647.8 ms    10 runs
```

**Comment by theHamsta** [comment]
I meant just to use a simple expression for the queries. Loading the query takes a long time. But we don't know whether it's a certain query or the parser itself loading for validation of the queries.

**Comment by fuelen** [comment]
well, I'm not sure if I'm doing it right, but I've removed everything from highlights.scm and left only this line:
```
["when"] @keyword
```
querying a file with only 1 word `when` produces the following result:
```
  pattern: 40
    capture: error, start: (0, 0), end: (1, 0)
```

benchmark:
```
  Time (mean ± σ):     640.6 ms ±   4.2 ms    [User: 635.4 ms, System: 4.7 ms]
  Range (min … max):   637.1 ms … 651.0 ms    10 runs
```
Is this what you've asked?

**Comment by fuelen** [comment]
updated a comment, initially I was querying using invalid path to a query file

**Comment by connorlay** [comment]
I'm experiencing this issue as well and want to fix it. What can I do to help triage? Has anyone tried isolating which highlight query is causing the problem? If not I can look into it.

**Comment by theHamsta** [comment]
Apparently, the queries are to complex. Maybe it's possible to move some of the complexity into parser?

**Comment by connorlay** [comment]
I took a first pass at removing chunks of the highlights and I did see a significant speed-up once the more complex ones were removed.

Elixir has relatively few special forms and much of the language is built on simple function calls and macros, which the parser itself reflects in the syntax tree that is produced. Compared to JavaScript, the highlight queries for Elixir are very "deep" and have a lot of specific matches based on the more abstract syntax tree produced by the parser. This results in contextually accurate highlights, which visually are appealing, but I suspect are slowing things down.

The easiest solution I can think of is to simplify the highlights a bit in favor of performance. Things won't be quite as contextually accurate, but it would at least make things more usable for now.

**Comment by vigoux** [comment]
I am highly in favor to simplify the queries then, we want sane defaults for most languages, not huge queries.

**Comment by connorlay** [comment]
Sounds good to me. I'll take a stab at simplifying these queries.

**Comment by Yarnus** [comment]
I am also concerned about this problem. 
May I know if your highlighting work normally on `eex` file ?

**Comment by connorlay** [comment]
Hey all, I opened this PR https://github.com/nvim-treesitter/nvim-treesitter/pull/1682 that rewrites the highlighting logic for Elixir. On my machine it feels much faster, but I'd love additional testers to give it a go.

**Comment by dottorblaster** [comment]
@connorlay I gave a spin to your PR and everything looks fine, the situation is way better, the problem doesn't go completely away tho. How about merging this and keep investigating?

**Comment by vigoux** [comment]
We'll be sure to make that PR go further ASAP, we are just waiting for a review, and we'll be good to go.
