### ISSUE TITLE
Weird lines shown on buffer when using nvim-treesitter and svelte

### ISSUE THREAD

**Issue by charbelnicolas** [nvim-treesitter/nvim-treesitter#1494]
**Describe the bug**

When enabling nvim-treesitter highlighting on svelte, neovim shows some weird lines in the buffer.

**To Reproduce**

1. Open an .svelte file with nvim-treesitter highlight enabled.

**Expected behavior**

I expect the lines to not be present.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.4.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - css            ✓ . ✓ ✓ ✓ 
  - svelte         ✓ . ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.0/build/config -I/build/neovim/src/neovim-0.5.0/src -I/usr/include -I/build/neovim/src/neovim-0.5.0/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.0/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**

![20210704_212336](https://user-images.githubusercontent.com/14960414/124409792-a6a45400-dd0e-11eb-8470-ff0eae42678d.png)

**Comment by charbelnicolas** [comment]
A small video showing the issue:

https://user-images.githubusercontent.com/14960414/124410828-de140000-dd10-11eb-9d59-bab1b13c7b88.mp4

**Comment by stsewd** [comment]
Hi, this issue is the same as https://github.com/nvim-treesitter/nvim-treesitter/issues/1371.

**Comment by charbelnicolas** [comment]
I can see that html files no longer have this issue but svelte files still show the weird lines.

HTML:
![20210714_111736](https://user-images.githubusercontent.com/14960414/125656726-ece99bac-d6d3-4335-9ee9-8f4b323df7c0.png)

SVELTE:
![20210714_111804](https://user-images.githubusercontent.com/14960414/125656784-a723eef4-655e-41b5-bc86-2659e9ce502d.png)

Is there a quick fix for svelte seeing html no longer shows this issue?

**Comment by stsewd** [comment]
@charbelnicolas the issue is still present, but it's less noisy on html files, see https://github.com/nvim-treesitter/nvim-treesitter/issues/1506. Also, could you please provide the svelte file to test in the other issue?
