### ISSUE TITLE
query.lua:367: No handler for any-of?

### ISSUE THREAD

**Issue by wibbit** [nvim-treesitter/nvim-treesitter#1499]
Please note, I am running the most recent release 0.5.0, not master.
**Describe the bug**

When editing a .py file, I get the following error
treesitter/highlighter: Error executing lua: /opt/bats/share/nvim/runtime/lua/vim/treesitter/query.lua:376: No handler for any-of?

**To Reproduce**

Edit a blank .py file, and start typing, errors straight away.

**Expected behavior**

Well, for it not to throw an error, and to highlight appropriately

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v15.11.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `clang` executable found. Selected from { "clang", "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - python         ✓ ✓ ✓ ✓ ✓
  - comment        ✓ . . . .
  - lua            ✓ ✓ ✓ ✓ ✓
  - go             ✓ ✓ ✓ ✓ ✓
  - json           ✓ ✓ ✓ ✓ .
  - bash           ✓ ✓ ✓ . ✓
  - yaml           ✓ ✓ ✓ ✓ ✓
  - html           ✓ ✓ ✓ ✓ ✓
  - toml           ✓ ✓ ✓ ✓ ✓
  - jsonc          ✓ ✓ ✓ ✓ ✓

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

:version
NVIM v0.5.0-dev
Build type: Release
LuaJIT 2.0.4
Compilation: /bin/gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -DNDEBUG -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Ws
hadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/dfurlong/rpms/bats-neovim/BUILD/neovim-nightly/build/config -I/home/dfurlong/rpms/bats-neovim/BUILD/neovim-nightl
y/src -I/opt/bats/include -I/usr/include -I/home/dfurlong/rpms/bats-neovim/BUILD/neovim-nightly/build/src/nvim/auto -I/home/dfurlong/rpms/bats-neovim/BUILD/neovim-nightly/build/include
Compiled by dfurlong@dev-rhel7-bats-neovim

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/bats/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**

using treesitter version 0.20.0, however I can confirm the same issue with 0.19.4

**Comment by theHamsta** [comment]
Did you install Neovim 0.5 with a `make clean` before building. Sometimes the runtime files don't get updated. `any-of?` is defined in Neovim core. If it's not there the your Neovim version is maybe too old.

**Comment by wibbit** [comment]
Thanks for the quick reply.

This is built as an RPM, so each time it gets a clean build env.

However, the version of query.lua laid down by the RPM certainly doesn't have "any-of?" listed, so I'll do some more digging.

**Comment by wibbit** [comment]
This issue was down to how I was building the RPM, and the spec file was pointing to an older version of a tar.gz file.

After cleaning that up, and actually building 0.5.0 and not an old nightly, the issue went away.
