### ISSUE TITLE
Problem source config file .vim

### ISSUE THREAD

**Issue by picolloo** [nvim-treesitter/nvim-treesitter#1510]
I'm having kind of a same problem, my init.vim sources a treesitter.vim file like this:

init.vim
```vim
for f in split(glob('~/.config/nvim/plugins.d/*.vim'), '\n')
    exe 'source' f
endfor
```

treesitter.vim
```vim
lua <<EOF
require'nvim-treesitter.configs'.setup {
    ensure_installed = {"bash", "javascript", "ruby", "go", "dockerfile", "html", "json", "yaml"},

    highlight = {
      enable = true,
    },
    indent = {
      enable = true
    },
    textobjects = {
      select = {
        enable = true,
        keymaps = {
          ["af"] = "@function.outer",
          ["if"] = "@function.inner",
          ["ab"] = "@block.outer",
          ["ib"] = "@block.inner",
          ["as"] = "@statement.outer",
          ["is"] = "@statement.inner",
          ["ac"] = "@conditional.outer",
          ["ic"] = "@conditional.inner",
        }
      }
    }
}
EOF
```

When I start vim I get the message: error trying to parse file treesitter.vim at the last EOF line

_Originally posted by @tammarut in https://github.com/nvim-treesitter/nvim-treesitter/issues/647#issue-741812145

**Comment by stsewd** [comment]
Can you share a minimal init.vim that is causing this?

I'm not able to reproduce this with this.

```
exe 'source treesitter.vim'
```

**Comment by picolloo** [comment]
Hi @stsewd, i figured that out. 
the problem was happening because of the source statement being placed inside `call plug#begin...call plug#end`. 

Thank you anyway
