### ISSUE TITLE
Question: Is it possible to embed languages, that are handling by traditional highlighting? (Vue/Pug)

### ISSUE THREAD

**Issue by zealot128** [nvim-treesitter/nvim-treesitter#1520]
Over at https://github.com/ikatyang/tree-sitter-vue/issues/2 we discussed on how to handle Vue embedded languages. Scss, Typescript are already working. 
There is another common embedded format, the Pug templating language (Former Jade, also similar to HAML/Slim in Ruby land).

By adding an appropriate query to queries/vue/injections.scm:

```
(template_element
	(start_tag
    	(attribute
    		((attribute_name) @lang_key (#match? @lang_key "lang"))
        	((quoted_attribute_value) @_lang (#match? @_lang "pug"))
        )
    )
    ((text) @pug)
)
```

It seems to be possible to select the correct area. I cross checked it, by using another available language (typescript/javascript) in the lang attribute, and it should work in general.

But, treesitter has no language definition for Pug yet. So my question: Is it possible to "fall back" to the Vim native syntax highlighting? 
In the other issue, one user also had reported, that by changing ``setf pug`` in the buffer, the visual selection then uses the vim highlighting.

I would be glad for any pointers, of information if it is possible! Thanks!

**Comment by theHamsta** [comment]
It's not possible to mix tree-sitter and old regex highlighting at the moment. It is however not to difficult to create a parser. Apparently somebody already started https://github.com/RianFuro/tree-sitter-pug

**Comment by zealot128** [comment]
@theHamsta Thank you for the quick answer. This looks promising! I will try to compile + install it manually later, as it is not available via TSInstall yet.

**Comment by theHamsta** [comment]
Hi, it would be possible to use tree-sitter and vim regex as long as the vim regex will find the language region by itself. Then,  you could just set `:set syntax=on` to enable regex highlighting.

**Comment by zealot128** [comment]
I've made some progress and got the parser installed.

- I've just checked out the repo, ran ``tree-sitter generate`` which only changed minor things in parser.h
- Then, I've loaded the script:

```lua
        local parser_config = require("nvim-treesitter.parsers").get_parser_configs()
    parser_config.pug = {
      install_info = {
        url = "~/OpenSource/tree-sitter-pug", -- local path or git repo
        files = {"src/parser.c", "src/scanner.cc" }
      },
      filetype = "pug", -- if filetype does not agrees with parser name
      used_by = {"vue"} -- additional filetypes that use this parser
    }
```

Then, TSInstall or TSInstallFromGrammer ran without error. 
Now, I've installed the Playground, but the parser window is empty... so I guess it did not match the file type with the parser. 
After making "set ft=pug", the Vim Regex Highlighting comes back AND the parser window has now some content.

So I guess, now it is time to make some queries.... @theHamsta any ideas to fix the Filetype detection?

**Comment by zealot128** [comment]
It works good for now with a minimum set of queries. But I think the parser needs more work. Missing several pieces of the syntax... Time to jump into the grammar stuff...

![Bildschirmfoto 2021-07-10 um 10 48 15](https://user-images.githubusercontent.com/147175/125157632-71639000-e16c-11eb-96cc-1706de7bb2ca.png)

**Comment by vigoux** [comment]
For filetype detection, we have a directory in the plugin named `ftdetect` where we have several files to detect filetypes, you should add you filetype detection here.

**Comment by clason** [comment]
Random drive-by thought: Would it be possible to create a fake `vimsyntax` parser that just pipes the text through vim (with a `filetype` annotation)? You could then inject that into a tree-sitter context.

(It wouldn't work for the reverse: embedding tree-sitter parsed regions into a non-tree-sitter parsed file, but still?)

**Comment by zealot128** [comment]
I've made some good progress with the pug parser:

https://github.com/zealot128/tree-sitter-pug/

- inline Javascript with injection queries for all "{{ }}" and vue-like attributes "v-foo", ":foo"
- pipes as Content blocks

I've added those queries to my after/queries folder:

highlights: 

```scm
(comment) @comment
(tag_name) @tag
(content) @none
(quoted_attribute_value) @string
(id) @constant
(class) @constant
(attribute_name) @label
```

injections:

```scm
(javascript) @javascript
(
   (attribute_name) @_attribute_name
   (quoted_attribute_value (attribute_value )  @javascript)
   (#match? @_attribute_name "^(:|v-bind|v-)")
)
```

I've also added a ``ftdetect/pug.vim`` with:

```vim
au BufRead,BufNewFile *.pug             set filetype=pug
```

Now, that works great for *.pug files as you can see:

![Bildschirmfoto 2021-07-10 um 17 18 19](https://user-images.githubusercontent.com/147175/125167846-d89c3700-e1a2-11eb-9122-9d79ba691871.png)

Now, there are 2 more steps:

1. Integrating it into nvim-treesitter. I would open up a PR with definition of the parser as my fork, with the queries and ftdetect. Are there any other things to consider? Am I missing something?
2. It does work for plain "template.pug" files, but when integrating into Vue, it does not work yet. The template body is not highlighted when using the injections.scm modification mentioned in the issue description. IF I change the "@pug" to any other language for test, such as "@scss" or "@typescript", it highlights the body with the according parser, though. That means, Tree-sitter is not able to map the @pug to the "pug" treeparser, despite having the ftdetect. Is there any other hint on how to tell Nvim-treesitter on how to "detect" the inline body as Pug?

**Comment by vigoux** [comment]
Great to see you are making progress then !

**Comment by theHamsta** [comment]
I think we answered this question that it's not possible. A parser has been created to support Pug nonetheless.
