### ISSUE TITLE
[Question/Bug] terraform parser is triggered by packer's buffers

### ISSUE THREAD

**Issue by akinsho** [nvim-treesitter/nvim-treesitter#1524]
Since the change that introduced the `hcl` parser, buffers created by [packer]() (the plugin manager) have been being highlights using that parser, which results in a screen full of errors.

![image](https://user-images.githubusercontent.com/22454918/124820704-bc5f8680-df65-11eb-82ba-71ab3a721e99.png)

https://github.com/nvim-treesitter/nvim-treesitter/blob/53d92f65bddf6623000b81ca5beae5ee3a6a736e/lua/nvim-treesitter/parsers.lua#L363

I work very rarely with terraform, but was under the impression that the current filetype was `terraform`, the addition in the line above seems to indicate that it should also match the `packer` ft.

Having a look around I discovered that HashiCorp have developed a new technology called [packer](https://www.packer.io/) with an extension of `pkr.hcl` so I guess my question is there another filetype for terraform actually called packer cc @MichaHoffmann

If so, then packer needs to change the filetype it uses to be more unique (which it might do anyway), at the moment anyone who is using both the `maintained` installation argument and `packer` is seeing error messages in all their packer buffers.

**Comment by MichaHoffmann** [comment]
Hey @akinsho,

i think terraform is by far the most used filetype for this parser so its probably best to be pragmatic and remove `packer` and `nomad` here for now, possible reintroducing them at a later point with an appropriate filetype then.

**Comment by stsewd** [comment]
PR merged!
