### ISSUE TITLE
bracket highlight conflict with rainbow

### ISSUE THREAD

**Issue by minrui-hust** [nvim-treesitter/nvim-treesitter#1529]
**Is your feature request related to a problem? Please describe.**

rainbow is good plugin for highlight bracket, but the nvim-treesitter hightlight override it

**Describe the solution you'd like**
an config to disable hightlight for bracket, leave for rainbow

**Describe alternatives you've considered**

**Additional context**

**Comment by theHamsta** [comment]
You can set this map entry to nil https://github.com/p00f/nvim-ts-rainbow/blob/72e51738bb6bf966f3f0b336739eb02cf3f8266a/lua/rainbow/internal.lua#L130-L131

Linking TSPunctuationBracket too something non-existenting probably also works.

**Comment by minrui-hust** [comment]
Thanks, I will try it.

**Comment by theHamsta** [comment]
Is this solved?
