### ISSUE TITLE
Legacy syntax highlights appear in the visual selection (only for the initial buffer load)

### ISSUE THREAD

**Issue by vigoux** [nvim-treesitter/nvim-treesitter#1542]
### Discussed in https://github.com/nvim-treesitter/nvim-treesitter/discussions/1539

<div type='discussions-op-text'>

<sup>Originally posted by **creasty** July  9, 2021</sup>
When I open a `.tsx` file and make a visual selection, highlights in the visual selection get rendered in different colors.
It can be fixed by reloading the buffer with `:e!` or opening another file with the same filetype, or by disabling the legacy syntax system completely with `:syntax off`.

Perhaps, some kind of race condition?

| 1. Initially opened | 2. Visual selection | 3. After `:e!` or  `:syntax off` |
|---|---|---|
| <img width="1003" alt="Screen Shot 2021-07-09 at 12 35 26" src="https://user-images.githubusercontent.com/1695538/125020238-757fa700-e0b3-11eb-9957-e3361d1509a8.png"> | <img width="1027" alt="Screen Shot 2021-07-09 at 12 35 51" src="https://user-images.githubusercontent.com/1695538/125019834-a4e1e400-e0b2-11eb-948b-77c0fee031f0.png"> | <img width="1096" alt="Screen Shot 2021-07-09 at 12 36 23" src="https://user-images.githubusercontent.com/1695538/125019838-a8756b00-e0b2-11eb-94e9-ec0d0f7f13f4.png"> | 

FYI, this is the same file rendered with the legacy syntax highlighter (`TSBufDisable highlight`):

<img width="300" alt="Screen Shot 2021-07-09 at 12 36 38" src="https://user-images.githubusercontent.com/1695538/125019843-a90e0180-e0b2-11eb-83db-d207e65ec552.png">
</div>

**Comment by stsewd** [comment]
@creasty can you replicate this with a minimal init.vim? As mentioned, this may be due to a plugin.

**Comment by elianiva** [comment]
pretty sure this is caused by a plugin, I came across this issue a few weeks ago and it was caused by vim-matchup which was loaded later, i.e not loaded in startup

**Comment by creasty** [comment]
Okay, I'll try... but It'll take some time since I use 47 plugins and the lazy loading feature of a plugin manager.

@elianiva Could you elaborate on how vim-matchup caused the issue? I need to know what to look for.

**Comment by elianiva** [comment]
> Could you elaborate on how vim-matchup caused the issue? I need to know what to look for.

I was loading vim-matchup *after* the startup, I was loading it on `CursorMoved` event. 

You could try binary search your configurations and see if the issue disappear, that's what I did to find the problem

**Comment by creasty** [comment]
I've figured out that it has to do with https://github.com/windwp/nvim-ts-autotag being lazy-loaded only for certain filetypes.
Changing it to be loaded at the startup solved the problem.

https://github.com/creasty/dotfiles/commit/53e16622a940b93c7bd9136aac107e88d01a08dc

Thanks for the help.
