### ISSUE TITLE
E5108: Error executing lua [string ":lua"]:1: attempt to index a boolean value [/nvim-treesitter/plugin/nvim-treesitter.vim:15]

### ISSUE THREAD

**Issue by sfbr** [nvim-treesitter/nvim-treesitter#1545]
I have tried everything; all dependencies are available (tree-sitter, git, gcc, neovim with ABI 13), I included only 'c' as a language to install, installed fresh a million times, made sure I had LuaJIT 2.1-beta3 as the installer would suggest... I can't convince nvim-treesitter to stop indexing a boolean.

I'm seeing from some sources that `require` returns a boolean under certain circumstances (unavailable resource), but I messed with my load order and it did not make a difference.

**Comment by stsewd** [comment]
@sfbr can you provide the file you are using and a minimal init.vim?

**Comment by sfbr** [comment]
The name of my treesitter config lua file conflicted with the plugin itself... renamed to "treesitter-conf.lua" and the problem was solved.
