### ISSUE TITLE
Fold bare compound statements in C/C++

### ISSUE THREAD

**Issue by ecnerwala** [nvim-treesitter/nvim-treesitter#1565]
C and C++ permit bare (top-level) compound statements (brace-enclosed blocks), typically used to introduce temporary local scopes. Bare compound statements should be identified as folds like other block structures. This is a little nontrivial, because the `compound_statement` node is also used for the bodies of if/for/while statements, but we probably do not want mostly-redundant folds when people use the brace on a separate line, like
```
if (a)
{
  // code
}
```

The argument could be made that we should always only fold the `compound_statement`, so the above example would look like
```
if (a)
-- Folded { //code }
```
but I suspect people wouldn't want that, so I think we'd have to go for a more complex solution.

**Comment by ecnerwala** [comment]
Actually, it looks like vim's builtin `foldmethod=syntax` folds exactly on `compound_statement`s, so maybe the only-`compound_statements` suggestion isn't quite so bad.

**Comment by theHamsta** [comment]
You can change the folds in your personal config via
```lua
      if require("nvim-treesitter.parsers").has_parser "python" then
        local folds_query = [[
  [
      (compound_statement)
  ] @fold
  ]]
        require("vim.treesitter.query").set_query("c", "folds", folds_query)
        require("vim.treesitter.query").set_query("cpp", "folds", folds_query)
```

I personally like also `(_) @fold` for most languages.

I personally also wanted to have `compound_statement` in the beginning. But after some discussion it was decided to have them on the semantic level which has also some arguments. `foldmethod=syntax` can't do anything really sophisticated so I wouldn't count that as an argument.

It's true that we have to make configuring and adapting particular aspects of the queries easier.
