### ISSUE TITLE
Number column background color is the same as primary background, except if relativenumber

### ISSUE THREAD

**Issue by oryband** [nvim-treesitter/nvim-treesitter#1569]
- Should the number column be the same color as the primary background color? IIRC it should be a different one, like the background color of the lines with the relative number in the screenshot.
- The `relativenumber` background is different than the other lines.

![image](https://user-images.githubusercontent.com/115387/125454792-24953a3f-f6a0-47ea-976b-84f564cf09e0.png)

**Comment by gegoune** [comment]
I don't think that has anything to do with treesitter. Did you mean to submit to your colorscheme repository tracker instead?

**Comment by theHamsta** [comment]
I don't think this is related to our repo. This is either a issue with your color scheme or a rendering issue upstream Neovim. We don't set own highlights and just link to existing ones

**Comment by stsewd** [comment]
Was already mentioned in https://github.com/RRethy/nvim-base16/issues/16 that's the current behavior of the theme.

**Comment by oryband** [comment]
Thanks for the response people. Got you.
