### ISSUE TITLE
Nvim-Treesitter colors for R script not showing

### ISSUE THREAD

**Issue by ECon87** [nvim-treesitter/nvim-treesitter#1576]
**Describe the bug**

When in normal mode, the color highlighting is not showing in R scripts (i.e., filetype=r) for the sonokai and gruvbox-material color-schemes.
However,  I can see the color highlighting when I am in visual mode (see pictures below).  Other color-schemes work fine with R and nvim-treesitter. The maintainer of sonokai and gruvbox-material twas able to replicate but thinks is an nvim-treesitter issue.

Finally, highlighting works fine for R with other color-schemes. So, I am not really sure what the source of the bug is. But the issue occurs both with neovim-nightly v0.6 and neovim v0.5.

**To Reproduce**

<details>
<code>

```
filetype off

call plug#begin('~/.vim/plugged')
Plug 'sainnhe/sonokai'
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}  " We recommend updating the parsers on update
Plug 'nvim-treesitter/playground'
Plug 'jalvesaq/Nvim-R', {'brach': 'stable', 'for': ['R', 'r']}
call plug#end()
filetype plugin indent on

if has('termguicolors')
    set termguicolors
endif
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
let &t_ZH="\e[3m"
let &t_ZR="\e[23m"
set background=dark
let g:sonokai_style = 'atlantis'
let g:sonokai_enable_italic = 1
let g:sonokai_disable_italic_comment = 1
colorscheme sonokai

lua <<EOF
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
    custom_captures = {
      -- Highlight the @foo.bar capture group with the "Identifier" highlight group.
      ["foo.bar"] = "Identifier",
    },
  },
}

require "nvim-treesitter.configs".setup {
  playground = {
    enable = true,
    disable = {},
    updatetime = 25, -- Debounced time for highlighting nodes in the playground from source code
    persist_queries = false, -- Whether the query persists across vim sessions
    keybindings = {
      toggle_query_editor = 'o',
      toggle_hl_groups = 'i',
      toggle_injected_languages = 't',
      toggle_anonymous_nodes = 'a',
      toggle_language_display = 'I',
      focus_language = 'f',
      unfocus_language = 'F',
      update = 'R',
      goto_node = '<cr>',
      show_help = '?',
    },
  }
}
EOF
```
</code>
</details>

**Expected behavior**

I expect the colors to render.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

```

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.4.2 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - python         ✓ ✓ ✓ ✓ ✓ 
  - r              ✓ ✓ . . . 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

```
</code>
</details>

**Output of `nvim --version`**

<details>
<code>

```
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.0/build/config -I/build/neovim/src/neovim-0.5.0/src -I/usr/include -I/build/neovim/src/neovim-0.5.0/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.0/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

</code>
</details>

**Additional context**

Here is what it looks in normal mode:

![treesitter_0](https://user-images.githubusercontent.com/46789268/125712540-483445f5-7a0e-46d3-bc22-13287d9f9205.png)

and here how it looks in visual mode:

![treesitter_1](https://user-images.githubusercontent.com/46789268/125712587-66111826-5c9c-4a24-a603-e32da8448c64.png)

EDIT 1: The bug is present with [Oceanic-next (tree-sitter compatable theme)](https://github.com/mhartington/oceanic-next) as well. So it might have something to do with the r-module.

EDIT 2: Just to clarify the color-schemes that work in R are gruvbox, zenburn, and others that I think might not have explicit tree-sitter support.

EDIT 3: Somehow I get partial highlighting in some files now (this is the oceanic theme):

![Screenshot_2021-07-15_18-36-59](https://user-images.githubusercontent.com/46789268/125871218-a2a3decb-0255-481f-9fef-58d69c8bc55f.png)

**Comment by stsewd** [comment]
Hi, I think this may be to the vim syntax being activated. Can you try this branch https://github.com/nvim-treesitter/nvim-treesitter/pull/1550?

**Comment by ECon87** [comment]
Hi,

thanks for responding. It kills my syntax highlighting completely. But I might be doing it wrong.

It's so weird that it only happens for R scripts

**Comment by stsewd** [comment]
@ECon87 can you share the file you are using to test?

**Comment by ECon87** [comment]
Sure thing (I hope you mean my init and R script). I am using Alacritty but I get the same behavior in the XFCE terminal.

First, here is a minimal init.vim

```
filetype off

call plug#begin('~/.vim/plugged')


Plug 'mhartington/oceanic-next'

" Treesitter
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}  " We recommend updating the parsers on update
Plug 'nvim-treesitter/playground'

" Nvim-R: R specific REPL
Plug 'jalvesaq/Nvim-R', {'brach': 'stable', 'for': ['R', 'r']}
" Plug 'jalvesaq/Nvim-R', {'brach': 'stable', 'on': []}

call plug#end()
filetype plugin indent on


lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained",
  highlight = {
    enable = true
  },
  playground = {
    enable = true,
    disable = {},
    updatetime = 25, -- Debounced time for highlighting nodes in the playground from source code
    persist_queries = false, -- Whether the query persists across vim sessions
    keybindings = {
      toggle_query_editor = 'o',
      toggle_hl_groups = 'i',
      toggle_injected_languages = 't',
      toggle_anonymous_nodes = 'a',
      toggle_language_display = 'I',
      focus_language = 'f',
      unfocus_language = 'F',
      update = 'R',
      goto_node = '<cr>',
      show_help = '?',
    },
  }
}
EOF

syntax enable
colorscheme OceanicNext

```

And here is a minimal R code.

```
library(dplyr)

# ######################
# DEF FUNS
# ######################

get_corr_gram <- function(df, excluded) {
  corr <- df %>% select(-!!as.symbol(excluded)) %>% cor()
  corr <- round(corr, 1)
  p_mat <- select(df, -!!as.symbol(excluded)) %>% cor_pmat()
  return(list(corr, p_mat))
}


find_vars <- function(df, regexpress) {
  print(names(df)[grepl(regexpress, names(df))])
}
```

**Comment by stsewd** [comment]
@ECon87 thanks. Looks like this is the same problem as https://github.com/nvim-treesitter/nvim-treesitter/issues/1544.

Your file looks like this with tree-sitter only syntax using oceancnext

![Screenshot-20210717153008-641x311](https://user-images.githubusercontent.com/4975310/126048696-c5068611-95ac-472a-98d6-506bc87ba9bb.png)

But that's because that theme is defining those HL groups to look like that, this is how it looks like with the default theme


![image](https://user-images.githubusercontent.com/4975310/126048768-b4b937f8-302f-4d66-ba75-a8cdd706b6b3.png)


or with tokyonight

![image](https://user-images.githubusercontent.com/4975310/126048783-8e649f9a-dd48-4f90-9e30-d02ae5d6468f.png)


Please use a theme with tree-sitter support or change the hl groups to your like, you could also improve the queries if you think some are missing https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/r/highlights.scm
