### ISSUE TITLE
 "/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:347: No handler for any-of?" 

### ISSUE THREAD

**Issue by christianparpart** [nvim-treesitter/nvim-treesitter#1577]
Hey,

since a OS update last night my neovim (latest master branch) keeps blaming at me like so:

![image](https://user-images.githubusercontent.com/56763/125853178-c60fe4d3-6b6e-4055-96f5-ca18785f8843.png)

Updating neovim, fully recompiling, updating respective python module, updating treesitter and reinstalling c/cpp plugins, nothing helped. I am kinda clueless what to do from here on.

What does this message tell me, and how can it be mitigated?

I am indeed thinking it might be due to the OS update, but the error does not help me understanding the problem.

**Comment by theHamsta** [comment]
You're sure the latests master get's executed and not another hidden Neovim version (`/usr/share/` looks like a system installation of Neovim)? The message basically tells you that your runtime files are outdated. You can grep you Neovim runtime and the one from git for `any-of?` and compare.

**Comment by christianparpart** [comment]
> You're sure the latests master get's executed and not another hidden Neovim version (`/usr/share/` looks like a system installation of Neovim)? The message basically tells you that your runtime files are outdated (not 0.5 but older). You can grep you Neovim runtime and the one from git for `any-of?` and compare.

For some reason, my `$HOME/bin/vim` pointed to `/usr/bin/nvim` and not `/usr/local/bin/nvim`. Fixing my symlink fixed it. :facepalm:  Wow. Many thanks, and sorry for the inconvenience. It's a really nice & helpful project ;-)
