### ISSUE TITLE
Why not support markdown? 

### ISSUE THREAD

**Issue by kdurant** [nvim-treesitter/nvim-treesitter#1578]
[tree-sitter-markdown](https://github.com/ikatyang/tree-sitter-markdown)

**Comment by Joakker** [comment]
Iirc, there's still some kinks to be ironed out from that implementation, which is why it hasn't been introduced yet into this repo

**Comment by theHamsta** [comment]
It was in the repo but the parser causes defaults and will crash Neovim. See #1202

**Comment by stsewd** [comment]
Please subscribe to https://github.com/nvim-treesitter/nvim-treesitter/issues/872
