### ISSUE TITLE
The highlights are not working onload 

### ISSUE THREAD

**Issue by Alienover** [nvim-treesitter/nvim-treesitter#1608]
**Describe the bug**
The highlights and the playground are not working on nvim launch. But when I run `:TSModuleInfo`, the highlight and playground work.

https://user-images.githubusercontent.com/12182069/126331610-fcb9d6fc-c580-4254-a6bf-1b07445b8f87.mp4

**To Reproduce**
Just open any file with nvim

**Expected behavior**
The highlights and playground should work anytime I launch the nvim.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

Paste the output here
![image](https://user-images.githubusercontent.com/12182069/126329238-09c51db8-cce5-4d1d-86e5-5d0184122217.png)

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

Paste the output here
![image](https://user-images.githubusercontent.com/12182069/126329340-23eafcf1-2095-414d-a0f8-27d0582f098c.png)

</code>
</details>

**Additional context**
The `treesitter` config for packer is defined in `plugins.lua` and it's own config is in `config.treesitter-config``

The `plugins.lua` is loaded by `vim.defer_fn`.
```lua
-- init.lua
vim.defer_fn(
    function()
        require "plugins"
    end,
    0
)

-- plugins.lua
return require"packer".setup({
  function(use)
    -- 
    -- Other plugins config here
    --
    use {
      "nvim-treesitter/nvim-treesitter",
      run = ":TSUpdate",
      config = function()
        require "config/treesitter-config"
      end,
      requires = {
          "andymass/vim-matchup",
          {"nvim-treesitter/playground", cmd = {"TSHighlightCapturesUnderCursor", "TSPlaygroundToggle"}}
      }
    }
  end
})
```

**Comment by Alienover** [comment]
![image](https://user-images.githubusercontent.com/12182069/126335646-598bf24b-905f-448c-b4a5-310d14300e8d.png)
I tried the stable neovim. The issue is still there.

**Comment by ray-x** [comment]
Also saw a similar issue. I am using a statement like this as well

```
vim.defer_fn(
    function()
        require "plugins"
    end,
    0
)
```

**Comment by stsewd** [comment]
I believe this is a problem with packer lazy loading the plugin, if you load the configs at the end of your init.vim/init.lua it should work as expected.

**Comment by stsewd** [comment]
If you find the correct way to use packer with this plugin, please update our wiki https://github.com/nvim-treesitter/nvim-treesitter/wiki/Installation

**Comment by ray-x** [comment]
I am using treesitter in a more hacky way.  I will check the file size and dynamic load treesitter based on its size.

**Comment by kyazdani42** [comment]
if you defer initializiation of the plugins, then it will not function as expected on start. defer 0 acts like schedule and adds the callback to the event loop which will run once nvim has started initializing.
These issues are related to user configurations, i'm closing this.
