### ISSUE TITLE
broken highlighting

### ISSUE THREAD

**Issue by alanlai1234** [nvim-treesitter/nvim-treesitter#1618]
**Describe the bug**

Highlighting breaks from time to time.(cpp)

**To Reproduce**

Keep editing the file and it will appear.

**Expected behavior**

Highlighting should be formatted and neat.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.4.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I
  - cpp            ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.0/build/config -I/build/neovim/src/neovim-0.5.0/src -I/usr/include -I/build/neovim/src/neovim-0.5.0/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.0/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**

<img width="239" alt="螢幕擷取畫面 2021-07-23 164220" src="https://user-images.githubusercontent.com/45114742/126757896-9896a096-90d2-4ed4-a2f9-04c65799b83b.png">

```
:lua <<EOF
require'nvim-treesitter.configs'.setup {
  highlight = {
	enable = true,              
	additional_vim_regex_highlighting = false,
  },
}
vim.treesitter.highlighter.hl_map.error = nil
require "nvim-treesitter.highlight"
EOF
```

**Comment by alanlai1234** [comment]
is anyone here?

**Comment by alanlai1234** [comment]
turns out to be Coc.nvim problem

**Comment by stsewd** [comment]
sorry for the late reply! yes, you should try disabling some plugins or using a minimal init.vim to see if the problem is from a plugin.
