### ISSUE TITLE
[Question] Does the C parser also parse header files?

### ISSUE THREAD

**Issue by HumblePresent** [nvim-treesitter/nvim-treesitter#1630]
I've been using the highlights module with the C parser and noticed today that it doesn't seem to operate on header files. Is this just a current limitation of the parser or do I need to enable that somehow?

**Comment by theHamsta** [comment]
It will operate on all files with filetype C set. When C++ is set it will use the c++ parser.

**Comment by HumblePresent** [comment]
So is the filetype determined by the file extension?

**Comment by theHamsta** [comment]
It depends on your config but normally vim would set filetypes based on extensions. You also have to have the highlighting module enabled.

You can check the current filetype with `:echo &filetype`

**Comment by HumblePresent** [comment]
Yeah it looks like vim considers header files to be `cpp` type. It's working now that I installed the cpp parser. Thanks!
