### ISSUE TITLE
'Error during compilation' on `TSInstall haskell`

### ISSUE THREAD

**Issue by carljohnesan** [nvim-treesitter/nvim-treesitter#1638]
Sorry for creating this issue, I understand that the bug isn't of nvim-treesitter, but I'm just desperate to get it working for haskell (all other languages were compiled fine).

My OS: macOs 10.13.6 High Sierra
Neovim: 0.5.0

`.vimrc` part regarding tree-sitter:
```vim
if has('nvim')
  Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
endif
```

`init.vim`:
```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc

lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = "all",
  highlight = {
    enable = true,
  },
}
EOF
```

This is the output from `:TSInstallSync haskell` (`Sync` part here because output seems to be more informative yet concise):
```text
src/scanner.cc:240:15: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
  for (auto i : state.indents) {
              ^
src/scanner.cc:285:10: error: expected expression
  return [=](State & state) {
         ^
src/scanner.cc:308:57: error: expected expression
Peek operator&(const Peek & l, const Peek & r) { return [=](uint32_t c) { return l(c) && r(c); }; }
                                                        ^
src/scanner.cc:309:57: error: expected expression
Peek operator|(const Peek & l, const Peek & r) { return [=](uint32_t c) { return l(c) || r(c); }; }
                                                        ^
src/scanner.cc:310:30: error: expected expression
Peek not_(Peek con) { return [=](uint32_t c) { return !con(c); }; }
                             ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 warnings and 20 errors generated.
Error during compilation
Failed to execute the following command:
{
  cmd = "cc",
  err = "Error during compilation",
  info = "Compiling...",
  opts = {
    args = { "-o", "parser.so", "-I./src", "src/parser.c", "src/scanner.cc", "-shared", "-Os", "-lst
dc++", "-fPIC" },
    cwd = "/Users/aaaaaaa/.local/share/nvim/tree-sitter-haskell"
  }
}
```

I don't know what to do really, so please give me some suggestions if you can.
I guess I would be fine if I was on Catalina at least, but my mac doesn't support it. On my Windows 10 + WSL2 on pc the plugin worked fine with all the languages.

**Comment by stsewd** [comment]
> src/scanner.cc:240:15: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]

That looks like your version of the compiler isn't the right one. What c++ compiler do you have in your windows and mac machine? Also, you can try with `cc={another-c++-compiler} nvim` and test with clang or similar.

**Comment by carljohnesan** [comment]
I have `gcc` of version `9.3.0` on windows wsl2 (so on ubuntu in fact), and `Apple LLVM version 10.0.0 (clang-1000.10.44.4)` on my mac.
Running `cc={another-c++-compiler} nvim` didn't help

**Comment by theHamsta** [comment]
Also make sure that gcc has its libstdc++ and does not use whatever your OS provides as libc++

**Comment by carljohnesan** [comment]
Thank you. Any installations using `brew` takes hours on my system, so I'll just install other OS
