### ISSUE TITLE
Remove or mention that kotlin parser is slow.

### ISSUE THREAD

**Issue by abellaismail7** [nvim-treesitter/nvim-treesitter#1643]
I came here because I can't open an issue in [their repository](https://github.com/tormodatt/tree-sitter-kotlin) which is suspicious!!
I know that Kotlin has dozens of features which makes parsing it harder.
So I did some investigations and I found out that the Kotlin's parser.c is huge ([92M before compiling](https://github.com/tormodatt/tree-sitter-kotlin/blob/master/src/parser.c), 18M after compiling) , which means 
40 bigger than Bash
80 bigger than Js
It takes more than 10s seconds to open every Kotlin file even with files that contain only one line .

So I believe that it's not usable or at least slow. so I think you guys need to mention that in Readme or just remove it

**Comment by theHamsta** [comment]
It became 10x longer to load with the change from 0.18.X to 0.19.X

**Comment by Joakker** [comment]
I have the suspicion that the kotlin parser is so monumentally slow because it translates the [grammar](https://kotlinlang.org/docs/reference/grammar.html) directly, which results in dozens of nodes for even the simplest of constructs. I've been developing a replacement which simplifies the grammar significantly, though it might be a while before it's PR ready

**Comment by tormodatt** [comment]
just wanted to say that it's my fork that you are referring to @abellaismail7 , and I see now that I've forgot to enable issues. my mistake! having a "suspicious" fork was not my intention :) 

the fork was created, as @theHamsta mentioned, mainly to make it run on 0.19.X. I did not find the time to all the other issues with it, but I'm glad @Joakker  did! :)

**Comment by quangnguyen30192** [comment]
Just updated the plugin and I dont know why I got this when doing :TSUpdate
```
Error during tarball extraction.
Failed to execute the following command:
{
  cmd = "tar",
  err = "Error during tarball extraction.",
  info = "Extracting...",
  opts = {
    args = { "-xvzf", "tree-sitter-kotlin.tar.gz", "-C", "tree-sitter-kotlin-tmp" },
    cwd = "/Users/qnguyen/.local/share/nvim"
  }
}
```

**Comment by quangnguyen30192** [comment]
No worry, just installed it again and it works. Thanks for the fix

**Comment by theHamsta** [comment]
Had the same problem. The issue is that the git SHA will update immediately but the Github URL only after restart.

**Comment by abellaismail7** [comment]
thanks for @Joakker and @theHamsta for The new parser it works perfectly fine for me
