### ISSUE TITLE
Vue highlights everything with vueTsTag

### ISSUE THREAD

**Issue by mcchrish** [nvim-treesitter/nvim-treesitter#1646]
**Describe the bug**

I'm not sure where to report this issue whether here or https://github.com/ikatyang/tree-sitter-vue.

Example text:
```vue
<template>
    <div class="field has-addons">
        <span>hello</span>
    </div>
</template>
```

The highlight is off, everything is bold. The only ones that should be bold are the `TsTag` highlight. Since all nodes including attributes and text are highlighted with `vueTsTag` everything is bold.

<img width="444" alt="Screen Shot 2021-07-31 at 1 04 52 PM" src="https://user-images.githubusercontent.com/7200153/127729321-ff36214a-e848-43d6-82cc-e792394845ae.png">
<img width="456" alt="Screen Shot 2021-07-31 at 1 05 17 PM" src="https://user-images.githubusercontent.com/7200153/127729659-f01cdc52-2d2c-4e9d-b467-adbc5afc85a2.png">

**To Reproduce**

1. Use treesitter playground to inspect highlight groups used.
2. Open any vue file.

config:
```lua
require("nvim-treesitter.configs").setup {
	ensure_installed = {
		"css",
		"graphql",
		"html",
		"lua",
		"javascript",
		"php",
		"typescript",
		"vue",
	},
	matchup = {
		enable = true,
	},
	highlight = {
		enable = true,
	},
	indent = {
		enable = true,
	},
}
```

**Expected behavior**

Tag names, attributes, values etc should have a distinct highlight. I think an example of a correct one is from html:

<img width="316" alt="Screen Shot 2021-07-31 at 1 12 15 PM" src="https://user-images.githubusercontent.com/7200153/127729429-666afce0-a181-4444-9ded-afe3e14f6b47.png">
<img width="498" alt="Screen Shot 2021-07-31 at 1 11 47 PM" src="https://user-images.githubusercontent.com/7200153/127729535-f0771bee-4931-4f01-a15a-eb5bd8668d9c.png">

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.17.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - css            ✓ . ✓ ✓ ✓ 
  - graphql        ✓ . . ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - vue            ✓ . ✓ . ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
</code>
</details>

**Output of `nvim --version`**

<details>
<code>
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/config -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/include
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.5.0/share/nvim"

Run :checkhealth for more info
</code>
</details>

**Additional context**

Colorscheme is https://github.com/pgdouyon/vim-yin-yang

**Comment by stsewd** [comment]
This looks like a problem with the query https://github.com/nvim-treesitter/nvim-treesitter/blob/8ab1a5e5f7087c4ed49c42e8d14ecb9d91d58363/queries/vue/highlights.scm#L3-L9

Removing `template_element` should fix your example, I'm not familiar with vue, so I'm not sure about the other elements that are captured as a tag.

Also, you should still see some other captures, that's probably because of https://github.com/nvim-treesitter/nvim-treesitter/issues/1506
