### ISSUE TITLE
How to stop ALL_CAPS names to be parsed as a constant

### ISSUE THREAD

**Issue by jabra98** [nvim-treesitter/nvim-treesitter#1647]
I suppose ALL_CAPS identifiers are automatically added to the TSConstant group. How can I avoid this?

**Comment by stsewd** [comment]
You'll need to add a custom query for all queries, to something like (for python)


```scm
-- in ~/.config/nvim/after/queries/python/hightlights.scm
((identifier) @none
 (#match? @none "^[A-Z][A-Z_0-9]*$"))
((identifier) @yourgroup
 (#match? @yourgroup "^[A-Z][A-Z_0-9]*$"))
```

If you want just to change the color of all constants, you can link the `TSConstant` hl group to anything of your liking.

**Comment by theHamsta** [comment]
You can also `require 'nvim-treesitter.highlight` and then set `['constant]' in `vim.treesitter.highlighter.hl_map` to something non-existing (nil will also soon work) or map `TSConstant` to a non-existing highlight group. I think there is nothing in TSConstant that isn't bases on the ALL CAPS RULE. 

https://github.com/theHamsta/nvim-treesitter/blob/d7e509f3cceddcf4cfc02d45562754136852869d/lua/nvim-treesitter/highlight.lua#L9-L23
