### ISSUE TITLE
Any function to check whether `nvim-treesitter` works in a file?

### ISSUE THREAD

**Issue by UzimakiNaruto** [nvim-treesitter/nvim-treesitter#1649]
I'm use the `incremental selection` feature.

 and i want to remap the keymap in file that treesitter works. keep it as it is in file that treesitter not works.

Now i'm maintained an installed parsers list.
Like 

```vimscript
    func s:treesitter_support()
        return index(get(g:, 'treesitter_installed_parsers', []), &ft) > -1
    endfunc

    Plug 'nvim-treesitter/nvim-treesitter', {'do': 'TSUpdate'}
        nmap <expr> v (<SID>treesitter_support() ? "gnn" : "v")
        vmap <expr> v (<SID>treesitter_support() ? "grn" : "v")
        vmap <expr> V (<SID>treesitter_support() ? "grm" : "V")
```

the `treesitter_installed_parsers` is the list that installed parsers.

1. Do we have any function to check whether treesitter works in a file?
2. Do we have any function to execute `incremental selection` instead of use the keymaps config only?

**Comment by theHamsta** [comment]
> Do we have any function to check whether treesitter works in a file?
https://github.com/theHamsta/nvim-treesitter/blob/d7e509f3cceddcf4cfc02d45562754136852869d/lua/nvim-treesitter/parsers.lua#L693

It's possible to check whether a certain filetype has a parser and there's also a function to check whether a certain module is active. `require "vim.treesitter.highlighter".active[bufnr]` would work to check whether the current file has a highlighter. You can use luaeval to evaluate lua expressions from Vim land.

> Do we have any function to execute incremental selection instead of use the keymaps config only?

https://github.com/theHamsta/nvim-treesitter/blob/d7e509f3cceddcf4cfc02d45562754136852869d/lua/nvim-treesitter/incremental_selection.lua#L112

`:lua require'nvim-treesitter.incremental_selection'.incremental_scope()<CR>`

**Comment by UzimakiNaruto** [comment]
@theHamsta Thanks 👍 .
The doc is too difficult to found 😢

**Comment by UzimakiNaruto** [comment]
@theHamsta It works. Thanks again.
