### ISSUE TITLE
Custom git clone prefix for language extensions? 

### ISSUE THREAD

**Issue by glyh** [nvim-treesitter/nvim-treesitter#1650]
**Is your feature request related to a problem? Please describe.**

I'm trying to install some languages via `:TSInstall`, which clone files from github. 

It'll takes forever (because of the censorship of www in my country) so I need to setup some CDN, like replace `github.com` with `hub.fastgit.org`. 

However, there doesn't seem to be a config that I can achieve this.  

**Describe the solution you'd like**
Add options for specifying prefix for git clone. 

**Describe alternatives you've considered**
Use git proxy, but it would be better if there's just an option.

**Comment by theHamsta** [comment]
You could program a small loop that just replaces the parser addresses.

```lua
local parsers = require "nvim-treesitter.parsers".get_parser_configs()

for _, p in pairs(parsers) do
   p.install_info.url = p.install_info.url:gsub("github.com", "some replacement")
end
```
I'm on mobile so code might contain flaws.

**Comment by glyh** [comment]
> You could program a small loop that just replaces the parser addresses.
> 
> ```lua
> local parsers = require "nvim-treesitter.parsers".get_parser_configs()
> 
> for _, p in pairs(parsers) do
>    p.install_info.url = p.install_info.url:gsub("github.com", "some replacement")
> end
> ```
> 
> I'm on mobile so code might contain flaws. So let me work whether it works for you. Should be done before the setup call

Thanks a lot, I approach this via fennel (lisp compiled to lua): 
```lua
(defn- fix-cdn [github-original]
  (: github-original :gsub "github.com" "hub.fastgit.org"))

(let [parser-confs (parsers.get_parser_configs)]
  (each [parser _ (pairs parser-confs)]
    (a.update-in parser-confs [parser :install_info :url] fix-cdn)))
```

**Comment by theHamsta** [comment]
@glyh feel free to add this information to the installation wiki!
