### ISSUE TITLE
Is it possible to get the highlight/syntax group of the text under cursor

### ISSUE THREAD

**Issue by urbainvaes** [nvim-treesitter/nvim-treesitter#1654]
**Is your feature request related to a problem? Please describe.**
Some time ago I wrote [a plugin](https://github.com/urbainvaes/vim-macaw) to interactively change the foreground and background colours of the text under the cursor (or more precisely, of the highlight group to which the text under the cursor belongs), and at the moment the plugin doesn't work with `nvim-treesitter`. Hence my question: Is there a function to obtain the highlight group for the text under the cursor?

**Comment by vigoux** [comment]
Hi, you should try the [playground](https://github.com/nvim-treesitter/playground) ?
There is a command named `TSHighlightCapturesUnderCursor` exactly for that.

**Comment by urbainvaes** [comment]
Thank you very much! I was just about to comment about what you mention in your edit;  it'd be great to have access to `M.get_treesitter_hl()` or something like that -- something that can then be parsed. :)

**Comment by vigoux** [comment]
I'll try to see what I can do.
Maybe we'll be able to create a function that returns the ordered table of the highlights applied.

**Comment by urbainvaes** [comment]
Many thanks, that'd be great!

**Comment by urbainvaes** [comment]
In fact, the Lua functions are accessible without changes to your code, so I managed to fix the issue. Thanks again for pointing me to `treesitter-playground`!

My fix, just FYI: https://github.com/urbainvaes/vim-macaw/commit/be633f850fb54ed71cc6a1d46ee788380b7393b5

**Comment by figsoda** [comment]
I would still like to have a function similar to `synstack` for treesitter so I don't have to have 20 lines of code for such a simple task or parse the output from playground which is inefficient

**Comment by urbainvaes** [comment]
That'd be idea!! Perhaps an easy way to implement this would be to use a list of lists (or of dictionaries), instead of a list of strings?

**Comment by myarcana** [comment]
Why doesn't treesitter want to (best-effort?) synchronise `synstack()` with itself?

**Comment by clason** [comment]
Because a) it's a completely different syntax engine, so this kind of integration is far from trivial and b) Neovim 0.9 already has `:Inspect`, which covers this use case fully.
