### ISSUE TITLE
[New] Tree sitter for zig

### ISSUE THREAD

**Issue by maxxnino** [nvim-treesitter/nvim-treesitter#1656]
## Info
> I'm working on new tree sitter parse for zig, using official [zig-spec](https://github.com/ziglang/zig-spec) repo. Everything seem to working really good.
The generated c files only 3,6m which is really small,.
I need help for contribution(more test, highlight, local...)
My repo [tree-sitter-zig](https://github.com/maxxnino/tree-sitter-zig)

## Progress

- [X] Highlight
- [x] Indent
- [x] Fold
- [ ] Local

## Image

![demo](https://user-images.githubusercontent.com/34153891/128273937-9dad6483-d456-4d98-a8f5-625825e369cb.png)

**Comment by stsewd** [comment]
A good test to start would be to port the tests from the other project https://github.com/Himujjal/tree-sitter-zig/tree/master/corpus

**Comment by maxxnino** [comment]
I try, but it's not right syntax for zig. I need to wrap it in test block. It's good idea to use test in zig-spec. I write a quick and dirty test, seem to pass almost all of them( in zig-spec)

**Comment by vigoux** [comment]
Tree-sitter has it's own syntax to writ test cases, and you can run `tree-sitter test` on them right after that.

**Comment by maxxnino** [comment]
> Tree-sitter has it's own syntax to writ test cases, and you can run `tree-sitter test` on them right after that.

I did it too. Seem to passed all of the test cases. I'm usually using `tree-sitter test -u`. I just need more help to speed up the release

**Comment by vigoux** [comment]
Sadly enough, I don't think anybody here is a zig expert unfortunately. We can help for generic tree-sitter questions, but not for zig-specific topics.

**Comment by maxxnino** [comment]
@vigoux is the local working yet? I tried, but it doesn't seem to work. Can you help me with that

**Comment by vigoux** [comment]
Locals are still a work in progress, I'll see what I can do to move that forward.

**Comment by maxxnino** [comment]
My attemp with local. I want `my_const` highlight as constant as it declare above. But it doesn't seem to work. Did I miss something?

```
(VarDecl (IDENTIFIER) @definition.var)
(IDENTIFIER) @reference
(Block) @scope
```

![Untitled](https://user-images.githubusercontent.com/34153891/129433635-b4feab22-0b06-4723-b0a9-39cc8056a5ea.png)

**Comment by stsewd** [comment]
> My attemp with local. I want `my_const` highlight as constant as it declare above. But it doesn't seem to work. Did I miss something?
> 
> ```
> (VarDecl (IDENTIFIER) @definition.var)
> (IDENTIFIER) @reference
> (Block) @scope
> ```
> 
> ![Untitled](https://user-images.githubusercontent.com/34153891/129433635-b4feab22-0b06-4723-b0a9-39cc8056a5ea.png)

Currently that isn't possible, see  https://github.com/nvim-treesitter/nvim-treesitter/issues/81. Also, locals only affects things like go to definition and scope selection, not highlight.
Looks like support for the new zig parser was added, I'm closing this issue. Feel free to ask more questions on our discussions https://github.com/nvim-treesitter/nvim-treesitter/discussions or on our zulip channel
