### ISSUE TITLE
Add position to the jumplist when calling to `goto_definition`

### ISSUE THREAD

**Issue by stsewd** [nvim-treesitter/nvim-treesitter#166]
Currently, `goto_definition` doesn't add the position to the jumplist, so you can't use `<C-o>` to go back to the original position. 

Looks like this can be done, from `:h jumplist`:

> You can explicitly add a jump by setting the ' mark with "m'".  Note that calling setpos() does not do this.

**Comment by theHamsta** [comment]
Sounds great! Do you want to add that feature by creating a small `set_jump` function and test it?

I only remember that in another situation we had trouble setting the jump.
