### ISSUE TITLE
Custom Capture Groups

### ISSUE THREAD

**Issue by 1saf** [nvim-treesitter/nvim-treesitter#167]
**Is your feature request related to a problem? Please describe.**
Hello! I've been meaning to contribute to the tsx/jsx queries for nvim-treesitter, throughout me learning the ins and outs of this plugin I thought this feature might be beneficial in supporting various languages, and might a degree of customisation to users of this plugin.

I am not sure if this would be viable, but I think it would be useful for the handling of some language specific highlighting or allowing customisation of highlighting just based on preference.

**Describe the solution you'd like**
Using typescript as an example

`capturegroups.scm`
```
capturegroups = { -- custom capture groups
    typescriptreact = {
        "tsx.tag" = TSConstant -- mapping to an existing syntax group
        "tsx.tag" = TSHTMLTag -- mapping to a custom user defined syntax group, which can be picked up by the theme
        "tsx.tag" = DraculaOrange -- mapping to theme syntax group, this could allow for user customisable syntax highlighting
    }
}
```

```
(jsx_attribute (property_identifier) @tsx.tag)
```

I am unsure if you can call ```highlight default link``` programmatically, since this would essentially rely on that...I believe.

**Describe alternatives you've considered**
I've looked into achieving highlighting using the groups available, however to me, it seems pretty misleading (for maintainers) and incorrect (as the user) to define a query to classify a piece of syntax as something it is not.
Taking the above example for a tsx tag, being highlighted as a function just for a certain colour.

```
(jsx_attribute (property_identifier) @function)
```

**Additional context**
I am still learning so please excuse me if I failed to consider a case.

**Comment by theHamsta** [comment]
As a work-around you can do the following:
- create a file `queries/typescript/highlights.scm` with content `(jsx_attribute (property_identifier) @tsx.tag)`
- Add this snippet of lua code somewhere in your conig:
```lua
    require "nvim-treesitter.highlight"
    local hlmap = vim.treesitter.TSHighlighter.hl_map

    hlmap["tsx.tag"] = "DraculaOrange"
```

**Comment by 1saf** [comment]
Thank you. Is there any intention of having this sort of custom capture group for this plugin built-in though? or is this a kind of use case that doesn't really align with the goal of this plugin

**Comment by theHamsta** [comment]
I am currently working on this. I guess the only we are only missing the configuration table you were mentioning.

Extending the queries the way I described is already possible.

**Comment by 1saf** [comment]
Awesome, do you need any help documenting it?

**Comment by theHamsta** [comment]
Would you test https://github.com/theHamsta/nvim-treesitter/pull/new/custom_captures ?

**Comment by 1saf** [comment]
Sure, I will do this tomorrow. Currently it is 11PM Sun in Sydney

**Comment by 1saf** [comment]
Hey,

The document example you provided was a little incorrect. It turns out having the quotes around the key inside for a KV pair in a lua table is incorrect syntax.

This
```lua
    "foo" = "Identifier"
```
does not work but the following does.

```lua
    foo = "Identifier"
```

and the following for periods inside the key
```lua
    ["tsx.tag"] = "Identifier"
```

Apart from that, the actual targeting and highlighting worked for various scenarios I had tested. Including targeting a theme colour such as `DraculaOrange`.

Hope this helped.
