### ISSUE TITLE
Ir

### ISSUE THREAD

**Issue by zyp2005** [nvim-treesitter/nvim-treesitter#168]

**Comment by zyp2005** [comment]
It is not work.
![Uploading IMG_1847.jpeg…]()
![Uploading IMG_1848.jpeg…]()

**Comment by zyp2005** [comment]
It is not work.
![Uploading IMG_1847.jpeg…]()
![IMG_1848](https://user-images.githubusercontent.com/59333102/87243498-01db9780-c469-11ea-807c-418ab50e8cb2.jpeg)

**Comment by theHamsta** [comment]
You're probably not user the latest master of Neovim. `vim.fn` does not exits.
