### ISSUE TITLE
Fix vimspector's syntax highlighting

### ISSUE THREAD

**Issue by igorlfs** [nvim-treesitter/nvim-treesitter#1681]
**Is your feature request related to a problem? Please describe.**
I'm using vimspector as a debugger and when using it coupled with treesitter, vimspector's syntax highlighting simply doesn't work. It is a [well known](https://github.com/puremourning/vimspector/issues/324) issue from vimpsector's side, but I believe their maintainer isn't willing to look further into that.

**Describe the solution you'd like**
From the issue I linked earlier, vimspector's maintainer suggests 

>  a way to turn off tree sitter per buffer

for buffers whose syntax is invalid. 

**Describe alternatives you've considered**
Of course I could use these tools separately, but both are extremely useful. I then looked into alternatives for both, but treesitter's syntax highlighting is just too perfect and though I tried [nvim-dap](https://github.com/mfussenegger/nvim-dap), it's not as stable as vimspector. Either way, using others plugins is just a workaround for a "bug" that would remain there.

**Additional context**
I wrote a simple program to illustrate the differences between debugging _with_ treesitter:
![image](https://user-images.githubusercontent.com/84649544/128867051-dfef0ad9-a61d-4c13-b047-07200f61a393.png)
and _without_ treesitter:
![image](https://user-images.githubusercontent.com/84649544/128867264-37884021-b257-4f35-8913-feef5b2cf600.png)

Apologies if you think  this issue doesn't fit here.

**Comment by vigoux** [comment]
I think the issue fits here no worry, the only question I have is: why is it broken ? My problem is that I dont know how vimspector highlights things. Once we know that we ill be able to move forwardt.

**Comment by igorlfs** [comment]
> why is it broken ? My problem is that I dont know how vimspector highlights things.

Neither do I. Perhaps we could somehow invite Puremourning for this conversation?

**Comment by MuhammedZakir** [comment]
Relevant comments from the issue linked in OP:

puremourning:
> vimspector sets the syntax of the watch and variables windows to match the filetype being debugged. this isn't perfect but it's not awful either. [...]

raiguard:
> Upon cursory inspection, I believe the problem is that I'm using treesitter for my syntax highlighting. If I disable treesitter, then the variables view gets some syntax highlighting to match the basic syntax highlighting of the file.

puremourning:
> I guess the problem is that the buffer is not really valid syntax so treesitter can’t parse it to make a CST. I don’t have a solution for that. Is there a way to turn off tree sitter per buffer? If it were trivial I would consider a PR that did that, but otherwise I’m unlikely have any time to look at this.

**Comment by theHamsta** [comment]
Can you check the filetype of the buffer? nvim-treesitter should get triggered only on filetype `:echo &ft`?, not on the value of `syntax`?

**Comment by igorlfs** [comment]
> Can you check the filetype of the buffer?

Vimspector spawns several splits. I screenshotted the _variables_ buffer, which yields nothing on `:echo &ft`. There's also the _stacktrace_ and (optionally) a terminal, both yielding nothing. Additionally, there are 2 other buffers: _console_ and _watches_, which yield `VimspectorPrompt`. I believe such differences come from the fact that both of the latter take input from the user.

**Comment by zzLinus** [comment]
> > Can you check the filetype of the buffer?
> 
> Vimspector spawns several splits. I screenshotted the _variables_ buffer, which yields nothing on `:echo &ft`. There's also the _stacktrace_ and (optionally) a terminal, both yielding nothing. Additionally, there are 2 other buffers: _console_ and _watches_, which yield `VimspectorPrompt`. I believe such differences come from the fact that both of the latter take input from the user.

I think it's because vimspector didnt give those buffers a filetype.....If you try :setfiletype cpp (in my case),treesitter will work just fine,but i need to disable my lsp for the watch window becasue after i give the buffer a filetype,lsp start to check it and throw me errors....

**Comment by zzLinus** [comment]
> > > Can you check the filetype of the buffer?
> > 
> > 
> > Vimspector spawns several splits. I screenshotted the _variables_ buffer, which yields nothing on `:echo &ft`. There's also the _stacktrace_ and (optionally) a terminal, both yielding nothing. Additionally, there are 2 other buffers: _console_ and _watches_, which yield `VimspectorPrompt`. I believe such differences come from the fact that both of the latter take input from the user.
> 
> I think it's because vimspector didnt give those buffers a filetype.....If you try :setfiletype cpp (in my case),treesitter will work just fine,but i need to disable my lsp for the watch window becasue after i give the buffer a filetype,lsp start to check it and throw me errors....


> > > Can you check the filetype of the buffer?
> > 
> > 
> > Vimspector spawns several splits. I screenshotted the _variables_ buffer, which yields nothing on `:echo &ft`. There's also the _stacktrace_ and (optionally) a terminal, both yielding nothing. Additionally, there are 2 other buffers: _console_ and _watches_, which yield `VimspectorPrompt`. I believe such differences come from the fact that both of the latter take input from the user.
> 
> I think it's because vimspector didnt give those buffers a filetype.....If you try :setfiletype cpp (in my case),treesitter will work just fine,but i need to disable my lsp for the watch window becasue after i give the buffer a filetype,lsp start to check it and throw me errors....

noremap <leader>sb :call SetName()<CR>
func! SetName()
	let buffers = filter(range(1, bufnr('$')), 'bufexists(v:val)')
	echo buffers
	for i in buffers 
		if bufname(i) == 'vimspector.Variables'
			call setbufvar(i,'&filetype','cpp')
			:LspStop
		endif
		if bufname(i) == 'vimspector.StackTrace'
			call setbufvar(i,'&filetype','cpp')
			:LspStop
		endif
		if bufname(i) == 'vimspector.Watches'
			call setbufvar(i,'&filetype','cpp')
			:LspStop
		endif
		if bufname(i) == 'vimspector.Console'
			call setbufvar(i,'&filetype','cpp')
			:LspStop
		endif
	endfor
endfunc

Since i dont know how to write vim scripts and how vim spector work....so i just write down this little script in my init.vim and bind  this function to a hot key....I just need to press leader sb to invoke this function ever time i open vimspector debbuger to highlight those buffers....it a little bit stupid i should say...but i m fine with it

**Comment by zzLinus** [comment]
> > > Can you check the filetype of the buffer?
> > 
> > 
> > Vimspector spawns several splits. I screenshotted the _variables_ buffer, which yields nothing on `:echo &ft`. There's also the _stacktrace_ and (optionally) a terminal, both yielding nothing. Additionally, there are 2 other buffers: _console_ and _watches_, which yield `VimspectorPrompt`. I believe such differences come from the fact that both of the latter take input from the user.
> 
> I think it's because vimspector didnt give those buffers a filetype.....If you try :setfiletype cpp (in my case),treesitter will work just fine,but i need to disable my lsp for the watch window becasue after i give the buffer a filetype,lsp start to check it and throw me errors....
'''
noremap <leader>sb :call SetName()<CR>
func! SetName()
	let buffers = filter(range(1, bufnr('$')), 'bufexists(v:val)')
	echo buffers
	for i in buffers 
		if bufname(i) == 'vimspector.Variables'
			call setbufvar(i,'&filetype','cpp')
			:LspStop
		endif
		if bufname(i) == 'vimspector.StackTrace'
			call setbufvar(i,'&filetype','cpp')
			:LspStop
		endif
		if bufname(i) == 'vimspector.Watches'
			call setbufvar(i,'&filetype','cpp')
			:LspStop
		endif
		if bufname(i) == 'vimspector.Console'
			call setbufvar(i,'&filetype','cpp')
			:LspStop
		endif
	endfor
endfunc


'''

Since i dont know how to write vim scripts and how vim spector work....so i just write down this little script in my init.vim and bind this function to a hot key....I just need to press leader sb to invoke this function ever time i open vimspector debbuger to highlight those buffers....it a little bit stupid i should say...but i m fine with it

**Comment by stsewd** [comment]
Looks like vimspector doesn't set the filetype for some buffers, so not much we can do from our side.
