### ISSUE TITLE
autocmd event for when install/sync/update is complete

### ISSUE THREAD

**Issue by ck3mp3r** [nvim-treesitter/nvim-treesitter#1697]
A user event being fired to enable detection of successful installation of parser in headless operation, especially useful for automated installation routines without user interaction.

e.g.  nvim --headless -c 'autocmd User TSComplete quitall' -c 'TSInstall go'

**Comment by theHamsta** [comment]
For your concrete application, you could use `TSInstallSync  go`

**Comment by ck3mp3r** [comment]
Thanks for the pointer @theHamsta 
The following works a treat:
```
for n in "go" "hcl" "lua"; do nvim --headless -c "TSInstallSync ${n}" -c 'q'; done
```
