### ISSUE TITLE
Lost syntax after execute :Prettier

### ISSUE THREAD

**Issue by singlexyz** [nvim-treesitter/nvim-treesitter#1698]
The formatted part:

![ezgif-3-68a442c16c1d](https://user-images.githubusercontent.com/4456413/129456149-2fa04b66-ecd1-4e84-941f-e80e70b0d12c.gif)

sometimes treesitter will prompt an error:
<img width="1280" alt="图片" src="https://user-images.githubusercontent.com/4456413/129456186-87ca437e-9d60-4d67-b93b-349b878886f2.png">

**Comment by wilcus** [comment]
This is a duplicate of #1201

**Comment by vigoux** [comment]
Is this still reproducible on latest neovim Master? It should have been fixed

**Comment by vigoux** [comment]
This should be fixed by https://github.com/neovim/neovim/pull/14994

**Comment by hood** [comment]
It's still there. Just found out my way: https://github.com/nvim-treesitter/nvim-treesitter/issues/1810

**Comment by lewis6991** [comment]
Is this still an issue?

**Comment by clason** [comment]
Closing due to no response, so I assume it is indeed fixed. Otherwise please **open a new issue** with minimal reproducing step for the latest version.
