### ISSUE TITLE
[RFC]: How to handle scope of @definition.function

### ISSUE THREAD

**Issue by theHamsta** [nvim-treesitter/nvim-treesitter#170]
Things like `goto_definition` are based that on the assumption that all `@definition`s have a surrounding scope in which they are valid. But there is a problem: Most `locals.scm` define functions as separate scopes which makes sense since all the arguments of a function are only valid in this function. However, the name of the function is defined for the surrounding scope not the scope defined by the function itself.

How can we tackle that problem?

**Comment by steelsojka** [comment]
@theHamsta Is the example here a function that is called with the function itself?

```javascript
function iterate() {
   // to stuff
  return iterate();
}
```

**Comment by theHamsta** [comment]
`@definition` should be valid for their scope. So the definition of function parameters is valid for the current function. However, the function name is also defined in that scope but it can be used in the parent scope.

**Comment by steelsojka** [comment]
@theHamsta Good point. I'll take a look

**Comment by vigoux** [comment]
Maybe we can just have a directive stating that this definition is valid :

- `global` : globaly
- `parent` : in the parent scope too

**Comment by steelsojka** [comment]
Do you mean a tag like `@parent` or a directive like `((function)(parent-scope!))`

**Comment by theHamsta** [comment]
Something like
```scheme
((foo) @definition.function
(set! "definition.scope" "parent")
```
?

**Comment by steelsojka** [comment]
@theHamsta I like that. That could work.
