### ISSUE TITLE
Add capture groups to highlight brackets and delimiter in vimscript

### ISSUE THREAD

**Issue by mystilleef** [nvim-treesitter/nvim-treesitter#1705]
Please add `punctuation.bracket` and `punctuation.delimiter` capture groups for `vimscript.` After the update, brackets, and delimiters are no longer colored.

**Comment by vigoux** [comment]
What do you mean by "bracket and delimiters" ?
Do you have a screenshot ?

**Comment by mystilleef** [comment]
Add this to `highlights.scm` for vim.

```scm
[
  "("
  ")"
  "{"
  "}"
  "["
  "]"
] @punctuation.bracket

[
  "!"
  ","
  "."
  "?"
  ":"
] @punctuation.delimeter
```

This allows brackets and delimiters to be colored.

**Comment by vigoux** [comment]
Feel free to open a PR, but:
- the `!` is wrong, this is not a delimiter, rather a `punctuation.special` or something like this
- `.` is wrong too, it need to be wrapped in a `field_expression` before
- `?` and `:` are already highlighted as `conditionnal`

**Comment by mystilleef** [comment]
> Feel free to open a PR, but:
> 
> * the `!` is wrong, this is not a delimiter, rather a `punctuation.special` or something like this
> * `.` is wrong too, it need to be wrapped in a `field_expression` before
> * `?` and `:` are already highlighted as `conditionnal`

Interesting. I just noticed less highlighting after the update. That was my quick hack to get colors close to my previous settings. I haven't looked into the `vimscript` grammar, and I'm not too familiar with `treesitter`.

**Comment by vigoux** [comment]
Then I will open a pr, and see if that makes the higlighting better

**Comment by vigoux** [comment]
Could you try https://github.com/nvim-treesitter/nvim-treesitter/pull/1706 and see if it is better ?

**Comment by mystilleef** [comment]
> Could you try #1706 and see if it is better ?

Yes, that looks better. I'm going to see if I can add the `vimscript` events and built-in functions to the tokens to be colored. Those seem to be the only colors missing now.
