### ISSUE TITLE
disable treesitter on bigfile

### ISSUE THREAD

**Issue by windwp** [nvim-treesitter/nvim-treesitter#1708]
**Is your feature request related to a problem? Please describe.**
I want to create an autocmd to disable tree-sitter on a very big file.
if I open nvim on a big file then my neovim is stuck on that file. 
I am very sure it is a problem with a tree-sitter. if I remove tree-sitter plugin I can open it easily.
I know that command vim `TSBufDisable highlight` but it doesn't work on bufenter or bufread event. 
maybe it runs after treesitter highlight
my auto command already run `set syntax off`  treesitter still enable it again and highlight

Is treesitter `highlight`  work with `synmaxcol` ?

**Describe the solution you'd like**
I want  a solution to open the big file without tree-sitter 
or make command `TSBufDisable highlight` can run on autocmd and after that tree-sitter stop highlight.

**Additional context**
step to reproduce 
enable treesitter, download that file and open it.
https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js

thank you

**Comment by vigoux** [comment]
Indeed tree-sitter does not work with `synmaxcol` which is indeed an issue.

**Comment by matu3ba** [comment]
@theHamsta Helix does not provide a separation of time measurements (and it looks to me like they only log lsp-related stuff with their default build profile) and I did a simple `hx -vvv ir.cpp` with [this file](https://github.com/ziglang/zig/blob/master/src/stage1/ir.cpp). From what I see they also dont cache things in `/tmp`,`.cache` etc.

It also looks like they disabled tree-sitter logging, as the output only shows stuff from `helix_lsp::transport`, and `mio::poll`.

**Comment by theHamsta** [comment]
The timings can also be obtained using Tree-Sitter CLI. But it would be informative to add some profiling stubs to Tree-Sitter stubs in nvim. So that you can hook in some profiling logic that plots you the events and parsing/querying ranges in a timeline

**Comment by stsewd** [comment]
I think to prevent neovim hanging without being able to cancel the operation, we could expose this option as well https://github.com/tree-sitter/tree-sitter/blob/67de9435b109f9bd8bf5957d11ff13161966d262/lib/include/tree_sitter/api.h#L296, so the parsing is cancelled if it takes too long.

**Comment by theHamsta** [comment]
better than exposing this option directly would be to have a timeout for parsing+querying+other logic combined to stay always below the specified limit..

**Comment by windwp** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/pull/1994
