### ISSUE TITLE
‘for’ loop initial declarations are only allowed in C99 mode

### ISSUE THREAD

**Issue by xtrats** [nvim-treesitter/nvim-treesitter#1717]
The plugin reports error while compiling some parsers like below:

```
nvim-treesitter[comment]: Error during compilation
In file included from src/tree_sitter_comment/parser.c:3:0,
                 from src/scanner.c:3:
./src/tree_sitter_comment/chars.c: In function ‘is_newline’:
./src/tree_sitter_comment/chars.c:25:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < length; i++) {
   ^
```

- **nvim：NVIM** v0.6.0-dev+156-g7bff64216
- **os**: centos 7
- **gcc**: 4.8.5

It doesn't work when I changed gcc to 8.5.0 (by `export PATH=/usr/local/gcc-8.5.0/bin/:$PATH`)

Any ideas? Thanks!

**Comment by stsewd** [comment]
You can change the order of the compilers with 

```
require 'nvim-treesitter.install'.compilers = { "clang", "gcc" }
```

or with `CC=/path/to/c/compiler nvim`

**Comment by xtrats** [comment]
`require 'nvim-treesitter.install'.compilers = { "clang", "gcc" }` doesn't work.
`CC=/path/to/c/compiler nvim` works.

Thanks!

**Comment by benjamin051000** [comment]
For those still using RHEL7 or CentOS 7, you can provide a full path to it like so:
```lua
require 'nvim-treesitter.install'.compilers = { "/path/to/your/gcc" }
```

I'm not sure _which_ version of `gcc` started using `c99` by default, but I can say that `gcc` version 4.8.5 does not, and `gcc` version 9.2.0 does (and presumably all versions after 9.2.0 as well). I'm using 9.2.0 and I no longer get this error.
