### ISSUE TITLE
Neovim (nvim-qt.exe) - Windows x64 - Treesitter Crashing - 

### ISSUE THREAD

**Issue by dantearaujo1** [nvim-treesitter/nvim-treesitter#1718]
Installed treesitter for my setup with cpp parser but when i try to enter in any cpp or hpp file the nvim-qt.exe process crash, i tried to click retry button but nothing change, i got another crash. I disabled manually the markdown parser and everything but nothing works, for months i can't make treesitter works in my computer, sometimes even python files (after download python parsers) causes the crash

## To Reproduce**

1. Use this minimal configuration file: [Minimal_config](https://gist.github.com/dantearaujo1/b9b232e99bb0f0647f0ca61bc5d02b31)
2. Install cpp parser with TSInstall cpp if not installed yet
3. Try to open a cpp or hpp file
4. Neovim crash

## Expected behavior**

Treesitter work fine with cpp words being identified!

## Output of `:checkhealth nvim_treesitter`**

I can't even output checkhealth info because nvim crashes in the process with treesitter installed .. this is what i get from log with  -V9 flag

</code>
Running healthchecks...
linha 21: executando "D:\Code\Text Editors\Neovim 64\share\nvim\runtime\autoload\health\nvim.vim"
fim da execução de D:\Code\Text Editors\Neovim 64\share\nvim\runtime\autoload\health\nvim.vim
continuando em function health#check

Configuration
  - OK: no issues found

Performance

NVIM v0.6.0-dev+155-g15b736d6e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compilado por runneradmin@fv-az159-48

Features: -acl +iconv +tui
See ":help feature-compile"

    arquivo vimrc de sistema: "$VIM\sysinit.vim"
            padrão para $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
  - OK: Build type: RelWithDebInfo

Remote Plugins
linha 4: executando "D:\Code\Text Editors\Neovim 64\share\nvim\runtime\autoload\remote\host.vim"
fim da execução de D:\Code\Text Editors\Neovim 64\share\nvim\runtime\autoload\remote\host.vim
continuando em function health#check[21]..health#nvim#check[3]..<SNR>55_check_rplugin_manifest
  - OK: Up to date

terminal
Executing command: "'cmd.exe' '/s' '/c' '"infocmp -L"'"

  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
linha 21: executando "D:\Code\Text Editors\Neovim 64\share\nvim\runtime\autoload\health\provider.vim"
fim da execução de D:\Code\Text Editors\Neovim 64\share\nvim\runtime\autoload\health\provider.vim
continuando em function health#check

Clipboard (optional)
linha 10: executando "D:\Code\Text Editors\Neovim 64\share\nvim\runtime\autoload\provider\clipboard.vim"
fim da execução de D:\Code\Text Editors\Neovim 64\share\nvim\runtime\autoload\provider\clipboard.vim
continuando em function health#check[21]..health#provider#check[1]..<SNR>57_check_clipboard
  - OK: Clipboard tool found: win32yank
  

 Python 2 provider (optional)
linha 19: executando "D:\Code\Text Editors\Neovim 64\share\nvim\runtime\autoload\provider\pythonx.vim"
fim da execução de D:\Code\Text Editors\Neovim 64\share\nvim\runtime\autoload\provider\pythonx.vim
continuando em function health#check[21]..health#provider#check[2]..<SNR>57_check_python
Executing command: "'C:\Users\dante\.windows-build-tools\python27\python.EXE' '-c' 'import sys; sys.path = list(filter(lambda x: x != "", sys.path)); sys.stdout.write(str(sys.version_info[0]) + "." + str(sys.version_info[1])); import pkgutil; exit(2*int(pkgutil.get_loader..."

  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          C:\Users\dante\.windows-build-tools\python27\python.EXE does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found
Executing command: "'C:\Users\dante\.windows-build-tools\python27\python.EXE' '-c' 'import sys; sys.path = list(filter(lambda x: x != "", sys.path)); sys.stdout.write(str(sys.version_info[0]) + "." + str(sys.version_info[1])); import pkgutil; exit(2*int(pkgutil.get_loader..."

Python 3 provider (optional)
Executing command: "'C:\Users\dante\.windows-build-tools\python27\python.EXE' '-c' 'import sys; sys.path = list(filter(lambda x: x != "", sys.path)); sys.stdout.write(str(sys.version_info[0]) + "." + str(sys.version_info[1])); import pkgutil; exit(2*int(pkgutil.get_loader..."

  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 3:
          python3 not found in search path or not executable.
          python3.10 not found in search path or not executable.
          python3.9 not found in search path or not executable.
          python3.8 not found in search path or not executable.
          python3.7 not found in search path or not executable.
          python3.6 not found in search path or not executable.
          C:\Users\dante\.windows-build-tools\python27\python.EXE is Python 2.7 and cannot provide Python 3.
  - INFO: Executable: Not found
Executing command: "'C:\Users\dante\.windows-build-tools\python27\python.EXE' '-c' 'import sys; sys.path = list(filter(lambda x: x != "", sys.path)); sys.stdout.write(str(sys.version_info[0]) + "." + str(sys.version_info[1])); import pkgutil; exit(2*int(pkgutil.get_loader..."

Python virtualenv
  - OK: no $VIRTUAL_ENV

Ruby provider (optional)
  - INFO: Ruby: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x64-mingw32]
linha 15: executando "D:\Code\Text Editors\Neovim 64\share\nvim\runtime\autoload\provider\ruby.vim"
fim da execução de D:\Code\Text Editors\Neovim 64\share\nvim\runtime\autoload\provider\ruby.vim
continuando em function health#check[21]..health#provider#check[5]..<SNR>57_check_ruby
  - INFO: Host: D:\Code\Languages\Ruby\Ruby27-x64\bin\neovim-ruby-host.bat
  - OK: Latest "neovim" gem is installed: 0.8.1

Node.js provider (optional)
  - INFO: Node.js: v14.13.0
linha 20: executando "D:\Code\Text Editors\Neovim 64\share\nvim\runtime\autoload\provider\node.vim"
Executing command: "'D:\Code\NodeJS\node.EXE' '-v'"

fim da execução de D:\Code\Text Editors\Neovim 64\share\nvim\runtime\autoload\provider\node.vim
continuando em function health#check[21]..health#provider#check[6]..<SNR>57_check_node
Executing command: "'D:\Code\NodeJS\node.EXE' '-v'"

Executing command: "'D:\Code\NodeJS\node.EXE' '-v'"

  - INFO: Nvim node.js host: D:\Code\NodeJS\node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.0

Perl provider (optional)
linha 7: executando "D:\Code\Text Editors\Neovim 64\share\nvim\runtime\autoload\provider\perl.vim"
Executing command: "'D:\Code\Git\usr\bin\perl.EXE' '-e' 'use v5.22'"

health#nvim-treesitter#check
========================================================================
  - ERROR: Failed to run healthcheck for "nvim-treesitter" plugin. Exception:
    function health#check, linha 21
    Vim(call):E107: Parênteses faltando: health#nvim-treesitter#check()
health#nvim-treesitter#check

Executing command: "'D:\Code\Git\usr\bin\perl.EXE' '-W' '-MNeovim::Ext' '-e' ''"

fim da execução de D:\Code\Text Editors\Neovim 64\share\nvim\runtime\autoload\provider\perl.vim
continuando em function health#check[21]..health#provider#check[7]..<SNR>57_check_perl
Executing command: "'D:\Code\Git\usr\bin\perl.EXE' '-e' 'use v5.22'"

Executing command: "'D:\Code\Git\usr\bin\perl.EXE' '-W' '-MNeovim::Ext' '-e' ''"

  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed
linha 21: executando "D:\Code\Text Editors\Neovim 64\sha

</details>

## Output of `nvim --version`**

NVIM v0.6.0-dev+155-g15b736d6e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compilado por runneradmin@fv-az159-48

Features: -acl +iconv +tui
See ":help feature-compile"

    arquivo vimrc de sistema: "$VIM\sysinit.vim"
            padrão para $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info

## Additional context

Using checkhealth makes nvim-qt crash too.

**Comment by vigoux** [comment]
Could you try updating both the plugin and `nvim-treesitter` please ?

**Comment by dantearaujo1** [comment]
I just updated to NVIM v0.6.0-dev+156-g7bff64216 right now and run :PackerUpdate to update treesitter everything was exact the same, same errors same log information except for the nvim --version part.

**Comment by vigoux** [comment]
This is a bit weird because the checkhealth for nvim tree-sitter does not run, which indicates an error at some point, do you think you can do a clean install of everything ?

**Comment by dantearaujo1** [comment]
With a clean install of everything (WITHOUT INSTALLING CPP WITH TSINSTALL) this is what i get from treesitter healthcheck

health#treesitter#check
========================================================================
## Checking treesitter configuration
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for c: ABI version 13

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: clangd: configuration checked.

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (e85a279cf29da1b08648e27214dda20a841e57c8) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.13.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.


After that, i installed again cpp parser with "TSInstall cpp" and couldn't use checkhealth nvim-treesitter again without crashing my nvim-qt.exe

**Comment by vigoux** [comment]
Could you try following the indications [here](https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support) and see if that fixes the issue ?

**Comment by dantearaujo1** [comment]
it seems like require 'nvim-treesitter.install'.compilers = { "clang", "gcc" } compiling the parsers with clang and not with gcc makes everything goes well! Thank for the support! This solved my issue.

**Comment by vigoux** [comment]
Great then ! Glad you can finally use the plugin, and feel free to report any other issue you have !
Closing as solved.
