### ISSUE TITLE
"Plugin runtime path not found" when installed via dein.vim

### ISSUE THREAD

**Issue by foisonocean** [nvim-treesitter/nvim-treesitter#172]
**Describe the bug**

**To Reproduce**
1. Install `nvim-treesitter` via dein.vim. (add a line `call dein#add('nvim-treesitter/nvim-treesitter')` in the `init.vim` file)
1. Run `:call dein#install()`.
1. Restart NeoVim.
1. Run `:TSInstall lua`. 
1. See error

**Expected behavior**
Should install lua parser properly.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## c parser healthcheck
  - OK: c parser found.
  - OK: `locals.scm` found.
 - OK: `highlights.scm` found.

## Missing parsers
 - WARNING: Some parsers are not installed:
   html
   typescript
   regex
   nix
   swift
   java
   python
   yaml
   elm
   vue
   cpp
   toml
   lua
   ruby
   ocaml
   go
   scala
   haskell
   rust
   json
   markdown
   javascript
   css
   julia
   php
   c_sharp
   bash
   tsx
   - ADVICE:
     - Install them using `:TSInstall language

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-593-g1ca67a73c
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by vigoux** [comment]
Hi ! thanks for reporting ! Can you paste the full error messages ? Because this `Plugin runtime path not found` looks quite strange to me as you successfully ran `:checkhealth`.

**Comment by carlitux** [comment]
Hi,

As dein merge all config needs to be:

```vim
call dein#add('nvim-treesitter/nvim-treesitter', { 'merged': 0 })
```

**Comment by Shougo** [comment]
I know the problem.
https://github.com/Shougo/dein.vim/issues/372

Because nvim-treesitter checks runtimepath and it does not support dein.vim merge feature.
Note: I don't know why it checks runtimepath.

**Comment by vigoux** [comment]
Okay at least we have a fix for that.
`nvim-treesitter` uses the `rtp` to collect the query files, thus we have this problem, but we really should try and fix this.

**Comment by vigoux** [comment]
As we are forced to check `rtp` within this plugin, there is no fix on our side. Furthermore the fix can be found [here](https://github.com/Shougo/dein.vim/issues/372#issuecomment-653833562).

Can we close this ?

**Comment by foisonocean** [comment]
It's OK for me to close this issue.
