### ISSUE TITLE
vim

### ISSUE THREAD

**Issue by max397574** [nvim-treesitter/nvim-treesitter#1725]
**Describe the bug**

the augroup name isn't parsed correctly

I have an augroup with a `_`in the name. The `_`and the part after it are seen as command and not as name. Perhhaps an error with the regex
![Screen Shot 2021-08-20 at 16 03 03](https://user-images.githubusercontent.com/81827001/130245773-a79051f7-15a2-403b-b5a1-6423313b15bc.png)

**Comment by max397574** [comment]
sorry for the title. I can't change it.

**Comment by vigoux** [comment]
No worry, but could you post those issues in the `tree-sitter-viml` repo instead ? This is to avoid having parser-related issues here.
