### ISSUE TITLE
Issue using parser on Windows

### ISSUE THREAD

**Issue by vzytoi** [nvim-treesitter/nvim-treesitter#1727]
**Describe the bug**

I installed and setup tree-sitter. I installed parser using `:TSUpdate` and now, when i open a buffer i get this error : 
```
E5108: Error executing lua Failed to load parser: uv_dlopen: ~\AppData\Local\nvim-data\site\parser\lua.so is not a valid Win32 app.
```

**Output of `:checkhealth nvim_treesitter`**

```
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.6.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `clang` executable found. Selected from { "clang", "gcc" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.
```

**Output of `nvim --version`**

```
NVIM v0.6.0-dev+96-g5f01714b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compilé par runneradmin@fv-az152-272

Features: -acl +iconv +tui
See ":help feature-compile"

         fichier vimrc système : "$VIM\sysinit.vim"
               $VIM par défaut : "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

**Additional context**

As you can see I use Windows 10 (x64), here is my configuration for tree-sitter : 

```
require('nvim-treesitter.configs').setup({
    ensure_installed = "maintained",
    highlight = {
        enable = true
    },
    indent = {
        enable = true
    },
    autopairs = {
        enable = true
    },
    autotag = {
        enable = true
    }
})

require('nvim-treesitter.install').compilers = { "clang", "gcc" }
```

**Comment by theHamsta** [comment]
Does clang compile for x64? Because you seem to use a 32bit installation of Neovim. Please make sure you're compiling for the same architecture.

**Comment by vzytoi** [comment]
I had intalled neovim from choco so I reinstall it from package :
```
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compilé par runneradmin@fv-az152-786

Features: -acl +iconv +tui
See ":help feature-compile"

         fichier vimrc système : "$VIM\sysinit.vim"
               $VIM par défaut : "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```
It doesn't seem to make any change,
thank you

**Comment by vzytoi** [comment]
I finally solved my problem, for those who are following me, you have to check as @theHamsta said, that our compiler compiles for the same architecture.

- Check if neovim is 64-bit: 
`nvim --version` section `Compilation` check the path to cl.exe `.../x64/cl.exe`
If neovim is 32-bit please reinstall it [here](https://github.com/neovim/neovim/releases)
- Check if the compiler compiles in 64-bit :
`gcc -dumpmachine`, if the output is `mingw32`, you are in 32-bit and if the output is `x86_64-w64-mingw32`, you are in 64.
To make sur that tree-sitter is using gcc : `require('nvim-treesitter.install').compilers = { "gcc" }`
If you don't have ggc yet or if gcc is in 32-bit, please (re)?install it [here](https://sourceware.org/cygwin/)

Once all of that is done, run neovim and type :  `:TSUninstall all`. You can now simply restart nvim, install parsers again and everything should works just fine. To be sure you can try to open the [playground](https://github.com/nvim-treesitter/playground) to check if it show anything  (`:TSPlaygroundToggle`

**Comment by danielgarzaf** [comment]
> I finally solved my problem, for those who are following me, you have to check as @theHamsta said, that our compiler compiles for the same architecture.
> 
> * Check if neovim is 64-bit:
>   `nvim --version` section `Compilation` check the path to cl.exe `.../x64/cl.exe`
>   If neovim is 32-bit please reinstall it [here](https://github.com/neovim/neovim/releases)
> * Check if the compiler compiles in 64-bit :
>   `gcc -dumpmachine`, if the output is `mingw32`, you are in 32-bit and if the output is `x86_64-w64-mingw32`, you are in 64.
>   To make sur that tree-sitter is using gcc : `require('nvim-treesitter.install').compilers = { "gcc" }`
>   If you don't have ggc yet or if gcc is in 32-bit, please (re)?install it [here](https://sourceware.org/cygwin/)
> 
> Once all of that is done, run neovim and type : `:TSUninstall all`. You can now simply restart nvim, install parsers again and everything should works just fine. To be sure you can try to open the [playground](https://github.com/nvim-treesitter/playground) to check if it show anything (`:TSPlaygroundToggle`

If anyone else is having trouble using gcc (even when reinstalling for `x86_64-w64-mingw32`) like I did, you can also use clang. That's what worked for me.

Just run `choco install llvm` and add `require('nvim-treesitter.install').compilers = { "clang" }` into your `init.vim` file

**Comment by theHamsta** [comment]
@vzytoi can you check whether there's some information missing in our Windows wiki and add the information on how to check 32bit vs 64bit?

**Comment by nonsleepr** [comment]
I found out the cause of the problem and solved it the following way.

In my case the parsers were build using MinGW toolchain. It seems it is, in fact a [recommended approach](https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support#mingw-toolchain). Some of the compiled libraries are c++ based, and those libraries aren't statically compiled:

```
>dumpbin /dependents %LocalAppData%\nvim-data\site\pack\packer\start\nvim-treesitter\parser\lua.so

Microsoft (R) COFF/PE Dumper Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file %LocalAppData%\nvim-data\site\pack\packer\start\nvim-treesitter\parser\lua.so

File Type: DLL

  Image has the following dependencies:

    KERNEL32.dll
    msvcrt.dll
    libstdc++-6.dll
```

That `libstdc++-6.dll` is located in `C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin` if you installed MinGW with chocolatey. That path wasn't on my `$PATH` for whatever reason. When added, the error was gone, no recompilation required.

**Comment by theHamsta** [comment]
Does compiling with g++ with `-static-libc++` help as in https://github.com/nvim-treesitter/nvim-treesitter/pull/1911#issuecomment-939527210

**Comment by nonsleepr** [comment]
'-static-libstdc++` doesn't work with MinGW's `gcc`. From what I gathered, [this is](https://newbedev.com/static-libstdc-works-on-g-but-not-on-pure-gcc) the reason (the option should be passed to `g++` directly). `-static-libgcc` works though (tested on the Python parser) to eliminate `libgcc_s_seh-1.dll` dependency.

**Comment by cloudre01** [comment]
> I finally solved my problem, for those who are following me, you have to check as @theHamsta said, that our compiler compiles for the same architecture.
> 
> * Check if neovim is 64-bit:
>   `nvim --version` section `Compilation` check the path to cl.exe `.../x64/cl.exe`
>   If neovim is 32-bit please reinstall it [here](https://github.com/neovim/neovim/releases)
> * Check if the compiler compiles in 64-bit :
>   `gcc -dumpmachine`, if the output is `mingw32`, you are in 32-bit and if the output is `x86_64-w64-mingw32`, you are in 64.
>   To make sur that tree-sitter is using gcc : `require('nvim-treesitter.install').compilers = { "gcc" }`
>   If you don't have ggc yet or if gcc is in 32-bit, please (re)?install it [here](https://sourceware.org/cygwin/)
> 
> Once all of that is done, run neovim and type : `:TSUninstall all`. You can now simply restart nvim, install parsers again and everything should works just fine. To be sure you can try to open the [playground](https://github.com/nvim-treesitter/playground) to check if it show anything (`:TSPlaygroundToggle`

this worked for me. After install a gcc compiler, I needed to do `:TSUninstall all` and reopen nvim. Hope this can save you guys out there your time.
