### ISSUE TITLE
if statement parsed in a comment for VimL

### ISSUE THREAD

**Issue by comiluv** [nvim-treesitter/nvim-treesitter#1732]
**Describe the bug**

When there is a word ```if``` in a commented line, the parser recognizes it as an if statement

**To Reproduce**

1. Make a viml file: test-vim.vim
2. Type following
```viml
if
	" A comment containing a word if
else
	echo ELSE
endif
```
3. Press % while the cursor is on ```endif```
4. The cursor jumps to the word ```if``` in the commented line
![GIF 2021-08-22 오후 7-42-23](https://user-images.githubusercontent.com/19642705/130352289-5be6d397-b00e-45f0-92ae-ca3faebbadc0.gif)

**Expected behavior**
The cursor jumps to correct if statement
![GIF 2021-08-22 오후 7-43-05](https://user-images.githubusercontent.com/19642705/130352283-b77ab769-c3f4-4d3c-bebe-a4e8ebc4411e.gif)

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>
health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v14.17.4 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - c              ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - vim            ✓ . . . ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>
NVIM v0.6.0-dev+142-g5a111c1b0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-899

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
</code>
</details>

**Additional context**

**Comment by comiluv** [comment]
Also ```else``` is not highlighted as same as ```if``` and ```endif``` but it should

**Comment by vigoux** [comment]
So the `%` here is actually matchit from what I remember so not related to this plugin.

Plus the fact that `else` is not highlighted is because we expect an expression after the `if` (the condition) which is not present here, so unrelated too.

**Comment by comiluv** [comment]
> So the `%` here is actually matchit from what I remember so not related to this plugin.

Tried clean install of neovim and the plugin and reproduced the same result: % jumps to commented "if", which strongly suggests treesitter is the cause of this issue.
Configuration is as below.
```viml
lua require'nvim-treesitter.configs'.setup{ highlight = { enable = true } }
```

> Plus the fact that `else` is not highlighted is because we expect an expression after the `if` (the condition) which is not present here, so unrelated too.

Inserting an expression after the first "if" results in "endif" not being highlighted.
<img width="500" alt="화면 캡처 2021-08-23 024852" src="https://user-images.githubusercontent.com/19642705/130365310-7e322634-d769-4bc6-8423-d05058a71e56.png">
Which means either way, highlighting is broken.

**Comment by stsewd** [comment]
> Tried clean install of neovim and the plugin and reproduced the same result: % jumps to commented "if", which strongly suggests treesitter is the cause of this issue.

This is because matchit may relay on syntax being enabled, when you enable tree-sitter, syntax is disabled, so plugins that depend on that may break, you can test this with `:set syntax=vim`

For the other problem, as @vigoux said, that expression is invalid (if requires an expression)

![image](https://user-images.githubusercontent.com/4975310/130377224-4af96595-a942-4f6f-aeb3-9f72a700e577.png)

If you add an expression to the if, it gets parsed correctly

![image](https://user-images.githubusercontent.com/4975310/130377277-22263bdd-ab8c-4ed9-a92c-23378b70854f.png)

**Comment by comiluv** [comment]
> This is because matchit may relay on syntax being enabled, when you enable tree-sitter, syntax is disabled, so plugins that depend on that may break, you can test this with `:set syntax=vim`

Then if I understand it correctly, matchit currently doesn't work correctly with tree-sitter's syntax but tree-sitter is correctly parsing syntax, which can be seen as the highlightings are correct and in the tree view? I shall report this to matchit's issue.

> For the other problem, as @vigoux said, that expression is invalid (if requires an expression)
> 
> ![image](https://user-images.githubusercontent.com/4975310/130377224-4af96595-a942-4f6f-aeb3-9f72a700e577.png)
> 
> If you add an expression to the if, it gets parsed correctly
> 
> ![image](https://user-images.githubusercontent.com/4975310/130377277-22263bdd-ab8c-4ed9-a92c-23378b70854f.png)

I mistakenly took "expression" as an expression inside the if statement block, but controlling expression. Of course, controlling expression was missing and was causing the highlighting in the example case.
I have a highlighting issue happening with my real .vimrc file. I have a portion of my .vimrc file which is as follows:
```viml
" WSL yank support
let s:clip = '/mnt/c/Windows/System32/clip.exe'  " default location
if has('unix') && !has('nvim') && executable(s:clip) && has('patch8.0.1394')
    augroup WSLYank
        autocmd!
        autocmd TextYankPost * call system('echo '.shellescape(join(v:event.regcontents, "\<CR>")).' | '.s:clip)
    augroup END
    noremap "+p :exe 'norm a'.system('/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -Command Get-Clipboard')<CR>
endif

" C Compile settings. F5 to compile with GCC and F8 to execute
let compile_cmdline='gcc % -g -Wall -Wextra -pedantic -o %<'
if has('nvim')
    nnoremap <F5> :w! <BAR> execute 'terminal '.compile_cmdline<CR>
else
    nnoremap <F5> :w! <BAR> execute '!'.compile_cmdline<CR>
endif
if !has("unix")
    if has('nvim')
        noremap <F8> :terminal %<<Enter>
    else
        noremap <F8> :!%<<Enter>
    endif
elseif has("unix")
    if has('nvim')
        noremap <F8> :terminal ./%<<Enter>
    else
        noremap <F8> :!./%<<Enter>
    endif
endif

" loop through subdirectory and source .vim files
" https://johngrib.github.io/wiki/vim-configure-split/
for include_file in uniq(sort(globpath(&rtp, 'vim-include/*.vim', 0, 1)))
    execute "source " . include_file
endfor
```
and this file, although reads with no error and works as intended, is giving me incorrect highlighting for ```else``` and ```endif``` as you can see in line 97, 103, 105, 109, 115 in this screenshot.
<img width="831" alt="화면 캡처 2021-08-23 133900" src="https://user-images.githubusercontent.com/19642705/130391144-41d533cb-65db-4d26-b4e1-312af047fbcc.png">
What could be the cause of this broken highlighting? I commented out all the other plugins but nvim-treesitter and nvim-treesitter-textobjects (except for vim-plug the plugin manager which should be irrelevant) and commented out all the sets except for ```lua.require'nvim-treesitter.configs'setup{ highlight = { enable:true } }``` and it gives me the same result of incorrect highlighting of those statements.

**Comment by vigoux** [comment]
As already discussed in (many) oether issues: there is a bug with mappings as of today in the tree-sitter parser that I am working on, causing parsing error _if you mapping contains a `"`_.

For the matching part, you are missing everything: tree-sitter _can not_ help matchit because _matchit is a pile of regexes that guesstimate what the file looks like_.
Thus when you enable tree-sitter (and disable the builtin syntax engine), you lose parts of this because matchit loses the information from builting syntax engine.

**Comment by comiluv** [comment]
> As already discussed in (many) oether issues: there is a bug with mappings as of today in the tree-sitter parser that I am working on, causing parsing error _if you mapping contains a `"`_.

As you can clearly see in the part of the .vimrc and the screenshot, there are unhighlighted ```else``` and ```endif``` statements which are not about any mappings containing `"`. Thus this issue is a new one, unrelated to already existing bug you mentioned.

> For the matching part, you are missing everything: tree-sitter _can not_ help matchit because _matchit is a pile of regexes that guesstimate what the file looks like_.
> Thus when you enable tree-sitter (and disable the builtin syntax engine), you lose parts of this because matchit loses the information from builting syntax engine.

The fact that tree-sitter parses AST and matchit works in regex but these differences not leading to completely broken parentheses matching but partially working, in a broken way, is very misleading for an end-user. In a nutshell, if tree-sitter speaks AST and matchit says regex, which one should be translating for another? I posted this issue on the neovim's issue thread after investigation of my own and discussing in this thread, but when it comes to API it's not clear who should be doing something for whom.

**Comment by comiluv** [comment]
I'm opening a new issue regarding highlighting issue in viml files discussed in the thread and closing this one, as the original issue is referred to neovim's issue thread.
