### ISSUE TITLE
A function to indicate the status of tree-sitter modules

### ISSUE THREAD

**Issue by dimus** [nvim-treesitter/nvim-treesitter#1733]
**Is your feature request related to a problem? Please describe.**
When I open a buffer I do not know if a tree-sitter module, `highlight` for example, is working or not, I have to use `TSEnableAll {module}` 
and `TSDisableAll {module}` a few times to understand the state of a module.

**Describe the solution you'd like**
I would like to have a function that provides a succint info about the `enabled/disabled` state of tree-sitter modules for a current buffer. I would like to show this information on a statusline (via lualine or similar). I would like to pick
modules that I want to monitor, so to be able to have an output like:

`TS hl:on to.sel:off` 

to show (in this example) an information about `highlight` and `textobject.select` ignoring other modules.

**Describe alternatives you've considered**

**Additional context**

**Comment by ram02z** [comment]
This could allow for a command similar to `LspInfo` from nvim-lspconfig to be made for nvim-treesitter.

**Comment by theHamsta** [comment]
Like `:TSModuleInfo`? It should already be able to find out via functions whether a module is activated or not.

**Comment by ram02z** [comment]
> 
> 
> Like `:TSModuleInfo`? 

Ah, TIL. Thanks!
