### ISSUE TITLE
PHP indentation stops working when parser is installed

### ISSUE THREAD

**Issue by Geraint** [nvim-treesitter/nvim-treesitter#1742]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`

### Describe the bug

I have the treesitter plugin installed, and this config:

```
lua <<EOF
require'nvim-treesitter.configs'.setup {
    ensure_installed = { "javascript" },
    highlight = {
        enable = true,
    }
}
EOF
```

I I don't install the PHP parser, I don't get tree-sitter syntax highlighting, but auto-indent works as expected

If I do install the PHP parser, I get tree-sitter syntax highlighting, but auto-indent stops working. Whenever I hit the return key, I'm on column 0, no matter how the preceding line is indented (in a method, in a if statement, etc).

If I issue

```
:syntax on
```

... indentation starts working again, but if I switch to another buffer and then back again, syntax has been turned back off and auto indentation is once again broken.

I have tried adding `syntax on` to `after/ftplugin/php.vim`, but it does not help.

### To Reproduce

1. Open a PHP file.
2. Move to the end of a line in an indented code block
3. Press return

### Expected behavior

In this code:

```
    public function foo()
    {
    }
```

... if the cursor in to the right of the opening brace and I am in Insert mode, when I press Return, I would expect a new line to inserted with 8 leading spaces, and my cursor to be at column 9.

What actually happens is a new line gets inserted with no leading spaces, and the cursor is at column 0.

### Output of `:checkhealth nvim_treesitter`

```markdown
health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v10.19.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - c              ✓ ✓ ✓ ✓ ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - php            ✓ ✓ ✓ ✓ ✓

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/root/opt/neovim/build/config -I/root/opt/neovim/src -I/root/opt/neovim/.deps/usr/include -I/usr/include -I/root/opt/neovim/build/src/nvim/auto -I/root/opt/neovim/build/include
Compiled by root@DESKTOP-<redacted>

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by vigoux** [comment]
Hi, this issue seems to appear because of tree-sitter replacing the builtin syntax engine.

Please look [here](https://github.com/nvim-treesitter/nvim-treesitter#highlight) and especially set `  additional_vim_regex_highlighting` to `true` in your `setup` call and see if the issues disappears.

**Comment by Geraint** [comment]
> especially set additional_vim_regex_highlighting to true in your setup call and see if the issues disappears.

Yes, that does appear to fix it.

Thank you - very much appreciated.
