### ISSUE TITLE
Highlighting test groups priority and highlight testing

### ISSUE THREAD

**Issue by nkrkv** [nvim-treesitter/nvim-treesitter#1784]
Hello! I’ve already [asked my question](https://github.com/tree-sitter/tree-sitter/issues/1374) in ` tree-sitter/tree-sitter` and was directed here because it probably better suits `nvim-treesitter/nvim-treesitter`. So, here’s the quotation:

---
I’m making a [Tree-sitter parser for the ReScript language](https://github.com/nkrkv/tree-sitter-rescript/) and use the `test/highlight` facilities to ensure highlight queries capture things right. So far so good until I have a syntax subtree that is matched by several queries at once. In this case, the test runner of `tree-sitter` takes the first match as the result. And in `nvim-treesitter` highlight is exactly the opposite: the last query effectively wins.

As an example, I’ve compared `highlights.scm` for JavaScript. And indeed,  `tree-sitter/tree-sitter-javascript/queries/highlights.scm` looks like this:

```scheme
(function
  name: (identifier) @function)

; ... la la la

(identifier) @variable
```

whereas `nvim-treesitter/nvim-treesitter/queries/ecma/highlights.scm` looks like:

```scheme
; the very first query
(identifier) @variable

; ... la la la

(function
  name: (identifier) @function)
```

An `(identifier)` indeed might be a variable name or function name depending on the context. And if I swap the order in `nvim-treesitter` the `@variable` group will win and all `(identifier)`’s used as function names will be colored as variables no matter what.

Similarly, if I swap the order in `tree-sitter-javascript`, the tests fail because function names now are captured as simple `@variable` as it goes first.

--- 

Only now did I start to realize that the “default” `highlights.scm` carried with various language parsers and the `queries/{lang_name}/highlights.scm` are different things with different group names, different order, different nuances.

Although I find it more intuitive to have “last query group wins” as `nvim-treesitter` does, I cannot quite understand why the “upstream” convention was not adopted to avoid the necessity of maintaining two diverse query sets. I believe there are some technical reasons, I’m just curious and can’t find any explanation.

Developing the new grammar I found the highlights test runner provided by `tree-sitter` very handy. And now, as I understand that `highlights.scm` for nvim differ from the vanilla `highlights.scm`, I realize I can no longer use the test runner to make bullet-proof highlighting for NeoVim. Am I right? If so, I wonder how `nvim-treesitter` language maintainers solve the problem? I see two ways:

1. Scm-ninja: craft the queries in a way that always lead to at most single query match. Cannot be automatically verified. However, the highlights test runner might be used
2. Finger crossed development :crossed_fingers: Update `highlights.scm`, visually observe an example snippet in NeoVim, hope nothing is broken

Taking a look at a few langs and issue tracker here I suspect (2) is the way to go. That’s sad and I hope I miss some idea. Could anyone help me and tell the best way to craft a testable and nvim-compatible `highlights.scm`?

**Comment by theHamsta** [comment]
If the order of Tree-Sitter changed to take the latter one then this is something new. Our query files where always copies of the  upstream in the beginning and it had `@variable` always on top which was mostly overwritten. Neovim applies all the highlights that are described by Tree-Sitter. So if the first highlight says "bold" and the second "foreground" both will be applied. If they are setting the same attribute and exactly the same range the later one  wins. There is also the option to use `#set` to manually specify a priority of a specific highlight.

There are highlight tests in Neovim core, but they are probably too low-level for you compared to the option provided by tree-sitter CLI.

**Comment by nkrkv** [comment]
Thank you for the answers.

> There is also the option to use `#set` to manually specify a priority of a specific highlight

This might be a solution. Will look further.
