### ISSUE TITLE
ensure_installed has no effect on latest master

### ISSUE THREAD

**Issue by fsouza** [nvim-treesitter/nvim-treesitter#179]
**Describe the bug**

When doing a fresh install, ensure_installed has no effect on latest master. Here's how I'm configuring nvim-treesitter: https://github.com/fsouza/vimfiles/blob/2f9e248a7566bd45fd1aa9fe32d86093a0e3c11a/lua/plugin/ts.lua#L34-L51 (let me know if I'm doing this the wrong way).

I bisected the code and it seems that it stops working after this commit: https://github.com/nvim-treesitter/nvim-treesitter/commit/c42c38a8346dd9edda96477b774d3e086cd73650.

Other custom module configs are also ignored (for example, <tab> doesn't expand selection). See #178 for issue with textobjects.

**To Reproduce**

Using the latest master, follow instructions from the README to add ensure_installed. Open nvim and nothing really happens.

**Expected behavior**

The desired parsers should get installed.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
  2 ========================================================================
  3 ## Installation
  4   - OK: git executable found.
  5   - OK: cc executable found.
  6
  7 ## c parser healthcheck
  8   - OK: c parser found.
  9   - OK: locals.scm found.
 10   - OK: highlights.scm found.
 11
 12 ## Missing parsers
 13   - WARNING: Some parsers are not installed:
 14     html
 15     typescript
 16     regex
 17     nix
 18     swift
 19     java
 20     python
 21     yaml
 22     elm
 23     vue
 24     cpp
 25     toml
 26     lua
 27     ruby
 28     ocaml
 29     go
 30     scala
 31     haskell
 32     rust
 33     json
 34     markdown
 35     javascript
 36     css
 37     julia
 38     php
 39     c_sharp
 40     bash
 41     tsx
 42     - ADVICE:
 43       - Install them using `:TSInstall language

</code>
</details>

**Output of `nvim --version`**
```
 nvim --version
NVIM v0.5.0-593-g1ca67a73c
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/fsouza/Projects/os/3/neovim/build/config -I/Users/fsouza/Projects/os/3/neovim/src -I/Users/fsouza/Projects/os/3/neovim/.deps/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/Users/fsouza/Projects/os/3/neovim/build/src/nvim/auto -I/Users/fsouza/Projects/os/3/neovim/build/include
Compiled by fsouza@fsouza-mbp152

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/Users/fsouza/opt/neovim/share/nvim"

Run :checkhealth for more info
```

**Comment by vigoux** [comment]
Hi ! It looks like this has been fixed in lastest master, can you try it ?

**Comment by fsouza** [comment]
@vigoux yes, thank you very much for the quick fix! 😁
