### ISSUE TITLE
MDX (markdown / jsx) support

### ISSUE THREAD

**Issue by lynndylanhurley** [nvim-treesitter/nvim-treesitter#1791]
**Language information**

MDX is a markdown-like language that allows the embedding of react components. It's mostly used for documentation with things like [storybook](https://storybook.js.org/).

Github:
https://github.com/mdx-js/mdx

Website:
https://mdxjs.com/

Specification:
https://github.com/mdx-js/specification#specification

**Comment by Guneetconvent2002** [comment]
I don't think you're very clear about what you want from this issue. Could you maybe give a bit more detail about what one needs to do?

**Comment by stsewd** [comment]
@lynndylanhurley to add support for this language someone needs to write a tree-sitter grammar for it.

**Comment by lynndylanhurley** [comment]
Sorry I thought this was the place to request that someone write new tree-sitter grammars for unsupported languages. Is that not the case? If not I'll close the issue.

**Comment by stsewd** [comment]
You may have more luck asking in https://github.com/tree-sitter/tree-sitter/discussions if someone already wrote one.

**Comment by matallui** [comment]
I second this request. Still no MDX syntax highlighting in nvim.

**Comment by clason** [comment]
Please add requests to https://github.com/nvim-treesitter/nvim-treesitter/issues/2282

(And note that grammars are community contributed; consider contributing yourself if you need something, otherwise you'll be waiting a long time if it's something not many people care about.)
