### ISSUE TITLE
Invalid query syntax error on MacOS

### ISSUE THREAD

**Issue by Akin909** [nvim-treesitter/nvim-treesitter#184]
**Describe the bug**
When trying to add highlighting to a buffer using treesitter on my mac I encounter a syntax error and highlighting
fails to load. The exact same command works without issues on Linux. Other functionality works correctly like incremental selection etc. only highlighting fails. I've tried this highlighting `disabled` and manually highlighting each buffer. I'm not sure if this might be due to different compilers being used between mac and linux (I don't have any visibility on which is used on mac)

**To Reproduce**
1. Open a file in a supported language on MacOS (Catalina)
2. Run `:TSBufEnable highlight`
3. See error
```
E5108: Error executing lua ...m/HEAD-91e41c8/share/nvim/runtime/lua/vim/treesitter.lua:127: query: invalid syntax at position 536  
```

**Expected behavior**
The buffer should be syntax highlighted correctly like on linux.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
  - ERROR: Failed to run healthcheck for "nvim_treesitter" plugin. Exception:
    function health#check[21]..health#nvim_treesitter#check, line 1
    Vim(lua):E5108: Error executing lua ...m/HEAD-91e41c8/share/nvim/runtime/lua/vim/treesitter.lua:127: query: invalid syntax at position 190

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-nightly
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200602-82373-1pwmboa/build/config -I/tmp/neovim-20200602-82373-1pwmboa/src -I/usr/local/include -I/tmp/neovim-20200602-82373-1pwmboa/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200602-82373-1pwmboa/build/src/nvim/auto -I/tmp/neovim-20200602-82373-1pwmboa/build/include
Compiled by akinsowemimo@Akins-MacBook-Pro

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-91e41c8/share/nvim"

Run :checkhealth for more info
```

**Comment by vigoux** [comment]
Two more questions :
 - Can you tell us the language that you used together with the error messages ?
 - Did you try compiling neovim from source and updating to latest master ?

**Comment by Akin909** [comment]
Hi @vigoux thanks for the quick response, I've tried it in Java and in Go and get a syntax error in both.
I haven't compiled it from source I use the nightly version via homebrew. I'm not sure how far the formula lags behind master. I'm currently at `HEAD-91e41c8`

**Comment by vigoux** [comment]
Can you try updating to the very latest master ?
I think the issue is related to the treesitter runtime being too old.

**Comment by Akin909** [comment]
I just got the latest nightly from the neovim releases page, seems the homebrew formula is very stale (which I didn't realise). Everything works with the latest version installed 👍 . I'll close this out. Thanks for helping debug this.

**Comment by vigoux** [comment]
Thanks for reporting, this issue will be used as a motivation to test the plugin on other platforms too 😉
