### ISSUE TITLE
Highlighting of Lua `ffi.cdef` string is strange and inconsistent across different quoting types

### ISSUE THREAD

**Issue by zeertzjq** [nvim-treesitter/nvim-treesitter#1840]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`

### Describe the bug

Highlighting of Lua `ffi.cdef` string is strange and inconsistent across different quoting types

### To Reproduce

Open a Lua file with `ffi.cdef`.

When single quotes are used, the first character of `ffi.cdef` string is highlighted as `TSString`:

![Screenshot_20210920_074316](https://user-images.githubusercontent.com/35768171/133946735-b3952db3-7a66-4894-bd80-7c4a7a38f618.png)

When double quotes are used, all of `ffi.cdef` string is highlighted as `TSString`:

![Screenshot_20210920_074707](https://user-images.githubusercontent.com/35768171/133946833-b4e383a5-c5ac-4bf2-830c-66bde6efeac5.png)

When double square brackets are used, the opening and closing square brackets have different highlighting, and the highlighting of the function definition is also wrong (`TSString` is used for types):

![Screenshot_20210920_075035](https://user-images.githubusercontent.com/35768171/133946942-6c53e26e-15ac-4ea6-b52c-405705b429a2.png)

### Expected behavior

Lua `ffi.cdef` string is always highlighted as C.

### Output of `:checkhealth nvim_treesitter`

```markdown
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.9.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - python         ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.0-dev+311-ge61ea7772e
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-git/src/build/config -I/build/neovim-git/src/neovim-git/src -I/usr/include -I/build/neovim-git/src/build/src/nvim/auto -I/build/neovim-git/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by stsewd** [comment]
Can you share the code from the images so it is easy for us to test?

**Comment by zeertzjq** [comment]
```lua
local ffi = require('ffi')
ffi.cdef('bool ctrl_x_mode_not_default(void);')

return function()
  local mode = vim.fn.strtrans(vim.fn.mode(true))
  if mode == 'ic' or (mode == 'i' and ffi.C.ctrl_x_mode_not_default()) then
    local ctrl_x_mode = vim.fn.complete_info({ 'mode' }).mode
    if ctrl_x_mode == '' then
      ctrl_x_mode = 'scroll'
    end
    mode = mode .. ':' .. ctrl_x_mode
  end
  return mode
end
```

**Comment by stsewd** [comment]
So, the error happens because the quotes are included in the injection, in this case `'bool` produces an error on C parser. This is the same problem as described in https://github.com/nvim-treesitter/nvim-treesitter/issues/1743#issuecomment-904654438.

I think it should be possible to write a query that doesn't match the quotes, but it may be a little complex.

**Comment by theHamsta** [comment]
The injection should use `offset!` to trim away " and ' offset! 1 0 -1 0 and match against [[ to use `offset!` with 2 0 -2 0 in the latter case. The injection query predates the offset! directive
