### ISSUE TITLE
Punctuation Special with Variable inside String detected as one whole string

### ISSUE THREAD

**Issue by ybbond** [nvim-treesitter/nvim-treesitter#1850]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`

### Describe the bug

through https://github.com/UserNobody14/tree-sitter-dart/issues/22

With Dart language treesitter. Pressing neovim's asterisk `*` or pound `#` on `TSVariable` to search word will include TSPunctSpecial interpolated inside TSString.

### To Reproduce

```dart
const String baseURL = 'https://github.com/nvim-treesitter/nvim-treesitter';
//             ^------ press * when cursor here
const String pullRequestsURL = '$baseURL/pulls';
const String issuesURL = '${baseURL}/issues';
```

given that example, the highlighted will only be the one in `issuesURL`.

---

```dart
const String baseURL = 'https://github.com/nvim-treesitter/nvim-treesitter';
const String pullRequestsURL = '$baseURL/pulls';
//                                ^------ press * when cursor here
const String issuesURL = '${baseURL}/issues';
```

given that example, the searched keyword will be `/$baseURL`

### Expected behavior

Dollar sign (`TSPunctSpecial`) with brace-less TSVariable interpolation inside TSString don't detected as part of the TSString.

### Output of `:checkhealth nvim_treesitter`

```markdown
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.9.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - html           ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - vim            ✓ ✓ . . ✓ 
  - http           ✓ . . . . 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - cmake          ✓ . ✓ . . 
  - zig            ✓ . ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - css            ✓ . ✓ ✓ ✓ 
  - gomod          ✓ . . . . 
  - dart           ✓ ✓ . ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.0-dev+318-g21f755527
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by xxxx@xxx.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-21f7555/share/nvim"

Run :checkhealth for more info
```

### Additional context

if I test the same in a string of a `*.lua` file, the behavior is different.

### Demo on Dart String

https://user-images.githubusercontent.com/25895873/132248632-926ee162-7420-4a8e-8a86-4f7affb42661.mov

### Demo on Lua string

https://user-images.githubusercontent.com/25895873/132248627-4557ca41-a55c-4f5d-ae33-eee943758de9.mov

**Comment by stsewd** [comment]
Hi, this isn't related to treesitter, but to your neovim configuration, see `:h iskeyword`. BTW, it works as expected for me using the default value

```
:set iskeyword?
@,48-57,_,192-255
```

**Comment by ybbond** [comment]
> Hi, this isn't related to treesitter, but to your neovim configuration, see `:h iskeyword`. BTW, it works as expected for me using the default value
> 
> ```
> :set iskeyword?
> @,48-57,_,192-255
> ```

I'd like to clarify, did you tried in Dart (or Flutter project) files too? as demoed above, it works in LUA, but not in Dart.

anyway, thanks for the relatively fast response :)

**Comment by ybbond** [comment]
@stsewd hi, in the previous reply, I declared that I have default `iskeyword`. I was wrong, because I did `set keyword?` on LUA file, when I do in Dart file, the keywords are:

```
iskeyword=@,48-57,_,192-255,$
```

I remember adding augroup to append dollar sign into `iskeyword` just for *.dart file. But the augroup has been deleted, it persists. I end up adding augroup to force default `iskeyword` value to Dart files.

thanks for giving insight to my problem! do you by chance know on where in my config I should check that adds dollar sign to `iskeyword` in dart files?

**Comment by stsewd** [comment]
> thanks for giving insight to my problem! do you by chance know on where in my config I should check that adds dollar sign to iskeyword in dart files?

Maybe a plugin is doing it, you can try disabling plugin by plugin or checking any of the paths from `:set runtimepath?`
