### ISSUE TITLE
cpp: closing all folds collapses the file in a single line

### ISSUE THREAD

**Issue by igorlfs** [nvim-treesitter/nvim-treesitter#1853]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`

### Describe the bug

When using treesitter's folds for C++, closing all folds (eg, zC) collapses the file in a single line. It probaly also affects other languages (though I'm not sure), but not all of them, as it works just fine with JavaScript.

### To Reproduce

1. Open a C++ file, and set the following:
2. `set foldmethod=expr`
2. `set foldexpr=nvim_treesitter#foldexpr()`
3. The file will collapse into a single line, as described.

### Expected behavior

The file SHOULD NOT collapse into a single line. 

### Output of `:checkhealth nvim_treesitter`

```markdown
health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v14.17.6 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `clang` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - bash           ✓ ✓ ✓ . ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.0-dev+284-gc2a65921d
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az32-807

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
```

### Additional context

I've been using `set foldlevel=1` as a workaround, but regardless of that, `zC` still doesn't work properly.

**Comment by stsewd** [comment]
Can you share the file where you are experimenting this, so we can test it more easily?

**Comment by igorlfs** [comment]
> Can you share the file where you are experimenting this, so we can test it more easily?

It happens with _any_ C++ file, something as simple as 

```
#include <iostream>
int main() {
  std::cout << "Hello World!\n";
  return 0;
}
```

**Comment by theHamsta** [comment]
@igorlfs does removing the line that jdrouhard suggested solve your problem? Could you create a PR?

**Comment by stsewd** [comment]
Yeah, toplevel nodes shouldn't be included in folds
