### ISSUE TITLE
Treesitter `highlight` function conflicting with `luochen1990/rainbow` plugin

### ISSUE THREAD

**Issue by OmanF** [nvim-treesitter/nvim-treesitter#1855]
**Is your feature request related to a problem? Please describe.**
Currently, TS's `highlight` functionality breaks `louchen1990/rainbow` plugin's functionality in that that the rainbow plugin is loaded, but then overridden, and all parens highlighting become single-color, like the `rainbow` plugin never started.

This can be easily confirmed:
1. Open a big file, that has a lot of parens fairly close to the file's top. As the file opens and TS works to parse it, the parens will be rainbow-ified. As soon as TS kicks in, TS's highlighter takes precedence and removes all coloring.
2. For that file, simply run `:TSBufDisable highlight` and notice all the parens being rainbow-ified.

**Describe the solution you'd like**
I'm hoping you can resolve the conflict, thus having all code semantic parts highlighted by TS, but all matching parens being color-coded by `Rainbow`.

**Describe alternatives you've considered**
There are (surprisingly) no other (good) parens rainbow plugins, so for every file, a choice must be made which is more important, TS semantic coloring, or rainbow parens.

There are, to my knowledge, no alternatives.

**Additional context**
`TSBufEnable highlight`:
<img width="1027" alt="screenshot_2021-09-23 15h18_09" src="https://user-images.githubusercontent.com/7848797/134505550-ec33f548-9eac-4208-82c4-f4c00a5865fe.png">

`TSBufDisable highlight`:

<img width="993" alt="screenshot_2021-09-23 15h18_30" src="https://user-images.githubusercontent.com/7848797/134505594-305b8585-3738-4e07-b781-72a9c7ed96ea.png">

**Comment by theHamsta** [comment]
You can map TSDelimiter and TSPunctSpecial to something not visible in order to not conflict with the parenthesis highlighting. There is also a tree-sitter-based parenthesis highlighter https://github.com/p00f/nvim-ts-rainbow (be careful whether it's performance is good enough for you)

**Comment by OmanF** [comment]
Also, I suspect, but haven't confirmed it yet, the same issue may cause indent lines coloring not showing, while all other settings do take effect when used with `lukas-reineke/indent-blankline.nvim`.

**Comment by OmanF** [comment]
Thanks for the reply concerning the parens.
I'll look into both options you listed.
