### ISSUE TITLE
Rust derive highlighting vanishes after 5 elements

### ISSUE THREAD

**Issue by MultisampledNight** [nvim-treesitter/nvim-treesitter#1856]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`

### Describe the bug

When typing a `#[derive()]` with 5 derive macros inside, any derive macro more just gets displayed the same highlighting as the `derive` itself (`PreProc`):
![Image showing the missing highlighting](https://user-images.githubusercontent.com/80128916/134557892-68d3f675-d5b5-479f-9472-3c68f9c51942.png)
(also again with the default colorscheme, in case my colorscheme is causing the issue:)
![Same as above, but with the `default` colorscheme](https://user-images.githubusercontent.com/80128916/134558343-4cc52784-b8fd-4f25-a9d6-34bd37a00f73.png)

This does not change with the count of characters, it seems to rely only on the count of the elements in the `derive` list.

### To Reproduce

1. Open up an empty buffer
2. Set filetype to `rust` (`:set ft=rust`)
3. Write `#[derive(a, b, c, d, e, f, g, h)]`
4. See the `PreProc` highlighting of `f`, `g` and `h` differ with the one by all other elements

### Expected behavior

To show _all_ elements in that list as the same highlighting, in this case, blue. (I'm not sure to which highlight that one is bound to, eventually `Type`?)

### Output of `:checkhealth nvim_treesitter`

```markdown
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.9.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - python         ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.0-dev+43-g02bf251bb
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/multisn8/info/lurk/quick-neovim-nightly/neovim/build/config -I/home/multisn8/info/lurk/quick-neovim-nightly/neovim/src -I/usr/include -I/home/multisn8/info/lurk/quick-neovim-nightly/neovim/build/src/nvim/auto -I/home/multisn8/info/lurk/quick-neovim-nightly/neovim/build/include
Compiled by multisn8@spaceshuttle

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by stsewd** [comment]
Can you share the file so is more easy for us to test?

**Comment by theHamsta** [comment]
This is probably related to the maximum number of results that the tree-sitter libraries keep. There was a plan to expose this option from a tree-sitter compile constant to be configured in Neovim

**Comment by MultisampledNight** [comment]
> Can you share the file so is more easy for us to test?

Surely, here you are in case it's of any use:
```rust
#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Debug)]
enum Elements {
    CoolElement,
    AnotherOne,
    TheseAreJustPlaceholders,
}
```

**Comment by MultisampledNight** [comment]
Works like a charm now. Thanks!
