### ISSUE TITLE
Scala highliting: invalid node type

### ISSUE THREAD

**Issue by chuwy** [nvim-treesitter/nvim-treesitter#1858]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`

### Describe the bug

Whenever I open any Scala file with TS highlighting enabled I'm getting this error:

```
treesitter/highlighter: Error executing lua: ...neovim-master/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 2397
```

### To Reproduce

1. Enable highlighting
2. Open `.scala` file

### Expected behavior

No error and highliting working without regex help

### Output of `:checkhealth nvim_treesitter`

```markdown
health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - WARNING: `node` executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - query          ✓ ✓ ✓ ✓ ✓ 
  - nix            ✓ ✓ ✓ . ✓ 
  - org            ✓ . . . ✓ 
  - scala          x . x . ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

The following errors have been detected:
  - ERROR: scala(highlights): ...d-master/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 2397
  - ERROR: scala(folds): ...d-master/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 144
```

### Output of `nvim --version`

```text
NVIM v0.6.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by antonparkhomenko

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/nzy87w4j77l1jiyrmxlifn9nv6i1jyc1-neovim-unwrapped-master/share/nvim
"
```

### Additional context

I had to disable some queries to fix it:

```
:TSEditQuery highlights
```

And comment some queries such as:

```scm
;;[
;;  "do"
;;  "for"
;;  "while"
;;  "yield"
;;] @repeat

;; (integer_literal) @number
;; (floating_point_literal) @float

[
  "=>"
;; "<-"
  "@"
] @operator

[
   "try"
   "catch"
;;   "throw"
] @exception
```

Originally posted in https://github.com/tree-sitter/tree-sitter-scala/issues/37, but it seems these queries belong to this repo.

**Comment by stsewd** [comment]
Can you share the file you are using? Looks like the queries need to be updated.

**Comment by chuwy** [comment]
Sure, here it is https://gist.github.com/chuwy/474edce052b4b46888af39dcb31fa82f (also same problem was for `folds` and I added few very sensbie folds)

Just in case - those commented keywords are completely valid and common Scala keywords, just something else doesn't recognize them as such.

**Comment by theHamsta** [comment]
If you already have the queries that fix the problem you're welcome to open a PR! We greatly appreciate it!

Would also be interesting why our CI didn't catch that.

**Comment by stsewd** [comment]
@chuwy I meant the scala file you are using p:

**Comment by chuwy** [comment]
@stsewd you mean the one I'm editing? It happens on pretty much any Scala file, i.e. minimal one like following:

```scala
object Foo {
  val bar = 42
}
```

Was already causing the problem.

I'm still bit reluctant to open a PR becase as I said those commented queries are perfectly valid Scala constructs and as Stephan pointed out - it haven't been caught by CI and nobody else complained.

**Comment by stevanmilic** [comment]
@chuwy Could you try updating the Scala parser and check if it works? It should work fine after https://github.com/tree-sitter/tree-sitter-scala/pull/34 has been merged.

**Comment by stsewd** [comment]
> @stsewd you mean the one I'm editing? It happens on pretty much any Scala file, i.e. minimal one like following:
> 
> ```scala
> object Foo {
>   val bar = 42
> }
> ```
> 
> Was already causing the problem.
> 
> I'm still bit reluctant to open a PR becase as I said those commented queries are perfectly valid Scala constructs and as Stephan pointed out - it haven't been caught by CI and nobody else complained.

I wasn't able to replicate the problem with that example. You can try re-installing the parser with `TSInstall! scala`.

**Comment by chuwy** [comment]
The issue still persists after `TSInstall! scala` and many other component updates. Would appreciate any tips on how I can debug it. Based on GH reactions @pistachiology also has the same problem?

**Comment by chuwy** [comment]
The issue persisited after many NeoVim/Tressitter/everything upgrades, but finally went away after purging `~/.local/share/nvim/` and `~/.cache/nvim/`.
