### ISSUE TITLE
Is there a better way to add one more parser to `ensure_installed` other than listing them all?

### ISSUE THREAD

**Issue by AndOrangutan** [nvim-treesitter/nvim-treesitter#1874]
I am currently setting up Neorg's `norg` parser and realized I am using
```
ensure_installed = "maintained",
```
Is there a way I can just add on `norg` without having to list all the other parsers?

**Comment by theHamsta** [comment]
Do you want to avoid `ensure_installed = "all",`? At the moment almost all parsers are maintained. `:TSUpdate norg` / `require 'nvim-treesitter.install'.update('norg')` would also work but display "Parsers update".

**Comment by AndOrangutan** [comment]
Yeah, I was attempting to stay away from unmaintained ones. I'll give what you suggested a shot.
