### ISSUE TITLE
Provide the ability to use a proxy when installing parsers

### ISSUE THREAD

**Issue by SChakravorti21** [nvim-treesitter/nvim-treesitter#1888]
**Is your feature request related to a problem? Please describe.**
I need to use a proxy at work to download anything that is outside of our company's network (eg. anything from `https://github.com`). In order to ensure that I only use the proxy when necessary (for me, that's when downloading vim plugins), I have set up `~/.gitconfig` to use the proxy like so:

```
[http "https://github.com"]
    proxy = http://<proxy url>
```

Package managers like `packer.nvim` automatically respect this configuration since they use `git` to install plugins, which means I don't have to `export https_proxy="..."` everytime I need to install a plugin (I also don't want to *always* have `https_proxy` set because that causes other problems with our internal systems 🙂).

However, when I try to install a parser using `:TSInstallSync cpp`, I get the following error:

```
Error during download, please verify your internet connection
Failed to execute the following command:
{
  cmd = "curl",
  err = "Error during download, please verify your internet connection",
  info = "Downloading...",
  opts = {
    args = { "--silent", "-L", "https://github.com/tree-sitter/tree-sitter-cpp/archive/a7652fce5943c9d5d9c49dd8e3256a699aa33bf5.tar.gz", "--output", "tree-sitter-cpp.tar.gz" },
    cwd = "/home/bldroot/.local/share/nvim"
  }
}
```

**Describe the solution you'd like**
I would like to be able to configure `nvim-treesitter` so that it uses a proxy when installing parsers. Some possible solutions:

- Being able to configure `nvim-treesitter` to pass a `--proxy` to `curl`
- Being able to configure `nvim-treesitter` to prefer using `git` instead of `curl` when possible (this will automatically respect `~/.gitconfig`)

The second option seems cleaner to me because it would allow people to configure more than just the proxy used by `git`. It would also spare `nvim-treesitter` from needing to support all of various ways in which `git` can be configured.

**Describe alternatives you've considered**
I can technically get around this by running neovim using `https_proxy="..." nvim` whenever I need to install a parser, but that's somewhat inconvenient.

**Additional context**
*N/A*

**Comment by theHamsta** [comment]
We could certainly add this option. Some else wanted to download from a different server that had a different URL. But you want a real proxy, so this wouldn't work for you?
```lua
for _, p in require("nvim-treesitter.parsers").get_parser_configs() do
  p.install_info.url = p.install_info.url:gsub('github.com', 'something_else.com')
end
```

**Comment by theHamsta** [comment]
Can you try https://github.com/nvim-treesitter/nvim-treesitter/pull/1889
```
require("nvim-treesitter.install").prefer_git = true
```
or
```
require("nvim-treesitter.install").command_extra_args = {
  curl = { "--foo", "baz" },
}
```

**Comment by SChakravorti21** [comment]
Sure, would love to try it out! How do I install `nvim-treesitter` from that branch?

**Comment by SChakravorti21** [comment]
Sweet, both options worked! For `curl`, I just used:
```
require("nvim-treesitter.install").command_extra_args = {
    curl = { "--proxy", "<proxy url>" },
}
```

**Comment by SChakravorti21** [comment]
Thank you so much! Just wanted to say that the turnaround time from request to implementation was impressively fast. Keep it up 😃
