### ISSUE TITLE
Rust loop labels don't get highlighting

### ISSUE THREAD

**Issue by MultisampledNight** [nvim-treesitter/nvim-treesitter#1891]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`

### Describe the bug

Loop labels don't get highlighted at all, only the leading `'` gets highlighted. Other editors highlight loop labels specially.

Code:
```rust
fn main() {
    let mut counter = 0;

    'game: loop {
        counter += 1;

        println!("{}", counter);

        if counter == 5 {
            break 'game;
        }
    }
}
```
How it's displayed:
![image](https://user-images.githubusercontent.com/80128916/135674705-7ceb29f4-6a02-4451-84a9-17550a303600.png)
How Visual Studio Code displays it (note the `'game`):
![image](https://user-images.githubusercontent.com/80128916/135674802-7e6aee3f-5014-4a1e-a596-88f89b81cd39.png)

If this is just a false positive and it's ignored for good or assigned to a highlight group I just don't know of, please mention it, I'm easily confusable at times.

### To Reproduce

1. Launch a new NeoVim instance with an empty buffer
2. Set the filetype to `rust` (`:set ft=rust`)
3. Write `'label: loop {}`
4. See `label` without direct highlighting

### Expected behavior

To see the label have the highlight group `Label`, or said in other words, to have it displayed in colors

### Output of `:checkhealth nvim_treesitter`

```markdown
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.10.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - python         ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.0-dev+368-g9337fff8a
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/multisn8/info/lurk/quick-neovim-nightly/neovim/build/config -I/home/multisn8/info/lurk/quick-neovim-nightly/neovim/src -I/usr/include -I/home/multisn8/info/lurk/quick-neovim-nightly/neovim/build/src/nvim/auto -I/home/multisn8/info/lurk/quick-neovim-nightly/neovim/build/include
Compiled by multisn8@spaceshuttle

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

I'm not sure if this is incorrect parsing, things getting assigned the wrong highlighting, or simply me being stupid

**Comment by stsewd** [comment]
This is just missing a query https://github.com/nvim-treesitter/nvim-treesitter/pull/1893
