### ISSUE TITLE
Windows 10 failure to compile with LLVM Clang

### ISSUE THREAD

**Issue by Zamachi** [nvim-treesitter/nvim-treesitter#1897]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`

### Describe the bug

Well I've got on a new Windows 10 machine, decided to install Neovim (using Chocolatey, latest version is 0.5), downloaded Neovim, fd, ripgrep, LLVM, Python3 all using Chocolatey and downloaded Pynvim using Pip3(which is included with Python3 package on choco), I've installed NodeJS via their own executable installer, setup proper folders on Windows (configs are stored @ by default `~/AppData/Local/nvim/` , and data is stored at `~/AppData/Local/nvim-data/` ). Cloned my repo with my plugins, ran PackerInstall and everything got installed successfully( I've yet to run `:COQdeps` ) except the treesitter parsers. Of course, Git is also installed because I'd need it to download packages. 

All of the necessary compilers/tools are available via PATH(tried it on both CMD and PowerShell) on User and/or System variables: 

![image](https://user-images.githubusercontent.com/32929482/135718016-700ba954-4c81-44b1-92f4-a5a08fa7254d.png)

The previously shown was User variables, which should be bare minimum for compiling Treesitter parsers. 
I've went through the [following link](https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support) setup treesitter to use Clang by default. I've tried `refreshenv` command, reset my PC, tried `:TSUpdate` (it said all parsers are up-to-date, they're downloaded, I can see their folders, but they cannot be compiled). 

It worked on my previous machine, but over there I've had Visual Studio, GCC, Clang, and all the the other non-essential stuff installed, it was bloated, but I don't see Visual Studio as a hard requirement, LLVM should be enough? 

Anyways, here's what the errors are spat out when it tries compiling the parsers:

![image](https://user-images.githubusercontent.com/32929482/135717307-989c42cb-3296-4bcf-9bdf-f2adb41e6718.png)

P.S. I know there is Neovim 0.5.1, I updated to it as well and it didn't help, the errors still persist

### To Reproduce

1. Download and install Chocolatey, NodeJS and Git
2. Using Chocolatey install the following: LLVM, fd, ripgrep, Neovim, Python3
3. Using Pip install Pynvim
4. Install Packer and configure it for Neovim
5. Using Packer, install `nvim-treesitter`, `autopairs` and `rainbow` and configure it this way(or remove the `autopairs` and `rainbow` settings):
```
require'nvim-treesitter.install'.compilers = { 'clang' }
require("nvim-treesitter.configs").setup{
	ensure_installed = { "c", "cpp", "json", "python", "lua", "html", "css", "javascript" },
	highlight = {
		enable = true
	},
	incremental_selection = {
		enable = true,
		keymaps = {
			init_selection = "gnn",
			node_incremental = "grn",
			scope_incremental = "grc",
			node_decremental = "grm",
		},
	},
	rainbow = {
		enable = true,
		extended_mode = true, 
		max_file_lines = nil,
		-- colors = {},
		-- termcolors = {} 
	},
    autopairs = { enable = true }
}
vim.api.nvim_exec([[
	set foldmethod=expr
	set foldexpr=nvim_treesitter#foldexpr()
]], true)

```
6. Wait for nvim-treesitter to download parsers specified in `ensure_installed` and check if they compile

### Expected behavior

Well, nvim-treesitter should download AND compile successfully all the parsers if everything was done correctly. For me it only succeeds at downloading, but compiling doesn't work, even though the Clang compiler is recognized by Neovim

### Output of `:checkhealth nvim_treesitter`

```markdown
health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v14.18.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `clang` executable found. Selected from { "clang" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-786

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

### Additional context

I'll note here again, I've written this config when Neovim 0.5 was on the `master`, I tried this with both 0.5 using Chocolatey and manually installing v0.5.1, the errors are the same, and the outputs for checkhealth are the same as well( `nvim --version` obviously is different, it points to v0.5.1).

**Comment by maxmx03** [comment]
### Here works fine with mingw

# install scoop

```powershell
iwr -useb get.scoop.sh | iex
```

## with mingw gcc v8 (recommend)

```powershell
scoop install mingw
```

### treesitter.rc.lua

```lua
require "nvim-treesitter.install".compilers = {"gcc"}
```

## with gcc v11 (not working)

```powershell
scoop install gcc
```

## [nvim-windows](https://github.com/maxmx03/dotfiles/tree/main/.config/nvim-windows)

**Comment by stsewd** [comment]
Would be great if you could update the windows guide, If those steps aren't already there https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support


@Zamachi can you try those steps?

**Comment by Zamachi** [comment]
Sorry I'm only answering now, this was published a long time ago, anyhow, from what I understood how using LLVM on Windows works, I **must** install MSVC in order to use Clang, because for some reason, it is a requirement for me to have both compilers, as if somehow Clang isn't self-sufficient...
Another problem I encountered with this is that, after I install MSVC, there's absolutely no way for me to explicitly use Clang in a terminal, because Microsoft does some kind of witchcraft which prevents me for setting flags for the compiler to use a linker, libraries etc. required by Clang... The only way it would work is if I used it in Visual Studio(which is not what I want)...
