### ISSUE TITLE
Pause highlighting

### ISSUE THREAD

**Issue by Abh15h3k** [nvim-treesitter/nvim-treesitter#1944]
**Is your feature request related to a problem? Please describe.**
Currently highlighting for (big or in big projects) typescript / javascript files are pretty slow. makes typing very sluggish.

**Describe the solution you'd like**
either a command / function to pause queries. so it can be used to pause highlight updates on InsertEnter and continue on InsertLeave.

**Describe alternatives you've considered**
currently im using `au InsertEnter *ts :TSBufDisable highlight` `au InsertLeave *ts TSBufEnable`.
but this cause all TS highlighting to be undone on disable.

**Additional context**
n/a

**Comment by gwerbin** [comment]
Is it possible to check if a Tree Sitter module is currently enabled/disabled? If so, it'd be pretty easy to write a function/command to toggle between them.

**Comment by kyazdani42** [comment]
You can now use `require"nvim-treesitter.highlight".stop(bufnr)` and `require"nvim-treesitter.highlight".start(bufnr, lang)`  to pause/restart the highlighter.
