### ISSUE TITLE
Performance Discussion - Haskell TreeSitter

### ISSUE THREAD

**Issue by JonathanLorimer** [nvim-treesitter/nvim-treesitter#1947]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`

### Describe the bug

Haskell tree-sitter grammar is very slow on large-ish files (~300+ lines). We started a discussion on the issue [here](https://github.com/tree-sitter/tree-sitter-haskell/issues/41)

I am not very familiar with the nvim-treesitter project, and I was wondering if my summary of the performance issues [here](https://github.com/tree-sitter/tree-sitter-haskell/issues/41#issuecomment-950942354) is accurate. Particularly I am interested to know if, in insert mode, the entire state tree is recomputed, or if it is localized to the particular node that is being edited.

### To Reproduce

1. clone this project https://github.com/JonathanLorimer/tree-sitter-haskell/tree/profile-haskell
2. make sure that the haskell treesitter grammar is installed
3. open `profile.hs` from the root of the project
4. enter insert mode and type something

### Expected behavior

Smooth typing

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
  - ERROR: Failed to run healthcheck for "nvim-treesitter" plugin. Exception:
    function health#check, line 24
    Vim(eval):E5108: Error executing lua [string "luaeval()"]:1: attempt to call field 'check' (a nil value)

---------------

I am not sure what is up with this? nvim-treesitter works just fine, and others are experiencing the lag as well. Its literally only the performance that gives me problems.
```

### Output of `nvim --version`

```text
$ nvim --version
NVIM v0.6.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld
```

**Comment by theHamsta** [comment]
I think, if still applicable, this is a issue for tree-sitter-haskel - not for this repo.
