### ISSUE TITLE
Parsers using c++14 kick me back to the powershell prompt on windows 10

### ISSUE THREAD

**Issue by Binx-Codes** [nvim-treesitter/nvim-treesitter#1959]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`

### Describe the bug

I am running Windows 10, and using neovim 0.6 on it. Note, i'm not using WSL. Whenever I install a treesitter parser which uses c++14 and open a file using neovim with the language treesitter parser I just installed. It hangs for about 5 seconds, and kicks me out of neovim, and back to the powershell prompt e.g this issue happens when I install the `lua` treesitter parser using `:TSInstall lua`. The issue I explained above now, only happens when I open/create a file with that same filetype I installed the treesitter parser. So basically it only kicks me out when I do `nvim example.lua`, the rest of the filetypes when opened/created work just as expected. (Looks like the parsers which use c++14 is the cause to this issue). I currently use `clang`, which I have installed through Microsoft Visual Studio Community 2019.

List of treesitter parsers which I have tried, and cause the same issue:
- `haskell`
- `lua`
- [`norg`](https://github.com/nvim-neorg/tree-sitter-norg)

Output of `clang --version`:
```bash
clang version 12.0.0
Target: i686-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\Llvm\bin

### To Reproduce

1. Open neovim
2. Install the `lua` treesitter parser using `:TSInstall lua`
3. Open/create a `lua` file in neovim e.g `nvim example.lua`

### Expected behavior

I install any treesitter parser, open a file with the same filetype of the treesitter parser I just installed. And neovim doesn't kick me out, back to the powershell prompt.

### Output of `:checkhealth nvim-treesitter`

```markdown
(When I do `:checkhealth nvim-treesitter` in neovim, it kicks me out of neovim and back to the powershell prompt).
```

### Output of `nvim --version`

```text
NVIM v0.6.0-dev+544-g7ae86c1d4
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az152-71

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

**Comment by theHamsta** [comment]
I don't think that Lua uses any C++14 features. The C++ standard shouldn't affect the binary after the compilation while the used version of the c++ runtime can. Did you find a parser with a C++ scanner were this does not happen?

Is there a profiler that you could use to find out where Neovim/the parser stops during that 5 seconds?

**Comment by Binx-Codes** [comment]
> 
> 
> I don't think that Lua uses any C++14 features. The C++ standard shouldn't affect the binary after the compilation while the used version of the c++ runtime can. Did you find a parser with a C++ scanner were this does not happen?

Yeah, you're right lua doesn't use them. No, I haven't found any TS parser with a c++ scanner where it does work as expected.

> 
> Is there a profiler that you could use to find out where Neovim/the parser stops during that 5 seconds?

Hmm, I don't really know of any profilers I could use 😦

**Comment by Binx-Codes** [comment]
@theHamsta Hi! I just wanted to let you know that I fixed the issue! 🥳 

Basically all I did was install mingw through msys2, and it fixed the issue
