### ISSUE TITLE
General performance issues after the latest update.

### ISSUE THREAD

**Issue by lifer0se** [nvim-treesitter/nvim-treesitter#1964]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`

### Describe the bug

After the latest update there has been a considerable decrease in performance. I was playing around with some plugins and I did a plug update, after which the cursor will lag when going to a variable, typing or even in the command line. It took me some time to narrow down the issue and it seems to be treesitter as without it the problem disappears.

I've tried disabling all other plugins apart from treesitter and nvm-lspconfig and the problem persists.

I know this is not much to go on. I tried the profiler and there wasn't anything to go on.
Profiler output:
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   37   0.012410   0.010914  <SNR>50_Highlight_Matching_Pair()
    3   0.002734   0.002594  <SNR>29_LoadFTPlugin()
   39   0.001573             <SNR>50_Remove_Matches()
    4   0.001503   0.000995  <SNR>32_SynSet()
    3   0.000412   0.000388  <SNR>30_LoadIndent()
    3   0.000309             <SNR>51_LocalBrowse()
    2   0.000027             <SNR>59_dopopd()
    1   0.000012             FugitiveDetect()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
   37   0.012410   0.010914  <SNR>50_Highlight_Matching_Pair()
    3   0.002734   0.002594  <SNR>29_LoadFTPlugin()
   39              0.001573  <SNR>50_Remove_Matches()
    4   0.001503   0.000995  <SNR>32_SynSet()
    3   0.000412   0.000388  <SNR>30_LoadIndent()
    3              0.000309  <SNR>51_LocalBrowse()
    2              0.000027  <SNR>59_dopopd()
    1              0.000012  FugitiveDetect()
```

### To Reproduce

1. Install treesitter
2. Lag..

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.11.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.
```

### Output of `nvim --version`

```text
NVIM v0.6.0-dev+546-g7f4b7320f
Build type: Debug
LuaJIT 2.1.0-beta3
```

**Comment by theHamsta** [comment]
To which *last update* do you refer to? Can you give a commit? An update of nvim-treesitter or Neovim?

**Comment by lifer0se** [comment]
Not sure which commit caused the issue, my last update through Plug was around 2 weeks ago.
As for which language, all of them. Any language with a parser makes nvim lag, as long as highlighting is enabled and/or playground is toggled.

My setup function is currently this:
`require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained",
  highlight = {
    enable = true,
  }
}`

I do have more options in the config, but I've commented all of them out to narrow down the issue.

**Comment by theHamsta** [comment]
We cannot reproduce your issue. Can you please bisect to determine which commit introduced the problems for you?

**Comment by lifer0se** [comment]
After a few hours of bashing my head trying to fix the issue, I decided to reinstall my distro, which fixed the issue. Something must have gotten messed up in my files - no idea what. Closing this, sorry for the trouble :)
