### ISSUE TITLE
regex lookahead / lookbehind broken for "#match?" predicate

### ISSUE THREAD

**Issue by yomotherboard** [nvim-treesitter/nvim-treesitter#1977]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`

### Describe the bug

Regex lookahead and lookbehind is not functioning for "#match?" predicate. The error returned is:
```
E5108: Error executing lua ...d/playground/lua/nvim-treesitter-playground/internal.lua:634: Vim(lua):E5108: Error executing lua /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:234 couldn't parse regex: Vim:E866 (NFA regexp) Misplaced ?
```

### To Reproduce

In a query folder or in the playground (reproduced in both) write a query that uses the `#match?` predicate, e.g.:

Javascript code:
```
color = red;
```

Query:
```
(
	(assignment_expression
		left: (_) @assignment.left
    	right: ((_) @assignment.right (#match? @assignment.right "^(?!red)")))
)
```

### Expected behavior

The above code should exclude assignments to "red" from the match. This is a simplified example though.

I am trying to match for javascript assignments without including function assignments. This can be done without negative lookahead but the solution is much more hacky. I tried using `#not-match?` first but it didn't seem to be working as intended. The query I am using:
```
(assignment_expression
    left:(_) @assignment.left
    right:((_) @assignment.right (#match? @assignment.right "^(?!function)")))
```

### Output of `:checkhealth nvim-treesitter`

```markdown
## Installation
  - OK: `tree-sitter` found  0.20.0 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.11.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - bash           ✓ ✓ ✓ . ✓
  - vim            ✓ ✓ . . ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - query          ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.0-dev+555-gf26b39131
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by jab

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
```


### Additional context

_No response_

**Comment by savq** [comment]
It seems other `#match?` regexes are failing (not just lookaheads). For example, non-scoped Rust functions are being highlighted as constants, probably because the query for enum constructors that isn't respecting case sensitivity.

**Comment by stsewd** [comment]
> It seems other `#match?` regexes are failing (not just lookaheads). For example, non-scoped Rust functions are being highlighted as constants, probably because the query for enum constructors isn't respecting case sensitivity.

if some predicate are being skipped, that's a bug that was already fixed on neovim nightly.

**Comment by yomotherboard** [comment]
@stswed Just confirmed all lookahead regex do not function for `#match?` in nightly (same behavior as initially described). @savq `#match?` predicate seems to be working fine otherwise for me.

**Comment by savq** [comment]
This is what I'm getting:

<img width="405" alt="Screen Shot 2021-11-06 at 13 38 46" src="https://user-images.githubusercontent.com/30883030/140620541-7b045ad6-f7b5-4653-9423-067be42f5def.png">

All `f`s used to be the same color. `m` and `T` should also be highlighted differently. It seems some queries, specifically [1](https://github.com/nvim-treesitter/nvim-treesitter/blob/83efae51bfe92163e7cb0d215d9e9f746830ab6f/queries/rust/highlights.scm#L63) and [2](https://github.com/nvim-treesitter/nvim-treesitter/blob/83efae51bfe92163e7cb0d215d9e9f746830ab6f/queries/rust/highlights.scm#L81) highlight everything, regardless of the `#match?` query.



<details> <summary> nvim --version</summary>

```
NVIM v0.6.0-dev+nightly-1346-g03b805aee
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by savq@

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-03b805a_1/share/nvim"

Run :checkhealth for more info
```

</details>

**Comment by savq** [comment]
@yomotherboard, I took another look at the issue, and it seems vim regex syntax differs from perl syntax here. The equivalent  syntax for `?!` would be `\@!`, that is:

```scm
((assignment_expression
  left: (_) @assignment.left
  right: (_) @assignment.right
  (#match? @assignment.right "^(function)\@!")))
```

**Comment by savq** [comment]
PS: many `#match?` queries were changed to `#lua-match?`, which fixed the issue I mentioned beforehand.

**Comment by stsewd** [comment]
ah, yes that's not the vim syntax for look ahead. See `:h /\@!`
