### ISSUE TITLE
hl_map['method'] ignores color

### ISSUE THREAD

**Issue by fdschmidt93** [nvim-treesitter/nvim-treesitter#198]
**Describe the bug**
When defining a highlight scheme for the method the hlmap["method"] group ignores the color being set and seems to revert to the global default.

![tree-sitter_issue](https://user-images.githubusercontent.com/39233597/87828905-478bcc00-c87e-11ea-8339-778dd8220c81.png)
On the left-hand side, I have set the color bold_red for hlmap["method"]. However, as seen for torch.arange on the right-hand side only the bold font is being applied. I played a lot with the highlighting groups (still have not found how I quite like it perfectly :) and everything else seemed to have worked fine.

**To Reproduce**
Set hlmap["method"] to anything else but the standard highlighting group. For instance, see "[4.8] nvim-treesitter in my [init.vim](https://github.com/fdschmidt93/dotfiles/blob/master/nvim/.config/nvim/init.vim). I define highlighting groups for my colorscheme gruvbox further below manually to have more control and hopefully facilitates to reproduce the issue.

**Expected behavior**
Color highlighting for method group as set in config.

**Output of :checkhealth nvim_treesitter**
health -- nvim_treesitter -- check
-- Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

-- python parser 
  - OK: python parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.

**Output of `nvim --version`**
NVIM v0.5.0-594-ga02a267f8
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-8f879c1d-28ee-4300-8b89-6a5ac11fd666

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

**Additional context**
Thank you for your great work on the plugin! Great progress and I've been playing with the past few days quite a lot :)

**Comment by vigoux** [comment]
Hi, I guess that what you want is the `__init__` colored in bright red right ?

If that's the case, it is normal as (looking at the queries) we don't use the `@method` in method declarations for python. 
@theHamsta do you have any opinion on this ?

**Comment by fdschmidt93** [comment]
Hi, no - see the arange method of torch in line 28 on the right-hand side, which should be red rather than blue as per my configuration.

> If that's the case, it is normal as (looking at the queries) we don't use the @method in method declarations for python.
I'm not sure if this conflicts with the fact that bold fonts can be applied to methods - the highlighting just disregards the color.

Many thanks for your consideration!

**Comment by vigoux** [comment]
The thing that bugs is that it is highlighted in bold blue, as if the bold red was applied and then a blue highlight.

What I tend to think by looking at that is that the highlights query is wrong and the order between method calls highlighting and field highlighting should be reversed.

I can't confirm though, and I think that @theHamsta will have better answers than I have.

**Comment by theHamsta** [comment]
My opinion: it makes no sense to distinguish between functions and methods. Especially at caller site. This is why I suggested earlier to introduce a "@call" highlight. Because at caller site you can only guess (at least now). There might be alleviations in future when we use definitions of identifiers also in highlighting. Then, we can decide whether the scoped call is a function knowing the preceding identifier is a module and not an object.
 
- I added highlighting of methods at definition site.

**Comment by fdschmidt93** [comment]
Apologies, on further playing around I actually think the behavior I observed rooted in some intertwinedness between "function", "field", and "method" I did not realize at first. I'm sorry, I don't entirely understand what you are referring to @theHamsta though I suspect it has to to what I'm describing.

Consider the below example -

```
def test_fun():
    pass

class TestClass:
    def __init__(self):
        pass 

    def cool_method(self):
        pass

cls = TestClass()
cls.cool_method()
```
For clarity, "words" refer to key of hlmap.

| What?  | Color | Boldness|
| ------------- | ------------- |------------- |
| def test_fun  | "function"  | "function"|
| test_fun()  | "function"  | "function"|
| def cool_method  | "method"  | if "function" bold; otherwise set by "method" |
| cool_method()  | "field"  | if "field" bold; otherwise set by "method" |

A consequence from the above,  say "method" and "field" were set to non-bold fonts, while "function" is. Boldness of function only propagates to def cool_method but not its call.

And this is what the default looks like for Gruvbox. "method" is linked to TSFunction, that's why both are bright green and bold. The color (boldness) of cool_method() comes from "field" ("method"), as you can derive from when looking at random module from numpy.

![Screenshot from 2020-07-20 12-16-44](https://user-images.githubusercontent.com/39233597/87927113-fb5da900-ca82-11ea-8a1e-1224b93a5988.png)

And yes, per semantics it does not make sense to distinguish between functions and methods and you can say that it's consistent that way. However, I guess if it would also be consistent if cls.cool_method() were also bright green and bold, but then there is no clear relationship between "method" and "field" anymore. In sum, if the above described behavior is intended, we can close this. 

Sorry to go through all that length and many thanks!

**Comment by theHamsta** [comment]
Right now: the highlights rely on the the fact that each highlight can override each other highlight. Since the treesitter query syntax is quite limited now. All class methods are highlighted: function+method and the calls field+method.

Can you try that your method highlight can override previous highlights? Then, the highlight should be purely method for both situations.

**Comment by fdschmidt93** [comment]
> All class methods are highlighted: function+method and the calls field+method.

Yeah that's true on a high level, but there is some non-obvious though logical connection here. See below.

> Can you try that your method highlight can override previous highlights (by also setting a color)? Then, the highlight should be purely method for both situations.

The color of `cls.cool_method()` is not being overriden by method if that's what you are referring to. `cls.cool_method()` always takes the color from "field". Sorry if that was not perfectly clear from the table. 

To illustrate what the table refers to. On the left side, you can see the color configuration (set properly outside picture) for the fields, and see them applied on the right-hand side:

Example 1:
----
"function" - purple and not bold
"method" - red and bold
"field" - blue and not bold

"method" overrides color of "function" and, as "function" is not bold, method overrides it appropriately. `cls.cool_method()`  is bold because "method" is bold. Otherwise `random` of `np.random.randint` would also be bold, but it takes its color from "field".

![example1](https://user-images.githubusercontent.com/39233597/87935170-dff99a80-ca90-11ea-883f-24e4d1b28c8f.png)

I think that already clarifies what you were asking for.

Example 2:
----
"function" - purple and  bold
"method" - red and not bold
"field" - blue and not bold

![Example 2](https://user-images.githubusercontent.com/39233597/87935745-f48a6280-ca91-11ea-9768-f9f7176d9b63.png)

Here, the boldness of "function" propagates to `def cool_method` even though "method" is not set to a bold font. Further, it does not cascade to `cls.cool_method()`, and again `cls.cool_method` takes its color from field. 
If I would now set `method` to red and bold, `cls.cool_method` would be bold as well. If instead "field" was bold (and "method" not) in this example `cool_method()` and `random.randint` would all be bold.

Hope that clarifies my remarks above.

**Comment by theHamsta** [comment]
Does putting the @field highlight to the top of the `python/highlights.scm` file help? It's currently at the bottom, so applied lastly. I am not sure whether it's possible to solve the issue with bold highlighting.

The current treesitter highlighter is still limited. I would recommend you to try out whether any reordering or deactivating of the queries can solve your problem. If this is not possible we need to make sure that field and method can never occur at the same time by excluding that in the query for field (we need to add a directive for that as this is not possible with the current query DSL).

**Comment by fdschmidt93** [comment]
Ordering does not seem to matter. 

> The current treesitter highlighter is still limited. 

Yeah, this is a minor issue that only came up because default highlighting on (default version of) gruxbox requires a bit of getting used to I guess. 

Nevertheless, this is a very peculiar issue and a method call having the color of field is not far-fetched though I guess aligning method calls with function (calls) comes more natural. 

> I would recommend you to try out whether any reordering or deactivating of the queries can solve your problem.

I'll revisit the issue and try to look into how queries are defined more in-depth, once I have time (beginning of August), maybe there is something there. Thanks a lot in any case!

**Comment by theHamsta** [comment]
At least on my machine, reordering fixes your issue: https://github.com/theHamsta/nvim-treesitter/pull/new/python-prefer-method
You're sure that this fails with gruvbox? I admit that we have not yet the same priority system as classical vim syntax highlighting for conflicting highlights.

**Comment by fdschmidt93** [comment]
I'm sorry, my bad. I read too quickly over your comment and merely re-ordered the hlmap in the config rather than in the scm file :x Re-ordering as per your pull request resolves the coloring issue. 

Solely for completeness - font boldness can still propagate. For instance, say one sets method to a normal and function to a bold font. The definition of the method will then be bold, whereas the method call won't. But I guess that is a minor edge case.

Many thanks!

**Comment by vigoux** [comment]
> Solely for completeness - font boldness can still propagate. For instance, say one sets method to a normal and function to a bold font. The definition of the method will then be bold, whereas the method call won't. But I guess that is a minor edge case.

Interesting note, we will be working on this.
