### ISSUE TITLE
Error executing lua Failed to load parser: uv_dlopen: cpp.so is not a valid Win32 application.

### ISSUE THREAD

**Issue by 17Swagat** [nvim-treesitter/nvim-treesitter#1985]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`

### Describe the bug

When ever try to open my .cpp file which contains Win32 code in it with **neovide (or nvim) from command-prompt or any other .cpp file I get an error saying:
 "Error_ detected while processing FileType Autocommands for "*":
E5108: Error executing lua Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\cpp.so is not a valid Win32 application."**

pics:->
<img width="960" alt="error1" src="https://user-images.githubusercontent.com/72545910/140612461-488985ef-b0ef-4545-88c1-ea34e4cd09e0.PNG">

 and there is no syntax highlighting for the Win32 api code.

pics:->
 
<img width="960" alt="f1" src="https://user-images.githubusercontent.com/72545910/140612542-6ab3ae19-0025-4873-a24d-5746cc4271a9.PNG">

<img width="960" alt="f2" src="https://user-images.githubusercontent.com/72545910/140612549-3d6d51d4-42f5-4de1-a053-d00d70b1a874.PNG">

<img width="960" alt="f5" src="https://user-images.githubusercontent.com/72545910/140612552-740952b1-8e75-4e40-adaa-35550ae46c80.PNG">

**But when I do the same thing from Cmder or Git (I use neovide. Since nvim do not works properly with cmder) I get No-Errors and also get a proper syntax highlighting for the code.**

pics:->
<img width="960" alt="g1" src="https://user-images.githubusercontent.com/72545910/140612613-03d9dd7f-8359-4a00-a6b8-6e491c71d0e5.PNG">

<img width="957" alt="g2" src="https://user-images.githubusercontent.com/72545910/140612622-eeb5beaf-c42e-4ba9-b280-d5ad493597fd.PNG">

<img width="960" alt="g3" src="https://user-images.githubusercontent.com/72545910/140612626-01bcd9c4-d716-4528-8a1c-ddb4061bca56.PNG">

### To Reproduce

1. Open the file contaning Win32 (or C++) code with Neovide (or nvim) from **Command prompt** to get the following error and no syntax highlighting for the Win32 code.
2.  Open the file contaning Win32 (or C++) code with Neovide from **Cmder or Git** to get the following error and no syntax highlighting for the Win32 code.

### Expected behavior

I Expect that the neovim and neovide to show me proper syntax highlighting for my Win32 code and no errors like the following. I want the same behaviour when I open the file with Neovide and Neovim from Command prompt, just like when I do the same thing from Cmder Or Git.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (e85a279cf29da1b08648e27214dda20a841e57c8) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.6.2 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: gcc.exe (MinGW-W64 x86_64-posix-seh, built by Brecht Sanders) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - python         x x x x x 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - gomod          ✓ . . . . 
  - graphql        ✓ . . ✓ ✓ 
  - ruby           x x x x x 
  - perl           x . . . . 
  - bash           x x x . x 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - php            x x x x x 
  - java           ✓ ✓ . ✓ ✓ 
  - rst            ✓ ✓ . . ✓ 
  - fennel         ✓ ✓ . . ✓ 
  - html           x x x x x 
  - teal           ✓ ✓ ✓ ✓ ✓ 
  - julia          ✓ ✓ ✓ ✓ ✓ 
  - ql             ✓ ✓ . ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - scss           ✓ . . ✓ . 
  - comment        ✓ . . . . 
  - jsdoc          ✓ . . . . 
  - elixir         ✓ ✓ ✓ ✓ ✓ 
  - sparql         ✓ ✓ ✓ ✓ ✓ 
  - gdscript       x x . . x 
  - heex           ✓ . ✓ ✓ ✓ 
  - ocaml          x x x . x 
  - godotResource  ✓ ✓ ✓ . . 
  - ocaml_interfacex x x . x 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - ocamllex       x . . . x 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - beancount      ✓ . ✓ . . 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - latex          ✓ . ✓ . ✓ 
  - scala          ✓ . ✓ . ✓ 
  - supercollider  ✓ ✓ ✓ ✓ ✓ 
  - llvm           ✓ . . . . 
  - hcl            x . x x x 
  - zig            ✓ . ✓ ✓ ✓ 
  - cmake          ✓ . ✓ . . 
  - tlaplus        x . x . x 
  - pioasm         ✓ . . . ✓ 
  - vim            ✓ ✓ . . ✓ 
  - json5          ✓ . . . ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - clojure        ✓ ✓ ✓ . ✓ 
  - glimmer        ✓ . . . . 
  - hjson          ✓ ✓ ✓ ✓ ✓ 
  - commonlisp     ✓ ✓ ✓ . . 
  - bibtex         ✓ . ✓ ✓ . 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - r              ✓ ✓ . . . 
  - cpp            x x x x x 
  - svelte         ✓ . ✓ ✓ ✓ 
  - devicetree     ✓ ✓ ✓ ✓ ✓ 
  - cuda           x x x x x 
  - regex          ✓ . . . . 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - yaml           x x x x x 
  - dockerfile     ✓ . . . ✓ 
  - yang           ✓ . ✓ . . 
  - css            ✓ . ✓ ✓ ✓ 
  - lua            x x x x x 
  - nix            ✓ ✓ ✓ . ✓ 
  - surface        ✓ . ✓ ✓ ✓ 
  - glsl           ✓ ✓ ✓ ✓ ✓ 
  - erlang         . . . . . 
  - dot            ✓ . . . ✓ 
  - vue            x . x . x 
  - kotlin         ✓ . . . ✓ 
  - dart           ✓ ✓ . ✓ ✓ 
  - ledger         ✓ . ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: python(highlights): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\python.so is not a valid Win32 application.

  - ERROR: python(locals): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\python.so is not a valid Win32 application.

  - ERROR: python(folds): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\python.so is not a valid Win32 application.

  - ERROR: python(indents): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\python.so is not a valid Win32 application.

  - ERROR: python(injections): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\python.so is not a valid Win32 application.

  - ERROR: ruby(highlights): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\ruby.so is not a valid Win32 application.

  - ERROR: ruby(locals): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\ruby.so is not a valid Win32 application.

  - ERROR: ruby(folds): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\ruby.so is not a valid Win32 application.

  - ERROR: ruby(indents): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\ruby.so is not a valid Win32 application.

  - ERROR: ruby(injections): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\ruby.so is not a valid Win32 application.

  - ERROR: perl(highlights): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\perl.so is not a valid Win32 application.

  - ERROR: bash(highlights): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\bash.so is not a valid Win32 application.

  - ERROR: bash(locals): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\bash.so is not a valid Win32 application.

  - ERROR: bash(folds): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\bash.so is not a valid Win32 application.

  - ERROR: bash(injections): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\bash.so is not a valid Win32 application.

  - ERROR: php(highlights): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\php.so is not a valid Win32 application.

  - ERROR: php(locals): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\php.so is not a valid Win32 application.

  - ERROR: php(folds): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\php.so is not a valid Win32 application.

  - ERROR: php(indents): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\php.so is not a valid Win32 application.

  - ERROR: php(injections): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\php.so is not a valid Win32 application.

  - ERROR: html(highlights): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\html.so is not a valid Win32 application.

  - ERROR: html(locals): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\html.so is not a valid Win32 application.

  - ERROR: html(folds): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\html.so is not a valid Win32 application.

  - ERROR: html(indents): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\html.so is not a valid Win32 application.

  - ERROR: html(injections): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\html.so is not a valid Win32 application.

  - ERROR: gdscript(highlights): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\gdscript.so is not a valid Win32 application.

  - ERROR: gdscript(locals): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\gdscript.so is not a valid Win32 application.

  - ERROR: gdscript(injections): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\gdscript.so is not a valid Win32 application.

  - ERROR: ocaml(highlights): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\ocaml.so is not a valid Win32 application.

  - ERROR: ocaml(locals): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\ocaml.so is not a valid Win32 application.

  - ERROR: ocaml(folds): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\ocaml.so is not a valid Win32 application.

  - ERROR: ocaml(injections): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\ocaml.so is not a valid Win32 application.

  - ERROR: ocaml_interface(highlights): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\ocaml_interface.so is not a valid Win32 application.

  - ERROR: ocaml_interface(locals): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\ocaml_interface.so is not a valid Win32 application.

  - ERROR: ocaml_interface(folds): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\ocaml_interface.so is not a valid Win32 application.

  - ERROR: ocaml_interface(injections): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\ocaml_interface.so is not a valid Win32 application.

  - ERROR: ocamllex(highlights): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\ocamllex.so is not a valid Win32 application.

  - ERROR: ocamllex(injections): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\ocamllex.so is not a valid Win32 application.

  - ERROR: hcl(highlights): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\hcl.so is not a valid Win32 application.

  - ERROR: hcl(folds): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\hcl.so is not a valid Win32 application.

  - ERROR: hcl(indents): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\hcl.so is not a valid Win32 application.

  - ERROR: hcl(injections): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\hcl.so is not a valid Win32 application.

  - ERROR: tlaplus(highlights): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\tlaplus.so is not a valid Win32 application.

  - ERROR: tlaplus(folds): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\tlaplus.so is not a valid Win32 application.

  - ERROR: tlaplus(injections): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\tlaplus.so is not a valid Win32 application.

  - ERROR: cpp(highlights): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\cpp.so is not a valid Win32 application.

  - ERROR: cpp(locals): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\cpp.so is not a valid Win32 application.

  - ERROR: cpp(folds): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\cpp.so is not a valid Win32 application.

  - ERROR: cpp(indents): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\cpp.so is not a valid Win32 application.

  - ERROR: cpp(injections): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\cpp.so is not a valid Win32 application.

  - ERROR: cuda(highlights): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\cuda.so is not a valid Win32 application.

  - ERROR: cuda(locals): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\cuda.so is not a valid Win32 application.

  - ERROR: cuda(folds): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\cuda.so is not a valid Win32 application.

  - ERROR: cuda(indents): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\cuda.so is not a valid Win32 application.

  - ERROR: cuda(injections): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\cuda.so is not a valid Win32 application.

  - ERROR: yaml(highlights): Failed to load parser: uv_dlopen: The specified module could not be found.

  - ERROR: yaml(locals): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\yaml.so is not a valid Win32 application.

  - ERROR: yaml(folds): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\yaml.so is not a valid Win32 application.

  - ERROR: yaml(indents): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\yaml.so is not a valid Win32 application.

  - ERROR: yaml(injections): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\yaml.so is not a valid Win32 application.

  - ERROR: lua(highlights): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\lua.so is not a valid Win32 application.

  - ERROR: lua(locals): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\lua.so is not a valid Win32 application.

  - ERROR: lua(folds): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\lua.so is not a valid Win32 application.

  - ERROR: lua(indents): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\lua.so is not a valid Win32 application.

  - ERROR: lua(injections): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\lua.so is not a valid Win32 application.

  - ERROR: vue(highlights): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\vue.so is not a valid Win32 application.

  - ERROR: vue(folds): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\vue.so is not a valid Win32 application.

  - ERROR: vue(injections): Failed to load parser: uv_dlopen: C:\Users\Swagat\AppData\Local\nvim\plugged\nvim-treesitter\parser\vue.so is not a valid Win32 application.
```

### Output of `nvim --version`

```text
NVIM v0.6.0-dev+560-g1fdbd29df
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az152-482

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

### Additional context

As you can see I use Windows 10 (x64), here is my configuration for tree-sitter :

"nvim-treesitter settings
lua <<EOF
require'nvim-treesitter.configs'.setup 
{
    ensure_installed = "maintained", -- one of "all", "maintained" (parsers with maintainers), or a list of languages
    
	ignore_install = { "javascript" }, -- List of parsers to ignore installing
    
	highlight = 
		{
			enable = true,         -- false will disable the whole extension
			--disable = { "rust" },  -- list of language that will be disabled
		}
}
require('nvim-treesitter.install').compilers = { "cl", "clang", "gcc" }
EOF

**Comment by 17Swagat** [comment]
IDK what was actually the problem but the followed the instructions in the **Troubleshooting** section of the following link (https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support) and now everything is working fine.

**Comment by maxxnino** [comment]
> IDK what was actually the problem but the followed the instructions in the **Troubleshooting** section of the following link (https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support) and now everything is working fine.

yeah, sometime I have that error too, when this error happen again, just update nvim-treesitter, neovim-nightly and reinstall parser

**Comment by geofflangenderfer** [comment]
same issue on m1 mac

@maxxnino how do you reinstall parser?

**Comment by maxxnino** [comment]
@geofflangenderfer in neovim type `:TSInstall lua` replace language you want to install

**Comment by Luvjeet** [comment]
I am still facing this problem I have installed clang version 14.0.0 add to path but still I get error cannot run html.so file in win32 
nvim version 0.6.1

**Comment by nz45s2** [comment]
I'm having the extract same issue here and :TSUpdate shows All parsers are up-to-date.  :TSInstall all shows everything installed properly.
Appreciated for any advice in advance!

**Comment by wunoman** [comment]
I found it. From :checkhealth I see compiler select gcc in online circumstance and clang in offline, and ABI different one is 13 and another 14.
Solution: make them same, all use clang by put below in config lua
require 'nvim-treesitter.install'.compilers = { 'clang' }

and then reinstall and recompile in online, copy parser to offline, everything is find.

**Comment by ar492** [comment]
You need a 64 bit parser because neovim is 64 bit but you likely have 32 bit MinGW. So downloading 64 bit MinGW should fix (it did for me).

**Comment by William9923** [comment]
Just want to add suggestion for other who had same issue. Installing zig as compiler would be a faster solution (for Windows user). This method assume you had installed `scoop`

Steps:
1. `scoop install zig` : install zig
2. Modify compiler used : ```require 'nvim-treesitter.install'.compilers = { 'clang' }```
3. Re-install each lang.

For me, this solution works and its quite easy. Have a good day 🙏

**Comment by ansumanbebarta** [comment]
> Just want to add suggestion for other who had same issue. Installing zig as compiler would be a faster solution (for Windows user). This method assume you had installed `scoop`
> 
> Steps:
> 
> 1. `scoop install zig` : install zig
> 2. Modify compiler used : `require 'nvim-treesitter.install'.compilers = { 'clang' }`
> 3. Re-install each lang.
> 
> For me, this solution works and its quite easy. Have a good day 🙏

Worked perfectly for me on Windows!!! Thank you

**Comment by nomyfan** [comment]
> > Just want to add suggestion for other who had same issue. Installing zig as compiler would be a faster solution (for Windows user). This method assume you had installed `scoop`
> > Steps:
> > 
> > 1. `scoop install zig` : install zig
> > 2. Modify compiler used : `require 'nvim-treesitter.install'.compilers = { 'clang' }`
> > 3. Re-install each lang.
> > 
> > For me, this solution works and its quite easy. Have a good day 🙏
> 
> Worked perfectly for me on Windows!!! Thank you The only change I did was: `require 'nvim-treesitter.install'.compilers = { 'zig' }`

Saved my life.

**Comment by techCarpenter** [comment]
> Just want to add suggestion for other who had same issue. Installing zig as compiler would be a faster solution (for Windows user). This method assume you had installed `scoop`
> 
> Steps:
> 
> 1. `scoop install zig` : install zig
> 2. Modify compiler used : `require 'nvim-treesitter.install'.compilers = { 'clang' }`
> 3. Re-install each lang.
> 
> For me, this solution works and its quite easy. Have a good day 🙏

This installation can also be done by using chocolatey: `choco install zig`

**Comment by BillyFromTheFutur** [comment]
> 1. scoop install zig

THANKS !!!!!!!!!!!!!!!!!

**Comment by 0-th** [comment]
Ran into similar issue when I ran the `:checkhealth` command.
I just looked up the parser that was causing the issue from the `:checkhealth` output and I ran `:TSInstall {parser_name}`. In my case the parsers were wgsl and wgsl_bevy.
Hope this helps.

**Comment by giuseppe-g-gelardi** [comment]
> Just want to add suggestion for other who had same issue. Installing zig as compiler would be a faster solution (for Windows user). This method assume you had installed `scoop`
> 
> Steps:
> 
> 1. `scoop install zig` : install zig
> 2. Modify compiler used : `require 'nvim-treesitter.install'.compilers = { 'clang' }`
> 3. Re-install each lang.
> 
> For me, this solution works and its quite easy. Have a good day 🙏

this doesnt work at all. when i try to add the compiler i get this

Error detected while processing C:\Users\me\AppData\Local\nvim\init.lua:
E5112: Error while creating lua chunk: C:\Users\me\AppData\Local\nvim\init.lua:249: '}' expected (to close '{' at line 68) near '.'

**Comment by samir1498** [comment]
> 2\. require 'nvim-treesitter.install'.compilers = { 'clang' }

try it like this `require ('nvim-treesitter.install').compilers = { 'clang' }`

**Comment by D3N2-A** [comment]
> Just want to add suggestion for other who had same issue. Installing zig as compiler would be a faster solution (for Windows user). This method assume you had installed `scoop`
> 
> Steps:
> 
> 1. `scoop install zig` : install zig
> 2. Modify compiler used : `require 'nvim-treesitter.install'.compilers = { 'clang' }`
> 3. Re-install each lang.
> 
> For me, this solution works and its quite easy. Have a good day 🙏

Thank you so much. It took me so much time and finally this helped

**Comment by D3N2-A** [comment]
> > Just want to add suggestion for other who had same issue. Installing zig as compiler would be a faster solution (for Windows user). This method assume you had installed `scoop`
> > Steps:
> > 
> > 1. `scoop install zig` : install zig
> > 2. Modify compiler used : `require 'nvim-treesitter.install'.compilers = { 'clang' }`
> > 3. Re-install each lang.
> > 
> > For me, this solution works and its quite easy. Have a good day 🙏
> 
> this doesnt work at all. when i try to add the compiler i get this
> 
> Error detected while processing C:\Users\me\AppData\Local\nvim\init.lua: E5112: Error while creating lua chunk: C:\Users\me\AppData\Local\nvim\init.lua:249: '}' expected (to close '{' at line 68) near '.'

You have done syntax mistake in config file check again

**Comment by max-programming** [comment]
> > Just want to add suggestion for other who had same issue. Installing zig as compiler would be a faster solution (for Windows user). This method assume you had installed `scoop`
> > Steps:
> > 
> > 1. `scoop install zig` : install zig
> > 2. Modify compiler used : `require 'nvim-treesitter.install'.compilers = { 'clang' }`
> > 3. Re-install each lang.
> > 
> > For me, this solution works and its quite easy. Have a good day 🙏
> 
> Worked perfectly for me on Windows!!! Thank you The only change I did was: `require 'nvim-treesitter.install'.compilers = { 'zig' }`

Thank  you very much! I tried all other compilers but `zig` worked flawlessly!
