### ISSUE TITLE
Post-install hook with vim-plug doesn't work

### ISSUE THREAD

**Issue by carlosala** [nvim-treesitter/nvim-treesitter#1989]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`

### Describe the bug

When you first install nvim-treesitter using vim-plug, the post update hook seems freezed, and no other hook is running.
I've tried to use it with any other hook and it works, so it's not a problem from vim-plug nor neovim.

### To Reproduce

1. Delete the plugin folder and install it using vim-plug: `Plug 'nvim-treesitter/nvim-treesitter', { 'do': ':TSUpdate' }`
2. Run `:PlugUpdate` or `:PlugInstall`
3. Look that post-update hook doesn't finish.

### Expected behavior

The hook should install (or update) the C parser.

### Output of `:checkhealth nvim-treesitter`

```markdown
Not useful, after installing all goes right.
```

### Output of `nvim --version`

```text
NVIM v0.6.0-dev+563-gb74916cfd
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az32-619

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

### Additional context

With the stable version of neovim (0.5.1) it doesn't happens, even though using master branch of nvim-treesitter.

**Comment by stsewd** [comment]
Maybe your computer doesn't handle very well installing all parsers at the same time?

You can try using 

```lua
require'nvim-treesitter.configs'.setup {
  sync_install = true
}
```

**Comment by carlosala** [comment]
This doesn't help, the same error.

> Maybe your computer doesn't handle very well installing all parsers at the same time?
> 
> You can try using
> 
> ```lua
> require'nvim-treesitter.configs'.setup {
>   sync_install = true
> }
> ```

**Comment by carlosala** [comment]
With nvim 0.6 stable works (kind of)

**Comment by 0xRZ** [comment]
still does not work for me with Plug and NVIM v0.7.0
Have to update like this: `:PlugUpdate --sync<cr>:TSUpdate<cr>`

**Comment by carlosala** [comment]
For me the install doesn't work, but if I restart nvim it works, so it's not a huge problem. By the way, I'm going to reopen it as you have troubles in nvim 0.7.

**Comment by carlosala** [comment]
Go [here](https://github.com/nvim-treesitter/nvim-treesitter/wiki/Installation#packernvim) to see why is not working. It's just because tree-sitter is not loaded!
