### ISSUE TITLE
No syntax highlight for injected HTML in custom parser

### ISSUE THREAD

**Issue by eirabben** [nvim-treesitter/nvim-treesitter#1998]
Hi

I'm currently working on a tree-sitter parser for the Twig language. The parser is working for basic directives, and HTML injection is working when I use the `tree-sitter highlight` command on a twig file. But HTML is not highlighted with nvim-treesitter in neovim.

The twig filetype is recognized by neovim, and I have installed the parser as described in the README. I have added `highlights.scm` and `injections.scm` in the `after/queries/twig/` directory of my nvim config. The highlights.scm file is working, so directives and comments are highlighted. But no syntax highlights for the HTML.

I have tried adding `parser_config.html.used_by = "twig"` to my config, but it doesn't seem to make a difference.

Here is the content of my `after/queries/twig/injections.scm` file:

```
((content) @injection.content
 (#set! injection.language "html")
 (#set! injection.combined))
```

Here is an example twig snippet where html is highlighted by the tree-sitter cli, but not in neovim:

```
{# Twig test document #}
<ul id="navigation">
  {% for item in navigation %}
     <li><a href="{{ item.href }}">{{ item.caption }}</a></li>
  {% endfor %}
 </ul>

<h1>My Webpage</h1>
{{ a_variable|filter }} 
```

This is how the tree-sitter playground sees the file in neovim:

```
comment_directive [0, 0] - [0, 24]
content [0, 24] - [2, 2]
directive [2, 2] - [2, 30]
  code [2, 4] - [2, 27]
content [2, 30] - [3, 17]
output_directive [3, 17] - [3, 32]
  code [3, 19] - [3, 29]
content [3, 32] - [3, 34]
output_directive [3, 34] - [3, 52]
  code [3, 36] - [3, 49]
content [3, 52] - [4, 2]
directive [4, 2] - [4, 14]
  code [4, 4] - [4, 11]
content [4, 14] - [8, 0]
output_directive [8, 0] - [8, 23]
  code [8, 2] - [8, 20]
content [8, 23] - [9, 0]
```

Any pointers on how I could get this to work?

I am using nvim 0.5.1 and the 0.5-compat branch of nvim-treesitter.

Output from `:checkhealth nvim_treesitter`:

```
## Parser/Features H L F I J
  - html           x‚x‚x‚x,x 
  - twig           x, , , ‚x 
  - query          x‚x‚x‚x,x 
  - css            x‚x‚x‚x,x 
  - lua            x‚x‚x‚x,x 

```

**Comment by theHamsta** [comment]
You have to use `@language` and `@content`. `@combined` is not fully supported

https://github.com/theHamsta/nvim-treesitter/blob/fa3aa92dfc4e352df2d6a806cc4098144191496f/queries/markdown/injections.scm#L1-L1

**Comment by theHamsta** [comment]
Pardon! If you know that you want to inject html, you can just use `@html`

**Comment by eirabben** [comment]
Thank you!

Replacing 

```
((content) @injection.content
 (#set! injection.language "html")
 (#set! injection.combined))
```

with 

```
(content) @html
```

has worked.
