### ISSUE TITLE
Elixir TSConstBuiltin matching too much

### ISSUE THREAD

**Issue by stephenprater** [nvim-treesitter/nvim-treesitter#2001]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`

### Describe the bug

When parsing elixir files, the TSConstBuiltin highlight group matches entirely too much.  This causes the highlighting to be incorrect for multiple queries (anything that's matching `identifier` with an `#any_of?` constraint.)

### To Reproduce

Open an elixir file.  This snippet displays the behavior.

```
defmodule Test do
  use AThing

  @spec a_and_b(number)
  def a_and_b(a,b) do
    a + b
  end
end
```

### Expected behavior

`defmodule`, `use`, `def` the `a_and_b` identifier and the spec identifier should not be highlighted with TSConstBuiltin
![Screen Shot 2021-11-11 at 3 10 47 PM](https://user-images.githubusercontent.com/149870/141382073-dc0c7c5b-4380-490a-b8c9-09c45746a3c6.png)
![Screen Shot 2021-11-11 at 3 12 06 PM](https://user-images.githubusercontent.com/149870/141382109-f3890873-26bd-47a2-ba85-93869369b960.png)

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (e85a279cf29da1b08648e27214dda20a841e57c8) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.17.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Homebrew GCC 11.2.0) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - kotlin         ✓ . . . ✓ 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - elixir         ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - vim            ✓ ✓ . . ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```
```


### Output of `nvim --version`

```text
NVIM v0.6.0-dev+570-g14def4d22
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by stephenprater@kdatlyno

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-14def4d_1/share/nvim"

Run :checkhealth for more info
```
```


### Additional context

_No response_

**Comment by stsewd** [comment]
It works fine for me 
![image](https://user-images.githubusercontent.com/4975310/141395259-4481fb9c-ab66-45d0-a439-242f92498e8f.png)

I think you're missing updating your version of treesitter, see https://github.com/nvim-treesitter/nvim-treesitter/issues/1506#issuecomment-944622847

**Comment by stephenprater** [comment]
That was it.
