### ISSUE TITLE
can't use keywords in query file for new language

### ISSUE THREAD

**Issue by dark-ether** [nvim-treesitter/nvim-treesitter#2017]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`

### Describe the bug

i was writing a highlights.scm file for a language that i installed using TSInstallFromGrammar and when i add a keyword rule such as `[">"] @operator` the highlighting breaks and i get an error treesitter/highlighter: Error executing lua: /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 83, though the position of the error changes when i modfiy the highlights.scm

### To Reproduce

1. install a non supported parser following the section adding parsers of advanced setup(add the snippet, add filetype recognition, do TSInstall language ) 
2. in the queries directory add a directory corresponding to your language
3. in the directory of your language create a highlights.scm which contain a string rule such as `"while" @keyword`
4. use checkhealth nvim-treesitter
5. see the error

### Expected behavior

keyword rules should work and highlight whenever their text appears

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.11.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - maptool_macro_scriptx . . . . 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: maptool_macro_script(highlights): /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 83
```

### Output of `nvim --version`

```text
NVIM v0.6.0-dev+584-g98af683e0
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/eldritch/builds/neovim/build/config -I/home/eldritch/builds/neovim/src -I/home/eldritch/builds/neovim/.deps/usr/include -I/usr/include -I/home/eldritch/builds/neovim/build/src/nvim/auto -I/home/eldritch/builds/neovim/build/include
Compilado por eldritch

Features: +acl +iconv +tui
See ":help feature-compile"

    arquivo vimrc de sistema: "$VIM/sysinit.vim"
            padrão para $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Additional context

other types of rules(those using nodes) seem to work as normal, and i tested it  and using the normal TSInstall does not seem to make a difference. i've written myself the parser that i am using, so if there is an extra step besides adding query files not mentioned in the treesitter docs nor on advanced setup that is specific to using the parser on neovim  it may be that.

**Comment by stsewd** [comment]
does the parser you are installing has those keywords as nodes?

**Comment by dark-ether** [comment]
no, do i need to speciffically add the keywords as anonymous nodes?

**Comment by stsewd** [comment]
> not specifically only as identifiers, do i need to speciffically add the keywords as anonymous nodes?

You need to declare those nodes in your grammar like https://github.com/tree-sitter/tree-sitter-python/blob/24b530ca158d2782ea9046e756057a412e16b52f/grammar.js#L258.

Do you have a link to your grammar?

**Comment by dark-ether** [comment]
[grammar.js file](https://gist.github.com/dark-ether/434352fec0d9e94f6f47f76e8cd60080) 
the highlights.scm i am using

```
(string) @string

(identifier) @variable

(ERROR) @error

(text) @comment

(function_call
  function: (identifier) @function)

(number) @number
(roll_option) @keyword

[
"["
"]"
] @punctuation.brackets

[
"macro.return"
] @constant
```
but i see what you mean i need to have a corresponding anonymous node

**Comment by stsewd** [comment]
yeah, you need to have those explicitly, you can also use the `match` predicate to match nodes with certain text https://github.com/nvim-treesitter/nvim-treesitter/blob/a47df48e7d4232fd771f2537a4fb43f582c026c9/queries/python/highlights.scm#L11-L12

You can also use the `alias` function on your grammar to map something as a node `alias($._rule, "node")`.
