### ISSUE TITLE
use tab to jump right under the lowest level of indentation

### ISSUE THREAD

**Issue by alexzanderr** [nvim-treesitter/nvim-treesitter#2023]
i have a self-explanatory demo right here

https://user-images.githubusercontent.com/54772464/142259927-4d77165b-474a-481e-97b1-d0ff2f168373.mp4

thats it. thanks in advance!

**Comment by stsewd** [comment]
I'm not sure if that's possible or how it's handled. But one thing I used to do with normal indentation (I don't use the one provided by tresitter) is go to normal mode and press `cc`, it maybe works as well.

**Comment by alexzanderr** [comment]
that is clearly possible in sublime text 3 and 4

`cc` doesnt work

**Comment by kyazdani42** [comment]
this should be a plugin related feature, we do not want to override the default `<tab>` for users which might be confusing.

**Comment by alexzanderr** [comment]
yeah. sure, i understand. but its possible?

**Comment by kyazdani42** [comment]
i believe it should be. You might be able to reuse the indentation code in order to do so.

**Comment by alexzanderr** [comment]
thanks.
