### ISSUE TITLE
Highlighting doesnt change when useing this

### ISSUE THREAD

**Issue by Unknown-User2** [nvim-treesitter/nvim-treesitter#2024]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`

### Describe the bug

Highlighting doesnt change at all when i have the plugin enabled

### To Reproduce

i dont know

### Expected behavior

the highlighting should change

### Output of `:checkhealth nvim-treesitter`

```markdown
health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v14.17.6 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Gentoo 11.2.0 p1) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - cpp            ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.5.1
Build type: Gentoo
Lua 5.1
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc -O2 -pipe -march=native -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/var/tmp/portage/app-editors/neovim-0.5.1/work/neovim-0.5.1_build/config -I/var/tmp/portage/app-editors/neovim-0.5.1/work/neovim-0.5.1/src -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.5.1/work/neovim-0.5.1_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.5.1/work/neovim-0.5.1_build/include
Compiled by portage@localhost

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by stsewd** [comment]
> Highlighting doesnt change at all when i have the plugin enabled

Can you describe more what you mean? change how? what file are you testing with?

**Comment by Unknown-User2** [comment]
I'm testing it with a cpp file I installed the cpp highlighting with `:TSInstall cpp` and it didnt change at all from the default

**Comment by theHamsta** [comment]
Did you enable the highlight
module with the setup call described in the README?

**Comment by Unknown-User2** [comment]
yea i have this code in my init.lua
```lua
require'nvim-treesitter'.setup{
  highlight = {
    enable = true
  }
}
```

**Comment by stsewd** [comment]
> I'm testing it with a cpp file I installed the cpp highlighting with `:TSInstall cpp` and it didnt change at all from the default

Can you provide that file? Maybe a screenshot of how it looks for you

**Comment by theHamsta** [comment]
And try `: TShighlightCapturesUnderCursor` from nvim-treesitter/playground

**Comment by Unknown-User2** [comment]
@stsewd [this](https://i.imgur.com/hOrn6Ly.png) is how it looks like
@theHamsta that does show some stuff like on top of std it says `cBlcok -> cBlock`

**Comment by theHamsta** [comment]
@Unknown-User2 we don't have highlights for `Block`. Can you show a screenshot? It's possible that nvim-treesitter isn't enabled at all and you're just seeing standard highlighting.

**Comment by Unknown-User2** [comment]
[this](https://i.imgur.com/KplQJPS.png) is what it shows

**Comment by theHamsta** [comment]
There you go. Tree-sitter is not enabled.

**Comment by Unknown-User2** [comment]
them how do enable it i but `require'nvim-treesitter'.setup{}`

**Comment by theHamsta** [comment]
Maybe it's an issue with your plugin manager? Which one are you using? Are the highlight.scm files for cpp in your Neovim runtime?

**Comment by Unknown-User2** [comment]
im using packer and where should the highlight.scm files be

**Comment by theHamsta** [comment]
did you do a `:PackerCompile`? `:echo nvim_get_runtime_file('queries/cpp/highlights.scm', v:true)` should display you the `highlight.scm` files

**Comment by Unknown-User2** [comment]
i did `:PackerCompile` it didnt do anything and my `highlight.scm` files are in `/home/brook/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/cpp/highlights.scm` and `/home/brook/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/cpp/highlights.scm`

**Comment by Unknown-User2** [comment]
other plugins are working and this one is being setup so i dont think its packer thats causing the problem

**Comment by theHamsta** [comment]
I suppose even `:TSBufEnable highlight` does nothing for you, right? Can you run `:TSModuleInfo` on a C++ buffer?

**Comment by Unknown-User2** [comment]
`:TSBufEnable highlight` does nothing and `:TSModuleInfo` shows an ✗ in every column and row

**Comment by theHamsta** [comment]
Is your filetype `cpp` (`:echo &ft`)? Can you see any parsing going when using https://github.com/nvim-treesitter/playground ? Sorry for this weak advices, but I'm really puzzled what's going on on your machine as it seems to be working for everyone else.

When you only see `x` in every column, none of the plugins of tree-sitter is enabled. Could you try to debug (e.g. with debug `print` at which point among this lines it returns false on your machine https://github.com/theHamsta/nvim-treesitter/blob/fa3aa92dfc4e352df2d6a806cc4098144191496f/lua/nvim-treesitter/configs.lua#L339-L358

**Comment by Unknown-User2** [comment]
the filetype is `cpp`, when i run `:TSPlaygroundToggle` i do see some parsing, its `module+config.enable` that is making it return false

**Comment by theHamsta** [comment]
So could you fix this `enable` by calling your `setup{...}` config again, after Neovim already started up? Would it work when you return simple `true` from that function where `module_config.enable` simply return false?

**Comment by Unknown-User2** [comment]
it doesnt work if i do the setup when nvim is started and it doesnt work if i make it return `true` instead of `false`

**Comment by theHamsta** [comment]
But then all modules will be enabled. Running `setup` after start up won't work. We had issues like this before where plugin managers did not make nvim-treesitter available yet when setup was called and it had to be called at a later moment

**Comment by Unknown-User2** [comment]
I ran `:lua require'nvim-treesitter'.setup{highlight = {enable = true}}` after it started and it changed nothing

**Comment by theHamsta** [comment]
Shouldn't it be `:lua require'nvim-treesitter.configs'.setup{highlight = {enable = true}}`

**Comment by theHamsta** [comment]
btw. issue 2024 https://play2048.co/

**Comment by Unknown-User2** [comment]
doing `:lua require'nvim-treesitter.configs'.setup{highlight = {enable = true}}` after it started worked

**Comment by Unknown-User2** [comment]
and in `init.lua` the problem was i mis-spelt it

**Comment by theHamsta** [comment]
So it should also work when you change your config. I will open an issue that we rename this internal function in `require'nvim-treesitter`.
