### ISSUE TITLE
Update 0.5-compat branch

### ISSUE THREAD

**Issue by figsoda** [nvim-treesitter/nvim-treesitter#2025]
There hasn't been any updates to 0.5-compat branch in about 2 months. It would be nice to see some pull requests being backported to this branch

**Comment by stsewd** [comment]
from what I remember, don't think there has been any breaking changes in that time-lapse, so should be good to just merge master into the 0.5 branch. But would be great if someone could test the master branch with neovim 5.0.

**Comment by figsoda** [comment]
since 0.6 is out it should be no longer a problem now
