### ISSUE TITLE
No syntax highlight for scss

### ISSUE THREAD

**Issue by bryant-the-coder** [nvim-treesitter/nvim-treesitter#2027]
I have already install scss by running `:TSInstall scss`
This is what I got.
![No syntax hightlight](https://user-images.githubusercontent.com/92417638/142416000-eba3845e-3bb6-4d66-9e42-7d25af9a3b57.png)

My config:
```
vim.lsp.handlers['textDocument/publishDiagnostics'] = vim.lsp.with(
    vim.lsp.diagnostic.on_publish_diagnostics,
    {
        underline = true,
        virtual_text = {
            spacing = 5,
            severity_limit = 'Warning',
        },
        update_in_insert = true,
    }
)

require 'nvim-treesitter.install'.compilers = { "clang" }
require'nvim-treesitter.configs'.setup {
  ensure_installed = {"html", "javascript", "lua", "scss"},
  sync_install = false,
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  rainbow = {
      enable = true,
      extended_mode = false,
  },
  autotag = {
    enable = true,
  },
  autopairs = {
      enable = true,
  }
}
```

### **HELP IS NEEDED**

**Comment by stsewd** [comment]
Please provide the output of `:checkhealth nvim-treesitter`.

**Comment by bryant-the-coder** [comment]
health#nvim-treesitter#check
========================================================================
  - ERROR: Failed to run healthcheck for "nvim-treesitter" plugin. Exception:
    function health#check, line 21
    Vim(call):E107: Missing parentheses: health#nvim-treesitter#check()

**Comment by stsewd** [comment]
@bryant-the-coder you probably need to update your neovim.

**Comment by bryant-the-coder** [comment]
Problem solved thx
