### ISSUE TITLE
`require'nvim-treesitter'.setup` can be easily confused with `require'nvim-treesitter.configs'.setup` 

### ISSUE THREAD

**Issue by theHamsta** [nvim-treesitter/nvim-treesitter#2036]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`
- [X] I have read the [troubleshooting section](https://github.com/nvim-treesitter/nvim-treesitter#troubleshooting)

### Describe the bug

We should rename `require'nvim-treesitter'.setup` as it can easily be confused with `require'nvim-treesitter.configs'.setup`. The former is merely used internally and could be prefixed with an underscore or maybe be renamed to `_setup_plugin`. Maybe this function could also just call the other setup function when called with parameters.

https://github.com/nvim-treesitter/nvim-treesitter/issues/2024 specifically https://github.com/nvim-treesitter/nvim-treesitter/issues/2024#issuecomment-974711225

@vigoux @stsewd any ideas on how to solve this the best way?

### To Reproduce

N/A

### Output of `:checkhealth nvim-treesitter`

```markdown
This bug is not related to program behavior but user documentation
```

### Output of `nvim --version`

```text
N/A
```

**Comment by stsewd** [comment]
I'd be +1 on renaming it to `_setup_plugin`. Would be cool to have that be the setup function, but then we will have two ways of doing the same thing and could turn confusing.

**Comment by lewis6991** [comment]
On the `main` branch we are going with `require'nvim-treesitter'.setup()`.
