### ISSUE TITLE
Add support for Hack

### ISSUE THREAD

**Issue by 4e554c4c** [nvim-treesitter/nvim-treesitter#2041]
**Language information**
[Hacklang](https://hacklang.org/) is a statically typed language originally designed as a dialect of PHP that is widely used at Meta and Slack.

I believe that there is already a [treesitter parser written for Hack by slack](https://github.com/slackhq/tree-sitter-hack), but I am unsure about how much work it would take to make it work for neovim.

**Comment by theHamsta** [comment]
You would have to add (assuming filetype is `hack`, need to do a `set filetype=hack` if not done by a plugin)
```lua

list.hack = {
  install_info = {
    url = "https://github.com/slackhq/tree-sitter-hack",
    branch = "main",
    files = { "src/parser.c", "src/scanner.cc" },
  },
}
```
to `lua/parser.lua`. Do you want to experiment with https://github.com/nvim-treesitter/playground to add highlights. You can see in https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#highlights which highlight captures we have. It's basically associating the nodes that 
![image](https://user-images.githubusercontent.com/7189118/142952777-d30be606-2dab-466a-a263-820b65804e84.png)

e.g. `(comment) @comment` would add comment highlight to a file `queries/hack/highlights.scm`

![image](https://user-images.githubusercontent.com/7189118/142952821-6e0e0310-0ebd-4022-96c0-37adf2b44d1f.png)

**Comment by theHamsta** [comment]
Maybe I can do that tomorrow when I have some time.

**Comment by theHamsta** [comment]
@4e554c4c This is enough to highlight the hello world https://github.com/nvim-treesitter/nvim-treesitter/pull/2042

**Comment by 4e554c4c** [comment]
oh wow I look away for a second and it's already mostly done, thanks a bunch!
I'm happy to test anything on more complicated files.
