### ISSUE TITLE
`:checkhealth nvim_treesitter` freezes neovim

### ISSUE THREAD

**Issue by garcia5** [nvim-treesitter/nvim-treesitter#2044]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`
- [X] I have read the [troubleshooting section](https://github.com/nvim-treesitter/nvim-treesitter#troubleshooting)

### Describe the bug

When running `:checkhealth nvim_treesitter`, neovim becomes unresponsive and I have to kill the process in order to exit.

### To Reproduce

1. Open nvim
2. `:checkhealth nvim_treesitter<CR>`
3. Nvim unresponsive

### Expected behavior

Healthchecks complete as normal and do not crash nvim

### Output of `:checkhealth nvim-treesitter`

```markdown
N/A -- no output is shown
```

### Output of `nvim --version`

```text
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20211103-3501-1gz0ofb/neovim-0.5.1/build/config -I/tmp/neovim-20211103-3501-1gz0ofb/neovim-0.5.1/src -I/usr/local/include -I/tmp/neovim-20211103-3501-1gz0ofb/neovim-0.5.1/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20211103-3501-1gz0ofb/neovim-0.5.1/build/src/nvim/auto -I/tmp/neovim-20211103-3501-1gz0ofb/neovim-0.5.1/build/include
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.5.1_1/share/nvim"

Run :checkhealth for more info
```

### Additional context

Running on M1 MacOS Monterey 12.0.1

**Comment by garcia5** [comment]
Running `:call health#nvim_treesitter#check()` directly outputs the following then freezes:

```
## Installation
  - OK: `tree-sitter` found  0.20.1 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.17.5 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
```

**Comment by theHamsta** [comment]
The next check would be the compiler. What happens when you run `cc --version`

**Comment by garcia5** [comment]
`cc --version` gives me the expected output.

```
$ cc --version
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin21.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/Xc
odeDefault.xctoolchain/usr/bin
```

I even tried copy-pasting the [install_health](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/health.lua#L18) function and executing that locally and it gave me a normal output with no issue

```
## Installation
  - OK: `tree-sitter` found  0.20.1 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.17.5 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.0.0 (clang-1300.0.29.3)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.
```

**Comment by nabezokodaikon** [comment]
The same thing happens to me.
The `cc` version is:
```
$ cc --version              
Apple clang version 13.0.0 (clang
Target: arm64-apple-darwin21.1.0
Thread model: posix
InstalledDir: /Library/Developer/
```

**Comment by garcia5** [comment]
Some more fiddling with the `M.check()` function and it looks like the [query_status](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/health.lua#L102) call is what's hanging. I went through and uncommented out chunks of the file until it started to break

**Comment by theHamsta** [comment]
You're sure you compiled your parsers for arm64 and not amd64?

**Comment by garcia5** [comment]
Not sure how to check that, I haven't manually installed any of the parsers. I just have the recommended setup in my config

```lua
-- treesitter.lua
require("nvim-treesitter.configs").setup(
    {
        -- one of "all", "maintained" (parsers with maintainers), or a list of
        -- languages
        ensure_installed = "maintained",
        -- ...
    }
)
```

```lua
-- plugins.lua
packer.startup(
    function(use)
        use {
            'nvim-treesitter/nvim-treesitter',
            run = ':TSUpdate'
        }
        -- ...
    end
)

```

**Comment by garcia5** [comment]
The parsers also seem to work fine, it's just the healthcheck that is erroring out. Folding, highlighting, indenting is working as expected

**Comment by maxxnino** [comment]
@theHamsta recently neovim hang with below query in zig too. Don't know what cause the problem
```
;; #1
(PtrTypeStart "c" @variable.builtin)

;; #2
(
  (ContainerDeclType
    [
      (ErrorUnionExpr)
      "enum"
    ]
  )
  (ContainerField (IDENTIFIER) @constant)
)
```

**Comment by AlexisFinn** [comment]
same here.
BTW I have three options for the `:checkhealth` parameter pertaining to treesitter:
- `:checkhealth nvim-treesitter` = crash
- `:checkhealth nvim_treesitter` = crash
- `:checkhealth vim.treesitter` = Works as expected

**Comment by kyeb** [comment]
Similar issue, `:checkhealth` hangs on treesitter and requires a `kill -9` to stop.

Like @garcia5, it gives 3 `OK`s, then hangs. On Arch Linux, and my `cc --version` is `cc (GCC) 11.1.0`. Happy to help debug further if there's anything I can do.

**Comment by Cichawy** [comment]
This also happens to me on Ubuntu 21.10.

neovim-0.6.0~ubuntu1+git202111251249-6ea5e8039-adeb5640f
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

cc (Ubuntu 11.2.0-7ubuntu2) 11.2.0

I can confirm that running `:checkhealth vim.treesitter` works as expected. Other options end with a hang.

**Comment by Cichawy** [comment]
`:checkhealth` finishes after a couple of seconds on 

neovim-0.6.0~ubuntu1+git202111301249-04c7b5503

**Comment by garcia5** [comment]
After upgrading to neovim 0.6 w/ brew, `:checkhealth` is now working as expected for me. 

```
$ nvim --version
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.6.0/share/nvim"

Run :checkhealth for more info
```

**Comment by AlexisFinn** [comment]
Seems fixed on latest version, this issue can probably be closed now.
```
NVIM v0.7.0-dev+663-g254c22afc
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/alexis/Applications/neovim/build/config -I/home/alexis/Applications/neovim/src -I/home/alexis/Applications/neovim/.deps/usr/include -I/usr/include -I/home/alexis/Applications/neovim/build/src/nvim/auto -I/home/alexis/Applications/neovim/build/include
Compilé par alexis@AlexisFinn-Bloomin

Features: +acl +iconv +tui
See ":help feature-compile"

         fichier vimrc système : "$VIM/sysinit.vim"
               $VIM par défaut : "/usr/local/share/nvim"
```

**Comment by nabezokodaikon** [comment]
I confirmed that it does not occur in version 0.6.
