### ISSUE TITLE
module 'vim.ui' not found

### ISSUE THREAD

**Issue by emielvanseveren** [nvim-treesitter/nvim-treesitter#2059]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [ ] I have run `:TSUpdate`
- [x] I have read the [troubleshooting section](https://github.com/nvim-treesitter/nvim-treesitter#troubleshooting)

### Describe the bug

Installation of nvim-treesitter with vim-plug fails with the following error:

Error detected while processing /home/emiel/.config/nvim/plugged/nvim-treesitter/plugin/nvim-treesitter.vim:
line   15:
E5108: Error executing lua vim.lua:113: module 'vim.ui' not found:
        no field package.preload['vim.ui']
        no file './vim/ui.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/vim/ui.lua'
        no file '/usr/local/share/lua/5.1/vim/ui.lua'
        no file '/usr/local/share/lua/5.1/vim/ui/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vim/ui.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vim/ui/init.lua'
        no file './vim/ui.so'
        no file '/usr/local/lib/lua/5.1/vim/ui.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/vim/ui.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './vim.so'
        no file '/usr/local/lib/lua/5.1/vim.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/vim.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        vim.lua:113: in function '__index'
        .../plugged/nvim-treesitter/lua/nvim-treesitter/configs.lua:216: in main chunk
        [C]: in function 'require'
        ...vim/plugged/nvim-treesitter/lua/nvim-treesitter/info.lua:2: in main chunk
        [C]: in function 'require'
        .../plugged/nvim-treesitter/lua/nvim-treesitter/install.lua:7: in main chunk
        [C]: in function 'require'
        ...fig/nvim/plugged/nvim-treesitter/lua/nvim-treesitter.lua:5: in main chunk
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk

### To Reproduce

Installation of nvim-treesitter with vim-plug, happens both with post hook and without post hook

### Output of `:checkhealth nvim-treesitter`

```markdown
health#nvim-treesitter#check
========================================================================
  - ERROR: Failed to run healthcheck for "nvim-treesitter" plugin. Exception:
    function health#check, line 21
    Vim(call):E107: Missing parentheses: health#nvim-treesitter#check()
```

### Output of `nvim --version`

```text
NVIM v0.6.0-dev+566-g4174244d8
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az68-184

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Comment by theHamsta** [comment]
Vim 0.6 should have `vim.ui`. Can you try cleaning you build cache to make sure the runtime files get installed.

**Comment by emielvanseveren** [comment]
You were right! Something must have went wrong during install. Thank you! Issue resolved

**Comment by theHamsta** [comment]
Neovim uses an minimal required cmake version (2.XX). The old behavior doesn't get globbing and file changes for installed files right.

**Comment by emielvanseveren** [comment]
I'm pretty sure I installed it with cmake v3.22

**Comment by eduardoarandah** [comment]
I'm getting the exact same error on neovim 0.6.1

I didn't compile neovim, I just downloaded nvim-macos.tar.gz from 

https://github.com/neovim/neovim/releases/tag/v0.6.1

**Comment by theHamsta** [comment]
@emielvanseveren that doesn't matter CMake will import bugs from the past and behave exactly like the version specified in the CMakeLists.txt.
