### ISSUE TITLE
[MacOS] In neovim, treesitter's executable isn't being found

### ISSUE THREAD

**Issue by olliequ** [nvim-treesitter/nvim-treesitter#2064]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`
- [X] I have read the [troubleshooting section](https://github.com/nvim-treesitter/nvim-treesitter#troubleshooting)

### Describe the bug

When I run `:checkhealth` in neovim I get 2 warnings, one notably indicating treesitter's executable isn't found. Is this hampering any functionality? Ie. is this normal? The report is below: 
```
health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - WARNING: `node` executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple LLVM version 10.0.1 (clang-1001.0.46.4)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.
```
I use `vim-plug` and installed treesitter using: 
```
Plug 'nvim-treesitter/nvim-treesitter', { 'do': ':TSUpdate' }
```

### To Reproduce

Run `:checkhealth`.

### Expected behavior

No warnings.

### Output of `:checkhealth nvim-treesitter`

```markdown
health#treesitter#check
========================================================================
## Checking treesitter configuration
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for c: ABI version 13
```

### Output of `nvim --version`

```
v0.5.1
```

**Comment by theHamsta** [comment]
The tree-sitter executable is not needed for most parsers. If you need to generate parsers from grammar.js files please download it via homebrew or Github Releases: https://github.com/tree-sitter/tree-sitter/releases and add it to your PATH

**Comment by stsewd** [comment]
As mentioned, those are needed only for some parsers (wouldn't hurt for you to install node and treesitter).

**Comment by smokeyhallow** [comment]
I am having a lot of issues with ts message overlays not being refreshed. I have these same errors, I am wondering whether this is the root cause of it.
