### ISSUE TITLE
Treesitter causes long startup time for elixir buffers after update to neovim 0.6.0

### ISSUE THREAD

**Issue by sdoering01** [nvim-treesitter/nvim-treesitter#2078]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`
- [X] I have read the [troubleshooting section](https://github.com/nvim-treesitter/nvim-treesitter#troubleshooting)

### Describe the bug

Opening any buffer with a filetype of 'elixir' (.ex, .exs) takes ~4s. When I add "elixir" to nvim-treesitter.configs.highlight.disable opening an elixir buffer takes the expected ~150ms.

### To Reproduce

1. Setup nvim-treesitter config

```lua
require'nvim-treesitter.configs'.setup {
    highlight = {
        enable = true,
        disable = {},
        -- this 'solves' the problem
        -- disable = {"elixir"},
    },
    indent = {
        enable = false,
        disable = {},
    },
    ensure_installed = "maintained",
}
```

2. Open an elixir buffer, e.g. `nvim foo.exs`
3. Neovim takes ~4s to start

### Expected behavior

Opening elixir buffers takes ~150ms (like all other filetypes).

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.1 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.18.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - ocaml_interface✓ ✓ ✓ . ✓ 
  - beancount      ✓ . ✓ . . 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - sparql         ✓ ✓ ✓ ✓ ✓ 
  - comment        ✓ . . . . 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - ocaml          ✓ ✓ ✓ . ✓ 
  - dot            ✓ . . . ✓ 
  - nix            ✓ ✓ ✓ . ✓ 
  - glsl           ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - jsdoc          ✓ . . . . 
  - ledger         ✓ . ✓ ✓ ✓ 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - clojure        ✓ ✓ ✓ . ✓ 
  - supercollider  ✓ ✓ ✓ ✓ ✓ 
  - heex           ✓ . ✓ ✓ ✓ 
  - godot_resource ✓ ✓ ✓ . . 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - fennel         ✓ ✓ . . ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - vue            ✓ . ✓ ✓ ✓ 
  - latex          ✓ . ✓ . ✓ 
  - rst            ✓ ✓ . . ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - glimmer        ✓ . . . . 
  - erlang         . . . . . 
  - regex          ✓ . . . . 
  - svelte         ✓ . ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - teal           ✓ ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - hjson          ✓ ✓ ✓ ✓ ✓ 
  - gomod          ✓ . . . . 
  - dart           ✓ ✓ . ✓ ✓ 
  - prisma         ✓ . . . . 
  - bash           ✓ ✓ ✓ . ✓ 
  - http           ✓ . . . ✓ 
  - llvm           ✓ . . . . 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - pioasm         ✓ . . . ✓ 
  - json5          ✓ . . . ✓ 
  - vim            ✓ ✓ . . ✓ 
  - cmake          ✓ . ✓ . . 
  - julia          ✓ ✓ ✓ ✓ ✓ 
  - zig            ✓ . ✓ ✓ ✓ 
  - bibtex         ✓ . ✓ ✓ . 
  - r              ✓ ✓ . . . 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - devicetree     ✓ ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - gdscript       ✓ ✓ . . ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - commonlisp     ✓ ✓ ✓ . . 
  - yang           ✓ . ✓ . . 
  - surface        ✓ . ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - ql             ✓ ✓ . ✓ ✓ 
  - elixir         ✓ ✓ ✓ ✓ ✓ 
  - cuda           ✓ ✓ ✓ ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - kotlin         ✓ . . . ✓ 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - ocamllex       ✓ . . . ✓ 
  - scala          ✓ . ✓ . ✓ 
  - dockerfile     ✓ . . . ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - perl           ✓ . . . . 
  - tlaplus        ✓ . ✓ . ✓ 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - graphql        ✓ . . ✓ ✓ 
  - pug            ✓ . . . ✓ 
  - scss           ✓ . . ✓ . 
  - hcl            ✓ . ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

- I use a GNU/Linux system.

- I tried the `--startuptime` flag and it turns out that the step `first screen update` causes this major delay. But I don't know how to debug it further.
[startup-without-ts.txt](https://github.com/nvim-treesitter/nvim-treesitter/files/7640878/startup-without-ts.txt)
[startup-with-ts.txt](https://github.com/nvim-treesitter/nvim-treesitter/files/7640879/startup-with-ts.txt)

- During the startup delay htop shows that the nvim process uses 100% of the CPU.

- It also takes some seconds to switch to insert mode (only in elixir files) and during this delay htop reports that the nvim process uses 100% of the CPU. This problem comes from my completion engine coq_nvim though. But maybe it helps to identify the underlying problem, as both of the delays started occurring at the same time -- after a system update, that also updated nvim to version 0.6.0.

- Both delays (this issue and delay cuased by my completion engine) don't happen for other filetypes that use treesitter and lsp.

- Rolling the neovim version back to the last installed 0.5.x version didn't solve the problems.

- I tried to run `:TSUninstall all` and let treesitter reinstall all parsers. This was mentioned in some issue.

- I am not quite sure how exactly treesitter works, so this could potentially be a bug of the parser too. But I think it's very confusing that the bug happens only for elixir filetypes and both treesitter and the completion engine at the same time.

**Comment by nifoc** [comment]
Probably related to #1957

**Comment by theHamsta** [comment]
You can try rebuilding with tree-sitter 0.20.0 instead of the default 0.20.1

**Comment by sdoering01** [comment]
Thanks, building from the mentioned commit solved both of my problems. I tried looking for the problem online but didn't find the mentioned issue, sorry.
This issue can be closed.

**Comment by audendana** [comment]
Also seeing this issue on latest

**Comment by anhari** [comment]
[Neovim was upgraded](https://github.com/neovim/neovim/commit/302beaa36b8b53765c986bd88741e0d547256938) to use [treesitter 0.20.2](https://github.com/tree-sitter/tree-sitter/issues/1510) which improves performance quite a bit:

```
brew upgrade neovim --fetch-HEAD
```
```
:PackerUpdate nvim-treesitter
```

**Comment by virchau13** [comment]
I am still seeing this issue on latest.

**Comment by vigoux** [comment]
When did you update last? The issue in slowly progressing these days, and PRs improving the performances landed today.

**Comment by ryansch** [comment]
I'm using the nightly from 13 hours ago and I'm still seeing the same issue.
