### ISSUE TITLE
Highlighting for Python 3.10's structural pattern matching

### ISSUE THREAD

**Issue by rouge8** [nvim-treesitter/nvim-treesitter#2080]
Currently nvim-treesitter doesn't highlight Python 3.10+'s [structural pattern matching](https://www.python.org/dev/peps/pep-0636/). Now that Python 3.10 is released, it probably should.

This is the current behavior:
![unhighlighted match/case](https://user-images.githubusercontent.com/237005/144544031-f674a54a-5364-4eb9-bcc1-76c65ca89023.png)

**Comment by theHamsta** [comment]
Please open this request at github.com/tree-sitter/tree-sitter-python. When the parser supports this feature it will be automatically updated here and we will highlight the keyword `match`

**Comment by rouge8** [comment]
Looks like there's an open issue there: https://github.com/tree-sitter/tree-sitter-python/issues/116

**Comment by theHamsta** [comment]
@rouge8 you can test if you want. It appears that it wasn't very complicated.

E.g. change this  https://github.com/theHamsta/nvim-treesitter/blob/a37830cfe03564a5848875f41e5213d11fcbc126/lua/nvim-treesitter/parsers.lua#L160-L166 to 
```lua
list.python = {
  install_info = {
    url = "~/projects/tree-sitter-python",
    files = { "src/parser.c", "src/scanner.cc" },
  },
  maintainers = { "@stsewd", "@theHamsta" },
}
```

and run `:TSInstall python` with #2081

**Comment by theHamsta** [comment]
Need to add support for `as patterns`
