### ISSUE TITLE
Document clarification requested

### ISSUE THREAD

**Issue by EdmundsEcho** [nvim-treesitter/nvim-treesitter#2095]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`
- [X] I have read the [troubleshooting section](https://github.com/nvim-treesitter/nvim-treesitter#troubleshooting)

### Describe the bug

I'm confident I'm somehow confused.  Here is the issue: For some reason all of the available languages are "up and running". e.g., when I run `check health` I see the full list of languages.

When you take a look at my config setting for the plugin (see below), did I somehow "enable all" by not including anything in the `disable` prop, or `ensure_installed="maintained"`?

I could not decipher an answer after reading the docs a couple of times.  Also, I'm a bit confused about whether running `TSInstall <lang>` installs _both_ the parser and the `json` rules file, or are the parsers always ready to go for all supported languages (and thus only run the install to create the rules file)?

The likely answer: `ensure_installed: maintained`.  This is counter-intuitive if I don't understand that running the TSInstall command creates a persistent change or not.  If persistent, then I should not have to care about the config setting (should leave out), if not persistent, then the config setting saves me from having to do so every time... depending on what it is doing "every time" i.e., likely not rebuilding the rules file each time. 

PS: Great plugin and in a really nicely updated Neovim.

Thank you.

\- E

### To Reproduce

I ran `TSInstall` on 5 or so languages. Then I updated my config for the plugin to the following:

```lua
require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained", -- one of "all", "maintained" (parsers with maintainers), or a list of languages
  sync_install = false, -- install languages synchronously (only applied to `ensure_installed`)
  ignore_install = {}, -- List of parsers to ignore installing
  highlight = {
    enable = true, -- false will disable the whole extension
    disable = {},  -- list of language that will be disabled **** <<<<<<<<<<<<
    -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
    -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
    -- Using this option may slow down your editor, and you may see some duplicate highlights.
    -- Instead of true it can also be a list of languages
    additional_vim_regex_highlighting = false,
  },
  indent = {
    enable = true
  }
}
```

### Expected behavior

Only have the 5 languages active, not the full list of supported languages.

### Output of `:checkhealth nvim-treesitter`

```markdown
vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for bash: ABI version 13
  - OK: Loaded parser for beancount: ABI version 13
  - OK: Loaded parser for bibtex: ABI version 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for clojure: ABI version 13
  - OK: Loaded parser for cmake: ABI version 13
  - OK: Loaded parser for comment: ABI version 13
  - OK: Loaded parser for commonlisp: ABI version 13
  - OK: Loaded parser for cpp: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for cuda: ABI version 13
  - OK: Loaded parser for c_sharp: ABI version 13
  - OK: Loaded parser for dart: ABI version 13
  - OK: Loaded parser for devicetree: ABI version 13
  - OK: Loaded parser for dockerfile: ABI version 13
  - OK: Loaded parser for dot: ABI version 13
  - OK: Loaded parser for elixir: ABI version 13
  - OK: Loaded parser for erlang: ABI version 13
  - OK: Loaded parser for fennel: ABI version 13
  - OK: Loaded parser for fish: ABI version 13
  - OK: Loaded parser for gdscript: ABI version 13
  - OK: Loaded parser for glimmer: ABI version 13
  - OK: Loaded parser for glsl: ABI version 13
  - OK: Loaded parser for go: ABI version 13
  - OK: Loaded parser for godot_resource: ABI version 13
  - OK: Loaded parser for gomod: ABI version 13
  - OK: Loaded parser for graphql: ABI version 13
  - OK: Loaded parser for hcl: ABI version 13
  - OK: Loaded parser for heex: ABI version 13
  - OK: Loaded parser for hjson: ABI version 13
  - OK: Loaded parser for html: ABI version 13
  - OK: Loaded parser for http: ABI version 13
  - OK: Loaded parser for java: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for jsdoc: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for json5: ABI version 13
  - OK: Loaded parser for jsonc: ABI version 13
  - OK: Loaded parser for julia: ABI version 13
  - OK: Loaded parser for kotlin: ABI version 13
  - OK: Loaded parser for latex: ABI version 13
  - OK: Loaded parser for ledger: ABI version 13
  - OK: Loaded parser for llvm: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for nix: ABI version 13
  - OK: Loaded parser for ocaml: ABI version 13
  - OK: Loaded parser for ocamllex: ABI version 13
  - OK: Loaded parser for ocaml_interface: ABI version 13
  - OK: Loaded parser for perl: ABI version 13
  - OK: Loaded parser for php: ABI version 13
  - OK: Loaded parser for pioasm: ABI version 13
  - OK: Loaded parser for prisma: ABI version 13
  - OK: Loaded parser for pug: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for ql: ABI version 13
  - OK: Loaded parser for query: ABI version 13
  - OK: Loaded parser for r: ABI version 13
  - OK: Loaded parser for regex: ABI version 13
  - OK: Loaded parser for rst: ABI version 13
  - OK: Loaded parser for ruby: ABI version 13
  - OK: Loaded parser for rust: ABI version 13
  - OK: Loaded parser for scala: ABI version 13
  - OK: Loaded parser for scss: ABI version 13
  - OK: Loaded parser for sparql: ABI version 13
  - OK: Loaded parser for supercollider: ABI version 13
  - OK: Loaded parser for surface: ABI version 13
  - OK: Loaded parser for svelte: ABI version 13
  - OK: Loaded parser for teal: ABI version 13
  - OK: Loaded parser for tlaplus: ABI version 13
  - OK: Loaded parser for toml: ABI version 13
  - OK: Loaded parser for tsx: ABI version 13
  - OK: Loaded parser for turtle: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for vim: ABI version 13
  - OK: Loaded parser for vue: ABI version 13
  - OK: Loaded parser for yaml: ABI version 13
  - OK: Loaded parser for yang: ABI version 13
  - OK: Loaded parser for zig: ABI version 13
```

### Output of `nvim --version`

```text
NVIM v0.7.0-dev+653-g7229afcd6
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by theHamsta** [comment]
>  :checkhealth nvim-treesitter

that's the output of the build-in healthcheck (i.e. `:checkhealth tree-sitter`, not `:checkhealth nvim-treesitter`.  

> I could not decipher an answer after reading the docs a couple of times. Also, I'm a bit confused about whether running TSInstall <lang> installs both the parser and the json rules file, or are the parsers always ready to go for all supported languages (and thus only run the install to create the rules file)?

Only the parser. The config files are included in this repo so you already have all of them. It will fetch the third-party repository and compile it to a shared library that will stay on your machine (in the folder of nvim-treesitter to be exact). It will stay there until you TSUninstall or remove nvim-treesitter

`ensure_installed` is thought as a cross-machine setup. When you use it, it will auto-install all parsers specified by the config. Right now almost all parsers have maintainers so it will install all the parsers. Run `:TSUninstall all` to remove all parsers and remove the `ensure_installed` key. You can then either set only the languages you want in `ensure_installed` or run `:TSInstall cpp python rust` when you just want to have those three languages.

Then, there is `:TSUpdate`: we recommend it as a post-update hook. It will ensure that all parsers that are installed on your machine are updated to the version that is CI tested and compatible with the newest queries in this plugin. So we already tested that the new plugin revision compiles on all mayor platform and is still compatible with the language configuration in our plugin

**Comment by theHamsta** [comment]
@EdmundsEcho did my clarification help? What should be added to our documentation?

**Comment by EdmundsEcho** [comment]
What I did:
> Right now almost all parsers have maintainers so it will install all the parsers. 

The fix:
> Run :TSUninstall all to remove all parsers and remove the ensure_installed key. 

Start-over with:
> You can then either set only the languages you want in ensure_installed or run :TSInstall cpp python rust when you just want to have those three languages. 

To make sure parsers remain up-to-date, include the post-update hook `:TSUpdate`
```
Plug 'nvim-treesitter/nvim-treesitter', { 'do': ':TSUpdate' }
```

Your input was spot-on.

Thank you.
