### ISSUE TITLE
`ts_utils.update_selection` doesn't work when already in visual mode

### ISSUE THREAD

**Issue by rosehuds** [nvim-treesitter/nvim-treesitter#2097]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`
- [X] I have read the [troubleshooting section](https://github.com/nvim-treesitter/nvim-treesitter#troubleshooting)

### Describe the bug

when called from visual mode, `ts_utils.update_selection()` tries to set the window to visual mode but ends up setting it to normal mode. i believe this is because pressing `v` while in visual mode switches back to normal, but the code doesn't seem to expect this.

i can achieve the expected behaviour by copy-pasting the function source and adding an `<ESC>` before the `v`, `V`, or `<C-v>` that the function feeds, but i didn't want to write a patch that did this without checking that it's a good solution

### To Reproduce

```lua
local ts = require('nvim-treesitter.ts_utils')
local vimp = require('vimp')

local current_node = nil
vimp.nnoremap('K', function()
  current_node = ts.get_node_at_cursor(0)
  ts.update_selection(0, current_node)
end)
vimp.vnoremap('K', function()
  current_node = current_node:parent()
  ts.update_selection(0, current_node)
end)
```
this example config is intended to map K to expand the selection to the next smallest node that contains the cursor/current selection
1. be in normal mode
2. move the cursor over a syntax node that has a parent
3. press K twice
4. observe that you are now in normal mode with the cursor at the end of the parent node, despite the last thing to happen being `ts.update_selection()`

### Expected behavior

after calling `ts_utils.update_selection()`, we should be in visual mode, and there should be a selection

### Output of `:checkhealth nvim-treesitter`

```markdown
.
```

### Output of `nvim --version`

```text
.
```

**Comment by stsewd** [comment]
don't know what vimp is, but I'm not able to replicate this with

```lua
local ts = require('nvim-treesitter.ts_utils')

local current_node = nil
function InitSelection()
  current_node = ts.get_node_at_cursor(0)
  ts.update_selection(0, current_node)
end

function SelectParent()
  current_node = current_node:parent()
  ts.update_selection(0, current_node)
end
```

```vim
nnoremap K :lua InitSelection()<CR>
vnoremap K :lua SelectParent()<CR>
```

We also have https://github.com/nvim-treesitter/nvim-treesitter#incremental-selection, which does that.

**Comment by rosehuds** [comment]
yeah, thanks, i tried with using normal vim maps instead of vimp and it worked as expected. sorry about that. incremental-selection looks cool, but doesn't seem to allow horizontal traversal
