### ISSUE TITLE
Automatically install just one parser on encountering a new filetype

### ISSUE THREAD

**Issue by HaleTom** [nvim-treesitter/nvim-treesitter#2108]
**Summary**
I want to be able to automatically install the relevant parser when encountering a new filetype.

How could I install *only* the required parser for this new filetype?

**Is your feature request related to a problem? Please describe.**

I have PolyGlot installed.  When I open a file of a new filetype how do I know if I need to install the TS parser for it?  It would be easier to not need to check, but that the TS parser is installed automatically if it exists.

**Describe the solution you'd like**

A `.vimrc` snippet for the following:

I'm not a vim guru. I'd love to have a complete example snippet for how to add the relevant entry in `ensure_installed` upon encountering a new filetype, and then what to do to call either  `TSInstall` or `TSUpdate` as appropriate.

https://github.com/nvim-treesitter/nvim-treesitter/issues/293 says it's possible to add to:
```
ensure_installed = { 'typescript' }
```

**Describe alternatives you've considered**
I could install **all** parsers but that would be a waste of time / disk / bandwidth especially when `ssh`-ing to a new machine to edit a single text file.

**Comment by theHamsta** [comment]
This would work, I guess
```lua
local parsers = require'nvim-treesitter.parsers'
function _G.ensure_treesitter_language_installed()
  local lang = parsers.get_buf_lang()
  if parsers.get_parser_configs()[lang] and not parsers.has_parser(lang) then
    vim.schedule_wrap(function()
    vim.cmd("TSInstallSync "..lang)
    vim.cmd[[e!]]
    end)()
  end
end

vim.cmd[[autocmd FileType * :lua ensure_treesitter_language_installed()]]
```
This will cause an input lag when first opening a file of an unknown language because it installs the parser synchronously. This can be annoying

This will perform a background install but you have to reload the buffer once the installation is finished
```
local parsers = require'nvim-treesitter.parsers'
function _G.ensure_treesitter_language_installed()
  local lang = parsers.get_buf_lang()
  if parsers.get_parser_configs()[lang] and not parsers.has_parser(lang) then
    vim.schedule_wrap(function()
    vim.cmd("TSInstall "..lang)
    end)()
  end
end

vim.cmd[[autocmd FileType * :lua ensure_treesitter_language_installed()]]
```

**Comment by wimstefan** [comment]
That would be a tremendous feature!

**Comment by theHamsta** [comment]
This version will ask you before install
```lua
function _G.ensure_treesitter_language_installed()
  local parsers = require "nvim-treesitter.parsers"
  local lang = parsers.get_buf_lang()
  if parsers.get_parser_configs()[lang] and not parsers.has_parser(lang) then
    vim.schedule_wrap(function()
      vim.ui.select({"yes", "no"}, { prompt = "Install tree-sitter parsers for " .. lang .. "?" }, function(item)
        if item == "yes" then
          vim.cmd("TSInstall " .. lang)
        end
      end)
    end)()
  end
end

vim.cmd [[autocmd FileType * :lua ensure_treesitter_language_installed()]]
```
I think the best option for this feature would probably be to document those code snippets in README (or extract parts of the README to the Wiki).

The auto-loading of freshly installed parsers is now in master.

**Comment by HaleTom** [comment]
Thanks @theHamsta  for the awesome work on this! :partying_face: 

Where do I put the above snippet?  If I put int in my `.vimrc`, I get:

```
Error detected while processing /home/ravi/.dotfiles/vim/.config/vim/vimrc:                                                                                                                                        
line   63:                                                                                                                                                                                                         
E492: Not an editor command: local ask_install = {}                                                                                                                                                                
line   64:                                                                                                                                                                                                         
E121: Undefined variable: _G 
...
```
I'm guessing it's Lua and I've got some things to learn :)

**Comment by theHamsta** [comment]
You can either put this in a lua filé and source it with `:luafile <file path here> or you wrap it with the fancy syntax that we use in the README for the setup call. Can't remember the exact syntax here on my phone. But you can look it up in our README.

**Comment by theHamsta** [comment]
Found it:
```
lua <<EOF


EOF
```

You can put the lua code between the EOFs.

**Comment by HaleTom** [comment]
Excellent! Thanks!

To have a `.vimrc` that also works with plain `vim`, I went with:

```
if has('nvim') | lua << EOF
  <snippet>
EOF
endif
```

**Comment by HaleTom** [comment]
Would it make sense to include the snippet above into treesitter-nvim itself, perhaps activated by an option:

`ask_plugin_install_on_new_ft`

**Comment by HaleTom** [comment]
Also, how would I go about wrapping the line:

```
vim.cmd [[autocmd FileType * :lua ensure_treesitter_language_installed()]]
```

With the equivalent of:

```
if exists(loaded_nvim_treesitter)
    vim.cmd [[autocmd FileType * :lua ensure_treesitter_language_installed()]]
endif
```

**Comment by clason** [comment]
As long as tree-sitter support is experimental (which it is, and still will be for a while), I strongly believe there should not be any such automatic steps. (Depending on the filetype, there can be severe unexpected side effects if you are not sure what you are doing.)

If you use `init.vim`, you can (and should) just omit the `vim.cmd [[...]]` and use the naked vimscript. I suggest you read https://github.com/nanotee/nvim-lua-guide to learn about using Lua in Neovim.

**Comment by stsewd** [comment]
> As long as tree-sitter support is experimental (which it is, and still will be for a while), I strongly believe there should not be any such automatic steps. 

Good point! Maybe we can add this snipped somewhere on the wiki https://github.com/nvim-treesitter/nvim-treesitter/wiki

I'd fine also making it an option with a warning.

**Comment by HaleTom** [comment]
Here's the final backward-compatible code I came up with:

```
" Ask to install treesitter plugins on encountering a new filetype
 " Load plugins on encountering new filetype: https://github.com/nvim-treesitter/nvim-treesitter/issues/2108#issuecomment-995069984
if has('nvim') && exists('loaded_nvim_treesitter') | lua << EOF
-- Above is dodgy, replace with:
-- https://github.com/nvim-treesitter/nvim-treesitter/issues/2108#issuecomment-995433452
  local ask_install = {}
  function _G.ensure_treesitter_language_installed()
    local parsers = require "nvim-treesitter.parsers"
    local lang = parsers.get_buf_lang()
    if parsers.get_parser_configs()[lang] and not parsers.has_parser(lang) and ask_install[lang] ~= false then
      vim.schedule_wrap(function()
        vim.ui.select({"yes", "no"}, { prompt = "Install tree-sitter parsers for " .. lang .. "?" }, function(item)
          if item == "yes" then
            vim.cmd("TSInstall " .. lang)
          elseif item == "no" then
            ask_install[lang] = false
          end
        end)
      end)()
    end
  end
EOF
endif

" Prompt to install treesitter language if appropriate
if has ('autocmd') | augroup treesitter | autocmd!
  if exists('loaded_nvim_treesitter')
      autocmd FileType * :lua ensure_treesitter_language_installed()
  endif
augroup END | endif
```

**Comment by smjonas** [comment]
> I'd fine also making it an option with a warning.

Is this still the case? I.e.would you accept a PR to add this as an (non-default) option, like `ensure_installed = "on_file_open"` (not sure about the name)? I think automatically installing parsers is great for user experience. Also, do you mean a warning in the documentation?

**Comment by HaleTom** [comment]
@stsewd I wonder if you saw the question from smjonas above?

**Comment by HaleTom** [comment]
@theHamsta I'm noticing an issue with the behaviour of the code based on yours that I wrote [above](https://github.com/nvim-treesitter/nvim-treesitter/issues/2108#issuecomment-998468164).

I'm needing to press `<Enter>` multiple times, eg:

```
Install treesitter parser for git_config?
1: yes
2: no
Type number and <Enter> or click with the mouse (q or empty cancels): 1[nvim-treesitter] [0/4] Checking out locked revision
Press ENTER or type command to continue
[nvim-treesitter] [0/4] Downloading tree-sitter-git_config...
Press ENTER or type command to continue
nvim-treesitter[git_config]: Error during download, please verify your internet connection
Cloning into 'tree-sitter-git_config'...
error: could not lock config file /home/ravi/.local/share/nvim/tree-sitter-git_config/.git/config: No such file or directory
fatal: could not set 'core.repositoryformatversion' to '0'
Press ENTER or type command to continue
[nvim-treesitter] [1/4, failed: 1] Compiling...
Press ENTER or type command to continue
[nvim-treesitter] [1/4, failed: 1] Checking out locked revision
Press ENTER or type command to continue
[nvim-treesitter] [1/4, failed: 1] Checking out locked revision
Press ENTER or type command to continue
[nvim-treesitter] [1/4, failed: 1] Compiling...
Press ENTER or type command to continue
[nvim-treesitter] [1/4, failed: 1] Compiling...
Press ENTER or type command to continue
[nvim-treesitter] [2/4, failed: 1] Treesitter parser for git_rebase has been installed
Press ENTER or type command to continue
```

Above, I was pressing Enter every 3 seconds.

Any way to avoid this?

**Comment by clason** [comment]
We have `auto_install` now.
