### ISSUE TITLE
[Dart] Very slow startup performance for Dart files once 'textobjects' are enabled

### ISSUE THREAD

**Issue by bluz71** [nvim-treesitter/nvim-treesitter#2126]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`
- [X] I have read the [troubleshooting section](https://github.com/nvim-treesitter/nvim-treesitter#troubleshooting)

### Describe the bug

Neovim startup with Treesitter-enabled Dart files is **very slow** if Treesitter text objects are enabled.

### To Reproduce

Download [this Dart file](https://github.com/bluz71/vim-nightfly-guicolors/blob/master/samples/dart.dart).

Use this minimal Neovim `init.vim` configuration (or something similar):

```viml
call plug#begin('~/.vim/plugged')
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
Plug 'nvim-treesitter/playground'
Plug 'nvim-treesitter/nvim-treesitter-textobjects'
call plug#end()

lua << EOF
  local treesitter = require('nvim-treesitter.configs')

  treesitter.setup({
    ensure_installed = {
      'dart',
    },
    highlight = {
      enable = true,
    },
    indent = {
      enable = false,
    },
    textobjects = {
      select = {
        enable = true,
        lookahead = true,
        keymaps = {
          ['am'] = '@function.outer',
          ['im'] = '@function.inner',
        },
      },
    }
  })
EOF
```

At the command line type `nvim dart.dart`. This will be **very slow**.

Now in the `init.vim` file comment out all the `textobjects` block and redo `nvim dart.dart`. Now it is fast.

### Expected behavior

Starting up Neovim with Treesitter Dart files should always be fast.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar,   not required for :TSInstall)
  - OK: `node` found v14.17.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be        compatible with runtime ABI.

## Parser/Features H L F I J
  - dart           ✓ ✓ . ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az32-74

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Comment by stsewd** [comment]
Hi, I can't reproduce with neovim nightly. Probably you need https://github.com/neovim/neovim/pull/16606, please try with neovim nightly.

**Comment by bluz71** [comment]
@stsewd,

This issue does not reproduce with nightly (just tested).
Issue is **very noticeable** with 0.6 stable.

**Comment by stsewd** [comment]
Then that was the problem then. We recommend using nightly, since tree-sitter isn't stable yet.

**Comment by bluz71** [comment]
I will stick with 0.6.
I did the nightly dance with 0.5 and 0.6, I now wish to use stable for a few months.
I will disable Treesitter for Dart instead.
Such a shame that the upstream Treesitter folks buggered up performance.

**Comment by lvmtam** [comment]
i have a same problem too, the first time we open a dart file. it take me a 3~4 seconds. hope it will stable soon

**Comment by jshji252** [comment]
Hello, was this a problem with neovim?

I experienced the same problem, and so I temporarily disabled textobjects. I'm using
```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377
```
thx

**Comment by clason** [comment]
It's a problem with the dart parser, which makes some (reasonable-looking) queries extraordinarily slow.

**Comment by jshji252** [comment]
@clason Hey thanks for the reply and your suggestions! I'll do that. Thanks again for your super quick help :)

**Comment by TpouHuK** [comment]
Issue still persists.
