### ISSUE TITLE
nvim-treesitter doesn't seem to work in windows.

### ISSUE THREAD

**Issue by nishu-murmu** [nvim-treesitter/nvim-treesitter#2135]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`
- [X] I have read the [troubleshooting section](https://github.com/nvim-treesitter/nvim-treesitter#troubleshooting)

### Describe the bug

As soon as I load my neovim there's error showing nvim-treesitter failed to execute the command. I've installed all the C compilers (cc, gcc, clang, zig). But it still doesnt seem to work. 
<img src="https://github.com/nishu-murmu/dotfiles/blob/main/images/error.png?raw=true" width="100%">

### To Reproduce

```
require("nvim-treesitter.install").prefer_git = true
require("nvim-treesitter.install").command_extra_args = {
    curl = { "--proxy", "<proxy url>" },
}
require 'nvim-treesitter.install'.compilers = { "clang" }
require'nvim-treesitter.configs'.setup {

    ensure_installed = "maintained",
    sync_install = false,
    ignore_install = { "javascript" },
    highlight = {
      enable = true,
      disable = { "c", "rust" }
    },
    incremental_selection = {
      enable = true,
      keymaps = {
        init_selection = "gnn",
        node_incremental = "grn",
        scope_incremental = "grc",
        node_decremental = "grm",
      }
    },
    indent = {
      enable = true
    },
    textobjects = { enable = true }
}

```
This is my nvim-treesitter config in lua can someone point out what's the issue?

### Expected behavior

I expected to nvim-treesitter to work with the above config.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found (unknown version) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.17.6 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `clang` executable found. Selected from { "clang" }
    Version: clang version 13.0.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az152-703

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"
```

**Comment by theHamsta** [comment]
Can you please repost the image in your report? I can't see anything.

**Comment by nishu-murmu** [comment]
I got it, the problem was that I had not installed tree-sitter-cli globally, so this error was shown.

**Comment by ffuszthaler** [comment]
I tried that and I still get the same error

**Comment by nishu-murmu** [comment]
In your `:checkhealth` did you see your tree sitter cli version?

**Comment by ffuszthaler** [comment]
This is what ```:checkhealth nvim-treesitter``` gives me:
![image](https://user-images.githubusercontent.com/25418250/148596204-d7c8bf52-81ae-4b0f-9583-c698c4f80e4f.png)

**Comment by nishu-murmu** [comment]
Which system are you using Windows or Linux?
If Linux then you shouldn't have seen this error.
If windows then, it is expected, cause I had this problem in my windows. It's bug I suppose.
I think it might have something to do with [Windows support](https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support)

**Comment by theHamsta** [comment]
@ffuszthaler how did you install GCC? Please make sure that all it's executables are in path.

The tree-sitter-cli is not necessary to build parsers.

**Comment by ffuszthaler** [comment]
I used scoop, so `scoop install gcc`, the same way I installed neovim and yes I it is part of the PATH

**Comment by ffuszthaler** [comment]
Also, yes I use windows 11

**Comment by ffuszthaler** [comment]
It previously worked on the windows 10 machine, I guess it auto-updated gcc and that broke it again. Something like version 8.x to 11.x.

**Comment by nishu-murmu** [comment]
@theHamsta all the executables are in the path but still this error was shown in my case as well.

**Comment by ffuszthaler** [comment]
are there any new developments regarding this issue?

**Comment by clason** [comment]
If there were, you would have been notified since you commented on this issue.

**Comment by dundargoc** [comment]
> @theHamsta are there any new developments regarding this issue?

I couldn't not get tree-sitter to work on Windows with any of the "standard" compilers like gcc, clang or zig. The only compiler that worked for me was MinGW. Have you tried MinGW?

**Comment by theHamsta** [comment]
For me, it is working on all the compilers (with some unpredictable problems that sometimes occur with GCC). Also the artifacts from CI (as we still uploaded them) worked for me.

There is no concrete issue described in this issue. The screen shot from  OP is still missing. For @ffuszthaler, the compiler complains that `as` which is part of the GCC compiler suite is not in PATH. An issue with `scoop` maybe? Have you asked them about this issue?

I would prefer to close this issue instead of collecting different problems under the same issue with a very undescriptive title. Please file a detailed report with you concrete problem that we can help you with that concrete instance of the problem instead of confusing others which are tackling something else.

**Comment by EhsanHerai** [comment]
install Cygwin
http://cygwin.com/install.html

**Comment by jrasanen** [comment]
I also get this error. Which version of `gcc` and `g++` are required?

I have gcc and g++ 11.3 installed. What else is required?

![image](https://user-images.githubusercontent.com/13303/172000398-cdff8b6a-bdea-470e-9247-0356c9d5facb.png)

![image](https://user-images.githubusercontent.com/13303/172000393-32cf1387-f643-4e39-bc56-9ebc1117f867.png)

![image](https://user-images.githubusercontent.com/13303/172000442-7bf34cef-48a4-4886-85bf-1672ab04ae3a.png)

**Comment by Rohith-JN** [comment]
I got the same error so I reinstalled gcc like this:
```
scoop install gcc
```
and it automatically added it to PATH and treesitter installed all the parsers

**Comment by tankorsmash** [comment]
I was having a similar trouble, seems like using Powershell as admin, then installing llvm via `choco install llvm`, and `npm install -g tree-sitter-cli`, and also adding the following to my `init.lua`:

    require 'nvim-treesitter.install'.compilers = { "clang" }

Then `:TSInstall c` compiles successfully, and more importantly `:checkhealth` doesn't list the `c.so` as unable to be installed.
