### ISSUE TITLE
Python - Calling an identifier that looks like a constant gets classified as a "Constructor" call

### ISSUE THREAD

**Issue by omertuc** [nvim-treesitter/nvim-treesitter#2141]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`
- [X] I have read the [troubleshooting section](https://github.com/nvim-treesitter/nvim-treesitter#troubleshooting)

### Describe the bug

In Python , calling an identifier that looks like a constant gets highlighted as a "constructor" call:
![image](https://user-images.githubusercontent.com/10882062/146683317-af73c3a7-6360-4a7c-beba-6f80852764e7.png)

### To Reproduce

in some `file.py` write:

```python
some_function()
SOME_CONSTANT()
```

And observe the different syntax highlighting

(funnily looking at the code block above in the GitHub web UI, it seems like GitHub suffers from the same/similar bug? I think they just highlight it as a constant rather than a function, and nvim-treesitter highlights it as a constructor rather than a function)

### Expected behavior

I guess it should be a highlighted as a regular function call (`@function`). Or as specified above, maybe what GitHub is doing is better - highlighting it as a constant still, even when called like a function.

Doesn't seem like GitHub even has different highlighting for things that look like a constructor call:

```python
SOME_CONSTANT = 5
some_variable = 3

some_function()
some_variable()
SOME_CONSTANT()
SomeConstructor()
```

So maybe following their footsteps is not a great idea

### Output of `:checkhealth nvim-treesitter`

```markdown
:checkhealth nvim-treesitter
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.1 (9f535f95bdfa12fa1240d5c33d2c20de2da7d357) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.11.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - cmake          ✓ . ✓ . . 
  - dockerfile     ✓ . . . ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - gomod          ✓ . . . ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - gowork         ✓ . . . ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - markdown       ✓ . . . ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.7.0-dev+748-gabdf3a812
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az50-246

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

cc @stsewd confirmed this was a bug on Matrix chat

**Comment by stsewd** [comment]
This comes from https://github.com/nvim-treesitter/nvim-treesitter/blob/e01c7ce9727b9d18b71b41cc792cb4719e469598/queries/python/highlights.scm#L65-L72

Every function call where the identifier starts with an uppercase letter is considered a constructor.
We could ignore all uppercase identifiers from that, but then things like `HTTP()` won't be highlighted as a constructor... Maybe just ignore them if they are all uppercase with `_`? But I haven't seen an all uppercase function in codebases (have you deal with codebases like this?), so maybe the current query is just good enough?

**Comment by omertuc** [comment]
The more I think about it the more I realize just how much those queries are all just best-effort heuristics rather than strict rules, making #2141 seem rather unimportant in hindsight.

I guess we could exclude call identifiers with `_` from being considered "constructors" - but to be fair it probably has no real world consequences so I guess this ticket could be closed, it just adds unnecessary complexity to the query

**Comment by theHamsta** [comment]
For other such situations, we required to have at least one lower case letter to apply the type/constructor highlight. This could be done also in this situation.

**Comment by omertuc** [comment]
> For other such situations, we required to have at least one lower case letter to apply the type/constructor highlight. This could be done also in this situation.

Yeah but even then I feel it's an arbitrary decision which also has imperfections / tradeoffs, for example:
- You'll miss classes named after acronyms. Such as Python's `abc` module's `ABC` class from the built-in library (it's an acronym for AbstractBaseClass if you're unfamiliar with it)
- You'll miss classes with a single letter as a name, which I've seen a lot show up in example code / exercises:
```python
class A:
    pass

class A(B):
    pass
```

The former is unfortunate, the latter is admittedly less probelmatic, but I feel like there's no perfect solution here
