### ISSUE TITLE
[markdown] Allow to fold headers

### ISSUE THREAD

**Issue by echasnovski** [nvim-treesitter/nvim-treesitter#2145]
**Is your feature request related to a problem? Please describe.**
I find it very useful to have folds when writing markdown. For me, the most reasonable foldable regions are text belonging to same header and code blocks. With recently added [markdown parser](https://github.com/MDeiml/tree-sitter-markdown) this is not possible at the moment.

**Describe the solution you'd like**
A way to use folds in markdown files.

**Describe alternatives you've considered**
Before treesitter parser I used [vim-markdown](https://github.com/plasticboy/vim-markdown) which has folds but together with other set of unwanted issues.

**Additional context**
The main problem here is that current markdown parser doesn't produce hierarchical tree when parsing text, i.e. paragraphs seem to always be "level 1" nodes. Here is an example:

![screenshot_2021-12-20_14:58:19](https://user-images.githubusercontent.com/24854248/146771028-ca1f7002-9ae2-4a15-9d3c-36b2d28cb90e.png)

This contradicts existing approach to folding with `nvim_treesitter#foldexpr()` which folds queried regions based on hierarchy. I've come up with solution that I am happy with. It is a slightly modified version of this code (which itself is based on 'fold.lua' from this repository):
<details>
<summary>Details of `markdown_foldexpr`</summary>

Lua code:

```lua
local query = require('nvim-treesitter.query')
local parsers = require('nvim-treesitter.parsers')
local ts_utils = require('nvim-treesitter.ts_utils')

local folds_levels = ts_utils.memoize_by_buf_tick(function(bufnr)
  local parser = parsers.get_parser(bufnr)

  if not (parser and query.has_folds('markdown')) then
    return {}
  end

  local levels = {}

  -- NOTE: don't use `_recursive` variant to fold only based on markdown itself
  local matches = query.get_capture_matches(bufnr, '@fold', 'folds')
  for _, m in pairs(matches) do
    local node = m.node
    local s_row, _, e_row, _ = node:range()
    local node_is_heading = node:type() == 'atx_heading' or node:type() == 'setext_heading'
    local node_is_code = node:type() == 'fenced_code_block'

    -- Process heading. Start fold at start line of heading with fold level
    -- equal to header level.
    if node_is_heading then
      for child in node:iter_children() do
        local _, _, level = string.find(child:type(), 'h([0-9]+)')
        if level ~= nil then
          levels[s_row] = ('>%s'):format(level)
          break
        end
      end
    end

    -- Process code block. Add fold level at start line and subtract at end.
    if node_is_code then
      levels[s_row] = 'a1'
      levels[e_row - 1] = 's1'
    end
  end

  return levels
end)

_G.markdown_foldexpr = function()
  local levels = folds_levels(vim.api.nvim_get_current_buf()) or {}

  return levels[vim.v.lnum - 1] or '='
end
```

Fold queries:
```
[
 (atx_heading)
 (setext_heading)
 (fenced_code_block)
] @fold
```

</details>

I am happy to put this kind of solution somewhere in this repository. Just not sure where and in what form.

**Comment by David-Else** [comment]
I am pretty new to using folds in Neovim, just trying to develop my own workflow. Is your use case to automatically fold paragraphs and code blocks using something like toggling with `za` in the same way that headers work now, or does this relate to 'Cannot create fold with current fold method' using `zf{motion}`?

The header folding is actually working perfectly at the moment, I was quite surprised as the new markdown parser is so new.

**Comment by echasnovski** [comment]
I usually use `foldmethod=indent` as it is very intuitive and is actually what I want around 99% of the time. I usually use `za`, `zA`, `zR` and `zM` to work with automatically created folds.

I am not sure what you mean by "header folding is actually working perfectly". As there seem to be no mechanism of doing folds based on output of current markdown parser. Are you sure you don't use some other functionality from other plugin or filetype?

**Comment by David-Else** [comment]
I have this in my `init.vim`
```
let g:markdown_folding = 1
let g:markdown_fenced_languages = [
  \ 'bash=sh', 'javascript', 'js=javascript', 'typescript',
  \ 'ts=typescript', 'php', 'html', 'css', 'rust', 'sql']
```
and the new markdown parser with treesitter, header folding is working perfectly for me in Neovim 0.6. Do you have `markdown_folding = 1`?

**Comment by theHamsta** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries/markdown has not yet `folds.scm` to support tree-sitter-based folding. Someone could add them.

**Comment by echasnovski** [comment]
This setting seems to enable folding from [Neovim's runtime filetype](https://github.com/neovim/neovim/blob/master/runtime/ftplugin/markdown.vim). It doesn't actually use treesitter parser but custom regex-based solution. Which should work most of the time if you want to fold only by headers.

Generally, a nice alternative, albeit might be slow on large files. However, this is not what this issue is about.

**Comment by echasnovski** [comment]
> https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries/markdown has not yet `folds.scm` to support tree-sitter-based folding. Someone could add them.

Just doing that won't work as parser doesn't define hierarchical structure. I tried that: it will fold only headers themselves.

**Comment by David-Else** [comment]
> > I have this in my `init.vim`
> > ```
> > let g:markdown_folding = 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and the new markdown parser with treesitter, header folding is working perfectly for me in Neovim 0.6. Do you have `markdown_folding = 1`?
> 
> This setting seems to enable folding from [Neovim's runtime filetype](https://github.com/neovim/neovim/blob/master/runtime/ftplugin/markdown.vim). It doesn't actually use treesitter parser but custom regex-based solution. Which should work most of the time if you want to fold only by headers.
> 
> Generally, a nice alternative, albeit might be slow on large files. However, this is not what this issue is about.

OK, thanks for the info. Header folding is enough for me for now, but if a native treesitter solution is made available then fantastic :)

**Comment by MDeiml** [comment]
I don't think it's a good idea to add the hierarchical structure to the markdown grammar. It's not really part of the syntax. Would it be possible to make folds more flexible to support something like this? Or would this require some kind of plugin?

**Comment by theHamsta** [comment]
It's possible to fold on multiple nodes summarizing then to a single range using `#make-range`. It would be nice to have a more modern version of this directive that only uses nvim core metadata.

**Comment by fisher-j** [comment]
@MDeimi For me, the markdown syntax does imply a hierarchical structure: level 2 headers are nested within level 1, level 3 within level 2 and so on. I frequently write papers in markdown where there is a need to edit the document in a hierarchical fashion. Attempting to move sections, including their subsections around using regex is complicated, especially when there is code (with comments) embeded in the document.

**Comment by fisher-j** [comment]
I'd also love the ability to fold header sections. In addition, it seems like the ability to interact with header levels hierarchically would facilitate useful outlining operations like moving header-sections (with all sub-header sections) and promoting/demoting header sections recursively.

**Comment by musjj** [comment]
I still can't fold markdown headers even in the latest commit. Has anyone else tested this?
