### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by ffuszthaler** [nvim-treesitter/nvim-treesitter#2152]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`
- [X] I have read the [troubleshooting section](https://github.com/nvim-treesitter/nvim-treesitter#troubleshooting)

### Describe the bug

Everytime i start neovim I get messages like these while it tries to install parsers: 
<img width="914" alt="image" src="https://user-images.githubusercontent.com/25418250/147082313-54f3851b-c802-4f37-8d2f-a45b74656cdd.png">

### To Reproduce

Wouldn't know how you could reproduce this, sorry.

### Expected behavior

No errors while installing the parsers.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v17.3.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: gcc.exe (GCC) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Übersetzt von runneradmin@fv-az152-703

Features: -acl +iconv +tui
See ":help feature-compile"

          System-vimrc-Datei: "$VIM\sysinit.vim"
     Voreinstellung für $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

### Additional context

Wanted to install my config on my new PC
Installed neovim and gcc trough scoop

**Comment by theHamsta** [comment]
Can you check whether `tree-sitter-javascript` already exists in `:echo stddir('data')` and whether nvim does not have the rights to remove it (e.g. because you had it previously running as admin)

**Comment by ffuszthaler** [comment]
Once I start nvim the folder gets created, and the next time I start it it complains that the folder already exists.
If I delete it, it'll get created the next time i restart nevim

**Comment by ffuszthaler** [comment]
But it seems to download everything correctly

**Comment by ffuszthaler** [comment]
Any help on this would be really appreciated

**Comment by ffuszthaler** [comment]
Also, commands like :TSInstallSync,  seem to work, but if I restart nvim afterwards, the same messages reappear

<img width="499" alt="image" src="https://user-images.githubusercontent.com/25418250/147361140-db29c342-dd8a-47b2-8f41-33aa9dc6f42a.png">

**Comment by ffuszthaler** [comment]
<img width="611" alt="image" src="https://user-images.githubusercontent.com/25418250/147362772-f9029285-8086-4976-a11b-df639e6db2eb.png">

**Comment by ffuszthaler** [comment]
Also where can I find more specific logfiles to see if those contain more information than nvim shows?

**Comment by ffuszthaler** [comment]
Is there any chance at help?

**Comment by lewis6991** [comment]
Is this still an issue?

**Comment by DawidKrysiak** [comment]
@lewis6991 I have the same problem (win11, nvim 0.9.2.
