### ISSUE TITLE
Treesitter shows error messages after upgrading to nvim 0.6.0

### ISSUE THREAD

**Issue by kaiywen** [nvim-treesitter/nvim-treesitter#2162]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`
- [X] I have read the [troubleshooting section](https://github.com/nvim-treesitter/nvim-treesitter#troubleshooting)

### Describe the bug

After upgrading to nvim0.6.0, treesitter reports following messages:

```
packer.nvim:` Error running config for nvim-treesitter: [string "..."]:0: loop or previous error loading module 'nvim-treesitter.configs'
```

while nvim0.5.0 works well.

### To Reproduce

1. Upgrading neovim from 0.5.0 to release-0.6
2. Open neovim and treesitter shows error messages

### Expected behavior

Neovim works without any warnings or errors

### Output of `:checkhealth nvim-treesitter`

```markdown
health#nvim_treesitter#check
========================================================================
  - ERROR: Failed to run healthcheck for "nvim_treesitter" plugin. Exception:
    function health#check[21]..health#nvim_treesitter#check, line 1
    Vim(lua):E5108: Error executing lua ...acker/opt/nvim-treesitter/lua/nvim-treesitter/health.lua:5: loop or previous error loading module 'nvim-treesitter.info'
    stack traceback:
    [C]: in function 'require'
    ...acker/opt/nvim-treesitter/lua/nvim-treesitter/health.lua:5: in main chunk
    [C]: in function 'require'
    [string ":lua"]:1: in main chunk
```

### Output of `nvim --version`

```text
$ nvim6 --version
NVIM v0.6.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az65-618

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by stsewd** [comment]
did you try re-installing the plugin? Also make sure you have deleted all previous installations from the runtime directory, we have had some other reports where packer installs the plugin on two paths.

**Comment by kaiywen** [comment]
I've tried to reinstall the plugin for several times,  with packer or manually, but it did not help.

I also checked that packer did not install the plugin on any other paths.

**Comment by kaiywen** [comment]
More infomation,

```
:lua print(vim.inspect(require'nvim-treesitter.info'))  
:lua print(vim.inspect(require'nvim-treesitter.configs'))  
```

both say like this:

```
E5108: Error executing lua [string ":lua"]:1: loop or previous error loading module 'nvim-treesitter.info'
stack traceback:
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
```

**Comment by kaiywen** [comment]
> did you try re-installing the plugin? Also make sure you have deleted all previous installations from the runtime directory, we have had some other reports where packer installs the plugin on two paths.

I find that my `$VIMRUNTIME` pointed to the wrong path. After fixing it, everything goes well.

Thanks for your suggestions.

**Comment by andersondanilo** [comment]
I was having a similar error and had to go to the directories and exec an git pull, like: `cd ~/.local/share/nvim/site/pack/packer/start/packer.nvim` and `git pull`, besides the packer i also upgraded the treesitter using this way

**Comment by HeorhiiS** [comment]
> 

This has worked for me, one `git pull` in `packer.nvim` and another in `nvim-treesitter.nvim`.
