### ISSUE TITLE
[OOM-KILL] nvim-treesitter[bash]: Error during compilation cc: fatal error: Killed signal terminated program cc1 compilation terminated.

### ISSUE THREAD

**Issue by dzintars** [nvim-treesitter/nvim-treesitter#2177]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`
- [X] I have read the [troubleshooting section](https://github.com/nvim-treesitter/nvim-treesitter#troubleshooting)

### Describe the bug

When testing Nvim setup i am using VM with 1024 MB of memory... because... why would i need more? 😃 
My Treesitter config is simple as:
```lua
local ok, treesitter = pcall(require, "nvim-treesitter.configs")
if (not ok) then return end

treesitter.setup({
  ensure_installed = {
    'bash', 'go', 'html', 'javascript', 'json', 'lua', 'python', 'toml', 'yaml', 'markdown'
  },
})
```
When i first run the fresh instance VM just die. Get's, laggy, unresponsive, etc.
Errors i get is quite chaotic, but one of them is:
```bash
nvim-treesitter[bash]: Error during compilation cc: fatal error: Killed signal terminated program cc1 compilation terminated.
```
and like:
![image](https://user-images.githubusercontent.com/547420/147775678-36b9f605-619f-456c-83a4-02cf0bce7427.png)

If i continue to kill the Nvim and to run it again on the same VM instance, i eventually get past those errors and all language parsers get installed.
I am building Neovim from source on the same instance an i have no issues with that.

If i give little bit more juice for particular testing VM, then i have no issues at all. All parsers get compiled flawlessly in a first run.

![image](https://user-images.githubusercontent.com/547420/147777948-3608abf4-252f-4614-a66d-dc3a6e0fd502.png)

### To Reproduce

Not sure. Try to run many `ensure_installed` parsers on a small instance.

### Expected behavior

Is there a way to control how parser compilation happens?

### Output of `:checkhealth nvim-treesitter`

```markdown
Unfortunately my clipboard is not there configured. I added image above.
```

### Output of `nvim --version`

```text
NVIM v0.7.0-dev+nightly
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/vagrant/code/github.com/neovim/neovim/build/config -I/home/vagrant/code/github.com/neovim/neovim/src -I/home/vagrant/code/github.com/neovim/neovim/.deps/usr/include -I/usr/include -I/home/vagrant/code/github.com/neovim/neovim/build/src/nvim/auto -I/home/vagrant/code/github.com/neovim/neovim/build/include
Compiled by vagrant@f34

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by theHamsta** [comment]
Can you try `:TSInstallSync` or the sync option in `setup`? Sequential instillation requires less memory. Normal installation will spawn all parser compilations at once. The generated files can be quite big.

Is there any action items that we can do on that? I think most user would prefer the speed of parallel parser compilation over increased memory usage. Can you profile memory usage? E.g. with valgrind, Intel vtune or the simple process monitor which parser is causing the memory consumption?

**Comment by theHamsta** [comment]
I think this is more of an edge case. Please try to run synchronous compilation when memory usage is an issue.
