### ISSUE TITLE
How to check which parser is using?

### ISSUE THREAD

**Issue by fecet** [nvim-treesitter/nvim-treesitter#2180]
Is there a function to tell me which parser is using like `LspInfo`, for example, show "treesitter.python" when edit a ".py" file, `TSModuleInfo` is a similar thing but not  exactly what I want.

**Comment by theHamsta** [comment]
No, directly but you can write one

```
function _G.current_treesitter_lang()
   local parser = require'vim.treesitter.highlighter'.active[vim.api.nvim_get_current_buf()]
   if parser then
      return parser.tree:lang()
  end
end 
```
Usage
```
:lua print(current_treesitter_lang)
```
or create a command
```
comand! TSCurrentLang :lua print(current_treesitter_lang() or "tree-sitter disabled")
```

**Comment by fecet** [comment]
Thank you! This solved my urgent need!
