### ISSUE TITLE
Add RASI (rofi advanced style information) support

### ISSUE THREAD

**Issue by Fymyte** [nvim-treesitter/nvim-treesitter#2187]
**rasi**

It's a language based on css.
[here is the language spec](https://man.archlinux.org/man/community/rofi/rofi-theme.5.en).
I already created a parser and syntax highlighting queries for this language here: [Fymyte/tree-sitter-rasi](https://github.com/Fymyte/tree-sitter-rasi)

Do you think it could be possible to include this language here ?

I can make the pull request but I am not sure of all places were modification is needed

**Comment by theHamsta** [comment]
This looks very nice! To add the parser zyou just need to add its metainformation to parsers.lua (README is autogenerated).

If you want to add highlight queries just place the files under `queries/rofi`. There's nothing more you need to do. You might want to have a look at our CONTRIBUTING.md
