### ISSUE TITLE
@constructor overrides @constant highlighting in php files

### ISSUE THREAD

**Issue by infectos** [nvim-treesitter/nvim-treesitter#2207]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`
- [X] I have read the [troubleshooting section](https://github.com/nvim-treesitter/nvim-treesitter#troubleshooting)

### Describe the bug

Freshly installed nvim-treesitter with php parser has `@constructor` group which sometime overrides other groups. 
For example I cannot change highlighting for constants because `@constructor` apparently has higher priority.
I am not sure it is supposed to act that way. All constants should be purple, but they are orange.
![Screenshot from 2022-01-07 05-30-21](https://user-images.githubusercontent.com/57968042/148483714-4bb5d88e-77ad-4dd4-b1d6-eb63963d8069.png)

### To Reproduce

1. Enable php parser 
2. Turn on highlighting in php files.
3. `:TSHighlightCapturesUnderCursor `on any constant.

### Expected behavior

I expect constants (declaration and calls) to be highlighted not as `@constructor`, but as `@constant` group.

### Output of `:checkhealth nvim-treesitter`

```markdown
1 nvim-treesitter: require("nvim-treesitter.health").check()
    2 ========================================================================
    3 ## Installation
    4   - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
    5   - OK: `node` found v17.1.0 (only needed for :TSInstallFromGrammar)
    6   - OK: `git` executable found.
    7   - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    8     Version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
    9   - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.
   10 
   11 ## Parser/Features H L F I J
   12   - php            ✓ ✓ ✓ ✓ ✓ 
   13   - query          ✓ ✓ ✓ ✓ ✓ 
   14   - javascript     ✓ ✓ ✓ ✓ ✓ 
   15   - ruby           ✓ ✓ ✓ ✓ ✓ 
   16 
   17   Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
   18          +) multiple parsers found, only one will be used
   19          x) errors found in the query, try to run :TSUpdate {lang}
   20
```

### Output of `nvim --version`

```text
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by xeluxee** [comment]
I'm experiencing a similar issue with CPP, **every** function is considered a costructor

![func-constructor](https://user-images.githubusercontent.com/88047141/149020095-7a676aa0-8e86-4481-a836-b462c6a39a87.png)
As you can see methods and functions are highlighted with bold yellow, a color that is used for constructors (the colorscheme I'm using, [onedark](https://github.com/navarasu/onedark.nvim), uses blue for methods and functions).

Launching `:TSHighlightCapturesUnderCursor` with cursor on `printf` gives the following output:
![ts](https://user-images.githubusercontent.com/88047141/149020645-493690b1-eca8-4588-8ff4-f11677bb57d6.png)
`TSConstructor` shouldn't be there.

**Comment by mikehaertl** [comment]
Same happens for PHP class definitions:

![ts_class_constructor](https://user-images.githubusercontent.com/675062/149394109-838a51f5-4878-4a7f-8e64-f4e79e4242d2.png)

**Comment by theHamsta** [comment]
@xeluxee your issue seems lot like a tree-sitter issue that was ago where it wouldn't check predicates. Which nvim version are you using? Are you building from source with a specific tree-sitter version?

**Comment by mikehaertl** [comment]
@theHamsta I tried your proposed change but it made no difference. Do I need to compile something after the change?

BTW in the current code it uses `lua-match`:

https://github.com/nvim-treesitter/nvim-treesitter/blob/a76e1eb89d57e25cedbc71d6bf8e2d2c23d5d85b/queries/php/highlights.scm#L58-L59

**Comment by theHamsta** [comment]
@mikehaertl i think the regex is matching to constructor calls and we most likely have inherited it from the original upstream query. Can you create a fix for this issue? I have no experience with PHP

**Comment by mikehaertl** [comment]
I will try. I need to study TS query language first. It seems the PHP highlighting is lacking many features that the parser provides.

**Comment by infectos** [comment]
@theHamsta,
I created pull request #2249, if it's any helpful.

**Comment by xeluxee** [comment]
> @xeluxee your issue seems lot like a tree-sitter issue that was ago where it wouldn't check predicates. Which nvim version are you using? Are you building from source with a specific tree-sitter version?

I'm using NVIM 0.6.0 and treesitter 0.20.0
```
NVIM v0.6.0                                                                                                                                                    
Build type: Release                                                                                                                                            
LuaJIT 2.0.5
```

**Comment by mikehaertl** [comment]
@xeluxee Your issue is about C++ right? Isn't it better if you open a new issue for this to keep things separated?

**Comment by xeluxee** [comment]
@theHamsta I've just update tree-sitter to 0.20.1 and the bug disappeared. Thanks for your help

**Comment by theHamsta** [comment]
This has been fixed by various PRs.
