### ISSUE TITLE
The hpp file is detected as a foam file.

### ISSUE THREAD

**Issue by rhcher** [nvim-treesitter/nvim-treesitter#2224]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`
- [X] I have read the [troubleshooting section](https://github.com/nvim-treesitter/nvim-treesitter#troubleshooting)

### Describe the bug

The hpp file with some special context is detected as a foam file.

### To Reproduce

1. open hpp file I provide.
2. `:set ft?`
![image](https://user-images.githubusercontent.com/50723480/148678193-4205df33-146a-4cb6-862f-53ca7ea7ff4a.png)
3. the language server works properly, so it't not a filetype.lua issue.

### Expected behavior

The filetype is not detected as foam.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.2 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.3.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Sele
```

### Output of `nvim --version`

```text
NVIM v0.7.0-dev+858-gc7ffe406bc
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno
-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong
 -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_L
OG_LEVEL=3 -I/build/neovim-git/src/build/config -I/build/neovim-git/src/neovim-git/src -I/usr/include -I/build/neovim-git/src/build/src/nvim/auto
 -I/build/neovim-git/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

The issue appears after this commit 99d4d7e2d8c224089b30531592f9ae35a2313964
test.hpp
```cpp
#ifndef LLVM_EXECUTIONENGINE_ORC_KALEIDOSCOPEJIT_H
#define LLVM_EXECUTIONENGINE_ORC_KALEIDOSCOPEJIT_H

#include "llvm/ADT/StringRef.h"
#include "llvm/ExecutionEngine/JITSymbol.h"
#include "llvm/ExecutionEngine/Orc/CompileUtils.h"
#include "llvm/ExecutionEngine/Orc/Core.h"
#include "llvm/ExecutionEngine/Orc/ExecutionUtils.h"
#include "llvm/ExecutionEngine/Orc/IRCompileLayer.h"
#include "llvm/ExecutionEngine/Orc/IRTransformLayer.h"
#include "llvm/ExecutionEngine/Orc/JITTargetMachineBuilder.h"
#include "llvm/ExecutionEngine/Orc/RTDyldObjectLinkingLayer.h"
#include "llvm/ExecutionEngine/SectionMemoryManager.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/InstCombine/InstCombine.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Scalar/GVN.h"
#include "llvm/Transforms/Utils.h"
#include <algorithm>
#include <memory>

namespace llvm {
namespace orc {

class KaleidoscopeJIT {
private:
  ExecutionSession ES;
  RTDyldObjectLinkingLayer ObjectLayer;
  IRCompileLayer CompileLayer;
  IRTransformLayer OptimizeLayer;

  DataLayout DL;
  MangleAndInterner Mangle;
  ThreadSafeContext Ctx;

  JITDylib &MainJD;

public:
  KaleidoscopeJIT(JITTargetMachineBuilder JTMB, DataLayout DL)
      : ObjectLayer(ES,
                    []() { return std::make_unique<SectionMemoryManager>(); }),
        CompileLayer(ES, ObjectLayer,
                     std::make_unique<ConcurrentIRCompiler>(std::move(JTMB))),
        OptimizeLayer(ES, CompileLayer, optimizeModule), DL(std::move(DL)),
        Mangle(ES, this->DL), Ctx(std::make_unique<LLVMContext>()),
        MainJD(ES.createBareJITDylib("<main>")) {
    MainJD.addGenerator(
        cantFail(DynamicLibrarySearchGenerator::GetForCurrentProcess(
            DL.getGlobalPrefix())));
  }

  const DataLayout &getDataLayout() const { return DL; }

  LLVMContext &getContext() { return *Ctx.getContext(); }

  static Expected<std::unique_ptr<KaleidoscopeJIT>> Create() {
    auto JTMB = JITTargetMachineBuilder::detectHost();

    if (!JTMB) {
      return JTMB.takeError();
    }

    auto DL = JTMB->getDefaultDataLayoutForTarget();
    if (!DL) {
      return DL.takeError();
    }

    return std::make_unique<KaleidoscopeJIT>(std::move(*JTMB), std::move(*DL));
  }

  Error addModule(std::unique_ptr<Module> M) {
    return OptimizeLayer.add(MainJD, ThreadSafeModule(std::move(M), Ctx));
  }

  Expected<JITEvaluatedSymbol> lookup(StringRef name) {
    return ES.lookup({&MainJD}, Mangle(name.str()));
  }

private:
  static Expected<ThreadSafeModule>
  optimizeModule(ThreadSafeModule TSM, const MaterializationResponsibility &R) {
    TSM.withModuleDo([](Module &M) {
      auto FPM = std::make_unique<legacy::FunctionPassManager>(&M);

      FPM->add(createPromoteMemoryToRegisterPass());
      FPM->add(createInstructionCombiningPass());
      FPM->add(createReassociatePass());
      FPM->add(createGVNPass());
      FPM->add(createCFGSimplificationPass());
      FPM->doInitialization();

      for (auto &F : M) {
        FPM->run(F);
      }
    });
    return std::move(TSM);
  }
};

} // end namespace orc
} // end namespace llvm

#endif // LLVM_EXECUTIONENGINE_ORC_KALEIDOSCOPEJIT_H
```

**Comment by theHamsta** [comment]
@FoamScience can you check what's the issue here?

Long-term I'd really love to remove all file type detect modules from nvim-treesitter. It's not a core competency of this plugin and file types can now be added easily to core nvim or usptream vim.

**Comment by FoamScience** [comment]
> @FoamScience can you check what's the issue here?
> 
> Long-term I'd really love to remove all file type detect modules from nvim-treesitter. It's not a core competency of this plugin and file types can now be added easily to core nvim or usptream vim.

- On my local setup, the test file stays as CPP.
- On a fresh nvim install, it stays as CPP
- Explicitly calling [foamFile(path)](https://github.com/nvim-treesitter/nvim-treesitter/blob/0d53066533643fac8d9a1a247bde3cf9132077ad/after/ftdetect/foam.vim#L3) does not change the CPP file type to foam.

**Comment by FoamScience** [comment]
@rhcher We need more context to tackle this issue; Please, put this in a vim file:
```vim
function FoamFile(path)
    " Return if file type already set
    if (&filetype == 'foam')
        return
    endif

    let l:lines = getline(1, 15)
    let l:f = -1
    let l:o = -1
    for line in lines
        if (match(line, 'FoamFile') >= 0)
            let l:f = index(lines, line)
        endif
        if (match(line, 'object') >= 0)
            let l:o = index(lines, line)
        endif
    endfor
    if ((l:o >= 0) && (l:f) && (l:o > l:f))
        set filetype=foam
    endif
endfunction
```
When you open your c++ file, source that function and call it:
```
:set ft=cpp
:call FoamFile(expand("%"))
:set ft
```
and see if that somehow switches the file type back to foam.
This will help us figure out where the problem is occurring exactly.

**Comment by rhcher** [comment]
@FoamScience @gikari Ok, things are clear, it related to the option `ignorecase`.
nvim -u vimrc.vim test.hpp
min vimrc.vim:
```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
call plug#end()
PlugInstall | quit

set ignorecase

" Setup global configuration. More on configuration below.
lua << EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = {"c", "cpp"},
  sync_install = false,
  highlight = {
    enable = true,
  },
}
EOF
```

**Comment by theHamsta** [comment]
I'm also observing this issue. Is someone confident enough about the reasons of the issue to post a fix?

**Comment by rhcher** [comment]
> I'm also observing this issue. Is someone confident enough about the reasons of the issue to post a fix?
```vim
set ignorecase
```

**Comment by FoamScience** [comment]
I have also reached the same conclusion.
Does anyone know any more regex options we should be aware of?
@theHamsta I have a [branch with this fix](https://github.com/FoamScience/nvim-treesitter/tree/fix-foam-ftdetect), Do you think it's better if I move the file type detection to neovim itself? if so, what's the best place to do that?

**Comment by theHamsta** [comment]
Yes, long-term I think it would be best to remove all ftdetect plugins from the plugin and maybe only have one filetype.lua file with simple extension detection. Can you create a PR that either removes that file or applies some fix?

**Comment by FoamScience** [comment]
OK, let's go with this temporary fix for now, I'll open a draft PR at neovim to handle things properly; I won't have to deal with the C++ issue then.

**Comment by clason** [comment]
> Yes, long-term I think it would be best to remove all ftdetect plugins from the plugin and maybe only have one filetype.lua file with simple extension detection. 

Why can you not rely on Neovim's own `filetype.lua`? What would need to be changed there in order to do so?

**Comment by theHamsta** [comment]
I'd prefer to just rely on Neovim's `filetype.lua` and remove everything filetype related from here.

**Comment by FoamScience** [comment]
BTW I've already started a [PR against VIM](https://github.com/vim/vim/pull/9501) to solve the issue of its root as I don't like `after` stuff either. When/if that PR gets merged in, and NeoVIM takes in the patch, I'll remove `ftdetect` for foam as a first step

**Comment by clason** [comment]
One issue (related to this one, actually) is if there is no actual filetype support in (Neo)Vim -- so the filetype check would do absolutely nothing...  (I.e., if there is _only_ a tree-sitter parser). That's a discussion to be had together with upstream, though.

**Comment by clason** [comment]
Looks like Bram will accept it, though, so it'll come to Neovim in the near future.

**Comment by rhcher** [comment]
However, this issue is fixed by 2fb4e3ec9433b9d8d35d7b198a10e6332638ffd4.

**Comment by FoamScience** [comment]
vim/vim@2284f6cca384e0ccc352bfec7277dc26386cac3dfoam now recognizes filetype.

**Comment by FoamScience** [comment]
@clason Thanks for the super fast response!
I'll remove the `ftdetect` on next NeoVim release.
