### ISSUE TITLE
Remove filetype detection

### ISSUE THREAD

**Issue by kaddkaka** [nvim-treesitter/nvim-treesitter#2231]
**Is your feature request related to a problem? Please describe.**
I updated my `nvim-treesitter` plugin, and suddenly some files were detected as a different filetype, this was very surprising. In my case, files that previously was detected as `mason` now got detected as `glsl`. If I disable the nvim-treesitter plugin, the files are detected as `mason` again.

**Describe the solution you'd like**
Some way to disable treesitter from changing with the filetype or control how it's done

**Describe alternatives you've considered**
Creating my own `autocmd` doesn't seem to take affect after treesitter.
Setting the filetype with `setf` will be reverted back when reloading the file `:e`.

**Comment by theHamsta** [comment]
I'd totally support that. I think that common filetype should be submitted to Vim core or the new Neovim Lua filetype module and uncommon should be set in user config. We really don't want to become polyglot.

**Comment by theHamsta** [comment]
what file ending  does your file have https://github.com/nvim-treesitter/nvim-treesitter/blob/master/ftdetect/glsl.vim Are you refering to meson files ? Do you want to create a PR either to remove the problematic file endings from glsl.vim or to remove all ftdetect plugins together?

**Comment by kaddkaka** [comment]
My file has ending `.comp`, so for my case it would be enough to remove this. I don't want to disturb others but I would prefer to remove all ftdetects in nvim-treesitter.
I can try to provide a PR.

**Comment by kaddkaka** [comment]
Oh I wasn't quick enough, but we did the different solutions. @theHamsta

**Comment by kaddkaka** [comment]
#https://github.com/nvim-treesitter/nvim-treesitter/pull/2235
