### ISSUE TITLE
Early vim style 'syntax enable' command breaks treesitter and lsp attaching capabilities

### ISSUE THREAD

**Issue by RayZ0rr** [nvim-treesitter/nvim-treesitter#2254]
### Before reporting

- [X] I have updated my neovim version to latest _master_
- [X] I have updated my plugin to the latest version
- [X] I have run `:TSUpdate`
- [X] I have read the [troubleshooting section](https://github.com/nvim-treesitter/nvim-treesitter#troubleshooting)

### Describe the bug

Tree-sitter and lsp doesn't attach to file given as first argument to nvim.  Attaches to second file and opening files through other means `:e <files>`

### To Reproduce

1. Download [nvim.appimage](https://github.com/neovim/neovim/releases) (latest or pre-release) and make it executable.
2. Remove any pre-existing plugins in `/tmp` directory
`rm -rf /tmp/nvim*`
3. Use the below minimalrc to open nvim.
<details>
<summary>minimalrc.lua</summary>

```lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
      'nvim-treesitter/nvim-treesitter',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

_G.load_config = function()
  vim.cmd [[ syntax enable ]]
  vim.cmd([[ " PROBLEM PART
    set foldmethod=expr
    set foldexpr=nvim_treesitter#foldexpr()
    set foldlevel=99
  ]])
  require('lspconfig').clangd.setup{}
  -- vim.cmd([[ " PUTTING HERE WORKS
    -- set foldmethod=expr
    -- set foldexpr=nvim_treesitter#foldexpr()
    -- set foldlevel=99
  -- ]])
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end

-- Parsers must be installed manually via :TSInstall
require('nvim-treesitter.configs').setup {
	ensure_installed = {
		"bash",
		"c",
		"cpp",
		"lua",
		"python",
		"rust",
		"html",
		"css",
		"toml",
		"vim",
		-- for `nvim-treesitter/playground`
		"query",
	},
	-- Install languages synchronously (only applied to `ensure_installed`)
	sync_install = false,
	highlight = {
		enable = true, -- false will disable the whole extension
		additional_vim_regex_highlighting = false,
	},
	incremental_selection = {
		enable = true,
		keymaps = {
			-- init_selection = 'gnn',
			init_selection = '<cr>',
			node_incremental = '<tab>',
			scope_incremental = 'grc',
			node_decremental = '<s-tab>',
		},
  },
  indent = {
    enable = true,
  },
}
```
</details>

`./nvim.appimage -nu minimalrc.lua`

4. Repeat this one more time to completely install treesitter parsers.

`./nvim.appimage -nu minimalrc.lua`

5. Now open a sample cpp file

<details>
<summary>sample.cpp</summary>

```cpp
#include <iostream>

int main() {
    std::cout << "Hello World!";
    return 0;
}
```
</details>

`./nvim.appimage -nu minimalrc.lua sample.cpp`

6. Type `:LspInfo`

### Expected behavior

Tree-sitter and lsp client attaches to all files

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.2 (parser generator, only needed for :TSInstallFromGrammar)
  - WARNING: `node` executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - python         ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - vim            ✓ ✓ . . ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

Can be fixed by commenting out or changing position of the this code part in minimal rc .
```lua
  vim.cmd [[ syntax enable ]] -- PROBLEM IF BELOW COMMAND DIRECTLY BELOW
  vim.cmd([[ " CAUSES PROBLEM PROBLEM WITH ABOVE LINE
    set foldmethod=expr
    set foldexpr=nvim_treesitter#foldexpr()
    set foldlevel=99
  ]])
  require('lspconfig').clangd.setup{}
```
The following re-arrangement works : 
```lua
  -- vim.cmd [[ syntax enable ]] -- COMMENT OUT
  vim.cmd([[
    set foldmethod=expr
    set foldexpr=nvim_treesitter#foldexpr()
    set foldlevel=99
  ]])
  require('lspconfig').clangd.setup{}
```
```lua
  vim.cmd [[ syntax enable ]]
  require('lspconfig').clangd.setup{}
  vim.cmd([[ " CHANGE POSITION
    set foldmethod=expr
    set foldexpr=nvim_treesitter#foldexpr()
    set foldlevel=99
  ]])
```
```lua
  vim.cmd([[
    set foldmethod=expr
    set foldexpr=nvim_treesitter#foldexpr()
    set foldlevel=99
  ]])
  vim.cmd [[ syntax enable ]]  -- CHANGE POSITION
  require('lspconfig').clangd.setup{}
```

**Comment by clason** [comment]
Please add a complete minimal example (including a test file and expected/actual outcome).

(Also, your LuaJIT is _ancient_. You should build with a recent commit from the v2.1 branch, like the official/tested builds.)

**Comment by RayZ0rr** [comment]
I have already added minimal rc file. Test file can be any bash or cpp or any file you have treesitter parser and lsp client. I have given for cpp (clangd).

I will look into LuaJIT version. I installed nvim from offical arch repo.

**Comment by clason** [comment]
> I have already added minimal rc file. Test file can be any bash or cpp or any file you have treesitter parser and lsp client. I have given for cpp (clangd).

That's not enough. If you want somebody to look into this, you need to provide simple steps to follow to reproduce exactly what you're seeing and why you thing that's an error.

**Comment by RayZ0rr** [comment]
1. open a cpp file (sample given below) with minimal rc provided in the first comment.  
`nvim -nu minimalrc.lua sample.cpp`
2. Lsp client (here clangd) doesn't attach to file ( from `:Lspinfo` )
3. Tree-sitter also doesn't attach. ( In the sense that text-objects, highlight module, etc doesn't work )

Sample cpp

```cpp
#include <iostream>

int main() {
    std::cout << "Hello World!";
    return 0;
}
```

If `synatx enable` is set by default, it should not break while setting it again.

Could you reproduce?

**Comment by clason** [comment]
I strongly suspect that this is related to filetype detection; since you never actually enable tree-sitter syntax highlighting, the ftdetect scripts are the only thing that are actually run. Hence I believe this should be solved by https://github.com/nvim-treesitter/nvim-treesitter/pull/2234.

**Comment by clason** [comment]
> If synatx enable is set by default, it should not break while setting it again.

That is not a safe assumption.

**Comment by clason** [comment]
> Tree-sitter also doesn't attach. ( In the sense that text-objects, highlight module, etc doesn't work )

That is not surprising since your minimal rc does not tell it to.

**Comment by clason** [comment]
> Could you reproduce?

No, `clangd` attaches with your sample files just fine.

**Comment by RayZ0rr** [comment]
Sorry, I was on phone earlier, so couldn't reply properly.

Can you test with this minimalrc. I am not getting clangd and treesitter to attach ( <cr> doesn't initiate selection)

I had already opened an [issue ](https://github.com/neovim/neovim/issues/17083)at neovim

<details>
<summary>minimalrc.lua</summary>

```lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
      'nvim-treesitter/nvim-treesitter',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

_G.load_config = function()
  vim.cmd [[ syntax enable ]]
  vim.cmd([[ " PROBLEM PART
    set foldmethod=expr
    set foldexpr=nvim_treesitter#foldexpr()
    set foldlevel=99
  ]])
  require('lspconfig').clangd.setup{}
  -- vim.cmd([[ " PUTTING HERE WORKS
    -- set foldmethod=expr
    -- set foldexpr=nvim_treesitter#foldexpr()
    -- set foldlevel=99
  -- ]])
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end

-- Parsers must be installed manually via :TSInstall
require('nvim-treesitter.configs').setup {
	ensure_installed = {
		"bash",
		"c",
		"cpp",
		"lua",
		"python",
		"rust",
		"html",
		"css",
		"toml",
		"vim",
		-- for `nvim-treesitter/playground`
		"query",
	},
	-- Install languages synchronously (only applied to `ensure_installed`)
	sync_install = false,
	highlight = {
		enable = true, -- false will disable the whole extension
		additional_vim_regex_highlighting = false,
	},
	incremental_selection = {
		enable = true,
		keymaps = {
			-- init_selection = 'gnn',
			init_selection = '<cr>',
			node_incremental = '<tab>',
			scope_incremental = 'grc',
			node_decremental = '<s-tab>',
		},
  },
  indent = {
    enable = true,
  },
}
```
</details>

**Comment by clason** [comment]
Yep, same result: clangd is attached.

**Comment by RayZ0rr** [comment]
Could you provide more info? I tried with latest nvim nightly appimage. But same bug : 
```
NVIM v0.7.0-dev+886-ga88046fe2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az139-954

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
That's my setup as well.

**Comment by RayZ0rr** [comment]
This is a very confusing situation. Mostly same setup but two different results. I will keep this open so that others can also test to reproduce.

**Comment by clason** [comment]
Again: why do you set `syntax enable`?

(This is like that old joke where a man goes to the doctor and says "It hurts when I do *this*" ...)

**Comment by clason** [comment]
(To be very clear: you should NOT set `syntax enable`, especially when using tree-sitter highlighting.)

**Comment by RayZ0rr** [comment]
> (This is like that old joke where a man goes to the doctor and says "It hurts when I do _this_" ...)

I don't understand. This is a nvim setting and on by default. If it should be set again then it should be mentioned somewhere right?

> (To be very clear: you should NOT set syntax enable, especially when using tree-sitter highlighting.)
I didn't see this in the documentation. My bad. But changing the position does work. Moreover, it's surprising you cannot reproduce this

**Comment by clason** [comment]
Because nobody thought that someone insisted on using that command even when it broke their config ;)

(You're executing a command, not setting a variable, so there's no guarantee it's idempotent. It looks to be resetting something at a point where that's harmful.)

**Comment by RayZ0rr** [comment]
> (You're executing a command, not setting a variable, so there's no guarantee it's idempotent. It looks to be resetting something at a point where that's harmful.)

Thank you but I know this much. I am using this issue to figure out what is breaking and how. Atleast to update the docs to explicitly say _not use this command_  or something like that.

> Because nobody thought that someone insisted on using that command even when it broke their config ;)

Because not everybody will know what settings will conflict each other. `syntax enable` is quite common in configs ( at least in the past) and if it breaks treesitter, it should be mentioned.

Also, I want to figure out why your setup works and mine doesnt.

**Comment by RayZ0rr** [comment]
1. Download [nvim.appimage](https://github.com/neovim/neovim/releases/tag/v0.6.1) and make it executable.
2. Use the below minimalrc to open sample cpp.
<details>
<summary>minimalrc.lua</summary>

```lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
      'nvim-treesitter/nvim-treesitter',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

_G.load_config = function()
  vim.cmd [[ syntax enable ]]
  vim.cmd([[ " PROBLEM PART
    set foldmethod=expr
    set foldexpr=nvim_treesitter#foldexpr()
    set foldlevel=99
  ]])
  require('lspconfig').clangd.setup{}
  -- vim.cmd([[ " PUTTING HERE WORKS
    -- set foldmethod=expr
    -- set foldexpr=nvim_treesitter#foldexpr()
    -- set foldlevel=99
  -- ]])
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end

-- Parsers must be installed manually via :TSInstall
require('nvim-treesitter.configs').setup {
	ensure_installed = {
		"bash",
		"c",
		"cpp",
		"lua",
		"python",
		"rust",
		"html",
		"css",
		"toml",
		"vim",
		-- for `nvim-treesitter/playground`
		"query",
	},
	-- Install languages synchronously (only applied to `ensure_installed`)
	sync_install = false,
	highlight = {
		enable = true, -- false will disable the whole extension
		additional_vim_regex_highlighting = false,
	},
	incremental_selection = {
		enable = true,
		keymaps = {
			-- init_selection = 'gnn',
			init_selection = '<cr>',
			node_incremental = '<tab>',
			scope_incremental = 'grc',
			node_decremental = '<s-tab>',
		},
  },
  indent = {
    enable = true,
  },
}
```
</details>

<details>
<summary>sample.cpp</summary>

```cpp
#include <iostream>

int main() {
    std::cout << "Hello World!";
    return 0;
}
```
</details>

`./nvim.appimage -nu minimalrc.lua sample.cpp`

3. Type `:LspInfo`

**Comment by RayZ0rr** [comment]
@clason Could you repeat the above steps again? Maybe 2 times consecutively?

**Comment by RayZ0rr** [comment]
@clason tested the following with 
```
NVIM v0.7.0-dev+895-ga0201b6ed
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
Same problem persists. I think the following steps will 100% reproduce this.

1. Download [nvim.appimage](https://github.com/neovim/neovim/releases) (latest or pre-release) and make it executable.
2. Remove any pre-existing plugins in `/tmp` directory
`rm -rf /tmp/nvim*`
3. Use the below minimalrc to open nvim.
<details>
<summary>minimalrc.lua</summary>

```lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
      'nvim-treesitter/nvim-treesitter',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

_G.load_config = function()
  vim.cmd [[ syntax enable ]]
  vim.cmd([[ " PROBLEM PART
    set foldmethod=expr
    set foldexpr=nvim_treesitter#foldexpr()
    set foldlevel=99
  ]])
  require('lspconfig').clangd.setup{}
  -- vim.cmd([[ " PUTTING HERE WORKS
    -- set foldmethod=expr
    -- set foldexpr=nvim_treesitter#foldexpr()
    -- set foldlevel=99
  -- ]])
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end

-- Parsers must be installed manually via :TSInstall
require('nvim-treesitter.configs').setup {
	ensure_installed = {
		"bash",
		"c",
		"cpp",
		"lua",
		"python",
		"rust",
		"html",
		"css",
		"toml",
		"vim",
		-- for `nvim-treesitter/playground`
		"query",
	},
	-- Install languages synchronously (only applied to `ensure_installed`)
	sync_install = false,
	highlight = {
		enable = true, -- false will disable the whole extension
		additional_vim_regex_highlighting = false,
	},
	incremental_selection = {
		enable = true,
		keymaps = {
			-- init_selection = 'gnn',
			init_selection = '<cr>',
			node_incremental = '<tab>',
			scope_incremental = 'grc',
			node_decremental = '<s-tab>',
		},
  },
  indent = {
    enable = true,
  },
}
```
</details>

`./nvim.appimage -nu minimalrc.lua`

4. Repeat this one more time to completely install treesitter parsers.

`./nvim.appimage -nu minimalrc.lua`

5. Now open a sample cpp file

<details>
<summary>sample.cpp</summary>

```cpp
#include <iostream>

int main() {
    std::cout << "Hello World!";
    return 0;
}
```
</details>

`./nvim.appimage -nu minimalrc.lua sample.cpp`

6. Type `:LspInfo`

**Comment by clason** [comment]
Sorry, I am a bit busy; let me be blunt here: as you still haven't explained why you need to set `syntax enable` (and removing it fixes your issue as you stated), I'm not very motivated to spend much time on this.

In any case, happens here is that `syntax enable` interferes with filetype detection, which both LSP and tree-sitter rely on. So that is better handled in Neovim core rather than worked around here. (But, again, there needs to be a valid use case to merit spending time on it.)

**Comment by RayZ0rr** [comment]
>why you need to set `syntax enable`

`syntax enable` is a nvim setting. If enabling it breaks something then it's obviously a problem. I don't see what other reason should be given.

> syntax enable interferes with filetype detection, which both LSP and tree-sitter rely on

LSP doesn't break because of this. Only in combination with treesitter, explicitly :

```lua
  vim.cmd [[ syntax enable ]]
  vim.cmd([[ " PROBLEM PART
    set foldmethod=expr
    set foldexpr=nvim_treesitter#foldexpr()
    set foldlevel=99
  ]])
```
See [this](https://github.com/neovim/neovim/issues/17083#issuecomment-1012542130) comment.

> So that is better handled in Neovim core rather than worked around here

As I already mentioned in [this](https://github.com/nvim-treesitter/nvim-treesitter/issues/2254#issuecomment-1013504382) comment, which you may have missed, I already raised an issue there.

I am very confused by your repeated questions like this. Let me ask this.
1). Why does this issue tracker exist?
2). If a user finds that a builtin neovim setting breaks something shouldn't they report it here?

I am sorry that I am just an end-user who can only report issues like these but not fix them. But this is the least I can do. However, I see that you think this is not an issue at all. So, I will close.

**Comment by clason** [comment]
> syntax enable is a nvim setting. If enabling it breaks something then it's obviously a problem. I don't see what other reason should be given.

`syntax` is a command (not setting!) that is inherited from Vim; changes in Neovim have made this command obsolete for the vast majority of users, but we are not in the habit of just removing legacy commands.

> I am sorry that I am just an end-user who can only report issues like these but not fix them. But this is the least I can do. However, I see that you think this is not an issue at all. So, I will close.

Well, I am trying to identify what the actual, user-facing, issue is here so that this can be addressed. Such an issue would have a significantly higher priority than dealing with a nasty edge case involving the intersection of the deepest corners of legacy code and two external plugins.

**Comment by RayZ0rr** [comment]
Tried reinstalling nvim with [paq](https://github.com/savq/paq-nvim). Had the same issue. Luckily remembered this issue I had created.

It would be good to add a note in README about this breaking option as it's a common option in many `$MYVIMRC` files.

**Comment by clason** [comment]
> It would be good to add a note in README about this breaking option as it's a common option in many $MYVIMRC files.

But it shouldn't, is (still) the point.

**Comment by RayZ0rr** [comment]
> But it shouldn't, is (still) the point.

Only for treesitter. I haven't had the issue for other plugins including lspconfig. Anyway it may break plugins in the future so it can be either mentioned in README or this issue will serve as the documentation.

Also, Syntax highlighting is enabled by default so one would assume `syntax enable` option to be harmless. But in reality it breaks first file attaching capabilities of tree-sitter and also lspconfig. Note: lspconifg alone works properly and only breaks when used along with tree-sitter.

**Comment by clason** [comment]
Again, `syntax` is **not an option** -- it's a command and not guaranteed to be idempotent. You should not be using it with `Neovim`; that you run into issues only with nvim-treesitter is incidentally (albeit not surprising).

If there is any part of the Neovim documentation that makes it sound like you should be using it, let me know, and I will fix it. But this is _not_ an issue with nvim-treesitter.

**Comment by RayZ0rr** [comment]
> If there is any part of the Neovim documentation that makes it sound like you should be using it, let me know, and I will fix it.

It is available in nvim docs (`:h syntax`). So, obviously, people might use it.

> You should not be using it with `Neovim`; that you run into issues only with nvim-treesitter is incidentally (albeit not surprising).

This is the thing that is not present (is it?) in the documentation and needs fixing.

> But this is _not_ an issue with nvim-treesitter.

Other plugins I had, including lspconfig, were working fine until treesitter was installed. That is why I had opened an issue here.

**Comment by bluebrown** [comment]
I think this is the fact that it is a syntax related option is misleading. I think it doesn't matter. I get errors on different kinds of vm.cmd.

For example, from the neo-tree docs: https://github.com/nvim-neo-tree/neo-tree.nvim

```lua
vim.cmd([[ let g:neo_tree_remove_legacy_commands = 1 ]])
```

![show image of error](https://user-images.githubusercontent.com/39703898/209498018-467cafbf-7137-4864-abcd-a7b7cb6ce3e3.png)

**Comment by clason** [comment]
Duplicate of #3092

**Comment by cosmicac** [comment]
Just for posterity - found this issue since I'm running into something similar on my end. Running `vim.cmd('syntax enable')` at the beginning of my config in conjunction with `nvim-treesitter` seems to prevent my LSPs from attaching.

If I move the `syntax enable` to later anywhere in my config after plugins are loaded (I'm using `lazy.nvim`), then everything works as expected. Or, if I keep `syntax enable` in the beginning, but then move the `treesitter` setup to after the `lspconfig` setup, everything works as expected.

Of course, as pointed out in this thread, you don't actually need `syntax enable` and it seems to cause issues, so what I did was just remove it from my config entirely.

Also [posted about this on Reddit](https://www.reddit.com/r/neovim/comments/1b8r5rf/nvimtreesitter_highlighting_prevents_lsp_client/) (will reference this issue there too for posterity).

**Comment by jaredmyers** [comment]
Thanks for this thread, I burned a better part of a weekend tearing my config apart chasing this.  LSPs were auto attaching until installing `nvim-treesitter` during my transition to `lazy.nvim`.  Removing `syntax enable` did the trick. 💯
