### ISSUE TITLE
Impossible to add a custom parser

### ISSUE THREAD

**Issue by vigoux** [nvim-treesitter/nvim-treesitter#226]
**Describe the bug**
When building and installing manually a custom parser, `nvim-treesitter` does not let you use it easily.

**To Reproduce**
Build a custom parser or get `tree-sitter-viml` without installing it.

Try to use it with the playground.

Nothing happens and the buffer is not attached to.

**Expected behavior**
It should be possible to add your own parser / queries and use nvim-treesitter like with any other parser.

**Additional context**
I think the problem comes from how the module system handles languages.

**Comment by theHamsta** [comment]
Calling this
```lua
    require "nvim-treesitter.parsers".get_parser_configs().clojure = {
        install_info = {
            url = "https://github.com/oakmac/tree-sitter-clojure",
            files = {"src/parser.c"}
        }
    }
```
before `setup` works for me.

**Comment by vigoux** [comment]
That's nice, I also added some things too, pr to come.

**Comment by rabieifk** [comment]
I'm trying to add my own parser to nvim-tree-sitter.
`:TSPlaygroundToggle` does not show anything.

**What I did:**
1) Built a custom parser, `grammar.js` and `highlights.scm`.
No errors running the following snippet,
```
tree-sitter generate
tree-sitter test
```
2) Added the following snippet to `init.vim`

```
local parser_config = require("nvim-treesitter.parsers").get_parser_configs()
parser_config.jdummy = {
  install_info = {
    url = <path_to_repo>,
    files = { "src/parser.c" },
    branch= 'main'
  },
  filetype = "jdummy", -- if filetype does not agrees with parser name
}
```
3) Installed the parsers without any errors, 
`:TSInstall jdummy`
The `jdummy.so` is created in the `/home/farzaneh/.local/share/nvim/plugged/nvim-treesitter/parser` path 
4) `nvim test.jdummy`
5) `:TSPlaygroundToggle` does not show anything for me.

**Am I missing something?**

**Comment by kyazdani42** [comment]
did you add query files ?

**Comment by kyazdani42** [comment]
`set ft=jdummy` ?

**Comment by rabieifk** [comment]
Is that a command?
Where should I run `set ft=jdummy` ?

**Comment by kyazdani42** [comment]
yes it is. `set ft=jdummy` will set the filetype of your buffer to jdummy (`:help filetype`)

**Comment by rabieifk** [comment]
I took these steps:
`nvim test.jdummy`
`:set filetype=jdummy`
`:TSPlaygroundToggle`

an error occurred:

```
Error executing vim.schedule lua callback: Failed to load parser: uv_dlsym: /home/farzaneh/.local/share/nvim/plugged/nvim-treesitter/parser/jdummy.so: undefined symbol: tree_sitter_jdummy
stack traceback:
        [C]: in function '_ts_add_language'
        ...local/share/nvim/runtime/lua/vim/treesitter/language.lua:33: in function 'require_language'
        /usr/local/share/nvim/runtime/lua/vim/treesitter.lua:38: in function '_create_parser'
        /usr/local/share/nvim/runtime/lua/vim/treesitter.lua:93: in function 'get_parser'
        ...d/playground/lua/nvim-treesitter-playground/internal.lua:50: in function 'get_node_at_cursor'
        ...d/playground/lua/nvim-treesitter-playground/internal.lua:413: in function 'fn'
        ...gged/playground/lua/nvim-treesitter-playground/utils.lua:23: in function 'cb'
        vim.lua:291: in function <vim.lua:291>
```
**Do I have to set anything else?**

**Comment by theHamsta** [comment]
`jdummy` must be the name of your grammar in grammar.js. Only then `tree_sitter_jdummy` will end up in the compiled shared object. You can check the symbols in the parser binary with `nm`

**Comment by rabieifk** [comment]
Although the grammar name in `grammar.js` is `jdummy`, 
after running `nm jdummy.so`, I see no `tree_sitter_jdummy`.
**What am I missing?**

```
...
0000000000004020 d __TMC_END__
00000000000017f9 T tree_sitter_json
0000000000002790 r ts_alias_sequences
00000000000027a0 r ts_field_map_entries
...
```
