### ISSUE TITLE
request: Asciidoc support ?

### ISSUE THREAD

**Issue by mnabila** [nvim-treesitter/nvim-treesitter#2263]
**asciidoc**

Whats is asciidoc  ? asciiDoc is a lightweight and semantic markup language primarily designed for writing documentation. The language can be used to produce a variety of presentation-rich output formats, all from content encoded in a concise, human-readable, plain text format.

**Comment by clason** [comment]
Is there a tree-sitter parser for this? If not, there's nothing that can be done here.

**Comment by theHamsta** [comment]
I didn't find a parser for it but we could create a parser wishlist tracking issue. The markdown parser was also a long time wished by a lot of people until some volunteered to implement it.

I didn't know that you can create issues out of tracking issues so easily by just clicking on the TODO Checkboxen.

**Comment by clason** [comment]
added to the tracking issue!

**Comment by cpkio** [comment]
For those interested, I'm slowly developing asciidoc grammar. There's stil a lot to do, but may usable (I use it daily).

plugin: https://github.com/cpkio/nvim-treesitter-asciidoc
grammar: https://github.com/cpkio/tree-sitter-asciidoc

**Comment by CarlosNihelton** [comment]
What about this one?

https://github.com/cathaysia/tree-sitter-asciidoc

**Comment by clason** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/pull/6710

(Note we no longer take requests or host such discussions; if there is a parser that is ready to be used -- we don't accept "experimental parsers" anymore -- just make a PR.)
