### ISSUE TITLE
Avoid non-standard parser installation

### ISSUE THREAD

**Issue by clason** [nvim-treesitter/nvim-treesitter#2300]
As pointed out in https://github.com/nvim-treesitter/nvim-treesitter/issues/2295#issuecomment-1016519273, nvim-treesitter can install parsers in a directory that is not inside its own tree, which can lead to massive confusion. We should 

1. stop doing that -- if the `nvim-treesitter` directory is not writable, just give a descriptive error; if people need to keep it read-only and install parsers somewhere else, they should do this themselves (so they'll always know where their towels are).
2. add the location of the used parsers to `:checkhealth` so we can catch this situation in bug reports.

Note to self: The README should also mention where parsers are installed to.

**Comment by theHamsta** [comment]
The none standard location was introduced for nix installation and other configurations were the plugin directory is read only. Ideally, we should use cache directory for that. Problems with this approach arrive when when nvim-treesitter directory changes from non-writable to writable. A solution would be to allow to specify the install location when the standard is not desired or just also look on non-standard location on install/remove/update.

**Comment by clason** [comment]
+1 on being able to specify a non-default path -- but I'm strongly against using _any_ non-default path automatically. If someone insists on using Nix, they should know how to work around its constraints and not expect any automagic.

**Comment by clason** [comment]
An alternative would be to just use `stdpath('data')/treesitter/parser{-info}` unconditionally. I think I would prefer that to having the parsers be under the plugin directory.

**Comment by clason** [comment]
Already implemented on `main` (nvim-treesitter 1.0).
