### ISSUE TITLE
Support for protobuf

### ISSUE THREAD

**Issue by sainad2222** [nvim-treesitter/nvim-treesitter#2307]
Any plans for adding support for Google's protocol buffer(proto3)?

References: [proto.vim](https://github.com/protocolbuffers/protobuf/blob/3f5fc4df1de8e12b2235c3006593e22d6993c3f5/editors/proto.vim)

**Comment by clason** [comment]
Sure, PR welcome! I've added it to the tracking issue.

**Comment by theHamsta** [comment]
I didn't find tree-sitter-protobuf too useful. It failed to parse even simple documents.

**Comment by sainad2222** [comment]
@theHamsta I'm sorry, which one you are talking about? [This?](https://github.com/mitchellh/tree-sitter-proto)

**Comment by hiberabyss** [comment]
seems no indents for protobuf.
