### ISSUE TITLE
Incremental selection skips one parent on some grammars

### ISSUE THREAD

**Issue by stsewd** [nvim-treesitter/nvim-treesitter#232]
On grammars where there isn't a char that "ends" the node, like indentation base languages (python, rst),
when the incremental selection is started in the last line of the node, calling to next node will skip one node.

**To Reproduce**

Open this file

```python
def foo(a, b):
    # foo
    return a + b

def foo(a, b):
    return a + b
```

Start incremental selection on any of the returns and advance one node, the whole document gets selected instead of selecting the function first.

If you start in a node that doesn't "touch" the last line (the foo comment in the first function) it works as expected. It selects the function first and then the whole document

**Comment by stsewd** [comment]
Looks like this line, but I'm not familiar enough to know how to fix it...

https://github.com/nvim-treesitter/nvim-treesitter/blob/6f9e5bf23f651dc1437d9b43220a4f44a122865f/lua/nvim-treesitter/incremental_selection.lua#L21-L21

**Comment by stsewd** [comment]
Not incrementing one seems to fixed it, but it introduces one "extra step" before selecting the function.

**Comment by vigoux** [comment]
It looks weird to me why this line is the problem, as it is just getting the content of the appropriate line. Will need to dig into that.
