### ISSUE TITLE
The highlight disappears after selecting delete and undo

### ISSUE THREAD

**Issue by zgpio** [nvim-treesitter/nvim-treesitter#235]
**Describe the bug**
The highlight disappears after selecting delete and undo

**To Reproduce**
NOTE: example_config.vim ref to README
1. nvim -u example_config.vim
2. :e example.cpp
3. `vi{`  to select and `d` to delet and `u` to undo
4. See highlight disappears after undo

**Expected behavior**
The highlight  should not disappears.

**Output of `nvim --version`**
```
NVIM v0.5.0-607-g459800db4
```

**Comment by zgpio** [comment]
`di(` and `u` also reproduce this issue.

**Comment by stsewd** [comment]
This is related to https://github.com/nvim-treesitter/nvim-treesitter/issues/78
Reloading the buffer should bring back the color https://github.com/nvim-treesitter/nvim-treesitter#i-experience-weird-highlighting-issues-similar-to-78

**Comment by vigoux** [comment]
Hi, thanks for reporting that. It is actually related to #78 but in a different way. We will keep that issue, just to keep track of the progress we make. The fact that this is related to undo bothers me a bit though.

**Comment by stsewd** [comment]
This also happens when changing branches in a git repo.

**Comment by norcalli** [comment]
If you're using on_lines to trigger incremental highlighting, then you could try a vim.schedule for the inside of the on_lines. In my colorizer, I found that helped to prevent lack of highlighting on undo.

**Comment by meain** [comment]
Could be related, I am also hitting weird highlight issues. Not disappearing, but syntax highlight gets messed up if I have external code formatters used on the buffer or if use a plugin like https://github.com/zirrostig/vim-schlepp.

![screenshot](https://images.meain.io/dump/1599802886.png)

**Comment by stsewd** [comment]
@meain yes, it's related. You can fix it by reloading the buffer https://github.com/nvim-treesitter/nvim-treesitter#i-experience-weird-highlighting-issues-similar-to-78

`:write | edit | TSBufEnable highlight`

**Comment by hwamil** [comment]
Similar issue:
Using smart rename disables highlights to all scopes containing said name

**Comment by yzia2000** [comment]
I found a pr on atom that fixes this issue. https://github.com/atom/atom/pull/18375. If someone is interested they can port it to nvim-treesitter. If not I will start working on it myself

**Comment by stsewd** [comment]
I can't replicate this with the latest version from neovim

**Comment by yzia2000** [comment]
you mean 1080? cuz the problem persists on 1079

**Comment by stsewd** [comment]
1080, yes

**Comment by yzia2000** [comment]
I still face the issue when I open a document and immediately hold `u`.

**Comment by stsewd** [comment]
@yzia2000 do you have a specific example? I have tested with 

```python
def main():
    print("hello")
    {
        'foo': 'bar',
    }
```

and others, but I can't replicate with pressing `u` or deleting using a textobject.

**Comment by yzia2000** [comment]
Oh my god, I just figured it out. I am using `undofile`. Maybe when the first thing I press on opening a file is `u`, it looks into the undofile and that has a weird interaction. Perhaps that deserves a different issue.

**Comment by Philipp-M** [comment]
> Oh my god, I just figured it out. I am using `undofile`. Maybe when the first thing I press on opening a file is `u`, it looks into the undofile and that has a weird interaction. Perhaps that deserves a different issue.

I can actually confirm this issue, I'm also using an undofile and having this issue (but was too lazy to file an issue yet)

**Comment by kyazdani42** [comment]
should this issue be closed in favor of another one then ?

**Comment by yzia2000** [comment]
> should this issue be closed in favor of another one then ?

Yes.
