### ISSUE TITLE
some parsers aren't shown as option to TSInstall 

### ISSUE THREAD

**Issue by dark-ether** [nvim-treesitter/nvim-treesitter#2375]
### Describe the bug

the norg parser doesn't appears as an option for the TSInstall command when i \<C-d\>  and when i tried to install using TSInstall norg i got an error like this one  
```
E5108: Error executing lua .../plugged/nvim-treesitter/lua/nvim-treesitter/install.lua:371: Parser not available for language norg                     
stack traceback:                                                                                                                                       
        [C]: in function 'get_parser_install_info'                                                                                                     
        .../plugged/nvim-treesitter/lua/nvim-treesitter/install.lua:371: in function 'install_lang'                                                    
        .../plugged/nvim-treesitter/lua/nvim-treesitter/install.lua:420: in function 'run'                                                             
        [string ":lua"]:1: in main chunk                                                                                                               
Press ENTER or type command to continue                                      
```
this made me look if any others weren't showing and  these with a check mark(meaning  supported) don't show as option for installing  and i get a similar error to the one written above

- eex
-  Godot Resources (gdresource)
- phpdoc (do note that this one has only experimental support )

### To Reproduce

1. open neovim 
2. run TSInstall norg
3. get the error

### Expected behavior

parsers listed should be installable by the TSInstall command

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v17.3.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - vim            ✓ ✓ . . ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - haskell        ✓ . . . ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.7.0-dev+923-gecec95712
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az139-830

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

### Additional context

i do have tree-sitter cli Installed, when i was testing more hadn't shown when i pressed tab but when i tried installing them i was able to install sucessfully

**Comment by clason** [comment]
Works for me (note that 2. is actually called `godot_resource`). Just to be sure: nvim-treesitter is updated to the latest commit, and you have restarted Neovim after updating before trying this?

**Comment by meanindra** [comment]
**I am also getting same issue.**

![image](https://user-images.githubusercontent.com/36324543/151318701-3e8ec32d-243c-4db8-8d74-082f30f8f07d.png)
## neovim version

> NVIM v0.6.1
> Build type: Release
> LuaJIT 2.1.0-beta3
> Compiled by team+vim@tracker.debian.org
> 
> Features: +acl +iconv +tui
> See ":help feature-compile"
> 
>    system vimrc file: "$VIM/sysinit.vim"
>   fall-back for $VIM: "/usr/share/nvim"
> 
> Run :checkhealth for more info

## :checkhealth nvim-treesitter

> nvim-treesitter: require("nvim-treesitter.health").check()
> ========================================================================
> ## Installation
>   - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
>   - OK: `node` found v16.13.2 (only needed for :TSInstallFromGrammar)
>   - OK: `git` executable found.
>   - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
>     Version: cc (Ubuntu 11.2.0-7ubuntu2) 11.2.0
>   - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

**Comment by clason** [comment]
> I am also getting same issue.

No you're not; the error message is very different (and refers to `nvim-tree`, not `nvim-treesitter`!)

**Comment by meanindra** [comment]
> > I am also getting same issue.
> 
> No you're not; the error message is very different (and refers to `nvim-tree`, not `nvim-treesitter`!)

Okey

**Comment by stsewd** [comment]
@dark-ether what's your nvim-treesitter config?

**Comment by dark-ether** [comment]
this one 
```lua
lua <<EOF
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
    custom_captures = {
      -- Highlight the @foo.bar capture group with the "Identifier" highlight group.
      ["foo.bar"] = "Identifier",
    },
    -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
    -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
    -- Using this option may slow down your editor, and you may see some duplicate highlights.
    -- Instead of true it can also be a list of languages
    additional_vim_regex_highlighting = false,
  },
}
EOF

lua <<EOF
require'nvim-treesitter.configs'.setup {
    indent = {
        enable = true
    }
}
EOF
"end treesitter config

```
but  i tried today and it worked, so i am closing this issue.
