### ISSUE TITLE
Error during compilation, ‘for’ loop initial declarations are only allowed in C99 mode

### ISSUE THREAD

**Issue by kylo252** [nvim-treesitter/nvim-treesitter#2383]
### Describe the bug

The default compiler on RHEL7 (also Centos7) is gcc 4.8.x, which requires specifying the `-std=c99` flag.

<details>
<summary>Full error log</summary>

```console
nvim-treesitter[vim]: Error during compilation
src/scanner.c: In function ‘check_prefix’:
src/scanner.c:221:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (unsigned int i = 0; i < preffix_len; i++) {
   ^
src/scanner.c:221:3: note: use option -std=c99 or -std=gnu99 to compile your code
src/scanner.c: In function ‘try_lex_script_start’:
src/scanner.c:243:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(size_t j = 0; j < 2; j++) {
   ^
src/scanner.c: In function ‘try_lex_keyword’:
src/scanner.c:367:15: error: redeclaration of ‘i’ with no linkage
   for (size_t i = 0; keyword.opt[i] && possible[mandat_len + i]; i++) {
               ^
src/scanner.c:358:10: note: previous declaration of ‘i’ was here
   size_t i;
          ^
src/scanner.c:367:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; keyword.opt[i] && possible[mandat_len + i]; i++) {
   ^
src/scanner.c: In function ‘scope_correct’:
src/scanner.c:378:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; SCOPES[i]; i++) {
   ^
src/scanner.c: In function ‘lex_scope’:
src/scanner.c:395:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; sid[i] && lexer->lookahead; i++) {
     ^
src/scanner.c: In function ‘tree_sitter_vim_external_scanner_scan’:
src/scanner.c:518:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (size_t i = 0; i < s->marker_len; i++) {
     ^
src/scanner.c:575:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (enum TokenType t = TRIE_START; t < TOKENTYPE_NR; t++) {
     ^
```
</details>

### To Reproduce

`:TSInstall vim`

<details>
<summary>minimal_init.lua</summary>

```lua
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
	local path_sep = on_windows and "\\" or "/"
	local result = table.concat({ ... }, path_sep)
	return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			{
				"nvim-treesitter/nvim-treesitter",
				branch = vim.fn.has("nvim-0.6") == 1 and "master" or "0.5-compat",
			},
		},
		config = {
			package_root = package_root,
			compile_path = compile_path,
		},
	})
end

_G.load_config = function()
	local status_ok, treesitter_configs = pcall(require, "nvim-treesitter.configs")
	if not status_ok then
		error("unable to load treesitter")
		return
	end

	local opts = {}

	treesitter_configs.setup(opts)
end

if vim.fn.isdirectory(install_path) == 0 then
	vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
	load_plugins()
	require("packer").sync()
	vim.cmd([[autocmd User PackerComplete ++once lua load_config()]])
else
	load_plugins()
	require("packer").sync()
	_G.load_config()
end
```

</details>

### Expected behavior

NA

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :    TSInstall)
  - OK: `node` found v15.14.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime    ABI.

## Parser/Features H L F I J

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.7.0-dev+948-gc5ac04331
Build type: Release
LuaJIT 2.1.0-beta3
...
```

**Comment by theHamsta** [comment]
GCC 4.8.2 is fairly ancient. Please use a compiler that used C99 as default. You can change the compiler that nvim-treesitter uses via `require'nvim-treesitter.install'.compilers = {"your_favorite_c_compiler"}`. We don't specify standards during our compilation step since we want to keep the installation command simple.

You can also overwrite all parser entries to use our makefile like the norg parsers that requires C++14 (see #1795). The makefile will automatically add the c99 flag.

**Comment by kylo252** [comment]
@theHamsta, I think you might've missed that this is the default, and _only_ gcc version available on those distros. I specifically wanted to open this issue to show the benefit of using the makefile approach instead :)

**Comment by theHamsta** [comment]
https://gcc.gnu.org/gcc-4.8/ -> This release series is no longer supported.

CentOS is infamous for old software. But you might as well also use an as old version of Vim.

**Comment by kylo252** [comment]
- gcc 4.8.5 came out in 2015 and not 1995, but it was still using `-std=gnu89` as default
- https://github.com/neovim/neovim/wiki/Building-Neovim#build-prerequisites

**Comment by djvolz** [comment]
I'm seeing this as well. Red Hat Linux 7, Oracle Linux 7, and CentOS 7 all face this and are still widely used. They don't have much in the way of alternatives to gcc 4.8.5 either. As @kylo252 points out, gcc 4.8.5 isn't all that old.

**Comment by djvolz** [comment]
I've been using a nix package manager version of clang++ as a work around on these OSes for a while similar to what is mentioned in #1717. This has been working great, however after a recent nvim-treesitter update I'm seeing this C99 issue again.

```require 'nvim-treesitter.install'.compilers = { "clang++" } ```

**Comment by benjamin051000** [comment]
On RHEL7, I have manually installed a new version of gcc and added it to my PATH. I still need to `require 'nvim-treesitter.install'.compilers = { "gcc" }`, but when I have that (oddly enough) it works.

**Comment by scutwengxinqian** [comment]
> On RHEL7, I have manually installed a new version of gcc and added it to my PATH. I still need to `require 'nvim-treesitter.install'.compilers = { "gcc" }`, but when I have that (oddly enough) it works.

After I get a new version of gcc, setting environment CC=gcc fixed it for me. I think it is because of the way compiler is selected.
https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/install.lua has
`M.compilers = { vim.fn.getenv "CC", "cc", "gcc", "clang", "cl", "zig" }`
When I didn't set $CC, it used **cc** which is an old compiler. After I see the CC env, it uses what's specified in the env var.

**Comment by benjamin051000** [comment]
As I mentioned in #1717, I think specifying the absolute path also works. See that comment.
