### ISSUE TITLE
Anchors are not respected when predicates are used

### ISSUE THREAD

**Issue by uyha** [nvim-treesitter/nvim-treesitter#2390]
### Describe the bug

When a query uses both anchors and predicates, the query result differs with a similar query with which only uses anchors

### To Reproduce

1. Install the CMake tree-sitter parser
2. Have a file with the following content
```cmake
list(GET l 1 var)
```
3. Open the query editor
4. Look at the result of the following query
```query
(normal_command
  (identifier) @function.builtin
  . (argument) @constant
  (argument) @variable .
)
```
5. Then look at the result of the following query
```query
(normal_command
  (identifier) @function.builtin
  . (argument) @constant
  (argument) @variable .
  (#match? @function.builtin "\\c^(list)$")
)
```

### Expected behavior

Both queries should give out same result but they don't, the query without the predicate gives the expected result for the anchored values while the query with the predicate doesn't.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.4 (714bfd47a744ab44b904375c177a24c0614ef49c) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.13.2 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - cmake          ✓ . ✓ . . 
  - svelte         ✓ . ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by uy@Uy-Personal-Laptop

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/uy/.local/opt/neovim/share/nvim"

Run :checkhealth for more info
```

**Comment by theHamsta** [comment]
Can you reproduce this using tree-sitter CLI only without Neovim involved?

**Comment by uyha** [comment]
i'm not sure how to using the tree-sitter CLI for this

**Comment by uyha** [comment]
looks like it is the case with the `tree-sitter` cli also

**Comment by uyha** [comment]
Reported tree-sitter/tree-sitter#1622

**Comment by theHamsta** [comment]
There's no logic in Neovim that interprets the query language, only the predicates are implemented as a yes/no functions and as long as we iterate correctly over the results, the behavior is fully controlled by the tree-sitter C library.

**Comment by uyha** [comment]
I figured out what's wrong. It seems like the anchor for the last element has to be at the end of the query also, so the predicate can't be at the end.
