### ISSUE TITLE
Get error when starting nvim: query: invalid node type at position 1707 

### ISSUE THREAD

**Issue by voldikss** [nvim-treesitter/nvim-treesitter#240]
**Describe the bug**
After 8021a769edb542a0d00c1f5765a519361874aa56, every time when I start nvim, I got the following error message from nvim-treesitter.

```vim
Error detected while processing /home/voldikss/.cache/nvim/plugged/nvim-treesitter/plugin/nvim-treesitter.vim:
line   20:
E5108: Error executing lua /usr/local/share/nvim/runtime/lua/vim/treesitter.lua:151: query: invalid node type at position 1707
```

**To Reproduce**
1. Use the lastest build nvim

2. Use the simplest config file 
```vim
set rtp+=~/.cache/nvim/plugged/nvim-treesitter

lua <<EOF
require'nvim-treesitter.configs'.setup {
    highlight = {
      enable = true,                    -- false will disable the whole extension
      disable = { "c", "rust" },        -- list of language that will be disabled
      custom_captures = {               -- mapping of user defined captures to highlight groups
        -- ["foo.bar"] = "Identifier"   -- highlight own capture @foo.bar with highlight group "Identifier", see :h nvim-treesitter-query-extensions
      },
    }
}
EOF
```
3. start nvim using `nvim -u mini_vimrc`

4. See error, as described above.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
  - ERROR: Failed to run healthcheck for "nvim_treesitter" plugin. Exception:
    function health#check[21]..health#nvim_treesitter#check, line 1
    Vim(lua):E5108: Error executing lua /usr/local/share/nvim/runtime/lua/vim/treesitter.lua:151: query: invalid node type at position 1707

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-615-g5f5bd576e
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/mnt/repo/neovim/build/config -I/mnt/repo/neovim/src -I/mnt/repo/neovim/.deps/usr/include -I/usr/include -I/mnt/repo/neovim/build/src/nvim/auto -I/mnt/repo/neovim/build/include
Compiled by root@legion

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

Also, `/usr/local/share/nvim/runtime/lua/vim/treesitter.lua` is the identical with neovim official repo.

**Additional context**
Screenshot
![image](https://user-images.githubusercontent.com/20282795/88819490-a0e6ea00-d1f2-11ea-8ea9-2e5ba0c18730.png)

**Comment by stsewd** [comment]
I think you need to reinstall some parsers (probably `:TSInstall rst`)

Maybe we should have something like an update command.

**Comment by voldikss** [comment]
Wow, I forgot to try reinstalling the plug-in. Thank you for the quick response, I'll try it.

**Comment by Shougo** [comment]
Yes.  Plugin re-install works for me.

**Comment by voldikss** [comment]
Also works for me, thanks!
