### ISSUE TITLE
nvim-treesitter and tree-sitter disagree about query results

### ISSUE THREAD

**Issue by uyha** [nvim-treesitter/nvim-treesitter#2438]
### Describe the bug

I'm trying to write a query for CMake but encountered an inconsitency for highlighting between `nvim-treesitter` and `tree-sitter`.

### To Reproduce

1. Install the `cmake` parser
2. Have a cmake file named *set.cmake* with the following content
```cmake
set(a value PARENT_SCOPE)
```
3. Modify the file *queries/cmake/highlights.scm* to contain only the following query
```query
(normal_command
  (identifier) @function.builtin
  (#match? @function.builtin "^(set)$")
  . (argument) @variable
  . (argument)
  (
    (argument) @constant
    (#any-of? @variable "PARENT_SCOPE")
  )? .
)
```

### Expected behavior

`nvim-treesitter` should highlight the text correctly according to the capture output of
```bash
tree-sitter query .../nvim-treesitter/queries/cmake/highlights.scm set.cmake
```
which is
```
set.cmake
  pattern: 0
    capture: 0 - function.builtin, start: (0, 0), end: (0, 3), text: `set`
    capture: 1 - variable, start: (0, 4), end: (0, 5), text: `a`
    capture: 2 - constant, start: (0, 8), end: (0, 20), text: `PARENT_SCOPE`
```
However, `nvim-treesitter` doesn't highlight any of the above captures.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.4 (714bfd47a744ab44b904375c177a24c0614ef49c) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.13.2 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - cmake          ✓ . ✓ . . 
  - svelte         ✓ . ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by uy@Uy-Personal-Laptop

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/uy/.local/opt/neovim/share/nvim"

Run :checkhealth for more info
```

### Additional context

Version of `tree-sitter` cli used is `tree-sitter 0.20.4 (714bfd47a744ab44b904375c177a24c0614ef49c)`

**Comment by clason** [comment]
What does TSPlayground show?

**Comment by uyha** [comment]
![image](https://user-images.githubusercontent.com/8091245/152603605-e76f8c08-4624-4487-bb35-753fb22b29c9.png)

**Comment by uyha** [comment]
`:TSHighlightCapturesUnderCursor` shows `No highlight groups found` for all nodes

**Comment by theHamsta** [comment]
Could you move out the `any-of?` predicate out of `@constant`? or use  `(#any-of? @constant "PARENT_SCOPE")` I'm not very clear what the `#any-of` inside the `?` should mean

**Comment by uyha** [comment]
@theHamsta oh yeah, I am a dumbass, for what i want to do, it should be `@constant` instead of `@variable` for the `#any-of?` predicate. However, for the wrong query, there still seems to be a discrepancy between `nvim-treesitter` and `tree-sitter` when it comes to the query result.

> I'm not very clear what the #any-of inside the ? should mean

I'm assuming you mean `#any-of?` inside the `()`. Putting the predicate inside the pair of parentheses together with `(argument) @constant` make the anchor that follows to mean that that `@constant` is the last `@constant`, if I put it outside, the anchor wouldn't have the same effect.

With this cmake snippet
```cmake
set(a a a PARENT_SCOPE)
```
```query
(normal_command
  (identifier) @function.builtin
  (#match? @function.builtin "^(set)$")
  . (argument) @variable
  . (argument)
  (
    (argument) @constant
    (#any-of? @variable "PARENT_SCOPE")
  )? .
)
```
gives the following query result 
```
pattern: 0
  capture: 0 - function.builtin, start: (0, 0), end: (0, 3), text: `set`
  capture: 1 - variable, start: (0, 4), end: (0, 5), text: `a`
  capture: 2 - constant, start: (0, 23), end: (0, 35), text: `PARENT_SCOPE`
```
While this query
```query
(normal_command
  (identifier) @function.builtin
  (#match? @function.builtin "^(set)$")
  . (argument) @variable
  . (argument)
  (
    (argument) @constant
  )? .
  (#any-of? @variable "PARENT_SCOPE")
)
```
gives

```
pattern: 0
  capture: 0 - function.builtin, start: (0, 0), end: (0, 3), text: `set`
  capture: 1 - variable, start: (0, 4), end: (0, 5), text: `a`
  capture: 2 - constant, start: (0, 8), end: (0, 9), text: `a`
pattern: 0
  capture: 0 - function.builtin, start: (0, 0), end: (0, 3), text: `set`
  capture: 1 - variable, start: (0, 4), end: (0, 5), text: `a`
  capture: 2 - constant, start: (0, 10), end: (0, 22), text: `PARENT_SCOPE`
```

**Comment by uyha** [comment]
I ran the experiment wrong, `tree-sitter` doesn't have `#any-of?`, that's why I got the result which I thought was the correct one. Which is also why `nvim-treesitter` and `tree-sitter` disagree about the query result.
