### ISSUE TITLE
"nvim-treesitter requires a more recent Neovim nightly version!" despite running Neovim nightly

### ISSUE THREAD

**Issue by zakrywilson** [nvim-treesitter/nvim-treesitter#2482]
### Describe the bug

- [x] I just now downloaded Neovim nightly (`v0.7.0-dev+1018-g8215c0594`) [1]
- [x] Packer updated plugin to `3eb4dff`
- [ ] I cannot run `:TSUpdate` because the previous command fails (`Not an editor command: TSUpdate`)
- [ ] I read the [vim.treesitter.query](https://github.com/nvim-treesitter/nvim-treesitter#i-get-module-vimtreesitterquery-not-found) section, but I am running the nightly version

Error message when loading nvim:
```
Error detected while processing /Users/redacted/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ...cker/start/nvim-treesitter/lua/nvim-treesitter/query.lua:2: module 'vim.treesitter.query' not found:
        no field package.preload['vim.treesitter.query']
        no file './vim/treesitter/query.lua'
        no file '/Users/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/vim/treesitter/query.lua'
        no file '/usr/local/share/lua/5.1/vim/treesitter/query.lua'
        no file '/usr/local/share/lua/5.1/vim/treesitter/query/init.lua'
        no file '/Users/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vim/treesitter/query.lua'
        no file '/Users/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/vim/treesitter/query/init.lua'
        no file './vim/treesitter/query.so'
        no file '/usr/local/lib/lua/5.1/vim/treesitter/query.so'
        no file '/Users/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/vim/treesitter/query.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './vim.so'
        no file '/usr/local/lib/lua/5.1/vim.so'
        no file '/Users/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/vim.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        ...cker/start/nvim-treesitter/lua/nvim-treesitter/query.lua:2: in main chunk
        [C]: in function 'require'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:3: in main chunk
        [C]: in function 'require'
        /Users/redacted/.config/nvim/init.lua:124: in main chunk
Error detected while processing /Users/redacted/.local/share/nvim/site/pack/packer/start/nvim-treesitter/plugin/nvim-treesitter.vim:
line   15:
E5108: Error executing lua ...ack/packer/start/nvim-treesitter/lua/nvim-treesitter.lua:2: nvim-treesitter requires a more recent Neovim nightly version!
stack traceback:
        [C]: in function 'error'
        ...ack/packer/start/nvim-treesitter/lua/nvim-treesitter.lua:2: in main chunk
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
```

### To Reproduce

1. Set up Packer to install nvim-treesitter:
```lua
return require("packer").startup(function(use)
  use({ "wbthomason/packer.nvim" })
  use { 'nvim-treesitter/nvim-treesitter', run = ':TSUpdate' }
end)
```
2. Run `:PackerInstall`
3. _Packer will fail to install nvim-treesitter_

I am running macOS Monterey (Version 12.2).

### Expected behavior

I would expect that since I am running the latest version of Neovim (`v0.7.0-dev+1018-g8215c0594`) and the latest version of nvim-treesitter (`3eb4dff`), Packer would be able to install nvim-treesitter without any errors.

### Output of `:checkhealth nvim-treesitter`

```markdown
health#nvim_treesitter#check
========================================================================
  - ERROR: Failed to run healthcheck for "nvim_treesitter" plugin. Exception:
    function health#check[21]..health#nvim_treesitter#check, line 1
    Vim(lua):E5108: Error executing lua ...ker/start/nvim-treesitter/lua/nvim-treesitter/health.lua:4: loop or previous error loading module 'nvim-treesitter.query'
    stack traceback:
    [C]: in function 'require'
    ...ker/start/nvim-treesitter/lua/nvim-treesitter/health.lua:4: in main chunk
    [C]: in function 'require'
    [string ":lua"]:1: in main chunk
```

### Output of `nvim --version`

```text
nvim --version
NVIM v0.7.0-dev+1018-g8215c0594
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1644123757189.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"
```

### Additional context

I had this working until I switched from vim-plug to packer as part of moving my config over from init.vim to init.lua. I've already successfully set up nvim-treesitter on Linux machines. This only became a problem on my Mac.

This also isn't my first attempt to get nvim-treesitter working on my Mac: I ran into these same problems a couple weeks ago, but figured there was probably a bug in either Neovim or nvim-treesitter, so I waited to see if it sorted itself out. So today, I downloaded the most recent versions of everything, and tried it again, and no luck.

The most confusing thing to me is that I get an error message stating that I need a newer version of Neovim, but that's what I have.

-----

Thanks for the help!

**Comment by clason** [comment]
The error messages point towards a problem with your Neovim installation. How did you set it up?

**Comment by theHamsta** [comment]
The message is in particular triggered by https://github.com/nvim-treesitter/nvim-treesitter/blob/3cfbde4db05dc9f3f38fcee212849799bb6f2e54/lua/nvim-treesitter.lua#L1-L3  So probably you have an out-dated Lua runtime. This may also happen during an own build of Neovim as the `minimum_cmake_version` that Neovim uses is quite old and seems to miss sometimes some of required install steps after a build. Or you just have also an older Neovim installation somewere.

**Comment by clason** [comment]
I suspect the build didn't install properly (maybe a mixup of homebrew and self-built versions?)

**Comment by zakrywilson** [comment]
#### Installation

I installed Neovim on my Mac by downloading `nvim-macos.tar.gz` from their [Github releases page](https://github.com/neovim/neovim/releases/nightly). From there, followed the simple steps on that page to run it. I made it executable and moved it into `~/.local/bin`… nothing too fancy. I don't suspect this is a softlink or aliasing issue where I would be running a different version, since I've double-checked that, and I have the same errors when using the full path.

#### Lua runtime

I also updated Lua. I can't remember what I was on, but it doesn't appear to have fixed anything. I tried reinstalling Packer and its plugins, and I have the same errors:

```bash
→ lua
Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio
> print(_VERSION)
Lua 5.4
```

#### Neovim runtime

`:echo $VIMRUNTIME` --> `/usr/local/share/nvim/runtime`

It took me a minute, but this is the wrong runtime. I did some cleaning up on my system:
- There was an old version of Neovim installed by brew, but I don't think it was affecting anything
- I had some older backup versions of Neovim 0.5, as well

#### Solution

Since I have Neovim installed at `~/.local/bin/nvim-osx64/bin/nvim`, I updated my `$VIMRUNTIME` to be `~/.local/bin/nvim-osx64/share/nvim/runtime` and that fixed the issue.

Thanks for your help!
