### ISSUE TITLE
WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)

### ISSUE THREAD

**Issue by CharlesARoy** [nvim-treesitter/nvim-treesitter#2484]
### Describe the bug

When I launch nvim, treesitter tries to install 14 modules but can't seem to complete the installation. (On the first install it successfully installed 69/83 modules). 

I've tried pretty much every combination of uninstalling and reinstalling nvim and treesitter, running TSUpdate, PackerClean, PackerSync, PackerCompile, and etc

This is the output of checkhealth:
![image](https://user-images.githubusercontent.com/46253001/152732316-2f771697-ecf7-45e8-87a5-4e65285e3745.png)

These are the sorts of errors I'm getting when I launch nvim:
![image](https://user-images.githubusercontent.com/46253001/152732624-a11d35ee-2780-4b12-8de1-086d4c20e586.png)

### To Reproduce

I'm testing out Chris@Machine's Nvim config which can be cloned with:
`git clone https://github.com/LunarVim/Neovim-from-scratch.git ~/.config/nvim`

More information here: https://github.com/LunarVim/Neovim-from-scratch

### Expected behavior

I expect nvim to launch without any errors from TreeSitter.

### Output of `:checkhealth nvim-treesitter`

```markdown
See above screenshot.
```

### Output of `nvim --version`

```text
NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az87-780

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```
```


### Additional context

I am working on a fairly old version of Ubuntu without admin privileges.

```
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

Also, with an old version of git:
`git version 1.9.1`

**Comment by theHamsta** [comment]
The error tells you that you use a very old compiler (gcc 4.8) that does not use C99 as a default standard. Are you able to use a newer compiler?

**Comment by CharlesARoy** [comment]
It seems like it would be quite a project to install another version of GCC from the source (I don't have sudo privileges in this environment).

From the warning, it seems like the missing modules only affect ":TSInstallFromGrammar". I'm just getting started with TreeSitter so I'm not sure if I'll need that command. Is there an easy way to disable the attempt to install the other packages?

**Comment by clason** [comment]
No, a compiler is required. It's only the tree-sitter CLI (and `npm`) that are generally not needed.

**Comment by theHamsta** [comment]
Can you try the following snippet?
```lua
for _, config in pairs(require("nvim-treesitter.parsers").get_parser_configs()) do
  config.install_info.use_makefile = true
  config.install_info.cxx_standard = 'c++14'
end
```
This should enable you old compiler to use `-std=c99`

**Comment by CharlesARoy** [comment]
@theHamsta thanks so much for the help! After adding that snippet to the top of my treesitter.lua file, 11 of the 14 modules were installed. The final 3 appear to not like the c++14 command:

![image](https://user-images.githubusercontent.com/46253001/152881734-780ad123-adac-4d47-9876-26786df96663.png)

**Comment by theHamsta** [comment]
Try `-std=c++11` or `-std=c++98`

**Comment by CharlesARoy** [comment]
Sorry, trying to follow but I'm a complete beginner. 

Changing this line in the snippet you shared:
`config.install_info.cxx_standard = 'c++14'`
to:
`config.install_info.cxx_standard = 'c++11'`
or to:
`config.install_info.cxx_standard = 'c++98'`

seems to have no effect (the errors are the same regarding "unrecognized command line option -std=c++14"). 

When you say to try those flags, are you suggesting that I manually run those commands with the adjusted flags (rather than relying on Packer to run them for me)?

If that's right, where should I run them? In this directory?:
`~/.local/share/nvim/site/pack/packer/start/nvim-treesitter`

**Comment by theHamsta** [comment]
Actually, I meant in the above snippet as it is supposed to change this parameter: https://github.com/theHamsta/nvim-treesitter/blob/a0074622353c2308aaeb0851cab0fac387b3d439/scripts/compile_parsers.makefile#L6 Feel also free to remove `$(CXXFLAGS)` from that file by `-std=c++11` directly

**Comment by theHamsta** [comment]
Sorry, I forgot that setting the standard will only work with #2465 . Can you try to change `-std=c++14` manually in the makefile?

**Comment by CharlesARoy** [comment]
Ok, almost there, I changed `-std=c++14` to `-std=c++11` manually in the makefile and 2/3 remaining packages were installed. The error for the final package looks like:

![image](https://user-images.githubusercontent.com/46253001/152886714-b5cbd11b-f1e9-4f25-ae0f-4e7e11a58e03.png)

I also tried `-std=c++98` but that gave me a longer error that said I should use `-std=c++11`.

**Comment by theHamsta** [comment]
Yes, norg is the only parser that requires c++14 you won't be able to install it

**Comment by clason** [comment]
Also, it should be pointed out that blindly installing all parsers is an anti-pattern; you should only and explicitly install parsers for languages you are actually working with.

**Comment by theHamsta** [comment]
I think this is fixed now. Maybe we can put this "old compiler can use makefile" trick to the trouble shooting seciton

**Comment by CharlesARoy** [comment]
@theHamsta on last question on this.

Currently, every time I load nvim, treesitter tries to download and install the norg compiler and then produces the error I showed in the most recent screenshot above. Is there a way to stop nvim/treesitter from doing this? I'm using Packer for plugins.

**Comment by clason** [comment]
make sure `nvim-treesitter` is setup before calling `:TSUpdate` or `:TSInstall`

**Comment by CharlesARoy** [comment]
Thanks @clason !

Hopefully this is the last follow-up. Do you know what the proper syntax is to use ensure_installed or ignore_install with Packer? I emulated what was described in [this discussion](https://github.com/nvim-treesitter/nvim-treesitter/discussions/2406) but that didn't work.

E.g. with this code:
![image](https://user-images.githubusercontent.com/46253001/153668981-fb9dd754-a8c6-4e4b-8552-aef8aeb1d68c.png)

 I get this error:
![image](https://user-images.githubusercontent.com/46253001/153669122-3a9c164f-8942-4302-b619-586b22768aaf.png)

**Comment by clason** [comment]
I think such usage questions belong on https://matrix.to/#/#nvim-treesitter:matrix.org 

(But briefly, that looks garbled. Stick to the instructions from the README, and try not to add too many complications -- like config via packer -- at once.)

**Comment by CharlesARoy** [comment]
For anyone else with a similar issue, Christian Chiarulli's treesitter config helped me figure this out. I just added "norg" to ignore_install. 

https://github.com/ChristianChiarulli/nvim/blob/master/lua/user/treesitter.lua
