### ISSUE TITLE
nvim-treesitter[teal]: Error during "tree-sitter generate" node:events:498

### ISSUE THREAD

**Issue by fleongg** [nvim-treesitter/nvim-treesitter#2493]
### Describe the bug

I installed neovim and node on Mac through homebrew and when I launch nvim on iterm2, "[nvim-treesitter] [0/4] Downloading..." shows up and the download fails very soon. I am not sure if that is caused by the Apple m1 chip,

### To Reproduce

1. Install nvim and node with homebrew
2. git clone https://github.com/LunarVim/[Neovim-from-scratch](https://github.com/LunarVim/Neovim-from-scratch) or [ayamir](https://github.com/ayamir)/[nvimdots](https://github.com/ayamir/nvimdots)
3. Input nvim +PackerSync on terminal

I tried git clone other nvim configs but the problem persists, it seems to be the problem of nvim-treesitter with neovim on m1 Mac?

### Expected behavior

[nvim-treesitter] [0/4] Downloading...
[nvim-treesitter] [0/4] Downloading...
[nvim-treesitter] [0/4] Downloading...
[nvim-treesitter] [0/4] Downloading...
[nvim-treesitter] [0/4] Creating temporary directory
[nvim-treesitter] [0/4] Extracting...
[nvim-treesitter] [0/4] Generating source files from grammar.js...
nvim-treesitter[teal]: Error during "tree-sitter generate"
node:events:498
      throw er; // Unhandled 'error' event
      ^
Error: spawn /Users/username/.config/yarn/global/node_modules/tree-sitter-cli/tree-s
itter EACCES
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn /Users/username/.config/yarn/global/node_modules/tree-sitter-cli/t
ree-sitter',
  path: '/Users/username/.config/yarn/global/node_modules/tree-sitter-cli/tree-sitte
r',
  spawnargs: [ 'generate' ]
}
Node.js v17.4.0

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found (unknown version) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.4.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.0.0 (clang-1300.0.29.30)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - ledger         ‚úì . ‚úì ‚úì ‚úì 
  - ql             ‚úì ‚úì . ‚úì ‚úì 
  - gomod          ‚úì . . . ‚úì 
  - pascal         ‚úì ‚úì ‚úì ‚úì ‚úì 
  - gowork         ‚úì . . . ‚úì 
  - graphql        ‚úì . . ‚úì ‚úì 
  - lua            ‚úì ‚úì ‚úì ‚úì ‚úì 
  - jsdoc          ‚úì . . . . 
  - perl           ‚úì . . . . 
  - query          ‚úì ‚úì ‚úì ‚úì ‚úì 
  - fish           ‚úì ‚úì ‚úì ‚úì ‚úì 
  - php            ‚úì ‚úì ‚úì ‚úì ‚úì 
  - java           ‚úì ‚úì . ‚úì ‚úì 
  - kotlin         ‚úì ‚úì ‚úì . ‚úì 
  - turtle         ‚úì ‚úì ‚úì ‚úì ‚úì 
  - julia          ‚úì ‚úì ‚úì ‚úì ‚úì 
  - regex          ‚úì . . . . 
  - css            ‚úì . ‚úì ‚úì ‚úì 
  - svelte         ‚úì . ‚úì ‚úì ‚úì 
  - scss           ‚úì . . ‚úì . 
  - erlang         . . . . . 
  - elixir         ‚úì ‚úì ‚úì ‚úì ‚úì 
  - surface        ‚úì . ‚úì ‚úì ‚úì 
  - bibtex         ‚úì . ‚úì ‚úì . 
  - eex            ‚úì . . . ‚úì 
  - zig            ‚úì . ‚úì ‚úì ‚úì 
  - heex           ‚úì ‚úì ‚úì ‚úì ‚úì 
  - ocaml          ‚úì ‚úì ‚úì . ‚úì 
  - cmake          ‚úì . ‚úì . . 
  - python         ‚úì ‚úì ‚úì ‚úì ‚úì 
  - ocaml_interface‚úì ‚úì ‚úì . ‚úì 
  - json5          ‚úì . . . ‚úì 
  - gdscript       ‚úì ‚úì . ‚úì ‚úì 
  - hjson          ‚úì ‚úì ‚úì ‚úì ‚úì 
  - c_sharp        ‚úì ‚úì ‚úì . ‚úì 
  - bash           ‚úì ‚úì ‚úì . ‚úì 
  - cpp            ‚úì ‚úì ‚úì ‚úì ‚úì 
  - html           ‚úì ‚úì ‚úì ‚úì ‚úì 
  - javascript     ‚úì ‚úì ‚úì ‚úì ‚úì 
  - tsx            ‚úì ‚úì ‚úì ‚úì ‚úì 
  - llvm           ‚úì . . . . 
  - json           ‚úì ‚úì ‚úì ‚úì . 
  - vim            ‚úì ‚úì . . ‚úì 
  - c              ‚úì ‚úì ‚úì ‚úì ‚úì 
  - supercollider  ‚úì ‚úì ‚úì ‚úì ‚úì 
  - latex          ‚úì . ‚úì . ‚úì 
  - rasi           ‚úì ‚úì ‚úì ‚úì . 
  - make           ‚úì . . . ‚úì 
  - prisma         ‚úì . . . . 
  - http           ‚úì . . . ‚úì 
  - tlaplus        ‚úì ‚úì ‚úì . ‚úì 
  - hocon          ‚úì . . . ‚úì 
  - norg           . . . . . 
  - go             ‚úì ‚úì ‚úì ‚úì ‚úì 
  - pioasm         ‚úì . . . ‚úì 
  - toml           ‚úì ‚úì ‚úì ‚úì ‚úì 
  - beancount      ‚úì . ‚úì . . 
  - r              ‚úì ‚úì . ‚úì . 
  - vala           ‚úì . . . . 
  - sparql         ‚úì ‚úì ‚úì ‚úì ‚úì 
  - pug            ‚úì . . . ‚úì 
  - comment        ‚úì . . . . 
  - fennel         ‚úì ‚úì . . ‚úì 
  - vue            ‚úì . ‚úì ‚úì ‚úì 
  - rust           ‚úì ‚úì ‚úì ‚úì ‚úì 
  - cuda           ‚úì ‚úì ‚úì ‚úì ‚úì 
  - jsonc          ‚úì ‚úì ‚úì ‚úì ‚úì 
  - dot            ‚úì . . . ‚úì 
  - ruby           ‚úì ‚úì ‚úì ‚úì ‚úì 
  - dockerfile     ‚úì . . . ‚úì 
  - yaml           ‚úì ‚úì ‚úì ‚úì ‚úì 
  - yang           ‚úì . ‚úì . . 
  - glsl           ‚úì ‚úì ‚úì ‚úì ‚úì 
  - typescript     ‚úì ‚úì ‚úì ‚úì ‚úì 
  - ninja          ‚úì . ‚úì ‚úì . 
  - commonlisp     ‚úì ‚úì ‚úì . . 
  - scala          ‚úì . ‚úì . ‚úì 
  - nix            ‚úì ‚úì ‚úì . ‚úì 
  - clojure        ‚úì ‚úì ‚úì . ‚úì 
  - hcl            ‚úì . ‚úì ‚úì ‚úì 
  - dart           ‚úì ‚úì . ‚úì ‚úì 
  - glimmer        ‚úì . . . . 
  - fusion         ‚úì ‚úì ‚úì ‚úì . 
  - rst            ‚úì ‚úì . . ‚úì 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.6.1/share/nvim"

Run :checkhealth for more info
```

### Additional context

macos Monterey
Version 12.1
Chip Apple M1

**Comment by theHamsta** [comment]
`EACCES` seems to be an access problem. Is the current user able to execute programs installed via the global node installation?

**Comment by fleongg** [comment]
I do have and do not really know how other nom programs, but I tried sudo nvim on the terminal and the error does not pop up. However, probably caused by gfw, it shows: `nvim-treesitter[teal]: Error during download, please verify your internet connection`.
This is awkward since I usually uses a proxy to use brew and git commands, and it works. But I do not know why it fails and looking for a solution. Thank you very much @theHamsta !

**Comment by theHamsta** [comment]
You can try to install the tree-sitter CLI by downloading it form the release page instead of running it via it's npm installation

**Comment by Shinolr** [comment]
same issue, M1 & use proxy to cross gfw. Noticed that the 4 parsers were downloaded successfully, but can't finish the folowing steps somehow.
<img width="319" alt="image" src="https://user-images.githubusercontent.com/20644119/155974410-80b494c9-0933-4642-94a7-a8cbde18491b.png">

**Comment by Shinolr** [comment]
test on another Intel chip Mac, also faild on this 4 parser too.

**Comment by Shinolr** [comment]
solved by set global node version. tried set shell/local node version, neither works.

**Comment by fleongg** [comment]
> solved by set global node version. tried set shell/local node version, neither works.

this also solved my problem, thanks a lot!

**Comment by jakDev003** [comment]
How do I set the global node version?

**Comment by Shinolr** [comment]
> How do I set the global node version?

I used nodenv as my node version manager that can set node version for global by `nodenv global 17.3.0`. Not sure if other version managers have the same idea of handling this topic.
