### ISSUE TITLE
Support defining forward and backward movements

### ISSUE THREAD

**Issue by stsewd** [nvim-treesitter/nvim-treesitter#250]
This would allow users to make use of `]]`, [[`, `]m`, `[m`, `[M`, and friends.

Right now plugins implement this using a search with regular expressions.

Maybe we can re-use the textobjects.scm file for these queries, or have a movements.scm file. The queries will define something like

```
@function
@function.start
@function.end
```

If only function is given the start would be taken from the beginning of the first node, and the end would be taken from the end of the last node inside that.

This will need to search the node matching the query from the cursor position to the end of the file for forward movements and from the cursor position till the start of the file for backward movements.

**Comment by theHamsta** [comment]
I already have some code necessary for this feature in #218 (textobject at point). I should finish the swap feature (only thing missing is that it should not swap with next node but next textobject).

**Comment by stsewd** [comment]
This is already implemented :)
