### ISSUE TITLE
Track latest commit from parsers

### ISSUE THREAD

**Issue by stsewd** [nvim-treesitter/nvim-treesitter#251]
This will avoid having to update all parsers with `:TSUpdate`, and only update the ones that have changed. We can make use of `git ls-remote <repo> HEAD` to query the latest commit, and compare that with the one saved from when the parser was installed.

**Comment by vigoux** [comment]
That would be an awesome feature. But I think that what we should also do is pin the parsers versions.

**Comment by vigoux** [comment]
Closing this in favor of #292 .
