### ISSUE TITLE
Lua broken: query.lua invalid node at position 1

### ISSUE THREAD

**Issue by reportaman** [nvim-treesitter/nvim-treesitter#2519]
### Describe the bug

.lua files and lua code blocks inside inside vim script files always result in a error condition being hit.

For now I have disabled lua in tree sitter config, that works ok for .lua files. But! the lua code blocks inside vim script still result in same problem. Even if I have let ``g:vimsyn_embed= 'mpPr'``, which lacks ``l`` for lua.

https://user-images.githubusercontent.com/71736629/153726979-2dcf7eb4-dc49-43c6-8ebe-ffce3d79504f.mov

### To Reproduce

Use latest nightlies of nvim, and nvim-treesitter

### Expected behavior

This error should not occur

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.4 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.4.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.0.0 (clang-1300.0.29.30)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - bibtex         ✓ . ✓ ✓ . 
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - ledger         ✓ . ✓ ✓ ✓ 
  - supercollider  ✓ ✓ ✓ ✓ ✓ 
  - vue            ✓ . ✓ ✓ ✓ 
  - erlang         . . . . . 
  - hocon          ✓ . . . ✓ 
  - tlaplus        ✓ ✓ ✓ . ✓ 
  - llvm           ✓ . . . . 
  - http           ✓ . . . ✓ 
  - eex            ✓ . . . ✓ 
  - rasi           ✓ ✓ ✓ ✓ . 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - norg           . . . . . 
  - sparql         ✓ ✓ ✓ ✓ ✓ 
  - ql             ✓ ✓ . ✓ ✓ 
  - glimmer        ✓ . . . . 
  - clojure        ✓ ✓ ✓ . ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - dot            ✓ . . . ✓ 
  - cmake          ✓ . ✓ . . 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - pug            ✓ . . . ✓ 
  - gowork         ✓ . . . ✓ 
  - make           ✓ . . . ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - lua            x ✓ ✓ ✓ ✓ 
  - commonlisp     ✓ ✓ ✓ . . 
  - bash           ✓ ✓ ✓ . ✓ 
  - dockerfile     ✓ . . . ✓ 
  - ocaml_interface✓ ✓ ✓ . ✓ 
  - scala          ✓ . ✓ . ✓ 
  - graphql        ✓ . . ✓ ✓ 
  - prisma         ✓ . . . . 
  - hjson          ✓ ✓ ✓ ✓ ✓ 
  - pioasm         ✓ . . . ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - json5          ✓ . . . ✓ 
  - glsl           ✓ ✓ ✓ ✓ ✓ 
  - scss           ✓ . . ✓ . 
  - yang           ✓ . ✓ . . 
  - zig            ✓ . ✓ ✓ ✓ 
  - latex          ✓ . ✓ . ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - beancount      ✓ . ✓ . . 
  - r              ✓ ✓ . ✓ . 
  - rst            ✓ ✓ . . ✓ 
  - gomod          ✓ . . . ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - svelte         ✓ . ✓ ✓ ✓ 
  - ocaml          ✓ ✓ ✓ . ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - ninja          ✓ . ✓ ✓ . 
  - gdscript       ✓ ✓ . ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - teal           ✓ ✓ ✓ ✓ ✓ 
  - pascal         ✓ ✓ ✓ ✓ ✓ 
  - regex          ✓ . . . . 
  - comment        ✓ . . . . 
  - jsdoc          ✓ . . . . 
  - css            ✓ . ✓ ✓ ✓ 
  - heex           ✓ ✓ ✓ ✓ ✓ 
  - julia          ✓ ✓ ✓ ✓ ✓ 
  - vala           ✓ . . . . 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - elixir         ✓ ✓ ✓ ✓ ✓ 
  - dart           ✓ ✓ . ✓ ✓ 
  - perl           ✓ . . . . 
  - godot_resource ✓ ✓ ✓ . . 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - kotlin         ✓ ✓ ✓ . ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - nix            ✓ ✓ ✓ . ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - devicetree     ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - vim            ✓ ✓ . . ✓ 
  - cuda           ✓ ✓ ✓ ✓ ✓ 
  - fusion         ✓ ✓ ✓ ✓ . 
  - fennel         ✓ ✓ . . ✓ 
  - hcl            ✓ . ✓ ✓ ✓ 
  - surface        ✓ . ✓ ✓ ✓ 
  - ocamllex       ✓ . . . ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: lua(highlights): ...-f89f4b1/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 1
    lua(highlights) is concatenated from the following files:
    | [ERROR]:"/Users/reportaman/.vim/plugged/material_plus.nvim/queries/lua/highlights.scm", failed to load: ...-f89f4b1/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 1
    |    [OK]:"/Users/reportaman/.vim/plugged/nvim-treesitter/queries/lua/highlights.scm"

```
```


### Output of `nvim --version`

```text
NVIM v0.7.0-dev+1070-gf89f4b1e1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by reportaman@macos.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-f89f4b1/share/nvim"

Run :checkhealth for more info

```
```


### Additional context

_No response_

**Comment by theHamsta** [comment]
This is the culprit `/Users/reportaman/.vim/plugged/material_plus.nvim/queries/lua/highlights.scm"` Try to de-install the color scheme

**Comment by reportaman** [comment]
@theHamsta Worked! Uninstalled that colorscheme, and things are good now. Thanks a lot.

**Comment by reportaman** [comment]
+ @ray-x

**Comment by ray-x** [comment]
Yes, seems the highlight.scm conflicts with the new version of treesitter. It was updated.

**Comment by dotjairo** [comment]
Like @fcnaud mentioned in glepnir/zephyr-nvim#29, this happens with the them `zephyr-nvim` colorscheme too. It's enough that the theme is installed, it doesn't have to be in use to cause the issue.

Notice the `[ERROR]` with `.../zephyr-nvim/after/queries/lua/highlights.scm` from `:checkhealth nvim-treesitter`:

```
## The following errors have been detected:
- ERROR: lua(highlights): ...R57w/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 2349
     lua(highlights) is concatenated from the following files:
     |    [OK]:"/home/USERNAME/.local/share/nvim/site/pack/packer/start/nvim-treesitter/queries/lua/highlights.scm"
     | [ERROR]:"/home/USERNAME/.local/share/nvim/site/pack/packer/start/zephyr-nvim/after/queries/lua/highlights.scm", failed to load: ...R57w/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 16
```

**Comment by stoddart** [comment]
> 

Somewhat unrelated, but how did you get the perl module installed? Been having trouble with that today.

**Comment by poetaman** [comment]
@stoddart  ``:TSInstall perl``

**Comment by stoddart** [comment]
> @stoddart `:TSInstall perl`

Thanks, I thought that would clear it up too, but it doesn't. It tells me it's already available, but that the `Neovim::Ext` CPAN module is not installed. Running `cpan -i Neovim::Ext` fails. Running `sudo cpanm -n Neovim::Ext` also fails. 

I'm at a loss as to what I need to do to fix this.

**Comment by poetaman** [comment]
@stoddart Not sure what machine you have, these steps worked for me on macOS 13.1 ARM64:

```
brew reinstall cpanminus
sudo cpanm -n Eval::Safe
sudo cpanm -n MsgPack::Raw
sudo cpanm -n Neovim::Ext
sudo cpanm -n App::cpanminus
```

**Comment by stoddart** [comment]
> @stoddart Not sure what machine you have, these steps worked for me on macOS 13.1 ARM64:
> 
> ```
> brew reinstall cpanminus
> sudo cpanm -n Eval::Safe
> sudo cpanm -n MsgPack::Raw
> sudo cpanm -n Neovim::Ext
> sudo cpanm -n App::cpanminus
> ```
> 
> Then try `:checkhealth provider` from `nvim`.

Thanks so much! The error message in Neovim does not even specify which modules are needed, and I couldn't find that information anywhere, so this is much appreciated.

**Comment by poetaman** [comment]
@stoddart You are welcome! Yeah, I saw three problems: 1) information wasn't sufficient and I had to open the docs, 2) ``sudo cpanm -n Neovim::Ext`` wasn't sufficient as it either did not install other dependencies or not know about them (``App::cpanminus``). Adding @jacquesg as he seems to be the maintainer for https://github.com/jacquesg/p5-Neovim-Ext and might want to improve the instructions.

**Comment by clason** [comment]
> Thanks, I thought that would clear it up too, but it doesn't. It tells me it's already available, but that the Neovim::Ext CPAN module is not installed. Running cpan -i Neovim::Ext fails. Running sudo cpanm -n Neovim::Ext also fails.

Those are completely different things. The Perl provider (`Neovim::Ext`) has _nothing_ to do with nvim-treesitter; it's only for writing remote plugins in Perl.

**Comment by stoddart** [comment]
> > Thanks, I thought that would clear it up too, but it doesn't. It tells me it's already available, but that the Neovim::Ext CPAN module is not installed. Running cpan -i Neovim::Ext fails. Running sudo cpanm -n Neovim::Ext also fails.
> 
> Those are completely different things. The Perl provider (`Neovim::Ext`) has _nothing_ to do with nvim-treesitter; it's only for writing remote plugins in Perl.

I understand that, but the error message is lacking in information.

**Comment by jacquesg** [comment]
Please don't `sudo cpanm`... You are creating a whole heap of new problems. Homebrew is designed to execute in a non-privileged context.

Installing perl modules is well documented: http://www.cpan.org/modules/INSTALL.html

Having rerun this myself:

```
cpanm Neovim::Ext  
--> Working on Neovim::Ext                                                                                                                                                                                
Fetching http://www.cpan.org/authors/id/J/JA/JACQUESG/Neovim-Ext-0.05.tar.gz ... OK                                                                                                                       
==> Found dependencies: IO::Async, Eval::Safe, Class::Accessor, MsgPack::Raw                                                                                                                              
--> Working on IO::Async                                                                                                                                                                                  
Fetching http://www.cpan.org/authors/id/P/PE/PEVANS/IO-Async-0.802.tar.gz ... OK                                                                                                                          
Configuring IO-Async-0.802 ... OK                                                                                                                                                                         
==> Found dependencies: Future, Test::Metrics::Any, Test::Refcount, Future::Utils, Test::Identity, Test::Future::IO::Impl, Struct::Dumb                                                                   
--> Working on Future                                                                                                                                                                                     
Fetching http://www.cpan.org/authors/id/P/PE/PEVANS/Future-0.49.tar.gz ... OK                                                                                                                             
Configuring Future-0.49 ... OK                                                                                                                                                                            
==> Found dependencies: Test::Identity, Test::Refcount                                                                                                                                                    
--> Working on Test::Identity                                                                                                                                                                             
Fetching http://www.cpan.org/authors/id/P/PE/PEVANS/Test-Identity-0.01.tar.gz ... OK                                                                                                                      
Configuring Test-Identity-0.01 ... OK                                                                                                                                                                     
Building and testing Test-Identity-0.01 ... OK                                                                                                                                                            
Successfully installed Test-Identity-0.01
...
Building and testing Neovim-Ext-0.05 ... FAIL
! Installing Neovim::Ext failed. See /home/jacquesg/.cpanm/work/1673814833.608744/build.log for details. Retry with --force to force install it.
15 distributions installed
```

I did notice that there is a compatibility problem with neovim 0.8+, similar to https://github.com/jacquesg/p5-Neovim-Ext/issues/4

I believe I've fixed it, waiting for CI builds to complete and do some final testing before pushing a new release to cpan.

**Comment by stoddart** [comment]
I understand that about Homebrew since I use it myself. But the problem is that running that unprivileged fails.

**Comment by stoddart** [comment]
The :checkhealth advice in Neovim leads users to believe that running it unprivileged will install the module:

> ## Perl provider (optional)
  - INFO: perl executable: /opt/homebrew/bin/perl
  - WARNING: Module "Neovim::Ext" is out-of-date. Installed: 0.05, latest: 0.06
    - ADVICE:
      - Run in shell: cpanm -n Neovim::Ext
      
But I'm afraid that fails.

**Comment by stoddart** [comment]
> Please don't `sudo cpanm`... You are creating a whole heap of new problems. Homebrew is designed to execute in a non-privileged context.
> 
> Installing perl modules is well documented: http://www.cpan.org/modules/INSTALL.html
> 
> Having rerun this myself:
> 
> ```
> cpanm Neovim::Ext  
> --> Working on Neovim::Ext                                                                                                                                                                                
> Fetching http://www.cpan.org/authors/id/J/JA/JACQUESG/Neovim-Ext-0.05.tar.gz ... OK                                                                                                                       
> ==> Found dependencies: IO::Async, Eval::Safe, Class::Accessor, MsgPack::Raw                                                                                                                              
> --> Working on IO::Async                                                                                                                                                                                  
> Fetching http://www.cpan.org/authors/id/P/PE/PEVANS/IO-Async-0.802.tar.gz ... OK                                                                                                                          
> Configuring IO-Async-0.802 ... OK                                                                                                                                                                         
> ==> Found dependencies: Future, Test::Metrics::Any, Test::Refcount, Future::Utils, Test::Identity, Test::Future::IO::Impl, Struct::Dumb                                                                   
> --> Working on Future                                                                                                                                                                                     
> Fetching http://www.cpan.org/authors/id/P/PE/PEVANS/Future-0.49.tar.gz ... OK                                                                                                                             
> Configuring Future-0.49 ... OK                                                                                                                                                                            
> ==> Found dependencies: Test::Identity, Test::Refcount                                                                                                                                                    
> --> Working on Test::Identity                                                                                                                                                                             
> Fetching http://www.cpan.org/authors/id/P/PE/PEVANS/Test-Identity-0.01.tar.gz ... OK                                                                                                                      
> Configuring Test-Identity-0.01 ... OK                                                                                                                                                                     
> Building and testing Test-Identity-0.01 ... OK                                                                                                                                                            
> Successfully installed Test-Identity-0.01
> ...
> Building and testing Neovim-Ext-0.05 ... FAIL
> ! Installing Neovim::Ext failed. See /home/jacquesg/.cpanm/work/1673814833.608744/build.log for details. Retry with --force to force install it.
> 15 distributions installed
> ```
> 
> I did notice that there is a compatibility problem with neovim 0.8+, similar to [jacquesg/p5-Neovim-Ext#4](https://github.com/jacquesg/p5-Neovim-Ext/issues/4)
> 
> I believe I've fixed it, waiting for CI builds to complete and do some final testing before pushing a new release to cpan.

I just wanted to add that I understand why users shouldn't run `sudo cpanm` and I try hard to avoid doing it but in this case it was the only way to load them. What do you suggest Neovim users should do in order to undo that and set it up correctly?

**Comment by jacquesg** [comment]
The latest version installs for me:

```
cpanm -f Neovim::Ext
--> Working on Neovim::Ext
Fetching http://www.cpan.org/authors/id/J/JA/JACQUESG/Neovim-Ext-0.06.tar.gz ... OK
Configuring Neovim-Ext-0.06 ... OK
Building and testing Neovim-Ext-0.06 ... OK
Successfully reinstalled Neovim-Ext-0.06
1 distribution installed
```

Normally if there is an error, it will tell you about the log file. Posting its contents is helpful, merely saying it fail is not.

**Comment by jacquesg** [comment]
`:checkhealth` provides you with all the information required, i.e. in my case after installing the latest version

![image](https://user-images.githubusercontent.com/3534453/212642707-28ad4a34-2658-4766-ac7d-bd1e1f8f8d56.png)

Your situation:
```
Run in shell: cpanm -n Neovim::Ext
```

**Comment by ALENTL** [comment]
![image](https://user-images.githubusercontent.com/82425585/216593771-afa14ed5-a264-4120-8f6c-2b17b905759e.png)
Please explain how to resolve this issue.
