### ISSUE TITLE
Not loaded treesitter

### ISSUE THREAD

**Issue by Harshit-Chitkara** [nvim-treesitter/nvim-treesitter#2522]
## Bug
Whenever I open a file I see "Not loaded treesitter" and it doesn't work. Something like this:
![image](https://user-images.githubusercontent.com/72375487/153745246-cddd19db-c41a-4a40-84bc-16af174b2c09.png)

### To Reproduce

I've tried :TSUpdate many times and reinstalling the plugin but all in vain.

### Output of `:checkhealth nvim-treesitter`

Eveything seems to perfect.
![image](https://user-images.githubusercontent.com/72375487/153745413-2e323d2b-63c1-45dc-98ff-c73adcdc4810.png)

### Output of `nvim --version`

Neovim version: Latest Stable as of now i.e. 0.6.1.
![image](https://user-images.githubusercontent.com/72375487/153748776-db1119ee-7228-4275-a1f0-4247a07f2721.png)

## My Setup:
OS: Arch Linux on WSL 2
tar, curl & git are installed.
C Compiler: GCC.
This is my treesitter config:
![image](https://user-images.githubusercontent.com/72375487/153745491-2a1fc0f0-8890-4038-878a-32dcbdb43510.png)

**Comment by clason** [comment]
Please don't add code as screenshot; copy and paste the (relevant!) parts into a code block in the issue description itself. In particular, you need to share the full config, not just an arbitrary excerpt.

"Not loaded treesitter" is definitely not an error message coming from `nvim-treesitter`, and the variable `g:loaded_nvim_treesitter` is used internally to ensure the plugin is not loaded twice, so you shouldn't check it in your own config (especially not the way you are doing). Just remove the first four lines.
