### ISSUE TITLE
Indent in comment is broken for TS and JS files

### ISSUE THREAD

**Issue by ajitid** [nvim-treesitter/nvim-treesitter#2544]
### Describe the bug

Try typing in text and hit enter in a multiline comment. You would see an issue similar to this:

![153990427-6335faf3-c713-4e92-a258-71a6b255254d](https://user-images.githubusercontent.com/26769888/154752428-4a74246a-88dd-4eb8-a117-427a46ea5c05.gif)

I must mention that it works fine in a typescript react (.tsx) file:

![anim-rg](https://user-images.githubusercontent.com/26769888/154752656-fb4c0354-6aa2-4cb8-a5bd-0fbb46394872.gif)

### To Reproduce

Use this config

```lua
local ts = require'nvim-treesitter.configs'

ts.setup {
  ensure_installed = "maintained",
  highlight = {
    enable = true,
  },
}
```

and open a JavaScript or a TypeScript file. Try to do a multiline comment. You would notice upon hitting enter after typing text in the first line `*` (star) doesn't align for the next one.

### Expected behavior

Should behave either:
- like what it behaves in a TypeScript React (.tsx) file, or
- the way stock Vim works

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v14.18.3 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 10.3.0-1ubuntu1) 10.3.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - hocon          ✓ . . . ✓ 
  - fennel         ✓ ✓ . . ✓ 
  - llvm           ✓ . . . . 
  - surface        ✓ . ✓ ✓ ✓ 
  - glimmer        ✓ . . . . 
  - vue            ✓ . ✓ ✓ ✓ 
  - regex          ✓ . . . . 
  - rasi           ✓ ✓ ✓ ✓ . 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - glsl           ✓ ✓ ✓ ✓ ✓ 
  - gleam          ✓ ✓ ✓ ✓ ✓ 
  - latex          ✓ . ✓ . ✓ 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - vala           ✓ . . . . 
  - rst            ✓ ✓ . . ✓ 
  - perl           ✓ . . . . 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - eex            ✓ . . . ✓ 
  - fusion         ✓ ✓ ✓ ✓ . 
  - pascal         ✓ ✓ ✓ ✓ ✓ 
  - supercollider  ✓ ✓ ✓ ✓ ✓ 
  - yang           ✓ . ✓ . . 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - dockerfile     ✓ . . . ✓ 
  - tlaplus        ✓ ✓ ✓ . ✓ 
  - elixir         ✓ ✓ ✓ ✓ ✓ 
  - dot            ✓ . . . ✓ 
  - graphql        ✓ . . ✓ ✓ 
  - cmake          ✓ . ✓ . . 
  - beancount      ✓ . ✓ . . 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - r              ✓ ✓ . ✓ . 
  - scala          ✓ . ✓ . ✓ 
  - ninja          ✓ . ✓ ✓ . 
  - lalrpop        ✓ ✓ . . . 
  - norg           . . . . . 
  - css            ✓ . ✓ ✓ ✓ 
  - make           ✓ . . . ✓ 
  - prisma         ✓ . . . . 
  - gowork         ✓ . . . ✓ 
  - http           ✓ . . . ✓ 
  - hjson          ✓ ✓ ✓ ✓ ✓ 
  - pioasm         ✓ . . . ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - json5          ✓ . . . ✓ 
  - vim            ✓ ✓ . . ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - ocaml          ✓ ✓ ✓ . ✓ 
  - clojure        ✓ ✓ ✓ . ✓ 
  - zig            ✓ . ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - comment        ✓ . . . . 
  - bibtex         ✓ . ✓ ✓ . 
  - jsdoc          ✓ . . . . 
  - svelte         ✓ . ✓ ✓ ✓ 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - hcl            ✓ . ✓ ✓ ✓ 
  - sparql         ✓ ✓ ✓ ✓ ✓ 
  - gdscript       ✓ ✓ . ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - heex           ✓ ✓ ✓ ✓ ✓ 
  - nix            ✓ ✓ ✓ . ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - pug            ✓ . . . ✓ 
  - julia          ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - scss           ✓ . . ✓ . 
  - ql             ✓ ✓ . ✓ ✓ 
  - erlang         . . . . . 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - dart           ✓ ✓ . ✓ ✓ 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - gomod          ✓ . . . ✓ 
  - ledger         ✓ . ✓ ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - kotlin         ✓ ✓ ✓ . ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - cuda           ✓ ✓ ✓ ✓ ✓ 
  - commonlisp     ✓ ✓ ✓ . . 
  - ocaml_interface✓ ✓ ✓ . ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.7.0-dev+1109-gfaeff49cb
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Additional context

Options I tried:
- [Treesitter's indent option](https://github.com/nvim-treesitter/nvim-treesitter#indentation) — this breaks multiline comment indent in .tsx file too
- The PR which resolves #2515 — it didn't help

There's a related discussion [happened on reddit](https://old.reddit.com/r/neovim/comments/ss8mp7/any_idea_why_when_writing_jsst_multline_comment/) (informal, not with neovim core members)

**Comment by steelsojka** [comment]
To add on to this, I'm also experiencing this without having the indentation module enabled. I traced it to the creation of the parser in neovim. I think this is a neovim/treesitter integration bug. I haven't dug into what is causing it exactly in neovim.

**Comment by everett1992** [comment]
This issue is still reproducible with nvim 8 and latest treesitter.

I have examples of how the indentation is wrong with and without indent enabled,  and demonstrate that neovim's out of the box indentation is fine in #3830

**Comment by apazzolini** [comment]
On nightly neovim with the latest nvim-treesitter, I'm getting way better JS/TS comment indentation by using @theHamsta's changes from the commit above. Instead of forking, it worked by just creating in my config

`nvim/after/queries/ecma/indents.scm` with contents:
```
; extends

(comment) @auto
```

**Comment by davidosomething** [comment]
@theHamsta fix did not work for me in the case of O/o continuation

E.g. make a new `jsfile.js` and enter:

```js
/**
 */
```

        - From the end of /**, press "o" to open a new line.
        - EXPECTED: ` * ` with spaces before and after
        - OBSERVED: `* ` no preceding space (so the value of s1 in 'comments' was no respected.)

**Comment by rgcv** [comment]
I'm still afflicted by this, even with an override to `queries/ecma/indents.scm`.  My config might be a bit more complex, so I'm guess it may come in conflict.  I found adjusting the `shiftwidth` explicitly is interfering with the indent size for me, i.e., the spacing I get before the asterisk `*` in new lines is directly proportional to my set `shiftwidth`.

I do have a plugin that heuristically sets `shiftwidth`, `expandtab` and co. (`vim-sleuth`), but other than that, not sure what else could be fiddling with this.

**Comment by amaanq** [comment]
> I'm still afflicted by this, even with an override to `queries/ecma/indents.scm`. My config might be a bit more complex, so I'm guessing there may be some more conflicts hidden away. I found adjusting the `shiftwidth` explicitly is interfering with the indent size for me, i.e., the spacing I get before the asterisk `*` in new lines is directly proportional to my set `shiftwidth`.
> 
> I do have a plugin that heuristically sets `shiftwidth`, `expandtab` and co. (`vim-sleuth`), but other than that, not sure what else could be fiddling with this.

Try out #4669

**Comment by rgcv** [comment]
> Try out https://github.com/nvim-treesitter/nvim-treesitter/pull/4669

Didn't do it for me :\ Config aside, I'm not on nightly right now, so that might not help either.  I'll try the patch with a simpler config, akin to the one you shared

```
$ nvim --version
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by raph5** [comment]
`(comment) @indent.auto` in queries/ecma/indents.scm solved the issue for me
