### ISSUE TITLE
Is it possible to achieve different colors for arguments and local variables? Java parser

### ISSUE THREAD

**Issue by ChrisAmelia** [nvim-treesitter/nvim-treesitter#255]
Regarding to config, I've pasted what is defined in the readme's setup.

<code>

## java parser healthcheck
  - OK: java parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for java
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

</code>

##  colorscheme `sublimemonokai`

-  `TSBufEnable highlight`

![image](https://user-images.githubusercontent.com/16366403/89209487-abbcc880-d5be-11ea-88c2-cfd60a908c75.png)

- `TSBufDisable highlight`

![image](https://user-images.githubusercontent.com/16366403/89209651-01917080-d5bf-11ea-85ec-e6da85192929.png)

The differences are:

1. Class name `Main` from non-italic to italic.
1. Return type `void` from non-italic to italic.
1. Type variable `String` from non-italic to italic.
1. Highlight of function name `main`.
1. Highlight of brackets.

## colorscheme `default`

-  `TSBufEnable highlight`

![image](https://user-images.githubusercontent.com/16366403/89210414-5b466a80-d5c0-11ea-9d8b-b121d162468f.png)

- `TSBufDisable highlight`

![image](https://user-images.githubusercontent.com/16366403/89210485-7a44fc80-d5c0-11ea-8c75-ee64391adcdf.png)

The differences are:

1. Highlight of class name `Main`.
1. Highlight of keyword `static`.
1. Highlight of return type `void`.
1. Highlight of function name `main`.
1. Highlight of type variable `String[]`.
1. Highlight of argument `args`.
1. Highlights of local type variable `String` and variable name `element`.
1. Highlight of  brackets.

**Comment by theHamsta** [comment]
The highlights for argument is TSParameter you can configure it freely and locals currently have no highlight.

**Comment by stsewd** [comment]
Some symbols may not be highlighted after enabling the feature on the fly, you can try forcing the buffer to reload `:e!` or redraw (Ctrl-L), or just give it a try by enabling it by default :) this is how a java file looks like for me

![Screenshot from 2020-08-03 17-39-04](https://user-images.githubusercontent.com/4975310/89233886-3cd87300-d5b0-11ea-9d9a-feff073b2c18.png)

You can modify the highlight groups defined in https://github.com/nvim-treesitter/nvim-treesitter/blob/master/plugin/nvim-treesitter.vim#L25-L75 as you like (like marking some elements with italics).

**Comment by ChrisAmelia** [comment]
I've tried a few but not all of them work.

```vim
hi TSMethod      guifg=#0066FF " Only one working
hi TSParameter   guifg=red
hi TSProperty    guifg=pink
hi TSField       guifg=forestgreen
hi TSConstructor guifg=#66FF22 
```

This is the result:

![image](https://user-images.githubusercontent.com/16366403/89304617-edf11300-d66d-11ea-9576-8bad601df6c4.png)

Is there something I'm missing?

**Comment by TravonteD** [comment]
I've looked into the field groups that you are trying to use and it looks like they don't necessarily line up.

TSMethod -> works.
TSParameter -> works.
TSProperty -> not used.
TSField -> not used seems to be mapped TSType instead.
TSConstructor -> not used also mapped to TSType.

We can update the queries to better match the expected highlight groups, or at least add documentation so that users know which to use.

**Comment by kyazdani42** [comment]
@vigoux should we close this in favor of #81 ?

**Comment by p00f** [comment]
> Is there something I'm missing?

surely, because atleast TSParamter works for me
