### ISSUE TITLE
HTML closing tag with php

### ISSUE THREAD

**Issue by dvandyy** [nvim-treesitter/nvim-treesitter#2565]
### Describe the highlighting problem

I ran into some issues with highlighting in Php combined with Html. Everytime when I write Php in Html element, closing tag is not highlighted.

### Example snippet that causes the problem

```
<div>
  <p><?php /* some php code */ ?></p>
</div>
```

### Tree-sitter parsing result

<img width="1408" alt="Screenshot 2022-02-22 at 23 47 23" src="https://user-images.githubusercontent.com/40064599/155232516-2fd782a7-ddd0-45bd-aece-d2da59fb8ecd.png">

### Example screenshot

<img width="424" alt="Screenshot 2022-02-22 at 23 48 04" src="https://user-images.githubusercontent.com/40064599/155232589-b0af6843-87e7-40a1-8ab8-87235f19e207.png">

### Output of `:checkhealth nvim-treesitter`

```markdown
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.4 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.13.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.0.0 (clang-1300.0.29.30)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.
```

### Output of `nvim --version`

```text
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey
```

### Additional context

I created issue here: https://github.com/tree-sitter/tree-sitter-php/issues/123 
But there was said its a issue with Neovim. Really don't know if its my bad but i can't figure this out. Am I missing something?
Its also mentioned here: https://github.com/tree-sitter/tree-sitter-php/issues/119

**Comment by thesandybridge** [comment]
Has anyone found a work around for this?

**Comment by CalebDW** [comment]
> Has anyone found a work around for this?

Especially since `@combined` is listed in the [injection captures](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#injections).

**Comment by thesandybridge** [comment]
I placed the following in `.config/nvim/queries/php` and it seemed to fix this specific issue, but it is not injecting javascript highlighting in a `<script>` tag, nor does php inside an attribute work.

```
; inherits: php

(
 (text) @content
 @html
 @combined
)
```
