### ISSUE TITLE
Indent getting reset while typing

### ISSUE THREAD

**Issue by npezza93** [nvim-treesitter/nvim-treesitter#2566]
### Describe the bug

Take the snippet:
```ruby
def foo
  if bar
end
```
Up to this point everything works great. But once you chain a method call to bar, it dedents. Running this in the playground, i think it is because after typing the `.` the node gets parsed as a call and then after typing another character to finish the method name it gets reparsed as an if and then dedents. 

https://user-images.githubusercontent.com/5059927/155231638-c1d9a234-241d-4d48-9d08-fed0519a44dd.mov

### To Reproduce

1. Type the following into ruby file:
```
def foo
  if bar
end
```
2. Type a `.` after bar

### Expected behavior

That nothing changes. 

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.1 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v14.17.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.0.0 (clang-1300.0.29.3)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - json           ✓ ✓ ✓ ✓ . 
  - markdown       ✓ . ✓ . ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - regex          ✓ . . . . 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - vim            ✓ ✓ . . ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - comment        ✓ . . . . 
  - css            ✓ . ✓ ✓ ✓ 
  - hcl            ✓ . ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - scss           ✓ . . ✓ . 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - embedded_template✓ . . . ✓ 
  - dockerfile     ✓ . . . ✓ 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - python         x x ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: python(highlights): ...im/0.6.1/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 5423
    python(highlights) is concatenated from the following files:
    | [ERROR]:"/Users/nick/.local/share/nvim/plugged/nvim-treesitter/queries/python/highlights.scm", failed to load: ...im/0.6.1/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 5423
  - ERROR: python(locals): ...im/0.6.1/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 2418
    python(locals) is concatenated from the following files:
    | [ERROR]:"/Users/nick/.local/share/nvim/plugged/nvim-treesitter/queries/python/locals.scm", failed to load: ...im/0.6.1/share/nvim/runtime/lua/vim/treesitter/query.lua:161: query: invalid node type at position 2418
```

### Output of `nvim --version`

```text
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.6.1/share/nvim"

Run :checkhealth for more info
```

**Comment by theHamsta** [comment]
It has nothing to do with the `.`. The `.` just triggers re-indent (`:h indentkeys`). For me it only dedent when the end is missing (which it would also do when starting the new line after `def`. We would need to add a `indent` onto the incomplete function definition.

**Comment by npezza93** [comment]
Ahh yep, you're totally right. This is a configuration thing on my end. Sorry about that and appreciate the info!

**Comment by theHamsta** [comment]
But it's not good that it would set indent to 0 after typing
```
def thing
```

**Comment by hahuang65** [comment]
> Ahh yep, you're totally right. This is a configuration thing on my end. Sorry about that and appreciate the info!

Were you able to fix this by changing configuration? If so, what did you do? I'm running into this as well and it's not clear from this ticket whether there is a fix or workaround.

**Comment by babelfish** [comment]
I also frequently get inexplicable dedents and would like to know if there's some configuration that can fix it.

**Comment by npezza93** [comment]
It's caused by https://github.com/vim-ruby/vim-ruby/blob/master/indent/ruby.vim#L41 so you'll want to change this to not include the dot or anything you don't want.

**Comment by hahuang65** [comment]
> It's caused by https://github.com/vim-ruby/vim-ruby/blob/master/indent/ruby.vim#L41 so you'll want to change this to not include the dot or anything you don't want.

How might you set that in nvim without changing the source code of `vim-ruby`?

**Comment by babelfish** [comment]
Thanks for that, I'd been considering removing treesitter for a while now because I waste so much time fixing indentation due to this.

**Comment by hahuang65** [comment]
> > > It's caused by https://github.com/vim-ruby/vim-ruby/blob/master/indent/ruby.vim#L41 so you'll want to change this to not include the dot or anything you don't want.
> > 
> > How might you set that in nvim without changing the source code of `vim-ruby`?
> 
> `vim.cmd [[autocmd FileType ruby setlocal indentkeys-=.]]`

Are you able to get that to work in a `ftplugin/ruby.vim`?

I would prefer it there over a autocommand but it didn't do anything for me.

**Comment by danielrlatham** [comment]
Adding `vim.cmd([[autocmd FileType ruby setlocal indentkeys-=.]])` to my configuration worked. Thank you.

**Comment by hahuang65** [comment]
For those 

> > > > It's caused by https://github.com/vim-ruby/vim-ruby/blob/master/indent/ruby.vim#L41 so you'll want to change this to not include the dot or anything you don't want.
> > > 
> > > 
> > > How might you set that in nvim without changing the source code of `vim-ruby`?
> > 
> > 
> > `vim.cmd [[autocmd FileType ruby setlocal indentkeys-=.]]`
> 
> Are you able to get that to work in a `ftplugin/ruby.vim`?
> 
> I would prefer it there over a autocommand but it didn't do anything for me.

Turns out we need to set this in `after/indent/ruby.vim` instead of `after/ftplugin/ruby.vim`

**Comment by 9mm** [comment]
> Thanks for that, I'd been considering removing treesitter for a while now because I waste so much time fixing indentation due to this.

sadly im thinking the same. the most basic of situations (def... end) break indentation. What's even the point? I notice this in multiple languages as well. I have only began my path of trying to fix everything though, which is what lead me here
