### ISSUE TITLE
Embedded Regexp in HTML <input pattern="">

### ISSUE THREAD

**Issue by bennypowers** [nvim-treesitter/nvim-treesitter#2569]
**Is your feature request related to a problem? Please describe.**
[HTML `<input>` elements can accept a `pattern` attribute containing a regexp](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern) 

**Describe the solution you'd like**
nvim-treesitter should inject `pattern` (from regexp) into the attribute text content
<img width="880" alt="Screen Shot 2022-02-23 at 23 53 56" src="https://user-images.githubusercontent.com/1466420/155559054-39ab9925-eee2-403a-9dbb-8e077afa0aae.png">

**Describe alternatives you've considered**
manually parsing?

**Additional context**

https://github.com/tree-sitter/tree-sitter-html/issues/37#issuecomment-1049494680

**Comment by bennypowers** [comment]
straw proposal for `queries/html/injections.scm'

```scheme
(input_element
  (attribute
     (attribute_name) @_attr
     (quoted_attribute_value (attribute_value) @pattern))
   (#eq? @_attr "pattern"))
```

**Comment by bennypowers** [comment]
If this is acceptable we can add more script types as well, like

```html
<script type="application/graphql">...</script>

**Comment by theHamsta** [comment]
> If this is acceptable we can add more script types as well, like
> 
> ```
> <script type="application/graphql">...</script>
> <script type="text/markdown">...</script>
> ```

Of course, everything that improves highlighting is always welcome!
