### ISSUE TITLE
Creating and running a test

### ISSUE THREAD

**Issue by dwoznicki** [nvim-treesitter/nvim-treesitter#2570]
Hi, I'd like to add a fix for some Java indentation issues and create a test. However, I'm having trouble running the tests currently.

When I run `scripts/run_tests.sh indent/lua_spec.lua`, I get the following error.

```
$ scripts/run_tests.sh indent/lua_spec.lua
Error detected while processing command line:
E492: Not an editor command: PlenaryBustedDirectory tests/indent/lua_spec.lua { minimal_init = './scripts/minimal_init.lua' }
```

Looking at `scripts/minimal_init.lua`, I see that it expects to find a `plugin/plenary.vim` file. I have plenary installed at `~/.config/nvim/plugged/plenary.nvim`, so I tried copying the `plenary.nvim/plugin/plenary.vim` file to the `nvim-treesitter/plugin/` dir. But alas, I still got an error when trying to execute the test runner.

```
$ scripts/run_tests.sh indent/lua_spec.lua
Error detected while processing command line:
E5108: Error executing lua [string ":lua"]:1: module 'plenary.test_harness' not found:
	no field package.preload['plenary.test_harness']
	no file './plenary/test_harness.lua'
	no file '/home/danwoz/neovim/.deps/usr/share/luajit-2.1.0-beta3/plenary/test_harness.lua'
	no file '/usr/local/share/lua/5.1/plenary/test_harness.lua'
	no file '/usr/local/share/lua/5.1/plenary/test_harness/init.lua'
	no file '/home/danwoz/neovim/.deps/usr/share/lua/5.1/plenary/test_harness.lua'
	no file '/home/danwoz/neovim/.deps/usr/share/lua/5.1/plenary/test_harness/init.lua'
	no file './plenary/test_harness.so'
	no file '/usr/local/lib/lua/5.1/plenary/test_harness.so'
	no file '/home/danwoz/neovim/.deps/usr/lib/lua/5.1/plenary/test_harness.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './plenary.so'
	no file '/usr/local/lib/lua/5.1/plenary.so'
	no file '/home/danwoz/neovim/.deps/usr/lib/lua/5.1/plenary.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	[string ":lua"]:1: in main chunk
```

How can I install plenary so that it can be used by the `run_tests.sh` script? Is there anything else I should know about writing tests?

**Comment by theHamsta** [comment]
I think it expects that you have plenary installed using built-in package (`:h packages` e.g. by using packer) or copying it to the right magic place like our CI does. When you're using `plugged` you probably also need to invoke it in the `minimal_init.lua` so that the plugins get found.

Does `:PlenaryBustedFile %` work when you have one of the test files opened?

**Comment by dwoznicki** [comment]
It does appear to work. I output looks something like so:

```
...
Success ||      indent Lua: new line: cond.lua[8]
Success ||      indent Lua: new line: cond.lua[10]
Success ||      indent Lua: new line: cond.lua[12]
Success ||      indent Lua: new line: no-indent-after-paren-pairs.lua[3]
Success ||      indent Lua: new line: no-indent-after-paren-pairs.lua[6]

Success:        29
Failed :        0
Errors :        0
```

**Comment by theHamsta** [comment]
So the only thing you need to do is to activate plenary. Whether through `:PlenaryBustedDirectory`, built-in packages or by adding https://github.com/junegunn/vim-plug#example to the minimal config.

**Comment by dwoznicki** [comment]
Cool, that appears to have worked. For future reference, here's what I did.

Copied `~/.config/nvim/plugged/plenary.nvim/plugin/plenary.vim` to the `nvim-treesitter/plugin/` directory.

Added the following snippet to the bottom of file `nvim-treesitter/scripts/minimal_init.lua`.

```lua
vim.cmd [[
call plug#begin()
Plug 'nvim-lua/plenary.nvim'
call plug#end()
]]
```
