### ISSUE TITLE
README: Mention tree-sitter minimum requirement

### ISSUE THREAD

**Issue by shuber2** [nvim-treesitter/nvim-treesitter#2581]
This project requires tree-sitter at least 0.20.1 as the discussion on issue #2579 displays.

In the README, the requirements mention neovim (latest stable or nightly). However, neovim itself does not specify minimum versions of tree-sitter and also the cmake config of neovim does not check for any specific version. Gentoo Linux, for instance, builds neovim currently against tree-sitter 0.20.0 (unless newer versions of tree-sitter are marked stable by the user). As a consequence, Gentoo users can be assumed to have a neovim that adheres to tree-sitter ABI version 13, instead of version 14, and run into issue #2579 of nvim-treesitter.

I suggest to explicitly mention a minimum required version of tree-sitter in the README.

**Comment by theHamsta** [comment]
We don't have the requirement on the tree-sitter version except ABI 13. ABI 14 is not used yet by any of the parsers. We support generating for ABI 14 if your runtime supports it. There might be small differences in the query engine (e.g. a few bugs were fixed in recent tree-sitter runtimes). But those bugs are properties of the tree-sitter version and don't of this plugin.

**Comment by shuber2** [comment]
@theHamsta But issue #2579 is triggered for ABI 13 and not for ABI 14. So if this plugin shall work with ABI 13, too, then issue #2579 needs to be reopened.

**Comment by clason** [comment]
It's not about ABI, though.

**Comment by shuber2** [comment]
Could you help me understand what it is about?

**Comment by clason** [comment]
Probably a bug in tree-sitter with predicates that was fixed in 0.20.1.

**Comment by clason** [comment]
The point is, nvim-treesitter works (as in, does not produce errors) with any version that supports ABI 13; that's what "support" means. Of course, any version except the most recent one will be missing bugfixes that may impact highlighting; that's the nature of things.

**Comment by shuber2** [comment]
I am a bit puzzled. So issue #2579 is triggered by a tree-sitter bug present in 0.20.0?

**Comment by clason** [comment]
Yes.

**Comment by shuber2** [comment]
It would be good to know what bug this is, because this would mean that the Gentoo bug report https://bugs.gentoo.org/834039 needs to be refined (or corrected, indeed).

Anyhow, we do agree that nvim-treesitter does not work with tree-sitter-0.20.0. Yet you would not like to phrase a minimum requirement on tree-sitter, because it is not about a version contract per se, but only about a bug in this particular version. By the same argument, Gentoo shall not introduce a minimum requirement tree-sitter-0.20.1 for neovim. Instead, it shall mark tree-sitter 0.20.0 as buggy and therefore not build neovim against it.

Like that?

**Comment by clason** [comment]
> Anyhow, we do agree that nvim-treesitter does not work with tree-sitter-0.20.0. 

No, we do _not_ agree on that. "Does not work" implies more than a highlighting bug for a single language.

Also, Gentoo should just respect Neovim's build scripts and build against the versions we deliberately specify and test with.

**Comment by shuber2** [comment]
> Also, Gentoo should just respect Neovim's build scripts

I am happy to open a bug at the Gentoo bugzilla. Help me understand where Gentoo is not respecting Neovim's build scripts.

> and build against the versions we deliberately specify and test with.

Please tell me where I can find these specifications and what the versions are.

> > Anyhow, we do agree that nvim-treesitter does not work with tree-sitter-0.20.0.
> No, we do _not_ agree on that. "Does not work" implies more than a highlighting bug for a single language.

Ok, highlighting for latex is impaired (and for me personally to an extent that it is distracting and in this sense "does not work" even though "it runs"). But what is the conclusion from this?

**Comment by clason** [comment]
> Help me understand where Gentoo is not respecting Neovim's build scripts.

By apparently not building against the tree-sitter version we specify in our build scripts.

> Please tell me where I can find these specifications and what the versions are.

They're specified in `third-party/CMakeLists.txt`.

> Ok, highlighting for latex is impaired (and for me personally to an extent that it is distracting and in this sense "does not work" even though "it runs"). But what is the conclusion from this?

My personal conclusion is never to trust distribution builds and instead build from source with all bundled dependencies myself.

**Comment by shuber2** [comment]
> > Please tell me where I can find these specifications and what the versions are.
> 
> They're specified in `third-party/CMakeLists.txt`.

That is good to know, thanks for the hint.

However, if neovim would really want to specify that tree-sitter 0.20.1 is to be used then it would specify it in the root `CMakeLists.txt`. I think you know very well what the purpose of `third-party/CMakeLists.txt` actually is.

> > Ok, highlighting for latex is impaired (and for me personally to an extent that it is distracting and in this sense "does not work" even though "it runs"). But what is the conclusion from this?
> My personal conclusion is never to trust distribution builds and instead build from source with all bundled dependencies myself.

I am pretty sure that you do not do that for your entire user space software and I am pretty sure that you do not expect that from the average user even for neovim alone. If you would really build tens of thousands of packages from source then you would quickly despair due to the dependency hell if indeed each and every package would want one very specific version of all its dependencies. This is just not how building software for Linux can work, would have ever worked, or will ever work.

So, putting your personal conclusion on building neovim from source – as a neovim developer – aside, it would be more important to ask what the conclusion of Kant would be on that matter. And here, according to my experience, it would make sense to support package maintainers of Linux distributions by being clear on dependency requirements.

**Comment by theHamsta** [comment]
The reason for this bug is that the old tree-sitter was skipping the evaluation of predicates in some instances, so 
```
((word) @punctuation.delimiter
(#eq? @punctuation.delimiter "&"))
```
`#eq?` would not run everytime on word where it should run. This is as property of the old tree-sitter runtime. Bugs are a property of software. This does not mean it's not possible to use it. The parsers in this repo have to be compatible with ABI 13 this are the version requirements that we get from tree-sitter itself. You will be able to build and run the software. We have a check for this ABI in our healthcheck. As it's an experimental feature of Neovim it may or may not work and the quality of the feature is not stable.

This repo is not distributed by any distribution if you want to discuss the version requirements Neovim please open an issue there. As far as I know there aren't strict version fixed and in doubt the bundled revisions are recommended.

**Comment by thesamesam** [comment]
> > Help me understand where Gentoo is not respecting Neovim's build scripts.
> 
> By apparently not building against the tree-sitter version we specify in our build scripts.
> 
> > Please tell me where I can find these specifications and what the versions are.
> 
> They're specified in `third-party/CMakeLists.txt`.
> 
> > Ok, highlighting for latex is impaired (and for me personally to an extent that it is distracting and in this sense "does not work" even though "it runs"). But what is the conclusion from this?
> 
> My personal conclusion is never to trust distribution builds and instead build from source with all bundled dependencies myself.

I do try to read entire diffs between packages I bump and I'm sorry I missed the hunk where the minimum dependency bound changed. Fixed now. Cheers.

**Comment by theHamsta** [comment]
Regarding tree-sitter I would go for `:h minimum-language-version` and try that this matches our current parsers. I would try that `:h vim.treesitter.language_version` matches the constants come from hereIn particular here: https://github.com/tree-sitter/tree-sitter/blob/3ff5c19403ccb8e6139a048b3257302a8da6139e/lib/include/tree_sitter/api.h#L30-L13 So at the moment, nvim nightly supports 13-14 while older versions of nvim only support 13. If a ABI 13 nvim encounters a pre-generated ABI 14 parser we try to generate a parser for the old ABI. The users needs to have tree-sitter-cli installed for that. We have not done the transition to ABI 14 yet (@matbme)

When the ABI numbers change, it is typically loudly announced at tree-sitter/tree-sitter. The might be a tree-sitter 1.0 at some point so I would subscribe to https://github.com/tree-sitter/tree-sitter/issues/930. All in all, the tree-sitter C library is very stable and you could probably build Neovim with any of the old tree-sitter versions. The only touch point for users is that the ABI of the parser must be in the supported ABI range of the runtime. When the version of the runtime changes there might be minor changes in experience like the LaTeX bug you discovered, but it should be all in all compatible when the ABI numbers match.

We tried to hide that from user (there was a lot of confusion about that) by depending on the latest release on Neovim.
