### ISSUE TITLE
TSBufToggle

### ISSUE THREAD

**Issue by kyazdani42** [nvim-treesitter/nvim-treesitter#259]
When i work in some files, i sometime want to enable a plugin that uses the default neovim syntax (like styled-components stuff in js files).
Mapping TSBufDisable and TSBufEnable would work but it's a hassle and it would be easier to just map `TSBufToggle highlight`.

**Comment by apazzolini** [comment]
Maybe this would be better served as a separate issue, but for the use case described above, would it instead be possible to define a rule to exclude a specific chunk of a file from treesitter highlighting and fall back to Neovim highlighting? I also use styled-components (and the nvim plugin for it), and it would be awesome if there was something like:

```
(call_expression
  left: (member_expression (identifier #eq? 'styled')
  right: (template_string @neovim_fallback_highlight))
```

**Comment by kyazdani42** [comment]
this is a completely different issue indeed, and this is on the roadmap and i think it should be first addressed upstream.

**Comment by vigoux** [comment]
I guess that this would be really hard too.

**Comment by kyazdani42** [comment]
js land makes everything harder doesn't it x)
