### ISSUE TITLE
TSBufDisable and disabling module not working properly on some filetypes

### ISSUE THREAD

**Issue by kyazdani42** [nvim-treesitter/nvim-treesitter#260]
not too much time to describe the issue right now but it seems disabling highlight on javascriptreact files doesn't work (it might be related to all linked filetypes, not sure, i'll investigate tonight)

**Comment by kyazdani42** [comment]
also TSModuleInfo doesn't give informations about linked filetypes (like javascriptreact)

**Comment by kyazdani42** [comment]
Not sure but it seems javascriptreact is actually not defined anywhere in the code.

**Comment by theHamsta** [comment]
I remember that someone had a complaint about the file type changed by a plugin. Nvim-treesitter gave error messages when trying to use the parser for the buffer it was attached to but now with a different file type. After that typescriptreact was added to the used_by of the parser. Can you disable for JavaScript react once it's registered as used_by?

**Comment by kyazdani42** [comment]
I will look into it later today if i'm not too tired :) i think javascriptreact is indeed not set as `used_by` in the js parser.
Also i should look into the js queries to see if they handle jsx stuff.

**Comment by theHamsta** [comment]
@kyazdani42 is this still an issue?

**Comment by kyazdani42** [comment]
looks like it has been fixed
