### ISSUE TITLE
Jump to certain parts of a function type signature

### ISSUE THREAD

**Issue by cameron1024** [nvim-treesitter/nvim-treesitter#2601]
**Is your feature request related to a problem? Please describe.**
Disclaimer: I'm just dipping my toes in treesitter, I have a feeling this might be possible through config, but I'm not sure, happy either way :grin: 

I fairly often find myself wanting to change the type signature of a function, or add a parameter, etc. Essentially I'd like to be able to "jump to the return type of the current function". For example:

```rust
fn foo(bar: Bar) -> Foo {
  bar.qux();
// ^ - cursor here
}

// then after pressing a bind

fn foo(bar: Bar) -> Foo {
//                  ^ - cursor here
  bar.qux();
}

// or a different bind takes you to the start/end of the parameter list

fn foo(bar: Bar) -> Foo {
//             ^ - cursor here
  bar.qux();
}
```

**Describe the solution you'd like**
See above 

**Describe alternatives you've considered**
Currently I'm just using `treesitter-textobjects` to go to the beginning of the function, and then either hitting `W` a few times or using some language specific shortcut (e.g. searching for `->` when writing Rust). However, I spend a decent amount of time in other languages with different syntax, so it would be handy to just be able to go straight to that point

**Comment by clason** [comment]
That is something that should be implemented in a plugin (but not this one!) -- maybe https://github.com/mfussenegger/nvim-treehopper is what you're looking for?

**Comment by stsewd** [comment]
@cameron1024 you can also do this with a custom text object, see:

- https://github.com/nvim-treesitter/nvim-treesitter-textobjects#overriding-or-extending-textobjects
- https://github.com/nvim-treesitter/nvim-treesitter-textobjects#text-objects-move
