### ISSUE TITLE
`TSVariable` highlight supersedes `TSVariableBuiltin`

### ISSUE THREAD

**Issue by HumblePresent** [nvim-treesitter/nvim-treesitter#2606]
### Describe the highlighting problem

I have noticed that the `TSVariable` highlight group appears to supersede the `TSVariableBuiltin` highlight group. I do not believe this has always been the case because I noticed a change in the way built-in variables were highlighted after updating `nvim-treesitter` a month or so ago.

### Example snippet that causes the problem

```lua
-- treesitter-test.lua
local object = {}

function object:set_property(val)
    self.property = val
end
```

### Tree-sitter parsing result

![treesitter-test](https://user-images.githubusercontent.com/60856003/156942784-53eda2ff-3a26-4150-bd87-518b425cd6ee.png)

### Example screenshot

![treesitter-highlight](https://user-images.githubusercontent.com/60856003/156942867-4c792455-752b-4d18-8f87-85379d245abb.png)

### Expected behavior

Given that built-in variables are a subset of normal variables I would expect the `TSVariableBuiltin` highlight group to supersede the `TSVariable` highlight group, not the other way around. I believe this was the behavior previously but I have not tracked down a particular commit that changed this behavior.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - WARNING: `node` executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - c              ✓ ✓ ✓ ✓ ✓ 
  - make           ✓ . . . ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - comment        ✓ . . . . 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.7.0-dev+1192-g8ed9c8448
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az242-168

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
The change comes from switching the Lua parser to a different one and rewriting the queries to match.

The order is determined by, well, the order these highlights are applied.

**Comment by clason** [comment]
Can you try moving the lines
https://github.com/nvim-treesitter/nvim-treesitter/blob/69a02b88d8ca937b2e00ecba947f62f115bead90/queries/lua/highlights.scm#L10-L11

to below 
https://github.com/nvim-treesitter/nvim-treesitter/blob/69a02b88d8ca937b2e00ecba947f62f115bead90/queries/lua/highlights.scm#L139-L141
