### ISSUE TITLE
queries/javascript/jsx.scm file

### ISSUE THREAD

**Issue by kyazdani42** [nvim-treesitter/nvim-treesitter#263]
I believe this file was there at some point when i introduced different query files for a filetype (like `javascript.jsx`) > see query.lua
The file is not here anymore which is quite strange, i remember @steelsojka writing it some time ago.

**Comment by kyazdani42** [comment]
maybe this file never existed but locally on one machine of mine.
I'm will add this when i have some free time.

**Comment by steelsojka** [comment]
I can also take a look at this. TSX doesn't work for me right now either.

**Comment by kyazdani42** [comment]
this is done
