### ISSUE TITLE
Shouldn't hl-TSUnderline link to vim's hl-Underlined group?

### ISSUE THREAD

**Issue by adrian5** [nvim-treesitter/nvim-treesitter#2653]
Looks like by default `TSUnderline` is `cleared` (no styling whatsoever). Shouldn't it instead link to the classic [`Underlined` group](https://neovim.io/doc/user/syntax.html#group-name), or is there some issue that arises from this?

**Comment by clason** [comment]
That's not what it says for me:
```
:hi TSUnderline
TSUnderline    xxx cterm=underline gui=underline
```

**Comment by kyazdani42** [comment]
same here

**Comment by adrian5** [comment]
Ok, thanks guys. Must have been cleared by a colorscheme then. I can close and reopen vim in the same term window and it's still cleared, but vim in a new term will show linked like you. False alarm then!
