### ISSUE TITLE
Use `conceal` metadata in highlight queries

### ISSUE THREAD

**Issue by max397574** [nvim-treesitter/nvim-treesitter#2660]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
allow to have a conceals.scm file inside queries/*/ for concealing queries.

**Describe alternatives you've considered**
none

**Additional context**
Since [this pr](https://github.com/neovim/neovim/pull/17776) it's possible to conceal with treesitter.
To make it actually possible for people to do this you should add support for `conceals.scm`file

**Comment by clason** [comment]
Conceal is part of syntax, so this has to be part of highlights queries.

Also, this should wait for the actual 0.7 release.

**Comment by theHamsta** [comment]
We want to support this at some point. There are more things we want to to for the 0.7 release and it would be good that we track that

**Comment by clason** [comment]
But we can't do this in a separate query (easily) as the conceal is an annotation on a highlight query.

We want to support conceal, of course, but this is not the way.

(And I don't think this is a good tracking issue.)

**Comment by clason** [comment]
If there is already an issue about conceal support, this is a duplicate and should definitely be closed.

**Comment by theHamsta** [comment]
We can already set the meta-data that the linked PR. The previous issues were unspecific on how conceal should be added, this PR links the solution. It would be good to close the old conceal issue (as it's implemented now) and open a tracking issues were we can add list and discuss were conceal would make sense.

**Comment by clason** [comment]
I still think we should have a separate tracking issue. A conceal.scm is not tue way.

**Comment by theHamsta** [comment]
> Wait for 0.7

Why? Metadata is just ignored when not supported. It would make sense to add it now as we did before with `priority`.

I don't know whether this new feature is still guarded by `conceallevel`. If now it would make sense to have a directive that sets the metadata based on this. I interpret this issue as "please support this new feature". We often have the situation where we solve a feature request in a different way as originally proposed. A tracking issue if needed can supersede this issue.

**Comment by clason** [comment]
It is still guarded by conceallevel.

**Comment by theHamsta** [comment]
Was about to close some of the old conceal issues. But I realized that this does not fully solve old use cases like concealing single letters which would require either specialized directives regexing over the whole test or selecting sub-ranges from nodes.

**Comment by theHamsta** [comment]
Superseded by #2663
