### ISSUE TITLE
JSX related queries throw error on startup

### ISSUE THREAD

**Issue by apazzolini** [nvim-treesitter/nvim-treesitter#267]
**Describe the bug**
Adding JSX-related highlight queries cause an error on startup. However, if they're added after Neovim is already running, reloading a file works properly.

**To Reproduce**
1. Add `(jsx_attribute (property_identifier) @number)` to `queries/javascript/highlights.scm`
2. Close Neovim and relaunch it
3. An `invalid node type` error will be raised.

**Additional Info**
1. Launch Neovim and open a JS file
2. Add the above rule, save the file
3. Run `:w | e | TSBufEnable highlight` in the JS file buffer
4. Rule is applied as expected, no errors are raised

**Expected behavior**
No errors should be raised on startup when JSX related queries exist

**Output of `:checkhealth nvim_treesitter`**

With the above rule:
```
health#nvim_treesitter#check
========================================================================
  - ERROR: Failed to run healthcheck for "nvim_treesitter" plugin. Exception:
    function health#check[21]..health#nvim_treesitter#check, line 1
    Vim(lua):E5108: Error executing lua ...m/HEAD-1ca67a7/share/nvim/runtime/lua/vim/treesitter.lua:151: query: invalid node type at position 3209
```

Without the above rule:
```

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## typescript parser healthcheck
  - OK: typescript parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.

## query parser healthcheck
  - OK: query parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for query
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## javascript parser healthcheck
  - OK: javascript parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.
```

**Comment by kyazdani42** [comment]
This happens because typescript loads the javascript file, this is why we need a `jsx.scm` file which will contain jsx related highlight queries and which will be loaded by `.tsx` files and not `.ts` files

**Comment by steelsojka** [comment]
@apazzolini Can you check this with the latest master and see if the problem still exists?

**Comment by apazzolini** [comment]
Looks good to me, thanks!
