### ISSUE TITLE
C TreeSitter segfaults when too many '->' encountered in a single expression

### ISSUE THREAD

**Issue by Eolien55** [nvim-treesitter/nvim-treesitter#2676]
### Describe the bug

When you write too much -> in a single expression, the C TreeSitter segfaults. When I say "too much", it's like 20.

### To Reproduce

1. Open a file with the C TreeSitter enabled
2. Copy the following text : 
```{c}
#include <stdio.h>

struct LinkedList {
	char info[50];
	struct LinkedList *next;
};

int main() {
	struct LinkedList head = {"heeyyyyyy", NULL};
	head.next = &head;

	puts(head.next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next->next-next->next->next->next->next->next->next->next->next->next-next->next->next->next->next->next->next->next->next->next-next->next->next->next->next->next->next->next->next->next->info);
}
```
3. Observe NeoVim segfaulting

### Expected behavior

The TreeSitter not segfaulting and managing to highlight the text.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :
  TSInstallFromGrammar)
  - WARNING: `node` executable not found (only needed for :TSInstallFromGrammar,
  not required for :TSInstall)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang",
  "cl", "zig" }
    Version: cc (GCC) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required
  >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - cpp            ✓ ✓ ✓ ✓ ✓
  - rust           ✓ ✓ ✓ ✓ ✓
  - markdown       ✓ . ✓ . ✓
  - jsonc          ✓ ✓ ✓ ✓ ✓
  - c              ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by theHamsta** [comment]
Does it also default on `tree-sitter parse`? Can you get a backtrace when executing with gdb or a core dump?

**Comment by Eolien55** [comment]
Output from gdb : 
```
Thread 1 "nvim" received signal SIGSEGV, Segmentation fault.
0x00007ffff7eed03d in ts_query_cursor_next_capture () from /usr/lib/libtree-sitter.so.0
```

I don't really know what you mean by `tree-sitter parse`.

**Comment by Eolien55** [comment]
It's the same if it's `.` instead of `->`

**Comment by theHamsta** [comment]
You can also use tree-sitter as a CLI tool. Since it's crashing in the queries you could test with `tree-sitter query ` in the tree-sitter-c repository.

**Comment by clason** [comment]
This means it's a problem with the C parser, not Neovim. (`tree-sitter` is the CLI version of the library linked into Neovim.)

I think you should report this upstream: https://github.com/tree-sitter/tree-sitter-c

**Comment by theHamsta** [comment]
Well, we don't know. It could also be Neovim to use the API in a wrong way.

**Comment by theHamsta** [comment]
@clason i guess `tree-sitter query ` returns the matches instead of the AST. Still it is very likely that iterating the queries is application dependent. @Eolien55 can you open a neovim issue? I think we had this issue with a similar `->` intensive file.

**Comment by Eolien55** [comment]
The problems comes from the parsing of the AST on neovim's side ?

**Comment by Eolien55** [comment]
https://github.com/neovim/neovim/issues/17858 (i hope i correctly presented the issue)
