### ISSUE TITLE
Expose filetype_to_parsername object or give the ability to extend it

### ISSUE THREAD

**Issue by ChristianChiarulli** [nvim-treesitter/nvim-treesitter#2698]
**Is your feature request related to a problem? Please describe.**
I would like to add some extra options to this table:
https://github.com/nvim-treesitter/nvim-treesitter/blob/7bb97d270a5b3d00aca0c801f187e88e2bc2232a/lua/nvim-treesitter/parsers.lua#L4

**Describe the solution you'd like**
A way to extend the filetype_to_parsername table

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by theHamsta** [comment]
It should already be exposed although in a slightly unusual way in the code
https://github.com/nvim-treesitter/nvim-treesitter/blob/9e8749f787c206d44b2e7b1be2b79f809a0e92d8/lua/nvim-treesitter/parsers.lua#L983-L980

**Comment by ChristianChiarulli** [comment]
Gotcha, I was able to make it work like this:

```
local ft_to_parser = require"nvim-treesitter.parsers".filetype_to_parsername
ft_to_parser.motoko = "typescript"
```

Is this documented somewhere or maybe I missed it?

**Comment by theHamsta** [comment]
It is described in the adding parser section https://github.com/nvim-treesitter/nvim-treesitter#adding-parsers
