### ISSUE TITLE
Module not found Error When Setting Up nvim-treesitter

### ISSUE THREAD

**Issue by laxman20** [nvim-treesitter/nvim-treesitter#270]
**Describe the bug**
I see the following error after setting up treesitter and opening neovim.

Error executing lua [string ":lua"]:1: module 'nvim-treesitter.configs' not found

**To Reproduce**
1. Download nvim 0.5.0-nightly
2. Installed plugin and parser (verified with :TSInstallInfo)
3. Added the following to init.vim

```
lua <<EOF
require'nvim-treesitter.configs'.setup {}
EOF
```

**Expected behavior**
No errors when starting neovim

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## python parser healthcheck
  - OK: python parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.

## Missing parsers
  - WARNING: Some parsers are not installed:
    elm
    c
    java
    dart
    lua
    ocaml
    go
    nix
    yaml
    json
    jsdoc
    markdown
    julia
    html
    typescript
    swift
    query
    cpp
    ruby
    vue
    scala
    tsx
    rust
    bash
    c_sharp
    rst
    css
    php
    javascript
    haskell
    toml
    regex
    - ADVICE:
      - Install them using `:TSInstall language

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-nightly
Build type: Release
LuaJIT 2.0.5
Compilation: /Users/laxmanso/.local/bin/homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200807-86806-5koi6w/build/config -I/tmp/neovim-20200807-86806-5koi6w/src -I/Users/laxmanso/.local/bin/homebrew/include -I/tmp/neovim-20200807-86806-5koi6w/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -I/Users/laxmanso/.local/bin/homebrew/opt/gettext/include -I/tmp/neovim-20200807-86806-5koi6w/build/src/nvim/auto -I/tmp/neovim-20200807-86806-5koi6w/build/include
Compiled by laxmanso@A19723LaxmanSo

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/Users/laxmanso/.local/bin/homebrew/Cellar/neovim/HEAD-f26df8b/share/nvim"

```

Run :checkhealth for more info

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## python parser healthcheck
  - OK: python parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.

## Missing parsers
  - WARNING: Some parsers are not installed:
    elm
    c
    java
    dart
    lua
    ocaml
    go
    nix
    yaml
    json
    jsdoc
    markdown
    julia
    html
    typescript
    swift
    query
    cpp
    ruby
    vue
    scala
    tsx
    rust
    bash
    c_sharp
    rst
    css
    php
    javascript
    haskell
    toml
    regex
    - ADVICE:
      - Install them using `:TSInstall language

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: xterm-kitty
  - ERROR: $TERM should be "screen-256color" or "tmux-256color" in tmux. Colors might look wrong.
    - ADVICE:
      - Set default-terminal in ~/.tmux.conf:
          set-option -g default-terminal "screen-256color"
      - https://github.com/neovim/neovim/wiki/FAQ

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /Users/laxmanso/.local/bin/homebrew/bin/python2 does not have the "neovim" module. :help |provider-python|
          /Users/laxmanso/.local/bin/homebrew/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /Users/laxmanso/.local/bin/homebrew/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 3:
          /Users/laxmanso/.local/bin/homebrew/bin/python3 does not have the "neovim" module. :help |provider-python|
          python3.9 not found in search path or not executable.
          /Users/laxmanso/.local/bin/homebrew/bin/python3.8 does not have the "neovim" module. :help |provider-python|
          python3.7 not found in search path or not executable.
          python3.6 not found in search path or not executable.
          python3.5 not found in search path or not executable.
          python3.4 not found in search path or not executable.
          python3.3 not found in search path or not executable.
          /Users/laxmanso/.local/bin/homebrew/bin/python is Python 2.7 and cannot provide Python 3.
  - INFO: Executable: Not found

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v11.12.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - WARNING: `perl` and `cpanm` must be in $PATH.
    - ADVICE:
      - Install Perl and cpanminus and verify that `perl` and `cpanm` commands work.

**Comment by laxman20** [comment]
This is an issue with my package manager (minpac). It's happening with all lua plugins.

**Comment by Furkanzmc** [comment]
Just in case somebody else get here having the same problem, configuring the plugin on `VimEnter` or on demand did the trick for me.

**Comment by David-Else** [comment]
I used:
```
$ mkdir -p ~/.local/share/nvim/site/pack/nvim-treesitter/start
$ cd ~/.local/share/nvim/site/pack/nvim-treesitter/start
$ git clone https://github.com/nvim-treesitter/nvim-treesitter.git
```
and added:
```
lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = "typescript",     -- one of "all", "language", or a list of languages
  highlight = {
    enable = true,              -- false will disable the whole extension
    disable = { },  -- list of language that will be disabled
  },
}
EOF
```
as per the instructions and also get ` Error executing lua [string ":lua"]:1: module 'nvim-treesitter.configs' not found:`

```
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## c parser healthcheck
  - OK: c parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for c
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - OK: `folds.scm` found.

## typescript parser healthcheck
  - OK: typescript parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for typescript
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - OK: `folds.scm` found.
```

**Comment by RonanMacF** [comment]
Am also getting this error, 
```
Error executing lua [string ":lua"]:1: module 'nvim-treesitter.configs' not found
no field package.preload['nvim-treesitter.configs']
```

**Comment by vigoux** [comment]
What package manager are you sing ?

**Comment by RonanMacF** [comment]
nix home-manager, it seems to be installed in `/store/knlxpcr0zapy1404b4z4pjvlb8hxb94j-neovim-nightly-master/share/nvim/runtime/lua/vim/treesitter`. I was able to run `:TSInstall all` but it fails when sourcing the lua config file.

**Comment by vigoux** [comment]
Oh that's weird then.
I am not a nix expert though, so I can't help at all...
Could you check the output of `:lua package.path` ?

**Comment by RonanMacF** [comment]
It provides a fairly hefty output, the paths that share the same nix prefix are as follows
```
/nix/store/knlxpcr0zapy1404b4z4pjvlb8hxb94j-neovim-nightly-master/share/nvim/runtime/lua/?/init.lua
/nix/store/knlxpcr0zapy1404b4z4pjvlb8hxb94j-neovim-nightly-master/share/nvim/runtime/pack/dist/opt/matchit/lua/?.lua
/nix/store/knlxpcr0zapy1404b4z4pjvlb8hxb94j-neovim-nightly-master/share/nvim/runtime/pack/dist/opt/matchit/lua/?/init.lua;
/nix/store/knlxpcr0zapy1404b4z4pjvlb8hxb94j-neovim-nightly-master/lib/nvim/lua/?.lua;
/nix/store/knlxpcr0zapy1404b4z4pjvlb8hxb94j-neovim-nightly-master/lib/nvim/lua/?/init.lua;
```

**Comment by vigoux** [comment]
Are you using vim built-in pack feature?

**Comment by David-Else** [comment]
@vig I am using the built-in pack feature and my output for `:lua print(package.path)` is:
```
/home/david/.config/nvim/lua/?.lua;/home/david/.config/nvim/lua/?/init.lua;/etc/xdg/nvim/lua/?.lua;/etc/xdg/nvim/lua/?/init.lua;/home/david/.local/share/nvim/site/lua/?.lua;/home/david/.loca
l/share/nvim/site/lua/?/init.lua;/home/david/.local/share/nvim/site/pack/nvim-treesitter/start/nvim-treesitter/lua/?.lua;/home/david/.local/share/nvim/site/pack/nvim-treesitter/start/nvim-tr
eesitter/lua/?/init.lua;/home/david/.local/share/flatpak/exports/share/nvim/site/lua/?.lua;/home/david/.local/share/flatpak/exports/share/nvim/site/lua/?/init.lua;/var/lib/flatpak/exports/sh
are/nvim/site/lua/?.lua;/var/lib/flatpak/exports/share/nvim/site/lua/?/init.lua;/usr/local/share/nvim/site/lua/?.lua;/usr/local/share/nvim/site/lua/?/init.lua;/usr/share/nvim/site/lua/?.lua;
/usr/share/nvim/site/lua/?/init.lua;/tmp/.mount_nvimnoqBQw/usr/share/nvim/runtime/lua/?.lua;/tmp/.mount_nvimnoqBQw/usr/share/nvim/runtime/lua/?/init.lua;/tmp/.mount_nvimnoqBQw/usr/share/nvim
/runtime/pack/dist/opt/matchit/lua/?.lua;/tmp/.mount_nvimnoqBQw/usr/share/nvim/runtime/pack/dist/opt/matchit/lua/?/init.lua;/tmp/.mount_nvimnoqBQw/usr/lib/nvim/lua/?.lua;/tmp/.mount_nvimnoqB
Qw/usr/lib/nvim/lua/?/init.lua;/usr/share/nvim/site/after/lua/?.lua;/usr/share/nvim/site/after/lua/?/init.lua;/usr/local/share/nvim/site/after/lua/?.lua;/usr/local/share/nvim/site/after/lua/
?/init.lua;/var/lib/flatpak/exports/share/nvim/site/after/lua/?.lua;/var/lib/flatpak/exports/share/nvim/site/after/lua/?/init.lua;/home/david/.local/share/flatpak/exports/share/nvim/site/aft
er/lua/?.lua;/home/david/.local/share/flatpak/exports/share/nvim/site/after/lua/?/init.lua;/home/david/.local/share/nvim/site/after/lua/?.lua;/home/david/.local/share/nvim/site/after/lua/?/i
nit.lua;/etc/xdg/nvim/after/lua/?.lua;/etc/xdg/nvim/after/lua/?/init.lua;/home/david/.config/nvim/after/lua/?.lua;/home/david/.config/nvim/after/lua/?/init.lua;./?.lua;/home/travis/build/neo
vim/bot-ci/build/neovim/.deps/usr/share/luajit-2.1.0-beta3/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/sh
are/lua/5.1/?.lua;/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/share/lua/5.1/?/init.lua
```

**Comment by vigoux** [comment]
@David-Else are you on nix?

**Comment by David-Else** [comment]
@vigoux Yes! Centos 8.2 with Gnome Desktop.

**Comment by RonanMacF** [comment]
I am not using the built in pack feature, I am using nix itself as my package manager. This plugin has been added to nix-packages already see:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/vim-plugins/vim-plugin-names#L373

I manage many other plugins this way, this is the first plugin to cause an issue. Although it is also the first fully lua based plugin so that may be a reason

**Comment by vigoux** [comment]
Could you try doing `packadd nvim-treesitter` in you config and see if it solves the issue?

**Comment by RonanMacF** [comment]
I ran that and it didn't provide any outputt, expected I think?

For posterity this is my packpath `/nix/store/nyibggd7xbfb7pd0vfa9nm578iqkihab-vim-pack-dir,/Users/ronan/.config/nvim,/etc/xdg/nvim,/Users/ronan/.local/share/nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/si
te,/nix/store/8k88gnk6yl6mlis46909r7bbibijjqh3-neovim-nightly-master/share/nvim/runtime,/nix/store/8k88gnk6yl6mlis46909r7bbibijjqh3-neovim-nightly-master/lib/nvim,/usr/share/nvim
/site/after,/usr/local/share/nvim/site/after,/Users/ronan/.local/share/nvim/site/after,/etc/xdg/nvim/after,/Users/ronan/.config/nvim/after`

Note `8k88gnk6yl6mlis46909r7bbibijjqh3` is the new hash of neovim nightly which replaces `knlxpcr0zapy1404b4z4pjvlb8hxb94j` above as I had to recompile my nix config

**Comment by David-Else** [comment]
@vigoux `packadd nvim-treesitter` got rid of the errors, now it seems to be working. Please add that to the README :)

**Comment by obxhdx** [comment]
I have the same error happens with [vim-plug](https://github.com/junegunn/vim-plug).

**Comment by ernestre** [comment]
@obxhdx  maybe you've put the setup block inside the vim-plug's setup function similar to this?

```vim
call plug#begin('~/.vim/plugged')

Plug 'nvim-treesitter/nvim-treesitter'

lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained", -- one of "all", "maintained" (parsers with maintainers), or a list of languages
  highlight = {
    enable = true,              -- false will disable the whole extension
    disable = { "c", "rust" },  -- list of language that will be disabled
  },
}
EOF

call plug#end()
```

If that's the case, try moving it outside:

```vim
call plug#begin('~/.vim/plugged')
Plug 'nvim-treesitter/nvim-treesitter'
call plug#end()


lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained", -- one of "all", "maintained" (parsers with maintainers), or a list of languages
  highlight = {
    enable = true,              -- false will disable the whole extension
    disable = { "c", "rust" },  -- list of language that will be disabled
  },
}
EOF
```

Had the same issue and this helped.

**Comment by obxhdx** [comment]
That definitely helped, thank you!

**Comment by vigoux** [comment]
Is this issues still valid ? Could we close it ?

**Comment by David-Else** [comment]
@vigoux Could you add the info about `packadd` to the README?

**Comment by vigoux** [comment]
Yep, will do

**Comment by bjeanes** [comment]
> maybe you've put the setup block inside the vim-plug's setup function similar to this?

This was it for me. `packadd` was a red herring for me and didn't resolve it, but moving the `lua` block after `call plug#end()` did the trick.

**Comment by jc00ke** [comment]
This bit me today because of the current difference between [master](https://github.com/nvim-treesitter/nvim-treesitter/commit/42fc28ba918343ebfd5565147a42a26580579482) and [main](https://github.com/nvim-treesitter/nvim-treesitter/commit/9866036ec3c5db40700a9178494e0cfdcfe6ecfd).

I wasn't able to get the `main` branch variant working, but the following does work with the `master` branch:

```lua
vim.pack.add({
  { src = "https://github.com/nvim-treesitter/nvim-treesitter", version = "master" },
})

require("nvim-treesitter.configs").setup({
  ensure_installed = { "elixir", "eex", "heex", },
})
```
