### ISSUE TITLE
Remove cloned folder if error occurs when installing

### ISSUE THREAD

**Issue by glyh** [nvim-treesitter/nvim-treesitter#2702]
**Is your feature request related to a problem? Please describe.**

I sometimes run into this problem:
```
Press ENTER or type command to continue                                                                                        
nvim-treesitter[norg]: Error during download, please verify your internet connection                                           
fatal: destination path 'tree-sitter-norg' already exists and is not an empty directory.    
```

**Describe the solution you'd like**
Delete the cloned folder if failed to install the plugin. 

**Additional context**
None.

**Comment by glyh** [comment]
After further investigation, I found this plugin attempted to create the same folder twice in some situations..

**Comment by kyazdani42** [comment]
hi, can you specify what "some situations" are ?

**Comment by glyh** [comment]
I don't know... It just happens sometimes to me. Maybe the network connection is not stable?

**Comment by kyazdani42** [comment]
We cannot help with this issue if we don't have more information. Please find a way to reproduce consistently so we can help with this.

**Comment by theHamsta** [comment]
@glyh we have a check for "is the folder readable". It can happen that reability of the folder changes (e.g. you're executing as root). We planned to remove the fallback when the folder is not readable since it caused a lot of confusion and bugs. Also tsx and typescript share the same repo, I hope that we give the downloaded folders different names, but I'm not 100% sure about that.

**Comment by glyh** [comment]
I've troubleshoot my config and found out this is the issue in my config. Sorry for wasting your time, I'm closing this.

**Comment by bryanboateng** [comment]
How did you solve that? @glyh

**Comment by glyh** [comment]
@bryanboateng Because I'm installing one plugin for multiple times

**Comment by CoreyCole** [comment]
For me the error went away when I removed the `TSUpdate` from my nvim-treesitter packer config:
```lua
    use {
        "nvim-treesitter/nvim-treesitter",
        -- run = ":TSUpdate" commented this out
    }
```
