### ISSUE TITLE
Swift support

### ISSUE THREAD

**Issue by jandamm** [nvim-treesitter/nvim-treesitter#271]
You've listed Swift in the readme as maintainer needed.

Right now treesitter does support Swift but this plugin needs additional files (`.scm`).

Is my understanding correct?
Is there any document to learn how to write those or any other help available?

**Comment by vigoux** [comment]
Hi and thanks for reporting !
I highly suggest going through our CONTRIBUTING.md, which provide useful links to learn how to write queries (`.scm` files).
A useful plugin too is [the playground](https://github.com/nvim-treesitter/playground) which allow you to interactively test your queries within neovim.

I see that the tree-sitter-swift repo does not provide pre-made queries so we will have to write our own, but the CONTRIBUTING should provide all the information needed. For any information, feel free to reach out on gitter (check to README and the CONTRIBUTING for the links), that's the fastest way to have answer to your questions.

We will keep this issue open as tracking.

**Comment by vigoux** [comment]
Hi, do you have any update on this ?

If you want to come and ask some questions, feel free to join [our Zulip](https://nvim-treesitter.zulipchat.com/join/1twnvjqumn0t97p65eragu5o/) !

**Comment by jandamm** [comment]
No, unfortunately I haven't found the time to read the documentation yet.
I'll join the Zulip when I have further questions 👍

**Comment by vigoux** [comment]
No rush!
I just wanted to update a bit some issues we have here and there 😉

**Comment by jandamm** [comment]
Wouldn't it make more sense to implement the queries in https://github.com/tree-sitter/tree-sitter-swift, assuming they would want to include them.
This way not only this plugin could use them. Am I missing something?

**Comment by theHamsta** [comment]
@jandamm we forked all the queries to include extra vim-related stuff but the basic queries can mostly be duplicates of upstream. We have for instance a bit more subcategories for keywords.

**Comment by theHamsta** [comment]
I just had a look at the parser results of the swift parser, it seems that its not capable yet to parse all the grammar of Swift. There were just too many ERRORs in the parsing result.

**Comment by jandamm** [comment]
I also got the impression that `tree-sitter-swift` is still mostly `WIP`.

**Comment by theHamsta** [comment]
Unpinning this since realiable highlighting not possible without substancial upstream changes.

**Comment by jandamm** [comment]
Haven't had the time to check it out but there's another treesitter plugin for swift.
https://github.com/alex-pinkus/experimental-tree-sitter-swift

Maybe this syntax is a more viable solution.

**Comment by jandamm** [comment]
Definitely, I just don't have any experience with TreeSitter so I'm not sure when I'll be able to test it out.

**Comment by jandamm** [comment]
I weren't able to install the parser :(

I first tried the steps you were describing and I got those errors on `:TSInstall swift`:
```
nvim-treesitter[swift]: Error during tarball extraction.
tar: Error opening archive: Unrecognized archive format
```

Then I tried cloning the repo locally, ran `tree-sitter generate` and ` tree-sitter test` (everything green).
I added this to my vimrc:
```lua
local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
parser_config.test = {
  install_info = {
    url = "~/.local/share/nvim/site/pack/packager/start/nvim-treesitter/swift", -- local path or git repo
    files = {"src/parser.c"}
  },
  filetype = "swift", -- if filetype does not agrees with parser name
}
```
Then I ran `:TSInstall test` which gave me those errors:
```
nvim-treesitter[test]: Error during compilation
Undefined symbols for architecture x86_64:
  "_tree_sitter_swift_external_scanner_create", referenced from:
      _tree_sitter_swift.language in parser-4b8be7.o
  "_tree_sitter_swift_external_scanner_deserialize", referenced from:
      _tree_sitter_swift.language in parser-4b8be7.o
  "_tree_sitter_swift_external_scanner_destroy", referenced from:
      _tree_sitter_swift.language in parser-4b8be7.o
  "_tree_sitter_swift_external_scanner_scan", referenced from:
      _tree_sitter_swift.language in parser-4b8be7.o
  "_tree_sitter_swift_external_scanner_serialize", referenced from:
      _tree_sitter_swift.language in parser-4b8be7.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Installing the "builtin" swift parser worked fine though.

**Comment by theHamsta** [comment]
You're missing `branch="main"` in your instal_info. Also `test` won't work it has to be the name of this parser as used in grammar.js. it has to be Swift. Your also missing scanner.cc in the install_info. You're only referencing parser.c.

**Comment by jandamm** [comment]
Got it working but still some errors (looks less than with the other swift tree sitter).

When I'll find some time I'll have a look how to write a tree sitter grammar and further improve it.
