### ISSUE TITLE
Installing TreeSitter languages outside of neovim

### ISSUE THREAD

**Issue by Clumsy-Coder** [nvim-treesitter/nvim-treesitter#2724]
I've being trying to install TreeSitter languages on the terminal without having to open neovim.

Config
```lua
require('nvim-treesitter.configs').setup({
  ensure_installed = "maintained", -- download all maintained languages
  sync_install = false,
  highlight = {
    enable = true,
    -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
    -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
    -- Using this option may slow down your editor, and you may see some duplicate highlights.
    -- Instead of true it can also be a list of languages
    additional_vim_regex_highlighting = false,
  },
  indent = {
    enable = true,
    disable = { "yaml" }
  },
  autopairs = {
    enable = true
  },
  context_commentstring = {
    enable = true,
    enable_autocmd = false,
  },
  rainbow = {
    enable = true,
    extended_mode = true,
  },
})
```

I used `nvim --headless +TSUpdate` to update all the languages.
But the output is messy and nvim doesn't exit when it's finished (I have to `Ctrl + c`).
![image](https://user-images.githubusercontent.com/19594044/161399171-57743b6d-2a90-4295-ba21-6a9c8d095578.png)

I also tried using `nvim --headless +TSUpdate +qall`
But that doesn't install the languages correctly. It just downloads them, not compiling and installing

![image](https://user-images.githubusercontent.com/19594044/161399228-e392b862-2dff-418d-aa71-8a14d9ab4edf.png)

**Comment by theHamsta** [comment]
`nvim --headless +TSUpdateSync +qa`
It will update the parsers one by one synchronous instead of a background job.

**Comment by Clumsy-Coder** [comment]
Turns out I needed `nvim --headless -c 'TSInstallSync maintained' -c 'qall'`

It's a bit slow, but it works and has better logs output.

Thanks for the help 👍

**Comment by theHamsta** [comment]
Install sync only installs if not already installed. TSUpdateSync installs if not installed but also updates if necessary when already installed.

**Comment by Clumsy-Coder** [comment]
My criteria is setting up dotfiles in a new host machine from scratch. I'm creating dotfile setup to install nvim plugins (among other things). So needed a way to that.
