### ISSUE TITLE
[lua] Syntax tree ERROR when inserting empty string with double quotes

### ISSUE THREAD

**Issue by HumblePresent** [nvim-treesitter/nvim-treesitter#2762]
### Describe the bug

The the lua parser generates an ERROR in the syntax tree when inserting empty double quotes: `""`. The error persists even after other text is inserted into the string. This results in incorrect highlighting of the string and subsequent text.

### To Reproduce

1. Create a new lua file and type
```lua
local var = ""
```
Here is the corresponding syntax tree.
![treesitter-quote-issue1](https://user-images.githubusercontent.com/60856003/162545110-8e314472-6ce0-48a4-8c7b-99cd9aaa824f.png)

2. Insert other text in between the pair of double quotes to make the string non-empty.
```lua
local var = "some text"
```
Here is the updated text and syntax tree. As you can see the ERROR persists and the string is not properly highlighted
![treesitter-quote-text](https://user-images.githubusercontent.com/60856003/162545474-a17f545e-4b4b-4838-93ab-a4f9e5f9b00b.png)
![treesitter-quote-issue2](https://user-images.githubusercontent.com/60856003/162545527-8dc36475-3355-462f-b37a-23adf5c008dd.png)

### Expected behavior

I expect there to be no ERROR in the syntax tree for an empty double quoted string.
![treesitter-quote-text3](https://user-images.githubusercontent.com/60856003/162546050-907d1919-63fd-45c0-87b2-f5d95b6cd52b.png)
![treesitter-quote-issue3 png](https://user-images.githubusercontent.com/60856003/162546057-11bb2fbb-a9d7-4e23-adf2-89ceaa8fe509.png)

I also expect there to be no ERROR when text is inserted in the string.
![treesitter-quote-text2](https://user-images.githubusercontent.com/60856003/162546103-25d35618-dcee-4bec-814e-ccf868761d1b.png)
![treesitter-quote-issue4](https://user-images.githubusercontent.com/60856003/162546436-589664d8-6a68-48ad-9a6e-9220d39d7225.png)

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - WARNING: `node` executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - make           ✓ . . . ✓ 
  - comment        ✓ . . . . 
  - bash           ✓ ✓ ✓ . ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.7.0-dev+1400-g233014f92
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az121-468

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

### Additional context

I do not encounter the issue when typing the string out directly such that it is never empty
```lua
local var = "some text"
```
Even after deleting the content of the string, making it empty, there is no ERROR in the syntax tree. This is how I generated the screenshots in the "Expected behavior" section

**Comment by theHamsta** [comment]
@muniftanjim

**Comment by MunifTanjim** [comment]
This has something to do with incremental sync and happens randomly.

![Peek 2022-04-09 13-04](https://user-images.githubusercontent.com/8050659/162560904-57969e0d-dc99-45af-afb9-7c01946eb789.gif)

To me it seems like an upstream tree-sitter bug? 🤔

**Comment by HumblePresent** [comment]
Any idea why this issue might be affecting lua in particular? I have not been able to reproduce it while using treesitter with other languages (I have tried C and python so far).

**Comment by theHamsta** [comment]
I would try to reproduce the issue using the web playground that you can build using tree-sitter CLI and web assembly. It might be that something goes wrong in the custom scanner of tree-sitter-lua. When it's not reproducible using the web playground, it's a upstream Neovim issue.

**Comment by HumblePresent** [comment]
Thanks for the suggestion! Do you have a link to information about this web playground by chance? I haven't used the tree-sitter CLI before. Looks like it has commands to generate, test, and parse.

**Comment by theHamsta** [comment]
`tree-sitter build-wasm && tree-sitter playground` it requires a wasm-toolchain for Rust. tree-sitter doesn't provide much information about this feature. Probably best to follow the error messages that those commands yield.

**Comment by Chromosore** [comment]
This problem with syntax was really upsetting me so I've done some research. Unfortunately, I haven't managed to get the playground working (I don't know why) but I've made a rudimentary python script.

You need to build `lua.so` first to be able to use this.
<details>
<summary>Build <code>lua.so</code></summary>

```sh
$ git clone https://github.com/Azganoth/tree-sitter-lua.git
$ cd tree-sitter-lua
$ python3 - <<EOF
from tree_sitter import Language
Language.build_library('lua.so', ['.'])
EOF
```
</details>

<details>
<summary>Python script</summary>

```python
from tree_sitter import Language, Parser
LUA_LANGUAGE = Language('./lua.so', 'lua')

parser = Parser()
parser.set_language(LUA_LANGUAGE)

while True:
    line = input('line: ')
    if line.strip() == 'reset':
        tree = None
        continue

    if tree != None:
        tree = parser.parse(line.encode('utf-8'), tree)
    else:
        tree = parser.parse(line.encode('utf-8'))

    print('out : ' + tree.root_node.sexp())
```
</details>

And the parser gets stuck sometimes:
```
line: reset
line: local var = ""
out : (program (local_variable_declaration (variable_declarator (identifier)) (string)))
line: local var = )""
out : (program (local_variable_declaration (variable_declarator (identifier)) (string)) (expression (string (MISSING """))))
line: local var = ""
out : (program (local_variable_declaration (variable_declarator (identifier)) (string)) (expression (string (MISSING """))))
```
```
line: reset
line: local var = "
out : (program (local_variable_declaration (variable_declarator (identifier)) (string (MISSING """))))
line: local var = ""
out : (program (local_variable_declaration (variable_declarator (identifier)) (string)))
line: local var = "
out : (program (local_variable_declaration (variable_declarator (identifier)) (string)))
```
<br />

I haven't managed to recreate the initial bug with the empty quotes, so there might be some unexpected things going on neovim's side, but the overall weird behaviour of the parser leads me to believe that this error indeed comes from the parser.

**Comment by MunifTanjim** [comment]
I think this got solved in the latest release: https://github.com/MunifTanjim/tree-sitter-lua/compare/v0.0.11...v0.0.12

**Comment by kyazdani42** [comment]
closing, indeed this is working as expected now.
