### ISSUE TITLE
Add TSRemove to remove the installed parsers from `local/share`

### ISSUE THREAD

**Issue by mvpopuk** [nvim-treesitter/nvim-treesitter#2776]
When you run `TSInstall all` and then `TSUninstall all` it's not actually uninstalling the parsers and it's reading the parsers from `local/share` folder so I had to manually delete them in order to start "fresh".

I was thinking if maybe a new command will be added so we can run something like `TSRemove` to delete everything from `local/share` ?

Thanks.

**Comment by theHamsta** [comment]
I think you're referring to the C parser bundled with Neovim, right?

**Comment by clason** [comment]
Or possibly a parser installed in a different location because the nvim-treesitter dir wasn't writeable?

(*Ceterum censeo:* We _really_ should stop doing that. Working around Nix idiosyncrasies was a mistake in my view.)

**Comment by mvpopuk** [comment]
@theHamsta no. I am referring to all of the TS available parsers. So this is what happened. I hit `TSInstall all` by accident right so at this point I just wanted to uninstall all and only install the parsers I have specified in `ensure_installed = { ... }` (which are 14 or so). I ran `TSUninstall all` and quit neovim. When opening neovim again, it started to install **ALL** of the parsers ... 90 something parsers. After debugging this for some time, I found out that neovim was reading the parsers from somewhere else and not from my plugins folder. That folder is `./local/share/nvim/...`. So in there I had bunch of `treesitter` folders and parsers and whatnot. I had to manually delete everything that had `treesitter` in the name and run `TSUninstall all` again and restart neovim and only then it installed only the parsers that I have in my treesitter config in `ensure_installed = { ... }`. 

You can reproduce this by just following the steps above.

**Comment by clason** [comment]
Are you using impatient, or Packer `config = ...`?

The `.local/share/nvim/.../nvim-treesitter/parsers` is the correct directory where all parsers should be installed.

**Comment by mvpopuk** [comment]
I use `Plug` and this is my `treesitter` config:

```lua
 require('nvim-treesitter.configs').setup {
  ensure_installed = {
         "yaml",
         "markdown",
         "comment",
         "css",
         "html",
         "javascript",
         "json",
         "lua",
         "php",
         "phpdoc",
         "regex",
         "scss",
         "vim",
         "vue",
     },
  highlight = {
    enable = true,
    disable = { "html", "bash" },
  },
  indent = {
    enable = true,
  },
}

```

**Comment by clason** [comment]
Where do you install the plugins? Are the directories write-protected in some way? What platform are you on?

**Comment by clason** [comment]
To be clear, `:TSUninstall` should have removed them; if it didn't, that's a bug. The reinstalling is _very_ likely to be because somehow the config with `ensure_installed = 'all'` was cached somewhere, because that's the only thing that would automatically install parsers.

Again, without knowing a lot more about your config, it's hard to say.

**Comment by mvpopuk** [comment]
I'm on `macOS Big Sur` , the plugins are installed in ./config/nvim/plugged` and this folder has `Read & Write` permissions. I use `NVIM v0.7.0-dev+1292-ge9b53f3f` but a buddy of mine was able to reproduce this on Neovim's latest stable version as well.

**Comment by clason** [comment]
That sounds good. Would you please open a new bug report with these minimal reproducible steps?
