### ISSUE TITLE
Treesitter not removing the parsers when running `TSUninstall all`

### ISSUE THREAD

**Issue by mvpopuk** [nvim-treesitter/nvim-treesitter#2777]
### Describe the bug

I ran `TSInstall all` by accident so that installed all parsers. I wanted to get rid of all of them so I ran `TSUninstall all` and I restarted neovim. When opened neovim again, `TS` started to install everything back even tho I uninstalled everything. When running `TSInstallInfo` it was showing all of the parsers being installed. The only workaround was to delete everything with `treesitter` in their name from `local/share/nvim/...` 

### To Reproduce

1. Run `:TSInstall all`
2. Restart Neovim
3. Run `:TSUninstall all`
4. Restart Neovim

### Expected behavior

When opening Neovim again (after you ran `:TSUninstall all`), it will start to install all of the parsers back ignoring what you have in `ensure_installed = {}`. 

_If you run `:TSInstallInfo` after running `:TSUninstall all` you will still see all of the parsers being installed._

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.1 (062421dece3315bd6f228ad6d468cba083d0a2d5) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v15.14.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.0.0 (clang-1300.0.29.30)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.
```

### Output of `nvim --version`

```text
NVIM v0.7.0-dev+1292-ge9b53f3fb
Build type: Release
LuaJIT 2.1.0-beta3

_ps: I was able to reproduce this behaviour on the latest Neovim stable version as well_
```

### Additional context

- I am on `macOS Big Sur`
- I use `Plug` for installing the plugins:
```vim
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
``` 
- The plugins are installed in `/config/nvim/plugged/` and I have `Read & Write` permissions for this folder
- My treesitter config:
```lua
 require('nvim-treesitter.configs').setup {
  ensure_installed = {
         "yaml",
         "markdown",
         "comment",
         "css",
         "html",
         "javascript",
         "json",
         "lua",
         "php",
         "phpdoc",
         "regex",
         "scss",
         "vim",
         "vue",
     },
  highlight = {
    enable = true,
    disable = { "html", "bash" },
  },
  indent = {
    enable = true,
  },
}

```

**Comment by clason** [comment]
I cannot reproduce that. Please add a _complete_ config I can test with `nvim --clean -u minimal.vim` (see the issue template).

**Comment by theHamsta** [comment]
It should only install when there is some call to `ensure_installed`. Maybe you need to run PackerCompile to update your config.

**Comment by mvpopuk** [comment]
@theHamsta I use `Plug` not `Packer` and I removed the `nvim-treesitter` plugin and installed it back again and without me running any install / update commands, it started to install al of the parsers back on.

**Comment by clason** [comment]
Again, please provide a self-contained, minimal, reproducing config. Otherwise there's nothing we can do here but guess (incorrectly).

**Comment by mvpopuk** [comment]
@clason I mentioned the steps you have to take to reproduce this right above in my initial bug report. There's nothing more to it.

[My dotfiles](https://github.com/mvpopuk/dotfiles/tree/main/nvim) 

## To Reproduce
1. Run `:TSInstall all`
2. Restart Neovim
3. Run `:TSUninstall all`
4. Restart Neovim
## Expected behaviour
When opening Neovim again (after you ran `:TSUninstall all`), it will start to install all of the parsers back ignoring what you have in `ensure_installed = {}`.

If you run `:TSInstallInfo` after running `:TSUninstall all` you will still see all of the parsers being installed.

**Comment by clason** [comment]
And I already mentioned that I cannot reproduce this problem with (just) the steps you mentioned, so clearly more is needed. That config is also far from minimal, and I will not look through all your files for potential bad interactions for you.

**Comment by mvpopuk** [comment]
@clason it isn't any bad interactions between plugins, someone else was able to reproduce it as well.

**Comment by clason** [comment]
Well, maybe _they_ can provide the needed minimal reproducing steps then. Without them, nothing can be done here.

**Comment by mvpopuk** [comment]
@clason "Please add a complete config I can test with nvim --clean -u minimal.vim (see the issue template)." - I am not able to find that.

**Comment by jesseleite** [comment]
Hey @clason! 🙂 👋

I don't see a minimal config in the issue template either, but ripped the minimal.lua example from telescope's repo template and [created this](https://gist.github.com/jesseleite/3331f3eb6668c94dc97877419db2c9b8).

That said, I can't reproduce this issue with minimal.lua (can you @mvpopuk?). I wonder if it could have something to do with vim-plug over packer, will have to play with this 🤔

Also, I notice `:help --clean` mentions no shada file is read or written when running `nvim --clean`. Does treesitter use a shada file for anything?

**Comment by clason** [comment]
> I don't see a minimal config in the issue template either, but ripped the minimal.lua example from telescope's repo template and [created this](https://gist.github.com/jesseleite/3331f3eb6668c94dc97877419db2c9b8).

That's on me -- I distinctly remember adding a minimal config template at some point, but must have confused this with one of the other orgs (too many orgs...)

> That said, I can't reproduce this issue with minimal.lua (can you @mvpopuk?). I wonder if it could have something to do with vim-plug over packer, will have to play with this 🤔

That's a useful data point -- I'm fine with a `minimal.lua`  (or `minimal.vim`) that uses `vim-plug`, as long as I can reproduce the issue.

Let me be clear: it's possible that nvim-treesitter will leave parsers around if it is installed in an unexpected location, but I don't see _any_ way from the code that it will automatically install parsers unless they are explicitly listed in an `ensure_installed` key for `setup`.

> Also, I notice :help --clean mentions no shada file is read or written when running nvim --clean. Does treesitter use a shada file for anything?

I don't think so, at all.

**Comment by nolantait** [comment]
Same issue here. Happened after trying to go from `ensure_installed = { "all" }` to a list of specific languages.

I tried wiping my neovim cache, local plugins, basically reinstalling from scratch and it seems to persist.

Notably in when I run `:TSConfigInfo` it shows `ensure_installed = {}` on the top level config even though I have it specified correctly in my config.

**Comment by minijackson** [comment]
I have a similar issue of having parsers in my `ensure_installed` config, and nvim-treesitter will try to install them, report that it successfully installed them, but `:TSInstallInfo` reports that they are not available. I think that the `--clean` option is the offender, since I've noticed it removes things like `~/.config/nvim`, `~/.local/share/nvim`, `~/.local/share/nvim/site` from `runtimepath`, and nvim-treesitter uses the last one to install the `.so` files.

Adding `~/.local/share/nvim/site` to `runtimepath` again fixes my issues. For you Lua people:

```lua
vim.opt.runtimepath:append "~/.local/share/nvim/site"
```

**Comment by clason** [comment]
`nvim --clean` is a debug option introduced for reproducible bug reports. it should not be used in normal operation!

**Comment by clason** [comment]
(You're not using Nix, are you?)

**Comment by minijackson** [comment]
I'm personally using a combination of Nix-configured neovim (for parsers that are available in nixpkgs), and config in `~/.config/nvim` to have a faster edit cycle on my own nvim plugins and custom tree-sitter parsers.

**Comment by clason** [comment]
Ah. Good luck with that. (We can't support Nix, sorry. It's just too intrusive.)

**Comment by minijackson** [comment]
Welp, for some reason I thought I was on the nixpkgs bug tracker, sorry about that ^^'

**Comment by clason** [comment]
I didn't mean it quite as literally: we cannot support nvim-treesitter when using the Neovim Nix package, as this makes too intrusive changes (like forcing `--clean`). This plugin is only guaranteed to work on the official Neovim builds.

**Comment by minijackson** [comment]
No worries, I think lots of Nix users are quite used to that, and will normally report these kind of issues in the Nix packages repo. Sorry again for the confusion

**Comment by minijackson** [comment]
Although, one sanity check that could be done, is to check that `stdpath("data") + "/site"` is in `runtimepath`. It might save some trouble outside of Nix users too

**Comment by clason** [comment]
Note that parser location is now fully and explicitly configurable. I think that this is the better approach here.
