### ISSUE TITLE
Typo in issue template for highlighting issues

### ISSUE THREAD

**Issue by cionx** [nvim-treesitter/nvim-treesitter#2787]
The issue template for highlighting issues features a section `Example screenshot`, whose description reads as follows:

> Please provide a screenshot of the current highlighting. Please also tell us the `:h colorscheme` you are using
> and how to install it. If applicable, you can also upload a screenshot with the contents of
> `:TSHighlightCapturesUnderCursor'.

It seems to me that the last line should be `` `TSHighlightCapturesUnderCursor` `` instead of `` `:TSHighlightCapturesUnderCursor' ``, i.e., there seems to be a typo that replaces the closing backtick `` ` `` by the apostrophe-quote `` ' ``.

**Comment by clason** [comment]
Yup. Want to make a PR?
