### ISSUE TITLE
Local variable use 'Identifier' as group highlight.

### ISSUE THREAD

**Issue by PangPangPangPangPang** [nvim-treesitter/nvim-treesitter#280]
In the latest version, it seems like local variable se 'Identifier' as group highlight. It looks like as below, but previous version looks normal.
![image](https://user-images.githubusercontent.com/8207475/89882407-5f463e00-dbf9-11ea-8930-abc1e4d55448.png)

**Comment by vigoux** [comment]
Hi, what is the issue here ?

**Comment by PangPangPangPangPang** [comment]
> Hi, what is the issue here ?

I think local variable should use default white color.

**Comment by vigoux** [comment]
Then I highly suggest adding the following to your config :
```
highlight! link TSVariable Normal
```

I think that this is more a colorscheme issue tbh.

**Comment by theHamsta** [comment]
I guess most colorscheme use a very aggressive highlighting for Identifier. We had a discussion over that before. Back then, we decided to use Normal over Identifier. I guess we have to leave that to user configuration as there's no easy way to find a compromise.

**Comment by PangPangPangPangPang** [comment]
> I guess most colorscheme use a very aggressive highlighting for Identifier. We had a discussion over that before. Back then, we decided to use Normal over Identifier. I guess we have to leave that to user configuration as there's no easy way to find a compromise.

Yes. I test several colorscheme, all of them can't distinguish between variables and attributes.

**Comment by vigoux** [comment]
Do you want us to do a specific action regarding this issue, or do you think leaving that to user configuration is fine ?

**Comment by PangPangPangPangPang** [comment]
> Do you want us to do a specific action regarding this issue, or do you think leaving that to user configuration is fine ?

I think the alternative configuration of the plug-in should be friendly to most users. For me, I can accept two treatments

**Comment by theHamsta** [comment]
I would also prefer returning to the old defaults. Simply because highlighting means givening different things different colors. Would be a pity if all the other stuff with Identifier would get lost.

**Comment by vigoux** [comment]
The old default meaning `Normal` here ?

**Comment by PangPangPangPangPang** [comment]
Maybe `None` is better.
