### ISSUE TITLE
Improving python folding

### ISSUE THREAD

**Issue by wookayin** [nvim-treesitter/nvim-treesitter#2804]
I feel treesitter's default folding behavior for python files is quite confusing and could be improved.

Currently, [the folds definition for python](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/python/folds.scm) allows the 'body' block in a function/class definition to fold, as well as in a while/for/if/with/try statement, but not the entire statement or region itself.

<img width="720" alt="image" src="https://user-images.githubusercontent.com/1009873/163659033-ec537e71-b2f6-423f-bd77-59652881a41f.png">

For instance, you cannot fold a two-line method (when foldminlines=1) into one visible line. When you try closing the fold on the function definition (e.g., Line 3 and 7 in the above example), it will fold the entire body of the `Foo` class rather than the current method. This is very confusing and frustrating behavior for me.

Compare to other languages: ruby, go, etc; treesitter syntax for most languages allow folding of the function/class or block statements into a single line.

![image](https://user-images.githubusercontent.com/1009873/163659072-b87ef6f9-00d8-42e2-bae1-ccf81093545f.png)

```diff
 Folding in Go language:
-func main() {
-    fmt.Println("Hello, World")
-}
+func main() {...}  ------------------ 3 lines
```

### Describe the solution you'd like

This is what python folding should look like:

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/1009873/163659224-a8bfc536-b5be-44e4-ac30-03754ebdc87e.png">

It is actually not that difficult to achieve this behavior:

```diff
diff --git queries/python/folds.scm queries/python/folds.scm
-(function_definition (block) @fold)
-(class_definition (block) @fold)
-
-(while_statement (block) @fold)
-(for_statement (block) @fold)
-(if_statement (block) @fold)
-(with_statement (block) @fold)
-(try_statement (block) @fold)
 
 [
+  (function_definition)
+  (class_definition)
+
+  (while_statement)
+  (for_statement)
+  (if_statement)
+  (with_statement)
+  (try_statement)
+
 ...
```

(Note: this is not the final proposal -- see other notes below)

I would be happy to make a PR once we get to a consent, but my questions would be: Looking at other syntax and fold query files, I see python is the only language where folding applies only on the "body" block. Why is that? If there is no specificreason, shall we allow entire function/class definition regions can be folded.

When it comes to other statements, one would still want to fold the body region only. For instance:
```
try:
+ -- long statements            (10 lines)
except:
+ -- handle exceptions            (7 lines)
finally:
+ -- free resources              (3 lines)
```
v.s.
```
try:  except:  finally:               (23 lines)
```
(the above example assumes one have some smart foldtext)

We could allow both by having some nested folding, but this could feel too much depending on one's taste.

**Comment by wookayin** [comment]
Cc'ing @stsewd and @vigoux who are the authors of https://github.com/nvim-treesitter/nvim-treesitter/commit/bdf43b15df799ae12fadd4eb214e13704454dd98.

**Comment by wookayin** [comment]
Found a relevant discussion https://github.com/nvim-treesitter/nvim-treesitter/pull/390#issuecomment-688442597

I would agree with folding the body only is readable given highlight of folds is not yet possible (https://github.com/neovim/neovim/issues/12649), but I think some people will still prefer the proposed behavior as it gives more control over the folded region. While it remains controversial, I believe the default, built-in folding behavior should be **consistent** across different languages; in case the former style is preferred, users could override query scm to their taste.

**Comment by theHamsta** [comment]
i would agree with @wookayin since the one line-after behavior can easily derived from the proper function/class range which is not possible vice-versa inc case of multi-Line signatures (+1 line would still always show you the function name)

**Comment by wookayin** [comment]
Thanks! I think we can bring up and revisit #1451 again given the essentially same PR is already there.
