### ISSUE TITLE
TSInstall xxx error  Tips ->  No C compiler found! "cc", "gcc", "clang", "cl", "zig" are not executable.

### ISSUE THREAD

**Issue by JoeABCDEF** [nvim-treesitter/nvim-treesitter#2811]
### Describe the bug

execute command   No C compiler found! "cc", "gcc", "clang", "cl", "zig" are not executable.

### To Reproduce

tsInstall css

### Expected behavior

![image](https://user-images.githubusercontent.com/39638510/163670513-432c83ae-78f8-4969-a993-dd404b5bdee5.png)

### Output of `:checkhealth nvim-treesitter`

```markdown
vim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found (unknown version) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.14.2 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - ERROR: `cc` executable not found.
    - ADVICE:
      - Check that any of { vim.NIL, "cc", "gcc", "clang", "cl", "zig" } is in your $PATH or set the environment variable CC or `require"nvim-treesitter.install".compilers` explicitly!
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
```

### Output of `nvim --version`

```text
0.6.1
```

**Comment by clason** [comment]
So, _do_ you have a C compiler installed and on your `$PATH`?

**Comment by JoeABCDEF** [comment]
> 

no,  Install those dependencies. Do you have a website

**Comment by clason** [comment]
Did you read the [README](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/README.md)?

**Comment by JoeABCDEF** [comment]
> Did you read the [README](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/README.md)?

I read it. I'm sorry, but I didn't find the relevant content. It's the first time that I don't understand it

**Comment by clason** [comment]
So, first question: What platform are you on? (Windows, Linux, macOS -- be as detailed as you can!)

**Comment by JoeABCDEF** [comment]
windows

**Comment by clason** [comment]
Then please read https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support

**Comment by VuongTran21** [comment]
hi @clason , I have the same issue, my platform is Linux (Ubuntu 21.04), I can not found any thing on `Linux support`, could you please take a look?

Thanks

**Comment by clason** [comment]
> `Check that any of { vim.NIL, "cc", "gcc", "clang", "cl", "zig" } is in your $PATH or set the environment variable CC or `require"nvim-treesitter.install".compilers` explicitly!`

**Comment by JoeABCDEF** [comment]
> 然后请阅读https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support

thanks

**Comment by VuongTran21** [comment]
> > `Check that any of { vim.NIL, "cc", "gcc", "clang", "cl", "zig" } is in your $PATH or set the environment variable CC or `require"nvim-treesitter.install".compilers` explicitly!`

thanks, my problem solved

**Comment by damingerdai** [comment]
i alos meet this issue in wsl...

**Comment by damingerdai** [comment]
> i alos meet this issue in wsl...

fixed by run `sudo apt-get install gcc`
