### ISSUE TITLE
Usage highlighting does not work with variable shadowing

### ISSUE THREAD

**Issue by steelsojka** [nvim-treesitter/nvim-treesitter#282]
**Describe the bug**

When variables are defined with the same name in a lower scope usage highlighting highlights them even though they aren't correct usages.

![Screen Shot 2020-08-11 at 12 59 09 PM](https://user-images.githubusercontent.com/2062154/89932137-c6043100-dbd2-11ea-9ca0-d8a1c765ee43.png)

**To Reproduce**
Use this code:

```javascript
import { test } from 'test';

const a = 'test';

function(a) {
  console.log(a);

  return function(a) {
    return a;
  }
}

a = 'test'
```

Put cursor on the first `a` definition

**Expected behavior**
Only `a = 'test'` should have it's usage highlighted

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

Paste the output here

</code>
</details>

**Output of `nvim --version`**
```
Paste your output here
```

**Additional context**

**Comment by steelsojka** [comment]
I've looked into this issue and it seems a hard one to solve. We need to determine the definition for each reference and see if it's the same as the definition of the node we have highlighted. This get's VERY expensive since `find_definition` has to check each definition and it's scope.

**Comment by vigoux** [comment]
I think we need to to some kind of sprint focusing on locals, definitions and so on.
Starting from scratch may help us to have better results afterwards.

**Comment by steelsojka** [comment]
I have a refactor that may help here with definitions and references... I'll see how it turns out.

**Comment by theHamsta** [comment]
A note for this: two definitions in same scope should probably not count as shadowing (or should it?)

In python and rust you can do:
```python
a = 1
a = a + 1
```
```rust
let a = 1;
let a = a + 1;
```

**Comment by vigoux** [comment]
I guess that the problem occurs for Python only, because. the `let` keyword in Rust really means shadowing here.

**Comment by theHamsta** [comment]
In Rust, it should probably count as shadowing.

Maybe I can add "set!" attribute to show @steelsojka that a python "definition" will not shadow if it's in same scope (except `global`, `nonlocal` is used)

**Comment by steelsojka** [comment]
I'll have to experiment with that one. I'm gonna test this with #284 and see if the issue still exists... I'm curious how it will behave.

**Comment by steelsojka** [comment]
@theHamsta So would the definition be the one that occurs first? If definitions collide within the same scope we could just take the one that occurs first.

**Comment by vigoux** [comment]
T would say take the closest before the current reference (in the current scope of course...).

**Comment by steelsojka** [comment]
@vigoux  I think this is the default behavior with #284 
@theHamsta I think for #170 and your python scenario we can handle that in another PR. I recreated it and seems a little tricky. I think a special `tag` would probably be the solution.

**Comment by theHamsta** [comment]
> @theHamsta So would the definition be the one that occurs first? If definitions collide within the same scope we could just take the one that occurs first.

would be nice if that could work for python. I could explicitly mark such definitions in the Python queries. I does not make sense to count each assignment as a new definition.
