### ISSUE TITLE
Include parser URL in lockfile

### ISSUE THREAD

**Issue by clason** [nvim-treesitter/nvim-treesitter#2827]
Currently, the lockfile only contains the commit hash of a parser. This is fine for the most part, but if we switch parsers for a language in `parsers.lua`, this will not be picked up by `:TSUpdate`, leading to a broken installation.

Instead, the lockfile should contain the full URL of the parser (repo _and_ branch), and that should be checked (and kept updated via the CI action).

**Comment by theHamsta** [comment]
Can maybe implemented that along with a consoled version of different versions of how ABI compatibility can be solved. So I would include repo URL and ABI version if pre-generated.

**Comment by clason** [comment]
Coming back to this, moving URL to the `lockfile` is not the right way of solving the actual issue (`:TSUpdate` doesn't see repo changes).

Instead, it's enough to store the `url` in the `parser-info` file and check it against `parsers.lang.install_info.url`.

**Comment by clason** [comment]
Actually, I'm not convinced this is as an actual problem, since switching the repo will necessarily require changing the commit hash for HEAD. (The _real_ issue is that PRs switching repos tend to forget that, and the effect is a very obscure CI failure.)

**Comment by theHamsta** [comment]
> Coming back to this, moving URL to the `lockfile` is not the right way of solving the actual issue (`:TSUpdate` doesn't see repo changes).
> 
> Instead, it's enough to store the `url` in the `parser-info` file and check it against `parsers.lang.install_info.url`.

The `lockfile.json` is the part of the Lua data that needs to be hot-reloaded. With the parser info in-separate files, hot-reloading the parser info would be easier and more targeted (just reload the updated parser instead of all of nvim-treesitter). The problem currently is that you're trying to load data of a updated nvim-treesitter while nvim has still the old nvim-treesitter loaded.

**Comment by clason** [comment]
Hot-reloading is not supported in Neovim, period. If any part of your config changes, you should restart. (That's not the problem I was trying to solve here.)

And we tried that (splitting up `parsers.lua`) on `main`, but that led to an inacceptable performance regression since you need to loop over all configs to build a list of parsers to install (or ignore) based on tiers.

**Comment by theHamsta** [comment]
> Hot-reloading is not supported in Neovim, period. If any part of your config changes, you should restart. (That's not the problem I was trying to solve here.)
> 
> And we tried that (splitting up `parsers.lua`) on `main`, but that led to an inacceptable performance regression since you need to loop over all configs to build a list of parsers to install (or ignore) based on tiers.

`lockfile.json` and other non-Lua data is hot-reloadable and this is how `TSUpdate` works. Also imperative code that is not loaded via require but just executed (e.g. `luafile`) can be executed multiple times. `TSUpdate` could defer the update just to the next reloaded to.

The model is a bit fuzzy here: the revision is data while everything else is Lua config. The problem of inconsistent state wouldn't occur if everything was Lua or everything was json data.

**Comment by clason** [comment]
Indeed, if we moved everything to json (or `loadfile`d the parser config including the revision), that would be cleaner. However, this would muddy up the current split between manual changes (`parsers.lua`) and automated changes (`lockfile.json`, which is in JSON for this very reason). None of the options is clearly better than the others, and what we currently have works sufficiently well.

**Comment by theHamsta** [comment]
> Indeed, if we moved everything to json (or `loadfile`d the parser config including the revision), that would be cleaner. However, this would muddy up the current split between manual changes (`parsers.lua`) and automated changes (`lockfile.json`, which is in JSON for this very reason). None of the options is clearly better than the others, and what we currently have works sufficiently well.

They two sets of information wouldn't need to be necessarily in the same file. They would just need to be treated by the plugin the same way (both lua or both JSON).
