### ISSUE TITLE
Support org files

### ISSUE THREAD

**Issue by TerseTears** [nvim-treesitter/nvim-treesitter#2841]
[Org files and Orgmode](https://orgmode.org)

> Org is a highly flexible structured plain text file format, composed of a few simple, yet versatile, structures.

There is already a parser for org files, the [tree-sitter-org](https://github.com/milisims/tree-sitter-org) parser maintained by @milisims. It seems pretty complete. I manually added it to the list of parsers ([here](https://github.com/nvim-treesitter/nvim-treesitter/blob/62fa8f77c43ed3a4ac2bbdfa4327f6b4a835bbea/lua/nvim-treesitter/parsers.lua)) in a local clone:

```lua
list.org = {
  install_info = {
    url = "https://github.com/milisims/tree-sitter-org",
    revision = "main",
    files = { "src/parser.c", "src/scanner.cc" },
  },
  maintainers = { "@milisims" },
}
```

And it worked as expected. Can the parser be supported by `nvim-treesitter`, and if so, are there any other code modifications required?

Possibly related to milisims/tree-sitter-org#18 and stevearc/aerial.nvim#83.

**Comment by clason** [comment]
added it to the tracking issue (which contains more information)

**Comment by clason** [comment]
If it works well locally, just make a PR -- you can look at previous PRs that added a language to see what is needed.

**Comment by wylited** [comment]
has anyone done this? if not I can do it now.
