### ISSUE TITLE
Support ensure_installed "not much": Install all parsers except few named ones

### ISSUE THREAD

**Issue by reportaman** [nvim-treesitter/nvim-treesitter#2843]
At the moment,

ensure_install="maintained" is deprecated and hijacks nvim at launch time:
https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1094250553
https://github.com/nvim-treesitter/nvim-treesitter/issues/2836

ensure_install="all" is not recommended because it also hijacks nvim at launch time:
https://github.com/nvim-treesitter/nvim-treesitter/issues/2837#issuecomment-1102197187

ensure_install= {<hundred_of_individual_names>} is the recommended solution. But it is not thoughtful, and is a config bloat (config bloat is a neovim plugin ecosystem zeitgeist, if we haven't observed it yet). Like why should a user list hundreds of names when all they want is to install all except one or few parsers causing install problem?

So, the proposal is to simplify ensure_install to accept negative names like this:

ensure_install = {"all", "-phpdoc", "-ruby"} to install all except a few.

**Comment by clason** [comment]
Sorry, we discussed this, but there's no objective list of parsers that would be reasonable to maintain.

(And I submit that adding hundreds of tree-sitter parsers of widely varying quality -- no matter whether manually or via a convenience option -- is the very essence of bloat. Please accept that the goal of this project is _not_ "Polyglot 2.0".)
