### ISSUE TITLE
Disabling highlight module always turns vim's syntax back on

### ISSUE THREAD

**Issue by jaekyeom** [nvim-treesitter/nvim-treesitter#2846]
### Describe the bug

Hi,

I'm not quite sure if I should call this a "bug", but I noticed that [disabling the highlight module always turns vim's syntax back on](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/highlight.lua#L150).

I believe this is intentional, but I think at least the user should have an option to choose whether it turns vim's syntax on or not when disabled.

If the user only manually disables the highlight module, then the user can turn syntax off manually as well just by using two commands instead of one command.

However, if some code (e.g., one of the installed plugins) disables treesitter's highlight module somehow algorithmically (e.g., [coq_nvim](https://github.com/ms-jpq/coq_nvim)), then the user has no choice but turning syntax off manually every time that happens.

### To Reproduce

1. Open a file with treesitter's highlight support
2. `:ownsyntax off`
3. `:TSBufDisable highlight`
4. Then, vim's built-in syntax is on again..

### Expected behavior

I wouldn't say that not turning syntax on is the expected behavior, but I think the user should be able to choose.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v15.0.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - c              ✓ ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - bibtex         ✓ . ✓ ✓ . 
  - bash           ✓ ✓ ✓ . ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - latex          ✓ . ✓ . ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - markdown       ✓ . ✓ . ✓ 
  - comment        ✓ . . . . 
  - regex          ✓ . . . . 
  - javascript     ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.7.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az316-460

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
I think the vast majority of users _expect_ that disabling treesitter highlighting reverts to legacy highlighting (just like enabling treesitter highlighting disables legacy highlighting). Adding an option would significantly increase code complexity (and user friction) for comparatively very little gain.
