### ISSUE TITLE
Raw string literals should be treated the same as string literals while highlighting in c++

### ISSUE THREAD

**Issue by hashinclude** [nvim-treesitter/nvim-treesitter#286]
**Describe the bug**
Raw string literals get a different color than string literals. 

**To Reproduce**
<img width="1680" alt="Screen Shot 2020-08-13 at 12 27 30 AM" src="https://user-images.githubusercontent.com/1989695/90106094-c9470c00-dcfb-11ea-91d5-924fe7d80a0d.png">

**Expected behavior**
Both the string literal and raw string literal should be green in color. 

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

## cpp parser healthcheck
  - OK: cpp parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-627-g94b7ff730
Build type: Debug
LuaJIT 2.1.0-beta3
```

**Additional context**
I played around with this a bit on the [treesitter playground](https://tree-sitter.github.io/tree-sitter/playground), and it correctly identifies the string literal and raw string literal.

**Comment by vigoux** [comment]
@theHamsta, that seems related to cpp queries.
