### ISSUE TITLE
Wrong indentation in multiline comments with tree-sitter-php

### ISSUE THREAD

**Issue by przepompownia** [nvim-treesitter/nvim-treesitter#2873]
### Describe the bug

Incorrect indentation is inserted to multiline phpdoc comment after installing 'php' extension. The initial indentation does not matter.
```
<?php

/**
*  no leading space here
 */
```

### To Reproduce

1. Open nvim with `nvim-treesitter` installed only and the following minimal config:

```lua
require'nvim-treesitter.configs'.setup {
  indent = {
    enable = true,
  },
}
```
2. Open `test.php` with
```
<?php

/**
 */
```
3. go to the line with `/**` then press `o` to insert some content inside the comment.
4. see that indentation is correct i.e. one leading space is inserted
```
<?php

/**
 *
 */
```
5. undo the change then run `TSInstall php` and repeat step 3. 
6. see no leading space as shown in the description. 

### Expected behavior

The correct amount of spaces is inserted inside the comment. 

In my real environment I have also `phpdoc` installed. Currently it does not support indentation. On the other side it both does not cause this bug and does not fix it. Probably the problem is on nvim-treesitter or treesitter-php side. 

While the bug exists I would like to disable indentation inside PHP comments. I found https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/php/indents.scm#L17-L19 
```
[
  (comment)
] @ignore
```
What does it mean if not what I expect? I am beginner in tree-sitter domain. 

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (ccd6bf554d922596ce905730d98a77af368bba5c) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.9.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.                                                                                                        
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Debian 11.3.0-1) 11.3.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - php            ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```
```


### Output of `nvim --version`

```text
NVIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -ffile-prefix-map=/home/test/dev/external/neovim-launchpad/neovim-0.7.0~ubuntu1+git202204211627-28fb40b16-dd05b3569=. -fstack-protector-strong -Wformat -Werror=format-security -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/test/dev/external/neovim-launchpad/neovim-0.7.0~ubuntu1+git202204211627-28fb40b16-dd05b3569/build/config -I/home/test/dev/external/neovim-launchpad/neovim-0.7.0~ubuntu1+git202204211627-28fb40b16-dd05b3569/src -I/home/test/dev/external/neovim-launchpad/neovim-0.7.0~ubuntu1+git202204211627-28fb40b16-dd05b3569/.deps/usr/include -I/usr/include -I/home/test/dev/external/neovim-launchpad/neovim-0.7.0~ubuntu1+git202204211627-28fb40b16-dd05b3569/build/src/nvim/auto -I/home/test/dev/external/neovim-launchpad/neovim-0.7.0~ubuntu1+git202204211627-28fb40b16-dd05b3569/build/include            
Compiled by test@wc  

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
```


### Additional context

_No response_

**Comment by kyazdani42** [comment]
I think this will be a similar issue for most 'doc' comments. Phpdoc is parsed as comment. @theHamsta should we ignore comment indentation in every language ? I can't remember if we made a design choice about this.

**Comment by theHamsta** [comment]
@kyazdani42 we ignore `phpdoc` and `comment` as comment parser in the indent module

**Comment by rodrigues-i** [comment]
Maybe this answer helps you:
https://github.com/nvim-treesitter/nvim-treesitter/issues/462#issuecomment-700278736

I desabled treesitter indentation for php and changed noautoindent and nosmartindent to autoindent and smartindent in indent/php.vim

**Comment by przepompownia** [comment]
@rodrigues-i thanks for the example although it would be good to have treesitter indentation working everywhere except comments. Isn't it possible or doesnt' below code work?
```
[
  (comment)
] @ignore
```

**Comment by theHamsta** [comment]
@przepompownia well, you can try it out and submit a pull request with tests that get fixed with your addition. For other languages we had `(comment) @auto` to make indentation of `*` after `/*` work. If your method works we're happy to accept a PR.

**Comment by przepompownia** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/php/indents.scm#L17-L19

As an almost complete tree-sitter beginner I am still even not sure what is the expected behavior of this instruction (especially if it should prevent from indentation inside comment area). At the moment I need some explanation more than you can expect any solution from me :grin: 

On the other side, even if we were able to disable indentation per specific comment line, we had further native vim indentation  disabled by nvim-treesitter (because `indentexpr` would be still attached to treesitter's frunction). Thus it seems that disabling indentation per line would not be useful.

**Comment by theHamsta** [comment]
@przepompownia I'm also not an expert on vim indentation, but `@ignore´ means that we don't touch that line at all and that there will be no indentation. For `@auto`, we return `-1` and then Vim does whatever it thinks it's ok. So if @rodrigues-i advice to turn on smartindent works we maybe need to stay with that

**Comment by przepompownia** [comment]
`@auto` can gives fallback to Vim indentation in a specific area - it's a key basis that I had no idea about - thanks @theHamsta 

I created `after/queries/php/indents.scm` with
```scheme
[
  (comment)
] @auto
```
and left 
```vim
setlocal autoindent
setlocal smartindent
```
with `after/indent/php.vim`. It seems to partially fix the problem and I did not observe any regression. 

It works assuming that nvim-treesitter recgnizes a comment in given place. Given a correct docblock comment 
```php
/**
*/
```
it works as expected but with only starting line
```php
/**
```
it does not work. In such case treesiter-playground marks this line as `error`. @theHamsta is it possible to do similar exclusion on `error`? I'll look into `nvim-treesitter` if such example exists.

**Comment by przepompownia** [comment]
```scm
[
  (comment)
] @auto

(ERROR) @auto
```
seems to work on the first test :tada:

**Comment by theHamsta** [comment]
@przepompownia any suggestions how we can make the default experience with PHP better?
```
[
  (comment)
] @auto

(ERROR) @auto
```
will users have a bad experience without setting `autoindent` and `smartindent` manually?

**Comment by przepompownia** [comment]
@theHamsta without manual after-setting the above I see the same bad experience inside comments as with the current nvim-treesitter indent settings, i.e
```php
    /**
 *
 */
```
Maybe some other people might have a look at both cases: @rodrigues-i 
Considering the proposition of merging I wonder what it would be like if it were turned into treesitter-phpdoc project. Does such settings (inside nvim-treesitter, in opposite to local `after`) override any possible imprvements in treesiter-phpdoc?

**Comment by przepompownia** [comment]
I did not notice any additional issues. From my perspective #2935 can be merged.
