### ISSUE TITLE
Github Sponsor

### ISSUE THREAD

**Issue by TornaxO7** [nvim-treesitter/nvim-treesitter#2879]
**Is your feature request related to a problem? Please describe.**
There's only a link to the open-collective sponsor page.

**Describe the solution you'd like**
A link to the github-sponsor page.

**Describe alternatives you've considered**
Ehm...

**Additional context**
I prefer the github sponsor ship because otherwise I'd have to create a new account on that page. Would that be possible?

**Comment by kyazdani42** [comment]
from what i see it would be feasible with opencollective bank informations

**Comment by vigoux** [comment]
We started the procedure a while ago but got stuck, I'll try to see what I can do.

**Comment by vigoux** [comment]
You should already be able to sponsor the organization when going to it's sponsor page, we just need to add the link in the `sponsor` file in this repository.
