### ISSUE TITLE
Show registered modules in health check

### ISSUE THREAD

**Issue by clason** [nvim-treesitter/nvim-treesitter#2883]
For debugging issues without provided config, it would be very useful if `:checkhealth` could list the enabled (and/or attached) modules, including from external plugins created from the module template.

**Comment by kyazdani42** [comment]
Good idea, i think it would be very useful when people complain about stuff not working but it's actually syntax stuff from nvim :smile:

**Comment by clason** [comment]
Obsolete with the removal of modules for nvim-treesitter 1.0.
