### ISSUE TITLE
install.lua:373: Parser not available for language maintained

### ISSUE THREAD

**Issue by deisignemoon** [nvim-treesitter/nvim-treesitter#2887]
### Describe the bug

Error detected while processing /home/moe/.config/nvim/init.lua:                                                                                                        
E5113: Error while calling lua chunk: ...er/start/nvim-treesitter/lua/nvim-treesitter/install.lua:373: Parser not available for language maintained                     
stack traceback:                                                                                                                                                        
        [C]: in function 'get_parser_install_info'                                                                                                                      
        ...er/start/nvim-treesitter/lua/nvim-treesitter/install.lua:373: in function 'install_lang'                                                                     
        ...er/start/nvim-treesitter/lua/nvim-treesitter/install.lua:419: in function 'ensure_installed'                                                                 
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:388: in function 'setup'                                                                            
        /home/moe/.config/nvim/lua/user/treesitter.lua:6: in main chunk                                                                                                 
        [C]: in function 'require'                                                                                                                                      
        /home/moe/.config/nvim/init.lua:8: in main chunk 

### To Reproduce

1.lastest version of nvim-treesitter
2.the configuration of https://github.com/LunarVim/Neovim-from-scratch

### Output of `:checkhealth nvim-treesitter`

```markdown
48 nvim-treesitter: require("nvim-treesitter.health").check()
   49 ========================================================================
   50 ## Installation
   51   - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
   52   - WARNING: `node` executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
   53   - OK: `git` executable found.
   54   - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
   55     Version: cc (GCC) 11.2.0
   56   - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.
   57
```

### Output of `nvim --version`

```text
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
Please do not spam issues repeatedly. This option was removed after a long deprecation period (which mentioned how to update).

**Comment by geofflangenderfer** [comment]
could you link update instructions? This is the first link for searching for this in issues

**Comment by theHamsta** [comment]
The update instructions are simply that you replace "maintained" with the list of languages you want to install in `ensure_installed`. E.g. `ensure_installed = {'python', 'cpp'}`
