### ISSUE TITLE
Error during "tree-sitter generate"

### ISSUE THREAD

**Issue by piersolenski** [nvim-treesitter/nvim-treesitter#2899]
### Describe the bug

When I try and run `:TSUpdate` or `:checkhealth nvim-treesitter` I get the following error:

```
nvim-treesitter[devicetree]: Error during "tree-sitter generate"
node:internal/modules/cjs/loader:942
  throw err;
  ^
Error: Cannot find module '/opt/homebrew/Cellar/node/17.7.1/pnpm-global/5/node_modules/tree-sitter-cli/cli.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:939:15)
    at Module._load (node:internal/modules/cjs/loader:780:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Node.js v18.0.0
```

I'm assuming from the error it's to do with the fact I'm using a different node version, but I'm not sure why it's specifically looking for `17.7.1`. Even if I set my node version to `17.7.1` or something different with `NVM`, I'm still getting this exact error.

### To Reproduce

1. `:TSUpdate` or `:checkhealth nvim-treesitter`
2. See error

### Expected behavior

It doesn't throw an error.

### Output of `:checkhealth nvim-treesitter`

```markdown
I get the error.
```

### Output of `nvim --version`

```text
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local
```

### Additional context

I'm using homebrew and nvm.

**Comment by theHamsta** [comment]
Two different node installations? One form nvm, one from homebrew? I don't think it's about versions just that they are two separate installations

opt/homebrew/Cellar/node/17.7.1/p  <- node from homebrew

Node.js v18.0.0 <- node from nvm

Can you try to uninstall tree-sitter-cli from homebrew and install it via `nvm` (npm i -g tree-sitter-cli) or `cargo install tree-sitter-cli`?

**Comment by piersolenski** [comment]
In the end I reinstalled neovim via homebrew, which installs treesitter as a dependency, and that seems to have fixed it.

Running `which tree-sitter` still results in `/opt/homebrew/bin/tree-sitter` but it seems to be working now! 🤷‍♀️

**Comment by kyazdani42** [comment]
closing then :)
