### ISSUE TITLE
Compiling *.cc with C compiler gives shared object no personality

### ISSUE THREAD

**Issue by theHamsta** [nvim-treesitter/nvim-treesitter#29]
Hello! Thanks for this awesome plugin.

I have some problem install those parsers who use C++ files (*.cc, e.g. tree-sitter-python). Apparently, linking with a C compiler to libstdc++ is not sufficient.

I get the following error when compiling with the C compiler GCC 9.3 or Clang 11.0:
![image](https://user-images.githubusercontent.com/7189118/80353993-6fb6f080-8876-11ea-8b9c-2583d1480049.png)

`__gxx_personality_v0` is missing :cry: 
 
The problem is solved when I compile the C++ files with g++ instead of gcc or clang++ instead of clang  (e.g. by setting up a small CMake project).

**Comment by kyazdani42** [comment]
Hi, everything works fine on my end. Could you tell me:
- which os are your running, (if linux which kernel version)
if linux:
- `ls /usr/lib* | grep libstdc++` will tell you if libstdc++ is installed properly. If this is the case, which version of it are you using ?

**Comment by theHamsta** [comment]
I am using Ubuntu 20.04 l(inux-headers-5.4.0-26)

➜ ls /usr/lib* | grep libstdc++ 
libstdc++.so.6 -> libstdc++.so.6.0.28
libstdc++.so.6.0.28

I have the problem with
```
/usr/bin/clang-7 -shared -o python.so src/parser.c src/scanner.cc -I./src -fPIC
```
```
/usr/bin/gcc-7 -shared -o python.so src/parser.c src/scanner.cc -I./src
```
```
/usr/bin/gcc-9 -shared -o python.so src/parser.c src/scanner.cc -I./src
```

**Comment by theHamsta** [comment]
Stange

**Comment by theHamsta** [comment]
Ok. It still does not work when compiling within neovim wiht `TSInstall` even if I set the exact same compile arguments by changing the source code of this plugin.

As I said, compiling with `/usr/bin/gcc-9 -shared -o python.so src/parser.c src/scanner.cc -I./src -fPIC -lstdc++` (outside of neovim) works. But `TSInstall python` does not work. Even after changing to excact same arguments. Is the enviroment somehow different when using Neovim jobs? 

```
      cmd = '/usr/bin/gcc-9',
      info = 'Compiling...',
      err = 'Error during compilation',
      opts = {
        args = vim.tbl_flatten({
            '-o',
            'python.so',
            '-shared',
            '-lstdc++',
            '-I./src',
            repo.files
          }),
```

**Comment by kyazdani42** [comment]
could you try `/usr/bin/gcc-9 -shared -o python.so -I./src -fPIC -lstdc++  src/parser.c src/scanner.cc` outside of neovim ? It should behave the same way though.
I have no idea why, this is not specific to neovim's api but to the libuv api.

**Comment by kyazdani42** [comment]
also not every command has a print error, could you try, on line 44:
```lua
    if code ~= 0 then return api.nvim_err_writeln(attr.err or vim.inspect(cmd_list[i + 1])) end 
```

**Comment by kyazdani42** [comment]
I dont think it matters though. 
This might happen because not all files are being compiled.
Could you check the output of `command_list[3].opts.arg` in `run_install` ?

**Comment by theHamsta** [comment]
This fails
```
➜ /usr/bin/gcc-9 -shared -o python.so -I./src -fPIC -lstdc++ src/parser.c src/scanner.cc
14:39:07 in tree-sitter-python on  master [?] is 📦 v0.16.1 via ⬢ v14.0.0 
➜ mv python.so ~/.local/share/nvim/plugged/nvim-treesitter/parser/python.so
````
While the following is working
```
14:39:09 in tree-sitter-python on  master [?] is 📦 v0.16.1 via ⬢ v14.0.0 
➜ /usr/bin/gcc-9 -shared -o python.so -I./src  src/parser.c src/scanner.cc -fPIC -lstdc++
14:39:21 in tree-sitter-python on  master [?] is 📦 v0.16.1 via ⬢ v14.0.0 
➜ mv python.so ~/.local/share/nvim/plugged/nvim-treesitter/parser/python.so
```

I tried both twice. Strange that this makes a difference...

**Comment by theHamsta** [comment]
Both compile without warning. The error only occurcs only on loading:

```
14:41:33 in tree-sitter-python on  master [?] is 📦 v0.16.1 via ⬢ v14.0.0 
➜ /usr/bin/gcc-9 -shared -o python.so -I./src  src/parser.c src/scanner.cc -fPIC -lstdc++

➜ ldd python.so 
        linux-vdso.so.1 (0x00007ffd66cd1000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1496ecd000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1496eb2000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1496cc0000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1496b71000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f1497128000)
```

```
14:50:56 in tree-sitter-python on  master [?] is 📦 v0.16.1 via ⬢ v14.0.0 
➜ /usr/bin/gcc-9 -shared -o python2.so -I./src -fPIC -lstdc++ src/parser.c src/scanner.cc
14:51:03 in tree-sitter-python on  master [?] is 📦 v0.16.1 via ⬢ v14.0.0 
➜ ldd python2.so 
        linux-vdso.so.1 (0x00007ffdacff9000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0ab3eaf000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0ab3cbd000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0ab3f44000)
```

**Comment by theHamsta** [comment]
When moving `-fPIC`, `-lstdc++` to the end, it also works with `TSInstall`. `-fPIC` seems to be required only if using clang.

**Comment by kyazdani42** [comment]
well `-fPIC` is better to have anyway. It is strange that your gcc complains about argument positionning but it happened to me in the past using clang on macos.
