### ISSUE TITLE
[cpp] Make :: punctuation instead of operator?

### ISSUE THREAD

**Issue by adrian5** [nvim-treesitter/nvim-treesitter#2902]
Seems to me that semantically it would be better if the namespace related `::` (e.g. `std::string`) was treated as something like `@punctuation.delimiter` rather than `@operator`.

I noticed because it looks distracting in colorschemes, who often leave punctuation (`.`, `;`) inconspicuous while making operators (`*`, `+`, `=`) stand out.

p.s. Rust seems to [do so](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/rust/highlights.scm#L268) btw.

**Comment by kyazdani42** [comment]
Please make a PR for it :)

**Comment by adrian5** [comment]
Merci!
