### ISSUE TITLE
cc1p no such file or directory and -lstdc++ cannot find

### ISSUE THREAD

**Issue by Jetandarkumar** [nvim-treesitter/nvim-treesitter#2908]
### Describe the bug

![Screenshot from 2022-05-06 02-14-02](https://user-images.githubusercontent.com/73706161/167028183-f6927f20-85e3-4d9c-9540-94c13ddb2f56.png)
![Screenshot from 2022-05-06 02-13-38](https://user-images.githubusercontent.com/73706161/167028195-9582fbf2-56d5-4a22-862c-bee44bdba31e.png)
These are both the Errors 

![Screenshot from 2022-05-06 02-19-48](https://user-images.githubusercontent.com/73706161/167029393-0013f177-cd72-4809-b06e-2735ceec2010.png)

### To Reproduce

1.Go to blah blah blah

### Expected behavior

I expected it to run,of course

### Output of `:checkhealth nvim-treesitter`

```markdown
This health is 4 tests ok screenshot is up above
```

### Output of `nvim --version`

```text
0.7.0
```

### Additional context

gcc  11.1.0
build essentials installed and also updated
clang 10.0.0

Working in Ubuntu 20

**Comment by clason** [comment]
I'm sorry, this is not nearly enough context to go with. It's "working in Ubuntu 20" -- that's nice, but where is it _not_ working? What _is_ the output of `:checkhealth`? Does `cc1plus` etc. work from the command line?

I'm closing this for now and will reopen when the requested information is provided (these templates are there for a reason!)

**Comment by theHamsta** [comment]
`apt install g++`

**Comment by Jetandarkumar** [comment]
> I'm sorry, this is not nearly enough context to go with. It's "working in Ubuntu 20" -- that's nice, but where is it _not_ working? What _is_ the output of `:checkhealth`? Does `cc1plus` etc. work from the command line?
> 
> I'm closing this for now and will reopen when the requested information is provided (these templates are there for a reason!)

Updated the issue context and I don't know how to check if cc1plus and lstdc++ are installed

**Comment by Jetandarkumar** [comment]
> `apt install g++` you will also need the c++ standard library (for the version of your gcc)

by C++ you mean the build essentials ---right. As far as  I know the standard library is in it

**Comment by theHamsta** [comment]
The most effective way is to do a `gcc --version`. You need the same g++ for your your gcc version. E.g. when you installed gcc-8 in addition to build-essentials you will also need g++-8. build-essential will be satisfied with different versions of gcc and g++.

**Comment by Jetandarkumar** [comment]
> The most effective way is to do a `gcc --version`. You need the same g++ for your gcc version. E.g. when you installed gcc-8 in addition to build-essentials you will also need g++-8. build-essential will be satisfied with different versions of gcc and g++. A mismatch was sometimes a problem for issues in the past

Yeah! that was the culprit. I had gcc-11 but g++-10 so after updating to g++-11,It worked fine.Thanks a lot
