### ISSUE TITLE
Add link of parser into readme : version check mecanism for each parser before downloading

### ISSUE THREAD

**Issue by wsdjeg** [nvim-treesitter/nvim-treesitter#292]
**Is your feature request related to a problem? Please describe.**
When install a parser, I want to know what is the parser, and where is it downloaded from, and is it safe?

**Describe the solution you'd like**

add the link of the parser to README file,

**Comment by vigoux** [comment]
Hi and thanks for reporting !

This is effectively a good issue, and as a work around while we link all the parsers, you can can find the parser list in `lua/nvim-treesitter/parsers/lua`.

We (just) need to extract links into the README.

**Comment by vigoux** [comment]
Let's reopen this regarding the safety part of the issue, maybe we can try verifying sha of the parsers we get, before compiling, for a bit more safety.

**Comment by stsewd** [comment]
We should update the title of the issue to reflect the real task that is left, also this isn't a good first issue anymore.
