### ISSUE TITLE
:TSToggle or TSDisable highlight enable default neovim highlights.

### ISSUE THREAD

**Issue by zorgick** [nvim-treesitter/nvim-treesitter#2920]
**Is your feature request related to a problem? Please describe.**

When `:TSToggle` or `:TSDisable` commands are used with **highlight** parameter, 'syntax' option is set to 'ON', enabling default neovim syntax highlighting. This disturbs me a lot, when I really need to switch off any highlighting at all (for fugitive diffs for example). So I always have to execute `:syntax off`, after disabling treesitter highlight.

**Describe the solution you'd like**
Can this behavior be disabled, so that all highlighting is switched off at once?

**Comment by theHamsta** [comment]
At the moment this is not possible. This has probably be managed by language tree https://github.com/theHamsta/neovim/blob/e709f83889ad515359a30cd41a719bafc7852241/runtime/lua/vim/treesitter/highlighter.lua#L184 The language tree could try to restore the state `syntax` had before it got attached to the buffer.

The usecase to not syntax is probably at bit rare. Maybe it's not too much to require a user command that does `:TSDiable | set syntax off`

**Comment by zorgick** [comment]
I've already tried to switch off all syntax with <BAR> commands, like `:TSDiable | set syntax off`, but it seems, that default syntax remains. So anyway I need to call to consecutive commands anyway. Do you use fugitive in your neovim setup? If so how do you manage highlighting with this plugin to see diffs clearly ?

**Comment by zorgick** [comment]
Thank you! Checked it `:TSDiable | set syntax off`, everything works now
