### ISSUE TITLE
Automatically installing parsers

### ISSUE THREAD

**Issue by pyrr** [nvim-treesitter/nvim-treesitter#293]
Hello, is there a way to install a bunch of parsers by default when nvim starts ? 
This would be comfortable for people who carry their init.nvim around.

**Comment by steelsojka** [comment]
You can set this up by setting the `ensure_installed` property on your setup call.

```lua
ensure_installed = { 'typescript' }
```

**Comment by steelsojka** [comment]
I'm gonna close this as resolved. If you are having issues with this, feel free to reopen this issue.

**Comment by pyrr** [comment]
Yep.Thank you. Sorry I missed that in the readme.
Btw what is the difference between a module and a parser ? Aren't they the same thing ?

**Comment by stsewd** [comment]
@pyrr a parser provides a grammar for a language, a module makes uses of the grammars to provide a feature. You can find the defaults in  https://github.com/nvim-treesitter/nvim-treesitter/blob/a9abe2b9b084958ffcbf8a696ced416eff24fbfe/lua/nvim-treesitter/configs.lua#L28, I'm trying to document them at https://github.com/nvim-treesitter/nvim-treesitter/pull/269

**Comment by kyazdani42** [comment]
a module is a feature. A parser is a library used by treesitter to parse source code for a specific language. Thus a module needs a parser to work because it needs to use the tree returned by the parser.

**Comment by kyazdani42** [comment]
all options are specified on the readme or the docs.
