### ISSUE TITLE
why executable not found (parser generator, only needed for :TSInstallFromGrammar, not reguired for :TSInstall) 

### ISSUE THREAD

**Issue by myzjy** [nvim-treesitter/nvim-treesitter#2931]
**Language information**

Please paste any useful information here !
executable not found (parser generator, only needed for :TSInstallFromGrammar, not reguired for :TSInstall)

**Comment by myzjy** [comment]
nvim 0.7

**Comment by clason** [comment]
Please open an actual bug report and fill out the template (which is there for a reason!)

**Comment by clason** [comment]
(Although that will likely get closed as well. Make sure the `tree-sitter` CLI is installed and on you PATH.)

**Comment by myzjy** [comment]
:checkhealth
![image](https://user-images.githubusercontent.com/58101943/168276122-4d84f0ee-6df9-4252-9d25-2c8a2e08588d.png)

**Comment by myzjy** [comment]
Is it a path problem?
