### ISSUE TITLE
vim.TSHighlighter is deprecated

### ISSUE THREAD

**Issue by alexaandru** [nvim-treesitter/nvim-treesitter#294]
**Describe the bug**
Using the latest nvim nightly (v0.5.0-628-gaa48c1c72) I get the _"vim.TSHighlighter is deprecated, please use vim.treesitter.highlighter"_ error. Looks like you are using it here: https://github.com/nvim-treesitter/nvim-treesitter/blob/5a7579c8f5e8edddcce44f477961d111432772d8/lua/nvim-treesitter/highlight.lua#L12 and it was deprecated on nvim 2 days ago, here: https://github.com/neovim/neovim/commit/613068071e02ddf5958fa82974373c370112c5e6

**Expected behavior**
Not to error.

**Comment by vigoux** [comment]
Hi and thanks for reporting!

We have a pull request opened, waiting for review and fixing that : #291.

As soon as this is merged, everything will be fixed.

**Comment by steelsojka** [comment]
This is now fixed in master by #291

**Comment by alexaandru** [comment]
Indeed it is! :)  Thank you for your awesome work. I've been using nvim+lsp+treesitter for over a month now and I absolutely love it.

Have a great day!
