### ISSUE TITLE
Python does not indent properly

### ISSUE THREAD

**Issue by ryan-WORK** [nvim-treesitter/nvim-treesitter#2947]
### Describe the bug

When expecting an indent in python, no indent is produced.

My `treesitter` config looks like this:
```lua
local configs = require("nvim-treesitter.configs")
configs.setup {
  ensure_installed = {"lua", "python", "c"},
  sync_install = false,
  ignore_install = { "" }, 
  autopairs = { enable = true,},
  highlight = {
    enable = true, 
    disable = { "" }, 
    additional_vim_regex_highlighting = true,

  },
  indent = { enable = true, disable = { "yaml",} }, -- ***Indent Enabled***
  context_commentstring = {
    enable = true,
    enable_autocmd = false,
  },
}

```

Example:
```python
if True:
#<----- cursor is here
```

### To Reproduce

1. Work on python file using `nvim-treesitter`
2. Use a keyword that would expect an indent in the next line (if, def, while, etc..)
3. After hitting enter the indent is not provided

### Expected behavior

Example:
```python
if True:
    #<----- cursor is expected to be here
```

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` executable found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.15.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - python         ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.0-dev+67-g0d41c4dee
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1651034582504.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Comment by milanglacier** [comment]
Have the same issue, I am on `nvim 0.7 release`, the treesitter version is `09e73bc72d30ac09ea5300ce6a95c945e96db901`
the following example indent at wrong position:

```python
import pandas as pd
import numpy as np


def b(a=5):
    return np.arange(a)


a = pd.DataFrame({
    'dodadasdasdasdsadasg': b(5),
    'cgdfgdfgdfgdfgdfat': b(5),
    'mdadadsadassddasouse': b(5),
    '_dsadsd': b(5),
    '_fsdfsdfZ_rfsdfsdhfsdf': b(5),
    'fsdfhsjdfkhsdkfhsdkjfhsdjfhsdf': b(5),
    'fsdfsdfsdsdf_24q4q4': b(5)
})| # put cursor at | and type <CR>, the cursor next will go to position at next |
                 | # the position is defenetely wrong
```

**Comment by mangelozzi** [comment]
So excited for treesitter support thank you!

Yes I am also finding issues with python indentation. It often refuses to indent comments, and will put the comments in the first column. If I try to manually tab the comments to the correct indentation, it does not allow me. The only thing that works is adding spaces manually in front of each comment line.
Also it often adds a the closing `}` at the column 1, instead of following the code's indentation. Now that I think about it, it maybe due to syntax errors further above, taking preference over current context, because I see it a lot during refactors. Sorry has been months of frustration, thinking it was the built in vim indentation, so I setup to LSP to fix it, only to find I had setup LSP long ago, and that was issue!

**Comment by garyzhang2002** [comment]
Running into the same issue. After enabling the indentation module, the indentation doesn't work at all in Python files on my end.

**Comment by esn89** [comment]
Running into same issue too.

But I am not running vim-plug.

**Comment by joshbode** [comment]
fa0644667ea7ee7a72efdb69c471de4953a11019 appears to fix this for me! :)

**Comment by esn89** [comment]
THanks @joshbode  will give it a try.

**Comment by theHamsta** [comment]
> [fa06446](https://github.com/nvim-treesitter/nvim-treesitter/commit/fa0644667ea7ee7a72efdb69c471de4953a11019) appears to fix this for me! :)
> 
> I'm seeing some weirdness with decorators, but that's probably for another issue (and much less annoying):
> 
> ```
> class X:
>     @property
>         █ <- cursor ends up here
> ```

Please file this as a separate issue! So we don't forget to fix it.

**Comment by joshbode** [comment]
@theHamsta - something else appears to have fixed that issue! :shrug:
