### ISSUE TITLE
treesitter spell check exception in TS and JS files?

### ISSUE THREAD

**Issue by askfiy** [nvim-treesitter/nvim-treesitter#2969]
I don't know if you have encountered this kind of problem, in `ts` or `js` files, some keywords will be wrongly marked in red.

I use `spellsitter` and set the `additional_vim_regex_highlighting` of `treesitter` to `false`, it gives the following (currently I only tested the `ts` and `js` files), which is surprising ..

![图片](https://user-images.githubusercontent.com/81478335/170836077-9084bdf8-943c-4ba2-ab40-072988867f17.png)

`additional_vim_regex_highlighting` When set to `true` or manually typed `:set syntax=on`, spell checking will be correct.

![图片](https://user-images.githubusercontent.com/81478335/170836091-8619804d-5c76-4e8e-97da-c6adc6a300ea.png)

How should I fix it?

**Comment by askfiy** [comment]
I think they are just wrongly marked because when I press `[s` and `]s` they don't jump to the wrong marked word.

**Comment by kyazdani42** [comment]
sorry but this is the wrong place to ask that question, this seems to be related to spellsitter, not nvim-treesitter.
We disabled syntax with treesitter, because the highlighting would conflicting with nvim-treesitter's one. 
You should open an issue in spellsitter though :)
