### ISSUE TITLE
dart code crashes neovim

### ISSUE THREAD

**Issue by marcusatiliusregulus** [nvim-treesitter/nvim-treesitter#2972]
### Describe the bug

when treesitter parses dart code the editor crashes! when my shell is fish the message is:

```
fish: Job 1, 'nvim file.dart' terminated by signal SIGSEGV (Address boundary error)
```

### To Reproduce

1. have the dart grammer `:TSInstall dart` installed
2. open file.dart
3. in insert mode type 'v'
4. nvim crashes

### Expected behavior

editor does not crash

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.2.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - dart           ✓ ✓ . ✓ ✓·

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.0-dev+334-ge9803e1de
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/auser/.cache/paru/clone/neovim-git/src/build/config -I/home/auser/.cache/paru/clone/neovim-git/src/neovim-git/src -I/usr/include -I/home/auser/.cache/paru/clone/neovim-git/src/build/src/nvim/auto -I/home/auser/.cache/paru/clone/neovim-git/src/build/include
Compiled by auser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

originally i thought it was a problem with the markdown grammar because my editor kept crashing when i edited 600 line markdown file with dart code fences. when i poked around i found that the editor would not crash if i removed all the 'dart' arguments to the opening fence lines. the weird thing is: after removing the 'dart' argument from the lines i could hit undo 15 times and everything was still fine but the 16th undo would crash the editor. moreover, i can open a markdown file with only a dart code fence just fine, and even type into the existing fence for about 15 characters before vim crashes, but when i create a new dart code fence the first character already crashes vim...

**Comment by AmaaelTyrneaMitore** [comment]
Same here! In my case, I also noticed that when I try to open a dart file (from my flutter project) which is already populated with some dart code, it does not crash. But when I try to open an empty dart file, it gives me the same error as you mentioned.

**Comment by theHamsta** [comment]
I think this a duplicate of #2961. Can you maybe produce a backtrace with GDB? I could not reproduce on my machine so it would be ver valuable for us.

**Comment by AmaaelTyrneaMitore** [comment]
> I think this a duplicate of #2961. Can you maybe produce a backtrace with GDB? I could not reproduce on my machine so it would be ver valuable for us.

Thanks for replying! I can most certainly do that but it's just I am new to do this, so can you please guide me through the steps for producing a backtrace.

**Comment by theHamsta** [comment]
I think you get best results when you compile Neovim and the tree-sitter dependency in Debug or RelWithDebInfo mode (`-DCMAKE_BUILD_TYPE=....`) but it should also work with a precompiled Neovim instance. Run `gdb --args nvim file.dart`, first `r` to start Neovim. Then, type until you trigger the segfault. When the SEGFAULT is triggered, run `bt` for backtrace or even `bt full`. When you compiled with debug info you should even see the live where it's crashing. To compile even the `dart` parser with debug information, add a `-g` here https://github.com/thmsmlr/nvim-treesitter/blob/47259fb32cfa4f362014bbe62e071530ab0e0317/lua/nvim-treesitter/shell_command_selectors.lua#L85 and reinstall the dart parser.

For the SEGFAULT, there are multiple possibilities:
- segfault in tree-sitter generated code (very improbably)
- segfault in external scanner https://github.com/UserNobody14/tree-sitter-dart/blob/master/src/scanner.c
- segfault in the way how Neovim parses the code (I'd say not very probable either)
- segfault in the query code (I'd guess for that one since we saw that for other parsers)

The backtrace should reveal where the SEGFAULT occurs. When it happens inside the parser, it should be reproducible without Neovim by fuzzing, when it happens during querying we should also test whether it can be reproduced with tree-sitter-cli only. There is also the helix editor which can use tree-sitter also.

**Comment by marcusatiliusregulus** [comment]
here is a coredump: do you want something else? https://gist.github.com/marcusatiliusregulus/5976a6af29452b8645779376121c05d9

**Comment by marcusatiliusregulus** [comment]
i've added a `bt full` to the gist

**Comment by theHamsta** [comment]
```
tree-sitter on  master [$!?] via 🦀 v1.63.0-nightly took 5s 
❯ ./out/dart_fuzzer 
dart_fuzzer: test/fuzz/fuzzer.cc:32: int LLVMFuzzerInitialize(int *, char ***): Assertion `lang_query' failed.
[1]    9919 IOT instruction (core dumped)  ./out/dart_fuzzer
```
It crashes on loading with `TSQueryErrorNodeType` even for our highlights.scm

So I now deleted the queries for now.

@marcusatiliusregulus can you use a pre-compiled Neovim from the releases (either binary or appimage). The crash shouldn't happen with that one. Can you find out with what tree-sitter runtime they are compiling (AUR package). Usually that's a bug report to the AUR maintainers as Neovim only provides support for the package versions and compile flags they are using. I see that AUR adds a lot of additional compile flags.

**Comment by marcusatiliusregulus** [comment]
i downloaded the latest nightly binary but it still crashes once i type a character in a new file file.dart...

```
NVIM v0.8.0-dev+334-ge9803e1de
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az217-252

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Comment by marcusatiliusregulus** [comment]
```
~ ❯ paru --aur -Qi tree-sitter
Name            : tree-sitter
Version         : 0.20.6-1
Description     : An incremental parsing system for programming tools
Architecture    : x86_64
URL             : https://github.com/tree-sitter/tree-sitter
Licenses        : MIT
Groups          : None
Provides        : libtree-sitter.so=0-64
Depends On      : gcc-libs
Optional Deps   : None
Required By     : neovim-git
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 11,68 MiB
Packager        : Daniel M. Capella <polyzen@archlinux.org>
Build Date      : Fr 04 Mär 2022 04:03:32 CET
Install Date    : So 29 Mai 2022 20:02:19 CEST
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

**Comment by theHamsta** [comment]
One could bisect which node was causing problems in the highlights. `conditional_assignable_selector` does not exist. But it apparently doesn't cause our tests or the query checker to fail...

**Comment by theHamsta** [comment]
Could you uninstall the tree-sitter AUR? Is it possibile that it uses the system `#include <tree_sitter/parser.h>` instead of the one provided in the parser repo? It could be a different tree-sitter version... (they were using tree-sitter 0.19.2)
```
nvim-treesitter on  patch-2 [$?] via 🐹 v1.18.2 via 🌙 v5.3.6 
❯ ldd parser/dart.so 
        linux-vdso.so.1 (0x00007fff557b4000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4f4879e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4f48576000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4f4848f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4f48a9a000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4f4846f000)
```
Does a parser that you generated using `:TSInstallFromGrammar` crash in the same way? Can you delete the `src` folder of tree-sitter-dart and regenerate it using your tree-sitter?

**Comment by theHamsta** [comment]
Yes, can make it crash with the fuzzer (was using an old version of tree-sitter-dart for fuzzing before). So, not a Neovim problem
```
❯ ./out/dart_fuzzer 
lib/src/query.c:927:11: runtime error: index -1 out of bounds for type 'AnalysisStateEntry[8]'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior lib/src/query.c:927:11 in 
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1455236800
INFO: Loaded 1 modules   (27683 inline 8-bit counters): 27683 [0x5607624a0780, 0x5607624a73a3), 
INFO: Loaded 1 PC tables (27683 PCs): 27683 [0x5607624a73a8,0x5607625135d8), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: A corpus is not provided, starting from an empty corpus
#2      INITED cov: 2364 ft: 2365 corp: 1/1b exec/s: 0 rss: 44Mb
#3      NEW    cov: 2365 ft: 2463 corp: 2/3b lim: 4 exec/s: 0 rss: 44Mb L: 2/2 MS: 1 CopyPart-
lib/src/./subtree.h:219:65: runtime error: member access within null pointer of type 'const SubtreeHeapData'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior lib/src/./subtree.h:219:65 in 
AddressSanitizer:DEADLYSIGNAL
=================================================================
==21601==ERROR: AddressSanitizer: SEGV on unknown address 0x00000000002c (pc 0x56076212b095 bp 0x7ffdb9ea93b0 sp 0x7ffdb9ea9300 T0)
==21601==The signal is caused by a READ memory access.
==21601==Hint: address points to the zero page.
    #0 0x56076212b095 in ts_subtree_is_keyword parser.c
    #1 0x5607620f9d3f in ts_parser__advance parser.c
    #2 0x5607620ef576 in ts_parser_parse (/home/stephan/projects/tree-sitter/out/dart_fuzzer+0x2ba576) (BuildId: 28fbd2903eb60c5486aa6d77b5a72f56880a45ab)
    #3 0x5607620fff11 in ts_parser_parse_string_encoding (/home/stephan/projects/tree-sitter/out/dart_fuzzer+0x2caf11) (BuildId: 28fbd2903eb60c5486aa6d77b5a72f56880a45ab)
    #4 0x5607620ffb43 in ts_parser_parse_string (/home/stephan/projects/tree-sitter/out/dart_fuzzer+0x2cab43) (BuildId: 28fbd2903eb60c5486aa6d77b5a72f56880a45ab)
    #5 0x560762087366 in LLVMFuzzerTestOneInput (/home/stephan/projects/tree-sitter/out/dart_fuzzer+0x252366) (BuildId: 28fbd2903eb60c5486aa6d77b5a72f56880a45ab)
    #6 0x560761faa272 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/stephan/projects/tree-sitter/out/dart_fuzzer+0x175272) (BuildId: 28fbd2903eb60c5486aa6d77b5a72f56880a45ab)
    #7 0x560761fa99c9 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/home/stephan/projects/tree-sitter/out/dart_fuzzer+0x1749c9) (BuildId: 28fbd2903eb60c5486aa6d77b5a72f56880a45ab)
    #8 0x560761fab1b7 in fuzzer::Fuzzer::MutateAndTestOne() (/home/stephan/projects/tree-sitter/out/dart_fuzzer+0x1761b7) (BuildId: 28fbd2903eb60c5486aa6d77b5a72f56880a45ab)
    #9 0x560761fabd35 in fuzzer::Fuzzer::Loop(std::vector<fuzzer::SizedFile, std::allocator<fuzzer::SizedFile>>&) (/home/stephan/projects/tree-sitter/out/dart_fuzzer+0x176d35) (BuildId: 28fbd2903eb60c5486aa6d77b5a72f56880a45ab)
    #10 0x560761f99f62 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/stephan/projects/tree-sitter/out/dart_fuzzer+0x164f62) (BuildId: 28fbd2903eb60c5486aa6d77b5a72f56880a45ab)
    #11 0x560761fc3342 in main (/home/stephan/projects/tree-sitter/out/dart_fuzzer+0x18e342) (BuildId: 28fbd2903eb60c5486aa6d77b5a72f56880a45ab)
    #12 0x7fb891aa1d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #13 0x7fb891aa1e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #14 0x560761f8eb04 in _start (/home/stephan/projects/tree-sitter/out/dart_fuzzer+0x159b04) (BuildId: 28fbd2903eb60c5486aa6d77b5a72f56880a45ab)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV parser.c in ts_subtree_is_keyword
==21601==ABORTING
MS: 1 ChangeByte-; base unit: adc83b19e793491b1c6ea0fd8b46cd9f32e592fc
0x77,
w
artifact_prefix='./'; Test unit written to ./crash-aff024fe4ab0fece4091de044c58c9ae4233383a
Base64: dw==
```

**Comment by theHamsta** [comment]
@marcusatiliusregulus can you try again with tree-sitter-dart compiled with `-O0` and `-g` (or without the `-O0`) https://github.com/thmsmlr/nvim-treesitter/blob/47259fb32cfa4f362014bbe62e071530ab0e0317/lua/nvim-treesitter/shell_command_selectors.lua#L85?

**Comment by theHamsta** [comment]
All the crashes are a single non-white space character and then end of document:
[crashes.tar.gz](https://github.com/nvim-treesitter/nvim-treesitter/files/8800774/crashes.tar.gz)

**Comment by theHamsta** [comment]
Bisected to this commit https://github.com/UserNobody14/tree-sitter-dart/commit/5e5d9533b52a14d6b324fdaa6061ca0af519f896

@marcusatiliusregulus can you try the commit before this bad commit: f95876f0ed3ef207bbd3c5c41987bc2e9cecfc97 ?

**Comment by theHamsta** [comment]
I would recommend to add something like this to tree-sitter-dart CI (be careful fuzzer does not return error code on fail)

diff in tree-sitter (because it won't accept `conditional_assignable_selector` in the query file)
```
────────────────────────────────────┐
51: for lang in ${languages[@]}; do │
────────────────────────────────────┘
  $CC $CFLAGS -g -O0 "-I${lang_dir}/src" "${lang_dir}/src/parser.c" -c -o "${lang_dir}/src/parser.o"
  objects+=("${lang_dir}/src/parser.o")

  highlights_filename="${lang_dir}/queries/highlights.scm"
  if [ -e "${highlights_filename}" ]; then
    ts_lang_query_filename="${lang}.scm"
    cp "${highlights_filename}" "out/${ts_lang_query_filename}"
  else
    ts_lang_query_filename=""
  fi
  #highlights_filename="${lang_dir}/queries/highlights.scm"
  #if [ -e "${highlights_filename}" ]; then
    #ts_lang_query_filename="${lang}.scm"
    #cp "${highlights_filename}" "out/${ts_lang_query_filename}"
  #else
  ts_lang_query_filename=""
  #fi

  # FIXME: We should extract the grammar name from grammar.js. Use the name of
  # the directory instead. Also, the grammar name needs to be a valid C

────────────────────────────────────┐
68: for lang in ${languages[@]}; do │
────────────────────────────────────┘
    libtree-sitter.a "$LIB_FUZZER_PATH" \
    -o "out/${lang}_fuzzer"

  python test/fuzz/gen-dict.py "${lang_dir}/src/grammar.json" > "out/$lang.dict"
  python2 test/fuzz/gen-dict.py "${lang_dir}/src/grammar.json" > "out/$lang.dict"
done
```
and the n I run to bisect
```
git rebase -i HEAD~10 --exec="rm -f src/*.o;cd ../tree-sitter;./script/build-fuzzers;echo ' ' > ./out/dart.scm;timeout 10s ./out/dart_fuzzer;cd -"
```
but easier to just look at https://github.com/UserNobody14/tree-sitter-dart/commits/master/src/scanner.c

**Comment by marcusatiliusregulus** [comment]
ok, i've compiled the correct commit, but how do i use it now?

**Comment by theHamsta** [comment]
Either set the commit SHA in https://github.com/thmsmlr/nvim-treesitter/blob/47259fb32cfa4f362014bbe62e071530ab0e0317/lockfile.json#L48 and `:TSInstall` or change the url to your local repository of tree-sitter-dart https://github.com/thmsmlr/nvim-treesitter/blob/47259fb32cfa4f362014bbe62e071530ab0e0317/lua/nvim-treesitter/parsers.lua#L634

**Comment by marcusatiliusregulus** [comment]
ok, no crash now!

**Comment by AmaaelTyrneaMitore** [comment]
Yay!! Works for me too! Thanks for your precious time💟

**Comment by GenesisTMS** [comment]
Thanks for investigation! It works. :rocket:

**Comment by dmguezjaviersnet** [comment]
I almost open another issue because of this. The fix worked for me. Thank a lot

**Comment by Kavantix** [comment]
@theHamsta is there any way I can confirm it is using the correct commit for the dart parser?
I tried setting it in the lock file and TSInstall dart but it still crashes

**Comment by Kavantix** [comment]
Got it to work, turns out the plugged directory is moved to `~/.local/share/nvim/plugged`

**Comment by CarlosNihelton** [comment]
Great investigation! Worked for me as well!

**Comment by AmaaelTyrneaMitore** [comment]
Hey @marcusatiliusregulus, now that you have a working solution, don't you think you should close this?

**Comment by Jetandarkumar** [comment]
@marcusatiliusregulus , @AmaaelTyrneaMitore @CarlosNihelton ? I have recently configured my neovim and also facing these issue? Can someone guide me through the steps in more concise manner so I could avoid this bug.

**Comment by brneor** [comment]
Is this fix already in master branch? I'm having the same issue today.

**Comment by brneor** [comment]
@ayoubelmhamdi using a fork that is 162 commits behind official repo doesn't sound like a viable long term solution.

**Comment by theHamsta** [comment]
@brneor We're open for a PR that set's dart to that old version and skips updates by adding dart here: https://github.com/theHamsta/nvim-treesitter/blob/5737f781699c275fe81ea970ccc4d66fb04040be/.github/workflows/update-lockfile.yml#L33

**Comment by brneor** [comment]
@theHamsta thank you for pointing me the directions! https://github.com/nvim-treesitter/nvim-treesitter/pull/3171
