### ISSUE TITLE
Treesitter errors in latest neovim master

### ISSUE THREAD

**Issue by trickster** [nvim-treesitter/nvim-treesitter#3002]
### Describe the bug

Treesitter errors when opening cargo project
![Screen Shot 2022-06-10 at 10 40 09](https://user-images.githubusercontent.com/1740785/172973461-87accd98-8436-4191-b975-122ac639893c.png)
.

### To Reproduce

1. Get latest neovim
2. Install AstroVim
3. Open a rust project

### Expected behavior

Works without errors.

### Output of `:checkhealth nvim-treesitter`

```markdown
1 nvim-treesitter: require("nvim-treesitter.health").check()
    2 ========================================================================
    3   - ERROR: Failed to run healthcheck for "nvim-treesitter" plugin. Exception:
    4     function health#check, line 20
    5     Vim(eval):E5108: Error executing lua [string "luaeval()"]:1: attempt to call field 'check' (a nil value)
    6     stack traceback:
    7     [string "luaeval()"]:1: in main chunk
```

### Output of `nvim --version`

```text
➜ nvim --version
NVIM v0.8.0-dev+399-g58323b1fe
Build type: Release
LuaJIT 2.1.0-beta3

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-58323b1/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
Please give a _minimal_ config we can use to reproduce the problem -- in particular, this means _no config framework_ like AstroVim or LunarVim (all errors using such frameworks should be reported at the respective repo first).

**Comment by trickster** [comment]
@clason I raised an issue here https://github.com/AstroNvim/AstroNvim/issues/595#issuecomment-1147302462
