### ISSUE TITLE
Restructuring the markdown parser

### ISSUE THREAD

**Issue by MDeiml** [nvim-treesitter/nvim-treesitter#3008]
I'm currently in the process of restructuring my [markdown grammar](https://github.com/MDeiml/tree-sitter-markdown) and would be interested in other peoples opinions.

The goal is to split it into two parts, one for the block structure (headings, paragraphs, fenced code blocks, ...) and one for the inline structure (emphasis, code spans, links, ...). These two grammars would then be used by:
1. Parsing the whole document with the block grammar to obtain the block tree and
2. Parsing everything that was marked as inline content in the previous step with the inline grammar (probably using language injection)

This approach of course has some pretty big disadvantages:
* The entire file has to be read twice
* The language will fit worse into the model of one grammar per language (writing queries that include inline as well as block structure for example would be impossible or very hard)
* Language injection might not work good enough yet to support this model without extra handling (well, this is more a problem with neovim itself that gets apparent here)

But I think the advantages outweigh the disadvantages:
* The recommended way of parsing markdown is actually to read the file twice (https://github.github.com/gfm/#appendix-a-parsing-strategy), so this approach fits better into the mental model.
* In theory less parsing could be done by only running the inline parser over relevant sections (e.g. sections that are visible currently)
* And __most importantly__: The complexity of the parser at the moment is just too high. It is quite buggy and hard to understand, which also stops me from implementing new elements such as tables. This is mostly due to handling parsing conflicts, which happen A LOT with markdown.

  By splitting the parse into two grammars, each grammar can be viewed separately and it's not necessary to understand one to understand the other (which is not true at the moment due to how parsing conflicts / dynamic precedence work). This would lower the hurdle for new contributions and make it possible to rewrite the grammars separately (which might be necessary at some point)

I've already adapted the block grammar and in the process a bug related to parsing link reference definition solved itself, which I think is very promising. Anyone interested can check it out in the split_parser branch.

But obviously this work is only worth it, if it ends up being used in nvim-treesitter / other editors.

**Comment by MDeiml** [comment]
Any thoughts @theHamsta?

**Comment by theHamsta** [comment]
Hi, @MDeiml I'm not an expert in parsing. But your reasoning sounds fair. Having two grammars wouldn't be too bad for us. We just also would need to improve incremental parsing for injected language which I wanted to do anyway.
