### ISSUE TITLE
Expand TSString node to improve highlighting in Angular

### ISSUE THREAD

**Issue by jgarciaokode** [nvim-treesitter/nvim-treesitter#3027]
Look at the word "translate" in both editors, i guess in neovim this is not possible yet cause it is encapsulated under the same node

In vscode

<img width="956" alt="image" src="https://user-images.githubusercontent.com/79897391/174054687-fde200ca-0361-4156-bd76-579fe7010a6c.png">

In Neovim

<img width="1604" alt="image" src="https://user-images.githubusercontent.com/79897391/174054597-344bd057-3d09-44f0-b369-b8af5e5d0ec6.png">

**Comment by jgarciaokode** [comment]
More examples:

In vscode:

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/79897391/174061034-434c1819-f6fb-4b37-8a71-9fc24314c972.png">


In neovim:

<img width="854" alt="image" src="https://user-images.githubusercontent.com/79897391/174061071-8dbc1f02-2abf-4511-b25c-bd88b5f71587.png">

**Comment by kyazdani42** [comment]
neovim treesitter doesn't aim to implement framework related stuff, maybe see https://github.com/steelsojka/ts-angular.nvim but i think it's not maintained.
