### ISSUE TITLE
Small delay before opening rust / c++ files. Treesitter highlighting lag

### ISSUE THREAD

**Issue by ltade** [nvim-treesitter/nvim-treesitter#3030]
### Describe the bug

blank buffer with "no user-defined commands found" text in the mini-buffer briefly flashes before opening a file where treesitter highlighting is enabled.
I only tested this on rust and c++ files. with c++ files this problem / lag is much more more noticeable than in rust.  

### To Reproduce

specific treesitter configuration:
```lua
require'nvim-treesitter.configs'.setup {
ensure_installed = { "c", "cpp", "lua", "rust" },
  highlight = {
    enable = true,
  },
}
```

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.14.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.1.1 20220507 (Red Hat 12.1.1-1)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - vim            ✓ ✓ . . ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.7.0
```

### Additional context

I also tested this with a bit older commit "e4df4228b7c07f98e55345b40ac0093d27d0d18c" still same problem.

**Comment by clason** [comment]
I cannot reproduce this. Please try with and share a **complete** and **minimal** config we can run with `nvim --clean -u config.lua`.

**Comment by MathieuDR** [comment]
@Adomas-beep-boop-maggots Did you figure out what the issue is? I'm facing something similar with Elixir files.
