### ISSUE TITLE
New version of Vim breaks Neovim 0.7 due to ABI 14

### ISSUE THREAD

**Issue by David-Else** [nvim-treesitter/nvim-treesitter#3051]
### Describe the bug

It works on the latest nightly, but breaks 0.7 as show in `checkhealth`:

```  ## The following errors have been detected:                                                                                                                                                   
    - ERROR: vim(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/david/.local/share/nvim/site/pack/paqs/start/nvim-treesitter/parser/       vim.so: supported between 13 and 13, found 14                                                                                                                                               
      vim(highlights) is concatenated from the following files:                                                                                                                                 
      | [ERROR]:"/home/david/.local/share/nvim/site/pack/paqs/start/nvim-treesitter/queries/vim/highlights.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33:    
      ABI version mismatch for /home/david/.local/share/nvim/site/pack/paqs/start/nvim-treesitter/parser/vim.so: supported between 13 and 13, found 14                                          
    - ERROR: vim(locals): /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/david/.local/share/nvim/site/pack/paqs/start/nvim-treesitter/parser/vim.   
    so: supported between 13 and 13, found 14                                                                                                                                                   
      vim(locals) is concatenated from the following files:                                                                                                                                     
      | [ERROR]:"/home/david/.local/share/nvim/site/pack/paqs/start/nvim-treesitter/queries/vim/locals.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI    
      version mismatch for /home/david/.local/share/nvim/site/pack/paqs/start/nvim-treesitter/parser/vim.so: supported between 13 and 13, found 14                                              
    - ERROR: vim(folds): /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/david/.local/share/nvim/site/pack/paqs/start/nvim-treesitter/parser/vim.so: 
    supported between 13 and 13, found 14                                                                                                                                                       
      vim(folds) is concatenated from the following files:                                                                                                                                      
      | [ERROR]:"/home/david/.local/share/nvim/site/pack/paqs/start/nvim-treesitter/queries/vim/folds.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI     
      version mismatch for /home/david/.local/share/nvim/site/pack/paqs/start/nvim-treesitter/parser/vim.so: supported between 13 and 13, found 14                                              
    - ERROR: vim(injections): /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch for /home/david/.local/share/nvim/site/pack/paqs/start/nvim-treesitter/parser/   
    vim.so: supported between 13 and 13, found 14                                                                                                                                               
      vim(injections) is concatenated from the following files:                                                                                                                                 
      | [ERROR]:"/home/david/.local/share/nvim/site/pack/paqs/start/nvim-treesitter/queries/vim/injections.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:33:    
      ABI version mismatch for /home/david/.local/share/nvim/site/pack/paqs/start/nvim-treesitter/parser/vim.so: supported between 13 and 13, found 14
```
Please can you revert this and make a branch to maintain compatibility with 0.7?

> # Quickstart

> ## Requirements

> - **Neovim 0.7.0 or later** (latest [nightly](https://github.com/neovim/neovim#install-from-source) recommended)

### Output of `nvim --version`

```text
$ nvim --version
NVIM v0.7.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/builddir/build/BUILD/neovim-0.7.0/x86_64-redhat-linux-gnu/config -I/builddir/build/BUILD/neovim-0.7.0/src -I/usr/include -I/usr/include/luajit-2.1 -I/builddir/build/BUILD/neovim-0.7.0/x86_64-redhat-linux-gnu/src/nvim/auto -I/builddir/build/BUILD/neovim-0.7.0/x86_64-redhat-linux-gnu/include
Compiled by mockbuild@koji
```

**Comment by theHamsta** [comment]
We've decided to not care about adding a compatibility mechanism, because 0.7 ships with ABI 14. You seem to be using a distro Neovim that was compiled with an alternative tree-sitter version. `:TSInstallFromGrammar` will inspect the ABI version you have an compile for the right version. Add `require_install_from_grammar = true` to the parsers you're having problems with to always install from grammar also on updates.

**Comment by David-Else** [comment]
@theHamsta Thanks for the quick reply, my current installer is Paq:
```
  {
    'nvim-treesitter/nvim-treesitter',
    run = function()
      vim.cmd 'TSUpdate'
    end,
  },
```
and treesitter settings are:
```
require('nvim-treesitter.configs').setup {
  ensure_installed = {
    'vim',
    'bash',
    'css',
    'html',
    'javascript',
    'jsdoc',
    'json',
    'jsonc',
    'lua',
    'rust',
    'typescript',
    'tsx',
    'markdown',
  },
  highlight = {
    enable = true,
  },
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = '<CR>',
      scope_incremental = '<CR>',
      node_incremental = '<TAB>',
      node_decremental = '<S-TAB>',
    },
  },
  indent = {
    enable = true,
  },
}
```
Please could you advise me what I need to change to keep the system working without intervention when new grammars come out? I am not sure what to do when you say:

> Add require_install_from_grammar = true to the parsers you're having problems with to always install from grammar also on updates


Thanks!

**Comment by clason** [comment]
Yes, it would. The minimal version for _Neovim_ can be (and is) lower than for plugins. 

I feel like I shouldn't need to repeat that so often, but remember that treesitter support and nvim-treesitter is **experimental**. You are essentially using an "early access" product and should be ideally be using nightly builds of Neovim. I believe this is stated quite prominently in the README; if something can be made clearer, please let me know how.

**Comment by David-Else** [comment]
@clason I appreciate it must be a bit annoying, seems like a bit of an exceptional case with the RHEL build, sorry!

Could you help me solve my problem? I was told:

> Add require_install_from_grammar = true to the parsers you're having problems with to always install from grammar also on updates.

but I have no idea what this means or how to accomplish it, could you have a quick look at my question above https://github.com/nvim-treesitter/nvim-treesitter/issues/3051#issuecomment-1164287101. I seem to need another executable to compile this grammar that is not included, and to add something to my `.setup` ? THANKS!

Really looking forward to when this is all stable and built into Neovim :)

**Comment by David-Else** [comment]
@clason I am happy to contact the maintainer on RHEL and request an official version of tree-sitter be used, but I am not sure what that means. Please could you tell me the exact package that should be used rather than the current `libtree-sitter-devel`? I am not a C developer, just a user trying to get things working.

**Comment by clason** [comment]
Then I would recommend to just use the appimage from the Neovim page.

**Comment by David-Else** [comment]
@clason I am of the opinion that it is much better to use official OS builds for many pedantic and probably boring reasons I won't get into.

**Comment by clason** [comment]
That is as it may be, but then you can't complain that exciting and experimental features are not available to you. I cannot stress enough that if you want to use nvim-treesitter, you _really_ should be following master, both for this plugin and Neovim.

**Comment by David-Else** [comment]
I get what you are saying, but the README here says `Neovim 0.7.0 or later (latest nightly recommended)`

That is *recommended* not mandatory. It would be pretty quick and easy to just branch a version for 0.7 and then go crazy with any incompatible updates?

**Comment by clason** [comment]
No. This will not happen, for many practical and probably disappointing reasons. 

I'll put the tree-sitter version requirement there, though, as that is indeed good to make explicit.

(Note that this has nothing to do with Neovim 0.7 vs. nightly, but with how a distro decides to build and package it. There's nothing we can do about that.)

**Comment by David-Else** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2100577
