### ISSUE TITLE
Basic Highlight Overriding

### ISSUE THREAD

**Issue by barrett-ruth** [nvim-treesitter/nvim-treesitter#3058]
### Describe the highlighting problem

All I want to do is override a highlight group. I have tried many times and cannot figure it out.

Lua keyword `local` is highlighted according to TSKeyword using `:TSHighlightCapturesUnderCursor`, the correct behavior.

I would simply like to un-italicize the word `local` while keeping all other TSKeywords the same.

I have tried with `set_query`, but that overrides all the other `highlights` queries. I have also used `set_custom_captures`, but this is overridden by `TSKeyword`. The only way I could fix the issue is removing "local" from the lua queries file in the source code itself.

### Example snippet that causes the problem

```lua
local hi = 'hello'
```

### Tree-sitter parsing result

```
local_declaration: variable_declaration [0, 0] - [0, 18]
  "local" [0, 0] - [0, 5]
  assignment_statement [0, 6] - [0, 18]
    variable_list [0, 6] - [0, 8]
      name: identifier [0, 6] - [0, 8]
    "=" [0, 9] - [0, 10]
    expression_list [0, 11] - [0, 18]
      value: string [0, 11] - [0, 18]
        start: "string_start" [0, 11] - [0, 12]
        content: "string_content" [0, 12] - [0, 17]
        end: "string_end" [0, 17] - [0, 18]
```

### Example screenshot

Device doesn't have screenshotting set up.
sainnhe/gruvbox-material

(don't think this is relevant)

### Expected behavior

Change the highlighting of keyword `local`

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v18.3.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - c              ✓ ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - make           ✓ . . . ✓ 
  - dockerfile     ✓ . . . ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - http           ✓ . . . ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - vim            ✓ ✓ ✓ . ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.0-dev+462-gf17d88c47
```

### Additional context

Rather than looking at all my attempts and dissecting them, this seems like a pretty trivial issue that got around me. Please just recommend me a strategy that you would take - after all, I just need to change the color of a singular word!

**Comment by kyazdani42** [comment]
as stated in the README:

You can add custom highlight captures with:

```lua
  require"nvim-treesitter.highlight".set_custom_captures {
    -- Highlight the @foo.bar capture group with the "Identifier" highlight group.
    ["foo.bar"] = "Identifier",
  }
```

and then override the lua query to add `"local" @foo.bar`

**Comment by theHamsta** [comment]
However @kyazdani42 will not undo the `italization` of the keyword highlight even when you would give your highlight a higher priority

**Comment by kyazdani42** [comment]
Even if forcing `gui=NONE` on the highlight group overriding ?

**Comment by barrett-ruth** [comment]
Here's my setup: 
`after/queries/lua/highlights.scm`:
```scheme
"local" @lua.local
```
Treesitter file:
```lua
vim.cmd 'hi TSLocal gui=NONE guibg=#123123'
require('nvim-treesitter.highlight').set_custom_captures {
    ['lua.local'] = 'TSLocal',
}
```
What `:TSHighlightCapturesUnderCursor` shows on a local keyword in a lua file:
    3 │* @keyword -> luaTSKeyword -> TSKeyword
    2 │* @lua.local -> luaTSLocal -> TSLocal

The highlights remain both italicized *and* their background does not change according to highlight group TSLocal.

**Comment by theHamsta** [comment]
Does `(....... (set! "priority" 105))` change anything about the situation. Use the local query for the dots.

**Comment by kyazdani42** [comment]
i just tried with priority it does not work. I really don't know how to do this, are we able to remove groups from captures ?

**Comment by theHamsta** [comment]
I don't think that's possible at the moment. I thought that we could maybe use tree-sitter-query to enable query reflection to remove particular queries. Something similar could also be done with the plan to develop a fennel DSL to write the query. I guess the closest you can get to today is to read the query files and  do a `:gsub` on them to manipulate the query text (https://github.com/theHamsta/neovim/blob/5099653ae1089e9180c560b7a4172674d0fa5398/runtime/lua/vim/treesitter/query.lua#L100-L42) and then use `set_query`

**Comment by barrett-ruth** [comment]
Another question then - are those approaches more reasonable than allowing `set_query` to not completely override all queries, but instead a select few? In this case this means only overriding the lua list of keywords.

However, at this point it seems easiest for me to simply delete and copy the queries/lua/highlights.scm file to after/queries and make alterations accordingly.

**Comment by barrett-ruth** [comment]
Ok, well if you can't alter parts of queries without overriding rhe whole thing using `set_query` I'm just going to delete and paste language files from the source into my `after/queries/<filetype>` directory. Feel free to close.

**Comment by theHamsta** [comment]
you can try this snippet
```lua
local function safe_read(filename, read_quantifier)
  local file, err = io.open(filename, 'r')
  if not file then
    error(err)
  end
  local content = file:read(read_quantifier)
  io.close(file)
  return content
end

local function read_query_files(filenames)
  local contents = {}

  for _, filename in ipairs(filenames) do
    table.insert(contents, safe_read(filename, '*a'))
  end

  return table.concat(contents, '')
end
vim.treesitter.query.set_query('lua', 'highlights', D(read_query_files(vim.treesitter.query.get_query_files('lua', 'highlights')):gsub([[%[
 "goto"
 "in"
 "local"
%] @keyword]], [[
[ "goto" "in" ] @keyword

; put more queries of yours here
  ]])
))
```
yes, I agree that the API of `set_query` is very unfortunate. You basically have to load and parse the query and the parser beforehand before you touch a Lua file.

**Comment by barrett-ruth** [comment]
Ok, that snippet works well. Thanks for the explanation that actually explains why `set_query()` works the way it does.
