### ISSUE TITLE
[C/C++] Inconsistent highlighting of value and reference parameters

### ISSUE THREAD

**Issue by mliszcz** [nvim-treesitter/nvim-treesitter#3061]
### Describe the highlighting problem

I'm coming from: https://github.com/tree-sitter/tree-sitter-cpp/issues/164
Please see that one for some analysis and a potential solution.

Let me copy-paste the original report:

> Value parameters and reference parameters have different syntax highlight groups. Consider this example:
>
> (screenshot here)
>
> According to TSCaptureUnderCursor:
>   * arg1 is {TSVariable, TSParameter} in that order
>   * arg2 is {TSParameter, TSVariable} (order is reversed)
>
> The colorscheme I'm using indeed has different colors for TSVariable (fg) and TSParameter (red).
>
> I think that this inconsistency is not desired. This seems to be something that should be addressed by the parser, not the colorscheme.

### Example snippet that causes the problem

```cpp
void foo(int arg1, int& arg2, int const& arg3, int* arg4);
```

### Tree-sitter parsing result

```
declaration [0, 0] - [0, 58]
  type: primitive_type [0, 0] - [0, 4]
  declarator: function_declarator [0, 5] - [0, 57]
    declarator: identifier [0, 5] - [0, 8]
    parameters: parameter_list [0, 8] - [0, 57]
      parameter_declaration [0, 9] - [0, 17]
        type: primitive_type [0, 9] - [0, 12]
        declarator: identifier [0, 13] - [0, 17]
      parameter_declaration [0, 19] - [0, 28]
        type: primitive_type [0, 19] - [0, 22]
        declarator: reference_declarator [0, 22] - [0, 28]
          identifier [0, 24] - [0, 28]
      parameter_declaration [0, 30] - [0, 45]
        type: primitive_type [0, 30] - [0, 33]
        type_qualifier [0, 34] - [0, 39]
        declarator: reference_declarator [0, 39] - [0, 45]
          identifier [0, 41] - [0, 45]
      parameter_declaration [0, 47] - [0, 56]
        type: primitive_type [0, 47] - [0, 50]
        declarator: pointer_declarator [0, 50] - [0, 56]
          declarator: identifier [0, 52] - [0, 56]
```

### Example screenshot

![image](https://user-images.githubusercontent.com/6927259/175542680-45741073-c74a-4ed4-bbd8-fb7838dd437d.png)

### Expected behavior

arg1, arg2, arg3, arg4 all highlighted in red.

### Output of `:checkhealth nvim-treesitter`

```markdown
## Parser/Features H L F I J
  - cpp            ✓ ✓ ✓ ✓ ✓ 
```
```


### Output of `nvim --version`

```text
NVIM v0.7.0
```

**Comment by theHamsta** [comment]
@mliszcz you want to create a PR for that?

**Comment by theHamsta** [comment]
A problem with `(reference_declarator (identifier) @parameter)` is that you probably also want to have ` `(reference_declarator (reference_declarator (identifier) @parameter))`. This could be a reason why `(parameter_declaration
   declarator: (reference_declarator) @parameter)` was used instead (same for pointer_declarator).

**Comment by mliszcz** [comment]
Thanks @theHamsta for your comments. Yes, indeed we should support that. I have not found any way to annotate nested pointer_declarator of arbitrary depth. I think we need to just hard-code all the cases up to some fixed depth (3, maybe 4).

There are some constraints which are limiting the number of possible combinations:
* && is parsed as a single reference_declarator
* & && or && & is not a valid syntax, there is always just one reference_declarator
* & or && always appears after *

I can create a PR and add those combinations, if you think that this is the right approach:

```
(parameter_declaration
  declarator: (pointer_declarator (identifier) @parameter))
(parameter_declaration
  declarator: (pointer_declarator
                (pointer_declarator (identifier) @parameter)))
(parameter_declaration
  declarator: (pointer_declarator
                (pointer_declarator
                  (pointer_declarator (identifier) @parameter))))

(parameter_declaration
  declarator: (reference_declarator (identifier) @parameter))
(parameter_declaration
  declarator: (pointer_declarator
                (reference_declarator (identifier) @parameter)))
(parameter_declaration
  declarator: (pointer_declarator
                (pointer_declarator
                  (reference_declarator (identifier) @parameter))))
(parameter_declaration
  declarator: (pointer_declarator
                (pointer_declarator
                  (pointer_declarator
                    (reference_declarator (identifier) @parameter)))))
```

**Comment by mliszcz** [comment]
I noticed that the problem is back on nvim v0.8 and 0.9 (but not on 0.7). Git bisect points to: b273a06728305c1e7bd0179977ca48049aeff5e6

I'm investigating right now what is causing this. Looks like some highlight group configuration problem. Perhaps the colorscheme needs to be adjusted.
