### ISSUE TITLE
TSVariable and TSVariableBuiltin are not used

### ISSUE THREAD

**Issue by theHamsta** [nvim-treesitter/nvim-treesitter#307]
**Is your feature request related to a problem? Please describe.**
- Currently, normal identifiers have no highlight group. We planned to use `TSVariable` for this.
- We use `@constant.builtin` for stuff that's not constant.

**Describe the solution you'd like**

- [ ] use `@variable.builtin` for stuff that's currently `@constant.builtin` but is actually not constant (mostly self, this).
- [ ] add `@variable` queries for all languages (should be `(identifier) @variable` for most languages)
- [ ] document TSVariable and TSVariableBuiltin

**Comment by akinsho** [comment]
Just fyi `@variable.builtin` is used for dart to highlight `this`. `@variable` is used to highlight assignments in dart but I'm doing it in quite a blunt way so will revisit at a later date. As I'm sure there is a proper way to do that

**Comment by kyazdani42** [comment]
is use `@variable.builtin` in jsx i think because those are kind of constants but are extendable so i consider them variables. Also you can consider it's builtin for web developement these days.

**Comment by kyazdani42** [comment]
@theHamsta is this still relevant ?

**Comment by theHamsta** [comment]
I guess most languages still don't use `@variable` though `@identifier` got eliminated. The highlights are still not documented.
```
➜ rg @variable
queries/go/highlights.scm
9:(identifier) @variable

queries/rust/highlights.scm
100:(self) @variable.builtin

queries/javascript/highlights.scm
13:(identifier) @variable
24:((identifier) @variable.builtin
25: (#vim-match? @variable.builtin "^(arguments|module|console|window|document)$"))
92:(this) @variable.builtin
93:(super) @variable.builtin

queries/jsx/highlights.scm
8:(jsx_closing_element name: (identifier) @variable.builtin)
9:(jsx_opening_element name: (identifier) @variable.builtin)
10:(jsx_self_closing_element name: (identifier) @variable.builtin)

queries/fennel/highlights.scm
7:(identifier) @variable

queries/dart/highlights.scm
116:  left: (assignable_expression) @variable)
118:(this) @variable.builtin
126:  (label (identifier) @variable.parameter))
196:((identifier) @variable.builtin
197: (#vim-match? @variable.builtin "^(abstract|as|covariant|deferred|dynamic|export|external|factory|Function|get|implements|import|interf
ace|library|operator|mixin|part|set|static|typedef)$"))

queries/c_sharp/highlights.scm
174:] @variable.builtin

queries/php/highlights.scm
42:(relative_scope) @variable.builtin
50:((name) @variable.builtin
51: (#eq? @variable.builtin "this"))
53:(variable_name) @variable

queries/query/highlights.scm
6:  name: (identifier) @variable

CONTRIBUTING.md
140:@variable
```

**Comment by kyazdani42** [comment]
maybe we should just document the highlight groups and just remove `@variable`.
`@variable.builtin` does make sens, but they could just be `@builtin` maybe. But `@builtin` could also mean different things.
all the `this` `self`, and global objects in interpreted languages could be `@variable.builtin`, which makes sense.

**Comment by vigoux** [comment]
I quite like the `variable.builtin` in opposition to `constant.buitlin`, so I think it is worth keeping.

**Comment by theHamsta** [comment]
`@variable` is useful for those people who want to give basic identifiers a color. We should add it in one PR for all languages. I can take care of this weekend if it didn't happen before.

**Comment by kyazdani42** [comment]
i dont know if basic identifiers should be considered as variable (i'm never quite sure what identifier is though)

**Comment by theHamsta** [comment]
The concept `@variable` = identifier comes from upstream queries. It's basically anything that can have a name. If we use the same name we should keep the concept. To have it in the queries but not highlight it was the compromise between people who don't want to give almost anything else a highlight and those who want to configure a certain highlight. The conclusion of the last discussion was that it's not really needed for most users but might give an extra configuration option for a minority (?).
