### ISSUE TITLE
[Markdown] E13: File exists (add ! to override)

### ISSUE THREAD

**Issue by numToStr** [nvim-treesitter/nvim-treesitter#3074]
### Describe the bug

Unable to `:write` markdown files. This was working fine with non-split markdown parser.

Ref https://github.com/nvim-treesitter/nvim-treesitter/pull/3048

### To Reproduce

1. Run `:TSInstall markdown markdown_inline`
2. Open any markdown file
3. Run `:write`
4. Prints `E13: File exists (add ! to override)`

### Expected behavior

Should be able to `:write` markdown files

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.15.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - markdown_inline✓ . . . ✓
  - markdown       ✓ . ✓ . ✓
```

### Output of `nvim --version`

```text
NVIM v0.8.0-dev+494-ge2f9d0332
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Additional context

- If I do `ignore_install = { 'markdown', 'markdown_inline' }` then I am able to `:write`
- I am using neovim inside WSL.

**Comment by kyazdani42** [comment]
Might be fixed by https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/219, can you confirm ?

**Comment by numToStr** [comment]
@kyazdani42 yes, it does fix the issue.

**Comment by kyazdani42** [comment]
it's been merged, closing this then ! Thanks for testing this out :)
