### ISSUE TITLE
`#match?` is broken

### ISSUE THREAD

**Issue by stsewd** [nvim-treesitter/nvim-treesitter#308]
The match predicate doesn't work when matching multiple options `|`. For example, this python file

```python
class Foo:

    def foo(self):
        pass

    def bar(cls):
        pass
```

This query works

```
((function_definition (identifier) @foo) (#match? @foo "^(foo)$"))
```

This query doesn't work

```
((function_definition (identifier) @foo) (#match? @foo "^(foo|bar)$"))
```

**Comment by steelsojka** [comment]
match now uses lua patterns by default. For vim regexes we'll need to use `#vim-match?`

**Comment by theHamsta** [comment]
A lot of queries should be broken now especially the ones searching for keywords. They use a lot of |

**Comment by stsewd** [comment]
Hmm, wouldn't this break query files that are outside this repo? (I think we use those by default if we don't override them here)

**Comment by stsewd** [comment]
I see, this was changed in https://github.com/neovim/neovim/pull/12739. Not sure how different are lua regexes with the "basic" spec (is surprising `|` doesn't work)

**Comment by kyazdani42** [comment]
lua regex doesn't have group matching. Lua regexes are quite simplistic that's why they are faster than other ones.
