### ISSUE TITLE
Error when opening typescript file with 500 lines 

### ISSUE THREAD

**Issue by brenoprata10** [nvim-treesitter/nvim-treesitter#3090]
### Describe the highlighting problem

Nvim-treesiter works just fine with my setup, but when i open a long file, i get this error and i notice a big delay on my typing

I never experienced any kind of slow behavior before adding nvim-treesiter plugin, so i guess it's not my PC performance.

I notice this slow behavior when i start seeing autocomplete options, i also use COQ plugin by the way

### Example snippet that causes the problem

![image](https://user-images.githubusercontent.com/26099427/176405325-7b5ccb5a-44e4-4777-a572-962c9d7ebff8.png)

### Tree-sitter parsing result

.

### Example screenshot

![image](https://user-images.githubusercontent.com/26099427/176405325-7b5ccb5a-44e4-4777-a572-962c9d7ebff8.png)

### Output of `:checkhealth nvim-treesitter`

```markdown
https://user-images.githubusercontent.com/26099427/176407887-7b172086-2c09-4606-bd26-74c31c9cb4cc.png
```

### Output of `nvim --version`

```text
v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az164-457

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Comment by kyazdani42** [comment]
treesitter does not dump error about timeouts, it might come from another plugin. Did you try to reproduce using a minimal config ?

**Comment by brenoprata10** [comment]
It's COQ plugin that is triggering this error, sorry for the false alarm :p
