### ISSUE TITLE
Way to find the correct parser

### ISSUE THREAD

**Issue by carlitux** [nvim-treesitter/nvim-treesitter#31]
Hi,

I was playing with the plugin and I found these:

- javascript parser works well but not support for flowtype, not related to this plugin

- typescript has support for flowtype on files that has filetype javascript - https://github.com/tree-sitter/tree-sitter-typescript/pull/67

- on research atom do a mix of filetype - content regexp https://github.com/atom/language-typescript/pull/14/files

**Comment by kyazdani42** [comment]
Hi,
I'm not too sure what you are talking about. Flow is a type system for javascript right ?
It shouldn't be used in typescript files as typescript already is a type system that wraps javascript.

If you could elaborate what you were trying to suggest here it would be nice, thanks.

**Comment by carlitux** [comment]
Sorry I didn't explain to you well.

Yes, flow is a type system for javascript but **tree-sitter-typescript** supports it please see https://github.com/tree-sitter/tree-sitter-typescript/pull/67, **tree-sitter-javascript** doesn't support flow.

You can confirm this in this pull request of **atom** that uses **tree-sitter-typescript** for javascript files that have flow content.

How can I use **tree-sitter-typescript** in **nvim-treesitter** for javascript files that also have **(/\\*([^*]|\\*[^/])*|//.*)@flow** content ?

**Comment by kyazdani42** [comment]
Well i really don't see the point of parsing flow inside typescript as they are different type systems.
To resolve that you could change the filetype of your javascript files to typescript so you can use the typescript parser instead.
I will investigate more on my end to find the proper way to handle that particular case.

I must also inform you that at the moment, we do not yet have query files for javascript and typescript. Those will come along soon, informations about that will be added to the README.

**Comment by carlitux** [comment]
> To resolve that you could change the filetype of your javascript files to typescript so you can use the typescript parser instead.

I thought that also but doing that but issues raise with completion, diagnostic, and all the stuff that starts using tsserver instead of flow.

Only tree-sitter typescript is required.

> I must also inform you that at the moment, we do not yet have query files for javascript and typescript. Those will come along soon, informations about that will be added to the README.

Yes, I know I added some to test

Thank you very much for the plugin!

**Comment by kyazdani42** [comment]
Yes you are right, i didn't think about other plugins.
Well i'm gonna work on fixing that in the next days.

**Comment by vigoux** [comment]
I think that this issue will be fixed along with #63 , as it will provide a way to trigger various parsers for some filetypes. Am I wrong ?

**Comment by kyazdani42** [comment]
This PR doesn't add the ability to trigger multiple parsers but adds the ability to use extended query files for a language. Right now, it will partially fix this issue, but this is a little bit more complicated, as we would need javascript files to actually use the typescript parser instead of the javascript one on files that have flow types (which is quite wrong IMHO).

**Comment by kyazdani42** [comment]
Either we should use the typescript parser for everything, or we would need to detect that a javascript file has flow content.

**Comment by kyazdani42** [comment]
Updating this:
For this issue to be resolved, there are a few things to note:
- if we use the typescript parser, then react queries would not work, so we would need to use the tsx parser, which i hope has flow integration too.
- we would need to dynamically parse the file each time we require a parser for the filetype, to detect if it has flow content in it.
- we could do that only on javascript files though, but right now, i don't properly see how it should be done.
Also note that during runtime, if editing javascript file and adding the first flow annotations, it would not change the parser and would require reloading the whole buffer.

**Comment by kyazdani42** [comment]
resolved in #617

**Comment by carlitux** [comment]
there is a way to use typescript as parser when flow type is in use?

I can't see jsdoc working, something to do to get it working?

**Comment by kyazdani42** [comment]
you need to enable the languagetree feature for jsdoc:
```
lua <<EOF
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
    use_languagetree = true,
  },
}
EOF
```
I don't think we know how to detect flow content in a javascript file to enable the typescript parser instead.
I believe this should be done as a plugin as it is too framework oriented. We already exported angular support as a plugin (see [this](https://github.com/nvim-treesitter/nvim-treesitter-angular))

**Comment by theHamsta** [comment]
Is flow type just a different file type? You can add a used_by clause to the typescript parser. If it's mixture of many languages you can have a look on how languages injection is working (injection.scm). But it requires you to use the language tree implementation for the parser.

>I can't see jsdoc working, something to do to get it working?

Waiting. There is a pr for language injection (language tree) for Neovim.

**Comment by kyazdani42** [comment]
i think flow types have annotations at the beginning of a file (something like `@flow`), but the filetype is still javascript, this is why it bothers me to handle that inside nvim-treesitter as it would require parsing the first line of the file beforehand just for this use case and add a lot of unwanted complexity.

**Comment by theHamsta** [comment]
Applying a regex on the first few lines is very common for vim filetype detect. Probably this can be handled by a plugin like https://github.com/nvim-treesitter/nvim-treesitter-angular

**Comment by kyazdani42** [comment]
yes thats what i was advising

**Comment by carlitux** [comment]
@kyazdani42 @theHamsta I added this as ftdetect

```vim
au! BufRead,BufNewFile *.js if getline(1) =~ '//\s*@flow' | setf flowtype | endif
```

and editing https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/parsers.lua#L188 adding
```
used_by: { 'flowtype' }
```

I have it worked but I can't find a way to edit that from outside nvim-treesitter code, anything like nvim-lspconfig setup?

**Comment by theHamsta** [comment]
There should already be a filetypedetect for the query filetype.

**Comment by kyazdani42** [comment]
why wouldn't you set the filetype as typescript if the typescript parser supports flow ?

**Comment by carlitux** [comment]
@kyazdani42 yes it is an option, but then lsp config gets complicated to find a way to enable flow for typescript filetypes but disable typescript server. Also to reenable typescript server for plain javascript or for real typescript files.
