### ISSUE TITLE
Markdown error (query: invalid node type at position)

### ISSUE THREAD

**Issue by Integralist** [nvim-treesitter/nvim-treesitter#3108]
### Describe the bug

Opening certain files, in this case a `.md` Markdown file I see the following text displayed across multiple lines:

```
spellsitter: Error executing lua: ...im/0.7.2/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 2
```

<img width="1624" alt="Screenshot 2022-07-02 at 20 50 45" src="https://user-images.githubusercontent.com/180050/177014788-170b0a44-86cc-45dd-aee4-ede9adb74617.png">

### To Reproduce

Open a Markdown file and scroll down.

### Expected behavior

No error output.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.9.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - gomod          ✓ . . . ✓ 
  - dockerfile     ✓ . . . ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - cmake          ✓ . ✓ . . 
  - http           ✓ . . . ✓ 
  - make           ✓ . . . ✓ 
  - hcl            ✓ . ✓ ✓ ✓ 
  - regex          ✓ . . . . 
  - bash           ✓ ✓ ✓ . ✓ 
  - help           ✓ . . . . 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - zig            ✓ . ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - gowork         ✓ . . . ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - vim            ✓ ✓ ✓ . ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - markdown       ✓ . ✓ . ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.2/share/nvim"

Run :checkhealth for more info
```

### Additional context

I've tried all the various solutions mentioned in the pinned issue as well as https://github.com/nvim-treesitter/nvim-treesitter#i-get-query-error-invalid-node-type-at-position but none of it has worked.

Interestingly when removing treesitter and reinstalling it, there was an error with the post hook:
<img width="1624" alt="Screenshot 2022-07-02 at 20 53 48" src="https://user-images.githubusercontent.com/180050/177014846-f8e2f26a-3e15-4f47-a640-c47cbfbc728d.png">

But when running `:TSUpdate` everything was fine.

I also tried removing `markdown` from the list of parsers: https://github.com/Integralist/dotfiles/blob/main/.config/nvim/init.vim#L593-L612 but that didn't help either.

**Comment by clason** [comment]
As you ca see, , these errors are emitted by spellsitter, which is a separate plugin. Please report to lthe error there or provide a minimal reproducing example without any other plugins.
