### ISSUE TITLE
Suggested installation configuration for packer errors on fresh install

### ISSUE THREAD

**Issue by qubidt** [nvim-treesitter/nvim-treesitter#3135]
### Describe the bug

When using the [suggested installation configuration for Packer](https://github.com/nvim-treesitter/nvim-treesitter/wiki/Installation#packernvim):

```lua
    use {
        'nvim-treesitter/nvim-treesitter',
        run = ':TSUpdate'
    }
```

This errors out on a fresh install (with a default packer configuration) with the error:

```
[packer.nvim] [ERROR 19:21:25] async.lua:20: Error in coroutine: ...ack/packer/start/packer.nvim/lua/packer/plugin_utils.lua:236: Vim:E492: Not an editor command: TSUpdate
```

I'm not 100% sure of how all the setup/`require`ing/etc. happens, but calling the `nvim-treesitter.install.update()` directly resolves this. Not sure if that should be recommended since it *seems* internal to this plugin.

### To Reproduce

A minimal `init.lua` to reproduce:

```lua
local fn = vim.fn
local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
	packer_bootstrap = fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
end

return require('packer').startup(function(use)
	use { "wbthomason/packer.nvim" } -- let packer manage itself
	use {
		"nvim-treesitter/nvim-treesitter",
		run = ':TSUpdate'
	}
	if packer_bootstrap then require("packer").sync() end
end)
```

that will cause the initial packer setup to fail:

```
               packer.nvim - finished in 0.792s                  │
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ │~
 ✗ Failed to install nvim-treesitter/nvim-treesitter             │~
```

and the error in `:messages`:

```
[packer.nvim] [ERROR 19:21:25] async.lua:20: Error in coroutine: ...ack/packer/start/packer.nvim/lua/packer/plugin_utils.lua:236: Vim:E492: Not an editor command: TSUpdate
```

### Expected behavior

Packer bootstrapping completes successfully. This minimal configuration:

```lua
local fn = vim.fn
local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
	packer_bootstrap = fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
end

return require('packer').startup(function(use)
	use { "wbthomason/packer.nvim" } -- let packer manage itself
	use {
		"nvim-treesitter/nvim-treesitter",
		-- :TSUpdate[Sync] doesn't exist until plugin/nvim-treesitter is loaded (i.e. not after first install); call update() directly
		run = function() require("nvim-treesitter.install").update { with_sync = true } end
	}
	if packer_bootstrap then require("packer").sync() end
end)
```

works as expected:

```
               packer.nvim - finished in 0.789s                  │
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ │~
 ✓ Installed nvim-treesitter/nvim-treesitter                     │~
```

### Output of `:checkhealth nvim-treesitter`

```markdown
n/a
```

### Output of `nvim --version`

```text
v0.8.0-dev+563-gc68f1d7263 (w/ LuaJIT 2.1.0-beta3), but also happening on 0.7.2
```

**Comment by kyazdani42** [comment]
I think you need to first call the setup for the configs before updating (`require 'nvim-treesitter.configs'.setup()`)

**Comment by qubidt** [comment]
Assuming you mean something like:

```lua
		use {
			"nvim-treesitter/nvim-treesitter",
			run = ':TSUpdate',
			config = function() require('nvim-treesitter.configs').setup({
				ensure_installed = { "lua" },
				sync_install = true,
				auto_install = true,
			}) end,
		}
```

That also doesn't work either:

```
[packer.nvim] [ERROR 04:29:17] async.lua:20: Error in coroutine: ...ack/packer/start/packer.nvim/lua/packer/plugin_utils.lua:236: Vim:E492: Not an editor command: TSUpdate                                                                     
```

I believe the issue is because `:TSUpdate` doesn't exist until `require("nvim-treesitter.utils").setup_commands()` is called, which only happens in `nvim-treesitter.setup()`:

https://github.com/nvim-treesitter/nvim-treesitter/blob/3c50297eca950b4b1a7c07b28e586b0576c0a796/lua/nvim-treesitter.lua#L13-L18

which only gets called by `/plugin/nvim-treesitter.lua`:

https://github.com/nvim-treesitter/nvim-treesitter/blob/1f508ff394a288f4fc59104194880e1e42c0f366/plugin/nvim-treesitter.lua#L9

The problem is that (I believe) neovim sources `/plugin/nvim-treesitter.lua` but only on startup. The sequence of events on a fresh install I mentioned in the OP is:

1. User starts neovim with no state except aforementioned `init.lua`
2. Neovim checks $VIMRUNTIME/plugin for plugins (nvim-treesitter does not exist yet)
3. Packer bootstrapping code runs
4. Packer installs nvim-treesitter into `fn.stdpath('data')..'/site/pack/packer/`
5. Packer (in `packer.util.post_update_hook`) runs the plugin spec's `run` argument
	a. this fails because `/plugin/nvim-treesitter.lua` was never loaded so `setup_commands()` was never called

even changing the `run` in the Packer config to:

```lua
			run = function()
				require('nvim-treesitter.configs').setup({
					ensure_installed = { "lua" },
					sync_install = true,
					auto_install = true,
				})
				res = vim.api.nvim_cmd({cmd = "TSUpdate"}, {output = true})
			end,
```

doesn't help (Packer install still reports `✗ Failed to install nvim-treesitter/nvim-treesitter`) because `TSUpdate` does not get created by `require('nvim-treesitter.configs').setup`

**Comment by qubidt** [comment]
That's fine with me. Just wanted to make sure I wasn't doing the wrong thing by calling `nvim-treesitter.install.update()` directly. Mind if I update the wiki to make note of this then?

**Comment by frt** [comment]
Should work with only `run = require("nvim-treesitter.install").update()`, since the `update()` function always returns a function, that Packer will call later.
