### ISSUE TITLE
Option to disable default queries included with nvim-treesitter

### ISSUE THREAD

**Issue by nickeb96** [nvim-treesitter/nvim-treesitter#3146]
I can't find a way to disable a default highlighting query without manually editing the .scm file and clearing its contents.

I'd like to be able to **prevent** queries like `~/.local/.../nvim-treesitter/queries/rust/highlight.scm` from being loaded so my own queries in `~/.config/nvim/queries/rust/highlight.scm` will be use instead.

Currently they both get loaded at the same time, which I don't want.

If I specify `highlight = { enable = false }` in the treesitter config setup function, all highlight queries are disabled including mine.

I read through the documentation and did some googling, but couldn't find a solution.

**Comment by stsewd** [comment]
Hi, you need to use the `set_query` function, see https://github.com/nvim-treesitter/nvim-treesitter#adding-queries.

**Comment by nickeb96** [comment]
I don't think that's a great solution because it means I have to have the query as a lua string literal.

My `highlight.scm` file is almost 400 lines long.  Having to maintain a 400 line string literal wouldn't be a good longterm solution.

The other option is using `io.open("/path/to/.config/nvim/queries/rust/highlight.scm")` in a config file, reading the contents to a string, and then passing that to `set_query`.

This is a pretty hacky work around, and in my opinion even worse than the previous solution.

**Comment by stsewd** [comment]
There was some discussion around how to implement this in another way, like using the top level dir `queries` instead of the `after/queries` directory, but it settled on using the set_query function instead.

**Comment by nickeb96** [comment]
That's too bad.

It would make much more sense for .scm files in `.config/queries` to *override* the default queries, and then have `.config/after/queries` augment existing queries.

This would also better align with how native vim syntax files work.

The `set_query` function really isn't a good workaround if you have more than a couple queries to add.  And considering it overrides all existing queries, I think most use-cases for it would involve having to pass many large query strings to it.

Any way to revisit this discussion?

**Comment by theHamsta** [comment]
I agree with @nickeb96 that `set_query` is not a good solution. `set_query(function..)` would be slightly better since you wouldn't need to load and know everything about the query at start up.

@nickeb96 wants probably something like https://github.com/neovim/neovim/pull/15260. Also nvim-treesitter could wrap ` `set_query(function..)` in similar ways with config option like the PR . The queries could also not concatenate so that the queries could be overwritten by preferring something that comes first in rtp.

**Comment by milisims** [comment]
I also think this is not the best solution, it seems odd to me that `queries` dir won't override, but if it's not on nvim-treesitter's end, we can fix that easily.

I load this before queries are read, so I can use the `queries` dir as desired:
``` lua
local cfg = vim.fn.stdpath 'config'
for lang in vim.fs.dir(cfg .. '/queries') do
  for query in vim.fs.dir(('%s/queries/%s'):format(cfg, lang)) do
    if vim.endswith(query, '.scm') then
      local f = io.open(('%s/queries/%s/%s'):format(cfg, lang, query))
      if f then
        local qstr = f:read("*all")
        f:close()
        vim.treesitter.set_query(lang, query:sub(1, -5), qstr)
      end
    end
  end
end

```
Use of `pcall` is probably a good idea.

**Comment by gvolpe** [comment]
I'm trying to override the `scala` queries via `set_query`, but I get this error:

```console
E5108: Error executing lua ...ed-0.7.2/share/nvim/runtime/lua/vim/treesitte
r/query.lua:172: query: invalid node type at position 672
stack traceback:
        [C]: in function '_ts_parse_query'
        ...ed-0.7.2/share/nvim/runtime/lua/vim/treesitter/query.lua:172: in
 function 'parse_query'
        ...ed-0.7.2/share/nvim/runtime/lua/vim/treesitter/query.lua:119: in
 function 'set_query'
        [string ":lua"]:168: in main chunk
```

Can anyone tell what I'm doing wrong? I'm a newbie to Lua and the whole tree-sitter universe. Here's what I have:

```lua
        local scalaKeywords = [=[
          ;; Annotations

          "@" @operator

          ;; Types

          (class_definition
            name: (identifier) @type)
          (trait_definition
            name: (identifier) @type)
          (object_definition
            name: (identifier) @type)

          (type_identifier) @type

          ;; Variables

          ((identifier) @constant
           (#match? @constant "^_*[A-Z][A-Z\\d_]+$"))

          (identifier) @variable

          ;; Literals

          [
            (integer_literal)
            (floating_point_literal)
          ] @number

          [
            (character_literal)
            (string)
          ] @string

          [
            (boolean_literal)
            (null_literal)
          ] @constant.builtin

          (comment) @comment

          ;; Keywords

          [
            "abstract"
            "case"
            "catch"
            "class"
            "def"
            "do"
            "else"
            "enum"
            "export"
            "extends"
            "extension"
            "final"
            "finally"
            "for"
            "given"
            "if"
            "implicit"
            "import"
            "inline"
            "lazy"
            "match"
            "new"
            "object"
            "opaque"
            "open"
            "override"
            "package"
            "private"
            "protected"
            "return"
            "sealed"
            "summon"
            "then"
            "throw"
            "trait"
            "transparent"
            "try"
            "while"
            "while"
            "with"
          ] @keyword
        ]=];

        require'vim.treesitter.query'.set_query("scala", "highlight", scalaKeywords)
```

**Comment by theHamsta** [comment]
I would recommend to read the queries from a file and use the query linter GitHub.com/nvim-treesitter/playground to see what's wrong with your new query. You can also quickly paste the contents of your query into nvim-treesitter 's one. You may need to `:set ft=query`. Maybe scala is also in tree-sitter's own playground.

I agree that `set_query` os a pain to use and that we need a better solution.

**Comment by gvolpe** [comment]
@theHamsta thanks. FWIW even the example from the README file also fails with the same error, so I don't think it's the grammar. I should have clarified that.

```lua
require'vim.treesitter.query'.set_query("c", "injections", "(comment) @comment");
```

This fails with the same error. Perhaps something to do with the ABI versions? I realize I don't understand a lot of this stuff 😄 

```
vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for comment: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for elm: ABI version 13
  - OK: Loaded parser for graphql: ABI version 13
  - OK: Loaded parser for hare: ABI version 13
  - OK: Loaded parser for haskell: ABI version 13
  - OK: Loaded parser for html: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for make: ABI version 13
  - OK: Loaded parser for markdown: ABI version 13
  - OK: Loaded parser for nix: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for rust: ABI version 13
  - OK: Loaded parser for scala: ABI version 13
  - OK: Loaded parser for toml: ABI version 13
  - OK: Loaded parser for tsx: ABI version 13
```

**Comment by nickeb96** [comment]
Is there any way to just have queries in *~/.config/nvim/queries/* override the default queries?

**Comment by theHamsta** [comment]
@nickeb96 not directly at the moment. You can of course manually read the files from there and then use `set_query`. The disadvantage is that the queries will be loaded when you call `set_query` it would be better if it would accept a function and only load the query when needed. There are some proposal PRs open to disable nvim-treesitter queries. Maybe you can bump at one of these or create a own PR at upstream github.com/neovim/neovim . At the moment all queries in the runtime path get glued together. 

@gvolpe these are invalid node according to the Scala grammar
![grafik](https://user-images.githubusercontent.com/7189118/185761897-806d350e-8c61-45af-a68f-b8041169c27a.png)

**Comment by clason** [comment]
> Is there any way to just have queries in _~/.config/nvim/queries/_ override the default queries?

This is now the default (queries in "later" directories overwrite those in earlier ones unless they are explicitly marked as `;; extends`). So with Neovim 0.8, you can disable a builtin query by placing a corresponding empty query file in your `.config/nvim/queries`.
