### ISSUE TITLE
Segmentation fault when editing Lua file

### ISSUE THREAD

**Issue by smjonas** [nvim-treesitter/nvim-treesitter#3184]
### Describe the bug

When editing a Lua file containing a specific combination of characters and treesitter highlighting is enabled, Neovim crashes.

### To Reproduce

1. `nvim ~/test.lua` while `nvim-treesitter` is installed

I used the following minimal treesitter setup:
```lua
require("nvim-treesitter.configs").setup {
  highlight = {
    enable = true,
  },
}
```

2. Paste in the following file contents:
```lua
print
nil,
nil,
"",
--
print
```
3. Edit the first line (deletion, insertion) or append a `(` to the second line (there are probably more ways to reproduce this bug). 

### Expected behavior

No crash.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v17.9.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - html           ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - comment        ✓ . . . . 
  - markdown_inline✓ . . . ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.0-dev
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -DEXITFREE -I/tmp/nvim/build/cmake.config -I/tmp/nvim/src -I/tmp/nvim/.deps/usr/include -I/usr/include -I/tmp/nvim/build/src/nvim/auto -I/tmp/nvim/build/include
Compiled by root@jonas-MS-7C91

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Additional context

The issue does not occur when slightly altering the minimal example provided above (maybe someone can reduce it further though). (ping @MunifTanjim ?)

**Comment by MunifTanjim** [comment]
I tried with your exact example, but couldn't reproduce it 🤔

**Comment by kyazdani42** [comment]
could not reproduce either.

**Comment by smjonas** [comment]
No idea why, but I can't reproduce it either now... Closing unless it occurs again.

**Comment by smjonas** [comment]
Ok, I am, really confused why I could not reproduce it anymore earlier. This is definitely still an issue on my side. I uninstalled all my plugins except `nvim-treesitter` just to be sure.

Is there any way I can debug this further?

https://user-images.githubusercontent.com/40792180/179349239-20278a72-b0e4-4993-9349-6d9c63f35df1.mp4

**Comment by smjonas** [comment]
Seems to be solved by upgrading to the latest Neovim nightly version (appimage) :)
