### ISSUE TITLE
Folds based on import nodes

### ISSUE THREAD

**Issue by abenz1267** [nvim-treesitter/nvim-treesitter#3196]
Is it possible to "extend" the treesitter foldexpr to also create folds for imports? I looked at the source and to me it looks like it's creating folds based on nodes, but there's no logic to look for subsequent nodes and create a fold based on that. Is that correct?

So f.e. in Typescript there's a "import_statement" node, but  because it's just 1 line, it's not creating a fold. Makes sense. What needs to happen is nvim checking for subsequent "import_statment"s until none is found anymore and create a fold based on that range. Would that be correct?

I'm normally not much of a fan of hiding imports, but sometimes it can be a bit excessive (...looking at you, Java...).

What do you think?

**Comment by kyazdani42** [comment]
@theHamsta is it possible to match a range of nodes ?

**Comment by theHamsta** [comment]
This will be better supported in https://github.com/neovim/neovim/pull/17099 , you will then get `(import_statement)* @import` grouped in the query results.

We still have our old `TSRange` interface but no modern directives using it.

**Comment by lewis6991** [comment]
No plans to implement this, but PR's welcome.
