### ISSUE TITLE
Activating inconsistently

### ISSUE THREAD

**Issue by dzfrias** [nvim-treesitter/nvim-treesitter#3224]
### Describe the bug

Treesitter activates inconsistently when entering neovim. In what seems to be a random pattern, treesitter's highlights sometimes work and sometimes don't.

## Steps
1. Install with `Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}`
2. Put the following settings in your init.vim:
```vim
lua << EOF
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
    },
  }
EOF
```
3. Install the go parser with `TSInstall go`
4. Enter a go file

## Notes
The parser may or may not activate. After entering the same file a bunch of times, only some had treesitter's highlighting, while the rest were normal. After checking `:scriptnames`, it seems like the treesitter plugin isn't sourced when it doesn't work.

### Expected behavior

Treesitter's highlighting should work and be activated, in any form.

### Output of `:checkhealth nvim-treesitter`

```markdown
<!-- On a successful load of treesitter -->
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.14.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - go             ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}



<!-- On an unsuccessful load of treesitter -->
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.14.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - go             ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.2_1/share/nvim"

Run :checkhealth for more info
```

### Additional context

I've tried uninstalling treesitter. Manually sourcing the treesitter plugin and then writing the file works, but I'm not sure how to automate that process.

**Comment by kyazdani42** [comment]
This might be an plug initialization issue. Did you try adding the setup call in the after directory ?

**Comment by dzfrias** [comment]
I put it in runtime/after/plugin/load_treesitter.vim and it still had the inconsistent activation. I could try installing it manually instead of using vim-plug.

**Comment by dzfrias** [comment]
Using vim's built-in package manager makes treesitter work correctly. I'm not sure if I should close this issue because using vim-plug would be nice for consistency's sake.

**Comment by kyazdani42** [comment]
on nvim-tree, nvim-treesitter and nvim-web-devicons which i maintain, people with configuration issues mostly use plug, so believe this might just be related to how plug manages the runtime. Using something like packer or neovim builtin pack commands works just fine.

**Comment by dzfrias** [comment]
Ok good to know. Since it doesn't seem tied to this specific plugin, I'll go ahead and close this issue
