### ISSUE TITLE
Inconsistant Syntax highlight for C/C++ on Nvim

### ISSUE THREAD

**Issue by Patroklos99** [nvim-treesitter/nvim-treesitter#3227]
version 0.7.0 C/ C++ parsers are up to date.

Left is on clion using gruvbox, right is on nvim using gruvbox. 
Ive disabled Treesitter and gruvbox highlighted more coherently but not all data types/key words. True colors were applied.

![gruvbox](https://user-images.githubusercontent.com/96098657/181278670-924c9863-56b3-45f7-b2a1-3102b9a5fb6f.png)

``` 1                                                                                                                                                           
  2 nvim-treesitter: require("nvim-treesitter.health").check()
  3 ========================================================================
  4 ## Installation
  5   - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  6   - WARNING: `node` executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
  7   - OK: `git` executable found.
  8   - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  9     Version: cc (Debian 10.2.1-6) 10.2.1 20210110
 10   - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.
 11 
 12 ## Parser/Features H L F I J
 13   - cpp            ✓ ✓ ✓ ✓ ✓ 
 14   - c              ✓ ✓ ✓ ✓ ✓ 
 15 
 16   Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
 17          +) multiple parsers found, only one will be used
 18          x) errors found in the query, try to run :TSUpdate {lang}```

**Comment by kyazdani42** [comment]
shouldn't this be an issue for gruvbox instead of nvim-treesitter ?

**Comment by Patroklos98** [comment]
> shouldn't this be an issue for gruvbox instead of nvim-treesitter ?

No. I tried different themes and they all sit on top of tree-sitter. The color they give is based on what treesitter dictates, atleast thats my understanding and what I saw from my tests.

**Comment by theHamsta** [comment]
@Patroklos98 we give default mapping to built-in Vim highlight groups. A color scheme can either assign colors to Vim highlight groups or it can map our highlight groups to colors. The latter is what some color scheme refer as "Tree-sitter support" and gives the color scheme more control. The for the first option we decide which Vim highlight group what language component is mapped to.

Please be more specific in this issue on what should be changed: e.g. is our mapping to Vim highlight group wrong or is the mapping of C++ language construct to our highlight groups wrong. If yes it would be more effective to name concrete examples. `:TSHighlightUnderCursor` helps to explain what `:h syntax` is doing when tree-sitter  is off or what we are doing when tree-sitter is on.
