### ISSUE TITLE
Stray space in check health implementation

### ISSUE THREAD

**Issue by Lilja** [nvim-treesitter/nvim-treesitter#3248]
How `:checkhealth` looks like when `vim.opt.list=true` and shows leading spaces.

<img width="996" alt="bild" src="https://user-images.githubusercontent.com/6134511/182119885-f2ee61b5-033d-4f6e-a5bf-83f2008548fa.png">

Culprit: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/health.lua#L126

Suggestion:
```diff
- out = out .. status .. " "
+ out = out .. status
```

**Comment by theHamsta** [comment]
Thanks! You want to open a PR?

**Comment by theHamsta** [comment]
Ok, I already tried to fix it #3253
