### ISSUE TITLE
node_incremental for incremental selection jumping around

### ISSUE THREAD

**Issue by Jaco-Minnaar** [nvim-treesitter/nvim-treesitter#3255]
### Describe the bug

When I hit the key mapped to `node_incremental`, I'm put back in Normal mode, the cursor jumps to the end of the file, and a new line is inserted somewhere in the file.

### To Reproduce

1. Hit key mapped to `init_selection` (this works as expected).
2. Hit key mapped to `node_incremental`.
3. See described behavior.

### Expected behavior

The visual selection to increment to the next node.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.15.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - go             ✓ ✓ ✓ ✓ ✓
  - json           ✓ ✓ ✓ ✓ .
  - vim            ✓ ✓ ✓ . ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - zig            ✓ . ✓ ✓ ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - bash           ✓ ✓ ✓ . ✓
  - cpp            ✓ ✓ ✓ ✓ ✓
  - c_sharp        ✓ ✓ ✓ . ✓
  - css            ✓ . ✓ ✓ ✓
  - dockerfile     ✓ . . . ✓
  - glsl           ✓ ✓ ✓ ✓ ✓
  - php            ✓ ✓ ✓ ✓ ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - scss           ✓ . . ✓ .
  - tsx            ✓ ✓ ✓ ✓ ✓
  - typescript     ✓ ✓ ✓ ✓ ✓
  - yaml           ✓ ✓ ✓ ✓ ✓
  - html           ✓ ✓ ✓ ✓ ✓
  - rust           ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
           +) multiple parsers found, only one will be used
           x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.0-dev-762-g0a049c322
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by jaco@roshar

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Additional context

I've tried recompiling Neovim from the stable branch, remapping the keymap for  `node_incremental`, but nothing seems to work. This worked before yesterday.

**Comment by argshook** [comment]
Hey, i seem to be able to reproduce as well.

Looks like [this commit](https://github.com/nvim-treesitter/nvim-treesitter/commit/22824614163c54ef5d366b15c8685e24d33763db) introduced an issue.

Naively reverting this change locally fixes it.

in my case in the file resides at:
```
~/.local/share/nvim/plugged/nvim-treesitter/lua/nvim-treesitter/incremental_selection.lua
```

Here's a PR with relevant lines reverted. Using this incremental selection keymaps work well for me

https://github.com/nvim-treesitter/nvim-treesitter/pull/3256

**Comment by itepechi** [comment]
Caused by these lines:

```lua
local function visual_selection_range()
  local _, csrow, cscol, _ = unpack(vim.fn.getpos "'<")
  local _, cerow, cecol, _ = unpack(vim.fn.getpos "'>")
```

The marks `'<` and `'>` are only accessible outside of visual mode.
