### ISSUE TITLE
Neovim nightly freezes with org tree-sitter parser and existing highlights.scm query file

### ISSUE THREAD

**Issue by kristijanhusak** [nvim-treesitter/nvim-treesitter#3258]
### Describe the bug

When trying to input asterisk on a nightly release with a https://github.com/milisims/tree-sitter-org parser for org, Neovim completely freezes and starts consuming all available memory until the point where you have to kill it. At first I thought there's something wrong with my plugin, but it turns out something with tree-sitter is messed up.

`highlights.scm` file is the culprit. If it exists, even completely empty, Neovim freezes. If it doesn't exist, everything works fine. I'm not able to figure out what's happening so maybe someone else will be able to figure it out with the reproducible steps.

Note that Neovim 0.7.2 works fine.

Original issue reported on nvim-orgmode repo: https://github.com/nvim-orgmode/orgmode/issues/370

### To Reproduce

1. Use this minimal init:

```lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  vim.fn.mkdir(package_root..'/packer/start/test-org/queries/org', 'p')
  vim.fn.writefile({}, package_root..'/packer/start/test-org/queries/org/highlights.scm')
  require('packer').startup({
    {
      'wbthomason/packer.nvim',
      { 'nvim-treesitter/nvim-treesitter' },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  })
end

_G.load_config = function()
  local parser_config = require('nvim-treesitter.parsers').get_parser_configs()
  parser_config.org = {
    install_info = {
      url = 'https://github.com/milisims/tree-sitter-org',
      revision = 'main',
      files = { 'src/parser.c', 'src/scanner.cc' },
    },
    filetype = 'org',
  }
  require('nvim-treesitter.configs').setup({
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = { 'org' },
    },
  })

  vim.cmd([[packadd nvim-treesitter]])
  vim.cmd([[runtime plugin/nvim-treesitter.lua]])
  vim.cmd([[TSUpdateSync org]])

  -- Close packer after install
  if vim.bo.filetype == 'packer' then
    vim.api.nvim_win_close(0, true)
  end
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({ 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path })
  load_plugins()
  require('packer').sync()
  vim.cmd([[autocmd User PackerCompileDone ++once lua load_config()]])
else
  load_plugins()
  load_config()
end
```

2. Open Neovim with the minimal init and a test org file: 
```
   nvim -u minimal_init.lua test.org
```
**On the prompt just press Enter**. Minimal init creates an empty `highlights.scm` for you (Line 8 and 9).
3. Once the Packer finishes installing, try typing `*`. Neovim will freeze.

### Expected behavior

Expect Neovim not to freeze and work like on 0.7.2.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.13.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - org            . . . . . 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.0-dev-762-g0a049c322
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az151-687

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Comment by theHamsta** [comment]
@kristijanhusak Have you tried `:TSInstallFromGrammar` ? `parser.c` is generate for ABI 13. ABI 14 brings optimizations for loading speed of queries. `:TSInstalLFromGrammar` will regenerate for the best ABI (=the runtime version of your neovim installation). There were similar issues with Swift

**Comment by theHamsta** [comment]
It's a lot better for me with `:TSInstallFromGrammar`. We can change the parser to `requires_generate_from_grammer = true`

**Comment by theHamsta** [comment]
ABI 14 (parsing an almost empty file)
```

**Comment by kristijanhusak** [comment]
> @kristijanhusak Have you tried `:TSInstallFromGrammar` ? `parser.c` is generate for ABI 13. ABI 14 brings optimizations for loading speed of queries. `:TSInstalLFromGrammar` will regenerate for the best ABI (=the runtime version of your neovim installation). There were similar issues with Swift

Just tried, unfortunately same thing.

**Comment by aareman** [comment]
I have this issue when trying to enter a `#+results` block (freezes at the `+`)

**Comment by kristijanhusak** [comment]
> I have this issue when trying to enter a `#+results` block (freezes at the `+`)

My guess with all of this is that issue is related to some regex. Both `*` and `+` are special regex characters, and putting it at the start probably causes something to match "everything", and freezes.
Don't have any proof though, just throwing some ideas out.

**Comment by Maltimore** [comment]
I think we should pay more attention to the fact that neovim 0.7.2 works fine. There's not that much time between the release date of 0.7.2 and the original bug report. I think bisecting to find the commit that introduced this bug shouldn't be too hard. If I ever find the time, I'll try it.

**Comment by Maltimore** [comment]
I found the time! I bisected it. The culprit is this PR https://github.com/neovim/neovim/pull/19347 which, perhaps unsurprisingly, bumps treesitter to HEAD.

**Comment by kristijanhusak** [comment]
Thanks for finding the issue @Maltimore . I guess this should be reported upstream, on the same PR. @theHamsta will you do that or should I?

**Comment by theHamsta** [comment]
@kristijanhusak feel free to report. Have you investigated what the actual issue is? In which function is it hanging: parsing, querying?

**Comment by kristijanhusak** [comment]
@theHamsta I haven't investigated since I didn't knew how. It's way out of my knowledge scope around tree-sitter. I'll just mention this issue in the upstream PR, and let someone who knows how to debug it to figure it out.

**Comment by theHamsta** [comment]
I'll have a look on it

**Comment by clason** [comment]
First step is to bisect which exact tree-sitter (not Neovim!) commit broke the org parser. It's possible that the parser's `scanner.cc` needs adapting.

**Comment by kristijanhusak** [comment]
> First step is to bisect which exact tree-sitter (not Neovim!) commit broke the org parser.
> 
> You should also report it on the parser repo since it's possible that the parser's `scanner.cc` needs adapting.

@milisims maybe you can figure out what's happening here, or if `scanner.cc` needs some updates for the latest tree-sitter.

**Comment by Maltimore** [comment]
If I didn't make an error, I bisected the treesitter commit after which the bug occurs to this one:

https://github.com/tree-sitter/tree-sitter/commit/d223a81b5064587af3a5f61f52d519670ba8995f

**Comment by clason** [comment]
The effects seem to be known, then: https://github.com/tree-sitter/tree-sitter/pull/1783

**Comment by Maltimore** [comment]
There's absolutely no way how neovim could intervene in this endless loop between tree-sitter and the tree-sitter grammar? I'm just thinking it's a bit strange, that each of the dozens of tree-sitter grammars need to get this right, and otherwise there's always the danger of neovim freezing entirely, potentially losing some unsaved changes. Even if this gets fixed on the tree-sitter side, one could think in general whether neovim could monitor for such endless loops.

**Comment by clason** [comment]
That is a separate question (timeouts) that has been discussed before.

But _this_ issue needs to be fixed; it's just how things work. A timeout would still lead to broken syntax highlighting, which is not acceptable.

**Comment by kristijanhusak** [comment]
This issue was fixed in the org grammar as suggested. If you don't need this ticket any more, you can close it.
Thanks for your help.
