### ISSUE TITLE
slow on large go file

### ISSUE THREAD

**Issue by rhinoxi** [nvim-treesitter/nvim-treesitter#3263]
### Describe the bug

same issue as this one #3187 
found if I comment following lines in [injections.scm](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/go/injections.scm), the lag disappeared.
```
((comment) @c (#offset! @c 1 0 0 -2)
  (import_declaration
    (import_spec path: (interpreted_string_literal) @_import_path))
  (#eq? @_import_path "\"C\""))
```

### To Reproduce

https://user-images.githubusercontent.com/4988151/182517160-79f642e2-7c9e-4c32-9340-91ed158b17da.mp4

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (ccd6bf554d922596ce905730d98a77af368bba5c) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.1.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - python         ✓ ✓ ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - commonlisp     ✓ ✓ ✓ . . 
  - make           ✓ . . . ✓ 
  - http           ✓ . . . ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - graphql        ✓ . . ✓ ✓ 
  - help           ✓ . . . . 
  - vim            ✓ ✓ ✓ . ✓ 
  - cmake          ✓ . ✓ . . 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - sql            ✓ . . . ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - dart           ✓ ✓ . ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - gomod          ✓ . . . ✓ 
  - dot            ✓ . . . ✓ 
  - markdown       ✓ . ✓ . ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
v0.7.2
```

### Additional context

https://github.com/NvChad/NvChad/issues/1415

**Comment by obmutescences** [comment]
same as me. my go file 2000+ lines, edit so lags

**Comment by obmutescences** [comment]
> ```
> require("vim.treesitter.query").set_query("go", "injections", "(comment) @comment")
> ```
> @obmutescences  try this

l'll try later. tks

**Comment by theHamsta** [comment]
Would be interesting to investigate why this query is slow, either because it grabs the text of every comment in the file on every keystroke or there's something wrong with the query

**Comment by rhinoxi** [comment]
I have a few doubts:

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/4988151/183230245-45a63229-899e-4ffc-a72f-65f1a39baa9a.png">

1. the offset part is trying to get rid of the first and last line of the comment, but what if the comment is using `//` not `/* ... */`
2. the siblings query tries to find out not only the next sibling, but all siblings after itself, is it the reason of the slow query?
