### ISSUE TITLE
Highlighting completely gone for all languages in Windows 10/11

### ISSUE THREAD

**Issue by dvchoudh** [nvim-treesitter/nvim-treesitter#3271]
### Describe the highlighting problem

Hi, after the recent addition of the function/method calls for highlights it seems to have completely removed highlighting from all languages (with their treesitter parser installed, and without). However, highlighting for help pages still seems to work fine. I have noticed that only people using Windows are facing this issue. Some guidance would be appreciated :)

### Example snippet that causes the problem

```lua
local test_func = function(x, y)
    print("X is:", x)
    print("Y is:", y)
end

test_func(3, 4)
```

### Tree-sitter parsing result

I get no output after doing this, I'm assuming it's because there is no highlighting in the code.
![image](https://user-images.githubusercontent.com/68950943/183020944-e4c3e2ce-e7b3-4c03-a78f-31aa486c5e9c.png)

### Example screenshot

This is in a file called `test.lua`.
![image](https://user-images.githubusercontent.com/68950943/183021031-4427a178-106a-4361-948e-bd910f44312b.png)

I'm using the [kanagawa.nvim](https://github.com/rebelot/kanagawa.nvim) colorscheme, it can be installed by adding `use "rebelot/kanagawa.nvim"` in your packer setup.

Output of `:TSHighlightCapturesUnderCursor`:
![image](https://user-images.githubusercontent.com/68950943/183021382-8fbfe64a-748a-4002-a2b4-a1288f756209.png)

### Expected behavior

Highlighting for all languages should work (with and without the treesitter parser installed).

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - WARNING: `node` executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `git` executable found.
  - OK: `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: gcc (GCC) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - lua            ✓ ✓ ✓ ✓ ✓
  - cpp            ✓ ✓ ✓ ✓ ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - norg           ✓ . ✓ . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.0-dev-775-g27ce21ac8
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az30-95

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

**Comment by shift-d** [comment]
Can reproduce, sadly

**Comment by clason** [comment]
Can you bisect nvim-treesitter to find out which commit exactly broke highlighting for you? It's very unlikely to be the one you mentioned if you followed the usual advice on any highlighting problems (reinstall all parsers and queries and make sure you don't have incompatible ones lying around, e.g., from other plugins).

**Comment by shift-d** [comment]
There is an interesting moment: it looks like it is a NeoVim issue itself, since after I've downgraded to 0.7 from latest nightly everything seemed to work.

Although I am not sure which nightly release caused it since I hadn't updated for a while and this issue occured after upgrading nightly.

**Comment by BinxDot** [comment]
> Can you bisect nvim-treesitter to find out which commit exactly broke highlighting for you? It's very unlikely to be the one you mentioned if you followed the usual advice on any highlighting problems (reinstall all parsers and queries and make sure you don't have incompatible ones lying around, e.g., from other plugins).

My bad, I should have checked whether it worked in the the stable version before creating this issue. @shift-d is correct, it does work perfectly in v0.7.2, I'll try figuring out which commit caused this. Thanks for the help!
