### ISSUE TITLE
Adding support for generic XML files

### ISSUE THREAD

**Issue by asmodeus812** [nvim-treesitter/nvim-treesitter#3295]
**Is your feature request related to a problem? Please describe.**
Basically, as the title suggests, there is support for xml like languages - html for example. But nothing about supporting the general xml syntax. I would like to be able to use text objects such as attributes for example or even tags if possible, would be great.

**Describe the solution you'd like**
A parser working on files with plain xml extensions

**Describe alternatives you've considered**
Forcing treesitter to use the html parser when working with generic xml files

**Additional context**
It would be great to also support things like tag text objects (not sure if there are markers for that) to be able to do something like [t or ]t to move to the next tag. By default, i imagine ]t can jump to the next child tag, if you end up with no child tags remaining, jump to the next parent tag (the next sibling of the parent of the current child tag) one level up (if one exists).

**Comment by theHamsta** [comment]
I've opened two PRs. Can you tell which one you like better? I guess using the HTML parser for XML should be fine (#3297). The XML parser in #3296 had some issues parsing some scheme headers.

**Comment by asmodeus812** [comment]
Hi, thanks for the quick feedback. Even though html is a superset of xml, since there already is parser for xml, i think the proper approach should be to use that. Now as far as highlighting issue goes if it is too severe, having xml fallback to html temporarily is also an option.

**Comment by theHamsta** [comment]
@asmodeus812 but the HTML parser works better (it seems to be the HTML forked a long time ago) and is maintained (though XML should not change). I'd recommend to test the XML parser for while. If it's ok to use we can go for it. Sharing parsers is also an advantage for simplified maintenance of the queries. Using `html_tags` for `xml` didn't work for me, presumably because of one or two outdated nodes.

**Comment by asmodeus812** [comment]
Okay, i will checkout the branch where you have configured XML as a new parser, download it and test it. Using the HTML parser for XML only as a fallback is okay. One potential scenario which is going to be confusing to me is, if new XML derived specs and formats are introduced, i assume they will have special parsers created for them as HTML does ?

At the moment i am using the fallback like that, seems to be working fine
```lua
local parser_mapping = require("nvim-treesitter.parsers").filetype_to_parsername
parser_mapping.xml = "html" -- map the html parser to be used when using xml files
```
By the way, on my second point about moving across tags, does tree sitter support any means of jumping over to sibling elements instead of just the usual "next" node of that type. Without having to tap into the treesitter lua api. Maybe a query of some sort ? Trying to incorporate that into treesitter-textobjects for tags with [t and ]t. At the moment it is configured to use @function for tags but it jumps over to the next nearest tag.

**Comment by theHamsta** [comment]
@asmodeus812 just write a query for that recognizes the start tag as `@start` and the end tag as `@end`. You should then be able to either jump between start tags or end tags

**Comment by clason** [comment]
@asmodeus812 did you ever manage to actually test the XML parser?

(And, yes, new languages derived from XML would get likely their own parser.)

**Comment by asmodeus812** [comment]
Hi, never got the chance to, i was using the html parser.

**Comment by lucascool12** [comment]
Hi I made a fork with minimal changes of [https://github.com/unhammer/tree-sitter-xm](https://github.com/unhammer/tree-sitter-xml) that in this moment of time seems to work: [https://github.com/lucascool12/tree-sitter-xml](https://github.com/lucascool12/tree-sitter-xml). Highlighting is minimal.

**Comment by ghostbuster91** [comment]
@lucascool12 are you willing to somehow maintain that fork? If so could you enable issues so that I can raise one? :)
