### ISSUE TITLE
Reload queries?

### ISSUE THREAD

**Issue by lf-** [nvim-treesitter/nvim-treesitter#3304]
**Is your feature request related to a problem? Please describe.**

I thought that in the past the queries were reloaded from disk when they're saved, but it seems like that's not happening at the moment. Anyway, I want to edit a query and test it immediately without seemingly having to restart the editor.

I have been running into this with https://github.com/rrethy/nvim-treesitter-textsubjects, with the command `:TSEditQueryUserAfter textsubjects-smart haskell`.

Here's a sample query you could put in there to validate:

```scheme
([
  (signature)
  (function)
 ] @_start @_end
 (#make-range! "range" @_start @_end))
```

on this code:

```haskell
module Test where

a = 2
b = 3
```

Then trigger textsubjects-smart with `v.` on the `b = 3`.

**Describe the solution you'd like**

Ideally when I write the query file to disk, the query gets reloaded and becomes active.

**Describe alternatives you've considered**

--

**Additional context**

Versions:

nvim 0.7.0 from Nix

```
start/nvim-treesitter-textsubjects - [master] » git rev-parse @
ed026cfdff93b2d63d9d8cd2525481d8f002f65e
start/nvim-treesitter-textsubjects - [master] » cd ../nvim-treesitter
start/nvim-treesitter - [master] » git rev-parse @
e7b5e92d46355919e96e78f596bd5297c9ef77dd
```

**Comment by theHamsta** [comment]
We have our own cache that is supposed to be invalidated whenever one of the query files is written.
https://github.com/theHamsta/nvim-treesitter/blob/bccd7fd3d9e0074632b25463336c9fdd6ed88eb7/lua/nvim-treesitter/query.lua#L58-L39

I suppose we can remove this cache now that queries are cached in core. Maybe this will solve the problem?

**Comment by lf-** [comment]
Heya. This autocmd fixes it: (oh damn, sorry this thing is using [my funny autocmd thing](https://github.com/lf-/dotfiles/blob/main/configs/nvim/lua/augroups.lua) but nevertheless)

```lua
augroup('reload queries on query save', function(autocmd) --https://github.com/nvim-treesitter/nvim-treesitter/issues/3304
    autocmd(
        'BufWrite',
        {
            pattern = '*.scm',
            callback = function ()
                require'nvim-treesitter.query'.invalidate_query_cache()
            end
        }
    )
end)
```

**Comment by lf-** [comment]
This was regressed in neovim core and needs something like the following called. I'm going to file a bug in there.

https://github.com/neovim/neovim/blob/e512efe3696b2ed18db55683fecf42bbc733c767/runtime/lua/vim/treesitter/query.lua#L277-L281

It's additionally very much misleading that `invalidate_query_caches` doesn't invalidate the nvim core cache for the query.

https://github.com/nvim-treesitter/nvim-treesitter/blob/42fc28ba918343ebfd5565147a42a26580579482/lua/nvim-treesitter/query.lua#L114-L143

**Comment by clason** [comment]
Yes, which is why this function was burninated. Don't waste time opening issues at Neovim about nvim-treesitter (master, which is archived).
