### ISSUE TITLE
neovim crashing when opening .py files

### ISSUE THREAD

**Issue by aliu-here** [nvim-treesitter/nvim-treesitter#3305]
### Describe the bug

neovim crashes when trying to open a .py file

### To Reproduce

1. Install python parser
2. try to open .py file

### Expected behavior

editor does not crash

### Output of `:checkhealth nvim-treesitter`

```markdown
Neovim crashes
```

### Output of `nvim --version`

```text
NVIM v0.8.0-dev+168-g5359be789
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az158-691

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"
```

**Comment by aliu-here** [comment]
i updated neovim to latest nightly, fixed bug

**Comment by azinsharaf** [comment]
@aliu-here  I am experiencing the same issue and updating to the latest nightly didn't fix it. IS there anything you did? Is it possible to share your treesitter.lua and plugins.lua files?

**Comment by thriveth** [comment]
I am experiencing the same problem, but only when nvim-treesitter is enabled, and only for Python files. 
I am using the latest Snap store NVim (0.9.1) with the built-in python treesitter parser. I get no feedback, NVim simply segfaults when trying to invoke any Python tree-sitter functionality.

**Comment by BrightXiaoHan** [comment]
> 

Same problem, have you solved it?

**Comment by thriveth** [comment]
@BrightXiaoHan  Unfortunately not, I have basically resorted to Emacs for my Python coding for now, since I couldn't find a way to fix this and Evil-mode, Tree-sitter and LSP means I end up with an experience that is very close to that of NVim. But it is frustrating and I would like to see it solved.

**Comment by clason** [comment]
A complete and minimal set of reproducing steps would go a long way. Clearly, not everybody (to put it mildly) is experiencing this crash.

**Comment by clason** [comment]
(Also, the Python parser is now bundled with Neovim, so you should be able to reproduce this with `nvim --clean` and `vim.treesitter.start()`. If you can't, it's not a Neovim issue.)

**Comment by BrightXiaoHan** [comment]
I am sure that this is a problem caused by treesitter Python. When I uninstall treesitter Python with `TSUninstall python`, I can open Python files normally.

**Comment by clason** [comment]
I am sure it is not, since I can open Python files normally using the bundled parser.

**Comment by thriveth** [comment]
@clason Since which NVim version is the Python parser built in?

**Comment by clason** [comment]
Master (0.10-dev)

**Comment by BrightXiaoHan** [comment]
I execute `nvim --headless hello.py`. Got following error
```
/tmp/appimage_extracted_5b9f0fab4119f9e3dd1aab5fde07b210/usr/bin/nvim: symbol lookup error: /home/homecli/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser/python.so: undefined symbol: static_assert
```
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/25839309/a7e05471-4e32-4e59-a5eb-b485a4ede7cc)

**Comment by clason** [comment]
We need a lot more details (which the issue template asked you for).

**Comment by clason** [comment]
Please open a new issue with your details.
