### ISSUE TITLE
How to get the next_node name of the capture in the query

### ISSUE THREAD

**Issue by glepnir** [nvim-treesitter/nvim-treesitter#3319]
@vigoux   Please check here.Thanks

```lua 
  local query = queries.get_query(ft_to_lang(vim.bo[bufnr].filetype),'highlights')

  for id, node, _ in query:iter_captures(parent_node, 0, start_row, end_row) do
    local name = query.captures[id] -- name of the capture in the query
    print("- capture name: " .. name)
   local next_node = ts_utils.get_next_node()
   -- I have tried the next_node:type() next_node:id() next_node:name()
```

test file is a go file
```go

func  test( str ,str1 string, str3 module.Package)

```
string  `- capture name: type`  cursor on str1 . next_node is `string` , so how can i get ` type` . the id is not number `next_node:id()` and `next_node:name` is nil.

**Comment by theHamsta** [comment]
I don't understand what your're trying to do.
The CST is
```
function_declaration [9, 0] - [9, 50]
  "func" [9, 0] - [9, 4]
  name: identifier [9, 6] - [9, 10]
  parameters: parameter_list [9, 10] - [9, 50]
    "(" [9, 10] - [9, 11]
    parameter_declaration [9, 12] - [9, 28]
      name: identifier [9, 12] - [9, 15]
      "," [9, 16] - [9, 17]
      name: identifier [9, 17] - [9, 21]
      type: type_identifier [9, 22] - [9, 28]
    "," [9, 28] - [9, 29]
    parameter_declaration [9, 30] - [9, 49]
      name: identifier [9, 30] - [9, 34]
      type: qualified_type [9, 35] - [9, 49]
        package: package_identifier [9, 35] - [9, 41]
        "." [9, 41] - [9, 42]
        name: type_identifier [9, 42] - [9, 49]
    ")" [9, 49] - [9, 50]
"\n" [9, 50] - [10, 0]
```
when you're trying to get the node corresponding to the "type" property, you can call `node:field("type")` where node is the `parameter_declaration`. I would recommend to write a dedicated query where all the nodes you're interested have their own captures.

**Comment by glepnir** [comment]
I know "type" is  a field of parameter_declaration .it define in `highlights.scm` I want to get function name and param name param type.  I had tied that way and write it like this .but this sexpr can't work with all param type .like 
`str3 module.Package ` it's `package_identifier` . for me use `highlights.scm` is easy to do .but currently I want to get 
`next_node` field `type`. all `highlights.scm` define `type` .so I don't need write query for every language. 
```
(function_declaration
  (identifier) @func.name
  (parameter_list
      (parameter_declaration
        (identifier) @param.name
        ("," @param.separator (_))*
        (type_identifier) @param.type)))
```

**Comment by glepnir** [comment]
```
- capture name: parameter
- capture name: type
- capture name: type.builtin
- capture name: punctuation.delimiter
- capture name: variable
- capture name: parameter
- capture name: type
- capture name: type.builtin
- capture name: punctuation.delimiter

```

**Comment by theHamsta** [comment]
I think this would only work when you remember the I'd of next_node and search through all other matches for a node with the same id that was matched for capture `@type`. The code for TSHighlightCapturesUnderCursor does this reverse lookup, but it is kind of a hack.

**Comment by glepnir** [comment]
okay so current I can't get that id right.

**Comment by glepnir** [comment]
find the way to solve this .
