### ISSUE TITLE
Use tree-sitter for indentation

### ISSUE THREAD

**Issue by theHamsta** [nvim-treesitter/nvim-treesitter#332]
**Is your feature request related to a problem? Please describe.**
No problem. Vim indentation is good enough for me. So this has absolutely low priority for me.

**Describe the solution you'd like**
We could use the approach discussed here and get inspiration of the Atom PRs https://github.com/ubolonton/emacs-tree-sitter/pull/34

There are PRs for Atom to do it: https://github.com/atom/atom/pull/18321 https://github.com/atom/language-javascript/pull/608 (config file for aforementioned PR).

Essentially, we get current indentation by traversing through all parents of the current node and check with a config file which nodes require `indent/outdent`.

**Describe alternatives you've considered**
Just use vim indentation and be happy

**Additional context**
N/A

**Comment by vigoux** [comment]
This can be done quite easily I think.
One thing we might need tough is the correspondance `node -> capture`instead of `capture -> node` for queries.
I'll dig into that as this is related to folding too.

**Comment by theHamsta** [comment]
FYI https://github.com/atom/language-javascript/pull/608

Would be nice if we could directly use the Atoms queries.

**Comment by FelipeLema** [comment]
> 
> 
> FYI: https://codeberg.org/FelipeLema/tree-sitter-indent.el

Just got this out of beta and getting it out there. Maybe I'm missing some stuff, but I'd say most of what's needed for every day work is there.

**Comment by vigoux** [comment]
I _think_ indentation can be implemented using a similar technique than the one used for `fold`.
One thouhg have to go through the hassle of understanding how `indentexpr`, and from what I saw last time I looked, it is not as easy as `foldexpr`.

**Comment by kyazdani42** [comment]
indeed indentexpr is quite complicated. It is actually a function that returns the indent level (as a number) or -1 if not indenting.
I'm not sure treesitter would help. Maybe it could, but i'm not too sure how we would do this. This should attach a `indentexpr=TreesitterIndent(v:lnum)` for each buffer with treesitter.
I'm going to try play with this to see what i can come up with.

**Comment by vigoux** [comment]
`foldexpr` is pretty similar, and that's why `fold` is a bit strangely written.
