### ISSUE TITLE
Cannot switch between tree menu and code while in poetry shell

### ISSUE THREAD

**Issue by yenaras** [nvim-treesitter/nvim-treesitter#3342]
### Describe the bug

While the current terminal is on a poetry shell, I cannot switch between the neovim terminal and the tree view, via neovim keybinds that I set up in Lua.  If I exit poetry shell while editing it works fine, so I am able to get around this issue by editing my code outside of the virtual environment and testing it in another shell in the virtual environment.

### To Reproduce

poetry shell
nvim test.py
<leader> e
ctrl hjkl #my keybinds to move through terminal, tmux, neovim
doesn't work for tree

### Expected behavior

I expected to be able to seamlessly navigate to the treesitter files as normal.

### Output of `:checkhealth nvim-treesitter`

```markdown
18
 17 nvim-treesitter: require("nvim-treesitter.health").check()
 16 ========================================================================
 15 ## Installation
 14   - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
 13   - OK: `node` found v18.7.0 (only needed for :TSInstallFromGrammar)
 12   - OK: `git` executable found.
 11   - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
 10     Version: cc (GCC) 12.2.0
  9   - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.
  8
  7 ## Parser/Features H L F I J
  6   - bash           ✓ ✓ ✓ . ✓
  5   - lua            ✓ ✓ ✓ ✓ ✓
  4   - python         ✓ ✓ ✓ ✓ ✓
  3
  2   Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
  1          +) multiple parsers found, only one will be used
19           x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIm v0.7.2
```

**Comment by theHamsta** [comment]
How is this related to this repo?
