### ISSUE TITLE
High CPU load and very long loading when opening parser.c

### ISSUE THREAD

**Issue by matthias-Q** [nvim-treesitter/nvim-treesitter#3375]
### Describe the bug

When opening a `parser.c` (checked the one from rust and sql) neovim runs with 100% CPU load and does not finish to startup.

I hav disabled all of my plugins and boiled it down to nvim-treesitter. The log file does not show any suspicious messages.

### To Reproduce

1. disable all plugins except of nvim-treesitter
2. open src/parser.c of any tree-sitter syntax repository

### Expected behavior

File opens like any other.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.7.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.1.1 20220730
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - javascript     ✓ ✓ ✓ ✓ ✓
  - css            ✓ . ✓ ✓ ✓
  - bash           ✓ ✓ ✓ . ✓
  - html           ✓ ✓ ✓ ✓ ✓
  - proto          ✓ . ✓ . .
  - markdown       ✓ . ✓ . ✓
  - toml           ✓ ✓ ✓ ✓ ✓
  - rust           ✓ ✓ ✓ ✓ ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - query          ✓ ✓ ✓ ✓ ✓
  - yaml           ✓ ✓ ✓ ✓ ✓
  - nix            ✓ ✓ ✓ . ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - sql            ✓ . . . ✓
  - fish           ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.7.2
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/matthias/Programmieren/neovim/build/config -I/home/matthias/Programmieren/neovim/src -I/home/matthias/Programmieren/neovim/.deps/usr/include -I/usr/include -I/home/matthias/Programmieren/neovim/build/src/nvim/auto -I/home/matthias/Programmieren/neovim/build/include
Übersetzt von matthias@pulse

Features: +acl +iconv +tui
See ":help feature-compile"

          System-vimrc-Datei: "$VIM/sysinit.vim"
     Voreinstellung für $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
Did you see the size of these parsers? I'm not sure what you're expecting here...

**Comment by matthias-Q** [comment]
Yes, I know that these are huge files. However neovim is completely frozen and I have to kill it because it is completely stuck. When disabling nvim-treesitter, the file opens right away.

**Comment by theHamsta** [comment]
Yes, we should use `ts_parser_set_timeout_micros(*p, <some value>);` in `parser_parse`. We need to think of something that we should do when the timeout is reached. We would still have the old parsed tree and the edits that happened between the last parse. So we could maybe just highlight unchanged text.

**Comment by matthias-Q** [comment]
Thanks for the comment. I cannot find the code location that you are referring to. Would that be part of the neovim TS code or should that be done in this plugin?

**Comment by theHamsta** [comment]
Please look at the diff of this PR: https://github.com/neovim/neovim/pull/18761 `ts_parser_set_timeout_micros` is out-commented. All code doing `parser_parse` must be adapted to react to a timeout (timeout could return `nil` or Lua error`). A reaction could be to just return immediately from method doing parsing, when parsing fails. This means loosing all highlights. Even when a timeout is reached, the parser made progress and might succeed the next time called

**Comment by matthias-Q** [comment]
So, this means this is an issue that needs to be solved directly in neovim and not in the nvim-treesitter plugin. Thus, this issue can be closed, right?

**Comment by theHamsta** [comment]
Yes, this needs to be resolved in neovim core.  We often solve issues reported here in Neovim core.
