### ISSUE TITLE
Improve documentation for contributing

### ISSUE THREAD

**Issue by NoahTheDuke** [nvim-treesitter/nvim-treesitter#3397]
Hey there!

I'm looking to improve the Clojure highlighting, and I'm struggling to get the tests working correctly. I'm asking for some guidance or maybe a description of development workflow, so I can stop stumbling over myself and the existing set up.

Here are the areas I've stumbled on so far:

* It seems that the `scripts/run_tests.sh` system doesn't use the highlighting files in the repo but that are installed with `:TSInstall`, making it quite cumbersome to iterate without messing with my current config. Or maybe some combination? I'm not entirely sure. If I make a change in `queries/clojure/highlighting.scm`, it's not reflected in the test. But if I add a syntax error to the file, then the test crashes.
* I can't select a specific language or specific file to test, I have to either run the entire `query` directory (which includes errors from languages I don't have installed), or I have to manually edit `tests/query/highlights_spec.lua` to glob the specific language directory I wish to target, which I then have to avoid committing.

I would love help to make this work.

Thanks so much!

**Comment by theHamsta** [comment]
TODO myself: write the answers in long prosa.

> It seems that the scripts/run_tests.sh system doesn't use the highlighting files in the repo but that are installed with :TSInstall, making it quite cumbersome to iterate without messing with my current config. Or maybe some combination? I'm not entirely sure. If I make a change in queries/clojure/highlighting.scm, it's not reflected in the test. But if I add a syntax error to the file, then the test crashes.

no, that's not true. The files in `queries/clojure/highlighting.scm` are used (or better all `*.scm` files in your runtime path). `:TSInstall` does not install any `*.scm` files.

> I can't select a specific language or specific file to test, I have to either run the entire query directory (which includes errors from languages I don't have installed), or I have to manually edit tests/query/highlights_spec.lua to glob the specific language directory I wish to target, which I then have to avoid committing.

yes, that's tricky: you can actually run `query/highlights_spec.lua` without the `tests`. `./scripts/run_tests.sh query/highlights_spec.lua`

**Comment by NoahTheDuke** [comment]
> no, that's not true. The files in queries/clojure/highlighting.scm are used (or better all *.scm files in your runtime path). :TSInstall does not install any *.scm files.

Ah, okay, `:TSInstall` only installs the parser. Interesting.

To rephrase what I said correctly, I have nvim-treesitter installed as a plugin with packer.nvim, so all of the `highlighting.scm` files are in my runtime path from packer.nvim. And then I fork and clone nvim-treesitter and edit one of the `highlighting.scm` files. Then I run `scripts/run_tests.sh` and because nvim-treesitter is on my runtime path, all of its highlighting queries are used in the tests instead of my edits.

Is there a way to avoid that?

> ./scripts/run_tests.sh query/highlights_spec.lua

Right, but that still runs all highlighting tests instead of just my chosen language. It's a mild annoyance, to be clear, but it is annoying lol.

**Comment by NoahTheDuke** [comment]
Any chance to see the documentation for running specific tests updated? Or maybe the functionality expanded a bit? I'm still learning Lua or I'd dive right in.

**Comment by NoahTheDuke** [comment]
Okay, thanks.
