### ISSUE TITLE
E5113: Error while calling lua chunk: .../nvim/plugged/nvim-treesitter/plugin/nvim-treesitter.lua:15:  attempt to call field 'nvim_create_augroup' (a nil value)

### ISSUE THREAD

**Issue by marroen** [nvim-treesitter/nvim-treesitter#3408]
### Describe the bug

Used vim-plug to install nvim-treesitter first with this line:
```
Plug 'nvim-treesitter/nvim-treesitter'
```
Then changed to this line after first install (note: errors also occurred before changing this line):
```
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
```

Now, everytime I launch nvim I get this error:
```
Error detected while processing /Users/marty/.config/nvim/plugged/nvim-treesitter/plugin/nvim-treesit
ter.lua:
E5113: Error while calling lua chunk: .../nvim/plugged/nvim-treesitter/plugin/nvim-treesitter.lua:15:
 attempt to call field 'nvim_create_augroup' (a nil value)
stack traceback:
        .../nvim/plugged/nvim-treesitter/plugin/nvim-treesitter.lua:15: in main chunk
```
It appears that nvim-treesitter is working as it should, it's just the nvim launch that produces this.
I tried reinstalling nvim-treesitter multiple times without success.

### To Reproduce

1. Launch nvim with any file or new file
2. See error message

### Expected behavior

Clean launch of nvim.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
  2 ========================================================================
  1 ## Installation
5     - OK: `tree-sitter` found 0.20.1 (parser generator, only needed for :TSInstallFromGrammar)
  1   - OK: `node` found v18.8.0 (only needed for :TSInstallFromGrammar)
  2   - OK: `git` executable found.
  3   - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  4     Version: Apple clang version 13.0.0 (clang-1300.0.29.30)
  5   - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers           must be compatible with runtime ABI.
  6 
  7 ## Parser/Features H L F I J
  8   - kotlin         ✓ ✓ ✓ . ✓
  9 
 10   Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
 11          +) multiple parsers found, only one will be used
 12          x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.7.0-dev+765-g4f9522490
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by marty@Martins-MacBook-Air.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-4f95224/share/nvim"

Run :checkhealth for more info
```

### Additional context

I am fairly fresh to Neovim and completely fresh to using nightly, in fact I just uninstalled my entire nvim and reinstalled nightly to include nvim-treesitter.
I also have CoC for my nvim, maybe they are interfering? 
Furthermore, I have an init.lua file with only a single println call that I used to check that it works. It's required in my init.vim. Aside from that I'm exclusively using init.vim. If needed I may share all of my init.vim file.

**Comment by rockerBOO** [comment]
The version being v0.7.0-dev+765-g4f9522490 seems like an older version, and not using the current nightly. The current stable is 0.7.2 and the nightly would be 0.8.0-dev. The error seems due to lacking `nvim_create_augroup` which is part of lua autocmds which came late in the 0.7 development lifecycle.

I would check to make sure you are getting the latest nightly.

**Comment by marroen** [comment]
> 

Forgive my ignorance, but how can I update to latest nightly? I thought I did that by following the latest build from source as per Neovim's repo README.md.

**Comment by rockerBOO** [comment]
If you want the nightly, they are available on github: https://github.com/neovim/neovim/releases/tag/nightly

If you are doing it from the source code, make sure you are updating your local git respository, `git pull` to get the latest changes.

**Comment by clason** [comment]
Make sure you are on the correct branch (`master`).

**Comment by marroen** [comment]
> If you want the nightly, they are available on github: https://github.com/neovim/neovim/releases/tag/nightly
> 
> If you are doing it from the source code, make sure you are updating your local git respository, `git pull` to get the latest changes.

Confirmed that successfully updating to nightly solved my issue.
