### ISSUE TITLE
Switch to upstream solidity parser

### ISSUE THREAD

**Issue by shuklaayush** [nvim-treesitter/nvim-treesitter#3421]
Looks like the current repo used for solidity (https://github.com/YongJieYongJie/tree-sitter-solidity) isn't being maintained. I think it makes sense to switch to the upstream repo (https://github.com/JoranHonig/tree-sitter-solidity). 

I've made the changes in the following commit and I can create a PR
https://github.com/shuklaayush/nvim-treesitter/commit/fc4c6db7119f86971f9024cb5c3a5c46bdf64ffe

cc @YongJieYongJie

**Comment by amaanq** [comment]
Not sure if you got `@JoranHonig`'s permission to maintain solidity here, but I'll maintain it via his repo (this seems a bit stale anyways)
