### ISSUE TITLE
Improve shell syntax in Makefile recipes: shell variables and other need double dollars ($$)

### ISSUE THREAD

**Issue by kiryph** [nvim-treesitter/nvim-treesitter#3428]
Consider this Makefile from the GNU Make documentation section [5.1.2 Using Variables in Recipes](https://www.gnu.org/software/make/manual/html_node/Variables-in-Recipes.html)
```make
LIST = one two three
all:
	for i in $(LIST); do \
	    echo $$i; \
	done
```
`:TSInstall make`  without `bash` (`:TSUninstall bash` if already installed) gives you following syntax tree
```
variable_assignment [0, 0] - [1, 0]
  name: word [0, 0] - [0, 4]
  value: text [0, 7] - [0, 20]
rule [1, 0] - [5, 0]
  targets [1, 0] - [1, 3]
    word [1, 0] - [1, 3]
  recipe [1, 4] - [5, 0]
    recipe_line [2, 1] - [4, 5]
      shell_text [2, 1] - [3, 0]
        variable_reference [2, 10] - [2, 17]
          word [2, 12] - [2, 16]
      shell_text [3, 0] - [4, 0]
        escape [3, 10] - [3, 12]
      shell_text [4, 1] - [4, 5]
```

`$(LIST)` is a node `variable_reference` as defined in the Makefile grammar which is semantically correct.

If you install additionally `:TSInstall bash` together with nvim-treesitter and its file `queries/make/injections.scm`, the syntax tree changes to

```
variable_assignment [0, 0] - [1, 0]
  name: word [0, 0] - [0, 4]
  value: text [0, 7] - [0, 20]
rule [1, 0] - [5, 0]
  targets [1, 0] - [1, 3]
    word [1, 0] - [1, 3]
  recipe [1, 4] - [5, 0]
    recipe_line [2, 1] - [4, 5]
      shell_text [2, 1] - [3, 0]
        ERROR [2, 1] - [3, 0]
          variable_name [2, 5] - [2, 6]
          command_substitution [2, 10] - [2, 17]
            command [2, 12] - [2, 16]
              name: command_name [2, 12] - [2, 16]
                word [2, 12] - [2, 16]
          ERROR [3, 0] - [3, 0]
        variable_reference [2, 10] - [2, 17]
          word [2, 12] - [2, 16]
      shell_text [3, 0] - [4, 0]
        ERROR [3, 5] - [4, 0]
          command [3, 5] - [3, 13]
            name: command_name [3, 5] - [3, 9]
              word [3, 5] - [3, 9]
            argument: concatenation [3, 10] - [3, 13]
              simple_expansion [3, 10] - [3, 12]
                special_variable_name [3, 11] - [3, 12]
              word [3, 12] - [3, 13]
          ERROR [4, 0] - [4, 0]
        escape [3, 10] - [3, 12]
      shell_text [4, 1] - [4, 5]
        command [4, 1] - [4, 5]
          name: command_name [4, 1] - [4, 5]
            word [4, 1] - [4, 5]
```

`$(LIST)` becomes now a node `command_substitution` which is semantically incorrect. It is still a Make variable.
If this should be a shell command substitution, one has to escape the `$` by doubling it to `$$(LIST)`.

The tree now also contains several `ERROR` markers and in generally, does not understand `$$` for shell usage.

It is correct that recipe lines are mostly shell syntax but not fully. The differences are not exotic and an ordinary user encounters them. E.g. one can also use Make substitution references `$(var:pattern=replacement)` and call Make functions in recipe lines `$(foreach ...)`...

**Describe the solution you'd like**
I am not sure how in the tree sitter world this difference in this make+shell syntax compared to pure shell syntax can be resolved.

One possibility would be copying the shell grammar into the make grammar and adjust it. Then there would be no need for the injection done by nvim-treesitter. However, this does not feel appropriate since one can change the used shell in make (e.g. from sh to bash or zsh).

Opinions are welcome.

Documentation about the differences can be found here:

- https://www.gnu.org/software/make/manual/html_node/Recipes.html
- https://www.gnu.org/software/make/manual/html_node/Recipe-Syntax.html
- https://www.gnu.org/software/make/manual/html_node/Variables-in-Recipes.html (`$$i` and `$$(ls -1)`
- Minor differences: line prefix with `@` no echoing, `-` proceed on error, `+` run despite cli flags of make command

**Comment by theHamsta** [comment]
when pressing `I` you can see the source languages from the syntax, with `t` you can disable the injected languages
![grafik](https://user-images.githubusercontent.com/7189118/188316496-0b75a985-92b1-4bea-b2ca-0d7e31f374cd.png)

It seems that this would be solved if Neovim used the same default as upstream tree-sitter and just excluded the nodes from `make` in it's parsing. So it would not see any `\` and also not `$$(...)` even though bash will then see `echo ;`. I wonder why https://github.com/nvim-treesitter/nvim-treesitter/pull/3429 isn't working. I haven't looked into implementation of `@exclude-children`

**Comment by lewis6991** [comment]
> One possibility would be copying the shell grammar into the make grammar and adjust it. Then there would be no need for the injection done by nvim-treesitter. However, this does not feel appropriate since one can change the used shell in make (e.g. from sh to bash or zsh).

I think this is the only realistic way this could be achieved for the best results.

One could also add some makefile specific nodes to the bash parser.

Either way, this is high effort low reward so not something we will explicitly plan to do.
