### ISSUE TITLE
Change Text objects: move to behave like word motions

### ISSUE THREAD

**Issue by fredizzimo** [nvim-treesitter/nvim-treesitter#343]
**Is your feature request related to a problem? Please describe.**
I just tested the text object movement support and technically it works very well and fast. It's a good alternative when moving through the document, for example when jumping from function to function instead of scrolling by half pages or moving from paragraph to paragraph.

However, for actual navigation, for example if I'm in the middle of a function, and want to go to the start it's not very practical, since it always skips the start of the current function and jumps to the previous function. I do, however think that it could be a very effective way to move around if it worked differently and you get used to it.  

**Describe the solution you'd like**
I would like that:
* `goto_next_start` works like `w`, so it moves to the start of the next capture group. This currently works as I would like to.
* `goto_next_end` works like `e`, so it moves to the end of the current capture group. This currently works differently, it moves to the next group.
* `goto_prev_start` works like `b`, so if you are at the start of the capture group it moves to the start of the previous one, otherwise it moves to the start of the current one. Currently it always moves to the previous one.
* `goto_prev_end` works like `ge`, so it moves to the end of the previous capture group. This currently works as I would like to.

**Describe alternatives you've considered**
I played with mappings like `goto_prev_start (b)` = `goto_prev_start` `goto_next_start`, but that just moves the problem around, and now it doesn't handle the case where you are at the start of the capture group. It also doesn't handle methods at the start and end of the file.

**Additional context**
The above method of navigation obviously requires a lot of keybindings, especially if you want to be granular and support all kinds of symbols. There's obviously many ways to handle that, but I have a special navigation layer, where I can for example press `nms (navigate method start)`, then I press `;` or `,` to choose the direction, and repeat if needed (using the repmo-vim plugin). This of course overrides the normal search `n` command, but I have mapped that and all kinds of other list and scrolling to the same system, so I'm happy with that.

And now slightly off-topic, but I don't have a good way of doing this yet, so I didn't want to create a new issue
The current way of always navigating recursively, is probably good for now, but ultimately it would be good to have more control, like never navigate recursively, or navigate inside the current group, for example to not jump out of the current function by accident. But I can't really think of a good way to do that. My way of navigation could support it, since I could choose the scope for the initial command, and then it just follows that scope with repetitions, but I don't really see any way to do it in the general case.

**Comment by vigoux** [comment]
Hi, and thanks for the suggestions !

@theHamsta it looks like you are the designated person to work on this.

PS: @fredizzimo feel free to reach out to us on Zulip too (link in the README) so that we can talk about that more directly :wink:

**Comment by stsewd** [comment]
I think that's actually a bug, I was about to report.


```python
def foo():
    def bar():
         pass
   cursor = 'here'
```

That would skip `bar`.

**Comment by theHamsta** [comment]
I can fix this. The feature was until now mainly a by product of swapping textobjects. I can finetune the behavior and make it more configurable. I guess go to end also goes one char to far.

**Comment by fredizzimo** [comment]
@theHamsta, thank you!

@stsewd, That is actually slightly different, since I was primarily talking about functions without nesting. But yes, I would except that it would go to the `def bar():` line when you go to the previous start, and to `pass`, when you go to the previous end, which means that it has to traverse the full tree depth in both directions. 

And actually for me in this test with C++
```c++
class FooBar
{
};

class Foo
{
	class Bar
	{
	};
	int cursorHere;
};
```
It also skips Foo, and jumps to FooBar

**Comment by theHamsta** [comment]
This is also perfect for finally adding more tests to our CI.
