### ISSUE TITLE
Invalid node type at position 3318 for language typescript

### ISSUE THREAD

**Issue by MaximilianLloyd** [nvim-treesitter/nvim-treesitter#3433]
![image](https://user-images.githubusercontent.com/10583205/188448007-95bb4f1f-c59e-481d-b966-e21b486db41b.png)

I'm consistently experiencing this for both Mac and Ubuntu.

**Comment by clason** [comment]
Duplicate of #3092

**Comment by MaximilianLloyd** [comment]
Hi. Thank you for the quick response. I tried the proposed solutions but with no luck. It's worth mentioning that i am running neovim from master, maybe that has something to do with it?

**Comment by clason** [comment]
No, I don't think so. This error occurs when you have outdated queries somewhere in your runtimepath.

**Comment by MaximilianLloyd** [comment]
![image](https://user-images.githubusercontent.com/10583205/188630568-8eb4713b-6cbf-45b8-bd92-f7e54d960614.png)

This is what i'm getting.

**Comment by smithbm2316** [comment]
I am personally still experiencing a typescript-specific error after following all the steps outlined in #3092 multiple times now, on both my Mac and Ubuntu machines. @clason is there any other advice that you might have in trying to debug this further? I can open a new issue with specific debug info, but from what I can tell it's coming directly from either Neovim's built-in treesitter queries or the typescript parser's queries, not from an adjacent syntax parser that inherits from typescript
