### ISSUE TITLE
Mappings from textobjects.move aren't loaded in python files

### ISSUE THREAD

**Issue by stsewd** [nvim-treesitter/nvim-treesitter#346]
**To Reproduce**
1. Set some custom mappings for textobjects.move

```lua
  textobjects = {
    move = {
      enable = true,
      goto_next_start = {
        ["]m"] = "@function.outer",
        ["]]"] = "@class.outer",
      },
      goto_next_end = {
        ["]M"] = "@function.outer",
        ["]["] = "@class.outer",
      },
      goto_previous_start = {
        ["[m"] = "@function.outer",
        ["[["] = "@class.outer",
      },
      goto_previous_end = {
        ["[M"] = "@function.outer",
        ["[]"] = "@class.outer",
      },
    },
  },
```

2. Open a suppported file
3. `:map ]m` doesn't show the mapping

It was working before https://github.com/nvim-treesitter/nvim-treesitter/pull/330 was merged. Mappings from `textobjects.{select,swap}` work as expected, so not sure what's happening with `textobjects.move`

**Comment by steelsojka** [comment]
I tried to reproduce this but the bindings are there for me. Where is setup being called from (init.vim)?
![Screen Shot 2020-08-26 at 7 17 17 AM](https://user-images.githubusercontent.com/2062154/91302570-4fd40280-e76c-11ea-8808-0b55a7fb338f.png)

**Comment by stsewd** [comment]
Looks like this is due https://github.com/sheerun/vim-polyglot, commenting that plugin fixes my problem.

I'm calling the setup method at the end of my config https://github.com/stsewd/dotfiles/blob/650ecd645beb9750195ef3e7f9fef855703c4166/config/nvim/init.vim#L530


But, still weird that it works before that commit.

**Comment by steelsojka** [comment]
Prior to that change `attach` was getting called multiple times for the same buffer. So, for example, multiple highlighters would get created for the same file causing memory leaks and performance issues. So most likely what is happening is related to the file detection for vim-polyglot. What filetype are you noticing this far. I have vim-polyglot installed as well. I will try and reproduce it.

**Comment by stsewd** [comment]
I'm experiencing this in python files. I just checked with other filetype (restructuredtext) and the mappings work there.

**Comment by stsewd** [comment]
This is working again for some reason :man_shrugging:
