### ISSUE TITLE
[typescript] Recognize angle brackets <T> as delimiter, not operator

### ISSUE THREAD

**Issue by adrian5** [nvim-treesitter/nvim-treesitter#3460]
![ts-angle-brackets](https://user-images.githubusercontent.com/5426924/189166908-29a588e6-bc26-4baa-afe3-76584a740cc5.png)

I reckon this would need to override what's inherited from the **ecma** highlights.

**Comment by theHamsta** [comment]
You can just add this as an additional highlight (maybe even with higher priority) to the typescript queries. Do you want to open a PR?
