### ISSUE TITLE
Support for bitbake files

### ISSUE THREAD

**Issue by Fildo7525** [nvim-treesitter/nvim-treesitter#3462]
**Is your feature request related to a problem? Please describe.**
It would be really nice if tree-sitter supported bitbake files for yocto

**Describe the solution you'd like**
tree-sitter support for bitbake files .bb and .bbappend

**Describe alternatives you've considered**
There is a highlighting for bitbake https://github.com/kergoth/vim-bitbake. However, this works only for vim and to have this feature in one place with all the others would be great.

**Additional context**
![Screenshot from 2022-09-08 21-07-38](https://user-images.githubusercontent.com/59179935/189205892-1294bdf9-da25-452c-9e06-531aaf4616ab.png)

**Comment by clason** [comment]
Please add this to the language request tracking issue: https://github.com/nvim-treesitter/nvim-treesitter/issues/2282
