### ISSUE TITLE
no highlighting on lua 

### ISSUE THREAD

**Issue by bryant-the-coder** [nvim-treesitter/nvim-treesitter#3467]
![image](https://user-images.githubusercontent.com/92417638/189287224-4e38f43a-439c-466b-a793-0df164e553c5.png)
i hv remove vim.so and vim.revision from treesitter. the highlighting doesnt work on lua ONLY other filetypes it works

**Comment by clason** [comment]
Duplicate. Please do not spam issues. Ask in https://app.element.io/#/room/#nvim-treesitter_community:gitter.im if you need help.

**Comment by bryant-the-coder** [comment]
sorry lastest nightly works :)) sorry for disturbing u @clason  😥
