### ISSUE TITLE
Syntax highlight in folded code

### ISSUE THREAD

**Issue by davxy** [nvim-treesitter/nvim-treesitter#3471]
When code is folded the syntax highlight (colors) disappears. 

Is there the possibility to preserve colors for the first line of folded code?

For example, to have syntax highlight in the underlined code

<img src ="https://paste.pictures/5B8vPvsyS.png" />

**Comment by clason** [comment]
Not with how folding currently works in Neovim.

But see https://github.com/kevinhwang91/nvim-ufo for what is possible if you do it manually.
