### ISSUE TITLE
Failed to load parser: dlsym(..., tree_sitter_Dockerfile): symbol not found on arm64 Mac

### ISSUE THREAD

**Issue by wookayin** [nvim-treesitter/nvim-treesitter#3515]
### Describe the bug

treesitter parser for `Dockerfile` cannot be loaded with the following error:

```
E5108: Error executing lua Failed to load parser: uv_dlsym: dlsym(0x200f3fde0, tree_sitter_Dockerfile): symbol not found
stack traceback:
        [C]: in function '_ts_add_language'
        ...eab_1/share/nvim/runtime/lua/vim/treesitter/language.lua:36: in function 'require_language'
        ...HEAD-89b9eab_1/share/nvim/runtime/lua/vim/treesitter.lua:38: in function '_create_parser'
        ...HEAD-89b9eab_1/share/nvim/runtime/lua/vim/treesitter.lua:96: in function 'get_parser'
        ...plugged/nvim-treesitter/lua/nvim-treesitter/ts_utils.lua:163: in function 'get_node_at_cursor'
```

### To Reproduce

1. Open a `Dockerfile`
2. `:lua require'nvim-treesitter.ts_utils'.get_node_at_cursor()`

I tried `:TSUninstall` and `:TSInstall` `dockerfile` but the result is same.

### Expected behavior

`get_parser(..)` should work without an error.	

### Output of `:checkhealth nvim-treesitter`

```markdown
<details>
   <summary>Click to expand</summary>


nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.7.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.1.6 (clang-1316.0.21.2.3)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - typescript     ✓ ✓ ✓ ✓ ✓
  - json           ✓ ✓ ✓ ✓ .
  - lua            ✓ ✓ ✓ ✓ ✓
  - toml           ✓ ✓ ✓ ✓ ✓
  - jsonc          ✓ ✓ ✓ ✓ ✓
  - yaml           ✓ ✓ ✓ ✓ ✓
  - cpp            ✓ ✓ ✓ ✓ ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - bibtex         ✓ . ✓ ✓ .
  - bash           ✓ ✓ ✓ . ✓
  - rst            ✓ ✓ . . ✓
  - tsx            ✓ ✓ ✓ ✓ ✓
  - cmake          ✓ . ✓ . .
  - c              ✓ ✓ ✓ ✓ ✓
  - json5          ✓ . . . ✓
  - http           ✓ . . . ✓
  - cuda           ✓ ✓ ✓ ✓ ✓
  - ruby           ✓ ✓ ✓ ✓ ✓
  - perl           ✓ . ✓ . .
  - dockerfile     ✓ . . . ✓
  - java           ✓ ✓ . ✓ ✓
  - rust           ✓ ✓ ✓ ✓ ✓
  - vim            ✓ ✓ ✓ . ✓
  - make           ✓ . ✓ . ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - html           ✓ ✓ ✓ ✓ ✓
  - scss           ✓ . . ✓ .
  - glimmer        ✓ . . . .
  - css            ✓ . ✓ ✓ ✓
  - graphql        ✓ . . ✓ ✓
  - regex          ✓ . . . .
  - fish           ✓ ✓ ✓ ✓ ✓
  - latex          ✓ . ✓ . ✓
  - go             ✓ ✓ ✓ ✓ ✓
  - proto          ✓ . ✓ . .

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```
</details>
```


### Output of `nvim --version`

```text
NVIM v0.8.0-dev-2549-g89b9eab63-dirty

Note: same in v0.7.2 release
```

### Additional context

I tested the same on a Linux x86_64, where it works without any issue.

On a M1 arm64 mac:

```
$ nm -gU ~/.vim/plugged/nvim-treesitter/parser/dockerfile.so
000000000000341c T _tree_sitter_dockerfile
```

neovim(lua) is trying to find `tree_sitter_Dockerfile`, not `tree_sitter_dockerfile`, so this might be the reason why.

**Comment by wookayin** [comment]
Looks like this is a `neovim` core's lua runtime issue.

**Comment by jduhamel** [comment]
I guess what I don't understand is that I've tried to reproduce this in vanilla neovim and have been unsuccessful. I've done a `:TSinstall markdown` and then loaded a markdown file and I can't get it to fail. but it will fail with lunar vim.

**Comment by theHamsta** [comment]
Neovim tries to load symbol `tree_sitter_<lang>` from a file `parser/<lang>.so` . Of the `.so` and the symbol can now be changed. `<lang>` is decided by the parser config in nvim-treesitter.

The problem seems to be that for some reasons, the symbol is called `_tree_sitter_dockerfile`

**Comment by theHamsta** [comment]
@wookayin . Is this still an issue?

**Comment by theHamsta** [comment]
> @theHamsta This is still an an issue for me. Same behaviour as @wookayin described, same output of `checkhealth`. Newest version of treesitter, uninstalling and re-installing `dockerfile` did not help.
> 
> Output of `nvim --version`:
> 
> ```
> NVIM v0.8.3
> Build type: Release
> LuaJIT 2.1.0-beta3
> ```
> 
> I'm on an Intel Mac.
> 
> Please reopen

Also
```
$ nm -gU ~/.vim/plugged/nvim-treesitter/parser/dockerfile.so
000000000000341c T _tree_sitter_dockerfile
```

**Comment by gbirke** [comment]
Almost:

```nm -gU ~/.local/share/nvim/plugged/nvim-treesitter/parser/dockerfile.so                  29.5m  Fr 24 Feb 14:27:18 2023
0000000000002844 T _tree_sitter_dockerfile
```

**Comment by theHamsta** [comment]
How would you compile that it generates ?
```
➜  nvim-treesitter git:(ce0dba96) ✗ nm -g parser/dockerfile.so 
                 w __cxa_finalize@GLIBC_2.2.5
                 w __gmon_start__
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
00000000000020fc T tree_sitter_dockerfile
```
Does it Apple Clang by default hide symbols? Can you try a different compiler?

**Comment by gbirke** [comment]
I don't know much about C development on a Mac, I just installed NeoVim via `brew` and `nvim-treesitter` via the vim-plug plugin. If you want me to try out different commands or compiling things, I'd need more detailed instructions, sorry.

**Comment by clason** [comment]
Works fine for me on macOS, so there must be something special on your systems.

**Comment by oeuftete** [comment]
For others finding this, the problem _might_ be the presence of an interfering plugin like https://github.com/ekalinin/Dockerfile.vim, which [will set the filetype to capital-D `Dockerfile`](https://github.com/ekalinin/Dockerfile.vim/blob/2a31e6bcea5977209c05c728c4253d82fd873c82/ftdetect/Dockerfile.vim#L4).   Removing the plugin or setting the filetype back to `dockerfile` worked for me.

**Comment by theHamsta** [comment]
> For others finding this, the problem _might_ be the presence of an interfering plugin like https://github.com/ekalinin/Dockerfile.vim, which [will set the filetype to capital-D `Dockerfile`](https://github.com/ekalinin/Dockerfile.vim/blob/2a31e6bcea5977209c05c728c4253d82fd873c82/ftdetect/Dockerfile.vim#L4). Removing the plugin or setting the filetype back to `dockerfile` worked for me.

So we would need to adapt capitalization for filetypes when loading the parser? Will attempt to fix this in Neovim. When filetypes can really be case-agnostic then the loaded parser needs to be normalized to it's canonical form. Still don't understand how this can happen. Usually the parser should be loaded by its name with which it was registered

**Comment by mmerickel** [comment]
The workaround for me is to override treesitter as follows:

```lua
vim.treesitter.language.register("dockerfile", "Dockerfile")
```

Would love to know if I'm missing something though. Of course I could also remove the dockerfile plugin entirely.

**Comment by ttxtea** [comment]
've got a similar issue with `nvim v0.10.0.`

~~~
.local/share/nvim/rocks/lib/luarocks/rocks-5.
1/rocks.nvim/2.22.0-1/plugin/rocks.lua:                                                
E5113: Error while calling lua chunk: ...ua/neorg/modules/core/integrations/treesitter/
module.lua:53: Unable to load nvim-treesitter.ts_utils :(                              
stack traceback:                                                                       
        [C]: in function 'assert'                                                      
        ...ua/neorg/modules/core/integrations/treesitter/module.lua:53: in function 'lo
ad'                                         
~~~

**Comment by clason** [comment]
That's not the same issue, and looks like a neorg problem.

**Comment by LyndonArmitage** [comment]
I was having a similar issue and resolved it by manually reinstalling the support for dockerfile in TreeSitter in nvim using `:TSInstall dockerfile`
