### ISSUE TITLE
"Cannot make changes, 'modifiable' is off" race condition with ale when foldexpr is set

### ISSUE THREAD

**Issue by DanCardin** [nvim-treesitter/nvim-treesitter#352]
**Describe the bug**
Took a while to track this down, and feel free to let me know if this makes more sense as an ale bug report, or even floaterm, but i started here, since it only appears when using the `nvim_treesitter#foldexpr()`

Errors with `Cannot make changes, 'modifiable' is off` during the period of time when ale is trying to fix a file while changing the screen focus.

This may not be the most minimal rc file but I'm not sure how to minimally produce things like delayed buffer modifications in the same way ale does + focused floating windows like floaterm does.

**To Reproduce**
vimrc:
```vim
set nocompatible
set runtimepath^=~/.config/nvim/pack/packager/start/ale  " or path to ale
set runtimepath^=~/.config/nvim/pack/packager/start/vim-floaterm  " or path to vim-floaterm

autocmd VimEnter * lua require'nvim-treesitter.configs'.setup {}
set foldmethod=expr
set foldexpr=nvim_treesitter#foldexpr()

let g:ale_fixers = {
\   'python': ['isort'],
\}
let g:ale_fix_on_save = 1

noremap  <silent> <Leader>fj :FloatermToggle<CR>

filetype plugin indent on
syntax on
```
1. Open a python file, which will be modified by an ale fixer. Here i use python/isort and like... `import pytest; import unittest`
2. save that file
3. Quickly (before the fixer is completed) invoke floaterm
4. See:
```
Error detected while processing function <SNR>111_NeoVimCallback[29]..<lambda>40[1]..<SNR>106_ExitCallback[28]..<SNR>129_HandleExit[32]..<SNR>129_RunFixer[6]..ale#fix#ApplyFixe
s[26]..ale#fix#ApplyQueuedFixes[10]..ale#util#SetBufferContents:
line   17:
E21: Cannot make changes, 'modifiable' is off
Press ENTER or type command to continue
```

**Expected behavior**
The same behehavior, as when `set foldexpr=nvim_treesitter#foldexpr()` is left out, i.e. the fix is applied in the background, while you are focused into the floating window.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## python parser healthcheck
  - OK: python parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.

## json parser healthcheck
  - OK: json parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for json
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for json
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## rust parser healthcheck
  - OK: rust parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.

## css parser healthcheck
  - OK: css parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for css
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for css
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## javascript parser healthcheck
  - OK: javascript parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.

## toml parser healthcheck
  - OK: toml parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for toml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## Missing parsers
  - WARNING: Some parsers are not installed:
    elm
    c
    java
    dart
    lua
    ocaml
    go
    nix
    yaml
    jsdoc
    markdown
    julia
    html
    typescript
    fennel
    swift
    query
    cpp
    ruby
    vue
    scala
    tsx
    bash
    c_sharp
    rst
    php
    haskell
    regex
    - ADVICE:
      - Install them using `:TSInstall language
</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by 

Features: +acl +iconv +tui
```

**Comment by vigoux** [comment]
Weird... And this does not happen when you comment the `set foldmethod=expr` right ?

**Comment by DanCardin** [comment]
yup

**Comment by vigoux** [comment]
Is that the same with any other `foldexpr` value ?

**Comment by DanCardin** [comment]
ahh yes, indeed it does. Presumably that indicates it's a bug in Ale then? Happy to close this and resubmit there

**Comment by vigoux** [comment]
I think that we can transfer issues

**Comment by DanCardin** [comment]
alrighty, while i'll close this. thanks for your help, and sorry for the inconvenience!

**Comment by vigoux** [comment]
Thanks for reporting !
