### ISSUE TITLE
Add comment highlight for the `NOTE` marker

### ISSUE THREAD

**Issue by erikw** [nvim-treesitter/nvim-treesitter#3536]
(redirect from original issue https://github.com/stsewd/tree-sitter-comment/issues/13)

It is custom in source code files to add special markers in comments, most known probably `TODO`. Then it's easy to to `grep(1)` for this later.

The current known comment markers are defined here:
https://github.com/nvim-treesitter/nvim-treesitter/blob/9b13872f19aa97916ba0ae92bac6fb9e2c1dd06d/queries/comment/highlights.scm#L10-L20

What I quickly noticed when I started to use treesitter for comments, is that the `NOTE` marker that I frequently use was not included. I [found a way](https://github.com/stsewd/tree-sitter-comment/issues/13#issuecomment-1243443143) to add this my self however I wonder if this could possibly be included by default.

Well, I claim `NOTE` is common but this could of course likely be biased by my own usage...
Thus I tried to get some numbers from GitHub's new Code Search:
https://cs.github.com/?scopeName=All+repos&scope=&q=%2F%28%3F-i%29+NOTE+%2F

`/(?-i) NOTE /` matched to 725k files, compared to
* `FIXME`: 500k files
* `HACK`:  122k files
* `TODO` : 5.3M files
* `WARNING`: 350k files
* `BUG`: 137k files

So `NOTE` seems to be at least as common as some already recognized comment markers. These numbers should not be exact, since this simple regex don't even try to match the context of a comment. However it seems to say that it's in the same ballpark at least.

Could we add `NOTE` to the default recognized comment markers?

**Comment by clason** [comment]
Sure, just make a PR!
