### ISSUE TITLE
[Lua] Parser installed but no highlighting happening. 

### ISSUE THREAD

**Issue by teddylear** [nvim-treesitter/nvim-treesitter#3538]
### Describe the bug

After building nightly neovim, updating plugins, and running `:TSUpdate`, treesitter highlighting on lua files is not working. `:checkhealth` is not showing any problems either (everything is healthly and everything in lua is checked). I checked a few other languages and only the lua parser is giving me issues.

### To Reproduce

Open a lua file and see no highlighting

### Expected behavior

Lua file highlighting. 

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.0 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.0.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.1.6 (clang-1316.0.21.2.3)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - yaml           ✓ ✓ ✓ ✓ ✓
  - markdown       ✓ . ✓ . ✓
  - cpp            ✓ ✓ ✓ ✓ ✓
  - json           ✓ ✓ ✓ ✓ .
  - vim            ✓ ✓ ✓ . ✓
  - hcl            ✓ . ✓ ✓ ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - dockerfile     ✓ . . . ✓
  - rust           ✓ ✓ ✓ ✓ ✓
  - ruby           ✓ ✓ ✓ ✓ ✓
  - java           ✓ ✓ . ✓ ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - cue            ✓ . . . .
  - python         ✓ ✓ ✓ ✓ ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - typescript     ✓ ✓ ✓ ✓ ✓
  - help           ✓ . . . .
  - query          ✓ ✓ ✓ ✓ ✓
  - bash           ✓ ✓ ✓ . ✓
  - go             ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
[I] ➜ nvim --version
NVIM v0.8.0-dev-1150-gede66a0b8
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by root@Kenneths-Air

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Additional context

Confirmed this on two separate macbooks. Please let me know if you need additional information or anything else to debug. 

My config for treesitter:
```lua
require("nvim-treesitter.configs").setup({
    ensure_installed = {
        "python",
        "go",
        "lua",
        "yaml",
        "json",
        "bash",
        "rust",
        "dockerfile",
        "typescript",
        "ruby",
        "javascript",
        "query",
        "cpp",
        "markdown",
        "hcl",
        "cue",
    },
    highlight = {
        enable = true,
    },
})
```

**Comment by teddylear** [comment]
Also using `nvim-treesitter/playground` plugin, `:TSPlaygroundToggle` is working and showing everything correctly. So I assume it's not an issue with the parser being installed but something with the highlighting for lua specifically.

**Comment by cuicuicuicuixi** [comment]
I had the same problem after updating treesitter, finally solved it by updating neovim-nightly to `NVIM v0.8.0-dev-1152-g14610332b`

**Comment by teddylear** [comment]
I'm still having iusse on later build:
```
[I] ➜ nvim --version
NVIM v0.8.0-dev-1160-gb0fcdf9f0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by root@Kenneths-Air

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by petertriho** [comment]
Strangely do not have this issue with lua but have this issue with python

**Comment by LoneExile** [comment]
I have an issue with python too.

**Comment by ccastanedaucf** [comment]
I just updated plugins + neovim-nightly and just started seeing something similar with csharp, while other languages work fine. Oddly though, highlighting still shows in the telescope previews, just not when opening the buffer. Manually triggering `:TSBufToggle highlight` currently works as a workaround for me.

**Comment by teddylear** [comment]
@ccastanedaucf Thanks for the work around! Weird that lsp caused this though...

**Comment by JMarkin** [comment]
I found this problem on python
1. lsp enable/disable not change issue
2. I iterated days and used first green commit, found that on commit 4dc4cf346755375e49410e16635c00a602b26c36 (Date:   Wed Sep 7 17:59:27 2022 +0200) problem not reproduce

I don't know what it means but if you want to use nvim's nighty features you can use commit  4dc4cf346755375e49410e16635c00a602b26c36 that works correctly

**Comment by LoneExile** [comment]
My Treesitter is working properly now.

**Comment by teddylear** [comment]
I'm still having issue, but I temporarily resolved per @ccastanedaucf comment with the following autocmd: 
```lua
vim.api.nvim_create_autocmd({ "BufEnter"}, {
    pattern = { "*.lua" },
    command = "TSBufToggle highlight",
})
```

Even with turning off my lua lsp, I'm still having issue.

**Comment by manveru** [comment]
The neovim version didn't make any difference for me, for the time being i run `TSBufEnable` for all TS features and for all languages, but obviously it would be nice to have that working again.

**Comment by unrealhoang** [comment]
Still having same issue with lua at `NVIM v0.9.0-dev-20-g28fbdd3385`
`TSBufDisable highlight` will show highlighting, not sure it's still TS highlighting or regex based.

**Comment by loqusion** [comment]
I was able to solve it by adding `; extends` to the beginning of every file in `nvim-treesitter/queries/lua`. It seems to be related to neovim/neovim#20105.

**Comment by clason** [comment]
No, that is _not_ the right fix here. You should instead find out which queries are overriding the nvim-treesitter ones, and fix _those_.

**Comment by loqusion** [comment]
If I understand correctly, neovim/neovim#20105 will either partially or completely break highlighting for anyone with plugins written before September 9th that include treesitter queries, and currently the only fix is to either manually patch the plugin query files yourself, delete the plugins, or submit a pr to each plugin and hope that the authors will notice and merge it in.

Can anyone think of a better alternative, or will we just have to cope with this for now?

**Comment by clason** [comment]
Yes. The situation was fundamentally broken before that already, with plugins adding queries indiscriminately and things ending up working by pure accident. 

The Neovim PR is part of the attempt to make this more deterministic and deliberate. The proper fix is for downstream (plugins, users) to decide whether they want to replace or extend and annotate accordingly.

And a reminder: **Treesitter support is still experimental** -- things can and will break frequently while we extend, refactor, and polish the API. I consider plugins (and color schemes!) that ship queries without closely following and adapting to upstream development to be irresponsible to the point of being harmful.
