### ISSUE TITLE
Typescript/TSX freeze when component is returned in a ternary

### ISSUE THREAD

**Issue by davidroeca** [nvim-treesitter/nvim-treesitter#3550]
### Describe the bug

Neovim freezes under odd circumstances when an inline function with multiple arguments is passed as a prop to a component followed by a component with props that use `object.access` syntax. Under this circumstance, any attempts to add a string prop to a component within a ternary expression will cause neovim to freeze the moment `"` is typed, or if an existing string prop loses one of its quotation marks (via deletion or e.g. `x` in normal mode). I have linked a bug reproduction repo for a full example of this behavior. 

By disabling tree-sitter highlights, I was able to prevent the issue from happening, so I'm figuring it's an issue with tsx tree-sitter highlight groups and/or the interaction with the latest versions of neovim.

### To Reproduce

1. To attempt in your own editor, try deleting `this will freeze"` in this file:
```tsx
import React from 'react'


const FailingCase = () => {
  const result1 = {
    error: null,
    loading: false,
    data: [],
  }
  const result2 = {
    error: null,
    loading: false,
    data: [],
  }
  const [value, setValue] = React.useState('')
  return result1.error || result2.error ? (
    <div className="this is fine">Error loading data</div>
  ) : result1.loading || result2.loading ? (
    <div className="so is this" />
  ) : !result1.data || !result2.data ? (
    <div className="this will freeze">No Data</div>
  ) : (
    <div>
      <input
        type="text"
        onChange={(event) => setValue(event.target.value)}
        value={value}
      />
      <button
        disabled={result1.loading}
        autofocus={result2.loading}
      />
    </div>
  )
}

export default FailingCase
```

2. A fully reproducible example can be found [here](https://github.com/davidroeca/nvim-treesitter-tsx-freeze-reproduction#reproduction) if your plugins prevent reproduction.

### Expected behavior

No freezes

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - WARNING: `node` executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Debian 8.3.0-6) 8.3.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - vim            ✓ ✓ ✓ . ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - typescript     ✓ ✓ ✓ ✓ ✓
  - tsx            ✓ ✓ ✓ ✓ ✓
  - jsdoc          ✓ . . . .
  - javascript     ✓ ✓ ✓ ✓ ✓
  - help           ✓ . . . .

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - WARNING: No clipboard tool found. Clipboard registers (`"+` and `"*`) will not work.
    - ADVICE:
      - :help |clipboard|

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python version: 3.10.7
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - WARNING: `node` and `npm` (or `yarn`, `pnpm`) must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` (or `yarn`, `pnpm`) commands work.

## Perl provider (optional)
  - WARNING: "Neovim::Ext" cpan module is not installed
    - ADVICE:
      - See :help |provider-perl| for more information.
      - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/devuser/.local/state/nvim/lsp.log
  - INFO: Log size: 0 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for jsdoc: ABI version 13
  - OK: Loaded parser for tsx: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for help: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for vim: ABI version 14
```

### Output of `nvim --version`

```text
NVIM v0.8.0-dev-1176-g9a5ac0650
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/root/neovim/build/cmake.config -I/root/neovim/src -I/root/neovim/.deps/usr/include -I/usr/include -I/root/neovim/build/src/nvim/auto -I/root/neovim/build/include
Compiled by root@276ee25dcf5d

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Additional context

Using an autopairs plugin (e.g. `nvim-autopairs`) can get around a few of the edge cases, but won't necessarily fix the freeze when someone leaves behind `subtext="` by visual-highlighting and deleting `loading"`,

Based on this behavior, I'm thinking that the freeze happens only when the TSX is technically invalid, with a missing quotation mark.

**Comment by arjenbloemsma** [comment]
Same issue here.

My details:

```
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v17.9.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 15.0.0 (clang-1500.0.40.1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.0.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.0.0: Tue Aug 22 02:13:26 PDT 2023; root:xnu-10002.1.11~16/RELEASE_ARM64_T6000"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

```
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.2/share/nvim"

Run :checkhealth for more info
```

**Comment by denisinvader** [comment]
I have the same issue. If file contains ternary operator inside JSX I can't type `const test = ['` (pressing `'` freezes neovim, top shows 100% CPU usage on its process)

Example code:

```typescript
function Render() {
  const [value, setValue] = useState<string | null>(null);

  // trying to type a line below freezes nvim on first ' character
  // const test = [''];

  return (
    <Select
      value={value}
      renderValue={(currentValue, option) => (
        currentValue
          ? 'Selected state label' || option?.label || value
          : ''
      )}
      onChange={setValue}
    />
  );
}
```

If I move `renderValue` into another function everything works fine

```typescript
const renderValue = <T extends string | number>(valueLabel: ReactNode) => (
  (value: T | null, option: SelectOption<T> | null) => (
    value !== null
      ? valueLabel || option?.label || value
      : ''
  )
);

function Render() {
  const [value, setValue] = useState<string | null>(null);

  const test = [''];

  return (
    <Select
      value={value}
      renderValue={renderValue('Selected state label')}
      onChange={setValue}
    />
  );
}
```

**Comment by strogonoff** [comment]
I have the exact same issue. 

- Happens with either a backtick, a single quote, or a double quote.
- Happens when beginning to enter a string value for a key in an object being passed as an argument to a function call

o, I have grounds to suspect it is much less specific than the original ticket description.

However, it seems to happen in a particular set of circumstances in the surrounding tree of the buffer. Some unfortunate alignment of tokens that trips TS.

Here is a snippet for reproduction. The freeze occurs at entering a quote, in insert mode, immediately following `keyPath: ` in this snippet. The freeze happens before the quote even appears on screen. I couldn’t reduce the snippet further so far.

```typescript
async function _getDB(version?: number): Promise<IDBDatabase> {
  new Promise((resolve, reject) => {
    const request = indexedDB.open('cache', version);
    request.onupgradeneeded = function handleDBOUpgrade(evt: IDBVersionChangeEvent & { target: null | { result?: IDBDatabase } }) {
      const db = evt.target?.result;
      db.createObjectStore('objects', { keyPath: });
      if (!db) {
        throw new Error("Unable to obtain IDB handle while handling version update");
      }
    }
  });
}
export function cacheOne(data: unknown) {
  return Effect.gen(function * (_) {
    yield * _(Effect.tryPromise(() => db.registerFileText('data.json', JSON.stringify(data))));
  });
}
```

The issue goes away after `TSBufDisable highlight`, of course.

**Comment by strogonoff** [comment]
Any issues with this particular TS grammar aside, I believe that no matter what trips TreeSitter, no matter how bad the grammar and the tree, it should never result in Neovim having to be killed.

**Comment by lucario387** [comment]
can reproduce :thinking: 

Well this is oddly specific.

**Comment by clason** [comment]
>  TreeSitter, no matter how bad the grammar and the tree, it should never result in Neovim having to be killed.

That would be nice, but we have no control over external libraries (in this case scanners) -- if they crash, they crash.

**Comment by strogonoff** [comment]
To be honest, a crash, while suboptimal, is still better than a freeze. But if I understand this correctly, external libraries like this, probably for performance, execute directly as part of nvim rather than something separate that can be monitored and killed *by* nvim, so it’s impossible to avoid this because it’s a Turing-complete language and nvim can’t predict whether the code halts. Fair enough.

Then, I guess, fixing this particular issue in the grammar or TreeSitter itself is all we can do.

I wonder if it reproduces in TreeSitter generally, as opposed to TS just in nvim🤔

**Comment by strogonoff** [comment]
> Well this is oddly specific.

It was adapted from a real-world scenario. It took long enough just to reduce that file to a manageable snippet that I don’t think I’d try any time soon to create the most minimal general case that has nothing except the conditions required for the freeze. I bet it’s probably something about a combination of quotes, nested functions and maybe `*` plays a role.

It happened 2–3 times over the past month for me. The first time I thought it’s typescript-language-server choking and I worked around this by getting the quote in without entering insert mode. Only this time I decided to really look whether many people encountered it… Doesn’t seem like it, I suppose most TypeScript devs stick to VS Code.

**Comment by lucario387** [comment]
Two ways to resolve this from what I tried:

- have a plugin that automatically finish quotes for you. It wont freeze in that case
- have some keymaps to do the job instead of a plugin.

**Comment by strogonoff** [comment]
> Two ways to resolve this from what I tried:
> 
> * have a plugin that automatically finish quotes for you. It wont freeze in that case
> * have some keymaps to do the job instead of a plugin.

`vlr"` is easier. Anyway, this doesn’t solve the underlying issue.

For example, here is a file that will freeze Neovim upon opening, even before you can enter anything:

```typescript
async function _getDB(version?: number): Promise<IDBDatabase> {
  new Promise((resolve, reject) => {
    const request = indexedDB.open('cache', version);
    request.onupgradeneeded = function handleDBOUpgrade(evt: IDBVersionChangeEvent & { target: null | { result?: IDBDatabase } }) {
      const db = evt.target?.result;
      db.createObjectStore('objects', { keyPath: '});
      if (!db) {
        throw new Error("Unable to obtain IDB handle while handling version update");
      }
    }
  });
}
export function cacheOne(data: unknown) {
  return function * (_) {
    yield * _(() => db.registerFileText('data.json', JSON.stringify(data)));
  };
}
```

**Comment by clason** [comment]
Can you try debugging this? (Compile Neovim in debug mode and attach a debugger when it freezes; this will tell you where exactly it's spending all the CPU cycles.)

**Comment by strogonoff** [comment]
Note two curiosities:

- My above comment took really long to post.
- Github’s treesitter-based highlighter does not work on that snippet.

I think Github runs treesitter on it, but unlike Neovim it kills it after a while. Would *love* if Neovim did the same!

**Comment by clason** [comment]
Nevertheless, this seems to be an upstream bug in tree-sitter (see https://github.com/tree-sitter/tree-sitter-typescript/issues/265). Please file an issue in tree-sitter/tree-sitter.

(Async parsing -- i.e., not fully blocking the editor while parsing -- is already being worked on and planned for 0.10.)

**Comment by strogonoff** [comment]
> Can you try debugging this? (Compile Neovim in debug mode and attach a debugger when it freezes; this will tell you where exactly it's spending all the CPU cycles.)

I’m a very basic user and I’m on stable Neovim. But in any case:

1. It’s obviously Tree Sitter that’s running into the infinite loop, not Neovim itself. As you can see, the issue affects Tree Sitter everywhere, including Github syntax highlighter.
2. As I’ve been told upthread, Neovim’s architecture is such that an infinite loop in Tree Sitter will take down the entire editor.

Which brings us to two separate issues:

1. An upstream issue in Tree Sitter & its Typescript grammar. This is irrelevant to Neovim.
2. An architectural issue in Neovim that means Tree Sitter can take it down. This is relevant to Neovim, but I guess Neovim core devs may or may not want to won’t fix it. I for sure think it’d be better if Neovim was resilient against infinite loops in treesitter, and eliminating this issue would help Neovim gain wider adoption (I imagine running into such an issue can easily push a novice away towards VS Code and the like).

**Comment by clason** [comment]
1. It's still a bug that needs fixing, and opening an issue helps with that -- since Neovim depends on tree-sitter, this will also help Neovim (and, in turn, you).
2. Is already being worked on, as I said, so doesn't need to be tracked here.

So there's nothing left to do here.

**Comment by strogonoff** [comment]
> Nevertheless, this seems to be an upstream bug in tree-sitter (see [tree-sitter/tree-sitter-typescript#265](https://github.com/tree-sitter/tree-sitter-typescript/issues/265)). Please file an issue in tree-sitter/tree-sitter.
> 
> (Async parsing -- i.e., not fully blocking the editor while parsing -- is already being worked on and planned for 0.10.)

If Neovim editor is not blocked, but there is still a background process occupying 100% CPU until you kill it, then it’s a half-measure.

**Comment by strogonoff** [comment]
> It's still a bug that needs fixing, and opening an issue helps with that -- since Neovim depends on tree-sitter, this will also help Neovim (and, in turn, you).

Thank you. Filed https://github.com/nvim-treesitter/nvim-treesitter/issues/5882.

**Comment by clason** [comment]
I meant "issue in tree-sitter/tree-sitter", where this bug is happening. #5882 is a pure duplicate and just noise.
