### ISSUE TITLE
[Question]: Language specific highlight changes in nvim 0.8.0

### ISSUE THREAD

**Issue by JosefLitos** [nvim-treesitter/nvim-treesitter#3568]
I have multiple places in different languages, where I wanted to use a different highlight from the default.
```vim
hi link yamlTSField TSKeyword
hi link bashTSConstant TSVariable
hi bashTSConstant gui=italic
hi link bashTSNone TSString
```
After the update there `languageTS...` highlights exist no more.
How would one replicate the language specific highlight changes with the new weird `@...` style?

**Comment by nullchilly** [comment]
`@constructor.lua`

**Comment by JosefLitos** [comment]
what?
how would I transfer this vimscript code into lua to work with the latest neovim update?
