### ISSUE TITLE
Update to Nvim 0.8 highlighting changes

### ISSUE THREAD

**Issue by clason** [nvim-treesitter/nvim-treesitter#3572]
Now that Nvim 0.8 is released, we should yeet all traces of the old `TSFoo` highlight groups -- including the tests. 

In particular the one that is failing now (and thus blocking all PRs) that the stable version doesn't set these by default anymore -- @theHamsta

**Comment by theHamsta** [comment]
Would be nice to have a PR for that. I will return from vacation on oct 9

**Comment by theHamsta** [comment]
The highlight tests are already able to test for queries only. One would just have to remove the translation to highlight groups in the tests

**Comment by clason** [comment]
Tests should pass again with my PR that you just merged; but the tests explicitly check for `TSFoo` highlights, so we can't remove those groups until we (search and) replace those in the corpus.

**Comment by theHamsta** [comment]
We should also tag a v0.8.0 release of nvim-treesitter. Maybe @vigoux could do that with his admin privileges?

**Comment by clason** [comment]
I'd rather tag a v.0.7.0 to indicate the last version compatible with Nvim 0.7?

**Comment by theHamsta** [comment]
The point is rather to have a snapshot that will work with whatever release the user choses. In the past, we have snapshotted more or less with nvim releases. We could wait for 0.8.0 until we remove the other highlight groups

**Comment by clason** [comment]
Neovim 0.8 got released last Friday...

**Comment by clason** [comment]
A separate issue, lest I forget, is to remove the upstreamed functions and instead call their Neovim version. (But I'd rather wait for some refactoring on those to be done first.)

This also applies to the highlighting module that can just be replaced with `vim.treesitter.start()`.

**Comment by clason** [comment]
Closed in #3656
