### ISSUE TITLE
set_custom_captures doesn't do anything after update to nvim 0.8

### ISSUE THREAD

**Issue by Dook97** [nvim-treesitter/nvim-treesitter#3586]
I use the treesitter plugin for syntax highlighting (among other things), but
after the recent neovim update I cannot seem to use:

```
require"nvim-treesitter.highlight".set_custom_captures {
    ...
}
```

to set different highlight group for the given capture. It simply doesn't do anything.

This is the relevant block of code in my init.vim:

```
lua << EOF
require'nvim-treesitter.configs'.setup {
    -- A list of parser names, or "all"
    ensure_installed = {
        "c", "cpp", "go", "javascript", "json", "latex", "python", "typescript", "lua"
    },

    -- Install parsers synchronously (only applied to `ensure_installed`)
    sync_install = false,

    highlight = {
        -- `false` will disable the whole extension
        enable = true,
        -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
        additional_vim_regex_highlighting = false,
    },
}

require"nvim-treesitter.highlight".set_custom_captures {
    ["constant.builtin"] = "Normal",
    ["function.builtin"] = "TSFunction",
    ["constructor"]      = "TSFunction",
    ["method.call"]      = "TSFunction",
    ["namespace"]        = "Normal",
    ["parameter"]        = "Normal",
    ["property"]         = "Normal",
    ["operator"]         = "Normal",
    ["function"]         = "Normal",
    ["method"]           = "TSFunction",
}
EOF
```

Worked fine before the update, now I just get the default treesitter
highlighting, which is way too colourful for me.

Obligatory: Sorry, this is probably a stupid question ;p

**Comment by mabugaj** [comment]
I've got similar situation where:

- ~/.config/nvim/after/queries/python/highlights.scm
- ~/.config/nvim/after/queries/python/injections.scm

stopped working and after I've switched back everything is working correctly.

**Comment by mateusz-n7mobile** [comment]
Ok my problem solved with: https://github.com/nvim-treesitter/nvim-treesitter/issues/3569#issuecomment-1267331875

**Comment by mabugaj** [comment]
My problem solved with: https://github.com/nvim-treesitter/nvim-treesitter/issues/3569#issuecomment-1267331875

**Comment by lasypig** [comment]
lua function `set_custom_captures()` was executed before `link_all_captures()`,  but why?

**Comment by clason** [comment]
This function has been removed since highlighting is now completely handled by Neovim core. Just define or link highlight groups with the same name as the capture you want to highlight (e.g., `hi link @constant.builtin Normal`).
