### ISSUE TITLE
Impossible to load parser for html: Failed to load parser: uv_dlopen: error: 127

### ISSUE THREAD

**Issue by sirAndre1337** [nvim-treesitter/nvim-treesitter#3587]
### Describe the highlighting problem

in html files the highlights does not work, i`m using gcc windows 10 64-bits, in js,tsx,jsx,css works well.

### Example snippet that causes the problem

  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for cpp: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for fish: ABI version 13
  - OK: Loaded parser for help: ABI version 14
  - ERROR: Impossible to load parser for html: Failed to load parser: uv_dlopen: error: 127
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for php: ABI version 13
  - OK: Loaded parser for toml: ABI version 13
  - OK: Loaded parser for tsx: ABI version 13
  - OK: Loaded parser for vim: ABI version 14
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for help: ABI version 14
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for vim: ABI version 14

### Tree-sitter parsing result

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.17.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: gcc.exe (MinGW-W64 x86_64-posix-seh, built by Brecht Sanders) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - c              ✓ ✓ ✓ ✓ ✓
  - fish           ✓ ✓ ✓ ✓ ✓
  - php            ✓ ✓ ✓ ✓ ✓
  - css            ✓ . ✓ ✓ ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - toml           ✓ ✓ ✓ ✓ ✓
  - cpp            ✓ ✓ ✓ ✓ ✓
  - html           x x x x x
  - tsx            ✓ ✓ ✓ ✓ ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - json           ✓ ✓ ✓ ✓ .
  - vim            ✓ ✓ ✓ . ✓
  - help           ✓ . . . .

### Example screenshot

  - ERROR: html(highlights): Failed to load parser: uv_dlopen: error: 127
    html(highlights) is concatenated from the following files:
    | [ERROR]:"C:\Users\Andre\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html_tags\highlights.scm", failed to load: Failed to load parser: uv_dlopen: error: 127
    | [ERROR]:"C:\Users\Andre\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html\highlights.scm", failed to load: Failed to load parser: uv_dlopen: error: 127
  - ERROR: html(locals): Failed to load parser: uv_dlopen: error: 127
    html(locals) is concatenated from the following files:
    | [ERROR]:"C:\Users\Andre\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html\locals.scm", failed to load: Failed to load parser: uv_dlopen: error: 127
  - ERROR: html(folds): Failed to load parser: uv_dlopen: error: 127
    html(folds) is concatenated from the following files:
    | [ERROR]:"C:\Users\Andre\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html\folds.scm", failed to load: Failed to load parser: uv_dlopen: error: 127
  - ERROR: html(indents): Failed to load parser: uv_dlopen: error: 127
    html(indents) is concatenated from the following files:
    | [ERROR]:"C:\Users\Andre\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html_tags\indents.scm", failed to load: Failed to load parser: uv_dlopen: error: 127
    | [ERROR]:"C:\Users\Andre\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html\indents.scm", failed to load: Failed to load parser: uv_dlopen: error: 127
  - ERROR: html(injections): Failed to load parser: uv_dlopen: error: 127
    html(injections) is concatenated from the following files:
    | [ERROR]:"C:\Users\Andre\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html\injections.scm", failed to load: Failed to load parser: uv_dlopen: error: 127

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.17.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: gcc.exe (MinGW-W64 x86_64-posix-seh, built by Brecht Sanders) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - c              ✓ ✓ ✓ ✓ ✓
  - fish           ✓ ✓ ✓ ✓ ✓
  - php            ✓ ✓ ✓ ✓ ✓
  - css            ✓ . ✓ ✓ ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - toml           ✓ ✓ ✓ ✓ ✓
  - cpp            ✓ ✓ ✓ ✓ ✓
  - html           x x x x x
  - tsx            ✓ ✓ ✓ ✓ ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - json           ✓ ✓ ✓ ✓ .
  - vim            ✓ ✓ ✓ . ✓
  - help           ✓ . . . .

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: html(highlights): Failed to load parser: uv_dlopen: error: 127
    html(highlights) is concatenated from the following files:
    | [ERROR]:"C:\Users\Andre\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html_tags\highlights.scm", failed to load: Failed to load parser: uv_dlopen: error: 127
    | [ERROR]:"C:\Users\Andre\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html\highlights.scm", failed to load: Failed to load parser: uv_dlopen: error: 127
  - ERROR: html(locals): Failed to load parser: uv_dlopen: error: 127
    html(locals) is concatenated from the following files:
    | [ERROR]:"C:\Users\Andre\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html\locals.scm", failed to load: Failed to load parser: uv_dlopen: error: 127
  - ERROR: html(folds): Failed to load parser: uv_dlopen: error: 127
    html(folds) is concatenated from the following files:
    | [ERROR]:"C:\Users\Andre\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html\folds.scm", failed to load: Failed to load parser: uv_dlopen: error: 127
  - ERROR: html(indents): Failed to load parser: uv_dlopen: error: 127
    html(indents) is concatenated from the following files:
    | [ERROR]:"C:\Users\Andre\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html_tags\indents.scm", failed to load: Failed to load parser: uv_dlopen: error: 127
    | [ERROR]:"C:\Users\Andre\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html\indents.scm", failed to load: Failed to load parser: uv_dlopen: error: 127
  - ERROR: html(injections): Failed to load parser: uv_dlopen: error: 127
    html(injections) is concatenated from the following files:
    | [ERROR]:"C:\Users\Andre\AppData\Local\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html\injections.scm", failed to load: Failed to load parser: uv_dlopen: error: 127
```

### Output of `nvim --version`

```text
NVIM v0.8.0-1210-gd367ed9b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilado por runneradmin@fv-az177-603

Features: -acl +iconv +tui
See ":help feature-compile"

    arquivo vimrc de sistema: "$VIM\sysinit.vim"
            padrão para $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

### Additional context

![image](https://user-images.githubusercontent.com/21043350/193996314-d82ff20d-e039-4957-a129-fcaf4d6ad3db.png)
![image](https://user-images.githubusercontent.com/21043350/193996569-9127617e-0546-4652-b340-ab60051d29aa.png)

**Comment by Jesspu** [comment]
I am having this same issue as well, only showed up recently. 

```
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.15.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `gcc` executable found. Selected from { "gcc" }
    Version: gcc.exe (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders) 12.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - javascript     ✓ ✓ ✓ ✓ ✓
  - help           ✓ . . . .
  - html           x x x x x
  - typescript     ✓ ✓ ✓ ✓ ✓
  - svelte         ✓ . ✓ ✓ ✓
  - css            ✓ . ✓ ✓ ✓
  - jsdoc          ✓ . . . .
  - java           ✓ ✓ . ✓ ✓
  - c_sharp        ✓ ✓ ✓ . ✓
  - json           ✓ ✓ ✓ ✓ .
  - vim            ✓ ✓ ✓ . ✓
  - markdown       ✓ . ✓ . ✓
  - org            . . . . .
  - c              ✓ ✓ ✓ ✓ ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - markdown_inline✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: html(highlights): Failed to load parser: uv_dlopen: The specified procedure could not be found.
    
    html(highlights) is concatenated from the following files:
    | [ERROR]:"C:\Users\patmj\Github\dotfiles\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html_tags\highlights.scm", failed to load: Failed to load parser: uv_dlopen: The specified procedure could not be found.
    
    | [ERROR]:"C:\Users\patmj\Github\dotfiles\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html\highlights.scm", failed to load: Failed to load parser: uv_dlopen: The specified procedure could not be found.
  - ERROR: html(locals): Failed to load parser: uv_dlopen: The specified procedure could not be found.
    
    html(locals) is concatenated from the following files:
    | [ERROR]:"C:\Users\patmj\Github\dotfiles\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html\locals.scm", failed to load: Failed to load parser: uv_dlopen: The specified procedure could not be found.
  - ERROR: html(folds): Failed to load parser: uv_dlopen: The specified procedure could not be found.
    
    html(folds) is concatenated from the following files:
    | [ERROR]:"C:\Users\patmj\Github\dotfiles\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html\folds.scm", failed to load: Failed to load parser: uv_dlopen: The specified procedure could not be found.
  - ERROR: html(indents): Failed to load parser: uv_dlopen: The specified procedure could not be found.
    
    html(indents) is concatenated from the following files:
    | [ERROR]:"C:\Users\patmj\Github\dotfiles\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html_tags\indents.scm", failed to load: Failed to load parser: uv_dlopen: The specified procedure could not be found.
    
    | [ERROR]:"C:\Users\patmj\Github\dotfiles\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html\indents.scm", failed to load: Failed to load parser: uv_dlopen: The specified procedure could not be found.
  - ERROR: html(injections): Failed to load parser: uv_dlopen: The specified procedure could not be found.
    
    html(injections) is concatenated from the following files:
    | [ERROR]:"C:\Users\patmj\Github\dotfiles\nvim-data\site\pack\packer\start\nvim-treesitter\queries\html\injections.scm", failed to load: Failed to load parser: uv_dlopen: The specified procedure could not be found.
```

**Comment by beauwilliams** [comment]
Same here

**Comment by RitschAlex** [comment]
Got the same problem! I`m using gcc with windows 11 64-bits. Besides html, all other filetypes I use work fine.

**Comment by theHamsta** [comment]
Could you try to analyze the generated DLL (maybe rename from so to DLL)? From the list presented here, I think only C++ and HTML use C++ in their parser. This will require the C++ standard library for the DLL, except the C++ standard library gets somehow optimized out which might have happened for c++.

> The specified procedure could not be found.

This could hint to somewhat needed from the C++ standard library. There are tools which will show you the dependencies of a DLL

**Comment by Jesspu** [comment]
@theHamsta I renamed the `html.so` to `html.dll`. Then ran `ldd html.dll`. The output is 

```
 ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7ff8e50b0000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7ff8e4e50000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7ff8e2920000)
        msvcrt.dll => /c/WINDOWS/System32/msvcrt.dll (0x7ff8e3110000)
        umppc15908.dll => /c/WINDOWS/System32/umppc15908.dll (0x2822b0e0000)
        umppc15908.dll => /c/WINDOWS/System32/umppc15908.dll (0x2822b0e0000)
        ucrtbase.dll => /c/WINDOWS/System32/ucrtbase.dll (0x7ff8e2fe0000)
        libgcc_s_seh-1.dll => /c/tools/neovim/nvim-win64/bin/libgcc_s_seh-1.dll (0x61440000)
        libstdc++-6.dll => /c/tools/neovim/nvim-win64/bin/libstdc++-6.dll (0x6fc40000)
        USER32.dll => /c/WINDOWS/System32/USER32.dll (0x7ff8e4c50000)
        win32u.dll => /c/WINDOWS/System32/win32u.dll (0x7ff8e2cc0000)
        GDI32.dll => /c/WINDOWS/System32/GDI32.dll (0x7ff8e4b80000)
        gdi32full.dll => /c/WINDOWS/System32/gdi32full.dll (0x7ff8e2e20000)
        msvcp_win.dll => /c/WINDOWS/System32/msvcp_win.dll (0x7ff8e2d80000)
        libwinpthread-1.dll => /c/Users/patmj/AppData/Local/Android/Sdk/platform-tools/libwinpthread-1.dll (0x6cb70000)
        libwinpthread-1.dll => /c/Users/patmj/AppData/Local/Android/Sdk/build-tools/30.0.3/libwinpthread-1.dll (0x6cb90000)
        libwinpthread-1.dll => /c/tools/neovim/nvim-win64/bin/libwinpthread-1.dll (0x64940000)
        ```

**Comment by T-727** [comment]
Any updates on this?

**Comment by elge70** [comment]
One issue with html and yaml parsers are that they are written in C++. Both have dependency with  libstdc++-6.dll. Neovim windows version distributes the library for nvim-qt.exe. When we compile using gcc installed on the machine, it links with  libstdc++-6.dll which comes with gcc. But due to path variable, the html.so and yaml.so points  libstdc++-6.dll which comes with nvim. If you are not using nvim-qt, you could delete  libstdc++-6.dll which comes with nvim. Otherwise adjust paths so that it will point to the  libstdc++-6.dll which comes with installed gcc.

**Comment by Parables** [comment]
To resolve this issue, you can try the following:

Check which version of libstdc++-6.dll is being used by Neovim by running the following command:

javascript
Copy code
ldd $(which nvim)
This will show a list of all the libraries that Neovim depends on, including libstdc++-6.dll.

Make sure that the version of libstdc++-6.dll being used by Neovim is the same as the one installed by Pacman. To do this, run the following command:

bash
Copy code
pacman -Qo /usr/lib/libstdc++.so.6
This will show you which package provides the version of libstdc++-6.dll that is installed on your system.

If the version of libstdc++-6.dll being used by Neovim is different from the one installed by Pacman, you may need to adjust your system's library search path. To do this, add the following line to your .bashrc or .zshrc file:

javascript
Copy code
export LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH
This will add /usr/lib to the beginning of your system's library search path, so that Neovim will use the version of libstdc++-6.dll provided by Pacman.

Restart your terminal or source your .bashrc or .zshrc file to apply the changes.

Verify that Neovim is now using the correct version of libstdc++-6.dll by running the ldd command again and checking the output.

Credit: ChatGPT

**Comment by Jesspu** [comment]
So, @elge70 fix of deleting `libstdc++-6.dll` in the `nvim-win64\bin` used to work fine. However it is no longer working. After removing `libstdc++-6.dll` I am still getting this error. 

Is my only option to build from source with the option for nvim-qt turned off?

**Comment by kylemacfarlane** [comment]
I worked around this issue using the tip in the wiki: https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support#troubleshooting

Install LVMC which contains clang, configure treesitter to prefer clang (or take gcc off your path), build broken parsers with clang instead of gcc.

**Comment by Jesspu** [comment]
@kylemacfarlane Thanks, that got the issue resolved for me.
