### ISSUE TITLE
Do i need turn off other syntax plugins when using treesitter?

### ISSUE THREAD

**Issue by xaljer** [nvim-treesitter/nvim-treesitter#359]
Do i need turn off other syntax plugins like sheerun/vim-polyglot when using treesitter? How do they work together?
I want syntax highlight on file type which treesitter unsupported, should i configure for every file type, or treesitter will disable other syntax highlight on supported file type?

**Comment by theHamsta** [comment]
When you activate treesitter highlighting, syntax gets automatically turned off for that file type while you can keep it for the file types without parser. Unfortunately, there's no priority system as for classic highlighting so usually both highlighting of plugins and treesitter gets applied. This should however only apply to plugins that add additional highlights and not for plugins that provide/extend vims syntax rules.

If there's any interference between plugins and treesitter highlighting for certain syntax elements, e.g. brackets, you can deactivate the highlights linking the corresponding highlight groups to no highlights.

**Comment by xaljer** [comment]
@theHamsta, thanks for your reply. 
> syntax gets automatically turned off for that file type
it's like `syntax off`? I found that 'luochen1990/rainbow' works fine with treesitter, and it use syntax highlighting i guess.
> you can deactivate the highlights linking the corresponding highlight groups to no highlights.
Do you mean deactivate traditional syntax highlight rules? Could treesitter control highlight of some syntax elements?

By the way, does treesitter have some plan to do rainbow brackets feature? It looks like sensible to treesitter?

**Comment by theHamsta** [comment]
It literally executes `syntax off` this deactivates lading of files in`syntax/*`. Plugins can still execute vim script so set other highlights.

You can control treesitter highlighting by modifing or or extending the query files. Have look at the `scm` files in our `queries` folder.

There's no plan for rainbow highlighting at the moment. But it would be easy to write a custom module https://github.com/nvim-treesitter/module-template. But as you said it can also be done with existing plugins.

**Comment by p00f** [comment]
When nvim-treesitter didn't have java, I used to use https://github.com/uiiaoo/java-syntax.vim . It worked properly

**Comment by theHamsta** [comment]
This was more a question. We hope we have answered it. We have enough other Lua-highlighting-should-work-with-normal-`syntax` highlights issues. We are still working on it.
