### ISSUE TITLE
Can treesitter add a new highlight group 'TSPreCondit'?

### ISSUE THREAD

**Issue by Bekaboo** [nvim-treesitter/nvim-treesitter#3633]
**Is your feature request related to a problem? Please describe.**
I find no way to set highlights for preprocessors like '#if', '#ifdef', '#ifndef' in c explicitly without affecting the highlights of other keywords (such as 'extern', 'static', etc) because these preprocessors are assigned to 'TSKeyword'.
In vim/nvim however, there's a highlight group called 'PreCondit' for these preprocessors, so I wonder if we can have a 'TSPreCondit' in nvim-treesitter.

Below are screenshots with and without nvim-treesitter highlights:

![Screenshot_20221013_021318](https://user-images.githubusercontent.com/76579810/195528188-46e01628-4519-476c-80ca-085d32e597f3.png)
![Screenshot_20221013_021340](https://user-images.githubusercontent.com/76579810/195528184-8fb7d28d-4e54-4df4-aeb7-38eb6da366f1.png)

**Describe the solution you'd like**
Add a new highlight group 'TSPreCondit' for preprocessors like '#if', '#ifdef', '#ifndef'.

**Comment by clason** [comment]
No, these highlight groups are obsolete since Neovim 0.8 exposes all captures directly as highlight groups. Rather than adding new ones, they will all be removed soon.

**Comment by Bekaboo** [comment]
> No, these highlight groups are obsolete since Neovim 0.8 exposes all captures directly as highlight groups. Rather than adding new ones, they will all be removed soon.

Thank you for reply, but can you tell us how to change the highlighting of `#if`, `#ifdef`, `ifnef` without affecting other keywords, such as `extern`, `static`, etc?

**Comment by clason** [comment]
You'd need to write your own queries that use different captures for these.

**Comment by Bekaboo** [comment]
> You'd need to write your own queries that use different captures for these.

Thanks!

**Comment by theHamsta** [comment]
Not specific to conditions, but `@preproc` might be used for this https://github.com/nvim-treesitter/nvim-treesitter/pull/3567#issuecomment-1270105013. `@preproc.conditional` might not be absurd, but let's go one step at a time to make sure people can still theme a limited amount of captures
