### ISSUE TITLE
Enum variants

### ISSUE THREAD

**Issue by Trard** [nvim-treesitter/nvim-treesitter#3651]
**Is your feature request related to a problem? Please describe.**
Nvim-treesitter highlights Rust enum variants as constants. In fact, they are not constants. It also highlights TS enum members and C++ union members as `@property`. In fact, they are not properties.

**Describe the solution you'd like**
Add new highlight group for enum variants.

**Additional context**
It might also help to fix  https://github.com/nvim-treesitter/nvim-treesitter/issues/3610

**Comment by theHamsta** [comment]
> It also highlights TS enum members and C++ union members as @property. In fact, they are not properties.

I don't see any issues for using `@constant` for enum variant or `@field`/`@property` for unions. I think they are the closest concept and editors have a tradition of highlighting `struct`/`enum` similarly. It is worth to compare with queries from upstream tree-sitter or VSCode.

For Rust, it would be important to me to distinguish enum variants from types. Do you have an alternative suggestion? For me, `@constant` is still plausible as the variant names mostly stand for the variant tags to be distinguished. `@symbol` and no highlight would be possible.

**Comment by amaanq** [comment]
I disagree, and at this point this seems somewhat stale. Imo enum variants **are** constants for the most part, the way they're structured, often their values (except for tuple/struct variants in Rust), etc.. #3610 is a valid issue but I think this can be closed.
