### ISSUE TITLE
How to make hl-TSTodo work

### ISSUE THREAD

**Issue by Neur1n** [nvim-treesitter/nvim-treesitter#3655]
### Describe the highlighting problem

As what `:h hl-TSTodo` says

> hl-TSTodo
TSTodo
Anything that needs extra attention, such as keywords like TODO or FIXME.

And `:hi TSTodo` echoes "TSTodo xxx links to Todo", where `Todo` is defined as an orange color by myself.

I was expecting "TODO", "FIXME" and "NOTE" being highlighted in something like this:

```cpp
// TODO: some todo
// NOTE: some note
// FIXME: some fixme
```

But they are highlighted as normal comment strings (gray in my config). And `:TSHighlightCapturesUnderCursor` echoes the following in a floating window:

```
# Treesitter
* @comment
* @spell
```

### Example snippet that causes the problem

```cpp
// TODO: some todo
// NOTE: some note
// FIXME: some fixme

int main(int argc, char **argv)
{


  return 0;
}
```

### Tree-sitter parsing result

![image](https://user-images.githubusercontent.com/17579247/196035814-de1c3f0e-90d3-4de4-bb3e-8d9c0373f760.png)

### Example screenshot

![image](https://user-images.githubusercontent.com/17579247/196035852-2d6a2dd1-1b17-4a80-8202-21747595629e.png)

### Expected behavior

Highlight "TODO", "NOTE", "FIXME" words.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v14.15.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: clang version 15.0.2
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - cpp            ✓ ✓ ✓ ✓ ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - vim            ✓ ✓ ✓ . ✓
  - help           ✓ . . . .

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.0-1210-gd367ed9b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az177-603

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
You need to install the `comment` parser for those highlights (and note that `TS*` highlight groups are deprecated with Nvim 0.8, you should map `@text.warning` etc. directly.)

**Comment by Neur1n** [comment]
Sorry to disturb again. After installing the `comment` parser, it work for a while. After I restarted my PC and updated my plugins (including nvim-treesitter) today, it is not working again but with different behavior: the `:` after `NOTE`, `TODO`, `FIXME` is now highlighted with `@punctuation.delimiter`.

**Comment by rafikdraoui** [comment]
@Neur1n https://github.com/nvim-treesitter/nvim-treesitter/pull/3705 might fix this for you, assuming that your color scheme defines the `Todo` or `text.todo` highlights.
