### ISSUE TITLE
Titles in markdown file are not highlighted

### ISSUE THREAD

**Issue by monaqa** [nvim-treesitter/nvim-treesitter#3669]
### Describe the highlighting problem

Titles in markdown are not highlighted.

* Tree-sitter seems to be parsing correctly.
* In fact, token `#` is correctly highlighted (as `@punctuation.delimiter`).
* Highlight group `Delimiter` and `Title` are defined. `@punctuation.delimiter` is also defined.
* However, highlight group `@text.title` is not defined. I guess this is the direct cause.

### Example snippet that causes the problem

```markdown:test.md
# Test Title
```

### Tree-sitter parsing result

```
section [0, 0] - [1, 0]
  atx_heading [0, 0] - [1, 0]
    atx_h1_marker [0, 0] - [0, 1]
    heading_content: inline [0, 1] - [0, 12]
```

### Example screenshot

![not_highlighted](https://user-images.githubusercontent.com/48883418/196166889-efc94f32-46a6-4adf-96bd-5c45ff7b07be.png)

### Expected behavior

The title string should be highlighted in the same color as that defined in `Title` highlight group

![definition_title](https://user-images.githubusercontent.com/48883418/196166943-b715fedb-6918-493a-8560-967ead09254d.png)

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.9.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.1.6 (clang-1316.0.21.2)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - c              ✓ ✓ ✓ ✓ ✓
  - help           ✓ . . . .
  - vim            ✓ ✓ ✓ . ✓
  - markdown       ✓ . ✓ . ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - markdown_inline✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local
Features: +acl +iconv +tui
See ":help feature-compile"
   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.0/share/nvim"
Run :checkhealth for more info
```

### Additional context

Here is minimal `init.lua`:

```lua:init.lua
vim.opt.runtimepath:append("/path/to/latest/nvim-treesitter")
-- to use :TSHighlightCapturesUnderCursor and :TSPlaygroundToggle
vim.opt.runtimepath:append("/path/to/latest/playground")
vim.cmd([[
    source /path/to/latest/nvim-treesitter/plugin/nvim-treesitter.lua
    source /path/to/latest/playground/plugin/nvim-treesitter-playground.lua

    colorscheme morning
    syntax off
]])

require("nvim-treesitter.configs").setup({
	ensure_installed = {
		"markdown",
		"markdown_inline",
	},
	highlight = {
		enable = true,
	},
})
```

I confirmed the behavior with the following command:
```
nvim -u init.lua test.md
```

**Comment by clason** [comment]
You need to link `@text.title` to `Title` (or whatever you prefer) manually.

**Comment by monaqa** [comment]
@clason Thank you for the reply.
Yes, I know `hi link @text.title Title` solves this problem.

However, there are a number of highlight groups that have lost their links due to the breaking change.
In fact, there seem to be fewer group names [defined now](https://github.com/neovim/neovim/commit/030b422d1e9517ed1b1c70fd8002b74881c80650) than [there were originally defined](https://github.com/nvim-treesitter/nvim-treesitter/commit/42ab95d5e11f247c6f0c8f5181b02e816caa4a4f), and the following highlight groups seem to be lost (simple diff from the commit history).

```
@annotation
@attribute
@function.call
@keyword.function
@keyword.operator
@keyword.return
@method.call
@namespace
@none
@string.special
@symbol
@tag
@tag.attribute
@tag.delimiter
@text
@text.danger
@text.emphasis
@text.environment
@text.environment.name
@text.literal
@text.math
@text.note
@text.reference
@text.strike
@text.strong
@text.title
@text.uri
@text.warning
@variable
@variable.builtin
```

Will nvim-treesitter not support these highlights anymore?

**Comment by monaqa** [comment]
Thanks, I see.
As you say, in the long run it is a nice change to have the highlight group name directly tied to the capture name.
For the time being, I have dealt with the settings described [here](https://github.com/nvim-treesitter/nvim-treesitter/commit/42ab95d5e11f247c6f0c8f5181b02e816caa4a4f#commitcomment-87014462).

It might be a good idea to write down how to set this up somewhere easy to find during the transition.
Some people seem to have the same issue and have not been able to resolve it.
https://github.com/nvim-treesitter/nvim-treesitter/issues/3666

**Comment by clason** [comment]
The point is that (now) there's nothing special involving treesitter about this anymore -- you assign highlight groups to captures exactly like you would to legacy syntax groups, so the already documented way applies.
