### ISSUE TITLE
set filetype dynamically

### ISSUE THREAD

**Issue by Freed-Wu** [nvim-treesitter/nvim-treesitter#3692]
**Is your feature request related to a problem? Please describe.**

```lua
local ft_to_parser = require"nvim-treesitter.parsers".filetype_to_parsername
ft_to_parser.someft = "python" -- the someft filetype will use the python parser and queries.
```

For some filetype, e.g., liquid, it is a template language to generate html/css/json/etc. [tpope/vim-liquid](https://github.com/tpope/vim-liquid) will set `b:liquid_subtype` to `html`/`css`/`json`/etc. How to set it dynamically? Thanks.

Similar problem: <https://github.com/neoclide/coc.nvim/issues/4282>

**Describe the solution you'd like**

```lua
local ft_to_parser = require"nvim-treesitter.parsers".filetype_to_parsername
ft_to_parser.someft = "%{get(b:, 'liquid_subtype', 'html')}" -- the someft filetype will use the python parser and queries.
```

**Comment by clason** [comment]
For such a niche situation, it's best to simply use `vim.treesitter.start()` dynamically.

**Comment by Freed-Wu** [comment]
> it's best to simply use vim.treesitter.start() dynamically.

Any document or example about `vim.treesitter.start()`? I cannot find it in README.md

**Comment by clason** [comment]
`:h vim.treesitter.start()` (it's in Neovim 0.8.0)

**Comment by Freed-Wu** [comment]
```
E149: Sorry, no help for vim.treesitter.start()
```

```sh
❯ has nvim
✓ nvim 0.8.0
```

**Comment by clason** [comment]
Yeah, the tags are messed up in that file. Just `:h start()` should get you there.

**Comment by Freed-Wu** [comment]
I am not similar with lua. Can you tell me how can I pass `b:liquid_subtype` to lua?

**Comment by Freed-Wu** [comment]
```
start({bufnr}, {lang})                                               *start()*
    Starts treesitter highlighting for a buffer
```

It only works for highlight? Don't include fold and other functions?

**Comment by Freed-Wu** [comment]
It looks can work:

```lua
vim.api.nvim_create_autocmd("FileType", {
    pattern = "liquid",
    callback = function(args)
        vim.treesitter.start(args.buf, vim.b.liquid_subtype)
        -- only if additional legacy syntax is needed
        vim.bo[args.buf].syntax = "on"
    end
})
```
