### ISSUE TITLE
Incorrect highlighting example for Go

### ISSUE THREAD

**Issue by twharmon** [nvim-treesitter/nvim-treesitter#3718]
### Describe the highlighting problem

The entire file will be highlighted incorrectly if that file contains an interface with an array followed by a slice (see the example below)

### Example snippet that causes the problem

```go
package foo

type T interface {
	[4]int | []int8
}

func Foo() {
}
```

### Tree-sitter parsing result

Unable to provide this info

### Example screenshot

<img width="185" alt="image" src="https://user-images.githubusercontent.com/16892444/197980917-bbf5c449-f2fa-4fc6-83b9-4930da321569.png">

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.13.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - markdown       ✓ . ✓ . ✓
  - typescript     ✓ ✓ ✓ ✓ ✓
  - markdown_inline✓ . . . ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - vim            ✓ ✓ ✓ . ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - help           ✓ . . . .
  - go             ✓ ✓ ✓ ✓ ✓
  - bash           ✓ ✓ ✓ . ✓
  - javascript     ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```
```


### Output of `nvim --version`

```text
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local
```
Same for
```text
NVIM v0.9.0-dev-163+gec33edc7b
```

**Comment by twharmon** [comment]
I wonder if this is a tree-sitter bug - I see the same messed up behavior in Helix. VSCode gets it right.

**Comment by angshumanHalder** [comment]
I was facing the same. For me copying the contents of the [file](https://github.com/tree-sitter/tree-sitter-go/tree/master/queries) into my nvim/after/queries/go/injections.scm seems to fix the syntax highlighting issues.

**Comment by clason** [comment]
Probably a parser issue. Look at the parsed output (using `tree-sitter parse` or `nvim-treesitter/playground`), and possibly open an issue at https://github.com/tree-sitter/tree-sitter-go.
