### ISSUE TITLE
[ Feature Request ] Will treesitter support parse args in functin / method?

### ISSUE THREAD

**Issue by NEX-S** [nvim-treesitter/nvim-treesitter#3758]
Will treesitter support parse args in function / method in the future?

> function args are highlighted
![image](https://user-images.githubusercontent.com/97107165/199347805-8653fc68-6d24-4555-99a2-275a9911ad35.png)

if so, it would be great cuz we don't need `hlargs.nvim` anymore :smile_cat: 

btw, maybe treesitter can add color highlights in HTML / CSS, etc so we don't need `colorizer.nvim`

**Comment by clason** [comment]
This sounds more like a case for LSP semantic highlights, which is orthogonal to what tree-sitter does.
