### ISSUE TITLE
Support `get_node_at_cursor` in comments

### ISSUE THREAD

**Issue by igorlfs** [nvim-treesitter/nvim-treesitter#3761]
**Is your feature request related to a problem? Please describe.**
When using [indent-blankline](https://github.com/lukas-reineke/indent-blankline.nvim), context indent highlight isn't show when the cursor is on a comment ([ref](https://github.com/lukas-reineke/indent-blankline.nvim/issues/92))

**Describe the solution you'd like**
According to the plugin's author, providing `get_node_at_cursor` for comments would solve this issue.

**Comment by clason** [comment]
Why would that function (which is a Neovim core function, by the way) _not_ work for comments?

(Unless you forgot to install the `comment` parser?)

**Comment by clason** [comment]
Looks like indent-blankline can't handle injected languages? In any case, there is no issue with nvim-treesitter here.
