### ISSUE TITLE
Syntax highlighting does not start on file open

### ISSUE THREAD

**Issue by sleaper** [nvim-treesitter/nvim-treesitter#3767]
### Describe the bug

When I open any rust or typescript file I don't have syntax highlighting turned on. I have to manually use `:TSEnable highlight`. This happened after I updated my neovim plugins.

### To Reproduce

1. Fork this nvim folder: https://github.com/sleaper/dotfiles/tree/main/nvim
2. Update plugins with `:PackerInstall`
3. Open any rust or typescript file
4. Syntax highlighting is off

### Expected behavior

Syntax highlighting should be visible. 

### Output of `:checkhealth nvim-treesitter`

```markdown
## Installation 
- OK: ‘tree-sitter' found 0.20.7 (6268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
- OK: 'node found v16.14.2 (only needed for :TSInstallFromGrammar), 
- OK: 'git' executable found. OK: 'cc' executable found. Selected from { vim.NIL, "CC", "gcC", "clang", "cl", "zig" }
Version: cc (Ubuntu 11.3.0-lubuntu 1-22.04) 11.3.0
- OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.
```

### Output of `nvim --version`

```text
NVIM v0.8.0-dev 
Build type: RelwithDebInfo 
LuaJIT 2.1.0-beta3 
Compilation: /usr/bin/cc -g -02 -fdebug-prefix-map=/build/neovim-rhkwe2/neovim-0.8.0-ubuntu 1+git202207311232-abc087f4c-66ad461b6=-fstack-protector-strong-Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 - DNVIM_TS_HAS_SET_MATCH_LIMIT - DNVIM_TS_HAS_SET_ALLOCATOR -02 -9 -Og -g -Wall - Wextra -pedantic -Wno-unused-parameter -W strict-prototypes -std=gnu99 -Wshadow - Wconversion - Wdouble-promotion - Wmissing-noreturn - Wmissing-format-attribute - Wmissing-prototypes -Wimplicit-fallthrough - Wyla -fstack-protector-strong-fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 - I/build/neovim-rhkwe2/neovim-0.8.0-ubuntu 1+git202207311232-abc087f4c-66ad461b6/build/cmake.config -I/build/neovim-rhkwe2/neovim-0.8.0-ubuntu 1+git202207311232- abc087f4c-66ad461b6/src -I/build/neovim-rhkwe2/neovim-0.8.0-ubuntu 1+git202207311232 - abc087f4c-66ad46156/.deps/usr/include -I/usr/include -I/build/neovim-rhkwe2/neovim-0.8.0-ubuntu 1+git20220 7311232-abc087f4c-66ad46156/build/src/nvim/auto -I/build/neovim-rhkwe2/neovim-0.8.0-ubuntu 1+git202207311232 - abc087f4c-66ad461b6/build/include Compiled by buildd@lcy02-amd64-085

Features: +acl +icony +tui See ":help feature-compile"
system vimrc file: "SVIM/sysinit.vim", fall-back for $VIM: "/usr/share/nvin",
Run :checkhealth for more info
```

### Additional context

Here is my treesitter config:
![image](https://user-images.githubusercontent.com/19505081/200112935-3dc31a49-2206-4c1c-a435-e2f3f9861fb5.png)

**Comment by trien1** [comment]
lol I have what seems to be the sameproblem here
do you get this error message?
![image](https://user-images.githubusercontent.com/98476198/200188300-be8d1842-c2b1-48f2-8060-1b77d3d12223.png)

**Comment by sleaper** [comment]
Sometimes same error shows up, and sometimes not. `:TSUpdate` does not work for me. I will try to rebuild my neovim config.

**Comment by Matsuuu** [comment]
I too, am having this problem currently

**Comment by clason** [comment]
PSA: "me, too" comments add nothing to an issue except for noise; it makes it harder to extract the really useful information such as context.

**Comment by sleaper** [comment]
> PSA: "me, too" comments add nothing to an issue except for noise; it makes it harder to extract the really useful information such as context.

If you have some questions feel free to ask. I will try to rebuild my neovim config from scratch.

**Comment by BitInByte** [comment]
> 

If you find something on your config, please let me know because I've been messing around with mine and I can't detect nothing :)
