### ISSUE TITLE
Startup time is very slow on macOS

### ISSUE THREAD

**Issue by kontheocharis** [nvim-treesitter/nvim-treesitter#377]
**Describe the bug**
On a minimal config of neovim 0.5.0 nightly, on macOS Catalina, nvim-treesitter alone takes about 1.5 seconds to load. With the full config, this goes up to 7 seconds.

**To Reproduce**
1. Install neovim 0.5.0 nightly with homebrew on macOS Catalina
2. Install nvim-treesitter through dein.vim
3. Check startup time

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## elm parser healthcheck
  - OK: elm parser found.
  - WARNING: No `highlights.scm` query found for elm
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `locals.scm` query found for elm
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for elm
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## c parser healthcheck
  - OK: c parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.

## java parser healthcheck
  - OK: java parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for java
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## python parser healthcheck
  - OK: python parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.

## dart parser healthcheck
  - OK: dart parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for dart
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for dart
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## lua parser healthcheck
  - OK: lua parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.

## ocaml parser healthcheck
  - OK: ocaml parser found.
  - WARNING: No `highlights.scm` query found for ocaml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `locals.scm` query found for ocaml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for ocaml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## go parser healthcheck
  - OK: go parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.

## nix parser healthcheck
  - OK: nix parser found.
  - WARNING: No `highlights.scm` query found for nix
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `locals.scm` query found for nix
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for nix
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## yaml parser healthcheck
  - OK: yaml parser found.
  - WARNING: No `highlights.scm` query found for yaml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `locals.scm` query found for yaml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for yaml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## json parser healthcheck
  - OK: json parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for json
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for json
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## jsdoc parser healthcheck
  - OK: jsdoc parser found.
  - WARNING: No `highlights.scm` query found for jsdoc
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `locals.scm` query found for jsdoc
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for jsdoc
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## markdown parser healthcheck
  - OK: markdown parser found.
  - WARNING: No `highlights.scm` query found for markdown
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `locals.scm` query found for markdown
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for markdown
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## julia parser healthcheck
  - OK: julia parser found.
  - WARNING: No `highlights.scm` query found for julia
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `locals.scm` query found for julia
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for julia
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## html parser healthcheck
  - OK: html parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for html
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## typescript parser healthcheck
  - OK: typescript parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.

## swift parser healthcheck
  - OK: swift parser found.
  - WARNING: No `highlights.scm` query found for swift
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `locals.scm` query found for swift
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for swift
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## query parser healthcheck
  - OK: query parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for query
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## cpp parser healthcheck
  - OK: cpp parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.

## ruby parser healthcheck
  - OK: ruby parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for ruby
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## vue parser healthcheck
  - OK: vue parser found.
  - WARNING: No `highlights.scm` query found for vue
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `locals.scm` query found for vue
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for vue
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## scala parser healthcheck
  - OK: scala parser found.
  - WARNING: No `highlights.scm` query found for scala
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `locals.scm` query found for scala
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for scala
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## tsx parser healthcheck
  - OK: tsx parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.

## rust parser healthcheck
  - OK: rust parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.

## bash parser healthcheck
  - OK: bash parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for bash
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## c_sharp parser healthcheck
  - OK: c_sharp parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for c_sharp
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - OK: `textobjects.scm` found.

## rst parser healthcheck
  - OK: rst parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.

## css parser healthcheck
  - OK: css parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for css
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for css
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## php parser healthcheck
  - OK: php parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for php
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## javascript parser healthcheck
  - OK: javascript parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.

## haskell parser healthcheck
  - OK: haskell parser found.
  - WARNING: No `highlights.scm` query found for haskell
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `locals.scm` query found for haskell
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for haskell
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## toml parser healthcheck
  - OK: toml parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for toml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## regex parser healthcheck
  - OK: regex parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for regex
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for regex
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
</code>
</details>

**Output of `nvim --version`**

<details>

```
NVIM v0.5.0-nightly-26-g948e625e1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200902-10064-1jxapw8/build/config -I/tmp/neovim-20200902-10064-1jxapw8/src -I/usr/local/include -I/tmp/neovim-20200902-10064-1jxapw8/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200902-10064-1jxapw8/build/src/nvim/auto -I/tmp/neovim-20200902-10064-1jxapw8/build/include
Compiled by constantine@naboo.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-948e625/share/nvim"

Run :checkhealth for more info
```

</details>

**Output of `--startuptime`**

<details>

```
times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.008  000.008: --- NVIM STARTING ---
000.812  000.804: locale set
001.480  000.668: inits 1
001.505  000.025: window checked
001.508  000.003: parsing arguments
001.726  000.217: expanding arguments
001.794  000.068: inits 2
002.365  000.571: init highlight
002.367  000.001: waiting for UI
004.240  001.873: done waiting for UI
004.298  000.058: initialized screen early for UI
006.937  000.258  000.258: sourcing /Users/constantine/.cache/dein/repos/github.com/Shougo/dein.vim/autoload/dein.vim
007.929  000.660  000.660: sourcing /Users/constantine/.cache/dein/repos/github.com/Shougo/dein.vim/autoload/dein/util.vim
008.798  000.042  000.042: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/ftoff.vim
048.619  000.303  000.303: sourcing /Users/constantine/.cache/dein/repos/github.com/Shougo/dein.vim/autoload/dein/autoload.vim
049.576  000.416  000.416: sourcing /Users/constantine/.cache/dein/repos/github.com/Shougo/dein.vim/autoload/dein/types/git.vim
049.850  000.911  000.495: sourcing /Users/constantine/.cache/dein/repos/github.com/Shougo/dein.vim/autoload/dein/parse.vim
053.261  048.665  046.490: sourcing /Users/constantine/.config/nvim/init.minimal.vim
053.270  000.307: sourcing vimrc file(s)
053.473  000.064  000.064: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/ftplugin.vim
088.716  000.099  000.099: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/indent.vim
125.455  000.379  000.379: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/syntax/syncolor.vim
160.618  035.712  035.333: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/syntax/synload.vim
207.664  046.834  046.834: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/filetype.vim
244.049  119.341  036.795: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/syntax/syntax.vim
**1638.328  1393.519  1393.519: sourcing /Users/constantine/.cache/dein/repos/github.com/vigoux/nvim-treesitter_fix-perf/plugin/nvim-treesitter.vim**
1639.881  000.479  000.479: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/plugin/gzip.vim
1639.981  000.023  000.023: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/plugin/health.vim
1640.204  000.157  000.157: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/plugin/man.vim
1642.305  000.335  000.335: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/pack/dist/opt/matchit/plugin/matchit.vim
1642.431  002.157  001.822: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/plugin/matchit.vim
1642.732  000.227  000.227: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/plugin/matchparen.vim
1643.463  000.654  000.654: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/plugin/netrwPlugin.vim
1644.344  000.344  000.344: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/autoload/remote/host.vim
1644.973  000.276  000.276: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/autoload/remote/define.vim
1645.104  001.277  000.656: sourcing /Users/constantine/.local/share/nvim/rplugin.vim
1645.115  001.551  000.274: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/plugin/rplugin.vim
1645.360  000.133  000.133: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/plugin/shada.vim
1645.487  000.040  000.040: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/plugin/spellfile.vim
1645.764  000.196  000.196: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/plugin/tarPlugin.vim
1646.039  000.187  000.187: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/plugin/tohtml.vim
1646.154  000.035  000.035: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/plugin/tutor.vim
1646.478  000.241  000.241: sourcing /usr/local/Cellar/neovim/HEAD-948e625/share/nvim/runtime/plugin/zipPlugin.vim
1680.921  108.547: loading plugins
1681.210  000.289: loading packages
1681.428  000.218: loading after plugins
1681.449  000.021: inits 3
1685.668  004.219: reading ShaDa
1687.883  002.215: opening buffers
1687.951  000.068: BufEnter autocommands
1687.957  000.005: editing files in windows
1688.129  000.173: VimEnter autocommands
1688.134  000.005: UIEnter autocommands
1688.136  000.002: before starting main loop
1689.124  000.989: first screen update
1689.127  000.003: --- NVIM STARTED ---
```

</details>

**`vimrc`**
<details>

```
set runtimepath+=/Users/constantine/.cache/dein/repos/github.com/Shougo/dein.vim
set rtp+=$(brew\ --prefix)/opt/fzf
call dein#begin(expand('~/.cache/dein'))

call dein#add('https://github.com/vigoux/nvim-treesitter', {'merged': 0, 'rev': 'fix-perf'})
call dein#end()
if dein#check_install()
    call dein#install()
endif

lua <<EOF
require'nvim-treesitter.configs'.setup {
    highlight = {
      enable = true,                    -- false will disable the whole extension
    },
}
EOF
```

</details>

**Comment by vigoux** [comment]
Hi ! And thanks for reporting !

I am not a dein expert but it looks like you are not using the correct version of the plugin.
Can you try using `https://github.com/nvim-treesitter/nvim-treesitter` and `master` and tell us if the problem is still there ?

**Comment by kontheocharis** [comment]
Thanks, not sure how I missed that. Unfortunately, the problem persists exactly as before.

**Comment by vigoux** [comment]
This is a quite tricky problem we try to work on for some time.
Can you reach out to us on the Zulip channel to discuss that there ?
The relevant stream is [this one](https://nvim-treesitter.zulipchat.com/#narrow/stream/252274-plugin.2Fnvim-treesitter).

**Comment by kontheocharis** [comment]
I posted a message on the Zulip channel (/Performance). Also, it seems that using `vim-plug` instead of `dein.vim` solves the problem. Still not sure why.

**Comment by vigoux** [comment]
This needs doecumentation hehe
