### ISSUE TITLE
Extending query files are applied for every query types

### ISSUE THREAD

**Issue by kyazdani42** [nvim-treesitter/nvim-treesitter#378]
in `query.lua`, `base_language_map` and `query_extensions` are loaded for every type of queries (highlights, locals...), and i think it could be invalid in some cases (for instance, the `javascript/jsx.scm` file is highlight specific, but is loaded for the locals).
I don't have too much time to invest lately, so i put this here in case someone wants to tackle that.

**Comment by vigoux** [comment]
This is actually a bug we need to work on, how about splitting those files and use something like `queries/jsx/*.scm`instead ?

**Comment by kyazdani42** [comment]
mhhh that could actually be a good solution ! we then could provide folds for jsx also and not just highlighting
