### ISSUE TITLE
parsers compilation error when using zig as compiler at windows platform

### ISSUE THREAD

**Issue by jjamesllong** [nvim-treesitter/nvim-treesitter#3780]
### Describe the bug

after updating treesitter to the latest version, I met some prolems as #3092 mentioned. I uninstalled treesitter and reinstalled it, but parsers I want to install always failed to compile to a .so file. Errors output below: 
```
nvim-treesitter[rust]: Error during compilation
warning(compilation): failed to write cache manifest when compiling 'src/parser.c': Unexpected
src/scanner.c:1:1: error: unable to build C object: InvalidFormat
```
I reproduced this bug named *InvalidFormat*, but another error relative to cache exists.
When I converted to a console environment which using msvc as c compiler, everything was ok. So I suspect this is a bug when using zig as compiler.

### To Reproduce

As described in the description section

### Expected behavior

may compilation should be normal when using zig as c compiler.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v18.0.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `zig` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: info: Usage: zig [command] [options]
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - help           ✓ . . . .
  - lua            ✓ ✓ ✓ ✓ ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - vim            ✓ ✓ ✓ . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.0-1210-gd367ed9b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az177-603

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
```

**Comment by clason** [comment]
Curiously, `zig` works on this parser when compiling manually (even on Windows); it must have something to do with being called from `luv.spawn` -- whether that's an issue with Zig or with Luv on Windows is anyone's guess.

I recommend not using `zig` as a compiler yet (it's still work in progress, after all, especially the `cc` mode) and installing one of the other supported compilers like `gcc` or `clang`.

**Comment by gsuuon** [comment]
Updating zig from 0.10 to 0.10.1 fixed this for me
