### ISSUE TITLE
[highlights] Parameters' highlighting not only in parameter list but in function's body either

### ISSUE THREAD

**Issue by hacker-biba** [nvim-treesitter/nvim-treesitter#3785]
In PyCharm when I set parameters' color:
![image](https://user-images.githubusercontent.com/81816655/200555462-149a7bfa-ae23-4f6e-a799-dfcdb52c91f7.png)

I get highlighting like this ("event" is highlighted everywhere throughout the function):
![image](https://user-images.githubusercontent.com/81816655/200555637-ce95009e-ef22-4644-9605-79ea97956e0c.png)

But with Treesitter in Neovim only parameter list is highlighted:
![image](https://user-images.githubusercontent.com/81816655/200555956-cf22413b-d250-4fcc-953b-f99665e8391d.png)

I set colors using vim-plug in init.vim file like this:
![image](https://user-images.githubusercontent.com/81816655/200572862-9b95528e-4e31-48a0-8eab-a64beb66eece.png)

How to make Treesitter to highlight variables that come from parameter list just like PyCharm does?

**Comment by ObserverOfTime** [comment]
See #81
