### ISSUE TITLE
Keep geting the same error every time openig neovim

### ISSUE THREAD

**Issue by ryannewcomer** [nvim-treesitter/nvim-treesitter#3797]
### Describe the bug

when I run nvim on Powershell on window, it says this: 

![image](https://user-images.githubusercontent.com/88273136/201414526-fd48703f-5daa-448d-930c-7dfb2ac83127.png)

then run :TSUpdate and get this:

![image](https://user-images.githubusercontent.com/88273136/201424383-b8ffea98-6d36-45f7-8b96-25ca95a75134.png)

### To Reproduce

1. run powershell
2. open nvim
3. see error
4. fix it with :TSUpdate
5. see the second error

### Expected behavior

do not have this error anymore

### Output of `:checkhealth nvim-treesitter`

```markdown
- WARNING: 'tree-sitter' executable not found (parser generator, only need for :TSInstallFromGrammar, not required for :TSInstall)
- OK: 'node' found v16.16.0 (only needed for :TSInstallFromGrammar)
- OK: git executable found
- OK: GCC executable found version: gcc
```

### Output of `nvim --version`

```text
NVIM v0.8.0-1210-gd367ed9b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az177-603

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

### Additional context

I have run the ':TSInstallFromGrammar' and it say E471: Argument required
then I run:TSInstall and get the same error.
what to do?

p.s. this is the result of checkhealth nvim-treesitter

![image](https://user-images.githubusercontent.com/88273136/201423355-19d81936-1e91-4cc5-ad42-4e48058c5aa4.png)

**Comment by ryannewcomer** [comment]
Ok, I fix it. it turn out that I have install to much compiler on my computer so it can't run it.

Thanks so much!!

**Comment by xaviernogueira** [comment]
@ryannewcomer can you be more specific? Which compiler did you install. I have the same problem.

**Comment by ryannewcomer** [comment]
> Sorry,but it must be an old problem, you may have to install GCC or something similar.

**Comment by ryannewcomer** [comment]
It should be some thing like gcc, my config had change a lot in these 10 months. You can try to install gcc first
