### ISSUE TITLE
Dart folds query

### ISSUE THREAD

**Issue by victorlacorte** [nvim-treesitter/nvim-treesitter#3844]
I've noticed that Dart folding capabilities are limited since we currently don't have a `queries/dart/folds.scm` file and are falling back to `queries/dart/locals.scm` `@scope` captures. Could we add such file to improve folding or is it intentionally missing?

**Comment by clason** [comment]
Of course; all queries are community-contributed (and maintained). PR welcome (but ping the listed maintainer to discuss the specifics).
