### ISSUE TITLE
Cannot change highlights on markdown files

### ISSUE THREAD

**Issue by nikinbaidar** [nvim-treesitter/nvim-treesitter#3845]
### Describe the bug

I have installed the markdown parser, and I've got two issues:

1. I cannot change explicitly define a highlights group for markdown code delimiters. 
2. Plus, `set conceallevel=<anything>` seems to hide the start and end of code blocks too.  

### To Reproduce

1. Run `TSInstall markdown`
2. Enable highlights
3. For the first issue run `hi markdownCodeDelimiter guifg=red ctermfg=red`.
4. For the second issue run `set conceallevel=1`.

### Expected behavior

 `hi markdownCodeDelimiter guifg=red` seems to have no effect. I'd expect it change the color of "```" characters to red. 

`set conceallevel=1` would normally only conceal the bold and italic delimiters. But with TS enabled it also hides the start and end of the code blocks.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v19.1.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - html           ✓ ✓ ✓ ✓ ✓
  - java           ✓ ✓ . ✓ ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - markdown       ✓ . ✓ . ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - css            ✓ . ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

Both these issues are resolved as I run `TSDisable highlight`, but of course the beautiful highlighting is gone too.

The first issue also goes away if I change the highlights group of `Delimeter`, which I dont' want to change. Can someone point to some resources that could help me resolve this.

**Comment by clason** [comment]
You need to also install the `markdown_inline` parser; both are needed for full Markdown support.

**Comment by nikinbaidar** [comment]
Installing `markdown_inline` solves neither of those problems.

**Comment by clason** [comment]
> hi markdownCodeDelimiter guifg=red ctermfg=red.

That highlight group will have no effect with treesitter highlighting, which only uses `@foo.bar` highlight groups. Check the query file or the playground for what each capture refers to.

(Spoiler: It's `@punctuation.delimiter`, and concealed by default.)

**Comment by nikinbaidar** [comment]
> If you want to override a capture (like the conceal), you need to put a corresponding query (with `; extends`) in your personal `queries` directory.

I've no idea how to do that. 

Nevertheless, I figured [this](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/markdown/highlights.scm#L61) block of code is what is causing the conceal issue I'm talking about. I deleted that block to fix the issue but couldn't figure a way to implement this through my configs.
