### ISSUE TITLE
Failed to update in lua setup of nvim

### ISSUE THREAD

**Issue by lobanov4real** [nvim-treesitter/nvim-treesitter#3850]
### Describe the bug

I installed nvim-treesitter/nvim-treesitter by packer:  
  

> use({  
> 		"nvim-treesitter/nvim-treesitter",   
> 		run = function()   
> 			require("nvim-treesitter.install").update({ with_sync = true })   
> 		end,   
> 	})  

  
Then I try to update my plugins I get error from nvim-treesitter plugin: ``✗ Failed to update nvim-treesitter\nvim-treesitter``

### To Reproduce

1. Open plugins-setup.lua in nvim
2. Save file :w
3. All installed plugins are updated except nvim-treesitter
4. Get error: Failed to update nvim-treesitter\nvim-treesitter

### Expected behavior

1. Open plugins-setup.lua in nvim
2. Save file :w
3. Get : Everything already up to date!

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v19.1.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: gcc (GCC) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - dockerfile     ✓ . . . ✓
  - help           ✓ . . . .
  - bash           ✓ ✓ ✓ . ✓
  - css            ✓ . ✓ ✓ ✓
  - gitignore      ✓ . . . .
  - graphql        ✓ . . ✓ ✓
  - json           ✓ ✓ ✓ ✓ .
  - javascript     ✓ ✓ ✓ ✓ ✓
  - markdown       ✓ . ✓ . ✓
  - toml           ✓ ✓ ✓ ✓ ✓
  - yaml           ✓ ✓ ✓ ✓ ✓
  - html           ✓ ✓ ✓ ✓ ✓
  - gitattributes  ✓ . . . ✓
  - tsx            ✓ ✓ ✓ ✓ ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - vim            ✓ ✓ ✓ . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az30-11

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

### Additional context

Windows 11 (22H2, OS build 22621.819).
PowerShell 7.3.0

**Comment by clason** [comment]
That was probably my fault (force-push to master by accident). Just remove the local repository and clone again, or do `git pull -f` manually.

**Comment by lobanov4real** [comment]
I reinstalled plugin with:  
``use({ "nvim-treesitter/nvim-treesitter", run = ":TSUpdate" })`` 
and now all plugins up to date.
