### ISSUE TITLE
I can make tree-sitter install

### ISSUE THREAD

**Issue by lautar0pp** [nvim-treesitter/nvim-treesitter#3859]
### Describe the bug

I try to install treesitter but when I re open vim to install this happen

![error](https://user-images.githubusercontent.com/32388725/203829238-c9517d67-acf7-407c-b6ba-220e09674c33.png)

### To Reproduce

.

### Output of `:checkhealth nvim-treesitter`

```markdown
https://ibb.co/N2PzPjn
```

### Output of `nvim --version`

```text
nvim --version                                                                                                                                                             ok  17m 15s
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld
```

**Comment by clason** [comment]
As the error message says, you need to install a C compiler (including system headers -- whatever the "standard developer tools" are for your platform.
