### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Joarell** [nvim-treesitter/nvim-treesitter#3865]
### Describe the bug

Hi there!
Firstly, thank you guys for this amazing project for Neovim!
You are awesome!
However, I don't know what happened, but I can't install/update treesitter plugins anymore.

### To Reproduce

:PackerInstall

### Expected behavior

Treesitter installed

### Output of `:checkhealth nvim-treesitter`

```markdown
N/A
```

### Output of `nvim --version`

```text
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

![treesitter](https://user-images.githubusercontent.com/42722369/203871826-b52a1b40-aeca-4e5a-abdd-8230e22a1847.png)

**Comment by clason** [comment]
playground hasn't had any updates for a week, so the problem must be on your end.

Try removing all plugins and reinstalling.

**Comment by Joarell** [comment]
Thank you for you prompt reply.
I'll try to figure it out what happening following your tip.
Have a nice day/night!
