### ISSUE TITLE
I need to turn on highlighting manually?

### ISSUE THREAD

**Issue by xuyastc** [nvim-treesitter/nvim-treesitter#3888]
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/37319368/204296856-d6c60cb6-5fd3-414c-b0b0-1bf27c105e73.png">

**I need to do :TSToggle highlight every time I reopen the file**

**Comment by theHamsta** [comment]
Do you have this in your config? Do you have parses installed with `:TSInstall <language>`?

```lua

require'nvim-treesitter.configs'.setup {
  highlight = {
    -- `false` will disable the whole extension
    enable = true,
  }
}
````

**Comment by clason** [comment]
First you should fix those errors your screenshot shows. Then we can talk about whether highlighting still doesn't work.

(No reproduction steps and no minimal config means we can't really help you other than link to #3092.)

**Comment by xuyastc** [comment]
> Do you have this in your config? Do you have parses installed with `:TSInstall <language>`?
> 
> ```lua
> require'nvim-treesitter.configs'.setup {
>   highlight = {
>     -- `false` will disable the whole extension
>     enable = true,
>   }
> }
> ```

yes，I'm all set
