### ISSUE TITLE
Consider tagging commits with breaking changes to match nvim versioning

### ISSUE THREAD

**Issue by savq** [nvim-treesitter/nvim-treesitter#3915]
Currently nvim-treesitter has a rolling-release model, where you have to stay up-to-date on the breaking changes of the repo and the minimum Neovim version required.

I'd like to suggest adding tags to the commits where these changes happen, so that it's easier to use the specific version  that matches the Neovim version one's using (without having to `git log` and find the hash of the commit where the changes happen).

Unlike version branches, which sometimes come with the expectation of backporting changes, this would be strictly to annotate versions with no guarantees whatsoever. The tags would be `nvim-0.7`, `nvim-0.8`, etc.

Breaking changes already have to be listed in #2293, so I don't believe this adds any additional maintenance cost.

**Comment by clason** [comment]
I'm sorry, but treesitter support in general and nvim-treesitter in particular is still experimental. We're in no state yet to consider supporting multiple versions. Dropping support for old versions (after a grace period, which we admittedly could handle better) is deliberate.

**Comment by Ttibsi** [comment]
Could git tags be added before you introduce a breaking change, for older versions of nvim to be sent to that tag instead

**Comment by theHamsta** [comment]
Tags were indeed planned. But I was just forgetting them. We wanted to tag on the day of each stable release. Breaking changes happen only after the release of a stable version so we can tag retroactively.

**Comment by savq** [comment]
> Dropping support for old versions ... is deliberate.

Yes, I understand that old versions are not supported, but sometimes you have to work with an older version of neovim, and in those cases there's no easy way to use nvim-treesitter (besides looking for a commit that works and copying the hash).

> We wanted to tag on the day of each stable release. Breaking changes happen only after the release of a stable version so we can tag retroactively.

That would be ideal.

**Comment by theHamsta** [comment]
Ok, I've set `v0.7.0` to the commit before https://github.com/nvim-treesitter/nvim-treesitter/pull/3656/commits/28fb81bddf41ebc530ea80e64046f9581649f728 . `v0.8.0`/`v0.8.1` to the current commit. Apparently there is not too much that happened between the releases: https://github.com/neovim/neovim/releases/tag/v0.8.1. `v0.8.0` does not `@spell` but the additional captures should be just silently ignore. Please let me know if there are any problems with the chosen revisions. I will tag the next release at the same time when nvim `v0.9.0` comes out.

**Comment by theHamsta** [comment]
fixing the `v0.8.0` tag...

**Comment by savq** [comment]
Great! Thank you @theHamsta
