### ISSUE TITLE
query: invalid node type at position

### ISSUE THREAD

**Issue by hrqmonteiro** [nvim-treesitter/nvim-treesitter#3934]
### Describe the bug

![Screenshot from 2022-12-05 20-27-51](https://user-images.githubusercontent.com/17055027/205766379-89b4f670-98de-46c8-81db-698874d85a1d.png)

Showing this everywhere

### To Reproduce

Just open any file, any extension, that i get this at some point somewhere.

### Expected behavior

Not to appeart this?

### Output of `:checkhealth nvim-treesitter`

```markdown
local options = {
  background = "dark",
  backup = false,
  clipboard = "unnamedplus",
  cmdheight = 0,
  completeopt = { "menuone", "noselect" },
  conceallevel = 0,
  expandtab = true,
  fileencoding = "utf-8",
  hlsearch = true,
  ignorecase = true,
  laststatus = 3,
  mouse = "nv",
  number = true,
  numberwidth = 2,
  pumheight = 10,
  relativenumber = true,
  shiftwidth = 2,
  showmode = false,
  showtabline = 0,
  signcolumn = "yes",
  smartcase = true,
  smartindent = true,
  splitbelow = true,
  splitright = true,
  swapfile = false,
  tabstop = 2,
  termguicolors = true,
  timeoutlen = 1000,
  title = true,
  undofile = false,
  updatetime = 200,
  wrap = true,
  writebackup = false,
}

for k,v in pairs(options) do
  vim.opt[k] = v
end

vim.cmd 'colorscheme solarized'
```

### Output of `nvim --version`

```text
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by linuxbrew@43b3775c8372

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/linuxbrew/.linuxbrew/Cellar/neovim/0.8.1/share/nvim"

Run :checkhealth for more info
```

**Comment by figsoda** [comment]
Have you tried the possible solutions listed in https://github.com/nvim-treesitter/nvim-treesitter/issues/3092?

**Comment by yofriadi** [comment]
got the same error https://github.com/folke/noice.nvim/issues/260

tried #3092 but still no works

**Comment by hagnerd** [comment]
By the way, for future reference for anyone else who runs into this, when this error happened for me it was because neovim 0.8+ includes built in parsers for vim and lua that were causing errors (not quite sure why). Deleting those language files and uninstalling/re-installling the treesitter parsers for vim and lua fixed this.

**Comment by navaneeth-dev** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/issues/3092 Not working on windows

**Comment by navaneeth-dev** [comment]
Ok on windows i had to delete 4 dlls at `C:\Program Files\Neovim\lib\nvim\parser` and now it works

**Comment by hongyuanjia** [comment]
> Ok on windows i had to delete 4 dlls at C:\Program Files\Neovim\lib\nvim\parser and now it works

This works for me, too.

**Comment by TamaMcGlinn** [comment]
Had this problem after updating from NeoVim 0.8 to 0.10, fixed by doing `:TSUpdate python` in my case (it happened on python files)
