### ISSUE TITLE
string.escape not work in java

### ISSUE THREAD

**Issue by codebysandwich** [nvim-treesitter/nvim-treesitter#3942]
### Describe the highlighting problem

<img width="513" alt="image" src="https://user-images.githubusercontent.com/32191093/206101570-7d0790ba-0bc1-4e8f-b2d7-c706ce67c7b9.png">

### Example snippet that causes the problem

hi @string.escape xxx links to SpecialChar

### Tree-sitter parsing result

block_comment [0, 0] - [6, 3]
package_declaration [8, 0] - [8, 17]
  scoped_identifier [8, 8] - [8, 16]
    scope: identifier [8, 8] - [8, 11]
    name: identifier [8, 12] - [8, 16]
block_comment [10, 0] - [12, 3]
class_declaration [13, 0] - [18, 1]
  modifiers [13, 0] - [13, 6]
  name: identifier [13, 13] - [13, 23]
  body: class_body [13, 24] - [18, 1]
    method_declaration [14, 1] - [17, 2]
      modifiers [14, 1] - [14, 14]
      type: void_type [14, 15] - [14, 19]
      name: identifier [14, 20] - [14, 24]
      parameters: formal_parameters [14, 24] - [14, 39]
        formal_parameter [14, 25] - [14, 38]
          type: array_type [14, 25] - [14, 33]
            element: type_identifier [14, 25] - [14, 31]
            dimensions: dimensions [14, 31] - [14, 33]
          name: identifier [14, 34] - [14, 38]
      body: block [14, 40] - [17, 2]
        local_variable_declaration [15, 2] - [15, 31]
          type: type_identifier [15, 2] - [15, 8]
          declarator: variable_declarator [15, 9] - [15, 30]
            name: identifier [15, 9] - [15, 10]
            value: string_literal [15, 13] - [15, 30]
        expression_statement [16, 2] - [16, 24]
          method_invocation [16, 2] - [16, 23]
            object: field_access [16, 2] - [16, 12]
              object: identifier [16, 2] - [16, 8]
              field: identifier [16, 9] - [16, 12]
            name: identifier [16, 13] - [16, 20]
            arguments: argument_list [16, 20] - [16, 23]
              identifier [16, 21] - [16, 22]

### Example screenshot

<img width="774" alt="image" src="https://user-images.githubusercontent.com/32191093/206102509-fdceef51-6f9a-4ab3-b946-cb11fbc252f3.png">

### Expected behavior

<img width="443" alt="image" src="https://user-images.githubusercontent.com/32191093/206101935-b0e54cf9-fe47-4b6a-9947-45afa7464e0f.png">

in python work well

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.15.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 12.0.0 (clang-1200.0.32.29)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "19.6.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64"
}

## Parser/Features H L F I J
  - cpp            ✓ ✓ ✓ ✓ ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - help           ✓ . . . ✓
  - java           ✓ ✓ . ✓ ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - go             ✓ ✓ ✓ ✓ ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - vim            ✓ ✓ ✓ . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@iMac-Pro

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.8.0/share/nvim"

Run :checkhealth for more info
```

### Additional context

I change @string.escape color work in python however java use the whole string color without string.escape

**Comment by stsewd** [comment]
Hi, this is a limitation of the java parser, they don't have a node for escaped characters

https://github.com/tree-sitter/tree-sitter-java/blob/09d650def6cdf7f479f4b78f595e9ef5b58ce31e/grammar.js#L157

In order to support those here, the java parser need to add them as a separate node.

**Comment by codebysandwich** [comment]
@stsewd Thanks your answer!
I'm not good at java.parser, whether existed solution about fixing this issue? i searched in `tree-sitter-java` no answer about this :(, or waiting for java parser add string.escape as a separate node?
I will do more research about java parser.

**Comment by amaanq** [comment]
is this still an issue? I can submit a pr to java to add this feature, but are escaped strings supported/meant to be differentiated in Java to begin with? never used it before.

**Comment by codebysandwich** [comment]
> is this still an issue? I can submit a pr to java to add this feature, but are escaped strings supported/meant to be differentiated in Java to begin with? never used it before.

yeah, this is still an issue :(

**Comment by amaanq** [comment]
> > is this still an issue? I can submit a pr to java to add this feature, but are escaped strings supported/meant to be differentiated in Java to begin with? never used it before.
> 
> yeah, this is still an issue :(

https://github.com/tree-sitter/tree-sitter-java/pull/137

**Comment by codebysandwich** [comment]
@amaanq 
I update `nvim-treesitter` and update tree-sitter-java today. and checked hi @string.escape links to SpecialChar in java worked, however string.escape not  identified in java file :( 
Thanks your pr in tree-sitter-java too.
