### ISSUE TITLE
TSInstall python fails with Unsupported architecture error

### ISSUE THREAD

**Issue by forrestfwilliams** [nvim-treesitter/nvim-treesitter#3945]
### Describe the bug

When working on a fresh install of `neovim` and `nvim-treesitter` on an ARM64 M1 MacBook, I am trying to install the python parser using `:TSInstall python` I receive the a long error message at the compile step that begins:

```
nvim-treesitter[python]: Error during compilation
In file included from src/parser.c:1:
In file included from ./src/tree_sitter/parser.h:9:
In file included from /Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include/stdint.h:52:
In file included from /Library/Developer/CommandLineTools/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/stdint.h:52:
In file included from /Library/Developer/CommandLineTools/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/sys/_types.h:32:
/Library/Developer/CommandLineTools/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/sys/cdefs.h:655:2: error: Unsupported
architecture
#error Unsupported architecture
```

I'm guessing this error might be related to the ARM64 architecture of my computer, but I don't know how to resolve this. Any help would be appreciated!

I worked through the troubleshooting section and found that I had some `invalid node type at position` errors because I had two parser runtime paths (`~/.local/share/nvim/site/pack/packer/start/nvim-treesitter/parser`, and `/opt/homebrew/Cellar/neovim/0.8.1/lib/nvim/parser`). However, when I remove the second path the original error still persists.  `:TSUpdate` runs without issue.

### To Reproduce

1. Install `nvim` using home-brew
2. Install `nvim-treesitter` using `packer`
3. In `nvim`, run `:TSUpdate`
4. In `nvim`, run `:TSInstall python`

### Expected behavior

`:TSInstall python` should compile/complete without errors.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v19.2.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 14.0.0 (clang-1400.0.29.102)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "arm64",
  release = "21.6.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000"
}

## Parser/Features H L F I J

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.1/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
Make sure you are using a native M1 terminal (and build tools), not a Rosetta Terminal.app.

> /Library/Developer/CommandLineTools/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk

That looks very wrong. You could try removing the `CommandLineTools` directory and reinstalling. Also make sure that you don't have any outdated `DEPLOYMENT_TARGET` environment variables set.

(I just reinstalled the Python parser on my M1 MBA, so this definitely works.)

**Comment by forrestfwilliams** [comment]
Thanks, I'll try this!

**Comment by forrestfwilliams** [comment]
Reinstalling `CommandLineTools` fixed the issue, thanks!
