### ISSUE TITLE
No highlighting in command window

### ISSUE THREAD

**Issue by musjj** [nvim-treesitter/nvim-treesitter#3961]
### Describe the bug

No vim syntax highlighting in the command window.

### To Reproduce

1. Enter `q:` to open the command window
2. No syntax highlighting is visible
3. Deactivate treesitter's plugin and restart neovim
4. Open the command window again
5. Syntax highlighting is visible

### Expected behavior

Vimscript's syntax highlighting should also be visible in command window buffers.

### Output of `:checkhealth nvim-treesitter`

```markdown
Installation ~
- OK `tree-sitter` found 0.20.6 (ccd6bf554d922596ce905730d98a77af368bba5c) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v18.7.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: bash: cannot set terminal process group (-1): Inappropriate ioctl for device
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.19045",
  sysname = "Windows_NT",
  version = "Windows 10 Enterprise"
} ~

Parser/Features H L F I J
  - typescript     ✓ ✓ ✓ ✓ ✓
  - json           ✓ ✓ ✓ ✓ .
  - vim            ✓ ✓ ✓ . ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - html           ✓ ✓ ✓ ✓ ✓
  - css            ✓ . ✓ ✓ ✓
  - go             ✓ ✓ ✓ ✓ ✓
  - help           ✓ . . . ✓
  - norg           . . . . .
  - yaml           ✓ ✓ ✓ ✓ ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - rust           ✓ ✓ ✓ ✓ ✓
  - bash           ✓ ✓ ✓ . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
v0.9.0-dev-484+gb5edea655
```

**Comment by theHamsta** [comment]
I think this should be filed against github.com/neovim/neovim. There `:set syntax=off` is currently set.

**Comment by comfortablynick** [comment]
I noticed this issue too. Is there a fix?

**Comment by clason** [comment]
https://github.com/neovim/neovim/pull/21358

**Comment by clason** [comment]
> I think this should be filed against github.com/neovim/neovim. There `:set syntax=off` is currently set.

I don't think that's correct. I get syntax highlighting just fine with manual `vim.treesitter.start()` in Neovim (without nvim-treesitter) and with legacy syntax (`: set syn` shows `syntax=vim`). The issue is with nvim-treesitter not recognizing the command window as a buffer to attach to.

**Comment by clason** [comment]
It works if you manually start treesitter highlighting with  `vim.treesitter.start()` but not with that command put in a `ftplugin`. Seems like the command window doesn't trigger autocommands or filetype plugins, but somehow the `syntax off` still goes through.

**Comment by comfortablynick** [comment]
> It works if you manually start treesitter highlighting with `vim.treesitter.start()` 
I tried executing this and it doesn't restore command window highlighting for me.

**Comment by musjj** [comment]
@theHamsta 
> I think this should be filed against github.com/neovim/neovim. There `:set syntax=off` is currently set.

I thought the `syntax` option is only related to the regex highlighting and not treesitter? 
I tried doing this:
```lua
vim.api.nvim_create_autocmd("CmdwinEnter", {
  callback = function(opts)
    vim.cmd.syntax("on")
  end,
})
```
But for some reason, the resulting highlighting looks wrong compared to `nvim --clean`. It also looks nothing like vimscript buffers highlighted with treesitter.

@clason 
I tried to set it via autocmd:
```lua
vim.api.nvim_create_autocmd("CmdwinEnter", {
  callback = function(opts)
    vim.treesitter.start(opts.buf, "vim")
  end,
})
```
But it doesn't work. It doesn't work even if you schedule it:
```lua
vim.api.nvim_create_autocmd("CmdwinEnter", {
  callback = function(opts)
    vim.schedule(function() vim.treesitter.start(opts.buf, "vim") end)
  end,
})
```
I also tried to manually run it in the command bar while the command window is open, but it doesn't work either.
Can you give the exact code you tried?

**Comment by clason** [comment]
* `q:`
* `lua vim.treesitter.start()`

**Comment by comfortablynick** [comment]
Has anyone found out what caused syntax highlighting in the cmdwin to break? I can't get any workaround to restore the highlighting unless I run with `--clean`.

**Comment by WieeRd** [comment]
I also just noticed this issue, and came up with this simple fix with config:
```lua
require("nvim-treesitter.configs").setup({
  highlight = {
    enable = true,
    disable = function(lang, buf)
      if lang == "vim" then
        local bufname = vim.api.nvim_buf_get_name(buf)
        return string.match(bufname, "%[Command Line%]")
      else
        return false
      end
    end,
    additional_vim_regex_highlighting = false,
  },
})
```

Basically, it disables TS highlights for `q:` window but not for the normal `.vim` buffers.  
This brings back regex based highlights inside command line window.  
It's more of a workaround than a solution, but this is gonna be my quick fix until this issue gets solved.

**Comment by WieeRd** [comment]
Also, if there is a better way of detecting command line windows, please let me know.  
The only way I could think of was searching for `[Command Line]` in buffer name using `string.match()`.  
(It looks like command line buffers are named `{pwd}/[Command Line]`)

**Comment by comfortablynick** [comment]
Thanks for that workaround. It looks like disabling TS highlights is the best option for now. I’m still curious why it stopped working.

**Comment by AstrickHarren** [comment]
In my case, I found out that TS is actively highlighting everything to no highlight. Sounds confusing, but if I disable TS, the syntax highlight comes back with neovim native highlights. Moreover, if I first change the filetype to something else, say `python`, and change back to `vim`, TS works. 

I have been able to generate the TS highlighting with the following workaround: 
```lua 

-- fix ts no highlight in cmd win
-- see https://github.com/nvim-treesitter/nvim-treesitter/issues/3961
vim.api.nvim_create_autocmd("CmdWinEnter", {
    callback = function()
        vim.cmd('setfiletype python')
        vim.schedule(function()
            vim.cmd('setfiletype vim')
        end)
    end,
    group = vim.api.nvim_create_augroup('_fix_ts_cmdwin', { clear = false }),
})
```

Pretty ugly, but it works for me :rofl:

**Comment by clason** [comment]
This is a neovim issue: https://github.com/neovim/neovim/issues/26346
