### ISSUE TITLE
library not found for -lc++

### ISSUE THREAD

**Issue by Coop8** [nvim-treesitter/nvim-treesitter#3963]
### Describe the bug

I am trying to install clangd on mac and keep getting this error when trying to compile. 
`nvim-treesitter[cpp]: Error during compilation
ld: library not found for -lc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)`
I have tried everything I can find online and nothing seems to be working. Every other parser, eg. Lua, seems to work fine.

### To Reproduce

1. Install Neovim from homebrew
2. Install nvim-treesitter and its dependencies
3. Get the following error when trying to open a .c, .h, or .cpp file

### Expected behavior

Compiles with no issues

### Output of `:checkhealth nvim-treesitter`

```markdown
1 nvim-treesitter: require("nvim-treesitter.health").check()
  2 ========================================================================
  3 ## Installation
  4   - OK: `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
  5   - OK: `node` found v19.2.0 (only needed for :TSInstallFromGrammar)
  6   - OK: `git` executable found.
  7   - OK: `/Library/Developer/CommandLineTools/usr/bin/clang` executable found. Selected from { "/Library/Developer/CommandLineTools/usr/bin/clang", "cc", "gcc", "clang", "cl", "zig" }
  8     Version: Apple clang version 14.0.0 (clang-1400.0.29.202)
  9   - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.
 10
 11 ## OS Info:
 12 {
 13   machine = "arm64",
 14   release = "22.2.0",
 15   sysname = "Darwin",
 16   version = "Darwin Kernel Version 22.2.0: Mon Nov 14 23:07:13 PST 2022; root:xnu-8792.61.2~6/RELEASE_ARM64_T8103"
 17 }
 18
 19 ## Parser/Features H L F I J
 20   - lua            ✓ ✓ ✓ ✓ ✓
 21   - rust           ✓ ✓ ✓ ✓ ✓
 22   - c              ✓ ✓ ✓ ✓ ✓
 23   - vim            ✓ ✓ ✓ . ✓
 24   - help           ✓ . . . ✓
 25
 26   Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
 27          +) multiple parsers found, only one will be used
 28          x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.1/share/nvim"

Run :checkhealth for more info
```

**Comment by carlocab** [comment]
It looks to me that you have `CC` set to `/Library/Developer/CommandLineTools/usr/bin/clang` in your environment.

If so, unset `CC` then try again.

**Comment by theHamsta** [comment]
You need to have a C++ standard library installed and discoverable by your compiler as stated in the README.

**Comment by Coop8** [comment]
> It looks to me that you have `CC` set to `/Library/Developer/CommandLineTools/usr/bin/clang` in your environment.
> 
> If so, unset `CC` then try again.

Currently I have `CC` set to `export CC=$(xcrun --find clang)`. Does and `CXX` set to `export CXX=$(xcrun --find clang++) `. Is this correct?

**Comment by theHamsta** [comment]
`CXX` will be ignored. We rely that `CC` will automatically dispatch to C++ when a file has a C++ file ending (*.cc, *.cpp). `CC` will try to link against the C++ standard runtime which `CXX` would do automatically. We invoke `CC` both for C and C++ in one single call. You should be fine when you have a clang++ for whatever installation method you used for clang

**Comment by Coop8** [comment]
> `CXX` will be ignored. We rely that `CC` will automatically dispatch to C++ when a file has a C++ file ending (*.cc, *.cpp). `CC` will try to link against the C++ standard runtime which `CXX` would do automatically. We invoke `CC` both for C and C++ in one single call. You should be fine when you have a clang++ for whatever installation method you used for clang

So I'm confused on how my compiler can't find the standard C++ library if I am able to compile C and C++ programs using the same compiler that I linked in my ZSH config. Is there something that I am missing here? I've got the same setup as multiple people online, however I keep getting this error...

**Comment by carlocab** [comment]
> Currently I have `CC` set to `export CC=$(xcrun --find clang)` and `CXX` set to `export CXX=$(xcrun --find clang++) `. Is this correct?

This is not correct.

> So I'm confused on how my compiler can't find the standard C++ library if I am able to compile C and C++ programs using the same compiler that I linked in my ZSH config.

Not if you invoke `CC` or `CXX` directly.

```
❯ export CXX=$(xcrun --find clang++)
❯ $CXX -xc++ - <<< 'int main(){}'
ld: library not found for -lc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)

❯ clang++ -xc++ - -o /dev/null <<< 'int main(){}' && echo success
success
```

```
❯ export CC=$(xcrun --find clang)
❯ $CC -xc - <<EOS
heredoc> #include <stdio.h>
heredoc> int main(){ printf("hello"); }
heredoc> EOS
<stdin>:1:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
```

Unset these variables and try again.

**Comment by Coop8** [comment]
> > Currently I have `CC` set to `export CC=$(xcrun --find clang)` and `CXX` set to `export CXX=$(xcrun --find clang++) `. Is this correct?
> 
> This is not correct.
> 
> > So I'm confused on how my compiler can't find the standard C++ library if I am able to compile C and C++ programs using the same compiler that I linked in my ZSH config.
> 
> Not if you invoke `CC` or `CXX` directly.
> 
> ```
> ❯ export CXX=$(xcrun --find clang++)
> ❯ $CXX -xc++ - <<< 'int main(){}'
> ld: library not found for -lc++
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> ❯ clang++ -xc++ - -o /dev/null <<< 'int main(){}' && echo success
> success
> ```
> 
> ```
> ❯ export CC=$(xcrun --find clang)
> ❯ $CC -xc - <<EOS
> heredoc> #include <stdio.h>
> heredoc> int main(){ printf("hello"); }
> heredoc> EOS
> <stdin>:1:10: fatal error: 'stdio.h' file not found
> #include <stdio.h>
>          ^~~~~~~~~
> 1 error generated.
> ```
> 
> Unset these variables and try again.

If I were to unset these variables I get loads of errors which boil down to not having a C++ compiler linked in my PATH...

**Comment by carlocab** [comment]
Is `/usr/bin` in your `PATH`?

**Comment by Coop8** [comment]
> Is `/usr/bin` in your `PATH`?

Yes

**Comment by carlocab** [comment]
Do you have a `/usr/bin/clang`?

**Comment by Coop8** [comment]
> Do you have a `/usr/bin/clang`?

Yes

**Comment by carlocab** [comment]
Sounds like a problem with your Neovim configuration then. I'd check what the output of `:echo $PATH` is inside Neovim to see if it does, in fact, include `/usr/bin`.

If you must, you can set `CC=/usr/bin/clang` (and `CXX=/usr/bin/clang++`, but that's not relevant here). This is really just a band-aid, as it's clear there's something else wrong with your setup.

**Comment by Coop8** [comment]
> Sounds like a problem with your Neovim configuration then. I'd check what the output of `:echo $PATH` is inside Neovim to see if it does, in fact, include `/usr/bin`.
> 
> If you must, you can set `CC=/usr/bin/clang` (and `CXX=/usr/bin/clang++`, but that's not relevant here). This is really just a band-aid, as it's clear there's something else wrong with your setup.

Yea I don't know what could be wrong here. Running `echo $PATH` does show that `/usr/bin` is in my path. Setting `CC=/usr/bin/clang` does nothing and gives me a bunch of errors.

**Comment by Coop8** [comment]
> Sounds like a problem with your Neovim configuration then. I'd check what the output of `:echo $PATH` is inside Neovim to see if it does, in fact, include `/usr/bin`.
> 
> If you must, you can set `CC=/usr/bin/clang` (and `CXX=/usr/bin/clang++`, but that's not relevant here). This is really just a band-aid, as it's clear there's something else wrong with your setup.

Running `checkhealth nvim-treesitter` now returns this,
`## Installation
  4   - OK: `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
  5   - OK: `node` found v19.2.0 (only needed for :TSInstallFromGrammar)
  6   - OK: `git` executable found.
  7   - OK: `/usr/bin/clang` executable found. Selected from { "/usr/bin/clang", "cc", "gcc", "clang", "cl", "zig" }
  8     Version: Apple clang version 14.0.0 (clang-1400.0.29.202)
  9   - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.`

So it looks like its ok, however, I am receiving a bunch of errors,
`nvim-treesitter[cpp]: Error during compilation
In file included from src/parser.c:1:
In file included from ./src/tree_sitter/parser.h:10:
/usr/local/include/stdlib.h:134:25: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
double   atof(const char *);
                         ^
/usr/local/include/stdlib.h:134:25: note: insert '_Nullable' if the pointer may be null
double   atof(const char *);
                         ^
                          _Nullable
/usr/local/include/stdlib.h:134:25: note: insert '_Nonnull' if the pointer should never be null
double   atof(const char *);
                         ^
                          _Nonnull
/usr/local/include/stdlib.h:135:22: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
int      atoi(const char *);
                         ^
/usr/local/include/stdlib.h:135:22: note: insert '_Nullable' if the pointer may be null
int      atoi(const char *);
                         ^`
that go on for pages.

**Comment by carlocab** [comment]
You have system headers (e.g. `stdlib.h`) in `/usr/local/include` for some reason:
```
/usr/local/include/stdlib.h:134:25: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
```
I don't know why you have that, but that's likely to break any compiler usage on your system. It does explain why you seem to need to set `CC=$(xcrun --find clang)` -- this is a band-aid for having incompatible system headers inside `/usr/local/include`.

I don't think I can help you much, I'm afraid. There seem to be a number of things weird/non-standard and probably broken about your system (e.g. not being able to find `/usr/bin/clang` despite `/usr/bin` being in `PATH`, or the existence of a `/usr/local/include/stdlib.sh`), so it's hard to give advice that's applicable.

**Comment by Coop8** [comment]
> You have system headers (e.g. `stdlib.h`) in `/usr/local/include` for some reason:
> 
> ```
> /usr/local/include/stdlib.h:134:25: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
> ```
> 
> I don't know why you have that, but that's likely to break any compiler usage on your system. It does explain why you seem to need to set `CC=$(xcrun --find clang)` -- this is a band-aid for having incompatible system headers inside `/usr/local/include`.
> 
> I don't think I can help you much, I'm afraid. There seem to be a number of things weird/non-standard and probably broken about your system (e.g. not being able to find `/usr/bin/clang` despite `/usr/bin` being in `PATH`, or the existence of a `/usr/local/include/stdlib.sh`), so it's hard to give advice that's applicable.

Huh, weird... Maybe it has something to do with MacOS because I can run this same config without errors on Asahi Linux. I am not sure why it can't find c++ :/ Thanks for your assistance either way though.

**Comment by Coop8** [comment]
> `CXX` will be ignored. We rely that `CC` will automatically dispatch to C++ when a file has a C++ file ending (*.cc, *.cpp). `CC` will try to link against the C++ standard runtime which `CXX` would do automatically. We invoke `CC` both for C and C++ in one single call. You should be fine when you have a clang++ for whatever installation method you used for clang

What exactly does this mean?

**Comment by theHamsta** [comment]
> > `CXX` will be ignored. We rely that `CC` will automatically dispatch to C++ when a file has a C++ file ending (*.cc, *.cpp). `CC` will try to link against the C++ standard runtime which `CXX` would do automatically. We invoke `CC` both for C and C++ in one single call. You should be fine when you have a clang++ for whatever installation method you used for clang
> 
> What exactly does this mean? CXX gets ignored in this situation?

`CXX` gets ignored. We invoke `CC`to compile the C++ file and C file together. We use the linker flag `-c++` to link the C++ standard library as `CC` will not do this automatically. We do something like `cc -Isrc src/parser. src/scanner.cc -lc++ -shared -o parser.so`

**Comment by Coop8** [comment]
> > > `CXX` will be ignored. We rely that `CC` will automatically dispatch to C++ when a file has a C++ file ending (*.cc, *.cpp). `CC` will try to link against the C++ standard runtime which `CXX` would do automatically. We invoke `CC` both for C and C++ in one single call. You should be fine when you have a clang++ for whatever installation method you used for clang
> > 
> > 
> > What exactly does this mean? CXX gets ignored in this situation?
> 
> `CXX` gets ignored. We invoke `CC`to compile the C++ file and C file together. We use the linker flag `-c++` to link the C++ standard library as `CC` will not do this automatically. We do something like `cc -Isrc src/parserc. src/scanner.cc -lc++ -shared -o parser.so`. The `.cc` file extension triggers that the file gets treated as C++.

Hmmm ok. Maybe there is something wrong with my clang? I am using AppleClang provided by Xcode. I can't find this issue anywhere else online so I have no idea how to fix it.
