### ISSUE TITLE
missing hlmap query name result in a lot of issues

### ISSUE THREAD

**Issue by kyazdani42** [nvim-treesitter/nvim-treesitter#398]
using neovim latest and nvim-treesitter latest.

Open a rust file, try to save, you get :
`Overwrite existing file "....../main.rs"? (Y)es, [N]o:`

Try to format the file, or do some kind of changes (for instance on a `derive` directive, remove the last `e` and write it back), you'll get:
`Error executing lua callback: /usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:122: Expected lua string`

This is happening because in the highlights.scm file for rust, we use `@meta` which is not declared in the `TSHighlight.hl_map` dict, and going through the highlighter at some point it messes up stuff. 

This is an upstream issue, i might need to post it there.

**Comment by kyazdani42** [comment]
would be closed by https://github.com/neovim/neovim/pull/12858

**Comment by vigoux** [comment]
The PR got merged, but we need to fix the wrong usage of names anyway.

**Comment by stsewd** [comment]
this also breaks queries using auxiliary capture groups like `@_role`


https://github.com/nvim-treesitter/nvim-treesitter/blob/c719e60266fb59807f277035b4405603d8dc09c2/queries/rst/highlights.scm#L81-L85

**Comment by kyazdani42** [comment]
with neovim latest these errors should not happen anymore.

**Comment by kyazdani42** [comment]
`@_role` is not defined in the hl_map dict that's why it does that. We should be more careful about merging the queries, or add a CI to make sure queries are correct.

**Comment by kyazdani42** [comment]
the ci would not be too hard actually, a simple script extracting `@...` values to pass them in the hl_map hashtable to verify they exist would be enough.

**Comment by vigoux** [comment]
Using the `CONTRIBUTING.md` as a reference, that would be what I aim for.

**Comment by vigoux** [comment]
See #411 for discussion on this problem.
