### ISSUE TITLE
java wrong highlight of: '!', spread param, global field

### ISSUE THREAD

**Issue by JosefLitos** [nvim-treesitter/nvim-treesitter#3987]
### Describe the highlighting problem

the unary negation operator is not highlighted as an operator

### Example snippet that causes the problem

```java
!false;
```

### Tree-sitter parsing result

```
unary_expression [53, 2] - [53, 8]
    operator: "!" [53, 2] - [53, 3]
    operand: false [53, 3] - [53, 8]
```

### Example screenshot

![image](https://user-images.githubusercontent.com/54900518/208253782-ebd27043-bb46-4bca-9d3a-e67c88750e8b.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/54900518/208253794-53e9e83a-c208-4219-958b-f85147e1ae6d.png)
the structure looks identical, is is only needed to add "!" to the operator list

### Output of `:checkhealth nvim-treesitter`

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.18.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "6.0.12-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Thu, 08 Dec 2022 11:03:38 +0000"
}

## Parser/Features H L F I J
  - json           ✓ ✓ ✓ ✓ .
  - vim            ✓ ✓ ✓ . ✓
  - css            ✓ . ✓ ✓ ✓
  - yaml           ✓ ✓ ✓ ✓ ✓
  - bibtex         ✓ . ✓ ✓ .
  - lua            ✓ ✓ ✓ ✓ ✓
  - html           ✓ ✓ ✓ ✓ ✓
  - latex          ✓ . ✓ . ✓
  - java           ✓ ✓ . ✓ ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - rust           ✓ ✓ ✓ ✓ ✓
  - bash           ✓ ✓ ✓ . ✓
  - query          ✓ ✓ ✓ ✓ ✓
  - regex          ✓ . . . .
  - cpp            ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

### Output of `nvim --version`

```text
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
přeložil  builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   systémový vimrc soubor: "$VIM/sysinit.vim"
  implicitní hodnota $VIM:"/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by JosefLitos** [comment]
If I wanted to add this highlight using set_query, how would I do that?

**Comment by JosefLitos** [comment]
also global variables (`@field`) are highlighted same as variables, because `variable_declarator` is deeper in the tree.

**Comment by ObserverOfTime** [comment]
> the `after/queries/java/highlights.scm` file didn't seem to do anything

You have to add `; extends` to the top of the file.

Alternatively, you can submit the changes in a PR.

**Comment by JosefLitos** [comment]
> also global variables (`@field`) are highlighted same as variables, because `variable_declarator` is deeper in the tree. The same occurs with the `spread_parameter` that also uses `(variable_declarator)` which gives `@variable` set on the `(identifier)` higher priority over any other highlight: ![image](https://user-images.githubusercontent.com/54900518/208262982-2f61abed-411d-431c-9e9d-d29a39906394.png)

This is probably for another issue, but I don't know how to replace the `variable_declarator` and not break the parser.
