### ISSUE TITLE
JSON - Treesitter not detecting missing quotes

### ISSUE THREAD

**Issue by NiloDrumond** [nvim-treesitter/nvim-treesitter#3989]
I find something weird while working with JSONs, that I'm not sure if it's a limitation, bug, or bad configuration on my side.

TS highlights errors from trailing commas:

Without TS
![image](https://user-images.githubusercontent.com/48765760/208261704-d64a03a1-37bb-4f3f-9520-cf55e4f106d4.png)

With TS:
![image](https://user-images.githubusercontent.com/48765760/208261388-3c82b2ca-0880-43d8-b81e-a1ca66c05aa6.png)

But it doesn't for missing quotes:

Without TS
![image](https://user-images.githubusercontent.com/48765760/208260407-62c31e6d-b63a-4ed5-a01b-fce19e12c79b.png)

With TS
![image](https://user-images.githubusercontent.com/48765760/208260471-6f32f2c8-e35f-4c9e-81cf-f39960e8a87d.png)

--- 

The result is that without TS I have visual feedback for errors that I do not have with TS. I tried manually setting the highlight for the syntax error (tokyonight in my case)
```
hl.jsonNoQuotesError = { bg = c.red }
```
But it seems TS highlights are always prioritized

I'm not sure if this is a problem with the tokyonight theme or with TS. But considering that TS can detect trailing commas, I suppose it should also capable of detecting missing quotes?

**Comment by ObserverOfTime** [comment]
It's a limitation. You can link `@error` (or `@error.json`) to `Error` but that will highlight all incomplete nodes as errors.

**Comment by theHamsta** [comment]
In general, tree-sitter try to parse reliable in the presence of errors, even if that means that errors incorrectly get recognized as valid code. In this case, the parser detects an error but tree-sitter doesn't have the objective at the moment to detect errors or validate the syntax.

**Comment by bew** [comment]
Do you know if the C API can tell us there is a parsing error some place?
:point_right: Could Neovim core expose this?

**Comment by clason** [comment]
Sure, just look for `@error` nodes. But this doesn't change the fundamental point: tree-sitter is _not_ a linter; the goal is to _not_ error on all _correct_ code, not to error on all _incorrect_ code.
