### ISSUE TITLE
Treesitter triggers FileType autocmd twice

### ISSUE THREAD

**Issue by jackwoodside** [nvim-treesitter/nvim-treesitter#4007]
### Describe the bug

I have the following autocmd for starting git commits in insert mode: 

`vim.api.nvim_create_autocmd("FileType", { pattern = { "gitcommit", "gitrebase" }, command = "startinsert" })`

This worked fine before I had the `gitcommit` parser. Now that I have the parser installed, the commit will start in insert mode without syntax highlighting, and then when I go to normal mode, it will add the highlighting and trigger the autocmd again putting it back into insert mode. 

### To Reproduce

1. Add the autocmd to your config
2. Install the gitcommit parser
3. Open a git commit
4. Press esc

### Expected behavior

It only triggers the autocmd once, either before or after the highlighting triggers.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v18.12.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: gcc (GCC) 11.3.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "5.15.83",
  sysname = "Linux",
  version = "#1-NixOS SMP Wed Dec 14 10:37:31 UTC 2022"
}

## Parser/Features H L F I J
  - lua            ✓ ✓ ✓ ✓ ✓
  - bibtex         ✓ . ✓ ✓ .
  - bash           ✓ ✓ ✓ . ✓
  - fortran        ✓ . ✓ ✓ .
  - julia          ✓ ✓ ✓ ✓ ✓
  - rust           ✓ ✓ ✓ ✓ ✓
  - make           ✓ . ✓ . ✓
  - cpp            ✓ ✓ ✓ ✓ ✓
  - nix            ✓ ✓ ✓ . ✓
  - latex          ✓ . ✓ . ✓
  - toml           ✓ ✓ ✓ ✓ ✓
  - gitcommit      ✓ . . . ✓
  - regex          ✓ . . . .
  - markdown       ✓ . ✓ . ✓
  - help           ✓ . . . ✓
  - query          ✓ ✓ ✓ ✓ ✓
  - vim            ✓ ✓ ✓ . ✓
  - yaml           ✓ ✓ ✓ ✓ ✓
  - json           ✓ ✓ ✓ ✓ .

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/zfyninsb38hzxkx3rxvwz3lxdxnsfz0j-neovim-unwrapped-0.8.1/share/nvim
"

Run :checkhealth for more info
```

**Comment by clason** [comment]
_where_ do you define that autocommand?

**Comment by jackwoodside** [comment]
> _where_ do you define that autocommand?

In my `init.lua`

**Comment by clason** [comment]
Then put it in `plugin/after/something.lua`.

**Comment by jackwoodside** [comment]
> Then put it in `plugin/after/something.lua`.

I tried this now and it gives the same behaviour as before

**Comment by jackwoodside** [comment]
I've now changed from packer to lazy, and the problem has disappeared, so that appears to have changed the ordering, which is odd since the previously mentioned fix didn't seem to change the ordering.
