### ISSUE TITLE
Some files lose information when I reboot my system.

### ISSUE THREAD

**Issue by fnacarellidev** [nvim-treesitter/nvim-treesitter#4022]
### Describe the bug

Yesterday I was editing a file then I shut my pc down and today when I go back to that file, boom, everything was gone and I got two messages, one complaining about undo file, I believe it was saying that my file was not an undo file, then I unset my persist undo config which seem to solve, but I don't know yet, and now I'm getting this message when I try to open my .gitignore file:

Error detected while processing BufReadPost Autocommands for "*":

Error executing lua callback: /tmp/.mount_nvimSF42a2/usr/share/nvim/runtime/filetype.lua:22: Error executing lua: /tmp/.mount_nvimSF42a2/usr/share/nvim/runtime/filetype.lua:23: Vim(ap

pend):tree-sitter CLI not found: `tree-sitter` is not executable!

stack traceback:

        [C]: in function 'nvim_cmd'

        /tmp/.mount_nvimSF42a2/usr/share/nvim/runtime/filetype.lua:23: in function </tmp/.mount_nvimSF42a2/usr/share/nvim/runtime/filetype.lua:22>

        [C]: in function 'nvim_buf_call'

        /tmp/.mount_nvimSF42a2/usr/share/nvim/runtime/filetype.lua:22: in function </tmp/.mount_nvimSF42a2/usr/share/nvim/runtime/filetype.lua:11>

stack traceback:

        [C]: in function 'nvim_buf_call'

        /tmp/.mount_nvimSF42a2/usr/share/nvim/runtime/filetype.lua:22: in function </tmp/.mount_nvimSF42a2/usr/share/nvim/runtime/filetype.lua:11>

### To Reproduce

I'm not sure how to reproduce the behavior, all I did was install the treesitter, once I restarted my computer I started having this trouble.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v18.12.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "5.15.0-56-generic",
  sysname = "Linux",
  version = "#62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022"
}

## Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - vim                 ✓ ✓ ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - help                ✓ . . . ✓
  - elixir              ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.1

Build type: RelWithDebInfo

LuaJIT 2.1.0-beta3

Compilation: /usr/bin/gcc-10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/__w/neovim/neovim/build/cmake.config -I/__w/neovim/neovim/src -I/__w/neovim/neovim/.deps/usr/include -I/usr/include -I/__w/neovim/neovim/build/src/nvim/auto -I/__w/neovim/neovim/build/include

Compiled by root@08a8cca64bea



Features: +acl +iconv +tui

See ":help feature-compile"



   system vimrc file: "$VIM/sysinit.vim"

  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"



Run :checkhealth for more info
```

**Comment by clason** [comment]
I commiserate, but this has nothing
