### ISSUE TITLE
auto_install requires restart or reinstallation for highlighting

### ISSUE THREAD

**Issue by rliebz** [nvim-treesitter/nvim-treesitter#4026]
### Describe the bug

With `auto_install` enabled, opening a filetype for a language for the first time successfully installs the parser for that language. Although it is installed, it does not highlight the current buffer or other buffers of that filetype. 

### To Reproduce

1. Create a treesitter config such as the following (currently using lazy.nvim, but reproduced with packer.nvim). In particular, have `auto_install` set to `true` and highlights enabled:
```lua
{
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter.configs").setup({
			auto_install = true,
			highlight = {
				enable = true,
			},
		})
	end,
}
```
2. Open a filetype that has not been opened before. Optionally, run `:TSUninstall` first to ensure the parser is not installed.
3. Observe a message such as `[nvim-treesitter] [1/1] Treesitter parser for go has been installed` confirming the parser has been installed, but that highlights are not being applied.
4. Either open a new neovim instance to see highlights applied, or run `TSInstall!` in the current instance to see highlights applied.

### Expected behavior

After the parser is installed automatically, highlights should be visible immediately without having to reinstall the parser or restart neovim.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v19.1.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 14.0.0 (clang-1400.0.29.202)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "22.1.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:52 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8112"
} ~

Parser/Features         H L F I J
  - lua                 ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.0-dev-553+g9be24110f-dirty
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by rob@Roberts-MacBook-Air.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-9be2411/share/nvim"

Run :checkhealth for more info
```

### Additional context

When running `:checkhealth nvim-treesitter`, a parser that has been auto-installed and but is not yet highlighting does not appear in the `Parser/Features` table. After reinstalling or starting a new neovim instance, it does appear.

This bug only seems to occur with auto_install enabled, and does not occur after installing manually with `auto_install` disabled.

**Comment by theHamsta** [comment]
Actually this was already implemented. The highlight module was attached right after the installation. But apparently, since the highlight module right now does no longer activate the actual tree-sitter highlighting. Apparently, this is done now using `vim.treesitter.start()`. Either we should do that in the highlight module or do that here when reattaching all tree-sitter modules after an successful installation

https://github.com/theHamsta/nvim-treesitter/blob/0eae8d3f61fee90c659bc581528343cf093312fe/lua/nvim-treesitter/install.lua#L386-L396

**Comment by theHamsta** [comment]
Can you have a look at https://github.com/nvim-treesitter/nvim-treesitter/pull/4032

**Comment by rliebz** [comment]
@theHamsta unfortunately it doesn't appear to have fixed the issue. I'm seeing the same behavior as before with the following config:

```lua
{
	"theHamsta/nvim-treesitter",
	branch = "auto-start-treesitter",
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter.configs").setup({
			auto_install = true,
			highlight = {
				enable = true,
			},
		})
	end,
}
```

**Comment by rliebz** [comment]
@theHamsta I'm not seeing any difference in behavior with #4032 merged. Looking at the changes there, if I manually call `require('nvim-treesitter').highlight.attach` or `vim.treesitter.start` it appears to start highlighting, but I would assume I shouldn't have to set up an autocmd or anything to make that work:


![Screen Recording 2022-12-26 at 8 10 06 AM](https://user-images.githubusercontent.com/5321575/209552973-b5620603-3f58-45de-bc76-593b5185907f.gif)

**Comment by theHamsta** [comment]
```
{
	"theHamsta/nvim-treesitter",
	branch = "auto-start-treesitter",
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter.configs").setup({
			auto_install = true,
			highlight = {
				enable = true,
			},
		})
	end,
}
```
you shouldn't use my fork of nvim-treesitter. It is centuries old

**Comment by rliebz** [comment]
Added a debug statement, and it looks like `M.attach` in `highlight.lua` is not being reached with `auto_install`, but is being reached with a manual call to `:TSInstall`.

**Comment by theHamsta** [comment]
Hmm, I can now reproduce it, too. It seems the module doesn't get enabled on `auto_install`

**Comment by theHamsta** [comment]
Can you test https://github.com/nvim-treesitter/nvim-treesitter/pull/4040

**Comment by rliebz** [comment]
Working on my end, thanks for the quick turnaround!
