### ISSUE TITLE
Add documentation that describes how to install parsers offline

### ISSUE THREAD

**Issue by joshbainbridge** [nvim-treesitter/nvim-treesitter#4049]
I'm often in a scenario where I'd like to configure Neovim but don't have access to the internet, and must be able to configure using local files on a drive. This is easily done. And for Tree-sitter, just requires pointing the config towards a local url:

``` lua
local parser_config = require("nvim-treesitter.parsers").get_parser_configs()
parser_config.cpp.install_info.url = "/local/path/to/tree-sitter-cpp-master"
parser_config.rust.install_info.url = "/local/path/to/tree-sitter-rust-master"
...
```

However this isn't that clear in the README documentation. Perhaps adding a new item under the 'Troubleshooting' section to help others in a similar situation would be a good call?

I'd be happy to write this and submit a PR if others think it would be useful.

**Comment by theHamsta** [comment]
How do you get the parser repos? Couldn't you then also provide the parsers as local files or do you want to target many Docker Linux versions and need always generate from source? Our online installer is only one option, the Neovim documentation describes where to put parsers to be discoverable for Neovim. Would it help if we would provide binary parser packs for one-time download that you can then store locally?

**Comment by joshbainbridge** [comment]
Thanks for your reply!

For example, a typical workflow for myself would be to `git clone https://github.com/tree-sitter/tree-sitter-cpp` and place it alongside my `.config/nvim` on a drive. Then bring that physically onto a system that has no internet access. I'd finally point the url to the grammar as described above, and then install.

You mention there is a location to put parsers that is discoverable? I must have missed that in the docs. That does sound better. This was just the method I've arrived at, but please do let me know if there's a better alternative, I'd be happy to adopt it.

Either way, perhaps there is still potential to make the docs clearer on the specific 'no internet access' scenario if you think that is a common enough case.

**Comment by theHamsta** [comment]
> You mention there is a location to put parsers that is discoverable? I must have missed that in the docs. That does sound better. > This was just the method I've arrived at, but please do let me know if there's a better alternative, I'd be happy to adopt it.

It should be mentioned in the Neovim docs. nvim-treesitter will install it's parsers to `nvim-treesitter/parser/*.so`. You can put the parsers anywhere in your runtime path in a folder named `parser/`

**Comment by clason** [comment]
> You mention there is a location to put parsers that is discoverable?

The **compiled** parsers, not the cloned repo.

**Comment by joshbainbridge** [comment]
Thanks for the input. So correct me if I'm wrong, you are saying the alternative would be to compile the parsers on the system and then place them in the `nvim-treesitter/parser/` directory. And I'm presuming this also requires that tree-sitter itself (and potentially node) are installed on the system as a dependency to compile the parser?

From a user's perspective, and a non-knowledgable one like myself, I would say it's easier to rely on :TSInstall. This is great for two reasons. I'm not required to have any prior knowledge about how parsers work and how they are compiled + the system doesn't appear to require any further dependencies over just nvim. Just point to the repo and go.

**Comment by clason** [comment]
> Thanks for the input. So correct me if I'm wrong, you are saying the alternative would be to compile the parsers on the system and then place them in the `nvim-treesitter/parser/` directory

In _any_ `parser` subdirectory of `runtimepath`. As long as the `.so` is there, nothing else matters -- in particular, if the repo contains the `parser.c`, you don't need `tree-sitter`, `rust`, or `node` at all

> From a user's perspective, and a non-knowledgable one like myself, I would say it's easier to rely on :TSInstall

Obviously. That's the whole point of nvim-treesitter.

**Comment by joshbainbridge** [comment]
Okay great, I've got that to work. Using the cpp parser as an example, it compiled with:
```
c++ -o parser.so -shared src/parser.c src/scanner.cc -Os -I./src
```
Although, I'm going to stick with setting the `url` and allow nvim-treesitter to handle this for me. That's much simpler. As you say it's the whole point. It's a fantastic library!

I think my original feedback is still valid, it might be useful for other users to know that nvim-treesitter can point the `url` to a local repo. But feel free to close the issue, just wanted to pass that along, up to you if you feel that would be worthwhile.

**Comment by amaanq** [comment]
> it might be useful for other users to know that nvim-treesitter can point the url to a local repo

It is in the README, https://github.com/nvim-treesitter/nvim-treesitter#adding-parsers
