### ISSUE TITLE
attempt to call field 'start' (a nil value)

### ISSUE THREAD

**Issue by tinnick** [nvim-treesitter/nvim-treesitter#4063]
### Describe the bug

After updating to the latest treesitter version via packer, all syntax highlighting broke.

Below error message will show up on start of any file being opened:

```
Error detected while processing BufReadPost Autocommands for "*.lua"..FileType Autocommands for "*":
Error executing lua callback: .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:26: attempt to call field 'start' (a nil value)
stack traceback:
        .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:26: in function 'attach'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:505: in function 'attach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:528: in function 'reattach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:131: in function <...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:130>
```

What's even more bothering is that it seems healthcheck itself is broken because it can't find the .lua file for healthcheck. (this could just be the nvim master branch issue?)

I'm trying to figure out in which version of nvim and nvim-treesitter will work without any issues as I don't have any special configuration other than the below:

```lua
local nvim_treesitter_configs_ok, nvim_treesitter_configs = pcall(require, 'nvim-treesitter.configs');

if not nvim_treesitter_configs_ok then
  return;
end

nvim_treesitter_configs.setup({
  ensure_installed = 'all',
  sync_install = false,
  auto_install = true,
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
});
```

I believe I should probably fix the healthcheck command problem since it seems unrelated but I'd also like to know the issue behind the first error message above and see it any one else is experiencing this.

happy new years btw :)

### To Reproduce

1. build neovim from source (master branch) with `make` (not `make install`).

The above will build neovim and put an executable under /build/bin/nvim (relative to the git root) and I only have interest in the build artifact as I have configured in my .bashrc as so:
```bash
export PATH=$PATH:~/path/to/neovim/build/bin
```

2. install packer.
3. configure nvim:

```lua
vim.cmd [[packadd packer.nvim]];

return require('packer').startup(function(use)
  use 'wbthomason/packer.nvim';
  use 'neovim/nvim-lspconfig';
  use 'williamboman/mason.nvim';
  use 'williamboman/mason-lspconfig.nvim';
  use({
    'nvim-treesitter/nvim-treesitter',
    run = function()
      local ts_update = require('nvim-treesitter.install').update({ with_sync = true });
      ts_update();
    end,
  });
end)
```

### Expected behavior

no errors and syntax highlighted.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
  - ERROR: Failed to run healthcheck for "nvim-treesitter" plugin. Exception:
    function health#check, line 24
    Vim(eval):E5108: Error executing lua vim/_init_packages.lua:0: module 'vim.health' not found:
    no field package.preload['vim.health']
    no file './vim/health.lua'
    no file '/root/programs/neovim/.deps/usr/share/luajit-2.1.0-beta3/vim/health.lua'
    no file '/usr/local/share/lua/5.1/vim/health.lua'
    no file '/usr/local/share/lua/5.1/vim/health/init.lua'
    no file '/root/programs/neovim/.deps/usr/share/lua/5.1/vim/health.lua'
    no file '/root/programs/neovim/.deps/usr/share/lua/5.1/vim/health/init.lua'
    no file '/root/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/vim/health.lua'
    no file '/root/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/vim/health/init.lua'
    no file '/root/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/vim/health.lua'
    no file '/root/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/vim/health/init.lua'
    no file './vim/health.so'
    no file '/usr/local/lib/lua/5.1/vim/health.so'
    no file '/root/programs/neovim/.deps/usr/lib/lua/5.1/vim/health.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
    no file '/root/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/vim/health.so'
    no file './vim.so'
    no file '/usr/local/lib/lua/5.1/vim.so'
    no file '/root/programs/neovim/.deps/usr/lib/lua/5.1/vim.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
    no file '/root/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/vim.so'
    stack traceback:
    [C]: in function 'require'
    vim/_init_packages.lua: in function '__index'
    ...ker/start/nvim-treesitter/lua/nvim-treesitter/health.lua:10: in main chunk
    [C]: in function 'require'
    [string "luaeval()"]:1: in main chunk
```

### Output of `nvim --version`

```text
NVIM v0.9.0-dev-581+gcb9d68fe6
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by root@DESKTOP-H4CGC4J

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
This is a broken Neovim installation. Make sure to clean all caches (impatient, hotpot, lazy, etc.)

**Comment by tinnick** [comment]
> This is a broken Neovim installation. Make sure to clean all caches (impatient, hotpot, lazy, etc.)

How are you sure this is a "broken Neovim installation"?

Anyway, I've reinstalled neovim still get the same issues but all other packages healthcheck actually works.
It seems like this is trreesitter issue. I'd like to know why you thought this as a broken installation so I can go do it correctly.

Kind regards

**Comment by clason** [comment]
> How are you sure this is a "broken Neovim installation"?

Because a built-in part of Neovim (runtime files) is not available; this is a classic issue that pops up again and again.

If you're sure it's not your Neovim installation, then it's usually an outdated version of the plugin files that is cached somewhere.

**Comment by tinnick** [comment]
> > How are you sure this is a "broken Neovim installation"?
> 
> Because a built-in part of Neovim (runtime files) is not available; this is a classic issue that pops up again and again.
> 
> If you're sure it's not your Neovim installation, then it's usually an outdated version of the plugin files that is cached somewhere.

That might be true, but this in the nvim-treesitter source code looks wrong to me as well:
```lua
-- in '/lua/nvim-treesitter/health.lua' this seems to be a recursive function
local health = vim.health or require "health"
```

Found from the below error:
```
  - ERROR: Failed to run healthcheck for "nvim-treesitter" plugin. Exception:
    function health#check, line 24
    Vim(eval):E5108: Error executing lua [string "luaeval()"]:1: loop or previous error loading module 'nvim-treesitter.health'
    stack traceback:
    [C]: in function 'require'
    [string "luaeval()"]:1: in main chunk
```

**Comment by tinnick** [comment]
Turns out that neovim just didn't recognize the runtime files that comes with the neovim repo because the runtime path was not set to include them. I just needed set the VIMRUNTIME environment variable correctly.

I've added the below line to my .bashrc file:
```bash
VIMRUNTIME=~/path/to/neovim/runtime
```
and now it works.

Thanks for pointing me in the right direction.

**Comment by Bridges369** [comment]
I have the same problem, but I'm a Windows user and I have no idea how to do this.

it's in Portuguese, but I imagine it's not a problem:
```
Erro detectado ao processar FileType Autocommands for "*":
Error executing lua callback: ...\start\nvim-treesitter/lua/nvim-treesitter/highlight.lua:19: attempt to call field 'start' (a nil value)
stack traceback:
        ...\start\nvim-treesitter/lua/nvim-treesitter/highlight.lua:19: in function 'attach'
        ...er\start\nvim-treesitter/lua/nvim-treesitter/configs.lua:505: in function 'attach_module'
        ...er\start\nvim-treesitter/lua/nvim-treesitter/configs.lua:528: in function 'reattach_module'
        ...er\start\nvim-treesitter/lua/nvim-treesitter/configs.lua:131: in function <...er\start\nvim-treesitter/lua/nvim-treesitter/configs.lua:130>
Aperte ENTER ou digite um comando para continuar
```

this is my config file, nothing much different from the previous guy:
```lua
require("nvim-treesitter.configs").setup {
  -- A list of parser names, or "all"
  ensure_installed = { "ruby", "rust", "lua", "html", "css", "python" },

  sync_install = true,
  indent = {
    enable = true
  },

  auto_install = true,

  -- List of parsers to ignore installing (for "all")
  ignore_install = { "javascript" },

  highlight = {
    -- `false` will disable the whole extension
    enable = true,

    additional_vim_regex_highlighting = false,
  },
}
```

## Output of `:checkhealth nvim-treesitter`
```
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.15.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: gcc.exe (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders) 12.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "10.0.22621",
  sysname = "Windows_NT",
  version = "Windows 10 Home Single Language"
}

## Parser/Features         H L F I J
  - rust                ✓ ✓ ✓ ✓ ✓
  - ruby                ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```


## Output of `nvim --version`
```
NVIM v0.7.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilado por runneradmin@fv-az320-113

Features: -acl +iconv +tui
See ":help feature-compile"

    arquivo vimrc de sistema: "$VIM\sysinit.vim"
            padrão para $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

**Comment by codycjy** [comment]
> I have the same problem, but I'm a Windows user and I have no idea how to do this.
> 
> it's in Portuguese, but I imagine it's not a problem:
> 
> ```
> Erro detectado ao processar FileType Autocommands for "*":
> Error executing lua callback: ...\start\nvim-treesitter/lua/nvim-treesitter/highlight.lua:19: attempt to call field 'start' (a nil value)
> stack traceback:
>         ...\start\nvim-treesitter/lua/nvim-treesitter/highlight.lua:19: in function 'attach'
>         ...er\start\nvim-treesitter/lua/nvim-treesitter/configs.lua:505: in function 'attach_module'
>         ...er\start\nvim-treesitter/lua/nvim-treesitter/configs.lua:528: in function 'reattach_module'
>         ...er\start\nvim-treesitter/lua/nvim-treesitter/configs.lua:131: in function <...er\start\nvim-treesitter/lua/nvim-treesitter/configs.lua:130>
> Aperte ENTER ou digite um comando para continuar
> ```
> 
> this is my config file, nothing much different from the previous guy:
> 
> ```lua
> require("nvim-treesitter.configs").setup {
>   -- A list of parser names, or "all"
>   ensure_installed = { "ruby", "rust", "lua", "html", "css", "python" },
> 
>   sync_install = true,
>   indent = {
>     enable = true
>   },
> 
>   auto_install = true,
> 
>   -- List of parsers to ignore installing (for "all")
>   ignore_install = { "javascript" },
> 
>   highlight = {
>     -- `false` will disable the whole extension
>     enable = true,
> 
>     additional_vim_regex_highlighting = false,
>   },
> }
> ```
> 
> ## Output of `:checkhealth nvim-treesitter`
> ```
> nvim-treesitter: require("nvim-treesitter.health").check()
> ========================================================================
> ## Installation
>   - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
>   - OK: `node` found v16.15.0 (only needed for :TSInstallFromGrammar)
>   - OK: `git` executable found.
>   - OK: `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
>     Version: gcc.exe (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders) 12.2.0
>   - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.
> 
> ## OS Info:
> {
>   machine = "x86_64",
>   release = "10.0.22621",
>   sysname = "Windows_NT",
>   version = "Windows 10 Home Single Language"
> }
> 
> ## Parser/Features         H L F I J
>   - rust                ✓ ✓ ✓ ✓ ✓
>   - ruby                ✓ ✓ ✓ ✓ ✓
>   - html                ✓ ✓ ✓ ✓ ✓
>   - c                   ✓ ✓ ✓ ✓ ✓
>   - lua                 ✓ ✓ ✓ ✓ ✓
>   - python              ✓ ✓ ✓ ✓ ✓
>   - cpp                 ✓ ✓ ✓ ✓ ✓
>   - css                 ✓ . ✓ ✓ ✓
> 
>   Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
>          +) multiple parsers found, only one will be used
>          x) errors found in the query, try to run :TSUpdate {lang}
> ```
> 
> ## Output of `nvim --version`
> ```
> NVIM v0.7.0
> Build type: RelWithDebInfo
> LuaJIT 2.1.0-beta3
> Compilado por runneradmin@fv-az320-113
> 
> Features: -acl +iconv +tui
> See ":help feature-compile"
> 
>     arquivo vimrc de sistema: "$VIM\sysinit.vim"
>             padrão para $VIM: "C:/Program Files/nvim/share/nvim"
> 
> Run :checkhealth for more info
> ```

Try using neovim 0.8.0 or later, this may solve your problem.

**Comment by Bridges369** [comment]
I switched to version 0.8.0 of Neovim, but it's still on the same error. And it goes to the latest (0.8.2 stable)

**Comment by wywl99** [comment]
> I switched to version 0.8.0 of Neovim, but it's still on the same error. And it goes to the latest (0.8.2 stable)

I have the same problem as you, did you find a solution?

**Comment by Bridges369** [comment]
> > I switched to version 0.8.0 of Neovim, but it's still on the same error. And it goes to the latest (0.8.2 stable)
> 
> I have the same problem as you, did you find a solution?

No. It's even funny that what software I try to install never works the first time...

**Comment by iiishop** [comment]
I have the same problem, but it did not happen one month before. I update this plugin this day then it happens. But when I replace with the old file, it disappears.

**Comment by Bridges369** [comment]
> I have the same problem, but it did not happen one month before. I update this plugin this day then it happens. But when I replace with the old file, it disappears. 

What version did you use?

**Comment by tinnick** [comment]
@iiishop @wywl99 @Bridges369 
Have tried my solution? (That is, settings the `$VIMRUNTIME` environment variable?

See my fix:
https://github.com/nvim-treesitter/nvim-treesitter/issues/4063#issuecomment-1368530516

the runtime should be a folder where healthcheck files and some docs exists.

**Comment by geofflangenderfer** [comment]
@tinnick can you show us what you get with the following commands? I downloaded the neovim executable so I'm not sure that I have a runtime folder available

```
tree ~/path/to/neovim/
tree ~/path/to/neovim/runtime
```
