### ISSUE TITLE
add the -static option to the gcc compiler

### ISSUE THREAD

**Issue by Antipula** [nvim-treesitter/nvim-treesitter#4078]
add the -static option to the gcc compiler
solves problems with some compiler versions
preferably optional

google translate

**Comment by theHamsta** [comment]
Can you check whether you can achieve that using `command_extra_args`  https://github.com/nvim-treesitter/nvim-treesitter#i-want-to-use-a-http-proxy-for-downloading-the-parsers? Use `cc` instead of `curl` when nvim-treesitter selects `cc` on your machine (check using `:healthcheck nvim-treesitter`
