### ISSUE TITLE
Indent with curly braces on new line behaves weirdly

### ISSUE THREAD

**Issue by lucario387** [nvim-treesitter/nvim-treesitter#4079]
### Describe the bug

When placing an opening curly braces on newline right after for/while, vim/nvim will (try to) align it with the indentation of the line above, but not for treesitter indent

### To Reproduce

1. Open nvim with a C parser, opening the file below
```c
#include <stdio.h>

int main()
{
  while(1)
       // put the cursor here
}
```
2. Enter insert mode, insert `{`

### Expected behavior

The code should be like below
```c
#include <stdio.h>

int main()
{
  while(1)
  {
}
```

### Actual behavior

The curly brace is placed at where the cursor is, not trying to put itself at the position that vim/nvim will place it
```c
#include <stdio.h>

int main()
{
  while(1)
       {
}
```

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v16.15.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 12.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.1.1-zen1-1-zen",
  sysname = "Linux",
  version = "#1 ZEN SMP PREEMPT_DYNAMIC Wed, 21 Dec 2022 22:27:59 +0000"
} ~

Parser/Features         H L F I J
  - todotxt             ✓ . . . .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - java                ✓ ✓ . ✓ ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - mermaid             ✓ . . . .
  - markdown            ✓ . ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - gitignore           ✓ . . . .
  - sxhkdrc             ✓ . ✓ . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓
  - pug                 ✓ . . . ✓
  - svelte              ✓ . ✓ ✓ ✓
  - rasi                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ .
  - scheme              ✓ . ✓ . ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - r                   ✓ ✓ . ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - awk                 ✓ . . . ✓
  - jsdoc               ✓ . . . .
  - diff                ✓ . . . .
  - comment             ✓ . . . .
  - toml                ✓ ✓ ✓ ✓ ✓
  - gitcommit           ✓ . . . ✓
  - gitattributes       ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - bash                ✓ ✓ ✓ . ✓
  - zig                 ✓ . ✓ ✓ ✓
  - regex               ✓ . . . .
  - git_rebase          ✓ . . . ✓
  - markdown_inline     ✓ . . . ✓
  - help                ✓ . . . ✓
  - vue                 ✓ . ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - vim                 ✓ ✓ ✓ . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.0-dev-594+gc590641fe
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by root@spacegliders

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Additional context

This may not only affect C but probably many other filetypes as well

**Comment by bryant-the-coder** [comment]
will test this when i get back on my linux machine.

**Comment by gdamore** [comment]
Indentation with purely tree-sitter queries is *hard*.  The notion of whether to indent after a while statement can be subject coding style, and in my experience, no editor really gets this "right" unless you have something that understands the actual formatting rules (e.g. clang-format) wired into the an understanding of the grammar.  The only way I know of to do this right now "universally" is to use an LSP with format-on-type.

I don't know of any tree-sitter grammar based solution that gets this right for languages that allow user-preference over things like whitespace placement.  (In fact, tree-sitter is mostly ignorant of whitespace most of the time.)

**Comment by yioneko** [comment]
> Indentation with purely tree-sitter queries is hard.

I have the exactly same feelings. I really suspect if there is an *easily configurable*, and *generic* solution for multi-language indent based on tree-sitter. From my experience of developing another tree-sitter based indent module, this task is nearly impossible. I only made it to work well in some c-style languages but I still have no idea to support friendly style configuration and other non-trival languages like yaml and markdown. Language-specific solution is possible (just implement it like a formatter) but I don't think generic rules (queries) for typical brackets-based languages could apply to those either (and didn't succeed in it).

> The only way I know of to do this right now "universally" is to use an LSP with format-on-type.

Can't agree with this more. Just FYI, here is the issue about lsp-based indent: https://github.com/microsoft/language-server-protocol/issues/1326. I'm looking forward to its standardization and I believe the indent should be better left to language-specific implementors.
