### ISSUE TITLE
TSInstall python error

### ISSUE THREAD

**Issue by Aya-Yang** [nvim-treesitter/nvim-treesitter#4090]
### Describe the bug

TSInstall python compile error
![image](https://user-images.githubusercontent.com/12084255/210524184-57fa2f15-52c8-4d87-a60a-b44f1686a48b.png)

### To Reproduce

run TSInstall python

### Output of `:checkhealth nvim-treesitter`

```markdown
ERROR: No healthcheck found for "nvim-treesitter" plugin.
```

### Output of `nvim --version`

```text
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.8.2/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
Can't reproduce, needs more info.

**Comment by theHamsta** [comment]
Maybe the tree-sitter-python was not tested with libc++ (the xcode apple-clang one). Do you have the chance to use your system compiler or try with gcc?

**Comment by Aya-Yang** [comment]
Just for a note, if someone has the same issue,
I edited /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cctype file, add iswspace, and now it worked

**Comment by theHamsta** [comment]
> Works fine for me on macOS.

But are you using Xcode?
