### ISSUE TITLE
Parser compilation fails on Windows 10

### ISSUE THREAD

**Issue by OndrikB** [nvim-treesitter/nvim-treesitter#4100]
### Describe the bug

When running `:TSInstall cpp`, for instance, the parser downloads properly but then I get the following error:

`clang: error: linker command failed with exit code 1104 (use -v to see invocation)^M`

### To Reproduce

Run `:TSInstall` with any parser

### Expected behavior

The parser compiles without issue. 

### Output of `:checkhealth nvim-treesitter`

```markdown
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v18.12.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `clang` executable found. Selected from { "clang", "gcc" }
    Version: clang version 15.0.5
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "10.0.19045",
  sysname = "Windows_NT",
  version = "Windows 10 Home"
}

## Parser/Features         H L F I J
  - c                   x x x x x
  - python              x x x x x
  - markdown            x . x . x
  - make                x . x . x
  - cpp                 x x x x x
  - rust                x x x x x
  - help                x . . . x

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: c(highlights): Failed to load parser: uv_dlopen: C:\Users\ondri\AppData\Local\nvim\autoload\plugged\nvim-treesitter\parser\c.so is not a valid Win32 application.
    
    c(highlights) is concatenated from the following files:
    | [ERROR]:"C:\Users\ondri\AppData\Local\nvim\autoload\plugged\nvim-treesitter\queries\c\highlights.scm", failed to load: Failed to load parser: uv_dlopen: C:\Users\ondri\AppData\Local\nvim\autoload\plugged\nvim-treesitter\parser\c.so is not a valid Win32 application.
  - ERROR: c(locals): Failed to load parser: uv_dlopen: C:\Users\ondri\AppData\Local\nvim\autoload\plugged\nvim-treesitter\parser\c.so is not a valid Win32 application.
    
    c(locals) is concatenated from the following files:
    | [ERROR]:"C:\Users\ondri\AppData\Local\nvim\autoload\plugged\nvim-treesitter\queries\c\locals.scm", failed to load: Failed to load parser: uv_dlopen: C:\Users\ondri\AppData\Local\nvim\autoload\plugged\nvim-treesitter\parser\c.so is not a valid Win32 application.
  - ERROR: c(folds): Failed to load parser: uv_dlopen: C:\Users\ondri\AppData\Local\nvim\autoload\plugged\nvim-treesitter\parser\c.so is not a valid Win32 application.
```
(this continues for all the different failed parsers)
```


### Output of `nvim --version`

```text
NVIM v0.8.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az28-353

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

### Additional context

I have checked that my PATH contains the correct `include` and `lib` directories. I have also attempted to install the parsers with `gcc`, `clang` and even `cl` from the Visual Studio command prompt, with none of them working properly. With these other compilers, it says that the parser was installed successfully, but the errors persist.

**Comment by theHamsta** [comment]
@OndrikB how do you install clang? Does it come with it's linker `ld` or does it try to use the MSVC toolchain to link? I guess that kind of depends on the LLVM installation.

> I have checked that my PATH contains the correct include and lib directories

This shouldn't be necessary.

> `cl` from the Visual Studio command prompt,

Did you select the native 64bit command prompt? That usually is the safest option on Windows.

**Comment by OndrikB** [comment]
> how do you install clang? 

I followed the instructions on the Windows Troubleshooting page and installed chocolatey, then used it to install llvm. I don't know what kind of linker it tries to use in that case. 

> This shouldn't be necessary.

It did fix previous issues the compiler threw at me, such as `corecrt.h` not being found. 

As far as `cl` with Visual Studio, I think the command prompt was 64bit? I unfortunately don't know exactly.

**Comment by ljani** [comment]
For what it is worth, my error was that I was accidentally compiling 32-bit libraries when my Neovim is 64-bit. This happens if you choose eg. `Developer PowerShell for VS 2022` instead of `x64 Native Tools Command Prompt for VS 2022`.

I think many of the `Failed to load parser: uv_dlopen: *.so is not a valid Win32 application.` errors (such as #1091 #502) are related to 32-bit vs 64-bit compatibility either way with different toolchains.

**Comment by rickywu** [comment]
@ljani I tried Developer PowerShell for VS 2022 and got the same error

Any update? @OndrikB

**Comment by OndrikB** [comment]
> Any update? @OndrikB

Sorry for the late reply. I did not check this in some time. 
I ended up essentially "giving up" by using neovim from within WSL instead, where the parsers compile and install without issue.

**Comment by rickywu** [comment]
Well, I found the reason and use MSVC Tool compile without problem, just install SDK and set env var:

[environment]::SetEnvironmentvariable("LIB", "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.38.33130\lib\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\ucrt\x64;", "User")

**Comment by EdenCore** [comment]
In the same fashion as @rickywu, here is a working config as of today.

1. First, look for "Build Tools pour Visual Studio 2022" on [Microsoft's site](download.visualstudio.microsoft.com). 
Download and run.
2. Check "C++ Development for Desktop". It will select the base tools.
3. Go to the optional components on the right pane. Check MSVC. For example, on windows 10, mine is MSVC v143 - VS 2022.
Also look for the latest windows SDK and the clang BuildTool for C++/CLI.

Finally, set up environment variables :

- INCLUDE = C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.42.34433\include;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include;C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\ucrt;

- LIB = C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.42.34433\lib\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.20348.0\um\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10348.0\ucrt\x64;
