### ISSUE TITLE
Refresh Treesitter Syntax Highlighting

### ISSUE THREAD

**Issue by AlexSWall** [nvim-treesitter/nvim-treesitter#4122]
Is there a command or similar for refreshing the current treesitter syntax highlighting?

Ocassionally it is slightly incorrect, I've found the standard strategies, such as `:redraw!`, aren't working for me—I end up needing to modify the incorrect text.

**Comment by theHamsta** [comment]
Are you sure that the deferred highlighting is tree-sitter highlighting and not LSP semantic token highlighting? Tree-sitter extmarks should also be drawn on `:redraw!` but why do you expect that the result of `:redraw!` should change the current highlighting. What do you expect to happen on the refresh command to happen. Tree-sitter updates are completely in sync with the current buffer.

**Comment by AlexSWall** [comment]
I am not sure, perhaps it is the LSP, I am not familiar with 'LSP semantic token highlighting'.

Here is an example—the T and M are randomly coloured differently. I was hoping there would be a generic way to refresh/redraw the view to remove such oddities.
<img width="126" alt="Screenshot 2023-01-11 at 00 22 31" src="https://user-images.githubusercontent.com/31999802/211689543-282e255c-ac44-4c5b-9f04-43d1d1f49bd5.png">

**Comment by clason** [comment]
Use nvim-treesitter/playground (if you're on Neovim 0.8.2) or `:Inspect` (if you're on Neovim nightly) to check where the colors are coming from.

**Comment by theHamsta** [comment]
Do you have "todo-comment.nvim" installed? I saw those too but they shouldn't be caused by tree-sitter (or if at all by a bug in extmarks)

**Comment by AlexSWall** [comment]
Ah, thanks for the suggestion—the `:Inspect` commands suggests that the [nvim-ts-rainbow](https://github.com/p00f/nvim-ts-rainbow) plugin may be the cause.

For example, here
<img width="359" alt="Screenshot 2023-01-12 at 03 10 25" src="https://user-images.githubusercontent.com/31999802/211967212-f57620af-6167-41a4-82d3-989c5c8e66aa.png">
if I run `:Inspect` at the `o` of `function` (highlighted correctly) I get
<img width="369" alt="Screenshot 2023-01-12 at 03 14 08" src="https://user-images.githubusercontent.com/31999802/211967361-89108bce-ea48-46c5-b8ef-ce729caa4a15.png">
whereas at the `n` I get
<img width="369" alt="Screenshot 2023-01-12 at 03 14 22" src="https://user-images.githubusercontent.com/31999802/211967393-e0ecd9ec-1209-492e-852d-b057b94e2217.png">

The first image was for comments, but it seems like the same colour so I suspect it may still be the cause. Looks like the plugin has recently become unmaintained, too, so would be less surprising. I'll close the issue, but reopen if it appears to not be as simple as this.
