### ISSUE TITLE
Impossible to ignore_install parser 'help' from loading twice 

### ISSUE THREAD

**Issue by stoddart** [nvim-treesitter/nvim-treesitter#4126]
### Describe the bug

There are at least four core parsers in Neovim that are installed by default: "c", "help", "lua", and "vim".

In the treesitter.lua configuration, I have this line to ignore the core parsers:

`ignore_install = { "c", "help", "lua", "vim" },`

...which successfully ignores "c", "lua", and "vim"...but NOT "help", which installs twice. When I run `:checkhealth`, it shows "help: ABI version 14" as loading twice, while the c, lua, and vim parsers are successfully ignored. 

I'm left wondering if this is a bug that installs parsers that are already included in core or if it's a bug because it displays them twice? Thanks. 

### To Reproduce

1. Go to '/Users/user/.config/nvim/lua/<user>/plugins/treesitter.lua

2. In the treesitter configuration, add:

`treesitter.setup({
         ignore_install = {  "c", "help", "lua", "vim" },`

3. Save and restart

4. Run `:checkhealth`

### Expected behavior

I expected the "help" parser to be ignored since it's already part of the core functionality of treesitter.

### Output of `:checkhealth nvim-treesitter`

```markdown
OK: Loaded parser for help: ABI version 14
OK: Loaded parser for help: ABI version 14
```

### Output of `nvim --version`

```text
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.2/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
What does 
```vim
:echo nvim_get_runtime_file('*/help.so', v:true)
```
report?

**Comment by clason** [comment]
Well, there you go, just delete the first one.

**Comment by stoddart** [comment]
> Well, there you go, just delete the first one.

I tried to do that, but when I did, it warned me not to delete root/wheel files, which I took seriously. Is that what I'm supposed to do?

**Comment by clason** [comment]
What? How is a file in your user directory a `root/wheel` file?

**Comment by stoddart** [comment]
> What? How is a file in your user directory a `root/wheel` file?

You're right. I was looking in the wrong directory. Thanks!

**Comment by stoddart** [comment]
I closed this, but I still think that this is not something that users should have to do. It should not be the case that users need to add the parsers to `ignore_installed`.

**Comment by clason** [comment]
>  It should not be the case that users need to add the parsers to ignore_installed.

They don't. Normally, nvim-treesitter only installs the parsers you tell it to via `ensure_installed`. So you must be doing something else in your config (which you did not share) that installs these parsers.

**Comment by stoddart** [comment]
Are not those four parsers installed by default?

**Comment by clason** [comment]
Not by nvim-treesitter, no. (They're bundled with Neovim, which places them in `/usr/local/lib/nvim/parser/`.)

**Comment by stoddart** [comment]
Here's my config: https://github.com/stoddart/.config-nvim
