### ISSUE TITLE
Mingw Windows 10 TSInstall fails to compile

### ISSUE THREAD

**Issue by TimUntersberger** [nvim-treesitter/nvim-treesitter#413]
**Describe the bug**
`:TSInstall lua` fails to compile.

**To Reproduce**
1. Install MingW on Windows 10 
2. refreshenv
3. start nvim in refreshed environment
4. `:TSInstall lua`

**Expected behavior**

Installs correctly.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - ERROR: `cc` executable not found.
    - ADVICE:
      - Install `gcc` with your package manager.
      - Install `clang` with your package manager.
      - Check that your `$PATH` is set correctly.

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-659-g7b1b271f4
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

**Additional context**
I installed mingw using `choco install mingw`. This only installed `gcc` and not `cc`.

**Comment by theHamsta** [comment]
We also check for `gcc`. I installed it with gcc only using a NeovimQt with a plugin version version prior to #391 . Can you try 930591b6896b5142ff2b5d9f66072e3472841c55

**Comment by TimUntersberger** [comment]
> Can you maybe try to compile with gcc when you directly clone tree-sitter-lua

I can compile it manually.

**Comment by TimUntersberger** [comment]
Oh I found the problem. I can compile it using `TSInstall` when Neovim is running  `cmd`, but not in `powershell`.

**Comment by theHamsta** [comment]
At which step does it fail? The compile step? May it be because of the path separators?

**Comment by TimUntersberger** [comment]
It fails with `Error during compilation`

**Comment by TimUntersberger** [comment]
Path separator seems to be ok. I'll try to find the problem.

**Comment by TimUntersberger** [comment]
The `cmd` one actually also has the same separators.

**Comment by theHamsta** [comment]
Before #391, I didn't call `cmd` explicitly.  I though that the separators in the compile command may be shell dependent. So you can fix the problem by using `\\`?

**Comment by TimUntersberger** [comment]
I just restarted my computer and now the `powershell` one also works. The problem is that I followed the steps in the Windows page and even ran `refreshenv` multiple times in `cmd` and `powershell`, but it still only worked after a reboot. I don't really know what caused this. 

Maybe add to the `Windows` page that you might have to restart your computer if it doesn't work after installing `mingw`, so no one else opens an issue for this.

Sorry!

**Comment by theHamsta** [comment]
You can just edit the Wiki!

**Comment by TimUntersberger** [comment]
> If the problem was the environment, why wasn't the error message couldn't find a compiler?

I'm sorry. I really have no idea.

**Comment by theHamsta** [comment]
Maybe there's some magic necessary for gcc to find it's stdlib and stuff...

**Comment by theHamsta** [comment]
`:TSInstallSync lua` does not work at the moment. This is partially because the the `cmd` in `get_command` is not escaped like that: https://github.com/theHamsta/nvim-treesitter/blob/ci/lua/nvim-treesitter/install.lua but also because the clone command return imediatelly without being finished.
