### ISSUE TITLE
offer `prefer_git` as an user option

### ISSUE THREAD

**Issue by ZhiyuanLck** [nvim-treesitter/nvim-treesitter#4139]
I'm using nvim in the environment without external internet connection, but it is allowed to clone repos from github. To clone and compile parsers, I have to change the lua scripts `lua/nvim-treesitter/install.lua`: change `M.prefer_git = fn.has "win32" == 1` to `M.prefer_git = true` to make it work.

It will be better if `prefer_git` is an alternative option for user.

**Comment by theHamsta** [comment]
You can also execute.

```
require "nvim-treesitter.install".prefer_git = true
```

No need to change the source code. It is mainly explained in the Windows wiki where this option is most relevant.
