### ISSUE TITLE
Markdown strikethrough and quote highlights are not working

### ISSUE THREAD

**Issue by UtkarshVerma** [nvim-treesitter/nvim-treesitter#4150]
### Describe the bug

Strikethrough text and quotes are not detected by the parser.

![image](https://user-images.githubusercontent.com/31820255/212010314-d769ff8b-fd39-4b69-b13f-cba8e380fc8d.png)

![image](https://user-images.githubusercontent.com/31820255/212010373-df909daa-b22e-438b-ae3a-2aa5a63029f7.png)

### To Reproduce

Here is my sample file:
````md
# This is a heading
This is some text.

## This is some bold text
This is some **bold** text. Some *italics* and ~~strikethrough~~ as well.

> a This is inline quote

```c
printf("Hello, world!\n");
```
````

### Expected behavior

Strikethrough text should have the strikethrough group. Same for the quotes.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v19.3.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "6.1.3-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Wed, 04 Jan 2023 16:28:15 +0000"
}

## Parser/Features H L F I J
  - query          ✓ ✓ ✓ ✓ ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - java           ✓ ✓ . ✓ ✓
  - help           ✓ . . . ✓
  - go             ✓ ✓ ✓ ✓ ✓
  - yaml           ✓ ✓ ✓ ✓ ✓
  - arduino        ✓ ✓ ✓ ✓ ✓
  - markdown_inline✓ . . . ✓
  - vim            ✓ ✓ ✓ . ✓
  - tsx            ✓ ✓ ✓ ✓ ✓
  - html           ✓ ✓ ✓ ✓ ✓
  - bash           ✓ ✓ ✓ . ✓
  - gomod          ✓ . . . ✓
  - markdown       ✓ . ✓ . ✓
  - latex          ✓ . ✓ . ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - typescript     ✓ ✓ ✓ ✓ ✓
  - json           ✓ ✓ ✓ ✓ .
  - cpp            ✓ ✓ ✓ ✓ ✓
  - gowork         ✓ . . . ✓
  - rust           ✓ ✓ ✓ ✓ ✓
  - javascript     ✓ ✓ ✓ ✓ ✓
  - regex          ✓ . . . .

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
Please check the playground whether the markdown_inline parser supports these nodes, otherwise there's nothing we can do here.

**Comment by clason** [comment]
These nodes _are_ captured by the parser (as `strikethrough` and `block_quote`). They are just not captured by default since there's no sensible default capture -- how would you expect them to be highlighted?

**Comment by clason** [comment]
All this is to say: PR welcome :)

**Comment by theHamsta** [comment]
> These nodes _are_ captured by the parser (as `strikethrough` and `block_quote`). They are just not captured by default since there's no sensible default capture -- how would you expect them to be highlighted?

I would expect it. A PR `@text.strikethrough` for would be welcome

**Comment by clason** [comment]
`@text.strike` already exists in CONTRIBUTING.md; the question is how to highlight block quotes (`@text.quote`?)

**Comment by UtkarshVerma** [comment]
Blockquote is a bit confusing. I would prefer the text to be a bit dimmed. Also, I noticed that `@text.uri` is also not working for markdown.

![image](https://user-images.githubusercontent.com/31820255/212256907-b8fda586-3c7b-47bb-b172-8a5f91b024a6.png)

**Comment by clason** [comment]
That's just inline text; the markdown parser doesn't parse this as a special URL node (only in actual links).
