### ISSUE TITLE
nvim-treesitter[lua]: Error during compilation

### ISSUE THREAD

**Issue by da-the-dev** [nvim-treesitter/nvim-treesitter#4168]
### Describe the bug

nvim-treesitter[lua]: Error during compilation
/usr/bin/ld: cannot find -lstdc++: No such file or directory
collect2: error: ld returned 1 exit status
Press ENTER or type command to continue
Press ENTER or type command to continue
[nvim-treesitter] [1/12, failed: 1] Extracting tree-sitter-tsx...
Press ENTER or type command to continue
nvim-treesitter[json]: Error during compilation
/usr/bin/ld: cannot find -lstdc++: No such file or directory
collect2: error: ld returned 1 exit status
Press ENTER or type command to continue
Press ENTER or type command to continue
[nvim-treesitter] [2/12, failed: 2] Creating temporary directory
Press ENTER or type command to continue
nvim-treesitter[yaml]: Error during compilation
cc: fatal error: cannot execute ‘cc1plus’: execvp: No such file or directory
compilation terminated.
Press ENTER or type command to continue
Press ENTER or type command to continue
[nvim-treesitter] [3/12, failed: 3] Creating temporary directory
Press ENTER or type command to continue
[nvim-treesitter] [3/12, failed: 3] Creating temporary directory
Press ENTER or type command to continue
nvim-treesitter[css]: Error during compilation
/usr/bin/ld: cannot find -lstdc++: No such file or directory
collect2: error: ld returned 1 exit status
Press ENTER or type command to continue
Press ENTER or type command to continue
nvim-treesitter[c]: Error during compilation
/usr/bin/ld: cannot find -lstdc++: No such file or directory
collect2: error: ld returned 1 exit status
Press ENTER or type command to continue
Press ENTER or type command to continue
nvim-treesitter[java]: Error during compilation
/usr/bin/ld: cannot find -lstdc++: No such file or directory
collect2: error: ld returned 1 exit status
Press ENTER or type command to continue
Press ENTER or type command to continue
[nvim-treesitter] [6/12, failed: 6] Compiling...
Press ENTER or type command to continue
[nvim-treesitter] [6/12, failed: 6] Extracting tree-sitter-bash...
Press ENTER or type command to continue

### To Reproduce

1. I've installed LunarVim on fresh Fedora Linux and launched it

### Expected behavior

LunarVim should work with no issues

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.13.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/builddir/build/BUILD/neovim-0.8.2/redhat-linux-build/cmake.config -I/builddir/build/BUILD/neovim-0.8.2/src -I/usr/include -I/usr/include/luajit-2.1 -I/builddir/build/BUILD/neovim-0.8.2/redhat-linux-build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.8.2/redhat-linux-build/include
Compiled by mockbuild@koji

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by da-the-dev** [comment]
I didn't have any C++ compiler installed on the system, since it's fresh. It's fixed with installing one     
`sudo dnf install gcc-c++`

**Comment by purplewazard** [comment]
this fixed it for me
