### ISSUE TITLE
Error when using bash for PKGBUILD files with highlight_definitions

### ISSUE THREAD

**Issue by Conni2461** [nvim-treesitter/nvim-treesitter#418]
**Describe the bug**
When using bash is installed and `refactor.highlight_definitions` is enabled `PKGBUILD` files throw errors every time the `CursorHold` autocmd is triggered. Since `PKGBUILD` files are also just shell scripts the bug goes away when filetype `sh` is set.
Disabling `refactor.highlight_definitions` fixes this issue aswell.

**To Reproduce**
1. Minimal vimrc
```viml
" Required to setup PKGBUILD filetype
set runtimepath+=/usr/share/vim/vimfiles

call plug#begin('~/.config/nvim/plugged')
	Plug 'nvim-treesitter/nvim-treesitter'
call plug#end()

lua << EOF
require'nvim-treesitter.configs'.setup {
	highlight = {
		enable = true,
	},
	refactor = {
		highlight_definitions = {
			enable = true
		},
	},
	ensure_installed = 'bash'
}
EOF
```
The vim files which are called are installed with the `pacman-contrib` package and can be found [here](https://git.archlinux.org/pacman-contrib.git/tree/src/vim)
2. Open PKGBUILD file. Example can be found here: [neovim PKGBUILD](https://github.com/archlinux/svntogit-community/blob/packages/neovim/trunk/PKGBUILD)
3. Experience Error, when moving cursor over any var definition. E.g. `pkgname`
```
Error detected while processing CursorHold Autocommands for "<buffer=1>":
E5108: Error executing lua ...im/plugged/nvim-treesitter/lua/nvim-treesitter/query.lua:261: attempt to call a nil v
alue
```

**Expected behavior**
`refactor.highlight_definitions` works like in every other shell script.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## c parser healthcheck
  - OK: c parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.
  - OK: `fold.scm` found.

## java parser healthcheck
  - OK: java parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for java
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `fold.scm` query found for java
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## python parser healthcheck
  - OK: python parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.
  - OK: `fold.scm` found.

## lua parser healthcheck
  - OK: lua parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.
  - OK: `fold.scm` found.

## go parser healthcheck
  - OK: go parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.
  - WARNING: No `fold.scm` query found for go
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## yaml parser healthcheck
  - OK: yaml parser found.
  - WARNING: No `highlights.scm` query found for yaml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `locals.scm` query found for yaml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for yaml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `fold.scm` query found for yaml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## json parser healthcheck
  - OK: json parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for json
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for json
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `fold.scm` query found for json
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## html parser healthcheck
  - OK: html parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for html
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `fold.scm` query found for html
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## typescript parser healthcheck
  - OK: typescript parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.
  - OK: `fold.scm` found.

## cpp parser healthcheck
  - OK: cpp parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.
  - OK: `fold.scm` found.

## ruby parser healthcheck
  - OK: ruby parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for ruby
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `fold.scm` query found for ruby
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## scala parser healthcheck
  - OK: scala parser found.
  - WARNING: No `highlights.scm` query found for scala
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `locals.scm` query found for scala
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for scala
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `fold.scm` query found for scala
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## rust parser healthcheck
  - OK: rust parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.
  - WARNING: No `fold.scm` query found for rust
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## bash parser healthcheck
  - OK: bash parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for bash
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `fold.scm` query found for bash
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## c_sharp parser healthcheck
  - OK: c_sharp parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for c_sharp
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - OK: `textobjects.scm` found.
  - WARNING: No `fold.scm` query found for c_sharp
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## rst parser healthcheck
  - OK: rst parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.
  - WARNING: No `fold.scm` query found for rst
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## css parser healthcheck
  - OK: css parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for css
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for css
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `fold.scm` query found for css
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## javascript parser healthcheck
  - OK: javascript parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.
  - OK: `fold.scm` found.

## toml parser healthcheck
  - OK: toml parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for toml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `fold.scm` query found for toml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## regex parser healthcheck
  - OK: regex parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for regex
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for regex
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `fold.scm` query found for regex
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-672-gd8e6a0396
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/conni/.cache/yay/neovim-git/src/build/config -I/home/conni/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/conni/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/conni/.cache/yay/neovim-git/src/build/include
Compiled by conni@home

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Additional context**
Nvim-Treesitter is also up to date.

**Comment by vigoux** [comment]
Hi, and thanks for reporting.

What feels weird to me is that it looks like the filetype for `PKGBUILD` are not set ?

**Comment by Conni2461** [comment]
I'm not sure what you mean.

When I open the PKGBUILD file without the vim files provided by `pacman-contrib` loaded, the filetype is `sh`. (Everything works fine)
With the vim files loaded, the filetype is `PKGBUILD`. (Produces error)

**Comment by kyazdani42** [comment]
this might come from another plugin then, we do not modify the filetype of buffers.

**Comment by theHamsta** [comment]
We had a similar situation where we attached to tsx buffer but a plugin then changed the filetype to `typescript.react` and cause a similar nil error.

**Comment by Conni2461** [comment]
Yeah i know that. I mention it in my Bug report.
It's this [file](https://git.archlinux.org/pacman-contrib.git/tree/src/vim/ftdetect/PKGBUILD.vim) which is provided by a arch package, which provides a bunch of tools for package management. (So i can't get rid of this package)
I thought you could make it work, without me having to work around with `autocmd! BufEnter,BufNewFile,BufRead PKGBUILD set filetype=sh`.

If that is not possible, that is totally fine.
Either way thanks for your time looking into this.

**Comment by vigoux** [comment]
The `PKGBUILD` filetype is not really standard and don't have a parser for it, the thing so, it that we should not error out when encountering such filetypes.

**Comment by theHamsta** [comment]
There should not be an error. Either we always continue the ft we attached to or we detach whenever we detect that the filetype changed. Or silently not execute that query request, should not be difficult to add a nil check. @Conni2461 can you send us your the line the error message points to? The current version of `query.lua` does not have 261 lines anymore (line 261 is the penultimate line).

**Comment by Conni2461** [comment]
Sure new line is:
```
Error detected while processing CursorHold Autocommands for "<buffer=1>":
E5108: Error executing lua ...im/plugged/nvim-treesitter/lua/nvim-treesitter/query.lua:256: attempt to call a nil value
```

**Comment by theHamsta** [comment]
Does #422 help? I guess the problem is that the iterator function returns nil instead of an empty iterator when the file lang has changed and there is not longer a parser.

What is the excact filetype name for PKGCONFIG. Should we add it to `used_by` form the shell parser.

**Comment by Conni2461** [comment]
Yes #422 fixes the issue. Thank you.

Filetype is `PKGBUILD`and yes if you would add it that would be perfect.
