### ISSUE TITLE
Trees sitter fails to compile

### ISSUE THREAD

**Issue by Roiqk7** [nvim-treesitter/nvim-treesitter#4180]
### Describe the bug

I have tried everything written and browsed several forums and nothing helped. Every time I open nvim I get error message from tree sitter stating that it failed due to being c++14 extension. When I tried two change compiler argument to "std=c++17" I get error that this does not work for c lang. 

### To Reproduce

x

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v19.4.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 14.0.0 (clang-1400.0.29.202)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "arm64",
  release = "22.2.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.2.0: Fri Nov 11 02:06:26 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8112"
}

## Parser/Features         H L F I J
  - markdown_inline     ✓ . . . ✓
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓
  - nix                 ✓ ✓ ✓ . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ . ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - svelte              ✓ . ✓ ✓ ✓
  - vue                 ✓ . ✓ ✓ ✓
  - help                ✓ . . . ✓
  - json                ✓ ✓ ✓ ✓ .
  - vim                 ✓ ✓ ✓ . ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - glsl                ✓ ✓ ✓ ✓ ✓
  - dockerfile          ✓ . . . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - comment             ✓ . . . .
  - fusion              ✓ ✓ ✓ ✓ .
  - bash                ✓ ✓ ✓ . ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - c_sharp             ✓ ✓ ✓ . ✓
  - llvm                ✓ . . . .
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ .
  - blueprint           ✓ . . . .
  - graphql             ✓ . . ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - gitignore           ✓ . . . .
  - javascript          ✓ ✓ ✓ ✓ ✓
  - java                ✓ ✓ . ✓ ✓
  - cmake               ✓ . ✓ . .
  - zig                 ✓ . ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.2/share/nvim"

Run :checkhealth for more info
```

**Comment by theHamsta** [comment]
Which language?

Please be aware that we don't set any language standard as we compile C and C++ in a single command. The simple solution is to use a compiler that uses the required language standard as default. You might also compile using `make` which set language standards.

Set `use_makefile = true` to the `install_info` of your language that you want to compile. Use `require "nvim-treesitter.parsers".get_parser_configs()`  similar as in https://github.com/nvim-treesitter/nvim-treesitter/blob/42c3a3c51e8fef027655e7facd293aae7c6984bb/README.md#L451-L463 but by changing the config for your language instead of adding a new one.

>     Version: Apple clang version 14.0.0 (clang-1400.0.29.202)

Yes, Apple clang is always a bit conservative about C++ standards.

**Comment by Roiqk7** [comment]
I am not gonna lie but I would like you to be more precise in your description because I do not understand your provided solution please.

**Comment by theHamsta** [comment]
> I am not gonna lie but I would like you to be more precise in your description because I do not understand your provided solution please.

What language are you trying to compile? And what is the compiler output? To compile most parsers correctly your compiler needs to assume at least c++-11 as default. That a parser requires c++14 would be new to me but is of course possible.


I referenced the code where we invoke the compiler or compile with a makefile. This might help when you want to fix the issue yourself. To find a general solution we need to know what language you are trying to compile 
https://github.com/nvim-treesitter/nvim-treesitter/blob/42c3a3c51e8fef027655e7facd293aae7c6984bb/lua/nvim-treesitter/shell_command_selectors.lua#L117-L147

**Comment by Roiqk7** [comment]
nvim-treesitter[norg]: Error during compilation
src/scanner.cc:176:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class TagType : char
     ^
src/scanner.cc:194:10: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    for (auto& elem : vec)
         ^
src/scanner.cc:194:21: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
    for (auto& elem : vec)
                    ^
src/scanner.cc:213:16: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    m_Previous = 0,  // previous char
               ^
src/scanner.cc:214:15: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    m_Current = 0;   // current char
              ^
src/scanner.cc:216:26: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    TagType m_TagContext = TagType::NONE;
                         ^
src/scanner.cc:217:23: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    size_t m_TagLevel = 0;
                      ^
src/scanner.cc:219:27: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    bool m_InLinkLocation = false;
                          ^
src/scanner.cc:223:27: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    TokenType m_LastToken = NONE;
                          ^
src/scanner.cc:226:26: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    size_t m_ParsedChars = 0;
                         ^
src/scanner.cc:228:50: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    const array<int32_t, 12> m_DetachedModifiers = {
                                                 ^
src/scanner.cc:243:74: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    const unordered_map<int32_t, TokenType> m_DetachedModifierExtensions = {
                                                                         ^
src/scanner.cc:256:65: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    const unordered_map<int32_t, TokenType> m_AttachedModifiers = {
                                                                ^
src/scanner.cc:811:6: error: expected expression
    [[nodiscard]]
     ^
src/scanner.cc:812:5: error: expected member name or ';' after declaration specifiers
    bool check_detached(const vector<TokenType>& results, const int32_t expected)
    ^
src/scanner.cc:216:28: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
    TagType m_TagContext = TagType::NONE;
                           ^
src/scanner.cc:243:76: error: non-aggregate type 'const unordered_map<int32_t, TokenType>' (aka 'const unordered_map<int, TokenType>') cannot be initialized with an initializer list
    const unordered_map<int32_t, TokenType> m_DetachedModifierExtensions = {
                                                                           ^
src/scanner.cc:256:67: error: non-aggregate type 'const unordered_map<int32_t, TokenType>' (aka 'const unordered_map<int, TokenType>') cannot be initialized with an initializer list
    const unordered_map<int32_t, TokenType> m_AttachedModifiers = {
                                                                  ^
src/scanner.cc:272:13: error: use of undeclared identifier 'reset_active_modifiers'
            reset_active_modifiers();
            ^
src/scanner.cc:279:20: error: use of undeclared identifier 'parse_text'
            return parse_text();
                   ^
src/scanner.cc:281:18: error: use of undeclared identifier 'is_newline'
        else if (is_newline(lexer->lookahead))
                 ^
src/scanner.cc:289:17: error: use of undeclared identifier 'reset_active_modifiers'
                reset_active_modifiers();              
                                 ^
src/scanner.cc:293:33: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
            if (m_TagContext != TagType::NONE && ((char)m_TagContext % 2) == 0)
                                ^
src/scanner.cc:299:17: error: use of undeclared identifier 'is_newline'
            if (is_newline(lexer->lookahead))
                ^
src/scanner.cc:303:17: error: use of undeclared identifier 'reset_active_modifiers'
                reset_active_modifiers();
                ^
src/scanner.cc:313:20: error: use of undeclared identifier 'is_blank'
            while (is_blank(lexer->lookahead))
                   ^
src/scanner.cc:329:28: error: use of undeclared identifier 'is_blank'
                    while (is_blank(lexer->lookahead))
                           ^
src/scanner.cc:333:44: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
                        && m_TagContext == TagType::IN_VERBATIM_TAG)
                                           ^
src/scanner.cc:336:40: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
                        m_TagContext = TagType::NONE;
                                       ^
src/scanner.cc:345:75: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
                if (m_LastToken == RANGED_VERBATIM_TAG || m_TagContext == TagType::IN_VERBATIM_TAG)
                                                                          ^
src/scanner.cc:353:32: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
                m_TagContext = TagType::ON_VERBATIM_TAG;
                               ^
src/scanner.cc:357:33: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
            if (m_TagContext == TagType::IN_VERBATIM_TAG)
                                ^
src/scanner.cc:358:24: error: use of undeclared identifier 'parse_text'
                return parse_text();
                       ^
src/scanner.cc:361:60: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
            if (lexer->lookahead == '=' && m_TagContext != TagType::IN_VERBATIM_TAG)
                                                           ^
src/scanner.cc:374:32: error: use of undeclared identifier 'is_newline'
                           && !is_newline(lexer->lookahead))
                               ^
src/scanner.cc:397:29: error: use of undeclared identifier 'is_newline'
                        if (is_newline(lexer->lookahead))
                            ^
src/scanner.cc:432:32: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
                m_TagContext = TagType::ON_TAG;
                               ^
src/scanner.cc:437:65: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
            else if (lexer->lookahead == '|' && m_TagContext != TagType::IN_VERBATIM_TAG)
                                                                ^
src/scanner.cc:449:28: error: use of undeclared identifier 'is_blank'
                    while (is_blank(lexer->lookahead))
                           ^
src/scanner.cc:473:32: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
                m_TagContext = TagType::ON_TAG;
                               ^
src/scanner.cc:478:65: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
            else if (lexer->lookahead == '#' && m_TagContext != TagType::IN_VERBATIM_TAG)
                                                                ^
src/scanner.cc:484:25: error: use of undeclared identifier 'is_newline'
                    if (is_newline(lexer->lookahead))
                        ^
src/scanner.cc:496:65: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
            else if (lexer->lookahead == '+' && m_TagContext != TagType::IN_VERBATIM_TAG)
                                                                ^
src/scanner.cc:506:65: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
            else if (lexer->lookahead == '.' && m_TagContext != TagType::IN_VERBATIM_TAG)
                                                                ^
src/scanner.cc:525:32: error: expected expression
            if (check_detached({HEADING1, HEADING2, HEADING3,
                               ^
src/scanner.cc:530:32: error: expected expression
            if (check_detached({QUOTE1, QUOTE2, QUOTE3, QUOTE4, QUOTE5, QUOTE6}, '>'))
                               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
27 warnings and 20 errors generated

**Comment by Roiqk7** [comment]
This is the entire error message. Hope it is helpful.

**Comment by Roiqk7** [comment]
Also I tried adding compiler flags to use c++ 14 and it says you can't use it for c and when I tried to force c99 it said you can't do it for c++ so we are compiling both c/c++

**Comment by theHamsta** [comment]
Ok, your compiler doesn't even assume C++. Do you use `norg`?

What happens when you do
```
local parser_configs = require("nvim-treesitter.parsers").get_parser_configs()
parser_configs.norg = {
  install_info = {
    url = "https://github.com/nvim-neorg/tree-sitter-norg",
    files = { "src/parser.c", "src/scanner.cc" },
    branch = "main",
   use_makefile = true, --- add this line
  },
} 
```
in your config
or
```
for _, parser in ipairs(require'nvim-treesitter.parsers'.get_parser_configs()) do
  parser.install_info.use_makefile = true
end
```
for all parsers

**Comment by Roiqk7** [comment]
nvim-treesitter[norg]: Error during compilation
src/scanner.cc:176:6: warning: scoped enumerations are a C++11 extension [-Wc++11-extensions]
enum class TagType : char
     ^
src/scanner.cc:194:10: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    for (auto& elem : vec)
         ^
src/scanner.cc:194:21: warning: range-based for loop is a C++11 extension [-Wc++11-extensions]
    for (auto& elem : vec)
                    ^
src/scanner.cc:213:16: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    m_Previous = 0,  // previous char
               ^
src/scanner.cc:214:15: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    m_Current = 0;   // current char
              ^
src/scanner.cc:216:26: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    TagType m_TagContext = TagType::NONE;
                         ^
src/scanner.cc:217:23: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    size_t m_TagLevel = 0;
                      ^
src/scanner.cc:219:27: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    bool m_InLinkLocation = false;
                          ^
src/scanner.cc:223:27: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    TokenType m_LastToken = NONE;
                          ^
src/scanner.cc:226:26: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    size_t m_ParsedChars = 0;
                         ^
src/scanner.cc:228:50: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    const array<int32_t, 12> m_DetachedModifiers = {
                                                 ^
src/scanner.cc:243:74: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    const unordered_map<int32_t, TokenType> m_DetachedModifierExtensions = {
                                                                         ^
src/scanner.cc:256:65: warning: default member initializer for non-static data member is a C++11 extension [-Wc++11-extensions]
    const unordered_map<int32_t, TokenType> m_AttachedModifiers = {
                                                                ^
src/scanner.cc:811:6: error: expected expression
    [[nodiscard]]
     ^
src/scanner.cc:812:5: error: expected member name or ';' after declaration specifiers
    bool check_detached(const vector<TokenType>& results, const int32_t expected)
    ^
src/scanner.cc:216:28: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
    TagType m_TagContext = TagType::NONE;
                           ^
src/scanner.cc:243:76: error: non-aggregate type 'const unordered_map<int32_t, TokenType>' (aka 'const unordered_map<int, TokenType>') cannot be initialized with an initializer list
    const unordered_map<int32_t, TokenType> m_DetachedModifierExtensions = {
                                                                           ^
src/scanner.cc:256:67: error: non-aggregate type 'const unordered_map<int32_t, TokenType>' (aka 'const unordered_map<int, TokenType>') cannot be initialized with an initializer list
    const unordered_map<int32_t, TokenType> m_AttachedModifiers = {
                                                                  ^
src/scanner.cc:272:13: error: use of undeclared identifier 'reset_active_modifiers'
            reset_active_modifiers();
            ^
src/scanner.cc:279:20: error: use of undeclared identifier 'parse_text'
            return parse_text();
                   ^
src/scanner.cc:281:18: error: use of undeclared identifier 'is_newline'
        else if (is_newline(lexer->lookahead))
                 ^
src/scanner.cc:289:17: error: use of undeclared identifier 'reset_active_modifiers'
                reset_active_modifiers();
                ^
src/scanner.cc:293:33: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
            if (m_TagContext != TagType::NONE && ((char)m_TagContext % 2) == 0)
                                ^
src/scanner.cc:299:17: error: use of undeclared identifier 'is_newline'
            if (is_newline(lexer->lookahead))
                ^
src/scanner.cc:303:17: error: use of undeclared identifier 'reset_active_modifiers'
                reset_active_modifiers();
                ^
src/scanner.cc:313:20: error: use of undeclared identifier 'is_blank'
            while (is_blank(lexer->lookahead))
                   ^
src/scanner.cc:329:28: error: use of undeclared identifier 'is_blank'
                    while (is_blank(lexer->lookahead))
                           ^
src/scanner.cc:333:44: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
                        && m_TagContext == TagType::IN_VERBATIM_TAG)
                                           ^
src/scanner.cc:336:40: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
                        m_TagContext = TagType::NONE;
                                       ^
src/scanner.cc:345:75: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
                if (m_LastToken == RANGED_VERBATIM_TAG || m_TagContext == TagType::IN_VERBATIM_TAG)
                                                                          ^
src/scanner.cc:353:32: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
                m_TagContext = TagType::ON_VERBATIM_TAG;
                               ^
src/scanner.cc:357:33: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
            if (m_TagContext == TagType::IN_VERBATIM_TAG)
                                ^
src/scanner.cc:358:24: error: use of undeclared identifier 'parse_text'
                return parse_text();
                       ^
src/scanner.cc:361:60: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
            if (lexer->lookahead == '=' && m_TagContext != TagType::IN_VERBATIM_TAG)
                                                           ^
src/scanner.cc:374:32: error: use of undeclared identifier 'is_newline'
                           && !is_newline(lexer->lookahead))
                               ^
src/scanner.cc:397:29: error: use of undeclared identifier 'is_newline'
                        if (is_newline(lexer->lookahead))
                            ^
src/scanner.cc:432:32: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
                m_TagContext = TagType::ON_TAG;
                               ^
src/scanner.cc:437:65: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
            else if (lexer->lookahead == '|' && m_TagContext != TagType::IN_VERBATIM_TAG)
                                                                ^
src/scanner.cc:449:28: error: use of undeclared identifier 'is_blank'
                    while (is_blank(lexer->lookahead))
                           ^
src/scanner.cc:473:32: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
                m_TagContext = TagType::ON_TAG;
                               ^
src/scanner.cc:478:65: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
            else if (lexer->lookahead == '#' && m_TagContext != TagType::IN_VERBATIM_TAG)
                                                                ^
src/scanner.cc:484:25: error: use of undeclared identifier 'is_newline'
                    if (is_newline(lexer->lookahead))
                        ^
src/scanner.cc:496:65: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
            else if (lexer->lookahead == '+' && m_TagContext != TagType::IN_VERBATIM_TAG)
                                                                ^
src/scanner.cc:506:65: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
            else if (lexer->lookahead == '.' && m_TagContext != TagType::IN_VERBATIM_TAG)
                                                                ^
src/scanner.cc:525:32: error: expected expression
            if (check_detached({HEADING1, HEADING2, HEADING3,
                               ^
src/scanner.cc:530:32: error: expected expression
            if (check_detached({QUOTE1, QUOTE2, QUOTE3, QUOTE4, QUOTE5, QUOTE6}, '>'))
                               ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
27 warnings and 20 errors generated.

**Comment by Roiqk7** [comment]
I have added the your suggestion to my config and this is the output. Now we have different errors so it seems to have helped

**Comment by theHamsta** [comment]
This seems like an issue in tree-sitter-norg. The c++ standard does not seem to matter in terms of c++11/c++14. Can you check whether c++-17 is required (c++17 was a problem with old MacOS) or whether there is a problem with their source code? You can set cxx_standard similar to the `use_makefile` property.

**Comment by Roiqk7** [comment]
I added you suggestion like this: `cxx_standard = "c++-17"` hope it is correct syntax and I added it bellow `use_make` file and it seems to have no effect possibly cause I added it wrongly.

**Comment by Roiqk7** [comment]
Also I want to confirm that norg file is the one causing problems

**Comment by theHamsta** [comment]
> Also I want to confirm that norg file is the one causing problems

Well, it says so in your logs. Again: do you use norg? Have you tried to compile norg in their repo (e.g. `npm install` or compiling scanner.cc manually?

**Comment by Roiqk7** [comment]
No I did not try it

**Comment by Roiqk7** [comment]
I will try it and let you know

**Comment by Roiqk7** [comment]
I fixed it by installing neorg. Thanks

**Comment by theHamsta** [comment]
Neorg also has a troube shooting section regarding C++14 on MacOS: https://github.com/nvim-neorg/neorg#troubleshooting-treesitter

Will close now
