### ISSUE TITLE
Neovim freezes when trying to parse a cpp file

### ISSUE THREAD

**Issue by alfaix** [nvim-treesitter/nvim-treesitter#4221]
### Describe the bug

Hey! I've been fiddling with parsing Google Test tests (C++) via treesitter and discovered a file that causes neovim to freeze.

When trying to parse [this specific file](https://github.com/google/googletest/blob/main/googletest/test/gtest_test_macro_stack_footprint_test.cc) neovim freezes. It parses and highlights in a window just fine, but specifically when parsing it with neovim treesitter api (exact invocations below), it freezes.

### To Reproduce

1. Clone [googletest](https://github.com/google/googletest) or just download [this file](https://github.com/google/googletest/blob/main/googletest/test/gtest_test_macro_stack_footprint_test.cc)
2. Put this in `somefile.lua`:
```lua
local PATH_TO_NVIM_TREESITTER="/home/alfaix/.local/share/nvim/site/pack/packer/start/nvim-treesitter"
local PATH_TO_CPP_SO="/home/alfaix/.local/share/nvim/site/pack/packer/start/cpp.so"
local PATH_TO_BAD_CC_FILE="gtest_test_macro_stack_footprint_test.cc"

local function setupTreesitter ()
  vim.opt.runtimepath:prepend(PATH_TO_NVIM_TREESITTER)
  require('nvim-treesitter.configs').setup({})
end

function Crash()
        -- you can delete this line if running with setupTreesitter(), the result does not change
	vim.treesitter.require_language("cpp", PATH_TO_CPP_SO)
	local content = table.concat(vim.fn.readfile(PATH_TO_BAD_CC_FILE), "\n")
	local parser = vim.treesitter.get_string_parser(content, "cpp", nil)
	print("THIS LINE WILL BE PRINTED")
	parser:parse()
	error("WILL NOT BE REACHED")
end
-- !!! if you comment out this line, the code works as expected
setupTreesitter()
```
3. Set the first three variables to point to things that they should point to. `cpp.so` can be found inside `nvim-treesitter/parser`
4. run `nvim --clean somefile.lua`
5. run `:sorce %`
6. run `:lua Crash()`
7. "THIS LINE WILL BE PRINTED" is printed, but "WILL NOT BE REACHED" error is not thrown. Neovim freezes on `parser:parse()` step.

### Expected behavior

When doing the steps above, the script should fail with an error "WILL NOT BE REACHED".

Instead, neovim freezes completely.

**Important notes**:
* Removing `neovim-treesitter` from the equation solves the issue. The error is thrown, as expected. Therefore, the issue, I believe, is in this plugin.
* I have tested this script with a few versions of neovim (recent master commits + most recent release), and that behavior does not change.
* It only happens when parsing that specific file. With other files it works fine, and I have not been able to figure out what exact part of the file causes it (yet). I'll investigate this further and try to come up with as small a file as possible.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v12.22.6 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 12.1.0-2ubuntu1~22.04) 12.1.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.15.0-58-generic",
  sysname = "Linux",
  version = "#64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023"
} ~

Parser/Features         H L F I J
  - cmake               ✓ . ✓ . .
  - vim                 ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - java                ✓ ✓ . ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - help                ✓ . . . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.0-dev-15394b685
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g  -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fno-common -fdiagnostics-color=always -fstack-protector-strong -DNVIM_UNIBI_HAS_VAR_FROM -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DMIN_LOG_LEVEL=3 -I/home/alfaix/dev/tmp/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/alfaix/dev/tmp/neovim/.deps/usr/include -I/home/alfaix/dev/tmp/neovim/build/src/nvim/auto -I/home/alfaix/dev/tmp/neovim/build/include -I/home/alfaix/dev/tmp/neovim/build/cmake.config -I/home/alfaix/dev/tmp/neovim/src
Compiled by alfaix@alfaix-pc

Features: +acl +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Additional context

This is very bizzare to me and I have no idea what is special about that file.
Any pointers for debugging would be very appreciated. I've been pulling my hair at this for quite some time now.

**Comment by clason** [comment]
This is almost certainly related to recursive injections (macros being highlighted using the C(++) parser itself), and that file is just cursed.

Does the error go away if you remove the `injections.scm` queries for c(pp)?

**Comment by alfaix** [comment]
Hey, thanks for such a speedy answer!
Yes, the file is certainly cursed, but I thought that treesitter doesn't expand macros so though that it shouldn't be an issue. In that sense I thought that there's nothing special about it - guess I was wrong.

Yes, removing the file helps.

**Comment by alfaix** [comment]
Is it possible to come up with a more general fix/workaround?

E.g., disable the plugin when parsing files this specific way, or at least being able to tell in advance when a file is going to cause a freeze so I can display a warning and ignore the file?

**Comment by clason** [comment]
This is something we definitely need and plan to fix, but in Neovim core, where it's already tracked: https://github.com/neovim/neovim/issues/21275

It's not clear yet how to best fix this, though (see https://github.com/neovim/neovim/pull/20712 for one attempt).

**Comment by alfaix** [comment]
Alright, I'll close this issue as a duplicate then. I think for my purposed `set_query()` will suffice.
Thanks a lot for such quick help :)

**Comment by theHamsta** [comment]
It does not freeze for me. Was this nvim version maybe before the tree-sitter C runtime updates?
