### ISSUE TITLE
How to add parser?

### ISSUE THREAD

**Issue by mrdgo** [nvim-treesitter/nvim-treesitter#4226]
**Is your feature request related to a problem? Please describe.**
When using code for robotframework, I have no highlights.

**Describe the solution you'd like**
An easy way to use the [tree-sitter-robot](https://github.com/Hubro/tree-sitter-robot)

**Describe alternatives you've considered**
Tried setting up myself, didn't work.

**Comment by clason** [comment]
Please add it to https://github.com/nvim-treesitter/nvim-treesitter/issues/2282

**Comment by amaanq** [comment]
@mrdgo Since you wrote the parser yourself, I'm assuming it's complete, or as much as it can be. If so, just submit a PR to add it!

**Comment by mrdgo** [comment]
> @mrdgo Since you wrote the parser yourself, I'm assuming it's complete, or as much as it can be. If so, just submit a PR to add it!

No, I didn't. How did you conclude that?

**Comment by amaanq** [comment]
My apologies. I misread completely, sorry!
