### ISSUE TITLE
Toggle between treesitter and legacy highlighting

### ISSUE THREAD

**Issue by lshprung** [nvim-treesitter/nvim-treesitter#4232]
I would like to be able to toggle between treesitter highlighting and legacy syntax highlighting. My treesitter configuration sets the highlight module to disabled by default. Running `:TSEnable highlight` will enable treesitter highlighting as expected, however running `:TSDisable highlight` will result in no highlighting whatsoever, rather than reverting to legacy syntax highlighting as expected.

My treesitter configuration:

```lua
local configs = require("nvim-treesitter.configs")
configs.setup {
  ensure_installed = "",
  sync_install = false,
  ignore_install = { "" }, -- List of parsers to ignore installing
  highlight = {
    enable = false, -- false will disable the whole extension
    disable = { "" }, -- list of language that will be disabled
    additional_vim_regex_highlighting = true,

  },
  indent = { enable = false, },
}
```

**Comment by clason** [comment]
This is a bug in Neovim core that is already fixed on master. You can download a nightly build to use it.
