### ISSUE TITLE
nvim-treesitter[markdown]: Error during tarball extraction. tar: Error opening archive: Failed to open 'tree-sitter-markdown.tar.gz'

### ISSUE THREAD

**Issue by nyngwang** [nvim-treesitter/nvim-treesitter#4250]
### Describe the bug

```
17:12:56 msg_show [nvim-treesitter] [0/2] Downloading tree-sitter-markdown...
17:12:57 msg_show [nvim-treesitter] [0/2] Creating temporary directory
17:12:57 msg_show [nvim-treesitter] [0/2] Extracting tree-sitter-markdown...
17:12:57 msg_show [nvim-treesitter] [0/2] Compiling...
17:12:57 msg_show [nvim-treesitter] [0/2] Creating temporary directory
17:12:57 msg_show [nvim-treesitter] [0/2] Extracting tree-sitter-markdown...
   Error  17:12:57 msg_show.emsg nvim-treesitter[markdown]: Error during tarball extraction.
17:12:57 msg_show tar: Error opening archive: Failed to open 'tree-sitter-markdown.tar.gz'
   Error  17:12:58 msg_show.emsg [nvim-treesitter] [2/2, failed: 1] Treesitter parser for markdown has been installed
```

### To Reproduce

1. remove all parsers by `TSUninstall all`.
2. use `auto_install = true`.
3. open any session with a markdown file.

### Expected behavior

No error installing tree-sitter-markdown

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v16.15.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 14.0.0 (clang-1400.0.29.202)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "22.3.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.3.0: Wed Dec 21 21:59:24 PST 2022; root:xnu-8792.80.25.121.4~2/RELEASE_ARM64_T8103"
} ~

Parser/Features         H L F I J
  - help                ✓ . . . ✓
  - vim                 ✓ ✓ ✓ . ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - c                   ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.0-dev-844+gb649a96fc
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by clason** [comment]
Probably https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/

In any case, this is a transient problem with Github that happens once in a while and we can do nothing about; just try again in a little while.

**Comment by jose-lpa** [comment]
Was this fixed at all? I am still seeing a lot of similar errors for multiple parsers: `nvim-treesitter[comment]`, `nvim-treesitter[make]`, `nvim-treesitter[markdown]`, `nvim-treesitter[regex]`... Is this related to the GitHub issue, or am I doing something else wrong?

**Comment by theHamsta** [comment]
This shouldn't be related to GitHub. GitHub didn't change commit checksums. The readme explains how to use git instead of curl. Maybe this can help debugging the issue.

The creator of this issue let's somehow two installations of tree-sitter-markdown race against each other (only one of them succeeds). This is not supported and maybe a configuration error. You can use vim.inspect to print the parser configuration to see whether you have any duplicates.

**Comment by jose-lpa** [comment]
> This shouldn't be related to GitHub. GitHub didn't change commit checksums. The readme explains how to use git instead of curl. Maybe this can help debugging the issue.
> 
> The creator of this issue let's somehow two installations of tree-sitter-markdown race against each other (only one of them succeeds). This is not supported and maybe a configuration error. You can use vim.inspect to print the parser configuration to see whether you have any duplicates.

Oh, I didn't know the internals of nvim-treesitter. To be honest I was just using the plugin out of the box, without configuring it. I was not aware that it can use `curl` or GitHub to fetch the parsers.

Following your advice, I looked the README and I found [how to configure it to use Git](https://github.com/nvim-treesitter/nvim-treesitter#i-want-to-use-git-instead-of-curl-for-downloading-the-parsers). And that just works! All my errors disappeared :slightly_smiling_face: 

Thank you!

**Comment by elmehdiabdi-src** [comment]
I face the same issue debug your configuration. i found a plugin glepnir/lspsaga.vim causes the problem i remove it all things fine.
