### ISSUE TITLE
dart: highlighting an assigment freezes neovim

### ISSUE THREAD

**Issue by ignatz** [nvim-treesitter/nvim-treesitter#4255]
### Describe the bug

When I type an assignment statement in dart and treesitter enabled, my vim will freeze up (spinning @100% cpu). I attached gdb but unfortunately the lua side of things is pretty intransparent, only showing the bridge suggesting that some lua is executing.

After a bit of trial and error, I narrowed it down to treesitter. Especially,

```lua
  highlight = {
    -- ...
    disable = function(lang, bufnr)
        return lang == "dart"
    end,
  },
```

avoids the isue.

I tried both nightly (0.9.0-dev) and stable (0.8.0). The result is the same.

Somewhat curious, typing:

```dart
final i = int(4);
```

from start to finish will freeze nvim as soon as I input the number. However, if I craft the line non-sequentially by turning the expression into an assignment later on, it just works fine, i.e. w/o nvim freezing up :shrug:.

I'd love to debug this more, unfortunately I'm not sure on how to introspect the lua event loop. This issue is also compounded by the fact that it seems nvim cannot cancel lua execution (I'd love to be wrong, only just switched from vim to nvim).

Thanks and cheers!

### To Reproduce

1. Open a new dart file
2. Type something like:   `final i = int(4`
3. Watch nvim freeze

### Expected behavior

no freeze :)

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v18.13.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Debian 12.2.0-14) 12.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.0.0-4-amd64",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Debian 6.0.8-1 (2022-11-11)"
} ~

Parser/Features         H L F I J
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - dart                ✓ ✓ . ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - help                ✓ . . . ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - c                   ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```
```


### Output of `nvim --version`

```text
NVIM v0.9.0-dev-843+g860fea1a3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g  -Og -g -Wall -Wextra -pedantic -Wno-unused-paramete
r -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissi
ng-prototypes -Wimplicit-fallthrough -Wvla -fno-common -fdiagnostics-color=always -fstack-protector-strong -DNVIM_MSGPACK_HAS_F
LOAT32 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DMIN_LOG_LEVEL
=3 -I/home/runner/work/neovim/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/runner/work/neovim/neovim/.deps/usr/in
clude -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include -I/home/runner/work
/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src
Compiled by runner@fv-az198-341

Features: +acl +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"
```

From the official nvim release channel. I did also try the stable release with the same result
```


### Additional context

_No response_

**Comment by ignatz** [comment]
Weirdly enough, the problem went away when I changed colorschemes. This strikes me as very surprising that the freezes depend on the colorscheme :woman_shrugging: . It might still be worth/interesting/educational to investigate given the level of weirdness. Maybe this is obvious to someone else.
In either case this is not a priority for myself and likely less for everyone else. Thus, I'll close this issue to reduce noise. Thanks!

**Comment by theHamsta** [comment]
> Weirdly enough, the problem went away when I changed colorschemes. This strikes me as very surprising that the freezes depend on the colorscheme woman_shrugging . It might still be worth/interesting/educational to investigate given the level of weirdness. Maybe this is obvious to someone else. In either case this is not a priority for myself and likely less for everyone else. Thus, I'll close this issue to reduce noise. Thanks!

Does the colorscheme add custom queries? Problematic queries can affect performance

**Comment by ignatz** [comment]
Interesting hypothesis. I took a look at the scheme: https://github.com/shaunsingh/solarized.nvim/blob/34c2245a6ddfd85766f6127768f6b04b0ae2f84a/lua/solarized/theme.lua#L206, which seems to rely on predefined highlighting groups. However, being new to nvim and treesitter, so I'm also not fully sure what i'd be looking for :).
@theHamsta I really appreciate you stepping up! That said, I also want to be mindful of your time. Thanks mate
