### ISSUE TITLE
Lspsaga hover doc throws an error

### ISSUE THREAD

**Issue by yeseongmoon** [nvim-treesitter/nvim-treesitter#4297]
### Describe the bug

I had no issue using Lspsaga doc hover before, but now I got the error message by doing it.
The error is shown below:
<img width="1440" alt="Screenshot 2023-02-12 at 12 22 35 AM" src="https://user-images.githubusercontent.com/20822372/218266597-bac8b8d1-99d4-47ee-9cf1-d65918e64295.png">

Screenshow for checkhealth nvim-treesitter:
<img width="1047" alt="Screenshot 2023-02-12 at 12 22 52 AM" src="https://user-images.githubusercontent.com/20822372/218266737-be69ebed-f8d2-4ccb-969a-3cdbdc2ee100.png">

### To Reproduce

Lspsaga hover doc to anything. The error is occurred.

### Expected behavior

no error and shows the docs

### Output of `:checkhealth nvim-treesitter`

```markdown
.
```

### Output of `nvim --version`

```text
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.8.3/share/nvim"

Run :checkhealth for more info
```

### Additional context

I am using Lazy.nvim for installing and configuring nvim-treesitter. I've updated all the parsers and reinstalled treesitter as well.
I feel like this has happened ever since I switched packer to lazy.nvim. The highlighting is working correctly, so I don't know... LOL

**Comment by yeseongmoon** [comment]
installing markdown_inline fixes the problem

**Comment by theHamsta** [comment]
Ideally, lspsaga could check for `markdown_inline` or call `require_language` with pcall. There is also a open PR for neovim/neovim to make this function not throw an error when it fails.

**Comment by yeseongmoon** [comment]
> 

Thanks for letting me know! I did not have any problems without installing makrdown_inline, but since I got a problem, I installed it, and it fixed my problem.
