### ISSUE TITLE
Download parser using git@github 

### ISSUE THREAD

**Issue by meicale** [nvim-treesitter/nvim-treesitter#4304]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I try to update the parsers I have installed. I had the same problem when I update my plugins, because it use the https://gitthub.  ... and my plugin manager (packer) provides the method to download through git@github which is much more reliable and stable.
**Describe the solution you'd like**
Provide config  method to use git@github to download parser.
**Describe alternatives you've considered**
Use the proxy, use mirror of github may help, but I think git@github is the best solution. Or other download method with is more reliable.
**Additional context**
None.

**Comment by clason** [comment]
[The `git` protocol is no longer supported by Github.](https://github.blog/2021-09-01-improving-git-protocol-security-github/)

**Comment by theHamsta** [comment]
I think you're trying to say that you want to use git instead of curl. You can do so using `require'nvim-treesitter.install'.prefer_git = true`. Git downloads will take longer than curling tarbals since we don't keep the large repos on disk. Just fetching the lasted snapshot is a lot faster than cloning a whole repo.

**Comment by meicale** [comment]
> You can do so using `require'nvim-treesitter.install'.prefer_git = true`

I tried that, it uses https:// to download the parser, which is not stable. Using ssh and git@github can use security link and can be much more stable.  


> Git downloads will take longer than curling tarbals since we don't keep the large repos on disk.

We can provide "--depth 1" as default options to just get one commit. My curl suffer the same unstable problem and can seldom download a completed file and often stop unexpectedly. I will provide more info about that. So, some workaround to make curl more stable behind VPN (or proxy) may help.  Thx!

**Comment by amaanq** [comment]
using ssh would require an ssh key tied to your account as GitHub requires authentication.

**Comment by meicale** [comment]
> 



> using ssh would require an ssh key tied to your account as GitHub requires authentication.

Yes, which makes it stable and other method may be blocked or affect by the intermediate network. So I always set ssh key.

**Comment by amaanq** [comment]
> > 
> 
> 
> 
> > using ssh would require an ssh key tied to your account as GitHub requires authentication.
> 
> Yes, which makes it stable and other method may be blocked or affect by the intermediate network. So I always set ssh key.

I think if it's being blocked or affected by your network that's a bigger problem and using ssh is just a band-aid level solution, and this doesn't really benefit anyone imo. Nothing wrong with using https

**Comment by meicale** [comment]
> I think if it's being blocked or affected by your network that's a bigger problem and using ssh is just a band-aid level solution, and this doesn't really benefit anyone imo. Nothing wrong with using https
Adding surport to ssh do nothing wrong, too. And it can also benifit more people who has different network setting ups instead of benefit nobody else.

**Comment by amaanq** [comment]
> > I think if it's being blocked or affected by your network that's a bigger problem and using ssh is just a band-aid level solution, and this doesn't really benefit anyone imo. Nothing wrong with using https
> 
> Adding surport to ssh do nothing wrong, too. And it can also benifit more people who has different network setting ups instead of benefit nobody else. 
> 

If you would like to add it as an option/extension that can be configured by the user, then that's ok as long as it doesn't affect the defaults, feel free to submit a PR

**Comment by meicale** [comment]
That is cool!
