### ISSUE TITLE
Adding a @hexadecimal highlight group

### ISSUE THREAD

**Issue by willrabbermann** [nvim-treesitter/nvim-treesitter#4308]
### Describe the highlighting problem

What would I need to add to have hexadecimals ```0x000000``` ```0xf``` ```#000000``` in their own separate highlight group? A query? Targeting all language parsers.

### Example snippet that causes the problem

.

### Tree-sitter parsing result

no

### Example screenshot

.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v18.12.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: gcc (Gentoo Hardened 12.2.1_p20230121-r1 p10) 12.2.1 20230121
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "5.15.88-gentoo",
  sysname = "Linux",
  version = "#1 SMP Mon Jan 16 17:29:22 CST 2023"
}

## Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/lib/distcc/bin/x86_64-pc-linux-gnu-gcc -march=skylake -O2 -pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/var/tmp/portage/app-editors/neovim-0.8.2/work/neovim-0.8.2_build/cmake.config -I/var/tmp/portage/app-editors/neovim-0.8.2/work/neovim-0.8.2/src -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.8.2/work/neovim-0.8.2_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.8.2/work/neovim-0.8.2_build/include
Compiled by portage@localhost
```

**Comment by amaanq** [comment]
It depends on how the language parser is implemented, like are hex numbers captured differently or lumped together with say a $.number rule. If the former, then it would just be as easy as adding a query. In the latter, maybe a match based on regex in the query? Not too familiar w that. 

However, any color scheme that then supports tree-sitter won't support this, so you'd have to add it yourself in the colorscheme setup or wherever.

Say `@hexadecimal` is then added to nvim-treesitter as a highlight capture. This would then force `@octal` and `@bin/binary` to be added as well for consistency. I also feel this would bloat the highlights a bit. 

My recommendation, if you are willing to put in the time and effort, is to look into whatever languages you want this for, check how they define hex numbers, apply the appropriate capture/match as an extension to the query (not sure about how to do this besides editing the nvim install location), and then set the highlight for this specific highlight capture in your color scheme

**Comment by willrabbermann** [comment]
I set highlight groups manually for my own themes and I don't see additional contexts as bloat. I don't use octal or bin nearly as much as hex anyway. Ill see if I can make my own query just for hex to start.

**Comment by amaanq** [comment]
> I set highlight groups manually for my own themes and I don't see additional highlight contexts as bloat. I don't use octal or bin nearly as much as hex anyway. Ill see if I can make my own query just for hex to start.

By bloat I mean if it were supported in the base repo here, see https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#highlights for what I meant
