### ISSUE TITLE
New keyword group for keywords related to coroutines

### ISSUE THREAD

**Issue by EleanorNB** [nvim-treesitter/nvim-treesitter#4334]
**Is your feature request related to a problem? Please describe.**
Recently I rearranged the keywords in the Zig highlights query. Everything had a logical place except for `async`/`await`/`suspend`/`resume`, which had to be awkwardly jammed in in other places.

**Describe the solution you'd like**
We should have a new group, `@keyword.coroutine`, for keywords related to the running of coroutines: `async`/`await`/`suspend`/`resume` in Zig, `async`/`await` in Python, `go` in Go etc.

**Describe alternatives you've considered**
The alternative is to jam them all in `@keyword.return` but that just doesn't feel right

## Language checklist
This list was populated by a search through queries for `async|await`. It is therefore to be considered incomplete and possibly inaccurate.
- [ ] c_sharp
- [ ] tlaplus
- [ ] racket
- [ ] svelte
- [ ] clojure
- [ ] ecma
- [ ] dart
- [ ] vala
- [ ] thrift
- [ ] swift
- [ ] rust
- [ ] cpp
- [ ] hack
- [ ] zig
- [ ] python

Do we change them upstream first or are our copies allowed to desynchronise?

**Comment by amaanq** [comment]
I wonder if any of the listed language's upstream queries even follow the ones here...definitely not any of the bigger ones. It also might be a good idea to ping maintainers of any language once to see if `@keyword.coroutine` would apply to any of the languages they maintain.

@theHamsta @clason if pinging them all is not a good idea, then I can dig into the languages myself and get the PR started to add this new capture group.
