### ISSUE TITLE
fatal: could not read Username for 'https://github.com': terminal prompts disabled

### ISSUE THREAD

**Issue by mikwee** [nvim-treesitter/nvim-treesitter#4335]
### Describe the bug

When I try to install TreeSitter using Packer, I get this error: `fatal: could not read Username for 'https://github.com': terminal prompts disabled`.

### To Reproduce

1. Have Packer installed
2. Add `use 'nvim-treesitter/treesitter'` to `plugins.lua`
3. Restart Neovim
4. Run `:PackerSync`

### Expected behavior

I expect it to install the plugin, without giving an error.

### Output of `:checkhealth nvim-treesitter`

```markdown
vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for help: ABI version 14
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for vim: ABI version 14
```

### Output of `nvim --version`

```text
NVIM v0.8.3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az171-224

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

### Additional context

`:checkhealth nvim-treesitter` actually gave me this error:
```
nvim-treesitter: 
========================================================================
  - ERROR: No healthcheck found for "nvim-treesitter" plugin.
```
What I wrote above was the output of `:checkhealth nvim-treesitter`.

**Comment by theHamsta** [comment]
Do you try to have anything special in your gitconfig? It seems to try ssh.

**Comment by mikwee** [comment]
Which gitconfig? The one in my user directory (I'm on Windows, sadly)?
If so, then here are its contents:
```
[gui]
	recentrepo = D:/מסמכים/Git/Now
	recentrepo = D:/׳׳•׳¡׳™׳§׳”/׳׳¡׳׳›׳™׳/RMS Open Letter/rms-open-letter.github.io
	recentrepo = D:/example-codeberg
[user]
	name = mikwee
	email = [EMAIL]
	username = mikwee
[filter "lfs"]
	required = true
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
[global]
[init]
	defaultBranch = master
```

**Comment by mikwee** [comment]
Okay, I found that the `gitconfig` file in `C:\Program Files\Git\etc` includes this part:
```
[http]
	sslCAInfo = C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
	sslBackend = openssl
```
Is this the part we're looking for?

**Comment by mikwee** [comment]
UPDATE:
I followed [these](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) [sources](https://stackoverflow.com/questions/59797272/receiving-fatal-could-not-read-username-for-https-github-com-terminal-prom/59803903#59803903), created an SSH key and put it in GitHub, which I didn't do before. After retrying `:PackerSync`, I get this error message:
```
Host key verification failed.
    fatal: Could not read from remote repository.
    Please make sure you have the correct access rights
    and the repository exists.
```

**Comment by clason** [comment]
I don't understand how this is an nvim-treesitter issue if the error happens _before_ you install it. Have you reported this over at Packer (after searching prior issues -- open and closed)?

**Comment by clason** [comment]
> Add use 'nvim-treesitter/treesitter' to plugins.lua

And just to make sure: the plugin name is `nvim-treesitter/nvim-treesitter` (double `nvim-`).

**Comment by mikwee** [comment]
> I don't understand how this is an nvim-treesitter issue if the error happens _before_ you have installed it. Have you reported this over at Packer (after searching prior issues -- open and closed)?

I'll do so, thanks!

Also, in case this is relevant, now *all* installed plugins give me the error above while running `:PackerSync`. This h appens with the double `nvim-` or without.

**Comment by clason** [comment]
> Also, in case this is relevant, now all installed plugins give me the error above while running :PackerSync. 

It is; it confirms that this is not an nvim-treesitter issue. I'll close this then (but of course it can be reopened in the unlikely case that it _is_ one.)
