### ISSUE TITLE
`latex` inline highlighting doesn't work properly in markdown file

### ISSUE THREAD

**Issue by saurabhchardereal** [nvim-treesitter/nvim-treesitter#4349]
### Describe the highlighting problem

If a markdown file has a heading, in my case, then it doesn't highlight inline `latex` line.

### Example snippet that causes the problem

```markdown
## Heading
$\frac{{x}{y}^m}$
```

## With Heading
```
section [0, 0] - [2, 0]
  atx_heading [0, 0] - [1, 0]
    atx_h2_marker [0, 0] - [0, 2]
    heading_content: inline [0, 2] - [0, 10]
  paragraph [1, 0] - [2, 0]
    inline [1, 0] - [1, 17]
      latex_block [1, 0] - [1, 17]
        latex_span_delimiter [1, 0] - [1, 1]
        latex_span_delimiter [1, 16] - [1, 17]
```

## Without Heading
```
section [0, 0] - [1, 0]
  paragraph [0, 0] - [1, 0]
    inline [0, 0] - [0, 17]
      latex_block [0, 0] - [0, 17]
        inline_formula [0, 0] - [0, 17]
          generic_command [0, 1] - [0, 16]
            command: command_name [0, 1] - [0, 6]
            arg: curly_group [0, 6] - [0, 16]
              curly_group [0, 7] - [0, 10]
                text [0, 8] - [0, 9]
                  word: word [0, 8] - [0, 9]
              curly_group [0, 10] - [0, 13]
                text [0, 11] - [0, 12]
                  word: word [0, 11] - [0, 12]
              text [0, 13] - [0, 15]
                word: superscript [0, 13] - [0, 15]
                  superscript: word [0, 14] - [0, 15]
        latex_span_delimiter [0, 0] - [0, 1]
        latex_span_delimiter [0, 16] - [0, 17]
```

### Example screenshot

![Screenshot-20-02-2023-03-47-39](https://user-images.githubusercontent.com/51372520/220081427-7447b380-cf49-467d-a06e-da234ff4a159.png)
![Screenshot-20-02-2023-03-47-23](https://user-images.githubusercontent.com/51372520/220081436-b0281c79-1fb5-4fe6-94b5-f7dc9b6443be.png)

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.12.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.2.1 20230201
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "6.1.12-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Tue, 14 Feb 2023 22:08:08 +0000"
}

## Parser/Features         H L F I J
  - lua                 ✓ ✓ ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓
  - help                ✓ . . . ✓
  - vim                 ✓ ✓ ✓ . ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - sql                 ✓ . . . ✓
  - json                ✓ ✓ ✓ ✓ .
  - query               ✓ ✓ ✓ ✓ ✓
  - bash                ✓ ✓ ✓ . ✓
  - latex               ✓ . ✓ . ✓
  - markdown            ✓ . ✓ . ✓
  - html                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

### Additional context

It is same for latest neovim-nightly release also.

**Comment by clason** [comment]
That's an issue you need to raise at https://github.com/MDeiml/tree-sitter-markdown

**Comment by MDeiml** [comment]
I disagree. The nodes in the output for both cases are the same besides the shift by one line. It seems though that for some reason the latex parser is not injected when there is a heading present.

I don't know why that is the case. Looking at the `injections.scm` I don't see any reason for that.

**Comment by theHamsta** [comment]
I also debugged this when this was opened. This seems to be a edge case/bug with the language tree implementation

**Comment by clason** [comment]
I think the issue comes from the recursive injection `markdown` -> `markdown_inline` -> `latex`. It is instructive to look at these examples with parsers shown:

* Without heading:
```
(section) [1:1-2:0] markdown
 (paragraph) [1:1-2:0] markdown
  (inline) [1:1-17] markdown
   (inline_formula) [1:1-17] latex
    (generic_command) [1:2-16] latex
     command: (command_name) [1:2-6] latex
     arg: (curly_group) [1:7-16] latex
      (curly_group) [1:8-10] latex
       (text) [1:9-9] latex
        word: (word) [1:9-9] latex
      (curly_group) [1:11-13] latex
       (text) [1:12-12] latex
        word: (word) [1:12-12] latex
      (text) [1:14-15] latex
       word: (superscript) [1:14-15] latex
        superscript: (word) [1:15-15] latex
```

* With heading:
```
(section) [1:1-3:0] markdown
 (atx_heading) [1:1-2:0] markdown
  (atx_h1_marker) [1:1-1] markdown
  heading_content: (inline) [1:2-6] markdown
 (paragraph) [2:1-3:0] markdown
  (inline) [2:1-17] markdown
   (latex_block) [2:1-17] markdown_inline
    (latex_span_delimiter) [2:1-1] markdown_inline
    (latex_span_delimiter) [2:17-17] markdown_inline
``

**Comment by MDeiml** [comment]
What does that mean? Is it a bug with injections in neovim?

Also through disabling the `markdown_inline -> latex` injection I DO get (almost) the same trees, besides of course the `atx_heading`.

**Comment by clason** [comment]
Unclear, but most likely. (I suspect the original tree was with `Playground`, so the difference is another indication that something's wrong.)

**Comment by clason** [comment]
@MDeiml I see you use (or at least contribute to) Helix -- could you test this example there and see what their tree looks like? Would be helpful to narrow this down.

(Also, looks like they are using different queries @theHamsta -- we should really try to coordinate so improved queries benefit not just one editor...)

**Comment by MDeiml** [comment]
**With heading**
![grafik](https://user-images.githubusercontent.com/10165741/221584302-c97ebf90-8d93-4f64-89e2-ccfba6357d64.png)

**Without heading**
![grafik](https://user-images.githubusercontent.com/10165741/221584348-06cc2c24-ad6b-4905-8d12-dcd2a06ccc10.png)

Unfortunately helix does not have an equivalent to `:lua vim.treesitter.show_tree()`, at least not that I know of, but clearly syntax highlighting is working. I guess that means it's a neovim bug.

**Comment by clason** [comment]
Indeed. Thanks for checking (feel free to close the issue on the parser repo then)!

**Comment by clason** [comment]
@lewis6991 as you recently looked at our language tree code: do you have any idea what could be causing this?

**Comment by lewis6991** [comment]
This is an issue in `LanguageTree:_get_injections()`. Debugging now.

**Comment by lewis6991** [comment]
Omg, 1 char bug

```diff
diff --git a/runtime/lua/vim/treesitter/languagetree.lua b/runtime/lua/vim/treesitter/languagetree.lua
index 7ec7bbfa1..43fb86689 100644
--- a/runtime/lua/vim/treesitter/languagetree.lua
+++ b/runtime/lua/vim/treesitter/languagetree.lua
@@ -467,7 +467,7 @@ function LanguageTree:_get_injections()

   -- Generate a map by lang of node lists.
   -- Each list is a set of ranges that should be parsed together.
-  for _, lang_map in ipairs(injections) do
+  for _, lang_map in pairs(injections) do
     for lang, patterns in pairs(lang_map) do
       if not result[lang] then
         result[lang] = {}
```

**Comment by clason** [comment]
best bug 😇

**Comment by lewis6991** [comment]
I think this issue is very specific to `markdown_inline`. Most of the time `ipairs` should be ok.
