### ISSUE TITLE
treesitter-html: <s></s> tag without highlighting

### ISSUE THREAD

**Issue by NicolasZapata** [nvim-treesitter/nvim-treesitter#4355]
### Describe the highlighting problem

La Etiqueta <s></s> no resalta el texto de contenido en el editor.

### Example snippet that causes the problem

```html
 <s>Preformatiado cruzado</s>
```

### Tree-sitter parsing result

![image](https://user-images.githubusercontent.com/35777697/220209792-6c2ebd13-d812-49b6-b8ac-483681ce4018.png)

### Example screenshot

In Light Theme
![image](https://user-images.githubusercontent.com/35777697/220207687-15ad5c2c-8d9a-4697-8129-570ca1a0fdaa.png)
In Dark Theme
![image](https://user-images.githubusercontent.com/35777697/220208351-00f0242e-9204-4321-aaa1-f2a59a3b52a4.png)

### Expected behavior

Simply that the element is displayed as in the other tags.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v16.15.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: gcc (x86_64-posix-seh, Built by strawberryperl.com project) 8.3.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "10.0.22623",
  sysname = "Windows_NT",
  version = "Windows 10 Home Single Language"
}

## Parser/Features         H L F I J
  - latex               ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - dart                ✓ ✓ . ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilado por runneradmin@fv-az30-11

Features: -acl +iconv +tui
See ":help feature-compile"

     archivo "vimrc" del sistema: "$VIM\sysinit.vim"
            predefinido para $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

### Additional context

Possibly a typo problem in source code.

**Comment by clason** [comment]
I'm sorry, I don't understand the problem.

**Comment by NicolasZapata** [comment]
I hope this helps you understand the problem
![image](https://user-images.githubusercontent.com/35777697/220220320-e4068851-52ac-40f2-8b90-6acc1375eb24.png)

The text dont show in s tag, If uninstall treesitter-html with TSUninstall (reset to the default highligh) now the text can be showing, look . . .

![image](https://user-images.githubusercontent.com/35777697/220221144-ad7fed93-cf98-47a6-b442-8535e7fce86b.png)

So, the problem is not the colorscheme or my terminal, is nvim-treesitter-html, the text is invisible there.

**Comment by clason** [comment]
No, sorry, that's exactly your problem. Check your colorscheme.
