### ISSUE TITLE
Failed to load parser, parser\*.so is not a valid Win32 app

### ISSUE THREAD

**Issue by osherbz** [nvim-treesitter/nvim-treesitter#438]
**Describe the bug**
I installed `nvim-treesitter'  and followed the documentation.
Also, I use windows, and followed the nvim-treesitter/wiki/Windows-support.

**Expected behavior**
no error

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

 health#nvim_treesitter#check
========================================================================
ERROR: Failed to run healthcheck for "nvim_treesitter" plugin. Exception:
function health#check[21]..health#nvim_treesitter#check, line 1
Vim(lua):E5108: Error executing lua Failed to load parser: uv_dlopen: C:
\Users\osher\AppData\Local\nvim\plugged\nvim-treesitter\parser\c.so is not
a valid Win32 application.

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-679-g0f41caa26
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/M
SVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEB
UG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0
x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VA
R_FROM -DMIN_LOG_LEVEL=3 -IC:/projects/neovim/build/config -IC:/projects/neovim/src -
IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/proj
ects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

**Additional context**
I used Chocolatey to install neovim with the command `choco install neovim --pre`.

**Comment by osherbz** [comment]
Hey, on my virutal machine with linux its working.
I tried to compile the parsers with gcc/g++ and another time with clangd.
Am I missing something?

**Comment by theHamsta** [comment]
Hi, I got a similar error when compiling with CL.exe (see my MSVC tool chain error). Can you try out the pre-compiled parsers from the Cross-Platform CI PR. You can download a zip archive with the parsers from the Windows workflow.

**Comment by osherbz** [comment]
> Hi, I got a similar error when compiling with CL.exe (see my MSVC tool chain PR). Can you try out the pre-compiled parsers from the Cross-Platform CI PR. You can download a zip archive with the parsers from the Windows workflow.
> 
> I guess you're using Windows 10 x64? Could be a problem the compiled binary is not *.DLL but *.so on all platforms

Yes I use Windows 10 x64. 
Sry but i dont know from where to install the zip archive with the parsers.
sry for this... but can you send the link please?

**Comment by theHamsta** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/pull/417/checks?check_run_id=1088255128 -> Artifacts

or https://github.com/nvim-treesitter/nvim-treesitter/suites/1162366131/artifacts/16859229

**Comment by osherbz** [comment]
> https://github.com/nvim-treesitter/nvim-treesitter/pull/417/checks?check_run_id=1088255128 -> Artifacts
> 
> or https://github.com/nvim-treesitter/nvim-treesitter/suites/1162366131/artifacts/16859229

Thanks! work like charm!
At start I extracted the downloaded zip file into the nvim-treesitter parser folder.
Got into my project and error raised : uv_dlopen.
Then I runned `:TSUpdate` and it works now.

Thanks for your help.

**Comment by dance** [comment]
Had the same problem. The solution was to make sure the CL.exe that treesitter uses to compile parsers matches nvim architecture. In my case nvim was built with x64 (to be sure check `nvim --version`, section `Compilation:`, path to cl.exe - `.../**x64**/cl.exe`) but CL.exe on path was x86 one. Solved by launching nvim via "x64 Native Tools Command Prompt" that Visual Studio provides (so that CL.exe is definetely x64 one), and re-installing parsers.

P.S. Artifacts have been expired already and are not available at the moment anymore.

**Comment by theHamsta** [comment]
The artifacts should be built on every build of our CI. Just click on the green tick next to each commit to master

**Comment by Abdullah-coder2013** [comment]
I also had this problem,
And I reinstalled my GCC compiler and it seems to work fine now.

**Comment by js-writer** [comment]
@Abdullah-coder2013 which compiler did you use?

**Comment by Abdullah-coder2013** [comment]
@js-writer I used the GCC compiler from Mingw.
Then deleted it. And installed GCC compiler with scoop.

**Comment by jhessin** [comment]
> @js-writer I used the GCC compiler from Mingw. Then deleted it. And installed GCC compiler with scoop.

This was the culprit Mingw doesn't work! get scoop!
