### ISSUE TITLE
Error installing Rust tree-sitter

### ISSUE THREAD

**Issue by WhyNotHugo** [nvim-treesitter/nvim-treesitter#4425]
### Describe the bug

Running `:TSInstall rust` fails:

```
Failed to execute the following command:                                                                                   
{
  cmd = <function 1>
}
```

Other tree-sitters that I've tried build fine.

Upon restarting neovim, if I open a Rust file I get this error:

```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:22: Error executing lua: /usr/share/nvim/runtime/filetype.lua:23:
Vim(append):Error executing lua callback: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at posit
ion 729 for language rust
stack traceback:
        [C]: in function '_ts_parse_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: in function 'get_query'
        ...gins/start/nvim-treesitter/lua/nvim-treesitter/query.lua:108: in function 'get_query'
        ...r-textobjects/lua/nvim-treesitter/textobjects/select.lua:151: in function 'attach'
        ...ns/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:511: in function 'attach_module'
        ...ns/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:534: in function 'reattach_module'
        ...ns/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:135: in function <...ns/start/nvim-treesitter/lua/nvim-treesitter
/configs.lua:134>
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:23: in function </usr/share/nvim/runtime/filetype.lua:22>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>
stack traceback:
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:23: in function </usr/share/nvim/runtime/filetype.lua:22>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>
```

### To Reproduce

1. `:TSInstall rust`

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v18.14.2 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Alpine 12.2.1_git20220924-r9) 12.2.1 20220924
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "6.1.12-0-edge",
  sysname = "Linux",
  version = "#1-Alpine SMP PREEMPT_DYNAMIC Tue, 14 Feb 2023 23:46:06 +0000"
}

## Parser/Features         H L F I J
  - rust                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.3
Build type: MinSizeRel
LuaJIT 2.1.0-beta3
Compiled by buildozer@build-edge-x86_64

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

I've tried both latest `master` and `v0.8.3`.

I've tried `git clean -xdf` in the plugin's repository to clean up any potential leftovers. Same result.

Complete configuration is here: https://git.sr.ht/~whynothugo/dotfiles/tree/main/item/home/.config/nvim

**Comment by WhyNotHugo** [comment]
Oh, very weird details, this error:

```
Failed to execute the following command:                                                                                    
{
  cmd = <function 1>
}
```

Is only printed if I run `TSInstall rust` when a rust file is open. If the current buffer is empty, I don't  see this error.

**Comment by WhyNotHugo** [comment]
However, even if I workaround above that error in order to build the TS, I still get the other error when opening a Rust file:

```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:22: Error executing lua: /usr/share/nvim/runtime/filetype.lua:23:
Vim(append):Error executing lua callback: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at posit
ion 729 for language rust
stack traceback:
        [C]: in function '_ts_parse_query'
        /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: in function 'get_query'
        ...gins/start/nvim-treesitter/lua/nvim-treesitter/query.lua:108: in function 'get_query'
        ...r-textobjects/lua/nvim-treesitter/textobjects/select.lua:151: in function 'attach'
        ...ns/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:511: in function 'attach_module'
        ...ns/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:534: in function 'reattach_module'
        ...ns/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:135: in function <...ns/start/nvim-treesitter/lua/nvim-treesitter
/configs.lua:134>
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:23: in function </usr/share/nvim/runtime/filetype.lua:22>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>
stack traceback:
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:23: in function </usr/share/nvim/runtime/filetype.lua:22>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:11>

```

**Comment by WhyNotHugo** [comment]
Bisecting shows that the error starts in c563abe92848a4581395f8f176b6f3f549144fbe. This updated `rust` tree sitter in the lock file. Maybe some queries need to be updated too?

**Comment by WhyNotHugo** [comment]
Ah, the `Failed to execute the following command` error is due to [the call to `reattach_if_possible_fn`](https://github.com/nvim-treesitter/nvim-treesitter/blob/07fb134752b4af49d1a87cc735573edeadcbb271/lua/nvim-treesitter/install.lua#L444) after rebuilding. So it's just another symptom of the same issue.

**Comment by WhyNotHugo** [comment]
Alright, I'm out of ideas on how to debug this :c

**Comment by clason** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/issues/3092

This is with almost 100% certainty an issue with you either not having updated nvim-treesitter before installing, or having some stale or cached query files lying around.

**Comment by theHamsta** [comment]
The error stack trace blames nvim-treesitter-textobjects.

**Comment by clason** [comment]
*ceterum censeo* we should pull this into nvim-treesitter main ;)

**Comment by theHamsta** [comment]
> _ceterum censeo_ we should pull this into nvim-treesitter main ;)

Well, a running textobjects in would also do the job. Maybe the query parsing could also be made more forgiven in upstream tree-sitter ignore individual s-expressions that are no longer valid, as the ecosystem will always have third-party queries. Putting nvim-treesitter-textobject

I like how nvim-treesitter-textobjects can now relatively work independently of the main repo. There is a lot of text documenting it's functionality and we relatively rarely need to change much in that repo.

Maybe we can instead split-up nvim-treesitter in a query-only repo and various code repos for functionality. I wanted to ask earlier if this could make life easier for people using multiple generations of Neovim (if this is a problem at all). The queries stay usually compatible over multiple editor-generations (unknown predicates/directives could be backported by the repo for older nvim versions) while the code/utility functionality will change over time. Much of the tree-sitter code will eventually diminish when more functionality goes into upstream Neovim. This would allow for users to experiment more with different implementations for different functionality.

**Comment by clason** [comment]
I would be very much in favor of breaking up nvim-treesitter, AT&T style! I have some ideas on an nvim-treesitter 2.0, maybe I should open a discussion about it.

**Comment by clason** [comment]
And I should mention that text objects are next on my list, now that folding is upstreamed.

**Comment by clason** [comment]
(can't let Helix have all the fun...)

**Comment by theHamsta** [comment]
My next plan was to work on some editor-independent CI service that would push different parser artifacts to GH registry. So that downstream consumers could get compatible artifacts of their choice of their choice for any parser, like:
- compiled shared-objects for different OSes/arches
- grammar.json for people wanting to generate the grammar without the need for node/npm
- C source files for people who don't want to run the Rust/tree-sitter CLI part of the generation
- node-type.json for simple refection on the grammar
- queries and flavored queries (flavored in the sense of basic, helix-style, nvim-style, Emacs-style)

I feel that there will never a situation where every repo will provide binaries/artifacts for all requirements even if there is ever some standardized GH workflow at some point. Even with GH releases it's difficult to discover which parsers exist at all.

One point I need to find out is how `brew` implements the Docker registry protocol to push binary blobs to `container.ghcr.io`

**Comment by clason** [comment]
As upstream (treesitter) is dragging its feet on this,, that would be very much appreciated!

**Comment by clason** [comment]
Honestly, I think if there's a ready made action, most parser repos would gladly just add that.

**Comment by theHamsta** [comment]
If it's a personal project, we don't have to worry whether it's a solution that fit's it all. It could just be another alternative to get the parser or a parser/query combo.

**Comment by WhyNotHugo** [comment]
> The error stack trace blames nvim-treesitter-textobjects.

Dammit, I can't believe I missed that (I swear I did check!). Updating that fixes the issue.

Do you want me to leave the issue open for the ongoing discussion?

> Maybe we can instead split-up nvim-treesitter in a query-only repo and various code repos for functionality.

Why can't queries be upstreamed into individual tree-sitter repositories? I've noticed that some very few tree-sitters do include their own queries. This would make it pretty much impossible to have a version mismatch between queries and parsers.

**Comment by clason** [comment]
> Why can't queries be upstreamed into individual tree-sitter repositories?

Because they're very specific to the editor implementation (say, Neovim supports `@conceal` and `@spell`, but not other editors), and text-objects is something only Vim (and Helix) has.

**Comment by WhyNotHugo** [comment]
Can't other editors simply ignored unsupported features (e.g.: `@conceal`, `@spell`)?

**Comment by clason** [comment]
You'll have to ask them. (Neovim throws an error for unknown nodes, as you have just noticed.)

In any case, the simple answer is: the implementations are (sometimes very) different, so the queries have to be different.
