### ISSUE TITLE
[Bash highlight] Environment and Shell variables are not being highlighted

### ISSUE THREAD

**Issue by bluz71** [nvim-treesitter/nvim-treesitter#444]
Hello Treesitter team,

I am the author of the [moonfly](https://github.com/bluz71/vim-moonfly-colors) and [nightfly](https://github.com/bluz71/vim-nightfly-guicolors) color schemes. The past couple of days I have been adapting my color shemes to render nicely when Treesitter is in effect. 

Treesitter is a very interesting technology and my first experimentation has been very positive. However I do have suggestions with regards to certain language highlighting issues; I will file one request for each language.

The first one is Bash.

With [this Bash file](https://github.com/bluz71/vim-nightfly-guicolors/blob/master/samples/bash.bash) none of the all-upper case variables are being highlighted for example `LS_COLORS` as seen here:

<img width="566" alt="Screen Shot 2020-09-12 at 11 17 38 am" src="https://user-images.githubusercontent.com/11382509/92983904-a02bbe00-f4e9-11ea-9f68-a28a7f7bb3b5.png">

Compare with Atom editor (which I consider the baseline Treesitter implementation):

<img width="601" alt="Screen Shot 2020-09-12 at 11 19 06 am" src="https://user-images.githubusercontent.com/11382509/92983916-cd786c00-f4e9-11ea-8472-463ec9c1e4a9.png">

I assume the `TSConstant` / `@constant` highlight / query group should capture Bash variables whether all uppercase or `local`.

Best regards.

**Comment by theHamsta** [comment]
Thanks for cleaning up a bit with your issue! :+1: 

@TravonteD

**Comment by theHamsta** [comment]
@bluz71 You can use https://github.com/nvim-treesitter/playground to inspect the parsed tree. Sometimes it may also be the fault of the tree-sitter parser.

**Comment by theHamsta** [comment]
In this case, the variable is just highlighted with `TSVariable` (no highlight as a default). We could use naming conventions to highlight these variables for instance as `TSConstant`

**Comment by bluz71** [comment]
Yes, my mistake, `TSVariable` indeed works.

But it looks like all upper-case variables will soon become `TSConstant` which also seems reasonable.

No need to keep this open, #458 replaces this.

Many thanks.
