### ISSUE TITLE
[C highlight] #include is being highlighted as TSKeyword, yet TSInclude seems a better match

### ISSUE THREAD

**Issue by bluz71** [nvim-treesitter/nvim-treesitter#445]
Hello,

With [this C file](https://github.com/bluz71/vim-nightfly-guicolors/blob/master/samples/c.c) the `#include` statements are being highlighted as `TSKeyword` which is noted by this section in the `c/highlights.scm` file:

```
"#define" @constant.macro
[
  "#if"
  "#ifdef"
  "#ifndef"
  "#else"
  "#elif"
  "#endif"
  "#include"
  (preproc_directive)
] @keyword
```

However, the nvim-treesitter help documentation for `TSInclude` states:

> For includes: `#include` in C, `use` or `extern crate` in Rust, or `require` in Lua.

I believe `#include` should be instead go to `@include` for language to language include/import style consistency and to match what the `TSInclude` documentation states.

Best regards.

**Comment by theHamsta** [comment]
We just stayed with the original Vim colors in that case (Vim uses Include for most languages but not for C). But it's of course it's more organize this way

**Comment by bluz71** [comment]
Tested, this is fixed, including for C++ files as well. 

Many thanks.
