### ISSUE TITLE
scoped SCSS incorrect highlight for .vue files

### ISSUE THREAD

**Issue by mtsr404** [nvim-treesitter/nvim-treesitter#4450]
### Describe the bug

<img width="809" src="https://user-images.githubusercontent.com/10844682/223007077-2c16bedf-9835-44b1-b6b3-2250c2596b3a.png">

Scoped scss is not highlighted correctly in .vue file.

With "scoped", it seems to be parsed as css, not scss.

### To Reproduce

```vue
<style lang="scss" scoped>
$foobar:10px;
</style>
```
Use this snippet and open Playground.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v16.13.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "21.6.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64"
} ~

Parser/Features         H L F I J
  - css                 ✓ . ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ .
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vue                 ✓ . ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.0-dev-1139+gba38f35d3-dirty
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by lucario387** [comment]
can you press I, or :Inspect (if on nightly) on foobar so I can see the output?

**Comment by mtsr404** [comment]
Thanks @lucario387 

## PlaygroundTree

```
template_element [0, 0] - [0, 0]
  start_tag [0, 0] - [0, 0]
    tag_name [0, 0] - [0, 0]
      identifier [0, 0] - [0, 0]
  text [0, 0] - [0, 0]
  end_tag [0, 0] - [0, 0]
    tag_name [0, 0] - [0, 0]
script_element [0, 0] - [0, 0]
  start_tag [0, 0] - [0, 0]
    tag_name [0, 0] - [0, 0]
    attribute [0, 0] - [0, 0]
      attribute_name [0, 0] - [0, 0]
      quoted_attribute_value [0, 0] - [0, 0]
        attribute_value [0, 0] - [0, 0]
  raw_text [0, 0] - [0, 0]
  end_tag [0, 0] - [0, 0]
    tag_name [0, 0] - [0, 0]
style_element [0, 0] - [2, 8]
  start_tag [0, 0] - [0, 26]
    tag_name [0, 1] - [0, 6]
    attribute [0, 7] - [0, 18]
      attribute_name [0, 7] - [0, 11]
      quoted_attribute_value [0, 12] - [0, 18]
        attribute_value [0, 13] - [0, 17]
    attribute [0, 19] - [0, 25]
      attribute_name [0, 19] - [0, 25]
  raw_text [1, 0] - [2, 0]
    declaration [1, 0] - [1, 13]
      variable_name [1, 0] - [1, 7]
      integer_value [1, 9] - [1, 12]
        unit [1, 10] - [1, 12]
    ERROR [1, 0] - [1, 13]
      ERROR [1, 0] - [1, 7]
      ERROR [1, 10] - [1, 12]
  end_tag [2, 0] - [2, 8]
    tag_name [2, 2] - [2, 7]
```

## Inspect on $foobar

```
Syntax
  - vue_scss
  - sassVariable links to Identifier
```

**Comment by amaanq** [comment]
Did #4430 cause this? was it fine before or no?

**Comment by lucario387** [comment]
> Did #4430 cause this? was it fine before or no?

It was not broken for a while before #4073, then #4073 breaks it again, and #4430 should revert it back to before #4073

**Comment by lucario387** [comment]
> Did #4430 cause this? was it fine before or no?
also for context, this is the same code as this issue, running on nvim-treesitter master
![image](https://user-images.githubusercontent.com/29790821/223009421-f760b918-f89b-4436-b8d4-bb709377df18.png)

**Comment by amaanq** [comment]
I can take a look in a bit, but I don't really use html so we'll see ;)

**Comment by lucario387** [comment]
To be more clear 
@amaanq 
It was:
- Broken before #3981 
- Broken again after #4073 
- (Should be) not broken again after #4430

**Comment by lucario387** [comment]
> ## Inspect on $foobar
> ```
> Syntax
>   - vue_scss
>   - sassVariable links to Identifier
> ```

The inspect is not showing a treesitter section, so im a bit confused
Can you show at which commit your nvim-treesitter is at currently?

**Comment by mtsr404** [comment]
@lucario387 
I use nvim-treesitter from 3731cf1c0c70287568d26f190849c68a46c21297

**Comment by lucario387** [comment]
> @lucario387 I use nvim-treesitter from [3731cf1](https://github.com/nvim-treesitter/nvim-treesitter/commit/3731cf1c0c70287568d26f190849c68a46c21297)

The fix for it should be the commit [right after](https://github.com/nvim-treesitter/nvim-treesitter/commit/d11dd552dbde181cd49652188521f4b5f6cad2f8)
Can you try on nvim-treesitter latest and see if the problems were resolved?

**Comment by mtsr404** [comment]
@lucario387 
Sorry It seems to be fixed

**Comment by amaanq** [comment]
So...#4430 is fine after all?

**Comment by lucario387** [comment]
> So...#4430 is fine after all?

yes
I broke it, fix it then broke it again so yep, it's fixed
