### ISSUE TITLE
[C++ highlight] some function calls are being highlighted as TSProperty but should be TSFunction

### ISSUE THREAD

**Issue by bluz71** [nvim-treesitter/nvim-treesitter#446]
Hello,

With [this C++ file](https://github.com/bluz71/vim-nightfly-guicolors/blob/master/samples/cplusplus.cc) the function invocations in the `parseStory` function definition are being highlighted as `TSProperty` but should be highlighted as `TSFunction`.

Here is nvim-treesitter highlighting that segment (look at the crimson highlights such as `firstChild` and compare with the blue color `parseStory` itself which is correctly styled as `TSFunction`):

<img width="563" alt="Screen Shot 2020-09-12 at 11 41 03 am" src="https://user-images.githubusercontent.com/11382509/92984348-dcace900-f4ec-11ea-9569-2919089918fc.png">

Contrast with the Atom editor highlighting the same segment, notice the same color for `parseStory`, `firstChild`:

<img width="594" alt="Screen Shot 2020-09-12 at 11 42 09 am" src="https://user-images.githubusercontent.com/11382509/92984373-049c4c80-f4ed-11ea-8c13-ce204e0c4f07.png">

Best regards.

**Comment by theHamsta** [comment]
Are you sure that the highlight is TSProperty and not TSMethod?

**Comment by theHamsta** [comment]
You were right it's TSProperty. I am trying to fix the prioritization of those highlights...

**Comment by bluz71** [comment]
You are right, `TSMethod` is a more appropriate highlight group than `TSFunction` for the items in crimson in the first screenshot; it has been a while since I did C++.

I look forward to testing the updates when they land.

Many thanks.

**Comment by bluz71** [comment]
For my own record keeping, this issue is waiting upon PR #453

**Comment by bluz71** [comment]
Tested, issue is confirmed as fixed:

![cplusplus](https://user-images.githubusercontent.com/11382509/99615794-262b2e80-2a70-11eb-9b2c-d5a61d1972f4.png)

Many thanks!
