### ISSUE TITLE
recent ECMA / Javascript constant highlighting is inconsistent

### ISSUE THREAD

**Issue by AlanWarren** [nvim-treesitter/nvim-treesitter#4466]
### Describe the highlighting problem

The following PR ( https://github.com/nvim-treesitter/nvim-treesitter/commit/c553e6c5608ba54e210e9131bf9ba5e36ef18e57 ) introduces changes that assign variables declared as const to the @constant highlight group.  I would personally like to see this reverted, but I'm curious how other JS devs feel about it. 

The largest issue I have with this is the inconsistency it introduces.  With this patch const variables are highlighted a different color than other variables in their declaration, but when const variables are read they remain the standard variable highlighting. Besides the inconsistency, it doesn't seem helpful for the intended purpose of reminding the developer. 

It also adds ambiguity with capitalized constants, which have historically had the @constant group, but are generally used differently. Neither C or C++ do this for const declarations, so it makes me wonder why we feel it would be helpful for JS?  

I realize enabling semantic highlighting somewhat resolves this, and I'm able to override this rule in my own queries. It just doesn't seem like a good default. Is it just me? 

### Example snippet that causes the problem

```javascript
const data = await res.json();
const users = data.Users;
```

### Tree-sitter parsing result

```
lexical_declaration [151, 6] - [151, 40]
  variable_declarator [151, 12] - [151, 39]
    name: identifier [151, 12] - [151, 17]
```

### Example screenshot

![image](https://user-images.githubusercontent.com/294606/223785752-22600ad4-9ed3-4511-ba00-0f2c168d4d29.png)

### Expected behavior

I realize this is subjective, but it would be ideal if const variable declarations were highlighted as @variable and not @constant.  @constant should remain enabled for capitalized constants, etc.  

Alternatively, allow semantics to handle highlighting readonly variables, etc. 

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v16.16.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 14.0.0 (clang-1400.0.29.202)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "22.3.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.3.0: Thu Jan  5 20:48:54 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T6000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - c_sharp             ✓ ✓ ✓ . ✓
  - cmake               ✓ . ✓ . .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - diff                ✓ . . . .
  - dockerfile          ✓ . . . ✓
  - embedded_template   ✓ . . . ✓
  - fennel              ✓ ✓ ✓ . ✓
  - fish                ✓ ✓ ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - graphql             ✓ . . ✓ ✓
  - help                ✓ . . . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - http                ✓ . . . ✓
  - java                ✓ ✓ . ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - json5               ✓ . . . ✓
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - jsruby              ✓ . . . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ . ✓
  - markdown_inline     ✓ . . . ✓
  - perl                ✓ . ✓ . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - prisma              ✓ . . . .
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - ruby                ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ .
  - sql                 ✓ . . . ✓
  - svelte              ✓ . ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓
  - ymlruby             ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.0-dev-1147+ge389b1890
```

**Comment by amaanq** [comment]
I think I'm starting to come around and agree. I don't really write much JS (outside of tree-sitter grammars) - I'm a big Rust/Go guy so in those const declarations it makes more sense as they're global/compile time consts, whereas in js it just means an immutable var.

I would be fine to partially revert the change that causes the inconsistent highlighting. Sorry about that :)

**Comment by AlanWarren** [comment]
Thanks for responding. I get where you're coming from with go/rust. I personally think it would be nice if it were how it was before, but I'm excited for the work you guys are doing with semantic tokens. Highlighting read-write vs. read-only variables would be pretty nice.

**Comment by amaanq** [comment]
I am ok with reverting, I do just want a 2nd opinion from another js/ts dev. 


( Paging @folke as we discussed this..sorry for the ping :) )
