### ISSUE TITLE
[Python highlight] and/in/is/not/or are being highlighted as TSOperator, I believe they should be TSKeyword

### ISSUE THREAD

**Issue by bluz71** [nvim-treesitter/nvim-treesitter#447]
Hello,

With [this Python file](https://github.com/bluz71/vim-nightfly-guicolors/blob/master/samples/python.py) the terms `and` / `in` / 'is' etc are being highlighted as `TSOperator`.

That makes sense once one looks at the current `python/highlights.scm` file:

```
  "and"
  "in"
  "is"
  "not"
  "or"
  "->"
] @operator
```

However the Atom editor by contrast appears to highlight those words as language keywords as seen here:

<img width="596" alt="Screen Shot 2020-09-12 at 11 52 06 am" src="https://user-images.githubusercontent.com/11382509/92984570-69a47200-f4ee-11ea-9fdc-e1741fffca20.png">

My feeling is that English style language words should be `TSKeyword` / `keyword`; hence `and` / `in` / `is` / `not` / `or` should shift from operators to keywords.

It is a judgement call, but I feel the currently classification for those Python words is not ideal.

Best regards.

**Comment by theHamsta** [comment]
Hi thanks! For giving us this feedback! We have several subcategories of keywords since Vim we could introduce keyword.operator which is either linked operator or keyword.

I realized that upstream tree-sitter-python has the same queries as we have but since Atom is not using the new query system yet the highlighting in the editor might be different.

@stsewd what's your opinion on this? having `@keyword.operator` would be good compromise to make both sides happy that either want operator or keyword highlighting.

**Comment by stsewd** [comment]
yeah, `keyword.operator` seems like a good middle ground

**Comment by bluz71** [comment]
I agree with the compromise.

Am I correct to assume there will be a new highlight group created from this, `TSKeywordOperator`?

I will adjust my color schemes upon confirmation that a new highlight group is upcoming.

**Comment by theHamsta** [comment]
> Am I correct to assume there will be a new highlight group created from this, TSKeywordOperator?

with #459 being merged, yes!

**Comment by bluz71** [comment]
Thanks. Will test soon and report back.

**Comment by bluz71** [comment]
I just test @theHamsta's `keyword.operator` branch.

All good, it gives Vim theme authors the flexibility to style `TSKeywordOperator` how they want, in my case I like to use the same color as `TSKeyword` / `Keyword`, others may prefer the `Operator` color or even something else.

This can be resolved upon merge.

Many thanks.

**Comment by bluz71** [comment]
This issue is awaiting PR #459 

Sorry, for the bump, just for my own record keeping it is easier for me to keep track with this short message. I am in no rush, just pure cataloging.
