### ISSUE TITLE
Minor Highlighting Issues for Julia

### ISSUE THREAD

**Issue by lfenzo** [nvim-treesitter/nvim-treesitter#4471]
### Describe the highlighting problem

A couple of minor highlight groups are not displayed correctly for the Julia language.  In this issue I've (excuse me the pun) highlighted 4 problems in the current highlight definitions for Julia and compared them to a Python snippet showcasing the expected behavior (see images below). 

### Example snippet that causes the problem

```julia
function load_data(split::Symbol; n_obs::Int) :: Tuple
    dataset = CIFAR10(; Tx = Float32, split = split)
    X = reshape(dataset.features[:, :, :, begin:n_obs], :, n_obs) # flattening the image pixels
    y = categorical2onehot(dataset.targets[begin:n_obs], N_LABELS)
    return X, y
end
```

### Tree-sitter parsing result

For the snippet above, the result of `:TSPlaygoundToggle` is:

```
string_literal [0, 0] - [4, 3]
  section [0, 3] - [4, 0]
    indented_code_block [1, 0] - [3, 0]
    paragraph [3, 0] - [4, 0]
      inline [3, 0] - [3, 92]
function_definition [5, 0] - [10, 3]
  name: identifier [5, 9] - [5, 18]
  parameters: parameter_list [5, 18] - [5, 45]
    typed_parameter [5, 19] - [5, 32]
      parameter: identifier [5, 19] - [5, 24]
      type: identifier [5, 26] - [5, 32]
    keyword_parameters [5, 32] - [5, 44]
      typed_parameter [5, 34] - [5, 44]
        parameter: identifier [5, 34] - [5, 39]
        type: identifier [5, 41] - [5, 44]
  return_type: identifier [5, 49] - [5, 54]
  assignment [6, 4] - [6, 52]
    identifier [6, 4] - [6, 11]
    operator [6, 12] - [6, 13]
    call_expression [6, 14] - [6, 52]
      identifier [6, 14] - [6, 21]
      argument_list [6, 21] - [6, 52]
        named_argument [6, 24] - [6, 36]
          identifier [6, 24] - [6, 26]
          identifier [6, 29] - [6, 36]
        named_argument [6, 38] - [6, 51]
          identifier [6, 38] - [6, 43]
          identifier [6, 46] - [6, 51]
  assignment [7, 4] - [7, 65]
    identifier [7, 4] - [7, 5]
    operator [7, 6] - [7, 7]
    call_expression [7, 8] - [7, 65]
      identifier [7, 8] - [7, 15]
      argument_list [7, 15] - [7, 65]
        index_expression [7, 16] - [7, 54]
          field_expression [7, 16] - [7, 32]
            value: identifier [7, 16] - [7, 23]
            identifier [7, 24] - [7, 32]
          vector_expression [7, 32] - [7, 54]
            operator [7, 33] - [7, 34]
            operator [7, 36] - [7, 37]
            operator [7, 39] - [7, 40]
            range_expression [7, 42] - [7, 53]
              identifier [7, 42] - [7, 47]
              identifier [7, 48] - [7, 53]
        operator [7, 56] - [7, 57]
        identifier [7, 59] - [7, 64]
  line_comment [7, 66] - [7, 95]
  assignment [8, 4] - [8, 66]
    identifier [8, 4] - [8, 5]
    operator [8, 6] - [8, 7]
    call_expression [8, 8] - [8, 66]
      identifier [8, 8] - [8, 26]
      argument_list [8, 26] - [8, 66]
        index_expression [8, 27] - [8, 55]
          field_expression [8, 27] - [8, 42]
            value: identifier [8, 27] - [8, 34]
            identifier [8, 35] - [8, 42]
          vector_expression [8, 42] - [8, 55]
            range_expression [8, 43] - [8, 54]
              identifier [8, 43] - [8, 48]
              identifier [8, 49] - [8, 54]
        identifier [8, 57] - [8, 65]
  return_statement [9, 4] - [9, 15]
    bare_tuple [9, 11] - [9, 15]
      identifier [9, 11] - [9, 12]
      identifier [9, 14] - [9, 15]
```

### Example screenshot

![issue-julia](https://user-images.githubusercontent.com/49812445/224015505-0b4ce4bf-b966-4790-88fb-8dbdf871d3ba.png)

1. The assignments inside parenthesis are not highlighted
2. A type being highlighted as a variable, instead of being highlighted as type (as in the function header)
3. The `begin` range indexing keyword is parsed as identifier and not highlighted
4. Constant parsed as identifier

As a reference, the Python highlight groups shows 1, 2, and 4 correctly:

![image](https://user-images.githubusercontent.com/49812445/224016476-e176ae7a-25ac-4bf2-b218-507b78264930.png)

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.12.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "6.1.13-200.fc37.x86_64",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Wed Feb 22 17:53:57 UTC 2023"
}

## Parser/Features         H L F I J
  - arduino             ✓ ✓ ✓ ✓ ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - dockerfile          ✓ . . . ✓
  - git_rebase          ✓ . . . ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - help                ✓ . . . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - java                ✓ ✓ . ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - julia               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - sql                 ✓ . . . ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/builddir/build/BUILD/neovim-0.8.3/redhat-linux-build/cmake.config -I/builddir/build/BUILD/neovim-0.8.3/src -I/usr/include -I/usr/include/luajit-2.1 -I/builddir/build/BUILD/neovim-0.8.3/redhat-linux-build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.8.3/redhat-linux-build/include
Compiled by mockbuild@koji

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
@savq

**Comment by lfenzo** [comment]
I was also hoping that this would be the case, however I also tested the same snippets in other colorschemes and still the inconsistencies persist.

Here is an example with GruvBox...
![image](https://user-images.githubusercontent.com/49812445/224173003-0e83c69b-eae8-4461-add9-235283873c85.png)

... and with Tokyo Night:
![image](https://user-images.githubusercontent.com/49812445/224173610-7e85ae3f-24ad-44e1-a00a-d783eb938018.png)

As for the output for `:TSHighlightCaptureUnderCursor` with respect to the issues:
- For the `=`: `No highlight groups found`, whereas in the Python snippet it is highlighted as `@operator`
- All of the rest are parsed as `@variable`s in the Julia snippet:
    -  `N_LABELS` is parsed as `@variable` (`@variable`; `@constant` in the Python snippet)
    - `Float32` is parsed as `@variable` (`@variable`; `@type.builtin` in the Python snippet for the equivalent `float`)

**Comment by clason** [comment]
Don't compare with Python; that's a different language. The question is what makes sense for Julia.

**Comment by amaanq** [comment]
Well, is Float32 a built-in type? If so, 2 can be resolved easily.

As for the others, please think objectively and don't tailor to how you want things colored.

Is 1 an operator? Is that an operation occurring (assignment)?

Is begin a builtin function or keyword (e.g. for keywords - class, struct, enum, type, typedef, etc) or neither?

Are consts *by convention* typically in SCREAMING_SNAKE_CASE in Julia?

**Comment by savq** [comment]
Regarding the list of issues:

1. Assignments inside and outside parentheses are parsed differently because of bare tuples and other stuff. We could highlight both the same way. Though I do appreciate being able to tell them apart:
    <img width="188" alt="Bildschirmfoto 2023-03-09 um 18 18 56" src="https://user-images.githubusercontent.com/30883030/224182492-26ba1fef-ff4e-4700-93c4-99716958cee6.png">


2. Types are runtime values in Julia, and highlighting based on letter casing usually causes false positives in math-heavy code. There's a pattern at the top of `queries/julia/highlights.scm` that's commented out that will highlight types. But I'd be against enabling it by default.
3. `begin` as a range index _is_ an identifier. We could use a predicate pattern to highlight it as a constant, but it's important to use a different color for `begin` keyword and `begin` index, since it's the same word in different contexts.
4. Same as 2.

**Comment by amaanq** [comment]
> Regarding the list of issues:
> 
> 1. Assignments inside and outside parentheses are parsed differently because of bare tuples and other stuff. We could highlight both the same way. Though I do appreciate being able to tell them apart:
>    <img alt="Bildschirmfoto 2023-03-09 um 18 18 56" width="188" src="https://user-images.githubusercontent.com/30883030/224182492-26ba1fef-ff4e-4700-93c4-99716958cee6.png">
> 2. Types are runtime values in Julia, and highlighting based on letter casing usually causes false positives in math-heavy code. There's a pattern at the top of `queries/julia/highlights.scm` that's commented out that will highlight types, but I'd be against enabling it by default.
> 3. `begin` as a range index _is_ an identifier. We could use a predicate pattern to highlight it as a constant, but it's important to use a different color for `begin` keyword and `begin` index, since it's the same word in different contexts.
> 4. Same as 2.

Well, I'd like to have the maintainer chime in if he's still active..now I'm conflicted about 1 as well.

For 2, I was just going to capture the builtins anyways, like Int/Float/String types

So for 3, it's just not a keyword then, so this isn't a problem

4, best to let the maintainer decide

**Comment by savq** [comment]
For `begin`, the simplest pattern would be

```scheme
((identifier) @constant
  (#any-of? @constant "begin" "end"))
```


If we wanted to highlight `begin` only in range expressions, we'd have to account for arithmetic expressions like `(begin+1):end`:
```scheme
(range_expression
  [
    (identifier) @constant
    (_ (identifier) @constant)
    (_ (_ (identifier) @constant))
  ]
  (#any-of? @constant "begin" "end"))
```

And that looks... bad.

**Comment by amaanq** [comment]
Why should begin be highlighted as a constant in a range expression?

**Comment by savq** [comment]
It used to be highlighted like a constant, but used a simpler pattern. I was the one that removed it.

**Comment by amaanq** [comment]
From an objective POV, should it really be a constant then? I'm guessing it's just convention to call the beginning identifier of a range exp as begin, hence the original decision (guessing).

**Comment by savq** [comment]
Since `begin` is a keyword, you cannot use it as an identifier, but in indices [the compiler will lower `begin` to `firstindex()`](https://docs.julialang.org/en/v1/base/collections/#Base.firstindex).

**Comment by amaanq** [comment]
> Since `begin` is a keyword, you cannot use it as an identifier, but in indices [the compiler will lower `begin` to `firstindex()`](https://docs.julialang.org/en/v1/base/collections/#Base.firstindex). It's a syntax sugar identifier, if that makes sense.

In this specific case, how about `@variable.builtin`?

**Comment by savq** [comment]
That looks much better. I agree `@variable.builtin` seems more adequate.

I didn't know `#has-ancestor?` existed. We can use it with `index_expression` to highlight `A[begin]` correctly too.

```scheme
((identifier) @variable.builtin
  (#any-of? @variable.builtin "begin" "end")
  (#has-ancestor? @variable.builtin index_expression))
```
