### ISSUE TITLE
[Ruby highlight] no TSType highlighting at all

### ISSUE THREAD

**Issue by bluz71** [nvim-treesitter/nvim-treesitter#448]
Hello,

With [this Ruby file](https://github.com/bluz71/vim-nightfly-guicolors/blob/master/samples/ruby.rb) there is not `TSType` highlighting at all. Actual Ruby types such as `AlbumsHelper` and `AlbumsController` are being highlighted as `TSConstant` as seen in this image (noting that types would normally be green with my color scheme):

<img width="543" alt="Screen Shot 2020-09-12 at 12 04 11 pm" src="https://user-images.githubusercontent.com/11382509/92984769-16cbba00-f4f0-11ea-8aae-e11ec7b03c97.png">

Contrast with Atom which correctly is highlighting Ruby types in the theme Type color of yellow:

<img width="596" alt="Screen Shot 2020-09-12 at 12 05 04 pm" src="https://user-images.githubusercontent.com/11382509/92984790-3a8f0000-f4f0-11ea-91f1-a4d45650bf30.png">

If one looks through `ruby/highlights.scm` there is no definition for `@type` unlike in Python for example (a similar'ish dynamic scripting language).

Best regards.

**Comment by bluz71** [comment]
Tested. 

Unfortunately, I see no change. Ruby types are still being highlighted as `TSConstant`, purple in the first screenshot, not as `TSType`.

May I request a re-opening of this?

**Comment by TravonteD** [comment]
@bluz71 I just retested with the latest update and class and module definitions are highlighted with TSType. In what way is it failing for you?

**Comment by bluz71** [comment]
It still appears with the latest version of this plugin that highlighting Ruby class types are via the `TSConstant` highlight group and not `TSType`.

Using [this Ruby file](https://github.com/bluz71/vim-nightfly-guicolors/blob/master/samples/ruby.rb) I just set `TSConstant` to strong crimson color, notice the types such as `AlbumsHelper` are being highlighted in the same color as `:require_admin` symbols (which are correctly highlighted as `TSConstant`):

<img width="550" alt="Screen Shot 2020-09-13 at 11 09 24 am" src="https://user-images.githubusercontent.com/11382509/93007903-9cfc0500-f5b1-11ea-83ab-19fa0d623948.png">

Constrast with JavaScript which is highlighting types in green color (my `Type` color which `TSType` links to):

<img width="565" alt="Screen Shot 2020-09-13 at 11 10 55 am" src="https://user-images.githubusercontent.com/11382509/93007915-d03e9400-f5b1-11ea-8921-2bbaa290da17.png">

I expect in the Ruby file `AlbumsHelper`, `AlbumsController`, `ApplicationController` and `Album` to be in green.

A query, is there Vimscript or Lua I can run in the Neovim command line that will display the highlight group under the cursor?

With normal Vim highlighting I can do `:echo synIDattr(synID(line("."), col("."), 1), "name")` to display the highlight group. But that does not seem to work with Treesitter. It would help with debugging if I can quickly print the current highlight group under the cursor.

Also, can you open this [Ruby file](https://github.com/bluz71/vim-nightfly-guicolors/blob/master/samples/ruby.rb), take a screenshot and post it here along with your `TSConstant` and `TSType` values. It is strange it is working for you but not for me. We must be missing something obvious, either a mistake on my part or an uncommitted file?

Note, I deleted the treesitter plugin and fully reinstalled with new downloaded and compiled parsers.

**Comment by TravonteD** [comment]
![highlight-test](https://user-images.githubusercontent.com/19380243/93008407-53c09c80-f542-11ea-98b7-49e2853bd432.png)

Here is the screenshot of my highlighting on the latest update. 
As you can see by the highlight groups the types are highlighted using TSType.

**Comment by bluz71** [comment]
Very interesting.

Notice that your Ruby symbols such as `:require_admin` and `:set_artist` are not being colored as `TSConstant` whilst mine are, along with my Types, but not yours.

Ok, we need to debug this issue. Something very strange is going on.

First would be a way to display the current Treesitter highlight group under the cursor. As I mentioned above, with normal Vim highlighting I can do `:echo synIDattr(synID(line("."), col("."), 1), "name")` to display the highlight group for the item under the cursor. What is the equivalent in Treesitter?

**Comment by bluz71** [comment]
Here is the screenshot in my case, which is very different to @TravonteD:

<img width="586" alt="Screen Shot 2020-09-13 at 1 11 27 pm" src="https://user-images.githubusercontent.com/11382509/93009298-a772ca80-f5c2-11ea-9f93-c2111a8996f1.png">

Something strange is going on, almost like I am not running the correct version? (Noting I did a full plugin delete and reinstall).

**Comment by theHamsta** [comment]
Maybe you're using different parser versions? For debugging, I like to paste the highlighting query in our playground plugin. It highlights which parts of the buffer are`@type` and which `@constant`.

Also note, that treesitter highlighting still has problems with prioritizing one type of highlights over another. So it might be that both `TSType` and another highlights are applied but the visual appearance depends on how you highlight groups are defined.

**Comment by bluz71** [comment]
Is there any type of Treesitter debugging available inside Neovim?

It would be really nice to know if `@type` / `TSType` or `@constant / `TSConstant` are in effect for the word under the cursor.

**Comment by bluz71** [comment]
> Maybe you're using different parser versions?

How do I query this?

**Comment by vigoux** [comment]
What you can do is install the `nvim-treesitter/playground` plugin, this is what most of us use when debugging.
More infos on the README there.

**Comment by bluz71** [comment]
Thanks, the playground will indeed be very useful, hopefully it can help solve this Ruby riddle.

**Comment by TravonteD** [comment]
I believe that I've solved the problem. I looked to be an issue with my setup. Try this branch of the plugin [ruby-type-fix](https://github.com/TravonteD/nvim-treesitter/tree/ruby-type-fix) and let me know if the highlighting is as expected. If so, we'll get it merged in!

**Comment by bluz71** [comment]
@TravonteD,

I just tested your `ruby-type-fix` branch and it works great.

New screenshot with Ruby Types now being **correctly** highlighted in green:

<img width="549" alt="Screen Shot 2020-09-14 at 1 06 56 pm" src="https://user-images.githubusercontent.com/11382509/93039584-35b28380-f68b-11ea-8468-02e6e2db8692.png">

Compare with before, too much purple, types highlighted as `TSConstant`:

<img width="586" alt="Screen Shot 2020-09-13 at 1 11 27 pm" src="https://user-images.githubusercontent.com/11382509/93009298-a772ca80-f5c2-11ea-9f93-c2111a8996f1.png">

Once merged this issue can be closed.

Many thanks.

**Comment by bluz71** [comment]
Just tested `master` branch which contains the #464 fix.

Confirmed, issue is now fixed.

Many thanks.
