### ISSUE TITLE
Some parsers fail to compile on macOS 

### ISSUE THREAD

**Issue by LachlanGray** [nvim-treesitter/nvim-treesitter#4482]
### Describe the bug

After updating today, treesitter fails to compile the parsers for html, cmake, yaml, bash, python, and cpp. It looks like the standard library isn't getting included.

Each of them produce an error like this in turn:

```
nvim-treesitter[html]: Error during compilation
In file included from src/scanner.cc:1:
In file included from ./src/tree_sitter/parser.h:10:
/Library/Developer/CommandLineTools/usr/include/c++/v1/stdlib.h:148:34: error: unknown type name 'ldiv_t'
inline _LIBCPP_INLINE_VISIBILITY ldiv_t div(long __x, long __y) _NOEXCEPT {
                                 ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/stdlib.h:149:12: error: no member named 'ldiv' in the global namespace
  return ::ldiv(__x, __y);
         ~~^
/Library/Developer/CommandLineTools/usr/include/c++/v1/stdlib.h:152:34: error: unknown type name 'lldiv_t'
inline _LIBCPP_INLINE_VISIBILITY lldiv_t div(long long __x,
                                 ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/stdlib.h:154:12: error: no member named 'lldiv' in the global namespace
  return ::lldiv(__x, __y);
         ~~^
In file included from src/scanner.cc:1:
./src/tree_sitter/parser.h:16:9: error: unknown type name 'uint16_t'
typedef uint16_t TSStateId;
        ^
./src/tree_sitter/parser.h:19:9: error: unknown type name 'uint16_t'
typedef uint16_t TSSymbol;
        ^
./src/tree_sitter/parser.h:20:9: error: unknown type name 'uint16_t'
typedef uint16_t TSFieldId;
        ^
./src/tree_sitter/parser.h:26:3: error: unknown type name 'uint8_t'
  uint8_t child_index;
```

The other parsers install normally.

### To Reproduce

Run `:TSInstall <lang>` for any of the six parsers

### Expected behavior

Parser to install normally

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v19.7.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 14.0.0 (clang-1400.0.29.202)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "arm64",
  release = "22.2.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.2.0: Fri Nov 11 02:06:26 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8112"
}

## Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - help                ✓ . . . ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - latex               ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ . ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.3/share/nvim"

Run :checkhealth for more info
```

### Additional context

Neovim is installed via homebrew.

I've tried using different compilers via `require 'nvim-treesitter.install'.compilers = { 'compiler'}`. 

I reinstalled Xcode developer tools, and also tried llvm (installed from homebrew) but there is no difference.

**Comment by LachlanGray** [comment]
I found the solution shortly after writing, it's not exactly a bug, maybe more of a feature request.

 If anyone has this problem, macOS Catalina+ clang has [some kind of linking problem](https://developer.apple.com/forums/thread/666700).

adding 
```
export CPLUS_INCLUDE_PATH=/Library/Developer/CommandLineTools/usr/include/c++/v1:/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include
```
to my .zshrc solved the issue.

Can this maybe be accounted for by `TSInstall`? Or maybe a note in the trouble shooting section could be a good idea

**Comment by clason** [comment]
Sorry, but this means your environment is messed up. Parser compilation works just fine on macOS. (Do not mix and match compilers and SDK!)

**Comment by theHamsta** [comment]
Sorry, our documentation states that we currently require your setup to be able to compile C++. While compilation at user-side might not be ideal, we hope that we offer binary packages in future (preferably via the tree-sitter project and not just for our project). We can't provide a build system that analyses each setup. It seems like our setup is unable to find clang standard C library headers which would be essential for any compiler invocation.

**Comment by LachlanGray** [comment]
Thanks, that makes sense.

One way to detect it could maybe be to echo `DYLD_LIBRARY_PATH` or `LD_LIBRARY_PATH` for macOS and check if the output contains `usr/include` and `c++/v1` or something like that.

It might just be an issue with my setup though, it doesn't sound like anyone else is running into this.

But a short mention in the troubleshooting section about compiler problems could help some people out. It took me a while to figure out where my problem was.
