### ISSUE TITLE
Error in C indentation triggered by multiple assignment and format macro constants

### ISSUE THREAD

**Issue by scienceplease** [nvim-treesitter/nvim-treesitter#4525]
### Describe the bug

An error in C indentation logic is triggered by multiple assignment and format macro constants. Example below is illustrated.

```c
#include <stdint.h>
#include <inttypes.h>
#include <stdio.h>

static int a, b, c;
a = b = c = 0;
    // <-- Indentation on this (and every subsequent) line is 1 level too deep.

static int d = 0, e = 0, f = 0;
    // <-- Indentation on this (and every subsequent) line is 1 level too deep.

int main(void) {
    printf("%" PRIu64 "\n", (uint64_t)0);
        // <-- Indentation on this (and every subsequent) line is 1 level too deep.
        fflush(stdout);
        // <-- Indentation remains 1 level too deep.
}
```
The macro `PRIu64` is defined in <inttypes.h> as the following. The explicit expansion exhibits the same bug.
```c
#define PRIu64	__PRI64_PREFIX "u"
printf("%" __PRI64_PREFIX "u" "\n", (uint64_t)0);
```

### To Reproduce

Minimal reproducible .c file illustrated above in bug description.

### Output of `:checkhealth nvim-treesitter`

```markdown
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.18.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "6.1.18-100.fc36.x86_64",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Sat Mar 11 16:46:48 UTC 2023"
}

## Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cmake               ✓ . ✓ . .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - cuda                ✓ ✓ ✓ ✓ ✓
  - help                ✓ . . . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - latex               ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ . ✓
  - ninja               ✓ . ✓ ✓ .
  - python              ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - tlaplus             ✓ ✓ ✓ . ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓
  - zig                 ✓ . ✓ ✓ ✓
```

### Output of `nvim --version`

```text
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3

Features: +acl +iconv +tui
```

**Comment by lucario387** [comment]
```c
#include <stdint.h>
#include <inttypes.h>
#include <stdio.h>

static int a, b, c;
a = b = c = 0;
    // <-- Indentation on this (and every subsequent) line is 1 level too deep. 
    // I cannot reproduce this
static int d = 0, e = 0, f = 0;
    // <-- Indentation on this (and every subsequent) line is 1 level too deep.
    // Also can't
int main(void) {
    printf("%" PRIu64 "\n", (uint64_t)0);
        // <-- Indentation on this (and every subsequent) line is 1 level too deep.
        // Can reproduce this
        fflush(stdout);
        // <-- Indentation remains 1 level too deep.
}
```

**Comment by amaanq** [comment]
> a = b = c = 0;
    // <-- Indentation on this (and every subsequent) line is 1 level too deep. 
    // I cannot reproduce this

I can reproduce this one (but it stops when the macro parsing bug is removed), but this is really reaching the limit of a tree-sitter parser, it cannot expand macros and thus cannot tell if the concatenated string is valid - it only allows regular string literals

**Comment by lucario387** [comment]
> > a = b = c = 0;
> > // <-- Indentation on this (and every subsequent) line is 1 level too deep.
> > // I cannot reproduce this
> 
> I can reproduce this one (but it stops when the macro parsing bug is removed), but this is really reaching the limit of a tree-sitter parser, it cannot expand macros and thus cannot tell if the concatenated string is valid - it only allows regular string literals

The problem lies weirdly in not having `@indent_end` at `;`
which I don't know why it is, but okay

**Comment by lucario387** [comment]
> ```c
> #include <stdint.h>
> #include <inttypes.h>
> #include <stdio.h>
> 
> static int a, b, c;
> a = b = c = 0;
>     // <-- Indentation on this (and every subsequent) line is 1 level too deep.
> 
> static int d = 0, e = 0, f = 0;
>     // <-- Indentation on this (and every subsequent) line is 1 level too deep.
> 
> int main(void) {
>     printf("%" PRIu64 "\n", (uint64_t)0);
>         // <-- Indentation on this (and every subsequent) line is 1 level too deep.
>         fflush(stdout);
>         // <-- Indentation remains 1 level too deep.
> }
> ```

Actually, even weirder, despite this having zero relationship to `@aligned_indent` bugfix of #4524, the branch actually fixed 3 of the 4 cases in this issue :)
