### ISSUE TITLE
Typescript highlights break with `import { type Foo } from './foo`

### ISSUE THREAD

**Issue by grddavies** [nvim-treesitter/nvim-treesitter#4546]
### Describe the bug

The following valid Typescript code breaks highlights:

```typescript
import { type Foo } from './blah'
```

Removing `type` fixes highlights.

Details: https://www.typescriptlang.org/docs/handbook/modules.html#importing-types

### To Reproduce

1. run `echo "import { type Foo, Bar } from './blah'" > example.ts`
2. nvim ./example.ts
Expected:
- Highlights work after import statement
Actual:
- Highlights break after import statement
3. Remove `type` import modifier
4. See working highlights

### Expected behavior

Consistent highlighting when explicitly importing types

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v19.7.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.19.0-35-generic",
  sysname = "Linux",
  version = "#36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - haskell             ✓ . ✓ . ✓
  - help                ✓ . . . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - r                   ✓ ✓ . ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ .
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
```

### Output of `nvim --version`

```text
NVIM v0.9.0-dev-1263+g3285cd6ec-dirty
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/linuxbrew/.linuxbrew/Cellar/neovim/HEAD-3285cd6/share/nvim"
```

## Screenshots:
![image](https://user-images.githubusercontent.com/24638517/226903634-61eb5cc3-dc55-4721-89f6-77393ae004f3.png)

Comparison without `type` import modifier:
![image](https://user-images.githubusercontent.com/24638517/226903760-bf87f0ff-7550-4f62-b912-c2fdeb278b4d.png)

## TS parse outputs:
```typescript
import { Foo, Bar } from './blah'
```
```
import_statement [0, 0] - [0, 33]
  import_clause [0, 7] - [0, 19]
    named_imports [0, 7] - [0, 19]
      import_specifier [0, 9] - [0, 12]
        name: identifier [0, 9] - [0, 12]
      import_specifier [0, 14] - [0, 17]
        name: identifier [0, 14] - [0, 17]
  source: string [0, 25] - [0, 33]
    string_fragment [0, 26] - [0, 32]
```
----
```typescript
import { type Foo, Bar } from './blah'
```
```
import_statement [0, 0] - [0, 38]
  import_clause [0, 7] - [0, 24]
    named_imports [0, 7] - [0, 24]
      import_specifier [0, 9] - [0, 17]
        name: identifier [0, 14] - [0, 17]
      import_specifier [0, 19] - [0, 22]
        name: identifier [0, 19] - [0, 22]
  source: string [0, 30] - [0, 38]
    string_fragment [0, 31] - [0, 37]
```

**Comment by amaanq** [comment]
Not sure what commit of the ts parser/nvim-ts you're on, but it seems fine for me:

![image](https://user-images.githubusercontent.com/29718261/226907508-a24e30c8-69b8-4c93-b2c7-d439d0d9bd92.png)

**Comment by Nargonath** [comment]
@grddavies I have the same problem as you with the highlight breaking up. Do you remember what code you had that disabled the TS highlighting?

**Comment by grddavies** [comment]
> @grddavies I have the same problem as you with the highlight breaking up. Do you remember what code you had that disabled the TS highlighting?

By the looks of it I wasn't passing `highlighting = {enable = true}` during setup of the `nvim-treesitter` plugin. See the commit I made to fix in my dotfiles https://github.com/grddavies/dotfiles/commit/e4a04f4e3bf6bacf719429c6c6a2112d3aff7266

**Comment by Nargonath** [comment]
Ok, thank you @grddavies.
