### ISSUE TITLE
Looking for a way to toggle semantic token highlighting on demand

### ISSUE THREAD

**Issue by unphased** [nvim-treesitter/nvim-treesitter#4559]
**Is your feature request related to a problem? Please describe.**

I found that often semantic token highlighting is often not even as granular as treesitter based syntax highlighting. since LSP based highlighting is much slower than treesitter also it may be good on many lang servers (good example is the dockerfile language server, it just makes all bash commands one color...) to disable semantic token highlighting.

**Describe the solution you'd like**
I want a way to toggle semantic token highlighting provided by LSPs on and off on demand since I can imagine sometimes the semantic information could be more in-depth (e.g. I expect this to be the case for c++)

**Describe alternatives you've considered**
I found the function `vim.lsp.semantic_tokens.stop()`, and this seems a lot closer to what I want to use than e.g. LspStop but I think I need to make some sort of menu so I can quickly tell it *which* LSP I want to toggle the semantic tokens for. Are there any plugins that already can do this or do I need to build this myself?

**Comment by unphased** [comment]
I got nearly 2k views [here](https://www.reddit.com/r/neovim/comments/11d50nd/how_to_toggle_semantic_highlighting_on_demand/) for this question but no input. 

I am definitely willing to try it out myself soon, I think there are a few menu ui approaches (including one built into neovim i think) that i can use.

**Comment by amaanq** [comment]
Disable the highlights for LSPs you want disabled. e.g.
![image](https://user-images.githubusercontent.com/29718261/227763087-b3e82e6f-42cc-4570-a682-db99d8d7adb4.png)

Display here is being overridden by the LSP (which I don't mind, I like it in this case as interfaces should be different imo). But, you could simply hl "@lsp.type.interface.rust" (notice the rust suffix) to disable it based on the language. This won't work if you have two lsps for one language (but is that even done?)

**Comment by clason** [comment]
Semantic tokens are a feature of the (upcoming!) Neovim release and have nothing to do with nvim-treesitter. `:help news` explicitly tells you how to disable it for specific servers.

**Comment by unphased** [comment]
Thanks, silly i missed the obvious superiority of filtering these at the highlight system!

**Comment by unphased** [comment]
OK but what about when the language server isn’t making an effort to add specific selectors? I have a screenshot but on my ipad and trying to work out how to paste it here, hold on.

**Comment by clason** [comment]
Your Neovim version is outdated. (And again, this is completely unrelated to nvim-treesitter, so please ask further questions on Matrix.)
