### ISSUE TITLE
CMake/C++ error while compiling

### ISSUE THREAD

**Issue by benmanone** [nvim-treesitter/nvim-treesitter#4560]
### Describe the bug

I can't install the treesitter plugin for c++ or cmake. When I try to, a long list of warnings and errors appears. There are 108 warnings which are mostly saying that a pointer is missing a nullability type specifier. Example:
```/usr/local/include/stdlib.h:134:25: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
double   atof(const char *);
                         ^
/usr/local/include/stdlib.h:134:25: note: insert '_Nullable' if the pointer may be null
double   atof(const char *);
                         ^
                          _Nullable
/usr/local/include/stdlib.h:134:25: note: insert '_Nonnull' if the pointer should never be null
double   atof(const char *);
                         ^
                          _Nonnull
```
The 1 error says:
```using std::iswspace;
      ~~~~~^~~~~~~~
           isspace
/Applications/Xcode-14.1.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/cctype:112:9: note: 'isspace' declared here
using ::isspace _LIBCPP_USING_IF_EXISTS;
```
What did I do wrong?

### To Reproduce

I installed treesitter through lazy:
`require("lazy").setup({
  "nvim-treesitter/nvim-treesitter",
})`
My treesitter setup:
```require'nvim-treesitter.configs'.setup {
   ensure_installed = { "c", "cpp", "help", "lua", "vim", "rust", "cmake"},
   sync_install = false,
   auto_install = true,

   highlight = {
      enable = true,
   }
}
```

### Output of `:checkhealth nvim-treesitter`

```
nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.12.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 14.0.0 (clang-1400.0.29.202)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "22.1.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64"
}

## Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - help                ✓ . . . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.8.3/share/nvim"

Run :checkhealth for more info
```

### Additional context

I'm on MacOS

**Comment by amaanq** [comment]
Gonna guess it has to do with your compiler, try using something else like gcc with this:
```lua
require 'nvim-treesitter.install'.compilers = { "gcc" }
```

**Comment by clason** [comment]
It's almost invariably due to a bored Xcode installation (wrong or incompatible SDK settings). Try removing Xcode and installing the CLI developer tools

**Comment by benmanone** [comment]
@amaanq Thanks for the response, I tried gcc, g++ and g++-12 but none of them seem to work

**Comment by benmanone** [comment]
@clason Thanks for the response, I just used the xcodes version manager to remove v14.1 which is what I had installed. I'll see if reinstalling helps

**Comment by theHamsta** [comment]
It could also be missing include in the usptream projects with which libc++ has problems. Can you give us the full output? You could use a command similar to our CI `nvim --headless "-cTSInstallSync cpp" -cq" to forward the output to a file. We need the part of the output that says `error: `

**Comment by benmanone** [comment]
@theHamsta Sorry, I missed that line out in my selection. The final 8 lines are:
```
src/scanner.cc:9:10: error: no member named 'iswspace' in namespace 'std'; did you mean simply 'iswspace'?
  while (std::iswspace(lexer->lookahead)) {
         ^~~~~~~~~~~~~
         iswspace
/usr/local/include/_wctype.h:105:1: note: 'iswspace' declared here
iswspace(wint_t _wc)
^
180 warnings and 1 error generated.
```

**Comment by benmanone** [comment]
@theHamsta Actually, there is a TS error which only appeared with `TSInstallSync cpp`:
```
Error during compilation
Failed to execute the following command:
{
  cmd = "cc",
  err = "Error during compilation",
  info = "Compiling...",
  opts = {
    args = { "-o", "parser.so", "-I./src", "src/parser.c", "src/scanner.cc", "-shared", "-Os", "-lstdc++", "-fPIC" },
    cwd = "/Users/benjychada/.local/share/nvim/tree-sitter-cpp"
  }
}
```

**Comment by theHamsta** [comment]
> @theHamsta Sorry, I missed that line out in my selection. The final 8 lines are:
> 
> ```
> src/scanner.cc:9:10: error: no member named 'iswspace' in namespace 'std'; did you mean simply 'iswspace'?
>   while (std::iswspace(lexer->lookahead)) {
>          ^~~~~~~~~~~~~
>          iswspace
> /usr/local/include/_wctype.h:105:1: note: 'iswspace' declared here
> iswspace(wint_t _wc)
> ^
> 180 warnings and 1 error generated.
> ```

Can you check whether the original parser compiles in tree-sitter-cpp either via `tree-sitter generate && tree-sitter test` or `npm install` compiles. Can you check their scanner.cc whether they include the correct header? They need to include the c++ version of that c header (i.e. without the `.h` extension) to have the function defined in `std` namespace. Can you fix compilation by editing scanner.cc in tree-sitter-cpp?

**Comment by theHamsta** [comment]
@jdrouhard could you have a look onto this. The user seems to have `iswspace` but not `std::iswspace`. Could this be a rare problem with the includes in scanner.cc or a problem with the libc++ installation

**Comment by jdrouhard** [comment]
It seems like your default compiler toolchain is gcc installed by homebrew (hence the /use/local paths to headers in your errors, and I noticed a `-lstdc++`). I'm guessing homebrew because your nvim was compiled by Brew@Ventura. 

Did you happen to brew link that gcc install so it became the default "cc" and toolchain on your PATH?

```sh
brew install coreutils
greadlink -f `which cc`
```

What does this say?

I don't actually have much experience using gcc on macOS, but my recommendation is to just use apple clang from Xcode's command line tools, or llvm from brew.

The nvim-treesitter team would have to comment on how compiler flags are deduced (platform/detected compiler?) but it would seem that brew gcc on macOS doesn't directly play nice. Or the package isn't built right. It's not finding the correct c++ headers.

**Comment by benmanone** [comment]
@jdrouhard
I have coreutils already installed. The output is:
```
~/`which
~/cc`
```

**Comment by jdrouhard** [comment]
> @jdrouhard I have coreutils already installed. The output is:
> 
> ```
> ~/`which
> ~/cc`
> ```

You must have copied/typed the command wrong, it should have given you a path.

First, even with brew gcc or llvm installed, there is still a system symlink from "cc", "gcc" etc all pointing to apple clang. Doesn't matter what you put in the treesitter config for compilers unless you put the _full path_ to the compiler brew installed.

I dug a little more into this, though. You must be using an Intel mac since brew is installing into /usr/local (and not /opt/). Apple clang (installed with xcode command line tools) will actually search for headers in /usr/local if they exist (I'm guessing here, based on the search paths _my_ apple clang is looking for on my Apple silicon Mac).

It's possible that if there is a gcc installed via brew such that headers now exist in `/usr/local/include/...`, the Apple clang toolchain will use headers from the gcc install and not its own. If this is true, it does seem like Intel Homebrew is broken when you've installed gcc. I don't have an Intel mac to test this theory on, but I know that Intel vs Apple silicon macs are different when it comes to how homebrew is set up.

Unless you really need it, try uninstalling your brew gcc completely.

**Comment by benmanone** [comment]
@jdrouhard Ah sorry, I wasn't looking too hard at it. The output is /usr/bin/cc. I `brew uninstall`ed gcc but treesitter still won't compile even after putting a full path to gcc in treesitter's compilers (/usr/bin/gcc).

**Comment by jdrouhard** [comment]
`/usr/bin/gcc` is a symlink to apple clang, putting that full path isn't going to change anything--I was saying if you left gcc installed you'd have to put something like /usr/local/bin/gcc-12.

Either way, you must still have bad headers installed under /usr/local from something. You may have other gcc versions installed as well: `brew list -1 | grep gcc`.

You shouldn't have a /usr/local/include/stdlib.h on your system at all if you've properly cleaned your system.

**Comment by benmanone** [comment]
So is it safe to just delete the stdlib in /usr/local/include then? What should I do to properly remove non-apple clang?

**Comment by jdrouhard** [comment]
> So is it safe to just delete the stdlib in /usr/local/include then? What should I do to properly remove non-apple clang?

No, you need to figure out where the file came from and prune the whole thing. If you just delete files you're likely to bork your system.

**Comment by benmanone** [comment]
I don't know why that file is there, but it looks like all the header files there are copies from `/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/` made about two months ago. Do you think it's safe to remove all of these header files then?

**Comment by jdrouhard** [comment]
My theory is still that those are gcc headers and wouldn't be copies of files from your apple command line tools install. Homebrew borked something on your system when you installed gcc. Make sure you have no gccs linked or installed, I gave the command above to check for installed gccs. Other than that, not sure how to help.

**Comment by benmanone** [comment]
Should I also uninstall llvm? Also, thanks for your help

**Comment by benmanone** [comment]
@theHamsta It doesn't compile. The error message is:
```
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module 'tree-sitter-c/grammar'
Require stack:
- ~/.local/share/nvim/tree-sitter-cpp/grammar.js
- ~/.local/share/nvim/tree-sitter-cpp/[stdin]
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (~/.local/share/nvim/tree-sitter-cpp/grammar.js:1:11)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '~/.local/share/nvim/tree-sitter-cpp/grammar.js',
    '~/.local/share/nvim/tree-sitter-cpp/[stdin]'
  ]
}

Node.js v18.12.1
Node process exited with status 1
```
I ran `tree-sitter generate && tree-sitter test` in `~/.local/share/nvim/tree-sitter-cpp`. I tried editing src/scanner.cc but it didn't seem to have an effect and it was reset after I tried compiling.

**Comment by benmanone** [comment]
Fixed - had aliases to some old versions of header files and needed to delete.
