### ISSUE TITLE
Adding a configuration option to use higher-levels of optimizations for the parsers

### ISSUE THREAD

**Issue by lyu** [nvim-treesitter/nvim-treesitter#4561]
**Is your feature request related to a problem? Please describe.**
I'm using neovim on a pretty weak ARM SBC and I would like to at least try to use higher optimization levels (e.g. `-O3 -march=native`) for the parsers to see if it improves performance, but it seems that the optimization level is [hard-coded as `-Os`](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/shell_command_selectors.lua#L114)?

**Describe the solution you'd like**
Is it possible to add configuration options like
```
require 'nvim-treesitter.install'.cflags = { "-O3 -march=native" }
require 'nvim-treesitter.install'.cxxflags = { "-O3 -march=native" }
```
For user specified CFLAGS and CXXFLAGS? Thanks!

**Comment by clason** [comment]
You can always compile parsers manually and place them in runtime path. This makes more sense for testing than adding (even more) config options here.
