### ISSUE TITLE
Functions called with template strings error with "no parser for <funcname> language"

### ISSUE THREAD

**Issue by gsuuon** [nvim-treesitter/nvim-treesitter#4572]
### Describe the bug

A function called with a template string errors (via `vim.notify`) with `no parser for 'fn' language, see :help treesitter-parsers`. This happens in both ts and js.

### To Reproduce

Have a function that calls a template literal:
```js
fn(``)
```

### Expected behavior

No errors or a config to silence the error reporting for missing injections. Every time I edit a file using template strings I get a bunch of error notifications.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v19.3.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `zig` executable found. Selected from { "zig", "cl", "clang" }
  Version: info: Usage: zig [command] [options]
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.22621",
  sysname = "Windows_NT",
  version = "Windows 11 Home"
} ~

Parser/Features         H L F I J
  - comment             ✓ . . . .
  - help                ✓ . . . ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luap                ✓ . . . .
  - norg                . . . . .
  - nu                  ✓ ✓ ✓ . ✓
  - prisma              ✓ . . . .
  - regex               ✓ . . . .
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.0-dev-1230+gd1e0f7454
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

**Comment by lucario387** [comment]
Sections that caused the problem:

https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/ecma/injections.scm#L7-L15

@amaanq @bennypowers

**Comment by lucario387** [comment]
I'm not sure of the exact use case for that query, even though it's somewhat documented down in the code. Will wait for @bennypowers changes, or I will comment it out and pinged him later again

**Comment by bennypowers** [comment]
the parenthesized form was added in https://github.com/nvim-treesitter/nvim-treesitter/commit/e3ebc8ec5d586162f3c408417621daa59ba8ea62 but that commit _replaced_ the template tag form (without parens). This was bad because in ecmascript ``` svg`hi` ``` and ``` svg(`hi`) ``` are two very different things, with the former being the more common case but the latter also being valid. #4520 fixed that, but it's possible it introduced this regression

**Comment by lucario387** [comment]
So it's e3ebc8ec5d586162f3c408417621daa59ba8ea62 that introduced the issue. Sorry for `@`-ing you then :D

**Comment by bennypowers** [comment]
IMO the fewer exceptions the better.

`svg` tag is an exception because it uses the HTML parser instead of a (non-existent) svg parser, but other than that, I'd expect html/sql/graphql/markdown/scala/whatever to function as if the tag function name sets the parser for the template contents

**Comment by lucario387** [comment]
So another directive, okay

**Comment by amaanq** [comment]
Weirdly I don't get the error when I have 
```
fn(``)
``` 
in a JS/TS file

**Comment by theHamsta** [comment]
Are you using any additional tree-sitter modules?

**Comment by theHamsta** [comment]
> Weirdly I don't get the error when I have
> 
> ```js
> fn(``)
> ```
> 
> in a JS/TS file

me neither. Neovim should not inject a language when it doesn't have a parser for it.
