### ISSUE TITLE
[un]commenting with tcomment_vim doesn't update the highlighting

### ISSUE THREAD

**Issue by ahmedelgabri** [nvim-treesitter/nvim-treesitter#460]
**Describe the bug**
When [un]commenting an area with https://github.com/tomtom/tcomment_vim the syntax highlighting doesn't get updated

**To Reproduce**
1. Open a file that is supported by treesitter (in my case, I tried `.js`, `.lua` & `.py`)
2. in normal mode do `gcc` on a line

Here is gif for the issue using treesitter-playground to show that the syntax tree doesn't get updated.

![Kapture 2020-09-13 at 17 59 39](https://user-images.githubusercontent.com/63876/93022811-6511b380-f5eb-11ea-964c-e07487a8e7af.gif)

**Expected behavior**
Highlight gets updated

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

      health#nvim_treesitter#check
      ========================================================================
      ## Installation
        - OK: `git` executable found.
        - OK: `cc` executable found.

      ## elm parser healthcheck
        - OK: elm parser found.
        - WARNING: No `highlights.scm` query found for elm
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `locals.scm` query found for elm
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `textobjects.scm` query found for elm
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `fold.scm` query found for elm
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## c parser healthcheck
        - OK: c parser found.
        - OK: `highlights.scm` found.
        - OK: `locals.scm` found.
        - OK: `textobjects.scm` found.
        - OK: `fold.scm` found.

      ## java parser healthcheck
        - OK: java parser found.
        - OK: `highlights.scm` found.
        - OK: `locals.scm` found.
        - WARNING: No `textobjects.scm` query found for java
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `fold.scm` query found for java
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## python parser healthcheck
        - OK: python parser found.
        - OK: `highlights.scm` found.
        - OK: `locals.scm` found.
        - OK: `textobjects.scm` found.
        - OK: `fold.scm` found.

      ## dart parser healthcheck
        - OK: dart parser found.
        - OK: `highlights.scm` found.
        - WARNING: No `locals.scm` query found for dart
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `textobjects.scm` query found for dart
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `fold.scm` query found for dart
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## lua parser healthcheck
        - OK: lua parser found.
        - OK: `highlights.scm` found.
        - OK: `locals.scm` found.
        - OK: `textobjects.scm` found.
        - OK: `fold.scm` found.

      ## ocaml parser healthcheck
        - OK: ocaml parser found.
        - OK: `highlights.scm` found.
        - OK: `locals.scm` found.
        - WARNING: No `textobjects.scm` query found for ocaml
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `fold.scm` query found for ocaml
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## go parser healthcheck
        - OK: go parser found.
        - OK: `highlights.scm` found.
        - OK: `locals.scm` found.
        - OK: `textobjects.scm` found.
        - WARNING: No `fold.scm` query found for go
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## nix parser healthcheck
        - OK: nix parser found.
        - WARNING: No `highlights.scm` query found for nix
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `locals.scm` query found for nix
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `textobjects.scm` query found for nix
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `fold.scm` query found for nix
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## yaml parser healthcheck
        - OK: yaml parser found.
        - WARNING: No `highlights.scm` query found for yaml
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `locals.scm` query found for yaml
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `textobjects.scm` query found for yaml
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `fold.scm` query found for yaml
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## json parser healthcheck
        - OK: json parser found.
        - OK: `highlights.scm` found.
        - WARNING: No `locals.scm` query found for json
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `textobjects.scm` query found for json
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `fold.scm` query found for json
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## jsdoc parser healthcheck
        - OK: jsdoc parser found.
        - WARNING: No `highlights.scm` query found for jsdoc
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `locals.scm` query found for jsdoc
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `textobjects.scm` query found for jsdoc
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `fold.scm` query found for jsdoc
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## markdown parser healthcheck
        - OK: markdown parser found.
        - WARNING: No `highlights.scm` query found for markdown
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `locals.scm` query found for markdown
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `textobjects.scm` query found for markdown
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `fold.scm` query found for markdown
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## julia parser healthcheck
        - OK: julia parser found.
        - WARNING: No `highlights.scm` query found for julia
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `locals.scm` query found for julia
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `textobjects.scm` query found for julia
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `fold.scm` query found for julia
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## html parser healthcheck
        - OK: html parser found.
        - OK: `highlights.scm` found.
        - OK: `locals.scm` found.
        - WARNING: No `textobjects.scm` query found for html
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `fold.scm` query found for html
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## typescript parser healthcheck
        - OK: typescript parser found.
        - OK: `highlights.scm` found.
        - OK: `locals.scm` found.
        - OK: `textobjects.scm` found.
        - OK: `fold.scm` found.

      ## fennel parser healthcheck
        - OK: fennel parser found.
        - OK: `highlights.scm` found.
        - OK: `locals.scm` found.
        - WARNING: No `textobjects.scm` query found for fennel
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `fold.scm` query found for fennel
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## swift parser healthcheck
        - OK: swift parser found.
        - WARNING: No `highlights.scm` query found for swift
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `locals.scm` query found for swift
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `textobjects.scm` query found for swift
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `fold.scm` query found for swift
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## query parser healthcheck
        - OK: query parser found.
        - OK: `highlights.scm` found.
        - OK: `locals.scm` found.
        - WARNING: No `textobjects.scm` query found for query
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `fold.scm` query found for query
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## cpp parser healthcheck
        - OK: cpp parser found.
        - OK: `highlights.scm` found.
        - OK: `locals.scm` found.
        - OK: `textobjects.scm` found.
        - OK: `fold.scm` found.

      ## ruby parser healthcheck
        - OK: ruby parser found.
        - OK: `highlights.scm` found.
        - OK: `locals.scm` found.
        - WARNING: No `textobjects.scm` query found for ruby
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `fold.scm` query found for ruby
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## vue parser healthcheck
        - OK: vue parser found.
        - WARNING: No `highlights.scm` query found for vue
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `locals.scm` query found for vue
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `textobjects.scm` query found for vue
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `fold.scm` query found for vue
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## scala parser healthcheck
        - OK: scala parser found.
        - WARNING: No `highlights.scm` query found for scala
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `locals.scm` query found for scala
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `textobjects.scm` query found for scala
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `fold.scm` query found for scala
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## tsx parser healthcheck
        - OK: tsx parser found.
        - OK: `highlights.scm` found.
        - OK: `locals.scm` found.
        - OK: `textobjects.scm` found.
        - OK: `fold.scm` found.

      ## rust parser healthcheck
        - OK: rust parser found.
        - OK: `highlights.scm` found.
        - OK: `locals.scm` found.
        - OK: `textobjects.scm` found.
        - WARNING: No `fold.scm` query found for rust
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## bash parser healthcheck
        - OK: bash parser found.
        - OK: `highlights.scm` found.
        - OK: `locals.scm` found.
        - WARNING: No `textobjects.scm` query found for bash
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `fold.scm` query found for bash
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## c_sharp parser healthcheck
        - OK: c_sharp parser found.
        - OK: `highlights.scm` found.
        - WARNING: No `locals.scm` query found for c_sharp
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - OK: `textobjects.scm` found.
        - WARNING: No `fold.scm` query found for c_sharp
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## rst parser healthcheck
        - OK: rst parser found.
        - OK: `highlights.scm` found.
        - OK: `locals.scm` found.
        - OK: `textobjects.scm` found.
        - WARNING: No `fold.scm` query found for rst
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## css parser healthcheck
        - OK: css parser found.
        - OK: `highlights.scm` found.
        - WARNING: No `locals.scm` query found for css
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `textobjects.scm` query found for css
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `fold.scm` query found for css
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## php parser healthcheck
        - OK: php parser found.
        - OK: `highlights.scm` found.
        - OK: `locals.scm` found.
        - WARNING: No `textobjects.scm` query found for php
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - OK: `fold.scm` found.

      ## javascript parser healthcheck
        - OK: javascript parser found.
        - OK: `highlights.scm` found.
        - OK: `locals.scm` found.
        - OK: `textobjects.scm` found.
        - OK: `fold.scm` found.

      ## haskell parser healthcheck
        - OK: haskell parser found.
        - WARNING: No `highlights.scm` query found for haskell
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `locals.scm` query found for haskell
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `textobjects.scm` query found for haskell
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `fold.scm` query found for haskell
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## toml parser healthcheck
        - OK: toml parser found.
        - OK: `highlights.scm` found.
        - OK: `locals.scm` found.
        - WARNING: No `textobjects.scm` query found for toml
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `fold.scm` query found for toml
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

      ## regex parser healthcheck
        - OK: regex parser found.
        - OK: `highlights.scm` found.
        - WARNING: No `locals.scm` query found for regex
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `textobjects.scm` query found for regex
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
        - WARNING: No `fold.scm` query found for regex
          - ADVICE:
            - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-c7ef80220
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200913-39181-1etb7vb/build/config -I/tmp/neovim-20200913-39181-1etb7vb/src -I/usr/local/include -I/tmp/neovim-20200913-39181-1etb7vb/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200913-39181-1etb7vb/build/src/nvim/auto -I/tmp/neovim-20200913-39181-1etb7vb/build/include
Compiled by ahmed@pandoras-box

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-c7ef802/share/nvim"

Run :checkhealth for more info
```

**Additional context**

It works fine when I comment the line manually, so not sure 100% if this is a bug in treesitter or an issue with tcomment_vim.

**Comment by stsewd** [comment]
Hi, this is same (related) as https://github.com/nvim-treesitter/nvim-treesitter/issues/235

**Comment by ahmedelgabri** [comment]
Thanks, @stsewd will close it in favour of #235 then.
