### ISSUE TITLE
[Ruby highlight] require should be highlighted as TSInclude not TSFunction

### ISSUE THREAD

**Issue by bluz71** [nvim-treesitter/nvim-treesitter#463]
Hello,

With [this Ruby file](https://github.com/bluz71/vim-nightfly-guicolors/blob/master/samples/ruby.rb) the `require` call at the top of the file is being highlighted as `TSFunction` yet it should be `TSInclude`. `require` is basically a Ruby code importation statement which is what the `TSInclude` highlight group exists for.

This is set in the `ruby/highlights.scm` file:

```
((identifier) @function
 (#eq? @function "require"))

"defined?" @function
```

Compare current Ruby Treesitter highlighting which is using `TSFunction` blue for the `require`:

<img width="551" alt="Screen Shot 2020-09-14 at 1 30 48 pm" src="https://user-images.githubusercontent.com/11382509/93040920-84ade800-f68e-11ea-8d88-b6fa2d743c7d.png">

Against Python Treesitter which is correctly highlighting imports in `TSInclude` dark red:

<img width="493" alt="Screen Shot 2020-09-14 at 1 31 53 pm" src="https://user-images.githubusercontent.com/11382509/93040972-aeffa580-f68e-11ea-9100-469d4991072e.png">

Note, Ruby also provides `require_relative` and `load` as less common code loading statements. You may also want to highlight those as `TSInclude` as well for consistency.

As best as I can tell, most Neovim Treesitter languages (Go, Rust, C, C++, Python) are now correctly using `TSInclude`, Ruby is the one that is out-of-step.

Best regards.

**Comment by theHamsta** [comment]
@TravonteD 
@bluz71 thanks again for this issue! Your color theme looks really nice!

**Comment by bluz71** [comment]
I appreciate the compliment.

I maintain two (Neo)vim color schemes: [moonfly](https://github.com/bluz71/vim-moonfly-colors) and [nightfly](https://github.com/bluz71/vim-nightfly-guicolors).

My aim is to have Neovim Treesitter look really nice since I genuinely believe it is the future of semantic editing and highlighting. I watched Max Brunsfeld's Treesitter talks a while ago and quickly became a believer in the technology.

Thanks to the team of coders doing the Neovim Treesitter work.

**Comment by bluz71** [comment]
I just tested current `master` branch which contains #477.

Unfortunately it does not work with [this Ruby file](https://github.com/bluz71/vim-nightfly-guicolors/blob/master/samples/ruby.rb).

The `require` is still being highlighted as `TSFunction`.

I believe the issue is that the new code of #477 is placed too high in `queries/ruby/highlights.scm`:

```
((identifier) @include
 (#vim-match? @include "^(require|require_relative|load)$"))
```

This new `@include` block should be moved down a couple blocks, this new placement here works (below the `@function` blocks):

```
; Function calls

"defined?" @function

(call
  [
   receiver: (constant) @constant
   method: [
            (identifier)
            (constant)
            ] @function
   ])

(method_call
  [
   receiver: (constant) @constant
   method: [
            (identifier)
            (constant)
            ] @function
   ])

((identifier) @include
 (#vim-match? @include "^(require|require_relative|load)$"))
```

It appears to be similar to the Ruby Types highlight issue #448 where again ordering matters.

Please don't close this issue until the ordering issue is fixed.

Cheers.

**Comment by vigoux** [comment]
Hi ! Now that you have the proper fix for your issue, maybe you can open a PR ? This will allow you to see this issue being fixed faster !

**Comment by bluz71** [comment]
@vigoux, 

Sure.

If @TravonteD does not fix it before me, I will do issue a PR tomorrow.

Cheers.

**Comment by bluz71** [comment]
Hello Treesitter team,

I have created PR #486 that reverts `@include` highlighting for `require` statements.

Turns out that is not a good idea.

In Ruby `require` is not a keyword, hence it can be overriden as a class method, and that actually happens in Ruby on Rails for strong params processing. For example this style of snippet below is extremely common in Rails:

```ruby
def album_params
    params.require(:album).permit(:title, :genre_id, :year, :track_list,
                                  :cover, :cover_cache)
end
```

The PR #477 the `require` next to `params` would get highlighted as `TSInclude` which is fundamentally wrong.

I now believe it is best to restore back to the previous state of highlighting `require` as `TSFunction` which is what it is fundamentally.

It is much better to highlight `import`, `#include` when they are keywords or pre-proc statements. In Ruby things are done a little different.

Story for going down this dead-end.

If/when #486 is merged, we should just close this as *will-not-do".

Best regards.

**Comment by bluz71** [comment]
#486 has been closed since @vigoux would prefer `require` to have two meanings:

- Either as a top-level import mechanism which would highlight as `TSInclude`

- Or as a class method which would highlight as `TSMethod` I assume.

Changes will likely be needed in `queries/ruby/highlights.scm`.

Someone with Treesitter knowledge will needed. It is out of my depth.

This is an example Ruby file would has two usages of require, one as a code importer and one as class method:

```ruby
require "pry"

class AlbumsController < ApplicationController
  def index
    @albums = Album.list(params)
    respond_to do |format|
      format.html
      format.json
    end
  end

  private

  def album_params
    params.require(:album).permit(:title, :genre_id, :year, :track_list,
                                  :cover, :cover_cache)
  end
end
```

Cheers.

**Comment by TravonteD** [comment]
We'll highlight the requires as includes globally as originally mentioned, but we will highlight them as functions when they are called on a receiver. here is an example.

```ruby
# as top-level method call (TSInclude)

require "foo"
#=> (method_call  method: (identifier)) 

# as namespaced method call (TSFunction)
Class.require
#=> (call receiver: (constant) method:(identifier))
```
This should give us the desired result.

**Comment by bluz71** [comment]
`Class.require` is not the second case we are concerned with, rather `params.require(:symbol).permit(:other_symbol)` is.

As best as I can tell:

- `require 'pry'` Ruby loading style results in the following Playground output:

```
method_call
  method: identifier
  arguments: argument_list
    string
```

- `params.require(:symbol).permit(:other_symbol)` results in the following Playground output:

```
    method_call
      method: call
        receiver: method_call
          method: call
            receiver: identifier
            method: identifier
          arguments: argument_list
            symbol
        method: identifier
```

I don't know how to translate those into `highlights.scm` syntax. It all looks like ancient scripture to me.

So I can't do a PR at the moment. Help `required`. Currently stalled.

**Comment by bluz71** [comment]
Noting that current `require` highlighting is being done as:

```
((identifier) @include
 (#vim-match? @include "^(require|require_relative|load)$"))
```

I assume that is pure string matching?

Would an alternative be to take into account what precedes `require`, if it is nothing or if pure whitespace then it is code loading, or if it is a non-blank/non-whitespace then it is a method call?

Hmmm, that would not work for this case:

```ruby
Class hello
  def require
     puts "My require"
  end
end
```

Damn.

I still am not against just reverting back to pure `TSFunction` highlighting for `require`. But I leave that to the Treesitter experts. I am out of my depth now.

**Comment by theHamsta** [comment]
This just matches top level expressions with parent `program`. With #453 you could select which parents you would allow or not allow for a `include` highlight.

```scheme
(program
 (method_call
  (identifier) @include)
 ((#vim-match? @include "^(require|require_relative|load)$")))
```

**Comment by bluz71** [comment]
@theHamsta,

Your block just above appears to work very well. 

PR #508 created containing that enhancement.

Best regards.
