### ISSUE TITLE
[HTML Highlight] Currently tagnames are highlighted with TSType / @type, maybe new a group such as TSTag would be better?

### ISSUE THREAD

**Issue by bluz71** [nvim-treesitter/nvim-treesitter#465]
Hello,

The current Neovim Treesitter highlighter use `TSType` for tagnames as defined in `queries/html/highlights.scm`:

```
(tag_name) @type
```

As a (Neo)vim theme author, Types are often in a strong color to emphasise importance. And types are usually sparsely seen in an editing session. However, HTML/XML tags are the predominant text in such files. Hence by choosing `TSType` for tags it produces unpleasant results with my themes, and I suspect others as well.

My belief, Types will be too strong a color for tag names. 

For example in my case:

<img width="547" alt="Screen Shot 2020-09-14 at 3 50 05 pm" src="https://user-images.githubusercontent.com/11382509/93048337-fa6f7f00-f6a1-11ea-8ab8-ecf11630d610.png">

I would prefer to use a blue color, but keep `TSType` as green for general purple languages like C, Go, Rust, Python etc.

Maybe `TSStructure` is a more appropriate highlight group from the existing choices?

Or better yet, maybe a new group such `TSTag` that could be used for HTML, XML and JSX? I strongly favour this, if possible.

Interestingly, in JSX the tag delimiters, `<` and `>` are highlighted as `TSOperator`. In the HTML highlighter they are `TSPunctBracket`. With my theme `TSOperator` looks better, but neither may be ideal.

Again, maybe a new highlight group `TSTagBracket` or `TSTagDelimiter`.

My formal request is for 2 new highlight groups:

- `TSTag`

- `TSTagDelimiter`

In the existing Treesitter those new groups could be used for HTML and JSX. In future maybe XML.

My 2cents.

**Comment by theHamsta** [comment]
@TravonteD

**Comment by theHamsta** [comment]
@kyazdani42 perhaps also relevant for JSX?

**Comment by steelsojka** [comment]
I agree. Type is to strong for html tags. I don't think we should add a capture specific to HTML though. We should have a capture that fits this already.

**Comment by theHamsta** [comment]
Why not? Markup is clearly different from a programming language and you can have html in Markdown, JSX (even has a built in textobject in vim). It could also be a more general concept like `TSElement` which could include stuff in other markup languages (Jinja start/end tags, Latex begin/end enviroments). But we should try to keep markup stuff and programming languages separated.

**Comment by bluz71** [comment]
The new highlight groups `TSTag` and `TSTagDelimiter` proposed in #478 will be greatly appreciated.

If/when merged both HTML and JSX Treesitter highlighters should use these new highlight groups which will bring Vim theme consistency when swapping from pure HTML files to mixed mode JavaScript files that sprinkle JSX.

Many thanks.

**Comment by steelsojka** [comment]
I'm fine having it more generalized. `TSTag` seemed very specific to HTML or XML, but I see it could be tied to other markups languages.

**Comment by stsewd** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/pull/478 was merged!

**Comment by bluz71** [comment]
Just tested `master` branch which contains the new `TSTag` and `TSTagDelimiter` highlight groups, fantastic.

For HTML files these new highlight groups are excellent; a very big improvement compared with before.

Many thanks Treesitter team.
