### ISSUE TITLE
vim.treesitter.query.get_node_text() is deprecated

### ISSUE THREAD

**Issue by sownteedev** [nvim-treesitter/nvim-treesitter#4678]
### Describe the bug

I have some problems with that message, and don't know what to do. Can you show me?

### To Reproduce

This is my treesitter config :
`local status, treesitter = pcall(require, "nvim-treesitter.configs")

if not status then
    return
end

require("nvim-treesitter.install").compilers = { "clang" }

treesitter.setup({
    sync_install = false,
    highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
        use_languagetree = true,
    },
    -- Playground
    playground = {
        enable = true,
        disable = {},
        updatetime = 25,
        persist_queries = false,
        keybindings = {
            toggle_query_editor = 'o',
            toggle_hl_groups = 'i',
            toggle_injected_languages = 't',
            toggle_anonymous_nodes = 'a',
            toggle_language_display = 'I',
            focus_language = 'f',
            unfocus_language = 'F',
            update = 'R',
            goto_node = '<cr>',
            show_help = '?',
        },
    },
    query_linter = {
        enable = true,
        use_virtual_text = true,
        lint_events = { "BufWrite", "CursorHold" },
    },
    -- Rainbow
    rainbow = {
        enable = true,
        -- query = 'rainbow-parens',
        -- strategy = require('ts-rainbow').strategy.global,
        -- max_file_lines = 3000,
    },
    -- Indent
    indent = { enable = true },
    -- Autotag
    autotag = { enable = true },
    -- Autopairs
    autopairs = { enable = true },
    -- Auto install
    ensure_installed = {
        "html",
        "css",
        "javascript",
        "typescript",
        "cpp",
        "c",
        "lua",
        "query",
        "json",
        "python",
        -- Support Noice
        "vim",
        "bash",
        "regex",
        "markdown",
        "markdown_inline",
    },
    auto_install = true,
})
`

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v19.8.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `clang` executable found. Selected from { "clang" }
  Version: clang version 15.0.7
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.2.11-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Thu, 13 Apr 2023 16:59:24 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ . ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
Disable your **other** treesitter plugins (rainbow, autopairs, ...) until the error goes away, then report the error to that plugin.

**Comment by sownteedev** [comment]
Not work guys ?

**Comment by iguntur** [comment]
We need better errors rather than just something generic. Since `treesitter` is used by another plugin, we need to know the source of the plugin using some deprecated API instead of turning it on/off the plugin.
