### ISSUE TITLE
Error with ts-autotag and ts-rainbow-2

### ISSUE THREAD

**Issue by sownteedev** [nvim-treesitter/nvim-treesitter#4679]
### Describe the bug

Hi everyone, today I did my own Neovim setup, I reinstalled my Neovim and when I used Packer Sync to install the plugins and apply it. There are Treesitter related plugins ts-rainbows2, nvim-ts-autotag and so on that have errors when installed with it. Below is the error image, do you have a solution for it?

Error : nvim-treesitter.config and nvim-treesitter.query not

I founded it but when i have everything it require, it doesn't work

https://github.com/nvim-treesitter/nvim-treesitter#troubleshooting

![image](https://user-images.githubusercontent.com/90148193/233018258-6629a1ed-5cb5-4935-a396-f174035ac0dd.png)

### To Reproduce

1. Delete Neovim
2. Reinstall
3. Use `sudo rm -rf ~/.config/nvim/plugin ~/.cache/nvim ~/.local/share/nvim` to remove all
4. Open Neovim
5. It will autoinstall Plugin but it get error like that

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v19.8.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `clang` executable found. Selected from { "clang" }
  Version: clang version 15.0.7
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.2.11-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Thu, 13 Apr 2023 16:59:24 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ . ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by sownteedev** [comment]
Did u see image ?
It is error guys ?

**Comment by lucario387** [comment]
I don't see how it's relevant if you fail your dependencies setup. If it cannot found nvim-treesitter, then make the plugin load earlier/on start
