### ISSUE TITLE
Add a query to match specific superclass/module

### ISSUE THREAD

**Issue by b-sep** [nvim-treesitter/nvim-treesitter#4696]
Im justing start to use neovim and i missed my old vscode theme, so im working on my own. Right now (at least is how i undestand), class, superclass and modules names are treated as the same way (@type). Is possible to add new queries to match each group individualy ? 

**Describe the solution you'd like**
Dont know if this is a solution but testing with playground it appears to match what i wish.

```ruby
(superclass) @superclass # for inheritance
(module
  name: (constant) @module_name # for module name
)

(module
  name: (scope_resolution) @module_nested # for modules that  has compact declaration way e.g Module Test::Test
)
```

As i say im justing starting to learn neovim (and lua), i never heard about treesitter until last week, so im trying to make my own colorscheme as a exercise and thought about that suggestion, if i say anything wrong and is already possible to match those things individualy please let me know.

**Comment by amaanq** [comment]
Not really a nvim-ts thing, but you could join the discord or matrix groups to get help w/ creating a theme (look at onedarkpro for inspiration) that leverages custom queries/captures
