### ISSUE TITLE
Solidity highlight is not working for function calls

### ISSUE THREAD

**Issue by zeroknots** [nvim-treesitter/nvim-treesitter#4708]
### Describe the highlighting problem

Solidity syntax highlighting is not detecting function calls

### Example snippet that causes the problem

```solidity
pragma solidity ^0.8.13;

contract Counter {
    uint256 public number;

    function setNumber(uint256 newNumber) public {
        number = newNumber;
    }

    function increment() public {
        number++;
    }
}


contract Caller {

  Counter counter;

  function foo() public {
    counter = new Counter();
    counter.setNumber(42);  // < -- no hightlight here. sad
    counter.increment(); // < -- no hightlight here. sad
  }
}
```

### Tree-sitter parsing result

comment [0, 0] - [0, 38]
pragma_directive [1, 0] - [1, 24]
  solidity_pragma_token [1, 7] - [1, 23]
    version_constraint: solidity_version_comparison_operator [1, 15] - [1, 17]
    version_constraint: solidity_version [1, 17] - [1, 23]
contract_declaration [3, 0] - [13, 1]
  name: identifier [3, 9] - [3, 16]
  body: contract_body [3, 17] - [13, 1]
    state_variable_declaration [4, 4] - [4, 26]
      type: type_name [4, 4] - [4, 11]
        primitive_type [4, 4] - [4, 11]
      visibility: visibility [4, 12] - [4, 18]
      name: identifier [4, 19] - [4, 25]
    function_definition [6, 4] - [8, 5]
      name: identifier [6, 13] - [6, 22]
      parameter [6, 23] - [6, 40]
        type: type_name [6, 23] - [6, 30]
          primitive_type [6, 23] - [6, 30]
        name: identifier [6, 31] - [6, 40]
      visibility [6, 42] - [6, 48]
      body: function_body [6, 49] - [8, 5]
        expression_statement [7, 8] - [7, 27]
          assignment_expression [7, 8] - [7, 26]
            left: identifier [7, 8] - [7, 14]
            right: identifier [7, 17] - [7, 26]
    function_definition [10, 4] - [12, 5]
      name: identifier [10, 13] - [10, 22]
      visibility [10, 25] - [10, 31]
      body: function_body [10, 32] - [12, 5]
        expression_statement [11, 8] - [11, 17]
          update_expression [11, 8] - [11, 16]
            argument: identifier [11, 8] - [11, 14]
contract_declaration [16, 0] - [25, 1]
  name: identifier [16, 9] - [16, 15]
  body: contract_body [16, 16] - [25, 1]
    state_variable_declaration [18, 2] - [18, 18]
      type: type_name [18, 2] - [18, 9]
        user_defined_type [18, 2] - [18, 9]
          identifier [18, 2] - [18, 9]
      name: identifier [18, 10] - [18, 17]
    function_definition [20, 2] - [24, 3]
      name: identifier [20, 11] - [20, 14]
      visibility [20, 17] - [20, 23]
      body: function_body [20, 24] - [24, 3]
        expression_statement [21, 4] - [21, 28]
          assignment_expression [21, 4] - [21, 27]
            left: identifier [21, 4] - [21, 11]
            right: call_expression [21, 14] - [21, 27]
              function: new_expression [21, 14] - [21, 25]
                name: type_name [21, 18] - [21, 25]
                  user_defined_type [21, 18] - [21, 25]
                    identifier [21, 18] - [21, 25]
        expression_statement [22, 4] - [22, 26]
          call_expression [22, 4] - [22, 25]
            function: member_expression [22, 4] - [22, 21]
              object: identifier [22, 4] - [22, 11]
              property: identifier [22, 12] - [22, 21]
            call_argument [22, 22] - [22, 24]
              number_literal [22, 22] - [22, 24]
        expression_statement [23, 4] - [23, 24]
          call_expression [23, 4] - [23, 23]
            function: member_expression [23, 4] - [23, 21]
              object: identifier [23, 4] - [23, 11]
              property: identifier [23, 12] - [23, 21]

### Example screenshot

<img width="431" alt="Screen Shot 2023-04-25 at 23 24 10" src="https://user-images.githubusercontent.com/102132718/234341378-96949398-886e-4c70-bdb4-3d633b61c6f7.png">

### Expected behavior

make function calls colorful

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v16.13.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "21.6.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - gitignore           ✓ . . . .
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ . ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - solidity            ✓ . . . .
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by ChmielewskiKamil** [comment]
I have the same issue, and would love to know how to resolve it.

**Comment by zeroknots** [comment]
can confirm that @amaanq fix works. What a legend!
