### ISSUE TITLE
In JSX and TSX files, while using ts:get_node(), I'm getting error there is no parser for javascriptreact

### ISSUE THREAD

**Issue by Herob527** [nvim-treesitter/nvim-treesitter#4710]
### Describe the bug

I'm working on snippet, that creates console.log using function in scope and I'm using treesitter to get parent and make query

For JS and TS it works fine, but for JSX and TSX I'm getting error `E5108: Error executing lua ...local/share/nvim/runtime/lua/vim/treesitter/language.lua:94: no parser for 'javascriptreact' language, see :help treesitter-parsers`

I managed to find out `local ts_node = ts.get_node()` is responsible for this crash

Snippet

```lua
local luasnip = require("luasnip")
local sn = luasnip.snippet
local t = luasnip.text_node
local s = luasnip.snippet_node
local d = luasnip.dynamic_node
local fmt = require("luasnip.extras.fmt").fmt
local ts = vim.treesitter
local ts_query = ts.query

--- @param node TSNode | nil
--- @param ts_elements table<string>
--- @returns TSNode | nil
local function seek_function_root(node, ts_elements)
    if node == nil then
        return nil
    end
    local node_type = node:type()

    if vim.tbl_contains(ts_elements, node_type) then
        return node
    end

    local parent = node:parent()

    return seek_function_root(parent, ts_elements)
end

--- @param node TSNode | nil
local function get_data(node)
    local filetype = vim.bo.filetype
    local query_lang = filetype == "javascriptreact" and "javascript" or filetype
    if node == nil then
        return nil
    end
    if node:type() == "program" then
        return "global"
    end
    local parsed_query = ts_query.parse(query_lang, [[(identifier) @name]])
    -- print("[get_data]")
    for _, parsed_node, _ in parsed_query:iter_captures(node, 0, node:start(), node:end_()) do
        return ts.get_node_text(parsed_node, 0)
    end
end

local console = sn(
    "con",
    fmt([[ console.log("[{function_name}]","{test}")]], {
        test = t(""),
        function_name = d(1, function()
            local ts_node = ts.get_node()
            local function_root = seek_function_root(ts_node, { "function_declaration", "variable_declarator" })
            local data = function_root ~= nil and get_data(function_root) or ""
            return s(nil, { t(data) })
        end),
    })
)

return console
```

### To Reproduce

1. Attach provided snippet to javascriptreact / typescriptreact in luasnip
2. In JSX file try to use con

my nvim config: https://github.com/Herob527/nvim-config

### Expected behavior

I expected that it won't crash on JSX / TSX files

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v19.5.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.19.0-40-generic",
  sysname = "Linux",
  version = "#41~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 31 16:00:14 UTC 2"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - comment             ✓ . . . .
  - css                 ✓ . ✓ ✓ ✓
  - diff                ✓ . . . .
  - dockerfile          ✓ . . . ✓
  - git_rebase          ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . .
  - graphql             ✓ . . ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - kotlin              ✓ ✓ ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ . ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - ruby                ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - vue                 ✓ . ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by lucario387** [comment]
the parser for javascriptreact is jsx,

**Comment by TheLeoP** [comment]
Since the name of the parser is `tsx` instead of `typescriptreact`, it is causing problems while using the command `:InspectTree`, since it uses the filetype to try and find the parser.

I saw that Neovim core uses a table to solve a similar problem for the `help` and `vimdoc` parsers. Would it make sense to do the same for these filetypes on core?

**Comment by Herob527** [comment]
> the parser for javascriptreact is jsx, and what is the return value of `vim.treesitter.get_parser()` while in jsx files

{                                                                                                                                                                                                                   
  _callbacks = {                                                                                                                                                                                                    
    bytes = { <function 1> },                                                                                                                                                                                       
    changedtree = { <function 2> },                                                                                                                                                                                 
    child_added = {},                                                                                                                                                                                               
    child_removed = {},                                                                                                                                                                                             
    detach = { <function 3> }                                                                                                                                                                                       
  },                                                                                                                                                                                                                
  _children = {                                                                                                                                                                                                     
    comment = {                                                                                                                                                                                                     
      _callbacks = {                                                                                                                                                                                                
        bytes = {},                                                                                                                                                                                                 
        changedtree = {},                                                                                                                                                                                           
        child_added = {},                                                                                                                                                                                           
        child_removed = {},                                                                                                                                                                                         
        detach = {}                                                                                                                                                                                                 
      },                                                                                                                                                                                                            
      _children = {},                                                                                                                                                                                               
      _has_regions = true,                                                                                                                                                                                          
      _lang = "comment",                                                                                                                                                                                            
      _opts = <1>{},                                                                                                                                                                                                
      _parser = <userdata 1>,                                                                                                                                                                                       
      _regions = { { { 15, 2, 437, 15, 42, 477 } }, { { 81, 8, 2492, 81, 35, 2519 } } },                                                                                                                            
      _source = 1,                                                                                                                                                                                                  
      _trees = { <userdata 2>, <userdata 3> },                                                                                                                                                                      
      _valid = true,                                                                                                                                                                                                
      <metatable> = <2>{                                                                                                                                                                                            
        __index = <table 2>,                                                                                                                                                                                        
        _do_callback = <function 4>,                                                                                                                                                                                
        _edit = <function 5>,                                                                                                                                                                                       
        _get_injection = <function 6>,                                                                                                                                                                              
        _get_injection_deprecated = <function 7>,                                                                                                                                                                   
        _get_injections = <function 8>,                                                                                                                                                                             
        _iter_regions = <function 9>,                                                                                                                                                                               
        _log = <function 10>,                                                                                                                                                                                       
        _on_bytes = <function 11>,                                                                                                                                                                                  
        _on_detach = <function 12>,                                                                                                                                                                                 
        _on_reload = <function 13>,                                                                                                                                                                                 
        add_child = <function 14>,                                                                                                                                                                                  
        children = <function 15>,                                                                                                                                                                                   
        contains = <function 16>,                                                                                                                                                                                   
        destroy = <function 17>,                                                                                                                                                                                    
        for_each_child = <function 18>,                                                                                                                                                                             
        for_each_tree = <function 19>,                                                                                                                                                                              
        included_regions = <function 20>,                                                                                                                                                                           
        invalidate = <function 21>,                                                                                                                                                                                 
        is_valid = <function 22>,                                                                                                                                                                                   
        lang = <function 23>,                                                                                                                                                                                       
        language_for_range = <function 24>,                                                                                                                                                                         
        named_node_for_range = <function 25>,                                                                                                                                                                       
        new = <function 26>,                                                                                                                                                                                        
        parse = <function 27>,                                                                                                                                                                                      
        register_cbs = <function 28>,
remove_child = <function 29>,                                                                                                                                                                               
        set_included_regions = <function 30>,                                                                                                                                                                       
        source = <function 31>,                                                                                                                                                                                     
        tree_for_range = <function 32>,                                                                                                                                                                             
        trees = <function 33>                                                                                                                                                                                       
      }                                                                                                                                                                                                             
    }                                                                                                                                                                                                               
  },                                                                                                                                                                                                                
  _injection_query = {                                                                                                                                                                                              
    captures = <3>{ "_jsdoc_comment", "jsdoc", "comment", "language", "content", "_name", "html", "graphql", "glimmer", "css", "regex", "_prop", "_attr" },                                                         
    info = {                                                                                                                                                                                                        
      captures = <table 3>,                                                                                                                                                                                         
      patterns = { { { "lua-match?", 1, "^/[*][*][^*].*[*]/$" } },                                                                                                                                                  
        [3] = { { "offset!", 5, "0", "1", "0", "-1" }, { "not-eq?", 5, "svg" } },                                                                                                                                   
        [4] = { { "eq?", 6, "svg" }, { "offset!", 7, "0", "1", "0", "-1" } },                                                                                                                                       
        [5] = { { "eq?", 6, "gql" }, { "offset!", 8, "0", "1", "0", "-1" } },                                                                                                                                       
        [6] = { { "eq?", 6, "hbs" }, { "offset!", 9, "0", "1", "0", "-1" } },                                                                                                                                       
        [8] = { { "eq?", 6, "styled" }, { "offset!", 10, "0", "1", "0", "-1" } },                                                                                                                                   
        [9] = { { "eq?", 6, "styled" }, { "offset!", 10, "0", "1", "0", "-1" } },                                                                                                                                   
        [10] = { { "eq?", 6, "styled" }, { "offset!", 10, "0", "1", "0", "-1" } },                                                                                                                                  
        [11] = { { "eq?", 6, "styled" }, { "offset!", 10, "0", "1", "0", "-1" } },                                                                                                                                  
        [13] = { { "lua-match?", 8, "^`#graphql" }, { "offset!", 8, "0", "1", "0", "-1" } },                                                                                                                        
        [14] = { { "any-of?", 12, "innerHTML", "outerHTML",                                                                                                                                                         
            string_set = {                                                                                                                                                                                          
              innerHTML = true,                                                                                                                                                                                     
              outerHTML = true                                                                                                                                                                                      
            }                                                                                                                                                                                                       
          }, { "offset!", 7, "0", "1", "0", "-1" } },                                                                                                                                                               
        [15] = { { "any-of?", 12, "innerHTML", "outerHTML" }, { "offset!", 7, "0", "1", "0", "-1" } },                                                                                                              
        [16] = { { "eq?", 6, "style" }, { "eq?", 13, "jsx" }, { "offset!", 10, "0", "1", "0", "-1" } }                                                                                                              
      }                                                                                                                                                                                                             
    },                                                                                                                                                                                                              
    query = <userdata 4>,                                                                                                                                                                                           
    <metatable> = <4>{                                                                                                                                                                                              
      __index = <table 4>,                                                                                                                                                                                          
      apply_directives = <function 34>,                                                                                                                                                                             
      iter_captures = <function 35>,                                                                                                                                                                                
      iter_matches = <function 36>,                                                                                                                                                                                 
      match_preds = <function 37>                                                                                                                                                                                   
    }                                                                                                                                                                                                               
  },                                                                                                                                                                                                                
  _lang = "javascript",                                                                                                                                                                                             
  _opts = <table 1>,                                                                                                                                                                                                
  _parser = <userdata 5>,                                                                                                                                                                                           
  _source = 1,                                                                                                                                                                                                      
  _trees = { <userdata 6> },                                                                                                                                                                                        
  _valid = true,                                                                                                                                                                                                    
  <metatable> = <table 2>                                                                                                                                                                                           
}

**Comment by lucario387** [comment]
Agreed on that, was a blunder from me. 

Then i don't really know why it bugs out then. Probably load order issues?

**Comment by Herob527** [comment]
> Agreed on that, was a blunder from me.
> 
> Then i don't really know why it bugs out then. Probably load order issues?

Is there anything I can do with it in my config or there should be work done in treesitter?

**Comment by lucario387** [comment]
`:h vim.treesitter.get_lang` seems to be okay as a workaround

**Comment by Herob527** [comment]
> `:h vim.treesitter.get_lang` seems to be okay as a workaround

But there is not get_land in vim.treesitter or is it a suggestion?

**Comment by Herob527** [comment]
I realised it is in treesitter, but still issue is even on nvim v0.9.2-dev-14+g06d137681

**Comment by Herob527** [comment]
Managed to fix it

Had to use LanguageTree named_node_for_range

core code of snippet looks like that now

```lua
local console = sn(
	"con",
	fmt([[ console.log("[{function_name}]",{var})]], {
		function_name = d(1, function(args)
			local bufnr = 0
			local parser = vim.treesitter.get_parser(bufnr, "tsx")
			local checked_value = args[1][1]
			local lineNum = vim.api.nvim_win_get_cursor(0)
			local row = lineNum[1]
			local col = lineNum[2]
			local ts_node = parser:named_node_for_range({ row, col, row, col })
			local function_root = seek_function_root(
				ts_node,
				{ "function_declaration", "variable_declarator", "method_definition", "field_definition" }
			)
			local data = function_root ~= nil and get_data(function_root) or ""
			local output = checked_value ~= "" and t(data .. " - " .. checked_value) or t(data)
			return s(nil, { output })
		end, { 2 }),
		var = i(2),
	})
)

return console
```

It'd be great to add get_node() from vim.treesitter, but for specific parser

**Comment by Herob527** [comment]
Turns out, it doesn't work properly event for js file, so it's not a solution for it

**Comment by Herob527** [comment]
Managed to fix it thanks to JoosepAlviste, who is using ts-based snippets too:
https://github.com/JoosepAlviste/dotfiles/blob/master/config/nvim/lua/j/plugins/snippets/typescriptreact.lua
