### ISSUE TITLE
Nvim Treesiter support for puppet language?

### ISSUE THREAD

**Issue by techsk8** [nvim-treesitter/nvim-treesitter#4712]
**Is your feature request related to a problem? Please describe.**
Do you plan to add puppet as a supported language in the future?
I was trying to find puppet syntax-highlighting support from treesitter but there's none.

**Describe alternatives you've considered**
All I could find so far on this subject is this snippet that would provide formatting +- using puppet-lint.

```lua
local null_ls = require("null-ls")

null_ls.setup({
    sources = {
        null_ls.builtins.diagnostics.puppet_lint,
        null_ls.builtins.formatting.puppet_lint,
    },
})
```

But I don't really know how to make it work on `neovim` or better `lunarvim`?
Has anybody done it?

**Comment by lucario387** [comment]
Is there an entry in https://github.com/nvim-treesitter/nvim-treesitter/issues/2282 to request for puppet lang support? If not, you should add it there for easier tracking.

I don't think there exists a treesitter parser for it just yet, so probably this will have to wait

**Comment by techsk8** [comment]
Okay, got it.
