### ISSUE TITLE
[Go] highlight magic comments

### ISSUE THREAD

**Issue by ArtAndreev** [nvim-treesitter/nvim-treesitter#4726]
**Is your feature request related to a problem? Please describe.**
Go has some magic comments, that are processed by go toolchain: `//go:generate`, `//go:build` and more. They are not highlighted.

**Describe the solution you'd like**
I suggest to inject highlightings in these comments.

For example, the line with `//go:generate` may have two highlightings injected: highlighting for directive `go:generate` and injected shell highlighting for the rest of the line (or highlighting for the first shell argument only).

`//go:build`: see https://pkg.go.dev/cmd/go#hdr-Build_constraints, it may have the same highlight that if condition has.

Also `//go:embed` shouldn't be forgotten. It may have path highligthing or highlight globs.

**Describe alternatives you've considered**
I opened an issue in [tree-sitter-go](https://github.com/tree-sitter/tree-sitter-go) parser: https://github.com/tree-sitter/tree-sitter-go/issues/111. Sorry, if this cannot be implemented in this repo, I understand TS bad.

**Comment by amaanq** [comment]
This is really more an lsps job, it's not impossible to capture comments starting with "go:" as preproc but this could also capture false positives

**Comment by ArtAndreev** [comment]
OK, thanks for the answer!

**Comment by amaanq** [comment]
Injecting into comments is also a bit expensive, but, are these only at the top of the file (before anything even package foo)? I haven't touched go in a while so I forget now

**Comment by ArtAndreev** [comment]
`//go:build` is at the top of file, but other could be anywhere.

**Comment by amaanq** [comment]
you can extend it yourself in a query file

```scm
((comment) @preproc
  (#lua-match? @preproc "go:"))
  ```

**Comment by ArtAndreev** [comment]
Put
```
; extends

((comment) @preproc (#lua-match? @preproc "^//go:"))
```
in `queries/go/highlights.scm` file, disabled LSP semantic tokens and it works, thanks a lot!

I guess, there is no way to inject two highlights for two parts of comment without parser modification.

**Comment by amaanq** [comment]
it wouldn't be a good idea to modify the parser in that way imo, but glad that works for you

**Comment by ArtAndreev** [comment]
OK, thanks a lot again!
