### ISSUE TITLE
comment: "@XXX" text is never highlighted differently because of priority 

### ISSUE THREAD

**Issue by MunifTanjim** [nvim-treesitter/nvim-treesitter#4727]
### Describe the highlighting problem

https://github.com/nvim-treesitter/nvim-treesitter/blob/2ce3c9080cfe4a39c7907e672edafd2a95244a7c/queries/comment/highlights.scm#L44-L46

This `@constant` capture has priority `95`. But since it's inside comment and `@comment` capture has default priority `100`, highlight for `@constant` capture is never applied.

### Example snippet that causes the problem

```tsx
// @ts-ignore
```

### Tree-sitter parsing result

```
 comment [63, 4] - [63, 17] tsx @comment / @spell / @spell /
   "text" [63, 4] - [63, 5] comment @comment / @spell / @spell /
   "text" [63, 5] - [63, 6] comment @comment / @spell / @spell /
   "text" [63, 7] - [63, 10] comment @comment / @spell / @spell / @constant / @nospell /
   "text" [63, 10] - [63, 11] comment @comment / @spell / @spell /
   "text" [63, 11] - [63, 17] comment @comment / @spell / @spell /
```

### Example screenshot

![image](https://user-images.githubusercontent.com/8050659/235153458-74f9929c-7faa-483a-bb93-2ee4388b3289.png)

![image](https://user-images.githubusercontent.com/8050659/235153537-df00f687-c3d6-4cd3-9d86-eaebe45a5594.png)

![image](https://user-images.githubusercontent.com/8050659/235153645-31c0a9ba-1a21-4b4b-9b37-98ea67ed8853.png)

### Expected behavior

`@constant` capture to have at least priority `100`

### Output of `:checkhealth nvim-treesitter`

```markdown
N/A
```

### Output of `nvim --version`

```text
N/A
```

### Additional context

- https://github.com/nvim-treesitter/nvim-treesitter/pull/4534
- https://github.com/nvim-treesitter/nvim-treesitter/commit/25b656a4b771ee7d440e506280b9ae546d6f7233#commitcomment-107405656

**Comment by clason** [comment]
This is deliberate: https://github.com/nvim-treesitter/nvim-treesitter/pull/4534

Not sure what the best option here is (except dropping the comment parser, which offers relatively little for the number of problems it generates...)

**Comment by MunifTanjim** [comment]
Yeah I saw that PR. But not sure what's the point of keeping that query if that highlight is never gonna be applied. Maybe just remove that highlight query?

**Comment by clason** [comment]
That's certainly an option. @ObserverOfTime ?

**Comment by ObserverOfTime** [comment]
I don't mind removing the query altogether.

**Comment by clason** [comment]
Then PR welcome :)
