### ISSUE TITLE
Add `punctuation.separator.key-value` capture

### ISSUE THREAD

**Issue by datsfilipe** [nvim-treesitter/nvim-treesitter#4737]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
Add `punctuation.separator.key-value` capture.

**Describe alternatives you've considered**
I didn't came with many solutions.

**Additional context**
In VS Code theme creation we can use `punctuation.separator.key-value` to style the character between `key` and `value`, but in Neovim it seems that the capture name is `punctuation.delimiter`, as the command `TSCaptureUnderCursor` shows:

![image](https://user-images.githubusercontent.com/76636791/235364972-4bb02a90-dfa2-497c-a6ad-8911751fcf2b.png)

`punctuation.delimiter` will apply changes to all delimiters, instead of just the desired character.

**Comment by lucario387** [comment]
Thank you for the request, but this can be done from user-side configuration, through `after/queries/{language}/highlights.scm`, or `queries/{language}/highlights.scm`. There isn't a large enough reason for this capture to exist here.

Use something like
```scheme
; extends

; something that narrows down to ":" inside key-value types
...
":" @punctuation.separator.key-value
```

After that you can theme the way you like
