### ISSUE TITLE
Semantic highlighting overrides comment queries

### ISSUE THREAD

**Issue by Shatur** [nvim-treesitter/nvim-treesitter#4744]
### Describe the bug

Semantic highlighting overrides [comment queries](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/comment/highlights.scm) which results in inconsistent highlighting after semantic highlighting catching up:
![изображение](https://user-images.githubusercontent.com/22453358/235493090-5c4b44a4-8d95-4250-8945-e3ff4efbd345.png)
![изображение](https://user-images.githubusercontent.com/22453358/235493068-c9ed65e6-2c9f-464c-8b86-5594a50c4f9b.png)

### To Reproduce

1. Open any file with LSP that supports semantic highlighting.
2. Write comment with `TODO`
3. Wait for semantic highlighting to catch up

### Expected behavior

It would be great to have the highest priority for comment queries to avoid highlighting "downgrade" after semantic highlighting application.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v19.9.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 12.2.1 20230201
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.1.26-1-lts",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Wed, 26 Apr 2023 19:15:42 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cmake               ✓ . ✓ . .
  - comment             ✓ . . . .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - dockerfile          ✓ . . . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ . ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - rust                ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - wgsl_bevy           ✓ . ✓ ✓ .
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by clason** [comment]
This is intended. Tune or disable the corresponding LSP semantic tokens if you want them to have lower priority.

**Comment by Shatur** [comment]
> This is intended. Tune or disable the corresponding LSP semantic tokens if you want them to have lower priority.

How can I do so?

**Comment by Shatur** [comment]
Maybe we could have a higher priority for comments for better experience out of the box?

**Comment by clason** [comment]
`:h lsp-semantic-highlight`

> Maybe we could have a higher priority for comments for better experience out of the box?

Sorry, no. There is a clear documented priority "LSP tokens >> treesitter", and deviations will be confusing.

You are welcome to customize queries in your config (just copy them and add the priority you want), of course.

**Comment by Shatur** [comment]
Got it, thanks!
