### ISSUE TITLE
Wrong folding

### ISSUE THREAD

**Issue by login6** [nvim-treesitter/nvim-treesitter#4748]
### Describe the bug

When i press "O" under the functions in these examples - it creates wrong folding, And because of it i cannot use folding at all. Why is this happening? Examples with cpp and js.

Folding options:
set foldclose=all
set foldopen=all
set foldmethod=expr
set foldexpr=nvim_treesitter#foldexpr()
set foldlevel=0
set foldnestmax=20

https://user-images.githubusercontent.com/96973293/235833579-764832e1-79d9-46ab-ae57-b65b1830a83b.mp4

### To Reproduce

Just use these options of folding with treesitter:
set foldclose=all
set foldopen=all
set foldmethod=expr
set foldexpr=nvim_treesitter#foldexpr()
set foldlevel=0
set foldnestmax=20

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v18.16.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Debian 10.2.1-6) 10.2.1 20210110
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.10.0-22-amd64",
  sysname = "Linux",
  version = "#1 SMP Debian 5.10.178-3 (2023-04-22)"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - cmake               ✓ . ✓ . .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

**Comment by lewis6991** [comment]
Treesitter folding is now managed in Neovim core.

Please use `vim.treesitter.foldexpr()`.

**Comment by login6** [comment]
> vim.treesitter.foldexpr()

Thanks for the answer. Folding works fine(probably) with vim.treesitter.foldexpr(). But doesn't work when highlight is disabled of treesitter. But treesitter nvim_treesitter#foldexpr() works without highlight. It's only me, or it is how it works?

**Comment by login6** [comment]
> > vim.treesitter.foldexpr()
> 
> Thanks for the answer. Folding works fine(probably) with vim.treesitter.foldexpr(). But doesn't work when highlight is disabled of treesitter. But treesitter nvim_treesitter#foldexpr() works without highlight. It's only me, or it is how it works?

  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },

**Comment by login6** [comment]
> Treesitter folding is now managed in Neovim core.
> 
> Please use `vim.treesitter.foldexpr()`.

It only works with highlight of treesitter enabled?

**Comment by lewis6991** [comment]
https://github.com/neovim/neovim/pull/23672 should fix that.

**Comment by rosingrind** [comment]
> Please use vim.treesitter.foldexpr()

Update `README.md` please:

https://github.com/nvim-treesitter/nvim-treesitter/blob/fa414da96f4a2e60c2ac8082f0c1802b8f3c8f6c/README.md?plain=1#L459
