### ISSUE TITLE
How to set folding option when attaching parser to buffer

### ISSUE THREAD

**Issue by weilbith** [nvim-treesitter/nvim-treesitter#475]
Hey guys,
thanks for your hard work on this plugin! :pray:  I have been waiting for this and I'm super happy to finally start using it now.

But unfortunately I fail to set the provided fold function if a parser attaches to a buffer. So I don't want to set it globally, because as I understood it this would then not work for buffers with languages I have no parser for. So there I would like to use markers for example. I thought I could use a custom module to do this. Unfortunately this seem to do nothing. What is wrong?

```
require'nvim-treesitter'.define_modules {
  set_folding = {
    attach = function(bufnr, lang)
      print("Set folding using treesitterl")
      vim.o.foldmethod="expr"
      vim.o.foldexpr="nvim_treesitter#foldexpr()"
    end,
  }
}
```

**Comment by theHamsta** [comment]
Hello, we now have a folding function that can be defined globally (but it's still lacking a fallback when tree-sitter is not available). Folding is window option (so with this shortcut notation in `vim.wo`?) so you cannot really bind it to buffer it will always bind to a window (we tried to make it a module multiple times).

However, folding isn't working right now on my machine also. Will ask/investigate whether there's a problem. 

My suggestion would be that users can set an alternative folding method when tree-sitter is not available but set tree-sitter folding globally.

**Comment by theHamsta** [comment]
Can you try it with https://github.com/nvim-treesitter/nvim-treesitter/pull/476

**Comment by vigoux** [comment]
This has been merged and should be all good in master now, can you try it ?

**Comment by weilbith** [comment]
Setting it by hand works. But the module with the attach function is doing nothing. I can't even see the print message. But I also don't get an error by the plugin that the module definition is wrong or the function has an error. :thinking:

**Comment by vigoux** [comment]
Oh I see. `fold`is not a module but a function we provide to set it by hand.
To enable it for some filetypes you can do
```vim
autocmd Filetype rust,java setlocal foldmethod=expr foldexpr=...
```

**Comment by weilbith** [comment]
Hmm. I would like to get rid of duplicated code where I have to copy-paste this for every filetype I'll introduce a parser for. In fact I want something logically simple: if there gets a parser attached, then change the folding options.

So I need to checkout the code how this function works in detail. Anyways I don't understand why my `set_folding` module is not working. I assume it is not working since the `attach` hooks does not get executed. So the intermediate goal would be to have a printed message when a parser gets attached to a buffer. Could you help me there? :upside_down_face:

**Comment by theHamsta** [comment]
> autocmd Filetype rust,java setlocal foldmethod=expr foldexpr=...

problem with this solution is that the window option will stay even when you change buffer that's not rust,java. There could be two ways how to solve it 

- hook into the event of buffer change
- make our #foldexpr configurable to do be active on certain filetypes and only when parser is attached. Make fallback configurable

Second option would be much cleaner to implement.

**Comment by weilbith** [comment]
Hmm the typical strategy is to use `let b:undo_ftplugin = "setlocal foldmethod< foldexpr<`.

**Comment by stsewd** [comment]
In your module example I think you are missing `active=true`

**Comment by weilbith** [comment]
> In your module example I think you are missing `active=true`

I guess you mean `enable`? :thinking: 
Anyways I tried with both versions (and both don't work). Also I think it is awkward to require the `enable` property for modules the user manually added.

So my current minimal example is:

```lua
require'nvim-treesitter'.define_modules {
  set_folding = {
    enable = true,
    attach = function(bufnr, lang)
      print("foo bar")
    end,
  }
}
```

**Comment by stsewd** [comment]
Define module is used for other plugins to define modules, that's why it defaults to false. Not sure if calling print will do something, I think you need to call vim.api.nvim_out_write('foo\n')

**Comment by stsewd** [comment]
Nope, looks like print in lua will put the output in messages

**Comment by Happy-Dude** [comment]
Just wanted to chime in here since I wanted to do something similar; I added the following snipped to my treesitter config:

```lua
ft_str = ""
for _, ft in pairs(parsers.available_parsers()) do
    if (ft == "c_sharp") then
        ft_str = ft_str..'cs'..','
    else
        ft_str = ft_str..ft..','
    end
end
autocmd_fold_str = 'autocmd Filetype '..ft_str..' setlocal foldmethod=expr foldexpr=nvim_treesitter#foldexpr()'
api.nvim_command(autocmd_fold_str)
```

This allowed me to keep `foldmethod=marker` in non-treesitter language files while enabling treesitter foldexpr for supported filetypes.

**Comment by theHamsta** [comment]
```lua
local configs = parsers.get_parser_configs()
local ft_str = table.concat(vim.tbl_map(function(ft) return configs[ft].filetype or ft end, parsers.available_parsers()), ',')
vim.cmd[[autocmd Filetype '..ft_str..' setlocal foldmethod=expr foldexpr=nvim_treesitter#foldexpr()']]
```
@Happy-Dude you forgot all `local` in you code. I'm just warning since globals in lua can lead to very suprising side effects across different scripts.

**Comment by Happy-Dude** [comment]
Thanks for letting me know @theHamsta ; first time playing with Lua (and nvim-lua) 😅

**Comment by weilbith** [comment]
What do you guys think about just adding another section to the configuration? So similar to what we have already for highlighting and indentation.

Extended version:

```lua
require'nvim-treesitter.config'.setup {
  highlight = {
    enable = true,
  },
  indent = {
    enable = true,
  },
  fold = {
    enable = true,
}
```

**Comment by stsewd** [comment]
@weilbith folding is a window option, so we can't have that per filetype/buffer. If you mean having that as a global option, I think it should be fine.

**Comment by weilbith** [comment]
@stsewd that is a good point that I missed. Sometimes don't understand why some things are linked to windows instead of buffers. I suspect there were good arguments for these decisions. At least I hope so.

So although this might be cumbersome it should provide a nice user experience. We could do this manually. On `BufWinEnter` when a parser attached to the buffer, we change the fold window option for the window (if configured to do so). On `BufWinLeave` we "unnset" it back to the value as it was before (ofc we would need to cache that).
What do you think? :upside_down_face:

**Comment by weilbith** [comment]
@stsewd that is a good point that I missed. Sometimes don't understand why some things are linked to windows instead of buffers. I suspect there were good arguments for these decisions. At least I hope so.

So although this might be cumbersome it should provide a nice user experience. We could do this manually. On `BufWinEnter` when a parser attached to the buffer, we change the fold window option for the window (if configured to do so). On `BufWinLeave` we "unnset" it back to the value as it was before (ofc we would need to cache that).
What do you think? :upside_down_face:

**Comment by vigoux** [comment]
That sounds like a good solution.

**Comment by kyazdani42** [comment]
It doesn't make any sense to attach folds to the window. When you swap a buffer from a window with folds to an empty window, the folds will still be here x)

**Comment by weilbith** [comment]
Just recognized that this issue is still open. So I just share my current solution and close it. If someone comes up with a better solution or agrees with the approach we could re-open it.

---

```lua
local define_modules = require('nvim-treesitter').define_modules
local query = require('nvim-treesitter.query')

local foldmethod_backups = {}
local foldexpr_backups = {}

define_modules({
  folding = {
    enable = true,
    attach = function(bufnr)
      -- Fold settings are actually window based...
      foldmethod_backups[bufnr] = vim.wo.foldmethod
      foldexpr_backups[bufnr] = vim.wo.foldexpr
      vim.wo.foldmethod = 'expr'
      vim.wo.foldexpr = 'nvim_treesitter#foldexpr()'
    end,
    detach = function(bufnr)
      vim.wo.foldmethod = foldmethod_backups[bufnr]
      vim.wo.foldexpr = foldexpr_backups[bufnr]
      foldmethod_backups[bufnr] = nil
      foldexpr_backups[bufnr] = nil
    end,
    is_supported = query.has_folds
  }
})
```
