### ISSUE TITLE
Treesitter highlights override cursorline background

### ISSUE THREAD

**Issue by nathunsmitty** [nvim-treesitter/nvim-treesitter#485]
**Describe the bug**

When I have `set cursorline` enabled, treesitter text highlighting overrides the cursorline.

With treesitter enabled:
![Screen Shot 2020-09-17 at 12 22 27 PM](https://user-images.githubusercontent.com/5677971/93518955-693b1b00-f8e2-11ea-951c-3bc8118047a5.png)

Default lua highlighting (treesitter disabled):
![Screen Shot 2020-09-17 at 12 22 44 PM](https://user-images.githubusercontent.com/5677971/93518989-77893700-f8e2-11ea-88f2-96c50500e925.png)

**To Reproduce**
1. Enable `set cursorline`.
2. Enable treesitter highlighting.
3. Move cursor to a line with highlighted text on it.
4. See error.

**Expected behavior**
Note the lack of the cursorline background around `assert_equal`, `__`, and `t` in the first image. Expected behavior would be for a consistent cursorline background as shown in the second image.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## c parser healthcheck
  - OK: c parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.
  - OK: `folds.scm` found.

## lua parser healthcheck
  - OK: lua parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.
  - OK: `folds.scm` found.

## go parser healthcheck
  - OK: go parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.
  - WARNING: No `folds.scm` query found for go
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## html parser healthcheck
  - OK: html parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for html
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `folds.scm` query found for html
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## typescript parser healthcheck
  - OK: typescript parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.
  - OK: `folds.scm` found.

## query parser healthcheck
  - OK: query parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for query
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `folds.scm` query found for query
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## cpp parser healthcheck
  - OK: cpp parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.
  - OK: `folds.scm` found.

## tsx parser healthcheck
  - OK: tsx parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.
  - OK: `folds.scm` found.

## css parser healthcheck
  - OK: css parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for css
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `textobjects.scm` query found for css
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `folds.scm` query found for css
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-d4b4335fe
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200917-37935-p2otvp/build/config -I/tmp/neovim-20200917-37935-p2otvp/src -I/usr/local/include -I/tmp/neovim-20200917-37935-p2otvp/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200917-37935-p2otvp/build/src/nvim/auto -I/tmp/neovim-20200917-37935-p2otvp/build/include
Compiled by nathan@nathans-mac.localdomain

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-d4b4335/share/nvim"

Run :checkhealth for more info
```

**Additional context**

My color scheme: https://github.com/nathunsmitty/night-owl.vim

**Comment by vigoux** [comment]
Hi, that seems related to `luahl` more than `nvim-treesitter`. @bfredl what do you think of this ?
The `t` not being highlighted is because we use `Normal` for some identifiers.

**Comment by bfredl** [comment]
we should just reimplement 'cursorline' as a blend effect for 0.5.

**Comment by nathunsmitty** [comment]
That makes sense. Should I close this issue out and reopen against the main neovim repo, or do you want me to leave this open?

**Comment by vigoux** [comment]
I think that moving this issue upstream is godd as it is not specifically related to treesitter.

**Comment by kyazdani42** [comment]
Normal shouldnt be used, i had this issue long time ago in vim too with other plugins. Normal applies a background color and should not be used for highlighting code.
