### ISSUE TITLE
Add indentation rules for SQL

### ISSUE THREAD

**Issue by matthias-Q** [nvim-treesitter/nvim-treesitter#4852]
**Is your feature request related to a problem? Please describe.**
The SQL parser only has highlighting and simple injections, but not indentation rules.

**Describe the solution you'd like**
Some basic indentation rules should be added. Mostly for simple select queries, queries with CTEs, create table statements and such...

**Describe alternatives you've considered**
I am trying to get these queries working by myself, but I am struggling to get them working

**Additional context**
I am willing to add a MR, since I am contributing to the tree-sitter-sql parser a lot.

Here is what I was trying:
indents.scm:
```
(select_expression) @indent.begin
```

Test SQL query after automatically indenting it with tree-sitter:
```sql
select
a,
    b
from tab;
```
Note the column `a` is not indented, even though it is a node `term` and a child of `select_expression`

AST:
```
statement [0, 0] - [3, 9]
  select [0, 0] - [2, 5]
    keyword_select [0, 0] - [0, 6]
    select_expression [1, 0] - [2, 5]
      term [1, 0] - [1, 1]
        value: field [1, 0] - [1, 1]
          name: identifier [1, 0] - [1, 1]
      term [2, 4] - [2, 5]
        value: field [2, 4] - [2, 5]
          name: identifier [2, 4] - [2, 5]
  from [3, 0] - [3, 8]
    keyword_from [3, 0] - [3, 4]
    relation [3, 5] - [3, 8]
      table_reference [3, 5] - [3, 8]
        name: identifier [3, 5] - [3, 8]
```

**Comment by lucario387** [comment]
I'll jump in if needed :smile: 

Feel free to PR it, I'll check if there's inconsistencies

Also, please comment a bit on why some queries are used, as I think there may be hacks needed(?, unsure, but most likely will happen)
