### ISSUE TITLE
Neovim freezes when opening a specific c file with a complex #define directive

### ISSUE THREAD

**Issue by vurentjie** [nvim-treesitter/nvim-treesitter#4906]
### Describe the bug

Neovim freezes when opening a specific c file. 

There is a file called "map.c" that is from an older revision of neovim source. When I try open it the freeze occurs. The issue does not occur when I disable nvim-treesitter. 

### To Reproduce

1. Use the attached init.lua 
2. Open neovim 
3. Allow initial install to happen 
4. Try open the attached "map.c" file 
5. Neovim freezes at this point

### Expected behavior

Neovim should not freeze.

### Output of `:checkhealth nvim-treesitter`

```markdown
Installation ~
- OK `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v14.17.6 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.19.0-43-generic",
  sysname = "Linux",
  version = "#44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - luap                ✓ . . . .
  - markdown            ✓ . ✓ . ✓
  - markdown_inline     ✓ . . . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - ruby                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

A sample init.lua is attached here: [init.lua.zip](https://github.com/nvim-treesitter/nvim-treesitter/files/11645365/init.lua.zip)

The problematic "map.c" file that causes the bug is attached here:[map.c.zip](https://github.com/nvim-treesitter/nvim-treesitter/files/11645366/map.c.zip)

It can also be found here: https://raw.githubusercontent.com/neovim/neovim/ca5a810c4a67c9c3f482d0c015270c26aee2c943/src/nvim/map.c

The issue seems to arise from the preprocessor directive starting on line 48 `#define MAP_IMPL(T, U, ...) `
https://github.com/neovim/neovim/blob/ca5a810c4a67c9c3f482d0c015270c26aee2c943/src/nvim/map.c#L48-L116

Removing this makes the freeze go away.

**Comment by clason** [comment]
This is a known issue with the `@preproc_arg` injection in files with too many of those. For now, just remove that line from `queries/c/injections.scm`. (You can place a copy in your `.config/nvim/queries/c` directory to override the nvim-treesitter query.)
