### ISSUE TITLE
:TSInstall doesn't copy over queries/highlights.scm

### ISSUE THREAD

**Issue by darthdeus** [nvim-treesitter/nvim-treesitter#4912]
### Describe the bug

I have a very simple custom parser for treesitter <https://github.com/darthdeus/tree-sitter-rebel>. Using the CLI tools I verified that my highlighting works, as both `tree-sitter test` returns no errors, and `tree-sitter highlight examples/simple.rbl` prints the source file highlighted.

I'm also able to install the parser via `:TSInstall rebel` and I checked in the playground that things get parsed correctly. The problem is the highlighting doesn't work, because `:TSInstall` doesn't copy it over.

Looking in `.local/share/nvim/lazy/nvim-treesitter/queries/` I can see that the directory didn't get copied over. If I manually put `highlights.scm` under `.local/share/nvim/lazy/nvim-treesitter/queries/rebel/highlights.scm` everything works fine.

### To Reproduce

1. Clone https://github.com/darthdeus/tree-sitter-rebel
2. Add the following to nvim config to configure the custom parser
```lua
local parsers = require "nvim-treesitter.parsers"
local parser_config = parsers.get_parser_configs()

parser_config.rebel = {
    install_info = {
        url = "~/projects/tree-sitter-rebel", -- update to point to the right path
        files = { "src/parser.c" },
        branch = "master",
        generate_requires_npm = true,
        requires_generate_from_grammar = true,
    },
    filetype = "rbl",
}
3. Run `:TSInstall rebel`
4. Open `examples/simple.rbl` in the repo
```

### Expected behavior

:TSInstall should copy over `highlights.scm` under the correct subdir

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.2.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "22.5.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:44 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8103"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - clojure             ✓ ✓ ✓ . ✓
  - commonlisp          ✓ ✓ ✓ . .
  - fennel              ✓ ✓ ✓ . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rebel               . . . . .
  - regex               ✓ . . . .
  - rust                ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - wgsl                ✓ . ✓ ✓ .

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

```
```


### Output of `nvim --version`

```text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.1/share/nvim"
```

**Comment by amaanq** [comment]
Of course it doesn't, that's intended

**Comment by clason** [comment]
(although that _will_ be how it works in Nvim-treesitter 1.0, which you can get early-access of on the `main` branch)

**Comment by clason** [comment]
If you mean "copy over from the repo", that is indeed not done -- and possible, since the captures (and predicates/directives) are editor-specific; we can't use the upstream captures as-is.

**Comment by darthdeus** [comment]
I don't understand what's the intended workflow for creating parsers then. Looking at a few existing ones, e.g. <https://github.com/tjdevries/tree-sitter-lua>, they just store the queries in the repo. Do I just copy all the .scm files with a script on every change?

**Comment by clason** [comment]
They store _their_ queries in the repo; we use different ones. If it's your own parser you're developing, you can of course make them neovim-specific. Then, yes, you can copy them.

(Although in this case I'd just add a makefile that creates a `<language>.so`, then link that and the queries directory into your config under `parser` and `queries`, respectively; you don't need nvim-treesitter for that at all.

**Comment by amaanq** [comment]
I just do a one-liner copy command and repeat it whenever I need to, something like 
```sh
cp queries/* ~/.local/share/nvim/lazy/nvim-treesitter/queries/objc
```

**Comment by clason** [comment]
And did you read https://github.com/nvim-treesitter/nvim-treesitter#adding-parsers (second to last paragraph)?

**Comment by darthdeus** [comment]
> (Although in this case I'd just add a makefile that creates a `<language>.so`, then link that and the queries directory into your config under `parser` and `queries`, respectively; you don't need nvim-treesitter for that at all.

The reason I ran into this is because I'm mainly intending to use my parser with nvim-treesitter, I did test it in isolation with treesitter CLI and things worked, but I was then surprised that the same parser didn't work in nvim fully.

> And did you read https://github.com/nvim-treesitter/nvim-treesitter#adding-parsers (second to last paragraph)?

Hmm looking at it now I definitely read it but probably misinterpreted it as "you need a nvim-treesitter parser config". I get it now though, but I think the wording of this is a little confusing

> you must manually [add query files](https://github.com/nvim-treesitter/nvim-treesitter#adding-queries) to your local nvim-treesitter installation

I mean it makes sense now that I _know_ that it doesn't copy them, though `TSInstall` has literally "install" in the name, so I'm not sure if it's immediately obvious how this works together.
