### ISSUE TITLE
Highlight the code between # ifdef foo # endif, even if macro foo is not defined

### ISSUE THREAD

**Issue by zaiqiang-dong** [nvim-treesitter/nvim-treesitter#4929]
### Describe the highlighting problem

In the kernel or android code, great macros are generated before compilation, and Parsing cannot complete the judgment of whether macros are defined, resulting in the inability to highlight large pieces of code between macros

How to Configure Forced Highlight the Code between  Macros

### Example snippet that causes the problem

#ifdef foo
    code between macros
#endif

### Tree-sitter parsing result

#ifdef foo
    code between macros
#endif
"code between macros" does not highlight.

### Example screenshot

#ifdef foo
    code between macros
#endif

How to Configure Forced Highlight the Code between  Macros

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v18.16.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.15.0-73-generic",
  sysname = "Linux",
  version = "#80~20.04.1-Ubuntu SMP Wed May 17 14:58:14 UTC 2023"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - diff                ✓ . . . .
  - git_rebase          ✓ . . . ✓
  - gitattributes       ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . .
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - todotxt             ✓ . . . .
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - vue                 ✓ . ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
=> vim --version
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
Please add a screenshot. (And make sure you don't have the `clang` language server overriding the tree-sitter highlights with semantic tokens; `:Inspect` will tell you whether that is the case.)

**Comment by zaiqiang-dong** [comment]
:Inspect output is :
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/10396859/58bbbfc6-cec0-413e-9d13-8a948ce537f1)
and i use cland as language server. If  don't use clangd, any other optional language services for c can be select?
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/10396859/8193b47e-f227-40e8-9184-167699e5796e)

**Comment by lucario387** [comment]
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/29790821/7cd3058f-9956-4560-ba07-2dbf0cabcee0)
With the cursor on line 9, on printf, we have an image like above

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/29790821/447f98da-240d-4ce5-98dd-11ff3b413b2d)
Also the same spot, but now with clangd with semantic tokens enabled, we have the highlight similar to how you describe it
So I'd say this is because of semantic tokens and not related to treesitter/nvim-treesitter

**Comment by amaanq** [comment]
`:h vim.lsp.semantic_tokens.stop()`
