### ISSUE TITLE
Screenshots!

### ISSUE THREAD

**Issue by stsewd** [nvim-treesitter/nvim-treesitter#494]
I'm just opening this issue to allow us to upload images for the wiki. Show us how your Neovim looks like using nvim-treesitter!

**Comment by stsewd** [comment]
![lua-ts](https://user-images.githubusercontent.com/4975310/93649836-8222f980-f9d2-11ea-9c91-dc5d7e02835a.png)

![python-ts](https://user-images.githubusercontent.com/4975310/93649922-bac2d300-f9d2-11ea-838e-f68f155f9e50.png)

**Comment by stsewd** [comment]
Wiki at https://github.com/nvim-treesitter/nvim-treesitter/wiki/Gallery

**Comment by p00f** [comment]
### Java

![ts_gallery](https://user-images.githubusercontent.com/36493671/93662382-485afd00-fa7d-11ea-881a-677eed2a8d6a.png)

**Comment by p00f** [comment]
vim's builtin java highlighting really sucks

**Comment by p00f** [comment]
Looks like I switched left and right (shouldn't treesitter be on the right to show before-after?)

**Comment by stsewd** [comment]
> shouldn't tree-sitter be on the right to show before/after?

Maybe, I don't know I did it the other way because left is what you normally see first, don't know, anyone else has thoughts about this?

I have added it to the wiki, soon you'll be able to edit the wiki by yourselves :)

**Comment by p00f** [comment]
Fennel - treesitter(left) vs builtin(top right) (there is no builtin highlight) vs regex-based highlight (bottom-right) (https://github.com/bakpakin/fennel.vim)
![image](https://user-images.githubusercontent.com/36493671/93671744-3dc35680-fac3-11ea-8e9c-de297d597692.png)

**Comment by pyrho** [comment]
Typescript - Treesitter on the left vs traditional regexp-based via [YATS.vim](https://github.com/HerringtonDarkholme/yats.vim), theme: [Embark](https://github.com/embark-theme/vim).
![Screenshot 2020-09-25 at 21 29 23](https://user-images.githubusercontent.com/145502/94308159-9da77a80-ff65-11ea-9de8-7be297148a25.png)

**Comment by vigoux** [comment]
Screenshots now moved to the wiki, please contribute there : https://github.com/nvim-treesitter/nvim-treesitter/wiki/Colorschemes

**Comment by stsewd** [comment]
This was so users could upload the images, the wiki doesn't allow to do that. But I have linked to this issue from the wiki :)

**Comment by paniash** [comment]
Recently added a screenshot using Julia!
