### ISSUE TITLE
API for manually syntax highlighting a string containing code.

### ISSUE THREAD

**Issue by no-more-secrets** [nvim-treesitter/nvim-treesitter#4942]
Sometimes I have commands that output small snippets of code into the message box, and I output it in a way that colors it (you can indeed emit colors to the message box).  Currently I'm manually coloring it though, but ideally I'd like to ask TS to do it for me.  For example, I'd like to be able to do something like this:
```lua
local c_code = 'int x = 0;'
local syntax_colored = magical_treesitter_api.highlight_string_for_message_box( 'C', c_code )
print( syntax_colored ) -- send to message box with colors.
```
Then it would appear syntax highlighted in the message box 8-)  Actually, the API would not even have to insert the color codes that the message box uses, it would just have to annotate the string in some way with color indicators that I could then parse and transform into the kind of color escape codes that the message box uses.

Is my dream possible?

**Comment by clason** [comment]
No, sorry, that is out of scope -- certainly of this plugin, which doesn't handle highlighting.
