### ISSUE TITLE
Failed healthcheck - query.lua:20 invalid node type at position

### ISSUE THREAD

**Issue by tkolleh** [nvim-treesitter/nvim-treesitter#497]
**Describe the bug**
Failed health check

**To Reproduce**
1. Open neovim `nvim $MYVIMRC`
2. Run `healthcheck`
3. See error

**Expected behavior**
Pass health check

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>
health#nvim_treesitter#check
========================================================================
  - ERROR: Failed to run healthcheck for "nvim_treesitter" plugin. Exception:
    function health#check[21]..health#nvim_treesitter#check, line 1
    Vim(lua):E5108: Error executing lua ...-569e757/share/nvim/runtime/lua/vim/treesitter/query.lua:20: query: invalid node type at position 2544
</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-nightly-75-g569e75799
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200919-28015-c8n83g/build/config -I/tmp/neovim-20200919-28015-c8n83g/src -I/usr/local/include -I/tmp/neovim-20200919-28015-c8n83g/deps-build/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200919-28015-c8n83g/build/src/nvim/auto -I/tmp/neovim-20200919-28015-c8n83g/build/include
Compiled by *************

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-569e757/share/nvim"

Run :checkhealth for more info
```

**Comment by tkolleh** [comment]
Not sure if this was the actual fix, but, issue resolved after running `:TSUpdate`. Closing issue.

**Comment by stsewd** [comment]
yeah, if  a grammar was updated, tsupdate/reinstalling should have picked the last update of the grammar.
