### ISSUE TITLE
gcc fails to compile parsers on Windows: not a valid WIN32 application

### ISSUE THREAD

**Issue by osherbz** [nvim-treesitter/nvim-treesitter#502]
**Is your feature request related to a problem? Please describe.**
On windows system setting-up nvim-treesitter was a little problem for me, because I got some error like :
1. uv_dlopen cant find module
2. *.so is not valid WIN32 application.

I fixed it by removing gcc/g++ compilers from path and using clang.

**Describe the solution you'd like**
Add this information to troubleshooting on windows or windows wiki.

**Describe alternatives you've considered**
When Using `:TSUpdate` etc... I would love if a little menu will shown up and show available compilers and choose from them.
like this for example:
:TSUpdate 
-- compilers from path
-- 1. gcc/g++ (default)
--  2. clang 
-- Enter compiler number:

**Additional context**
I am using gcc/g++ many times, every time that I want to TSUpdate I will need to remove it from path.
It will be very comfortable if there will be menu like i mentioned above.

Thanks in advance for any help you are able to provide.

**Comment by theHamsta** [comment]
You can edit the Windows wiki entry to add this information. After all it's a a wiki where everybody can share their knowledge and recommendations.

Should we prefer clang over gcc? `-fPIC` was removed for gcc on Windows, have you tried compiling with gcc with `-fPIC`.

**Comment by theHamsta** [comment]
I would prefer fixing the issue with gcc over asking the user every time for a compiler. In a ideal world, any compiler should work for nvim-treesitter.

**Comment by osherbz** [comment]
> You can edit the Windows wiki entry to add this information. After all it's a a wiki where everybody can share their knowledge and recommendations. Could you add instruction on how to install clang on Windows? Probably you can describe best since you are using Windows. When I was writing the article I had to borrow a foreign computer with Windows installed.
> 
> Should we prefer clang over gcc? `-fPIC` was removed for gcc on Windows, have you tried compiling with gcc with `-fPIC`?

Yes I will add information to the wiki and also add clang install instructions.
Now I am checking the -fPIC flag.

**Comment by osherbz** [comment]
@theHamsta  I added the clang installation and troubleshooting on Windows wiki, but I dont know how to push it.
I tried to fork https://github.com/nvim-treesitter/nvim-treesitter.wiki.git and didnt work.

Should I Send the updated Windows-support.md here?

**Comment by theHamsta** [comment]
@osherbz sorry! I didn't know that the Wiki is read only for contributers. You can post your updated file here. We try to give everyone permission ASAP.

**Comment by osherbz** [comment]
@theHamsta https://github.com/osherbz/nvim-treesitter.wiki.git

**Comment by theHamsta** [comment]
@osherbz thanks a lot for your help. I updated the Wiki.

**Comment by osherbz** [comment]
@theHamsta You're welcome (: 
 I tested with the -fPIC flag and it didnt worked with gcc/g++.

**Comment by vigoux** [comment]
This issue seems stalled for some reason, could you confirm ?
