### ISSUE TITLE
Python indent bug with escape strings

### ISSUE THREAD

**Issue by lcrownover** [nvim-treesitter/nvim-treesitter#5022]
### Describe the bug

After using an escape sequence in a string, indentation is broken. The odd thing is that I have indent turned off:

```lua
		require("nvim-treesitter.configs").setup({
			auto_install = true,
			highlight = { enable = true },
			indent = {
				enable = false,
			},
                }
```

I have verified that removing my treesitter config above (disabling treesitter) makes the bug go away.

### To Reproduce

Given the following python code in a file:

```python
def one():
    pass

mycolor = "\033[94m"

def two():
    pass
```

If I put my cursor at the `def one()` line and press `o`, it will correctly indent and my cursor will be in line with `pass` on a new line.

However, any indented code below the escape string will cause broken indentation. If I put my cursor on the `def two()` line and press `o`, it makes a new line and indents 14 spaces. 

If I make my function into a method and do the same indent operation:

```python
class MyClass:
    def two():
        pass
```

Even though the `def two()` line is already indented, the newly created line is still indented 14 characters.

### Expected behavior

Indentation should be correct. Or, disabling indentation should disable this behavior?

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.2.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "22.5.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

```
```


### Output of `nvim --version`

```text
NVIM v0.9.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Library/Developer/CommandLineTools/usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -I/Users/lcrown/repos/neovim/.deps/usr/include/luajit-2.1 -I/opt/homebrew/opt/gettext/include -I/Users/lcrown/repos/neovim/.deps/usr/include -I/Users/lcrown/repos/neovim/build/src/nvim/auto -I/Users/lcrown/repos/neovim/build/include -I/Users/lcrown/repos/neovim/build/cmake.config -I/Users/lcrown/repos/neovim/src -I/Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr/include -I/Users/lcrown/repos/neovim/.deps/usr/include -I/Users/lcrown/repos/neovim/.deps/usr/include -I/Users/lcrown/repos/neovim/.deps/usr/include -I/Users/lcrown/repos/neovim/.deps/usr/include -I/Users/lcrown/repos/neovim/.deps/usr/include -I/Users/lcrown/repos/neovim/.deps/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
```


### Additional context

_No response_

**Comment by lucario387** [comment]
Can you show your `setup` of nvim-treesitter.

I suspect the problem here lies in the disabling of Vim's syntax highlighting, which Vim's default indentexpr heavily relies on

**Comment by lcrownover** [comment]
I have added that line to my config and see no difference in behavior😢

**Comment by lucario387** [comment]
Well with `indent = { enable = true }` I can't reproduce the behavior, so the problem here must lie in Vim's indent not working.

Use `highlight = { additional_vim_regex_highlighting = true }` and retry. From my end, it's working as intended

**Comment by lcrownover** [comment]
Oh interesting, with `enable = true`, I don't get the behavior. It's odd though, that by commenting out the entire setup block, it also resolves the issue. Something about having treesitter loaded but not configured for indenting is worse than not having it loaded at all? 

I suppose that fix works for me, thanks!
