### ISSUE TITLE
Can we get A release of the Windows binaries

### ISSUE THREAD

**Issue by MegaMech** [nvim-treesitter/nvim-treesitter#5070]
Clang doesn't want to work with MSVC on my system.

I understand that you would like to have actions that auto-update the binaries.

But since that's a ways off, could we get _any_ Windows binaries added to the releases page? Something is better than nothing.

Or could I be sent the Windows binaries? Setting up compilers in gnu/Linux is easy, Windows sucks.

Thanks.

**Comment by amaanq** [comment]
Try using Zig as the compiler, there's been success w/ that

**Comment by MegaMech** [comment]
Thanks! Will try that

**Comment by clason** [comment]
We don't distribute binaries; that is completely infeasible and counter to the project goals.

**Comment by MegaMech** [comment]
You did in October

https://github.com/nvim-treesitter/nvim-treesitter/issues/1901

**Comment by clason** [comment]
If you think you can set this up you are very welcome to do so. (And that PR concerned our CI, not precompiled binaries suitable for distribution. You're welcome to download the artifacts created as byproducts from our CI, but we cannot make any guarantees on them.)
