### ISSUE TITLE
Support for wiki links and tags in markdown

### ISSUE THREAD

**Issue by musjj** [nvim-treesitter/nvim-treesitter#5081]
**Is your feature request related to a problem? Please describe.**
[tree-sitter-markdown](https://github.com/MDeiml/tree-sitter-markdown) recently added support for zettelkasten-style wiki links and tags. But these features require `EXTENSION_TAGS` and `EXTENSION_WIKI_LINK` to be set on compile-time. 

**Describe the solution you'd like**
Built-in support for these features would be nice.

**Describe alternatives you've considered**
I've tried to set these variables by doing `EXTENSION_WIKI_LINK=1 EXTENSION_TAGS=1 nvim`, before re-installing the parser but it's not working.

**Comment by clason** [comment]
Sorry, but we can't officially support this. Your best bet is to compile the parsers manually and place them in your local config directory.

**Comment by musjj** [comment]
It turns out that no special support was needed. You just had to make sure that `tree-sitter generate` is run before compiling. This can be easily done by setting `requires_generate_from_grammar` to `true` for markdown:
```lua
vim.env.EXTENSION_WIKI_LINK = 1
vim.env.EXTENSION_TAGS = 1

local parser_config = require("nvim-treesitter.parsers").get_parser_configs()
parser_config.markdown.install_info.requires_generate_from_grammar = true
parser_config.markdown_inline.install_info.requires_generate_from_grammar = true
```
Now on to making the queries I guess...

**Comment by amaanq** [comment]
you don't need to do that, you can just do `:TSInstallFromGrammar` instead

**Comment by musjj** [comment]
Thanks for the tip! But I think that method won't work when you do a `:TSUpdate all`.

**Comment by amaanq** [comment]
ah right, that is true.
