### ISSUE TITLE
Feat: Allow disabling based on table of languages and custom function

### ISSUE THREAD

**Issue by Subjective** [nvim-treesitter/nvim-treesitter#5105]
**Is your feature request related to a problem? Please describe.**
I'd like to disable treesitter highlighting for latex buffers as it interferes with VimTex, which has its own syntax highlighting. However, this conflicts with a function I have that disables highlighting on large files. It doesn't seem like there's an easy way to provide both a disable table and a custom function as both of these are supposed to be provided to the same entry in the config table.

**Describe the solution you'd like**
Add options `disabled_languages` and `disable_function` to distinguish these two use cases from one another. The former can be used to configure languages from a table, while the latter can be used to provide a custom function. As for the current `disable` option, it could be kept around to avoid breaking changes:

**Describe alternatives you've considered**
I've tried setting up an autocmd that disables treesitter on the `VimtexEventInitPre` event, but that doesn't seem to work. There also doesn't seem to be any treesitter related events I can hook into to disable based on filetype conveniently.

Thanks!

**Comment by clason** [comment]
Why are you even installing the LaTeX parser if you don't need it?

And there's already a `disable` feature that allow you to customize things based on language _and_ buffer contents.
