### ISSUE TITLE
nvim-treesitter[bash]: getting compilation error

### ISSUE THREAD

**Issue by rohit-s8** [nvim-treesitter/nvim-treesitter#5109]
### Describe the bug

The bash parser is unable to install due to compilation errors.

Here is the output of `TSInstall bash`
![Screenshot_20230715_215823](https://github.com/nvim-treesitter/nvim-treesitter/assets/29656930/6a046099-a640-49d6-ac91-1e7d7b7df5f3)

And `TSInstallSync bash`
![Screenshot_20230715_215900](https://github.com/nvim-treesitter/nvim-treesitter/assets/29656930/05a88a5a-da3a-4d86-97d3-2de649f064da)

I checked the repo https://github.com/tree-sitter/tree-sitter-bash which i guess is being downloaded, but found only `scanner.c` there, no `scanner.cc`.

### To Reproduce

1. Check out latest nvim-treesitter
2. Run `TSInstall bash` in neovim command line

### Expected behavior

Expected bash parser to install.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.3.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.1.1 20230429
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.3.12-1-MANJARO",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Thu Jul  6 15:52:38 UTC 2023"
} ~

Parser/Features         H L F I J
  - graphql             ✓ . . ✓ ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - sql                 ✓ . . ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
❯ nvim --version  
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
You need to update nvim-treesitter before compiling. (The C++ scanner was moved to C, which changed the filename.)

**Comment by rohit-s8** [comment]
@clason I got this error after updating nvim-treesitter. 

For more context i am on commit `12d970f8` which is the latest commit on master branch as of now.

**Comment by clason** [comment]
[No, you're not](https://github.com/nvim-treesitter/nvim-treesitter/blob/12d970f8aea7eed4d98727b3234ab098ddde3576/lua/nvim-treesitter/parsers.lua#L117). Make sure there aren't stale copies in your runtimepath, or some sort of Lua cache.

(and just to be _very_ clear about this: you always need to restart Neovim after updating a plugin. there's no such thing as "hot reloading", and don't believe anybody who tells you otherwise.)

**Comment by rohit-s8** [comment]
My bad, I should have restarted neovim after the update. Thanks :+1:
