### ISSUE TITLE
Change inner function and change inner module function

### ISSUE THREAD

**Issue by quantum-booty** [nvim-treesitter/nvim-treesitter#511]
Is there a way to have "change inner" ci motion for these objects (and similarly for di vi )?
np.log()
function()

I tried to use the incremental selection, with gnn initializes node selection, grn inceases node selection:
nmap cif gnngrngrnc
Howevery this only works for np.log(), because it has three nodes; and does not work for function(), as it has two nodes.

**Comment by stsewd** [comment]
What you are asking for are textobjects, and we already support them https://github.com/nvim-treesitter/nvim-treesitter#text-objects-select

**Comment by quantum-booty** [comment]
@stsewd Sorry I've not been clear, the supported text objects are for function definitions, what I had in mind was function call.

**Comment by stsewd** [comment]
What you see in the docs are only examples, you can define your own, function calls are already supported

https://github.com/nvim-treesitter/nvim-treesitter/blob/718fc1be3e9a4997217d25f59e59a5907cc3747f/queries/python/textobjects.scm#L33-L34

**Comment by quantum-booty** [comment]
@stsewd wow thank you
