### ISSUE TITLE
Lockfile has bad commit for tree-sitter-regex

### ISSUE THREAD

**Issue by ilkka** [nvim-treesitter/nvim-treesitter#5125]
### Describe the bug

lockfile.json has commit 17a3293714312c691ef14217f60593a3d093381c for [tree-sitter-regex](https://github.com/nvim-treesitter/nvim-treesitter/blob/19b29f7cb046317b74e60fc7bff2f86ece4dc118/lockfile.json#L438) but that commit has apparently [disappeared from the repo](https://github.com/tree-sitter/tree-sitter-regex/commit/17a3293714312c691ef14217f60593a3d093381c). Since the contents of the commit talk about releasing 1.0.0, maybe there was some problem with automation that the maintainer then fixed by rewriting history. Anyway, this breaks my fresh install of lazyvim because it's trying to check out that commit and failing.

### To Reproduce

1. clone tree-sitter-regex
2. `git checkout 17a3293714312c691ef14217f60593a3d093381c`

### Expected behavior

Checkout succeeds

### Output of `:checkhealth nvim-treesitter`

```markdown
Not relevant here
```

### Output of `nvim --version`

```text
Not relevant here
```

**Comment by amaanq** [comment]
Yeah that's on me, sorry. Should be fixed shortly, probably later today

**Comment by clason** [comment]
Should be fixed now.
