### ISSUE TITLE
Consistently receiving the error message "no parser for zsh language."

### ISSUE THREAD

**Issue by guxuerui** [nvim-treesitter/nvim-treesitter#5131]
### Describe the bug

When I try to press the keyboard `=` in my `.zshrc` file, I  consistently receiving the error message "no parser for zsh language.".

And I am certain that I have installed the latest parser "tree-sitter-bash" by executing `TSUpdate bash`.

[My treesitter config](https://github.com/guxuerui/nvim-0.8/blob/main/lua/plugins/treesitter.lua)

<img width="2426" alt="Screenshot 2023-07-19 at 23 17 12" src="https://github.com/nvim-treesitter/nvim-treesitter/assets/23629097/539874b3-3e76-40dd-af4e-9ad0cd204191">

### To Reproduce

1. run `TSUpdate bash`
2. write `alias pre='...' in `.zshrc` file
3. and will get error when press `=`

### Expected behavior

No errors were reported.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v18.14.2 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "22.5.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:44 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8103"
} ~

Parser/Features         H L F I J
  - astro               ✓ ✓ ✓ ✓ ✓
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - fish                ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - json5               ✓ . . . ✓
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - rust                ✓ ✓ ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ .
  - svelte              ✓ . ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - vue                 ✓ . ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Additional context

**In my test, The error only occurs when pressing the `=` key.**

**Comment by clason** [comment]
`bash` is not `zsh`. Can you reproduce this with _only_ nvim-treesitter?  I don't see anything in our plugin that should start the highlighting for `zsh` filetypes.

**Comment by guxuerui** [comment]
> `bash` is not `zsh`. Can you reproduce this with _only_ nvim-treesitter? I don't see anything in our plugin that should start the highlighting for `zsh` filetypes.

Oh  sorry, my mistake. But  I can't reproduce this with only `nvim-treesitter` too,  and I couldn't find any documentation related to the zsh file. Does that mean it's not supported?

**Comment by clason** [comment]
That's correct; there's no parser for `zsh`.

**Comment by guxuerui** [comment]
> That's correct; there's no parser for `zsh`.

Thank you, I understand. Will support for `zsh` files be provided in the future?

**Comment by clason** [comment]
If someone provides it, yes. (Everything here is community-contributed.)
