### ISSUE TITLE
Query error... Impossible pattern

### ISSUE THREAD

**Issue by dickmao** [nvim-treesitter/nvim-treesitter#5149]
### Describe the bug

```
$ tree-sitter -V
tree-sitter 0.20.8 (a809274009953c9d3c314c7dd27909b1347635f8)

$ tree-sitter query -c queries/c/indents.scm --scope source.c /dev/null
Query compilation failed

Caused by:
    Query error at 53:5. Impossible pattern:
        "else" @indent.branch
        ^
```
How do you guys get your indents.scm to parse when vim.treesitter calls ts_query_new()?

### To Reproduce

ibid. above

### Expected behavior

ibid. above

### Output of `:checkhealth nvim-treesitter`

```markdown
ibid. above
```

### Output of `nvim --version`

```text
ibid. above
```

**Comment by dickmao** [comment]
> We don't use the `tree-sitter`

Yeah you do, you just don't know it yet.

The reason why it works is because you've locked the tree-sitter-c parser revision to `6adee19`.

That is bad, but I admit I'll occasionally pull a similar fast one.

**Comment by clason** [comment]
What do you mean (and please keep it civil)?

Of course we don't use the treesitter highlight crate (which is what triggers this error).

And of course we lock parser revisions to working ones; that's the main job of this plugin. But that is a different issue.

**Comment by clason** [comment]
Ah, I just now notice my typo. That was meant to refer to the tree-sitter highlight crate; of course we (via Neovim) use the tree-sitter C library (and parsers).

My point is that your error stems from the crate specifically, so has nothing to do with this repo. And our queries are not meant to work with the crates, only with Neovim's own implementation.

(Not that tree-sitter even supports indent queries, so this is a double context error).

**Comment by theHamsta** [comment]
I assume the problem is related to the changes for the if statement by amaanq (here the corresponding update for cpp https://github.com/tree-sitter/tree-sitter-cpp/commit/0dd318d271dd818311a6f6558bffbdbd28e85b88)

**Comment by clason** [comment]
I mean, obviously, but I'm still not sure what the actual problem is...
