### ISSUE TITLE
Can't change highlighting of single keywords

### ISSUE THREAD

**Issue by vxld100** [nvim-treesitter/nvim-treesitter#5152]
### Describe the highlighting problem

I am trying to add new highlighting for single keywords for ada. However, whether I modify the highlights.scm file in the .local directory or my after/queries directory, treesitter refuses to acknowledge this config as valid, despite the fact that the default config in the .local directory uses this syntax all the time. 

### Example snippet that causes the problem

Some snippets that cause issues are 
`[ "Integer" ] @type` 
again, I can't even modify the highlights.scm file in the .local directory to add this. 
Also, the original configuation file does things like
`(loop_statement "end" @keyword.repeat)`
but when I try to do something like
`(loop_statement "exit" @keyword.repeat)`
Treesitter refuses to accept the config.

### Tree-sitter parsing result

      loop_statement [8, 1] - [12, 10]
        statements: procedure_call_statement [9, 2] - [9, 61]
          name: identifier [9, 2] - [9, 10]
          actual_parameter_part [9, 11] - [9, 60]
            parameter_association [9, 12] - [9, 59]
              expression [9, 12] - [9, 59]
                term [9, 12] - [9, 34]
                  name: string_literal [9, 12] - [9, 34]
                binary_adding_operator [9, 35] - [9, 36]
                term [9, 37] - [9, 53]
                  name: function_call [9, 37] - [9, 53]
                    name: identifier [9, 37] - [9, 44]
                    name: tick [9, 44] - [9, 45]
                    name: attribute_designator [9, 45] - [9, 50]
                      identifier [9, 45] - [9, 50]
                    actual_parameter_part [9, 50] - [9, 53]
                      parameter_association [9, 51] - [9, 52]
                        expression [9, 51] - [9, 52]
                          term [9, 51] - [9, 52]
                            name: identifier [9, 51] - [9, 52]
                binary_adding_operator [9, 54] - [9, 55]
                term [9, 56] - [9, 59]
                  name: string_literal [9, 56] - [9, 59]
        statements: exit_statement [10, 2] - [10, 18]
          condition: expression [10, 12] - [10, 17]
            term [10, 12] - [10, 13]
              name: identifier [10, 12] - [10, 13]
            relational_operator [10, 14] - [10, 15]
            term [10, 16] - [10, 17]
              numeric_literal [10, 16] - [10, 17]
        statements: assignment_statement [11, 2] - [11, 13]
          variable_name: identifier [11, 2] - [11, 3]
          expression [11, 7] - [11, 12]
            term [11, 7] - [11, 8]
              name: identifier [11, 7] - [11, 8]
            binary_adding_operator [11, 9] - [11, 10]
            term [11, 11] - [11, 12]
              numeric_literal [11, 11] - [11, 12]

### Example screenshot

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/111303738/904a7962-6b14-4ddc-8f0c-ccad9077b1c0)

### Expected behavior

Other custom configurations (from either file) work like a charm, but whenever I use quotes in any of the two config files in order to work with keywords, treesitter doesn't accept the config. This is particularly frustrating because the [Treesitter documentation](https://tree-sitter.github.io/tree-sitter/using-parsers#query-syntax) makes it seem like this kind of configuation should be perfectly legal.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- WARNING `node` executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 12.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.3.12_1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Fri Jul  7 08:41:32 UTC 2023"
} ~

Parser/Features         H L F I J
  - ada                 x ✓ ✓ . .
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR ada(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 4934 for language ada
  ada(highlights) is concatenated from the following files:
  |    [OK]:"/home/lilin/.local/share/nvim/lazy/nvim-treesitter/queries/ada/highlights.scm"
  | [ERROR]:"/home/lilin/.config/nvim/after/queries/ada/highlights.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 364 for language ada
```

### Output of `nvim --version`

```text
NVIM v0.9.1
Build type: None
LuaJIT 2.1.0-beta3
Compilation: /usr/lib/ccache/bin/cc  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/usr/include/luajit-2.1 -I/usr/include -I/usr/include -I/builddir/neovim-0.9.1/build/src/nvim/auto -I/builddir/neovim-0.9.1/build/include -I/builddir/neovim-0.9.1/build/cmake.config -I/builddir/neovim-0.9.1/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
Are these (anonymous) nodes exposed by the grammar? (You can check using `:InspectTree` and toggling anonymous nodes via `a`.)
