### ISSUE TITLE
Add support for `Linux Kconfig language`

### ISSUE THREAD

**Issue by beyond-fu** [nvim-treesitter/nvim-treesitter#5170]
**Is your feature request related to a problem? Please describe.**
Today I'm writing `Kconfig`, though the syntax is simple, it's better with a syntax highlighting. Thanks.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by clason** [comment]
Please add it to https://github.com/nvim-treesitter/nvim-treesitter/issues/2282 (with details on whether a parser exists, or links to the syntax description).
