### ISSUE TITLE
Use Pattern Matching to Ignore Misspelled Words

### ISSUE THREAD

**Issue by uvb1** [nvim-treesitter/nvim-treesitter#5173]
In markdown, without treesitter the following code prevents text like `v1` or `v2` from being flagged as misspelled words:

`vim.cmd.syntax([[match IgnoreVersion 'v[0-9]' contains=@NoSpell]])`

If markdown is installed in treesitter (ie, `:TSInstall markdown`), the above stops working and `v1` is flagged as a misspelled word.

Is there anything similar to the pattern matching above that could be used with treesitter to ignore some misspellings based on a pattern match?

**Comment by lucario387** [comment]
It's pretty impossible to do this, as the parser doesn't consider specific strings like that, but rather consider it as part of an entire paragraph. You'd need to mark the entire paragraph as `@nospell`.
