### ISSUE TITLE
Nim language-support

### ISSUE THREAD

**Issue by marwal-88** [nvim-treesitter/nvim-treesitter#5182]
name: nim
ts-parser:
  alaviss: https://github.com/alaviss/tree-sitter-nim
  aMOPel: https://github.com/aMOPel/tree-sitter-nim
queries:
  alaviss: https://github.com/alaviss/tree-sitter-nim/tree/main/queries
  aMOPel: https://github.com/aMOPel/tree-sitter-nim/tree/main/queries
grammar-desc: https://nim-lang.org/docs/manual.html#syntax-grammar

**Comment by clason** [comment]
Please check https://github.com/nvim-treesitter/nvim-treesitter/issues/2282 and add it there if it isn't already.
