### ISSUE TITLE
Multi-line folds using `(comment)+` do not work

### ISSUE THREAD

**Issue by leonerd** [nvim-treesitter/nvim-treesitter#5184]
### Describe the bug

While some languages have commenting constructs like C's `/* ... */` that can span multiple lines, many do not. It is common in such languages to just write multiple single-line comments across several adjacent lines. As the intended spirit of this is to create a multiple-line comment block similar to a C-style one, it is likely that users would want to consider such a construction as a single block for folding purposes, and have it hidden away nicely.

You would think, therefore, that a quantified capture in `folds.scm` such as

```
(comment)+ @fold
```

would achieve this. However, it does not. Either the query engine doesn't match it, or nvim doesn't recognise it as such. Either way, the fold does not apply.

A common workaround in these languages is to have the `(comment)` node match multiple adjacent lines of intput, but that causes its own many issues. I have explained two important ones here: https://github.com/tree-sitter-perl/tree-sitter-perl/issues/104

I don't know if this is a bug within nvim-treesitter's power to fix, or if it will require tree-sitter itself to support it. But either way it'd be nice to fix it.

### To Reproduce

1. Take a language definition whose `(comment)` token only matches a single line
2. Add `(comment)+ @fold` to `queries/fold.scm`

### Expected behavior

Multiple lines of comment in the source file are treated as a single block for folding purposes

### Output of `:checkhealth nvim-treesitter`

```markdown
OS Info:
{
  machine = "x86_64",
  release = "6.3.0-1-amd64",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Debian 6.3.7-1 (2023-06-12)"
}

Parser/Features         H L F I J
  - perl                ✓ . ✓ . ✓
  - vim                 ✓ ✓ ✓ . ✓
  - pod                 ✓ . . . .
  - help                ✓ . . . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - c                   ✓ ✓ ✓ ✓ ✓
```

### Output of `nvim --version`

```text
NVIM v0.9.0-dev-820+ga0a112515
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g  -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fno-common -fdiagnostics-color=always -fstack-protector-strong -DNVIM_UNIBI_HAS_VAR_FROM -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/runner/work/neovim/neovim/.deps/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src
Compiled by runner@fv-az844-837

Features: +acl +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"
```

**Comment by leonerd** [comment]
Unfortunately, given some local testing independently of `nvim`, I think this is a limitation of tree-sitter itself.

If I attempt to match a `(comment)+` when comment itself only covers a single line, then a four-line comment block such as the following gets interpreted as four individual matches of the pattern, each capturing just one line each:

```
╞   #  You may distribute under the terms of either the GNU General Public License
╞   #  or the Artistic License (the same terms as Perl itself)
╞   #
╞   #  (C) Paul Evans, 2023 -- leonerd@leonerd.org.uk
```

whereas the multiline definition of a comment gets treated as one four-line region:

```
┌── #  You may distribute under the terms of either the GNU General Public License
│   #  or the Artistic License (the same terms as Perl itself)
│   #
└── #  (C) Paul Evans, 2023 -- leonerd@leonerd.org.uk
```

I think therefore there's not a lot that nvim can do about this without an upstream fix from tree-sitter itself.

**Comment by clason** [comment]
Nvim-treesitter is the wrong place for this issue, as it doesn't handle any logic (anymore). Either this is a tree-sitter lib (if `tree-sitter query` behaves similarly) or a Neovim issue.

**Comment by clason** [comment]
@amaanq

**Comment by clason** [comment]
(Check the open issues/PRs, too; there was a related-looking bug about quantifiers not working properly.)

**Comment by leonerd** [comment]
Actually on further poking at code locally, I think this *is* specifically an nvim problem. My code was incorrectly handling the matches.

The old code used to iterate every capture of every match individually, and indeed found four separate `@fold` regions. But in the new approach, which now works, I iterate every match, then collect up the *entire* range of nodes that were captured under the `@fold` id, and then apply a single folding region to the entire span covered by all of those nodes. I suspect nvim-treesitter somewhere will contain a similar code structure to that, and can be fixed in a similar way. I'll go code-diving and see what I can find.

**Comment by clason** [comment]
https://github.com/neovim/neovim/pull/17099
