### ISSUE TITLE
How to show TS highlight group of current symbol?

### ISSUE THREAD

**Issue by merlinmarek** [nvim-treesitter/nvim-treesitter#519]
I want to use treesitter for highlighting and want to finetune the colors. I know that I can adjust the highlight through entries of the following type (example):

highlight default link TSFunction TSNone

Before using treesitter I could get the highlight groups of the current symbol under the cursor vim the following mapping:

"  show the highlight group of current word
nmap <leader>sh :call <sid>SynStack()<cr>
function! <sid>SynStack()
  if !exists("*synstack")
    return
  endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc

This does not work with treesitter. Is there any way to show the treesitter highlight group for the symbol under the cursor? That would greatly simplify the adjustments I want to make.

Thanks in advance

**Comment by kyazdani42** [comment]
i have a lua function for that in my configs, but right now, it does not work.
Lua hl is using decorations and not the standard syntax api so getting the value is a little bit trickier and the hl groups must be set in a namespace in order to get them, which isn't the case anymore, so we cannot get them atm. I'll tell you when it changes.

**Comment by theHamsta** [comment]
We could easily write a function for that that just lists all "highlight" matches defined by the queries and checks which of them have a range that contains current cursor position. Basically exchange "textobject" query group in textobject_at_point by "highlight'

**Comment by kyazdani42** [comment]
i do not agree. Lua hl shouldn't rely on treesitter to get highlight groups applied on a buffer, this should be built into neovim imo.

**Comment by kyazdani42** [comment]
but we could write a function that list highlights from matches in the meanwhile

**Comment by theHamsta** [comment]
Don't get me wrong there should be a built in mechanism for this. I only think it's not worth writing a built in solution for upstream as long Lua highlight is still in development (which marks are used and how queries translate to marks). But a workaround for the meantime could be useful for bug reports.
Maybe

**Comment by vigoux** [comment]
I _think_ there's nothing we can do yet for that. Though we should push to find a way upstream, and I think this should be marked as a upstream issue.

**Comment by theHamsta** [comment]
I can maybe add a helper for the playground that we can use for debugging until upstream has this funcionality.

**Comment by kyazdani42** [comment]
upstream had a fonctionnaliy when its was based on extmarks, but know they use decorations which is not associated to a namespace :) 
maybe a query helper would be a better solution until upstream is stable

**Comment by kyazdani42** [comment]
update on this PR: https://github.com/neovim/neovim/pull/13038/files has been merged, getting hl group for symbols should work again since the namespace has been added.

**Comment by rafikdraoui** [comment]
This now can be done through the `TSHighlightCapturesUnderCursor` command in `nvim-treesitter/playground`: https://github.com/nvim-treesitter/playground/pull/9

**Comment by theHamsta** [comment]
Yes, but it should only be a hack until the upstream highlighter stabilized and offers a proper solution.

**Comment by vigoux** [comment]
To be honest with everyone, this is how we are going to have it. The interface is pretty much ready now, and the main way of gathering highlights informations from tree-sitter (and other decoration providers actually) is expected to be done through the namespace APIs.

**Comment by theHamsta** [comment]
>gathering highlights informations from tree-sitter (and other decoration providers actually) is expected to be done through the namespace APIs.

which would be a more proper solution than the current one. But playground is for playing. Should be good enough in the meantime. Closing?

**Comment by vigoux** [comment]
Following https://github.com/nvim-treesitter/nvim-treesitter/issues/519#issuecomment-712533798, I think this is fair to close.
