### ISSUE TITLE
Code syntax highlight dissappear after enable TSBufEnable highlight

### ISSUE THREAD

**Issue by ynhhoJ** [nvim-treesitter/nvim-treesitter#5207]
### Describe the bug

Singe 5 august my syntax highlight is broken, it's just grey text, and i do not know how to fix that.

### To Reproduce

1. `init.lua`
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

vim.g.mapleader = " "

require("lazy").setup({
  {
    "nvim-treesitter/nvim-treesitter",
    cmd = { "TSInstall", "TSBufEnable", "TSBufDisable", "TSModuleInfo" },
    build = ":TSUpdate",
    config = function()
      require('nvim-treesitter.configs').setup({
        ensure_installed = { "javascript" },
        highlight = {
          enable = true,
        },
        additional_vim_regex_highlighting = false,
      })
    end,
  }
})
```
2. `rm -rf ~/.local/share/nvim`
3. Create `index.js` file with code:
```js
console.log('test');
```
5.  Run `nvim index.js`
6. Wait for installing all dependencies
7. Close nvim (`:q`)
8. Open again `index.js`
9. Open file and enable syntax usign `:TSBufEnable highlight`
Default `nvim` syntax highlight:
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/22500212/f5b7f310-f4de-41df-a849-0d3c16c74315)
`nvim-treesitter` with syntax highlight enabled:
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/22500212/8547dd24-d56c-4596-8126-bd7e21d127bd)

### Expected behavior

Code syntax should have some different colors, not just gray

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v18.16.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230728 (Red Hat 13.2.1-1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.4.7-200.fc38.x86_64",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Thu Jul 27 20:01:18 UTC 2023"
} ~

Parser/Features         H L F I J
  - javascript          ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev+766-gef44e5972
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```

### Additional context

1. `:echo &filetype` -> `javascript`
2. `TSUpdate` -> `All parsers are up-to-date!` 
3. I experience this bug with all types of modules (`html`, `javascript`, `typescript`)
4. `:write | edit | TSBufEnable highlight` - does not help
5. Tried to use `TSEnable highlight` instead of `TSBufEnable highlight` , but text from default `nvim` syntax will go to completely grey text
6. I tried to use different versions of `nvim-treesitter` / `nvim` from 1 august and older, but it seems something got broken, and i'm not sure if this is a `nvim-treesitter` problem
7. I tried to use default console from Fedora,
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/22500212/d920d13e-69ff-4251-b0b2-1b1a3840c59f)

**Comment by lucario387** [comment]
I cannot reproduce this issue, so Im not sure what's the cause here

**Comment by stoerdebegga** [comment]
Hello all:

I can confirm the issue as I face it since Aug 5 as well. Like the original reporter I'm on Fedora 38, tree-sitter as well as neovim have exactly the same versions.

Here's a screenshot of a random python file.

![py-broken-syntax-highlighting](https://github.com/nvim-treesitter/nvim-treesitter/assets/141717386/2dea0415-25f3-4d0e-b332-3edf2210d87c)

As I originally suspected the colorscheme I was disabling this, but this was to no avail.

**Comment by clason** [comment]
> something got broken, and i'm not sure if this is a nvim-treesitter problem

I'm fairly sure it's not an nvim-treesitter problem. How are you installing Neovim?

**Comment by stoerdebegga** [comment]
I'm using the same copr repository.

**Comment by clason** [comment]
Do not use distro-provided nightlies. We can't provide support for that. Either stick to stable builds, or build from source (or use the nightly appimages) if you need to test something.

**Comment by stoerdebegga** [comment]
Confirmed - the problem seems to be in the version that is provided by the nightly copr. I switched back to the Fedora 38 stock neovim, and can't observe the issue anymore.

**Comment by ynhhoJ** [comment]
But if problem exists in nightly version, how it can be fixed later, if at current moment no one faced it from dev team?

**Comment by clason** [comment]
The problem does not exist in the nightly _version_ of Neovim (which works just fine, e.g., for me); it's the nightly _build_ of Fedora. We are not responsible for those.

**Comment by ynhhoJ** [comment]
@clason , 
> it's the nightly build of Fedora

Thanks, now it remains to understand what version of fedora I have
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/22500212/1b0d1a7b-f0db-4240-9a7d-510540a96b51)

Sorry for offtop, @stoerdebegga , how did u switched to `Fedora 38 stock`?

**Comment by clason** [comment]
Remove the COPR and reinstall `nvim` (version should be 0.9.1, which is the latest stable).

The issue here is that that COPR also builds with tree-sitter master, which is _not_ a good idea (in fact, tree-sitter master is breaking currently).

**Comment by stoerdebegga** [comment]
@ynhhoJ you have added the following copr repository: https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/

This is the nightly build for Fedora which is apparently broken at the moment - not the build itself, but something is fishy in the build.

Nonetheless, you can switch back to the stock version like the following.

```bash
sudo dnf remove neovim
```


**Temporary Solution**

If you just want to temporarily switch to the stock version, the easiest way is to disable the COPR repo by setting the enabled flag to *0*.


```bash
sudo vi /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:agriffis:neovim-nightly.repo
sudo dnf autoremove && sudo dnf clean all
sudo dnf install neovim
```

**Permanent Solution**

```bash
sudo rm -f /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:agriffis:neovim-nightly.repo
sudo rpm -e gpg-pubkey-453d6413-5c7aa779
sudo dnf autoremove && sudo dnf clean all
sudo dnf install neovim
```

**Comment by clason** [comment]
> This is the nightly build for Fedora which is apparently broken at the moment - not the build itself, but something is fishy in the build.

No, it's the build. I looked at the packages, and I wouldn't touch this with a ten foot pole. Do Not Use.

**Comment by stoerdebegga** [comment]
Already switched back to stock - the sole purpose of the COPR was right in the beginning of neovim as the stock version was way behind release.

**Comment by clason** [comment]
Yes, there was a time (before the 0.5 release) where we recommended people to use nightly; that time has long passed. These days, nobody should be using nightlies unless they want to help development (and know what they're doing in case of inevitable problems), in which case distro builds are mostly useless.

**Comment by stoerdebegga** [comment]
Yeah, I guess that was just lazy me and so far it worked out. Nonetheless, apologies for the fuss and thanks for the help.

**Comment by clason** [comment]
No worries. I just want to be very clear about this for the benefit of people reading along.

**Comment by ynhhoJ** [comment]
Thank you for all help!

Switched to 0.9.1 version and syntax highlight is resolved.

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/22500212/c05e636b-f812-41ad-91bf-a15bf57554ea)
