### ISSUE TITLE
Certain files causing excessive memory usage, stalls and crashes.

### ISSUE THREAD

**Issue by VictorSohier** [nvim-treesitter/nvim-treesitter#5214]
### Describe the bug

Whenever I load a specific file with a large C macro (I'm messing around with generic collections), and I open the file either by the editor or via telescope preview, neovim either ceases, or at one point, just segfaults. Another symptom is that there seems to be excessive memory usage upon opening this file (16 GiB, the file is about 13KiB).

### To Reproduce

Open [list.h](https://github.com/VictorSohier/ccollections/blob/master/include/list.h) in neovim with [my config](https://github.com/VictorSohier/nvim). I have isolated this to nvim-treesitter already.

I just post my code as an example that I know causes the issue.

### Expected behavior

The ability to actually edit filles with huge macros without such a crash.

### Output of `:checkhealth nvim-treesitter`

```markdown
Uh, I can't really given that neovim just ceases to function when entering the file.
```

### Output of `nvim --version`

```text
Neovim version: 0.9.1
```

### Additional context

Operating system: Cachyos, Linux version 6.1.8-1-cachyos-cacule
Installation: cachyos-extra-v3/neovim via yay
Terminal:
- Kitty 0.29.2 (xterm-kitty)
- xfce4-terminal 1.0.4 (xterm-256color)

**Comment by clason** [comment]
This is due to the `preproc` self insertions. Just copy the `injections.scm` query to your config directory and remove it.
