### ISSUE TITLE
Integrating with Polyglot

### ISSUE THREAD

**Issue by nomasprime** [nvim-treesitter/nvim-treesitter#523]
Trying to get my head around this…

My initial approach was to disable highlight in Treesitter but it's definitely better, so I decided to disable duplicated "packs" in Polyglot.

The only negative I've noticed so far is that ftdetect isn't so good, eg, zsh files aren't getting picked up now.

Is this something Treesitter should be able to do or do I need to copy over ftdetect folders from Polyglot?

Any other recommendations?

**Comment by undu** [comment]
I use both at the same time and didn't have to disable anything to get tree-sitter to highlight code whenever it's available and fall back to whatever polyglot's highlighting. What problems were you having that made you start doing that?

Treesitter uses the ftplugins to decide which highlighter to load, so messing with ftdetects will mean treesitter won't work as expected.

**Comment by stsewd** [comment]
As undu said, you don't need to disable polyglot, treesitter will disable the regex based hightlight only, the rest of features should keep working.

**Comment by sQVe** [comment]
This could be relevant for `vim-polyglot` users that work in `javascript`: https://github.com/nvim-treesitter/nvim-treesitter/issues/641

**Comment by stsewd** [comment]
I put a faq section in the wiki with this https://github.com/nvim-treesitter/nvim-treesitter/wiki/FAQ#polyglot-vs-nvim-treesitter

**Comment by nomasprime** [comment]
Thanks @stsewd, very useful.
