### ISSUE TITLE
[C] #define macro expressions (and inline comments following a #define) are highlighted as variables

### ISSUE THREAD

**Issue by leitdeux** [nvim-treesitter/nvim-treesitter#5237]
### Describe the highlighting problem

It seems that up until around commit ad3805f5c34b51890c3d3c37c2f0c86269598a32 that C macro highlights (i.e.`#define` statements) were being highlighted as expected, but in the latest version of treesitter (when trying commit 800b2f388b0f880be8a2fcd29494f7459af30a21), any text following a `#define` is highlighted as  `variable` by TS, instead of its expected token type (e.g. `number`, etc.). In addition, comments are also highlighted as `variable`.

### Example snippet that causes the problem

Snippet from an example C header file:

`foo.h`:
``` c
#define FOO 123
#define BAR (FOO + 0xface) // a comment
```

### Tree-sitter parsing result

`:TSPlaygroundToggle` output when using installing `nvim-treesitter` up to an earlier commit ad3805f5c34b51890c3d3c37c2f0c86269598a32, where this issue is not present:
```
preproc_def [0, 0] - [1, 0] c
  "#define" [0, 0] - [0, 7] c
  name: identifier [0, 8] - [0, 11] c
  value: preproc_arg [0, 12] - [0, 15] c
    ERROR [0, 12] - [0, 15] c
      number_literal [0, 12] - [0, 15] c
preproc_def [1, 0] - [2, 0] c
  "#define" [1, 0] - [1, 7] c
  name: identifier [1, 8] - [1, 11] c
  value: preproc_arg [1, 12] - [1, 27] c
    expression_statement [1, 12] - [1, 26] c
      parenthesized_expression [1, 12] - [1, 26] c
        "(" [1, 12] - [1, 13] c
        binary_expression [1, 13] - [1, 25] c
          left: identifier [1, 13] - [1, 16] c
          operator: "+" [1, 17] - [1, 18] c
          right: number_literal [1, 19] - [1, 25] c
        ")" [1, 25] - [1, 26] c
      ";" [1, 26] - [1, 26] c
  comment [1, 27] - [1, 39] c
    "text" [1, 27] - [1, 28] comment
      "/" [1, 27] - [1, 28] comment
    "text" [1, 28] - [1, 29] comment
      "/" [1, 28] - [1, 29] comment
    "text" [1, 30] - [1, 31] comment
    "text" [1, 32] - [1, 39] comment
```
Output from latest version (800b2f388b0f880be8a2fcd29494f7459af30a21):
```
preproc_def [0, 0] - [1, 0] c
  "#define" [0, 0] - [0, 7] c
  name: identifier [0, 8] - [0, 11] c
  value: preproc_arg [0, 12] - [0, 15] c
preproc_def [1, 0] - [2, 0] c
  "#define" [1, 0] - [1, 7] c
  name: identifier [1, 8] - [1, 11] c
  value: preproc_arg [1, 12] - [1, 39] c
```

### Example screenshot

colorscheme: nightfox [(nightfox.nvim)](https://github.com/EdenEast/nightfox.nvim)

nightfox.nvim configuration:
``` lua
-- setup theme
local nightfox = require("nightfox")

nightfox.setup({
  options = {
    transparent = true,
    styles = {
      comments = "italic"
    }
  }
})

vim.cmd("colorscheme nightfox")
```

Screenshots from latest commit 800b2f388b0f880be8a2fcd29494f7459af30a21:

![スクリーンショット 2023-08-13 10 37 06](https://github.com/nvim-treesitter/nvim-treesitter/assets/16680740/6067cd9c-6aa3-400b-8a97-1d809d16d2ad)

![スクリーンショット 2023-08-13 10 37 25](https://github.com/nvim-treesitter/nvim-treesitter/assets/16680740/0df93c94-ea97-4fa2-b0de-77624732de7a)

### Expected behavior

Tokens in expressions following a `#define` should be parsed as their expected data type, where `number`, `comment`, etc.

Screenshots using nvim-treesitter from an earlier commit with the expected highlights, ad3805f5c34b51890c3d3c37c2f0c86269598a32:

![スクリーンショット 2023-08-13 10 41 33](https://github.com/nvim-treesitter/nvim-treesitter/assets/16680740/c5133f77-baae-4ad6-82ad-9b0239757cc4)

![スクリーンショット 2023-08-13 10 41 51](https://github.com/nvim-treesitter/nvim-treesitter/assets/16680740/805a6dc9-0790-4910-8fba-3898f04d41d9)

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v18.13.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "22.6.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:56 PDT 2023; root:xnu-8796.141.3~6/RELEASE_X86_64"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - comment             ✓ . . . .
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ .

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev-2175+g165c4c9e5-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3
```

### Additional context

The issue seems to arise when I install nvim-treesitter from the latest commit (800b2f388b0f880be8a2fcd29494f7459af30a21). Also, I have not made any changes to my colorscheme for several months, so I don't believe this issue is related to a change I made in my theme config specifically.

I hope I gave enough details here to help identify any issues. Thanks for all that you do!

**Comment by lucario387** [comment]
We removed the c injection for the specific case of one-line `#define` for now, due to performance issue. It may or may not be re-enabled in future revisions
