### ISSUE TITLE
Install the parsers on `data` by default

### ISSUE THREAD

**Issue by Zeioth** [nvim-treesitter/nvim-treesitter#5251]
**Is your feature request related to a problem? Please describe.**
Currently, treesitter install `:TSInstall` parsers on the `nvim-treesitter` plugin directory. 

This has two problems:
* Deleting the plugin will delete the parsers, too, meaning reinstalling treesitter trigger a big deal of downloads when `auto_install` is enabled every time you do.
* This make impossible for distros to pre-pack treesitter parsers. (Again, to avoid downloading an excessive amount of parsers on the first startup, as they are verbose, and often display warnings).

**Describe the solution you'd like**
Install the parsers on their own directory, under neovim `data` dir.

**Comment by clason** [comment]
That's already been changed on `main`; you can also customize the directory.

**Comment by Zeioth** [comment]
@clason could you provide a bit more info of where should I look exactly please?

**Comment by clason** [comment]
You should wait until nvim-treesitter 1.0 is released; see https://github.com/nvim-treesitter/nvim-treesitter/issues/4767

**Comment by Zeioth** [comment]
For anyone finding this on a search engine, the option is:

```lua
parser_install_dir = vim.fn.stdpath "data" .. "/treesitter/parsers" ,
```

**Comment by Zeioth** [comment]
@clason I've been testing with that setup:

```lua
vim.opt.runtimepath:append(vim.fn.stdpath "data" .. "/treesitter/parser") -- add treesitter parsers to the runtime
parser_install_dir = vim.fn.stdpath "data" .. "/treesitter", -- Also adding this to the runtime in ../base/1-options.lua
```

* Then I've done `TSInstall all` and I've opened 20+ different language files.

## Result
While all other languages seem to work fine, the `C` treesitter parser throw this error.

![screenshot_2023-08-16_20-11-21_466455393](https://github.com/nvim-treesitter/nvim-treesitter/assets/3357792/dfa5c884-fc19-47bb-a722-21af2a074ed9)

![screenshot_2023-08-16_20-13-03_160849883](https://github.com/nvim-treesitter/nvim-treesitter/assets/3357792/5810264c-a311-452f-88c5-2eeafc8c1d15)

Which fixes if I let the parsers on their default location, so probably that particular parser don't like to be moved to a different location. Just reporting, in case this may be useful for you.

**Comment by clason** [comment]
No, that just means it's not respecting the runtime path precedence of your queries (so queries for a different parser version are pulled in, e.g.the one bundled with Neovim).

There's a reason the install directory is what it is...
