### ISSUE TITLE
Python extra indent are inserted when using a string literal with unclosed parenthesis

### ISSUE THREAD

**Issue by ValouBambou** [nvim-treesitter/nvim-treesitter#5254]
### Describe the bug

Hi, I noticed something strange with indentations in python only.  If I create a newline after a line like this one.

```python
print("hello(")
    # the cursor pop 1 indent too far
```

### To Reproduce

1. Write a statement with a literal string with unclosed parenthesis or bracket 
2.  Go to the next line.
3. See the extra indent

### Expected behavior

I expected zero indent when creating a newline. Like this:

```python
print("hello(")
# the cursor should pop here
```

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.5.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.4.10-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Fri, 11 Aug 2023 11:03:36 +0000"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by lucario387** [comment]
How did you set it up? With `indent = { enable = true }`, I cannot reproduce this.

Most likely you are using vim's python indent, which relies on syntax, which is disabled when treesitter highlight is enabled

For workaround, please either enable treesitter indent through adding `indent = { enable = true }` in your setup func, or have `highlight = { additional_vim_regex_highlighting = true }`

**Comment by ValouBambou** [comment]
I use `indent = { disable = {"python"} }`, maybe it's the source of issue ? Ok, after a quick test, it was effectively the issue. Thanks a lot @lucario387 !
