### ISSUE TITLE
A strange bug with JS functions and innerHTML

### ISSUE THREAD

**Issue by nikola-vukicevic** [nvim-treesitter/nvim-treesitter#5257]
### Describe the bug

Lately, I'm experiencing a strange bug:

![Aug16::084154](https://github.com/nvim-treesitter/nvim-treesitter/assets/39658013/cceafca9-34d3-4f2e-ab99-08b6fa12e092)
![Aug16::084204](https://github.com/nvim-treesitter/nvim-treesitter/assets/39658013/91c3ebcb-9c3d-4ed4-8175-a7bf363d69d2)

If a JS function calls the "innerHTML" property, highlighting becomes .... "strange".

It doesn't matter if the object being referenced is passed as an argument, or called directly (as can be seen in the pics).

Can we shed some light on this subject (I don't see the issue as being related with those issues from the Troubleshooting section, but maybe I'm missing something)?

### To Reproduce

Just try the code seen in the pics:

```javascript
function test() {
	let p = document.getElementById("x")
	p.innerHTML = "???"
}
```

### Expected behavior

Consistent highlighting that doesn't "spill" all over the place.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.5.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.4.10-artix1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Fri, 11 Aug 2023 21:36:14 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - c_sharp             ✓ ✓ ✓ . ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - glimmer             ✓ ✓ ✓ ✓ .
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - pug                 ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - sql                 ✓ . . ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by amaanq** [comment]
can't reproduce, a minimal config would be nice

**Comment by clason** [comment]
Also show us `:InspectTree` for both variants.

**Comment by lucario387** [comment]
Well, `innerHTML` not having any highlights when it's a string is wrong, PR incoming.

We were blessed with automatically `include-chilren` that most queries were not fully narrowed down

**Comment by nikola-vukicevic** [comment]
> Broken highlighting here should be related to broken injections, which from the image, the response, and the reproduce code, it suggested that innerHTML was incorrectly injected.
> 
> Can you try update nvim-treesitter to latest, re install the parser, and try again?

Seems to be ok now.

**Comment by lucario387** [comment]
Please create a bug report next time with minimal init i.e. nvim --clean with only nvim-treesitter installed, not a bunch of plugins with it (like how you describe your 1k loc config)

We aren't here to debug your config, only here to fix nvim-treesitter's issues

**Comment by nikola-vukicevic** [comment]
> We aren't here to debug your config, only here to fix nvim-treesitter's issues

Duly noted. ;)

But, you didn't debug my config (nor do I expect you or anyone else to do so).

As far as I can tell, the issue was _entirely_ related to Treesitter (and not _in any way_ related to my config).

You fixed the issue, and I thank you for your effort (again).
