### ISSUE TITLE
Missing fields: Modules

### ISSUE THREAD

**Issue by 9mm** [nvim-treesitter/nvim-treesitter#5297]
### Describe the bug

https://github.com/LuaLS/lua-language-server/discussions/2271

> sumneko: It looks like these fields were not marked as optional when the function was defined. Until they are fixed, you can disable this diagnostic using diagnostics.disable.

Something was added to lua_ls recently that causes lots of popular plugins to get 'missing fields' (cmp, treesitter, surround, etc). This is the one I get for tree-sitter: 

<img width="732" alt="image" src="https://github.com/tree-sitter/tree-sitter/assets/1386207/614cee2a-8081-4fb3-aeb7-57d387ccec5f">

### To Reproduce

1. Paste in a config that comes from nvim-treesitter docs
2. Observe linter errors from lua_ls

### Expected behavior

Technically... it's working fine normally, but given that most Neovim distributions and suggestions and everything suggest people to use lua_ls or lsps in general, it seems like a good idea to mark 'modules' as optional if its really optional

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.5.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 14.0.3 (clang-1403.0.22.14.1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "22.6.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - clojure             ✓ ✓ ✓ . ✓
  - comment             ✓ . . . .
  - css                 ✓ . ✓ ✓ ✓
  - csv                 ✓ . . . .
  - diff                ✓ . . . .
  - dockerfile          ✓ . . . ✓
  - embedded_template   ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . .
  - go                  ✓ ✓ ✓ ✓ ✓
  - graphql             ✓ . . ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - ini                 ✓ . ✓ . .
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - r                   ✓ ✓ . ✓ ✓
  - regex               ✓ . . . .
  - ruby                ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - sql                 ✓ . . ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - vue                 ✓ . ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```
```


### Output of `nvim --version`

```text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.1/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
So why are you opening an issue here? This is just an overzealous LSP diagnostic output, not an actual error.

**Comment by 9mm** [comment]
> So why are you opening an issue here? This is just an overzealous LSP diagnostic output, not an actual error.

I already answered why:

> Expected behavior
> Technically... it's working fine normally, but given that most Neovim distributions and suggestions and everything suggest people to use lua_ls or lsps in general, it seems like a good idea to mark 'modules' as optional if its really optional

**Comment by clason** [comment]
I know; it's still a bit annoying to have a language server decide to report a new type of warning and have it labeled a "bug". If it's "working fine", it's not a bug!

**Comment by 9mm** [comment]
Sure I agree it's not a bug, but it doesn't really fit other categories. It's not a highlighting error, and it's not a feature request.

FWIW If this were any other plugin or language I could see not really dealing with it at all, but treesitter is pretty much the #1 neovim plugin I suspect, it's a big reason why people use it to begin with, and also lua_ls is in pretty much every starting distribution as far as I know (kickstart, lazy, etc).

I just opened an issue because at the time I noticed it in my own config, I already starting seeing a number of other issues at the same time confused what was wrong. It might be worth adding for that fact alone as new neovim users using treesitter will now see very large errors, also considering diagnostics are on by default. I realize that has nothing to do with you though, and it's not a bug, just an unfortunate circumstance.

**Comment by clason** [comment]
Yeah, sorry for the curt response, but this is putting too much pressure on this project. We need to focus on our core functionality: installing parsers and queries for >200 languages. I recommend just disabling this diagnostic, which is way too strict and noisy to be on by default (unless you're developing your own plugin and want strict typing).

Remember that this plugin is still (highly) experimental; type annotation polish will come after code stability.

**Comment by 9mm** [comment]
No problem, keep on truckin 🚚 Thanks for your effort
