### ISSUE TITLE
Svelte syntax highlighting not working

### ISSUE THREAD

**Issue by ehllie** [nvim-treesitter/nvim-treesitter#5314]
### Describe the bug

I've noticed svelte files do not get any syntax highlighting at all on my system. Interestingly enough, the telescope file preview window correctly highlights the code in the file, it's just when I open the file in a new buffer that the highlighting does not work.

<details>
<summary> Minimal example screenshot </summary>
<img width="1152" alt="Minimal example" src="https://github.com/nvim-treesitter/nvim-treesitter/assets/20847625/5b20f7e7-34b1-4765-b559-565f4864c17c">
</details>

<details>
<summary> Telescope preview working in my config </summary>
<img width="1217" alt="Telescope preview" src="https://github.com/nvim-treesitter/nvim-treesitter/assets/20847625/9dcbd0dc-7d08-41ab-a953-2bf659aa39a0">
</details>

<details>
<summary> Buffer not getting highlighted in my config </summary>
<img width="1217" alt="Personal config" src="https://github.com/nvim-treesitter/nvim-treesitter/assets/20847625/b3b8ca9e-486c-4868-b9d1-5662b1078833">
</details>

### To Reproduce

Using the following config:
<details>
<summary> init.lua </summary>

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = { "svelte", "typescript", "scss" },
    highlight = {
      enable = true,
    },
  },
})
```
</details>

Open a svelte file like:
<details>
<summary> Foo.svelte </summary>

```svelte
<script>
  let count = 0;
</script>

<button class="foo" on:click={() => count++}>
  clicks: {count}
</button>

<style>
  .foo {
    color: red
  }
</style>

```

</details>

### Expected behavior

The svelte file I open gets its syntax properly highlighted.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v18.17.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: gcc (GCC) 12.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "22.5.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000"
} ~

Parser/Features         H L F I J
  - javascript          ✓ ✓ ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ .
  - svelte              ✓ . ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/ajzx128q8239lnnkwscpdjm0xcqkb5p3-neovim-unwrapped-0.9.1/share/nvim
"

Run :checkhealth for more info
```

### Additional context

I'm using macOS Ventura 13.4.1 on an aarch64 M1 processor. I have neovim installed with nix.

**Comment by ehllie** [comment]
Apologies, I seem to have created a wrong type of an issue. I'll go through the steps in the "Highlighting Issue" template and update this message

**Comment by lucario387** [comment]
For all the relevant nodes `script`, `style`, and interpolations, the injected languages for the example code is `javascript`, `css`, and `javascript` respectively, while you installed typescript and scss (which isn't js and css).

Also, are you sure the highlight shown by telescope is provided by treesitter, and not regex-based highlighting? From the documentations of telescope:

```vimdoc
          - treesitter:       Determines whether the previewer performs treesitter
                              highlighting, which falls back to regex-based highlighting.
                              `true`: treesitter highlighting for all available filetypes
                              `false`: regex-based highlighting for all filetypes
                              `table`: may contain the following keys:
                                  - enable boolean|table: if boolean, enable ts
                                                          highlighting for all supported
                                                          filetypes.
                                                          if table, ts highlighting is only
                                                            enabled for given filetypes.
                                  - disable table: list of filetypes for which ts highlighting
                                                   is not used if `enable = true`.
                              Default: true
```

**Comment by ehllie** [comment]
I have included the colour scheme I use in the example config, as well as the results of running `TSPlaygroundToggle` and `TSHighlightCaptureUnderCursor`

<details>
<summary> Parsed syntax tree </summary>
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/20847625/a9942f1b-f531-454c-9d43-1c94965faf53)
</details>

<details>
<summary> Updated init.lua </summary>

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)
require("lazy").setup({
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "svelte",
	"typescript",
	"scss", 
	"javascript", 
	"css"
      },
      highlight = {
        enable = true,
      },
      playground = {
        enable = true,
      },
    },
    dependencies = {
      "nvim-treesitter/playground",
    },
  },
  {
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
    config = function()
      require("catppuccin").setup({
        flavour = "frappe",
	integrations = {
	  treesitter = true,
	},
      })
      vim.cmd("colorscheme catppuccin")
    end,
  }
})
```
</details>

**Comment by lucario387** [comment]
Both catppuccin/nvim and playground are not necessary, use :h InspectTree and :h Inspect for getting the syntax tree and the captures at the cursor position respectively

**Comment by ehllie** [comment]
This also happens on the latest neovim commit that builds on my system:
```
NVIM v0.10.0-dev-d321deb
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/1jbl285mcx5ld7w75qzj7751d24wgc0m-neovim-unwrapped-d321deb/share/nvim
"

Run :checkhealth for more info
```

**Comment by ehllie** [comment]
> Both catppuccin/nvim and playground are not necessary, use :h InspectTree and :h Inspect for getting the syntax tree and the captures at the cursor position respectively

<details>
<summary> Result of InspectTree </summary>

```
(script_element) ; [1:1 - 3:9]
 (start_tag) ; [1:1 - 8]
  (tag_name) ; [1:2 - 7]
 (raw_text) ; [2:3 - 3:0]
  (lexical_declaration) ; [2:3 - 16]
   (variable_declarator) ; [2:7 - 15]
    name: (identifier) ; [2:7 - 11]
    value: (number) ; [2:15 - 15]
 (end_tag) ; [3:1 - 9]
  (tag_name) ; [3:3 - 8]
(element) ; [5:1 - 7:9]
 (start_tag) ; [5:1 - 45]
  (tag_name) ; [5:2 - 7]
  (attribute) ; [5:9 - 19]
   (attribute_name) ; [5:9 - 13]
   (quoted_attribute_value) ; [5:15 - 19]
    (attribute_value) ; [5:16 - 18]
  (attribute) ; [5:21 - 44]
   (attribute_name) ; [5:21 - 28]
   (expr_attribute_value) ; [5:30 - 44]
    (expression) ; [5:30 - 44]
     (raw_text_expr) ; [5:31 - 43]
      (expression_statement) ; [5:31 - 43]
       (arrow_function) ; [5:31 - 43]
        parameters: (formal_parameters) ; [5:31 - 32]
        body: (update_expression) ; [5:37 - 43]
         argument: (identifier) ; [5:37 - 41]
 (text) ; [6:3 - 9]
 (expression) ; [6:11 - 17]
  (raw_text_expr) ; [6:12 - 16]
   (expression_statement) ; [6:12 - 16]
    (identifier) ; [6:12 - 16]
 (end_tag) ; [7:1 - 9]
  (tag_name) ; [7:3 - 8]
(style_element) ; [9:1 - 13:8]
 (start_tag) ; [9:1 - 7]
  (tag_name) ; [9:2 - 6]
 (raw_text) ; [10:3 - 13:0]
  (rule_set) ; [10:3 - 12:3]
   (selectors) ; [10:3 - 6]
    (class_selector) ; [10:3 - 6]
     (class_name) ; [10:4 - 6]
   (block) ; [10:8 - 12:3]
    (declaration) ; [11:5 - 15]
     (property_name) ; [11:5 - 9]
     (plain_value) ; [11:12 - 14]
 (end_tag) ; [13:1 - 8]
  (tag_name) ; [13:3 - 7]
```
</details>

Both `:Inspect` and `:TSHighlightCaptureUnderCursor` report `No items found at position ...` and `No highlight groups found` respectively

**Comment by ehllie** [comment]
> For all the relevant nodes `script`, `style`, and interpolations, the injected languages for the example code is `javascript`, `css`, and `javascript` respectively, while you installed typescript and scss (which aren't js and css).
> 
> Also, are you sure the highlight shown by telescope is provided by treesitter, and not regex-based highlighting? From the documentations of telescope:
> 
> ```
>           - treesitter:       Determines whether the previewer performs treesitter
>                               highlighting, which falls back to regex-based highlighting.
>                               `true`: treesitter highlighting for all available filetypes
>                               `false`: regex-based highlighting for all filetypes
>                               `table`: may contain the following keys:
>                                   - enable boolean|table: if boolean, enable ts
>                                                           highlighting for all supported
>                                                           filetypes.
>                                                           if table, ts highlighting is only
>                                                             enabled for given filetypes.
>                                   - disable table: list of filetypes for which ts highlighting
>                                                    is not used if `enable = true`.
>                               Default: true
> ```

Yes, telescope is using treesitter highlighting in the preview. I have not changed that setting, and the default is set to true. It also has the same looking preview when i manually set it to true

**Comment by ehllie** [comment]
This issue seems to also be affecting `.prisma` files. The syntax tree is correctly generated, since the `:InspectTree` shows the parsed tree, but that doesn't translate into any highlight groups being applied in the buffer

**Comment by lucario387** [comment]
then something is wrong with the highlight then ...

I cannot seem to reproduce it, with both minimal config you've provided

**Comment by ehllie** [comment]
What system are you running on? Maybe this is only affecting `aarch64-darwin` systems?

**Comment by lucario387** [comment]
Maybe yes, I'm running it on both linux and windows and cannot reproduce it

**Comment by ehllie** [comment]
Running `TSBufEnable highlight` fixed it. Shouldn't setting `highlight = { enable = true}` have turned it on by default though?

**Comment by ehllie** [comment]
Turns out it was a layer 8 issue. Lazy was not applying my options because the setup function is inside `nvim-treesitter.configs` rather than `nvim-treesitter` directly. https://github.com/ehllie/dotfiles/commit/b194aa946181248c7beb8aa79460bc2fa242b7c0
