### ISSUE TITLE
nvim_treesitter#statusline() not work as expected for java

### ISSUE THREAD

**Issue by yimingwangdell** [nvim-treesitter/nvim-treesitter#5338]
### Describe the bug

class A extends B implements C -> @ Override

it only show "@ Override" as method name for java.

config:

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/121928908/48190297-8b79-4ec3-8c53-488f3cadb9a1)

### To Reproduce

1. use lualine with below config:
2. open java file with @ Override method.

return {
	{
		-- "theniceboy/eleline.vim",
		"nvim-lualine/lualine.nvim",
		-- You can optionally lazy-load heirline on UiEnter
		-- to make sure all required plugins and colorschemes are loaded before setup
		-- event = "UiEnter",
		config = function()
			local treesitter = require('nvim-treesitter')
			local function treelocation()
				return treesitter.statusline({
					indicator_size = 1000,
					type_patterns = { 'class', 'function', 'method' },
					transform_fn = function(line, _node) return line:gsub('%s*[%[%(%{]*%s*$', '') end,
					separator = ' -> ',
					allow_duplicates = false
				})
			end
			require('lualine').setup {
				options = {
					icons_enabled = true,
					theme = 'auto',
					component_separators = { left = '', right = '' },
					section_separators = { left = '', right = '' },
					disabled_filetypes = {
						statusline = {},
						winbar = {},
					},
					ignore_focus = {},
					always_divide_middle = true,
					globalstatus = true,
					refresh = {
						statusline = 1000,
						tabline = 1000,
						winbar = 1000,
					}
				},
				sections = {
					lualine_a = { { 'filename', path = 3 } },
					lualine_b = { 'branch', 'diff', 'diagnostics' },
					lualine_c = {},
					lualine_x = { "progress" },
					lualine_y = { 'filesize', 'fileformat', 'filetype' },
					lualine_z = { 'location' }
				},
				inactive_sections = {
					lualine_a = {},
					lualine_b = {},
					lualine_c = { 'filename' },
					lualine_x = { 'location' },
					lualine_y = {},
					lualine_z = {}
				},
				tabline = {
					lualine_c = { { treelocation } }
				},
				winbar = {},
				inactive_winbar = {},
				extensions = {}
			}
		end
	},
}

### Expected behavior

show true method name.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v18.12.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.15.114-2-MANJARO",
  sysname = "Linux",
  version = "#1 SMP PREEMPT Sun Jun 4 10:32:43 UTC 2023"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - dart                ✓ ✓ ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - prisma              ✓ . . . .
  - python              x ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev-835+gdd09630a2
```

**Comment by clason** [comment]
use tree-sitter-context; that function is deprecated and will be removed in 1.0

**Comment by yimingwangdell** [comment]
@clason any document about how to config lualine with this feature of treesitter?

**Comment by clason** [comment]
No, you'd have to roll your own.
