### ISSUE TITLE
rainbow-delimiters.nvim produces bug when working with 'svelte' parser

### ISSUE THREAD

**Issue by Eren-Nevin** [nvim-treesitter/nvim-treesitter#5354]
### Describe the bug

When working with svelte files that have html, Treesitter throws invalid node type at position x.
For example:

<script lang="ts">
	import TabSelector from '$lib/components/TabSelector.svelte';
	import AppletTab from '$lib/components/tabs/AppletTab.svelte';
	import ProxyTab from '$lib/components/tabs/ProxyTab.svelte';

	let activeTab = 'Applet-Tab';
	let appletTabShowOnlyMyApplets = false;
	let proxyTabShowOnlyRunning = false;

</script>

<TabSelector bind:activeTab />
<div class="w-auto h-screen flex flex-col items-center">
	{#if activeTab === 'Applet-Tab'}
		<AppletTab bind:onlyShowMyApplets={appletTabShowOnlyMyApplets} />
	{:else if activeTab === 'Data'}
		
	{:else}
		<ProxyTab bind:onlyShowRunning={proxyTabShowOnlyRunning} />
	{/if}
</div>

* The syntax errors are not important. Treesitter throws error on file opening and on any cursor movement 

I needed to disable rainbow config as described by this answer on reddit:
https://www.reddit.com/r/neovim/comments/xqogsu/turning_off_treesitter_and_lsp_for_specific_files/

### To Reproduce

Create a new svelte project
Create a myFile.svelte file that has both script and html part (like the file above)
open the .svelte file, it throws invalid node type at position x. 
Any cursor movement in the file re throws the same error.

The suggested fix that worked for me:
require 'nvim-treesitter.configs'.setup {
    ...
    -- NOTE: Fixes svelte problem
    rainbow = {
        enable = false,
    },
   ...
}

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.5.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 14.0.0 (clang-1400.0.29.202)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "22.3.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - dart                ✓ ✓ ✓ ✓ ✓
  - diff                ✓ . . . .
  - dockerfile          ✓ . . . ✓
  - fish                ✓ ✓ ✓ ✓ ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . .
  - go                  ✓ ✓ ✓ ✓ ✓
  - groovy              ✓ . . . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - kotlin              ✓ ✓ ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - norg                ✓ . ✓ . ✓
  - norg_meta           ✓ . . ✓ .
  - php                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - svelte              ✓ . ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - vue                 ✓ . ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.9.1/share/nvim"
```

**Comment by lucario387** [comment]
It's not related to nvim-treesitter, but rather `rainbow-delimiters.nvim` or `nvim-ts-rainbow2`. Please report the issue to those plugins' issues list instead
