### ISSUE TITLE
Weird highlighting bug for Lua & C++ files

### ISSUE THREAD

**Issue by Wmbat** [nvim-treesitter/nvim-treesitter#5364]
### Describe the bug

The syntax highlighting seems to fail after a small delay upon opening a file. I've recorded a small video of the problem. The correct colours appear at first, but they then dissapear.

The problem happens for Lua & C++ files, It doesn't happen for Clojure, Golang, toml or python

https://github.com/nvim-treesitter/nvim-treesitter/assets/25081455/43c5520d-0f89-4c26-b4fc-5a52e7b5437b

Note: Running :TSBufToggle highlight works correctly for Clojure, Golang, toml & Python. But it only changes some of teh highlights for Lua & C++.

### To Reproduce

I just open a Lua or C++ file and it happens

### Expected behavior

The correct highlight colours should stay on for C++ and Lua files

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (0c49d6745b3fc4822ab02e0018770cd6383a779c) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.6.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.4.12-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:38:14 +0000"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - clojure             ✓ ✓ ✓ . ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - glsl                ✓ ✓ ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - latex               ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.1693350652

  system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
Do you have language servers (LSP) configured?

**Comment by clason** [comment]
(watched the video)

Yup.

That's LSP semantic highlighting kicking in; there's nothing wrong with treesitter.
