### ISSUE TITLE
64bit platform compiles 32bit parser elf

### ISSUE THREAD

**Issue by fanyx-ok** [nvim-treesitter/nvim-treesitter#5373]
### Describe the bug

I find all parser are compiled as 32 bit, but I am using 64 bit ubuntu.
I guess my PATH contains a 32 bit arm-gcc, so that these parsers are compiled using this arm-gcc.
How to sepecify the compiler for parser? 
And I think this problem can be avoided with an additional check step before using the first compiler in PATH.
<img width="1233" alt="image" src="https://github.com/nvim-treesitter/nvim-treesitter/assets/124134253/17f92eca-6dc5-46b7-a921-253b19021e6c">

### To Reproduce

1. add a 32bit C co,piler in PATH
2. install c parser by :TSInstall c
3. disable and then enable c hightlight by :TSEnable hightlight

<img width="1239" alt="image" src="https://github.com/nvim-treesitter/nvim-treesitter/assets/124134253/acab6881-971e-4ab7-adb2-a681700dab36">

### Output of `:checkhealth nvim-treesitter`

<img width="1428" alt="image" src="https://github.com/nvim-treesitter/nvim-treesitter/assets/124134253/4865b852-fbdb-4184-99cf-3db76daafc1f">

### Output of `nvim --version`

```text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
Sorry, but the logic is already complicated enough. It is on you to make sure your build environment is sane.

**Comment by fanyx-ok** [comment]
@clason I know what you mean. My real question is that is there a configuration item in tree-sitter to specify which compiler to use ?

**Comment by clason** [comment]
Yes, of course: https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support#which-c-compiler-will-be-used

**Comment by fanyx-ok** [comment]
@clason Thanks. I don't have any more questions.
