### ISSUE TITLE
treesitter: error when explicitly setting filetype

### ISSUE THREAD

**Issue by ilAYAli** [nvim-treesitter/nvim-treesitter#538]
**Bug**
Setting the filetype of a unified diff to e.g cpp causes an error.
Being able to do this can be beneficial to toggle between diff- and filetype highlightning.

**To Reproduce**
1. open unified diff
2. `:set ft=cpp`
4. See error below

**Expected behavior**
cpp syntax highlightning

**Output of `nvim --version`**
```
NVIM v0.5.0-pwa_01-482-g090551a80
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/petter/source/neovim/build/config -I/Users/petter/source/neovim/src -I/Users/petter/source/neovim/.deps/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/Users/petter/source/neovim/build/src/nvim/auto -I/Users/petter/source/neovim/build/include
Compiled by petter@pwa-mbp-3.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/Users/petter/local/share/nvim"

Run :checkhealth for more info
```

**Error message**
```
Error detected while processing FileType Autocommands for "*":
E5108: Error executing lua Failed to load parser: uv_dlopen: dlopen(/Users/petter/.vim/plugged/nvim-treesitter/parser/cpp.so, 1): no suitable image found.  Did find:
        /Users/petter/.vim/plugged/nvim-treesitter/parser/cpp.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
        /Users/petter/Dropbox/config/nvim/plugged/nvim-treesitter/parser/cpp.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

**Comment by theHamsta** [comment]
Strange,  0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00 is `uELF...`
![image](https://user-images.githubusercontent.com/7189118/94528450-b8654200-0238-11eb-9e41-aaa8cf54c0fa.png)

**Comment by ilAYAli** [comment]
`head -c8 /tmp/foo.diff | hexdump -Cv`
```
00000000  0a 77 78 32 20 63 61 6c                           |.wx2 cal|
00000008
```

The original filetype is an unified diff of c++ code, produced with `git diff format-patch HEAD`

**Comment by theHamsta** [comment]
The filetype seems to be `gitsendemail`.

But the parser will never be able to parse the content without any pre-processing with all the `+` and `-`. At the moment I would recommend the old regex highlighting with `set syntax=cpp`. Maybe this can improve with language injection when we would create a parser for git diffs.

**Comment by vigoux** [comment]
A parser for git diffs would be pretty tricky for language injection, as we would need to guess the actual contained fyletype, and there can be many errors (partial text and so on).

**Comment by theHamsta** [comment]
Btw parsing diffs as cpp works for me. I guess you might have a different problem with two *.so installed when it's complaining about invalid images. Normal `cpp` parsing is working for you?

**Comment by vigoux** [comment]
Maybe we can determine the language contained in a diff using the diff header.
Then using two parsers (one for deleted lines and one for added lines), we can come up with a proper, pretty reliable parsing without to many tweeks.

We need to think about it when designing language injection, as this is an interesting use case, pretty advanced too.

**Comment by ilAYAli** [comment]
> The filetype seems to be `gitsendemail`.
> 

`:echo &ft` reports `diff` but I don't think that matters

**Comment by ilAYAli** [comment]
> Btw parsing diffs as cpp works for me. I guess you might have a different problem with two *.so installed when it's complaining about invalid images. Normal `cpp` parsing is working for you?
> 

yes, I use it for `cpp` on a regular basis.

**Comment by ilAYAli** [comment]
> Maybe we can determine the language contained in a diff using the diff header.
> Then using two parsers (one for deleted lines and one for added lines), we can come up with a proper, pretty reliable parsing without to many tweeks.
> 

It would be nice if it was possible to explicitly set an arbitrary filetype and getting the associated highlightning even for the non-diff case. It is a regression, but I agree that e.g `:set syn=cpp` might be more correct. 
A similar non-diff scenario is e.g reviewing some code from some mail file, ...

**Comment by theHamsta** [comment]
But `:set filetype=cpp` works for me, also for diff files. We need more steps to reproduce the bug. Is there any plugins that might additionally change settings.

Thinking about it: this seems to be related to how OSX is loading the dynlibs. Any of the maintainers using OSX?

**Comment by theHamsta** [comment]
Are you sure the Dropbox parser is compiled for your local architecture?

**Comment by clason** [comment]
Here's what `hexdump cpp.so` returns on my macOS system:
```
0000000 cf fa ed fe 07 00 00 01 03 00 00 00 06 00 00 00
0000010 0f 00 00 00 d0 05 00 00 85 00 11 00 00 00 00 00
...
```

**Comment by ilAYAli** [comment]
> Are you sure the Dropbox parser is compiled for your local architecture?

Well spotted!
`~/.config/nvim` is symlinked to `~/Dropbox/config/nvim`, and the .so was likely updated on my linux development machine last.
This has worked well for the last ~ 15 years, as I have not had any binaries in _config_ directory.
I guess this can be solved by avoiding name conflicts, and ensuring that the library for the correct architecture is loaded.

**Comment by clason** [comment]
Or by putting plugins in a different directory from your config (`.local/share/nvim` comes to mind)...

**Comment by theHamsta** [comment]
We discussed that we should maybe put the parsers in the `data` dir. Maybe you can make Dropbox ignore `*.so`?
