### ISSUE TITLE
Add Mojo Language support

### ISSUE THREAD

**Issue by michihupf** [nvim-treesitter/nvim-treesitter#5387]
Modular just allowed users to use the mojo language on their own machine alongside a VS Code extension for syntax highlighting, auto completion and more. Mojo should be added to the supported languages for some nice neovim syntax highlighting :)

[`mojo` and `mojo-lsp-server`](https://www.modular.com/mojo) 
[VS Code Extension](https://marketplace.visualstudio.com/items?itemName=modular-mojotools.vscode-mojo)

[nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/commit/339ce2dad04d084cd6da62a0dc5ffb9d113d9bc2) already added the language server into their server configs for easy configuration.

**Comment by llllvvuu** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/issues/2282

**Comment by lucario387** [comment]
Well someone has to write a parser for mojo first ...

**Comment by llllvvuu** [comment]
Also, are you saying the mojo LSP doesn't support semantic tokens?

there is a [textmate grammar](https://gist.github.com/llllvvuu/fafc8aa32091f934dcf6a1eb2fc4975a), idk if it makes more sense to work from there or to work from the python tree-sitter grammar

**Comment by amaanq** [comment]
A textmate grammar doesn't mean much, tree-sitter is a full-blown parser after all so either a suite of source code or a real lexer/parser definition (yacc, peg, antlr) are needed

**Comment by llllvvuu** [comment]
This is probably not going to happen anytime soon: https://github.com/modularml/mojo/discussions/401

There's not much that can be done with a closed-source language

**Comment by shalei6698** [comment]
@llllvvuu https://www.modular.com/blog/the-next-big-step-in-mojo-open-source

**Comment by llllvvuu** [comment]
Unfortunately open sourcing the stdlib doesn't really help. They need to open-source the parser (even that will be hard to work with since it's hand-written)
