### ISSUE TITLE
Treesitter obscures away the LSP warnings (not errors)

### ISSUE THREAD

**Issue by alexaandru** [nvim-treesitter/nvim-treesitter#539]
**Describe the bug**

With TS enabled, I no longer get LSP warnings. LSP errors work just fine, but for LSP warnings all I get is a `W` in the gutter, but not the virtual text that comes with it.

**To Reproduce**

Given a folder with the following three files:

`foo.go`

```Go
package main

var f = func(a int) {
	a = 2
}
```

`go.mod` (so that the LSP kicks in):

```Gomod
module foo
```

and `test.vim` (the sample config):

```VimL
packadd nvim-lspconfig
packadd nvim-treesitter

lua << LUA
require'nvim_lsp'.gopls.setup{
  cmd = {"gopls", "serve"},
  settings = {gopls = {staticcheck = true}}
}
require'nvim-treesitter.configs'.setup{highlight = {enable = true}}
LUA
```

then running `nvim -u test.vim foo.go` will show a `W` in the gutter, but no virtual text for it.

Disabling the TS plugin (OR simply toggling off highlighting) and trying again, will reveal the actual warning text: _"argument a is overwritten before first use"_.

You can also introduce any error in the Go code (just type some garbage in there) and you will see that errors work fine, with or without TS.

**Expected behavior**
I expect TS to not break LSP warnings.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>
## go parser healthcheck
  - OK: go parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.
  - WARNING: No `folds.scm` query found for go
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-715-gc5ceefca7
```

**Additional context**
I use the latest master for the TS (and lspconfig) plugins.

**Comment by vigoux** [comment]
Hi and  thanks for reporting!
This is actually a known issue upstream, caused by luahl and recent patches made to neovim.

**Comment by alexaandru** [comment]
Got it, looks like this issue, right: https://github.com/neovim/neovim/issues/12943 ? Should we close this ticket then and wait for the upstream to fix?

**Comment by kyazdani42** [comment]
leave it open here, we'll close once upstream is fixed :)

**Comment by theHamsta** [comment]
I guess that's fixed now: https://github.com/neovim/neovim/pull/13038

**Comment by bfredl** [comment]
only accidentally in that case. We have yet to implement priority :]

**Comment by vigoux** [comment]
Should be fixed upstream, could you confirm it is the case ?

**Comment by alexaandru** [comment]
Yes, I cannot reproduce with the latest neovim (v0.5.0-dev+1000-g84d08358b). Thank you!
