### ISSUE TITLE
Latex highlighting with markdown inline not working

### ISSUE THREAD

**Issue by ribru17** [nvim-treesitter/nvim-treesitter#5397]
### Describe the bug

Since commit bfb4601f48c127ae6fb24a30ebf0495aaca8d28f, Latex highlights in Markdown documents no longer work properly through `markdown_inline`. Below is a preview:

![aftertsbug](https://github.com/nvim-treesitter/nvim-treesitter/assets/55766287/c2db591e-6ad5-468e-a64a-975b4a0093cc)

### To Reproduce

1. Install `markdown_inline`, `markdown`, and `latex` parsers
2. Open a Markdown file that has Latex content (marked with `$` delimiters)
3. Note how the highlighting is not properly applied

### Expected behavior

The parsers should highlight the latex blocks, looking something like this:

![beforetsbug](https://github.com/nvim-treesitter/nvim-treesitter/assets/55766287/5b92ea0a-8eeb-4618-ac96-d4027ecb832c)

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.2.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.5.3-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Wed, 13 Sep 2023 08:37:40 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - comment             ✓ . . . .
  - commonlisp          ✓ ✓ ✓ . .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - diff                ✓ . . . .
  - dot                 ✓ . . . ✓
  - git_rebase          ✓ . . . ✓
  - gitattributes       ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - haskell             ✓ . ✓ . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - ini                 ✓ . ✓ . .
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - latex               ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - mermaid             ✓ . . . .
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - scheme              ✓ . ✓ . ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓
  - zig                 ✓ . ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.1694285958

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

Running on most up to date parsers for all required parsers. Other injected languages for `markdown_inline` still work, such as the `mermaid` parser.

**Comment by lucario387** [comment]
Thank you for the report. Bugfix incoming

**Comment by lucario387** [comment]
@ribru17 Can you hover the cursor around the nodes with differing highlights, and do a `:Inspect` to see which hlgroup is being applied? For me, with or without `include-children`, the groups are the same.

**Comment by ribru17** [comment]
As a bit of follow up, I have tested this on nightly with the same results as 0.9.4. So I think I was wrong in the initial classificiation of the bug. But I think the core difference since after the mentioned commit is that `displayed_equation` and `inline_formula` no longer get applied to the LaTeX regions. Personally, this is a problem for me since I use Markdown LaTeX snippets that depend on the detection of the cursor being in those regions (as well as `math_environment` regions). Is this still a bug or is what I described intended behavior now?

**Comment by wzf03** [comment]
Good news!!! The `markdown_inline` works in the new nvim v0.9.5 release!
And with [my personal fork](https://github.com/wzf03/luasnip-latex-snippets.nvim) of luasnip-latex-snippets.nvim with add support for markdown_inline treesitter, I can use snippets in markdown latex block really smoothly!

**Comment by wzf03** [comment]
Actually the `injection.include-children` is required in markdown_inline. I have created a pull request to simply add this back, and it works well.
