### ISSUE TITLE
What would it take to use my lua grammar :)

### ISSUE THREAD

**Issue by tjdevries** [nvim-treesitter/nvim-treesitter#543]
Hi @vigoux  :)

Just wondering what it would take to switch to this grammar: https://github.com/tjdevries/tree-sitter-nlua

I'd like to iterate on it and use it w/ tree-sitter, but it's pretty hard right now because of the default query appending and not using the same names...

If change the names of my repo would make things easy / you would accept it as the new lua grammar, I could do that. Just wondering what your thoughts are :smile:

**Comment by theHamsta** [comment]
use https://github.com/nvim-treesitter/nvim-treesitter/pull/506 to install from local paths or else
```lua
  require "nvim-treesitter.parsers".get_parser_configs().lisp = {
    install_info = {
      url = "~/projects/tree-sitter-lisp",
      files = {"src/parser.c"}
    }
  }
  --require "nvim-treesitter.parsers".get_parser_configs().viml = {
  --install_info = {
  --url = "https://github.com/vigoux/tree-sitter-viml",
  --files = {"src/parser.c"}
  --}
  --}
  require "nvim-treesitter.parsers".get_parser_configs().markdown = nil
  require "nvim-treesitter.parsers".get_parser_configs().zig = {
    install_info = {
      url = "https://github.com/GrayJack/tree-sitter-zig",
      files = {"src/parser.c"}
    }
  }
  require "nvim-treesitter.parsers".get_parser_configs().kotlin = {
    install_info = {
      url = "https://github.com/QthCN/tree-sitter-kotlin",
      files = {"src/parser.c"}
    }
  }

```

**Comment by tjdevries** [comment]
One question I had related to this. Any way to get the query files from the parser repo? I'd like to keep the files there if possible and iterate on them.

**Comment by vigoux** [comment]
I think the easiest way would be to symlink them manually... We don't keep the parsers files around (to save some roome on users side).

**Comment by theHamsta** [comment]
@vigoux he wants us to adopt his queries.

**Comment by theHamsta** [comment]
If you make the language of your parser `nlua` both parsers you even co-exist (or better their queries). A setting could determine whether to load the one or the other.

**Comment by vigoux** [comment]
The trees generated by the `lua` parser and the `nlua` parser differs by a fair bit, I think having them more close one to the other would be a good selling point (as switching from one to the other would basically be noop).

**Comment by tjdevries** [comment]
I don't want them to be the same. I don't like the structure of the other tree. That's why I rewrote from scratch instead of forking and sending pr. Similar things are not grouped semantically IMO in the other grammar.

**Comment by clason** [comment]
Right now we're going with switching to https://github.com/MunifTanjim/nvim-treesitter-lua, which looks to be a better parser for the "pure" language.

But since your parser is called `nlua`, there is no obstacle to adding it as an _additional_ parser for people interested in something especially tuned towards Neovim development. (It might be worth investing a bit of thought into how to make it easier to use one or the other parser, depending on filepath?)

I've added this to the tracking issue so I'm closing this one; but feel free to continue discussing here!
