### ISSUE TITLE
Improved statusline function

### ISSUE THREAD

**Issue by kristijanhusak** [nvim-treesitter/nvim-treesitter#545]
I wrote a small simple implementation of a statusline function that returns the structure with the real lines and values.

So instead of having:
```
program->class->method->etc.
```

It shows real values:
```
class MyClass -> myMethod()
```

Here's the implementation if you are interested to see: https://github.com/kristijanhusak/neovim-config/blob/bleeding-edge/nvim/lua/ts_statusline.lua

My question is: Would you consider adding something like this to the core here? Or maybe a plugin that is part of the `nvim-treesitter` org?

**Comment by kyazdani42** [comment]
hi ! I think this is too simple to be added as a plugin, i'd rather add this to the core. Let's see what other think about that
