### ISSUE TITLE
Windows 11 failure to compile with LLVM Clang or mingw

### ISSUE THREAD

**Issue by TurnoffyourTV** [nvim-treesitter/nvim-treesitter#5452]
### Describe the bug

I have run the treesitter successfully on my laptop which is win10
then i tried it on my Desktops but failed which is win11
error shows nvim-treesitter error durning compilation

### To Reproduce

:TSInstallSync lua（same to all languages)

### Expected behavior

run successfully

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v18.17.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `clang` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: clang version 17.0.1
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.22621",
  sysname = "Windows_NT",
  version = "Windows 11 Pro"
} ~

Parser/Features         H L F I J

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.2
Build type: RelWithDebInfo
LuaJIT 2.1.1694082368
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

### Additional context

info after ':TSInstallSync lua'
Downloading tree-sitter-lua...
Checking out locked revision
Compiling...
E5108: Error executing lua D:/Neovim/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 2992 for language lua
stack traceback:
	[C]: in function '_ts_parse_query'
	D:/Neovim/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'get'
	...m/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:114: in function 'new'
	D:/Neovim/share/nvim/runtime/lua/vim/treesitter.lua:61: in function '_create_parser'
	D:/Neovim/share/nvim/runtime/lua/vim/treesitter.lua:131: in function 'get_parser'
	D:/Neovim/share/nvim/runtime/lua/vim/treesitter.lua:459: in function 'start'
	...a/lazy/nvim-treesitter/lua/nvim-treesitter/highlight.lua:20: in function 'attach'
	...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'
	...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
	...ata/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:69: in function 'cmd'
	...ata/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:295: in function 'iter_cmd_sync'
	...ata/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:455: in function 'run_install'
	...ata/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:494: in function 'install_lang'
	...ata/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:550: in function <...ata/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:513>
	...ata/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:582: in function 'run'
	[string ":lua"]:1: in main chunk
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/54170984/38a845dd-6b07-4dfb-b90c-b6747340f297)

**Comment by theHamsta** [comment]
> ### Describe the bug
> 
> I have run the treesitter successfully on my laptop which is win10 then i tried it on my Desktops but failed which is win11 error shows nvim-treesitter error durning compilation
> ### To Reproduce
> 
> :TSInstallSync lua（same to all languages)
> ### Expected behavior
> 
> run successfully
> ### Output of `:checkhealth nvim-treesitter`
> 
> ```
> ==============================================================================
> nvim-treesitter: require("nvim-treesitter.health").check()
> 
> Installation ~
> - WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
> - OK `node` found v18.17.1 (only needed for :TSInstallFromGrammar)
> - OK `git` executable found.
> - OK `clang` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
>   Version: clang version 17.0.1
> - OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.
> 
> OS Info:
> {
>   machine = "x86_64",
>   release = "10.0.22621",
>   sysname = "Windows_NT",
>   version = "Windows 11 Pro"
> } ~
> 
> Parser/Features         H L F I J
> 
>   Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
>          +) multiple parsers found, only one will be used
>          x) errors found in the query, try to run :TSUpdate {lang} ~
> ```
> 
> ### Output of `nvim --version`
> 
> ```
> NVIM v0.9.2
> Build type: RelWithDebInfo
> LuaJIT 2.1.1694082368
> Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include
> 
>    system vimrc file: "$VIM\sysinit.vim"
>   fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
> 
> Run :checkhealth for more info
> ```
> 
> ### Additional context
> 
> info after ':TSInstallSync lua' Downloading tree-sitter-lua... Checking out locked revision Compiling... E5108: Error executing lua D:/Neovim/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 2992 for language lua stack traceback: [C]: in function '_ts_parse_query' D:/Neovim/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'get' ...m/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:114: in function 'new' D:/Neovim/share/nvim/runtime/lua/vim/treesitter.lua:61: in function '_create_parser' D:/Neovim/share/nvim/runtime/lua/vim/treesitter.lua:131: in function 'get_parser' D:/Neovim/share/nvim/runtime/lua/vim/treesitter.lua:459: in function 'start' ...a/lazy/nvim-treesitter/lua/nvim-treesitter/highlight.lua:20: in function 'attach' ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module' ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module' ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:69: in function 'cmd' ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:295: in function 'iter_cmd_sync' ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:455: in function 'run_install' ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:494: in function 'install_lang' ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:550: in function <...ata/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:513> ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:582: in function 'run' [string ":lua"]:1: in main chunk ![image](https://user-images.githubusercontent.com/54170984/270852409-38a845dd-6b07-4dfb-b90c-b6747340f297.png)

You are not observing a compilation error. Rather a parser/query mismatch when the parser is loading. It seems that the newly installed parser is not regarded. Can you check whether the `.so` file generated and whether it is in your runtime path?

**Comment by TurnoffyourTV** [comment]
> > ### Describe the bug
> > I have run the treesitter successfully on my laptop which is win10 then i tried it on my Desktops but failed which is win11 error shows nvim-treesitter error durning compilation
> > ### To Reproduce
> > :TSInstallSync lua（same to all languages)
> > ### Expected behavior
> > run successfully
> > ### Output of `:checkhealth nvim-treesitter`
> > ```
> > ==============================================================================
> > nvim-treesitter: require("nvim-treesitter.health").check()
> > 
> > Installation ~
> > - WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
> > - OK `node` found v18.17.1 (only needed for :TSInstallFromGrammar)
> > - OK `git` executable found.
> > - OK `clang` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
> >   Version: clang version 17.0.1
> > - OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.
> > 
> > OS Info:
> > {
> >   machine = "x86_64",
> >   release = "10.0.22621",
> >   sysname = "Windows_NT",
> >   version = "Windows 11 Pro"
> > } ~
> > 
> > Parser/Features         H L F I J
> > 
> >   Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
> >          +) multiple parsers found, only one will be used
> >          x) errors found in the query, try to run :TSUpdate {lang} ~
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Output of `nvim --version`
> > ```
> > NVIM v0.9.2
> > Build type: RelWithDebInfo
> > LuaJIT 2.1.1694082368
> > Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include
> > 
> >    system vimrc file: "$VIM\sysinit.vim"
> >   fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
> > 
> > Run :checkhealth for more info
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Additional context
> > info after ':TSInstallSync lua' Downloading tree-sitter-lua... Checking out locked revision Compiling... E5108: Error executing lua D:/Neovim/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 2992 for language lua stack traceback: [C]: in function '_ts_parse_query' D:/Neovim/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'get' ...m/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:114: in function 'new' D:/Neovim/share/nvim/runtime/lua/vim/treesitter.lua:61: in function '_create_parser' D:/Neovim/share/nvim/runtime/lua/vim/treesitter.lua:131: in function 'get_parser' D:/Neovim/share/nvim/runtime/lua/vim/treesitter.lua:459: in function 'start' ...a/lazy/nvim-treesitter/lua/nvim-treesitter/highlight.lua:20: in function 'attach' ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module' ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module' ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:69: in function 'cmd' ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:295: in function 'iter_cmd_sync' ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:455: in function 'run_install' ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:494: in function 'install_lang' ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:550: in function <...ata/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:513> ...ata/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:582: in function 'run' [string ":lua"]:1: in main chunk ![image](https://user-images.githubusercontent.com/54170984/270852409-38a845dd-6b07-4dfb-b90c-b6747340f297.png)
> 
> You are not observing a compilation error. Rather a parser/query mismatch when the parser is loading. It seems that the newly installed parser is not regarded and instead the built-in one. Can you check whether the `.so` file generated and whether it is in your runtime path? Probably also installing a parser that does not ship with neovim will make debugging easier

thank you 
at last i moved the folder 'nvim' and 'nvim-data' from my laptop to desktop overwriting files on desktop, treesitter finally worked(before this I have  reinstall the two folders by desktop itself  for several times)
it confuses me what leads this
By the way which folder should i check  ->"whether .so file generated"(.dll in parser folder?)
