### ISSUE TITLE
Limit concurrent compilation to the number of cores

### ISSUE THREAD

**Issue by MahouShoujoMivutilde** [nvim-treesitter/nvim-treesitter#5458]
**Is your feature request related to a problem? Please describe.**

Today I've tried `ensure_installed = "all"` on Raspberry Pi 4 (4GB).

...It was a mistake.

After about a minute I was hitting full RAM utilization, and the pi became unresponsive.

**Describe the solution you'd like**

Run no more than `vim.loop.available_parallelism()` compilations concurrently or something along those lines.

**Describe alternatives you've considered**

An OOM killer could have saved the pi from locking up, but it is inelegant solution and I've never expected to see hundreds of `CC` running simultaneously.

**Additional context**

<details>
  <summary>htop</summary>

![29-09-2023-05_03_47](https://github.com/nvim-treesitter/nvim-treesitter/assets/14999778/6dcd45e5-3926-4b3b-b50c-06251243def7)

</details>

Arch Linux ARM (64 bit), neovim 9.2, lazy.nvim as plugin manager.

**Comment by clason** [comment]
Yes. `ensure_installed = "all"` is not supported; it's only meant for CI.

(We've already rewritten the installation logic for the 1.0 branch which will be released later this year, so this is not something we will change before that.)

**Comment by theHamsta** [comment]
Try `:TSInstallSync all` to serialize the compilation until this is addressed or mount a swapfile to allow your raspi consume more RAM
