### ISSUE TITLE
documentation update needed: highlight custom_captures 

### ISSUE THREAD

**Issue by coffebar** [nvim-treesitter/nvim-treesitter#5460]
### Describe the bug

[This documentation](https://github.com/nvim-treesitter/nvim-treesitter/blob/16ea2969ea0a5ba902fceece9b2db10c7c9ba2d6/doc/nvim-treesitter.txt#L151C1-L173C2) tells how to add custom_captures. This doesn't work for me. I looked into the code and didn't find any methods related to this feature in the "nvim-treesitter.highlight". Also `custom_captures` [marked as deprecated](https://github.com/nvim-treesitter/nvim-treesitter/blob/16ea2969ea0a5ba902fceece9b2db10c7c9ba2d6/lua/nvim-treesitter/configs.lua#L50) in the config of the highlight section. Comment `use highlight.set_custom_captures instead`, but where is it?

### To Reproduce

-

### Output of `:checkhealth nvim-treesitter`

```markdown
-
```

### Output of `nvim --version`

```text
-
```

### Additional context

I don't understand how it should be. However I see that the documentation does not match reality, and I also cannot use this feature.

Btf, I want to change the highlight color for params in functions.

**Comment by clason** [comment]
Highlights are completely handled by Neovim, not this plugin; the old custom capture functionality is obsolete and has been removed.

Just read `:h treesitter-highlight`.
