### ISSUE TITLE
re-parse when File just opened

### ISSUE THREAD

**Issue by qrockz** [nvim-treesitter/nvim-treesitter#5467]
**Is your feature request related to a problem? Please describe.**
So for example I have a lua file with a grammar error. The keyword _function_ is misspelled (letter 'f' is missing):

```
unction ()

end
```
When I open this file with nvim, treesitter does not throw errors or warnings like it should.
To get the Diagnostics finally to start I have to manually **:e!** in nvim to trigger treesitter to reparse this buffer.
Only then I get warnings/errors.

**Describe the solution you'd like**
Automatically reparse newly opened files so that Diagnostics shows errors/warnings just in case.

**Comment by lucario387** [comment]
Neovim treesitter does not have any relation to diagnostics, that's the LSP's job.
