### ISSUE TITLE
Problems configuring treesitter on neovim 0.9.0

### ISSUE THREAD

**Issue by fanny6213-web** [nvim-treesitter/nvim-treesitter#5484]
I've tried installing treesitter multiple times but throws this error: 

`Error detected while processing function <SNR>31_NetrwBrowseChgDir[197]..BufReadPost Autocommands for "*.lua"..FileType Autocommands for "*":                                       
Error executing lua callback: .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:20: attempt to call field 'start' (a nil value)
stack traceback:
        .../start/nvim-treesitter/lua/nvim-treesitter/highlight.lua:20: in function 'attach'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
        ...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...er/start/nvim-treesitter/lua/nvim-treesitter/configs.lua:132>`

this only happens when I open any file using neovim
the file doesn't get parsed after opening (which is obvious but still worth mentioning)

Thanks to anyone who helps :)

**Comment by lucario387** [comment]
Smth is wrong here as `vim.treesitter.start()` is nil, should not be like this since it's 0.9

**Comment by fanny6213-web** [comment]
> Smth is wrong here as `vim.treesitter.start()` is nil, should not be like this since it's 0.9

I installed neovim from a tar.gz file and added it to `usr/bin` directory, (download was from the official website of neovim) because apt installed nvim v0.7.2

Am I supposed to update something :/

**Comment by lucario387** [comment]
I'd say it's because artifacts from 0.7.2 still remains and neovim is still using some of the 0.7.2 files. Please uninstall both and then reinstall 0.9.0+ version

**Comment by fanny6213-web** [comment]
Yes it works now, some of the remains of nvim 0.7.0 were sitting in the corners and my g++ compiler was outdated 🗿

Thanks for the help ^_^
