### ISSUE TITLE
Slow highlight for large cpp files

### ISSUE THREAD

**Issue by MKrbm** [nvim-treesitter/nvim-treesitter#5503]
### Describe the bug

treesitter syntax highlight peform very poorly for cpp files.

### To Reproduce

1. install lazy
2. set option as follows
```
opts = {
  highligh = {
     enable = true
  },
  indent = {
     enable = false
  },
}
```
3, install cpp support via `TSInstall cpp`
4. open cpp files around 300 lines (may depend on your computer) and you can percept many operators including `o / O` peform really slow
5. If you enable indent, then it gets worse. 

### Expected behavior

Every operator perform same as without highlighting. 

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
OK tree-sitter found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
OK node found v18.18.0 (only needed for :TSInstallFromGrammar)
OK git executable found.
OK cc executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
Version: Apple clang version 15.0.0 (clang-1500.0.40.1)
OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "23.0.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103"
} ~

Parser/Features         H L F I J
  
c                   ✓ ✓ ✓ ✓ ✓
cpp                 ✓ ✓ ✓ ✓ ✓
lua                 ✓ ✓ ✓ ✓ ✓
query               ✓ ✓ ✓ ✓ ✓
vim                 ✓ ✓ ✓ . ✓
vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
❯ nvim --version
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.9.2/share/nvim"

Run :checkhealth for more info
```

**Comment by MKrbm** [comment]
I have read upstream issue : https://github.com/neovim/neovim/issues/22426
but I'm not sure if this is the same case as this.

**Comment by clason** [comment]
It is the same (your cpp files probably have macro injections, which are expensive). You can test with a nightly appimage to see if it will be better in 0.10.

**Comment by MKrbm** [comment]
In my understandings, what is meant by injections is "embedding one language within cpp-file and highlighting it correctly". 
But I'm wondering why this happens in the file like cpp?

**Comment by clason** [comment]
Because that's how macros work: you are embedding some C++ code into other C++ code.

**Comment by MKrbm** [comment]
I'm bit confusing right now. Macro injection is injection for macro definitions of c++?

**Comment by lucario387** [comment]
Basically, how we get highlights for `#define lhs rhs` is by re-parsing each rhs as c/cpp code. Meaning 10 #define = 10 extra injection trees, leading to a lot of reparsing -> slow

**Comment by MKrbm** [comment]
I tried 0.10 and I confirmed peformance gets better. I will close this issue! thank you everyone
