### ISSUE TITLE
official tree-sitter support for go/templ

### ISSUE THREAD

**Issue by wrnlb666** [nvim-treesitter/nvim-treesitter#5517]
**Is your feature request related to a problem? Please describe.**
golang/templ has an unsupported [treesitter plugin](https://github.com/vrischmann/tree-sitter-templ). But it would be very nice if we can download it directly with `TSInstall templ`

**Describe the solution you'd like**
Add support to `templ`? 

**Describe alternatives you've considered**
Installing it by myself :(

**Comment by clason** [comment]
See https://github.com/nvim-treesitter/nvim-treesitter/issues/2282 (and PR welcome, no permission needed).

**Comment by wrnlb666** [comment]
Thank you! Also sorry for didn't notice that issue.
