### ISSUE TITLE
Register two langs (`markdown` and `markdown_inline`) for the same filetype `markdown`

### ISSUE THREAD

**Issue by toh995** [nvim-treesitter/nvim-treesitter#5529]
**Is your feature request related to a problem? Please describe.**
I wanted to get extra syntax highlighting for markdown files, and didn't realize that there were actually two separate parsers - `markdown` and `markdown_inline`.

In the future, it would be nice to have the nvim-treesitter plugin **auto-install** BOTH languages, when I enter a `markdown` filetype buffer.

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
For now, I can get away with adding `markdown_inline` in my plugin config, as `ensure_installed`.

**Additional context**
There seems to be a limitation inside of the neovim source code itself.

Currently, neovim only allows registering a single parser language per filetype.

It's possible to update the neovim source code, but this would likely introduce a breaking change.

For example, we would change the function `vim.treesitter.language.get_lang()` - it would no longer return a string, instead it would return a list of strings. For reference: https://github.com/neovim/neovim/blob/a474348/runtime/lua/vim/treesitter/language.lua#L24-L36

I didn't feel comfortable introducing a potential breaking change, without discussion first.

Please let me know if I should move this issue to the neovim repo instead 😅

**Comment by lucario387** [comment]
It's already done in the rewrite of nvim-treesitter. So for the time being you are good to go

https://github.com/nvim-treesitter/nvim-treesitter/blob/main/lua/nvim-treesitter/parsers.lua

**Comment by toh995** [comment]
Thanks @lucario387!!!

Looks like this commit fixes it https://github.com/nvim-treesitter/nvim-treesitter/commit/c7ba60a512772bf14e5f71074972225377eec1a0

Out of curiosity, what's the difference between `main` and `master` branches? Looks like I'm currently downloading from the `master` branch.

**Comment by lucario387** [comment]
@toh995 `main` branch is the rewrite, soon-to-be-default branch in the upcoming future.
`master` branch is the current default branch
