### ISSUE TITLE
Prisma folds

### ISSUE THREAD

**Issue by RaafatTurki** [nvim-treesitter/nvim-treesitter#5539]
**Is your feature request related to a problem? Please describe.**
Prisma files don't have any folding capabilities

**Describe the solution you'd like**
Add treesitter fold queries

**Additional context**
There are only 4 foldable nodes is prisma, I've tried to do it myself but it oddly didn't work
`queries/prisma/folds.scm`
```
[
 (generator_declaration)
 (datasource_declaration)
 (model_declaration)
 (enum_declaration)
]
```

**Comment by lucario387** [comment]
PR welcome. Also your queries are missing `@fold`

**Comment by RaafatTurki** [comment]
done
