### ISSUE TITLE
Misleading contribution docs for @type.definition

### ISSUE THREAD

**Issue by aMOPel** [nvim-treesitter/nvim-treesitter#5544]
### Describe the bug

[contribution docs](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#types) state

> @type.definition ; type definitions (e.g. `typedef` in C)

Which implies to capture `typedef` as `@type.definition`.
But highlight queries generally use `@type.definition` for the identifier of the defined type instead of the keyword.

### To Reproduce

[C](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/c/highlights.scm#L155)
[CPP](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/cpp/highlights.scm#L36)
[GO](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/go/highlights.scm#L8)

### Expected behavior

> @type.definition ; identifiers in type definitions (e.g. in `typedef <type> <identifier>` in C)

### Output of `:checkhealth nvim-treesitter`

```markdown
unrelated
```

### Output of `nvim --version`

```text
unrelated
```

**Comment by lucario387** [comment]
PR welcome
