### ISSUE TITLE
Wrong highlighting when first opening the buffer

### ISSUE THREAD

**Issue by rafikdraoui** [nvim-treesitter/nvim-treesitter#555]
**Describe the bug**

With highlight enabled and this Python code:

```python
class Fruit(Food):
    APPLE = 1
    BANANA = 2
    KIWI = 3
    ORANGE = 4
    RASPBERRY = 5
```

every terms is highlighted except for the attribute `KIWI`, which has `Normal` (I think) highlighting. When looking at how it is is been parsed with `nvim_treesitter#statusline`, there's no difference with the other lines.

As soon as the line is modified, `KIWI` gets highlighted like the other attributes. But if we do `:edit` again then the highlight is reset (only for the `KIWI` term)

If the line `HELLO = 42` is added above the KIWI line, then the missing highlighting happens on `HELLO`.

If the parent class `Food` is removed (i.e. `class Fruit:` instead of `class Fruit(Food):`), then `KIWI` is the problem again. It's as if which term gets mis-highlighted depends on its position in the parse tree.

[![asciicast](https://asciinema.org/a/iPclPUm8FMmUNe7UFPhECGeiX.svg)](https://asciinema.org/a/iPclPUm8FMmUNe7UFPhECGeiX)

**To Reproduce**

1. Minimal vimrc `minimal.vim`

```vim
set runtimepath+=/path/to/nvim-treesitter
set statusline=%{nvim_treesitter#statusline(120)}
lua <<EOF
  local treesitter = require'nvim-treesitter.configs'
  treesitter.setup {
    ensure_installed = "python",
    highlight = { enable = true },
  }
EOF
```

2. Test python file `fruit.py`

```python
class Fruit(Food):
    APPLE = 1
    BANANA = 2
    KIWI = 3
    ORANGE = 4
    RASPBERRY = 5
```

3. `nvim --clean -u minimal.vim fruit.py`

4. `KIWI` has no highlight. Playing around with the code as shown in the Asciicast uncovers some other bugs.

**Expected behavior**

Consistent highlighting

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## c parser healthcheck
  - OK: c parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.
  - OK: `folds.scm` found.

## python parser healthcheck
  - OK: python parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `textobjects.scm` found.
  - OK: `folds.scm` found.

</code>
</details>

**Output of `nvim --version`**

```
NVIM v0.5.0-728-gf6ac37560
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/rafik/code/neovim/build/config -I/home/rafik/code/neovim/src -I/home/rafik/code/neovim/.deps/usr/include -I/usr/include -I/home/rafik/code/neovim/build/src/nvim/auto -I/home/rafik/code/neovim/build/include
Compiled by rafik

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Additional context**

I thought the non-highlighted term could have been an error term (which links to `hl-TSNone` by default), but even when I do `:hi! link TSError Error` the term remains `hl-Normal` (I think, fixing https://github.com/nvim-treesitter/nvim-treesitter/issues/519 would be useful to verify which highlight is really used).

**Comment by stsewd** [comment]
I have experienced this as well

**Comment by r-bar** [comment]
If you are doing any sort of lazy loading (loading with an autocmd) with either treesitter or your colorscheme you are likely to encounter this issue.

**Comment by stsewd** [comment]
Closing this in favor of https://github.com/nvim-treesitter/nvim-treesitter/issues/871
