### ISSUE TITLE
nvim-treesitter slow on very big files (especially C++)

### ISSUE THREAD

**Issue by theHamsta** [nvim-treesitter/nvim-treesitter#556]
**Describe the bug**
nvim-treesitter can be slow when opening a big file. `vulkan.hpp` has 90,000+ lines (https://github.com/KhronosGroup/Vulkan-Headers/blob/master/include/vulkan/vulkan.hpp).

**To Reproduce**
Open `vulkan.hpp` with treesitter syntax highlighting on and highlight_current. Vim freezes.

**Possible solution**

When parsing, we set start and end line. We could maybe limit the parsing to a certain contex around cursor (+-1000 lines?). Or just disable some modules when files are too big (threshold configurable by user).

**Comment by osherbz** [comment]
I commented the ensure_install="all" config and it much faster.(Important to look if the desired parser is installed).
May be helpful (:

**Comment by Happy-Dude** [comment]
Can the preference be to process to entire file for the tree-structure (such that functions, text-objects, and navigation) are still functional, but to "fence-off" the syntax highlighting to maybe 5-terminal window's widths on top and bottom?

I reckon that a lot of tree-sitter's processing can happen asynchronously and the relevant visual parts exposed when the user needs it to be (like how browsers lazy-load tabs and images only when the user is actively viewing them).

**Comment by vigoux** [comment]
Indeed, the plan would be to have the processing happen in another thread.

The thing is that we need to parse the full file initially anyway (because we want the full syntax tree at startup) but maybe what takes time is the queries that are running in the tree?

**Comment by kyazdani42** [comment]
I'm pretty sure it's related to queries. Doing regex matching on a huge file can take a lot of time.

**Comment by yashLadha** [comment]
@vigoux @kyazdani42 Is there any workaround for this currently, because i am also facing this issue when opening some lagre c++ files in chromium source.

**Comment by theHamsta** [comment]
You could add a check in the attach function of `highlight` and `highlight_definitions` to return when a file is has more than X lines.

**Comment by yashLadha** [comment]
So will it use the fallback mechanism or use the tree-sitter one.

**Comment by theHamsta** [comment]
This would enforce fallback.

You could also look for the spot where we create parsers and for highlighting where neovim creates the parsers. For `parse` it always expects a line range. You could enforce a maximum context it parsers. But then only a part of your file has highlighting and this would be more of a hack.

**Comment by kyazdani42** [comment]
there is a lot of match predicates in the cpp queries, i believe this is slowing down treesitter highlighting a lot. It's not that slow when opening very big json files (~25mb) with treesitter.

**Comment by theHamsta** [comment]
Removing all regexes helps a bit but doesn't solve the problem. Vim will still freeze after a few edits and refuse any other edits.

**Comment by vigoux** [comment]
Freezing after some edits does not seem related.. Do you have the list of edits you are doing ?

**Comment by theHamsta** [comment]
Any edits will do it. With `highlight_definitions` disabled you might be able to do three or four edits without complete freezing but only 2 sec lags. But usually it happens on the first edit of any kind especially when you issue the next edit command before you see the result of the previous. As far as I now vim doesn't do regex highlighting on the whole file at once.

**Comment by theHamsta** [comment]
Found out that the freezing processes were kind of unkillable in the background were stopping my PC. It's less predicatable when a deadly edit happens but I didn't manage to trigger it without tree-sitter.

**Comment by kyazdani42** [comment]
i think i had some issues with tree-sitter and nvim-lsp, nvim-lsp froze the editor a lot, then i switched back to coc and it came back to normal.
I sometimes have a process that takes too much of my cpu and which freezes, in which case, `kill -9 $(pgrep process)` works usually

**Comment by theHamsta** [comment]
I deactivated LSP and deoplete for that experiment. It is a tree-sitter issue (does not happen without it `nvim` goes 100% on one core forever). The highlighting itself seems to be fairly ok. So it seems to be nothing specific to this plugin. Closing....

`highlight_definition` has a performance issue on such files but it is not hosted in this repo anymore.

**Comment by maisiliym** [comment]
The issue here is not tree-sitter, but nvim blocking on it. Hence, the issue isnt solved yet.

**Comment by vigoux** [comment]
But we can't do anything about it here, hence this issue should be opened upstream.

**Comment by maisiliym** [comment]
There are two things nvim can do here; a tree-sitter cache, and the ability to delay and/or asynchronously-run the treesitter job (lazy highlight).

**Comment by vigoux** [comment]
WDYM by tree-sitter cache ?
Running the tree-sitter job asychronously is a track we are trying to follow, but is really complicated as async isn't handled by neovim.

**Comment by maisiliym** [comment]
>  tree-sitter cache ?

Treesitter is obviously computing the syntax tree; a cache would pre/post-compute this data to avoid having to recompute it for every `BufRead`

**Comment by vigoux** [comment]
@maisiliym We actually _must_ reproduce the syntax tree each time, as the file may have changed since last time we closed it.

Furthermore, parsing a file (even if it is insanely huge), should only take few miliseconds _at most_ (and furthermore is linear in the file length).

**Comment by maisiliym** [comment]
> @maisiliym We actually _must_ reproduce the syntax tree each time, as the file may have changed since last time we closed it.

 There are ways to solve this. Li is working on something that will do that.
 
> Furthermore, parsing a file (even if it is insanely huge), should only take few miliseconds _at most_ (and furthermore is linear in the file length).

This is off-topic

**Comment by vigoux** [comment]
Great you are saving us from that then, feel free to open a PR when you have a solution.
You are having a wrong understanding of the issue though, which was 

 > Is tree-sitter parsing / highlighting causing delay when opening big files ?

And the answer was no.

We don't have benchmarks (yet) but I am pretty convinced that tree-sitter highlighting / parsing may be faster than the legacy way of highlighting. And we have evidences that it _is_ faster in some cases.

As a side remark, every single discussion with you is just you on your high horse, and it is starting to be boring and irritating.

**Comment by kyazdani42** [comment]
agree with vigoux here. Although caching the tree might help a little, it might just cause more issues afterward.
I also do not think async highlighting is a solution, tried it in the past, and it doesn't feel right. Treesitter is a solution to avoid this kind of thing.
I did not experience any latency issue with languages I work with, and nvim is way faster than any other editor ive tried on huge files. although I didnt try opening a 90K Cpp file (which is imo not a common thing that might happen).

**Comment by maisiliym** [comment]
> As a side remark, every single discussion with you is just you on your high horse, and it is starting to be boring and irritating.

What discussion?

**Comment by maisiliym** [comment]
> async highlighting [...] doesn't feel right.

Anything worth mentionning?
Related: https://github.com/JasonWoof/vim-treesitter

**Comment by vigoux** [comment]
> Edit: The main issue is applying the highlight gradually, to avoid slowdowns.

This is how tree-sitter highlighting works today in neovim.

**Comment by VVKot** [comment]
Is there an issue for this upstream? Can't find one. Ironically, I hit this problem porting patch for neovim core, specifically in `edit.c`.

**Comment by maisiliym** [comment]
> Is there an issue for this upstream? Can't find one. Ironically, I hit this problem porting patch for neovim core, specifically in `edit.c`.

The issue is not upstream. A fix would require starting a coroutine that would apply the highlight *after* loading the buffer. The buffer could be read-only until then, to avoid obvious problems. Otherwise, the autocmd will lock the buffer until the parsing is done, no matter what.

**Comment by VVKot** [comment]
Ah, I think we're having different issues. The highlighting itself works totally fine for me, I am getting problems with `highlight_definitions`, which comes from different repo.

**Comment by i3d** [comment]
Noticed this when working on a some 3000+ line file using v0.6.0-dev+164-g50b30de20079. Disable highlight changed the UI responsiveness dramatically.  Is this issue closed with a solution or is it tracked by some other issues?

**Comment by sl8vz** [comment]
Also having similar issue with 100K + C file.
It takes 5+ seconds to open the file, barely able to navigate.
Setting additional_vim_regex_highlighting  to false doesn't change anything.
Wondering if there's any workaround or planned improvement ?

**Comment by theHamsta** [comment]
I have 3 weeks of vacation ahead of me. I had the plan to cap the parsing/querying to a timeout time and stop processing afterwards (defer to subsequent parsing calls)

**Comment by sl8vz** [comment]
Hi @theHamsta,

Nope not using additional module for TS, I use it only for syntax higlight.
I can try a more minimal config with only TS if that can help.

**Comment by dlvhdr** [comment]
I also have a 4mb json file and treesitter really causes nvim to hang.

**Comment by drewfish** [comment]
I have the same issue when editing a typescript file. I suspect that my issue is related to two things:  `indent = { enable = true }` in my treesitter setup, and a bug in my bash setup which causes each bash shell to take 3 seconds to start.

What I did to see the slowness:
* open a typescript file
* wait for LSP server to attach (2-3 seconds)
* `o` to start inserting a new line -- this hangs for 1.5 minutes

During the hang I see a lot of child processes like `/bin/bash -c unset nonomatch; vimglob() { while [ $# -ge 1 ]; do echo "$1"; shift; done }; vimglob >/Users/drew.folta/.tmp/nvimICBsfI/42 /Users/drew.folta/.local/share/nvim/site/pack/packer/start/editorconfig-vim/parser/$.*`

It seems that there are a lot of files in `~/.local/share/nvim/site/pack` which are processed (somehow).

**Comment by Twiggeh** [comment]
I have a 200k lines typescript file, that causes nvim to slow to a crawl with 100% cpu usage. I disabled all plugins except for tree-sitter, only happens with it enabled.

**Comment by Twiggeh** [comment]
@patrick96 Thank you, this worked for me !

Now on to find / do the same for lsp (Sorry I didn't know about :help yet :sweat_smile: )
