### ISSUE TITLE
Include support for TypoScript

### ISSUE THREAD

**Issue by Teddytrombone** [nvim-treesitter/nvim-treesitter#5561]
I have created a tree-sitter grammar for [TypoScript](https://github.com/Teddytrombone/tree-sitter-typoscript), the configuration and templating language of [TYPO3](https://typo3.org/).

Now my question is: are you willing to include this parser? If so I could prepare a PR. If you think there is no need for this feature just close this issue and I'll stick to including it locally in my nvim configuration 😊

Let me know what you think.

**Comment by clason** [comment]
No issue needed, just make a PR.
