### ISSUE TITLE
Windows Parser files not found

### ISSUE THREAD

**Issue by osherbz** [nvim-treesitter/nvim-treesitter#557]
**Describe the bug**
the path .../nvim/plugged/nvim-treesitter/parser is empty.

**To Reproduce**
1. Regular Installation.

**Expected behavior**
find *.so files in parser folder.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
    ========================================================================
   ## Installation
       OK: `git` executable found.
      - ERROR: `cc` executable not found.
       - ADVICE:
         - Install `gcc` with your package manager.
         - Install `clang` with your package manager.
         - Check that your `$PATH` is set correctly.
    
    ## cpp parser healthcheck
       - OK: cpp parser found.
       - OK: `highlights.scm` found.
       - OK: `locals.scm` found.
       - WARNING: No `textobjects.scm` query found for cpp
         - ADVICE:
         - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
       - OK: `folds.scm` found.
    

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-727-gc10c2fab5
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/
x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRE
CATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_V
AR_FROM -DMIN_LOG_LEVEL=3 -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/
include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

**Additional context**
This problem is that the parsers are working. I Installed all but only cpp shows in the healthcheck.(also cpp.so is not exist in parser folder).

EDIT: I started cmder(terminal) and run `:TSInstall all`, its works and my parser dir was full of *.so files.
I'm curios why when I started in default terminal the plugin worked but no *.so files.

**Comment by theHamsta** [comment]
We install to `:lua print(vim.fn.stddir('data'))`  /site/parser when the normal directory is not available. This might not be in runtime path on Windows.

This might also be related https://github.com/nvim-treesitter/nvim-treesitter/pull/558 (git fallback is broken when not having `unzip` installed`)

**Comment by osherbz** [comment]
> We install to `:lua print(vim.fn.stddir('data'))` /site/parser when the normal directory is not available. This might not be in runtime path on Windows. The parsers need to be in any subdirectory of `parser` in one of your runtime path folders.
> 
> This might also be related #558 (git fallback is broken when not having `unzip` installed`)
Oh! Thank you.
I will mention that, when the parsers are in the normal directory, neovim start faster,  50~ ms diff.
