### ISSUE TITLE
Certain queries of injected languages aren't applied (markdown)

### ISSUE THREAD

**Issue by ribru17** [nvim-treesitter/nvim-treesitter#5576]
### Describe the bug

Injected parsers do not properly inherit their superceding parsers (at least in the case of `html` and `html_tags`). 

### To Reproduce

1. Open a Markdown file with `markdown`, `markdown_inline`, and `html` parsers intalled. Sample buffer:
```md
<h1>Title</h1><u>Underlined</u>
```
2. Observe that `Underlined` is not underlined and `Title` is not highlighted as a title.

### Expected behavior

The inner text of the `h1` tag should link to `@text.title.1` and the inner text of the `u` tag should link to `@text.underline`

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.2.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.5.8-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Thu, 19 Oct 2023 22:52:14 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - comment             ✓ . . . .
  - commonlisp          ✓ ✓ ✓ . .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - diff                ✓ . . . .
  - dot                 ✓ . . . ✓
  - git_config          ✓ . . . .
  - git_rebase          ✓ . . . ✓
  - gitattributes       ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . .
  - go                  ✓ ✓ ✓ ✓ ✓
  - haskell             ✓ . ✓ . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - ini                 ✓ . ✓ . .
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - latex               ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - mermaid             ✓ . . . .
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - scheme              ✓ . ✓ . ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓
  - zig                 ✓ . ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1697887905

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

The missing highlights that are pointed out above are solely from the inherited `html_tags` parser. The base highlights from the actual `html` parser itself are still working properly.

This issue was also tested (and present) in Neovim nightly.

**Comment by lucario387** [comment]
:+1: But I think this has to be resolved from Neovim core itself

**Comment by lucario387** [comment]
@ribru17 Some weird cases with your issues here

`html` on its own doesn't have any highlighting for tags, it's part of `html_tags` yet when using `:Inspect` on `h1` and `u`, it shows `@tag.html` to be the applied mark, which means it is inherited. I suppose the issue goes deeper than what you have described

**Comment by ribru17** [comment]
Ah I see. Perhaps it has to do with the fact that the inner text relies on the position of both tags (and thus the `(#set! injection.combined)` directive), while the tags themselves can be highlighted independently? Just guessing. Thanks for the context.

**Comment by lucario387** [comment]
I'd say so.

**Comment by lucario387** [comment]
I will just close this because I've just seen the generated s-expr tree.
```
 (paragraph) ; [34:1 - 35:0]
  (inline) ; [34:1 - 31]
   (element) ; [34:1 - 14]
    (start_tag) ; [34:1 - 4]
     (tag_name) ; [34:2 - 3]
    (end_tag) ; [34:10 - 14]
     (tag_name) ; [34:12 - 13]
   (element) ; [34:15 - 31]
    (start_tag) ; [34:15 - 17]
     (tag_name) ; [34:16 - 16]
    (end_tag) ; [34:28 - 31]
     (tag_name) ; [34:30 - 30]
```

This suggests that only the tags are passed down, which is to be expected considering the parser is only receiving `html_tag` as a node, not the inner text nor the whole element

**Comment by lucario387** [comment]
>  I am assuming it is still a bug that, while the entire content of the combined injection is properly grouped, only nodes explicitly sent to the injected parser get highlighted

No, the entire content of the combined injection regions, for the example code you provided, are `<h1></h1><u></u>`

**Comment by ribru17** [comment]
But when there is, for example, `<u>Underline</u>`, the s-expr tree will contain
```
(element) ; [274:11 - 23] html
 (start_tag) ; [274:11 - 13] html
  (tag_name) ; [274:12 - 12] html
 (end_tag) ; [274:20 - 23] html
  (tag_name) ; [274:22 - 22] html
```
where `(element)` matches the entire text: tags and text inbetween. If this were an `html` file the tree would like like:
```
(element) ; [274:11 - 23] html
 (start_tag) ; [274:11 - 13] html
  (tag_name) ; [274:12 - 12] html
 (text) ; [274:14 - 19] html
 (end_tag) ; [274:20 - 23] html
  (tag_name) ; [274:22 - 22] html
```
Note that here the `(element)` still matches the entire content, and additionally the `(text)` node is captured properly

**Comment by lucario387** [comment]
Yes, but html and markdown inline aren't the same
Markdown inline injections:
```scheme
((html_tag) @injection.content
 (#set! injection.language "html")
 (#set! injection.combined))
```

Which means only the tag is considered for injections. Whatever goes between the tags are not part of the injection trees.

From markdown inline, the text is `<h1>Text</h1>`, But from the injected html tree, it's only `<h1></h1>`

**Comment by lucario387** [comment]
`(element)` does not matches the tag and text inbetween. It matches whatever it was thrown at, and in this case, it's just `<h1></h1>`

Consider the injected tree as an entirely different html file, without any text inbetween tags, and only tags and tag attributes.

**Comment by ribru17** [comment]
I see, thank you for the explanation.
