### ISSUE TITLE
C: expand macro before highlight 

### ISSUE THREAD

**Issue by duarm** [nvim-treesitter/nvim-treesitter#5612]
### Describe the highlighting problem

It's pretty common to place some keywords behind macros for various reasons like supporting more compilers, language extensions, etc...

The fact that treesitter apparently does not expand these macros before highlighting, results in some wrong highlights

### Example snippet that causes the problem

```c
#define se_internal static
se_internal enum se_log_type se__log_filter;
``` 

should highlight like this, since `se_internal` is essentially `static`

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/26150581/29a96b41-1664-472f-aa1d-5ce1a4a52b2e)

 `:InspectTree`
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/26150581/06601082-5562-48bf-a983-7b8aec3c4f3f)

but it highlights like this instead
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/26150581/8bff0426-6791-4868-b2da-1ba2839eeab0)

 `:InspectTree`
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/26150581/5919a0e0-86a5-4e40-8664-3deab01ecdf1)

### Example screenshot

Above

### Expected behavior

It expands the macro and realizes it's a storage_class_specifier inside of it, and highlights the following `enum` properly

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (0c49d6745b3fc4822ab02e0018770cd6383a779c) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v16.20.2 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.5.9-zen2-1-zen",
  sysname = "Linux",
  ...
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  ...
```

### Output of `nvim --version`

```
NVIM v0.10.0-dev-1438+g8405649f92
Build type: RelWithDebInfo
LuaJIT 2.1.1696795921
```

**Comment by amaanq** [comment]
tree-sitter is not an LSP or macro preprocessor

**Comment by duarm** [comment]
Who would solve this? Only an integration which expands the macro then conceals the text, perhaps?

**Comment by amaanq** [comment]
LSPs can solve this, like clangd

No, treesitter cannot just "know" it's a macro and ignore it - it's context-free highlighting

**Comment by lucario387** [comment]
Well that's what tree-sitter's `locals` was supposed to be, context-aware highlighting. But the idea was quickly scrapped because that should not be as LSPs already do that, and do that much better than what 
up-to-now-tree-sitter will ever be able to do

**Comment by mintelm** [comment]
> LSPs can solve this, like clangd
> 
> No, treesitter cannot just "know" it's a macro and ignore it - it's context-free highlighting

Can you tell me how I can make clangd solve this issue?
