### ISSUE TITLE
Add Typst language support

### ISSUE THREAD

**Issue by uben0** [nvim-treesitter/nvim-treesitter#5620]
The Typst language is a serious competitor to LaTeX, all infos on the official page https://typst.app

I wrote and maintain a TreeSitter grammar at https://github.com/uben0/tree-sitter-typst

This grammar is complete and works like a charm.

If this is legit candidate to be added to supported languages, I'd like to know what to do for it to be compatible with NeoVim. I saw the `queries` files follow a specific API. I do not use NeoVim my self, so maybe, someone interested in testing it and giving feed backs could help me. For instance, is there a document page describing the API of the `queries` file?

In my shallow understanding of the NeoVim TreeSitter plugin implementation, I see that the only requirements to add a new language is to add an entry in the `available-parsers` and add the corresponding `queries` file. Isn't it?

**Comment by ObserverOfTime** [comment]
Language support requests are tracked in #2282.
