### ISSUE TITLE
nvim crashes due to a python treesitter parser with error "undefined symbol: static_assert"

### ISSUE THREAD

**Issue by wookayin** [nvim-treesitter/nvim-treesitter#5623]
### Describe the bug

I think this is the same bug as #3305 (https://github.com/nvim-treesitter/nvim-treesitter/issues/3305#issuecomment-1674377851), which was closed without being resolved.

The bug: neovim crashes immediately with exit code 127.

```
❯❯❯ nvim --headless setup.py
nvim: symbol lookup error: $HOME/.vim/plugged/nvim-treesitter/parser/python.so: undefined symbol: static_assert
```

I guess this is due to a old Linux distro that lacks the `static_assert` symbol in the glibc/stdc++ lib.

System Information:

- Neovim v0.9.4 stable (installed from appimage)
- Ubuntu 20.04.6 LTS x86_64
- Treesitter parsers were download using `:TSUpdate`
- GLIBC version: (Ubuntu GLIBC 2.31-0ubuntu9.12) 2.31

Note: neovim nightly (0.10.x) has no problem for me.

### To Reproduce

```
nvim --clean -u minimal.lua -c TSUpdateSync -c q
nvim --clean -u minimal.lua --headless a.py
```

or activate the TS parser with `vim.treesitter.start(0, 'python')` on an empty buffer.

```lua
for name, url in pairs {
  ['nvim-treesitter'] = 'https://github.com/nvim-treesitter/nvim-treesitter',
} do
  local install_path = vim.fn.fnamemodify('/tmp/nvim_issue/' .. name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    print(vim.fn.system { 'git', 'clone', '--depth=1', url, install_path })
  end
  vim.opt.runtimepath:prepend(install_path)
end

vim.cmd [[
  set noswapfile
  set shadafile=/tmp/nvim_issue/shada
]]

local ts_configs = require("nvim-treesitter.configs")

---@diagnostic disable-next-line: missing-fields
ts_configs.setup {
  highlight = {
    enable = true
  }
}
```

### Expected behavior

No crash

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v16.0.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `$HOME/.miniforge3/envs/conda/bin/x86_64-conda-linux-gnu-cc` executable found. Selected from { "$HOME/.miniforge3/envs/conda/bin/x86_64-conda-linux-gnu-cc", "cc", "gcc", "clang", "cl", "zig" }
  Version: x86_64-conda-linux-gnu-cc (conda-forge gcc 12.2.0-19) 12.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.4.0-146-generic",
  sysname = "Linux",
  version = "#163-Ubuntu SMP Fri Mar 17 18:26:02 UTC 2023"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - comment             ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1692716794
```

### Additional context

-

**Comment by clason** [comment]
This indicates that you are using the wrong tree-sitter library (parser generated from master CLI with a release C library).

**Comment by wookayin** [comment]
Hmm after more debugging, I found this actually has something to do with the conda environment. Somehow I was using the v0.9.1 tag (c5a7533113b2deb7db899d387b877389cc8b6113).

So this happens when installing parsers inside a conda environment on a specific version of nvim-treesitter. I have no idea yet what makes difference between v0.9.1 and master (c5a7533113b2deb7db899d387b877389cc8b6113).

| nvim-treesitter        | Inside a conda environment | No conda environment |
|    ---                 | -------------------------- | -------------------- |
| v0.9.1                 | crashed                    | works OK             |
| master                 | works OK                   | works OK             |

Parsers were not generated from the grammar (I don't have the `tree-sitter` CLI in this environment), so probably the compiler/toolchains affected by conda messes up something.

**Comment by wookayin** [comment]
According to https://github.com/tree-sitter/tree-sitter-python/pull/235, this is actually a problem of tree-sitter python with regard to the STDC compatibility, which already has been fixed.

Since the latest version of nvim-treesitter (master) already includes this fix, I think this issue might be closed but I wish nvim-treesitter have more tagged release versions. What do you think?

**Comment by wookayin** [comment]
Actually this problem exists not only for python parsers but also for other parsers (e.g. c++, gitcommit, etc.), they also crashes with the same static_assert errors if built against an incompatible stdc++ library (in my case, coming from conda). Conda sucks. Even with the latest version of nvim-treesitter, nvim still can crash because some parsers still require up-to-date STDC.

Closing as nvim-treesitter can't help much with this. But we still need a better workaround to be more fool-proof.

**Comment by amaanq** [comment]
The workaround is to really not use custom-forked compilers, not the first time I've heard about this conda issue

**Comment by wookayin** [comment]
Yes, I agree that conda has really many annoying issues, but in some situations the use of conda is inevitable; also not all users are knowledgeable or aware of these hassles... when neovim is running under a conda environment it's not easy to avoid the wrong compiler being picked up by `$CC`.

**Comment by wookayin** [comment]
See also #5623

I think a good workaround (or suggested config for treesitter for those who might use conda) is to explicitly set `$CC` variable in their config so that we can ignore conda-configured `CC`.

e.g. put these lines in init.lua or anywhere before treesitter config:
```
  if vim.fn.executable("/usr/bin/gcc") > 0 then
    vim.env.CC = "/usr/bin/gcc"
  end
```
