### ISSUE TITLE
Look for compilers in `C:\msys2`

### ISSUE THREAD

**Issue by JakeIsMeh** [nvim-treesitter/nvim-treesitter#5642]
**Is your feature request related to a problem? Please describe.**
Currently the plugin only looks for compilers in path, which is a completely understandable decision.
However, on Windows, an issue arises, as it is not the best idea to add msys2 to path, as is often suggested, since the various subsystems distributed with msys2 may ship overlapping binaries, such as MINGW64 and UCRT64 both shipping GCC.

**Describe the solution you'd like**
The plugin should look for compilers under various msys2 subsystems in `C:\msys2\[subsystem]\bin`

**Additional context**
If this is an acceptable idea, I'd be willing to put in a PR for this, though I'm not sure where in the codebase I'd have to modify.

**Comment by clason** [comment]
Sorry, but no. The build systems are complex enough as they are, especially because of Windows.
