### ISSUE TITLE
Folding doesn't work, expression always returns 0

### ISSUE THREAD

**Issue by FalcoGer** [nvim-treesitter/nvim-treesitter#5643]
### Describe the bug

I am trying to use treesitter's folding mechanism, but whatever I do, it tells me

> E490: No fold found

I was trying to find some documentation if I maybe needed to enable folding in the treesitter configuration, but I couldn't find anything. The only mention in the docs is how to set it up with `foldexpr` and `foldmethod`, which I did.

Whenever I manually run `echo nvim_treesitter#foldexpr()` it always prints 0. I tried `zx` and `:edit` to reset folding information, but that also doesn't work.

Here is my testing configuration

[nvim.zip](https://github.com/nvim-treesitter/nvim-treesitter/files/13302558/nvim.zip)

### To Reproduce

1. Start nvim with `nvim -u nvim_test_config.vim /path/to/some/file` from where the testing configuration is (or edit the source line at the end of it)
2. Try to fold any block of text.
3. ???
4. No profit

I tested it with a cpp file, which was detected correctly by vim as `filetype=cpp`.
Testing with `zx` and also `zR` and `zM`, nothing works.

### Expected behavior

Blocks should fold in some way

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.2.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.15.0-84-generic",
  sysname = "Linux",
  version = "#93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - c_sharp             ✓ ✓ ✓ . ✓
  - cmake               ✓ . ✓ ✓ .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - diff                ✓ . . . .
  - dockerfile          ✓ . . . ✓
  - git_config          ✓ . . . .
  - git_rebase          ✓ . . . ✓
  - gitattributes       ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . .
  - go                  ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - http                ✓ . . . ✓
  - ini                 ✓ . ✓ . .
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - json5               ✓ . . . ✓
  - latex               ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - meson               ✓ . ✓ . ✓
  - ninja               ✓ . ✓ ✓ .
  - objc                ✓ ✓ ✓ ✓ ✓
  - passwd              ✓ . . . .
  - pem                 ✓ . ✓ . ✓
  - perl                ✓ . ✓ . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - phpdoc              ✓ . . . .
  - python              ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - ruby                ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - sql                 ✓ . . ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev-e59cf3b3a
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Additional context

NVim built from source.
I ran TSUpdate before the tests.
It never worked for me for some reason.

**Comment by clason** [comment]
:h vim.treesitter.foldexpr()

(The foldexpr in this repo is deprecated and will be removed.)

**Comment by FalcoGer** [comment]
> :h vim.treesitter.foldexpr()

This is documented nowhere in nvim-treesitter.

`:h nvim_treesitter#foldexpr()`

> 						  *nvim_treesitter#foldexpr()*
nvim_treesitter#foldexpr()~

Functions to be used to determine the fold level at a given line number.
To use it: >
  set foldmethod=expr
  set foldexpr=nvim_treesitter#foldexpr()
<

This will respect your 'foldminlines' and 'foldnestmax' settings.

Note: This is highly experimental, and folding can break on some types of
      edits. If you encounter such breakage, hitting `zx` should fix folding.
      In any case, feel free to open an issue with the reproducing steps.

**Comment by clason** [comment]
Yes, that's why I point it out here.

**Comment by dudarboh** [comment]
As OP,
I have spent hours trying to understand why treesitter's folding does not work in lazyvim by default.
I am quite new to vim and I would assume such a commonly used functionality would be available by default from the start to everybody trying to learn vim?

If the current method is not expected to work wouldn't it make sense to switch the default to:
`set foldmethod=syntax` or `set foldmethod=manual`?

**Comment by FalcoGer** [comment]
@dudarboh here is my fold configuration if you want it. I use a combined vim/nvim configuration by using soft links. adapt for your needs as required.

```vim
" =============================================================================
" Folding, :help fold -> All fold commands start with z
" Options for folds start at :help fcl
set foldenable

" auto open folds in these conditions
set foldopen=block,insert,jump,mark,percent,quickfix,search,tag,undo

function! MyFoldText()
    let line = getline(v:foldstart)
    let numberOfLines = 1 + v:foldend - v:foldstart
    let sub = substitute(line, '/\*\|\*/\|{{{\d\=', '', 'g')
    return v:folddashes .. sub .. ' (' .. numberOfLines .. ' Lines)'
endfunction

if has('nvim')
    " Treesitter folding
    " https://www.reddit.com/r/neovim/comments/16xz3q9/treesitter_highlighted_folds_are_now_in_neovim/
    set foldmethod=expr
    set foldexpr=v:lua.vim.treesitter.foldexpr()
    " set foldtext=v:lua.vim.treesitter.foldtext()
    set foldtext=MyFoldText()
else
    set foldmethod=syntax       " Fold based on indention levels.
    set foldtext=MyFoldText()
endif


" Folds with a level > foldlevel will be closed
" Setting 0 will close all folds
" Setting 99 ensures folds are open by default
set foldlevel=99
set foldlevelstart=-1
set foldnestmax=5               " Only fold up to this many nested levels.
set foldminlines=1              " Only fold if there are at least this many lines.
set fillchars=fold:·,foldopen:,foldclose:

" alias for fold current cursor position for convenience
nnoremap <silent> zz  za

highlight Folded ctermfg=14 ctermbg=236 gui=underdouble guisp=#008080 guifg=#00FFFF guibg=#303030

highlight SignColumn ctermfg=51 ctermbg=234 guifg=#00FFFF guibg=#1C1C1C
highlight LineNr ctermfg=11 ctermbg=234 guifg=#FFFF00 guibg=#1C1C1C
```
