### ISSUE TITLE
[Grammar Request] Support for GDB

### ISSUE THREAD

**Issue by FalcoGer** [nvim-treesitter/nvim-treesitter#5675]
## GDB

**Is your feature request related to a problem? Please describe.**

Want to use https://github.com/LiadOz/nvim-dap-repl-highlights with c++, I set up nvim-dap to use GDB, but it has no syntax highlighting. There is basic syntax highlighting for gdb in vim, but not for treesitter, which is what the plugin requires. It would also help with editing ~/.gdbinit

**Describe the solution you'd like**
A gdb language parser for gdb script should be written

**Describe alternatives you've considered**
N/A

**Additional context**
#2282

**Comment by clason** [comment]
Please add this to the pinned issue.
