### ISSUE TITLE
Indentation breaks in python unclosed '[' anywhere in file

### ISSUE THREAD

**Issue by BogdanTheGeek** [nvim-treesitter/nvim-treesitter#5679]
### Describe the bug

Automatic indentation inserts way too many indents in python when treesitter highlighting is enabled.

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/8824186/f0298b08-adf5-4d7a-9fa1-3cad76398d25)
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/8824186/0dbabd80-d181-4d0c-b724-e6f3b0c7e99d)
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/8824186/67a6d3de-79eb-4f5d-a94c-42e5d498df6d)

I have isolated the issue to treesitter by disabling all other plugins.
This seems to only happen in python, even if i disable indent in the setup function. The only way to get it to not do it is to disable highlight in the setup function.

I have tried older versions of neovim,  treesitter and nvim-treesitter with various errors or no effect.

### To Reproduce

nvim test.py
i
```py
def test():
    return "           [" 
```
:2
o

### Expected behavior

indentation continues at the same level as the previous line

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (9f398ca955d3329110d31ed523dac5275074948f) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.1.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 15.0.0 (clang-1500.0.40.1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.0.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103"
} ~

Parser/Features         H L F I J
  - arduino             ✓ ✓ ✓ ✓ ✓
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cmake               ✓ . ✓ . .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - diff                ✓ . . . .
  - git_config          ✓ . . . .
  - git_rebase          ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . .
  - go                  ✓ ✓ ✓ ✓ ✓
  - gomod               ✓ . . . ✓
  - gowork              ✓ . . . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓
  - zig                 ✓ . ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev-1507+g267c346e2
Build type: Release
LuaJIT 2.1.1699392533
Run "nvim -V1 -v" for more info
```

**Comment by lucario387** [comment]
Definitely a case of using syntax-based indent and not having syntax.

Either add `use_vim_regex_highlighting` into your config, or use treesitter indents

**Comment by lucario387** [comment]
Another reason: Duplicate of #1573

**Comment by BogdanTheGeek** [comment]
> Definitely a case of using syntax-based indent and not having `syntax on`.
> 
> Either add `additional_vim_regex_highlighting` into your config, or use treesitter indents

I have `syntax on` and `additional_vim_regex_highlighting` and treestitter indents
```lua
require'nvim-treesitter.configs'.setup {
  ensure_installed = { "c", "python", "lua", "vim", "help" },
  sync_install = false,
  auto_install = true,
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  indents = {
    enable = true,
  },
  playground = {
    enable = false,
    disable = {},
    updatetime = 25, -- Debounced time for highlighting nodes in the playground from source code
    persist_queries = false, -- Whether the query persists across vim sessions
    keybindings = {
      toggle_query_editor = 'o',
      toggle_hl_groups = 'i',
      toggle_injected_languages = 't',
      toggle_anonymous_nodes = 'a',
      toggle_language_display = 'I',
      focus_language = 'f',
      unfocus_language = 'F',
      update = 'R',
      goto_node = '<cr>',
      show_help = '?',
    },
    incremental_selection = {
       enable = true,
       keymaps = {
          init_selection = '<c-space>',
          node_incremental = '<c-space>',
          scope_incremental = '<c-s>',
          node_decremental = '<c-backspace>',
       },
    },
  }
}
```

**Comment by BogdanTheGeek** [comment]
> Another reason: Duplicate of #1573

thanks, i will follow this issue

**Comment by lucario387** [comment]
> I have `syntax on` and `additional_vim_regex_highlighting` and treestitter indents

Then something is off here. No, really, something is really off here. Treesitter indents never expose `[` inside a string like that. So it has to be syntax-based indentation. If you lazy load, there might be a case where indentexpr is not changed for the first buffer opened, so be aware of that. We don't recommend lazy loading nvim-treesitter, any side effects of it is entirely on you to handle
