### ISSUE TITLE
TSInstall all: Error during compilation

### ISSUE THREAD

**Issue by LoshanMoorthy** [nvim-treesitter/nvim-treesitter#5681]
I've been tinkering with this for a few days now, scouring Google for anyone facing a similar issue, but I've come up empty-handed.

So, here goes: 
When I use the command "TSInstall cpp" or any TSInstall for that matter - I keep hitting this error ->
 "nvim-treesitter[cpp]: Error during compilation - clang: error: no such file or directory: 'src/scanner.cc'^M."

I've double-checked that I have both GCC and Clang installed, and I've even tried uninstalling and reinstalling them, but no luck so far. Any help would be greatly appreciated!

**Comment by clason** [comment]
Update your nvim-treesitter. Your parser information is (way) out of date.

**Comment by LoshanMoorthy** [comment]
> Update your nvim-treesitter. Your parser information is (way) out of date.

By using TSUpdate? I've done that and it says "All parsers up to date"
