### ISSUE TITLE
[Rust highlight] macro_rules is highlighted as TSKeyword, despite what the documentation on TSFuncMacro says

### ISSUE THREAD

**Issue by fuine** [nvim-treesitter/nvim-treesitter#570]
In Rust files `use`/`extern` are being highlighted as `TSKeyword` which is noted by this section in the `rust/highlights.scm` file:

```
[
"break"
"const"
"default"
"dyn"
"enum"
"extern"
"fn"
"impl"
"let"
"macro_rules!"
"match"
"mod"
"move"
"pub"
"ref"
"return"
"static"
"struct"
"trait"
"type"
"union"
"unsafe"
"async"
"await"
"use"
"where"
(mutable_specifier)
(super)
; TODO(vigoux): attribute items should have some kind of injections
(attribute_item)
(inner_attribute_item)
 ] @keyword
```
This list is compliant with the [Rust list of keywords](https://doc.rust-lang.org/reference/keywords.html). However, the documentation for `TSInclude` quite ironically states:

> For includes: `#include` in C, `use` or `extern crate` in Rust, or `require` in Lua.

I'm not sure what the best course of the action would be here - whether to change the Rust highlighting to be similar with regards to other languages, or to let the highlighting respect the keywords list. In the latter case the documentation of `TSInclude` should be changed to not cause any confusion.

Furthermore, the same applies to `macro_rules` and `derive` (they are highlighted as keywords, even though I'd expect them to be highlighted as macros). `macro_rules` is even mentioned in the documentation for `TSFuncMacro`:

> For macro defined fuctions (calls and definitions): each `macro_rules` in Rust.

**Comment by kyazdani42** [comment]
I'm pretty sure it should be TSInclude, this is probably something we overlooked.

**Comment by kyazdani42** [comment]
mhhh actually you might not be using the last version, because in my highlights.scm file, use is TSInclude.

**Comment by fuine** [comment]
Hmm, that looks to be the case - after update the `use` and `crate` in `extern crate` is highlighted correctly, however `macro_rules`is still highglighted as a keyword, and so is `#[derive(...)]` statement

**Comment by kyazdani42** [comment]
not too sure about those, @vigoux was there a reason why derive is highlighted as TSType and macro_rules as keyword ?

**Comment by fuine** [comment]
@kyazdani42 just FYI I don't think `derive` is highlighted as TSType (at least on my setup it's highlighted as a keyword). What comes after derive should I guess be types, but on my setup they are highlighted as primitives. Should this be moved to another issue or should I modify this one?

**Comment by kyazdani42** [comment]
derive is actually highlighted as TSType:
```scheme
;; Assume that all `#[derive]` arguments are types
(meta_item
  (identifier) @type
  arguments: (meta_arguments (meta_item (identifier) @type))
  (#eq? @type "derive"))
```
Maybe juste modify the title. The discussion speaks for itself :)

**Comment by fuine** [comment]
![derive](https://user-images.githubusercontent.com/15677456/95689804-a9f13000-0c13-11eb-9dba-3231b8aad53f.png)
Well you say so, but for some reason my editor shows it differently :)

**Comment by kyazdani42** [comment]
indeed, all the `#[...]` is actually marked as attribute_item which is highlighted as a keyword. I'll let vigoux handle this because it seems this might be injection related but i'm not sure

**Comment by savq** [comment]
@vigoux, the problem with types not being highlighted properly has to do with the order of the queries.

Right now, the derive macros query is defined before more general attribute macros queries, so the highlighting gets overwritten. Changing the order of the definitions fixes it.

-------
The other highlighting problems have been solved already.

**Comment by stsewd** [comment]
Looks like this was fixed by https://github.com/nvim-treesitter/nvim-treesitter/pull/1535
