### ISSUE TITLE
Problems with `go.so` on Nix

### ISSUE THREAD

**Issue by cideM** [nvim-treesitter/nvim-treesitter#571]
I'm sorry for another Nix issue. I might link to this issue from the Nix Discourse later, but I thought I'd ask here first. Debugging these Nix/Neovim intersection issues is always tricky. Anyway...

Let's start with the error: `nvim foo.go` results in
```
Error detected while processing FileType Autocommands for "*":
E5108: Error executing lua ...er/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:78: attempt to index a nil value
Press ENTER or type command to continue
```

The `go.so` parser is installed like this
```
  treesitterGo = pkgs.vimUtils.buildVimPluginFrom2Nix rec {
    version = "latest";
    name = "tree-sitter-go-${version}";
    src = vimPluginsSources.treesitter-go;
    buildPhase = ''
      runHook preBuild
      mkdir -p parser/
      $CC -o parser/go.so -I$src/src -shared -Os -lstdc++ $src/src/parser.c
      runHook postBuild
    '';
  };
```
the result of this is that a `parser/go.so` folder is made available through my runtime path, at
```
/nix/store/pbi279nvpg7fm9kcspbivi1g98cb5hwr-vim-pack-dir/pack/foobar/start/tree-sitter-go-latest
```
which has the contents

```
$ tifa $ ls /nix/store/pbi279nvpg7fm9kcspbivi1g98cb5hwr-vim-pack-dir/pack/foobar/start/tree-sitter-go-latest/parser/
go.so
```

And indeed `TSInstallInfo` shows Go as being installed.

Now I'll install the Go parser again, but this time with `TSInstall go` and the issue is now gone! For the record, I ran `nix-shell -p clang` and then installed go so that's the compiler that was used here, but it works with `gcc` as well.

The two `go.so` files differ a bit (first one is the good one, second one fails). The weird date is to be expected in the nix builder env.

```
dotfiles (master|+12u1) $ ls -lah ~/.local/share/nvim/site/pack/nvim-treesitter/opt/nvim-treesitter/parser/go.so
Permissions Size User Date Modified Name
.rwxr-xr-x  185k tifa 11 Oct 23:52  /home/tifa/.local/share/nvim/site/pack/nvim-treesitter/opt/nvim-treesitter/parser/go.so

nvim-treesitter $ ls -lah /nix/store/hscb6hqfl60vajaib8klyjrdw4da9qgi-vim-pack-dir/pack/foobar/start/tree-sitter-go-latest/par
ser/
Permissions Size User Date Modified Name
.r-xr-xr-x  184k root  1 Jan  1970  go.so
```

There's not much I can do with these files though... 

I tried adding a `print` statement in[ `highlighter.lua`](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/treesitter/highlighter.lua#L78) since this is where the stack trace leads but it doesn't do anything.

```
  print(vim.inspect(self.parser:parse()))
```

I have no idea why this doesn't work. And now for thet ultimate kicker: I'm on NixOS and exactly the same code works on MacOS where I'm using Home Manager (Nix) to install things.

I kind of suspect that the compilation environment has something to do with things but I'm completely out of ideas on what to do next.

**Comment by theHamsta** [comment]
You need to use the version in the lock file lockfile.json. The current go parser is ABI incompatible with the current tree-sitter runtime of Neovim. Probably the runtime of Neovim will be updated soon so we can upgrade the Java python Go parser.

**Comment by theHamsta** [comment]
More to read #526. We've effectively pinned to parser version to the last one before the ABI update

**Comment by cideM** [comment]
Got it, thanks! With the lock file revision it works again.

**Comment by hurricanehrndz** [comment]
@cideM 

Here is derivation you can use for the parsers
https://github.com/hurricanehrndz/nixcfg/blob/main/nix/pkgs/nvim-treesitter-parsers.nix
