### ISSUE TITLE
Treesitter keymap not working as expected

### ISSUE THREAD

**Issue by grab-a-byte** [nvim-treesitter/nvim-treesitter#5719]
### Describe the bug

Using Ctrl+Space does not start a treesitter selection although the keymap in init.lua seems to specify otherwise (from using nvim and kickstart.nvim)
```
vim.defer_fn(function()
  require('nvim-treesitter.configs').setup {
    -- Add languages to be installed here that you want installed for treesitter
    ensure_installed = { 'c', 'cpp', 'go', 'lua', 'python', 'rust', 'tsx', 'javascript', 'typescript', 'vimdoc', 'vim', 'bash' },

    -- Autoinstall languages that are not installed. Defaults to false (but you can change for yourself!)
    auto_install = true,

    highlight = { enable = true },
    indent = { enable = true },
    incremental_selection = {
      enable = true,
      keymaps = {
        init_selection = '<C-space>',
        node_incremental = '<C-space>',
        scope_incremental = '<C-s>',
        node_decremental = '<M-space>',
      },
    },
}
```

filed issue with kickstart and was requested to bring it here.
https://github.com/nvim-lua/kickstart.nvim/issues/513

### To Reproduce

1) Fresh install of nvim and kickstart on windows 11 machine
2) Open init.lua file from kickstart folder
3) Type Ctrl+Space to try and init a treesitter selection
4) No action is performed within nvim

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.7.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `zig` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: info: Usage: zig [command] [options]
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.22631",
  sysname = "Windows_NT",
  version = "Windows 11 Pro"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.4
Build type: RelWithDebInfo
LuaJIT 2.1.1696883897
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

**Comment by lucario387** [comment]
Idk, it works for me while using `nvim --clean` with the minial repro

If the result of `nmap <C-space>` of yours doesn't look something like this:

```
n  <C-Space>   *@<Lua 197: ~/.local/share/nvim/site/pack/packer/start/nvim-treesitter/lua/nvim-
treesitter/incremental_selection.lua:14>                                                       
                 Start selecting nodes with nvim-treesitter 
```

Then that means kickstart.nvim is the culprit here

**Comment by grab-a-byte** [comment]
Hi there, thanks for your response. 
Using the command you provided it looks nigh on identical. 
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/30392071/86d9a8f9-cc62-4ed0-a04a-691e79b89a40)
Are there any further steps I can take to debug this?

**Comment by lucario387** [comment]
An extra step you can try is to do enter cmdline mode, press `Ctrl-V`, then `Ctrl-Space`. If the result doesn't show `:<C-Space>` then that means your terminal doesn't support this keybind

**Comment by grab-a-byte** [comment]
So hitting Ctrl + v in command line mode is simply pasting whatever is in my clipboard. I'm going to assume this is an issue caused by the terminal? I'm using windows 11 built-in Windows terminal.
I've tried installing the Cmder terminal emulator also and have the same behaviour happening on there.

**Comment by spflaumer** [comment]
iirc the alternative to ctrl+v on windows was ctrl+q; try to ctrl+q then ctrl+space

**Comment by spflaumer** [comment]
i'm also experiencing issues with keybinds, mine are:
```Lua
incremental_selection = {
    enabled = true,
    init_selection = "gts",
    node_incremental = "gni",
    scope_incremental = "gsi",
    node_decremental = "gdi",
}
```

**Comment by ryot1982** [comment]
Same here. I installed treesitter through kickstart.nvim but I don't think it matters.

It worked after changing the keymaps.

    # default
    init_selection = '<c-space>',
    node_incremental = '<c-space>'

    # changed
    init_selection = '<c-y>',
    node_incremental = '<c-y>'

**Comment by leviathan-n** [comment]
Same here.
I use lazyvim on Windows 11, and I can only run this command by searching key maps and select “Start selecting nodes with nvim-treesitter”.

**Comment by clason** [comment]
Do not lazy-load nvim-treesitter.

**Comment by cameronr** [comment]
If you find this from google and are on a Mac, <C-space> is likely being grabbed by OS for changing inputs as described here:

https://jay.gooby.org/2022/11/22/re-enabling-ctrl-space-shortcut-for-iterm-and-other-apps-under-macos-ventura
