### ISSUE TITLE
Highlighting sometimes creates strange rainbow patterns 🌈

### ISSUE THREAD

**Issue by kdurant** [nvim-treesitter/nvim-treesitter#572]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2704364/95728799-85966180-0cae-11eb-963a-c07615a06ce2.png)

**To Reproduce**
Often appear, but do not know the specific steps

**Comment by vigoux** [comment]
Hi, this is a duplicate of https://github.com/nvim-treesitter/nvim-treesitter/issues/65 from what I understand, could you provide _simple_ repro steps over at the other issue please ?
