### ISSUE TITLE
No parser for '4' language - E5108

### ISSUE THREAD

**Issue by PolarJunction** [nvim-treesitter/nvim-treesitter#573]
**Describe the bug**
Error detected while opening a .cpp file.

**To Reproduce**
1. Open a .cpp file
2. See error appear in window below.

Error:

> Error detected while processing FileType Autocommands for "*":
> E5108: Error executing lua ..eovim\share\nvim\runtime\lua\vim\treesitter\language.lua:20: no parser for '4' language, see :help treesitter-parsers

**Expected behavior**
Expected the file to open without error, and to highlight the file syntax.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - ERROR: `cc` executable not found.
    - ADVICE:
      - Install `gcc` with your package manager.
      - Install `clang` with your package manager.
      - Check that your `$PATH` is set correctly.

## c parser healthcheck
  - OK: c parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for c
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - OK: `folds.scm` found.

## cpp parser healthcheck
  - OK: cpp parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for cpp
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - OK: `folds.scm` found.

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-751-gd198aa511
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info

```

**Additional context**
Everything was working okay until I updated from NVIM v0.5.0-695-gf34eeba2d. Suspect  something has changed that introduced this error.

**Comment by vigoux** [comment]
Hi, thanks for reporting, this is due to a change upstream, could you try #574 to see if it fixes the issue ?

**Comment by PolarJunction** [comment]
> 
> 
> Hi, thanks for reporting, this is due to a change upstream, could you try #574 to see if it fixes the issue ?

#574 Corrects this issue for me, thanks!
