### ISSUE TITLE
(cpp) Non-field identifiers highlighted as `@field`

### ISSUE THREAD

**Issue by HumblePresent** [nvim-treesitter/nvim-treesitter#5731]
### Describe the highlighting problem

The query on lines 3-4 in `queries/cpp/highlights.scm` copied below applies the `@field` highlight to all identifiers starting with `m_` or `_`. While it may be common for field identifiers to start with `_`, I am finding that this query is too generic and results in a lot of non-field identifiers to be highlighted as fields. In particular, many compiler predefined macros and builtin functions start with a `_` but are not field identifiers.
```scheme
((identifier) @field
  (#lua-match? @field "^m?_.*$"))
```

### Example snippet that causes the problem

In the snippet below, `__GNUC__`, `__FILE__`, `__builtin_alloca`, and `_exit` are all highlighted with the `@field` group but are not field identifiers.
```cpp
#ifdef __GNUC__
#endif

int main()
{
    printf("%s", __FILE__);
    __builtin_alloca();
    _exit();
}
```

### Tree-sitter parsing result

```
(preproc_ifdef) ; [1:1 - 2:6]
 name: (identifier) ; [1:8 - 15]
(function_definition) ; [4:1 - 9:1]
 type: (primitive_type) ; [4:1 - 3]
 declarator: (function_declarator) ; [4:5 - 10]
  declarator: (identifier) ; [4:5 - 8]
  parameters: (parameter_list) ; [4:9 - 10]
 body: (compound_statement) ; [5:1 - 9:1]
  (expression_statement) ; [6:5 - 27]
   (call_expression) ; [6:5 - 26]
    function: (identifier) ; [6:5 - 10]
    arguments: (argument_list) ; [6:11 - 26]
     (string_literal) ; [6:12 - 15]
      (string_content) ; [6:13 - 14]
     (identifier) ; [6:18 - 25]
  (expression_statement) ; [7:5 - 23]
   (call_expression) ; [7:5 - 22]
    function: (identifier) ; [7:5 - 20]
    arguments: (argument_list) ; [7:21 - 22]
  (expression_statement) ; [8:5 - 12]
   (call_expression) ; [8:5 - 11]
    function: (identifier) ; [8:5 - 9]
    arguments: (argument_list) ; [8:10 - 11]
```

### Example screenshot

The screenshots below show how several non-field identifiers have semantically correct highlights that are being overwritten by the `@field` highlight group because they start with a `_`. I am using a custom colorscheme in these screenshots, but no custom queries are in use, so this behavior should be independent of the colorscheme.

#### Highlight groups applied to `__GNUC__`
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/60856003/f2cef8bf-599b-4a04-8aa1-a646fe714cfa)

#### Highlight groups applied to `__FILE__`
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/60856003/558dc1ad-a41a-4229-84f9-a9e3310878f0)

#### Highlight groups applied to `__builtin_alloca`
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/60856003/dc901fc9-ae39-4967-9019-e1094f2dbe5c)

#### Highlight groups applied to `_exit`
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/60856003/432f8f10-ccbb-44d0-a350-a47deb7b0c63)

### Expected behavior

I expect non-field identifiers to not be highlighted with the `@field` highlight group even if they start with a `_`.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- WARNING `node` executable not found (only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.5.9-arch2-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Thu, 26 Oct 2023 00:52:20 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cmake               ✓ . ✓ ✓ .
  - comment             ✓ . . . .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - diff                ✓ . . . .
  - git_config          ✓ . . . .
  - git_rebase          ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . .
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - linkerscript        ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luap                ✓ . . . .
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - proto               ✓ . ✓ . .
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - rust                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - udev                ✓ ✓ . . ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev-ee276f8
Build type: RelWithDebInfo
LuaJIT 2.1.1700008891
Run "nvim -V1 -v" for more info
```

### Additional context

I believe this issue could be solved by making a small change to the query such that it only matches identifiers that start with `m_`.
```scheme
((identifier) @field
  (#lua-match? @field "^m_.*$"))
```

**Comment by theHamsta** [comment]
I would be fine with that change. Do you want to create a PR?

**Comment by HumblePresent** [comment]
Sure, I'll submit a PR.
