### ISSUE TITLE
Inconsistent indentation with markdown lists and conceallevel set

### ISSUE THREAD

**Issue by antonk52** [nvim-treesitter/nvim-treesitter#5739]
### Describe the bug

I noticed that in markdown files when 4 spaces indent level is used and conceallevel is set to either one 1 | 2 | 3, the first item in a nested list displayed under a different indentation level than other items. For example please let's see these two examples

One with 4 spaces for indentations
```markdown
- one
    - two one
    - two two
    - two three

- [ ] one
    - [ ] two one
    - [ ] two two
    - [ ] two three
```

This is how it is rendered by github 

---
- one
    - two one
    - two two
    - two three

- [ ] one
    - [ ] two one
    - [ ] two two
    - [ ] two three
---

Another one with 2 spaces for indentations
```markdown
- one
  - two one
  - two two
  - two three

- [ ] one
  - [ ] two one
  - [ ] two two
  - [ ] two three
```

This is how it is rendered by github 

---
- one
  - two one
  - two two
  - two three

- [ ] one
  - [ ] two one
  - [ ] two two
  - [ ] two three
---

The following is what it looks it based wether 4 or 2 spaces used for indentation and whether I use treesitter or builtin functionality to highlight markdown content
![Screenshot 2023-11-29 at 11 37 48](https://github.com/nvim-treesitter/nvim-treesitter/assets/5817809/27f04a38-0db4-4350-a5c9-a468c7c0e6ce)

### To Reproduce

1. Ensure you have `markdown` and `markdown_inline` parsers installed and enabled
2. Create a markdown file
3. Paste the following content
  ```
  - one
      - two one
      - two two
      - two three
  
  - [ ] one
      - [ ] two one
      - [ ] two two
      - [ ] two three
  ```
  4. Set conceallevel=3

### Expected behavior

Expect `two one` and `two two` items to be displayed with the same indentation level

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v16.14.2 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 15.0.0 (clang-1500.0.40.1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.1.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - graphql             ✓ . . ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ .
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```
```


### Output of `nvim --version`

```text
▲ nvim --version
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/Users/antonk52/homebrew/Cellar/neovim/0.9.4/share/nvim
"

Run :checkhealth for more info
```
```


### Additional context

I am unsure whether this is a bug with markdown parser or treesitter itself. It seems that parser works as expected as it correctly marks nodes as list items.

**Comment by ribru17** [comment]
You're right, sorry about that. I'll take a look later today when I have time to see if there is anything that can be done to fix this

**Comment by lucario387** [comment]
When sw=4, markdown parser does something funny with the list marker. As you can see, only for the first list item, the range of `-` also covers 2 spaces before it. 
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/29790821/14a4f402-5769-4a64-bcf7-21c586ebe31f)

**Comment by lucario387** [comment]
I'm using `EditQuery` to capture the image above. So no `#offset!` should be affecting that.

**Comment by ribru17** [comment]
It seems like any number of spaces from 2-5 is valid (at least according to the parser) and spaces greater than two are captured at the beginning of the list marker (but only for the first list item it looks like). I could be wrong but I think the only solution would be to hard-code the offset for each of the possible indentation cases with `#eq?`, or just reverting the conceals if it's too much trouble

**Comment by clason** [comment]
> or just reverting the conceals if it's too much trouble

I think that's the best approach then; hard-coding item positions is just too much.

You could also raise an issue with the parser; if the white space can be made consistent, we can re-enable this.
