### ISSUE TITLE
C++ using ns-name::member-name highlight

### ISSUE THREAD

**Issue by SR-MyStar** [nvim-treesitter/nvim-treesitter#5747]
### Describe the bug

If I use ```using namespace std;``` to remove the ```std::``` prefix, the highlight color of the cout is red, and the highlight color of the format is orange.
![2023-11-30-20-45-22-area](https://github.com/nvim-treesitter/nvim-treesitter/assets/139795416/66129e0f-c5b7-49c5-9b84-f9ba90ff663e)
But if I use ```using std::format, std::cout``` to remove the ```std::``` prefix for std::format and std::cout, the highlight color of the cout is white, and the highlight color of the format is blue.
![2023-11-30-20-45-42-area](https://github.com/nvim-treesitter/nvim-treesitter/assets/139795416/f4d8bd72-80fb-4544-87ef-905459d27c98)

### To Reproduce

1. Install catppuccin neovim theme
2. Open a cpp file
3. Include bits/stdc++.h header file
4. Input ```using std::format, std::cout; int main(void) { int n = rand(); cout << format("n = {}\n", n); return 0; }```
5. Look at the color of ```cout``` and ```format```
6. delete ```using std::format, std::cout; int main(void) { int n = rand(); cout << format("n = {}\n", n); return 0; }```
7. Input ```using namespace std; int main(void) { int n = rand(); cout << format("n = {}\n", n); return 0; }```
8. Look at the color of ```cout``` and ```format```

### Expected behavior

The highlight color of the C++ standard library object should be red, and the highlight color of the C++ standard library function should be orange, after I use ```using std::member-name``` to remove the ```std::``` prefix.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (0c49d6745b3fc4822ab02e0018770cd6383a779c) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v21.2.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.6.1-zen1-1-zen",
  sysname = "Linux",
  version = "#1 ZEN SMP PREEMPT_DYNAMIC Wed, 08 Nov 2023 16:05:16 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cmake               ✓ . ✓ ✓ .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - diff                ✓ . . . .
  - git_config          ✓ . . . .
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - json5               ✓ . . . ✓
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - luap                ✓ . . . .
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - ninja               ✓ . ✓ ✓ .
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rasi                ✓ ✓ ✓ ✓ .
  - regex               ✓ . . . .
  - rst                 ✓ ✓ . . ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev-53cc835
Build type: RelWithDebInfo
LuaJIT 2.1.1700008891
Run "nvim -V1 -v" for more info
```

### Additional context

My neovim config ```https://github.com/SR-MyStar/MyNeovimDots```

**Comment by clason** [comment]
That's not from Treesitter; that's from LSP semantic tokens.
