### ISSUE TITLE
Does treesitter handle indentation?

### ISSUE THREAD

**Issue by lynndylanhurley** [nvim-treesitter/nvim-treesitter#575]
I'm currently using [vim-polyglot](https://github.com/sheerun/vim-polyglot) for indentation + syntax highlighting.

My understanding of treesitter is that it mainly handles syntax highlighting.

If I switch from polyglot to this plugin, will I lose indentation support?

**Comment by vigoux** [comment]
I don't think you will lose _all_ indentation. Though, you might encounter a change is polyglot is doing really advanced tricks for indentation, as you'll be using stock indentation.

Please have a look at https://github.com/nvim-treesitter/nvim-treesitter/issues/332 too, I'll close this issue in favour of the aforementioned.

**Comment by lynndylanhurley** [comment]
Thanks @vigoux. So just to be clear, indentation is currently outside the scope of this project, but may be added at some point in the future?

**Comment by vigoux** [comment]
I think it is inside the scope of this project ! Atm I think @kyazdani42 is working on this, as this issue interested him.
Feel free to reach out on the zulip channel to give your opinion  / feedback on the dev process !

**Comment by kyazdani42** [comment]
@lynndylanhurley you can follow development of the feature at #577
