### ISSUE TITLE
Highlighting doesn't appear when buffer opened on VimEnter autocmd. 

### ISSUE THREAD

**Issue by mageowl** [nvim-treesitter/nvim-treesitter#5750]
### Describe the bug

I created an auto command to run when I open neovim to source my `Session.vim`, however files that are opened don't have syntax highlighting, and you either have to use `set ft=[your filetype]` or you have to close and reopen the buffer.

### To Reproduce

1. Add an auto command like so:
```lua
autocmd("VimEnter", {
    callback = function (ev)
        if vim.fn.bufexists("./Session.vim") then
            vim.cmd("source ./Session.vim")
        end
    end
})
```
2. Open a file, and use `:mksession!` to create a `Session.vim` file.
3. Quit and reopen vim
4. No syntax highlighting is displayed.

### Expected behavior

Highlighting is automatically applied to the files opened by `Session.vim`.

### Output of `:checkhealth nvim-treesitter`

```markdown
──────────────────────────────────────────────────────────────────────────────
+WE 54 lines: nvim-treesitter: require("nvim-treesitter.health").check()···················································································
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev-1164+g23c21e763
Build type: RelWithDebInfo
LuaJIT 2.1.1694940244
Run ":verbose version" for more info
```

**Comment by lucario387** [comment]
Sorry, but this is not enough to resolve anything

**Comment by mageowl** [comment]
Is there something I can provide to help with the issue?

**Comment by clason** [comment]
Autocommands can't trigger other autocommands by default, so this won't work. `:h autocmd-nested`.
