### ISSUE TITLE
Don't conceal code blocks on Markdown files by default

### ISSUE THREAD

**Issue by polirritmico** [nvim-treesitter/nvim-treesitter#5751]
### Describe the bug

Hi, after merging PR #5414, the code blocks are now concealed along with the language of the block. I think this shouldn't be the default behavior because currently, there isn't a simple or straightforward way to disable them individually (refer to #2825) without modifying the `scm` file.

On the other hand, to enable this, there are two documented methods:

1. In `after/queries/markdown/highlights.scm` with `; extends`.
2. Through `vim.treesitter.query.set()`.

It seems there isn't a consensus on this issue, as I recall reading some messages along these lines: [#4801](https://github.com/nvim-treesitter/nvim-treesitter/issues/4801#issuecomment-1546845938). I don't know what changed, but when editing markdown files with a lot of code blocks one after the other, it's really difficult to determine where one block starts or where it ends without seeing the backticks. Similarly, when you have a lot of unfinished blocks this conceal makes it difficult to identify the correct block without the language information.

Regards.

### To Reproduce

1. `set conceal=2`
2. Open a markdown file with this content:

\``` language
\# Some code
\```

### Expected behavior

Default to don't conceal the backticks and language of code blocks until there is a way to remove/disable them individually. For users that want this, add the code snippet in the docs.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.6.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Gentoo 13.2.1_p20230826 p7) 13.2.1 20230826
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.1.57-gentoo",
  sysname = "Linux",
  version = "#2 SMP PREEMPT_DYNAMIC Mon Nov 13 11:06:51 -03 2023"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - rust                ✓ ✓ ✓ ✓ ✓
  - sql                 ✓ . . ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
```

### Output of `nvim --version`

```text
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes-std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/usr/include/luajit-2.1 -I/usr/include -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.9.4/work/neovim-0.9.4_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.9.4/work/neovim-0.9.4_build/include -I/var/tmp/portage/app-editors/neovim-0.9.4/work/neovim-0.9.4_build/cmake.config -I/var/tmp/portage/app-editors/neovim-0.9.4/work/neovim-0.9.4/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include

system vimrc file: "/etc/vim/sysinit.vim"
fall-back for $VIM: "/usr/share/nvim"
```

**Comment by clason** [comment]
Sorry, this is deliberate, since the Markdown parser is used for LSP documentation (which requires that). Right now, conceal is all or nothing; if you want to customize this, best to copy and edit the queries in your config.

**Comment by LJFRIESE** [comment]
For future searchers, the minimal fix for this is:

For future searchers, the minimal fix for this is to use the following:
```
require('vim.treesitter.query').set(
      'markdown',
      'highlights',
      [[
;From MDeiml/tree-sitter-markdown
[
  (fenced_code_block_delimiter)
] @punctuation.delimiter
]]
```

I have this right in my treesitter config = function({...})

**Comment by louwers** [comment]
This makes it very hard to see where code blocks are...

**Comment by MichaelAquilina** [comment]
Just thought it wou

> For future searchers, the minimal fix for this is to use the following:
> 
> ```
> require('vim.treesitter.query').set(
>       'markdown',
>       'highlights',
>       [[
> ;From MDeiml/tree-sitter-markdown
> [
>   (fenced_code_block_delimiter)
> ] @punctuation.delimiter
> ]]
> ```
> 
> I have this right in my treesitter config = function({...})

Thanks for this!

I do find that this default is quite confusing. There's a similar situation with json it seems.

It makes editing a lot harder than it used to be :(
