### ISSUE TITLE
Error detected while processing FileType Autocommands for "*"

### ISSUE THREAD

**Issue by ChrisAmelia** [nvim-treesitter/nvim-treesitter#579]
> Error detected while processing FileType Autocommands for "*":
E5108: Error executing lua ...nvimyVAdOT/usr/share/nvim/runtime/lua/vim/treesitter.lua:144: attempt to concatenate local 'lang' (a table value)
Error executing vim.schedule lua callback: Vim(lua):E5108: Error executing lua ...nvimyVAdOT/usr/share/nvim/runtime/lua/vim/treesitter.lua:144: attempt to concatenate local 'lang' (a table value)

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## c parser healthcheck
  - OK: c parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for c
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - OK: `folds.scm` found.

## java parser healthcheck
  - OK: java parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `textobjects.scm` query found for java
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `folds.scm` query found for java
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-751-gd198aa511
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Additional context**
The above error is appearing when I open a java file.  
Actual commit 06452845d63ac553

**Comment by vigoux** [comment]
Nooks like you are using an old version of neovim, could you try with latest master?

**Comment by ChrisAmelia** [comment]
I believe this is the latest appimage? Got it with ` wget https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage`.

**Comment by vigoux** [comment]
Then this app image version is fairly old, latest commit is at 759a05407f3e75cc002c0950563388735e969a94, which is not you nvim version here.

**Comment by kuator** [comment]
@vigoux, same error, I even reloaded my pc. 
ps: the build hasn't been updated yet
![image](https://user-images.githubusercontent.com/25168308/95853209-de313180-0d76-11eb-93d8-5030640bfa09.png)

**Comment by vgeof** [comment]
Hello,  I have the same issue with the nightly ppa version :
:version
NVIM v0.5.0-dev

**Comment by vgeof** [comment]
I fixed the issue by reverting last commit : 
commit 06452845d63ac553f3f9c5167e895e7c815a3f8f
fix(highlights): use new highlighter interface

**Comment by smartding** [comment]
installing `neovim-git`  aur on archlinux does fix the problem.

**Comment by kuator** [comment]
Bleeding edge is a good way to bleed, after all.

**Comment by kuator** [comment]
Staying on bleeding edge is a good way to bleed, after all.

**Comment by ChrisAmelia** [comment]
Fixed with latest appimage.

**Comment by antidotejack** [comment]
how do I get the latest appimage.
