### ISSUE TITLE
BASH: Process substitution inside parameter expansion breaks tree

### ISSUE THREAD

**Issue by artem-nefedov** [nvim-treesitter/nvim-treesitter#5791]
### Describe the bug

The specific case of using process substitution inside parameter expansion breaks highlighting, and ERRORs are seen in `:InspectTree`.

The same line doesn't cause any problems on [TS playground](https://tree-sitter.github.io/tree-sitter/playground).

### To Reproduce

The line that causes the problem:

```bash
some-command ${foo:+--arg <(printf '%s\n' "$foo")}
```

Removing double-quotes around `$foo` fixes the highlighting, although `:InspectTree` output still shows ERRORs.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v21.3.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 15.0.0 (clang-1500.1.0.2.5)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.1.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - ... <redacted>

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev-1843+gef38fdfdc-Homebrew
Build type: Release
LuaJIT 2.1.1700008891
```

**Comment by ObserverOfTime** [comment]
A. This is a [tree-sitter-bash](https://github.com/tree-sitter/tree-sitter-bash) issue.
B. I don't think that does what you expect it to.

**Comment by artem-nefedov** [comment]
@ObserverOfTime The line does the following:
If `$foo` is defined and is not empty, pass contents of `$foo` as a a file argument to `--arg` option of `some-command`.

So, if `$foo` is empty, it will be just `some-command`.
If `$foo` is not empty, it will become `some-command --arg /dev/fd/<id>`, where `/dev/fd/<id>` has contents of `$foo`.

Very useful to conditionally pass an option that only accepts a file without having to create an actual file or named pipe yourself.
