### ISSUE TITLE
Install parser with lua assumes 'master' branch

### ISSUE THREAD

**Issue by BonaBeavis** [nvim-treesitter/nvim-treesitter#580]
```
require "nvim-treesitter.parsers".get_parser_configs().zig = {
  install_info = {
    url = "https://github.com/GrayJack/tree-sitter-zig",
    files = {"src/parser.c"}
  }
}
```
Only works when the repo has a 'master' branch but 'main' is the new 'master'.

**Comment by theHamsta** [comment]
```
require "nvim-treesitter.parsers".get_parser_configs().zig = {
  install_info = {
    url = "https://github.com/GrayJack/tree-sitter-zig",
    files = {"src/parser.c"},
   branch = 'main',
  }
}
```
I guess I added  #517 for the zig parser.

**Comment by theHamsta** [comment]
Apparently, the zig parser improved a bit. The last time I checked there were only errors.

**Comment by theHamsta** [comment]
I guess we could add it to the official parsers. If you want you can create a PR for it.

**Comment by theHamsta** [comment]
@BonaBeavis is this really an issue? Downloading from other branches should work. E.g.
```
  require "nvim-treesitter.parsers".get_parser_configs().wat = {
    install_info = {
      url = "https://github.com/wasm-lsp/tree-sitter-wasm",
      files = {"src/parser.c"},
      branch = 'main',
      location = 'tree-sitter-wat/wat',
    },
  }
```

**Comment by BonaBeavis** [comment]
@theHamsta this works, it is only I left out the `branch` key, it defaulted to master and gave an misleading error message `Error during tarball extraction`.

**Comment by theHamsta** [comment]
Sorry about the error message.
