### ISSUE TITLE
Cpp and markdown parsers not compile

### ISSUE THREAD

**Issue by FedericoBruzzone** [nvim-treesitter/nvim-treesitter#5800]
### Describe the bug

I'm trying to install the cpp and markdown parser but I get this compilation error

<img width="880" alt="image" src="https://github.com/nvim-treesitter/nvim-treesitter/assets/99926684/dbbad333-8713-4fa2-be6b-f4041d1fdae7">

<img width="879" alt="image" src="https://github.com/nvim-treesitter/nvim-treesitter/assets/99926684/1ee44ee4-5ab7-4e21-937b-706d9706d960">

### To Reproduce

I have automatic plugin installation, when I open a cpp or markdown file I get this error

### Expected behavior

Installing the cpp/markdown parsers

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v21.2.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `clang` executable found. Selected from { "clang" }
  Version: Apple clang version 15.0.0 (clang-1500.0.40.1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "23.1.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:27 PDT 2023; root:xnu-10002.41.9~6/RELEASE_X86_64"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . .
  - javascript          ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - ocaml               ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - scala               ✓ ✓ ✓ . ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.9.4/share/nvim"

Run :checkhealth for more info
```

**Comment by lucario387** [comment]
Properly this. https://github.com/tree-sitter/tree-sitter-cpp/commit/2c93b82af7674e82e862d03133fd7abe6bd23cf0

Update your nvim-treesitter to latest version first

**Comment by FedericoBruzzone** [comment]
> Properly this. [tree-sitter/tree-sitter-cpp@2c93b82](https://github.com/tree-sitter/tree-sitter-cpp/commit/2c93b82af7674e82e862d03133fd7abe6bd23cf0)
> 
> Update your nvim-treesitter to latest version first

I'm using the latest version of nvim-treesitter. 
I just removed and reinstalled tree-sitter and I also have the same problem with the vim parser.

**Comment by theHamsta** [comment]
Oh, no apple clang strikes again. The compiler seems to hint that it's missing symbols from the C standard librarry. Others that filed this issue for other projects on GitHub compiled for a target for which they to have missing the C library. Other parsers don't seem to have this problem probably because they don't use any symbols from the c standard library 

Could you double check:
- you have a Intel Mac (as indicated by the arch reported by neovim). You run a x86 binary of neovim.
- your compiler by default targets x86_64 and not arm64 or arm64 for iOS

As a hacky work-around, could you try whether `export CFLAGS=-DNDEBUG=1` helps? Static_asserts shouldn't cause any symbol dependencies as they are static assertions at compile time (there must be real `assert` in the code)

**Comment by FedericoBruzzone** [comment]
I hadn't read this message, but as you say the problem is that the symbols of the standard library are missing, in this case the use of `assert` causes this problem. `_Static_assert` is not a part of stdlib @lucario387 

Compiling using `clang`, this code 
```c
// test.c

#include <assert.h>
#include <stdio.h>

int main(int argc, char *argv[]) {
  assert(argc == 1);
  printf("Hello, world!\n");
  return 0;
}
```
produce
```
ld: Undefined symbols:
  ___assert_func, referenced from:
      _main in test-a125d7.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
But using `clang++` compiles, with
```clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]```

@theHamsta thank you for your help.
So, answering your questions:
1. I recently got this mac and was trying it out, and it's an intel. `uname -m` produces `x86_64`
2. `file $(which nvim)` produces `/usr/local/bin/nvim: Mach-O 64-bit executable x86_64`

Until last week I was using a Unix machine, before retracing my steps I would like to try to give this Mac a little hope :'D

do you know how to fix this problem?

**Comment by clason** [comment]
> I recently got this mac and was trying it out, and it's an intel. uname -m produces x86_64

Are you sure? Apple stopped selling Intel Macs quite a while ago. It sounds rather that you're using an x86_64 terminal on an arm64 Mac. What's your terminal?

**Comment by FedericoBruzzone** [comment]
> > I recently got this mac and was trying it out, and it's an intel. uname -m produces x86_64
> 
> Are you sure? Apple stopped selling Intel Macs quite a while ago. It sounds rather that you're using an x86_64 terminal on an arm64 Mac. What's your terminal?

It's not a new Mac, I borrowed this Mac from a friend of mine :D
Anyway, I'm using kitty

**Comment by clason** [comment]
Then I'd recommend re-installing the XCode CLI tools for your OS.
