### ISSUE TITLE
Slight delay in the opening of Kotlin files

### ISSUE THREAD

**Issue by anthony-S93** [nvim-treesitter/nvim-treesitter#5810]
https://github.com/nvim-treesitter/nvim-treesitter/assets/69449791/bcf5dcfe-17bc-4ae1-a1bc-201830d1ffa1

As you can see, there is a slight delay in the loading of kotlin files, which used to be instantaneous. I must also point out that this delay has nothing to do with the size of the file being opened. Here is a video of the same delay occuring for a kotlin file with only two lines: 

https://github.com/nvim-treesitter/nvim-treesitter/assets/69449791/f52d4165-7a88-4070-80fa-d532b7fac3cf

I did open a similar issue here last month but was advised to open an issue at `tree-sitter-kotlin` instead, which I did: fwcd/tree-sitter-kotlin#107

The tests conducted by the developers over at `tree-sitter-kotlin` yielded nothing unusual (mean parsing time of `8.1ms`), which led me to believe that something in the plugin is causing the delay after all. 

**Additional Info:** 
Note that the delay disappears completely after I rolled back the plugin to commit `7b26b085` and reinstalled the parser.
 
https://github.com/nvim-treesitter/nvim-treesitter/assets/69449791/4b652647-9c71-44d1-a870-0827aac280fe

After rolling back to `7b26b085`, the opening of kotlin files is back to being instantaneous. 

These tests are conducted using the following minimal config:
```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({"config", "data", "state", "cache"}) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

--bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "--single-branch",
        "https://github.com/folke/lazy.nvim.git",
        lazypath,
    })
end
vim.opt.runtimepath:prepend(lazypath)


--install plugins
local plugins = {
    {
        "nvim-treesitter/nvim-treesitter",
        build = ":TSUpdate",
    },
}

require("lazy").setup(plugins, { root = root .. "/plugins", })

--setup treesitter
local ok, treesitter = pcall(require, "nvim-treesitter.configs")
if ok then
    treesitter.setup({
        ensure_installed = { "kotlin" },
        highlight = { enable = true },
    })
end
```

I will pin the plugin to `7b26b085` for now until this issue is resolved.

**Comment by amaanq** [comment]
Can you check whether 8996612bfbebe1657e1bb55a95201c96cab945c6 or b09d645098844d1fc250ef8c7087846e4bdae32f causes the regression, that'll tell us if it's us or upstream

**Comment by anthony-S93** [comment]
> Can you check whether [8996612](https://github.com/nvim-treesitter/nvim-treesitter/commit/8996612bfbebe1657e1bb55a95201c96cab945c6) or [b09d645](https://github.com/nvim-treesitter/nvim-treesitter/commit/b09d645098844d1fc250ef8c7087846e4bdae32f) causes the regression, that'll tell us if it's us or upstream

Hello. Thank you for getting back to me. Please note that I was able to reproduce the delay using both of the aforementioned commits. Every commit after `7b26b085` is affected.

**Comment by lucario387** [comment]
So 8996612bfbebe1657e1bb55a95201c96cab945c6 is the culprit. which means tree-sitter-kotlin's commit  0ef87892401bb01c84b40916e1f150197bc134b1 is the problem

**Comment by anthony-S93** [comment]
> So [8996612](https://github.com/nvim-treesitter/nvim-treesitter/commit/8996612bfbebe1657e1bb55a95201c96cab945c6) is the culprit. which means tree-sitter-kotlin's commit 0ef87892401bb01c84b40916e1f150197bc134b1 is the problem

I already mentioned this [here](https://github.com/fwcd/tree-sitter-kotlin/issues/107#issuecomment-1806863237) last month. No response yet so far.

**Comment by gmr458** [comment]
I am also having this problem

**Comment by theHamsta** [comment]
> > So [8996612](https://github.com/nvim-treesitter/nvim-treesitter/commit/8996612bfbebe1657e1bb55a95201c96cab945c6) is the culprit. which means tree-sitter-kotlin's commit 0ef87892401bb01c84b40916e1f150197bc134b1 is the problem
> 
> I already mentioned this [here](https://github.com/fwcd/tree-sitter-kotlin/issues/107#issuecomment-1806863237) last month. No response yet so far. Here is the developer's benchmarking results:
> 
> ```
> hyperfine --warmup 3 'tree-sitter parse examples/Logger.kt' -N
> Benchmark 1: tree-sitter parse examples/Logger.kt
>   Time (mean ± σ):       8.1 ms ±   0.6 ms    [User: 3.4 ms, System: 2.1 ms]
>   Range (min … max):     7.4 ms …  11.7 ms    256 runs
> ```

Please also check `tree-sitter query` with nvim-treesitter queries (might need modifications for predicates to be accepted by upstream tree-sitter). Often delays didn't happen due to slow parsing but inefficiencies in the query algorithm of Tree-Sitter with specific queries.

An alternative is using neovim with perf where neovim is launched sufficiently often with a kotlin file to gather samples with perf

**Comment by anthony-S93** [comment]
> . Often delays didn't happen due to slow parsing but inefficiencies in the query algorithm of Tree-Sitter with specific queries after specific grammar changes.

After your feedback, I decided to dig into this a little bit deeper. I'm unfortunately not experienced and familiar enough with the inner workings and benchmarking tools of treesitter and/or this plugin to perform the benchmarks you specified. Therefore, the approach I will take involves only the basic process of elimination. Here are my findings:

I first created a new environment for the tests using the following minimal config:
```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({"config", "data", "state", "cache"}) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

--bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "--single-branch",
        "https://github.com/folke/lazy.nvim.git",
        lazypath,
    })
end
vim.opt.runtimepath:prepend(lazypath)


--install plugins
local plugins = {
    {
        "nvim-treesitter/nvim-treesitter",
        build = ":TSUpdate",
    },
}

require("lazy").setup(plugins, { root = root .. "/plugins", })

--setup treesitter
local ok, treesitter = pcall(require, "nvim-treesitter.configs")
if ok then
    treesitter.setup({
        ensure_installed = { "kotlin" },
        highlight = { enable = true },
    })
end
```

As you pointed out above, the `queries` might be the culprit. So I `cd`-ed into the `nvim-treesitter` repo and deleted the `queries/kotlin` directory, and then opened a kotlin test file to see if the problem went away. The delay disappeared, which means you are on the right track. 

There are four files inside the `queries/kotlin` directory: `fold.scm`, `highlights.scm`, `injections.scm`, and `locals.scm`

I further discovered that the issue only went away after the `highlights.scm` file had been removed. The obvious conclusion here is that one of the query statements inside `highlights.scm` is causing the problem. 

After further testing, I managed to pinpoint the exact query statement inside `highlights.scm` that's causing the issue: 

```
(class_body
	(property_declaration
		(variable_declaration
			(simple_identifier) @property)))
```
Which occured at lines 30 to 33 inside `queries/kotlin/highlights.scm`

I hope these tests help.

**Comment by lucario387** [comment]
Replacing the query above with
```scheme
((simple_identifier) @property
  (#has-parent? @property variable_declaration))
```

Seems to lessen the issue

**Comment by anthony-S93** [comment]
@lucario387 
Yes. The query you suggested does remove the delay on my system. 

@theHamsta 
Should we just go ahead and replace the query? The alternative would be to fix this elsewhere so that the original query won't lead to a delay.

**Comment by lucario387** [comment]
Feel free to do a PR. I will check on it later
