### ISSUE TITLE
Svelte highlighting not working

### ISSUE THREAD

**Issue by synic** [nvim-treesitter/nvim-treesitter#5839]
### Describe the bug

Highlighting for svelte just doesn't seem to want to work. I've attached a screenshot

<img width="728" alt="image" src="https://github.com/nvim-treesitter/nvim-treesitter/assets/30906/bcc88e0b-6095-470f-87ac-c1fd84a50fcc">

of note, typescript, css, html all work on their own, but the svelte file won't highlight 

### To Reproduce

1. Run `:TSInstall svelte typescript javascript css html`
2. Open .svelte file
3. Observe that it is not highlighted

### Expected behavior

It should be highlighted

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v18.16.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 15.0.0 (clang-1500.1.0.2.5)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.2.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - graphql             ✓ . . ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - svelte              ✓ . ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

```

### Output of `nvim --version`

```text
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.4/share/nvim"

Run :checkhealth for more info
```

**Comment by lucario387** [comment]
I cannot reproduce it so I don't know what happened :). Can you also provide a minimal reproducible template ?

**Comment by ashtyn3** [comment]
Same issue

**Comment by synic** [comment]
Hi! I think I must have messed something up. I created a minimal config, and it's working there, and now it's working in my main config. I am not sure what I did to fix it, if anything.

Here's the minimal config just for fun, in case @lucario387 is still having issues and wants to try it out.

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

--bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--single-branch",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

--install plugins
local plugins = {
	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
	},
}

require("lazy").setup(plugins, { root = root .. "/plugins" })

--setup treesitter
local ok, treesitter = pcall(require, "nvim-treesitter.configs")
if ok then
	treesitter.setup({
		ensure_installed = { "typescript", "css", "javascript", "svelte" },
		highlight = { enable = true },
	})
end
```

**Comment by lucario387** [comment]
I was just asking for a more reproducible version since I myself have not run into this issue. Closing this since it seems to be resolved

**Comment by synic** [comment]
Sorry, I meant @ashtyn3. But yeah, seems fixed for me. Thank you!

**Comment by HeavenTao** [comment]
> Hi! I think I must have messed something up. I created a minimal config, and it's working there, and now it's working in my main config. I am not sure what I did to fix it, if anything.
> 
> Here's the minimal config, in case @ashtyn3 is still having issues and wants to try it out.
> 
> ```lua
> local root = vim.fn.fnamemodify("./.repro", ":p")
> 
> -- set stdpaths to use .repro
> for _, name in ipairs({ "config", "data", "state", "cache" }) do
> 	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
> end
> 
> --bootstrap lazy
> local lazypath = root .. "/plugins/lazy.nvim"
> if not vim.loop.fs_stat(lazypath) then
> 	vim.fn.system({
> 		"git",
> 		"clone",
> 		"--filter=blob:none",
> 		"--single-branch",
> 		"https://github.com/folke/lazy.nvim.git",
> 		lazypath,
> 	})
> end
> vim.opt.runtimepath:prepend(lazypath)
> 
> --install plugins
> local plugins = {
> 	{
> 		"nvim-treesitter/nvim-treesitter",
> 		build = ":TSUpdate",
> 	},
> }
> 
> require("lazy").setup(plugins, { root = root .. "/plugins" })
> 
> --setup treesitter
> local ok, treesitter = pcall(require, "nvim-treesitter.configs")
> if ok then
> 	treesitter.setup({
> 		ensure_installed = { "typescript", "css", "javascript", "svelte" },
> 		highlight = { enable = true },
> 	})
> end
> ```

Thanks! It works for me.

**Comment by txtyash** [comment]
I was facing the same issue, adding `highlight = { enable = true },` fixed it for me.
