### ISSUE TITLE
New user experience: Move `.setup` call to the main module

### ISSUE THREAD

**Issue by chrisgrieser** [nvim-treesitter/nvim-treesitter#5844]
Just a minor issue: Right now, the plugin is setup with `require('nvim-treesitter.configs').setup(…)`. 

However, the informal "convention" in the nvim-plugin-ecosystem is to have the `setup` available in the main module: `require('nvim-treesitter').setup(…)`. This is not just nitpicking, since plugin managers like `lazy.nvim` expect the setup call to be in the main module for the `opts` key in its plugin specification. (And future plugin managers are likely to also rely on that convention.)

While this can be solved by adding `main = "nvim-treesitter.configs"`, it is a small extra hurdle to do so. nvim-treesitter being one of the first plugins that beginners will install, it would make the new-user-experience a bit smoother. Had recently helped out an acquaintance starting to use nvim and who stumbled over exactly that issue, wondering why their treesitter config was not working.

**Comment by lucario387** [comment]
Closing as this is already done for the rewrite (`main` branch)
