### ISSUE TITLE
Broken syntax highlighting on *.luau files

### ISSUE THREAD

**Issue by ThatMG393** [nvim-treesitter/nvim-treesitter#5862]
### Describe the highlighting problem

I just installed luau ts using `:TSInstall` and it looks like that (all luau files looks like that) and some parts are highlighted probably because of the lsp.

On other languages, I never get this issue

### Example snippet that causes the problem

 No snippets available.

### Tree-sitter parsing result

![Screenshot_20240106_115658_Termux](https://github.com/nvim-treesitter/nvim-treesitter/assets/73651803/7acbf895-b68c-494b-93db-fd53dcc66a8c)
![Screenshot_20240106_115749_Termux](https://github.com/nvim-treesitter/nvim-treesitter/assets/73651803/b3f733f9-dd26-44e8-b92e-47a753a592eb)

### Example screenshot

![Screenshot_20240106_114742_Termux](https://github.com/nvim-treesitter/nvim-treesitter/assets/73651803/cd5a7b8c-0d72-4c3f-a88e-1a08f02de6bf)

### Expected behavior

Normal Highlighting

### Output of `:checkhealth nvim-treesitter`

```markdown
Installation
  - OK tree-sitter found 0.20.8 (parser generator, only needed for :            TSInstallFromGrammar)
 - OK node found v20.2.0 (only needed for :TSInstallFromGrammar)
 - OK git executable found.
 - OK cc executable found. Selected from { vim.NIL, "cc", "gcc",               "clang", "cl", "zig" }
   Version: ^[[48;2;98;98;98mWelcome to TERMUX!^[(B^[[m^[(B^[[m^[(B^[[m
 - OK Neovim was compiled with tree-sitter runtime ABI version 14              (required >=13). Parsers must be compatible with runtime ABI.
   
OS Info:                                                                   {
   machine = "armv8l",
   release = "4.14.186-27775459",
   sysname = "Linux",                                                       
   version = "#1 SMP PREEMPT Thu Nov 30 12:47:00 KST 2023"
}
                                                                                  
     Parser/Features         H L F I J
      - lua                 ✓ ✓ ✓ ✓ ✓
      - luau                ✓ ✓ ✓ ✓ ✓                                             
      - python              ✓ ✓ ✓ ✓ ✓   
                                                                                                                      Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
             +) multiple parsers found, only one will be used                   
             x) errors found in the query, try to run :TSUpdate {lang}
```

### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/data/data/com.termux/files/usr/share/nvim"
```

### Additional context

I'm using Termux

**Comment by clason** [comment]
>  and some parts are highlighted probably because of the lsp.

No an nvim-treesitter (or, in general, tree-sitter) problem then.
