### ISSUE TITLE
Add `@injection.shebang` for setting the language in `injections.scm`

### ISSUE THREAD

**Issue by tgross35** [nvim-treesitter/nvim-treesitter#5870]
**Is your feature request related to a problem? Please describe.**

Parsing shebangs in tree-sitter is possible, but extremely difficult to get correct without a fairly complex external scanner. Being able to do this is useful for nested languages if a direct injection specifier isn't available.

**Describe the solution you'd like**

Helix provides an `@injection.shebang` capture that gets parsed by the editor and the language extracted. Adding this to nvim-treesitter would be great!

Docs: https://docs.helix-editor.com/guides/injection.html#capture-types

Based on a quick search, they use this for Nix, Markdown (as a fallback), and typst.

Adding a field to `parsers.lua` for common shebanged languages, but a simple fallback that extracts `#!\S*bin\S*[/ ](?<executor>\s+)` would probably work for most cases

**Describe alternatives you've considered**

Making this an official feature of tree-sitter, I will open an issue.

**Comment by lucario387** [comment]
Let's hope someone implemented it :)
Also, this needs to be done from neovim. Nvim-treesitter cannot control injection captures, so please report the enhancement requests to Neovim

**Comment by tgross35** [comment]
Whoops, thanks for the pointer! Opened https://github.com/neovim/neovim/issues/26939

**Comment by lucario387** [comment]
Another pointer here :) 
We can fake this with injection.language and gsub. Just that it's snail slow

**Comment by clason** [comment]
I think this is a mistake as it is way too specific and can just as well be done with `injection.language`. (I don't see how this would be any slower than a direct implementation, which would also have to be based on `gsub`.)
