### ISSUE TITLE
node not found error after upgrading to neovim 0.9.5 on macOS

### ISSUE THREAD

**Issue by jdhao** [nvim-treesitter/nvim-treesitter#5877]
### Describe the bug

After upgrading neovim to latest stable 0.9.5, I am seeing the following errors when I check the vim help file:

> ERR 2024-01-08T10:50:58.526 nvim.56602.0 decor_provider_invoke:47: error in provider treesitter/highlighter:line: Error executing lua: ...im/0.9.5/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 615 for language vimdoc
stack traceback:
	[C]: in function '_ts_parse_query'
	...im/0.9.5/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'get'
	....5/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:50: in function 'new'
	....5/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:202: in function 'get_query'
	....5/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:228: in function 'fn'
	...5/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:345: in function 'for_each_tree'
	....5/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:214: in function 'on_line_impl'
	....5/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:290: in function <....5/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:284>

I have tried to run `TSUpdate` to fix the issue, but it does not help. What works for me to fix the issue:

1. Run the command `TSUinstall all` to remove all the parsers.
2. Restart nvim and install all needed parsers again (I am using the following config so the needed parsers will be installed automatically for me)

```lua
require("nvim-treesitter.configs").setup {
  ensure_installed = { "python", "cpp", "lua", "vim", "json", "toml" },
  ignore_install = {}, -- List of parsers to ignore installing
  highlight = {
    enable = true, -- false will disable the whole extension
    disable = { 'help' }, -- list of language that will be disabled
  },
}
```

After this, the error seems to be gone.

### To Reproduce

This is the original steps that trigger the error. Now that I have fixed the error, I can not reproduce anymore.

1. upgrade neovim to 0.9.5 using homebrew: `brew upgrade neovim`
2. open nvim and check the help doc `:h zc`
3. move the cursor up and down

### Expected behavior

No error occurs.

### Output of `:checkhealth nvim-treesitter`

```markdown
Now that I have fixed the error, not sure if the output is still relevant.
```

### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim"

Run :checkhealth for more info
```
```


### Additional context

_No response_

**Comment by clason** [comment]
`TSInstall vimdoc`

**Comment by jdhao** [comment]
I am also seeing the following error when trying to unistall the parsers

> ERROR Parser for vimdoc is installed! But not by nvim-treesitter! Please manually remove the following files: /opt/homebrew/Cellar/neovim/0.9.5/1ib/nvim/parser/vimdoc.so

so it seems that somehow treesitter is trying to find the parsers in the wrong location.

**Comment by clason** [comment]
No, that's not what's going on. (That message is not really helpful, and nvim-treesitter will behave very differently in 1.0). The issue is that the queries for vimdoc in nvim-treesitter target a different version of the parser than the one that is shipped with Neovim. So you _must_ install the compatible version with nvim-treesitter as well.
