### ISSUE TITLE
Not recognizing the filetype go.mod file for the gomod module

### ISSUE THREAD

**Issue by khanakia** [nvim-treesitter/nvim-treesitter#5880]
### Describe the bug

Ref: https://github.com/camdencheek/tree-sitter-go-mod/issues/13

I am using **gomod** module to highlight `.mod` files and it's not working for the file `go.mod`

because it takes the filetype as `rapid`

when I run this `:set filetype=gomod` manually for a file then highlighting works fine.

## BEFORE
![Screenshot 2024-01-09 at 9 53 34 PM](https://github.com/nvim-treesitter/nvim-treesitter/assets/2174170/1dd1d2bd-8dec-4c6d-a8de-7e206d189b1e)

## After setting :set filetype=gomod
![Screenshot 2024-01-09 at 9 53 46 PM](https://github.com/nvim-treesitter/nvim-treesitter/assets/2174170/b9bd7276-e33c-4ad2-b7cd-51900fd90de0)

### To Reproduce

1. nvim go.mod

### Expected behavior

It should highlight properly

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v18.17.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 15.0.0 (clang-1500.1.0.2.5)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.2.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - elixir              ✓ ✓ ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - gomod               ✓ . . . ✓
  - gosum               ✓ . . . .
  - heex                ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
nvim --version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim"

Run :checkhealth for more info
```

**Comment by lucario387** [comment]
Filetype setting are not handled by nvim-treesitter. Preferably, this should be done from vim, then backported to neovim

**Comment by clason** [comment]
Or set up on your own: `:h vim.filetype.add()`.

**Comment by khanakia** [comment]
But the **gomod** author filetypes are auto handled then why I need to set manually ?

https://github.com/camdencheek/tree-sitter-go-mod/issues/13#issuecomment-1883353115
```
If you use neovim, I'd recommend using [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter), which should set the filetype automatically for gomod.
```

**Comment by clason** [comment]
That claim is false; all filetype detection has been removed.

**Comment by khanakia** [comment]
@camdencheek will you be able to shed some light here please if possible?

I need to fix the highlighting for the go.mod files

**Comment by clason** [comment]
Your issue is with Vim's (not Neovim's!) filetype detection strategy; you need to bring it up with them. There's nothing to do here.
