### ISSUE TITLE
FR: `auto_install = true` should also auto-install "injection-only" parsers like `luadoc` or `regex`

### ISSUE THREAD

**Issue by chrisgrieser** [nvim-treesitter/nvim-treesitter#5888]
**Is your feature request related to a problem? Please describe.**
The simplest, plug-n-play config for treesitter (which is also the default, if I am not mistaken), is to set:
```lua
auto_install = true,
ensure_installed = {},
```
This will keep the parsers installed to a minimum, but also install any parser that is needed.

However, there is one drawback: special "injection-only" parsers like `luadoc` or `regex` do not appear to trigger the condition for `auto_install` of "install when entering buffer", since there will never be a something like luadoc-buffer.

**Describe the solution you'd like**
`auto_install = true` should also auto-install "injection-only" parsers like `luadoc` or `regex`. 

**Describe alternatives you've considered**
1. Setting `ensure_installed = "all"`. This ensures you always have complete syntax highlighting, but it has the drawback that you always install a total of 200+ parsers, most of you never use. (And also update those parsers on any update of nvim-treesitter, resulting basically in notification-spam.)
2. Set `ensure_installed` to a manually kept a list of all "injection-only" parsers and occasionally look at the list of available parsers if there is a new "injection-only" parser that you might add. This is not very straightforward, I assume even many experienced users are not aware that such parsers exist, let alone are able to identify from the list of available parsers which ones are such extra parsers and which ones are not (e.g. `luap` vs `luau`).

**Additional context**
The current situation means that users that do not change their treesitter-config to `ensure_installed = "all"` or manually find and install the "injection-only" parsers will have an "incomplete" treesitter-experience. For instance, having `luap`, `luadoc`, and `comment` installed on top of the `lua` parser is a marked and noticeable improvement to syntax highlighting that many users will simply miss out on since they aren't aware that those exist.

**Comment by lucario387** [comment]
Not really in favor of that. `comment` was and still is causing performance issues, if auto_install enforces the installation of `comment` parser then the way going forward will be no queries having `comment` by default

**Comment by chrisgrieser** [comment]
I don't think one individual parser having issues is really a reason to against the general idea? The auto-installation of injection-only parsers could simply exclude experimental parsers to avoid such issues.

**Comment by lucario387** [comment]
I only brought up the most controversial one, which is `comment`. 

The problems are below:
- Too many injection queries
  - In this case, excluding won't really work. Users still have to delve into the queries to know which injections are supported, which I don't think goes well with "automatically install injected parsers". JS is the most obvious example here. Not to mention users' custom injections. 
- Injections queries capturing too broadly
  - Example was `graphql` inside JS, nix's dynamic injections (noted a week or two later after proposal). Possibly many more I'm not remembering. 
- The injected language's parser leads to performance issue on moderately large files:
  - Users will need to do manual searching to know which is bad to exclude. This still means users need to look at the queries

Yes, having an easier way to install "injection-only" parsers is nice. But the need to look at injection queries to uninstall/exclude them isn't.

**Comment by clason** [comment]
I think this is too complicated. Reducing complication (and thus increasing maintainability) is one of the goals of the 1.0 rewrite on main. Please test that branch if it improves things for you, otherwise I am afraid it is "wontfix".

(In case you aren't aware, injection is handled by Neovim core so nvim-treesitter has no idea it's happening.)
