### ISSUE TITLE
Broken Tree Sitter install of parser

### ISSUE THREAD

**Issue by jpx40** [nvim-treesitter/nvim-treesitter#5911]
### Describe the bug

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/92295347/f9116e60-bdbf-4c96-8880-90b232523861)

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/92295347/13e1cafb-d99d-4d79-991f-44e865272e0b)

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/92295347/3c398b3e-66dd-4723-bad5-1185cca621fa)

https://github.com/nvim-treesitter/nvim-treesitter/commit/fe89bf17197fc5daead3878fb1328911b30fb022
U need to remove this commit it brakes tree sitter.

### To Reproduce

Re install nvim treesitter

### Expected behavior

Install works

### Output of `:checkhealth nvim-treesitter`

```markdown
normal
```

### Output of `nvim --version`

```text
Version 9.5
```

**Comment by clason** [comment]
You need to provide minimal reproducible steps.

**Comment by clason** [comment]
Your error is unrelated to the change. Find all the directories mentioned in your error and make sure they are deleted. Then update the plugin(s) and try again.

**Comment by wookayin** [comment]
See also #5913
