### ISSUE TITLE
You need to provide minimal reproducible steps.

### ISSUE THREAD

**Issue by jpx40** [nvim-treesitter/nvim-treesitter#5912]
You need to provide minimal reproducible steps.

_Originally posted by @clason in https://github.com/nvim-treesitter/nvim-treesitter/issues/5911#issuecomment-1896560308_
            Hey i am using the Nvim distro Lazvim on Arch Linux. I updatet my packages with Lazy and then noticed that there was somthing wrong with treesitter so reinstalled  all packages (removed nvim from ~/.local ) and then this happened.

Sry that are the steps now

**Comment by clason** [comment]
Not good enough. Please read the template and fill it out diligently. And try to extract a minimal example so we can know what exactly goes wrong for you.

**Comment by jpx40** [comment]
ok
