### ISSUE TITLE
Broken Parser Installation

### ISSUE THREAD

**Issue by jpx40** [nvim-treesitter/nvim-treesitter#5913]
### Describe the bug

I notticed that this could be related to this commit https://github.com/nvim-treesitter/nvim-treesitter/commit/fe89bf17197fc5daead3878fb1328911b30fb022

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/92295347/ca848119-3871-44b9-9aa9-7e3ed6657509)
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/92295347/2545ec8a-d347-4cd9-97d0-a70393861d8c)
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/92295347/ba2a8146-9e24-4c1f-8bd7-bc2bd56b0516)

### To Reproduce

1. Lazy Vim Update, Error occured
2. Reinstalled all Nvim Packages Same Error

### Expected behavior

The iinstall of tree sitter Parser should work

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v21.6.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.7.0-zen3-1-zen",
  sysname = "Linux",
  version = "#1 ZEN SMP PREEMPT_DYNAMIC Sat, 13 Jan 2024 14:36:54 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - bibtex              ✓ . ✓ ✓ .
  - c                   ✓ ✓ ✓ ✓ ✓
  - cmake               ✓ . ✓ ✓ .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - diff                ✓ . . . .
  - dockerfile          ✓ . . . ✓
  - eex                 ✓ . . . ✓
  - elixir              ✓ ✓ ✓ ✓ ✓
  - gitignore           ✓ . . . .
  - go                  ✓ ✓ ✓ ✓ ✓
  - gomod               ✓ . . . ✓
  - gosum               ✓ . . . .
  - gowork              ✓ . . . ✓
  - heex                ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - ini                 ✓ . ✓ . .
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - json5               ✓ . . . ✓
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - julia               ✓ ✓ ✓ ✓ ✓
  - latex               ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luap                ✓ . . . .
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - ninja               ✓ . ✓ ✓ .
  - ocaml               ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - r                   ✓ ✓ . ✓ ✓
  - reason              ✓ ✓ . . ✓
  - regex               ✓ . . . .
  - ron                 ✓ ✓ ✓ ✓ ✓
  - rst                 ✓ ✓ . . ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ .
  - sql                 ✓ . . ✓ ✓
  - svelte              ✓ . ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - v                   ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - vue                 ✓ . ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓
  - zig                 ✓ . ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
```

### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742
```

**Comment by clason** [comment]
> I notticed that this could be related to this commit https://github.com/nvim-treesitter/nvim-treesitter/commit/fe89bf17197fc5daead3878fb1328911b30fb022

It really is not.

**Comment by clason** [comment]
If you need help understanding what is asked of you, _ask_. But stop opening the same issue over and over again.

**Comment by jpx40** [comment]
> If you need help understanding what is asked of you, _ask_. But stop opening the same issue over and over again.

pls test pushes to master before you commit in the future

**Comment by wookayin** [comment]
@jpx40 There were **extensive** amount of tests and efforts you probably don't know. But we there might be issues or errors that might happen on the user side, that we could not capture perfectly. Sorry for the inconvenience, but it seems that your issue has nothing to do with the breaking changes.

In your specific case try `rm -rf /path/to/nvim-treesitter/parsers`

**Comment by lucario387** [comment]
(To be more clear) OP's first part of the issue is related to the commit (double curl to the same place), the second part of failing to compile isn't related at all
