### ISSUE TITLE
Errors with installing parsers 

### ISSUE THREAD

**Issue by Qpernicus** [nvim-treesitter/nvim-treesitter#5916]
### Describe the bug

I use Windows… sadly.  Most recently Treesitter was throwing errors on updating/installing parsers.. All parsers in commit fe89bf1 give an error the file already exists and is not empty. But on Windows I cannot delete the files in Users/Me/Appdata/Local/Nvim-data/ because some program (presumably some part of nvim) is using them. Kinda chicken and egg-like. 

The error in Nvim showing is the same for all parsers:

```
nvim-treesitter[yaml]: Failed to execute the following command:
{
  cmd = "cmd",
  opts = {
    args = { "/C", "if", "exist", "C:\\Users\\ME\\AppData\\Local\\nvim-data\\tree-sitter-yaml", "rmdir", "/s", "/q", "C:\\Users\\ME\\AppData\\Local\\nvim-data\\tree-sitter-yaml" },
    stdio = {
      [2] = <userdata 1>,
      [3] = <userdata 2>
    }
  }
}
The process cannot access the file because it is being used by another process.^M
```

With the subsequent error:

```
nvim-treesitter[markdown]: Error during download, please verify your internet connection
fatal: destination path 'tree-sitter-markdown' already exists and is not an empty directory.
```

### To Reproduce

1) Open nvim either via terminal or qt-app in windows
2) Errors start, have to ENTER several times before continuing 

### Expected behavior

I can delete files/force an update so treesitter does what it needs to 

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (0c49d6745b3fc4822ab02e0018770cd6383a779c) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.11.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `zig` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: info: Usage: zig [command] [options]
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.22631",
  sysname = "Windows_NT",
  version = "Windows 11 Enterprise"
} ~

Parser/Features         H L F I J

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1703942320
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
```

**Comment by Qpernicus** [comment]
> > But on Windows I cannot delete the files in Users/Me/Appdata/Local/Nvim-data/
> 
> I think that's the actual issue here. Delete the parser directory any way you can and then try again.
> 
> Also share your (relevant, minimal) config.

I'll look into possibilities (and triplecheck the above is the only relevant directory).

About my config:
C:\Users\Me\AppData\Local\nvim\ has a init.lua file with 2 lines:

require("config.core")
require("config.plugins")
require("config.lazy")

and a lua folder with a subfolder config. In that folder 2 folders: CORE, PLUGINS and a lazy.lua file. 


in the plugins folder i have a file nvim-treesitter.lua


```
return {
	{
		"nvim-treesitter/nvim-treesitter",
		event = { "BufReadPre", "BufNewFile" },
		--build = ":TSUpdate",
		dependencies = {
			"windwp/nvim-ts-autotag",
		},
		config = function()
			-- import nvim-treesitter plugin
			local treesitter = require("nvim-treesitter.configs")

			-- configure treesitter
			treesitter.setup({ -- enable syntax highlighting
				highlight = {
					enable = true,
				},
				-- enable indentation
				indent = { enable = true },
				-- enable autotagging (w/ nvim-ts-autotag plugin)
				autotag = { enable = true },
				-- ensure these language parsers are installed
				ensure_installed = {
					"yaml",
					"lua",
					"vim",
				},
				-- auto install above language parsers
				auto_install = true,
			})
		end,
	},
}
```

Any more you need?

**Comment by clason** [comment]
Find out where lazy installs the nvim-treesitter plugin, then remove it (completely!) and reinstall.

> Any more you need?

Yes, but let's take it one step at a time. This seems to be a Windows-only problem that I don't see how it's caused by the commit you linked, so you will have to debug it (with guidance).

**Comment by Qpernicus** [comment]
> Find out where lazy installs the nvim-treesitter plugin, then remove it (completely!) and reinstall.
> 
> > Any more you need?
> 
> Yes, but let's take it one step at a time. This seems to be a Windows-only problem that I don't see how it's caused by the commit you linked, so you will have to debug it (with guidance).

I'll look into that. And i'm not sure either, but the errors start with the same parsers that the commit made "ensure installed"

Made the changes you suggested, no improvement

**Comment by clason** [comment]
>  but the errors start with the same parsers that the commit made "ensure installed"

Correlation is not causation ;) First, we need to figure out where the conflicting directories are coming from.

Also, please edit your issue to show (in text!) the actual error.

**Comment by Qpernicus** [comment]
> > but the errors start with the same parsers that the commit made "ensure installed"
> 
> Correlation is not causation ;) First, we need to figure out where the conflicting directories are coming from.
> 
> Also, please edit your issue to show (in text!) the actual error.

Very true :) But highly unlikely is also not impossible ;)

Updated the first post

**Comment by clason** [comment]
But that parser is not in the list of "forced" parsers?

**Comment by clason** [comment]
Anyway, first step is to make sure that `C:\\Users\\ME\\AppData\\Local\\nvim-data\\` is empty before starting Neovim. Reboot or `sudo` if you have to.

**Comment by Qpernicus** [comment]
Ok, before the reboot only the treesitter folders couldnt be deleted.. after reboot they could. After deletion i started nvim (no reboot in between) and Lazy started installing everything, but hung:

```
nvim-treesitter[lua]: Error during download, please verify your internet connection
fatal: destination path 'tree-sitter-lua' already exists and is not an empty directory.

Press ENTER or type command to continue

nvim-treesitter[vim]: Error during download, please verify your internet connection
fatal: destination path 'tree-sitter-vim' already exists and is not an empty directory.

Press ENTER or type command to continue
```

After ENTER Lazy continues but shows a few errors in the back (blocked from view by lazy) and eventually finished installing all. 

I get a few notifications that a parser has been installed (36 total, 26 failed, didn't catch which ones)

After that i closed NVIM, restarted it, which then gives me the same errors as before

```
nvim-treesitter[python]: Failed to execute the following command:
{
  cmd = "cmd",
  opts = {
    args = { "/C", "if", "exist", "C:\\Users\\Jeroen.Kuper\\AppData\\Local\\nvim-data\\tree-sitter-python", "rmdir", "/s", "/q", "C:\\Users\\Jeroen.Kuper\\AppData\\Local\\nvim-data\\tree-sitter-python" },
    stdio = {
      [2] = <userdata 1>,
      [3] = <userdata 2>
    }
  }
}
The process cannot access the file because it is being used by another process.^M

Press ENTER or type command to continue
```

BUT, it seems only on python and Markdown-inline. So i'll try and remove the latter from my config and see if python is the only error left. Which could be obvious because i don't have (or use) Python on my laptop

**Comment by clason** [comment]
So the first order of business is to remove lazy from the equation. Can you test a minimal(!) config using the template from https://github.com/neovim/neovim/blob/master/contrib/minimal.lua ?

(The next order of business is to add print-debugging in the local nvim-treesitter checkout to see what's _really_ going on.)

**Comment by Qpernicus** [comment]
In the meanwhile, I was testing where i call markdown and/or python to be installed/used, but can't find it.

But I can delete the folders again.. after doing that and starting nvim, they reappear and the parser markdown.so file re-appears in 

C:\Users\ME\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\

So even if the folders AREN'T there, tree-sitter complains about them being there. Perhaps indeed something else is calling this aswell.

**Comment by clason** [comment]
> In the meanwhile, I was testing where i call markdown and/or python to be installed/used, but can't find it.

They're used in injections in Vim help files, for which treesitter highlighting is now enabled by default.

> . after doing that and starting nvim, they reappear and the parser markdown.so file re-appears in
>
> C:\Users\ME\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\

This is as expected and intended. The question is why this throwing an error on Windows (only!)

Again, please try a minimal config to make sure it's not a Lazy issue that is exposed by the change.

**Comment by Qpernicus** [comment]
> > In the meanwhile, I was testing where i call markdown and/or python to be installed/used, but can't find it.
> 
> They're used in injections in Vim help files, for which treesitter highlighting is now enabled by default.
> 
> > . after doing that and starting nvim, they reappear and the parser markdown.so file re-appears in
> > C:\Users\ME\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\
> 
> This is as expected and intended. The question is why this throwing an error on Windows (only!)
> 
> Again, please try a minimal config to make sure it's not a Lazy issue that is exposed by the change.

To prevent being an ass: I empty my local\nvim dir and place only the minimal.lua file there? or do i keep everything while booting the minimal.lua file?

**Comment by lucario387** [comment]
remove everything and use `nvim -u minimal.lua`

**Comment by lucario387** [comment]
Remove everything inside nvim-data and nvim. Just use the minimal.lua above, and add `require('nvim-treesitter.configs').setup({something})`, define the environment variable `NVIM_APPNAME` with something (i.e. `nvim-test`), use `nvim -u minimal.lua`, wait until all installations are finished. if there's no issue then it's lazy.nvim fault

**Comment by Qpernicus** [comment]
> Remove everything inside nvim-data and nvim. Just use the minimal.lua above, and add `require('nvim-treesitter.configs').setup({something})`, define the environment variable `NVIM_APPNAME` with something (i.e. `nvim-test`), use `nvim -u minimal.lua`, wait until all installations are finished. if there's no issue then it's lazy.nvim fault

What does the env variable do (sorry) ? I cleaned both nvim and nvim-data and appended the minimal.lua with a few options that i thought were harmless

**Without changing/creating the env variable**, and making my minimal.lua like this:

```
-- Run this file as `nvim --clean -u minimal.lua`

for name, url in pairs({
	-- ADD PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE, e.g:
	-- some_plugin = 'https://github.com/author/plugin.nvim'
	treesitter = "https://github.com/nvim-treesitter/nvim-treesitter",
}) do
	local install_path = vim.fn.fnamemodify("nvim_issue/" .. name, ":p")
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
	vim.opt.runtimepath:append(install_path)
end

-- ADD INIT.LUA SETTINGS _NECESSARY_ FOR REPRODUCING THE ISSUE
local opt = vim.opt -- for conciseness

-- line numbers
opt.relativenumber = true -- show relative line numbers
opt.number = true -- shows absolute line number on cursor line (when relative number is on)

-- tabs & indentation
opt.tabstop = 2 -- 2 spaces for tabs (prettier default)
opt.shiftwidth = 2 -- 2 spaces for indent width
opt.expandtab = true -- expand tab to spaces
opt.autoindent = true -- copy indent from current line when starting new one

-- line wrapping
opt.wrap = false -- disable line wrapping

-- search settings
opt.ignorecase = true -- ignore case when searching
opt.smartcase = true -- if you include mixed case in your search, assumes you want case-sensitive

-- cursor line
opt.cursorline = true -- highlight the current cursor line

-- appearance

-- turn on termguicolors for nightfly colorscheme to work
-- (have to use iterm2 or any other true color terminal)
opt.termguicolors = true
opt.background = "light" -- colorschemes that can be light or dark will be made dark
opt.signcolumn = "yes" -- show sign column so that text doesn't shift

-- backspace
opt.backspace = "indent,eol,start" -- allow backspace on indent, end of line or insert mode start position

-- clipboard
opt.clipboard:append("unnamedplus") -- use system clipboard as default register

-- split windows
opt.splitright = true -- split vertical window to the right
opt.splitbelow = true -- split horizontal window to the bottom

-- turn off swapfile
opt.swapfile = false

-- set leader key to space
vim.g.mapleader = ' '
vim.g.maplocalleader = ' '

--------------------
-- [[ Basic Keymaps ]]

-- Keymaps for better default experience
-- See `:help vim.keymap.set()`
vim.keymap.set({ 'n', 'v' }, '<Space>', '<Nop>', { silent = true })

-- Remap for dealing with word wrap
vim.keymap.set('n', 'k', "v:count == 0 ? 'gk' : 'k'", { expr = true, silent = true })
vim.keymap.set('n', 'j', "v:count == 0 ? 'gj' : 'j'", { expr = true, silent = true })
-- Diagnostic keymaps
vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, { desc = 'Go to previous diagnostic message' })
vim.keymap.set('n', ']d', vim.diagnostic.goto_next, { desc = 'Go to next diagnostic message' })
vim.keymap.set('n', '<leader>e', vim.diagnostic.open_float, { desc = 'Open floating diagnostic message' })
vim.keymap.set('n', '<leader>q', vim.diagnostic.setloclist, { desc = 'Open diagnostics list' })


require('nvim-treesitter.configs').setup({
	highlight = {
					enable = true,
				},
				-- enable indentation
				indent = { enable = true },
				-- enable autotagging (w/ nvim-ts-autotag plugin)
				autotag = { enable = true },
				-- ensure these language parsers are installed
				ensure_installed = {
					"yaml",
					"lua",
					"vim",
				},
				-- auto install above language parsers
				auto_install = true,
				lazy = false,
})
```


I still get this error:

```
nvim-treesitter[lua]: Error during download, please verify your internet connection
fatal: destination path 'tree-sitter-lua' already exists and is not an empty directory.

Press ENTER or type command to continue
```

Did i make a mistake in formatting the config?

If i use this as a minimal.lua with either nvim -u minimal.lua or nvim --clean -u minimal.lua FROM THE FOLDER NVIM

```
-- Run this file as `nvim --clean -u minimal.lua`

for name, url in pairs({
	-- ADD PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE, e.g:
	-- some_plugin = 'https://github.com/author/plugin.nvim'
	treesitter = "https://github.com/nvim-treesitter/nvim-treesitter",
}) do
	local install_path = vim.fn.fnamemodify("nvim_issue/" .. name, ":p")
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
	vim.opt.runtimepath:append(install_path)
end

-- ADD INIT.LUA SETTINGS _NECESSARY_ FOR REPRODUCING THE ISSUE

require('nvim-treesitter.configs').setup({
	highlight = {
					enable = true,
				},
				-- enable indentation
				indent = { enable = true },
				-- enable autotagging (w/ nvim-ts-autotag plugin)
				autotag = { enable = true },
				-- ensure these language parsers are installed
				ensure_installed = {
					"yaml",
					"lua",
					"vim",
				},
				-- auto install above language parsers
				auto_install = true,
				lazy = false,
})
```
I also get the errors with the addition of:

```
[nvim-treesitter] [2/12, failed: 2] Checking out locked revision
Press ENTER or type command to continue
```


checkhealth at that point gives:

```
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (0c49d6745b3fc4822ab02e0018770cd6383a779c) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.11.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `zig` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: info: Usage: zig [command] [options]
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.22631",
  sysname = "Windows_NT",
  version = "Windows 11 Enterprise"
} ~

Parser/Features         H L F I J

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```
Where TSUpdate gives a "everything up to date" message.

So based on that.. It isn't lazy OR the env variable does more than I think? (quite possible)

**Comment by clason** [comment]
so what of this is _necessary_? Please help us by keeping the information relevant. I mean it: remove _any_ line you can without changing the error message. Try them all.

**Comment by clason** [comment]
For example, remove the `auto_install` and `lazy` (which is a remnant from your Lazy config).

**Comment by Qpernicus** [comment]
OK fair point, the config setup isn't necessary. With empty nvim (except the minimal.lua) and empty nvim-data. With this in minimal.lua:
```

-- Run this file as `nvim --clean -u minimal.lua`

for name, url in pairs({
	-- ADD PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE, e.g:
	-- some_plugin = 'https://github.com/author/plugin.nvim'
	treesitter = "https://github.com/nvim-treesitter/nvim-treesitter",
}) do
	local install_path = vim.fn.fnamemodify("nvim_issue/" .. name, ":p")
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
	vim.opt.runtimepath:append(install_path)
end

-- ADD INIT.LUA SETTINGS _NECESSARY_ FOR REPRODUCING THE ISSUE

require('nvim-treesitter.configs').setup({})
```

I run (in the local\nvim folder, open in Terminal) `nvim --clean -u minimal.lua` (@lucario didn't mention the --clean flag, thats why i tried both). I STILL get the errors:


```
nvim-treesitter[lua]: Error during download, please verify your internet connection
fatal: destination path 'tree-sitter-lua' already exists and is not an empty directory.

Press ENTER or type command to continue
```

For lua, query, vimdoc, bash, vim, python, markdown, c, markdown_inline. Then i get 9x this one:

```
[nvim-treesitter] [9/18, failed: 9] Checking out locked revision
Press ENTER or type command to continue
```

Then 9x the compiling message. Then Nvim opens while in the commandbar `Treesitter parser for [9 above] has been installed` is being shown. Closing and reopening (both only Nvim and Terminal) shows no errors. Except the checkhealth::

` x) errors found in the query, try to run :TSUpdate {lang} `

**Comment by clason** [comment]
Can you try this in your home folder somewhere?

**Comment by Qpernicus** [comment]
> Can you try this in your home folder somewhere?

I'm on Windows, where's home :P 

(But thats also why I asked about the env. variable. If i go to C:Users/Me, i get the same error, but is that considered home?)

**Comment by clason** [comment]
Yes.

Now what does the `nvim_issue` directory look like?

**Comment by Qpernicus** [comment]
In it is only the folder treesitter. In that folder is a list of folders and separate files. Any specific one you look for?

**Comment by clason** [comment]
And in `C:\\Users\\ME\\AppData\\Local\\nvim-data`?

**Comment by Qpernicus** [comment]
> And in `C:\\Users\\ME\\AppData\\Local\\nvim-data`?

a logfile which appears empty and a few folders: tree-sitter-bash, c, etc. incl python/markdown_inline. 9 in total. 

The dir was empty when starting nvim. Almost seems to be a race between 2 functions that causes treesitter to check for the folder and creating it at the same time or something?

**Comment by clason** [comment]
Maybe, but I wouldn't know which. Nothing has changed in that regard, only the list of parsers has been extended.

**Comment by lucario387** [comment]
Probably markdown and markdown-inline. As they both use the same `markdown` repo

**Comment by clason** [comment]
Can you go to the `neovim_issue` folder, find the lines here, and put `vim.print(ensure_installed)` after it?
https://github.com/nvim-treesitter/nvim-treesitter/blob/503d0ccdee762bb4b2758c391288768fafe39861/lua/nvim-treesitter/configs.lua#L423-L426
Then run again and tell us what it prints.

> Probably markdown and markdown-inline. As they both use the same markdown repo

Maybe, but that should have been an issue with people installing these two manually before. And we've had errors messages about  `tree-sitter-lua` as well.

**Comment by Qpernicus** [comment]
> vim.print(ensure_installed)

Literally after the last END on your snippet?

That gives:

{ "lua", "query", "vimdoc", "vim", "c", "python", "bash", "markdown", "markdown_inline", "lua", "query", "vimdoc", "vim", "c", "python", "bash", "markdown", "markdown_inline" }
Press ENTER or type command to continue
So.. that would imply a double installation?

**Comment by clason** [comment]
It implies that `setup` is called twice, yes.

**Comment by jpx40** [comment]
I have the same issue on Arch linux, i also deleted the Parser Directory to make sure it's a clean reinstall

**Comment by clason** [comment]
Can you update and try again?

**Comment by jpx40** [comment]
still error

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/92295347/3e5cadad-ed1c-4152-9c99-79959b2cc0dd)

**Comment by jpx40** [comment]
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/92295347/ea4d05a3-053d-4f07-a781-2ed4a55d69ba)

**Comment by clason** [comment]
Those are unrelated; I'm asking @Qpernicus here.

**Comment by jpx40** [comment]
i have them got damm error what is wrong

**Comment by clason** [comment]
Update this plugin, yes; I just pushed a fix (hopefully).

**Comment by Qpernicus** [comment]
> Update this plugin, yes; I just pushed a fix (hopefully).

Its seeems to slow down the compilingproces (in my head, not measured),  but also doesnt drop an error..So it seems to work... although the healthcheck still gives the query remark.

Can i check with the same print function?  I tried it here: after line 446

```
 if #ensure_installed > 0 then
    if user_data.sync_install then
      require("nvim-treesitter.install").ensure_installed_sync(ensure_installed)
    else
      require("nvim-treesitter.install").ensure_installed(ensure_installed)
    end
  end
  vim.print(ensure_installed)
```


And it gives the singular 9 parsers

**Comment by clason** [comment]
Yes, after updating a plugin, you must restart to be sure to load the _new_ version.

**Comment by Qpernicus** [comment]
Today no problems thusfar, so i think its fixed. Thanks for the help!

**Comment by emocibob** [comment]
I had the same issue on Windows 10, even after following the [Windows support](https://github.com/nvim-treesitter/nvim-treesitter/wiki/Windows-support) wiki. My dumb workaround was to install [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) and use nvim from there. The same `init.lua` and `lua/user/lazy.lua` worked in WSL without issues.

**Comment by FadedBronze** [comment]
I had a similar error but I was able to hack a solution by manually moving the file from /nvim-data/tree-sitter-rust/ to the parser folder (for me it was \nvim-data\site\pack\packer\start\nvim-treesitter\parser) and renaming parser.so to rust.so. 

Using Neovim 0.9.5 on Windows 11
This was the error:

nvim-treesitter[rust]: Failed to execute the following command:
{                                                                                                                                                                                                                  cmd = "cmd",                                                                                                                                                                                                     opts = {                                                                                                                                                                                                           args = { "/C", "move", "/Y", "parser.so", "C:\\Users\\TheSa\\AppData\\Local\\nvim-data\\site\\pack\\packer\\start\\nvim-treesitter\\parser\\\\rust.so" },                                                        cwd = "C:\\Users\\TheSa\\AppData\\Local\\nvim-data\\tree-sitter-rust",                                                                                                                                           stdio = {                                                                                                                                                                                                          [2] = <userdata 1>,                                                                                                                                                                                              [3] = <userdata 2>                                                                                                                                                                                             }                                                                                                                                                                                                              }                                                                                                                                                                                                              }                                                                                                                                                                                                                Access is denied.^M                                                                                                                                                                                                                                                                                                                                                                                                               Press ENTER or type command to continue

**Comment by clason** [comment]
This happens if the parser is locked by another active Neovim instance. Make sure you close _all_ Neovim instances, then try updating again.

**Comment by VoidPaul** [comment]
Including WSL? I use the same config on WSL, Windows 10 (my personal laptop) and Windows 11 (my high school's desktop). I managed to fix it on W11 by installing every compiler I could think of. GCC, LLVM, Zig... I don't know what might prevent it for working on my personal machine whilst doing the same thing...

**Comment by n-crespo** [comment]
I had this problem and ended up solving it with `clink autorun uninstall`. It seems uninstallation clink didn't remove the things it injected in cmd.exe: https://chrisant996.github.io/clink/clink.html#using-clink

**Comment by dnperfors** [comment]
I was having the same errors, the reason this happens in my case was that Defender was scanning and locking files, so neovim or treesitter is just too fast.... Excluding the nvim-data folder from the virus scanner does fix the problem.
However do this at your own risk!
