### ISSUE TITLE
Plugin error message with Nix

### ISSUE THREAD

**Issue by polarmutex** [nvim-treesitter/nvim-treesitter#5921]
### Describe the bug

I think ensure_install checks for a writeable parser directory. On nix this folder only has read permissions. The ensure_install should check for the parsers and only if the parsers are absent check if the parser directory is writeable. 

```
Error detected while processing /nix/store/dk87iaif59hm1xahq3s46baf624zmfps-vimplugin-polarmutex-dev/plugin/treesitter.lua:
Parser dir ' /nix/store/adwv3i078mlmmkxhw61zfwcqwgi7rvkn-vim-pack-dir/pack/myNeovimPackages/start/nvim-treesitter/parser ' should be read/write (see README on how to configure an alternative install location) /nix/store/adwv3i078mlmmkxhw61zfwcqwgi7rvkn-vim-pack-dir/pack/myNeovimPackages/start/nvim-treesitter/parser '
```

### To Reproduce

on Nixos load neovim through nix nvim-treesitter plugin

### Expected behavior

no error message on neovim load

### Output of `:checkhealth nvim-treesitter`

```markdown
N/A
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev-7ed6966
Build type: Release
LuaJIT 2.1.1693350652
Run "nvim -V1 -v" for more info
```

**Comment by clason** [comment]
>  On nix this folder only has read permissions. 

Then choose a different folder, as the error message suggests.

**Comment by polarmutex** [comment]
I compile my parsers into the nvim-treesitter plugin in a nix package. I am not setting any folder or other ensure_installed parsers in my config.

 With the change of force adding parsers into the ensure_installed,  now the plugin requires the check of the writeable folder, which is not possible with nix.

**Comment by lucario387** [comment]
But doesn't `masters` still have `parser` and `parser-info` dir, which is the default to-be-used for installing :thinking: Shouldn't those dirs be writeable

**Comment by clason** [comment]
>  I am not setting any folder

I am saying that you have to, on Nix.

> With the change of force adding parsers into the ensure_installed, now the plugin requires the check of the writeable folder, which is not possible with nix.

How can you use this plugin without installing parsers? This check is _necessary_ to prevent broken installations in general. If this requires breaking Nix, this is a trade-off we are willing to make.

**Comment by linsui** [comment]
How can I remove the error if I don't want to install any parsers? I have disabled `auto_install` and `ensure_installed` is set to `{}`. But recently it pops an error on start.

**Comment by clason** [comment]
> How can I remove the error if I don't want to install any parsers?

You can't. Just don't install the plugin if you don't want to use it.

**Comment by clason** [comment]
Those are minor and will be removed in 1.0. (The main functionality besides parser installation and curating queries is provided by Neovim itself.) This usecase (not being able/wanting to install parsers) is nothing we want to support, period.
