### ISSUE TITLE
Markdown link highlight changes after capture group rename

### ISSUE THREAD

**Issue by Bekaboo** [nvim-treesitter/nvim-treesitter#5936]
### Describe the highlighting problem

Before commit fc0fceb43a8a6dee9ffa669de8b641493e64c276:

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/76579810/6b88e339-2d02-4ff5-ae75-51e7a49b745c)

After commit fc0fceb43a8a6dee9ffa669de8b641493e64c276:

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/76579810/846330a2-e3c2-454b-9f4e-c34e9eeb95e4)

`@text.reference.markdown_inline` and `@markup.link.label.markdown_inline` should link to the same hlgroup

### Example snippet that causes the problem

N/A

### Tree-sitter parsing result

N/A

### Example screenshot

N/A

### Output of `:checkhealth nvim-treesitter`

```markdown
N/A
```

### Output of `nvim --version`

```text
N/A
```

**Comment by lucario387** [comment]
#5935

**Comment by lucario387** [comment]
Ah no, :thinking: 
Linking to which hlgroup is not related. You should expect to see some changes there. That's on your colorscheme maintainers to handle

**Comment by Bekaboo** [comment]
@lucario387 I maintain my own colorscheme. I don't link `@text.reference.markdown_inline` nor `@markup.link.label.markdown_inline` in my colorscheme explicitly, so I suppose it is some default linkage provided by neovim or nvim-treesitter? Corret me if I am wrong.

**Comment by lucario387** [comment]
But neovim hasn't even add any links for `@markup*` though?

**Comment by Bekaboo** [comment]
So it is neovim not nvim-treesitter that provides the default linkage, right? I will double check when I am back to my computer.

**Comment by lucario387** [comment]
Neovim provide default links for treesitter captures that is defined by nvim-treesitter. However, neovim has not updated the links for new captures just yet. `@markup` is one of the new captures, yet it's having highlight tells me some other parts of your config/colorscheme is providing this link

**Comment by Bekaboo** [comment]
Thanks I understand. I will double check my config later.

**Comment by Bekaboo** [comment]
Turns out it is caused by `@string.special` -> `markup.link.label` renaming.

Originally I had `@string.special` linked to `Special` and `@text.reference.markdown_inline` linked to `Constant`, after the nvim-treesitter renamed captures I followed these changes and renamed `@string.special` to `@markup.link.special`, which causes the problem.

To summary:

To cater for the change in nvim-treesitter, I renamed the following highlight groups in my colorscheme:

- `@parameter`           -> `@variable.parameter`
- `@field`               -> `@variable.member`
- `@namespace`           -> `@module`
- `@float`               -> `@number.float`
- `@symbol`              -> `@string.special.symbol`
- `@string.regex`        -> `@string.regexp`
- `@text.title`          -> `@markup.heading`
- `@text.literal`        -> `@markup.raw`
- `@text.reference`      -> `@markup.link`
- `@text.uri`            -> `@markup.link.url`
- `@string.special`      -> `@markup.link.label`
- `@punctuation.special` -> `@markup.list`
- `@method`              -> `@function.method`
- `@method.call`         -> `@function.method.call`
- `@text.uri`            -> `@string.special.url`
- `@preproc`             -> `@keyword.directive`
- `@define`              -> `@keyword.directive.define`
- `@storageclass`        -> `@keyword.storage`
- `@conditional`         -> `@keyword.conditional`
- `@debug`               -> `@keyword.debug`
- `@exception`           -> `@keyword.exception`
- `@include`             -> `@keyword.import`
- `@repeat`              -> `@keyword.repeat`
- `@text.strong`         -> `@markup.strong`
- `@text.italic`         -> `@markup.italic`
- `@text.link`           -> `@markup.link`
- `@text.strikethrough`  -> `@markup.strikethrough` 
- `@text.todo`           -> `@comment.todo`
- `@text.warning`        -> `@comment.warning`
- `@text.note`           -> `@comment.info`
- `@text.danger`         -> `@comment.error` 
- `@text.diff.add`       -> `@diff.plug`
- `@text.diff.delete`    -> `@diff.minus`


So before renaming:

`@string.special` -> `Special`
`@text.reference.markdown_inline` -> `Constant` (markdown link highlighted in `Constant` color

After:

`@markup.link.label` -> `Special`
`@markup.link.markdown_inline` (invalid group) -> `Constant`
`@markup.link.label.markdown_inline` falls back to `@markup.link` by deault -> markdown link highlighted `Special` color

Seems that there is no easy way to migrate to the new capture groups without breaking old highlights because the hierarchical structure of some highlights are changed after the rename.
