### ISSUE TITLE
Highlights missing/ only appear after lsp loads

### ISSUE THREAD

**Issue by GR3YH4TT3R93** [nvim-treesitter/nvim-treesitter#5940]
### Describe the bug

Somewhere the latest commits (last 24 hrs) there is a breaking change that causes TreeSitter to only add highlights after the lsp has loaded. The issue occurs on lua, vue with typescript, and typescript that I've observed so far.

### To Reproduce

1. :Lazy update
2. open lua file
3. there should now be a delay between the colors attaching that corrects as soon as the lsp has loaded

### Expected behavior

The highlights to be present as soon as the file is opened and Typescript to be recognized and highlighted in vue files

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.2.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: clang version 17.0.6
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "aarch64",
  release = "5.10.168-android12-9-00003-gc873b6b86254-ab10823632",
  sysname = "Linux",
  version = "#1 SMP PREEMPT Mon Sep 18 13:31:53 UTC 2023"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - vue                 ✓ . ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/data/data/com.termux/files/usr/share/nvim"
```

### Additional context

I'm fairly new to nvim/ tree-sitter/ lua etc so I appologize if I'm not able to be more specific.

**Comment by lucario387** [comment]
We had a breaking change yesterday that required colorscheme maintainers to update their themes. Please report this to your currently used colorscheme repo.

**Comment by GR3YH4TT3R93** [comment]
The colors appear, they're just delayed.

**Comment by lucario387** [comment]
> The colors appear, they're just delayed.

That's on the Language Servers, and they don't have any relations to treesitter or nvim-treesitter.
