### ISSUE TITLE
Highlight not working properly on windows 11

### ISSUE THREAD

**Issue by andrrrw** [nvim-treesitter/nvim-treesitter#5941]
### Describe the bug

When I try to compile I get this error
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/81991382/26129319-c37d-48e1-9c78-0c4beb6178dc)
The highlight doesn't work of course

### To Reproduce

1. Windows Terminal
2. Powershell 7.4.1
3. TSInstall markdown

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v21.6.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `clang` executable found. Selected from { "clang" }
  Version: clang version 17.0.6
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.22621",
  sysname = "Windows_NT",
  version = "Windows 11 Home"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1703942320
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

            общесистемный файл vimrc: "$VIM\sysinit.vim"
          значение $VIM по умолчанию: "C:/Program Files (x86)/nvim/share/nvim
"

Run :checkhealth for more info
```

### Additional context

I tryed to change compilers but nothing changes
Btw other parsers work properly

**Comment by andrrrw** [comment]
> Please update nvim-treesitter to the latest commit (or better yet, pin to `v0.9.2`).

i think lazy already updated it for me

**Comment by clason** [comment]
Don't think, test. (And also test with a minimal config without plugin managers. We do not support lazy.)

**Comment by andrrrw** [comment]
So i tested 
I made minimal nvim config (without plugin manager - via packages)
and i MANUALLY download  nvim-treesitter - 0.9.2 from pinned
This is how the document is displayed without highlight
`:TSDisable highlight`
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/81991382/499f218e-f87b-466d-90b1-5688471783e2)
`:TSEnable highlight`
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/81991382/22f68296-a129-46c8-abb6-945495cc44b2)
And i am again see this error while trying to install markdown
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/81991382/c6a522fa-9f24-41cd-aa1e-d0d985083a79)
also i can't uninstall markdown
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/81991382/6ddb8616-a4e2-40d4-808d-9ee69b6332bc)

**Comment by gokayburuc** [comment]
without `:TSToggle highlight` command syntax higlighter not working properly at my Linux **20.04.1-Ubuntu SMP** 

I removed and reinstalled it. Also updated. But still same problem. There is two different markdown filetype in my system. `lsp_markdown` and `markdown`. `markdown` comes with treesitter and syntax highlighter not working properly. so i use `:TSToggle highlight` function manually. Do you have any suggestion? Such as `autocmd` or config etc.

**Comment by Omar-Ebrahim-1** [comment]
I am having issues with markdown not being highlighted too.

**Comment by kohane27** [comment]
I have the same issue but running `TSToggle highlight` manually make it work again

**Comment by clason** [comment]
Please stop adding irrelevant comments; this issue is about the markdown parser failing to build in windows (a configuration/environment issue with compilers on Windows, which is known to be fickle).

Missing highlights is different (and most likely due to the new capture names requiring colorscheme adjustments; please follow the "breaking changes" pinned issue.)

**Comment by andrrrw** [comment]
> Which `&shell` are you using for Neovim? Are you using powershell for the shell option? This seems to be a `/` vs `\\` issue. Compilation was successful but then moving the compilation artifact to the right place failed. Can you check for intermediate artifact at the path that Neovim is indicating? Can you try setting your shell option in neovim to `cmd`?

I use powershell 7.4.1
And changing shell had no effect
Tryed cmd, another powershell
Also set vim.o.shell = "cmd"

**Comment by andrrrw** [comment]
I spent several days trying to figure out what was wrong, in the end I just rolled back to the previous version of treesitter and everything started working

**Comment by andrrrw** [comment]
The issue started after this commit [1ae9b0e](https://github.com/nvim-treesitter/nvim-treesitter/commit/1ae9b0e4558fe7868f8cda2db65239cfb14836d0)

I didn't find anything smarter than to specify the previous commit
This is a temporary solution until the bug is fixed.
```
return {
	'nvim-treesitter/nvim-treesitter',
	commit = "10dd499",
	config = function ()
        --- your cfg ----
        end,
        }
```
