### ISSUE TITLE
Attempt to call field 'get_query' (a nil value)

### ISSUE THREAD

**Issue by pedropmedina** [nvim-treesitter/nvim-treesitter#596]
**Describe the bug**
Error detected while processing CursorMoved Autocommands for "<buffer=1>":

**To Reproduce**
:PlugUpdate
:TSUpdate

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>
## elm parser healthcheck
  - OK: elm parser found.
  - ERROR: Error in `highlights.scm` query found for elm
    ...ad/plugged/nvim-treesitter/lua/nvim-treesitter/query.lua:49: attempt to call field 'get_query' (a nil value)
    - ADVICE:
      - Try `:TSUpdate elm` (queries might have been adapted for a upstream parser change)
      - Try to find the syntax error/invalid node type in above file.
  - ERROR: Error in `locals.scm` query found for elm
    ...ad/plugged/nvim-treesitter/lua/nvim-treesitter/query.lua:49: attempt to call field 'get_query' (a nil value)
    - ADVICE:
      - Try `:TSUpdate elm` (queries might have been adapted for a upstream parser change)
      - Try to find the syntax error/invalid node type in above file.
  - ERROR: Error in `textobjects.scm` query found for elm
    ...ad/plugged/nvim-treesitter/lua/nvim-treesitter/query.lua:49: attempt to call field 'get_query' (a nil value)
    - ADVICE:
      - Try `:TSUpdate elm` (queries might have been adapted for a upstream parser change)
      - Try to find the syntax error/invalid node type in above file.
  - ERROR: Error in `folds.scm` query found for elm
    ...ad/plugged/nvim-treesitter/lua/nvim-treesitter/query.lua:49: attempt to call field 'get_query' (a nil value)
    - ADVICE:
      - Try `:TSUpdate elm` (queries might have been adapted for a upstream parser change)
      - Try to find the syntax error/invalid node type in above file.

## c parser healthcheck
  - OK: c parser found.
  - ERROR: Error in `highlights.scm` query found for c
    ...ad/plugged/nvim-treesitter/lua/nvim-treesitter/query.lua:49: attempt to call field 'get_query' (a nil value)
    - ADVICE:
      - Try `:TSUpdate c` (queries might have been adapted for a upstream parser change)
      - Try to find the syntax error/invalid node type in above file.
  - ERROR: Error in `locals.scm` query found for c
    ...ad/plugged/nvim-treesitter/lua/nvim-treesitter/query.lua:49: attempt to call field 'get_query' (a nil value)
    - ADVICE:
      - Try `:TSUpdate c` (queries might have been adapted for a upstream parser change)
      - Try to find the syntax error/invalid node type in above file.
  - ERROR: Error in `textobjects.scm` query found for c
    ...ad/plugged/nvim-treesitter/lua/nvim-treesitter/query.lua:49: attempt to call field 'get_query' (a nil value)
    - ADVICE:
      - Try `:TSUpdate c` (queries might have been adapted for a upstream parser change)
      - Try to find the syntax error/invalid node type in above file.
  - ERROR: Error in `folds.scm` query found for c
    ...ad/plugged/nvim-treesitter/lua/nvim-treesitter/query.lua:49: attempt to call field 'get_query' (a nil value)
    - ADVICE:
      - Try `:TSUpdate c` (queries might have been adapted for a upstream parser change)
      - Try to find the syntax error/invalid node type in above file.

....IT SAME ERROR FOR ALL PARSERS
</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-nightly
Build type: Release
LuaJIT 2.0.5
```

**Comment by vigoux** [comment]
Hi, when did you last updated your neovim?

**Comment by pedropmedina** [comment]
Hi @vigoux. I updated neovim today. I installed it via homebrew brew install --HEAD neovim

**Comment by vigoux** [comment]
Could you both :

- Show me the output of `lua print(vim.inspect(require'vim.treesitter.query'))` ?
- Try running `brew upgrade --HEAD --fetch-HEAD neovim` ?

**Comment by kontinuity** [comment]
lua print(vim.inspect(require'vim.treesitter.query'))

    {
        add_predicate = <function 1>,
        get_node_text = <function 2>,
        parse_query = <function 3>
    }

```
nvim -v                                                                                                                                master !1
NVIM v0.5.0-43202964f
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200825-44712-1eejrdx/build/config -I/tmp/neovim-20200825-44712-1eejrdx/src -I/usr/local/include -I/tmp/neovim-20200825-44712-1eejrdx/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200825-44712-1eejrdx/build/src/nvim/auto -I/tmp/neovim-20200825-44712-1eejrdx/build/include
Compiled by cruiser@MBP-Trois.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-4320296/share/nvim"

Run :checkhealth for more info
```

**Comment by vigoux** [comment]
So this indicates that nvim version is too old, now we need to find a way for you to actually update to latest master. From what I remember, you need to add some `--fetch-HEAD` flag to homebrew to actually update

**Comment by pedropmedina** [comment]
Hey @vigoux. Thanks for the help. Running "brew upgrade --fetch-HEAD neovim" upgraded neovim HEAD-4f8d98e -> HEAD-eaee3d9 and now the errors are gone.
