### ISSUE TITLE
"locals" update broke functions which iterates locals

### ISSUE THREAD

**Issue by leftas** [nvim-treesitter/nvim-treesitter#5980]
### Describe the bug

Similar bug to what https://github.com/nvim-treesitter/nvim-treesitter/pull/5956 PR fixed in `get_*` functions - account for new “local” nesting. 

I am experiencing breaking of the `find_usages` function. As it tries to check whether matches have reference and node,  however, it does not account for a change in new structure being:
`{["local"] = { reference = { node = { ... }}}}`
```lua
  for match in M.iter_locals(bufnr, scope_node) do
    if match.reference and match.reference.node and ts.get_node_text(match.reference.node, bufnr) == node_text then
```

Mainly, I could submit PR myself, but I have trouble identifying whether something else will be/is touched by this and whether this fix should be in iter_locals or find_usages itself.

### To Reproduce

You can use any module which uses get_usages to do any work, in this case I used nvim-treesitter-refactor's navigation, specifically `goto_next_usage`.

1. Enable navigation submodule: https://github.com/nvim-treesitter/nvim-treesitter-refactor?tab=readme-ov-file#navigation
2. Open a file supported by TS.
3. Go onto any variable/function or any TS node for that matter.
4. Use "goto_next_usage" functionality with your defined bindings (by default ALT-*). OR call method manually.

Or 

1. Call nvim-treesitter.locals' `find_usages` method manually supplying a node.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.3.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 15.0.0 (clang-1500.0.40.1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.1.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020"
} ~

Parser/Features         H L F I J
  - html                ✓ ✓ ✓ ✓ ✓
  - http                ✓ . . . ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev-2150+ge68decab0-Homebrew
Build type: Release
LuaJIT 2.1.1703358377
Run "nvim -V1 -v" for more info
```

**Comment by clason** [comment]
PR welcome!

**Comment by leftas** [comment]
@clason, I am more than happy to submit a PR, but I have a question then: 
- If the name implies that it iterates through locals, does it make sense to return inside “local” key (i.e. `{["local"] = { reference = { node = { ... }}}}`) or is it `find_usages`' responsibility, to deference the `local`.  Given `get_locals` function and its usage, it seems that the latter should be the way to go. WDYT?

**Comment by clason** [comment]
Either is fine with me; it depends on what the plugins like nvim-treesitter expect. (The whole module has already been rewritten on the `main` branch, so this is purely for compatibility. As I personally don't use any of these plugins, I appreciate help from those that do.)

The (only) important change here is that the captures have been renamed to `@local.foo` to be compatible with upstream tree-sitter.
