### ISSUE TITLE
Apex language support is shown on README, but is missing on wiki, and not available on install?

### ISSUE THREAD

**Issue by renatoliveira** [nvim-treesitter/nvim-treesitter#5997]
### Describe the bug

The Apex language is shown on the README on the list of supported languages, and is shown on the wiki page of "List of parsers", but it is not possible to install it with `TSInstall apex`. Installation fails with

> "Installation not possible: ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/install.lua:86: Parser not available for language "apex"

I wasn't sure which kind of issue to open, but a bug one seems more appropriate. Apologies if that's not the case. 

---

Also tried installing it from the repository, by cloning that repo into my local machine and referencing it in my init.lua file: 

```lua
local apex_parser_config = require "nvim-treesitter.parsers".get_parser_configs()

apex_parser_config.apex = {
  install_info = {
    url = vim.fn.expand("~/Documents/Projects/tree-sitter-sfapex"),
    files = { "apex/src/parser.c" },
    branch = "main",
    generate_requires_npm = false,
    requires_generate_from_grammar = false
  },
  filetype = "apex"
}

```

But this also doesn't work and code isn't highlighted. `TSInstall apex` works then, and I get the `Treesitter parser for apex has been installed` message at the bottom of the editor. However, `TSModuleInfo` shows apex not supporting any of the three features (highlight, incremental selection and indent):

```
>> default         highlight  incremental_selection  indent  
...
apex               ✗          ✗                      ✗       
...
```

### To Reproduce

With tree-sitter 0.20.8, runtime ABI version 14 and NeoVIM 0.9.4, run `TSInstall apex` and it should fail with the "parser not available for language".
Listing the parsers with `TSModuleInfo` shows a list of many languages, but `apex` isn't on the list.

### Expected behavior

The parser for `apex` maintained by @aheber should be on the list, and should be available for install.

https://github.com/aheber/tree-sitter-sfapex

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v18.18.2 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 15.0.0 (clang-1500.1.0.2.5)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.2.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ . ✓
  - markdown_inline     ✓ . . . ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.4/share/nvim"

Run :checkhealth for more info
```

### Additional context

On the wiki page, it would be nice to know what does it mean when a language has its checkbox ticked or not, by the way.

**Comment by clason** [comment]
Works for me.

**Comment by clason** [comment]
Are you sure your `nvim-treesitter` is fully updated (and not lazy-loaded!)?

**Comment by renatoliveira** [comment]
> Are you sure your `nvim-treesitter` is fully updated (and not lazy-loaded!)?

Indeed enabling the checker for lazy with `checker = { enabled = true, notify = true }` made Nvim list treesitter as one of the plugins with updates. I'll have to check if updating it solves the issue (I just did, but broke my setup in the process too).

**Comment by clason** [comment]
It does.
