### ISSUE TITLE
Make installer cross compatible

### ISSUE THREAD

**Issue by kyazdani42** [nvim-treesitter/nvim-treesitter#6]
the installer currently only works on *nix systems with `gcc` as a compiler. We need to make this command work on macos and windows. Windows support will be harder to implement as we also need to handle path resolution differently.

**Comment by vigoux** [comment]
Haven't tested it for now but it should work on macOS too, as it has some `BSD`-ish parts left.

**Comment by vigoux** [comment]
Confirmed to work on Macos.

**Comment by kyazdani42** [comment]
We still need someone to do this on windows

**Comment by theHamsta** [comment]
Requiring a compiler on Windows is always difficult. Maybe we can just let Travis precompile DLLs for all parsers? It's actually pretty easy to let Travis use GitHubs releases feature. We can then provide an automated download.

I personally try to ignore Windows for everything I'm doing. I cannot understand anyone using it except one is forced by the own company.

**Comment by kyazdani42** [comment]
i agree, its always a pain to support windows

**Comment by theHamsta** [comment]
If anyone wants to try: You should be able to build the parsers for Windows with our current setup using this Travis enviroment: https://docs.travis-ci.com/user/reference/windows/#how-do-i-use-msys2

Travis could then push the artifacts to the releases page of our repo to have URLs for windows users to auto-download.

**Comment by kyazdani42** [comment]
i will start working on that soon!

**Comment by theHamsta** [comment]
I mean if there are no complaints, we don't need to implement it.

**Comment by theHamsta** [comment]
From emacs-tree-sitter:

`npm install` is a cross-plattform way to install the parsers. Windows users would then need to have npm and a compiler installed.

**Comment by vigoux** [comment]
That's quite nice, we are going to investigate and use GH actions for testing in the future, we should look into that

**Comment by kyazdani42** [comment]
would windows user need to compile with npm install ? i believe treesitter is a plateform agnostic library, only linking the files into a shared library would be needed. I'm not too sure about that though, the best way to do this would be to get some guy that works on windows. A new issue with windows is that we do all path resolution with `/` also when they would need to be done with `\`.
I believe maintaining for windows would need a windows developer.
And ATM i am pretty convinced windows users are not too much invested in this kind of projects.
If some of them would manifest, then fixing this for their platform shouldn't be too hard, but ATM, i don't think we (unix users) need to focus on that.

**Comment by theHamsta** [comment]
Yes, npm install invokes the compiler to compile the parser shared libraries.

A Windows user should propose and maintain a solution. Probably, precompilation is still the easiest option.
