### ISSUE TITLE
Issues with system package manager and parser_install_dir

### ISSUE THREAD

**Issue by JSteitz** [nvim-treesitter/nvim-treesitter#6017]
### Describe the bug

I would like to use my system package manager to update the plugin. Unfortunately, I have several problems with installing the parsers.

**Setup**

The plugin is installed in the directory `/usr/share/nvim/site/pack/dist/start/`. The parsers themselves are installed via `:TSInstall`.

Due to the permissions, I have changed the installation path for the parsers in my configuration.

```lua
require("nvim-treesitter.configs").setup({
  ...
  parser_install_dir = vim.fn.stdpath("data") .. "/site/",
  auto_install = true,
  ...
})
```

**Problems**

Some parsers cannot be installed

```
nvim-treesitter[lua]: Failed to execute the following command:                                                                                              
{                                                                                                                                                           
  cmd = "mv",                                                                                                                                               
  opts = {                                                                                                                                                  
    args = { "-f", "tree-sitter-lua-tmp/tree-sitter-lua-master", "tree-sitter-lua" },                                                                       
    cwd = "/home/jura/.local/share/nvim",                                                                                                                   
    stdio = {                                                                                                                                               
      [2] = <userdata 1>,                                                                                                                                   
      [3] = <userdata 2>                                                                                                                                    
    }                                                                                                                                                       
  }                                                                                                                                                         
}                                                                                                                                                           
mv: cannot stat 'tree-sitter-lua-tmp/tree-sitter-lua-master': No such file or directory
```
And all parsers are not recognized as installed, although I can see them in the installation directory.

### To Reproduce

1. Install plugin in `/usr/share/nvim/site/pack/...`
2. Execute `:TSInstall [any parser]`

### Expected behavior

All parsers are installed and recognized in the installation directory.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v21.6.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.6.14-1-lts",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Fri, 26 Jan 2024 11:54:58 +0000"
} ~

Parser/Features         H L F I J

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

I think that the setting `parser_install_dir` is not working properly. When I install the plugin in the directory `~/.config/nvim/pack/*/start/`. Then I can install the parsers again, but they are still not recognized as installed.
Without the setting, I do not have any issues.

**Comment by clason** [comment]
Sorry, we do not support system-wide installation of this plugin; this is an anti-pattern.

You can try if the rewrite on `main` works for you, though.

**Comment by JSteitz** [comment]
In the readme it says:
> You can install nvim-treesitter with your favorite package manager (or using the native package feature of vim, see :h packages).

And that is precisely what I'm doing, the package manager (except downloading and placing it in the correct directory) has nothing to do with this.

And like said in additional context, it also does not work correctly with `parser_install_dir`.

**Comment by clason** [comment]
Sorry, that is a misinterpretation (assumed context by the writer): what was meant was a _Neovim_ package (or plugin) manager, not a _system_ package manager.

> And like said in additional context, it also does not work correctly with parser_install_dir.

Then let's focus on that. Can you create a minimal, reproducible example (without plugin managers etc.) that shows the error?

And do test `main`; `master` is essentially frozen.

**Comment by JSteitz** [comment]
```lua
-- Run this file as `nvim --clean -u minimal.lua`

for name, url in pairs {
  -- ADD PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE, e.g:
  -- some_plugin = 'https://github.com/author/plugin.nvim'
  treesitter = "https://github.com/nvim-treesitter/nvim-treesitter",
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/' .. name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

-- ADD INIT.LUA SETTINGS _NECESSARY_ FOR REPRODUCING THE ISSUE

require("nvim-treesitter.configs").setup({
  parser_install_dir = vim.fn.stdpath("data") .. "/site/",
  auto_install = true,
})
```
I have the same error, it tries to reinstall the parser.
* `auto_install` every time I open the minimal.lua file with `nvim --clean -u minimal.lua minimal.lua`
* using `:e` to reopen current lua file
* 
> Sorry, that is a misinterpretation (assumed context by the writer): what was meant was a Neovim package (or plugin) manager, not a system package manager.

Shouldn't this still work the same since `/usr/share/nvim/site/pack/*/start/` is in the runtimepath?
The package manager just does a git pull and moves the plugin there.

**Comment by clason** [comment]
You need to make sure the parser install dir is on runtimepath, of course (this is documented!)

**Comment by JSteitz** [comment]
I'm sorry, I was not aware that `stdpath("data")/site` is not in the runtimepath with the minimal config

Even after adding an absolute path, it still reinstalls the parsers:
```lua
-- Run this file as `nvim --clean -u minimal.lua`

for name, url in pairs {
  -- ADD PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE, e.g:
  -- some_plugin = 'https://github.com/author/plugin.nvim'
  treesitter = "https://github.com/nvim-treesitter/nvim-treesitter",
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/' .. name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

-- ADD INIT.LUA SETTINGS _NECESSARY_ FOR REPRODUCING THE ISSUE
vim.opt.runtimepath:append("/home/jura/.local/share/nvim/site/")
require("nvim-treesitter.configs").setup({
  parser_install_dir = "/home/jura/.local/share/nvim/site/",
  auto_install = true,
})
```

I'm not getting any warnings or errors.
`[nvim-treesitter] [1/1] Treesitter parser for lua has ben installed`

I also tried the minimal setup without the setting and it works as intended.

**Comment by clason** [comment]
Works for me, is all I can say: If it installs the parser once, it'll not reinstall it the second time.

**Comment by JSteitz** [comment]
Can you point me where I have to look in the code, maybe I can debug it on my side.Thanks for the help.On Jan 30, 2024 14:32, Christian Clason ***@***.***> wrote:
Works for me, is all I can say: If it installs the parser once, it'll not reinstall it the second time.
