### ISSUE TITLE
Neovim / Treesitter segfaults when previewing mardown files in Telescope

### ISSUE THREAD

**Issue by KoolieAid** [nvim-treesitter/nvim-treesitter#6021]
### Describe the bug

Neovim crashes whenever I open telescope. and since the README.md is usually shown first, it just crashes.
the terminal then outputs SIGSEGV on nvim

I tried disabling tree-sitter by adding a `enabled = false` property on the lazy specs, and it didnt crash, so I figured the segfault is from tree-sitter

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/26061711/81b6b6b3-be14-4e97-9586-ea98f3942fa0)

### To Reproduce

1. Make an empty folder
2. Cd into there
3. Make empty markdown file
4. Open nvim without args or flags
5. Open telescope
6. Observe that it segfaults or crash. (Sometimes it just freezes but thats part of segfault anyway)

### Expected behavior

It will preview the mardown file correctly and not crash / segfault

### Output of `:checkhealth nvim-treesitter`

```markdown
Also Segfaults :(
```

### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1703942320
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

### Additional context

telescope version 0.1.5 / commit d909568
treesitter commit 45cde45

Config repo: https://github.com/KoolieAid/nvim.git **`lazy-migrate` branch**
or `git clone https://github.com/KoolieAid/nvim.git --branch lazy-migrate` for copy and paste

**Comment by clason** [comment]
Try uninstalling and reinstalling the `markdown` _and_ `markdown_inline` parsers. (In fact, it's best to completely wipe the nvim-treesitter installation -- including parsers -- and reinstalling from scratch.)

Beyond that, there's nothing we can do to help.
