### ISSUE TITLE
Regression in PR #6014: error "rhs: expected string|function, got nil" on incremental_selection 

### ISSUE THREAD

**Issue by GR3YH4TT3R93** [nvim-treesitter/nvim-treesitter#6025]
### Describe the bug

When opening a file with nerd-tree or Dashboard errors appear and ts highlighting doesn't work

### To Reproduce

1.) Install Neo-tree or Dashboard-nvim
2.) Checkout commit 5f950cdcb82d2cf74e6b30338897b3a4897f52b3
3.) Restart Neovim
4.) Use Neo-tree or Dashboard to navigate to a file (should be working as expected)
5.) Update to commit ba6454783493ac3a5dd209c25e491640b07bd8de (#6014)
6.) Restart neovim
7.) Use Neo-tree or Dashboard to navigate to a file
8.) An error should appear (the error will be different based on whether you use Dashboard or Neo-tree but only occurs after this commit)

### Expected behavior

The file to open without errors and highlighting to work.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.9 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.2.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: clang version 17.0.6
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "aarch64",
  release = "5.10.168-android12-9-00003-gc873b6b86254-ab10823632",
  sysname = "Linux",
  version = "#1 SMP PREEMPT Mon Sep 18 13:31:53 UTC 2023"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - vue                 ✓ . ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/data/data/com.termux/files/usr/share/nvim"
```

**Comment by lucario387** [comment]
Doesn't seem related. Both of them doesn't change any queries though?

**Comment by GR3YH4TT3R93** [comment]
This is the exact error that occurs when using Dashboard to navigate to new file that only occurs when updating to the specified commit.

It has something to do with the command that they're working on.

   Error  08:49:11 msg_show.lua_error E5108: Error executing lua: vim/_editor.lua:341: nvim_exec2()..BufReadPost Autocommands for "*": Vim(append):Error executing lua callback: ...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:24: Error executing lua: ...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:25: nvim_exec2()..BufReadPost Autocommands for "*"..FileType Autocommands for "*": Vim(append):Error executing lua callback: vim/keymap.lua:36: rhs: expected string|function, got nil
stack traceback:
	[C]: in function 'error'
	vim/shared.lua:764: in function 'validate'
	vim/keymap.lua:36: in function 'set'
	...treesitter/lua/nvim-treesitter/incremental_selection.lua:151: in function 'attach'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
	...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:132>
	[C]: in function 'nvim_cmd'
	...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:25: in function <...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:24>
	[C]: in function 'nvim_buf_call'
	...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:24: in function <...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:10>
	[C]: in function 'nvim_exec2'
	vim/_editor.lua:341: in function 'cmd'
	...e/nvim/lazy/dashboard-nvim/lua/dashboard/theme/hyper.lua:299: in function <...e/nvim/lazy/dashboard-nvim/lua/dashboard/theme/hyper.lua:280>
stack traceback:
	[C]: in function 'nvim_cmd'
	...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:25: in function <...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:24>
	[C]: in function 'nvim_buf_call'
	...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:24: in function <...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:10>
	[C]: in function 'nvim_exec2'
	vim/_editor.lua:341: in function 'cmd'
	...e/nvim/lazy/dashboard-nvim/lua/dashboard/theme/hyper.lua:299: in function <...e/nvim/lazy/dashboard-nvim/lua/dashboard/theme/hyper.lua:280>
stack traceback:
	[C]: in function 'nvim_buf_call'
	...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:24: in function <...ata/com.termux/files/usr/share/nvim/runtime/filetype.lua:10>
	[C]: in function 'nvim_exec2'
	vim/_editor.lua:341: in function 'cmd'
	...e/nvim/lazy/dashboard-nvim/lua/dashboard/theme/hyper.lua:299: in function <...e/nvim/lazy/dashboard-nvim/lua/dashboard/theme/hyper.lua:280>
stack traceback:
	[C]: in function 'nvim_exec2'
	vim/_editor.lua:341: in function 'cmd'
	...e/nvim/lazy/dashboard-nvim/lua/dashboard/theme/hyper.lua:299: in function <...e/nvim/lazy/dashboard-nvim/lua/dashboard/theme/hyper.lua:280>

**Comment by wookayin** [comment]
I've changed the title to be more informative. /cc @MariaSolOs

**Comment by MariaSolOs** [comment]
Interesting. @GR3YH4TT3R93 could you please provide a minimal configuration? Else it would also be really helpful if you navigate to that `incremental_selection` file and print what `funcname` is [here](https://github.com/nvim-treesitter/nvim-treesitter/blob/364b86ec8ea88e4a77ba676b93fb10829d6a9cb3/lua/nvim-treesitter/incremental_selection.lua#L149).

**Comment by GR3YH4TT3R93** [comment]
Here's the the minimal config and steps to reproduce:

1.) Open with minimal config (eg. nvim -u repro.lua)
2.) Allow downloads to complete
3.) Close and reopen with file (eg. nvim repro.lua -u repro.lua
2.) Error will appear

```
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  -- do not remove the colorscheme!
  "folke/tokyonight.nvim",
  -- add any other pugins here
  {
    -- Highlight, edit, and navigate code
    "nvim-treesitter/nvim-treesitter",
    config = function()
      local configs = require("nvim-treesitter.configs")
      configs.setup({
        ensure_installed = {},
        auto_install = true,
        sync_install = false,
        ignore_install = {},
        modules = {},
        incremental_selection = {
          enable = true,
          keymaps = {
            init_selection = "<leader>ss",
            node_incremental = "<leader>nn",
            node_decremental = "<leader>np",
            scope_incremental = "<leader>sn",
            scope_dencremental = "<leader>sp",
          },
        },
      })
    end,
    build = ":TSUpdate",
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here
vim.opt.termguicolors = true
-- do not remove the colorscheme!
vim.cmd([[colorscheme tokyonight]])
```

**Comment by MariaSolOs** [comment]
@GR3YH4TT3R93 the error is correct. There's no `scope_decremental` mapping. The available functions are here:
https://github.com/nvim-treesitter/nvim-treesitter/blob/515b00598a4786631466d5c4b7c7fd0188ae1022/lua/nvim-treesitter/incremental_selection.lua#L129-L134

There was no error before because the command would still [receive a string during creation](https://github.com/nvim-treesitter/nvim-treesitter/blob/853b1ab39ae80b2e0e4a2224ac49f1763f025385/lua/nvim-treesitter/incremental_selection.lua#L151), but the binding would be incorrect during execution.

@clason please correct me if I'm wrong here.

**Comment by MariaSolOs** [comment]
> Oops my bad... removing that fixed the error! Thanks!!!

No worries! I'm glad we fixed it :) To be fair it's quite odd for `scope_incremental` to exist but not `scope_decremental`. Oh well...
