### ISSUE TITLE
svelte indents don't dedent after closing tag

### ISSUE THREAD

**Issue by LeviOP** [nvim-treesitter/nvim-treesitter#6028]
### Describe the bug

Indentation after a closing tag (that is on its own line) is one level too far forward.

### To Reproduce

1. Open a `.svelte` file in neovim, ensuring the `svelte` tree-sitter grammar is installed
2. Create any non-void element (`p` for example)
3. Ensure that the opening and closing tags are on separate lines
5. Allow tree-sitter to indent your cursor to any line under the closing tab (using `<CR>` in insert mode or `o` in normal mode)
6. Observe that the indentation is one level too far forward

Example result where `|` represents the cursor's position:
```html
<p>
</p>
    |
```

### Expected behavior

The cursor would not be indented as the block has ended.

Example result where `|` represents the cursor's position:
```html
<p>
</p>
|
```

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.11.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 15.0.0 (clang-1500.1.0.2.5)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.2.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - cfg                 ✓ . . . .
  - css                 ✓ . ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - prisma              ✓ . ✓ . .
  - query               ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - sql                 ✓ . . ✓ ✓
  - svelte              ✓ . ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/Users/3093357/.local/homebrew/Cellar/neovim/0.9.1/share/nvim"

Run :checkhealth for more info
```

### Additional context

The reason that this his happening is because the `indents.scm` file for svelte uses the `indent.branch` capture, which dedents captured nodes, but doesn't end the indented block:
https://github.com/nvim-treesitter/nvim-treesitter/blob/cb568af5393241e5dbc9c19157c5df5e9ca9af2d/queries/svelte/indents.scm#L10-L18 
To remedy this, you should use the `indent.branch` capture in tandem with the `indent.end` capture, which actually ends the indented block. See the [html tags indents](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/html_tags/indents.scm) for guidance on how to do this correctly.

**Comment by lucario387** [comment]
pr welcome
