### ISSUE TITLE
[latex] Some comments highlighted incorrectly in math regions

### ISSUE THREAD

**Issue by gi1242** [nvim-treesitter/nvim-treesitter#6047]
### Discussed in https://github.com/nvim-treesitter/nvim-treesitter/discussions/6038

<div type='discussions-op-text'>

<sup>Originally posted by **gi1242** February  1, 2024</sup>
Hi All,

In Latex files, is it possible for comments inside the file to be highlighted as comments. I'm attaching a screenshot of what it looks like now:

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/1884258/0966deff-ffcb-46ac-9155-7ea1bf10e0c8)

For the comment that is highlighted correctly, `:Inspect` shows:

    Treesitter
      - @markup.math.latex links to Special latex
      - @spell.latex links to @spell latex
      - @comment.latex links to Comment latex
      - @spell.latex links to @spell 

For the comment that is highlighted incorrectly, `:Inspect` shows:

    Treesitter
      - @comment.latex links to Comment latex
      - @spell.latex links to @spell latex
      - @markup.math.latex links to Special latex

Thanks in advance,

GI</div>

@clason  suspects this is a regression caused by a recent commit of @ribru17

**Comment by ribru17** [comment]
Oops sorry :smile: I have a PR in the works for this right now, just needs to be tested a bit more
