### ISSUE TITLE
Error During Compilation: No such file or directory

### ISSUE THREAD

**Issue by situlsrtq** [nvim-treesitter/nvim-treesitter#6081]
### Describe the bug

Using Vim-Plug, when attempting to install parsers for C++ and Python, the install fails on compilation, with the error message: `nvim-treesitter['lang']: Error during compilation
cc1plus: fatal error: src/scanner.cc: No such file or directory
compilation terminated`

The issue persists after uninstalling and cleaning the .local/share/nvim directory and cached files, then reinstalling nvim-treesitter. Looking in the temporary directories left behind from the failed installation attempts, it looks like the file in nvim-treesitter-[lang]/src is "scanner.c", not "scanner.cc", but that's the only thing I can see that looks incorrect. Parsers for C, Lua, Vim, and Help all installed successfully.

On Arch, gcc/g++ version is 13.2.1. Install commands are identical to the commands described in the basic installation readme here. Same results for TSInstallSync [lang].

### To Reproduce

Update gcc, neovim.

Clean install of Treesitter using `Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}` after successfully running PlugUpdate.

TSUpdate fails on cpp and python. Subsequent calls to TSUpdate only find the help parser to update

### Expected behavior

Successfully compiled parsers for cpp and python

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v21.6.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.7.2-arch1-2",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Wed, 31 Jan 2024 09:22:15 +0000"
} ~

Parser/Features         H L F I J
  - lua                 ✓ ✓ ✓ ✓ ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - help                . . . . .
  - vim                 ✓ ✓ ✓ . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.11702233742
```

**Comment by clason** [comment]
Yes, this looks very incorrect. Make sure the plugin is up to date, and you don't have ancient copies somewhere on your runtimepath.
