### ISSUE TITLE
bug: `spell` not working within TSX/JSX

### ISSUE THREAD

**Issue by Hacksore** [nvim-treesitter/nvim-treesitter#6082]
### Describe the bug

Spell check does not seem to work inside of TSX/JSX but it will work fine in HTML so is this a bug?

Not working in JSX/TSX (nvim left, vscode right)
<img width="1728" alt="2024-02-11_08-51-25" src="https://github.com/nvim-treesitter/nvim-treesitter/assets/996134/da9b0ab2-0cbc-4fab-b358-3947b3162adb">

Works in HTML
<img width="886" alt="2024-02-11_09-16-01" src="https://github.com/nvim-treesitter/nvim-treesitter/assets/996134/15f1618a-aef2-4bcb-970d-d9ef4c5e7df8">

### To Reproduce

1. load up the MVP code
2. use `set spell`
3. pasta in

```TypeScript
import React from "react";
import ReactDOM from "react-dom/client";
// thse is tpoes
ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>thse is tpoes</React.StrictMode>
);
```

### Expected behavior

The typos in the JSX/TSX should be showing underlines as they work outside of the JSX/TSX in the same file.

### Output of `:checkhealth nvim-treesitter`
yeeting this as it's not really helpful.

### Output of `nvim --version`

```text
$ nvim --version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim"

Run :checkhealth for more info
```

### Additional context
This was opened initially here but it needs to be in this repo instead.

https://github.com/tree-sitter/tree-sitter-typescript/issues/275

**Comment by lucario387** [comment]
We do not enable spell for such nodes it seems

So Pr welcome!

**Comment by Hacksore** [comment]
Yeah looking at this more comments work.
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/996134/66ed4f1c-a042-4206-9757-88fdd0b9d78e)

Because of the guidance here for how spell should work.
https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#non-highlighting-captures

I guess it's a "feature" that it doesn't highlight but a bit said that 🅱️SCode can do it.

**Comment by Hacksore** [comment]
reading deeper into the lore I found [this issue](
https://github.com/nvim-treesitter/nvim-treesitter/issues/5202) which points out that several langs do implement `@spell` on more than comment text nodes.

**Comment by clason** [comment]
Yes, it's perfectly fine to spell check if something is _known_ to be text-like. We just tend to be conservative and only added this for specific nodes (beside `@comment`) when there's a compellingly argued demand.

(Remember that queries are community-contributed.)
