### ISSUE TITLE
Detect http uri links and path's in comments and .md for specific highlighting

### ISSUE THREAD

**Issue by MikeLemo1** [nvim-treesitter/nvim-treesitter#6158]
**Is your feature request related to a problem? Please describe.**
So basically I'd the ability to change highlight of links throught the nvim editor whether they are inside c or lua comment or just in a markdown file I'd be nice to be able to differenciate between a normal text paragraph from links which noone usually reads and doesn't need to be as prominent as normal text so it's be nice to have entities such as `https://github.com/nvim-treesitter/nvim-treesitter/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.md&title=` referenceable in TS

**Describe the solution you'd like**
Parser / Tokenizer for http uri links

**Comment by clason** [comment]
That's not valid markdown, though. You need to enclose URIs in angled brackets; then it already works.

**Comment by clason** [comment]
(that's only for _clickable_ links, which this is not about?)

**Comment by lucario387** [comment]
True that, mb :bowing_man:

**Comment by clason** [comment]
> Who said that's not valid markdown?

CommonMark Spec. If it's not marked up, it's plain text. And we don't care what VS Code does; it's the poster child for ignoring specs (even their own).
