### ISSUE TITLE
@comment.todo and others no longer working

### ISSUE THREAD

**Issue by benjamin051000** [nvim-treesitter/nvim-treesitter#6171]
### Describe the bug

Using `nvim-treesitter` on commit https://github.com/nvim-treesitter/nvim-treesitter/commit/1398b1ba4619cef240abd496b500b95819c8c496 and `nvim` version `0.9.5`

I'm not sure which version of treesitter-nvim or this C parser I was using before (no more than 8 months old), but the following comment tags had special highlighting: 
```c
// TODO was yellow (I think?)
// WARNING was yellow
// BUG was read
// NOTE was light blue
// ERROR was red (I think?)
```
These no longer have special highlighting and are the same color as a normal comment.

`:InspectTree` shows them as `(comment)` objects rather than `(comment.note)` (I'm not sure if this is how it's supposed to show up, I am not super familiar with how treesitter works.)

I found this in the contributing.md of treesitter-nvim, perhaps it is relevant?
```
As languages differ quite a lot, here is a set of captures available to you when building a highlights.scm query. Note that your color scheme needs to define (or link) these captures as highlight groups.

...

@comment               ; line and block comments
@comment.documentation ; comments documenting code

@comment.error         ; error-type comments (e.g. `ERROR`, `FIXME`, `DEPRECATED:`)
@comment.warning       ; warning-type comments (e.g. `WARNING:`, `FIX:`, `HACK:`)
@comment.todo          ; todo-type comments (e.g. `TODO:`, `WIP:`, `FIXME:`)
@comment.note          ; note-type comments (e.g. `NOTE:`, `INFO:`, `XXX`)
```

It appears to be the same behavior for at least C and Python. I raised an issue here https://github.com/tree-sitter/tree-sitter-c/issues/195 but was told this is an upstream issue from the language grammar.

Let me know if you need any additional info, or if I should move this issue someplace else. Thank you!

### To Reproduce

1. Update neovim to `0.9.5` and `nvim-treesitter` to `1398b1ba4619cef240abd496b500b95819c8c496`
2. Install a parser, e.g., for C via `:TSInstall` 
3. Run `:TSEnable highlight` in a C file with comments that have one of the all-caps words shown above like `NOTE`
4. No special highlighting appears on those. They just show up as a normal comment coloring.
5. `:InspectTree` shows them as `(comment)` objects rather than `(comment.note)` (This may not be how it works, sorry if my lack of knowledge causes issues)

### Expected behavior

Special highlighting should show up (like it used to) on these comments.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v4.4.3 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `/apps/free/gcc/9.2.0/bin/gcc` executable found. Selected from { "/apps/free/gcc/9.2.0/bin/gcc" }
  Version: gcc (GCC) 9.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "3.10.0-693.el7.x86_64",
  sysname = "Linux",
  version = "#1 SMP Thu Jul 6 19:56:57 EDT 2017"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - tmux                ✓ . . . ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

```
```


### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

- On CentOS7 but using manually-installed versions of `gcc`, `git`, and some others that seem to be compliant with this version of neovim. `ldd $(which nvim)` doesn't show anything missing and the editor works totally fine otherwise. `:checkhealth` reports a couple of warnings here and there for various other issues, but nothing glaring to my eye. Let me know if you want to see that entire list. 
- I normally use tokyo night colorscheme but switching to `:colorscheme default` does not fix the problem, so I don't think it's a color scheme issue.

_No response_

**Comment by clason** [comment]
You need to have the `comment` parser installed for these comment highlights, which you do not.

**Comment by benjamin051000** [comment]
A ha! I didn't realize there was a parser just for comments. I ran `:TSInstall comment` and restarted nvim and they're back! Thank you @clason !
