### ISSUE TITLE
Highlighting: unable to distinguish between function/class definition and function/class usage

### ISSUE THREAD

**Issue by pappasam** [nvim-treesitter/nvim-treesitter#618]
**Describe the bug**

*Note: calling this a "bug" is a stretch, but it's somewhere between a "bug" and a "feature". Happy to have someone change the label to "enhancement" if you think that label is more appropriate*

I find it helpful to have a function's definition highlighted in a slightly different way than its usage (usually, I'll make the definition identifier bold). The definition is the function's single source of truth (hopefully), and I like my syntax highlighting to visually distinguish between the definition name and the usage name. There is currently no way that I know of, using the provided Vim highlight groups, to distinguish between a function/class definition identifier and a function/class usage identifier.

**To Reproduce**

Using any highlighting library compatible with treesitter, place the following code in a Python file:

```python
def world() -> int:
    return 12

def hello() -> str:
    y = world()
    return str(y)

class Hello:
    def __init__(self) -> str:
        pass

    def world(self, yolo) -> str:
        pass
```

You should end up with syntax highlighting similar to this:

![treesitter-screenshot](https://user-images.githubusercontent.com/3723671/97330896-04a2a280-1836-11eb-8781-c5f2ef5eccbd.png)

Notice how both the function definition (`def world`) and the function usage (`y = world()`) have the same color? I've used `:TSHighlightCapturesUnderCursor` from the treesitter playground to show the capture groups; they're the same for both sections.

**Expected behavior**

Ideally, the `world` identifier in `def world` and `y = world()` would have different highlight groups to allow colorscheme authors to distinguish between definitions and usage.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## c parser healthcheck
  - OK: c parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for c
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## python parser healthcheck
  - OK: python parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for python
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## html parser healthcheck
  - OK: html parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `folds.scm` query found for html
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for html
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## typescript parser healthcheck
  - OK: typescript parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for typescript
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## query parser healthcheck
  - OK: query parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `folds.scm` query found for query
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for query
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## rust parser healthcheck
  - OK: rust parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `folds.scm` query found for rust
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for rust
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## javascript parser healthcheck
  - OK: javascript parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for javascript
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## tsx parser healthcheck
  - OK: tsx parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for tsx
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-781-ga22fe09b9
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-cf8f8ff3-8560-4d24-8cbb-fea1921bfd23

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Comment by kyazdani42** [comment]
i believe a function call/name should keep the same colors to help users understand it's a function. A function definition or usage is after all, a function right ?
I think this is a convention people agreed on (not perfectly sure though).
If you wish, you could write an additional query to capture the method call and assign another color group to it.
I think @theHamsta is mostly responsible for python files ?

**Comment by theHamsta** [comment]
We had queries for call but we removed all of them. I would also prefer distinguishing functions and calls but we settled to the current solution. Would be possible to make a smoother transition to more fine-grained hl-groups: just have function_call and function linked to the same hl-group. Dunno if this is an urgent issue.

**Comment by pappasam** [comment]
It's certainly not urgent, I'm just raising it so we can keep track of it / collectively consider the feature when more-urgent issues have been handled

**Comment by theHamsta** [comment]
It's easy to fix. Since you're using Python you could add those new subgroups. How about `@function.call` `@method.call`? I guess this was how they were called before they were removed. We should ask @vigoux first, he was involved in the discussion when we removed them.

**Comment by vigoux** [comment]
I agree that people may wan to highlight calls differently than definitions. I think this can be done today by overwriting some highlighting (adding a query in your `after` directory), and changing the highlighting of function definitions.

Adding more capture may not be what we want, managing all of these is starting to be painful.

**Comment by alnj** [comment]
I would really love a feature like this, coding in TypeScript. Is there a straightforward way I could hack it back into the plugin?

**Comment by theHamsta** [comment]
This is now implemented

**Comment by girishji** [comment]
github syntax highlighting distinguishes function definition from use. It is helpful when you scan the file for function definition. Please put back this highlight group, and link it to function/method group so this is a non-issue for people who don't care.
