### ISSUE TITLE
C: query for control flow keywords

### ISSUE THREAD

**Issue by duarm** [nvim-treesitter/nvim-treesitter#6186]
**Is your feature request related to a problem? Please describe.**

I want to highlight keywords which control the flow of execution of my program. Those in C being `return`, `break`, `continue` and `goto`. It's not possible to individually highlight these keywords, as `return` has it's own `@keyword.return` group. `break` and `continue` are part of `@keyword.repeat`, which has the side-effect of also changing `for` and `while`. `goto` is part of the generic `@keyword` group

**Describe the solution you'd like**

Perhaps another query `@keyword.control_flow`,  or a query for each keyword separately.

**Comment by clason** [comment]
Sorry, these capture names are standardized upstream. They cannot be changed lightly. You can write your own queries, though, and use whatever captures you want!
