### ISSUE TITLE
Nvim crashes with "Assertion failed: (did_merge), function ts_parser__handle_error"

### ISSUE THREAD

**Issue by sbbddz** [nvim-treesitter/nvim-treesitter#6189]
### Describe the bug

Nvim crashes when inserting a double quote (") in Rust with this message:

`Assertion failed: (did_merge), function ts_parser__handle_error, file parser.c, line 1475.`

### To Reproduce

I'm not able to reproduce the behavior other than in a concrete file in a concrete project in my system.
However, I can share short video of the moment it crashes:

https://github.com/nvim-treesitter/nvim-treesitter/assets/5954310/70c73964-0449-4302-9bca-6ba1962703c9

It appears to happen only when using panic as a macro, as the video show

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.21.0 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v18.16.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 15.0.0 (clang-1500.1.0.2.5)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.3.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . .
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - requirements        ✓ . . . ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev-2048+g367e52cc7-Homebrew
Build type: Release
LuaJIT 2.1.1703358377
```

**Comment by lucario387** [comment]
@amaanq

**Comment by clason** [comment]
Please report at tree-sitter-rust.

**Comment by amaanq** [comment]
I think, for some unknown reason, https://github.com/tree-sitter/tree-sitter-rust/commit/85a21c96d31b2a5c4369e5836a7f4ab059268fea is the culprit, but I'm not sure why. Your snippet alone can't trigger the crash for me, probably because you're on line 220. Try and reduce the code needed to trigger it and send the *full* code snippet

**Comment by sbbddz** [comment]
> I think, for some unknown reason, [tree-sitter/tree-sitter-rust@85a21c9](https://github.com/tree-sitter/tree-sitter-rust/commit/85a21c96d31b2a5c4369e5836a7f4ab059268fea) is the culprit, but I'm not sure why. Your snippet alone can't trigger the crash for me, probably because you're on line 220. Try and reduce the code needed to trigger it and send the _full_ code snippet
> 
> I got this to reproduce with the seed `5382463102501212970` nvm

Curious on how you've been able to reproduce it. Deleting a bunch of random code in my file appears to fix the problem, tried a couple of things, large files, etc, but couldn't reproduce

**Comment by amaanq** [comment]
1. `git clone https://github.com/tree-sitter/tree-sitter.git`
2. `cd tree-sitter && ./script/fetch-fixtures`
3. `TREE_SITTER_SEED=5382463102501212970 TREE_SITTER_GRAMMAR_DEBUG=1 TREE_SITTER_DEBUG=1 cargo test test_corpus_for_rust -- --nocapture`
