### ISSUE TITLE
Fold: allow to show last line

### ISSUE THREAD

**Issue by zhoudaxia2016** [nvim-treesitter/nvim-treesitter#6199]
I want to config the fold like vscode: show the last line of a fold
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/24446852/ce826d41-b1dc-4986-ac77-1dfecf7ccd14)

I know there is a workround https://github.com/nvim-treesitter/nvim-treesitter/pull/390#issuecomment-709666989

But I want to highlight the foldtext, just as  https://github.com/neovim/neovim/pull/20750 sad.

When set foldtext a non-empty string
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/24446852/5513d215-d96b-413c-b885-22051eeb8fc8)

Can we make them both work?

**Comment by clason** [comment]
No. (Sorry, but that's just how Vim folding works; nothing we can do about it.)
