### ISSUE TITLE
Update and Install `all` Returns Prematurely

### ISSUE THREAD

**Issue by BodneyC** [nvim-treesitter/nvim-treesitter#620]
Hi,

This may be a design decision to begin phasing the `all` phrase out, I don't know, but the `all` option for `TSInstall` and `TSUpdate` no longer do anything.

---

The command `TSUpdate all` calls:

- [`install.update('all')`](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/install.lua#L293) which calls
- [`update(false, 'force')('all')`](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/install.lua#L212)
- The `ask_reinstall` var (currently `'force'`) is then [overwritten with `false` if the language is 'all'](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/install.lua#L190)
- [`install_lang(lang_it, false, ...)`](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/install.lua#L204) is then called, and
- [if the parser exists](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/install.lua#L150) and [`false ~= 'force'`](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/install.lua#L151) and [`false == false`](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/install.lua#L152), then do nothing and return

---

`TSUpdate all` should update all parsers, shouldn't it?

`TSUpdate` (no lang) accomplishes this but `TSInstall` (no lang) does not, it requires an argument.

Currently on d9454afd, Neovim nightly (v0.5.0-782-gb6897ebc0).

---

Please inform me if I've missed something obvious.

**Comment by kyazdani42** [comment]
i think this wont update if the parser is already up to date ^^ check the lockfile.json revision file

**Comment by BodneyC** [comment]
If I delete the bash parser, set the revision to one a little older ([60f2783](https://github.com/tree-sitter/tree-sitter-bash/commit/60f2783804d5f64bdd65fc27dc1832e5b1f8469c) specifically) and run a `TSInstall bash`, I get a parser with an MD5 of 1f86fda8dd3c468e77fe671234bf420e.

If I then restore the revision to what it is currently ([8ece09c](https://github.com/tree-sitter/tree-sitter-bash/commit/8ece09ca4c0b5e59b124cd19fa92c76b1a9e9dd4) specifically) and run a `TSUpdate all`, nothing changes, nothing happens.

`TSUpdate bash` on the other hand will update the version of the parser and produce a .so with an MD5 of 04ed3727b5aacd0396f2936ea04fdc3e. Repeatedly running the same command keeps recompiling the parser to the same .so with the same MD5.

Is there another mechanism for checking if an update is required that I'm unaware of. Or am I missing the point completely (a very definite possibility).

**Comment by kyazdani42** [comment]
this is strange indeed. @theHamsta is this a bug ?

**Comment by theHamsta** [comment]
We don't have Autoupdates at the moment. The parsers are frozen at the moment since the Neovim runtime is the old for some parsers which will cause breakages due to ABI incompatibility. When treesitter becomes a bundled dependency, we would regularly update the lockfile and this `TSUpdate` or a future autodection would give you the newest compatible parser. You can remove your language from the lockfile or change the update_strategy key to get the old behavior of updating to the newest master. The new behavior of freezing was more a hotfix for suddenly broken 0.17.1 parsers.

**Comment by theHamsta** [comment]
Btw incompatible parsers are right now Python, Java, Go. You should leave at least those parsers pinned. The rest should be safe to update.

**Comment by theHamsta** [comment]
When all parsers are installed both `TSinstall all` and `TSupdtae all` do nothing.

I guess the easiest fix would be to let `TSupdat all` behave like TSUpdate and error on a invalid language. TSInstall all could ask for reinstallation if everything is installed.

**Comment by theHamsta** [comment]
https://github.com/neovim/neovim/pull/12931 this PR would enable updating of the lockfile. @vigoux

**Comment by BodneyC** [comment]
Ah, that makes sense, thanks for the clarification.

It is perhaps a little ambiguous but it's only now that I spot multiple references to `TSUpdate` (no lang) in the readme (e.g. [adding parsers](https://github.com/nvim-treesitter/nvim-treesitter#adding-parsers)) but none to `TSUpdate all`.

The quickest and simplest fix for getting `TSUpdate` to behave like `TSUpdate all` would be, I suppose, a check that `lang ~= 'all'`, [here](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/install.lua#L211).

@theHamsta , would you prefer I keep the issue open until the ambiguity is resolved or close it now as your response has answered the initial concern?

**Comment by theHamsta** [comment]
@BodneyC do you want to create a PR for this?

**Comment by BodneyC** [comment]
Can do, it really is only the one edit. See #622 .

**Comment by theHamsta** [comment]
Closed via #622
