### ISSUE TITLE
Consider adding a highlight capture for struct/enum/union keywords

### ISSUE THREAD

**Issue by ebkalderon** [nvim-treesitter/nvim-treesitter#6205]
**Is your feature request related to a problem? Please describe.**

I'd like `nvim-treesitter` to offer greater control for highlighting the keywords for product and sum types (`struct`, `enum`, `union`) separately from other generic keywords. Editors such as Sublime Text, TextMate, and Vim/Neovim offer such functionality in their syntax highlighters, allowing color schemes to color these keywords differently from other keywords, if they so choose:

![241819697-7fbda943-6775-4526-9651-ab8734401399](https://github.com/nvim-treesitter/nvim-treesitter/assets/322831/92f01733-e5af-48c3-abd3-527211b7d8a7)

At the moment, most languages' `highlights.scm` lump these keywords in with other unrelated keywords in the general-purpose `@keyword` capture. Vim/Neovim includes a highlight group name for structs/enums/unions right out of the box ([`Structure`](https://neovim.io/doc/user/syntax.html#group-name)), but `nvim-treesitter` parsers lack an equivalent to this. This makes creating a Treesitter-based color scheme which highlights the `struct` keyword in a unique color, as in the screenshot above, impossible while `nvim-treesitter` is enabled.

**Describe the solution you'd like**

We could add a new `@keyword.structure` entry to the list of standard highlight captures in the ["Keywords" section of CONTRIBUTING.md](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#keywords). This capture would map to the keywords `struct`, `enum`, and `union` in all languages that have such concepts. Color scheme authors could then link `@keyword.structure` to the standard `Structure` Vim/Neovim highlight and specify unique colors for the `struct`, `enum`, and `union` keywords separately from other language keywords.

**Describe alternatives you've considered**

We could do nothing and leave the existing set of standard highlight captures unchanged.

**Additional context**

N/A

**Comment by lucario387** [comment]
Neovim also provide the functionality to do that: Overriding with your custom queries from local. So I don't see an issue with this?

**Comment by ebkalderon** [comment]
Indeed it does. I was wondering if there is any appetite towards adding something like this upstream, similar to the existing `@keyword.function`, `@keyword.storage`, etc. special-case captures that `nvim-treesitter` already uses? Considering that Neovim itself has an equivalent `Structure` highlight group for this exact purpose, it feels a bit odd to me that `nvim-treesitter` doesn't do the same as well.

**Comment by lucario387** [comment]
> onsidering that Neovim itself has an equivalent `Structure` highlight group for this exact purpose, it feels a bit odd to me that `nvim-treesitter` doesn't do the same as well.

But we do have that `Structure` equivalent though? https://github.com/neovim/neovim/blob/master/src/nvim/highlight_group.c#L231

Neovim upstream somewhat defined what the capture is supposed to represent as well

**Comment by ebkalderon** [comment]
Hmm, searching for how `@module` is used inside the `highlights.scm` files in this repo, it doesn't look like it's being used the way [Neovim specifies the `Structure` highlight group should be used](https://neovim.io/doc/user/syntax.html#highlight-groups) (matching the keywords `struct`, `enum`, `union`).

**Comment by lucario387** [comment]
it's the closest :)

Before that we use `@class` or `@type` for struct/enum/union, so not really anything changed

@clason will jump in and decide what is wanted

**Comment by ebkalderon** [comment]
Sounds good! I'd love for folks to weigh in on whether `@class` would be appropriate for reuse with `struct`, `enum`, and `union` instead of defining a new highlight capture. :relaxed:

**Comment by lucario387** [comment]
`@class` was renamed to `@module` so I guess it makes sense somewhat

**Comment by ebkalderon** [comment]
Thanks for the comprehensive explanation here, @clason! Though I admit I am slightly confused regarding the proposal of a new highlight group to Neovim. That wasn't my intention with this proposal, as both Vim and Neovim already supply the `Structure` highlight group for precisely this purpose (that is, highlighting the keywords for declaring a `struct`, `enum`, or `union`). Would you mind clarifying why this would require any changes to upstream Neovim?

Also, I'm more than prepared to open a pull request on `nvim-treesitter` to update all queries and the `CONTRIBUTING.md` provided that folks would be willing to assist with any additional guidance beyond the documented contribution workflow. :smile:

**Comment by clason** [comment]
Because treesitter has its own (more expressive) set of standard highlight groups that is documented just like the legacy groups. These are exactly the groups we enforce here via CI.

**Comment by ebkalderon** [comment]
Ah, makes sense! Thanks for clarifying the situation. :heart:

**Comment by clason** [comment]
We have `@keyword.type` now. Feel free to make a PR adjusting the queries accordingly.

**Comment by ebkalderon** [comment]
Sounds great. I'll open up a PR or two making adjustments as needed.
