### ISSUE TITLE
conceal

### ISSUE THREAD

**Issue by Freed-Wu** [nvim-treesitter/nvim-treesitter#6218]
**Describe the solution you'd like**

## Conceal emoji code in markdown, git-commit, ...

![screen-2024-02-29-17-19-12](https://github.com/nvim-treesitter/nvim-treesitter/assets/32936898/cef0205d-9d31-4485-bd00-f1e13d2d872f)

![screen-2024-02-29-17-19-20](https://github.com/nvim-treesitter/nvim-treesitter/assets/32936898/3a584c18-9ca1-4635-b557-9f1f3f557347)

<https://github.com/markdown-templates/markdown-emojis>

## Conceal html escape characters

![before-html](https://user-images.githubusercontent.com/32936898/193464800-a0f30429-f52a-4a34-8c7d-9dee58c872ea.png)

![after-html](https://user-images.githubusercontent.com/32936898/193464801-0298bd37-7367-4dbe-bacc-87c33b412925.png)

<https://mateam.net/html-escape-characters/>

## Conceal fontawesome

![before-fontawesome](https://user-images.githubusercontent.com/32936898/193462060-ca288f68-cfe7-472c-b3c5-e782fa508500.png)

![after-fontawesome](https://user-images.githubusercontent.com/32936898/193462062-c0e6f837-e2cd-4769-87c6-a511282719c9.png)

<https://fontawesome.com/v5/cheatsheet/pro/>
<https://fontawesome.com/v5/cheatsheet/pro/brands>

- html: `<i class="fa-solid fa-rss"></i>`
- tex: `\faIcon{rss}`
- javascriptreact/typescriptreact: `<FontAwesomeIcon icon="fa-solid fa-rss" />`
- vue: `<font-awesome-icon icon="fa-solid fa-rss" />`

**Comment by Freed-Wu** [comment]
> write your own queries for this.

Do you mean write `queries/markdown_inline/highlights.scm`? Can you give an example to display how to conceal `:XXX:`?

**Comment by Freed-Wu** [comment]
I tried, however, treesitter conceal only support 256 at maximum. Why?

![screen-2024-04-11-23-13-31](https://github.com/nvim-treesitter/nvim-treesitter/assets/32936898/caf02537-2450-4cd4-a673-dc4017a58291)

[Code](https://github.com/Freed-Wu/conceal.vim), Run `scripts/view-test.md.sh`.

**Comment by clason** [comment]
Probably the default `match_limit` of `query:iter_matches()`.

**Comment by clason** [comment]
By calling `iter_matches` with a higher `match_limit`.

**Comment by Freed-Wu** [comment]
Oh, I means:

Now I have a `query/markdown_inline/highlights.scm`. It have > 1000 emoji conceal. However, only 256 emoji conceal will work. Is it possible to change a global variable to make more emoji conceals work?

**Comment by clason** [comment]
No.
