### ISSUE TITLE
Misleading capture names for type qualifiers and  lifetimes

### ISSUE THREAD

**Issue by tomtomjhj** [nvim-treesitter/nvim-treesitter#6238]
Some highlight capture names are scoped inappropriately
* `@type.qualifier`
    * Problem: Most type qualifiers, such as `const`, `public`, `final` are language keywords.
    * Suggested solution: Use `@keyword.type.qualifier`.
* Rust lifetime (`@keyword.storage`)
    * Problem: Rust lifetimes (except for `'static` and `'_`) are not language keywords.
    * Suggested solution
        * normal lifetimes: Use `@type.storage`, `@type.qualifier`, or `@type.qualifier.storage`.
        * `'static` and `'_`: Use `@keyword.type.qualifier` or `@type.{whatever-chosen-above}.builtin`

**Comment by clason** [comment]
Queries are a community effort. Please open a PR instead.

**Comment by tomtomjhj** [comment]
ok then i'll make a pr that
* changes most of `@type.qualifier` to `@keyword.type` and
* changes normal rust lifetime to `@type.qualifier`
* changes builtin rust lifetime to `@keyword.type`

**Comment by clason** [comment]
To be clear, the first point makes sense to me (but someone -- not me -- will have to go through all the captures to make sure a simple rename will not break anything).

The second I leave to the maintainer @amaanq to comment on (which is always easier in the context of a PR).

**Comment by clason** [comment]
> ok then i'll make a pr that

_two_ PRs. These are separate issues.
