### ISSUE TITLE
feat: add gularen parser

### ISSUE THREAD

**Issue by noorwachid** [nvim-treesitter/nvim-treesitter#6266]
**Is your feature request related to a problem?**
Adding Gularen markup language parser

**Describe the solution you'd like**
[This repo](https://github.com/noorwachid/tree-sitter-gularen) has the parser implementation and Neovim queries

**Additional context**
It is yet another Markdown alternative with more features (closer to AsciiDoc)

<img width="1426" alt="Screenshot 2024-03-05 at 17 26 30" src="https://github.com/nvim-treesitter/nvim-treesitter/assets/42460975/83b47342-bfd0-44ef-86da-6f8a03e9b14d">

**Comment by lucario387** [comment]
PR welcome~~
