### ISSUE TITLE
Typescript parser cannot be installed

### ISSUE THREAD

**Issue by ALizarazoTellez** [nvim-treesitter/nvim-treesitter#6275]
### Describe the bug

The typescript parsers cannot be downloads in Windows, other parsers compiles and run ok.

Suspect Party:
```
Can't create '\\\\?\\C:\\Users\\ander...
```

That path is strange...

Full Logs:

```

[nvim-treesitter] [0/1] Downloading tree-sitter-typescript...
[nvim-treesitter] [0/1] Creating temporary directory
[nvim-treesitter] [0/1] Extracting tree-sitter-typescript...
nvim-treesitter[typescript]: Error during tarball extraction.
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/.eslintrc.js^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/.gitattributes^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/.github/^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/.github/ISSUE_TEMPLATE/^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/.github/ISSUE_TEMPLATE/bug_report.yml^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/.github/ISSUE_TEMPLATE/config.yml^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/.github/ISSUE_TEMPLATE/feature_request.yml^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/.github/pull_request_template.md^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/.github/workflows/^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/.github/workflows/ci.yml^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/.github/workflows/lint.yml^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/.github/workflows/release.yml^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/.gitignore^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/.npmignore^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/Cargo.toml^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/LICENSE^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/Package.swift^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/README.md^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/appveyor.yml^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/binding.gyp^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/bindings/^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/bindings/node/^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/bindings/node/binding.cc^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/bindings/node/index.js^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/bindings/node/tsx.js^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/bindings/node/typescript.js^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/bindings/rust/^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/bindings/rust/README.md^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/bindings/rust/build.rs^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/bindings/rust/lib.rs^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/bindings/swift/^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/bindings/swift/TreeSitterTypeScript/^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/bindings/swift/TreeSitterTypeScript/typescript.h^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/common/^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/common/corpus/^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/common/corpus/declarations.txt^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/common/corpus/expressions.txt^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/common/corpus/functions.txt^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/common/corpus/types.txt^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/common/define-grammar.js^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/common/scanner.h^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/examples/^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/examples/parser.ts^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/package.json^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/queries/^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/queries/highlights.scm^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/queries/locals.scm^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/queries/tags.scm^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/script/^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/script/check-generated-files^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/script/known-failures.txt^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/script/parse-examples^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/tsx/^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/tsx/corpus/^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/tsx/corpus/common: Can't create '\\\\?\\C:\\Users\\ander\\AppData\\Local\\nvim-data\\tree-sitter-typescript-tmp\\tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241\\tsx\\corpus\\common'^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/tsx/corpus/expressions.txt^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/tsx/grammar.js^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/tsx/package.json^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/tsx/src/^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/tsx/src/grammar.json^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/tsx/src/node-types.json^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/tsx/src/parser.c^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/tsx/src/scanner.c^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/tsx/src/tree_sitter/^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/tsx/src/tree_sitter/parser.h^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/typescript/^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/typescript/corpus/^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/typescript/corpus/common: Can't create '\\\\?\\C:\\Users\\ander\\AppData\\Local\\nvim-data\\tree-sitter-typescript-tmp\\tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241\\typescript\\corpus\\common'^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/typescript/corpus/expressions.txt^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/typescript/grammar.js^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/typescript/package.json^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/typescript/src/^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/typescript/src/grammar.json^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/typescript/src/node-types.json^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/typescript/src/parser.c^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/typescript/src/scanner.c^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/typescript/src/tree_sitter/^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/typescript/src/tree_sitter/parser.h^M
x tree-sitter-typescript-198e2ea43d1c4ddd76ee883f4eae15f4201cd241/typescript/test.ts^M
tar: Error exit delayed from previous errors.^M
```

Sorry for typos/mistakes, I'm not speak English.

### To Reproduce

Execute: `:TSInstall typescript`

### Expected behavior

Install typescript parser

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.11.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `zig` executable found. Selected from { "zig" }
  Version: info: Usage: zig [command] [options]
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.19045",
  sysname = "Windows_NT",
  version = "Windows 10 Home Single Language"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

```

### Output of `nvim --version`

Original version error found:

```text
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1703942320
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

     archivo "vimrc" del sistema: "$VIM\sysinit.vim"
            predefinido para $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

Nightly build version:

```
NVIM v0.10.0-dev-2551+g8797429a7
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634
Run "nvim -V1 -v" for more info
```

The error happens on both.

### Additional context

Windows user.
Using `zig cc` as C compiler.

Other parsers, as Go, install without problems and works.

The tar program uses strange paths.

I'm not a English speaker, sorry for mistakes/typos/inacuracies...

Thanks for your time.

**Comment by ALizarazoTellez** [comment]
Temporary solution I found:

First make sure you have the `zig` command available in a Powershell and open it in a temporary directory.

```
git clone https://github.com/tree-sitter/tree-sitter-typescript
cd tree-sitter-typescript/typescript/src/
zig cc -o parser.so -shared parser.c scanner.c -O2 -I./
cp ./parser.so $env:localappdata/nvim-data/lazy/nvim-treesitter/parser/typescript.so
``` 

---

Results:

In Neovim, the `:checkhealth nvim-treesitter` command does not complain.
In Neovim, the `:set ft=typescript` and highlight works as expected.

---

I'm not a English speaker, sorry for mistakes/typos/inacuracies...

**Comment by FlippingBinary** [comment]
The `\\\\?\\C:\\Users...` path is perfectly normal on Windows. It's backslash-escaped in the log, but the actual string `\\?\C:\Users...`, is a path in the [Win32 File Namespace](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#win32-file-namespaces).

It looks like the only files that failed to install were symbolic links. Maybe you don't have [Windows Developer mode enabled](https://learn.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development)?

**Comment by anishkumar127** [comment]
same error with lazynvm , astronvm 
with the typescript .ts .tsx file
i did everything still giving same error

12:14:17 PM msg_show   e Error executing lua callback: C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:35: Error executing lua: C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:36: BufReadPost Autocommands for "*"..FileType Autocommands for "*": Vim(append):Error executing lua callback: ...eovim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'tsx': uv_dlopen: no error
stack traceback:
	[C]: in function '_ts_add_language'
	...eovim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: in function 'add'
	...m/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:111: in function 'new'
	...m Files/Neovim/share/nvim/runtime/lua/vim/treesitter.lua:41: in function '_create_parser'
	...m Files/Neovim/share/nvim/runtime/lua/vim/treesitter.lua:108: in function 'get_parser'
	...m Files/Neovim/share/nvim/runtime/lua/vim/treesitter.lua:416: in function 'start'
	...a/lazy/nvim-treesitter/lua/nvim-treesitter/highlight.lua:20: in function 'attach'
	...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'
	...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
	...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:132>
	[C]: in function 'nvim_cmd'
	C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:36: in function <C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:35>
	[C]: in function 'nvim_buf_call'
	C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:35: in function <C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:10>
stack traceback:
	[C]: in function 'nvim_cmd'
	C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:36: in function <C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:35>
	[C]: in function 'nvim_buf_call'
	C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:35: in function <C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:10>
stack traceback:
	[C]: in function 'nvim_buf_call'
	C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:35: in function <C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:10>
12:14:32 PM msg_show   e Error executing lua callback: C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:35: Error executing lua: C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:36: BufReadPost Autocommands for "*"..FileType Autocommands for "*": Vim(append):Error executing lua callback: ...eovim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'tsx': uv_dlopen: no error
stack traceback:
	[C]: in function '_ts_add_language'
	...eovim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: in function 'add'
	...m/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:111: in function 'new'
	...m Files/Neovim/share/nvim/runtime/lua/vim/treesitter.lua:41: in function '_create_parser'
	...m Files/Neovim/share/nvim/runtime/lua/vim/treesitter.lua:108: in function 'get_parser'
	...m Files/Neovim/share/nvim/runtime/lua/vim/treesitter.lua:416: in function 'start'
	...a/lazy/nvim-treesitter/lua/nvim-treesitter/highlight.lua:20: in function 'attach'
	...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'
	...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
	...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...ata/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:132>
	[C]: in function 'nvim_cmd'
	C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:36: in function <C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:35>
	[C]: in function 'nvim_buf_call'
	C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:35: in function <C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:10>
stack traceback:
	[C]: in function 'nvim_cmd'
	C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:36: in function <C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:35>
	[C]: in function 'nvim_buf_call'
	C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:35: in function <C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:10>
stack traceback:
	[C]: in function 'nvim_buf_call'
	C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:35: in function <C:/Program Files/Neovim/share/nvim/runtime/filetype.lua:10>

**Comment by clason** [comment]
Your versions are very outdated. Please update Neovim and nvim-treesitter (remove all, even temporary, files and reinstall).

**Comment by anishkumar127** [comment]
> Your versions are very outdated. Please update Neovim and nvim-treesitter (remove all, even temporary, files and reinstall).

not outdated I have fresh install in my windows 11

**Comment by FlippingBinary** [comment]
@anishkumar127 The phrase `Can't create` followed by a Win32 path doesn't appear in your message, so I think your issue is different than the topic issue. Also, the software versions OP was using in the original topic are outdated, so you might get better assistance if you follow the [troubleshooting steps](https://github.com/nvim-treesitter/nvim-treesitter#troubleshooting) before opening your own issue that includes the context necessary for people to help you figure out what needs to be done.
