### ISSUE TITLE
Add fold text function as well as foldexpr function

### ISSUE THREAD

**Issue by hardenedapple** [nvim-treesitter/nvim-treesitter#6284]
**Is your feature request related to a problem? Please describe.**
In GNU style C/C++ code the return type of the function is on a separate line to the rest of the function declaration.
Using `foldmethod=syntax` this works just fine since it's just the curly braces that are folded.
Using treesitter's `foldexpr` the entire function is folded, and the `foldtext` used is just the return type of the function.
 
**Describe the solution you'd like**
I think it would be nice to provide a default `foldtext` description of what has been folded, taken based on the AST of the folded node.

**Describe alternatives you've considered**
I have hacked together my own `foldtext` function in my config which seems to work fine for me (https://github.com/hardenedapple/vim_repo/blob/9b9aa43ab3dc6a58da6b88e919df6e969c0b4e5b/plugin/treesitter-neovim.lua#L47-L73)

I have also tried folding just the function body with an adjusted `queries/c/folds.scm` in my personal config -- this works fine for me too.

Both seem acceptable, but I thought a `foldtext` specification might be a nice general feature and so am suggesting it.

**Comment by clason** [comment]
Folding itself is handled by Neovim; the functions that were here are just offered for backward compatibility.
