### ISSUE TITLE
My Custom Highlight Change Due To Update

### ISSUE THREAD

**Issue by Kairu-bit** [nvim-treesitter/nvim-treesitter#6286]
i regret updating treesitter my custom highlighting change when lsp was loaded the  property color should be violet but when the lsp loaded it will be orange, many more changes color like function, parameter. my method to highlight

```
vim.cmd([[autocmd FileType * hi @property gui=bold guifg=#7E5EFF guibg=#0F0C1C ]])
```

**Comment by clason** [comment]
That has nothing to do with treesitter; those are LSP semantic tokens which are controlled independently. Please read the Neovim documentation.
