### ISSUE TITLE
My Custom Highlight Change Due To Update

### ISSUE THREAD

**Issue by Kairu-bit** [nvim-treesitter/nvim-treesitter#6290]
i regret updating treesitter my custom highlight change when lsp loaded. the parameter color should be orange but when lsp was loaded it will change to blue many more changes when lsp was loaded like method.call, property, etc...
**MY METHOD TO HIGHLIGHT**

vim.cmd([[autocmd FileType * hi @parameter gui=bold guifg=#ffb20f guibg=#1C1100]])

**HELP ME GUYS I CAN'T CODE WITH THIS GOOFY ASS HIGHLIGHTING**
![IMG_20240314_025330](https://github.com/nvim-treesitter/nvim-treesitter/assets/134563480/24ef54ff-963b-40a4-921a-70d1e09cd78d)

**Comment by lucario387** [comment]
When lsp loaded -> highlight changed -> its semantic tokens, not treesitter. Please do the debugging yourself and learn how to disable semanticTokens by skimming through `:h lsp` doc

**Comment by clason** [comment]
Do not open duplicate issues. Your last post was closed for the exact same reason.
