### ISSUE TITLE
Feature to disable the highlighting for `XXX` in the comment.

### ISSUE THREAD

**Issue by genki** [nvim-treesitter/nvim-treesitter#6295]
**Is your feature request related to a problem? Please describe.**

Yes.
As I often draw some diagrams in the comment by ASCII art style, the highlight for `XXX` in the comment sometimes spoils them. 
Here's an example:

```
A\   /a
B\\ //b
C\\X//c
D\XXX/d
E/XXX\e
F//X\\f
G// \\g
H/   \h
```

**Describe the solution you'd like**
It is the best if there is an option to disable the highlighting of the `XXX` in comment.
Fortunately, I have no culture to use the `XXX` as a marker for anything.

**Describe alternatives you've considered**
It is the 2nd best if there is an option to choose the color of the `XXX` in comment.

**Comment by clason** [comment]
Then you need to override the queries in your config. This is way too niche to address here.
