### ISSUE TITLE
Indentexpr reverts to runtime specified after InsertEnter event

### ISSUE THREAD

**Issue by sunjon** [nvim-treesitter/nvim-treesitter#630]
When a file is first loaded into a buffer, `indentexpr` is set by TS.
After entering and exiting insert mode, it has now been overridden by the runtime indent file.

1. load a file into buffer
2. check the current indentexpr:
```
:verbose set indentexpr
indentexpr=nvim_treesitter#indent()                                                                                               
      Last set from Lua   
```
3. Enter and exit insert mode and repeat:
```
:verbose set indentexpr
indentexpr=GetLuaIndent()                                                                                                         
      Last set from /usr/local/share/nvim/runtime/indent/lua.vim line 13  
```

**Output of `:checkhealth nvim_treesitter`**

```
...
 ## lua parser healthcheck                                                                                                         
    - OK: lua parser found.                                                                                                         
    - OK: highlights.scm found.                                                                                                     
    - OK: locals.scm found.                                                                                                         
    - OK: folds.scm found.                                                                                                          
    - OK: indents.scm found.         
```
---

If `if exists("b:did_indent")` is a standard in the runtime indent files, then perhaps this is solved by TS setting the value?

**Comment by vigoux** [comment]
Hi thanks for that awesome report, could you tell me if #632 fixes your issue ?

**Comment by kyazdani42** [comment]
could not reproduce sorry

**Comment by yujinyuz** [comment]
@kyazdani42 I also have this problem:

[![asciicast](https://asciinema.org/a/m2TsJCitjLKxtA62O3ejKzMUv.svg)](https://asciinema.org/a/m2TsJCitjLKxtA62O3ejKzMUv)

If I open a file via telescope (or maybe any file finder), the `indentexpr` is set via vim runtime.

But if I open the file with the path to file `nvim path/to/file.js` then treesitter sets it properly

**Comment by kyazdani42** [comment]
hum that's strange, i can still not reproduce. Would you have a minimal config file to provide for testing ?

**Comment by yujinyuz** [comment]
@kyazdani42 I want to provide but do you have any ideas how I can prevent neovim from loading things inside `~/.local/share/nvim/site/pack/packer/start`?

Coz I tried opening a minimal config via `nvim -u minrc.vim`, it would load those things in that folder

**Comment by yujinyuz** [comment]
Interesting. I can't seem to reproduce this with a minimal config:

```vim
set nocompatible
set hidden
set laststatus=2
set rnu nu
set autoindent
set expandtab
set packpath=/tmp/vim

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
call plug#end()

" autocmd VimEnter * PlugClean! | PlugUpdate --sync | close


lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained",
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = "gnn",
      node_incremental = "grn",
      scope_incremental = "grc",
      node_decremental = "grm",
    }
  },
  highlight = {
    enable = true,
    disable = {"json"},
    use_languagetree = false,
  },
  indent = {
    enable = true,
  }
}
EOF
```

I'll try again later when I get the time to dig deper

**Comment by yujinyuz** [comment]
I was able to reproduce it by installing telescope and treesitter:

[![asciicast](https://asciinema.org/a/9yITlNhqyTXroTJ4lqvy4D79L.svg)](https://asciinema.org/a/9yITlNhqyTXroTJ4lqvy4D79L)

Steps:
1. First is open the file via telescope and see that `indentexpr` is set differently.
2. Open file via `:e path/to/file.py`. `indentexpr` is set properly

I'm not sure if it had something to do with telescope because in my regular neovim config, if I open the file via step 2, the `indentexpr` is still set via neovim runtime files

**Comment by vigoux** [comment]
Does setting the `indentexpr` to a dummy expression (say `0`), and using `telescope` only allows to reproduce the issue ?

**Comment by yujinyuz** [comment]
@vigoux In my regular neovim config I am able to reproduce this issue even without opening a file using telescope.

I haven't been able to narrow down what was actually causing it to have a different value but the method I posted was just one of the ways I found

**Comment by yzia2000** [comment]
I think, I found a solution to the problem. Let me submit a pr

**Comment by yujinyuz** [comment]
Thanks! It's working now

The patch does make sense too
