### ISSUE TITLE
Highlighting Parameter Does Not Change

### ISSUE THREAD

**Issue by Kairu-bit** [nvim-treesitter/nvim-treesitter#6309]
## Description
I'm experiencing an issue where the syntax highlighting for parameters does not change according to my custom settings when using Tree-sitter in Neovim. Despite setting the highlight for **@parameter** to green, it remains white.
## MY METHOD TO HIGHLIGHT
```
 vim.cmd([[autocmd FileType * highlight! @parameter gui=bold guifg=#ffb20f guibg=#1C1100]])
```
## Expected Behavior
The highlight color for parameters should change to green after applying the custom highlight command.
## Actual Behavior
The highlight color remains white, ignoring the custom settings.
![Uploading IMG_20240317_055252.jpg …]()

**Comment by lucario387** [comment]
Not enough info. Also we don't deal with highlighting, just captures so that you and colorscheme repos can handle it
