### ISSUE TITLE
Support djot

### ISSUE THREAD

**Issue by NoahTheDuke** [nvim-treesitter/nvim-treesitter#6326]
**Is your feature request related to a problem? Please describe.**
[djot](https://github.com/jgm/djot) is a lightweight markup language, a successor to markdown.

**Describe the solution you'd like**
Support through the available [treesitter parser](https://github.com/treeman/tree-sitter-djot).

**Describe alternatives you've considered**
1. Do nothing.
2. Write my own parser.
3. Not share my personal config.

**Additional context**
I already have the commit ready for this.

**Comment by clason** [comment]
No licking the cookie; we don't take requests. Just make a PR.
