### ISSUE TITLE
Cursor is indented after HTML void elements

### ISSUE THREAD

**Issue by LeviOP** [nvim-treesitter/nvim-treesitter#6332]
Currently, inserting a newline after an HTML void element will indent the cursor:
```html
<img src="img.png">
    |
```
It doesn't, however, indent after void elements `meta` and `link` because those have a special case:
https://github.com/nvim-treesitter/nvim-treesitter/blob/36860295919fb18e57cd637b2a5f22e16f750c2f/queries/html_tags/indents.scm#L1-L14

To fix this, all of the void elements should be added to this list of "special" elements (and maybe rename that to void element instead?). Though to stay consistent with the way that `tree-sitter-html` parses void elements, we should use all of the following tags (deprecated or not) that functionally cannot have children:

https://github.com/tree-sitter/tree-sitter-html/blob/cc53b6878a003cf26d213025af49c78388cebe21/src/tag.h#L7-L29

I had considered opening a pull request, but I'm interested in how we should deal with the case-insensitivity of HTML. `<IMG>` will be treated the same way as `<img>` (and `<iMg>`, etc.) by HTML parsers (and by extension `tree-sitter-html`), so I would think that we should handle that. I don't see a clear way to do that which wouldn't be very computationally expensive, _especially_ considering how many void-like elements that there are, so I'm wondering how I should proceed. Thanks.

**Comment by lucario387** [comment]
I'd say just cover for the lowercase and capitalized case. Mixed like aReA, don't care abt it

**Comment by LeviOP** [comment]
The other, maybe more correct solution, would be for tree-sitter-html to expose void element nodes as named so that we could easily capture them and not have to worry about capitlization
