### ISSUE TITLE
Error detected while processing FileType Autocommands for "*"

### ISSUE THREAD

**Issue by huyvohcmc** [nvim-treesitter/nvim-treesitter#634]
**Describe the bug**

I just updated plugins then `:TSUpdate` and now whenever I open a `ruby` or `go` file, this error pops up:
```
Error detected while processing FileType Autocommands for "*":
E5108: Error executing lua ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:71: attempt to index a nil value 
```
I tested with other languages and they don't have this issue.

**Output of `nvim --version`**
```
NVIM v0.5.0-775-gb59b8dd5b5fb
```

**Additional context**
Here is my [neovim config](https://github.com/huyvohcmc/dotfiles/blob/master/nvim/init.vim).

```
packadd minpac

call minpac#init()
call minpac#add('k-takata/minpac', { 'type': 'opt' })
call minpac#add('fatih/vim-go', { 'type': 'opt' })
call minpac#add('vim-ruby/vim-ruby', { 'type': 'opt' })
call minpac#add('nvim-treesitter/nvim-treesitter')

augroup pack_filetype
  autocmd!
  autocmd FileType go packadd vim-go
  autocmd FileType ruby packadd vim-ruby
augroup END

lua <<EOF
vim.cmd('packadd nvim-treesitter')
require'nvim-treesitter.configs'.setup {
  ensure_installed = "all",     -- one of "all", "language", or a list of languages
  highlight = {
    enable = true,              -- false will disable the whole extension
  },
}
EOF
```

**Comment by ChristianChiarulli** [comment]
Same issue here for Python.

**Comment by vigoux** [comment]
Hi, and thanks for reporting.
Both of your nvim version seems a bit old, could you try updating first ?

If the issue persists, try updating both the plugin and run `TSUpdate`.

**Comment by ChristianChiarulli** [comment]
Updated to `NVIM v0.5.0-804-geee066881` and everything is working.

I definitely thought I had the newest version, thanks.

**Comment by theHamsta** [comment]
Sorry! Forgot to include a warning https://github.com/nvim-treesitter/nvim-treesitter/pull/629#issuecomment-721329733

We really need to automate `TSUpdate`. We should write the revision of the parser to disk whenever it's installed to detect when lockfile was updated.

**Comment by vigoux** [comment]
I'd actually suggest everyone to run `TSUpdate` after each plugin update, most plugin managers do that

**Comment by huyvohcmc** [comment]
Updated and it's working again!

**Comment by Rimann91** [comment]
I am experiencing this issue on windows. Using nvim 0.8.3 and I have updated all plugins, run TSUpdate as well as TSUpdateSync. The problem persists. It makes tree sitter completely unusable for some files. I have to disable treesitter until I figure out how to fix it

**Comment by clason** [comment]
Please don't comment on ancient closed issues. If you run into an issue (that is not already reported in an open issue), open a new one with _your_ (minimal) reproducing steps.
