### ISSUE TITLE
Allow using globally installed tree-sitter-cli instead of leting source compiled parsers pull tree-sitter-cli again. 

### ISSUE THREAD

**Issue by glyh** [nvim-treesitter/nvim-treesitter#6354]
using tree sitter parsers from source used to work on my end but it's not working now due to a combo of GFW and https://github.com/tree-sitter/tree-sitter/issues/3213 . I have tree-sitter installed globally, though, this plugin should allow  users to use tree-sitter cli installed on local machine, so it plays nicely with mason.

**Comment by clason** [comment]
No details, no repro, nothing we can do. 

A global install of treesitter works fine at least for me.

**Comment by clason** [comment]
I recommend opening an issue with mason (and a lot more details).

**Comment by glyh** [comment]
You can't reproduce this unless you have the same network condition as I do.

**Comment by clason** [comment]
I have been there often. While I feel your pain, it's still out of scope for this plugin, especially without any details to make this actionable.

**Comment by clason** [comment]
Especially since we have a bunch of options already to work around network issues.

**Comment by glyh** [comment]
A simple reproduce just from [fsharp](https://github.com/Nsidorenco/tree-sitter-fsharp), where the parser is compiled from source.

```
local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
parser_config.fsharp = {
  install_info = {
    url = "https://github.com/Nsidorenco/tree-sitter-fsharp",
    branch = "develop",
    files = {"src/scanner.cc", "src/parser.c" },
    generate_requires_npm = true,
    requires_generate_from_grammar = true
  },
  filetype = "fsharp",
}
```

BTW, I have already set the github download link with mirrors, but that can't prevent a script invoked by npm willing download files from github.

**Comment by clason** [comment]
Nothing we can do about that. That is on the parsers.

**Comment by glyh** [comment]
Okay, I file an issue at their end.
