### ISSUE TITLE
attempt to index a nil value

### ISSUE THREAD

**Issue by rmGFW** [nvim-treesitter/nvim-treesitter#636]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Output of `:checkhealth nvim_treesitter`**
![image](https://user-images.githubusercontent.com/66858140/98212492-a33daa80-1f7e-11eb-949e-c848b6229bea.png)

<details>
<code>

![image](https://user-images.githubusercontent.com/66858140/98212282-4fcb5c80-1f7e-11eb-8a89-6e36f936993b.png)

</code>
</details>

**Output of `nvim --version`**
```
Paste your output here
```

**Additional context**

**Comment by rmGFW** [comment]
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Output of `:checkhealth nvim_treesitter`**
> ![image](https://user-images.githubusercontent.com/66858140/98212492-a33daa80-1f7e-11eb-949e-c848b6229bea.png)
> 
> ` ![image](https://user-images.githubusercontent.com/66858140/98212282-4fcb5c80-1f7e-11eb-8a89-6e36f936993b.png) `
> **Output of `nvim --version`**
> 
> ```
> Paste your output here
> ```
> 
> **Additional context**
> Add any other context about the problem here.

NVIM v0.5.0-754-g3566244d0

**Comment by vigoux** [comment]
Hi, your neovim version is fairly old, could you try updating both nvim and the plugin, then run `TSUpdate` ?

**Comment by rmGFW** [comment]
> Hi, your neovim version is fairly old, could you try updating both nvim and the plugin, then run `TSUpdate` ?

same version on the other machine works well 

I think it crash when install elm
![image](https://user-images.githubusercontent.com/66858140/98212914-4393cf00-1f7f-11eb-9aeb-08970d3dcedb.png)

**Comment by vigoux** [comment]
What is the plugin version then ?

**Comment by theHamsta** [comment]
We had a similar bug earlier. Elm requires C++11. Your compiler must default to at least C++11. `:TSInstallSync` reveals the compiler error.

**Comment by theHamsta** [comment]
Ruby queries has been updated to the newest parser version.

**Comment by theHamsta** [comment]
From were does this -std=c99 flag come from? It's not in our code base? We can not set standard flags since we try to compile c and c++ sources in one compiler invokation.

Just use a not to ancient compiler. c++11 was released 9 years ago and `auto` should be understood by any C++ compiler without any flags. I'd recommend setting env variable `CC` to newer version of gcc.

You can also set repo.url to a local dir and replace `auto` by the actual data type (uint8_t?)
```
  require "nvim-treesitter.parsers".get_parser_configs().query = {
  install_info = {
   url = "~/projects/tree-sitter-elm",
     files = {"src/parser.c", "src/scanner.cc"}
    }
  }
```

**Comment by theHamsta** [comment]
@rmGFW do you still have this issue?

**Comment by rmGFW** [comment]
> @rmGFW do you still have this issue?

my gcc version is 
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)
isn't this version new enough ?

**Comment by kyazdani42** [comment]
how can you have such an old version ? mine is 10.x ^^

**Comment by kyazdani42** [comment]
from [this page](https://gcc.gnu.org/releases.html), your version is 5years old.

**Comment by theHamsta** [comment]
I would prefer not supporting such old versions over a separate compilation for C and C++ files (which would enable setting both C99 and C++11, err we don't even know the standard the parser wants). Any other opinions?

**Comment by rmGFW** [comment]
> how can you have such an old version ? mine is 10.x ^^

This is my company's computer 🤣

**Comment by rmGFW** [comment]
> I would prefer not supporting such old versions over a separate compilation for C and C++ files (which would enable setting both C99 and C++11, err we don't even know the standard the parser wants). There is only very few languages that require fancy C++ features. Any other opinions?
> 
> Btw. 5 years old are only the bug fix releases. Original 4.8 is from March 22, 2013.

I see . so think you can close the issue now 😄 . thanks
