### ISSUE TITLE
Support # style comments for injected langs in nix files

### ISSUE THREAD

**Issue by nadir-ishiguro** [nvim-treesitter/nvim-treesitter#6380]
**Is your feature request related to a problem? Please describe.**
Nix recently adopted [rfc-166](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#parser-configurations) and [an official formatter along with it](https://github.com/NixOS/nixpkgs/pull/276503). 

The issue is that this new formatter converts any existing `/* comments */` into `# comments`. This means that it's no longer possible to tell Treesitter about any injected languages via comments, as it doesn't recognize this style.

**Describe the solution you'd like**
Supporting `# style` comments would be enough. There is an existing PR for that,  that was closed for staleness: #5785

**Comment by clason** [comment]
Then make a new PR. Queries are community-maintained.
