### ISSUE TITLE
`markdown_inline` doesn't show ini fenced code blocks

### ISSUE THREAD

**Issue by stevenxxiu** [nvim-treesitter/nvim-treesitter#6388]
### Describe the bug

The following block gets highlighted as raw code instead of INI:

```ini
[section]
foo = bar
```

### To Reproduce

1. Copy the above code block.
2. Run `:Inspect` in the code block.
3. This gives:

```
Treesitter
  - @markup.raw.block.markdown links to @markup.raw markdown
```

### Expected behavior

I expect INI to be highlighted there.

### Output of `:checkhealth nvim-treesitter`

```
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.22.2 (fc15f621334a262039ffaded5937e2844f88da61) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v21.7.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.8.2-arch2-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cmake               ✓ . ✓ ✓ .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - diff                ✓ . . . .
  - dockerfile          ✓ . . . ✓
  - git_config          ✓ . ✓ . ✓
  - git_rebase          ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . .
  - hjson               ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - ini                 ✓ . ✓ . .
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - kdl                 ✓ ✓ ✓ ✓ ✓
  - latex               ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - nu                  ✓ . . ✓ ✓
  - perl                ✓ . ✓ . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - readline            ✓ . ✓ ✓ ✓
  - regex               ✓ . . . .
  - rust                ✓ ✓ ✓ ✓ ✓
  - sql                 ✓ . . ✓ ✓
  - ssh_config          ✓ ✓ ✓ ✓ ✓
  - tmux                ✓ . . . ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - typst               ✓ . ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - xml                 ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
That is the expected behavior.

**Comment by stevenxxiu** [comment]
Sorry in the issue I forgot a few backticks. I edited it.

Shouldn't fenced code blocks work with INI?

**Comment by clason** [comment]
Yes, and it does for me.

**Comment by stevenxxiu** [comment]
For that command I get:

```
(section) ; [1:1 - 5:0] markdown
 (fenced_code_block) ; [1:1 - 5:0] markdown
  (fenced_code_block_delimiter) ; [1:1 - 3] markdown
  (info_string) ; [1:4 - 6] markdown
   (language) ; [1:4 - 6] markdown
  (block_continuation) ; [2:1 - 0] markdown
  (code_fence_content) ; [2:1 - 4:0] markdown
   (block_continuation) ; [3:1 - 0] markdown
   (block_continuation) ; [4:1 - 0] markdown
  (fenced_code_block_delimiter) ; [4:1 - 3] markdown
```

**Comment by clason** [comment]
Can you test the latest Neovim nightly?

**Comment by stevenxxiu** [comment]
I tested `bash`, `sh`, `nu`, `js`, `py`. Those seem to work fine.

I could test nightly later on. Does it only work for nightly?

**Comment by stevenxxiu** [comment]
Sorry but where is your working setup?

**Comment by stevenxxiu** [comment]
Here's a minimal reproducible config for me. In `init.lua`:

```lua
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable', -- latest stable release
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

require('lazy').setup({
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  config = function()
    local configs = require('nvim-treesitter.con
![Screenshot_2024-04-03_03-14-28](https://github.com/nvim-treesitter/nvim-treesitter/assets/2058940/8f46b701-4803-4901-9a0e-00ca22460ed2)
figs')

    configs.setup({
      ensure_installed = {
        'ini',
        'markdown',
        'javascript',
      },
      sync_install = false,
      highlight = { enable = true },
      indent = { enable = true },
    })
  end,
})
```

In `foo.md`:

````md
```ini
[section]
foo = bar
```

```js
const foo = 1
```
````

I run this with:

    $ /usr/bin/nvim --clean -u init.lua foo.md

A screenshot:

![Screenshot_2024-04-03_03-14-28](https://github.com/nvim-treesitter/nvim-treesitter/assets/2058940/7b535025-c552-475b-98e8-ebd5ea0c05dd)

**Comment by clason** [comment]
And the `ini` parser is in fact installed?

**Comment by stevenxxiu** [comment]
(Sorry deleted the comment by accident before. A repost.)

Here's a minimal reproducible config for me. In `init.lua`:

```lua
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable', -- latest stable release
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

require('lazy').setup({
  'nvim-treesitter/nvim-treesitter',
  build = ':TSUpdate',
  config = function()
    local configs = require('nvim-treesitter.con
![Screenshot_2024-04-03_03-14-28](https://github.com/nvim-treesitter/nvim-treesitter/assets/2058940/8f46b701-4803-4901-9a0e-00ca22460ed2)
figs')

    configs.setup({
      ensure_installed = {
        'ini',
        'markdown',
        'javascript',
      },
      sync_install = false,
      highlight = { enable = true },
      indent = { enable = true },
    })
  end,
})
```

In `foo.md`:

````md
```ini
[section]
foo = bar
```

```js
const foo = 1
```
````

I run this with:

```
$ /usr/bin/nvim --clean -u init.lua foo.md
```

A screenshot:

![Screenshot_2024-04-03_03-14-28](https://github.com/nvim-treesitter/nvim-treesitter/assets/2058940/f2ef09e9-5b8f-4f97-b3ad-7125a46caa59)

**Comment by stevenxxiu** [comment]
> (Your minimal config uses the standard lazy path so will likely conflict with your installed plugins. There's zero reason to use Lazy for a minimal repro -- just clone nvim-treesitter itself and add the path to `rtp`.)

I tried your suggestion. I cloned the repo to a temporary directory. Here's my new config file:

```lua
vim.opt.runtimepath:prepend("/run/user/1000/nvim/nvim-treesitter")

require("nvim-treesitter.configs").setup({
        ensure_installed = {
                "ini",
                "markdown",
                "markdown_inline",
                "javascript",
        },
        sync_install = false,
        highlight = {
                enable = true,
                additional_vim_regex_highlighting = false,
        },
})
```

The same thing occurs.

I see these `.so` files in `/run/user/1000/nvim/nvim-treesitter/parser/`:

- `ini.so`
- `javascript.so`
- `markdown_inline.so`
- `markdown.so`

**Comment by lucario387** [comment]
It also works for me so I think the problem is just stable version of neovim lacking something to detect it?

**Comment by stevenxxiu** [comment]
This happens to me even on *Termux*. *INI* seems to be the only language that doesn't work. Is there some way for me to dig deeper to see what the issue might be?

**Comment by clason** [comment]
Yes, try to compile the parser manually and see if it works via `tree-sitter` CLI.

**Comment by stevenxxiu** [comment]
Do you mean the *INI* parser? *INI* files themselves do get parsed correctly, just not inside *Markdown* files as code blocks.

If you mean the *Markdown* parser do I need to incorporate <https://github.com/nvim-treesitter/nvim-treesitter/blob/v0.9.2/queries/markdown/injections.scm> somehow?

**Comment by clason** [comment]
Oh, you're pinned on 0.9.2?

**Comment by stevenxxiu** [comment]
Oh no I'm using the latest commit. I just linked that to make the link shorter.

**Comment by clason** [comment]
I don't know what to tell you then; I have literally zero idea how the behavior you describe is possible.

**Comment by stevenxxiu** [comment]
This appears to be related to syntax aliases for me. I see some in <https://github.com/nvim-treesitter/nvim-treesitter/blob/fbe76211f45413feadb155a89073bf65b5766b2e/lua/nvim-treesitter/parsers.lua#L28>. `javascriptreact`, `ecma`, `jsx` don't work, when `js` and `javascript` do.

**Comment by clason** [comment]
Hmmm. Can you try adding `ini = "ini"` to that list?

**Comment by stevenxxiu** [comment]
Neither `dosini` nor `confini` work. However for an `ini` code block, I do get `dosini` returned for `metadata["injection.language"]` in <https://github.com/nvim-treesitter/nvim-treesitter/blob/fbe76211f45413feadb155a89073bf65b5766b2e/lua/nvim-treesitter/query_predicates.lua#L175>.

**Comment by clason** [comment]
Ah, ok. Yeah, that predicate has always been iffy. Can you try the injection queries from the `main` branch? (Might need Nvim nightly.)

**Comment by clason** [comment]
> I was always on the main branch, but not on Neovim nightly. 
 
That would have been important information and avoided my wasting significant time on this.

As the README on main makes abundantly clear, it is NOT compatible with 0.9.x and **requires** (the latest, **always**) nightly. Nobody knows when 0.10 will be released, and until `main` is declared stable (which is even longer), it will keep following Nvim HEAD.

**Comment by stevenxxiu** [comment]
Ah sorry I meant I was using `master`. I was a bit confused as there's both `master` and `main`. I just checked for a *LazyGit* update, and the commits it showed matches `master`.
