### ISSUE TITLE
Indention broken for javascript with vim-graphql

### ISSUE THREAD

**Issue by sQVe** [nvim-treesitter/nvim-treesitter#641]
**Describe the bug**
The indention of `javascript` is broken if you use `nvim-treesitter` together with `vim-graphql`. 

**To Reproduce**
1. Install `nvim-treesitter` with settings:
```
" Treesitter.
lua <<EOF
require'nvim-treesitter.configs'.setup {
  highlight = { enable = true },
  indent = { enable = true },
}
EOF
```
2. Install `vim-graphql`
3. Open `javascript` file and play around with indention.

**Expected behavior**
Indention should work correctly.

Refs: https://github.com/jparise/vim-graphql/issues/67

**Comment by sQVe** [comment]
I currently solve this issue by disabling the plugin. It's used by `vim-polyglot` so I have added this before sourcing my plugins:

```vim
" Disable polyglot language packs which are handled by treesitter.
let g:polyglot_disabled = [
  \ 'css.plugin',
  \ 'graphql', " Disable due to indentation issues.
  \ 'html.plugin',
  \ 'javascript.plugin',
  \ 'json.plugin',
  \ 'jsx.plugin',
  \ 'sh.plugin',
  \ 'typescript.plugin',
  \ 'yaml.plugin',
  \ ]
```

**Comment by kyazdani42** [comment]
i'm not sure why graphql files would intervene with javascript indentation. Does this plugin highlight/indent gql template strings ?

**Comment by sQVe** [comment]
Yes. https://github.com/jparise/vim-graphql

**Comment by kyazdani42** [comment]
well when i'm done with #619, you wont need vim-graphql no more :)
Although i should also finish #638 so we can extend indentation, and maybe another PR for region based indentation :)

**Comment by sQVe** [comment]
@kyazdani42 That's awesome. 

We should try to get this fixed thought as `vim-graphql` is used internally in `vim-polyglot` which is very popular. `vim-grapql` essentially breaks indention for all files with `ft` set to `javascript`. This will likely lead to the user/developer uninstalling `nvim-treesitter` rather than the real culprit.

**Comment by kyazdani42** [comment]
indeed. I think this has something to do with treesitter highlighting setting syntax off or loading synload, i'm not sure. I dont know how to fix this issue though.

**Comment by sQVe** [comment]
Fixed via https://github.com/jparise/vim-graphql/pull/70.
