### ISSUE TITLE
Disable injections for large files

### ISSUE THREAD

**Issue by vanaigr** [nvim-treesitter/nvim-treesitter#6435]
**Is your feature request related to a problem? Please describe.**
Neovim runs injection queries for the entire buffer on each edit. For large files, a significant portion of the time is spent executing injection queries, even if the file doesn't contain any injections.

**Describe the solution you'd like**
I think something similar to the `highlight`'s `disable(lang, bufnr)` could be added, but for injections.

**Describe alternatives you've considered**
Not running injection queries for the entire buffer. Though, I think it could break [`combined injections`](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection) in some situations
> injection.combined - indicates that all of the matching nodes in the tree should have their content parsed as one nested document.

**Additional context**

The redraw time and injection query execution time:
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/65824523/4171c3d9-ef37-45a3-8833-0a9f613859b4)

<details>

<summary>init.lua</summary>

```lua
local line = 'int func(int a, int b) { return a + b; }'
local lines = {}
for i = 1, 10000 do lines[i] = line end

vim.api.nvim_buf_set_lines(0, 0, 1, false, lines)
vim.cmd('set ft=c')


local path = "/tmp/nvim-treesitter-injections-perf"

local lazypath = path .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
    print('Downloading Lazy.nvim')
    vim.fn.system({
        "git", "clone", "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable",
        lazypath,
    })
end

vim.opt.rtp:prepend(lazypath)
require('lazy').setup({ { 'nvim-treesitter/nvim-treesitter' } }, { root = path .. '/plugins' })

local tspath = path .. '/parsers'
vim.opt.runtimepath:append(tspath)
require'nvim-treesitter.configs'.setup{
    parser_install_dir = tspath,
    ensure_installed = { 'c' },
    sync_install = false,
    auto_install = true,
    highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
    },
}
```

</details>

<details>

<summary>patch for measuring time for neovim commit 2c5fd3f966</summary>

```diff
diff --git a/runtime/lua/vim/treesitter/highlighter.lua b/runtime/lua/vim/treesitter/highlighter.lua
index 3f7e31212..0b167b0c4 100644
--- a/runtime/lua/vim/treesitter/highlighter.lua
+++ b/runtime/lua/vim/treesitter/highlighter.lua
@@ -400,10 +400,13 @@ function TSHighlighter._on_win(_, _win, buf, topline, botline)
   return true
 end
 
+local start
 api.nvim_set_decoration_provider(ns, {
   on_win = TSHighlighter._on_win,
   on_line = TSHighlighter._on_line,
   _on_spell_nav = TSHighlighter._on_spell_nav,
+  on_start = function() start = vim.uv.hrtime() end,
+  on_end = function() print("Total: " .. ((vim.uv.hrtime() - start) / 1000000)..'ms') end,
 })
 
 return TSHighlighter
diff --git a/runtime/lua/vim/treesitter/languagetree.lua b/runtime/lua/vim/treesitter/languagetree.lua
index 990debc77..18b4a44e3 100644
--- a/runtime/lua/vim/treesitter/languagetree.lua
+++ b/runtime/lua/vim/treesitter/languagetree.lua
@@ -403,7 +403,7 @@ function LanguageTree:_add_injections()
     end
   end
 
-  return query_time
+  return query_time, injections_by_lang
 end
 
 --- Recursively parse all regions in the language tree using |treesitter-parsers|
@@ -441,7 +441,9 @@ function LanguageTree:parse(range)
   end
 
   if not self._injections_processed and range ~= false and range ~= nil then
-    query_time = self:_add_injections()
+    local injections
+    query_time, injections = self:_add_injections()
+    print("Injections: " .. query_time .. 'ms, '..vim.inspect(injections))
     self._injections_processed = true
   end
```

</deatils>

**Comment by clason** [comment]
> Neovim runs injection queries for the entire buffer on each edit.

I don't think that's correct. After recent changes, it only runs injection queries for the viewport.

**Comment by vanaigr** [comment]
> > Neovim runs injection queries for the entire buffer on each edit.
> 
> I don't think that's correct. After recent changes, it only runs injection queries for the viewport.

It parses injections themselves lazily (neovim/neovim#22309, neovim/neovim#24647), but the queries are run if any region is invalidated neovim/neovim#22426 (task 8).
`LanguageTree:_get_injections()` uses root node's coordinates are used for iterating matches:
https://github.com/neovim/neovim/blob/4f3d018d15d299b66a341bed4d677d7ec03ad44f/runtime/lua/vim/treesitter/languagetree.lua#L856-L863

**Comment by clason** [comment]
I'm not sure the complexity is worth it. In any case, highlighting (and injections) are completely handled by Neovim; this project only coordinates queries (and provides a thin wrapper around `vim.treesitter.start()`, which will be removed in the next version). So this issue -- if at all -- belongs at `neovim/neovim`.

**Comment by tomtomjhj** [comment]
> Not running injection queries for the entire buffer. Though, I think it could break [combined injections](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection) in some situations

https://github.com/neovim/neovim/pull/26827 implements this.

**Comment by clason** [comment]
(was just about to edit my comment to point that out)
