### ISSUE TITLE
Python incorrectly indents brackets

### ISSUE THREAD

**Issue by dbrozovic** [nvim-treesitter/nvim-treesitter#6436]
### Describe the bug

I was messing around with ANSI color escape sequences when I discovered that my python indentation doesn't account for open parentheses/brackets inside string literals and attempts to indent the following line(s) as the start of a block.

```python
foo = "["
        |
```

Upon further inspection I found that "unclosed" parentheses/brackets in comments also cause the same behavior.

```python
bar = 0 #(
        |
```

### To Reproduce

1. Use the default configuration
2. Open a python file
3. Write a comment or string literal containing `(`, `[`, or `[`
4. Press enter

### Expected behavior

These characters should not cause an additional level of indenting when inside a string or comment.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v21.7.2 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20230801
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.6.26-1-lts",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Thu, 11 Apr 2024 09:22:29 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by lucario387** [comment]
Please enable syntax first. It seems like it's using syntax indenting but syntax is off

**Comment by dbrozovic** [comment]
I have `syntax on` in my vimrc, is there some more configuration I need to do in my `init.lua`?

**Comment by lucario387** [comment]
Yes, because enabling treesitter highlighting disables syntax for a buffer

**Comment by dbrozovic** [comment]
Oh, I hadn't realized that. A little bit of tinkering and the "issue" is resolved. Thanks for the help
