### ISSUE TITLE
stack corruption detected (-fstack-protector)

### ISSUE THREAD

**Issue by Kairu-bit** [nvim-treesitter/nvim-treesitter#6453]
### Describe the bug

I have Treesitter JavaScript installed in my nvchad. However, when I'm in insert mode and type something, then press enter, it says 'stack corruption detected (-fstack-protector),' and it kicks me out of nvim. But when I uninstall Treesitter JavaScript, in insert mode, typing something and pressing enter doesn't kick me out of nvim; it works fine.

### To Reproduce

1. Open the nvim JavaScript file.
2. Ensure that treesitter for JavaScript is installed.
3. Enter insert mode and type something, then press Enter.
4. You may encounter an error message saying "stack corruption detected (-fstack-protector)."
5. This error causes nvim to exit unexpectedly.

### Expected behavior

I expected that upon pressing Enter after typing something in insert mode in the nvim JavaScript file with treesitter JS installed, the input would be processed without any errors

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.22.5 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v21.6.2 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: clang version 18.1.3
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "armv7l",
  release = "4.9.193-perf-gc01f2fd",
  sysname = "Linux",
  version = "#1 SMP PREEMPT Tue Dec 28 20:04:50 CST 2021"
} ~

Parser/Features         H L F I J
  - javascript          ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - printf              ✓ . . . .
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/data/data/com.termux/files/usr/share/nvim"
```

**Comment by clason** [comment]
Please report this at the tree-sitter-javascript repository (but check open/closed issues first, and try uninstalling and reinstalling (from grammar) before that).
