### ISSUE TITLE
Can't setup or activate in init.vim

### ISSUE THREAD

**Issue by tammarut** [nvim-treesitter/nvim-treesitter#647]
When I put this code in my init.vim and restart.
```
require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained",
  highlight = {
    enable = true,
  },
}
```
But It **won't work!** ❌

Here's my errors
![68c207a1f0645fcaba1232f77909f6f6.png](https://www.img.in.th/images/68c207a1f0645fcaba1232f77909f6f6.png)
### What shold I do?
一一一一一一一一一一一一
My Neovim version (installed from `nvim.appimage`)
![85735fee9e21e2e359e2d2fa49c61345.png](https://www.img.in.th/images/85735fee9e21e2e359e2d2fa49c61345.png)

My init.vim
![cb1f30cc1344d3ea03a3165d9c789fca.png](https://www.img.in.th/images/cb1f30cc1344d3ea03a3165d9c789fca.png)

**Comment by stsewd** [comment]
Hi, I think you are missing

```vim
lua <<EOF

<Code from the example here>

EOF
```

See https://github.com/nvim-treesitter/nvim-treesitter/pull/644/

**Comment by tammarut** [comment]
Nice! Thanks!💙

This works!✔️
```
lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained",
  highlight = {
    enable = true,
    disable = { "c", "rust" },
  },
}
EOF
```

**Comment by picolloo** [comment]
I'm having kind of a same problem, my init.vim sources a treesitter.vim file like this:

init.vim
```vim
for f in split(glob('~/.config/nvim/plugins.d/*.vim'), '\n')
    exe 'source' f
endfor
```

treesitter.vim
```vim
lua <<EOF
require'nvim-treesitter.configs'.setup {
    ensure_installed = {"bash", "javascript", "ruby", "go", "dockerfile", "html", "json", "yaml"},

    highlight = {
      enable = true,
    },
    indent = {
      enable = true
    },
    textobjects = {
      select = {
        enable = true,
        keymaps = {
          ["af"] = "@function.outer",
          ["if"] = "@function.inner",
          ["ab"] = "@block.outer",
          ["ib"] = "@block.inner",
          ["as"] = "@statement.outer",
          ["is"] = "@statement.inner",
          ["ac"] = "@conditional.outer",
          ["ic"] = "@conditional.inner",
        }
      }
    }
}
EOF
```

When I start vim I get the message: error trying to parse file treesitter.vim at the last EOF line
