### ISSUE TITLE
Language Specific Highlights

### ISSUE THREAD

**Issue by tjdevries** [nvim-treesitter/nvim-treesitter#648]
Hi :)

I was thinking it would be cool if we could make highlights prepend the name of their filetype for better customization. These highlights would be linked by default to their counterpart.

`highlight default link TSAnnotationPython TsAnnotation`

This will let different things in different languages be highlighted differently if the user so decides.

I am distracted right now, so maybe I didn't explain this great. Just didn't want to forget.

**Comment by tjdevries** [comment]
( @vigoux I think we talked about this before )

**Comment by vigoux** [comment]
Jokes on you I already opened a pr for that : https://github.com/neovim/neovim/pull/13278

**Comment by Shougo** [comment]
This is nice.  I want to use the feature in context_filetype.vim.
https://github.com/Shougo/context_filetype.vim

And some default syntax files use similar feature like Vim script.

**Comment by stsewd** [comment]
We already do this, all hl groups have the  `{lang}TSGroup` prefix.
