### ISSUE TITLE
highlighter.lua:71: attempt to index a nil value

### ISSUE THREAD

**Issue by lanox** [nvim-treesitter/nvim-treesitter#649]
**Describe the bug**
Trying to install nvim-treesitter I seem to be getting following error message `highlighter.lua:71: attempt to index a nil value`.

My Configuration.

macos 11.0.1

`init.lua` contains.
`require("plugin.treesitter")`

`lua/plugin` containes

`treesitter.lua`

```
require'nvim-treesitter.configs'.setup {
  ensure_installed = "python", -- one of "all", "maintained" (parsers with maintainers), or a list of languages
  highlight = {
    enable = true,              -- false will disable the whole extension
    -- disable = { "c", "rust" },  -- list of language that will be disabled
  },
}
```

I am not sure what I am doing wrong here.

checkhealth

```
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## python parser healthcheck
  - OK: python parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for python
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
```

```

TSInfo also shows that Python is installed.

nvim --version
NVIM v0.5.0-9280a69
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20201024-19090-1jkmaal/build/config -I/tmp/neovim-20201024-19090-1jkmaal/src -I/usr/local/include -I/tmp/neovim-20201024-19090-1jkmaal/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20201024-19090-1jkmaal/build/src/nvim/auto -I/tmp/neovim-20201024-19090-1jkmaal/build/include
Compiled by 

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-9280a69/share/nvim"

Run :checkhealth for more info
```

**Comment by vigoux** [comment]
Can you run `TSnstall` just to be sure ?

**Comment by lanox** [comment]
Hi @vigoux thanks I have just tried that and this is what it says `python parser already available: would you like to reinstall ? y/n:`  obviously I said `y`  but I still get the same error message, as stated above.

**Comment by theHamsta** [comment]
Your Neovim build is from Oct 23

commit 2786d96fac2d5cb44eaf7de604adfdffe3dd9895
Merge: 9280a69a6 78ec28bca
Author: Jan Edmund Lazo <jan.lazo@mail.utoronto.ca>
Date:   Fri Oct 23 12:29:05 2020 -0400

You need at least:

```
Date:   Tue Nov 3 13:36:25 2020 +0100

    Merge pull request #12931 from vigoux/treesitter-bundled
    
    bundle: move tree-sitter as a bundled dep

commit 8e73cf67314095fe7240be5e57232ea3d20aac94
```

**Comment by vigoux** [comment]
I think that the command is `brew update --HEAD --fetch-HEAD` or something

**Comment by lanox** [comment]
> I think that the command is `brew update --HEAD --fetch-HEAD` or something


Thank you   this worked `brew upgrade --fetch-HEAD neovim`

Its little strange that you install neovim from `--HEAD` but then to update to latest you need to use `--fetch-HEAD` otherwise it will only look at the `HEAD` branch.

I guess what I am saying is that if you want to run nightly build you need to upgrade neovim with `--fetch-HEAD`

**Comment by vigoux** [comment]
Yeah that's kind of an awkward thing with Homebrew... If that's an issue for you, please open an issue there (at Homebrew) as it is more package manager-related than editor-related :wink:

**Comment by lanox** [comment]
@vigoux  oh yes definitely (Homebrew) sorry if that came across differently, was not my attention, I think I was trying to provide context if someone else comes across this issue.

**Comment by vigoux** [comment]
That is indeed a good idea, to help people when they search the issue list, thanks!
