### ISSUE TITLE
neovim crashes when editing an html file

### ISSUE THREAD

**Issue by shemishtamesh** [nvim-treesitter/nvim-treesitter#6533]
### Describe the bug

whenever I try to make some simple edits to an html file, neovim crashes. sometimes I can see a [message saying "free(): double free detected in tcache 2"](https://github.com/nvim-treesitter/nvim-treesitter/assets/62944862/7ca89a74-a520-419f-ae6f-0d0bce525be3) right before nvim closes, usually not.

### To Reproduce

1. install neovim
2. use [this](https://github.com/nvim-treesitter/nvim-treesitter/files/15142914/init.lua.txt) as `~/.config/nvim/init.lua` (remove the `.txt`)
3. open [this html file](https://github.com/nvim-treesitter/nvim-treesitter/files/15142937/test.html.txt) (and remove the `.txt`, or write it's content in a new buffer and type `:set ft=html<CR>`)
4. type `:TSInstall html<CR>`
5. type `:TSUpdate<CR>`
6. type `gg0j>>`

### Expected behavior

I would not expect neovim to crash, and I'd expect the edit I tried to make to happen.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.22.5 (cdd46888603e06d6474a96c0024907f68242c45f) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v18.18.2 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20240417
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.8.7-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000"
} ~

Parser/Features         H L F I J
  - html                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1713773202

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

I tried repeating the steps I described on a manjaro vm and couldn't reproduce the behavior. I assume there's something wrong in my system but I can't figure out what it is.

I've only had this happen with html. it does not happen 100% of the time, but in the vast majority of the time (on some edits) it does.

**Comment by clason** [comment]
Sounds like a tree-sitter-html issue; please report there (with exact commit of the html parser!)

Please also try the latest Neovim nightly.

**Comment by shemishtamesh** [comment]
After looking at https://github.com/tree-sitter/tree-sitter-html/issues/94 I realized I didn't make sure to update the nvim-treesitter plugin itself, and after updating it the problem was resolved for me. I probably should've done that before opening this issue so sorry for that.
