### ISSUE TITLE
zsh support (need a parser of its own)

### ISSUE THREAD

**Issue by ItsNilDev** [nvim-treesitter/nvim-treesitter#655]
**Language informations**

Add a zshrc language support, current syntax highlighting is good , but it's not beautiful , I'd rather keywords be red ....

**Comment by theHamsta** [comment]
Currently, zsh used bash syntax highlighting. There might be differences. Look at `queries/bash/highlights.scm`

**Comment by YaBoiBurner** [comment]
There's a lot of stuff that's broken thanks to some features of zsh syntax (especially with globs). Here's a few lines that caused a lot of errors for me:

```zsh
[[ $COLORTERM = *(24bit|truecolor)* ]] || zmodload zsh/nearcolor

[[ -n $ZDOTDIR/.zcompdump(#qN.mh+24) ]] && compinit || compinit -C

zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

() { : }

zstyle ':completion:*:git:*' user-commands ${${(M)${(k)commands}:#git-*}/git-/}

if [[ -e $ZDOTDIR/.zkbd/${TERM}-${${DISPLAY:t}:-$VENDOR-$OSTYPE} ]] {
  source $ZDOTDIR/.zkbd/$TERM-${${DISPLAY:t}:-$VENDOR-$OSTYPE}
}

if (( $+commands[zoxide] )) eval "$(zoxide init zsh)"

if (( $+commands[pigz] )) alias gzip=pigz gunzip="pigz -d" zcat="pigz -dc"

for element ( "$HOME/bin" "$HOME/.dotnet/tools" ) path[${path[(i)$element]}]=()
```

**Comment by theHamsta** [comment]
You could try to create a zsh parser, you can even import the grammar rules from bash or just fork the bash parser.

When you prefer to not use tree-sitter-bash on zsh you can either overwrite the "used_by" entry bash parser or deactivate tree-sitter for zsh file type.

**Comment by kyazdani42** [comment]
as @theHamsta said i believe someone should write a zsh parser, because the bash parser is crashing all over the place with zsh files.

**Comment by PouriDev** [comment]
Switched to Vim-Polyglot.

**Comment by adamwojt** [comment]
TS support for zsh is quite bad at the moment so better to turn it off.

in `~/.config/nvim/ftplugin/zsh.vim`:
```vim
if exists(':TSDisableAll')
    TSDisableAll highlight
endif
```

I am keeping good enough highlight with just `syntax on`

**Comment by gwerbin** [comment]
> TS support for zsh is quite bad at the moment so better to turn it off.
> 
> in `~/.config/nvim/ftplugin/zsh.vim`:
> 
> ```viml
> if exists(':TSDisableAll')
>     TSDisableAll highlight bash
> endif
> ```
> 
> I am getting good enough highlight with just `syntax on`

Does this disable Tree Sitter syntax highlighting for Bash syntax in _all_ files though? Is there a way to disable it just for Zsh files?

**Comment by theHamsta** [comment]
@gwerbin do you want to create PR?

btw you can edit the used by value or just create a separate entry for zsh
```
  require("nvim-treesitter.parsers").get_parser_configs().zsh = { install_info = {} }
```

```
  require("nvim-treesitter.parsers").get_parser_configs().bash.used_by = { "PKGBUILD" }
```

**Comment by theHamsta** [comment]
It should also be straight forward to modify the bash parser to have a separate zsh parser.

**Comment by adamwojt** [comment]
@gwerbin Fair point. With my workaround It would disable bash for session so if you open two files at the same time `zsh` and `bash` you would not have bash completion.

**Comment by gwerbin** [comment]
> @gwerbin do you want to create PR?
> 
> btw you can edit the used by value or just create a separate entry for zsh
> 
> ```
>   require("nvim-treesitter.parsers").get_parser_configs().zsh = { install_info = {} }
> ```
> 
> ```
>   require("nvim-treesitter.parsers").get_parser_configs().bash.used_by = { "PKGBUILD" }
> ```

Good tips on both of these. I also just submitted a PR that removes `zsh` from the default Bash list.

I can try to take a crack at extending the Bash parser for Zsh, but I am kind of intimidated by Tree Sitter grammars.

**Comment by gwerbin** [comment]
@adamwojt my PR was just merged, so you can remove your workaround now.

**Comment by adamwojt** [comment]
@gwerbin Awesome, thanks a lot. 

Also out of curiosity:
```
used_by = { "PKGBUILD" },
filetype = "sh",
```

Do i understand that `filetype="sh"` includes both `bash` and `sh` and in `used_by` has extra types, but now we removed `zsh`?

**Comment by theHamsta** [comment]
Yes, this is exactly what happened. The file type is `sh` while the symbol for the language in the tree-sitter parser is `bash`

**Comment by gwerbin** [comment]
In Vim/Neovim, the `sh` filetype has multiple "flavors": Bourne, POSIX Sh, Bash, and Ksh. So yes, `sh` includes Bash. I imagine this could cause problems for Ksh users, as Bash is mostly a superset of Bourne/POSIX but not Ksh. So we still would benefit from a way to selectively disable Tree Sitter entirely for certain filetypes, post-hoc.

The `used_by` setting still tells Tree Sitter to use the Bash grammar for `PKGBUILD` files. I find this a bit surprising, because PKGBUILD files are just shell scripts, and should probably be set to `filetype=sh`. So I don't really know what that setting is doing here.

**Comment by theHamsta** [comment]
Extensions can set their own file type. The user that submitted the  PKGBUILD patch had an extension creating a new file type.

The setup call already has a disable field to disable certain modules for certain file types. Just call `setup({ highlight= {disable={"zsh"}})`

**Comment by gwerbin** [comment]
> Extensions can set their own file type. The user that submitted the PKGBUILD patch had an extension creating a new file type.

> The setup call already has a disable field to disable certain modules for certain file types. Just call `setup({ highlight= {disable={"zsh"}})`

I was asking for a way to disable Tree Sitter entirely for a filetype, not just individual modules. Likewise, I was wondering about a way to enable it with the default settings.

The interface you described above (modifying `parser_configs`) seems like a good place to do this. Is that considered part of the API? Or is it "internal" and might break in future versions?

**Comment by theHamsta** [comment]
I really want to break the `used_by` API and replace it by the internal `ft -> lang` mapping, but sure you can manipulate decide right now which filetype has which parser and when the parser does not exist it is disabled.

**Comment by theHamsta** [comment]
Apparently, there are attempt to make the bash parser support more zsh features: https://github.com/tree-sitter/tree-sitter-bash/pull/115

**Comment by seblj** [comment]
Is there any way I can turn it back on? I tried to do something like this, but I couldn't get it to work
```lua
require("nvim-treesitter.parsers").get_parser_configs().bash.used_by = { "zsh" }
```

I never really had any issues with the bash parser, so I prefer that over the regular syntax

**Comment by clason** [comment]
Added to the tracking issue; but feel free to use this issue for further discussion!

**Comment by seblj** [comment]
I finally got something working for me. It's an ugly hack, but it works until #1317 and/or #2241 is fixed. If anyone has a better way I would love to hear it!


```lua
local ft_to_lang = require('nvim-treesitter.parsers').ft_to_lang
require('nvim-treesitter.parsers').ft_to_lang = function(ft)
    if ft == 'zsh' then
        return 'bash'
    end
    return ft_to_lang(ft)
end
```

**Comment by johnpitchko** [comment]
> I finally got something working for me. It's an ugly hack, but it works until #1317 and/or #2241 is fixed. If anyone has a better way I would love to hear it!
> 
> ```lua
> local ft_to_lang = require('nvim-treesitter.parsers').ft_to_lang
> require('nvim-treesitter.parsers').ft_to_lang = function(ft)
>     if ft == 'zsh' then
>         return 'bash'
>     end
>     return ft_to_lang(ft)
> end
> ```

I ran into this error `nvim-comment-frame/util.lua:96: [nvim-comment-frame]: Treesitter cannot figure out the language.` using [nvim-comment-frame](https://github.com/s1n7ax/nvim-comment-frame) when adding a comment frame on my `.zshrc` file.

Adding your code to my TreeSitter config file worked like a charm; thank you!

**Comment by FelipeLema** [comment]
it's now become simpler to use bash parser for zsh
```lua
require"nvim-treesitter.parsers".filetype_to_parsername.zsh = "bash"
```

**Comment by seblj** [comment]
> it's now become simpler to use bash parser for zsh
> 
> ```lua
> require"nvim-treesitter.parsers".filetype_to_parsername.zsh = "bash"
> ```

Even simpler on nightly ;)

```lua
vim.treesitter.language.register("bash", "zsh")
```

**Comment by amaanq** [comment]
I'll write a zsh parser...eventually

**Comment by seblj** [comment]
> > > it's now become simpler to use bash parser for zsh
> 
> > > ```lua
> 
> > > require"nvim-treesitter.parsers".filetype_to_parsername.zsh = "bash"
> 
> > > ```
> 
> > 
> 
> > Even simpler on nightly ;)
> 
> > 
> 
> > ```lua
> 
> > vim.treesitter.language.register("bash", "zsh")
> 
> > ```
> 
> 
> 
> @seblj @FelipeLema is this going to replace [vim.filetype.add()](https://neovim.io/doc/user/lua.html#vim.filetype.add()) / is it the new recommended way?

`vim.filetype.add` is for setting a filetype, but `vim.treesitter.language.register` is for registering a parser/lang to a specific filetype. However, it might be deprecated by this PR: https://github.com/neovim/neovim/pull/22643

**Comment by tjex** [comment]
ahhh yup, overlooked that. Thanks for clarifying and pointing out the potential upcoming change :)

**Comment by zhengpd** [comment]
`vim.treesitter.language.register("bash", "zsh")` causes error after upgrading to nvim 0.10.

```log
Error in decoration provider treesitter/highlighter.win:                                                                                                                            
Error executing lua: ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 15:2. Invalid node type "lookahead_assertion":                                 
(lookahead_assertion                                                                                                                                                                
 ^                                                                                                                                                                                  
                                                                                                                                                                                    
stack traceback:                                                                                                                                                                    
        [C]: in function '_ts_parse_query'                                                                                                                                          
        ...m/0.10.0/share/nvim/runtime/lua/vim/treesitter/query.lua:252: in function 'fn'                                                                                           
        ...ovim/0.10.0/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'fn'                                                                                            
        ...ovim/0.10.0/share/nvim/runtime/lua/vim/func/_memoize.lua:58: in function 'get_query'                                                                                     
        .../share/nvim/lazy/nvim-ts-rainbow2/lua/ts-rainbow/lib.lua:70: in function 'get_query'                                                                                     
        ...lazy/nvim-ts-rainbow2/lua/ts-rainbow/strategy/global.lua:101: in function 'fn'                                                                                           
        ...0/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:475: in function 'for_each_child'                                                                               
        ...lazy/nvim-ts-rainbow2/lua/ts-rainbow/strategy/global.lua:98: in function 'setup_parser'                                                                                  
        ...lazy/nvim-ts-rainbow2/lua/ts-rainbow/strategy/global.lua:124: in function 'cb'
```
