### ISSUE TITLE
Fenced Code Blocks on markdown files only highlighting with one color

### ISSUE THREAD

**Issue by bab014** [nvim-treesitter/nvim-treesitter#6553]
### Describe the highlighting problem

In markdown files when using a code block, I get a single color for the highlighting. I've done the above and have found no errors.

I have the python parser installed and when I inspect the tree I see that is recognizing python as the language in the code fence.

### Example snippet that causes the problem

![Screenshot 2024-05-02 132407](https://github.com/nvim-treesitter/nvim-treesitter/assets/61920876/e0560e49-5cfe-48a0-859d-7ad57d43a84a)

### Tree-sitter parsing result

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/61920876/0e0a82bf-e1b5-4529-be71-1fc99826110c)

### Example screenshot

:Inspect
Syntax
    - markdownCodeBlock
:colorscheme
onedark

### Expected behavior

I'd expect proper code highlighting of the fenced code type.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.11.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Debian 12.2.0-14) 12.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.1.0-20-cloud-amd64",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Debian 6.1.85-1 (2024-04-11)"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev-2404+geb1e8c12e
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634
Run "nvim -V1 -v" for more info
```

**Comment by clason** [comment]
Your :Inspect result shows that you are not using treesitter at all.

**Comment by bab014** [comment]
I have the markdown parser installed. What am I missing?

**Comment by bab014** [comment]
I found the source of the issue. In my treesitter config I had md files...disabled. Thanks for the help
