### ISSUE TITLE
stack corruption detected

### ISSUE THREAD

**Issue by King-Oni** [nvim-treesitter/nvim-treesitter#6556]
### Describe the bug

I have seen this bug reported multiple times before and one of which is related to JavaScript so I am guessing that this has to do with treesitter itself and not treesitter python but here is my issue.

I have been using treesitter since I have started using vim but this one problem didn't happen until now.
in `Python` when ever I insert `:` it causes neovim to print `stack corruption detected(-fstack-protector)` which never happened untill recently after I updated the plugin.

How did I come up with the conclusion that is's related to treesitter?
through trail and error
I disabled all the plugins even the plugin manager and tried adding a plugin to the working fine list until I reached `treesitter` on it's own without any other plugins working `treesitter` causes the same problem.
I tried running it with other plugs (cmp, lsp) to see if it's a compined problem but to no vain.
I ran the sam test on all the plugins I have but they are okay it only happens to `treesitter` other plugins are fine.

### To Reproduce

1. Install the `neovim-treesitter` plugin `build=":TSUpdate"` using your plugins manager
2. open a new file ending with `.py` then wirte it using `:w`
3. in insert mode type `:` on an empty line

### Expected behavior

The expected behavior was for neovim to write `:` to the file with no problems

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.22.5 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v21.6.2 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: clang version 18.1.4
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "armv8l",
  release = "3.18.137-g82f719e2f",
  sysname = "Linux",
  version = "#1 SMP PREEMPT Wed Dec 11 22:50:44 +03 2019"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/data/data/com.termux/files/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

I have seen this reported on:
[6453](https://github.com/nvim-treesitter/nvim-treesitter/issues/6453)

**Comment by lucario387** [comment]
That's not enough to reproduce anything. Please provide more concrete reproduce steps first.

**Comment by King-Oni** [comment]
I am not sure about how can I provide more reproduction steps
it seems strange disabling indent makes it work normally but I am not sure why
here is the exact configuration I am using:
```lua
require("nvim-treesitter.configs").setup({
    ensure_installed = { "vim", "vimdoc", "lua", "c", "python", "rust", "go" },
    auto_install = false,
    highlight = { enable = true },
    indent = { enable = true }, -- I disabled this to make it work properly
})
```

**Comment by clason** [comment]
Also a file and _exact reproducible steps_ to lead to a crash. A crash very likely implies an issue with the tree-sitter-python parser (scanner), and there's nothing we can do about those. Once you have a sequence of steps, you can report it there.

**Comment by amaanq** [comment]
https://github.com/tree-sitter/tree-sitter/issues/3296
