### ISSUE TITLE
can't install lua tree sitter

### ISSUE THREAD

**Issue by sahinf** [nvim-treesitter/nvim-treesitter#6579]
### Describe the bug

I am unable to install lua tree sitter through TSInstall

### To Reproduce

1. Run `:TSInstall lua `
2. Observe error
```sh
nvim-treesitter[lua]: Failed to execute the following command:
{
  cmd = "mv",
  opts = {
    args = { "-f", "tree-sitter-lua-tmp/tree-sitter-lua-master", "tree-sitter-lua" },
    cwd = "/home/furkan/.local/share/nvim",
    stdio = {
      [2] = <userdata 1>,
      [3] = <userdata 2>
    }
  }
}
mv: cannot stat 'tree-sitter-lua-tmp/tree-sitter-lua-master': No such file or directory
```

### Expected behavior

installed without errors

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v21.7.3 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 13.2.1 20240417
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.8.9-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Thu, 02 May 2024 17:49:46 +0000"
} ~

Parser/Features         H L F I J

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev-3053+g0b8a72b739
Build type: RelWithDebInfo
LuaJIT 2.1.1713773202
```

### Additional context

it installs other tree sitters without errors.

**Comment by clason** [comment]
We need complete and minimal reproduction steps. Obviously this works for other people, so the issue is specific to your setup.

**Comment by sahinf** [comment]
Can you be more specific regarding what information you need? For additional context, I don't use a package manager and have no other plugins installed. `:TSInstall c` works while `:TSInstall lua` results in that error.

**Comment by clason** [comment]
Something I can test with `nvim --clean -up test.lua`.

**Comment by sahinf** [comment]
Sorry, I'm still not sure what additional information you need from me. I'm using/testing a minimal setup with the only plugin being `nvim-treesitter`. I do not have themes, mappings, plugins. I can install a variety of treesitters successfully through `:TSInstall <parser>` except the parser for `lua`.

**Comment by clason** [comment]
Well, then please share that. I cannot fix something I cannot reproduce.
