### ISSUE TITLE
Error during download, please verify your internet connection

### ISSUE THREAD

**Issue by Miha0809** [nvim-treesitter/nvim-treesitter#6612]
### Describe the bug

This is a problem, I don't know whether it is a bug.

When write `TSUpdate` ->
nvim-treesitter[python]: Error during download, please verify your internet connection
Press ENTER or type command to continue
nvim-treesitter[vimdoc]: Error during download, please verify your internet connection
Press ENTER or type command to continue
nvim-treesitter[bash]: Error during download, please verify your internet connection
Press ENTER or type command to continue
nvim-treesitter[c]: Error during download, please verify your internet connection
Press ENTER or type command to continue
nvim-treesitter[markdown]: Error during download, please verify your internet connection
Press ENTER or type command to continue
nvim-treesitter[lua]: Error during download, please verify your internet connection
Press ENTER or type command to continue
nvim-treesitter[query]: Error during download, please verify your internet connection
Press ENTER or type command to continue
nvim-treesitter[vim]: Error during download, please verify your internet connection
Press ENTER or type command to continue

When write `nvim .config/nvim/init.lua`
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: /snap/nvim/2810/usr/share/nvim/runtime/filetype.lua:21: Error executing lua: /snap/nvim/2810/usr/share/nvim/runtime/filetype.lua:22: BufReadPost Autocommands fo
r "*"..FileType Autocommands for "*": Vim(append):Error executing lua callback: ...2810/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 3272 for
 language lua
stack traceback:
        [C]: in function '_ts_parse_query'
        ...2810/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: in function 'get'
        ...r/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:121: in function 'new'
        .../nvim/2810/usr/share/nvim/runtime/lua/vim/treesitter.lua:61: in function '_create_parser'
        .../nvim/2810/usr/share/nvim/runtime/lua/vim/treesitter.lua:131: in function 'get_parser'
        .../nvim/2810/usr/share/nvim/runtime/lua/vim/treesitter.lua:459: in function 'start'
        ...m/lazy/nvim-treesitter/lua/nvim-treesitter/highlight.lua:20: in function 'attach'
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:509: in function 'attach_module'
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:532: in function 'reattach_module'
        ...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:133: in function <...vim/lazy/nvim-treesitter/lua/nvim-treesitter/configs.lua:132>
        [C]: in function 'nvim_cmd'
        /snap/nvim/2810/usr/share/nvim/runtime/filetype.lua:22: in function </snap/nvim/2810/usr/share/nvim/runtime/filetype.lua:21>
        [C]: in function 'nvim_buf_call'
        /snap/nvim/2810/usr/share/nvim/runtime/filetype.lua:21: in function </snap/nvim/2810/usr/share/nvim/runtime/filetype.lua:10>
        [C]: in function 'nvim_exec_autocmds'
        .../AstroNvim/lua/astronvim/plugins/_astrocore_autocmds.lua:171: in function <.../AstroNvim/lua/astronvim/plugins/_astrocore_autocmds.lua:169>
stack traceback:
        [C]: in function 'nvim_cmd'
        /snap/nvim/2810/usr/share/nvim/runtime/filetype.lua:22: in function </snap/nvim/2810/usr/share/nvim/runtime/filetype.lua:21>
        [C]: in function 'nvim_buf_call'
        /snap/nvim/2810/usr/share/nvim/runtime/filetype.lua:21: in function </snap/nvim/2810/usr/share/nvim/runtime/filetype.lua:10>
        [C]: in function 'nvim_exec_autocmds'
        .../AstroNvim/lua/astronvim/plugins/_astrocore_autocmds.lua:171: in function <.../AstroNvim/lua/astronvim/plugins/_astrocore_autocmds.lua:169>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /snap/nvim/2810/usr/share/nvim/runtime/filetype.lua:21: in function </snap/nvim/2810/usr/share/nvim/runtime/filetype.lua:10>
        [C]: in function 'nvim_exec_autocmds'
        .../AstroNvim/lua/astronvim/plugins/_astrocore_autocmds.lua:171: in function <.../AstroNvim/lua/astronvim/plugins/_astrocore_autocmds.lua:169>
Press ENTER or type command to continue

### To Reproduce

1. nvim -> :TSUpdate [image](https://github.com/nvim-treesitter/nvim-treesitter/assets/40777154/3ba2cdc6-5005-4f69-8f3e-7521f616b7d1)
2. nvim .config/nvim/init.lua [image](https://github.com/nvim-treesitter/nvim-treesitter/assets/40777154/4f7fd29d-f5a3-49a2-955c-2d99e7d86106)

:TSUpdate
:TSInstall
:TSInstallSync

They didn't work.

### Expected behavior

Normally Install

### Output of `:checkhealth nvim-treesitter`

```markdown
The following errors have been detected: ~
- ERROR arduino(highlights): ...2810/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 214 for language arduino
  arduino(highlights) is concatenated from the following files:
  | [ERROR]:"/home/mark/.local/share/nvim/lazy/nvim-treesitter/queries/c/highlights.scm", failed to load: ...2810/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 214 for language arduino
  | [ERROR]:"/home/mark/.local/share/nvim/lazy/nvim-treesitter/queries/cpp/highlights.scm", failed to load: ...2810/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 4032 for language arduino
  |    [OK]:"/home/mark/.local/share/nvim/lazy/nvim-treesitter/queries/arduino/highlights.scm"
- ERROR arduino(folds): ...2810/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 306 for language arduino
  arduino(folds) is concatenated from the following files:
  | [ERROR]:"/home/mark/.local/share/nvim/lazy/nvim-treesitter/queries/c/folds.scm", failed to load: ...2810/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 306 for language arduino
  |    [OK]:"/home/mark/.local/share/nvim/lazy/nvim-treesitter/queries/cpp/folds.scm"
  |    [OK]:"/home/mark/.local/share/nvim/lazy/nvim-treesitter/queries/arduino/folds.scm"
- ERROR arduino(indents): ...2810/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 1103 for language arduino
  arduino(indents) is concatenated from the following files:
  | [ERROR]:"/home/mark/.local/share/nvim/lazy/nvim-treesitter/queries/c/indents.scm", failed to load: ...2810/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 1103 for language arduino
  |    [OK]:"/home/mark/.local/share/nvim/lazy/nvim-treesitter/queries/cpp/indents.scm"
  |    [OK]:"/home/mark/.local/share/nvim/lazy/nvim-treesitter/queries/arduino/indents.scm"
- ERROR astro(highlights): ...2810/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 1775 for language astro
  astro(highlights) is concatenated from the following files:
  |    [OK]:"/home/mark/.local/share/nvim/lazy/nvim-treesitter/queries/html_tags/highlights.scm"
  | [ERROR]:"/home/mark/.local/share/nvim/lazy/nvim-treesitter/queries/html/highlights.scm", failed to load: ...2810/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 66 for language astro
  |    [OK]:"/home/mark/.local/share/nvim/lazy/nvim-treesitter/queries/astro/highlights.scm"
- ERROR astro(injections): ...2810/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 2659 for language astro
  astro(injections) is concatenated from the following files:
  |    [OK]:"/home/mark/.local/share/nvim/lazy/nvim-treesitter/queries/html_tags/injections.scm"
  | [ERROR]:"/home/mark/.local/share/nvim/lazy/nvim-treesitter/queries/astro/injections.scm", failed to load: ...2810/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 39 for language astro
- ERROR bash(highlights): ...2810/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 280 for language bash
  bash(highlights) is concatenated from the following files:
  | [ERROR]:"/home/mark/.local/share/nvim/lazy/nvim-treesitter/queries/bash/highlights.scm", failed to load: ...2810/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 280 for language bash
- ERROR bash(injections): ...2810/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 196 for language bash
  bash(injections) is concatenated from the following files:
  | [ERROR]:"/home/mark/.local/share/nvim/lazy/nvim-treesitter/queries/bash/injections.scm", failed to load: ...2810/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 196 for language bash
```

### Output of `nvim --version`

```text
NVIM v0.10.0-dev-530+g8376e8700
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/build/nvim/parts/nvim/build/.deps/usr/include/luajit-2.1 -I/usr/include -I/build/nvim/parts/nvim/build/.deps/usr/include -I/build/nvim/parts/nvim/build/build/src/nvim/auto -I/build/nvim/parts/nvim/build/build/include -I/build/nvim/parts/nvim/build/build/cmake.config -I/build/nvim/parts/nvim/build/src

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Additional context

Thanks for your reply.

**Comment by clason** [comment]
Duplicate. Please search through open and closed issues; we cannot troubleshoot your configuration for you.
