### ISSUE TITLE
Changing the highlightings

### ISSUE THREAD

**Issue by PouriDev** [nvim-treesitter/nvim-treesitter#662]
Hi, Is there any way that I can change the highlightings? I wish I could change the highlighings specially for functions, or keywords, because it's a little bit annoying , they are both yellow/green like color....
( Also I'm talking about C++ ) both keywords like `int` and `functions` are yellow or green

**Comment by weilbith** [comment]
Does the `custom_captures` option in the highlight configuration table not help for this issue? :thinking: 
[See here](https://github.com/nvim-treesitter/nvim-treesitter#highlight)

**Comment by PouriDev** [comment]
Another thing that annoys me is capital letter, when I start typing something that starts with a capital letter, it will be blue: 
![myfile](https://user-images.githubusercontent.com/61497342/99516226-2c9fa480-29a3-11eb-9a38-305451c1b11e.gif)
I'm using gruvbox at the moment and I changed the default colors a little bit.
I uninstalled treesitter and I no longer had this issue, so it's treesitter's fault.
Any idea?

**Comment by PouriDev** [comment]
1, where is its query , couldn't find it
2.how can I repeat C function highlighting rule in C++ ??

**Comment by PouriDev** [comment]
I've another issue with highlightings too, When I type `// TODO` it won't be white like in the past, what can I do for this?

**Comment by theHamsta** [comment]
Maybe have a lot into: https://github.com/nvim-treesitter/nvim-treesitter/pull/453 (unmerged for eternity). It would add a `has-parent?` query. This would allow you to add a `not-has-parent?` clause to the type highlights to  not highlight as type if in a function context.

**Comment by PouriDev** [comment]
Are you planning to merge it?
also I changed the first line and it works:
`((identifier) @type (#match? @type "^[A]"))`
But If I use `A` It will be blue.But What does treesitter do when there is a type??

**Comment by PouriDev** [comment]
Also this problem is not just C++, it is here for everylanguage :(

**Comment by theHamsta** [comment]
try

```
:lua print(vim.inspect(vim.treesitter.highlighter.hl_map))
```
it will map `@type` to the `TSType` highlight. Change that dictionary or link that highlight group to something else to change the highlight.

**Comment by PouriDev** [comment]
Ok, I found another issue, If I use underscore `_` it will be green!!?

**Comment by theHamsta** [comment]
No the projects follows naming conventions when it can't infer the type of a symbol. Types in pascalcase. Constants all uppercase. It will highlight m_foo and _foo with the highlighing for fields.

**Comment by theHamsta** [comment]
@PouriDev btw, you can use your on query files if you like. nvim-treesitter uses `queries/c` and `queries/cpp` in your runtime path. You can just create your own `queries/c` and `queries/cpp` e.g. in your standard init.vim folder to overwrite our files.

**Comment by kyazdani42** [comment]
if you are not happy with the way queries are written, you could still override the queries yourself (it's loaded from the runtimepath). Also you could declare your own groups, and assign the colors you want. Nvim-treesitter tries to provide enough abstraction so you don't need to write every queries yourself, and it follows conventions that many people agreed on.
Also there is a lot of documentation about that that you could've read that people spend much time on that explains how everything works.

**Comment by PouriDev** [comment]
Thanks for merging that branch, also I found it a little bit hard to re-write queries.

**Comment by vigoux** [comment]
You can also add queries in you `after/queries/{mylang}/` directory, that will be used to overwrite things.
Writing queries is not as hard as making right vim syntax files (which is really really hard), some hints can be found [here](https://tree-sitter.github.io/tree-sitter/using-parsers#query-syntax).
