### ISSUE TITLE
New `compat.flatten` replacement in-compatible

### ISSUE THREAD

**Issue by barrydevp** [nvim-treesitter/nvim-treesitter#6651]
### Describe the bug

The replacement of old `vim.tbl_flatten` with `vim.iter(..):flatten` raises an un expected in-compatible behavior for non-list arguments such as `nil` value.

### To Reproduce

```lua

vim.inspect(require("nvim-treesitter.compat").flatten {nil, 1, 2, 3})

```

### Expected behavior

This should be compatible with old flattened usage. We would revert back to `vim.tbl_flatten` as this deprecated function has been extended to version `0.13` https://github.com/neovim/neovim/commit/50749f8df89d7a74ea17d51b28e737e043ac6c51

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.22.6 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v21.7.2 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 13.0.0 (clang-1300.0.29.3)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "21.6.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 21.6.0: Mon Feb 19 20:24:34 PST 2024; root:xnu-8020.240.18.707.4~1/RELEASE_X86_64"
} ~
```

### Output of `nvim --version`

```text
NVIM v0.11.0-dev-10+gaec4938a2-Homebrew
Build type: Release
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info
```

**Comment by clason** [comment]
Yes, that is a know issue (the function was deprecated without a proper replacement). This will be fixed before the 0.11 release, of course. For now, this is the best we can do here.

I would recommend sticking with the 0.10 release for the near future.

**Comment by barrydevp** [comment]
@clason Actually, 0.10 released version has the same issue https://github.com/nvim-treesitter/nvim-treesitter-textobjects/issues/617

**Comment by clason** [comment]
Ok, I'll adjust the compat guard. Thanks!

**Comment by clason** [comment]
Please update and try again.

**Comment by vandalt** [comment]
Your last commit fixes it for me. Thanks!

**Comment by barrydevp** [comment]
For anyone who uses the nightly version needs to wait for the upstream update and pre-process the arguments before passing them to `compat.flatten`.

**Comment by barrydevp** [comment]
@clason just wonder if we could make a workaround for the unstable version.

https://github.com/nvim-treesitter/nvim-treesitter/blob/00a8cfd562dc805eb4d732fbca35e23640dbf7c8/lua/nvim-treesitter/utils.lua#L81C1-L95C4

```diff
diff --git a/lua/nvim-treesitter/compat.lua b/lua/nvim-treesitter/compat.lua
index d4526c50..0ad01003 100644
--- a/lua/nvim-treesitter/compat.lua
+++ b/lua/nvim-treesitter/compat.lua
@@ -29,7 +29,7 @@ function M.require_language(lang, opts)
 end

 function M.flatten(t)
-  if vim.fn.has "nvim-0.10" == 1 then
+  if vim.fn.has "nvim-0.11" == 1 then
     return vim.iter(t):flatten():totable()
   else
     return vim.tbl_flatten(t)
```

**Comment by clason** [comment]
Sorry, I'll not add short-term workarounds for upstream bugs that will get fixed. (`master` branch is in principle frozen, and these fixes were an exception.)
