### ISSUE TITLE
zig not working for treesitter build after update to neovim nightly and lazyvim rewrite

### ISSUE THREAD

**Issue by WillEhrendreich** [nvim-treesitter/nvim-treesitter#6652]
### Describe the bug

1:06:56 PM msg_show.echomsg [nvim-treesitter/install/html] error: Error during "tree-sitter build": thread 'main' panicked at cli\src/main.rs:520:22:
called `Result::unwrap()` on an `Err` value: Parser compilation failed.
Stdout: 
Stderr: info: Usage: zig [command] [options]

Commands:

  build            Build project from build.zig
  fetch            Copy a package into global cache and print its hash
  init             Initialize a Zig package in the current directory

  build-exe        Create executable from source or object files
  build-lib        Create library from source or object files
  build-obj        Create object from source or object files
  test             Perform unit testing
  run              Create executable and run immediately

  ast-check        Look for simple compile errors in any set of files
  fmt              Reformat Zig source into canonical form
  reduce           Minimize a bug report
  translate-c      Convert C code to Zig code

  ar               Use Zig as a drop-in archiver
  cc               Use Zig as a drop-in C compiler
  c++              Use Zig as a drop-in C++ compiler
  dlltool          Use Zig as a drop-in dlltool.exe
  lib              Use Zig as a drop-in lib.exe
  ranlib           Use Zig as a drop-in ranlib
  objcopy          Use Zig as a drop-in objcopy
  rc               Use Zig as a drop-in rc.exe

  env              Print lib path, std path, cache directory, and version
  help             Print this help and exit
  std              View standard library documentation in a browser
  libc             Display native libc paths file or validate one
  targets          List available compilation targets
  version          Print version number and exit
  zen              Print Zen of Zig and exit

General Options:

  -h, --help       Print command-specific usage

**error: unknown command: -O2**

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### To Reproduce

have tree-sitter, lazyvim extra nvim-treesitter-rewrite, set CC environment variable to "zig", open neovim. 

### Expected behavior

i expect it to work like it did before, where it would use the compiler to compile. 

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Requirements ~
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13).
- OK tree-sitter 0.22.6 (c:\.local\share\nvim-data\mason\bin\tree-sitter.CMD)
- OK git 2.45.0 (C:\Program Files\Git\cmd\git.EXE)

OS Info ~
- machine: x86_64
- version: Windows 11 Enterprise
- sysname: Windows_NT
- release: 10.0.22631

Install directory for parsers and queries ~
- c:\.local\share\nvim-data/site/
- OK is writable.
- ERROR is not in runtimepath.

Installed languages     H L F I J ~
- ecma
- html_tags
- jsx

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[J]ections ~
```

### Output of `nvim --version`

```text
NVIM v0.11.0-dev-6+g06135cc21
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

### Additional context

I'm on windows. 

this isn't the only language that fails to compile now, half of them won't install

**Comment by clason** [comment]
I'm sorry, that's not nearly enough to go on. Please provide a minimal config and _exact_ steps we can use to reproduce this.

**Comment by WillEhrendreich** [comment]
tree sitter build assumes something about how zig works, or whatever. it's giving it an arg of -02, which it doesn't understand

zig needs to be called like "zig cc [.. etc]"

**Comment by clason** [comment]
Please give more details to see if this is a bug to be fixed or a configuration (or expectation) error on your part.

**Comment by clason** [comment]
Wait, is this using the `main` branch? Why is LazyVim using that?

**Comment by clason** [comment]
To be clear:

> i expect it to work like it did before, where it would use the compiler to compile.

is flat-out wrong. There are massive breaking changes on that branch, and there has been no testing on Windows. LazyVim should never have added that, and I've asked folke to remove it.

**Comment by ObserverOfTime** [comment]
Set CC to a normal C compiler.

**Comment by ObserverOfTime** [comment]
Actually, I think this is happening because tree-sitter does not accept multiple arguments in `CC`. You can add a `zig-cc` script to your `PATH` that calls `zig cc` with any arguments passed to it and use that instead.

**Comment by WillEhrendreich** [comment]
> Actually, I think this is happening because tree-sitter does not accept multiple arguments in `CC`. You can add a `zig-cc` script to your `PATH` that calls `zig cc` with any arguments passed to it and use that instead.

This is the simplest and best option. lol. I mean, for me, I did it as part of my powershell profile, just a function like this: 

```pwsh
function zig
{
  zig cc $args
}

```
then in my env vars I have zig as $Env:CC
