### ISSUE TITLE
Class members are highligted no more

### ISSUE THREAD

**Issue by GGCristo** [nvim-treesitter/nvim-treesitter#668]
Since the last commits, member and attributes are no longer highlighted in c++.
Sorry for not using the template but I think in this case I can be straight forward, if you still want I can fill it.
If I do TSHIglightUnderCursor it return "No tree-sitter matches found!"

**Comment by theHamsta** [comment]
Sorry, probably something went wrong when merging this old PR. I'll try to fix it tomorrow

**Comment by GGCristo** [comment]
#672
