### ISSUE TITLE
E5105: Error while calling lua chunk

### ISSUE THREAD

**Issue by muxik** [nvim-treesitter/nvim-treesitter#669]
**Describe the bug**
在我使用`Plug 'nvim-treesitter/nvim-treesitter'`安装完之后出现了以下错误:
Error detected while processing /home/muxik/.config/nvim/plugged/nvim-treesitter/plugin/nvim-treesitter.
vim:
line   12:
E5105: Error while calling lua chunk: ...fig/nvim/plugged/nvim-treesitter/lua/nvim-treesitter.lua:3: nvi
m-treesitter requires a more recent Neovim nightly version!

**To Reproduce**
1. Go to 'vim'

**Expected behavior**
请修复

**Output of `:checkhealth nvim_treesitter`**

<details>
health#nvim_treesitter#check
========================================================================
  - ERROR: Failed to run healthcheck for "nvim_treesitter" plugin. Exception:
    function health#check[21]..health#nvim_treesitter#check, line 1
    Vim(lua):E5105: Error while calling lua chunk: ...im/plugged/nvim-treesitter/lua/nvim-treesitter/query.lua:2: module 'vim.treesitter.query' not found:
    no field package.preload['vim.treesitter.query']
    no file '/home/muxik/.config/nvim/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/gruvbox/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/gruvbox/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/lightline.vim/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/lightline.vim/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/defx.nvim/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/defx.nvim/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/defx-icons/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/defx-icons/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/defx-git/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/defx-git/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/coc.nvim/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/coc.nvim/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/fzf/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/fzf/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/fzf.vim/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/fzf.vim/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/vim-startify/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/vim-startify/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/auto-pairs/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/auto-pairs/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/vim-autoformat/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/vim-autoformat/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/vim-devicons/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/vim-devicons/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/indentLine/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/indentLine/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/vim-surround/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/vim-surround/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/vim-commentary/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/vim-commentary/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/tabular/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/tabular/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/wildfire.vim/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/wildfire.vim/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/vim-visual-multi/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/vim-visual-multi/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/ultisnips/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/ultisnips/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/vim-snippets/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/vim-snippets/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/markdown-preview.nvim/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/markdown-preview.nvim/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/nvim-treesitter/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/nvim-treesitter/lua/vim/treesitter/query/init.lua'
    no file '/etc/xdg/nvim/lua/vim/treesitter/query.lua'
    no file '/etc/xdg/nvim/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.local/share/nvim/site/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.local/share/nvim/site/lua/vim/treesitter/query/init.lua'
    no file '/usr/local/share/nvim/site/lua/vim/treesitter/query.lua'
    no file '/usr/local/share/nvim/site/lua/vim/treesitter/query/init.lua'
    no file '/usr/share/nvim/site/lua/vim/treesitter/query.lua'
    no file '/usr/share/nvim/site/lua/vim/treesitter/query/init.lua'
    no file '/usr/share/nvim/runtime/lua/vim/treesitter/query.lua'
    no file '/usr/share/nvim/runtime/lua/vim/treesitter/query/init.lua'
    no file '/usr/share/nvim/runtime/pack/dist/opt/matchit/lua/vim/treesitter/query.lua'
    no file '/usr/share/nvim/runtime/pack/dist/opt/matchit/lua/vim/treesitter/query/init.lua'
    no file '/usr/share/nvim/site/after/lua/vim/treesitter/query.lua'
    no file '/usr/share/nvim/site/after/lua/vim/treesitter/query/init.lua'
    no file '/usr/local/share/nvim/site/after/lua/vim/treesitter/query.lua'
    no file '/usr/local/share/nvim/site/after/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.local/share/nvim/site/after/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.local/share/nvim/site/after/lua/vim/treesitter/query/init.lua'
    no file '/etc/xdg/nvim/after/lua/vim/treesitter/query.lua'
    no file '/etc/xdg/nvim/after/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/after/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/after/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/indentLine/after/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/indentLine/after/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/tabular/after/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/tabular/after/lua/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/plugged/ultisnips/after/lua/vim/treesitter/query.lua'
    no file '/home/muxik/.config/nvim/plugged/ultisnips/after/lua/vim/treesitter/query/init.lua'
    no file '/usr/share/vim/vimfiles/lua/vim/treesitter/query.lua'
    no file '/usr/share/vim/vimfiles/lua/vim/treesitter/query/init.lua'
    no file './vim/treesitter/query.lua'
    no file '/usr/share/luajit-2.0.5/vim/treesitter/query.lua'
    no file '/usr/local/share/lua/5.1/vim/treesitter/query.lua'
    no file '/usr/local/share/lua/5.1/vim/treesitter/query/init.lua'
    no file '/usr/share/lua/5.1/vim/treesitter/query.lua'
    no file '/usr/share/lua/5.1/vim/treesitter/query/init.lua'
    no file '/home/muxik/.config/nvim/lua/vim/treesitter/query.so'
    no file '/home/muxik/.config/nvim/plugged/gruvbox/lua/vim/treesitter/query.so'
    no file '/home/muxik/.config/nvim/plugged/lightline.vim/lua/vim/treesitter/query.so'
    no file '/home/muxik/.config/nvim/plugged/defx.nvim/lua/vim/treesitter/query.so'
    no file '/home/muxik/.config/nvim/plugged/defx-icons/lua/vim/treesitter/query.so'
    no file '/home/muxik/.config/nvim/plugged/defx-git/lua/vim/treesitter/query.so'
    no file '/home/muxik/.config/nvim/plugged/coc.nvim/lua/vim/treesitter/query.so'
    no file '/home/muxik/.config/nvim/plugged/fzf/lua/vim/treesitter/query.so'
    no file '/home/muxik/.config/nvim/plugged/fzf.vim/lua/vim/treesitter/query.so'
    no file '/home/muxik/.config/nvim/plugged/vim-startify/lua/vim/treesitter/query.so'
    no file '/home/muxik/.config/nvim/plugged/auto-pairs/lua/vim/treesitter/query.so'
    no file '/home/muxik/.config/nvim/plugged/vim-autoformat/lua/vim/treesitter/query.so'
    no file '/home/muxik/.config/nvim/plugged/vim-devicons/lua/vim/treesitter/query.so'
    no file '/home/muxik/.config/nvim/plugged/indentLine/lua/vim/treesitter/query.so'
    no file '/home/muxik/.config/nvim/plugged/vim-surround/lua/vim/treesitter/query.so'
    no file '/home/muxik/.config/nvim/plugged/vim-commentary/lua/vim/treesitter/query.so'
    no file '/home/muxik/.config/nvim/plugged/tabular/lua/vim/treesitter/query.so'
    no file '/home/muxik/.config/nvim/

<code>

Paste the output here

</code>
Error detected while processing /home/muxik/.config/nvim/plugged/nvim-treesitter/plugin/nvim-treesitter.
vim:
line   12:
E5105: Error while calling lua chunk: ...fig/nvim/plugged/nvim-treesitter/lua/nvim-treesitter.lua:3: nvi
m-treesitter requires a more recent Neovim nightly version!
Press ENTER or type command to continue

</details>

**Output of `nvim --version`**
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```

**Additional context**
None

**Comment by skt041959** [comment]
出错信息里已经说了，你需要最新的nightly build.
It's reported that
> E5105: Error while calling lua chunk: ...fig/nvim/plugged/nvim-treesitter/lua/nvim-treesitter.lua:3: nvi
m-treesitter requires a more recent Neovim nightly version!

**Comment by muxik** [comment]
已经编译好了最新的nvim，保存信息已经消失了，谢谢

**Comment by skt041959** [comment]
@muxik 那你最好关掉这个 issue
Then you'd better close this issue.

Thanks

**Comment by muxik** [comment]
Ok

**Comment by heresy0-0y** [comment]
i'm still getting this exact same issue, on 0.4.4

**Comment by kyazdani42** [comment]
the plugin specifies in the first lines of the readme that you need neovim *nightly* so 0.5.x at least.
