### ISSUE TITLE
Question: How to use correctly installed parser

### ISSUE THREAD

**Issue by li-maisiliym-xyz** [nvim-treesitter/nvim-treesitter#670]
Glancing at the code, it is difficult to see how this plugin can use parsers which have been correctly installed (ie. not installed by some curl job which does absolutely no source-integrity check)

Background, for the curious, or to answer questions which would probably come otherwise: Li's system strives for correctness and therefore does not permit random processes to `curl X && ./make` or whatever. TSInstall is *bad*. Li has already re-implemented nvim-lspconfig, since the developpers were quite opposed to split out the 'unsafe unix build system' from their plugin. Is anyone intersted in, perhaps, splitting out the unsafe code from this otherwise interesting plugin, in order to make it correct-system-friendly?

**Comment by theHamsta** [comment]
No, we will not do that. None of the installations is run without action of the user. Our plugin is basically lspconfig for tree-sitter. It is very easy to run install the parsers by yourself or use tree-sitter without this plugin.
Everything is off by default and you will only have the queries with the default config without any installation code running.

Installing the parser is also very easy it's just running the compiler on scanner.c and parser.c. our plugin accepts parsers that have been installed in alternative ways. They just have to be in nvim's standard runtime path `parser`

Regarding reproducibly, we use no build system and download the tarbals of a specific commit. The parser is just one compiler invocation on two or one source files.

**Comment by vigoux** [comment]
Hi, thanks for reporting this issue.

I think this is _fairly_ easy to implement, be storing the hashes of the archives in the `lockfile.json`
BUT, we are actually using `https` to download the archives, giving us some extra bits of security when downloading them.
But as security is a field of paranoid people, one can specify the sha's in the lockfile.

**Comment by theHamsta** [comment]
The lockfile does not contain the hashes of the of the tarbals but the SHA of the git commit. You could add an additional checksum. But I would recommend you to build the parser yourself and also generate the source files (like TSInstallFromGrammar). In theory, the parser creators could hide arbitrary code in their auto-generated parsers.

**Comment by vigoux** [comment]
That's what I suggested : add a checksum in the lockfile, that's the more secure way of doing so IMO. But indeed, the most secure is through `TSInstallFromGrammar` which will use `git`, rebuild the grammar, and compile it.

**Comment by theHamsta** [comment]
You can prevent this plugin from running any system commands by requiring "nvim-treesitter/shell.lua" and setting the module's functions to nil.

**Comment by bfredl** [comment]
> Li has already re-implemented nvim-lspconfig, since the developpers were quite opposed to split out the 'unsafe unix build system' from their plugin

For the uninitiated: be assured nvim-lspconfig already and alwsays has split out the 'unsafe unix build system'. It only installs stuff if you explicitly ask it to, but you can use existing binaries from `$PATH`. At some point we aim to split these parts out to per-language repos and merge the config infrastructure itself to neovim/neovm.

**Comment by li-maisiliym-xyz** [comment]
All right, Li will just learn all about nvim treesitter now and redo this correctly. Closing.

Side-note: only gentoo has a decent source-verification system, and it's still very sub-optimal. For those who dont know, they use a gpg-signed repo that keeps all the source hashes. Using a hash that was obtained by simply trusting a random SSL certificate or pulling a git repo does not guarantee much. Also, when Li tried to install nvim-lspconfig, it tried to modify the system upon simply loading it, and would fail since it was in a read-only sandbox, so it was unsusable on a secure system at the time. He hasent tried it since, especially since he has since reproduced most of the functionality with a twentieth of the code.

**Comment by li-maisiliym-xyz** [comment]
> You can prevent this plugin from running any system commands by requiring "nvim-treesitter/shell.lua" and setting the module's functions to nil. Or just delete "install.lua"

Well, Li already maintains too many forks to count, and deleting `install.lua` wouldnt work by itself, since the plugin loads it. What if Li splits out the functionality himself, and presents it as two repos? It could use a bool to `require('tspacman')` if people want to use the build system? In any case, he *will* reuse the `.scm` files. This  is a perfect exemple of duplication of effort. Who wins? Nobody. There must be a reasonable compromise. He's going to do this anyhow, and nvim-treesitter does a quite a bit more than install/load parsers. Modular code == reusable code. The unsafety of TSInstall doesnt really matter; the plugin would gain much utility by exposing an API which is useful to different developpers.

**Comment by li-maisiliym-xyz** [comment]
Actually, nevermind. Li is not going to spend more time on this. Forked it. Done.

**Comment by maisiliym** [comment]
> It's not the business of an editor plugin to re-invent a package manager. 

Source: https://github.com/mfussenegger/nvim-dap/blob/ef830470c8b39a5bc4bc798315d2bff9dbdf3fe7/README.md#non-goals
