### ISSUE TITLE
Links and images are underlined with dashes in markdown

### ISSUE THREAD

**Issue by uloco** [nvim-treesitter/nvim-treesitter#6731]
### Describe the highlighting problem

I am a theme creator and I want to change how markdown link text (label) is displayed. The link label between brackets is underlined with dashes. How can I change / disable this? I changed all hightlight groups that are applied and visible via :TSHighlightCapturesUnderCursor, but the dashes stay. This also only is applied when Treesitter is enabled for markdown. When I disable Treesitter and change the highlight of of `markdownLinkText` I can theme it easily.

### Example snippet that causes the problem

`[uloco](https://github.com/uloco/)`

### Tree-sitter parsing result

```
(document ; [0, 0] - [1, 0] markdown
  (section ; [0, 0] - [1, 0] markdown
    (paragraph ; [0, 0] - [1, 0] markdown
      (inline ; [0, 0] - [0, 34] markdown
        (inline ; [0, 0] - [0, 34] markdown_inline
          (inline_link ; [0, 0] - [0, 34] markdown_inline
            "[" ; [0, 0] - [0, 1] markdown_inline
            (link_text) ; [0, 1] - [0, 6] markdown_inline
            "]" ; [0, 6] - [0, 7] markdown_inline
            "(" ; [0, 7] - [0, 8] markdown_inline
            (link_destination ; [0, 8] - [0, 33] markdown_inline
              ":" ; [0, 13] - [0, 14] markdown_inline
              "/" ; [0, 14] - [0, 15] markdown_inline
              "/" ; [0, 15] - [0, 16] markdown_inline
              "." ; [0, 22] - [0, 23] markdown_inline
              "/" ; [0, 26] - [0, 27] markdown_inline
              "/") ; [0, 32] - [0, 33] markdown_inline
            ")")) ; [0, 33] - [0, 34] markdown_inline
        "[" ; [0, 0] - [0, 1] markdown
        "]" ; [0, 6] - [0, 7] markdown
        "(" ; [0, 7] - [0, 8] markdown
        ":" ; [0, 13] - [0, 14] markdown
        "/" ; [0, 14] - [0, 15] markdown
        "/" ; [0, 15] - [0, 16] markdown
        "." ; [0, 22] - [0, 23] markdown
        "/" ; [0, 26] - [0, 27] markdown
        "/" ; [0, 32] - [0, 33] markdown
        ")")))) ; [0, 33] - [0, 34] markdown

```

### Example screenshot

<img width="286" alt="Screenshot 2024-06-05 at 17 48 43" src="https://github.com/nvim-treesitter/nvim-treesitter/assets/8818340/f7921a35-bfee-403c-bbea-44e32ce0d847">

### Expected behavior

I am a theme creator and want to be able to change the highlight of the link labels, so they are no longer underdashed.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.22.6 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.10.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 15.0.0 (clang-1500.3.9.4)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.5.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.5.0: Wed May  1 20:16:51 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T8103"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - dart                ✓ ✓ ✓ ✓ ✓
  - dockerfile          ✓ . . . ✓
  - elixir              ✓ ✓ ✓ ✓ ✓
  - erlang              ✓ . ✓ . .
  - gitattributes       ✓ ✓ . . ✓
  - gitignore           ✓ . . . .
  - go                  ✓ ✓ ✓ ✓ ✓
  - graphql             ✓ . . ✓ ✓
  - groovy              ✓ ✓ ✓ ✓ ✓
  - haskell             ✓ ✓ ✓ . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - ini                 ✓ . ✓ . .
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - kotlin              ✓ ✓ ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - objc                ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - r                   ✓ ✓ . ✓ ✓
  - regex               ✓ . . . .
  - ruby                ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - scala               ✓ ✓ ✓ . ✓
  - scss                ✓ . ✓ ✓ .
  - sql                 ✓ . . ✓ ✓
  - svelte              ✓ ✓ ✓ ✓ ✓
  - swift               ✓ ✓ . ✓ .
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478
Run "nvim -V1 -v" for more info
```

**Comment by clason** [comment]
You're seeing two highlights, I suspect: 1. link (underline) and 2. spellchecker (undercurl).

`:Inspect` will tell you exactly which highlight groups are applied in which order. (Note that gui attributes combine unless you specifically have `nocombine` in your highlight group.)

**Comment by uloco** [comment]
@clason resetting both highlight groups does not solve the issue. spellchecking isn't enabled, too. did you actually check if this is a bug? `@spell @markup.link.label and @_label` are shown when I run :TSHighlightCapturesUnderCursor, but when I override those, nothing happens.

**Comment by uloco** [comment]
<img width="680" alt="image" src="https://github.com/nvim-treesitter/nvim-treesitter/assets/8818340/98ab85fd-5d75-4781-a0a9-35f93805f354">

**Comment by clason** [comment]
Nothing in the screenshot shows any underlining or undercurling. Are you sure it's not your terminal being extra helpful?

**Comment by uloco** [comment]
yes i am sure as it disappears when I disable treesitter for that file and use the default highlighting of neovim.

**Comment by clason** [comment]
And is spelling enabled?

**Comment by uloco** [comment]
:set spell?
nospell

**Comment by clason** [comment]
Then given the (lack of) information, I can't help you. In any case, there is no issue with this plugin as the correct captures look to be applied (which is all this plugin does).

**Comment by uloco** [comment]
ok... so do I need to file this bug at the markdown treesitter repo?

**Comment by uloco** [comment]
I could also create a reproduction. maybe then it's easier...

**Comment by clason** [comment]
No. If you can create a minimal(!) reproducing example to test with `nvim --clean -u minimal.lua`, you can open an issue at neovim (but search previous -- open and closed! -- issues first).

Note that the markdown parsers are now bundled with Neovim, so your repro will not require (and should not include) any plugins, including this one.

**Comment by uloco** [comment]
Okay thank you. Could you pinpoint me to a reference how to configure this so that treesitter is applied on markdown on files?

**Comment by uloco** [comment]
Sorry for bothering, but how would you install the markdown parser without this plugin? in the help file it says that it should be included already, but when I run `vim.treesitter.start()` in a .md file I get an error that says "no parser for 'markdown' language"

**Comment by clason** [comment]
Then your Neovim installation (of 0.10) is broken and you should complain to whomever you downloaded it from.

**Comment by uloco** [comment]
ok after reinstall it worked. thanks. minimal repo is just a single line of markdown and minimal lua is just a single line of vim.treesitter.start(), and it still appears. I'm going to look for an old issue if this is already known, otherwise I will post an issue on the neovim main repo. thanks a lot :)

**Comment by uloco** [comment]
yes I test with that command. it still happens.

**Comment by uloco** [comment]
Looks like it is indeed an issue with my terminal... how can this be? I'm using iTerm2 ... do you have any idea?

**Comment by clason** [comment]
No, sorry. Make sure you have the latest version (3.5.0, the 3.4 releases are known to be broken).

**Comment by uloco** [comment]
lol found it -.-
<img width="1054" alt="image" src="https://github.com/nvim-treesitter/nvim-treesitter/assets/8818340/0aa03a25-65f4-4b01-9573-e67b053b6552">

for anybody who sees this 🤦🏼‍♂️
