### ISSUE TITLE
[JSX Highlighting] tag delimiters no longer highlighted via TSTagDelimiter

### ISSUE THREAD

**Issue by bluz71** [nvim-treesitter/nvim-treesitter#674]
Hello,

[This pull request](https://github.com/nvim-treesitter/nvim-treesitter/pull/500) added tag and tag delimiter highlighting for JSX files as occurs for HTML. That worked great.

However, I just updated to the latest Neovim and Treesitter HEAD releases and JSX tag delimiters are no longer being highighted as `TSTagDelimiter`.

This screenshot visualises the issue:

![JSX_and_HTML](https://user-images.githubusercontent.com/11382509/99742092-df4c4000-2b26-11eb-88c1-07e401a4b928.png)

The top split is JavaScript with JSX and the bottom is HTML. Notice the tag delimiters, in the top split they are crimson (probably via the `TSOperator` color) and in the bottom split they are green (via the defined `TSTagDelimiter` group). Do look closely at the JSX, notice the `/` colors are in green, those are likely being highlighted still as `TSTagDelimiter` (correctly). The `<` and `>` characters are the issue.

I contend that HTML is being highlighted correctly and JSX slightly incorrect (as compared with ideal). Back when #500 was merged JSX tags were highlighted correctly.

So sometime between Sep 20 and Nov 20 this issue was introduced.
I tried a Git Bisect, but Neovim Treesitter failed because Neovim <---> Treesitter needed matching versions, I assume due to API changes.

Sorry, I can't easily pinpoint when this issue was introduced.

Hopefully this is a simple highlight ordering issue.

Best regards.

**Comment by kyazdani42** [comment]
Maybe you could Git Blame to check when this file was last edited. I think we merged something in the past month regarding jsx highlights, it could have broken this too.

**Comment by theHamsta** [comment]
A PR from me was merged in upstream nvim. It's changed the ordering of the queries (base languages first, then the queries of the language extension). This affected the ordering of the queries (but to the order we originally had when we wrote the first jsx/tsx queries)

**Comment by rockerBOO** [comment]
![2020-11-21-065538_4480x1440_scrot](https://user-images.githubusercontent.com/15027/99876772-eb87da00-2bc6-11eb-9035-a6cd167c604c.png)

The tag seems to be being detected but the highlighting is not correct.

My local version seems to work properly in tsx files but not js or jsx files.

![2020-11-21-070349_4480x1440_scrot](https://user-images.githubusercontent.com/15027/99876869-dcedf280-2bc7-11eb-9f52-832d3e8bc37b.png)

![2020-11-21-070522_4480x1440_scrot](https://user-images.githubusercontent.com/15027/99876885-fc851b00-2bc7-11eb-90a6-70eddf87a4a5.png)

**Comment by theHamsta** [comment]
Could this weird highlighting of left parens be related (#677)?  It's also not showing some highlight though it's clearly in the queries.

**Comment by rockerBOO** [comment]
I think in this case, its not the `/` but the `<` `>` that are getting the wrong highlight. All 3 should be the same color as all should be capture grouped as `@tag.delimiter`

**Comment by bluz71** [comment]
> I think in this case, its not the `/` but the `<` `>` that are getting the wrong highlight. All 3 should be the same color as all should be capture grouped as `@tag.delimiter`

Yes, I mention that in the first post, slash is highlighted correctly as tag-delimiter whilst < and > are highlighted as operator.

**Comment by stellarhoof** [comment]
I've run into this issue as well. The specificity of the highlighting groups seems to be the issue.

<img width="460" alt="Screen Shot 2020-11-30 at 8 15 56 AM" src="https://user-images.githubusercontent.com/4336260/100614819-b7a66600-32e4-11eb-8449-92e8d3ab9b97.png">

I can only style tags via `TSConstructor` since it's the more specific one.

**Comment by bluz71** [comment]
@stellarhoof,

Slight tangent.

Those screenshots showing the highlight groups are awesome. How do you do that? As a Vim theme author myself I could really use that helper for Treesitter highlight debugging.

Cheers.

**Comment by theHamsta** [comment]
@bluz71 I made this for https://github.com/nvim-treesitter/playground. I don't hook into the internal state of the highlighter but just evaluate the queries in highlights.scm. So results might be inaccurate if highlighter implementation changes. Also I suppose doesn't yet work with injections.

**Comment by ofrades** [comment]
My tsx is looking wrong too:

![image](https://user-images.githubusercontent.com/31070771/101160191-89978d80-3626-11eb-8118-a3313997b53c.png)

And if I capture under cursor, I get this:

![image](https://user-images.githubusercontent.com/31070771/101160353-d11e1980-3626-11eb-8237-090178f87771.png)

**Comment by kyazdani42** [comment]
seems like either your parser is not up to date, or you did not install the tsx parser, mine is working fine. Also if no matches were found, text wouldn't be highlighted if treesitter was active on the buffer.
Please run `TSInstall tsx` to fix this. Also make sure your neovim version is at one of the latest commits, and the same for nvim-treesitter.

**Comment by ofrades** [comment]
yes, it is strange, I have the latest tree-sitter and nvim and I have the parser installed. this is the playground:
![image](https://user-images.githubusercontent.com/31070771/101176371-4d702700-363e-11eb-8f14-f6ed2f78cd9f.png)

**Comment by bluz71** [comment]
Sorry to bump, but this still remains an issue for JSX tag highlighting (top JSX is incorrect, bottom HTML is correct):

![99742092-df4c4000-2b26-11eb-88c1-07e401a4b928](https://user-images.githubusercontent.com/11382509/109256172-90aaf200-7849-11eb-8c24-fd47caa1d63c.png)

As noted, for JSX `<` / `>` is being highlighted as `operator` rather than `tag.delimiter`. This used to work around September 2020 and then became broken between September to November 2020. I am pretty sure this is an ordering issue.

Hopefully this will be fixed prior to 0.5 release.

**Comment by bluz71** [comment]
Thank you @kyazdani42, issue is confirmed as fixed.
