### ISSUE TITLE
MyST directives with colon fence notation

### ISSUE THREAD

**Issue by petobens** [nvim-treesitter/nvim-treesitter#6748]
Hi! The MyST markdown parser allows  to write rst directives using `:::` as per this [docs](https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#syntax-colon-fence). So for instance one can write

```md
:::{toctree}
:hidden:
:maxdepth: 2

user-guide/index
api-reference/index
:::
```
The problem is that this is not parsed/captured as a directive but rather simply as an `(inline)`.  The feature request is precisely to extend the syntax to capture this as a directive.
cc @ribru17

**Comment by clason** [comment]
We don't support this parser, so we can't support this syntax.

**Comment by petobens** [comment]
Ohh I see. Thanks for the quick reply.

**Comment by mmcky** [comment]
@petobens we setup [this project](https://github.com/QuantEcon/myst-markdown-tree-sitter.nvim), to enable better MyST syntax highlighting (extending tree-sitter markdown and LaTeX highlighting). 

The core limitation however is the `:::` so we use backticks instead

````
```{toctree}
```
````

Just thought I would share in case that is helpful.
