### ISSUE TITLE
highlight TSConditional guifg= doesn't seem to work

### ISSUE THREAD

**Issue by esn89** [nvim-treesitter/nvim-treesitter#675]
**Describe the bug**
`highlight TSConditional guifg=#C586C0` in init.vim doesn't apply the colours on my `if`, `while`, `for` in Python 3.7.
I made sure I had this in my init.vim as well:

```
lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained", -- one of "all", "maintained" (parsers with maintainers), or a list of languages
  highlight = {
    enable = true,              -- false will disable the whole extension
    disable = { "c", "rust" },  -- list of language that will be disabled
  },
}
EOF
```

**To Reproduce**
1. Install nightly nvim 5.0.0
2. Install this treesitter as shown in the README.md
3. Add the highlight line as shown above and restart vim.

**Expected behavior**
I expect those keywords to follow my colourscheme

**Output of `nvim --version`**
```
v5.0.0
```

**Comment by kyazdani42** [comment]
can yo do `:hi TSConditionnal` after nvim was started ? Maybe you set TSConditionnal before NvimTreesitter does

**Comment by esn89** [comment]
Hi, 

This is what `:hi TSConditional` looks like

```
:hi TSConditional                                                                                                                                                                
TSConditional  xxx ctermfg=109 guifg=#81a1c1                                                                                                                                     
Press ENTER or type command to continue   
```

**Comment by kyazdani42** [comment]
seems like its overriden. You should set the highlight after nvim-treesitter is loaded.

**Comment by esn89** [comment]
@kyazdani42 

Thanks, how can I do that, to ensure it is highlighting only after it is loaded?

**Comment by kyazdani42** [comment]
depends on how you load your plugins, what package manager you use, or package management style you use (like lazy loading and so one).

**Comment by esn89** [comment]
@kyazdani42 

For plugins, I use vim-plug, without lazy loading.  In the same init.vim, I have the highlighting colours declared there:

[Link to my init.vim](https://pastebin.com/sBqhPwvY)

**Comment by kyazdani42** [comment]
`hi TSConditional guifg=#81a1c1 ctermfg=109 guibg=NONE ctermbg=NONE gui=NONE cterm=NONE`
just change that to match your desired color
