### ISSUE TITLE
Highlighs in .dart goes crazy sometimes

### ISSUE THREAD

**Issue by justjew** [nvim-treesitter/nvim-treesitter#6756]
### Describe the highlighting problem

Sometimes after changing any word and go to normal mode, the highlights become very strange. Even one single word may contain 2 or more colors.
To fix it I just need to go to insert mode, put some sybmol and go back to normal mode.

### Example snippet that causes the problem

See screenshots

### Tree-sitter parsing result

    (return_statement) ; [180:5 - 187:6]
     (identifier) ; [180:12 - 26]
     (selector) ; [180:27 - 187:5]
      (argument_part) ; [180:27 - 187:5]
       (arguments) ; [180:27 - 187:5]
        (named_argument) ; [181:7 - 38]
         (label) ; [181:7 - 15]
          (identifier) ; [181:7 - 14]
         (identifier) ; [181:17 - 31]
         (selector) ; [181:32 - 38]
          (unconditional_assignable_selector) ; [181:32 - 38]
           (identifier) ; [181:33 - 38]
        (named_argument) ; [182:7 - 39]
         (label) ; [182:7 - 12]
          (identifier) ; [182:7 - 11]
         (function_expression) ; [182:14 - 39]
          parameters: (formal_parameter_list) ; [182:14 - 15]
          body: (function_expression_body) ; [182:17 - 39]
           (identifier) ; [182:20 - 30]
           (selector) ; [182:31 - 39]
            (argument_part) ; [182:31 - 39]
             (arguments) ; [182:31 - 39]
              (argument) ; [182:32 - 38]
               (identifier) ; [182:32 - 38]
        (named_argument) ; [183:7 - 186:7]
         (label) ; [183:7 - 12]
          (identifier) ; [183:7 - 11]
         (identifier) ; [183:14 - 20]
         (selector) ; [183:21 - 186:7]
          (argument_part) ; [183:21 - 186:7]
           (arguments) ; [183:21 - 186:7]
            (named_argument) ; [184:9 - 72]
             (label) ; [184:9 - 16]
              (identifier) ; [184:9 - 15]
             (const_object_expression) ; [184:18 - 72]
              (const_builtin) ; [184:18 - 22]
              (type_identifier) ; [184:24 - 33]
              (identifier) ; [184:35 - 43]
              (arguments) ; [184:44 - 72]
               (named_argument) ; [184:45 - 58]
                (label) ; [184:45 - 55]
                 (identifier) ; [184:45 - 54]
                (decimal_integer_literal) ; [184:57 - 58]
               (named_argument) ; [184:61 - 71]
                (label) ; [184:61 - 69]
                 (identifier) ; [184:61 - 68]
                (decimal_integer_literal) ; [184:71 - 71]
            (named_argument) ; [185:9 - 22]
             (label) ; [185:9 - 14]
              (identifier) ; [185:9 - 13]
             (identifier) ; [185:16 - 22]

### Example screenshot

<img width="623" alt="SCR-20240611-luah" src="https://github.com/nvim-treesitter/nvim-treesitter/assets/15147974/e67f4550-e102-46d4-8e96-abacb993b1c1">
<img width="1314" alt="SCR-20240611-lvkr" src="https://github.com/nvim-treesitter/nvim-treesitter/assets/15147974/cc7b246b-d806-49af-a049-ee3d7fd97ee3">

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v22.2.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 15.0.0 (clang-1500.3.9.4)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.2.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - dart                ✓ ✓ ✓ ✓ ✓
  - diff                ✓ . . . .
  - gitignore           ✓ . . . .
  - groovy              ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - kotlin              ✓ ✓ ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - markdown            ✓ . ✓ ✓ ✓
  - prisma              ✓ . ✓ . .
  - proto               ✓ . ✓ . .
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - swift               ✓ ✓ . ✓ .
  - tmux                ✓ . . . ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - xml                 ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377
```

**Comment by justjew** [comment]
Any ideas?

**Comment by clason** [comment]
No, not really; but that is not an nvim-treesitter issue. Please try to create a minimal(!) reproducible config and an example file (plus explicit steps -- "type this, do that") so someone can reproduce it, then open an issue at Neovim. Do test the latest version (0.10) or, ideally, nightly build first, though.
