### ISSUE TITLE
Weird highlighing of parens in C

### ISSUE THREAD

**Issue by osa1** [nvim-treesitter/nvim-treesitter#677]
I'm using latest neovim and latest nvim-treesitter, both installed from master branches a few minutes ago.

![Screenshot_2020-11-21_13-43-14](https://user-images.githubusercontent.com/448274/99875315-961bef00-2bff-11eb-9dfb-f07ec72a4f5a.png)

The screenshot summarizes the problem. Not sure if this is a tree-sitter grammar bug or a nvim-treesitter bug though. Basically left and right parens in C are highlighted differently. Note that adding a space before the left paren doesn't change anything. For example in `if (...)` left and right parens are still highlighted differently.

Rust highlighting doesn't have this problem. I haven't tried other languages.

My nvim-treesitter config:

```
lua <<EOF
require('nvim-treesitter.configs').setup {
    ensure_installed = { "rust", "c" },
    highlight = {
        enable = true, -- false will disable the whole extension
        disable = {},  -- list of language that will be disabled
    },
    incremental_selection = {
        enable = true,
        keymaps = {
            init_selection = "gnn",
            node_incremental = "grn",
            scope_incremental = "grc",
            node_decremental = "grm",
        },
        indent = {
            enable = true
        },
    },
}
EOF
```

**Comment by theHamsta** [comment]
This is weird. With everything in hlmap set to nil apart from "punctuaction.bracket":

![image](https://user-images.githubusercontent.com/7189118/99878445-a2a34600-2c05-11eb-8a8b-529770fc8f90.png)

**Comment by osa1** [comment]
I did `:TSInstall c` and then `:TSInstallFromGrammar c` (I have tree-sitter-cli installed, from tree-sitter master branch) and C highlighing is now completely broken.

![Screenshot_2020-11-22_11-31-02](https://user-images.githubusercontent.com/448274/99898912-4e0bd380-2cb6-11eb-81ef-8309552c39e1.png)

After this C highlighting is not done via tree-sitter but using the plain old vim syntax files.

**Comment by osa1** [comment]
Ah, interesting. I re-run `TSInstall c` (without `TSInstallFromGrammar c`) and the highlighting seems to be fixed now.

If this is necessary then I guess it should be mentioned in the readme.

**Comment by theHamsta** [comment]
This can be probably avoided by running :TSUpdate whenever the plugin is updated. There's a PR that only updates those parsers that need an update

**Comment by theHamsta** [comment]
Feel free to re-open if this should ever occur again!
