### ISSUE TITLE
Code at the bottom of the screen is not highligted until I scroll more

### ISSUE THREAD

**Issue by osa1** [nvim-treesitter/nvim-treesitter#678]
Using nvim and nvim-treesitter head.

![Screenshot_2020-11-21_16-39-06](https://user-images.githubusercontent.com/448274/99878672-3716a400-2c18-11eb-964d-4ffdf5e0dfb1.png)

As shown in the screenshot, code at the bottom of the screen are not highlighted. If I scroll more they get highlighted, but I have to keep scrolling around until the buffer is properly highlighted.

I would expect the visible part of the code to be always highlighted.

**Comment by stsewd** [comment]
Hi, this looks the same as https://github.com/nvim-treesitter/nvim-treesitter/issues/621, this happens with any movement as noted in the another issue

**Comment by osa1** [comment]
Hmm, right, this seems to be a duplicate of #621. Closing.
