### ISSUE TITLE
Latex `@nospell`

### ISSUE THREAD

**Issue by jdujava** [nvim-treesitter/nvim-treesitter#6785]
A lot of latex nodes which are captured should have `@nospell`, but at this point it is not the case (for example includes, color definitions/references, `\href`, and so much more). Is there a reason for this, or just nobody cared enough to place it to appropriate places?

If I would embark on improving this state, do you have any guidance how to structure `@nospell` captures? Should I create exclusive captures for `@nospell` and gather them close together (this seems to be the current state, but this would result in a lot of duplication), or should I just append `@nospell` to the appropriate captures already created?

**Comment by lucario387** [comment]
append if possible will be the way to go

The other question is whether you can use only 1 or 2 capture for all of those nodes.
