### ISSUE TITLE
Changes in files outside of nvim causes errors

### ISSUE THREAD

**Issue by osa1** [nvim-treesitter/nvim-treesitter#679]
I'm using latest nvim and nvim-treesitter installed from master branches.

When the changes currently shown in nvim changes because e.g. changing git branches, or `git stash` etc. I get errors like shown in the screenshot below:

![Screenshot_2020-11-21_19-06-32](https://user-images.githubusercontent.com/448274/99881787-e3628580-2c2c-11eb-9426-6fb68e55abe9.png)

I have no idea how to see the full error message. If anyone tell me how to do that I can give more details.

**Comment by kdurant** [comment]
I have the sampe problem.

**Comment by stsewd** [comment]
This is kind of related to https://github.com/nvim-treesitter/nvim-treesitter/issues/610 and https://github.com/nvim-treesitter/nvim-treesitter/issues/651, both upstream issues

**Comment by kyazdani42** [comment]
closing since it's not an issue anymore
