### ISSUE TITLE
Long paragraph leads to breakdown of highlight.

### ISSUE THREAD

**Issue by yuukibarns** [nvim-treesitter/nvim-treesitter#6794]
### Describe the bug

https://github.com/nvim-treesitter/nvim-treesitter/assets/135401840/ed6f6a19-712d-4b7d-83f4-1f66374c3dfd

### To Reproduce

1

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.22.6 (b40f342067a89cd6331bf4c27407588320f3c263) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.13.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 14.1.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.22631",
  sysname = "Windows_NT",
  version = "Windows 11 Home China"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - bibtex              ✓ . ✓ ✓ ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - comment             ✓ . . . .
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - diff                ✓ . . . .
  - latex               ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - luap                ✓ . . . .
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
```

### Additional context

Even if I cancel the latex injection in the markdown_inline parser, the problem remains.

**Comment by clason** [comment]
Please provide config and text file we can test with `nvim --clean -u minimal.lua test.md`.

**Comment by yuukibarns** [comment]
Highlight fails as the top of the window pass the long paragraph

**Comment by yuukibarns** [comment]
You can create any markdown file and try to write a long paragraph with length exceeds the length of the window, and try to move the top of the window to pass the long paragraph, then the highlight of the lines below will fail.
Sorry for my bad English.

**Comment by clason** [comment]
I'm sorry, I don't see anything of the sort. Can you please provide a minimal example that fails for you that I can actually test myself?

**Comment by yuukibarns** [comment]
[j.md](https://github.com/user-attachments/files/15936322/j.md)

**Comment by yuukibarns** [comment]
Make the window smaller may help to reproduce the problem.

**Comment by clason** [comment]
I don't see any issue with that, sorry. That's why I am insisting on a minimal config to go with it that I can test with `nvim --clean -u test.lua`.

**Comment by yuukibarns** [comment]
I use both the markdown and markdown_inline parsors

**Comment by clason** [comment]
Yes, obviously, so am I. But there's a lot of other things in your config that can affect this.
