### ISSUE TITLE
Undo leads to markdown highlight failure.

### ISSUE THREAD

**Issue by yuukibarns** [nvim-treesitter/nvim-treesitter#6806]
### Describe the bug

https://github.com/nvim-treesitter/nvim-treesitter/assets/135401840/1e71a1cf-5390-4d24-b87d-6e94af9a6686

### To Reproduce

Here is my minimal config:
```lua
local path = vim.fn.stdpath("data") .. "/nvim-treesitter"
vim.opt.rtp:prepend(path)

require("nvim-treesitter.configs").setup({
	ensure_installed = {
		"markdown",
		"markdown_inline",
		"latex",
	},
	highlight = { enable = true },
})

vim.opt.smoothscroll = false
```
`vim.opt.smoothscroll = false` is to ensure that `smoothscroll` doesn't make any difference.

Here is my .md file used in the video.
[q.md](https://github.com/user-attachments/files/15964180/q.md)

My operation in the video is 
1. `G` to the bottom
2. `o` to open a new line and input some `a`
3. undo the last operation
4. navigate back to the top and find highlight of first two lines fails
5. input `a` and find highlight is restored.

### Expected behavior

The first two lines should be highlight properly after undo.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.22.6 (b40f342067a89cd6331bf4c27407588320f3c263) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.13.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 14.1.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.22631",
  sysname = "Windows_NT",
  version = "Windows 11 Home China"
} ~

Parser/Features         H L F I J
  - latex               ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
```

**Comment by lucario387** [comment]
This seems like a followup to what the neovim PR is, I'd assume.

Can you report the issue there?

**Comment by yuukibarns** [comment]
Sorry for my limited comprehension, but how should I report this issue there? By opening a new issue?

**Comment by lucario387** [comment]
Yes, just like how you reported the issue last time.

**Comment by yuukibarns** [comment]
I've opened an issue at neovim/neovim.
https://github.com/neovim/neovim/issues/29482

**Comment by lucario387** [comment]
It's superseded by that issue. so I'm closing this
