### ISSUE TITLE
Doc: deprecated tracking issue for language support still in REAMDE

### ISSUE THREAD

**Issue by foxyseta** [nvim-treesitter/nvim-treesitter#6811]
### Describe the bug

https://github.com/nvim-treesitter/nvim-treesitter/issues/2282, which was closed a while ago, is still mentioned in the README.

### To Reproduce

Open README.

### Output of `:checkhealth nvim-treesitter`

```markdown
-
```

### Output of `nvim --version`

```text
-
```

**Comment by clason** [comment]
The docs are outdated and will be completely rewritten for 1.0
