### ISSUE TITLE
Unexpected active the treesitter during lua function

### ISSUE THREAD

**Issue by zhyzky** [nvim-treesitter/nvim-treesitter#6822]
### Describe the bug

Using lazyvim, create a function like
···
vim.g.Testxxd = function()
  vim.cmd("%!xxd")
  vim.bo.ft = "xxd"
end
···
when the function executed, an error like "no parser for 'xxd' language" came up.
It's wiered that when execute "vim.cmd("%!xxd")" or "vim.bo.ft = "xxd"" or even both outside the function, no error appeared, and treesitter seemes not actived.
And if either line commented, no error.
the error pops only when both line exists in one function.

### To Reproduce

1. Create a function like
···
vim.g.Testxxd = function()
  vim.cmd("%!xxd")
  vim.bo.ft = "xxd"
end
···
2. In nvim exec cmd :call Testxxd()
3. The error appears

### Expected behavior

No error appear

### Output of `:checkhealth nvim-treesitter`

```markdown
Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v16.16.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.15.153.1-microsoft-standard-WSL2",
  sysname = "Linux",
  version = "#1 SMP Fri Mar 29 23:14:13 UTC 2024"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - diff                ✓ . . . .
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - json5               ✓ . . . ✓
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - luap                ✓ . . . .
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - ninja               ✓ . ✓ ✓ ✓
  - printf              ✓ . . . .
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - rst                 ✓ ✓ . . ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - xml                 ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
0.10.0
```

**Comment by ribru17** [comment]
I think this is an issue with neovim core, stemming from the fact that a buffer is given the treesitter foldexpr, then the filetype changes (to one without a parser, i.e. no fold queries), then buffer content changes (now there is no way to properly calculate folds, because no parser/fold queries); hence an error

**Comment by zhyzky** [comment]
> I think this is an issue with neovim core, stemming from the fact that a buffer is given the treesitter foldexpr, then the filetype changes (to one without a parser, i.e. no fold queries), then buffer content changes (now there is no way to properly calculate folds, because no parser/fold queries); hence an error

Make sense. I reproduced the error using command line.

**Comment by clason** [comment]
I cannot reproduce this with the given steps. If you can't reproduce it without LazyVim, please open an issue there.
