### ISSUE TITLE
Ensure installed option make parsers getting re-installed on each startup

### ISSUE THREAD

**Issue by weilbith** [nvim-treesitter/nvim-treesitter#683]
Hey,

In my configuration I have a list of parser I like to get installed automatically by the plugin. Unfortunately this makes them getting installed on each start of NeoVim. Over and over again. Why is that? I thought it **ensures** they are installed by checking if there is a parser or not and of not install it, else do nothing. Can I somehow prevent this behavior?

Partial config:

```lua
require'nvim-treesitter.configs'.setup {
   ensure_installed = {
    "bash",
    "c",
    "c_sharp",
    "cpp",
    "css",
    "go",
    "html",
    "java",
    "javascript",
    "jsdoc",
    "json",
    "lua",
    -- "markdown",
    "python",
    "rst",
    "rust",
    "toml",
    "typescript",
    -- "vue",
  },
}
```

Output of `:messages` after startup:

```
[nvim-treesitter] [0/17] Downloading...
[nvim-treesitter] [0/17] Downloading...
[nvim-treesitter] [0/17] Downloading...
[nvim-treesitter] [0/17] Downloading...
[nvim-treesitter] [0/17] Downloading...
[nvim-treesitter] [0/17] Downloading...
[nvim-treesitter] [0/17] Downloading...
[nvim-treesitter] [0/17] Downloading...
[nvim-treesitter] [0/17] Downloading...
[nvim-treesitter] [0/17] Downloading...
[nvim-treesitter] [0/17] Downloading...
[nvim-treesitter] [0/17] Downloading...
[nvim-treesitter] [0/17] Downloading...
[nvim-treesitter] [0/17] Downloading...
[nvim-treesitter] [0/17] Downloading...
[nvim-treesitter] [0/17] Downloading...
[nvim-treesitter] [0/17] Downloading...
[nvim-treesitter] [0/17] Creating temporary directory
[nvim-treesitter] [0/17] Extracting...
[nvim-treesitter] [0/17] Compiling...
[nvim-treesitter] [0/17] Creating temporary directory
[nvim-treesitter] [0/17] Extracting...
[nvim-treesitter] [0/17] Compiling...
[nvim-treesitter] [0/17] Creating temporary directory
[nvim-treesitter] [0/17] Extracting...
[nvim-treesitter] [0/17] Compiling...
[nvim-treesitter] [0/17] Creating temporary directory
[nvim-treesitter] [0/17] Extracting...
[nvim-treesitter] [0/17] Compiling...
[nvim-treesitter] [1/17] Treesitter parser for json has been installed
[nvim-treesitter] [1/17] Creating temporary directory
[nvim-treesitter] [1/17] Extracting...
[nvim-treesitter] [1/17] Compiling...
[nvim-treesitter] [1/17] Creating temporary directory
[nvim-treesitter] [1/17] Creating temporary directory
[nvim-treesitter] [1/17] Extracting...
[nvim-treesitter] [1/17] Extracting...
[nvim-treesitter] [1/17] Creating temporary directory
[nvim-treesitter] [1/17] Creating temporary directory
[nvim-treesitter] [1/17] Creating temporary directory
[nvim-treesitter] [1/17] Creating temporary directory
[nvim-treesitter] [1/17] Creating temporary directory
[nvim-treesitter] [1/17] Creating temporary directory
[nvim-treesitter] [1/17] Creating temporary directory
[nvim-treesitter] [1/17] Extracting...
[nvim-treesitter] [1/17] Compiling...
[nvim-treesitter] [1/17] Extracting...
[nvim-treesitter] [1/17] Extracting...
[nvim-treesitter] [1/17] Extracting...
[nvim-treesitter] [1/17] Extracting...
[nvim-treesitter] [1/17] Extracting...
[nvim-treesitter] [1/17] Extracting...
[nvim-treesitter] [2/17] Treesitter parser for jsdoc has been installed
[nvim-treesitter] [3/17] Treesitter parser for java has been installed
[nvim-treesitter] [3/17] Compiling...
[nvim-treesitter] [4/17] Treesitter parser for rst has been installed
[nvim-treesitter] [4/17] Compiling...
[nvim-treesitter] [4/17] Compiling...
[nvim-treesitter] [4/17] Compiling...
[nvim-treesitter] [4/17] Compiling...
[nvim-treesitter] [4/17] Compiling...
[nvim-treesitter] [4/17] Compiling...
[nvim-treesitter] [4/17] Creating temporary directory
[nvim-treesitter] [4/17] Compiling...
[nvim-treesitter] [4/17] Extracting...
[nvim-treesitter] [4/17] Creating temporary directory
[nvim-treesitter] [4/17] Extracting...
[nvim-treesitter] [4/17] Compiling...
[nvim-treesitter] [4/17] Creating temporary directory
[nvim-treesitter] [4/17] Extracting...
[nvim-treesitter] [4/17] Compiling...
[nvim-treesitter] [4/17] Compiling...
[nvim-treesitter] [5/17] Treesitter parser for css has been installed
[nvim-treesitter] [6/17] Treesitter parser for toml has been installed
[nvim-treesitter] [7/17] Treesitter parser for go has been installed
[nvim-treesitter] [8/17] Treesitter parser for python has been installed
[nvim-treesitter] [9/17] Treesitter parser for lua has been installed
[nvim-treesitter] [10/17] Treesitter parser for javascript has been installed
[nvim-treesitter] [11/17] Treesitter parser for html has been installed
[nvim-treesitter] [12/17] Treesitter parser for c has been installed
[nvim-treesitter] [13/17] Treesitter parser for rust has been installed
[nvim-treesitter] [14/17] Treesitter parser for cpp has been installed
[nvim-treesitter] [15/17] Treesitter parser for typescript has been installed
[nvim-treesitter] [16/17] Treesitter parser for bash has been installed
[nvim-treesitter] [17/17] Treesitter parser for c_sharp has been installed
```

**Comment by theHamsta** [comment]
This behavior is a bug (I've never observed it).

Could it be that the installed parsers are not in rtp in the moment when you run setup (and thus not recognized as installed).

**Comment by weilbith** [comment]
Hmm. I need to check that. Eventually I'm doing something wrong with my plugin manager _dein_ here. But actually it is not lazy loaded or so. :thinking: 
Where is the installation target of the parsers? 
I'll check the runtime path before the setup function gets called. I'm in a hurry now and do that later. I'll post a comment soon on that.

**Comment by theHamsta** [comment]
The default install location is `nvim-treesitter/parser`. You can check whether nvim finds a parser with
 `parser = vim.treesitter.get_parser(bufnr, lang)` or `nvim_get_runtime_file('parser/c.so`).

See `:h lua-treesitter-parser` and `:h lua-treesitter`.

**Comment by weilbith** [comment]
I'm confused. I swear before I opened this issue the parsers got installed each time I run NeoVim. Now I did an update of all my plugins and apparently this issue got resolved. At least it appears to not happen anymore. I'm sorry for wasting your time.
If it should occur again I'll do all the research as you suggest before I re-open it.
Thanks for your fast help! :+1:

**Comment by ryoakg** [comment]
I came across the same issue, and it still persists. I'm a Neovim newbie and setting up it.

Parsers seems to be installed.

    $ ls -ld ~/.local/share/nvim/lazy/nvim-treesitter/parser/parser
    drwxr-xr-x - a  1 Nov 21:48 /home/a/.local/share/nvim/lazy/nvim-treesitter/parser
    $ ls ~/.local/share/nvim/lazy/nvim-treesitter/parser
    c.so    css.so  html.so        json.so  php.so     query.so  tsx.so         vim.so
    cpp.so  go.so   javascript.so  lua.so   python.so  rust.so   typescript.so  vimdoc.so

But `:message` says:

    [nvim-treesitter] [0/2] Downloading tree-sitter-python...
    [nvim-treesitter] [0/2] Downloading tree-sitter-lua...
    [nvim-treesitter] [0/2] Creating temporary directory
    [nvim-treesitter] [0/2] Extracting tree-sitter-lua...
    [nvim-treesitter] [0/2] Compiling...
    [nvim-treesitter] [0/2] Creating temporary directory
    [nvim-treesitter] [0/2] Extracting tree-sitter-python...
    [nvim-treesitter] [0/2] Compiling...
    [nvim-treesitter] [1/2] Treesitter parser for lua has been installed
    [nvim-treesitter] [2/2] Treesitter parser for python has been installed

`nvim_get_runtime_file` indicate the same:

    :lua =vim.api.nvim_get_runtime_file('parser/lua.so',true)
    { "/home/a/.local/share/nvim/lazy/nvim-treesitter/parser/lua.so" }
    :lua =vim.api.nvim_get_runtime_file('parser/python.so',true)
    { "/home/a/.local/share/nvim/lazy/nvim-treesitter/parser/python.so" }

after `:q`, of course no parsers are deleted:

    ls ~/.local/share/nvim/lazy/nvim-treesitter/parser
    c.so    css.so  html.so        json.so  php.so     query.so  tsx.so         vim.so
    cpp.so  go.so   javascript.so  lua.so   python.so  rust.so   typescript.so  vimdoc.so

Does anyone have good ideas?

**Comment by clason** [comment]
> Does anyone have good ideas?

Check you lazy config. Nvim-treesitter does not support lazy-loading.
