### ISSUE TITLE
Highlighting not working when I open the file a second time

### ISSUE THREAD

**Issue by Kurren123** [nvim-treesitter/nvim-treesitter#6844]
### Describe the bug

Upon first install (and the first time installing after deleting the `nvim-treesitter` folder from the lazy package manager) the highlighting works correctly. But then once I `:q` and then open the `init.lua` file again, there is no highlighting. `:TSBufEnable highlight` and `:TSEnable highlight` does nothing. `:echo &filetype` returns `lua`. My `init.lua`:

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
  local lazyrepo = "https://github.com/folke/lazy.nvim.git"
  vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({{
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function () 
      local configs = require("nvim-treesitter.configs")

      configs.setup({
          ensure_installed = { "lua" },
          sync_install = false,
          highlight = { enable = true },
          indent = { enable = true },  
        })
    end
 }})
```

### To Reproduce

1. On windows 10, use the above `init.lua` script
2. Open `init.lua`
3. Close nvim, open `init.lua` again

### Expected behavior

Highlight should work

### Output of `:checkhealth nvim-treesitter`

```markdown
`:checkhealth treesitter`:


vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: lua                  ABI: 14, path: C:\Users\Kurren\AppData\Local\nvim-data\lazy\nvim-treesitter\parser\lua.so
- OK Parser: bash                 ABI: 14, path: C:\Program Files\Neovim\lib\nvim\parser\bash.dll
- OK Parser: c                    ABI: 14, path: C:\Program Files\Neovim\lib\nvim\parser\c.dll
- OK Parser: lua                  ABI: 14, path: C:\Program Files\Neovim\lib\nvim\parser\lua.dll
- OK Parser: markdown             ABI: 14, path: C:\Program Files\Neovim\lib\nvim\parser\markdown.dll
- OK Parser: markdown_inline      ABI: 14, path: C:\Program Files\Neovim\lib\nvim\parser\markdown_inline.dll
- OK Parser: python               ABI: 14, path: C:\Program Files\Neovim\lib\nvim\parser\python.dll
- OK Parser: query                ABI: 14, path: C:\Program Files\Neovim\lib\nvim\parser\query.dll
- OK Parser: vim                  ABI: 14, path: C:\Program Files\Neovim\lib\nvim\parser\vim.dll
- OK Parser: vimdoc               ABI: 14, path: C:\Program Files\Neovim\lib\nvim\parser\vimdoc.dll
```

`:checkhealth nvim-treesitter`:

```md
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v16.13.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: gcc (x86_64-posix-seh-rev0, Built by MinGW-Builds project) 13.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.19045",
  sysname = "Windows_NT",
  version = "Windows 10 Pro"
} ~

Parser/Features         H L F I J
  - lua                 ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

If I do `:TSUpdate lua` I just get `Parsers are up-to-date!`

### Output of `nvim --version`

```text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
```

**Comment by clason** [comment]
I don't understand this; on Nvim 0.10, treesitter highlighting is enabled by default (without nvim-treesitter). Can you reproduce this with another parser?

(Also, you don't need lazy in your repro -- just clone _this_ plugin like you do lazy and call setup normally.)

**Comment by Kurren123** [comment]
Thanks @clason. The usual nvim highlighting is on:

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/3525980/22ba6504-ae9d-45f6-a684-555aef3702d1)

But this is not the highlighting that exists after installing nvim-treesitter for the first time:

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/3525980/5403eaf5-4c0a-4c20-a415-254e0e4c0c5c)

I clone the repo directly and remove lazy. Strangely it does not even highlight the first time or subsequent times now:

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/3525980/43de7d17-9e93-4e45-9281-50d4f3c034e5)

**Comment by clason** [comment]
> But this is not the highlighting that exists after installing nvim-treesitter for the first time:

I think this is just lazy showing a different colorscheme on first install. Every other screenshot looks exactly like it should look with the new default colorscheme in 0.10.

**Comment by Kurren123** [comment]
This is the default highlighting without the treesitter plugin, eg:

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/3525980/852ac2d2-b528-4500-b2b0-93e24078f7ef)

Keywords like `local`, `if` and `then` as well as the booleans aren't being highlighted, unlike the highlighting applied after the lazy installation of treesitter. This makes me think it's more than a colour scheme.

**Comment by clason** [comment]
Always test `:Inspect`; this will show you exactly what highlight is applied. (It will also show any LSP semantic tokens, which are a common source of "my highlighting is broken" confusion.)

**Comment by Kurren123** [comment]
Yes you are correct. I applied a different colour scheme and it works correctly. Sorry for wasting your time!
