### ISSUE TITLE
[Feature] support goctl nvim-treesitter code highlights.

### ISSUE THREAD

**Issue by chaozwn** [nvim-treesitter/nvim-treesitter#6874]
**Is your feature request related to a problem? Please describe.**
go zero is a well-known go microservices framework. He has an api syntax of his own.
I already support its corresponding parser and highlighting, and want to support it in neovim.
How should I do?
go-zero : https://go-zero.dev/en/docs/tasks/dsl/api
goctl parser: https://github.com/chaozwn/tree-sitter-goctl

parse test:
<img width="849" alt="image" src="https://github.com/nvim-treesitter/nvim-treesitter/assets/51357674/a120a0ad-16a2-47f3-b99e-281aab5fa8cd">

highlight before:
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/51357674/63d94b5c-3a6b-44ae-bf7c-8f747e9e5d2b)

highlight after:
![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/51357674/ce52689d-2b06-4441-a9eb-5e97cbfb7d9f)

**Describe the solution you'd like**
I would like to contribute this section to nvim-treesitter

**Describe alternatives you've considered**

**Additional context**

**Comment by clason** [comment]
Just make a PR; look at merged pull requests labeled "new language".
