### ISSUE TITLE
python/locals.scm: class attribute captured as `@definition.associated` not `@definition.field`

### ISSUE THREAD

**Issue by ElPiloto** [nvim-treesitter/nvim-treesitter#688]
**Describe the bug**
In `queries/python/locals.scm`, @definition.associated is the incorrect capture to use for class attributes/fields.

**To Reproduce**
See image below using TSPlayground and queries loaded from `python/locals.scm`.    In the case below, I would expect `value` or `suit` under the Card class to be reported as `@definition.field`.
![image](https://user-images.githubusercontent.com/629190/99958125-b7f0af80-2d80-11eb-9685-8cafd4cd464c.png)

**Expected behavior**
Capture `suit` or `value` as `@definition.field`

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## c parser healthcheck
  - OK: c parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for c
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## python parser healthcheck
  - OK: python parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for python
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## lua parser healthcheck
  - OK: lua parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

## query parser healthcheck
  - OK: query parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `folds.scm` query found for query
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for query
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## javascript parser healthcheck
  - OK: javascript parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for javascript
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-823-g42ffa2d62
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/elpiloto/bin_from_source/neovim/build/config -I/home/elpiloto/bin_from_source/neovim/src -I/home/elpiloto/bin_from_source/neovim/.deps/usr/include -I/usr/include -I/home/elpiloto/bin_from_source/neovim/build/src/nvim/auto -I/home/elpiloto/bin_from_source/neovim/build/include
Compiled by elpiloto@DESKTOP-R2SL0QJ

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Additional context**

**Comment by ElPiloto** [comment]
It's unclear to me if this could be fixed by simply changed `@definition.associated` to `@definition.field` [here](https://github.com/nvim-treesitter/nvim-treesitter/blob/049028ef3e639d948e9e1ee464ad7b9fd317f2c4/queries/python/locals.scm#L9).

**Comment by theHamsta** [comment]
It should be fixed that way.
