### ISSUE TITLE
[hurl] Problem with GraphQL injections

### ISSUE THREAD

**Issue by lervag** [nvim-treesitter/nvim-treesitter#6882]
### Describe the bug

GraphQL blocks in hurl files are not displayed/parsed properly. Based on the discussion in https://github.com/pfeiferj/tree-sitter-hurl/issues/10, it seems this may be due to nvim-treesitter. I don't know these things well enough yet to be sure or to suggest a fix, so I'll just throw the issue up and hope for some feedback and help in fixing it.

### To Reproduce

* `nvim --clean -u test.lua`
* `:edit test.hurl`
* `:InspectTree`

`test.lua` and `test.hurl` are provided below.

### Expected behavior

The graphql code block should be highlighted properly. It is not, and the `InspectTree` output clearly shows a lot of errors.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v22.3.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 14.1.1 20240522
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.9.7-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Fri, 28 Jun 2024 04:32:50 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - graphql             ✓ . . ✓ ✓
  - hurl                ✓ . ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.11.0-dev-323+g8f5e908110
Build type: Release
LuaJIT 2.1.1716656478
Run "nvim -V1 -v" for more info
```

### Additional context

```lua
-- test.lua
local root = vim.fn.fnamemodify("./.lazy", ":p")

for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

require("lazy").setup({
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
      require("nvim-treesitter.configs").setup({
        ensure_installed = { "hurl", "graphql", "query" },
        highlight = { enable = true },
      })
    end,
  },
}, {
  root = root .. "/plugins",
})
```

`````
# test.hurl
POST https://api.starwars.com/graphql
```graphql
query HeroNameAndFriends($episode: Episode) {
  hero(episode: $episode) {
    name
    friends {
      name
    }
  }
}

variables {
  "episode": "JEDI"
}
```
HTTP 200
`````

**Comment by lervag** [comment]
@clason Let me know if I should add more context. I'll be happy to help, but I don't quite know where to start.

**Comment by clason** [comment]
The `(multiline_string)` injection needs `injection.combined` set; there might also be issues around  `set-lang-from-info-string` here which should be obsolete on latest Nvim.

**Comment by lervag** [comment]
Yes, it seems you are quite right. This block already seems to solve most of the issue:

```lisp
(multiline_string
  (multiline_string_type) @_lang
  (multiline_string_content) @injection.content
  (#set-lang-from-info-string! @_lang)
  (#set! injection.combined))
```

**Comment by lervag** [comment]
But the `set-lang-from-...` is used by other languages as well, including markdown:

https://github.com/nvim-treesitter/nvim-treesitter/blob/b7c0dbbe7d724f4741af37779135653bc3860304/queries/markdown/injections.scm#L1-L5

**Comment by clason** [comment]
Yes, since we haven't dropped support for Nvim 0.9 yet on this branch.

**Comment by lervag** [comment]
Ok. What is the new syntax that we should use instead?

**Comment by lervag** [comment]
Btw., after adding `(#set! injection.combined)`, the error I see now is this:

![image](https://github.com/nvim-treesitter/nvim-treesitter/assets/998898/6133e836-2996-4c77-82ee-1716a9b8d125)

But perhaps that is a problem with the graphql parser? At least it seems so.

**Comment by lervag** [comment]
Do you want me to create a PR with the one-line change?

**Comment by clason** [comment]
> But perhaps that is a problem with the graphql parser? At least it seems so.

Yes, it looks to be that way. I don't understand the language enough to tell.

> Do you want me to create a PR with the one-line change?

Yes, if you don't mind.

**Comment by lervag** [comment]
> Yes, it looks to be that way. I don't understand the language enough to tell.

👍🏻 

I've opened a PR as you probably noticed.

**Comment by lervag** [comment]
Great, thanks for the help here, @clason!
