### ISSUE TITLE
R: no indentation after `for` and `if` when there is no bracket 

### ISSUE THREAD

**Issue by jalvesaq** [nvim-treesitter/nvim-treesitter#6889]
### Describe the bug

R code isn't indented after `if` and `for` statements when their bodies are not between brackets.

### To Reproduce

Write an R file with the following contents:

```r
for (i in 1:10)
    print(i)

if (TRUE)
    print(FALSE)
```

and, in Normal mode, do `gg=G` to indent the entire buffer. I will be indented as:

```r
for (i in 1:10)
print(i)

if (TRUE)
print(FALSE)
```

### Expected behavior

One line should be indented after either `if` or `for` statement that isn't followed by curly braces.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.8 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v16.20.2 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Debian 13.3.0-1) 13.3.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.9.7-amd64",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Debian 6.9.7-1 (2024-06-27)"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - latex               ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - r                   ✓ ✓ . ✓ ✓
  - rnoweb              ✓ . ✓ . ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.11.0-dev-348+g3c53e8f78
Build type: Release
LuaJIT 2.1.1720049189
Run "nvim -V1 -v" for more info
```

**Comment by lucario387** [comment]
I don't know if brace-less if-for in R is common enough to add support for

@ribru17

**Comment by ribru17** [comment]
Yeah I agree, pretty uncommon. But also I am curious, in general why not add support if there is code for it? I see the argument for marking it unplanned but if there were a fix available (like in the js case) why not accept? Not that that applies here though.

**Comment by ribru17** [comment]
Makes sense. I would agree that this applies here too then

**Comment by jalvesaq** [comment]
Vim and RStudio support this coding style. Both even indent consecutive bracketless `if`s or `for`s. Example:

```r
if (TRUE)
  if (TRUE)
    print(FALSE)
```

The use of the syntax at least used to be common. For example, we find 1257 occurrences of bracketless `if`s in the `base` library in `R-4-4.1` source code (excluding the cases which have a `return` at the same line):

```sh
cd /path_to/R-4.4.1/src/library/base/R
grep '^\s*if.*)$' *.R | grep -v return | wc
```

But, indeed, it might reflect an old coding style. In a newer package like `dplyr`, bracketless `if`s are single-line commands.

**Comment by jalvesaq** [comment]
Is it possible to add this feature to `~/.config/nvim/after/queries/r/indents.scm`? I couldn't find the correct way of doing it.

**Comment by jalvesaq** [comment]
Perfect! I agree that `else` without braces might sometimes be ambiguous. So it's better to not support it.
