### ISSUE TITLE
[PHP]: Indentation indent the line above where the cursor is going.

### ISSUE THREAD

**Issue by jasper-at-windswept** [nvim-treesitter/nvim-treesitter#6911]
### Describe the bug

Example
```html
  <form action="index.php" method="post">
    <label for="age">Age:</label> <!-- I PRESS ENTER HERE -->
    <input type="number" name="age"><br>
    <input type="submit" value="Submit">
  </form>
```

```html
  <form action="index.php" method="post">
      <label for="age">Age:</label>
      <!-- CURSOR INDENTS TO HERE BUT ALSO INDENTS ABOVE LINE -->
    <input type="number" name="age"><br>
    <input type="submit" value="Submit">
  </form>
```

### To Reproduce

Lazy Vim Config:

```lua
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
      require("nvim-treesitter.configs").setup({
        ensure_installed = {
          "php",
        },
        highlight = { enable = true },
        indent = { enable = true },
      })
    end,
  },
```

### Expected behavior

Example:
```html
```html
  <form action="index.php" method="post">
    <label for="age">Age:</label>
    <!-- CURSOR SHOULD ONLY INDENT TO SAME AS PREVIOUS TAG -->
    <input type="number" name="age"><br>
    <input type="submit" value="Submit">
  </form>
```
```

### Output of `:checkhealth nvim-treesitter`

```markdown
Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.12.2 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `gcc` executable found. Selected from { "gcc", "cc", "gcc", "clang", "cl", "zig" }
  Version: gcc (GCC) 13.3.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.8.12",
  sysname = "Linux",
  version = "#1-NixOS SMP PREEMPT_DYNAMIC Thu May 30 07:49:53 UTC 2024"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - diff                ✓ . . . ✓
  - gleam               ✓ ✓ ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - gomod               ✓ . . . ✓
  - gosum               ✓ . . . .
  - gowork              ✓ . . . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - nix                 ✓ ✓ ✓ . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - ron                 ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - svelte              ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - xml                 ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓
```
```


### Output of `nvim --version`

```text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info
```

### Additional context

Disabling indent for "php" solves the problem but also removes all indentation entirely.

**Comment by ribru17** [comment]
This is because your `shiftwidth` is 4 but the indentation of this code snippet is 2. `:set shiftwidth=2` (you should make sure `softtabstop` is the same) should fix this

**Comment by jasper-at-windswept** [comment]
@ribru17 
I have set those to 2 but in HTML sections of the file it still indents the line I press enter on aswell as the line the cursor goes to.

Also there is a slight conflict between using 2 for tab since the PHP formatter uses 4 for indentation.

**Comment by ribru17** [comment]
Interesting. Would you mind sharing the entire file, then showing where the indentation happens? Right now I can't reproduce the issue (unless I set the erroneous shiftwidth value)

**Comment by jasper-at-windswept** [comment]
```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>PHP Basics</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>

<body class="flex flex-col h-auto m-0">
  <div id="products-container" class="flex flex-1 flex-wrap gap-6 justify-center"></div>
  <div id="loader" class="w-screen h-screen absolute left-0 top-0 z-10 bg-gray-500 flex justify-center items-center font-bold text-2xl">Loading...</div>
</body>

</html>

<script>
  fetch('fetch.php')
    .then(res => res.json())
    .then(json => {
      if (json.error) {
        document.getElementById('product-container').innerText = json.error;
      } else {
        // You can now manipulate or display the product data here
        console.log(json);
        document.getElementById('loader').remove();
        json.map(product => {
          document.getElementById('products-container').innerHTML += `
            <div class="flex flex-col padding-2 rounded-lg bg-white shadow-lg border gap-2 w-64">
              <img src="${product.image}" alt="${product.title}" class="m-10 rounded-lg max-h-32 object-contain self-center">
              <p class="text-lg font-semibold m-4 font-sans mt-auto">${product.title}</p>
            </div>
          `;
        });
      }
    });
</script>
```

Only when pressing enter inside the <html> tags does it indent as illustrated earlier. 
As a note If i set the filetype to html and then back to php the indentation works fine in the <html> tags.

**Comment by ribru17** [comment]
Thanks! I see what is going on now: the issue is the root `html` tag. It wants to increase the indentation level of everything inside of it (just like any other tag). Right now your head and body tags have the same indentation as the html tag. If you do `gg=G` you will see how it wants to be formatted. I think the solution here is to indent those blocks or to add a query to your config to exclude `html` tags from the normal indentation rules

**Comment by jasper-at-windswept** [comment]
@ribru17 
Thank you very much for that, it works fine now after running `gg=G` but the issue I am now confronted with is that both `pretty_php` and `phpcsfixer` the formatters avaliable for PHP by default indent the HTML so that it causes the issue. And having format on save makes it constantly break.

Do you have any suggestions or should I try to figure this out?

**Comment by ribru17** [comment]
It would be 

> to add a query to your config to exclude `html` tags from the normal indentation rules

So try something like

```scheme
; extends
((element
  (start_tag
    (tag_name) @_tag_name)) @indent.dedent
  (#eq? @_tag_name "html"))
```
in your `~/.config/nvim/queries/html/indents.scm`

**Comment by jasper-at-windswept** [comment]
@ribru17 
I created that file, works perfectly now despite the formatter.
Thank you so much for the help!

**Comment by jasper-at-windswept** [comment]
@ribru17 
I'm having some more issues but this time in my PHP code.

Example:
```php
<?php
$db_server = '172.17.0.2';
$db_user = 'root';
$db_pass = 'wwww';
$db_name = 'shop_db';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (isset($_POST['username']) && isset($_POST['password']) && isset($_POST['email'])) {
        $username = htmlspecialchars($_POST['username']);
        $password = htmlspecialchars($_POST['password']);
        $hashed_password = password_hash($password, PASSWORD_DEFAULT);
        $email = htmlspecialchars($_POST['email']);
        try {
            $conn = mysqli_connect($db_server, $db_user, $db_pass, $db_name);
            if ($conn) {
                echo 'Connected to the database';
                $sql = "INSERT INTO users (username, password, email) VALUES ('$username', '$hashed_password', '$email')";
                try {
                    mysqli_query($conn, $sql);
                } catch (Exception $e) {
                    echo 'Failed to add user to the database: ' . $e->getMessage(); // PRESS ENTER HERE
                }
                echo 'User added to the database';
                mysqli_close($conn);
            }
        } catch (Exception $e) {
            echo 'Connection failed: ' . $e->getMessage();
        }
    }
}
```

Outcome:
```php
<?php
$db_server = '172.17.0.2';
$db_user = 'root';
$db_pass = 'wwww';
$db_name = 'shop_db';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (isset($_POST['username']) && isset($_POST['password']) && isset($_POST['email'])) {
        $username = htmlspecialchars($_POST['username']);
        $password = htmlspecialchars($_POST['password']);
        $hashed_password = password_hash($password, PASSWORD_DEFAULT);
        $email = htmlspecialchars($_POST['email']);
        try {
            $conn = mysqli_connect($db_server, $db_user, $db_pass, $db_name);
            if ($conn) {
                echo 'Connected to the database';
                $sql = "INSERT INTO users (username, password, email) VALUES ('$username', '$hashed_password', '$email')";
                try {
                    mysqli_query($conn, $sql);
                } catch (Exception $e) {
          echo 'Failed to add user to the database: ' . $e->getMessage();
          // INDENTS ABOVE LINE AND THIS ONE BACK TO HERE!
                }
                echo 'User added to the database';
                mysqli_close($conn);
            }
        } catch (Exception $e) {
            echo 'Connection failed: ' . $e->getMessage();
        }
    }
}
?>
```

**Comment by ribru17** [comment]
Able to reproduce with `shiftwidth=2`, assuming you are still using it; this block is using a shiftwidth of 4 hence the weirdness. I would recommend `=ip`ing the block the indent it all to proper 2-space indentation, or just setting your shiftwidth to 4 to match this code

**Comment by jasper-at-windswept** [comment]
@ribru17 
I did `=ip` and it fixed the problem but as soon as I save the file, it doesn't change the positioning of the text but it returns to the previous issue of pushing the text back.

**Comment by ribru17** [comment]
That's a formatting issue then, nothing we can really do on our side; is there a way to configure this? I'd imagine it's annoying for you just to have proper indent width when working with tags, yet have to hit Tab twice when working in actual PHP code

**Comment by jasper-at-windswept** [comment]
@ribru17 
I can append to my formatting callback to run `=ip` after it formats the file. That should in theory make it always work right, do you know how I can call `=ip` from lua?

**Comment by ribru17** [comment]
You could hook `vim.cmd.normal('=ip')` in there, but that would only format the paragraph that the cursor is in. So if you save the file with a cursor in a random place it won't format everything, or maybe anything. You could make another text object to `=` everything, but I think in general that solution is not ideal. Best to try and configure the formatter options to use the same indent width for tags and code, otherwise it will just create problems for other things

**Comment by jasper-at-windswept** [comment]
I just figured out it was `pretty_php` causing the issue and switching to `phpcsfixer` resolved it.

Anyone coming here in the future make sure to use `phpcsfixer` for formatting and add this when using HTML in PHP files.
https://github.com/nvim-treesitter/nvim-treesitter/issues/6911#issuecomment-2227139115

My personal config with these fixes: https://github.com/jasper-at-windswept/neovim

**Comment by jasper-at-windswept** [comment]
@ribru17 
I wanted to ask you about the `indents.scm` because I have the problem that when I am working with pure .html files the indentation is now incorrect because it is formatted correctly.

Can that `indents.scm` only be applied in `.php` file?

**Comment by ribru17** [comment]
Unfortunately not easily (maybe not at all I think). But I'd recommend asking this in the matrix chat, you'll get better answers there and thats generally where these kind of discussions should be had
