### ISSUE TITLE
get_parser_install_dir: "site dir" should be used when "package dir" is readonly

### ISSUE THREAD

**Issue by MattSturgeon** [nvim-treesitter/nvim-treesitter#6912]
### Describe the bug

The doc-comment above `get_parser_install_dir` states:

> If `parser_install_dir` is nil try the package dir of the nvim-treesitter plugin first, followed by the "site" dir from `runtimepath`.

However I cannot find this implemented anywhere.

As noted later in the doc-comment, this causes issues on nix:

> Using only the package dir won't work when the plugin is installed with Nix, since the `/nix/store` is read-only.

I believe the "site dir" should be used when the package dir is readonly.\
Or perhaps if the package dir fails for any reason?

### To Reproduce

1. Install the nix package `pkgs.vimPlugins.nvim-treesitter`
2. Do not configure `parser_install_dir`
3. Observer error:

```
Error detected while processing /nix/store/5y36fg53rjbivbrxih547n5qjlsl46q4-init.lua:
Could not create parser dir ' /nix/store/ak1knrp12ckr8axic4g6ndfifgfmqzpl-vim-pack-dir/pack/m
yNeovimPackages/start/nvim-treesitter/parser ':  Vim:E739: Cannot create directory /nix/store
/ak1knrp12ckr8axic4g6ndfifgfmqzpl-vim-pack-dir/pack/myNeovimPackages/start/nvim-treesitter/pa
rser: read-only file system
Press ENTER or type command to continue
```

### Expected behavior

A graceful fallback to the "site" dir from the rtp.

### Output of `:checkhealth nvim-treesitter`

```markdown
N/A
```

### Output of `nvim --version`

```text
N/A
```

### Additional context

Nixvim issue: https://github.com/nix-community/nixvim/issues/1849
Nixvim PR: https://github.com/nix-community/nixvim/pull/1855

**Comment by clason** [comment]
This is already fixed on the `main` branch (which will become the default branch with 1.0).

**Comment by MattSturgeon** [comment]
> This is already fixed on the `main` branch (which will become the default branch with 1.0).

Thanks for clarifying!

**Comment by clason** [comment]
(In the sense that the documentation is corrected and the default is different. Nix users will still have to customize for their special environment; this is not something we want to support out of the box.)

**Comment by MattSturgeon** [comment]
Looks like in `main` the new default is in `XDG_DATA_HOME`:[^1] https://github.com/nvim-treesitter/nvim-treesitter/blob/7cd8c3fedc580e22ffbb2ca98623af7632a40114/lua/nvim-treesitter/config.lua#L16

This will be read-write on nix so I don't think any special config will be needed on nix.

[^1]: `stdpath('data')` should return `$XDG_DATA_HOME`, or `~/.local/share` if the env var isn't defined.

**Comment by clason** [comment]
Yes, that was the intention. Glad to hear that solves the issue for Nix!
