### ISSUE TITLE
Highlighting is not working for angular

### ISSUE THREAD

**Issue by Ryntak94** [nvim-treesitter/nvim-treesitter#6914]
### Describe the highlighting problem

There seems to be no syntax highlighting for Angular coming from treesitter. (It is working for most other languages).

### Example snippet that causes the problem

<div class="modal-container">
  <section class="ngx-modal" #modal>
    <ng-content></ng-content>
  </section>

  <div class="ngx-overlay" #overlay (click)="onClose()"></div>
</div>

### Tree-sitter parsing result

(program ; [0, 0] - [41, 0] query
  (named_node ; [0, 0] - [40, 19] query
    "(" ; [0, 0] - [0, 1] query
    name: (identifier) ; [0, 1] - [0, 9] query
    (comment) ; [0, 10] - [0, 32] query
    (named_node ; [1, 2] - [40, 18] query
      "(" ; [1, 2] - [1, 3] query
      name: (identifier) ; [1, 3] - [1, 10] query
      (comment) ; [1, 11] - [1, 33] query
      (named_node ; [2, 4] - [7, 30] query
        "(" ; [2, 4] - [2, 5] query
        name: (identifier) ; [2, 5] - [2, 14] query
        (comment) ; [2, 15] - [2, 38] query
        (named_node ; [3, 6] - [3, 16] query
          "(" ; [3, 6] - [3, 7] query
          name: (identifier) ; [3, 7] - [3, 15] query
          ")") ; [3, 15] - [3, 16] query
        (comment) ; [3, 17] - [3, 39] query
        (named_node ; [4, 6] - [7, 29] query
          "(" ; [4, 6] - [4, 7] query
          name: (identifier) ; [4, 7] - [4, 16] query
          (comment) ; [4, 17] - [4, 40] query
          (named_node ; [5, 8] - [5, 24] query
            "(" ; [5, 8] - [5, 9] query
            name: (identifier) ; [5, 9] - [5, 23] query
            ")") ; [5, 23] - [5, 24] query
          (comment) ; [5, 25] - [5, 48] query
          (named_node ; [6, 8] - [7, 28] query
            "(" ; [6, 8] - [6, 9] query
            name: (identifier) ; [6, 9] - [6, 31] query
            (comment) ; [6, 32] - [6, 56] query
            (named_node ; [7, 10] - [7, 27] query
              "(" ; [7, 10] - [7, 11] query
              name: (identifier) ; [7, 11] - [7, 26] query
              ")") ; [7, 26] - [7, 27] query
            ")") ; [7, 27] - [7, 28] query
          ")") ; [7, 28] - [7, 29] query
        ")") ; [7, 29] - [7, 30] query
      (comment) ; [7, 31] - [7, 55] query
      (named_node ; [8, 4] - [23, 20] query
        "(" ; [8, 4] - [8, 5] query
        name: (identifier) ; [8, 5] - [8, 12] query
        (comment) ; [8, 13] - [8, 36] query
        (named_node ; [9, 6] - [16, 28] query
          "(" ; [9, 6] - [9, 7] query
          name: (identifier) ; [9, 7] - [9, 16] query
          (comment) ; [9, 17] - [9, 40] query
          (named_node ; [10, 8] - [10, 18] query
            "(" ; [10, 8] - [10, 9] query
            name: (identifier) ; [10, 9] - [10, 17] query
            ")") ; [10, 17] - [10, 18] query
          (comment) ; [10, 19] - [10, 42] query
          (named_node ; [11, 8] - [14, 31] query
            "(" ; [11, 8] - [11, 9] query
            name: (identifier) ; [11, 9] - [11, 18] query
            (comment) ; [11, 19] - [11, 43] query
            (named_node ; [12, 10] - [12, 26] query
              "(" ; [12, 10] - [12, 11] query
              name: (identifier) ; [12, 11] - [12, 25] query
              ")") ; [12, 25] - [12, 26] query
            (comment) ; [12, 27] - [12, 51] query
            (named_node ; [13, 10] - [14, 30] query
              "(" ; [13, 10] - [13, 11] query
              name: (identifier) ; [13, 11] - [13, 33] query
              (comment) ; [13, 34] - [13, 58] query
              (named_node ; [14, 12] - [14, 29] query
                "(" ; [14, 12] - [14, 13] query
                name: (identifier) ; [14, 13] - [14, 28] query
                ")") ; [14, 28] - [14, 29] query
              ")") ; [14, 29] - [14, 30] query
            ")") ; [14, 30] - [14, 31] query
          (comment) ; [14, 32] - [14, 56] query
          (named_node ; [15, 8] - [16, 27] query
            "(" ; [15, 8] - [15, 9] query
            name: (identifier) ; [15, 9] - [15, 18] query
            (comment) ; [15, 19] - [15, 43] query
            (named_node ; [16, 10] - [16, 26] query
              "(" ; [16, 10] - [16, 11] query
              name: (identifier) ; [16, 11] - [16, 25] query
              ")") ; [16, 25] - [16, 26] query
            ")") ; [16, 26] - [16, 27] query
          ")") ; [16, 27] - [16, 28] query
        (comment) ; [16, 29] - [16, 53] query
        (named_node ; [17, 6] - [21, 22] query
          "(" ; [17, 6] - [17, 7] query
          name: (identifier) ; [17, 7] - [17, 14] query
          (comment) ; [17, 15] - [17, 38] query
          (named_node ; [18, 8] - [19, 21] query
            "(" ; [18, 8] - [18, 9] query
            name: (identifier) ; [18, 9] - [18, 18] query
            (comment) ; [18, 19] - [18, 42] query
            (named_node ; [19, 10] - [19, 20] query
              "(" ; [19, 10] - [19, 11] query
              name: (identifier) ; [19, 11] - [19, 19] query
              ")") ; [19, 19] - [19, 20] query
            ")") ; [19, 20] - [19, 21] query
          (comment) ; [19, 22] - [19, 45] query
          (named_node ; [20, 8] - [21, 21] query
            "(" ; [20, 8] - [20, 9] query
            name: (identifier) ; [20, 9] - [20, 16] query
            (comment) ; [20, 17] - [20, 41] query
            (named_node ; [21, 10] - [21, 20] query
              "(" ; [21, 10] - [21, 11] query
              name: (identifier) ; [21, 11] - [21, 19] query
              ")") ; [21, 19] - [21, 20] query
            ")") ; [21, 20] - [21, 21] query
          ")") ; [21, 21] - [21, 22] query
        (comment) ; [21, 23] - [21, 47] query
        (named_node ; [22, 6] - [23, 19] query
          "(" ; [22, 6] - [22, 7] query
          name: (identifier) ; [22, 7] - [22, 14] query
          (comment) ; [22, 15] - [22, 38] query
          (named_node ; [23, 8] - [23, 18] query
            "(" ; [23, 8] - [23, 9] query
            name: (identifier) ; [23, 9] - [23, 17] query
            ")") ; [23, 17] - [23, 18] query
          ")") ; [23, 18] - [23, 19] query
        ")") ; [23, 19] - [23, 20] query
      (comment) ; [23, 21] - [23, 44] query
      (named_node ; [24, 4] - [38, 20] query
        "(" ; [24, 4] - [24, 5] query
        name: (identifier) ; [24, 5] - [24, 12] query
        (comment) ; [24, 13] - [24, 36] query
        (named_node ; [25, 6] - [36, 32] query
          "(" ; [25, 6] - [25, 7] query
          name: (identifier) ; [25, 7] - [25, 16] query
          (comment) ; [25, 17] - [25, 40] query
          (named_node ; [26, 8] - [26, 18] query
            "(" ; [26, 8] - [26, 9] query
            name: (identifier) ; [26, 9] - [26, 17] query
            ")") ; [26, 17] - [26, 18] query
          (comment) ; [26, 19] - [26, 41] query
          (named_node ; [27, 8] - [30, 31] query
            "(" ; [27, 8] - [27, 9] query
            name: (identifier) ; [27, 9] - [27, 18] query
            (comment) ; [27, 19] - [27, 42] query
            (named_node ; [28, 10] - [28, 26] query
              "(" ; [28, 10] - [28, 11] query
              name: (identifier) ; [28, 11] - [28, 25] query
              ")") ; [28, 25] - [28, 26] query
            (comment) ; [28, 27] - [28, 50] query
            (named_node ; [29, 10] - [30, 30] query
              "(" ; [29, 10] - [29, 11] query
              name: (identifier) ; [29, 11] - [29, 33] query
              (comment) ; [29, 34] - [29, 58] query
              (named_node ; [30, 12] - [30, 29] query
                "(" ; [30, 12] - [30, 13] query
                name: (identifier) ; [30, 13] - [30, 28] query
                ")") ; [30, 28] - [30, 29] query
              ")") ; [30, 29] - [30, 30] query
            ")") ; [30, 30] - [30, 31] query
          (comment) ; [30, 32] - [30, 56] query
          (named_node ; [31, 8] - [32, 27] query
            "(" ; [31, 8] - [31, 9] query
            name: (identifier) ; [31, 9] - [31, 18] query
            (comment) ; [31, 19] - [31, 43] query
            (named_node ; [32, 10] - [32, 26] query
              "(" ; [32, 10] - [32, 11] query
              name: (identifier) ; [32, 11] - [32, 25] query
              ")") ; [32, 25] - [32, 26] query
            ")") ; [32, 26] - [32, 27] query
          (comment) ; [32, 28] - [32, 52] query
          (named_node ; [33, 8] - [36, 31] query
            "(" ; [33, 8] - [33, 9] query
            name: (identifier) ; [33, 9] - [33, 18] query
            (comment) ; [33, 19] - [33, 43] query
            (named_node ; [34, 10] - [34, 26] query
              "(" ; [34, 10] - [34, 11] query
              name: (identifier) ; [34, 11] - [34, 25] query
              ")") ; [34, 25] - [34, 26] query
            (comment) ; [34, 27] - [34, 51] query
            (named_node ; [35, 10] - [36, 30] query
              "(" ; [35, 10] - [35, 11] query
              name: (identifier) ; [35, 11] - [35, 33] query
              (comment) ; [35, 34] - [35, 58] query
              (named_node ; [36, 12] - [36, 29] query
                "(" ; [36, 12] - [36, 13] query
                name: (identifier) ; [36, 13] - [36, 28] query
                ")") ; [36, 28] - [36, 29] query
              ")") ; [36, 29] - [36, 30] query
            ")") ; [36, 30] - [36, 31] query
          ")") ; [36, 31] - [36, 32] query
        (comment) ; [36, 33] - [36, 57] query
        (named_node ; [37, 6] - [38, 19] query
          "(" ; [37, 6] - [37, 7] query
          name: (identifier) ; [37, 7] - [37, 14] query
          (comment) ; [37, 15] - [37, 39] query
          (named_node ; [38, 8] - [38, 18] query
            "(" ; [38, 8] - [38, 9] query
            name: (identifier) ; [38, 9] - [38, 17] query
            ")") ; [38, 17] - [38, 18] query
          ")") ; [38, 18] - [38, 19] query
        ")") ; [38, 19] - [38, 20] query
      (comment) ; [38, 21] - [38, 45] query
      (named_node ; [39, 4] - [40, 17] query
        "(" ; [39, 4] - [39, 5] query
        name: (identifier) ; [39, 5] - [39, 12] query
        (comment) ; [39, 13] - [39, 35] query
        (named_node ; [40, 6] - [40, 16] query
          "(" ; [40, 6] - [40, 7] query
          name: (identifier) ; [40, 7] - [40, 15] query
          ")") ; [40, 15] - [40, 16] query
        ")") ; [40, 16] - [40, 17] query
      ")") ; [40, 17] - [40, 18] query
    ")") ; [40, 18] - [40, 19] query
  (comment)) ; [40, 20] - [40, 42] query

### Example screenshot

I'm using catppuccin.
![image](https://github.com/user-attachments/assets/70191c1d-b581-48d7-882f-f437ecf7e81b)
![image](https://github.com/user-attachments/assets/bfc2e8ff-25d4-4237-b130-92cdb7b16a38)

### Expected behavior

I expect there to be different syntax highlighting than what I appear to be the default neovim syntax highlighting (with a colorscheme)

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.22.6 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v18.19.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 15.0.0 (clang-1500.0.40.1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.2.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000"
} ~

Parser/Features         H L F I J
  - angular             ✓ ✓ ✓ ✓ ✓
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - diff                ✓ . . . ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - gomod               ✓ . . . ✓
  - gosum               ✓ . . . .
  - gowork              ✓ . . . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478
Run "nvim -V1 -v" for more info
```

**Comment by clason** [comment]
> There seems to be no syntax highlighting for Angular coming from treesitter.

There is, but you need to enable it manually with `vim.treesitter.start()`; there is no official filetype for angular files yet, so it's not possible to autostart it.

**Comment by Ryntak94** [comment]
I appreciate the quick response! Should something like this work be working?
![image](https://github.com/user-attachments/assets/add27161-7b6a-4ba2-88db-c0edf710c922)

**Comment by clason** [comment]
No. If you're on Neovim nightly, then the pattern  `angularhtml` should work. Otherwise you need to roll your own detection using `vim.filetype.add`.

**Comment by Ryntak94** [comment]
```
vim.api.nvim_create_autocmd("FileType", {
			pattern = "htmlangular",
			callback = function(args)
				vim.treesitter.start(args.buf, "angular")
				vim.bo[args.buf].syntax = "on"
			end,
		})
```
I moved over to the nightly build and I'm using the [htmlangular pattern](https://github.com/neovim/neovim/blob/eab535e10edd69a2224a10f789bf3c2be6f0ba36/runtime/ftplugin/htmlangular.vim#L4) 
Now I'm seeing angular show up as the active parser for treesitter, but the highlights are the exact same if I run `:TSDisable highlights`
<img width="502" alt="image" src="https://github.com/user-attachments/assets/b6cfa3fe-e046-4ebb-89d7-a690bce740c4">

Do you have any other thoughts?

**Comment by clason** [comment]
Yes, because you set `syntax on`. You don't want to do that.

**Comment by Ryntak94** [comment]
So would you say that there is currently no syntax highlighting for Angular, currently?

**Comment by clason** [comment]
Of course there is, and it looks like it's working for you.

**Comment by Ryntak94** [comment]
You're right, it's just way more similar to the standard neovim syntax highlighting than I expected. I'm seeing somethings that are better now. Thanks for your help!
