### ISSUE TITLE
Type.builtin highlight cannot be changed in C++

### ISSUE THREAD

**Issue by AbriCroco** [nvim-treesitter/nvim-treesitter#6946]
### Describe the highlighting problem

When I change the color assigned to @type.builtin it does not actually change, at least within my c++ program.

### Example snippet that causes the problem

int n;
double x;
char letter;

### Tree-sitter parsing result

(translation_unit ; [0, 0] - [9, 0]
  (comment) ; [0, 0] - [0, 8]
  (function_definition ; [2, 0] - [8, 1]
    type: (primitive_type) ; [2, 0] - [2, 3]
    declarator: (function_declarator ; [2, 4] - [2, 10]
      declarator: (identifier) ; [2, 4] - [2, 8]
      parameters: (parameter_list)) ; [2, 8] - [2, 10]
    body: (compound_statement ; [2, 11] - [8, 1]
      (declaration ; [4, 2] - [4, 12]
        type: (type_identifier) ; [4, 2] - [4, 4]
        declarator: (identifier)) ; [4, 5] - [4, 11]
      (declaration ; [5, 2] - [5, 11]
        type: (primitive_type) ; [5, 2] - [5, 5]
        declarator: (identifier)) ; [5, 6] - [5, 10]
      (return_statement ; [7, 2] - [7, 11]
        (number_literal))))) ; [7, 9] - [7, 10]

### Example screenshot

![Screenshot 2024-07-19 185102](https://github.com/user-attachments/assets/87ef201a-dd23-4256-bb69-93afdfa523f1)
![Screenshot 2024-07-19 185139](https://github.com/user-attachments/assets/04b152cf-af65-491d-972e-7d7b004f9569)
![Screenshot 2024-07-19 185614](https://github.com/user-attachments/assets/3b3c080a-1af0-4a17-892a-bbda481252be)
![Screenshot 2024-07-19 185629](https://github.com/user-attachments/assets/ea22fa2e-a753-4364-89a2-d2314fee3c4b)
![Screenshot 2024-07-19 185638](https://github.com/user-attachments/assets/b8ac2443-7d15-41fe-95f5-9b7fe07f4f05)

### Expected behavior

"int" should be the same color as "main" or "cha"

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v22.4.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `gcc` executable found. Selected from { "gcc" }
  Version: gcc (Rev3, Built by MSYS2 project) 14.1.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.22631",
  sysname = "Windows_NT",
  version = "Windows 11 Pro"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

### Additional context

Hey,

I am a bit of a newbie in coding so I do not rule out an error from me but I feel like the change of color for these highlight groups is pretty straight forward and every other group worked pretty fine as you can see above, I changed, just to test, @type.cpp, @variable.cpp, @function.cpp without problem but @type.builtin.cpp or even just @type.builtin doesn't want to change color, wether I use fg or bg and I am not sure if there is a solution because I can't find one on the internet as this is a very specific topic or if this is a bug...

Of course I found a ticket issue that solved my problem with @function.cpp that was changing color in the :Inspect but not in my code, I just changed the semantic tokens priorities but in this cas @type.builtin.cpp doesn't even change color in the :Inspect.

Anyway, I hope I was concised enough and I welcome any help :)
Thank you very much

**Comment by clason** [comment]
You'll have to ask this at the catpuccin repo; how colors are assigned to captures is completely outside the scope of this plugin.

**Comment by AbriCroco** [comment]
Oh I am sorry then for this question. Thank you very much for your answer :)
