### ISSUE TITLE
Performance Issues with Treesitter Plugin for .pdb Files in Neovim

### ISSUE THREAD

**Issue by vasi786** [nvim-treesitter/nvim-treesitter#7007]
### Describe the bug

When opening a file with a .pdb extension, I experience significantly high UIEnter times, often in the thousands of milliseconds. This is unusual, considering the file is relatively small, with only 52K lines. I have not encountered this issue before, and it seems to have started after a recent update.

I identified that the Treesitter plugin causes a high startup time by systematically disabling plugins. Additionally, editing the file is sluggish; for instance, executing the `ciw` command takes at least a second. However, this issue disappears when I comment out `highlight, enabled=true` in the Treesitter plugin setup.

Interestingly, changing the file extension to something else, like .gro or .txt, resolves the performance issues, and everything runs smoothly, but does not resolve the high startuptime issue. This problem appears to be specifically related to the .pdb file format.

I have verified that the health of nvim-treesitter, and it is good and all language parsers are up to date, so I am unsure what is causing this specific behavior with .pdb files.

### To Reproduce

1. Open the pdb file
2. :Lazy -> Profile (to see the UIEnter time)

### Expected behavior

The UIEnter time should be very small

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.12.2 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `/opt/compiler/gcc/9.5.0/bin/gcc` executable found. Selected from { "/opt/compiler/gcc/9.5.0/bin/gcc", "cc", "gcc", "clang", "cl", "zig" }
  Version: gcc (GCC) 9.5.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.4.280-1.el8.elrepo.x86_64",
  sysname = "Linux",
  version = "#1 SMP Thu Jul 18 18:32:59 EDT 2024"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - csv                 ✓ . . . .
  - diff                ✓ . . . ✓
  - dockerfile          ✓ . . . ✓
  - gitignore           ✓ . . . ✓
  - graphql             ✓ . . ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - kdl                 ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - luap                ✓ . . . .
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - perl                ✓ . ✓ . ✓
  - prisma              ✓ . ✓ . ✓
  - prolog              ✓ . ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - rust                ✓ ✓ ✓ ✓ ✓
  - svelte              ✓ ✓ ✓ ✓ ✓
  - tcl                 ✓ . ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.1
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

### Additional context

[Download the file here - please change the extension to .pdb to replicate the issue](https://github.com/user-attachments/files/16468717/test.txt)

# SCREENSHOTS 

![check_health_treesitter](https://github.com/user-attachments/assets/b059433b-481c-4b09-b6a3-0de6b7441b90)
![Default_very_slow_UI_ENTER_1400ms](https://github.com/user-attachments/assets/43189474-edc9-43ea-8f8c-e3d5e63d5037)
![Default_very_slow_UI_ENTER_1400ms-LAZYProfile](https://github.com/user-attachments/assets/078ec5f4-e2c3-4dd8-a3a3-a306a2f2d682)

Here is my configuration for treesitter

```
return {
  "nvim-treesitter/nvim-treesitter",
  -- event = { "BufReadPre", "BufNewFile" },
  event = "VeryLazy",
  dependencies = {
    "windwp/nvim-ts-autotag",
  },
  config = function()
    -- import nvim-treesitter plugin
    local treesitter = require("nvim-treesitter.configs")

    -- configure treesitter
    treesitter.setup({ -- enable syntax highlighting
      highlight = {
        enable = true,
      },
      -- enable indentation
      indent = { enable = true },
      -- -- enable autotagging (w/ nvim-ts-autotag plugin)
      autotag = {
        enable = true,
      },
      ensure_installed = {
        "bash",
        "lua",
        "c",
        "cpp",
        "rust",
        "python",
      },
      auto_install = true,
      -- ensure these language parsers are installed
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = "<C-space>",
          node_incremental = "<C-space>",
          scope_incremental = false,
          node_decremental = "<bs>",
        },
      },
    })
  end,
}


```

**Comment by clason** [comment]
Don't install the `prolog` parser then. `auto_install` is _not_ recommended.

**Comment by clason** [comment]
(I don't see any slowdown for that file, for the record.)

**Comment by clason** [comment]
You can also open an issue at the parser repo; that's where performance issues would have to be fixed.

**Comment by vasi786** [comment]
Perfect. Uninstalling `prolog` fixed it. I have no idea why I needed that. I also removed `auto_install`. Thanks for the help. 

Could you guide me to the repo of the `prolog` parser? I will report it there.

**Comment by clason** [comment]
Looking further into this, the parser (and the language?) do not recognize floating point numbers. Either these are not part of the language (then the file is broken, so all bets are off), or they need to be added to the grammar.

The repo is linked from the README, but that's a mirror IIRC. The actual project lives at https://codeberg.org/foxy/tree-sitter-prolog.

**Comment by clason** [comment]
@foxyseta

**Comment by clason** [comment]
>  if the file is actually valid PROLOG (which it might not be!)

Yeah, looks like this file has nothing to do with Prolog, so it's not a parser issue either. The actual issue is filetype misdetection by Vim (from which Neovim takes the detection logic), so if you care about this, you should report this there. (In a nutshell, if `pdb` is a valid extension for multiple files, the check needs to look at the file contents to decide which it is. Nobody has contributed such a check for the `pdb` extension.)

**Comment by clason** [comment]
For the record, the PDB format is explained here: https://en.wikipedia.org/wiki/Protein_Data_Bank_(file_format)

It looks like it'd be enough to check if the first line contains (starts with?) `HEADER`, so that should be fairly easy to implement.

**Comment by foxyseta** [comment]
Glad to hear my parser is in the clear :)

**Comment by clason** [comment]
Yeah, sorry for the false alarm.

**Comment by foxyseta** [comment]
No problem!
