### ISSUE TITLE
Markdown heading continues to next line

### ISSUE THREAD

**Issue by JosefLitos** [nvim-treesitter/nvim-treesitter#7016]
### Describe the highlighting problem

When a heading appears as a list item, its highlight continues until the next item:
![obrazek](https://github.com/user-attachments/assets/296442f2-b00a-45aa-bbbd-e7cb3e5b604d)
You can see the underline continuing from the space before the heading itself until the beginning of the next list item. But when I select the `heading_content`, I see truly only the heading text highlighted, so probably that should have been used for setting the highlight group.

### Example snippet that causes the problem

```markdown
- ### any title
  - this stops the title highlight continuation
```

### Tree-sitter parsing result

```scm
(document ; [0, 0] - [2, 0]
  (section ; [0, 0] - [2, 0]
    (list ; [0, 0] - [2, 0]
      (list_item ; [0, 0] - [2, 0]
        (list_marker_minus) ; [0, 0] - [0, 2]
        (section ; [0, 2] - [2, 0]
          (atx_heading ; [0, 2] - [1, 2]
            (atx_h3_marker) ; [0, 2] - [0, 5]
            heading_content: (inline ; [0, 6] - [0, 15]
              (inline)) ; [0, 6] - [0, 15]
            (block_continuation)) ; [1, 0] - [1, 2]
          (list ; [1, 2] - [2, 0]
            (list_item ; [1, 2] - [2, 0]
              (list_marker_minus) ; [1, 2] - [1, 4]
              (paragraph ; [1, 4] - [2, 0]
                (inline ; [1, 4] - [1, 47]
                  (inline)))))))))) ; [1, 4] - [1, 47]
```

### Example screenshot

![obrazek](https://github.com/user-attachments/assets/609c4bd6-95ef-433c-832e-7aca68b25414)

### Expected behavior

The title, and only the title, gets highlighted with the corresponding level of `@markup.heading`

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v22.5.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 14.2.1 20240802
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.6.44-2-lts",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Sat, 03 Aug 2024 18:10:33 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - bibtex              ✓ . ✓ ✓ ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - c_sharp             ✓ ✓ ✓ . ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - dockerfile          ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - groovy              ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - json5               ✓ . . . ✓
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - kotlin              ✓ ✓ ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - racket              ✓ . ✓ . ✓
  - regex               ✓ . . . .
  - rust                ✓ ✓ ✓ ✓ ✓
  - scheme              ✓ . ✓ . ✓
  - sql                 ✓ . . ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - vue                 ✓ . ✓ ✓ ✓
  - xml                 ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1720049189
Run "nvim -V1 -v" for more info
```

**Comment by clason** [comment]
And it works fine if you don't put the heading into a list item, which I'm not sure is allowed by the grammar -- can you point me to where in the specification that situation is covered?

**Comment by JosefLitos** [comment]
No, not really. But I would think that the `heading_content` could be somehow matched together with the marker to get the correct part of the text. Is it not possible?

**Comment by JosefLitos** [comment]
In my testing doing:
```scm
(atx_heading
  (atx_h1_marker) (inline) @markup.heading.1)
```
instead of
```scm
(atx_heading
  (atx_h1_marker)) @markup.heading.1
```

fixes the issue.

**Comment by clason** [comment]
_This_ issue, but I think this would create problems in other situations.

**Comment by JosefLitos** [comment]
as far as the the official examples of headings go, all seem just fine:
![obrazek](https://github.com/user-attachments/assets/71ce4427-5e9f-4c0f-82c9-25ac145afedb)
Links and other elements inside the titles arent an issue, because they're inside the `inline` block. I am not aware of any other unusual forms of declaring headings other than mine. And since that one works well too I can't think of something that would get broken by marking the actual heading instead of all the text around it that shouldn't have been marked in the first place.

**Comment by clason** [comment]
Does this cover the markers as well? They should be captured, too.

**Comment by JosefLitos** [comment]
Oh, ok. That wouldn't be possible then. I forgot I added back for myself the separate match that used to be there for markers, so they were done separately. But no, this solution doesn't include the markers.

**Comment by JosefLitos** [comment]
Is there a way I can override those 6 query rules without copying the entire file? Extending the file doesn't work, because that only adds new rules.

**Comment by clason** [comment]
Sorry, no; it's impossible to disable individual patterns. I'm open for fixes, but they have to be blanket improvements and broadly tested (and ideally come with extended tests).

(For example, it would be possible to capture the `heading_content` and the marker separately -- but that would mean that any background would not apply to the whole line, which may be a regression to others.)
