### ISSUE TITLE
This code breaks highlighting for shell script

### ISSUE THREAD

**Issue by weilbith** [nvim-treesitter/nvim-treesitter#702]
**Describe the bug**
Here a screenshot that shows the code itself, but also the applied highlighting. As you can see, from the line including the `echo` command on, the highlighting is stucked. It never recovers from there, no matter how much code follows.

![screenshot_led_001](https://user-images.githubusercontent.com/12543647/100235391-a77d3800-2f2c-11eb-9867-e1b5ffa3fbfe.png)

**To Reproduce**
- setup treesitter with at least these settings:
```lua
require'nvim-treesitter.configs'.setup {
   ensure_installed = {
    "bash",
  },
  highlight = {
    enable = true,
  },
}
```
- edit a new file and make sure its filetype is `sh`
- write the code of the screenshot to the file

**Expected behavior**
Highlighting should just work

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## c parser healthcheck
  - OK: c parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for c
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## java parser healthcheck
  - OK: java parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `folds.scm` query found for java
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for java
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## python parser healthcheck
  - OK: python parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for python
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## lua parser healthcheck
  - OK: lua parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

## go parser healthcheck
  - OK: go parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for go
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## json parser healthcheck
  - OK: json parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for json
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `folds.scm` query found for json
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for json
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## jsdoc parser healthcheck
  - OK: jsdoc parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for jsdoc
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `folds.scm` query found for jsdoc
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for jsdoc
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## html parser healthcheck
  - OK: html parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `folds.scm` query found for html
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for html
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## typescript parser healthcheck
  - OK: typescript parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for typescript
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## cpp parser healthcheck
  - OK: cpp parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for cpp
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## toml parser healthcheck
  - OK: toml parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `folds.scm` query found for toml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for toml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## rust parser healthcheck
  - OK: rust parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `folds.scm` query found for rust
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for rust
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## bash parser healthcheck
  - OK: bash parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `folds.scm` query found for bash
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for bash
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## rst parser healthcheck
  - OK: rst parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `folds.scm` query found for rst
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for rst
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## css parser healthcheck
  - OK: css parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for css
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `folds.scm` query found for css
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for css
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## javascript parser healthcheck
  - OK: javascript parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for javascript
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## c_sharp parser healthcheck
  - OK: c_sharp parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for c_sharp
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `folds.scm` query found for c_sharp
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for c_sharp
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-834-g7c4f34966
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/thore/.cache/pikaur/build/neovim-git/src/build/config -I/home/thore/.cache/pikaur/build/neovim-git/src/neovim-git/src -I/usr/include -I/home/thore/.cache/pikaur/build/neovim-git/src/build/src/nvim/auto -I/home/thore/.cache/pikaur/build/neovim-git/src/build/include
Compiled by thore@kautz

Features: +acl +iconv +tui
```

**Comment by vigoux** [comment]
Can you show the tree that this content produces ?

**Comment by weilbith** [comment]
I'm sorry, but could you guide me how to do so? On the rush I did not saw a promising command that starts with `TS` for that.

**Comment by kyazdani42** [comment]
https://github.com/nvim-treesitter/playground

**Comment by weilbith** [comment]
Well, this opens an empty window for me. When I hit `R` up refresh I get this error:
`E5108: Error executing lua ...r/playground/lua/nvim-treesitter-playground/internal.lua:474: attempt to index local 'results' (a nil value)`

**Comment by stsewd** [comment]
For completeness, this is the code

```
file_list = (
  foo
  bar
)

VAR="(${(j:|:)file_list})"

echo 'anything'
ls -la
cd /tmp
```

Looks like that produces an  syntax error

```
command [0, 0] - [0, 11]
  name: command_name [0, 0] - [0, 9]
    word [0, 0] - [0, 9]
  argument: word [0, 10] - [0, 11]
subshell [0, 12] - [3, 1]
  command [1, 2] - [1, 5]
    name: command_name [1, 2] - [1, 5]
      word [1, 2] - [1, 5]
  command [2, 2] - [2, 5]
    name: command_name [2, 2] - [2, 5]
      word [2, 2] - [2, 5]
pipeline [5, 0] - [10, 0]
  variable_assignment [5, 0] - [5, 11]
    name: variable_name [5, 0] - [5, 3]
    ERROR [5, 4] - [5, 9]
    value: word [5, 9] - [5, 11]
  command [5, 12] - [10, 0]
    name: command_name [5, 12] - [10, 0]
      concatenation [5, 12] - [10, 0]
        word [5, 12] - [5, 13]
        ERROR [5, 13] - [5, 14]
        word [5, 14] - [5, 23]
        ERROR [5, 24] - [5, 25]
        string [5, 25] - [10, 0]
```


This should be reported to the bash parser

**Comment by stsewd** [comment]
The failed expression is `"(${(a:b:)})"`, please report that upstream https://github.com/tree-sitter/tree-sitter-bash/issues
