### ISSUE TITLE
endwise for lua & ruby (and likely others)

### ISSUE THREAD

**Issue by Julian** [nvim-treesitter/nvim-treesitter#703]
**Describe the bug**
[vim-endwise](https://github.com/tpope/vim-endwise/) support seems to not work (i.e. not produce automatic `end`s) for at least lua and ruby files. It seems to properly work for vimscript though. 

(I'm not sure whether this is considered a bug or not since I don't know whether syntax group names etc. are expected to be preserved over the built-in syntax files? Or whether this belongs here in the first place. Obviously apologies if not but filing it here in case it turns out to be design-related.)

**To Reproduce**
After installing `vim-endwise`, for all 3 languages, write the equivalent of `function foo()<CR>`, and only in vimscript is an `endfunction` inserted.

**Expected behavior**
Auto-ends inserted for all 3.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim-treesitter#check
========================================================================
  - ERROR: Failed to run healthcheck for "nvim-treesitter" plugin. Exception:
    function health#check, line 21
    Vim(call):E107: Missing parentheses: health#nvim-treesitter#check()

</code>
</details>

(not sure what that means / why the health check isn't working itself?)

**Output of `nvim --version`**
```
⊙  nvim --version                                                                                                                                                                               julian@Airm
NVIM v0.5.0-866-g2d36b62ed-dirty
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /Library/Developer/CommandLineTools/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/Users/julian/Development/neovim/build/config -I/Users/julian/Development/neovim/src -I/Users/julian/Development/neovim/.deps/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include -I/opt/homebrew/opt/gettext/include -I/Users/julian/Development/neovim/build/src/nvim/auto -I/Users/julian/Development/neovim/build/include
Compiled by julian@Airm.lan

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/nvim/share/nvim"

Run :checkhealth for more info


```

**Comment by kyazdani42** [comment]
i believe this kind of issue is related to treesitter setting off syntax. @vigoux correct me if i'm wrong, but i believe indentation is also broken because of that.

**Comment by vigoux** [comment]
I think this can be related.
But I don't see any way to fix this just yet.
This should be kept here for the record.

**Comment by theHamsta** [comment]
Tracking issue for syntax awesomeness we break?

**Comment by bluz71** [comment]
Just hit this myself. 

Hopefully something can be worked out to bring endwise (or a Neovim Treesitter equivalent) back into the mix. It is really really useful for programming Ruby.

Cheers.

**Comment by cloggier** [comment]
Perhaps https://github.com/windwp/nvim-ts-autotag could be extended?

**Comment by bluz71** [comment]
Yes, a tree sitter aware plugin, like ts-autotag, will likely need to be the solution for this issue.

**Comment by wodesuck** [comment]
```lua
require('nvim-treesitter.configs').setup {
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = true,
  },
}
```

Enable `additional_vim_regex_highlighting` and `vim-endwise` will work.

**Comment by bluz71** [comment]
That will work, but has a major issue.

Both Treesitter and regex highlighting will run at the same time which results in much higher CPU usage, especially on slower machines.

One of the benefits of Treesitter is speed, the above setting will negate that.

**Comment by caifara** [comment]
This may be a solution: https://github.com/windwp/nvim-autopairs/blob/master/doc/endwise.md

I didn't investigate much further though.

**Comment by theHamsta** [comment]
This is not planned for nvim-treesitter. Plugins need to support this functionality for syntax or tree-sitter separatly
