### ISSUE TITLE
Selecting inside / within a node

### ISSUE THREAD

**Issue by Sushisource** [nvim-treesitter/nvim-treesitter#7044]
I was trying out https://github.com/folke/flash.nvim and it's treesitter-based search mode. Lovely way to navigate, however I was surprised to find that after quite a lot of searching I couldn't find any way to do something that feels very desirable / intuitive:

Say I'm in a language with braces (Rust as an example here) and I've got something like:

```rust
fn main() {
    // code here, etc
}
```

Using flash's search (or, even ignoring flash, say I'm inside main and I use nvim-treesitter's built-in expand scope), I then want to select the _contents_ of the main function. This ends up selecting the function's body _including_ the braces on both ends. It makes sense, that's the node, but very often what you really want is to _exclude_ the delimiters themselves.

It'd be really nice to have some way to make the selection this way, plus adjust an existing selection to include or exclude delimiters. If I'm missing something and there's already a good way to do this, would love to know how. Thanks!

**Comment by ribru17** [comment]
Having you checked out [nvim-treesitter-textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects)? That repo handles this sort of thing

**Comment by clason** [comment]
(The "incremental-selection" module is deprecated and will be removed in 1.0.)
