### ISSUE TITLE
nvim +PlugUpdate does not update treesitter (results in errors)

### ISSUE THREAD

**Issue by maitra** [nvim-treesitter/nvim-treesitter#7047]
### Describe the bug

I have nvim-treesitter installed. I try to update it using nvim +PlugUpdate and get the following:

```
x nvim-treesitter:
    remote: Enumerating objects: 1899, done.        
    remote: Counting objects: 100% (1899/1899), done.        
    remote: Compressing objects: 100% (787/787), done.        
    remote: Total 1770 (delta 1068), reused 1510 (delta 922), pack-reused 0 (from 0)        
    Receiving objects: 100% (1770/1770), 465.09 KiB | 1.73 MiB/s, done.
    Resolving deltas: 100% (1068/1068), completed with 78 local objects.
    fatal: bad object refs/remotes/origin/feat/version
    error: https://github.com/nvim-treesitter/nvim-treesitter.git did not send all necessary objects

```
I am not quite sure what to do here.

### To Reproduce

See the above. Happy to test. 

### Expected behavior

Expected to update without error.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.22.5 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.12.2 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 14.2.1 20240801 (Red Hat 14.2.1-1)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.9.9-200.fc40.x86_64",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Thu Jul 11 19:29:01 UTC 2024"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - r                   ✓ ✓ . ✓ ✓
  - rnoweb              ✓ . ✓ . ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
v0.10.1
```

### Additional context

x nvim-treesitter:
    remote: Enumerating objects: 1899, done.        
    remote: Counting objects: 100% (1899/1899), done.        
    remote: Compressing objects: 100% (787/787), done.        
    remote: Total 1770 (delta 1068), reused 1510 (delta 922), pack-reused 0 (from 0)        
    Receiving objects: 100% (1770/1770), 465.09 KiB | 1.73 MiB/s, done.
    Resolving deltas: 100% (1068/1068), completed with 78 local objects.
    fatal: bad object refs/remotes/origin/feat/version
    error: https://github.com/nvim-treesitter/nvim-treesitter.git did not send all necessary objects

**Comment by clason** [comment]
Sounds like network flake. Remove the checkout completely and try again.

**Comment by maitra** [comment]
How do I do that? Sorry. Btw, this has happened to me for the past day.

**Comment by clason** [comment]
I don't know where you ask vim-plug to install your plugins. Find that folder and remove the `nvim-treesitter` (or the whole folder) and install the plugin(s) again.

**Comment by maitra** [comment]
OK, got it! It did install now, thanks!
