### ISSUE TITLE
[Feature] Automatically install dependent parsers

### ISSUE THREAD

**Issue by davidroeca** [nvim-treesitter/nvim-treesitter#708]
**Is your feature request related to a problem? Please describe.**

Tree-sitter failed to parse some of my typescript files with the error `no parser for 'jsdoc' language`. `:TSInstall jsdoc`, or specifying it as a parser via `ensure_installed` fixes this. To me, this indicates that the `typescript` parser relies on the `jsdoc` parser. 

**Describe the solution you'd like**

Make it easier to ensure that dependent parsers are installed when a parser is installed. In the above case, it would be nice to ensure that the plugin installs `jsdoc` as well.

**Describe alternatives you've considered**

Here are a few:

* Document which parsers rely on one another. Might be annoying to maintain if these dependencies evolve.

* Alternatively, allow those parsers to fail (if not installed) without crashing the other language highlights. For example, when `graphql` gets added, will the tree-sitter plugin crash if I open a typescript file with a graphql query in it, if I haven't added the `graphql` parser?

**Additional context**

Fortunately, highlighting can fall back to the typescript-vim plugin, but one main issue is that for some reason when I jump to definition, I have to reset `:set filetype=typescript` for the fallback highlights to render in the new buffer.

**Comment by vigoux** [comment]
Hi, thanks for reporting.
This is indeed an upstream issue, I'll try to fix that as soon a possible.

**Comment by vigoux** [comment]
The solution would be on two sides :

- Avoid crashing when injecting a language and the parser is not present (upstream).
- Install the dependencies when installing parsers (on our side).

**Comment by vigoux** [comment]
Okay, this should have been at least partially fixed upstream, shall we close this ?

**Comment by davidroeca** [comment]
Yep - I tried this out and it seems to be working (the first bullet, not the second)
