### ISSUE TITLE
Rust documentation comments (`///` and `//!`) get incorrectly highlighted

### ISSUE THREAD

**Issue by mawkler** [nvim-treesitter/nvim-treesitter#7133]
### Describe the highlighting problem

The last `/` in Rust comments recently started getting highlighted as "operator" instead of comment/documentation. This does _not_ seem to be an issue with treesitter. See this issue https://github.com/tree-sitter/tree-sitter-rust/issues/236:

> The latest release (0.23) broke the parsing of doc-comments. Here's an example of how it looks like right now:
>
> ![image](https://private-user-images.githubusercontent.com/40841816/365356219-7ac85986-ea39-4fe1-98cc-30a381fcac7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTQyODQsIm5iZiI6MTcyNTk1Mzk4NCwicGF0aCI6Ii80MDg0MTgxNi8zNjUzNTYyMTktN2FjODU5ODYtZWEzOS00ZmUxLTk4Y2MtMzBhMzgxZmNhYzdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA3Mzk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0NzdmNzMzMzU0YTFmOTEwYTlmMTc4YzQwMjBhNTdiOWQzZGQwZDIyMmQ0NWNlYmNjNTVhM2I3N2UwMGIyMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VEdYpnoPpvJ3C3fK3EDXZdIv2rRpxsW3Gzmm_fjLf78)
>
> It should look like the following (as in release 0.21.2):
>
> ![image](https://private-user-images.githubusercontent.com/40841816/365356244-80c7e815-4018-4c4e-8a5b-b1d5bd09b37d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTQyODQsIm5iZiI6MTcyNTk1Mzk4NCwicGF0aCI6Ii80MDg0MTgxNi8zNjUzNTYyNDQtODBjN2U4MTUtNDAxOC00YzRlLThhNWItYjFkNWJkMDliMzdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDA3Mzk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwYzg3MjE0MTM3ZjU0YmZjZTM5NTJjZjNlM2QzOTdmNmYzZjNkNjg5YzgxOTM5MjIyMzQ4ZjM5ZjMyY2FhMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KAYZAyV0Rwgy7pAdHmVTx0QbyDZ1qlWEHfFlVYrxe_s)
>
> I don't know the specific commit that broke this. However, the issue is present from commit `7de6a3bc1ba213424c137f134d2872975b3b7fbe` forwards.
>
> I'm using neovim (v0.10.0) with `nvim-treesitter` plugin.
>
> Here's the tree of the wrongly parsed part:
>
> ```scheme
> (source_file ; [0, 0] - [7, 0]
>   (line_comment ; [0, 0] - [1, 0]
>     outer: (outer_doc_comment_marker) ; [0, 2] - [0, 3]
>     doc: (doc_comment)) ; [0, 3] - [1, 0]
>   (function_item ; [1, 0] - [3, 1]
>     name: (identifier) ; [1, 3] - [1, 7]
>     parameters: (parameters) ; [1, 7] - [1, 9]
>     body: (block ; [1, 10] - [3, 1]
>       (line_comment ; [2, 4] - [3, 0]
>         inner: (inner_doc_comment_marker) ; [2, 6] - [2, 7]
>         doc: (doc_comment))))) ; [2, 7] - [3, 0]
> ```
>
> ### Steps To Reproduce/Bad Parse Tree
>
> 1. Open a Rust file.
> 2. Find (or create) a doc comment
> 3. The `///` and `//!` symbols of doc comments are parsed wrong, with third character parsed as operator (I think?)
>
> ### Expected Behavior/Parse Tree
>
> The `///` symbol should be parsed as one symbol.
>
> ### Repro
>
> ```rust
> /// This is a doc comment
> fn main() {
>     //! this is inside function comment
> }
> ```

### Example snippet that causes the problem

See above

### Tree-sitter parsing result

See above

### Example screenshot

See above

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.23.0 (12fb31826b8469cc7b9788e72bceee5af1cf0977) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v22.7.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 14.2.1 20240805
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.10.7-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Thu, 29 Aug 2024 16:48:57 +0000"
}

Parser/Features         H L F I J
  ...
  - rust                ✓ ✓ ✓ ✓ ✓
```

### Output of `nvim --version`

```text
NVIM v0.11.0-dev-230+g0231265c8
Build type: RelWithDebInfo
LuaJIT 2.1.1716656478
```

**Comment by clason** [comment]
Looks like the queries need to be adapted to a breaking (but not covered by highlight tests) grammar change. PR welcome!

@amaanq
