### ISSUE TITLE
Correction for vim-plug on Installation Wiki page

### ISSUE THREAD

**Issue by paddor** [nvim-treesitter/nvim-treesitter#7178]
The second line contains a syntax error and should instead be:
```vim
lua require'nvim-treesitter.configs'.setup{highlight={enable=true}}  " At the bottom of your init.vim, keep all configs on one line
```

**Comment by clason** [comment]
What's the error? I don't see any difference.

**Comment by paddor** [comment]
Sorry, copy paste error.

This works for me:
```vim
lua require('nvim-treesitter.configs').setup{highlight={enable=true}}
```

**Comment by clason** [comment]
That is syntactically equivalent.

**Comment by paddor** [comment]
Hm, you're right. Now it works without parens as well. Must have been another issue then. Never mind
