### ISSUE TITLE
nvim/lazyvim having treesitter installations issues in Ubuntu 24.04 

### ISSUE THREAD

**Issue by dev4openid** [nvim-treesitter/nvim-treesitter#7179]
### Describe the bug

I am in process of learning vim (so apologies if I missed something)

For some reason, treesitter fails to compile properly on lazyvim installation

My environment is as follows:
Ubuntu 24.04
NVIM v0.11.0-dev
gcc (Ubuntu 14-20240412-0ubuntu1) 14.0.1 20240412 (experimental) [master r14-9935-g67e1433a94f]
g++ (Ubuntu 13.2.0-23ubuntu4) 13.2.0

I originally installed nvim via sudo apt install nvim

I am following the recommended installation guide:
https://lazyvim-ambitious-devs.phillips.codes/course/chapter-1/

After install Lazyvim as per the guide nvim starts, so far so good EXCEPT for tree-sitter

Also, I have run healthcheck below and have run addition test as below

### To Reproduce

AFTER 
WHEN at cli I execute nvim command
THEN several errors appear

Errors captured:
Error 1:
/home/linuxbrew/.linuxbrew/bin/ld: /usr/libexec/gcc/x86_64-linux-gnu/14/liblto_plugin.so: error loading plugin: /home/linuxbrew/.linuxbrew/lib/libc.so.6: version `GLIBC_2.38' not found (required by /usr/libexec/gcc/x86_64-linux-gnu/14/liblto_plugin.so)
collect2: error: ld returned 1 exit status

Error 2:
nvim-treesitter[yaml]: Error during compilation

### Expected behavior

As per the guide I except Lazyvim to be installed without any issues and then continue the guide

### Output of `:checkhealth nvim-treesitter`

```markdown
WHEN checkhealth is run the report is generated:
>>>==========================================================================
lazy: require("lazy.health").check()

lazy.nvim ~
- {lazy.nvim} version `11.14.1`
- OK {git} `version 2.46.1`
- OK no existing packages found by other package managers
- OK packer_compiled.lua not found

luarocks ~
- checking `luarocks` installation
- OK no plugins require `luarocks`, so you can ignore any warnings below
- OK {luarocks} `/home/linuxbrew/.linuxbrew/bin/luarocks 3.11.1`
- WARNING `lua` version `5.1` needed, but found `Lua 5.4.7  Copyright (C) 1994-2024 Lua.org, PUC-Rio`
- WARNING {lua5.1} or {lua} or {lua-5.1} version `5.1` not installed

==============================================================================
lazyvim: require("lazyvim.health").check()

LazyVim ~
- OK Using Neovim >= 0.9.0
- OK `git` is installed
- OK `rg` is installed
- OK `fdfind` is installed
- OK `lazygit` is installed

==============================================================================
noice: require("noice.health").check()

noice.nvim ~
- OK **Neovim** >= 0.9.0
- OK You're using a GUI that should work ok
- OK **vim.go.lazyredraw** is not enabled
- OK **nvim-notify** is installed
- WARNING **TreeSitter vim** parser is not installed. Highlighting of the cmdline for vim might be broken
- WARNING **TreeSitter regex** parser is not installed. Highlighting of the cmdline for regex might be broken
- WARNING **TreeSitter lua** parser is not installed. Highlighting of the cmdline for lua might be broken
- WARNING **TreeSitter bash** parser is not installed. Highlighting of the cmdline for bash might be broken
- WARNING **TreeSitter markdown** parser is not installed. Highlighting of the cmdline for markdown might be broken
- WARNING **TreeSitter markdown_inline** parser is not installed. Highlighting of the cmdline for markdown_inline might be broken
- OK `vim.notify` is set to **Noice**
- OK `vim.lsp.handlers["textDocument/hover"]` is set to **Noice**
- OK `vim.lsp.handlers["textDocument/signatureHelp"]` is set to **Noice**
- OK `vim.lsp.handlers["window/showMessage"]` is set to **Noice**
- OK `vim.lsp.util.convert_input_to_markdown_lines` is set to **Noice**
- OK `vim.lsp.util.stylize_markdown` is set to **Noice**

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.23.0 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v22.9.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 14-20240412-0ubuntu1) 14.0.1 20240412 (experimental) [master r14-9935-g67e1433a94f]
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.11.0-061100-generic",
  sysname = "Linux",
  version = "#202409151536 SMP PREEMPT_DYNAMIC Sun Sep 15 16:01:12 UTC 2024"
} ~

Parser/Features         H L F I J

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

==============================================================================
vim.deprecated: require("vim.deprecated.health").check()

- OK No deprecated functions detected

==============================================================================
vim.health: require("vim.health.health").check()

Configuration ~
- OK no issues found

Runtime ~
- OK $VIMRUNTIME: /usr/share/nvim/runtime

Performance ~
- OK Build type: RelWithDebInfo

Remote Plugins ~
- OK Up to date

terminal ~
- key_backspace (kbs) terminfo entry: `key_backspace=\177`
- key_dc (kdch1) terminfo entry: `key_dc=\E[3~`
- $VTE_VERSION="7600"
- $COLORTERM="truecolor"

External Tools ~
- OK ripgrep 14.1.1 (/home/linuxbrew/.linuxbrew/bin/rg)

==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: /home/briand/.local/state/nvim/lsp.log
- Log size: 0 KB

vim.lsp: Active Clients ~
- No active clients

vim.lsp: File Watcher ~
- file watching "(workspace/didChangeWatchedFiles)" disabled on all clients

vim.lsp: Position Encodings ~
- No active clients

==============================================================================
vim.provider: require("vim.provider.health").check()

Clipboard (optional) ~
- OK Clipboard tool found: xsel

Node.js provider (optional) ~
- Node.js: v22.9.0
  
- Nvim node.js host: /home/briand/.nvm/versions/node/v22.9.0/lib/node_modules/neovim/bin/cli.js
- OK Latest "neovim" npm/yarn/pnpm package is installed: 5.2.1
  

Perl provider (optional) ~
- WARNING "Neovim::Ext" cpan module is not installed
  - ADVICE:
    - See :help |provider-perl| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim
- WARNING No usable perl executable found

Python 3 provider (optional) ~
- WARNING No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
- WARNING Could not load Python :
  /home/linuxbrew/.linuxbrew/bin/python3 does not have the "neovim" module.
  /home/linuxbrew/.linuxbrew/bin/python3.12 does not have the "neovim" module.
  /home/linuxbrew/.linuxbrew/bin/python3.11 does not have the "neovim" module.
  /home/linuxbrew/.linuxbrew/bin/python3.10 does not have the "neovim" module.
  /home/linuxbrew/.linuxbrew/bin/python3.9 does not have the "neovim" module.
  python3.8 not found in search path or not executable.
  python3.7 not found in search path or not executable.
  /home/linuxbrew/.linuxbrew/bin/python does not have the "neovim" module.
  - ADVICE:
    - See :help |provider-python| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_python3_provider = 0` to your init.vim
- Executable: Not found

Python virtualenv ~
- OK no $VIRTUAL_ENV

Ruby provider (optional) ~
- Ruby: ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]
- WARNING `neovim-ruby-host` not found.
  - ADVICE:
    - Run `gem install neovim` to ensure the neovim RubyGem is installed.
    - Run `gem environment` to ensure the gem bin directory is in $PATH.
    - If you are using rvm/rbenv/chruby, try "rehashing".
    - See :help |g:ruby_host_prog| for non-standard gem installations.
    - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

==============================================================================
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- Can load WASM parsers: false

==============================================================================
which-key: require("which-key.health").check()

- OK Most of these checks are for informational purposes only.
  WARNINGS should be treated as a warning, and don't necessarily indicate a problem with your config.
  Please |DON't| report these warnings as an issue.

Checking your config ~
- OK |mini.icons| is installed
- OK |nvim-web-devicons| is installed

Checking for issues with your mappings ~
- OK No issues reported

checking for overlapping keymaps ~
- WARNING In mode `n`, <g> overlaps with <gc>, <gcc>, <gcO>, <gco>, <g]>, <g%>, <gra>, <grn>, <grr>, <gx>, <g[>:
  - <g>: goto
  - <gc>: Toggle comment
  - <gcc>: Toggle comment line
  - <gcO>: Add Comment Above
  - <gco>: Add Comment Below
  - <g]>: Move to right "around"
  - <g%>: Cycle backwards through results
  - <gra>: vim.lsp.buf.code_action()
  - <grn>: vim.lsp.buf.rename()
  - <grr>: vim.lsp.buf.references()
  - <gx>: Open with system app
  - <g[>: Move to left "around"
- WARNING In mode `n`, <<Space>w> overlaps with <<Space>wd>, <<Space>wm>, <<C-W><C-D>>, <<C-W><Space>>:
  - <<Space>w>: windows
  - <<Space>wd>: Delete Window
  - <<Space>wm>: Enable Maximize
  - <<C-W><C-D>>: Show diagnostics under the cursor
  - <<C-W><Space>>: Window Hydra Mode (which-key)
- WARNING In mode `x`, <i> overlaps with <in>, <il>:
  - <i>: inside
  - <in>: next
  - <il>: last
- WARNING In mode `x`, <a> overlaps with <an>, <al>, <a%>:
  - <a>: around
  - <an>: next
  - <al>: last
- WARNING In mode `o`, <a> overlaps with <an>, <al>:
  - <a>: around
  - <an>: next
  - <al>: last
- WARNING In mode `o`, <i> overlaps with <in>, <il>:
  - <i>: inside
  - <in>: next
  - <il>: last
- WARNING In mode `n`, <gc> overlaps with <gcc>, <gcO>, <gco>:
  - <gc>: Toggle comment
  - <gcc>: Toggle comment line
  - <gcO>: Add Comment Above
  - <gco>: Add Comment Below
- OK Overlapping keymaps are only reported for informational purposes.
  This doesn't necessarily mean there is a problem with your config.

Checking for duplicate mappings ~
-

>>>==========================================================================
```

### Output of `nvim --version`

```text
NVIM v0.11.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.1703358377
```

### Additional context

#####NEXT
CREATE and THEN cat tstest.lua: 
local tspath = vim.fn.stdpath('data') .. '/tstest'
print(tspath)
if not vim.uv.fs_stat(tspath) then
  vim.system {
   'git',
   'clone',
   '--filter=blob:none',
   '--single-branch',
   'https://github.com/nvim-treesitter/nvim-treesitter',
   tspath,
  }:wait()
end
vim.opt.runtimepath:prepend(tspath)

require('nvim-treesitter.configs').setup({
  highlight = { enable = true },
})

WHEN I execute nvim --clean -u tstest.lua 
THEN run checkhealth the following report:
>>>==========================================================================
- LSP log level : WARN
- Log path: /home/briandanks/.local/state/nvim/lsp.log
- Log size: 0 KB

vim.lsp: Active Clients ~
- No active clients

vim.lsp: File Watcher ~
- file watching "(workspace/didChangeWatchedFiles)" disabled on all clients

vim.lsp: Position Encodings ~
- No active clients

==============================================================================
vim.provider: require("vim.provider.health").check()

Clipboard (optional) ~
- OK Clipboard tool found: xsel

Node.js provider (optional) ~
- Node.js: v22.9.0
  
- Nvim node.js host: /home/briandanks/.nvm/versions/node/v22.9.0/lib/node_modules/neovim/bin/cli.js
- OK Latest "neovim" npm/yarn/pnpm package is installed: 5.2.1
  

Perl provider (optional) ~
- WARNING "Neovim::Ext" cpan module is not installed
  - ADVICE:
    - See :help |provider-perl| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim
- WARNING No usable perl executable found

Python 3 provider (optional) ~
- WARNING No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
- WARNING Could not load Python :
  /home/linuxbrew/.linuxbrew/bin/python3 does not have the "neovim" module.
  /home/linuxbrew/.linuxbrew/bin/python3.12 does not have the "neovim" module.
  /home/linuxbrew/.linuxbrew/bin/python3.11 does not have the "neovim" module.
  /home/linuxbrew/.linuxbrew/bin/python3.10 does not have the "neovim" module.
  /home/linuxbrew/.linuxbrew/bin/python3.9 does not have the "neovim" module.
  python3.8 not found in search path or not executable.
  python3.7 not found in search path or not executable.
  /home/linuxbrew/.linuxbrew/bin/python does not have the "neovim" module.
  - ADVICE:
    - See :help |provider-python| for more information.
    - You may disable this provider (and warning) by adding `let g:loaded_python3_provider = 0` to your init.vim
- Executable: Not found

Python virtualenv ~
- OK no $VIRTUAL_ENV

Ruby provider (optional) ~
- Ruby: ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]
- WARNING `neovim-ruby-host` not found.
  - ADVICE:
    - Run `gem install neovim` to ensure the neovim RubyGem is installed.
    - Run `gem environment` to ensure the gem bin directory is in $PATH.
    - If you are using rvm/rbenv/chruby, try "rehashing".
    - See :help |g:ruby_host_prog| for non-standard gem installations.
    - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

==============================================================================
vim.treesitter: require("vim.treesitter.health").check()

- Nvim runtime ABI version: 14
- OK Parser: c                    ABI: 14, path: /usr/lib/x86_64-linux-gnu/nvim/parser/c.so
- OK Parser: lua                  ABI: 14, path: /usr/lib/x86_64-linux-gnu/nvim/parser/lua.so
- OK Parser: markdown             ABI: 14, path: /usr/lib/x86_64-linux-gnu/nvim/parser/markdown.so
- OK Parser: markdown_inline      ABI: 14, path: /usr/lib/x86_64-linux-gnu/nvim/parser/markdown_inline.so
- OK Parser: query                ABI: 14, path: /usr/lib/x86_64-linux-gnu/nvim/parser/query.so
- OK Parser: vim                  ABI: 14, path: /usr/lib/x86_64-linux-gnu/nvim/parser/vim.so
- OK Parser: vimdoc               ABI: 14, path: /usr/lib/x86_64-linux-gnu/nvim/parser/vimdoc.so
- Can load WASM parsers: false
>>>==========================================================================

**Comment by clason** [comment]
> I am following the recommended installation guide:

This is _not_ the guide recommended _by us_.

In any case, this looks like you have a broken compiler installation; I strongly recommend to stick to the system compiler and not use linuxbrew etc. unless you know exactly what you're doing.

**Comment by dev4openid** [comment]
Hi,
thanks for the reply.
I am in early stages of learning here.
Apologies, you refer to the compiler from linuxbrew.   Maybe it is me, I
removed all brew aspects of gcc/g++/neovim/lua/luarocks/transcrypt/python
and I executed

sudo apt-get update && sudo apt-get install build-essentialls

and ensuring installation of sudo apt-get install
gcc/g++/neovim/lua/luarocks/python.   Cannot find where to get transcrpyt
(seems to be a dependency of lua??).
*You refer to the compiler - however, I am not sure which compiler you
refer to. *(Happy to change it to sudo version, if I can know which one is
the issue)
Also, you refer to a guide recommended by us - I did not know you had a
guide.  I am following the Lazyvim site recommendations (the author is
recommended)

I cleared the .config/nvim and started again. Everything installs but
treesitter again failed

Regards

**Comment by clason** [comment]
>  I am following the Lazyvim site recommendations (the author is recommended)

Then please ask at the LazyVim site. We can only diagnose issues with this plugin, which means they have to be reproducible without any other plugins ("minimal reproducing example").
