### ISSUE TITLE
ensure_installed calls flatten on a nil value

### ISSUE THREAD

**Issue by Timoyoungster** [nvim-treesitter/nvim-treesitter#7209]
### Describe the bug

Hello,

I use neovim on a macbook m1 with nvim-treesitter (amongst other plugins; installed with Lazy).
My nvim config was created and developed mostly on an arch linux system, where everything ran without problems. For some reason the same config produces an error in startup on my macbook: 
<img width="1003" alt="Screenshot 2024-10-02 at 2 42 45 PM" src="https://github.com/user-attachments/assets/3059189a-95bb-4305-ba13-744c4b92bea4">

which I have now managed to trace this back to the ensure_installed config option.
For now I have removed the option and nvim starts without errors again, but I'm curious if there are other people also running into this problem and how I could possibly fix this issue.

### To Reproduce

1. add `ensure_installed = { 'bash', 'c', },` to your config (the chosen languages do not matter)
2. start neovim
3. => the error from the screenshot above 

### Expected behavior

no error would be the expectation

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()
    3
    4 Installation
    5 - OK tree-sitter found 0.23.0 (parser generator, only needed for :           TSInstallFromGrammar)
    6 - OK node found v22.4.0 (only needed for :TSInstallFromGrammar)
    7 - OK git executable found.
    8 - OK cc executable found. Selected from { vim.NIL, "cc", "gcc",              "clang", "cl", "zig" }
    9   Version: Apple clang version 15.0.0 (clang-1500.3.9.4)
   10 - OK Neovim was compiled with tree-sitter runtime ABI version 14             (required >=13). Parsers must be compatible with runtime ABI.
   11
   12 OS Info:
   13 {
   14   machine = "arm64",
   15   release = "23.6.0",
   16   sysname = "Darwin",
   17   version = "Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:21 PDT             2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8103"
   18 }
   19
   20 Parser/Features         H L F I J
   21   - bash                ✓ ✓ ✓ . ✓
   22   - c                   ✓ ✓ ✓ ✓ ✓
   23   - cpp                 ✓ ✓ ✓ ✓ ✓
   24   - csv                 ✓ . . . .
   25   - gitcommit           ✓ . . . ✓
   26   - gitignore           ✓ . . . ✓
   27   - html                ✓ ✓ ✓ ✓ ✓
   28   - json                ✓ ✓ ✓ ✓ .
   29   - lua                 ✓ ✓ ✓ ✓ ✓
   30   - make                ✓ . ✓ . ✓
   31   - markdown            ✓ . ✓ ✓ ✓
   32   - markdown_inline     ✓ . . . ✓
   33   - python              ✓ ✓ ✓ ✓ ✓
   34   - query               ✓ ✓ ✓ ✓ ✓
   11   - rust                x ✓ ✓ ✓ ✓
   10   - vim                 ✓ ✓ ✓ . ✓
    9   - vimdoc              ✓ . . . ✓
    8
    7   Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
    6          +) multiple parsers found, only one will be used
    5          x) errors found in the query, try to run :TSUpdate {lang}
    4
    3 The following errors have been detected:
    2 - ERROR rust(highlights): ...os-arm64/share/nvim/runtime/lua/vim/            treesitter/query.lua:252: Query error at 447:2. Invalid node type            "never_type":
    1   (never_type
  47     ^
    1 ··
    2   rust(highlights) is concatenated from the following files:
    3   | [ERROR]:"/Users/timo/.local/share/nvim/lazy/nvim-treesitter/               queries/rust/highlights.scm", failed to load: ...os-arm64/share/nvim/        runtime/lua/vim/treesitter/query.lua:252: Query error at 447:2.              Invalid node type "never_type":
    4   (never_type
    5    ^
    6 ··
```

### Output of `nvim --version`

```text
NVIM v0.11.0-dev-680+g4353996d0
Build type: RelWithDebInfo
LuaJIT 2.1.1724512491
Run "nvim -V1 -v" for more info
```

**Comment by clason** [comment]
Your Neovim version is outdated. If you use `master`, you need to stay on HEAD.

**Comment by Timoyoungster** [comment]
sorry, didn't realize I was on nightly on this machine. Just tested with:

NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1727621189
Run "nvim -V1 -v" for more info

and got the same error.

**Comment by Timoyoungster** [comment]
In case anyone else runs into the same issue:

I was using packer and switched to lazy quite some time back when I redid my config on another machine.
I didn't realize until now, that in ~/.local/nvim/site there still was a pack folder, which all the parsers were installed to before my config redo => parsers were marked as installed even though they were not in my configured install directory.

Rmrf'ing the folder fixed the problem for me.
