### ISSUE TITLE
diff + and - are highlighted as the same color

### ISSUE THREAD

**Issue by Anthony-Fiddes** [nvim-treesitter/nvim-treesitter#7232]
### Describe the highlighting problem

The pluses and minuses in git diffs are highlighted with the same color. They should be highlighted as different colors according to `@diff.minus.diff` and `@diff.plus.diff`, but they appear to be both overridden by `@punctuation.special.diff`.

### Example snippet that causes the problem

```

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# On branch main
# Your branch is up to date with 'origin/main'.
#
# Changes to be committed:
#	modified:   init.lua
#
# Changes not staged for commit:
#	modified:   lazy-lock.json
#
# Untracked files:
#	spell/
#	test.yaml
#
# ------------------------ >8 ------------------------
# Do not modify or remove the line above.
# Everything below it will be ignored.
diff --git a/init.lua b/init.lua
index 1f9d649..f4f3acd 100644
--- a/init.lua
+++ b/init.lua
@@ -329,9 +329,15 @@ vim.defer_fn(function()
     -- Add languages to be installed here that you want installed for treesitter
     ensure_installed = {
       "bash",
-      "fish",
       "dockerfile",
+      "fish",
       "go",
+      "git_config",
+      "gitcommit",
+      "diff",
+      "git_rebase",
+      "gitignore",
+      "gitattributes",
       "lua",
       "python",
       "sql",
```

### Tree-sitter parsing result

```
(source ; [0, 0] - [41, 0] gitcommit
  (generated_comment) ; [1, 0] - [1, 66] gitcommit
  (generated_comment) ; [2, 0] - [3, 0] gitcommit
  (generated_comment) ; [3, 0] - [3, 1] gitcommit
  (generated_comment ; [4, 0] - [5, 0] gitcommit
    (text) ; [4, 2] - [4, 12] gitcommit
    (branch)) ; [4, 12] - [4, 16] gitcommit
  (generated_comment ; [5, 0] - [5, 47] gitcommit
    "Your branch is up to date with '" ; [5, 2] - [5, 34] gitcommit
    (branch) ; [5, 34] - [5, 45] gitcommit
    "'.") ; [5, 45] - [5, 47] gitcommit
  (generated_comment) ; [6, 0] - [6, 1] gitcommit
  (generated_comment ; [7, 0] - [7, 26] gitcommit
    (title)) ; [7, 2] - [7, 26] gitcommit
  (generated_comment ; [8, 0] - [8, 22] gitcommit
    (change ; [8, 2] - [8, 11] gitcommit
      kind: (modified ; [8, 2] - [8, 11] gitcommit
        "modified:")) ; [8, 2] - [8, 11] gitcommit
    (filepath)) ; [8, 14] - [8, 22] gitcommit
  (generated_comment) ; [9, 0] - [9, 1] gitcommit
  (generated_comment ; [10, 0] - [10, 32] gitcommit
    (title)) ; [10, 2] - [10, 32] gitcommit
  (generated_comment ; [11, 0] - [11, 28] gitcommit
    (change ; [11, 2] - [11, 11] gitcommit
      kind: (modified ; [11, 2] - [11, 11] gitcommit
        "modified:")) ; [11, 2] - [11, 11] gitcommit
    (filepath)) ; [11, 14] - [11, 28] gitcommit
  (generated_comment) ; [12, 0] - [12, 1] gitcommit
  (generated_comment ; [13, 0] - [13, 18] gitcommit
    (title)) ; [13, 2] - [13, 18] gitcommit
  (generated_comment ; [14, 0] - [14, 8] gitcommit
    (filepath)) ; [14, 2] - [14, 8] gitcommit
  (generated_comment ; [15, 0] - [15, 11] gitcommit
    (filepath)) ; [15, 2] - [15, 11] gitcommit
  (generated_comment) ; [16, 0] - [16, 1] gitcommit
  (scissor) ; [17, 0] - [18, 0] gitcommit
  (diff ; [18, 0] - [41, 0] gitcommit
    (source ; [18, 41] - [41, 0] diff
      (block ; [20, 0] - [41, 0] diff
        (command ; [20, 0] - [20, 32] diff
          "diff" ; [20, 0] - [20, 4] diff
          (argument) ; [20, 5] - [20, 10] diff
          (filename)) ; [20, 11] - [20, 32] diff
        (index ; [21, 0] - [21, 29] diff
          "index" ; [21, 0] - [21, 5] diff
          (commit) ; [21, 6] - [21, 13] diff
          ".." ; [21, 13] - [21, 15] diff
          (commit) ; [21, 15] - [21, 22] diff
          (mode)) ; [21, 23] - [21, 29] diff
        (old_file ; [22, 0] - [22, 14] diff
          "---" ; [22, 0] - [22, 3] diff
          (filename)) ; [22, 4] - [22, 14] diff
        (new_file ; [23, 0] - [23, 14] diff
          "+++" ; [23, 0] - [23, 3] diff
          (filename)) ; [23, 4] - [23, 14] diff
        (hunks ; [24, 0] - [41, 0] diff
          (hunk ; [24, 0] - [41, 0] diff
            location: (location ; [24, 0] - [24, 44] diff
              "@@" ; [24, 0] - [24, 2] diff
              (linerange) ; [24, 3] - [24, 9] diff
              (linerange) ; [24, 10] - [24, 17] diff
              "@@") ; [24, 18] - [24, 20] diff
            changes: (changes ; [25, 0] - [41, 0] diff
              (context) ; [25, 0] - [25, 81] diff
              (context) ; [26, 0] - [26, 25] diff
              (context) ; [27, 0] - [27, 14] diff
              (deletion ; [28, 0] - [28, 14] diff
                "-") ; [28, 0] - [28, 1] diff
              (context) ; [29, 0] - [29, 20] diff
              (addition ; [30, 0] - [30, 14] diff
                "+") ; [30, 0] - [30, 1] diff
              (context) ; [31, 0] - [31, 12] diff
              (addition ; [32, 0] - [32, 20] diff
                "+") ; [32, 0] - [32, 1] diff
              (addition ; [33, 0] - [33, 19] diff
                "+") ; [33, 0] - [33, 1] diff
              (addition ; [34, 0] - [34, 14] diff
                "+") ; [34, 0] - [34, 1] diff
              (addition ; [35, 0] - [35, 20] diff
                "+") ; [35, 0] - [35, 1] diff
              (addition ; [36, 0] - [36, 19] diff
                "+") ; [36, 0] - [36, 1] diff
              (addition ; [37, 0] - [37, 23] diff
                "+") ; [37, 0] - [37, 1] diff
              (context) ; [38, 0] - [38, 13] diff
              (context) ; [39, 0] - [39, 16] diff
              (context)))))) ; [40, 0] - [40, 13] diff
    (generated_comment ; [18, 0] - [18, 41] gitcommit
      "#") ; [18, 0] - [18, 1] gitcommit
    (generated_comment ; [19, 0] - [19, 38] gitcommit
      "#"))) ; [19, 0] - [19, 1] gitcommit
```

### Example screenshot

I went ahead and enabled the default color scheme since the problem is still there with it:

![Image](https://github.com/user-attachments/assets/7d4644a4-eb1f-4df0-9147-c57941765ace)

### Expected behavior

Should look something like this (which is how it looks with the TS highlighting disabled):

![Image](https://github.com/user-attachments/assets/65af34e8-a616-460d-9411-78a11e08b4c6)

### Output of `:checkhealth nvim-treesitter`

==============================================================================
nvim-treesitter:                     require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.24.3 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v22.1.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 15.0.0 (clang-1500.3.9.4)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.6.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - diff                ✓ . ✓ . ✓
  - dockerfile          ✓ . . . ✓
  - fish                ✓ ✓ ✓ ✓ ✓
  - git_config          ✓ . ✓ . ✓
  - git_rebase          ✓ . . . ✓
  - gitattributes       ✓ ✓ . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - sql                 ✓ . . ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - vue                 ✓ . ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

### Output of `nvim --version`

NVIM v0.11.0-dev-946+g25665b365
Build type: RelWithDebInfo
LuaJIT 2.1.1727870382
Run "nvim -V1 -v" for more info

**Comment by clason** [comment]
That's an issue with your colorscheme then; nothing to do with this plugin.

**Comment by clason** [comment]
It's probably sufficient to move the punctuation patterns before the added/removed ones. PR welcome!

**Comment by Anthony-Fiddes** [comment]
Hey @clason, thanks for getting back to me! I don't have any experience with treesitter, but I took a look around and tried this: https://github.com/nvim-treesitter/nvim-treesitter/pull/7233

Unfortunately it didn't work. My other idea would be to pull out the + and - characters out of the `punctuation.special` array, but I figure they're in there for a good reason. Is there any chance you could point me to a good resource for learning more about how I could make this fix? (maybe a similar PR or issue from the past?)

**Comment by clason** [comment]
Yes, then they have to be captured differently. Not sure if that was intentional, or parity with the legacy syntax file was simply not considered. @ribru17 ?

**Comment by ribru17** [comment]
Yeah, I think parity was not considered. Would it be acceptable to just give `"+"` and `"-"` a low priority? That way the highlights still exist akin to being moved before the other highlights, and can still look nice in colorschemes that give additions/deletions a bg highlight, while also inheriting the foreground of that highlight if it exists
