### ISSUE TITLE
[C] Incorrect folding behaviour with top-level array literals

### ISSUE THREAD

**Issue by Keating950** [nvim-treesitter/nvim-treesitter#724]
Using the following settings:
```
set foldmethod=expr
set foldexpr=nvim_treesitter#foldexpr()
```

Attempting to fold a top-level array in C results in the entire file being folded instead of just the array.
![before](https://user-images.githubusercontent.com/43932454/100558838-1a184b80-327e-11eb-98dc-e0787884b1fd.png)
![after](https://user-images.githubusercontent.com/43932454/100558843-1d133c00-327e-11eb-8e74-f53659b03f28.png)

**To Reproduce**
Fold with `zc`.

**Expected behavior**
Just the array being folded.

**Output of `:checkhealth nvim_treesitter`**
```
health#nvim_treesitter#check  
========================================================================  
## Installation  
  - OK: git executable found.
  - OK: cc executable found.

## c parser healthcheck
  - OK: c parser found.
  - OK: highlights.scm found.
  - OK: locals.scm found.
  - OK: folds.scm found.
  - WARNING: No indents.scm query found for c
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
```

**Output of `nvim --version`**
```
NVIM v0.5.0-nightly-126-geefb19245
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -O3 -DNDEBUG [etc]
```

**Comment by theHamsta** [comment]
Can you add `(initializer_list)` to folds.scm and try again?

I personally would like to use `(_) @fold` to fold on every multi-line node but then your example currently only works when there are not two multi-line nodes with the same range.

So
```
int foo = { 2,
	3,4,5
}
;
```
works with `(_) @fold` but not
```
int foo = { 2,
	3,4,5
};
```
If you just add `(initializer_list)` it should work in most of the cases. You're welcome to create a PR if it works.

**Comment by theHamsta** [comment]
Can you try this PR https://github.com/nvim-treesitter/nvim-treesitter/pull/725 ?

**Comment by Keating950** [comment]
That PR solves it for me. Thanks!
