### ISSUE TITLE
recent update on `main` branch breaks the compatability with release nvim-0.10: `vim.fs.rm` only works with nightly

### ISSUE THREAD

**Issue by milanglacier** [nvim-treesitter/nvim-treesitter#7245]
This is not a bug, this should be a decision that if the `main` branch want to be remain compatibility with the release version, or only work with nightly.

Since this is documented in the `README` in the main branch that the release version is supported

> ## Requirements
> - Neovim 0.10.0 or later (nightly)
> - `tar` and `curl` in your path (or alternatively `git`)
> - [`tree-sitter`](https://github.com/tree-sitter/tree-sitter) CLI (0.24.0 or later)
> - a C compiler in your path (see <https://docs.rs/cc/latest/cc/#compile-time-requirements>)

**Comment by milanglacier** [comment]
Cool.  only working with nightly branch definitely makes sense for the sake of a completely write.

We should update the doc to state that the main branch only works with nightly (not official release) in the README of main branch.

**Comment by clason** [comment]
Why are people using the main branch in the first place? It's not ready yet, same as any other random non-default branch.
