### ISSUE TITLE
Is possible close InpectTree with q map?

### ISSUE THREAD

**Issue by vtmx** [nvim-treesitter/nvim-treesitter#7246]
I use this auto-commands to close some windows, is possible close InpectTree with q map?

```lua
-- Close help with "q"
autocmd('FileType', {
    pattern = { 'help', 'lspinfo', 'man', 'startuptime', 'qf' },
    command = 'nnoremap <buffer><silent> q :quit<cr>' 
  }
)
```

**Comment by clason** [comment]
Wrong repo; `:InspectTree` is implemented in Neovim. (And please search open and closed issues first.)
