### ISSUE TITLE
nvim-treesitter-c will recognize functional macros as normal functions.

### ISSUE THREAD

**Issue by ziyangzheng** [nvim-treesitter/nvim-treesitter#7255]
### Describe the highlighting problem

I used 'nvim-vscode' theme as my nvim theme.when i use ':TSBufToggle highlight',both the varibles, typedef, normal macros and C key words have been showed as correct color but functional macros(like #define STR_CAT2(a,b) a##b) are regarded as normal functions and have the same color as normal function but macros.How can i do to fix then?thanks!

### Example snippet that causes the problem

#include <stdio.h>
#define MAX_NUM 3
#define STR_CAT(a,b) a##b
#define STR_CAT2(a,b) STR_CAT(a,b)

int get_output_1(int input){
    return input * 3 + 1;
}

int main(void){
    int c = STR_CAT2(get_output_,1)(3);
    printf("Hello world, outout:%d\n",STR_CAT2(get_output_,1)(3)); 
    return 0;

### Tree-sitter parsing result

![Image](https://github.com/user-attachments/assets/689cb10c-71b2-4538-b965-2fcc7d613577)
In this output,nvim-treesitter-c seemed to recognize the macros as function

### Example screenshot

![Image](https://github.com/user-attachments/assets/90a43132-c98c-4912-bc3d-d79a116ae9dc)

### Output of `:checkhealth nvim-treesitter`

=============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.18.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.8.0-45-generic",
  sysname = "Linux",
  version = "#45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ x
  - query               x ✓ ✓ ✓ x
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              x . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR lua(injections): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 3272 for language lua
  lua(injections) is concatenated from the following files:
  | [ERROR]:"/home/charx/.vim/plugged/nvim-treesitter/queries/lua/injections.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 3272 for language lua
- ERROR query(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 460 for language query
  query(highlights) is concatenated from the following files:
  | [ERROR]:"/home/charx/.vim/plugged/nvim-treesitter/queries/query/highlights.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 460 for language query
- ERROR query(injections): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 85 for language query
  query(injections) is concatenated from the following files:
  | [ERROR]:"/home/charx/.vim/plugged/nvim-treesitter/queries/query/injections.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 85 for language query
- ERROR vimdoc(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 7 for language vimdoc
  vimdoc(highlights) is concatenated from the following files:
  | [ERROR]:"/home/charx/.vim/plugged/nvim-treesitter/queries/vimdoc/highlights.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 7 for language vimdoc

### Output of `nvim --version`

NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/usr/share/nvim"

Run :checkhealth for more info

**Comment by ziyangzheng** [comment]
> ### Describe the highlighting problem
> 
> I used 'nvim-vscode' theme as my nvim theme.when i use ':TSBufToggle highlight',both the varibles, typedef, normal macros and C key words have been showed as correct color but functional macros(like #define STR_CAT2(a,b) a##b) are regarded as normal functions and have the same color as normal function but macros.How can i do to fix then?thanks!
> ### Example snippet that causes the problem
> 
> #include <stdio.h> #define MAX_NUM 3 #define STR_CAT(a,b) a##b #define STR_CAT2(a,b) STR_CAT(a,b)
> 
> int get_output_1(int input){ return input * 3 + 1; }
> 
> int main(void){ int c = STR_CAT2(get_output_,1)(3); printf("Hello world, outout:%d\n",STR_CAT2(get_output_,1)(3)); return 0;
> ### Tree-sitter parsing result
> 
> ![Image](https://github.com/user-attachments/assets/689cb10c-71b2-4538-b965-2fcc7d613577) In this output,nvim-treesitter-c seemed to recognize the macros as function
> ### Example screenshot
> 
> ![Image](https://github.com/user-attachments/assets/90a43132-c98c-4912-bc3d-d79a116ae9dc)
> ### Expected behavior
> 
> _No response_
> ### Output of `:checkhealth nvim-treesitter`
> 
> ============================================================================= nvim-treesitter: require("nvim-treesitter.health").check()
> 
> Installation ~
> 
>     * WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
> 
>     * OK `node` found v20.18.0 (only needed for :TSInstallFromGrammar)
> 
>     * OK `git` executable found.
> 
>     * OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
>       Version: cc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
> 
>     * OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.
> 
> 
> OS Info: { machine = "x86_64", release = "6.8.0-45-generic", sysname = "Linux", version = "[#45](https://github.com/nvim-treesitter/nvim-treesitter/pull/45)-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024" } ~
> 
> Parser/Features H L F I J
> 
>     * c                   ✓ ✓ ✓ ✓ ✓
> 
>     * cpp                 ✓ ✓ ✓ ✓ ✓
> 
>     * lua                 ✓ ✓ ✓ ✓ x
> 
>     * query               x ✓ ✓ ✓ x
> 
>     * vim                 ✓ ✓ ✓ . ✓
> 
>     * vimdoc              x . . . ✓
> 
> 
> Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections +) multiple parsers found, only one will be used x) errors found in the query, try to run :TSUpdate {lang} ~
> 
> The following errors have been detected: ~
> 
>     * ERROR lua(injections): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 3272 for language lua
>       lua(injections) is concatenated from the following files:
>       | [ERROR]:"/home/charx/.vim/plugged/nvim-treesitter/queries/lua/injections.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid structure at position 3272 for language lua
> 
>     * ERROR query(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 460 for language query
>       query(highlights) is concatenated from the following files:
>       | [ERROR]:"/home/charx/.vim/plugged/nvim-treesitter/queries/query/highlights.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 460 for language query
> 
>     * ERROR query(injections): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 85 for language query
>       query(injections) is concatenated from the following files:
>       | [ERROR]:"/home/charx/.vim/plugged/nvim-treesitter/queries/query/injections.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 85 for language query
> 
>     * ERROR vimdoc(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 7 for language vimdoc
>       vimdoc(highlights) is concatenated from the following files:
>       | [ERROR]:"/home/charx/.vim/plugged/nvim-treesitter/queries/vimdoc/highlights.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:259: query: invalid node type at position 7 for language vimdoc
> 
> 
> ### Output of `nvim --version`
> 
> NVIM v0.9.5 Build type: Release LuaJIT 2.1.1703358377
> 
> ```
>  系统 vimrc 文件: "$VIM/sysinit.vim"
>      $VIM 预设值: "/usr/share/nvim"
> ```
> 
> Run :checkhealth for more info
> ### Additional context
> 
> _No response_

I loss the parsing result:
![Image](https://github.com/user-attachments/assets/e968ec1e-afc8-4fb6-a9b6-0aeb4a2b7b7e)

**Comment by ziyangzheng** [comment]
![Image](https://github.com/user-attachments/assets/bf3a40a4-2ea4-44fd-a06b-1131d10c9275)
I modified the color of @function.macro to Pink (same as normal macros) in vscode.nvim.But only functional macros definition is Pink, the call is still yellow.
 ![Image](https://github.com/user-attachments/assets/df4aed1d-c406-4c2c-ac91-e3accb1215c8)

**Comment by ValdezFOmar** [comment]
`nvim-treesitter` doesn't use `locals.scm` for highlighting so that's why the call is still highlighted as a function.

If you are using `clangd` as your language server, it reports a semantic token (the `@lsp.type.macro` highlight) for macros that will highlight the call.

**Comment by ribru17** [comment]
Closing as the color scheme itself must give the correct highlight for `@function.macro`, and as @ValdezFOmar says the other highlight must be applied by LSP

**Comment by clason** [comment]
(Also, Nvim 0.9 is no longer supported.)

**Comment by ziyangzheng** [comment]
> (Also, Nvim 0.9 is no longer supported.)

    thanks for all of your reply.Actually,I found the @lsp.type.macro and whose attribute is {link = '@constant'},I modified like this
![Image](https://github.com/user-attachments/assets/d6583984-99d4-45c9-af5a-785f60fd8ef4)
but nothing happened when I open the same .c file again.
    So dose  'Nvim 0.9 is no longer supported ' mean i can no longer get the effect I need?

**Comment by clason** [comment]
>  @lsp.type.macro 

That has nothing to do with tree-sitter. 

> So does 'Nvim 0.9 is no longer supported ' mean i can no longer get the effect I need?

It means you need to update Nvim _and your colorscheme_, or things won't work correctly. (Or pin everything to a previous tag where things worked and stop updating.)
