### ISSUE TITLE
Add https://github.com/kayhide/tree-sitter-idris

### ISSUE THREAD

**Issue by srghma** [nvim-treesitter/nvim-treesitter#7257]
**Is your feature request related to a problem? Please describe.**

Currently, there is no support for idris or idris2

**Describe the solution you'd like**

add https://github.com/kayhide/tree-sitter-idris

How can I add one? it is using c language

**Describe alternatives you've considered**

alternatives dont exist, other implementations are deprecated https://github.com/idris-lang/Idris2/issues/3369#issuecomment-2282455547

**Comment by clason** [comment]
We don't take requests; PRs are welcome (look at merged PRs labeled "new language" for models).
