### ISSUE TITLE
compilation error i am using lazy vim in neovide

### ISSUE THREAD

**Issue by 28arnab** [nvim-treesitter/nvim-treesitter#7263]
![Image](https://github.com/user-attachments/assets/73192bd1-2fc1-4670-b002-290c5a725cae)

**Comment by clason** [comment]
The issue template is there for a reason. 

(Reminder: This is not a support channel.)

**Comment by 28arnab** [comment]
https://www.reddit.com/r/neovim/comments/14oozmu/neovim_cant_find_c_compiler/

fixed it on my own haha

**Comment by clason** [comment]
Haha.
