### ISSUE TITLE
markdown: incremental_selection reports E5108

### ISSUE THREAD

**Issue by xudyang1** [nvim-treesitter/nvim-treesitter#7291]
### Describe the bug

When cursor is at the end of a line with a space, calling incremental selection in markdown file throws E5108.

### To Reproduce

1. `nvim repro.md`
2. type `ahello world`, with an extra space at the end
3. exit insert mode, move cursor to the ending space and use keymap to call `node_incremental`
4. Error message is shown:

```text
E5108: Error executing lua: ...ashfs-root/usr/share/nvim/runtime/lua/vim/treesitter.lua:167: attempt to index local 'node_or_range' (a n
il value)
stack traceback:
        ...ashfs-root/usr/share/nvim/runtime/lua/vim/treesitter.lua:167: in function 'get_node_range'
        ...im/lazy/nvim-treesitter/lua/nvim-treesitter/ts_utils.lua:279: in function 'update_selection'
        ...treesitter/lua/nvim-treesitter/incremental_selection.lua:19: in function <...treesitter/lua/nvim-treesitter/incremental_selec
tion.lua:15>
```

### Expected behavior

Selection should be made successfully without error

### Output of `:checkhealth nvim-treesitter`

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.15.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.15.153.1-microsoft-standard-WSL2",
  sysname = "Linux",
  version = "#1 SMP Fri Mar 29 23:14:13 UTC 2024"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cmake               ✓ . ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - diff                ✓ . ✓ . ✓
  - dockerfile          ✓ . . . ✓
  - git_config          ✓ . ✓ . ✓
  - git_rebase          ✓ . . . ✓
  - gitattributes       ✓ ✓ . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - http                ✓ . . . ✓
  - ini                 ✓ . ✓ . ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - luap                ✓ . . . .
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - rust                ✓ ✓ ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ ✓
  - sql                 ✓ . . ✓ ✓
  - ssh_config          ✓ ✓ ✓ ✓ ✓
  - terraform           ✓ . ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - xml                 ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

### Output of `nvim --version`

NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info

**Comment by xudyang1** [comment]
This may be related to tree-sitter-markdown. Tried with other filetypes, and the incremental selections worked.

Closed.

**Comment by xudyang1** [comment]
Reopen this. https://github.com/tree-sitter-grammars/tree-sitter-markdown/issues/167#issuecomment-2442635296

**Comment by clason** [comment]
That comment means this has nothing to do with this plugin and is an upstream issue. Please create a minimal example (the markdown parsers are bundled with Neovim, so you don't need this plugin), verify that it occurs with the latest nightly (can be downloaded from the releases page) then report at neovim/neovim.
