### ISSUE TITLE
Mapping description of `@class.outer` not correctly shown

### ISSUE THREAD

**Issue by tim-hilde** [nvim-treesitter/nvim-treesitter#7298]
### Describe the bug

Description of `@class.outer` mappings dont show as expected. This is for `next_start`, `next_end`, `previous_start` and `previous_end`. All other mappings show correct description 

Config is

```
goto_next_start = {
	["]m"] = "@function.outer",
	["]]"] = { query = "@class.outer", desc = "Next class start" },
	--
	-- You can use regex matching (i.e. lua pattern) and/or pass a list in a "query" key to group multiple queires.
	["]o"] = "@loop.*", -- that is, ["]o"] = { query = { "@loop.inner", "@loop.outer" } }

	-- You can pass a query group to use query from `queries/<lang>/<query_group>.scm file in your runtime path.
	-- Below example nvim-treesitter's `locals.scm` and `folds.scm`. They also provide highlights.scm and indent.scm.
	["]z"] = { query = "@fold", query_group = "folds", desc = "Next fold" },
},
goto_next_end = {
	["]M"] = "@function.outer",
	["]["] = "@class.outer",
},
goto_previous_start = {
	["[m"] = "@function.outer",
	["[["] = "@class.outer",
},
goto_previous_end = {
	["[M"] = "@function.outer",
	["[]"] = "@class.outer",
},
```

![Image](https://github.com/user-attachments/assets/0ea67268-be6c-4a75-8304-de26d03c1ec9)

### To Reproduce

Set config, use which-key type e.g. `]]`

### Output of `:checkhealth nvim-treesitter`

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.24.3 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v23.1.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 16.0.0 (clang-1600.0.26.3)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "24.0.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 24.0.0: Tue Sep 24 23:36:26 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T8103"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - csv                 ✓ . . . .
  - diff                ✓ . ✓ . ✓
  - dockerfile          ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - xml                 ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

### Output of `nvim --version`

NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
Run "nvim -V1 -v" for more info

**Comment by clason** [comment]
Wrong repo?
