### ISSUE TITLE
lua: Module in calling function highlight incorrectly

### ISSUE THREAD

**Issue by wingyplus** [nvim-treesitter/nvim-treesitter#732]
**Describe the bug**

The function in screenshot below, The `M` in return statement is not highlight but `M` in function declaration is highlight correctly:

![Screen Shot 2563-12-02 at 21 25 24](https://user-images.githubusercontent.com/484530/100885514-51d4fc80-34e5-11eb-8302-38efaf1282f4.png)

After inspect with `TSPlaygroundToggle`. I found that it's not the same identifier. Consider screenshots below:

This is `M` in return statement:

![Screen Shot 2563-12-02 at 21 30 20](https://user-images.githubusercontent.com/484530/100885758-96609800-34e5-11eb-9955-8a96dc56453f.png)

And this is `M` in function declaration:

![Screen Shot 2563-12-02 at 21 30 52](https://user-images.githubusercontent.com/484530/100885817-a9736800-34e5-11eb-8ef4-46cd9c1cfe6f.png)

**To Reproduce**

**Expected behavior**
The `M` in return statement should be the same color as `M` in function declration.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

Paste the output here

</code>
</details>

**Output of `nvim --version`**
```
$ nvim --version
NVIM v0.5.0-871-ga6bd52d87
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_11.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/thanabodee/src/github.com/neovim/neovim/build/config -I/Users/thanabodee/src/github.com/neovim/neovim/src -I/Users/thanabodee/src/github.com/neovim/neovim/.deps/usr/include -I/Applications/Xcode_11.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/Users/thanabodee/src/github.com/neovim/neovim/build/src/nvim/auto -I/Users/thanabodee/src/github.com/neovim/neovim/build/include
Compiled by thanabodee@TH-LW11435-M.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/Users/thanabodee/tools/neovim/share/nvim"

Run :checkhealth for more info
```

**Comment by vigoux** [comment]
Hi, sorry for the delay.

As you might have seen in your screenshots of the playground, the englobing node of the `identifer` node corresponding to the `M` is not the same. Thus making a link between the two requires a higher level in analysis.

If you still want to see that highlighting consistently (because using `M` is not a standard), you can add the followin in your `.config/nvim/after/queries/lua/highlights.scm` :

```scheme
((identifier) @constant
  (#eq? @constant "M"))
```

**Comment by stsewd** [comment]
This is the expected behavior, I think there is an open issue to be able to detect other things based on the currently captures.
