### ISSUE TITLE
Wait for installation of all parsers

### ISSUE THREAD

**Issue by flovilmart** [nvim-treesitter/nvim-treesitter#7323]
**Is your feature request related to a problem? Please describe.**
Running `nvim +TSUpdate +quitall` always exits before `TSUpdate` has run to completion. As such, one require to add a `sleep` to ensure the process gets enough time to complete, just to make sure upon next startup the TS setup is complete.

ex: https://github.com/flovilmart/vimrc/blob/main/install.sh#L16

**Describe the solution you'd like**

Having a `TSUpdateWait` or something similar would greatly help make sure we can install all parsers at once.

**Describe alternatives you've considered**

Using sleep is an alternative but a poor one.

**Comment by clason** [comment]
`:h TSUpdateSync`

**Comment by flovilmart** [comment]
@clason I explored this but it still exits immediately:

```
rm -rf  ~/.config/nvim/plugged/nvim-treesitter/parser-info/
rm ~/.config/nvim/plugged/nvim-treesitter/parser
nvim +TSUpdateSync +quitall
```

`TSUpdateSync` is not blocking the and `quitall` executes just after the command starts.
I'm aiming to have a behaviour similar to `PlugInstall`, where `nvim +PlugInstall` waits for the command to be completed.

**Comment by flovilmart** [comment]
@clason  Found out that I had `sync_install` false in the config:

```
require'nvim-treesitter.configs'.setup {
  -- A list of parser names, or "all" (the five listed parsers should always be installed)
  ensure_installed = { "ruby", "typescript", "javascript", "go", "lua", "vim", "query", "vimdoc", "c", "rust" },

  sync_install = false
}
```

This prevents TSUpdate to be run synchronously, do you consider this a bug or?

**Comment by clason** [comment]
No, I consider this behaving as intended. (Also, the `master` branch is essentially frozen in preparation for the -- delayed -- 1.0 release, so we're in bugfix mode only.)

**Comment by flovilmart** [comment]
Sounds good!
