### ISSUE TITLE
Trailing forward slash in jsdoc delimiter

### ISSUE THREAD

**Issue by rschristian** [nvim-treesitter/nvim-treesitter#7326]
### Describe the highlighting problem

The trailing forward slash in a JSDoc comment, be it single or multi-line comment, has `@punctuation.delimiter` applied which I'm not sure is correct. At the very least, it is inconsistent as the leading forward slash does not receive it.

Looks to be caused by #6864

### Example snippet that causes the problem

```js
/** this is a comment */
```

### Tree-sitter parsing result

```
(program ; [0, 0] - [1, 0] javascript
  (comment ; [0, 0] - [0, 24] javascript
    (source ; [0, 0] - [0, 24] comment
      "text" ; [0, 0] - [0, 1] comment
        "/") ; [0, 0] - [0, 1] comment
      "text" ; [0, 1] - [0, 3] comment
      "text" ; [0, 4] - [0, 8] comment
      "text" ; [0, 9] - [0, 11] comment
      "text" ; [0, 12] - [0, 13] comment
      "text" ; [0, 14] - [0, 21] comment
      "text" ; [0, 22] - [0, 23] comment
      "text" ; [0, 23] - [0, 24] comment
        "/")))) ; [0, 23] - [0, 24] comment
```

### Example screenshot

Leading Slash            |  Trailing Slash
:-------------------------:|:-------------------------:
![leading slash](https://github.com/user-attachments/assets/453b4939-ce52-4a3e-9430-dbf59774721f)  | ![trailing slash](https://github.com/user-attachments/assets/f1b98408-d2eb-49c1-9f9e-d540bc6d1f3d)

### Expected behavior

_I don't think_ that should count as a delimiter, so removing that highlight would be an option, else, also applying it to the leading slash would equally be reasonable.

### Output of `:checkhealth nvim-treesitter`

```
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.18.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (GCC) 14.2.1 20240910
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.11.5-arch1-1",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Tue, 22 Oct 2024 18:31:38 +0000"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - comment             ✓ . . . .
  - css                 ✓ . ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - sql                 ✓ . . ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```
NVIM v0.10.2
Build type: RelWithDebInfo
LuaJIT 2.1.1727870382
```

**Comment by clason** [comment]
That's due to the comment parser. As long as `jsdoc` doesn't expose the comment _contents_ as a separate node, there's not much we can do here.

**Comment by rschristian** [comment]
Can we not revert the handling of `"/"` from #6864 in that case? Seems weird to introduce something you know will be handled incorrectly, even if the issue ultimately lies upstream(?).

**Comment by clason** [comment]
Well, it's always a trade-off, isn't it? Feel free to make a PR and argue why your change is a net positive.

**Comment by rschristian** [comment]
Hm, not sure I'd agree.

Totally philosophical & subjective, everyone has different & valid opinions, but I personally wouldn't land a feature if it "broke" (I use this very lightly, highlights are far from the end of the world) something else. I guess my approach tends to be apply it cleanly or not at all, whilst allowing for breaking/intentional changes of course.

But thanks, might do that then. Appreciate your time.

**Comment by clason** [comment]
That's a perfectly fine development strategy, but intentionally and explicitly one we don't follow in this project. Queries are user-contributed and best effort, and that won't (can't) change in the near future.

**Comment by rschristian** [comment]
Fair enough! So feature-richness is generally preferred over "perfection" I'll call it for queries (and perhaps other items) then?

**Comment by clason** [comment]
No, just "best effort". Perfection is impossible anyway.
