### ISSUE TITLE
slow nvim_treesitter#foldexpr()  in json file

### ISSUE THREAD

**Issue by echoface** [nvim-treesitter/nvim-treesitter#7333]
### Describe the bug

- yes for all checklist
 
when open a big json file with treesitter 
vim.opt.foldmethod = "expr"
vim.opt.foldexpr = "nvim_treesitter#foldexpr()"

freezing(more actually is slow....) very long time when run cmd :w or :wq

### To Reproduce

1. nvim some_file.json
2. run: :wq
3. very long time with cpu cost 100%

profile output:
```
....
  1371 FUNCTION  nvim_treesitter#foldexpr()
  1372     Defined: ~/.local/share/nvim/lazy/nvim-treesitter/autoload/nvim_treesitter.vim:5
  1373 Called 3169 times
  1374 Total time: 153.582855
  1375  Self time: 153.582855
  1376
  1377 count  total (s)   self (s)
  1378  3169            153.578586     return luaeval(printf('require"nvim-treesitter.fold".get_fold_indic(%d)', v:lnum))
  1379
...
```

### Expected behavior

fast and correct

### Output of `:checkhealth nvim-treesitter`

    1
    2 ──────────────────────────────────────────────────────────────────────────────
    3 nvim-treesitter: require("nvim-treesitter.health").check()
    4
    5 Installation
    6 - OK tree-sitter found 0.24.3 (parser generator, only needed for :TSInstallFromGrammar)
    7 - OK node found v20.17.0 (only needed for :TSInstallFromGrammar)
    8 - OK git executable found.
    9 - OK cc executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
   10   Version: cc (Debian 8.3.0-6) 8.3.0
   11 - OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.
   12
   13 OS Info:
   14 {
   15   machine = "x86_64",
   16   release = "5.4.143.bsk.8-amd64",
   17   sysname = "Linux",
   18   version = "#5.4.143.bsk.8 SMP Debian 5.4.143.bsk.8 Wed Jul 20 08:43:36 UTC "
   19 }
   20
   21 Parser/Features         H L F I J
   22   - bash                ✓ ✓ ✓ . ✓
   23   - c                   ✓ ✓ ✓ ✓ ✓
   24   - comment             ✓ . . . .
   25   - cpp                 ✓ ✓ ✓ ✓ ✓
   26   - gitignore           ✓ . . . ✓
   27   - go                  ✓ ✓ ✓ ✓ ✓
   28   - gomod               ✓ . . . ✓
   29   - gosum               ✓ . . . .
   30   - gowork              ✓ . . . ✓
   31   - javascript          ✓ ✓ ✓ ✓ ✓
   32   - json                ✓ ✓ ✓ ✓ .
   33   - lua                 ✓ ✓ ✓ ✓ ✓
   34   - make                ✓ . ✓ . ✓
   35   - markdown            ✓ . ✓ ✓ ✓
   36   - markdown_inline     ✓ . . . ✓
   37   - proto               ✓ . ✓ ✓ ✓
   38   - python              ✓ ✓ ✓ ✓ ✓
   39   - query               ✓ ✓ ✓ ✓ ✓
   40   - sql                 ✓ . . ✓ ✓
   41   - thrift              ✓ ✓ ✓ ✓ ✓
   42   - tmux                ✓ . . . ✓
   43   - vim                 ✓ ✓ ✓ . ✓
   44   - vimdoc              ✓ . . . ✓
   45   - yaml                ✓ ✓ ✓ ✓ ✓
   46
   47   Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
   48          +) multiple parsers found, only one will be used
   49          x) errors found in the query, try to run :TSUpdate {lang}
   50

### Output of `nvim --version`

NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
Run "nvim -V1 -v" for more info

**Comment by clason** [comment]
This function is deprecated; please use `vim.treesitter.foldexpr` (and report any issues with that at Neovim).

Performance issues with long lines (e.g., json) are well known and ongoing work.
