### ISSUE TITLE
[python] Indentation is broken with a "[" string

### ISSUE THREAD

**Issue by rumpelsepp** [nvim-treesitter/nvim-treesitter#7339]
### Describe the bug

When there is a string containing `[` then the indentation using `o` in neovim is faulty.

### To Reproduce

Paste the following code 

``` python
def foo():
    a = "["
```

Move the cursor to the line containing `a =` and press `o`.

### Expected behavior

A new line is created and the cursor is on the column containing `a`.

### Output of `:checkhealth nvim-treesitter`

  - python              ✓ ✓ ✓ ✓ ✓

### Output of `nvim --version`

NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info

**Comment by ribru17** [comment]
Cannot reproduce (cursor is at `a` for me). This looks exactly like the kind of error that would happen with the regex based indents- please confirm you are using treesitter indentation? E.g. make sure you have 

```lua
{
  indent = {
    enable = true
  }
}
```

**Comment by rumpelsepp** [comment]
I wasn't aware of this, I can confirm that enabling the mentioned setting fixes the problem! Thank you. Is this a bug I need to report somewhere else?

**Comment by clason** [comment]
No, not a bug (in this project). If you want to contribute to Vim's legacy runtime files, contact the maintainer listed at the top of the file (`runtime/indent/python.vim`).
