### ISSUE TITLE
@reference only works with leaf nodes

### ISSUE THREAD

**Issue by BonaBeavis** [nvim-treesitter/nvim-treesitter#734]
Following soping rules work for `iri_reference` but not for `prefixed_name`.
I would guess this is because `iri_reference` is a terminal rule while `prefixed_name` has children. 

```
(turtle_doc) @scope

(triples (subject [
    (prefixed_name)
    (iri_reference)
  ] @definition.var))

[
  (prefixed_name)
  (iri_reference)
] @reference
```

**Comment by theHamsta** [comment]
Which parser? Which example code?

`@reference` is taking the whole node text. It should take the node text for any node. It can't know about leaf nodes. It only must have `@scope` as an ancestor (direct or indirect)

**Comment by kyazdani42** [comment]
closing since not answered
