### ISSUE TITLE
Nvim freezes when type <> in some condition.

### ISSUE THREAD

**Issue by crcrworks** [nvim-treesitter/nvim-treesitter#7349]
### Describe the bug

Nvim freezes when type > after typing < in some condition.
This problem was fixed when I turned treesitter off but just turning syntax highlight off didn't fix it.
I can see this problem in rust and typescript.

I'm using AstroNvim. I thought this caused problem so I reinstalled all and installed them minimally.
It didn't solve them.

Also, this problem doesn't cause my second PC despite same environment.
So I think something outside of nvim makes the problem.

### To Reproduce

in rust:
After typing "fn a()", type a<> in parentheses.

in typescript:
After typing "()", type "a<>" in parentheses.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.24.4 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v23.1.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 16.0.0 (clang-1600.0.26.4)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "24.1.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000"
} ~

Parser/Features         H L F I J
  - astro               ✓ ✓ ✓ ✓ ✓
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - c_sharp             ✓ ✓ ✓ . ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - cuda                ✓ ✓ ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - gomod               ✓ . . . ✓
  - gosum               ✓ . . . .
  - gowork              ✓ . . . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - luap                ✓ . . . .
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - objc                ✓ ✓ ✓ ✓ ✓
  - printf              ✓ . . . .
  - proto               ✓ . ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - ron                 ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - scss                ✓ . ✓ ✓ ✓
  - svelte              ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
$ nvim --version
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
Run "nvim -V1 -v" for more info
```

**Comment by Ax51** [comment]
Confirming this issue.
Trying to type `>` immediately after `<` causes nvim to freeze. Turning tree-sitter off resolves this issue. Tried to rollback tree-sitter to a random old commit and it doesn't solved this issue. I'm using MacOS Sequoia 15.1 and I tend to think that it could cause some problems since already faced with a bunch of random issues after upgrading MacOS.

Current setup:
 
- MacOS:
```
Sequoia 15.1
```
- neovim --version: 
```
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
```
- nvim-treesitter commit:
```
e1e3108
```

**Comment by crcrworks** [comment]
I solved!!!!!

$ brew uninstall neovim
$ brew uninstall tree-sitter
$ brew install neovim

The problem caused because of old tree-sitter-cli version remaining.
I solved deleting old them and reinstall neovim with tree-sitter as dependency

Thank you all for helping me.

**Comment by airRnot1106** [comment]
@crcrworks 
I am also facing the same problem. Can you tell me what version of Neovim and tree-sitter you used when you solved the problem?

**Comment by clason** [comment]
Version is irrelevant; if (and only if!) you use homebrew, you just need to follow the steps (homebrew patched their tree-sitter version so you don't have to wait for a new release).

**Comment by crcrworks** [comment]
@airRnot1106 

This is the versions:

$ tree-sitter --version
tree-sitter 0.24.4

$ nvim -v
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
Run "nvim -V1 -v" for more info

**Comment by airRnot1106** [comment]
@crcrworks 

Thank you!!
I'm not using Homebrew, so I'll update tree-sitter to v0.24.4 and see if that solves the problem.

**Comment by clason** [comment]
It does not; homebrew patched their version. But if you're not using homebrew, your Nvim 0.10.2 should not include the broken tree-sitter commit.

**Comment by airRnot1106** [comment]
But once I updated the tree-sitter version, the problem was solved. Anyway, thank you very much.
