### ISSUE TITLE
The commentstring for htmldjango is <!--%s--> but it should be {# %s #}

### ISSUE THREAD

**Issue by myarcana** [nvim-treesitter/nvim-treesitter#7355]
### Describe the bug

    :lua print(vim.filetype.get_option('htmldjango', 'commentstring'))

prints 

     

but it should be `{# %s #}`

This means `gcc` & co. don't work properly in django template files.

### To Reproduce

    :lua print(vim.filetype.get_option('htmldjango', 'commentstring'))

### Expected behavior

`{# %s #}`

### Output of `:checkhealth nvim-treesitter`

```markdown
Installation ~
- OK `tree-sitter` found 0.24.3 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v23.1.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 14.0.0 (clang-1400.0.29.202)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.


Parser/Features         H L F I J
  - html                ✓ ✓ ✓ ✓ ✓
  - htmldjango          ✓ . ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
```

### Output of `nvim --version`

```text
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
```

**Comment by clason** [comment]
Please report this to maintainer listed at the top of the django ftplugin in Vim, which is where this string is set.

**Comment by myarcana** [comment]
@clason I posted it here because I didn't think this string is set in https://github.com/interdependence/tree-sitter-htmldjango ; the HTML comment strings `<!--` don't appear anywhere at all in that repository.
