### ISSUE TITLE
highlight does not work in cpp standard file

### ISSUE THREAD

**Issue by qiyuewuyi2333** [nvim-treesitter/nvim-treesitter#7357]
### Describe the highlighting problem

I dont know it doesn't work in standard file . But it does work in the files with suffix like .cpp .h etc. 
And it will work if I change the file type to cpp, but you know, standard file couldn't be modify.

contex:
os: win11 
terminal: wezterm
framework: lazyvim
plugin_version: 6389ceb

### Example snippet that causes the problem

Images below:
![Image](https://github.com/user-attachments/assets/1416b2a1-24f9-4250-92de-bd3498a1db91)
![Image](https://github.com/user-attachments/assets/bceff81e-317e-4710-9cd1-6bd1eade4dea)

### Tree-sitter parsing result

![Image](https://github.com/user-attachments/assets/fa60785e-cf3e-4456-98d4-296e4dac8c85)
It doesn't work.

### Example screenshot

Images below:
![Image](https://github.com/user-attachments/assets/1416b2a1-24f9-4250-92de-bd3498a1db91)
![Image](https://github.com/user-attachments/assets/bceff81e-317e-4710-9cd1-6bd1eade4dea)

### Expected behavior

How to solve this problem? 
Please!

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v18.16.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: gcc (GCC) 15.0.0 20240908 (experimental)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.26100",
  sysname = "Windows_NT",
  version = "Windows 11 Home China"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cmake               ✓ . ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - diff                ✓ . ✓ . ✓
  - git_config          ✓ . ✓ . ✓
  - git_rebase          ✓ . . . ✓
  - gitattributes       ✓ ✓ . . ✓
  - gitcommit           ✓ . . . ✓
  - gitignore           ✓ . . . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - jsdoc               ✓ . . . .
  - json                ✓ ✓ ✓ ✓ .
  - json5               ✓ . . . ✓
  - jsonc               ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - luap                ✓ . . . .
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - printf              ✓ . . . .
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - regex               ✓ . . . .
  - ron                 ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - xml                 ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713484068

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

**Comment by clason** [comment]
I don't understand your problem. Please provide a precise, step-by-step, description we can follow with `nvim --clean -u test.lua` and a minimal(!) config file.

**Comment by qiyuewuyi2333** [comment]
> I don't understand your problem. What is a "standard file"?
> 
> Please provide a precise, step-by-step, description we can follow with `nvim --clean -u test.lua` and a minimal(!) config file.

I just use the lazyvim config in my windows 11 pc. And no more modify.

**Comment by clason** [comment]
Yes, but that doesn't help us. Again, what is a "standard file"?

**Comment by qiyuewuyi2333** [comment]
> Yes, but that doesn't help us. Again, what is a "standard file"?

like memory, string, etc. I show these in my images. These are cpp standard libary head files. But they don't have the suffix like .h. By the way, that's the reason I think they couldn't be highlight correctly.
