### ISSUE TITLE
nvim-treesitter hangs on large files without a way to fully disable

### ISSUE THREAD

**Issue by pipoprods** [nvim-treesitter/nvim-treesitter#7358]
### Describe the bug

Hi,

I've configured nvim-treesitter so that large files don't affect my nvim behavior as suggested in the docs:

```lua
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
    disable = function(lang, buf)
        local max_filesize = 100 * 1024 -- 100 KB
        local ok, stats = pcall(vim.loop.fs_stat, vim.api.nvim_buf_get_name(buf))
        if ok and stats and stats.size > max_filesize then
            return true
        end
    end,
  }
}
```

If I'm trying to inspect the tree, then Treesitter will run on the current file whatever its size.

This happens when using plugins that update `commentstring` according to Treesitter (eg JoosepAlviste/nvim-ts-context-commentstring or numToStr/Comment.nvim) and make nvim completely unusable to edit large files (eg 15k+ lines SQL file).

### To Reproduce

1. install nvim + nvim-treesitter + SQL grammar
2. open a large SQL file (15k+ lines)
3. call `vim.treesitter.inspect_tree()`
4. the editor gets stuck, using 100% CPU

### Expected behavior

Have no TS tree at all when a disabling condition is met.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.18.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Debian 12.2.0-14) 12.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.1.0-27-amd64",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Debian 6.1.115-1 (2024-11-01)"
} ~

Parser/Features         H L F I J
  - awk                 ✓ . . . ✓
  - bash                ✓ ✓ ✓ . ✓
  - blade               ✓ . ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - diff                ✓ . ✓ . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - http                ✓ . . . ✓
  - ini                 ✓ . ✓ . ✓
  - java                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - norg                . . . . .
  - perl                ✓ . ✓ . ✓
  - php                 ✓ ✓ ✓ ✓ ✓
  - php_only            ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - rst                 ✓ ✓ . . ✓
  - ruby                ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - sql                 ✓ . . ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - vue                 ✓ . ✓ ✓ ✓
  - xml                 ✓ ✓ ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713484068
```

### Additional context

nvim-treesitter rocks! Thanks a lot for this project 🙂

**Comment by pipoprods** [comment]
> you'll need to bring this up with each plugin directly

Which plugin are you refering to here? Do you mean treesitter-sql plugin or commentstring plugin?

It's not clear to me how I could deal with this problem outside of nvim-treesitter as none of the other plugins involved may be aware there's a disable rule somewhere.

**Comment by clason** [comment]
> Which plugin are you refering to here? Do you mean treesitter-sql plugin or commentstring plugin?

Any and all of them. Nvim-treesitter has a way of not attaching to large files; these have to come up with their own.

> It's not clear to me how I could deal with this problem outside of nvim-treesitter as none of the other plugins involved may be aware there's a disable rule somewhere.

Well, that's on them. Please believe me when I tell you that this is completely outside the possibilities of nvim-treesitter.
