### ISSUE TITLE
Delete motions in C++ files freeze Neovim (macOS)

### ISSUE THREAD

**Issue by javiersalcedopuyo** [nvim-treesitter/nvim-treesitter#7360]
### Describe the bug

After performing several delete motions, the neovim instance becomes unresponsive and requires killing the terminal window/tab.

I've only been able to reproduce this on C++ files.
I seems to happen everywhere but I believe it's more likely to occur inside string literals (might have been just chance though).
I also tested Swift and Lua files and it worked as expected (although on Swift it seemed to have some kind of delay).

### To Reproduce

1. Open a .cpp file
2. Move around and perform delete motions like `dw` and `d$`in different places of the file.
3. After a couple times Neovim becomes completely unresponsive.

### Expected behavior

I can perform delete motions without it freezing or slowing down Neovim.

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.24.4 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v23.1.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 16.0.0 (clang-1600.0.26.4)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "24.0.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 24.0.0: Tue Sep 24 23:36:30 PDT 2024; root:xnu-11215.1.12~1/RELEASE_X86_64"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - diff                ✓ . ✓ . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - swift               ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1727870382
Run "nvim -V1 -v" for more info
```

### Additional context

I'm on macOS 15.0, and I tested this on Alacritty and iTerm2. However, I couldn't reproduce it in the default Terminal app.
Worth noting that, for some reason, colorschemes do not work at all on my default Terminal (all text is the same color all the time).

**Comment by clason** [comment]
Duplicate; it's a tree-sitter bug that can be fixed by uninstallin and reinstalling `tree-sitter` with homebrew.
