### ISSUE TITLE
Higher latency than regex in latex

### ISSUE THREAD

**Issue by yashamon** [nvim-treesitter/nvim-treesitter#7366]
Platform windows 11. Neovim nightly. As measured in typometer with  treesitter latency is twice as high as with regex. I don't know if that's expected. I am in a latex buffer.

**Comment by clason** [comment]
It's expected.

**Comment by yashamon** [comment]
Interesting, is that a reality forever or temporary limitation? I thought treesitter was supposed to be more performant in principle.

**Comment by clason** [comment]
You thought wrong then. The reality is more complicated.

**Comment by yashamon** [comment]
Thanks for a nice explanation. Have a good day.
