### ISSUE TITLE
Select highlight group base on longest matching theme key

### ISSUE THREAD

**Issue by alemuller** [nvim-treesitter/nvim-treesitter#738]
Nvim-tree-sitter could have the same behavior on matching theme key as Tree-Sitter.

Excerpt from Tree Sitter 's [Syntax Highlighting](https://tree-sitter.github.io/tree-sitter/syntax-highlighting) documentation:

> #### Highlight Names
> 
> A theme can contain multiple keys that share a common subsequence. Examples:
> 
>  * `variable` and `variable.parameter`
>  * `function`, `function.builtin`, and `function.method`
> 
> For a given highlight produced, styling will be determined based on the **longest matching theme key**. For example, the highlight `function.builtin.static` would match the key `function.builtin` rather than function.

This feature would make easier for the end users to customize their highlighting without the need to add or change rules on `highlights.scm`. At same time, matching the longest valid theme key, would provide a sane default (instead of failing to apply any highlight).

**Comment by vigoux** [comment]
Oh that's interesting... This would also allow to directly use parsers highlight queries, which is great.

**Comment by alemuller** [comment]
I found an workaround that might be useful for others struggling with the same thing.

It seems nvim-ts allows to set more than one theme key per rule. For example:

```scm
(entity_declaration
   (identifier) @constant @constant.entity)
```

This will identifier with  `@constant` and `@constant.entity` in that order.
