### ISSUE TITLE
Is it possible, to apply treesitter to terminal-mode buffers?

### ISSUE THREAD

**Issue by bqv** [nvim-treesitter/nvim-treesitter#7388]
If not, could it be? 

An attempt now (by setting a reasonable filetype) does seem to work (highlights), but doesn't update on new text. 

I couldn't find any reliable way to trigger an update, let alone a way to make that happen every time the terminal output is updated.

**Comment by clason** [comment]
It's not, and it doesn't really make sense (sorry).

**Comment by nounder** [comment]
@clason Any chance to reconsider it? Although syntax highlighting in terminal doesn't make sense, having treesitter in terminal buffer would be very useful for selection in visual mode.
