### ISSUE TITLE
extend html and css to other "filetypes"

### ISSUE THREAD

**Issue by carlitux** [nvim-treesitter/nvim-treesitter#74]
I just saw that CSS and HTML were added.

I like to know if there is a way to use SCSS as CSS?

I like to know if there is a way to use HTML for https://github.com/tweekmonster/django-plus.vim or any other template engine?

**Comment by kyazdani42** [comment]
I guess you could change the filetype of files if you want to do that kind of stuff. At the moment language injection is not yet integrated into neovim's api so we cannot really move forward on this matter.
I'll have more free time soon, and ill try to look at that part of the api as it would be really great to have this in nvim :)

**Comment by theHamsta** [comment]
Usually, you want to embed another language via the `@inject.language` query. @vigoux is currently implementing this in neovim.

I created a parser for jinja2 which could be used in future to separate outer python code, templates and template instructions (`{% for foo in bar %}`).
