### ISSUE TITLE
Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by ADiamondChanger** [nvim-treesitter/nvim-treesitter#7402]
### Describe the bug

I was minding my OWN BUSINESS when the fuzz walked by...

The error:
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/treesitter.lua:421: Parser could not be created for bugger 29 and language "markdown" stack traceback: [C]: in function 'assert' /usr/share/nvim/runtime/lua/vim/treesitter.lua:421: in function 'start' /usr/share/nvim/runtime/lua/vim/lsp/uti;.lua:1570: in function 'open_floating_preview' /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:465: in function 'signature_help' /username/.local/share/nvim/lazy/ui/lua/nvchad/signature.lua:7: in function 'handler' /usr/share/nvim/runtime/lua/vim/lsp/client.lua:681: in function '' vim/_editor.lua: in function <vim/_editor.lua:0> Press ENTER or type command to continue

### To Reproduce

1. Open neovim
2. Open any file
3. Do really anything that requires memory; remove a letter, insert a letter.

### Expected behavior

No error.

### Output of `:checkhealth nvim-treesitter`

![Image](https://github.com/user-attachments/assets/808ccbed-d326-478c-999c-2130a53f82ac)

### Output of `nvim --version`

NVIM v0.11.0-dev                                                                                                                                                                              
Build type: RelWithDebInfo                                                                                                                                                                    
LuaJIT 2.1.1703358377                                                                                                                                                                         
Run ":verbose version" for more info

**Comment by clason** [comment]
Your Neovim installation is broken; the markdown parsers should be installed by default.

**Comment by ADiamondChanger** [comment]
so what do I do?
