### ISSUE TITLE
attempt to call method 'parent' (a nil value)

### ISSUE THREAD

**Issue by gramblerz** [nvim-treesitter/nvim-treesitter#7404]
### Describe the bug

vim-illuminate: An internal error has occured: false".../lazy/opt/nvim-treesitter/lua/
nvim-treesitter/locals.lua:286: attempt to call method 'parent' (a nil value)" 

Error in decoration provider treesitter/highlighter.line:                                                                                                                     
Error executing lua: ...nvim-treesitter/lua/nvim-treesitter/query_predicates.lua:80: attempt to call method 'parent' (a nil value)                                            
stack traceback:                                                                                                                                                              
        ...nvim-treesitter/lua/nvim-treesitter/query_predicates.lua:80: in function 'handler'                                                                                 
        /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:757: in function 'fn'                                                                                      
        /usr/local/share/nvim/runtime/lua/vim/func/_memoize.lua:56: in function 'match_preds'                                                                                 
        /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:873: in function 'iter'                                                                                    
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:303: in function 'fn'                                                                                     
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:210: in function 'for_each_highlight_state'                                                               
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:284: in function 'on_line_impl'                                                                           
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:360: in function <...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:354>                        
Press ENTER or type command to continue       

### To Reproduce

open file.

### Expected behavior

no error

### Output of `:checkhealth nvim-treesitter`

```markdown
Error in decoration provider treesitter/highlighter.line:                                                                                                                     
Error executing lua: ...nvim-treesitter/lua/nvim-treesitter/query_predicates.lua:80: attempt to call method 'parent' (a nil value)                                            
stack traceback:                                                                                                                                                              
        ...nvim-treesitter/lua/nvim-treesitter/query_predicates.lua:80: in function 'handler'                                                                                 
        /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:757: in function 'fn'                                                                                      
        /usr/local/share/nvim/runtime/lua/vim/func/_memoize.lua:56: in function 'match_preds'                                                                                 
        /usr/local/share/nvim/runtime/lua/vim/treesitter/query.lua:873: in function 'iter'                                                                                    
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:303: in function 'fn'                                                                                     
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:210: in function 'for_each_highlight_state'                                                               
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:284: in function 'on_line_impl'                                                                           
        ...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:360: in function <...al/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:354>                        
Press ENTER or type command to continue
```

### Output of `nvim --version`

```text
NVIM v0.11.0-dev-beec377
Build type: Release
LuaJIT 2.1.1731601260
Run "nvim -V1 -v" for more info
```

**Comment by clason** [comment]
Make sure your plugin(s) is/are updated. [There is no call to `parent` in the stated location](https://github.com/nvim-treesitter/nvim-treesitter/blob/d14bc4bd15a7b9b5a9e7977c6a28f2cab6c4ad4a/lua/nvim-treesitter/query_predicates.lua#L80).

**Comment by Tylerwbrown** [comment]
Having the same error, except I see the line in master: https://github.com/nvim-treesitter/nvim-treesitter/blob/066fd6505377e3fd4aa219e61ce94c2b8bdb0b79/lua/nvim-treesitter/locals.lua#L286

my plugins are up to date, exact error is:
```
vim-illuminate: An internal error has occured: false".../lazy/opt/nvim-treesitter/lua/nvim-treesitter/locals.lua:286: attempt to call method 'parent' (a nil value)"
```

Using lunarvim for what it's worth.
