### ISSUE TITLE
Cannot match available nodes in treesitter query

### ISSUE THREAD

**Issue by Ginner** [nvim-treesitter/nvim-treesitter#7410]
### Describe the bug

I am unable to match/query against nodes that are clearly visible in the syntax tree when inspected with :InspectTree in Neovim. 
Despite these nodes being present in the parsed syntax tree, attempts to include them in a treesitter query result in `invalid node type` errors.

This [video](https://github.com/user-attachments/assets/4f6df611-506e-41fa-a5c3-96e6e69b44bd) shows some nodes being matched as expected, while `shortcut_link` and `link_text` cannot be matched. In the video the full syntax tree is visible.

### To Reproduce

Create a markdown todolist like this:
```
# Test todo_list

- [-] Todo item 1
- [ ] Todo item 3
```
Run `:InspectTree` to see the treesitter tree. Run `:EditQuery` to write queries to match against the nodes.

`((link_text) @foo)` will give a 'Invalid node type` error. 

### Expected behavior

I'd expect to be able to match against any node in the tree. 

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.24.3 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.18.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: gcc (GCC) 13.3.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.6.62",
  sysname = "Linux",
  version = "#1-NixOS SMP PREEMPT_DYNAMIC Sun Nov 17 14:08:59 UTC 2024"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - nix                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713773202
```

### Additional context

I'm new to treesitter in general, so excuse any assumptions. Please let me know if this is not the right place to report (is it a markdown grammar specific issue?).

**Comment by Ginner** [comment]
Maybe I should've have mentioned: I'm specifically trying to resolve the issue mentioned [here](https://github.com/tree-sitter-grammars/tree-sitter-markdown/issues/78), but I can't find, that @aleksey-rowan should have opened an issue here.

However, I intend on using the functionality for additional stuff (more check-mark types) in addition to the linked issue.

**Comment by clason** [comment]
By default, `:EditQuery` works on the top-level tree (`markdown` in this case) **only**, so you can't query any injected nodes (`(link_text)`, which is handled by `markdown_inline`'s parser). You need to explicitly specify `:EditQuery markdown_inline` if you want to target an injected language.

**Comment by Ginner** [comment]
Thank you! And thank you for your work on the project!
