### ISSUE TITLE
Failed to load parser for language 'go': uv_dlopen: no error

### ISSUE THREAD

**Issue by huahuaid** [nvim-treesitter/nvim-treesitter#7441]
### Describe the highlighting problem

As a Windows user, I encounter the following error when using Treesitter:

"The following errors have been detected:

ERROR go(highlights): F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'go': uv_dlopen reported no error, but the parser did not load.
The go(highlights) query is concatenated from the following file:
| [ERROR]: 'C:\Users\86159\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\go\highlights.scm'. Failed to load due to: F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'go': uv_dlopen reported no error, but the issue persists.
This problem occurs for every language I try to use with Treesitter."

### Example snippet that causes the problem

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found (unknown version) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.15.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: gcc (MinGW.org GCC-6.3.0-1) 6.3.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.22631",
  sysname = "Windows_NT",
  version = "Windows 11 Home China"
} ~

Parser/Features         H L F I J
  - go                  x x x x x
  - vim                 x x x . x

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR go(highlights): F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'go': uv_dlopen: no error
  go(highlights) is concatenated from the following files:
  | [ERROR]:"C:\Users\86159\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\go\highlights.scm", failed to load: F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'go': uv_dlopen: no error
- ERROR go(locals): F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'go': uv_dlopen: no error
  go(locals) is concatenated from the following files:
  | [ERROR]:"C:\Users\86159\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\go\locals.scm", failed to load: F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'go': uv_dlopen: no error
- ERROR go(folds): F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'go': uv_dlopen: no error
  go(folds) is concatenated from the following files:
  | [ERROR]:"C:\Users\86159\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\go\folds.scm", failed to load: F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'go': uv_dlopen: no error
- ERROR go(indents): F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'go': uv_dlopen: no error
  go(indents) is concatenated from the following files:
  | [ERROR]:"C:\Users\86159\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\go\indents.scm", failed to load: F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'go': uv_dlopen: no error
- ERROR go(injections): F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'go': uv_dlopen: no error
  go(injections) is concatenated from the following files:
  | [ERROR]:"C:\Users\86159\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\go\injections.scm", failed to load: F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'go': uv_dlopen: no error
- ERROR vim(highlights): F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'vim': uv_dlopen: no error
  vim(highlights) is concatenated from the following files:
  | [ERROR]:"C:\Users\86159\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\vim\highlights.scm", failed to load: F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'vim': uv_dlopen: no error
- ERROR vim(locals): F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'vim': uv_dlopen: no error
  vim(locals) is concatenated from the following files:
  | [ERROR]:"C:\Users\86159\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\vim\locals.scm", failed to load: F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'vim': uv_dlopen: no error
- ERROR vim(folds): F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'vim': uv_dlopen: no error
  vim(folds) is concatenated from the following files:
  | [ERROR]:"C:\Users\86159\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\vim\folds.scm", failed to load: F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'vim': uv_dlopen: no error
- ERROR vim(injections): F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'vim': uv_dlopen: no error
  vim(injections) is concatenated from the following files:
  | [ERROR]:"C:\Users\86159\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\vim\injections.scm", failed to load: F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'vim': uv_dlopen: no error

### Tree-sitter parsing result

chunk ; [0, 0] - [14, 0]
  (function_call ; [0, 0] - [13, 1]
    name: (dot_index_expression ; [0, 0] - [0, 38]
      table: (function_call ; [0, 0] - [0, 32]
        name: (identifier) ; [0, 0] - [0, 7]
        arguments: (arguments ; [0, 7] - [0, 32]
          (string ; [0, 7] - [0, 32]
            content: (string_content)))) ; [0, 8] - [0, 31]
      field: (identifier)) ; [0, 33] - [0, 38]
    arguments: (arguments ; [0, 39] - [13, 1]
      (table_constructor ; [0, 39] - [13, 1]
        (comment ; [1, 2] - [1, 39]
          content: (comment_content)) ; [1, 4] - [1, 39]
        (field ; [2, 2] - [2, 28]
          name: (identifier) ; [2, 2] - [2, 18]
          value: (table_constructor ; [2, 21] - [2, 28]
            (field ; [2, 22] - [2, 27]
              value: (string ; [2, 22] - [2, 27]
                content: (string_content))))) ; [2, 23] - [2, 26]
        (comment ; [2, 30] - [2, 68]
          content: (comment_content)) ; [2, 32] - [2, 68]
        (field ; [4, 2] - [4, 31]
          name: (identifier) ; [4, 2] - [4, 11]
          value: (table_constructor ; [4, 14] - [4, 31]
            (field ; [4, 16] - [4, 29]
              name: (identifier) ; [4, 16] - [4, 22]
              value: (true)))) ; [4, 25] - [4, 29]
        (field ; [5, 2] - [5, 28]
          name: (identifier) ; [5, 2] - [5, 8]
          value: (table_constructor ; [5, 11] - [5, 28]
            (field ; [5, 13] - [5, 26]
              name: (identifier) ; [5, 13] - [5, 19]
              value: (true)))) ; [5, 22] - [5, 26]
        (comment ; [7, 2] - [7, 29]
          content: (comment_content)) ; [7, 4] - [7, 29]
        (field ; [8, 2] - [12, 3]
          name: (identifier) ; [8, 2] - [8, 9]
          value: (table_constructor ; [8, 12] - [12, 3]
            (field ; [9, 4] - [9, 17]
              name: (identifier) ; [9, 4] - [9, 10]
              value: (true)) ; [9, 13] - [9, 17]
            (field ; [10, 4] - [10, 24]
              name: (identifier) ; [10, 4] - [10, 17]
              value: (true)) ; [10, 20] - [10, 24]
            (field ; [11, 4] - [11, 24]
              name: (identifier) ; [11, 4] - [11, 18]
              value: (nil)))))))) ; [11, 21] - [11, 24]

### Example screenshot

![Image](https://github.com/user-attachments/assets/58cb2d59-6cd7-43fd-a363-2eb1c8476ab7)

![Image](https://github.com/user-attachments/assets/f0c3340d-e4c0-4704-8315-a043f15ff0d9)

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found (unknown version) (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v20.15.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: gcc (MinGW.org GCC-6.3.0-1) 6.3.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "10.0.22631",
  sysname = "Windows_NT",
  version = "Windows 11 Home China"
} ~

Parser/Features         H L F I J
  - go                  x x x x x
  - vim                 x x x . x

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

The following errors have been detected: ~
- ERROR go(highlights): F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'go': uv_dlopen: no error
  go(highlights) is concatenated from the following files:
  | [ERROR]:"C:\Users\86159\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\go\highlights.scm", failed to load: F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'go': uv_dlopen: no error
- ERROR go(locals): F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'go': uv_dlopen: no error
  go(locals) is concatenated from the following files:
  | [ERROR]:"C:\Users\86159\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\go\locals.scm", failed to load: F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'go': uv_dlopen: no error
- ERROR go(folds): F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'go': uv_dlopen: no error
  go(folds) is concatenated from the following files:
  | [ERROR]:"C:\Users\86159\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\go\folds.scm", failed to load: F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'go': uv_dlopen: no error
- ERROR go(indents): F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'go': uv_dlopen: no error
  go(indents) is concatenated from the following files:
  | [ERROR]:"C:\Users\86159\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\go\indents.scm", failed to load: F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'go': uv_dlopen: no error
- ERROR go(injections): F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'go': uv_dlopen: no error
  go(injections) is concatenated from the following files:
  | [ERROR]:"C:\Users\86159\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\go\injections.scm", failed to load: F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'go': uv_dlopen: no error
- ERROR vim(highlights): F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'vim': uv_dlopen: no error
  vim(highlights) is concatenated from the following files:
  | [ERROR]:"C:\Users\86159\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\vim\highlights.scm", failed to load: F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'vim': uv_dlopen: no error
- ERROR vim(locals): F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'vim': uv_dlopen: no error
  vim(locals) is concatenated from the following files:
  | [ERROR]:"C:\Users\86159\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\vim\locals.scm", failed to load: F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'vim': uv_dlopen: no error
- ERROR vim(folds): F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'vim': uv_dlopen: no error
  vim(folds) is concatenated from the following files:
  | [ERROR]:"C:\Users\86159\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\vim\folds.scm", failed to load: F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'vim': uv_dlopen: no error
- ERROR vim(injections): F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'vim': uv_dlopen: no error
  vim(injections) is concatenated from the following files:
  | [ERROR]:"C:\Users\86159\AppData\Local\nvim-data\lazy\nvim-treesitter\queries\vim\injections.scm", failed to load: F:/Nvim/share/nvim/runtime/lua/vim/treesitter/language.lua:112: Failed to load parser for language 'vim': uv_dlopen: no error
```

### Output of `nvim --version`

```text
 86159@DESKTOP-1UOAP6H ~  master nvim --version
NVIM v0.10.2
Build type: Release
LuaJIT 2.1.1713484068
Run "nvim -V1 -v" for more info
```

### Additional context

I want solve this problem

**Comment by clason** [comment]
Duplicate. Please search closed issues as well. (Your gcc is too old.)
