### ISSUE TITLE
Question: Why does this highlight apply?

### ISSUE THREAD

**Issue by mister-choo** [nvim-treesitter/nvim-treesitter#7446]
Sorry if this is an inappropriate place to ask this.
So I have this situation:
```cpp
TSLanguage *get_language_from_so(void *handle, const std::string &language);
```
Let's examine *handle highlight. 
To "\*" applies   
- @variable.parameter.cpp links to @variable.parameter cpp
- @operator.cpp links to Operator cpp

But highlight ends up as @operator.cpp
To "handle" applies 
  - @variable.parameter.cpp links to @variable.parameter cpp
  - @variable.cpp links to @variable cpp
 
But highlight ends up as @variable.parameter.cpp

I can't deduce why operator.cpp superseded the variable.parameter.cpp
In queries I didn't see any setting of priorities or other things like that
From my point of view in should either be:
1. variable.parameter.cpp for both (more specific capture)
or
2.  operator.cpp for "\*" and variable.cpp for "handle" (smaller captures)

So how does this work?

**Comment by clason** [comment]
> I can't deduce why operator.cpp superseded the variable.parameter.cpp

That's how it's supposed to work: last applied highlight "wins" -- and matching patterns are applied in the order in which they appear in the query file.

> But highlight ends up as @variable.parameter.cpp

How do you know that?

**Comment by clason** [comment]
In this case, it's probably because in the second example, the `@variable` pattern comes from the inherited `c` queries, not the `cpp` queries, while in the first case both patterns come from the `c` queries.

**Comment by mister-choo** [comment]
I'm dumb. Found this in the c queries: 
```
((identifier) @variable
  (#set! priority 95))
```
variable priority is deliberately lowered

**Comment by clason** [comment]
Hmm, `:Inspect` should show the priority. Apparently (no longer) for treesitter highlights. Can you open an issue at Neovim?

**Comment by mister-choo** [comment]
> ....matching patterns are applied in the order in which they appear in the query file.
Do you by chance know if it's enforced by treesitter api - ts_query_cursor_next_match - or is it specifically a neovim thing?

**Comment by clason** [comment]
It's just how the highlighter works (not just in Neovim); you can either bail on the first match (Helix) or apply all matches (everybody else).
