### ISSUE TITLE
Errors when opening files to do with extracting treesitter parsers _every time_

### ISSUE THREAD

**Issue by gfarrell** [nvim-treesitter/nvim-treesitter#7454]
### Describe the bug

I get the following sorts of errors when opening typescript files:
![Image](https://github.com/user-attachments/assets/f160e108-5f10-4d51-9bde-8d4bb19df9a3)
![Image](https://github.com/user-attachments/assets/ff83b01f-8a78-4ad1-8c5e-113cd0a1115b)

This sometimes messes with the highlighting of newly opened files.

### To Reproduce

1. Open nvim
2. Open a typescript file
3. Get errors

### Expected behavior

No errors and working highlighting

### Output of `:checkhealth nvim-treesitter`

```markdown
==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v20.15.1 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `gcc` executable found. Selected from { "gcc", "cc", "gcc", "clang", "cl", "zig" }
  Version: gcc (GCC) 13.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "6.6.63-1-lts",
  sysname = "Linux",
  version = "#1 SMP PREEMPT_DYNAMIC Fri, 22 Nov 2024 15:39:56 +0000"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - git_rebase          ✓ . . . ✓
  - gitcommit           ✓ . . . ✓
  - haskell             ✓ ✓ ✓ . ✓
  - ini                 ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - nix                 ✓ ✓ ✓ ✓ ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - sql                 ✓ . . ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.10.2
Build type: RelWithDebInfo
LuaJIT 2.1.1731601260
Run "nvim -V1 -v" for more info
```

### Additional context

* I have run `:TSUpdate` and I have checked the troubleshooting section.
* I have installed nvim-treesitter using lazy.nvim

**Comment by gfarrell** [comment]
Incidentally I checked the tarball, and it extracts fine (with `tar -xvzf`). Running `:TSUpdate typescript` after all the failures did seem to resolve the issue. IDK if there's a wider bug here around either recovering from this sort of failure or something with the installation process so I'll leave it open for now.

**Comment by clason** [comment]
No, just a race condition or a stale temporary directory. Without reproducible details (which are hard to provide, I understand) there's little we can do. So I would prefer closing this now and reopening if and when there is a reproducible scenario.
