### ISSUE TITLE
Double parser downloads with auto_install=true and ft defined in nvim-lspconfig

### ISSUE THREAD

**Issue by AndreasNasman** [nvim-treesitter/nvim-treesitter#7465]
### Describe the bug

If you have `auto_installed = true` set in your [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) config and `ft` configured in [neovim/nvim-lspconfig](https://github.com/neovim/nvim-lspconfig), Treesitter parsers are downloaded twice simultaneously when installed, causing an error.

![image](https://github.com/user-attachments/assets/b59f1b2b-1590-4633-bc2c-74f25c19905b)

```log
[nvim-treesitter] [0/2] Downloading tree-sitter-typescript...                                                                                                            
[nvim-treesitter] [0/2] Downloading tree-sitter-typescript...                                                                                                            
[nvim-treesitter] [0/2] Creating temporary directory                                                                                                                     
[nvim-treesitter] [0/2] Extracting tree-sitter-typescript...                                                                                                             
[nvim-treesitter] [0/2] Compiling...                                                                                                                                     
[nvim-treesitter] [0/2] Creating temporary directory                                                                                                                     
[nvim-treesitter] [0/2] Extracting tree-sitter-typescript...                                                                                                             
nvim-treesitter[typescript]: Error during tarball extraction.                                                                                                            
tar: Error opening archive: Failed to open 'tree-sitter-typescript.tar.gz'                                                                                               
```

The error can be either of the two above or a success in some rare cases, mostly likely due to the timing of the race condition.

I use this Treesitter and lspconfig configuration since I only want to enable LSP for specific file types and want to auto-download Treesitter parsers. I regularly use VMs where I set up Neovim from scratch, and I receive these errors for every parser installed.

### To Reproduce

1. Choose a file type you don't have a treesitter parser installed, say `javascript`.
2. Open a file of the chosen type, which triggers downloading the Treesitter parser, e.g., `nvim -u repro.lua test.js`.
3. Two processes will start downloading the Treesitter parser, causing a race condition and, most likely, an error.

```lua
-- repro.lua
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not (vim.uv or vim.loop).fs_stat(lazypath) then
    local lazyrepo = 'https://github.com/folke/lazy.nvim.git'
    local out = vim.fn.system({ 'git', 'clone', '--filter=blob:none', '--branch=stable', lazyrepo, lazypath })
    if vim.v.shell_error ~= 0 then
        error('Error cloning lazy.nvim:\n' .. out)
    end
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
    defaults = {
        lazy = false,
    },
    spec = {
        {
            'neovim/nvim-lspconfig',
            ft = { 'javascript' },
        },
        {
            'nvim-treesitter/nvim-treesitter',
            build = ':TSUpdate',
            main = 'nvim-treesitter.configs',
            opts = { auto_install = true },
        },
    },
})
```

### Expected behavior

Only one process should download the Treesitter parser.

### Output of `:checkhealth nvim-treesitter`

```markdown
nvim-treesitter:                     require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.24.5 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v23.3.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 16.0.0 (clang-1600.0.26.4)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "23.6.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 23.6.0: Thu Sep 12 23:36:55 PDT 2024; root:xnu-10063.141.1.701.1~1/RELEASE_ARM64_T8112"
} ~

Parser/Features         H L F I J
  - c                   ✓ ✓ ✓ ✓ ✓
  - csv                 ✓ . . . .
  - dockerfile          ✓ . . . ✓
  - fish                ✓ ✓ ✓ ✓ ✓
  - git_config          ✓ . ✓ . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - luadoc              ✓ . . . .
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - perl                ✓ . ✓ . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - toml                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~
```

### Output of `nvim --version`

```text
NVIM v0.11.0-dev-4456+g517ecb85f5-Homebrew
Build type: Release
LuaJIT 2.1.1732813678
Run "nvim -V1 -v" for more info
```

### Additional context

Most likely related to #4680.

Original bug report when I thought it was an issue with lazy.nvim: https://github.com/folke/lazy.nvim/issues/1832 and folke's reply:

> This is not a lazy issue. It can happen that FileType events need to be triggered twice like in this case.
It triggered when opening a JS file and that caused to load your lspconfig spec.
Then we need to trigger the FT again, to make sure lspconfig knows about it.
>
> nvim-treesitter should be fixed to not try installing a parser again if it's already installing the parser for that FT

**Comment by clason** [comment]
Sorry, but we do not support lazy loading. If you can't reproduce this without lazy.nvim, we can't do anything about it.

**Comment by AndreasNasman** [comment]
I modified `repro.lua` to include `defaults = { lazy = false }`, making Treesitter load without lazy loading, and I'm able to reproduce the issue. `nvim-lspconfig` still lazy loads with `ft`, is that causing the problem (and is unsupported)?

**Comment by clason** [comment]
>  nvim-lspconfig still lazy loads with ft, is that causing the problem (and is unsupported)?

You have to bring that up with `nvim-lspconfig`, sorry; I'm not involved in that project. It would really help to have a minimal reproducing example without any other plugin. (You can trigger autocommands manually.)

**Comment by AndreasNasman** [comment]
I'm not sure what autocommands I should trigger manually to reproduce the issue that `nvim-lspconfig` causes.

I'll add more parsers to `ensure_installed` (which causes no error), manually install failing parsers, and close this issue.

**Comment by faergeek** [comment]
Shouldn't this be reopened?

The issue is related to lazy loading, but it's not about supporting lazy loading nvim-treesitter itself.

lazy.nvim supports loading plugins on `FileType` event. To achieve that it triggers `FileType` the second time after adding a plugin so that it has a chance to handle the event itself.

As a result `FileType` autocommand that nvim-treesitter uses for auto-install gets triggered twice in a quick succession, starting installation twice for the same parser, which results in an error being shown, even though the first installation usually succeeds just fine despite it. It's just a bit annoying to see these errors when visiting a buffer which doesn't have a parser installed yet.

The simplest solution would be to perform auto-installation in a blocking way so on a second trigger it will see the parser is already there and do nothing:

```diff
diff --git a/lua/nvim-treesitter/install.lua b/lua/nvim-treesitter/install.lua
index cd12dbb81..78b4f0159 100644
--- a/lua/nvim-treesitter/install.lua
+++ b/lua/nvim-treesitter/install.lua
@@ -558,7 +558,7 @@ function M.setup_auto_install()
   local function try_install_curr_lang()
     local lang = parsers.get_buf_lang()
     if parsers.get_parser_configs()[lang] and not is_installed(lang) and not is_ignored_parser(lang) then
-      install() { lang }
+      install { with_sync = true } { lang }
     end
   end
 

```

Would this be an acceptable solution?

Another solution would be to introduce a way to place a lock on a parser once installation has started, which will just skip starting a new installation and will also fix #4680 as a result.

**Comment by clason** [comment]
> lazy.nvim supports loading plugins on FileType event

Yes, and we don't. Also, the whole installation routine has been rewritten for 1.0, and all this further encourages me to drop not just auto install but also "bootstrapping" from the setup call.

**Comment by faergeek** [comment]
>Yes, and we don't

There's no need to.

Not sure how much this is useful going forward, but just to make it clear here's a way to reproduce the issue:

1. Create `minimal_init.lua` inside nvim-treesitter repo root with this contents:

    ```lua
    vim.opt.runtimepath:append "."
    
    require("nvim-treesitter.configs").setup {
      auto_install = true,
      indent = { enable = true },
      highlight = { enable = true },
    }
    
    -- let's pretend this is some plugin's module
    local some_plugin = {
      setup = function()
        vim.api.nvim_create_autocmd("FileType", {
          pattern = "lua",
          callback = function()
            -- do some plugin-specific things
          end,
        })
      end,
    }
    
    -- this is roughly how it could be lazy loaded based on a filetype
    vim.api.nvim_create_autocmd("FileType", {
      once = true,
      nested = true,
      callback = function()
        -- let it set up it's autocommands
        some_plugin.setup()
        -- let's make sure these autocommands get triggered
        vim.cmd.doautocmd "FileType"
      end,
    })
    ```

2. Run `nvim --clean -u minimal_init.lua minimal_init.lua`. It should start installing lua parser twice, resulting in an error being shown.

`FileType` gets triggered twice in a row similar to how lazy.nvim would do it.

Is it considered inappropriate to trigger a `FileType` event using `:doautocmd` from another `FileType` event? Neovim allows it.

>all this further encourages me to drop not just auto install but also "bootstrapping" from the setup call.

Dropping auto install sounds reasonable as long as there is some way for it to be implemented on the user side. By "bootstrapping" you mean supporting `ensure_installed` or something else?

**Comment by clason** [comment]
> Is it considered inappropriate to trigger a FileType event using :doautocmd from another FileType event? Neovim allows it.

Sure, but _this_ plugin doesn't support it. You're on your own if you want to lazy-load.

> Dropping auto install sounds reasonable as long as there is some way for it to be implemented on the user side. By "bootstrapping" you mean supporting ensure_installed or something else?

Yes. `ensure_installed` will be removed; you can still call `install(langs)` manually (which is a no-op if all languages are already installed). For "bootstrapping", use an external script to make the procedure synchronous.
