### ISSUE TITLE
Different ordering of compilers based on the current platform

### ISSUE THREAD

**Issue by Poundednote** [nvim-treesitter/nvim-treesitter#7499]
I have recently run into a problem with treesitter on windows specifically. The way treesitter chooses its compilers is it just pulls the first one from the environment the order is found in the below code snippet

`M.compilers = { vim.fn.getenv "CC", "cc", "gcc", "clang", "cl", "zig" }`
Any Windows users that are using something like MYSYS or CYGWIN may have gcc on the path such as myself and tree-sitter will use cc (common alias for gcc) or gcc first. The parsers I have tested c, cpp when compiled with gcc on Windows just cause a flat-out crash of neovim when attempting to open up any .cpp or .c file. Admittedly I haven't tested every single parser but I think is down to compiling using the platform's incorrect compiler.

More sensible behaviour would be to check for the Windows platform and reorder the M.compilers to something more sensible like 
`M.compilers = { vim.fn.getenv "cl", "clang", ...}`

**Comment by clason** [comment]
We are dropping the whole manual compiler selection for 1.0 (`main` branch) anyway, in favor of relying on `tree-sitter build` (since the CLI is required for an increasing number of parsers anyway).

**Comment by Poundednote** [comment]
> We are dropping the whole manual compiler selection for 1.0 (`main` branch) anyway, in favor of relying on `tree-sitter build` (since the CLI is required for an increasing number of parsers anyway).

Good news thanks for the response :)
