### ISSUE TITLE
language parsers are not installing 

### ISSUE THREAD

**Issue by siduck76** [nvim-treesitter/nvim-treesitter#760]
Ive installed treesitter plugin in nvim nightly and I get this while installing any parser like :  

:TSInstall css gives me this 

![image](https://user-images.githubusercontent.com/59060246/101979943-7a988700-3c87-11eb-85e0-11973f900a98.png)

my nvim version 

![image](https://user-images.githubusercontent.com/59060246/101979931-59379b00-3c87-11eb-9223-6db8c01b9fa4.png)

**Comment by theHamsta** [comment]
Hey, I just wanted to fix this bug. I guess this is related to https://github.com/nvim-treesitter/nvim-treesitter/issues/744 the fix by vim was to raise an error on `vim.fn.executable(vim.NIL)` (before it would convert to a string).

Can you check whether adding a check `~= vim.NIl` in `select_executable` would fix the problem? Does `export CC=gcc` change the situation?

**Comment by siduck76** [comment]
thanks! export CC=gcc worked fixed it

**Comment by theHamsta** [comment]
Would this also fix it: https://github.com/nvim-treesitter/nvim-treesitter/pull/761 ? @siduck76

**Comment by siduck76** [comment]
do I need to update the plugin?

**Comment by theHamsta** [comment]
You can apply that mini-change locally or checkout the branch of that PR.

**Comment by siduck76** [comment]
how do I change it locally? I installed treesitter via vim plug.

**Comment by theHamsta** [comment]
There should be a `plugged` folder some where in `~/.local/share/nvim/.../plugged`. Maybe it also works if you change it to 
Plug 'nvim-treesitter/nvim-treesitter', { 'commit': 'xxxxxcommitofthatpr' }

**Comment by siduck76** [comment]
![image](https://user-images.githubusercontent.com/59060246/101981262-8b4dfa80-3c91-11eb-8f01-8b1f29385b27.png) 
![image](https://user-images.githubusercontent.com/59060246/101981268-91dc7200-3c91-11eb-90b4-0d55640233a1.png)

**Comment by theHamsta** [comment]
maybe 'theHamsta/nvim-treesitter' (requires a PlugClean, usually Github does not have the concept of forks on commit level)

**Comment by siduck76** [comment]
oh that doesnt work . export CC=gcc temporarily works
