### ISSUE TITLE
syntax highlighting of some languages randomly  only work

### ISSUE THREAD

**Issue by siduck76** [nvim-treesitter/nvim-treesitter#762]
I have html , css and js parsers  installed and only some of it works and this is my config 
![image](https://user-images.githubusercontent.com/59060246/101982677-b9d0d300-3c9b-11eb-98ab-7ea57f6d7bcd.png)

https://www.youtube.com/watch?v=VsZjhPYdf4A ( the odd behaviour of only js working with config and html /css working without config )

**Comment by kyazdani42** [comment]
if you disable setup of course it won't highlight anymore and use the base vim regex based highlighting, which is why js looks so empty. Also doesn't look like your html and css are not highlighted using treesitter. Maybe your colorscheme needs to be adapted ?

**Comment by siduck76** [comment]
yeah but if I enable all ( html , css , js ) with treesitter then only JS would work :l

**Comment by kyazdani42** [comment]
i use html css, js, ts ,tsx and jsx almost every day and everything works as expected. Do you have all parsers installed for sure ? Is your colorscheme well configured ? What are your neovim version / nvim-treesitter version ?

**Comment by siduck76** [comment]
yea I have all parsers installed , and nvm it works today after a reboot
