### ISSUE TITLE
Lua null value error when opening Neovim

### ISSUE THREAD

**Issue by sidmadala** [nvim-treesitter/nvim-treesitter#781]
**Describe the bug**
I get the following error when opening Neovim with the most recent version of nvim-treesitter installed.

<img width="1428" alt="Screen Shot 2020-12-18 at 5 29 12 PM" src="https://user-images.githubusercontent.com/22417141/102667352-20039d00-4157-11eb-9ff2-c867671209d5.png">

**To Reproduce**
1. Install nvim-treesitter with Packer.nvim
2. Run `:PackerSync`
3. Close Neovim
4. Open Neovim

**Expected behavior**

No error messages would appear on startup.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-dev+4383c0f
```

**Additional context**
N/A

**Comment by ZacharyRizer** [comment]
Same for me.

**Comment by theHamsta** [comment]
That's a fairly new feature. Have you tried to update Neovim? Yours is from Dec 7.

**Comment by sidmadala** [comment]
Fixed by updating Neovim.
