### ISSUE TITLE
Stuck at installation: Post-update hook for nvim-treesitter ...

### ISSUE THREAD

**Issue by ndavidpsi** [nvim-treesitter/nvim-treesitter#789]
**Describe the bug**

I have the latest neovim at the time I'm writing this and I'm on windows.
I put the following in my init.vim:
`Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}`
Then ran `:PlugInstall`
It gets stuck here every time I try to install it:
![1](https://user-images.githubusercontent.com/73792104/102886823-bda7e680-444d-11eb-8b7b-0a734e2992d3.PNG)

**Comment by theHamsta** [comment]
Maybe you could try without TSUpdate?  It is only necessary to update the parsers once installed.

Can you install the parsers normally with TSInstall python ?

**Comment by ndavidpsi** [comment]
I tried without TSUpdate, I got the following right after installation:
```
line   12:
E5108: Error executing lua ...nvim-treesitter\lua\nvim-treesitter\query_predicates.lua:89: attempt to call field 'add_directive' (a nil value)
```

**Comment by ndavidpsi** [comment]
> Did you have a look into the Windows wiki for our repo?

Yes and I have all the requirements

**Comment by theHamsta** [comment]
This means that your nvim nightly is too old. You need one that includes the directives feature

**Comment by ndavidpsi** [comment]
Mine is like 2 weeks old I thought it was earlier enough 👍  I'll try and come back afterwards

**Comment by ndavidpsi** [comment]
That was the solution. All working fine now. Thanks.

**Comment by theHamsta** [comment]
Sorry, for not updating the version check!
