### ISSUE TITLE
Use nvim-treesitter configuration to provide cli highlighting

### ISSUE THREAD

**Issue by BonaBeavis** [nvim-treesitter/nvim-treesitter#793]
**Is your feature request related to a problem? Please describe.**
Previews in terminals do have different highlights compared to nvim because another highlighter is used. Some plugins like fzf.vim use the terminal to preview files, which leads to inconsistent highlights inside of nvim.

**Describe the solution you'd like**
Generate a config for the `tree-sitter highlight` command from the parsers and configuration provided with nvim-treesitter

**Comment by theHamsta** [comment]
This sounds out of scope for this plugin. I believe you need to provide queries (we have queries) and highlight color (our plugin does not provide them).

You might be interested in using https://github.com/lucc/nvimpager which allows using nvim as a cat command (with highlighted output)
```
nvimpager -c file-to-highlight
```
I installed it by adding it as a plugin and executing its make file.
