### ISSUE TITLE
Parser detection for 'javascriptreact' filetype

### ISSUE THREAD

**Issue by fffed** [nvim-treesitter/nvim-treesitter#796]
I have javascript and typescript parsers installed and they work as intended for buffers with 'javascriptreact' or 'typescriptreact' `filetypes`.
I also use [nvim-telescope](https://github.com/nvim-telescope/telescope.nvim) plugin and it calls `nvim-treesitter.parsers.has_parser(filetype)` for a buffer previewer. 
And [`has_parser`](https://github.com/nvim-treesitter/nvim-treesitter/blob/cafe733e23cc3822bb303d70e8f71fe1e72136c9/lua/nvim-treesitter/parsers.lua#L430) looks like:
```lua
function M.has_parser(lang)
  local lang = lang or M.get_buf_lang(api.nvim_get_current_buf())

  if not lang or #lang == 0 then return false end
  -- HACK: nvim internal API
  if vim._ts_has_language(lang) then return true end
  return #parser_files[lang] > 0
end
```
In case of 'javascript' or 'typescript' filetypes the prieviewer highlights syntax correctly but for 'javascriptreact' or 'typescriptreact' 
`has_parser` returns `false`. What could be changed so `#parser_files[lang] > 0` in case of 'javascriptreact' or 'typescriptreact'  starts to return `true`?

**Comment by theHamsta** [comment]
This is intended. The lang is really the language of the parser it's not necessary the same as the filetype. Does 

has_lang(get_buf_lang(but)) work?

**Comment by Conni2461** [comment]
Hey guys,

I wrote the buffer previewer and we can't do `get_buf_lang` because the buffer doesn't have a filetype because we don't load it with `bufload` we load the file content with `vim.loop.fs_` aync and do `nvim_buf_set_lines`.
But can we use `parsers.ft_to_lang`?

**Comment by theHamsta** [comment]
parsers.ft_to_lang should do the right thing.

**Comment by fffed** [comment]
@theHamsta , @Conni2461 thanks guys, I've tested `parsers.ft_to_lang` and it works fine.
