### ISSUE TITLE
Error executing lua ...lugged\nvim-treesitter\lua\nvim-treesitter\highlight.lua:109: attempt to call method 'set_query' (a nil value)

### ISSUE THREAD

**Issue by ggandor** [nvim-treesitter/nvim-treesitter#798]
**Describe the bug**
If `:TSBufDisable highlight` is executed in a buffer where highlight is currently enabled, the highlighting remains, and the following error is thrown:
`E5108: Error executing lua ...lugged\nvim-treesitter\lua\nvim-treesitter\highlight.lua:109: attempt to call method 'set_query' (a nil value)`

**To Reproduce**
1. With the following config:
```lua
require 'nvim-treesitter.configs'.setup {
  highlight = { enable = true },
}
```
2. Load a buffer with a TS supported language.
3. Execute `:TSBufDisable highlight`.
4. See error.

**Expected behavior**
Highighting switched off for the buffer.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - ERROR: `cc` executable not found.
    - ADVICE:
      - Install `gcc` with your package manager.
      - Install `clang` with your package manager.
      - Check that your `$PATH` is set correctly.

## cpp parser healthcheck
  - OK: cpp parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for cpp
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## c parser healthcheck
  - OK: c parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for c
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-dev+00247ec
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /O2 /Ob2 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim-windows-nightly/neovim-windows-nightly/repo/build/config -ID:/a/neovim-windows-nightly/neovim-windows-nightly/repo/src -ID:/a/neovim-windows-nightly/neovim-windows-nightly/repo/.deps/usr/include -ID:/a/neovim-windows-nightly/neovim-windows-nightly/repo/build/src/nvim/auto -ID:/a/neovim-windows-nightly/neovim-windows-nightly/repo/build/include
Compiled by runneradmin@fv-az153-614

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "D:/a/neovim-windows-nightly/neovim-windows-nightly/Neovim/share/nvim"

Run :checkhealth for more info
```

**Additional context**
TS version: `57ba843d184e30339cff76869a0f5e60a467a047`.
`:TSUpdate` has been run before getting the error.

**Comment by stsewd** [comment]
@ggandor from the checkhealth output you can see that you are missing `cc` installed

```
ERROR: cc executable not found.

    ADVICE:
        Install gcc with your package manager.
        Install clang with your package manager.
        Check that your $PATH is set correctly.
```

**Comment by theHamsta** [comment]
@stsewd please read the issue before you post something unrelated.

Thanks for reporting! Apparently the API for disable is still behind.
