### ISSUE TITLE
Python indent does not work as expected.

### ISSUE THREAD

**Issue by nacknime-official** [nvim-treesitter/nvim-treesitter#802]
**Describe the bug**
https://asciinema.org/a/EGhvn4qlxKipiW2jP50h99tai
Python indent does not work as expected. It started after updating python plugin or the nvim-treesitter, I don't remember.

**To Reproduce**
1. Create minimal neovim config like this
```
if empty(glob('~/.config/nvim/autoload/plug.vim'))
    silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

call plug#begin('~/.config/nvim/plugged')
Plug 'nvim-treesitter/nvim-treesitter'
call plug#end()


lua << EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = "python",
  highlight = {
   enable = true,
  },
  indent = {
    enable = true,
  },
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = "gnn",
      node_incremental = "grn",
      scope_incremental = "grc",
      node_decremental = "grm",
    },
  },
}
EOF
```
2. Create an empty python file
3. Write any python construction that must has indents
4. See wrong indents

**Expected behavior**
In my asciinema record the 8-length indent must be 4-length.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## bash parser healthcheck
  - OK: bash parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for bash
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## c parser healthcheck
  - OK: c parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for c
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## css parser healthcheck
  - OK: css parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for css
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `folds.scm` query found for css
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - OK: `indents.scm` found.

## javascript parser healthcheck
  - OK: javascript parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for javascript
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## query parser healthcheck
  - OK: query parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `folds.scm` query found for query
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for query
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## python parser healthcheck
  - OK: python parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

</code>
</details>

**Output of `nvim --version`**
```
-> nvim -u test_config.vim -v

NVIM v0.5.0-dev+992-gf3a8c930a
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/pro/neovim/build/config -I/home/pro/neovim/src -I/home/pro/neovim/.deps/usr/include -I/usr/include -I/home/pro/neovim/build/src/nvim/auto -I/home/pro/neovim/build/include
Compiled by root@pro

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by theHamsta** [comment]
The indent functionality is work in progress right now. @kyazdani42 is working on some improvement right now.

**Comment by nacknime-official** [comment]
> The indent functionality is work in progress right now. @kyazdani42 is working on some improvement right now.

It's weird, because before it had worked very well

**Comment by kyazdani42** [comment]
Indeed it's still in progress, because indent has a lot of edge cases (most language don't work the same way). I have a draft PR that i'll try to finish soon that might temporarily fix some cases, but the overall algorithm is not good enough imo, and will need to be reconceptualized.

**Comment by ECon87** [comment]
I don't know if this closed or not, but I am still having issues with indent.

**Comment by stsewd** [comment]
There are already some open issues https://github.com/nvim-treesitter/nvim-treesitter/issues/1573  https://github.com/nvim-treesitter/nvim-treesitter/issues/1136. @ECon87 feel free to comment there the problems you have or open a new one if you think so.

**Comment by bavalpey** [comment]
Why is this closed? The issue isn't fixed.

**Comment by stsewd** [comment]
> Why is this closed? The issue isn't fixed.

Please subscribe to the other issues, this was marked as duplicated

**Comment by AntonellaCoder** [comment]
Hello, could you tell me how did you do to solve the indentation problem on nvim-python ?

**Comment by bavalpey** [comment]
> > Why is this closed? The issue isn't fixed.
> 
> Please subscribe to the other issues, this was marked as duplicated

I must be missing something.  Nowhere do I see this being marked as duplicated.  Also, the issues you mentioned are more recent than this post.  Furthermore, this issue remains unfixed after more than a year of not working.

**Comment by gmankab** [comment]
still actual

**Comment by McAlvaro** [comment]
configure in this way in the disable option place the language you want to disable:
``` 
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = "gnn",
      node_incremental = "grn",
      scope_incremental = "grc",
      node_decremental = "grm",
    },
  },
  indent = {
    enable = true,
    disable = {"python"}
  }
}
```
This way it worked for me
