### ISSUE TITLE
Docstrings

### ISSUE THREAD

**Issue by stsewd** [nvim-treesitter/nvim-treesitter#806]
With language injection present, a feature that I've been wanting to integrate since a long time is highlighting of docstrings (mainly python docstrings as rst). Currently, there isn't anything defined on how to handle this use case. I'm more concerned on having this customizable for the user, since the docstring format isn't the same for all projects (at least in python some use markdown).

## Allow users to select the docstring format

With this users won't need to override all the queries to disable or change the format of the docstrings,
but we can just always choose the most popular format and leave to users to override the queries if they use something else (I'm fine with this, but maybe can be done in the future).

## Highlight group

The injected content would need to be captured with `@none` to allow the injected language to have full control of colors, but testing this on big projects doesn't look that good, mainly bc the text can be confused with code easily. But again, maybe users want to have this the other way, so I propose to have a hl group named `@docs` or `@docstring` for this purpose (default to the same group of `@string` maybe).

Some images of python docstrings with rst

![Screenshot from 2021-01-01 22-17-32](https://user-images.githubusercontent.com/4975310/103450094-5c6ae900-4c7f-11eb-8937-f825614b297c.png)

![Screenshot from 2021-01-01 22-18-14](https://user-images.githubusercontent.com/4975310/103450093-5aa12580-4c7f-11eb-8541-843113772520.png)

Let me know what you think, I could help with a PR.

**Comment by theHamsta** [comment]
The rst parser can set none on code regions. Had a similar issue when trying out markdown+julia.

**Comment by vigoux** [comment]
This was closed by #917

**Comment by stsewd** [comment]
Still want to make this configurable, but I can do that in another PR

**Comment by wookayin** [comment]
#917 added some quieries for docstrings, but how can we add highlight map?

**Comment by stsewd** [comment]
> #917 added some quieries for docstrings, but how can we add highlight mappings for docstrings?

This conversation may be of interest, I can try doing a PR later https://github.com/nvim-treesitter/nvim-treesitter/pull/1519
