### ISSUE TITLE
highlighting works as unexpected after attach async, e0b49a9a1885708d3565e9a59847b14a42faef2c

### ISSUE THREAD

**Issue by kevinhwang91** [nvim-treesitter/nvim-treesitter#838]
**Describe the bug**
see reproduce.

**To Reproduce**
1. `nvim foo.lua +'e bar.lua' +'b #' `

`bar.lua` can't be highlighted.

**Expected behavior**
`bar.lua` must be highlighted.

**Comment by vigoux** [comment]
Indeed the highlights differ, but I am not sure this actually comes from the async part.

**Comment by vigoux** [comment]
Did a git bisect, and indeed the first bad commit is e0b49a9a1885708d3565e9a59847b14a42faef2c.
