### ISSUE TITLE
Latest update breaks queries when using custom grammer for already supported language

### ISSUE THREAD

**Issue by BerkeleyTrue** [nvim-treesitter/nvim-treesitter#839]
**Describe the bug**

PR to neovim:
https://github.com/neovim/neovim/pull/13590
Breaks the ability to overwrite queries. This is required when using a custom grammar for a language that is already supported. (In my case I'm using https://github.com/sogaiu/tree-sitter-fennel)

**To Reproduce**

Use a custom grammer for already supported language.
Use custom highlighting in <config>/queries/<lang>
Update to latest neovim

TS crashes due to custom queries being ignored with error "E5108: Error executing lua ...e/.local/share/nvim/runtime/lua/vim/treesitter/query.lua:104: query: invalid node type at position 12"

**Expected behavior**

nvim-treesitter builtin queries should be ignored and ts should run without crashing

**Output of `:checkhealth nvim_treesitter`**

<details>

<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## clojure parser healthcheck
  - OK: clojure parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `folds.scm` query found for clojure
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for clojure
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## json parser healthcheck
  - OK: json parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for json
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for json
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## lua parser healthcheck
  - OK: lua parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

## regex parser healthcheck
  - OK: regex parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for regex
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `folds.scm` query found for regex
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for regex
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## typescript parser healthcheck
  - OK: typescript parser found.
  - ERROR: Error in `highlights.scm` query found for typescript
    ...e/.local/share/nvim/runtime/lua/vim/treesitter/query.lua:104: query: invalid node type at position 4496
    - ADVICE:
      - Try `:TSUpdate typescript` (queries might have been adapted for a upstream parser change)
      - Try to find the syntax error/invalid node type in above file.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for typescript
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## query parser healthcheck
  - OK: query parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `folds.scm` query found for query
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for query
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## jsdoc parser healthcheck
  - OK: jsdoc parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for jsdoc
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `folds.scm` query found for jsdoc
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for jsdoc
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## fennel parser healthcheck
  - OK: fennel parser found.
  - ERROR: Error in `highlights.scm` query found for fennel
    ...e/.local/share/nvim/runtime/lua/vim/treesitter/query.lua:104: query: invalid node type at position 1777
    - ADVICE:
      - Try `:TSUpdate fennel` (queries might have been adapted for a upstream parser change)
      - Try to find the syntax error/invalid node type in above file.
  - ERROR: Error in `locals.scm` query found for fennel
    ...e/.local/share/nvim/runtime/lua/vim/treesitter/query.lua:104: query: invalid node type at position 12
    - ADVICE:
      - Try `:TSUpdate fennel` (queries might have been adapted for a upstream parser change)
      - Try to find the syntax error/invalid node type in above file.
  - WARNING: No `folds.scm` query found for fennel
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for fennel
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## tsx parser healthcheck
  - OK: tsx parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for tsx
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## javascript parser healthcheck
  - OK: javascript parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

## rust parser healthcheck
  - OK: rust parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for rust
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## c parser healthcheck
  - OK: c parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for c
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## css parser healthcheck
  - OK: css parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for css
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

## bash parser healthcheck
  - OK: bash parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for bash
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

## html parser healthcheck
  - OK: html parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `folds.scm` query found for html
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for html
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-dev+1012-gfe1ebea33
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/berkeleytrue/dvlpmnt/neovim/build/config -I/home/berkeleytrue/dvlpmnt/neovim/src -I/home/berkeleytrue/dvlpmnt/neovim/.deps/usr/include -I/usr/include -I/home/berkeleytrue/dvlpmnt/neovim/build/src/nvim/auto -I/home/berkeleytrue/dvlpmnt/neovim/build/include
Compiled by berkeleytrue@delora-linux

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/berkeleytrue/.local/share/nvim"

Run :checkhealth for more info

```

**Additional context**

**Comment by vigoux** [comment]
@bfredl this is critical, we need to find a way to avoid that

**Comment by vigoux** [comment]
Thanks for reporting, we'll try to find a way to fix that, or to provide you tools to avoid this issue.

**Comment by BerkeleyTrue** [comment]
Thanks! A work around for now is to revert just prior to that commit. This commit works for me https://github.com/neovim/neovim/commit/4cdc8b1efdc7a67d24c7193ef67839924eb7d5c0

**Comment by BerkeleyTrue** [comment]
@vigoux Maybe it would be best to no include queries in this project by default and instead have a plugin system just like grammars have. I would argue that including highlights/indents/locals are outside the scope of this project and a plugin system would make using alternative grammars easier.

**Comment by vigoux** [comment]
Maybe we can provide a way to completely disable a parser.
This way you will be able to declare a new parser, together with new queries, a use it for a given filetype.

Not sure how feasible it is though.

**Comment by vigoux** [comment]
Another idea I have is using another directive on top of the file something like `reset` or `clear`, which will clear any previously met query, and only use this file and the files after it in the `rtp`.

@bfredl do you think this version is good ? It mimics a bit VimL in some sense (things like `au!`), and allow for extension and override.

**Comment by tjdevries** [comment]
Maybe a good way is to provide a way to optionally specify _exactly_ the files you'd like to provide for queries as opposed to just looking them on runtime all the time.

If the user doesn't pass anything, then just look up in runtime path like we've been doing.

```lua
require('nvim-treesitter.configs').setup {
  highlight = {
    enable = true,
    queries = {
      lua = {
        "~/my/path/to/highlight.scm"
      }
    }
  },
}
```

**Comment by tjdevries** [comment]
(this issue is killing me when I try and override completely something that you already have builtin, which I want to do for my Lua grammar and I don't like the rust highlighting, so I've been playing with that)

**Comment by BerkeleyTrue** [comment]
Yes, I'd love to be able to configure this. Currently maintaining a fork with the fennel queries removed.

**Comment by theHamsta** [comment]
> Another idea I have is using another directive on top of the file something like reset or clear, which will clear any previously met query, and only use this file and the files after it in the rtp.

It there really anyone who is

**Comment by tjdevries** [comment]
Related: https://github.com/nvim-treesitter/nvim-treesitter/pull/995

**Comment by ronisbr** [comment]
Hi!

Is there any workaround besides reverting the Neovim commit? I need this to change a highlight in Julia.

**Comment by theHamsta** [comment]
> Is there any workaround besides reverting the Neovim commit? I need this to change a highlight in Julia.

You need what to change a highlight in Julia? The highlight queries just have to fit the parser version. You can change the git SHA of a parser in nvim-treesitte/lockfile.json . The Julia parser didn't change for ages. You might need a :TSInstallFromGrammar if you want to make an old parser compatible with newest tree-sitter runtime. 0.19.X might detect more queries that were already flawed before.

**Comment by ronisbr** [comment]
@theHamsta what I want is to change how `TODO:` is highlighted and also add a highlight to `NOTE:` inside comments.

**Comment by theHamsta** [comment]
This is done by a sub-parser for comment regions. You can deactivate the `comment` parser by deinstalling it `:TSUninstall comment` or by editing injections.scm for Julia

**Comment by ronisbr** [comment]
But then I have this bug. I will need to fork Julia tree-sitter and do the modifications, right? I just can't add files to `after/queries/` due to this bug, but I get that message `invalid node type at position`.

**Comment by theHamsta** [comment]
I think `after` no longer works. It must now be in the actual rtp. You can use nvim-treesitter/playground to use a linter to debug the issue.

>  I will need to fork Julia tree-sitter and do the modifications, right?

No. Why? There have not been any modification to Julia parser for ages and the language injection is just a different language in a region configured by queries.

**Comment by ronisbr** [comment]
> No. Why? There have not been any modification to Julia parser for ages and the language injection is just a different language in a region configured by queries.

Ah! Now I understand what you said, sorry. Thanks for the help, I will disable `comment` and try to see if I can do this. Thanks!

**Comment by Himujjal** [comment]
So, I have to update [tree-sitter-zig](https://github.com/Himujjal/tree-sitter-zig) with better queries and a better grammar. As of now, highlights using the `tree-sitter highlight` command is working, but I am not able to test it on neovim.

So? Should I wait for this to be fixed to make a PR?

**Comment by Himujjal** [comment]
@theHamsta What should I do? I am not able to test my new queries and grammar. Any suggestions?

**Comment by theHamsta** [comment]
You may use this PR now to overwrite the queries: https://github.com/neovim/neovim/pull/14252

**Comment by Himujjal** [comment]
okay. let me try

**Comment by BerkeleyTrue** [comment]
💯 Looks like this issue is resolved by https://github.com/neovim/neovim/pull/14252

For those who come later to this issue, you can see how I got around it here: 
https://github.com/BerkeleyTrue/dotfiles/blob/f8ff2c7eb368740e7a8adc879c79a9eb1285c87d/.config/nvim/fnl/plugins/tree-sitter.fnl#L100

Here is a transpiled view. The gist is to get your file into a string, then use 

`require('vim.treesitter.query').set_query(<language>, <query-type>, <query-file-as-string>)`

This will prevent the runtime query from pulling in any other queries for that filetype/querytype.

```lua
local function get_ft_query(ft, type)
  local path = (vim.fn.stdpath("config") .. ("/queries/" .. ft .. "/" .. type .. ".scm"))
  return vim.fn.join(vim.fn.readfile(path), "\n")
end

local vim_ts_queries = require("vim.treesitter.query")
vim_ts_queries.set_query("fennel", "highlights", get_ft_query("fennel", "highlights"))
vim_ts_queries.set_query("fennel", "locals", get_ft_query("fennel", "locals"))
```

Thanks to @tjdevries and everyone else who contributes to these awesome projects.

- Happy Coding

**Comment by lf-** [comment]
Heya (sorry for the necropost, but this thread is high on google for this issue) to anyone finding this in the future: you can just put it earlier on the runtimepath (ie, put it in `~/.config/nvim/queries/language/queryname.scm`) since https://github.com/neovim/neovim/pull/20105 landed upstream (not yet in a release; just on master, as of this writing)

If you want to extend a query, you now have to do `;; extends` at the start of the file. See `:h treesitter-query-modeline-extends`.
