### ISSUE TITLE
parsers not recognized/working for tsx files and csharp files

### ISSUE THREAD

**Issue by kyazdani42** [nvim-treesitter/nvim-treesitter#84]
a first easy way to fix this is to check for the filetype and change it when needed.

**Comment by vigoux** [comment]
Hmm I don't really like that way of fixing it though, as it changes the behaviour of nvim itself to fit our purposes. Binding `typescriptreact` files to `tsx` using the base query mechanism sounds better to me.

**Comment by kyazdani42** [comment]
yes i started working on it and it was not great. So i thought changing the name of tsx to typescriptreact would solve everything but i dont like it much. What is this `base query mechanism` you are talking about ?

**Comment by vigoux** [comment]
This one : https://github.com/nvim-treesitter/nvim-treesitter/pull/63

**Comment by kyazdani42** [comment]
the query is not the issue here, the parser is.
Basically when you have tsx, you need to use the tsx parser. The issue here is that tsx is not a filetype in vim but typescriptreact is, so it doesn't find either the parser nor the query. 
Another issue arose when i found that the `.so` file need to have a name that match their repo name too. So the `csharp` parser also cannot work first of all because csharp files are `cs` filetypes, and if you force the `csharp` filetype, you get this:
```
E5108: Error executing lua Failed to load parser: uv_dlsym: ...nvim-treesitter/parser/csharp.so: undefined symbol: tree_sitter_csharp
```

**Comment by kyazdani42** [comment]
i think you might have misunderstood the base purpose of #63 which was to introduce the ability to use multiple query files and not to use different parsers :)

**Comment by vigoux** [comment]
Oh I see now, I quite overlooked it to be honest... Then we have to come up with some kind of aliasing...

**Comment by steelsojka** [comment]
I original was doing an alias implementation in my ts/js pr, but I started going down a rabbit hole that seemed to be to much for that pr. Pretty much anywhere it had to reference the filetype, we would have to look up our aliases... this included setting the autocommands as well.

**Comment by kyazdani42** [comment]
This issue is actually more complicated to resolve in a proper manner than expected.
We cannot change the name of the parsers, because neovim would then fail to link names in the treesitter lib (treesitter-tsx would look for treesitter-typescriptreact symbols and fail because they don't exist !)
This is an issue related to binding filetypes to parsers i believe, which might need to be reported upstream (neovim).
@vigoux what do you think ? Should we find a dirty workaround or fix the issue upstream ?

**Comment by vigoux** [comment]
Why can't we change the name of the parser? Symbol resolution is not related to the name of the file.
If we rename `tsx.so` to `treesitterreact.so`, it should work just fine.

**Comment by kyazdani42** [comment]
```
Error executing lua Failed to load parser: uv_dlsym: .../nvim-treesitter/parser/typescriptreact.so: undefined symbol: tree_sitter_typescriptreact
```
obviously something doesn't work. I'm not too sure where this comes from, but i believe this is something to do with the way neovim (or more specifically, the libuv) loads the parsers

**Comment by kyazdani42** [comment]
`int uv_dlsym(uv_lib_t* lib, const char* name, void** ptr)`. And i believe `name` which should be the name of the library is a concatenation of `treesitter` with `_${FT}`

**Comment by kyazdani42** [comment]
and as the library is called treesitter_tsx, trying to load treesitter_typescript react does not work at all. Not sure how this should be solved

**Comment by vigoux** [comment]
Then I don't really know. I think that having a map and aliases this would be the easiest. Using `parsers.lua` would be great for that (does it still exists though?).

**Comment by kyazdani42** [comment]
This is why i asked for a `dirty` workaround, as this would involve changing a lot of code that should not be affected by that.
If you want, take a look at `src/nvim/lua/treesitter.c`, line 126 in neovim, we could potentially fix that there, and it would require very small change from our side.

**Comment by vigoux** [comment]
Then go for it 😉

**Comment by kyazdani42** [comment]
maybe the best solution right now is to fork parsers we need to change the names for, recompile them so they provide the api with the name we chose.

**Comment by kyazdani42** [comment]
csharp name will be renamed to `cs` and tsx name will be renamed to `typescriptreact` (unfortunately)

**Comment by vigoux** [comment]
That doesn't seem right though... I think that we should dig into the hints you gave on previous comments to find a better way to fix this.

**Comment by kyazdani42** [comment]
indeed, this is just a draft atm
