### ISSUE TITLE
(treesitter + julia) crash when typing triple quote

### ISSUE THREAD

**Issue by quantum-booty** [nvim-treesitter/nvim-treesitter#844]
![image](https://user-images.githubusercontent.com/28958399/104199692-a5f5c980-541f-11eb-97a8-a32610ee00b2.png)
~~This is what I get when I type "" and attempt to type a third ". I've tested it in other file extensions like .py and they do not crash.~~
Edit:
Crashes when typing the final " of triple quote """"""

```vim
au BufNewFile,BufRead *.jl set filetype=julia

call plug#begin('~/.config/nvim/plugged')
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
call plug#end()


lua <<EOF
require'nvim-treesitter.configs'.setup {
  highlight = {
    enable = true,
}}
EOF
```

**Output of `:checkhealth nvim_treesitter`**
I've only listed the julia check health.
<details>

<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## julia parser healthcheck
  - OK: julia parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - WARNING: No `folds.scm` query found for julia
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for julia
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-dev+1017-gad43f789e
```

**Comment by vigoux** [comment]
Hi, the julia parser is really WIP, so we'll try to dig a bit why this happens, I'll report here what I find.

**Comment by vigoux** [comment]
If you could give us some julia file that causes the error, that would greatly help !

**Comment by vigoux** [comment]
For now the fuzzing campaign does not yield anything, which is a little weird, but might have two origins :

- The bug is produced when editing only (possible)
- The bug produced is really specific, and only a single path fails (less possible)

**Comment by quantum-booty** [comment]
It crashes if whether or not the file is an empty file and regardless of the file path.

**Comment by quantum-booty** [comment]
hmm actually I think auto-pairs has nothing to do with this, because I disabled auto-pairs and it still crashes.

**Comment by theHamsta** [comment]
Just in case: do you have the markdown parser installed? (I added an injection for that at triple quotes). If the crash is due to the parser itself then it may be good to file the problem at tree-sitter-julia.

**Comment by quantum-booty** [comment]
> Just in case: do you have the markdown parser installed? (I added an injection for that at triple quotes). If the crash is due to the parser itself then it may be good to file the problem at tree-sitter-julia.

I don't see markdown parser in :checkhealth, but on the other hand, weird:
![image](https://user-images.githubusercontent.com/28958399/104226680-1e6c8280-5440-11eb-8ade-7af2e25e91fa.png)

**Comment by theHamsta** [comment]
Probably, the parser is installed but not the configuration. Maybe you can `TSUninstall` or delete `markdown.so` in `nvim-treesitter/parsers/` just to be super sure.

:point_up: really nice screenshot :smile:

**Comment by quantum-booty** [comment]
@theHamsta yeah uninstalling the markdown parcer fixed it!

**Comment by theHamsta** [comment]
Ok, then this issue seems to be fixed. I integrated this query in the hope that the markdown parser might improve in future. See: https://github.com/ikatyang/tree-sitter-markdown/issues/14
