### ISSUE TITLE
(Help) Unable to replace a query

### ISSUE THREAD

**Issue by shadmansaleh** [nvim-treesitter/nvim-treesitter#860]
Ok this might just be I'm trying to configure it wrong . So pardon me for wasing your time .

### Situation
I'm trying to create folds only for functions and tables.
The default query is:(nvim-trersitter/quries/lua/folds.scm
```scheme
[
 (for_in_statement)
 (for_statement)
 (while_statement)
 (repeat_statement)
 (if_statement)
 (function_definition)
 (local_function)
 (function)
 (table)
] @fold
```

So i'm trying to replace it with 
```
[
 (function_definition)
 (local_function)
 (function)
 (table)
] @fold
```

I've tried to put this file in 
`~/.config/nvim/quries/lua/folds.scm`
`~/.config/nvim/after/quries/lua/folds.scm`
`~/.local/share/nvim/site/quries/lua/folds.scm`
`~/.local/share/nvim/site/after/quries/lua/folds.scm`
But none works . Though if I replace the file in `nvim-trersitter/quries/lua/folds.scm`
it works . I donn't wana modify the local repo clone to configure it.

### Info
- I'm using neovim-nightly (I've compiled it from source afew days ago)
- using current nvim-treesitter master branch
- treesitter is installed with packer as a opt plugin 

### Speculations
I think loading is going like this XDG_HOME_DIR -> plugin -> XDG_HOME_DIR/after

> if the file is in any after/queries/ folder, then it will be used to extend the already defined queries.
Otherwise, it will be used as a base to define the query, the first query found (with the highest priority) will be the only one to be used.

I understand it right it's always expanding thus . No matter wherever I put the configs it will get expanded to the default version in repo as I'm trying to remove some not add .

So what can I do now?

**Comment by BerkeleyTrue** [comment]
This is related to #839. The ability to overwrite queries in neovim/treesitter has been removed and is up to the plugin provider (nvim-treesitter in this case) to include the mechanism. Unfortunately the only work around is to revert neovim back to the commit prior to this.

Another possibility is to fork this plugin and remove the unneeded queries.

**Comment by shadmansaleh** [comment]
>This is related to #839. The ability to overwrite queries in neovim/treesitter has been removed and is up to the plugin provider (nvim-treesitter in this case) to include the mechanism. Unfortunately the only work around is to revert neovim back to the commit prior to this.

Thanks for responding . 

>Another possibility is to fork this plugin and remove the unneeded queries.

We already have local clones . I'll just make the changes in a local branch for now.

**Comment by vigoux** [comment]
Hi thanks for reporting, this is indeed kinda related to #838, as they both are the result of some changes made upstream.

**Comment by tjdevries** [comment]
Related: https://github.com/nvim-treesitter/nvim-treesitter/pull/995

**Comment by vigoux** [comment]
This should have been fixed upstream now.

**Comment by shadmansaleh** [comment]
@vigoux I'm not sure but it seems overwritting queries by placing files in config directory($XDG_CONFIG_DIR) isn't possible.

Tj's pr allows to overwrite queriies I assume . But I don't understand how to make it work . I basically want only tables and functions to get folded in lua files .
I tried 
```lua
local folds_query = "(function) (table)"
require('vim.treesitter.query').set_query("lua", "folds", folds_query)
```
That's surely wrong . But I'm walking blind here I've no idea on how to write queries :P . Is there some instructions I can follow ?

**Comment by kyazdani42** [comment]
you have at least to `local folds_query = "[ (function) (table) ] @folds"` i think

**Comment by shadmansaleh** [comment]
> you have at least to local folds_query = "[ (function) (table) ] @folds" i think

I actually tried that . Same result "No folds found"

I was actually trying to follow the [test](https://github.com/tjdevries/neovim/blob/d6209a7b84a12fadd90fc5b4cb5efb66e8ca8127/test/functional/treesitter/highlight_spec.lua#L488) in tjs pr


Thanks for trying to help :)

**Comment by theHamsta** [comment]
It has to be `@fold` without `s`
```
local folds_query = [[
(function) @fold
]]
require('vim.treesitter.query').set_query("lua", "folds", folds_query)
require('vim.treesitter.query').set_query("lua", "textobjects", [[(function_call) @function.outer]])
```
but I only get it to work with textobjects

**Comment by theHamsta** [comment]
@vigoux the folding feature does not work for me at all at the moment.

**Comment by theHamsta** [comment]
I can confirm that this code worked earlier today
```
local folds_query = [[
[
 (function)
] @fold
]]
require('vim.treesitter.query').set_query("lua", "folds", folds_query)
```

**Comment by theHamsta** [comment]
See https://github.com/nvim-treesitter/nvim-treesitter/issues/1226

**Comment by shadmansaleh** [comment]
> @vigoux the folding feature does not work for me at all at the moment. @shadmansaleh I suppose you too have the newest Nvim and plugin version

Yeah I compiled like 12 hours ago so pretty new.
> See #1226

Thanks for opening an issue I'll follow that

**Comment by shadmansaleh** [comment]
@vigoux I've confirmed queries can now be overwritten . The issue with folds isn't related to this . So I'm closing this issue :)
