### ISSUE TITLE
Using @injection.language instead of @language in injection queries

### ISSUE THREAD

**Issue by b3nj5m1n** [nvim-treesitter/nvim-treesitter#873]
**Is your feature request related to a problem? Please describe.**
According to the Injections section in your contribution guidelines, the content of an injection group should be captured by a group called `@content`, and the name of the language with a group called `@language`. According to the official tree-sitter docs however, these groups should be called `@injection.content` and `@injection.language` (See [here](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection)). I've tested using these names instead, and `@injection.content` seemed to work, `@injection.language` however, did not.

**Describe the solution you'd like**
I mostly wanted to ask why the decision to divert from the official naming convention was made, and if adding support for it would be possible. This would mean that we could just use the `injections.scm` files from some parsers that were not specifically made for nvim-treesitter.

**Describe alternatives you've considered**
Simply using  `@content` and `@language` isn't a big problem, but it does make for some unnecessary work in some cases.

**Comment by theHamsta** [comment]
For reference, this is how they inject a known language
```scheme
((heredoc_body) @injection.content
 (#set! injection.language "ruby"))
```

**Comment by theHamsta** [comment]
Do you want to create a upstream PR for this? The code for injection in in the Neovim repository

**Comment by b3nj5m1n** [comment]
I see, I'll close this issue, then I'll either create a PR or another issue in the main neovim repo.

**Comment by theHamsta** [comment]
@b3nj5m1n there is also stuff to fix here (the queries) but we have to follow upstream here.
