### ISSUE TITLE
[Javascript] Object shorthand not highlighted as regular object property

### ISSUE THREAD

**Issue by kristijanhusak** [nvim-treesitter/nvim-treesitter#876]
Screenshot:
![screenshot](https://i.imgur.com/GEZcpXb.png)

I'd expect `two` in `test` object to be highlighted in the same way as `one`.

Not sure if it's like this by design, or just a missing highlight.

**Comment by vigoux** [comment]
Could you show us the tree generated by this ? There can be three problems here :

- The parser is wrong
- Highlights are wrong
- Highlights overlap and break things

**Comment by kristijanhusak** [comment]
@vigoux Sure. I'm not sure if this is what you asked for, but this is what I got from the playground:
```
lexical_declaration [0, 0] - [0, 14]
  variable_declarator [0, 6] - [0, 13]
    name: identifier [0, 6] - [0, 9]
    value: number [0, 12] - [0, 13]
lexical_declaration [2, 0] - [2, 29]
  variable_declarator [2, 6] - [2, 28]
    name: identifier [2, 6] - [2, 10]
    value: object [2, 13] - [2, 28]
      pair [2, 15] - [2, 21]
        key: property_identifier [2, 15] - [2, 18]
        value: number [2, 20] - [2, 21]
      shorthand_property_identifier [2, 23] - [2, 26]
```

**Comment by vigoux** [comment]
That's indeed what I meant, thanks, sorry I wasn't clear !

So, now we know the tree is correct (given the `shorthand_property_identifier` node), could you show me the output of `:TSHighlightCapturesUnderCursor` when your cursor is on the shorthad ?

**Comment by kristijanhusak** [comment]
Here's the screenshot:

![screenshot](https://i.imgur.com/WkYzHSO.png)

**Comment by vigoux** [comment]
So, we are indeed missing some highlights !
I think @steelsojka is maintaining this so I'll let him handle that with you, thanks for reporting !

**Comment by kristijanhusak** [comment]
Ok, thanks for the quick answer.

**Comment by kristijanhusak** [comment]
Nice, thanks!
