### ISSUE TITLE
Missing/wrong folds for yaml

### ISSUE THREAD

**Issue by gegoune** [nvim-treesitter/nvim-treesitter#887]
**Describe the bug**
yaml folding is not working correctly I think, it does not create separate folds for some nodes as illustrated here:

<img width="274" alt="Screenshot 2021-01-29 at 11 31 35" src="https://user-images.githubusercontent.com/69750637/106264127-8f27e300-6225-11eb-9746-c60fcc92014b.png">

**To Reproduce**
1. `nvim test.yaml`
2. insert following content:
```yaml
days:
  Monday:
    - test: example
  Tuesday:
    - test: example
  Wednesday:
    - test: example
    - test: example
  Thursday:
    - test: example
  Friday:
    - test: example
```
3. type `zM` to hide all folds 
4. type `zr` to reduce fold level by 1
5. observe hidden `Tuesday` and `Wednesday` nodes (folded with other nodes)

**Expected behavior**
See all weekdays nodes as separate folds.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

## yaml parser healthcheck
  - OK: yaml parser found.
  - OK: `highlights.scm` found.
  - WARNING: No `locals.scm` query found for yaml
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

</code>
</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-dev+271cec2
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210127-31974-1l49eev/build/config -I/tmp/neovim-20210127-31974-1l49eev/src -I/usr/local/include -I/tmp/neovim-20210127-31974-1l49eev/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210127-31974-1l49eev/build/src/nvim/auto -I/tmp/neovim-20210127-31974-1l49eev/build/include
Compiled by <hostname>

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-271cec2/share/nvim"

Run :checkhealth for more info
```

**Comment by stsewd** [comment]
@cloggier this fixed it for me locally, but let me know if woks for you as well https://github.com/nvim-treesitter/nvim-treesitter/pull/928

**Comment by vigoux** [comment]
Reopening since the folding issue is not completely fixes.

**Comment by cloggier** [comment]
@stsewd It is better, great thanks! Not perfect yet though, but thanks for your work!

**Comment by stsewd** [comment]
@cloggier what would be missing? or what looks buggy?

**Comment by cloggier** [comment]
@stsewd Same example as in initial report folds too much (not sure how to describe it better):

<img width="207" alt="Screenshot 2021-02-10 at 10 08 11" src="https://user-images.githubusercontent.com/69750637/107488614-e44de800-6b87-11eb-831a-9a8862269877.png">

(shows only first node and folds others?)

Hitting `zr` expands that fold to

<img width="298" alt="Screenshot 2021-02-10 at 10 09 13" src="https://user-images.githubusercontent.com/69750637/107488714-08112e00-6b88-11eb-95fe-30380764a348.png">

Which is what I think I was expecting with `foldlevelstart=1`

**Comment by stsewd** [comment]
@gegoune so is this problem with `foldlevelstart=1` them?

> Which is what I think I was expecting with foldlevelstart=1

You'll get that with `foldlevelstart=2`

```
	Sets the fold level: Folds with a higher level will be closed.
	Setting this option to zero will close all folds.  Higher numbers will
	close fewer folds.
```

That't the expected behavior from the docs.

Fold 0 is having the whole yaml folded.

**Comment by gegoune** [comment]
@stsewd I am not sure how that is suppose to work to be honest. With `foldlevelstart=1` I do get initial main object folded like this:
<img width="119" alt="Screenshot 2021-07-05 at 18 48 32" src="https://user-images.githubusercontent.com/69750637/124496052-9ac59a00-ddc1-11eb-9826-f0768e641869.png">

If that is what it is suppose to be that's fine, but I think I would expect to see all keys of `days` in there, so something more like:
<img width="188" alt="Screenshot 2021-07-05 at 18 49 23" src="https://user-images.githubusercontent.com/69750637/124496149-b92b9580-ddc1-11eb-9e03-ede1152e57f6.png">

which I get after `za` on `Monday`. Don't think problem is with `foldlevelstart` but with folds themselves, should I not be seeing all days (keys) when top key is unfolded?

Feel free to close it, I am not sure what desired behaviour should be.

**Comment by stsewd** [comment]
@gegoune yes, that's the expected behavior since `foldstart=0` means folding the whole document, fold 1 will fold the body of the first level keys, and so on.

To get what you expect, you can set `foldnestmax=2`
