### ISSUE TITLE
C++ - macros may break subsequent highlighting/folding

### ISSUE THREAD

**Issue by v-chernyshev** [nvim-treesitter/nvim-treesitter#891]
**Describe the bug**

Good evening, I've tried to use `nvim-treesitter` for semantic highlighting and folding and have noticed that it doesn't work as expected when a class declaration immediately follows a macro.

**To Reproduce**

Consider this C++ snippet:

```cpp
#define MY_MACRO

MY_MACRO

class MyClass {
public:
    using MyTypedef = int;
};
```

What I see on my side is that "class" and "using"  have no highlighting and there are only two folding markers: one for `#define MY_MACRO` and the other for the `MY_MACRO` statement immediately below, so it seems that the class is not recognized as a separate token. Removing the `MY_MACRO` line or putting a semicolon after it fixes the problem. This is, however, not always possible to do because these type of macros may be used for e.g. optional inline namespaces as may be seen in [Abseil](https://github.com/abseil/abseil-cpp/blob/887d0eee6bab35847253181b32e78ff707010ccd/absl/strings/string_view.h#L64-L67).

**Expected behavior**

I would expect the highlighting and folding to work in presence of such macros.

**Output of `:checkhealth nvim_treesitter`**

<details>

```
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## c parser healthcheck
  - OK: c parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

## lua parser healthcheck
  - OK: lua parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

## cpp parser healthcheck
  - OK: cpp parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.
```

</details>

**Output of `nvim --version`**
```
NVIM v0.5.0-dev+1056-gad98b8400
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az205-603

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by theHamsta** [comment]
Could you report this at tree-sitter-cpp. There is nothing that we as a consumer of the parser could do about it.

**Comment by v-chernyshev** [comment]
Thanks for pointing to the right repository, I see that it has already been reported there: https://github.com/tree-sitter/tree-sitter-cpp/issues/85. Closing this issue.
