### ISSUE TITLE
[Propose new highlight group] TSSymbol / @symbol for languages that support symbols & atoms (such as Ruby)

### ISSUE THREAD

**Issue by bluz71** [nvim-treesitter/nvim-treesitter#892]
Hello,

#874 recently changed the highlighting of Ruby symbols from `@constant` to `@property`. With certain themes that is an improvement, with others (such as mine) it is a regression.

In actuality programming language symbols are neither constants nor properties. They are their own thing as noted [in this wikipedia page about programming language symbols](https://en.wikipedia.org/wiki/Symbol_(programming)).

If possible, I strongly feel that symbols warrant their own Neovim Treesitter highlight group since quite a few languages do support the concept:

- Ruby symbols
- Dart symbols
- Lisp / Clojure symbols
- Elixir atoms
- Erlang atoms
- Julia symbols
- Scala symbols
- JavaScript ES6 Symbol

I believe this will be a worthwhile improvement since trying to fit Ruby symbols into `@constant` or `@property` is like trying to fit a square into a round hole. Neither is correct. Best of all this enhancement applies to multiple languages, not just Ruby.

Best regards.

**Comment by vigoux** [comment]
So, I have been looking into that.

And for once, I think adding a highlight of this sort would be kinda great, as a fallback from `integer` `float` or things like that.

I am not sure which between `@symbol` and `@literal` suits best though.

**Comment by theHamsta** [comment]
@sogaiu and I where also musing about introducing a category for lisp keywords (`:foo`) for Lisps and for Julia. `TSSymbol` would be perfect for that

**Comment by sogaiu** [comment]
I find cross-language terminology to be quite challenging :)

**Comment by bluz71** [comment]
> I am not sure which between @symbol and @literal suits best though.

> I find cross-language terminology to be quite challenging :)

I suspect the most obvious choice is the best choice, that being `@symbol` primarily due to it having it's own Wikipedia page: [Symbol (programming)](https://en.wikipedia.org/wiki/Symbol_(programming)).

Other choices would be `@atom` or `@literal` I suppose. If one of these is chosen it would not worry me, but I do feel that `@symbol` is the most appropriate name for this data primitive.

**Comment by bluz71** [comment]
Is it hard to had a new `@symbol` category? Is it something a complete novice such as myself could do?

I definitely want to correctly highlight Ruby symbols as `@symbol` before 0.5 release.

Best regards.

**Comment by theHamsta** [comment]
> Is it hard to had a new @symbol category? Is it something a complete novice such as myself could do?

Definitely easy, in higlight.lua there is a dictionary `hl_map` where you can map `symbol` to TSSymbol. Next you have to define TSSymbol highlight group in a vim file and add documentation. Since we upstreamed the highlight groupd you might want to add this highlight group to the Neovim repo as well.

**Comment by bluz71** [comment]
> Definitely easy, in higlight.lua there is a dictionary hl_map where you can map symbol to TSSymbol. Next you have to define TSSymbol highlight group in a vim file and add documentation.

Ok sounds reasonable, I will take this task on over the next week. I will try and do my small part for tree-sitter :)

> Since we upstreamed the highlight groupd you might want to add this highlight group to the Neovim repo as well.

We definitely want a `TSSymbol` highlight group. So that is an upstream item?

Chicken or egg? Which should happen first, `TSSymbol` highlight group in Neovim or `@symbol` in nvim-treesitter? I assume the Neovim task needs to happen first?

**Comment by theHamsta** [comment]
You're right. It's a bit more complicated now since we upstreamed the definition of the highlight group. Maybe it would be better to do the Neovim PR first?

**Comment by stsewd** [comment]
I think you can do that in this repo https://github.com/nvim-treesitter/nvim-treesitter/blob/master/lua/nvim-treesitter/highlight.lua https://github.com/nvim-treesitter/nvim-treesitter/blob/master/plugin/nvim-treesitter.vim

Defining the hl upstream could be done later in my opinion.

**Comment by bluz71** [comment]
PR #982 now ready for review and discussion.

**Comment by bluz71** [comment]
Are there any upstream Neovim changes needed?

Are tree-sitter highlight groups in base Neovim?

**Comment by theHamsta** [comment]
I think there is a copy of our highlight groups in nvim core.

**Comment by bluz71** [comment]
Ok, I will have a snoop around Neovim and open a PR over there if needed (likely yes).

**Comment by bluz71** [comment]
> I think there is a copy of our highlight groups in nvim core.

Ok, I looked around Neovim core, I could not find any Treesitter highlight groups in the source.

Are you sure they are upstreamed? I am not sure they are, unless I am blind (and Ripgrep is letting me down).

For the moment, I don't think there is anything left to do upstream.

**Comment by bluz71** [comment]
The recently merged #982 provides `TSSymbol` support for:

- Ruby `:symbol`

- Dart `#symbol`

- Julia `:symbol`

Once more languages become Treesitter capable then I envisage `TSSymbol` being used for:

- Elixir `:atom`

- Crystal `:symbol`

- Scala `'symbol`

- Clojure `'symbol`

Common cross-language idioms such as symbols and namespaces are worth extracting into their own highlight groups since they allow Vim theme authors, such as myself, to craft our themes with a high degree of precision.

Many thanks for merging.
