### ISSUE TITLE
LR: SuperCollider support

### ISSUE THREAD

**Issue by madskjeldgaard** [nvim-treesitter/nvim-treesitter#902]
**Language informations**
Hi!
It would be nice to add support for the supercollider language at some point. It works for filetype `supercollider` and suffices `.scd` and `.sc`.

I'm working on a grammar etc here: https://github.com/madskjeldgaard/tree-sitter-supercollider

Parser config could look like this:
```lua
parser_config.supercollider = {
	install_info = {
		-- url = "~/code/tree-sitter-supercollider",
		url = "https://github.com/madskjeldgaard/tree-sitter-supercollider",
		files = {"src/parser.c"},
		maintainer = "@madskjeldgaard"
	},
	filetype = "supercollider", -- if filetype does not agrees with parser name
}
```

**Comment by theHamsta** [comment]
Do you want to create a PR for this? You only have to add your snippet to `parsers.lua`
