### ISSUE TITLE
TSInstall errors with clang set as compiler

### ISSUE THREAD

**Issue by joshuachp** [nvim-treesitter/nvim-treesitter#907]
**Describe the bug**

The compilation of the parser fails if `clang` is used as compiler, since is more strict then gcc for compling cpp code. 

**To Reproduce**

1. `env CC=$(which clang) nvim '+TSInstallSync nix'`
2. Confirm the re installation
3. See the error

**Expected behavior**

Compile successfully

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

Paste the output here

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

Paste the output here

</code>
</details>

**Additional context**

The compilation doesn't fail with `clang++`.

**Comment by theHamsta** [comment]
```
                                                                                                                                          
nix parser already available: would you like to reinstall ? y/n: y
Downloading...
Creating temporary directory
Extracting...
Compiling...
Treesitter parser for nix has been installed
Press ENTER or type command to continue
```
cannot reproduce with `clang` being `clang-10` or with `clang-12`. Would you mind sharing `clang --version` and your OS?

But compiling C++ and C in different files with  the same command is a problem is a problem that can cause a lot of problems.

**Comment by joshuachp** [comment]
The problem is with the NixOS version of clang, I tried with version 7 and 10.
Also there is no problem with the Arch version of clang 11.

I tried with a different example and weird things happens on Nix.
The following code compiles with clang on Arch and not on NIx
```cpp
// test.cpp
#include <vector>
using namespace std;

int main(){return 0;}
```

**Comment by theHamsta** [comment]
Well libstdc++ is actually the gcc library for C++. It's not always installed when you have clang++ because it would usually use libc++
