### ISSUE TITLE
make checkhealth output more compact

### ISSUE THREAD

**Issue by teto** [nvim-treesitter/nvim-treesitter#908]
**Is your feature request related to a problem? Please describe.**
I think treesitter helpers could be clearer than they are and less verbose:

For instance TSInstallInfo doesn't sort the grammars so it's difficult to look for a specific grammar. 
Similarly `:checkhealth nvim_treesitter` output could be more compact. checkhealth should let you see in a glance what's wrong, the more output, the harder it gets to parse it.

Here 2 examples:
```
  - ERROR: `cc` executable not found.
    - ADVICE:
      - Install `gcc` with your package manager.
      - Install `clang` with your package manager.
      - Check that your `$PATH` is set correctly.
```
the 3 lines could be arranged as `check that either gcc or clang is in your $PATH`.

```
## lua parser healthcheck
  - OK: lua parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.
```
I have a feeling the first   `- OK: lua parser found.` is obvious since otherwise there would be no healthcheck for this parser ?
The rest could be written as a one-liner  ``` `highlights.scm`, `locals.scm` `indents.scm` found.```

Likewise I find TSModuleInfo hard to read since the difference between the cross and the tick is quite small. Maybe remove crosses to make it easier to see ?

Also as treesitter is supposed to have some native support in neovim, it would be nice to split the healthcheck into 2 parts and upstream a very basic healtcheck into the core.

Sorry for the complaints, loving what you do keep up the excellent work.

**Comment by vigoux** [comment]
Yep it is indeed an issue, I'll try to look into it at some point !

**Comment by alexaandru** [comment]
If I could possibly make a suggestion for the `checkhealth` part, how about something like this:

```
## Parser/Features P H L F I
 - css             ✓ ✓ ⨯ ✓ ✓
 - erlang          ✓ ⨯ ⨯ ⨯ ⨯
 - sparql*         ✓ ✓ ✓ ✓ ✓
 - gdscript        ✓ ✓ ✓ ⨯ ⨯
 - ...
 Legend: P[arser], H[ighlight], L[ocals], F[olds], I[ndents]
               *) multiple parsers found, only one will be used
```

and if you like it, would you be interested in a PR? Also, as suggested by OP, if `parser` is always true (installed), which seems to be the case, as you only list installed parsers, right? then you might want to drop that column entirely. Simply having the name in that list means that it is installed.

Cheers!

**Comment by cloggier** [comment]
Would be nice to omit crosses. It makes it difficult to spot what's enabled/available.

**Comment by alexaandru** [comment]
Yeah, I was thinking about that as well. Let's see how it looks like...

with dashes:

```
## Parser/Features P H L F I
 - css             ✓ ✓ - ✓ ✓
 - erlang          ✓ - - - -
 - sparql*         ✓ ✓ ✓ ✓ ✓
 - gdscript        ✓ ✓ ✓ - -
```

and with nothing (spaces):

```
## Parser/Features P H L F I
 - css             ✓ ✓   ✓ ✓
 - erlang          ✓ 
 - sparql*         ✓ ✓ ✓ ✓ ✓
 - gdscript        ✓ ✓ ✓ 
```

**Comment by clason** [comment]
How about a small centered dot (`⋅`) for "not available"?

**Comment by alexaandru** [comment]
```
## Parser/Features P H L F I
 - css             ✓ ✓ ⋅ ✓ ✓
 - erlang          ✓ ⋅ ⋅ ⋅ ⋅
 - sparql*         ✓ ✓ ✓ ✓ ✓
 - gdscript        ✓ ✓ ✓ ⋅ ⋅
```

**Comment by teto** [comment]
thanks
