### ISSUE TITLE
Module 'nvim-treesitter.configs' not found:

### ISSUE THREAD

**Issue by cadenhenrich** [nvim-treesitter/nvim-treesitter#914]
**Describe the bug**

`nvim-treesitter` is unable to find any of the files or directories required by the base lua code given in the README.
```lua
lua <<EOF
require'nvim-treesitter.configs'.setup {
  ensure_installed = "maintained", -- one of "all", "maintained" (parsers with maintainers), or a list of languages
  highlight = {
    enable = true,              -- false will disable the whole extension
    disable = { "c", "rust" },  -- list of language that will be disabled
  },
}
EOF
```

Error:
```
Error detected while processing /home/caden/.config/nvim/init.vim:
line  179:
E5108: Error executing lua [string ":lua"]:1: module 'nvim-treesitter.configs' not found:
        no field package.preload['nvim-treesitter.configs']
        no file './nvim-treesitter/configs.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/nvim-treesitter/configs.lua'
        no file '/usr/local/share/lua/5.1/nvim-treesitter/configs.lua'
        no file '/usr/local/share/lua/5.1/nvim-treesitter/configs/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/nvim-treesitter/configs.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/nvim-treesitter/configs/init.lua'
        no file './nvim-treesitter/configs.so'
        no file '/usr/local/lib/lua/5.1/nvim-treesitter/configs.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/nvim-treesitter/configs.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './nvim-treesitter.so'
        no file '/usr/local/lib/lua/5.1/nvim-treesitter.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/nvim-treesitter.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
```

**To Reproduce**

1. Install plugin
2. Add lua block to `init.vim`
3. Close and reopen file, or `:so %`

**Expected behavior**

The block of lua code finds the files it's looking for 

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## c parser healthcheck
  - OK: c parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

## python parser healthcheck
  - OK: python parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

## rust parser healthcheck
  - OK: rust parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

## toml parser healthcheck
  - OK: toml parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

## cpp parser healthcheck
  - OK: cpp parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

## bash parser healthcheck
  - OK: bash parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - WARNING: No `indents.scm` query found for bash
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev+1064-gb96db38af
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az204-674

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**

I installed `nvim-nightly` from the AUR.

**Comment by kyazdani42** [comment]
the plugin doesn't seem to be in your runtimepath, maybe you try to load nvim-treesitter.configs before loading the plugin ?

**Comment by cadenhenrich** [comment]
Unfortunately I don't think that's the case, here's the excerpt from my `init.vim`.
```vim
call plug#begin(stdpath('data') . '/plugged')
...

" Sittin' in a tree
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}

lua <<EOF
require'nvim-treesitter.configs'.setup {
  -- ensure_installed = "maintained", -- one of "all", "maintained" (parsers with maintainers), or a list of languages
  highlight = {
    enable = true,              -- false will disable the whole extension
    -- disable = { "c", "rust" },  -- list of language that will be disabled
  },
}
EOF

...

call plug#end()
```

**Comment by kyazdani42** [comment]
you gotta setup after the call to plug#end because it's when plug will load plugins in the rtp !

**Comment by cadenhenrich** [comment]
Works like a charm! Thanks so much, closing now.

**Comment by optimizasean** [comment]
That just got me good for quite a few minutes, would be nice to have that in a note somewhere 😆   Could we put this near where it is in the README stating to add the lua config block to make it clear this has to happen after plug#end for vim-plug install instructions?

New Neovim user here so maybe this is just understood for everyone but it definitely would have helped me.  Now I know for all plugins though 😄 !

**Comment by gwd999** [comment]
same issue even when putting the lua setup part all the way to the end of my init.vim file?

**Comment by ExpandingMan** [comment]
I'm hitting this again, same error as others have been posting above, but using `lazy` and it's only happening on some systems for some reason (maybe only when I use the appimage).  Any ideas?

**Comment by clason** [comment]
Make sure you're using the config for the new default `main` branch. Don't trust internet tutorials (which have the half-life of some of the more esoteric isotopes).
