### ISSUE TITLE
TeX LaTeX LuaTeX LuaLaTeX

### ISSUE THREAD

**Issue by reportaman** [nvim-treesitter/nvim-treesitter#915]
**Language informations**

TeX/LaTeX is the old duo typesetting/markup language still used by millions of active users (mostly academia afaik). Just one web-based TeX/LaTeX system announced last year that they passed 6 million users: https://www.overleaf.com/blog/reaching-six-million-users-in-an-unprecedented-six-months

LuaTeX/ LuaLaTeX is the more modern engine, and it makes Lua a first class citizen of in TeX, the way that neovim has made Lua a first class citizen in Vim. Lua code is embedded in LaTeX code in ```\directlua{<multiline lua code here>}``` macros. Ideally, Lua language syntax/language features will apply to code inside directlua macro (and other user defined patterns), and TeX language feature will apply to rest of the code outside of such special blocks.

**Comment by stsewd** [comment]
Hi, we will need to add a latex/tex parser, embedding lua would be easy. There are a couple of available parsers https://github.com/search?q=tree-sitter-latex not sure if they are working/maintained.

**Comment by stsewd** [comment]
From the three:

- https://github.com/yitzchak/tree-sitter-latex (archived, unmaintained?)
- https://github.com/Aerijo/tree-sitter-latex2e (looks like it has something working)
- https://github.com/thomasjo/tree-sitter-latex (isn't finished, looks very WIP)

**Comment by clason** [comment]
The most promising candidate are the internal parsers used by https://github.com/latex-lsp/texlab, which the devs promised to release after the rewrite for version 3.0 is finished. However, TeX is a very different (macro expansion) language than typical programming languages, and it'll probably be a long time before queries match the extensive syntax files included in vim(tex)...

**Comment by reportaman** [comment]
Seems like someone has started adding latex support. @theHamsta The syntax highlight can be better, please check the ticket: https://github.com/lervag/vimtex/issues/1983#issuecomment-794371224

**Comment by vigoux** [comment]
Indeed @theHamsta and @clason started working on this and are making progress.
Any specific highlighting issue you fi'd should be reported here.

**Comment by clason** [comment]
Let me correct that somewhat: @theHamsta has already added a working LaTeX (and Bibtex) parser and highlight queries in <https://github.com/nvim-treesitter/nvim-treesitter/pull/1106>, so this issue may be considered fixed now.

I plan on extending this a bit to be more in line with vimtex's *basic* syntax highlighting. However, vimtex as a dedicated filetype plugin provides specialized support for *a lot* of packages and special cases, and that will _never_ be in the base nvim-treesitter queries. (It wasn't in the default `tex.vim` syntax file bundled with vim, either.) These should be implemented in a separate plugin.

That being said, adding Lua injection for `luatex` is reasonable and should not be difficult. I'd appreciate it if you opened this (and any other specific additions) as a separate issue.

**Comment by theHamsta** [comment]
We have now latex support. So this can be closed. Feel free to add lua injections.
