### ISSUE TITLE
JSX tags using variable instead of tag

### ISSUE THREAD

**Issue by ChristianChiarulli** [nvim-treesitter/nvim-treesitter#921]
![image](https://user-images.githubusercontent.com/29136904/107004357-29bf7f00-675c-11eb-8bd9-84c604952814.png)

I think there are some issues out about this now. But just in case I'm documenting this here. 

The issue is that I believe tags in JSX should match `TSTAG`

**Comment by theHamsta** [comment]
I think tstag was specially created for jax tags. Any reasons why we should leave the tags without highlight?

**Comment by ChristianChiarulli** [comment]
> I think tstag was specially created for jax tags. Any reasons why we should leave the tags without highlight?
> 
> 
> 
> Edit: now i get it: you think variable should not match, right? But variable matches every literal. It's usually overwritten by the other highlights.

Right the picture may be confusing. I believe TSTAG should be what JSX tags use. Right now it seems they use variable.

**Comment by AlanWarren** [comment]
I came to report this myself, but noticed it was already here https://github.com/nvim-treesitter/nvim-treesitter/issues/814  

There's a (closed) PR from pmizio at the bottom of that issue that fixes the issue for JSX in javascript, but I believe it may break typescript / TSX. There's no comment, but I think this must be why it was closed.   

It would be nice if an official solution could be provided that allows JS/JSX overrides in after/queries/  to behave as expected.

**Comment by kyazdani42** [comment]
we are currently working on fixing these js issues, i agree it's not ideal at the moment

**Comment by pmizio** [comment]
@kyazdani42 There is any branch/issue/whatever where we can see any progress on this issue for me it is daily breaker and waiting for this so much :)

**Comment by kyazdani42** [comment]
not yet, i believe this issue might need either internal rework from our end or neovim implementing priority for treesitter queries.

**Comment by theHamsta** [comment]
@pmizio you can just copy the content of the jsx file at the end of your JS file.

**Comment by kyazdani42** [comment]
This workaround would work but 1) would break typescript files 2) does not completely resolves the issue.
But still, i'd go for 2) at the moment.
