### ISSUE TITLE
pressing tab button throws the error

### ISSUE THREAD

**Issue by rustiever** [nvim-treesitter/nvim-treesitter#925]
**Describe the bug**

- Throws me error whenever I press tab button
- sometimes I deleting the lines also throws me the error
- im using Golang

**To Reproduce**

1. Go to any go file
2. go to new line and press tab
3. See error

**Expected behavior**
should not throw any error, and behave normal

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## go parser healthcheck
  - OK: go parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev+nightly
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow
 -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -
D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210116-3199-z376w3/build/config -I/tmp/neovim-20210116-3199-
z376w3/src -I/usr/local/include -I/tmp/neovim-20210116-3199-z376w3/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/
usr/local/opt/gettext/include -I/tmp/neovim-20210116-3199-z376w3/build/src/nvim/auto -I/tmp/neovim-20210116-3199-z376w3/build/include
Compiled by sharan@Sharans-MacBook-Air.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-0fad952/share/nvim"

</code>
</details>

**Additional context**

[my config](https://github.com/rustiever/dots)

**Comment by theHamsta** [comment]
So this error is causes by the `indent` module right?
```
  indent = {
    enable = true
  },
```

Can you show use the error message?

**Comment by rustiever** [comment]
https://user-images.githubusercontent.com/60929919/107136862-ed8f4880-692c-11eb-8198-ec2b4995f13a.mov

**Comment by denstiny** [comment]
![image](https://user-images.githubusercontent.com/57088952/107242538-0c91f580-6a67-11eb-8977-2f3e4ea30e42.png)
 # I also happen this mistake

**Comment by kyazdani42** [comment]
could not reproduce this, does it still happen on latest master of neovim ?

**Comment by rustiever** [comment]
that error now stopped in all other filetypes, but still throws same error in Golang filetype

**Comment by kyazdani42** [comment]
i'm leaving this issue to someone else, i can still not reproduce. Maybe update your parsers (`TSUpdate all`), you neovim version and your nvim-treesitter version ?

**Comment by theHamsta** [comment]
Also a check with the query linter (github.com/nvim-treesitter/playground) may help to identify a potential problem in the Go queries (`queries/go/indent.scm`)

**Comment by kyazdani42** [comment]
@rustiever  is this solved since then ?

**Comment by rustiever** [comment]
Yes Now Work Cool
