### ISSUE TITLE
No `highlights.scm` query found for vue

### ISSUE THREAD

**Issue by WhyNotHugo** [nvim-treesitter/nvim-treesitter#936]
I'm trying to add highlighting for `vue`. I've followed the [instructions on the README](https://github.com/nvim-treesitter/nvim-treesitter#advanced-setup), and have reached a point where `:checkhealth` suggests I open an issue.

1. I cloned `https://github.com/ikatyang/tree-sitter-vue.git` into `/home/hugo/workspace/Forks/tree-sitter-vue`.
2. I ran `tree-sitter generate && tree-sitter test`
3. I added this to my config:

```lua
local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
parser_config.vue = {
  install_info = {
    url = "/home/hugo/workspace/Forks/tree-sitter-vue",
    files = {"src/parser.c", "src/scanner.cc"}
  },
  filetype = "vue"
}
```

4. I ran `:TSInstall`.

Syntax highlighting for files where `filetype=vue` doesn't work. `:checkhealth` shows this:

```
## vue parser healthcheck
  - OK: vue parser found.
  - WARNING: No `highlights.scm` query found for vue
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `locals.scm` query found for vue
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `folds.scm` query found for vue
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
  - WARNING: No `indents.scm` query found for vue
    - ADVICE:
      - Open an issue at https://github.com/nvim-treesitter/nvim-treesitter
```

Am I missing something?

**Comment by elianiva** [comment]
Because no one has made the queries for Vue, shouldn't be that hard to make though. ( You might want to look at HTML queries or Svelte queries)

**Comment by WhyNotHugo** [comment]
Oh, I see. I though these were programatically generated on install.

Do you have any hints/pointers on how to approach this? I've no idea what any of these values are of from where to extract them.

**Comment by theHamsta** [comment]
@WhyNotHugo I would recommend to install https://github.com/nvim-treesitter/playground . Based on the syntax nodes you can write queries. E.g. `(foo) @type` in a file `queries/vue/highlights.scm` would highlight all nodes `foo` with the `Type` highlight. You can see the highlight captures that we use in `CONTRIBUTING.md`. You can also declare inlined languages with `injections.scm`. Just have a look on how the queries are structured for the other languages: https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries

**Comment by WhyNotHugo** [comment]
Thanks! I'd looked at the HTML example as a reference of the format, but wasn't sure about how to get all the right types.

I've installed the playground and that seems to be enough to move forward, thanks!

**Comment by WhyNotHugo** [comment]
Closing, thanks for the pointers!
