### ISSUE TITLE
C queries should be excluded from the neovim repo

### ISSUE THREAD

**Issue by bool3max** [nvim-treesitter/nvim-treesitter#948]
* `nvim --version`: `NVIM v0.5.0-dev+1085-g52397aaa0` 
* latest nvim-treesitter
* ran `:TSUpdate`

Editing any C file while treesitter syntax highlighting is enabled results in no syntax highlighting being present and 

```
treesitter/highlighter: Error executing lua: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:104: query: error at position 1716
```

being printed at the end of the first line of the buffer.

**Comment by theHamsta** [comment]
Could you try to investigate which part of the queries is wrong using the query linter: https://github.com/nvim-treesitter/playground ?

**Comment by stsewd** [comment]
@bool3max what OS are you using, it works fine for me in fedora.

**Comment by stsewd** [comment]
Sorry, I didn't have my parsers updated, looks like this breaks in my system as well.

**Comment by stsewd** [comment]
So, yeah, looks like it was the parser update https://github.com/nvim-treesitter/nvim-treesitter/commit/96314670c7abe5bccc39710245210e9b95a96c77, previous version works just fine. Checking what changed.

**Comment by stsewd** [comment]
So, I think neovim isn't compatible with tree-sitter-cli 0.18 https://github.com/tree-sitter/tree-sitter-c/commit/8d4631b673f8a9d968d1d93393c0a965194abac0

**Comment by theHamsta** [comment]
I'm using the newest tree-sitter. Maybe it's because of that that I don't observe any issues. But actually there should be a version check.  Also a few nodes changed in the C parser.

**Comment by stsewd** [comment]
Looks like neovim is already using 0.18

https://github.com/neovim/neovim/blob/52397aaa0d1e2d4ce1320c73761cf316fc608ffb/third-party/CMakeLists.txt#L202

**Comment by stsewd** [comment]
We can merge https://github.com/nvim-treesitter/nvim-treesitter/pull/949 till we figure out what's happening.

**Comment by stsewd** [comment]
I just updates to rst parser as a test, and it also fails with neovim. Looks like the latest supported version is `0.16.9`, with `0.17.x` and above neovim fails.

**Comment by theHamsta** [comment]
c_sharp updated the runtime also. Maybe just revert the complete commit?

**Comment by stsewd** [comment]
Did a quick test with c_sharp

```cs
using System;

namespace HelloWorld
{
  class Program
  {
    static void Main(string[] args)
    {
      Console.WriteLine("Hello World!");    
    }
  }
}
```

It doesn't have the problem, they are using 0.17.1 https://github.com/tree-sitter/tree-sitter-c-sharp/blob/9e33bc572055057bb1ceee1b28d6245d80e78ec3/package.json#L16 I haven't tested my parser with that version (I tested with 0.17.3)

I'm checking if other parsers were updated.

**Comment by stsewd** [comment]
Teal also updated the cli, but they didn't regenerate their files https://github.com/euclidianAce/tree-sitter-teal/commit/766162e3dab71843de7f50819ecc97bacd60d289 so all good there for now.

**Comment by theHamsta** [comment]
Can you check whether out commenting these three queries help? Test fail with them on my machine and from the updated grammar it should be 

```
;(declaration type: [(identifier) (type_identifier)] @type)
;(cast_expression type: [(identifier) (type_identifier)] @type)
;(sizeof_expression value: (parenthesized_expression (identifier) @type))
```

```
(declaration (type_qualifier) @type)
(cast_expression type: (type_descriptor) @type)
```

**Comment by stsewd** [comment]
hmm, yeah, that looks like it solved the problem for me.

**Comment by stsewd** [comment]
we'll need to figure out what's going on with my rst parser before updating from 0.16.9 :/

**Comment by theHamsta** [comment]
There aren't any problems when Neovim has the newest tree-sitter runtime.

**Comment by bool3max** [comment]
5fab87f8a3d2c4b5d9e04c08ad1b6d575145056b seems to have fixed the problem for me.

**Comment by theHamsta** [comment]
@bool3max would this change also work: https://github.com/nvim-treesitter/nvim-treesitter/commit/e1e62f0f840e9cc589393633542802d5c333bea6

**Comment by bool3max** [comment]
I'm a little lost as to how to downgrade nvim-treesitter and apply that particular patch.

**Comment by theHamsta** [comment]
You can just delete c from the log file and apply the changes in those two lines and run `: TSUpdate`.

**Comment by stsewd** [comment]
Looks like for some reason neovim doesn't recognize some fields, and it also doesn't allow comments between lines of a query for grammars generated with ts-cli>=0.17.x. Some examples of queries I found in my parser.

```scm
(directive
  name: (type) @function)
```

Here the `name` field isn't recognized, but it's defined in the grammar (with the C grammar, the `type` field is also defined).

```scm
((directive (type) @function.builtin)
 (#match?
  @function.builtin
  ; https://docutils.sourceforge.io/docs/ref/rst/directives.html
  "^attention|caution|danger$"))
```

For example this doesn't work, the comment must be outside the query.

All those examples work with the web playground, so I guess something changed with the c integration and neovim needs to update something.

**Comment by theHamsta** [comment]
```
((directive @function.builtin)
 (#match?
  @function.builtin
  ; https://docutils.sourceforge.io/docs/ref/rst/directives.html
  "^attention|caution|danger$"))
((identifier) @constant
 (#match? @constant "^[A-Z][A-Z0-9_]+$"))
```

You're sure about the comment? The linter reports an error because the query parser cannot handle the syntax.
![image](https://user-images.githubusercontent.com/7189118/107860575-31f47a00-6e40-11eb-9931-b8e7462678c6.png)

**Comment by stsewd** [comment]
> You're sure about the comment? The linter reports an error because the query parser cannot handle the syntax.

What syntax? The field name? If I remove the field name, the playground still reports an error.

```
 (#match?
  @foo
  ; bar
  "foo")
```

That's a minimal example.

**Comment by stsewd** [comment]
Interesting, I start to see a pattern, looks like fields with the name `value` and `name` are marked as invalid in all queries, found a couple of parsers with that problem.

The comment error is annoying, but can be just moved, but still something that is working and supported by ts-cli/web.

**Comment by stsewd** [comment]
And for some reason those errors aren't reported or "error" when the grammars are generated with `ts-cli<=0.16.x`

**Comment by theHamsta** [comment]
> The comment error is annoying, but can be just moved, but still something that is working and supported by ts-cli/web.

I don't think there is a problem with the comments, only the linter has a problem with parsing the comments correctly (tree-sitter-query to be exact).

> And for some reason those errors aren't reported or "error" when the grammars are generated with ts-cli<=0.16.x.

Before 0.17, the were much fewer checks. So you could write more impossible query and it would be accepted.

> Interesting, I start to see a pattern, looks like fields with the name value and name are marked as invalid in all queries, found a couple of parsers with that problem.

But I suppose this is just a Lua binding problem. I've been seeing these lints since a long time and they never caused problems.

**Comment by stsewd** [comment]
> I don't think there is a problem with the comments, only the linter has a problem with parsing the comments correctly (tree-sitter-query to be exact).

Oh, yeah, you are right, I have fixed that in https://github.com/nvim-treesitter/tree-sitter-query/pull/8

**Comment by theHamsta** [comment]
I think this issue is not resolved until we replace those two problematic queries in nvim-treesitter and remove the query files from Neovim core.

**Comment by stsewd** [comment]
yeah, that wasn't mean to close this issue

**Comment by lewis6991** [comment]
Is this still an issue?

**Comment by clason** [comment]
Queries are currently fully synced, so this should not be a problem. Otherwise please open a new issue with more details.
