### ISSUE TITLE
Indent embedded javascript and css in HTML files.

### ISSUE THREAD

**Issue by Kazimazi** [nvim-treesitter/nvim-treesitter#951]
I would like to have embedded javascript and css in HTML indented.
Currently if I `gg=G`:
```html
<head>
  <title>asdf</title>
  <script type="text/javascript">
  for (var i = 0; i < 10; i++) {
  console.log(i);
  }
  </script>
  <style media = "all">
  body {
  background-color: orange;
  }
  h1 {
  color: yellow;
  margin-left: 30px;
  }
  </style>
</head>
```

**Comment by stsewd** [comment]
Right now all features like incremental selection, indentation, goto, etc work at the buffer level, so they would need to be updated to work at the parser level.

**Comment by bowmanmike** [comment]
Had this same question. Is there some documentation somewhere about how to go about fixing this? I'd be happy to give it a shot, but I don't know where to begin.

**Comment by RaafatTurki** [comment]
Ah yes, the bane of my `<Tab>` key

**Comment by LeviOP** [comment]
I'm not able to replicate this behavior. Indents inside of injections for html appear to be fully functional now.
