### ISSUE TITLE
Treesitter prevents custom syntax highlighting from loading

### ISSUE THREAD

**Issue by medwatt** [nvim-treesitter/nvim-treesitter#959]
I created a custom conceal syntax such as:
`syntax match Normal '\v<[[:alpha:]_]+0>'ms=e conceal cchar=₀`
and stored them in `~/.config/nvim/after/syntax/markdown.vim`. By placing the file inside `after/syntax`, the file should come into effect whenever I open a markdown file. For some reason, this didn't work. However, after I disabled treesitter, it worked. My treesitter config is very basic:

```vim
:lua << EOF
  require'nvim-treesitter.configs'.setup {
    highlight = {
      enable = true,
      disable = { "ocaml", "typescript", "tsx", "ocaml_interface" },
    },
  }
EOF
```

How can I have my custom conceal file load automatically as it should while still using treesitter?

**Comment by stsewd** [comment]
Hi, tree-sitter disables everything related to syntax (`setlocal syntax=`), you can't mix vim's syntax and tree-sitter currently.

**Comment by kyazdani42** [comment]
i think this is upstream related ? @vigoux

**Comment by theHamsta** [comment]
@stsewd nvim-treesitter does not deactivate `syntax` anymore (we now have regex highlighting with tree-sitter on top). At least you can have tree-sitter and normal highlights at the same time. I don't know why the after file is either not loaded or the conceal is not applied.

**Comment by stsewd** [comment]
@theHamsta this is done from neovim, yes https://github.com/neovim/neovim/blob/1caf58578c6e4b30c18fa56804dd905b5472b460/runtime/lua/vim/treesitter/highlighter.lua#L138

**Comment by theHamsta** [comment]
But you can activate it agaon  to run tree-sitter and syntax. Had this a while with julia. Where a plugin loaded syntax in additikn to the tree-sitter higlights

**Comment by theHamsta** [comment]
@medwatt so the utlimate question is whether `set syntax=on` bring back your custom syntax?

**Comment by medwatt** [comment]
> @medwatt so the utlimate question is whether `set syntax=on` bring back your custom syntax?

Yes, after the file is loaded in the buffer, `set syntax=on` works.

**Comment by sperezconesa** [comment]
Hello,
I am running into the same problem and `set syntax=on` fixes it. Is there a way to do this automatically? I have tried putting it in `~/.config/nvim/init.vim` and I still need to run the command after the file is opened.

**Comment by theHamsta** [comment]
@sperezconesa you could create a PR. Syntax=off is called in highlight.lua you could add an option to the config of that module

**Comment by sperezconesa** [comment]
I would love to but I don't know any lua or how to do such a thing. I wish I could. I can just leave this as feature request if some one wants to do so.

**Comment by chentau** [comment]
Would turning syntax on have a noticeable impact on neovim speed? Since now we are doing both regex highlighting and extmark highlighting from treesitter

**Comment by theHamsta** [comment]
> Would turning syntax on have a noticeable impact on neovim speed? Since now we are doing both regex highlighting and extmark highlighting from treesitter

:man_shrugging: if people want it they will get it.

**Comment by chentau** [comment]
Makes sense - I see the option will be off by default anyways.

**Comment by nsotelo** [comment]
For anyone who comes across this issue, you can resolve this by adding the following to your vim config.
```vimscript
:au BufNewFile,BufRead * set syntax=on
```

I'm using the to show concealed characters with vim-cute-python and it works, but I have no idea if other plugins will cause issues for treesitter.

**Comment by theHamsta** [comment]
@nsotelo this will soon no longer work as we want prevent plugins to accidentally activate syntax. See the option `additional_vim_regex_highlighting` (`:h nvim-treesitter-highlight-mod`)

**Comment by nsotelo** [comment]
@theHamsta Thanks for the info!
