### ISSUE TITLE
Installing nvim-treesitter on Fedora fails compiling

### ISSUE THREAD

**Issue by gbaranski** [nvim-treesitter/nvim-treesitter#961]
Same error as here: https://www.reddit.com/r/neovim/comments/jbsfx2/cant_install_treesitter_error_during_compilation/
Solved by
```bash
sudo dnf install gcc-c++
```
I'll fork the repo and add that to documentation.

**Comment by theHamsta** [comment]
We  already in the README that you need stdc++.
