### ISSUE TITLE
Folding with syntax highlight, i.e don't fold the first line.

### ISSUE THREAD

**Issue by lkhphuc** [nvim-treesitter/nvim-treesitter#967]
### Problem

I used to set `foldmethod=indent`, so in most code (especially python) the fold will start belows the function definition, if-else, ... That way the first line, which is the summary of what inside the fold is syntax highlighted, like this.
![Screenshot 2021-02-22 at 11 39 32](https://user-images.githubusercontent.com/12573521/108703525-a2fff580-7502-11eb-8d9f-8832adf39598.png)

But using treesitter's `foldmethod=expr`, it will fold everything, thus no syntax highlight for the first summary line, like this.
![Screenshot 2021-02-22 at 11 40 20](https://user-images.githubusercontent.com/12573521/108703602-bf039700-7502-11eb-961b-0360ac050b4c.png)

According to this [answer](https://stackoverflow.com/questions/1813060/syntax-highlighting-in-a-vim-fold-header/1813677#1813677), foldtext will never be syntax highlight, so it's not possible to edit `foldtext` manually. 

### Idea solution
An option for current `foldexpr` to not include the first line.
This will make each fold takes up two line, one for the first-highlighted line, second line is for the fold text, but I rather prefer that over just one grey line of foldtext.

**Comment by theHamsta** [comment]
@stsewd implemented this: https://github.com/nvim-treesitter/nvim-treesitter/pull/390 but we where not sure whether this should be an option for Neovim core.

**Comment by lkhphuc** [comment]
Thanks. Closing this now as I have found other trackers for this, as either Neovim fix syntax highlight for the foldtext https://github.com/neovim/neovim/issues/12649 , or treesitter add options to modify the fold without first line, as in #390 .
