### ISSUE TITLE
used_by config stopped working

### ISSUE THREAD

**Issue by carlitux** [nvim-treesitter/nvim-treesitter#981]
In this commit https://github.com/nvim-treesitter/nvim-treesitter/commit/9d57216c0d94c9823c0d971caeaffb3b261e527e

Was removed `used_by` and now this config is not working any more https://github.com/nvim-treesitter/nvim-treesitter#update-parsers-used_by

**Comment by carlitux** [comment]
I was able to emulate with more lines

```lua
local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
local javascriptflow = parser_config.typescript
javascriptflow.used_by = {"javascriptflow"}
parser_config.typescript = nil
parser_config.typescript = javascriptflow
```

**Comment by theHamsta** [comment]
@kyazdani42

**Comment by kyazdani42** [comment]
this is what I thought, Im adding this back asap
