### ISSUE TITLE
Comments can cause Fennel nodes to end early

### ISSUE THREAD

**Issue by Olical** [nvim-treesitter/nvim-treesitter#997]
**Describe the bug**

Hi there, I'm beginning to experiment with tree-sitter over in Conjure for Julia support https://github.com/Olical/conjure/issues/184

I noticed an issue with Fennel where forms / nodes are cut off when there's comments mid way through the node. This only seems to happen in certain scenarios so I presume it's related to the grammer(?).

**To Reproduce**

```fennel
;; This is okay
(+ 1
   ;
   )

;; This is not
(+ 1
   ;
   2)
```

It ends up producing `(+ 1` when I call `get_node_text`. The range also changes so it appears to be in parsing, not re-writing back to a string.

```
;; Okay
{:content "(+ 1
   ;
   )"
 :range {:end [123 3] :start [121 0]}}

;; Not okay
{:content "(+ 1" :range {:end [120 3] :start [120 0]}}
```

**Expected behavior**

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## Parser/Features H L F I
  - fennel         ✓ ✓ . . 
 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         *) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

</code>
</details>

**Output of `nvim --version`**

<details>
<code>

NVIM v0.5.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: 
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/anb133cb1hz7c5mfavly92wb437ds0qf-neovim-nightly-master/share/nvim"

Run :checkhealth for more info

</code>
</details>

**Additional context**

I'm happy to try and fix this, I just though I'd report it and get some more experienced eyes on it first. Thanks!

**Comment by stsewd** [comment]
Yes, this is a bug from the grammar, you should report this to https://github.com/travonted/tree-sitter-fennel

**Comment by stsewd** [comment]
I think fennel is a lisp-like language, so you can take some inspiration in how we implemented comments in the query grammar https://github.com/nvim-treesitter/tree-sitter-query/blob/master/grammar.js
