### ISSUE TITLE
[vue] query.lua:104: query: invalid node type at position 760

### ISSUE THREAD

**Issue by cloggier** [nvim-treesitter/nvim-treesitter#999]
**Describe the bug**
With latest Neovim (`v0.5.0-dev+df4440024`) and tree-sitter (`tree-sitter 0.19.1`) I am getting this error on multicomponent Vue files which contain `style` block.

```
treesitter/highlighter: Error executing lua: ...f44400_1/share/nvim/runtime/lua/vim/treesitter/query.lua:104: query: invalid node type at position 760
```

**To Reproduce**

1. Create `test.vue` file:
```
<template></template>
<script></script>
<style></style>
```
2. Observe error showing on last line.

**Expected behavior**

No error shown, `css` parser being injected for `css` (default) type `style` block (`<style lang="css">…`).
I have installed `html`, `css` and `javascript` (amongst other) parsers with `:TSInstallFromGrammar` after cleaning them all up first, upgrading tree-sitter and upgrading Neovim.

Prior to 0.19.0 version of treesitter there was no such error shown and highlighting worked. It even worked for `scss` lang of `style` block, with some errors shown on `scss` specific context.

**Output of `:checkhealth nvim_treesitter`**

<details>
<code>
health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## Parser/Features H L F I
  - css            x . ✓ ✓
  - javascript     ✓ x ✓ ✓
  - regex          ✓ . . .
  - bash           ✓ ✓ ✓ .
  - json           ✓ ✓ ✓ ✓
  - yaml           ✓ ✓ ✓ ✓
  - jsdoc          ✓ . . .
  - lua            ✓ ✓ ✓ ✓
  - python         ✓ ✓ ✓ ✓
  - html           ✓ ✓ ✓ ✓
  - vue            ✓ . ✓ .
 Legend: H[ighlight], L[ocals], F[olds], I[ndents]
         *) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}
</code>
</details>

**Output of `nvim --version`**

<details>
<code>
NVIM v0.5.0-dev+df4440024
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough
 -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-2021030
4-25060-1lv2qv6/build/config -I/tmp/neovim-20210304-25060-1lv2qv6/src -I/usr/local/include -I/usr/local/opt/luv/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gette
xt/include -I/tmp/neovim-20210304-25060-1lv2qv6/build/src/nvim/auto -I/tmp/neovim-20210304-25060-1lv2qv6/build/include
Compiled by <me>

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-df44400_1/share/nvim"

Run :checkhealth for more info
</code>
</details>

**Comment by theHamsta** [comment]
Can you debug the issue by using the query linter (https://github.com/nvim-treesitter/playground) on the vue highlights (`queries/vue/highlights.scm`)? It should show you which query is wrong.

It's possible that the new tree-sitter version can detect more errors in the queries or that the grammar has changed while the C files are still old.

**Comment by cloggier** [comment]
I am not quite sure how to debug tree-sitter, but this is what playground shows for minimal vue file from above:
```
template_element [0, 0] - [0, 21]
  start_tag [0, 0] - [0, 10]
    tag_name [0, 1] - [0, 9]
  end_tag [0, 10] - [0, 21]
    tag_name [0, 12] - [0, 20]
script_element [1, 0] - [1, 17]
  start_tag [1, 0] - [1, 8]
    tag_name [1, 1] - [1, 7]
  raw_text [1, 8] - [1, 8]
  end_tag [1, 8] - [1, 17]
    tag_name [1, 10] - [1, 16]
style_element [2, 0] - [2, 15]
  start_tag [2, 0] - [2, 7]
    tag_name [2, 1] - [2, 6]
  raw_text [2, 7] - [2, 7]
  end_tag [2, 7] - [2, 15]
    ERROR [2, 7] - [2, 8]
    tag_name [2, 9] - [2, 14]
```

**Comment by theHamsta** [comment]
The query linter will show problems when loading the respective queries. Here I voluntarily introduced an invalid node type

![image](https://user-images.githubusercontent.com/7189118/109954577-c9cbe200-7ce1-11eb-9d7c-294253e9a0c7.png)

I can't see any errors with me using 0.19.0 and a vue parser installed from source.

**Comment by theHamsta** [comment]
I'm getting the same error

![image](https://user-images.githubusercontent.com/7189118/109954865-20392080-7ce2-11eb-9b94-933e2fcb5560.png)

**Comment by theHamsta** [comment]
I guess this could be related to caching the queries. It's probably due to the fact that the filetype of the buffer has changed.

It does not happen if I'm setting the filetype to vue when it was an empty draft buffer before and not JS. 

@oberblastmeister The cache should probably include the filetype
https://github.com/nvim-treesitter/nvim-treesitter/pull/879

**Comment by cloggier** [comment]
> @cloggier could you try to deactivate the caching? E.g. always call `update_cached_matches`
> 
> ```lua
>     if not cached_local or api.nvim_buf_get_changedtick(bufnr) > cached_local.tick then
>       update_cached_matches(bufnr,api.nvim_buf_get_changedtick(bufnr), query_group)
>     end
> ```

Not sure if I did that correctly:

```lua
function M.get_matches(bufnr, query_group)
  bufnr = bufnr or api.nvim_get_current_buf()
  local cached_local = query_cache.get(query_group, bufnr)     ■ Unused local `cached_local`.
  -- if not cached_local or api.nvim_buf_get_changedtick(bufnr) > cached_local.tick then
  update_cached_matches(bufnr, api.nvim_buf_get_changedtick(bufnr), query_group)
  -- end

  return query_cache.get(query_group, bufnr).cache
end
``` 
Still shows that error.

**Comment by theHamsta** [comment]
Right, if it were the wrong language the error would occur way earlier. For me, it's now a Javascript problem.

I changed these lines to include the language https://github.com/neovim/neovim/blob/6995fad260e3e7c49e4f9dc4b63de03989411c7b/src/nvim/lua/treesitter.c#L1131-L1132
```
    return luaL_error(L, "query: %s at position %d for language %s",
                      query_err_string(error_type), (int)error_offset, lang_name);
```
you may even add `src + error_offset` to find out the actual problematic part of the query file.

**Comment by cloggier** [comment]
@theHamsta After upgrading to latest neovim (`v0.5.0-dev+0ab88c2`) and nvim-treesitter (#1000) I am no longer seeing those errors.

I would like to thank you very much for all your effort trying to solve this issue and continues work on neovim. I am going to close this issue now.
